### ISSUE TITLE
extra/oxidized-report-git-commits doesn't appear to be working anymore

### ISSUE THREAD

**Issue by gbeekmans** [ytti/oxidized#1001]
A recent (ish) update to this script moved away from a temporary staging directory to using the bare repository directly but I can't seem to get it to work. "git diff" doesn't want  to operate on a bare repository. I've tried versions 2.7.4 and 2.14.1 (latest version as of this writing).

With both versions the error message I get is:

fatal: ambiguous argument '8e8e23844427b4903d539fb5e1ed19e467060ff8~1..8e8e23844427b4903d539fb5e1ed19e467060ff8': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

**Comment by asenci** [comment]
Hi @gbeekmans, was able to reproduce the issue running the script against a new repo.

When OX_REPO_COMMITREF points to the initial commit, git obviously can't find the previous commit (OX_REPO_COMMITREF~1).

Working on a patch using "git show" instead of "git diff" now.

**Comment by gbeekmans** [comment]
This change works for me as well. Thanks for the update.
