### ISSUE TITLE
next_adds_job configuration option when using one node seems to cause a loop

### ISSUE THREAD

**Issue by gbeekmans** [ytti/oxidized#1005]
During testing of making configuration file changes, I was running Oxidized with one entry in the router.db file and next_adds_job was set to true.

This combination of one node and next_adds_job seems to cause a loop. When Oxidized starts, it checks the single node and all is well. When you select "update" from the actions column in the web interface, this happens (only visible when debug is also set).

Just before clicking the link, it appears to be idling with the following message scrolling every 1 second:

D, [2017-08-30T16:30:50.925693 #29501] DEBUG -- : lib/oxidized/worker.rb: Jobs 0, Want: 1
D, [2017-08-30T16:30:51.926239 #29501] DEBUG -- : lib/oxidized/worker.rb: Jobs 0, Want: 1
D, [2017-08-30T16:30:52.926676 #29501] DEBUG -- : lib/oxidized/worker.rb: Jobs 0, Want: 1

Now when I click the link:

D, [2017-08-30T16:31:50.107138 #29528] DEBUG -- : lib/oxidized/worker.rb: Jobs 1, Want: 2
D, [2017-08-30T16:31:50.107149 #29528] DEBUG -- : lib/oxidized/worker.rb: Jobs 1, Want: 2
D, [2017-08-30T16:31:50.107159 #29528] DEBUG -- : lib/oxidized/worker.rb: Jobs 1, Want: 2

It goes on forever.  Thousands of lines in the span of less than 1 single second. It's obviously stuck in some kind of failed logic loop. Adding a second node resolves the issue, or setting next_adds_job to false.

**Comment by jsynack** [comment]
I have seen this as well.

My source was SQL , and the query (purposely) was altered to limit to a single node for development purposes.

After startup and the first fetch of the device, a node/next would cause mayhem.

 I did a local change (one-liner) to fix it temporarily - but I am thinking there is a better way to solve it (still learning where things are done in oxidized).

**Comment by nova-2nd** [comment]
Just ran into this!!!!!!
