### ISSUE TITLE
Help with hooks to local gitlab

### ISSUE THREAD

**Issue by seekerOK** [ytti/oxidized#1008]
I installed Gitlab and create a user and set up  a project which is where the hook is going to push to, right ?
I add my hooks 

```
output:
  debug: true
  default: git
  git:
    user: centos_user
    email: oxidized@example.com
    repo: "/home/administrator/.config/oxidized/repo/git-repos/default.git"
hooks:
  push_to_remote:
    type: githubrepo
    events: [node_success]
    remote_repo:
      REPO1: git@serverHostName:oxidized/REPO1.git
      REPO2: git@serverHostName:oxidized/REPO2.git
    username: gitlab_create_user
    password: it_password
```
Iam getting a  lot of authentication errors

log

```
Aug 31 14:58:17 serverHostName oxidized[32889]: GithubRepo: Pushing local repository(/home/administrator/.config/oxidized/repo/git-repos/REPO1.git/)...
Aug 31 14:58:17 serverHostName oxidized[32889]: GithubRepo: to remote: gitlab_create_user@serverHostName:/oxidized/REPO1.git
Aug 31 14:58:17 serverHostName sshd[32904]: Invalid user gitlab_create_user from 127.0.0.1
Aug 31 14:58:17 serverHostName sshd[32904]: input_userauth_request: invalid user gitlab_create_user [preauth]
Aug 31 14:58:17 serverHostName oxidized[32889]: Hook push_to_remote (#<GithubRepo:0x000000008cdea8>) failed (#<Rugged::SshError: username does not match previous request>) for event :node_success
Aug 31 14:58:17 serverHostName sshd[32904]: Connection closed by 127.0.0.1 [preauth]
```
I also try to push directly from commandline but i cant login

**Comment by laf** [comment]
> I also try to push directly from commandline but i cant login

That and the error do say you have an invalid user, this doesn't seem to be an oxidized issue.

**Comment by seekerOK** [comment]
i just though you guys have seen this before, apparently it have something to do with ssh and the fact that oxidized and gitlab run in the same server but give up.

**Comment by laf** [comment]
I've never ran them both on the same server before but it's just an ssh connection so I wouldn't have thought it mattered where they were.

**Comment by seekerOK** [comment]
thats what i though but no matter what i do i cant authenticate to gitlab from the cli, but everything works fine through the webgui

**Comment by laf** [comment]
You using ssh keys?

**Comment by seekerOK** [comment]
yes but the error didnt change at all

**Comment by laf** [comment]
If it's not authing with keys when you do it via the cli then something is definitely up with the setup. Have you tested with another repo of just doing a basic git push origin master using the user oxidized is running as just to see?

**Comment by seekerOK** [comment]
I try from the cli directly to push something and it ask me for password but i cant pass that step

**Comment by seekerOK** [comment]
> using the user oxidized is running 

no, I havent tried that.

**Comment by laf** [comment]
If you are using keys then you must have the key set for the user doing the push so for Oxidized, it needs to be the user you start it with.
