### ISSUE TITLE
Dell Powerconnect 3448/3548 Not Removing Temperature

### ISSUE THREAD

**Issue by asteen-nexcess** [ytti/oxidized#1009]
Hi all,

Running into an issue where our Dell Powerconnect 3448 and 3548 switches are not removing the temperature block from the configs resulting in new changes every time it runs. Below is the output of one of the switches:

! 
SW version    2.0.0.34 ( date  25-Jul-2010 time  14:24:24 )
! Boot version    1.0.1.01 ( date  15-Jun-2006 time  11:42:56 )
! System Description:                       Ethernet Switch
! System Contact:
! System Name:                              <snip>
! System Location:
! System MAC Address:                        <snip>
! System Object ID:                          <snip>
! Type:                                     PowerConnect 3448
! 
! Main Power Supply Status:                 OK
! Fan 1 Status:                             OK
! Fan 2 Status:                             OK
! 
! 
! Unit            Temperature (Celsius)            Status
! ------------------------ ------------------------ ------------------------
! 1                        43                       OK

Any ideas?

Thanks!

**Comment by laf** [comment]
It looks for (U|u)nits in the output of `show version` (can you pastebin that). That then determines if it's a stackable device and excludes the Temp info.

**Comment by asteen-nexcess** [comment]
Hi Laf,

[https://pastebin.com/sBZMgVz6](url)

This output looks the same on every Dell 34xx/35xx/54xx switch we have (sans version numbers of course). I don't actually see stack units in `show version` until the Dell 55xx series. Linked a copy of a 5548 `show version` below.

[https://pastebin.com/9ZSn4JUT](url)

Thanks!

**Comment by laf** [comment]
Ok I'm not sure what to suggest here other than dropping the check for stacking modules.

This is a quick change, you can test it if you like: https://gist.github.com/laf/f7f7b4ceb0bb2008c41e5a01fe568a01

**Comment by asteen-nexcess** [comment]
Hi Laf,

Awesome, that worked perfect. I ended up making a new model for this though since it was making the Dell 55xx and Dell N15xx series configs a bit weird.

Thanks!
