### ISSUE TITLE
WebUI previous versions local git timeout

### ISSUE THREAD

**Issue by Wax-Trax** [ytti/oxidized#1014]
I set up Oxidized to use a local git repository for configuration storage and versioning. I've been running Oxidized for a couple of months now, and I used to be able to pull up previous versions with the web interface, but now when I try, nginx times out. Pulling up the current version is practically instant.

When I log into the box and do a "git log" it shows that files are being updated.

My local git repository is about 1.4 GB in size, which may be contributing to this. Is there some kind of timeout value for nginx that I can modify, or some other way to optimize Oxidized to retrieve this information from the local git faster?

Thank you

**Comment by danilopopeye** [comment]
@Wax-Trax could you try a [git gc --auto](https://git-scm.com/docs/git-gc) and see if the size of the repository changes? This should make your repository more optimized and faster.

**Comment by Wax-Trax** [comment]
Thank you so much!! That seems to have done the trick. I have 130,000 objects in my local repository. I have about 20 Fortigate firewalls that backup every single hourly run because they have little bits and pieces that change each time. If it becomes a problem in the future, I'll probably end up removing them from the backup.

On a related note, I know I can edit the *.rb files to try to skip the things that are making it back up each time, but is there a way to specify that individual devices keep X number of revisions, or individual devices keep only the latest revision, while still using Git?

Thanks for your time.

**Comment by laf** [comment]
> On a related note, I know I can edit the *.rb files to try to skip the things that are making it back up each time, but is there a way to specify that individual devices keep X number of revisions, or individual devices keep only the latest revision, while still using Git?

No that's not supported.

**Comment by Wax-Trax** [comment]
Thanks again everyone, I really appreciate your time and support.
