### ISSUE TITLE
Is there a forum/mailing list/community for oxidized?

### ISSUE THREAD

**Issue by howardjones** [ytti/oxidized#1019]
I'm looking at moving from RANCID to Oxidized, and keep coming up with questions that are not really issues. I can't see any place to ask these questions. Is there one? (I guess technically, some of them might *become* docs issues).

Like: 
1) how do I specify ssh parameters (like sshv1 (ancient console server), or specifc crypto)
2) how do I faultfind failed connections? Device fails to connect in ox, works from rancid and console. "verbose" mode in oxs just says it can't connect and gives a ruby stackdump
3) can I use ssh keys? per device?
4) why does oxidized still look in ~/.configs/oxidized/config FIRST and not $OXIDIZED_HOME/config?
5) Is there a web UI for managing nodes (add/remove/update) already?
6) I want to use oxidized-web behind an apache proxy (which already has ssl, ldap auth etc set up) - can I configure the base url for oxidized so that it doesn't redirect to `/nodes` but instead `/ox/nodes` as soon as I connect?

So far, I like the more flexible scheduling, but seem to get more debugging information out of RANCID...

**Comment by laf** [comment]
> I'm looking at moving from RANCID to Oxidized, and keep coming up with questions that are not really issues. I can't see any place to ask these questions. Is there one?

IRC channel #oxidized on freenode or [gitter](https://gitter.im/oxidized/Lobby?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)


> how do I specify ssh parameters (like sshv1 (ancient console server), or specifc crypto)

https://github.com/ytti/oxidized/issues/224

> how do I faultfind failed connections? Device fails to connect in ox, works from rancid and console. "verbose" mode in oxs just says it can't connect and gives a ruby stackdump

You can turn on debugging: https://github.com/ytti/oxidized#debugging

> can I use ssh keys? per device?

Not sure. This is the library it uses: http://net-ssh.github.io/net-ssh/

> Is there a web UI for managing nodes (add/remove/update) already?

No. This is usually dealt with via whichever source you use or another system managing that source.

> I want to use oxidized-web behind an apache proxy (which already has ssl, ldap auth etc set up) - can I configure the base url for oxidized so that it doesn't redirect to /nodes but instead /ox/nodes as soon as I connect?

Yes. We already do that.

In oxidized config: `rest: 0.0.0.0:8443/ox/` then you can proxy that /ox/ to it.

**Comment by howardjones** [comment]
I thought I'd tried debugging and got no more info. I will recheck.

Will check out gitter!

Sorry, I missed the relative URL part in the giant readme.

**Comment by danilopopeye** [comment]
> how do I faultfind failed connections? Device fails to connect in ox, works from rancid and console. "verbose" mode in oxs just says it can't connect and gives a ruby stackdump

can you provide a pastebin with the stacktrace?

**Comment by howardjones** [comment]
Here's the stacktrace:

```
oxs -d -v console-svr show version
unable to connect
/usr/local/share/gems/gems/oxidized-script-0.4.0/lib/oxidized/script/script.rb:113:in `connect': unable to connect (Oxidized::Script::NoConnection)
	from /usr/local/share/gems/gems/oxidized-script-0.4.0/lib/oxidized/script/script.rb:92:in `initialize'
	from /usr/local/share/gems/gems/oxidized-script-0.4.0/lib/oxidized/script/cli.rb:120:in `new'
	from /usr/local/share/gems/gems/oxidized-script-0.4.0/lib/oxidized/script/cli.rb:120:in `connect'
	from /usr/local/share/gems/gems/oxidized-script-0.4.0/lib/oxidized/script/cli.rb:35:in `run'
	from /usr/local/share/gems/gems/oxidized-script-0.4.0/bin/oxs:5:in `<top (required)>'
	from /usr/local/bin/oxs:23:in `load'
	from /usr/local/bin/oxs:23:in `<main>'
```

As far as I can see, it's something that useful to the developer but not the end user. No information about what happened (no route? No response? connection refused? login failed? some protocol error?)

As it happens, in this case, I now know it's because the device is a very old cisco console server and it only speaks SSHv1.

**Comment by danilopopeye** [comment]
> As far as I can see, it's something that useful to the developer but not the end user. No information about what happened (no route? No response? connection refused? login failed? some protocol error?)

yeah, I know it is not helpful but the connections lib (ssh & telnet) don't give much info why the connection couldn't be made.

@howardjones there is any other point that you still need help, or can we close this issue?

(not wanting to be rude or anything, but I'm trying to keep the issues and pull requests here under control)

**Comment by howardjones** [comment]
question 4 is still bothering me, but please close the ticket. I understand the motivation :-)
