### ISSUE TITLE
ASR 9k outputs a timestamp with every command

### ISSUE THREAD

**Issue by ja-frog** [ytti/oxidized#1022]
My first time posting anything so I am sorry if I go about this the wrong way. I recently set Oxidized up to backup the config of a new ASR 9k router. Unfortunately, it outputs the timestamp after every command which makes it think that the configuration has changed with every poll. My workaround has been to add `post_login 'terminal exec prompt no-timestamp'` at line 146 to turn this feature off. Could this be added to the code?

**Comment by laf** [comment]
Is `terminal exec prompt no-timestamp` session specific or does it change the devices config?

**Comment by ja-frog** [comment]
It is session specific

**Comment by laf** [comment]
I'd say submit the change as a pr then :)
