### ISSUE TITLE
High CPU utilization

### ISSUE THREAD

**Issue by dineshdil** [ytti/oxidized#1023]
I have installed oxidized and configured for 17 nodes but its eating high CPU and taking a long time even to attempts for backup. I tried with 3 nodes also but the same problem.

oxidized -v
0.20.0
ruby -v
ruby 2.2.6p396 (2016-11-15 revision 56800) [x86_64-linux]

I have tried with ruby 1.9, 2.0 2.1 but same problem.

PID USER PR NI VIRT RES SHR S %CPU %MEM TIME+ COMMAND
15566 oxidized 20 0 1079.2m 64.7m 4.7m S 100.3 0.4 21:17.33 oxidized

Samples: 48K of event 'cycles:ppp', Event count (approx.): 27581136044
Overhead Shared Object Symbol
7.08% libruby.so.2.0.0 [.] 0x00000000000fe03a
6.12% libruby.so.2.0.0 [.] rb_thread_check_ints
4.92% libruby.so.2.0.0 [.] 0x00000000000fe20c
4.02% libruby.so.2.0.0 [.] 0x00000000000fe03e
3.88% libruby.so.2.0.0 [.] 0x00000000000fe030
3.50% libruby.so.2.0.0 [.] onigenc_mbclen_approximate
3.46% libruby.so.2.0.0 [.] 0x00000000000fe041
3.26% libruby.so.2.0.0 [.] 0x00000000000fe80b
2.95% libruby.so.2.0.0 [.] 0x00000000000fe216
2.71% libruby.so.2.0.0 [.] 0x0000000000100617
2.39% libruby.so.2.0.0 [.] 0x00000000000fe212
1.86% libruby.so.2.0.0 [.] 0x00000000000fe1c7
1.76% libruby.so.2.0.0 [.] rb_thread_check_ints@plt
1.70% libruby.so.2.0.0 [.] 0x00000000000fe1e2
1.70% libruby.so.2.0.0 [.] 0x00000000000fe83a
1.66% libruby.so.2.0.0 [.] 0x0000000000188c28
1.63% libruby.so.2.0.0 [.] 0x00000000000fea23
1.61% libruby.so.2.0.0 [.] onigenc_mbclen_approximate@plt
1.55% libruby.so.2.0.0 [.] 0x00000000000fea7c
1.43% libruby.so.2.0.0 [.] 0x0000000000100619
1.39% libruby.so.2.0.0 [.] 0x00000000000fe9ff
1.32% libruby.so.2.0.0 [.] 0x00000000000fe201
1.30% libruby.so.2.0.0 [.] 0x00000000000fe1e5
1.23% libruby.so.2.0.0 [.] 0x00000000000fe1b0
1.17% libruby.so.2.0.0 [.] 0x00000000000ff1ac
1.17% libruby.so.2.0.0 [.] 0x00000000000fea44
1.17% libruby.so.2.0.0 [.] 0x00000000000fea14
1.15% libruby.so.2.0.0 [.] 0x000000000010060a
1.02% libruby.so.2.0.0 [.] 0x000000000010061d

**Comment by laf** [comment]
Please pastebin your config

**Comment by dineshdil** [comment]
cat config
---
username: username
password: password
model: vrp
interval: 3600
use_syslog: false
debug: false
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 127.0.0.1:8888
next_adds_job: true
vars: {}
groups: {}
models: {}
log: /home/oxidized/.config/oxidized/logs/log
pid: /home/oxidized/.config/oxidized/pid
input:
  default: ssh, telnet
  debug: true
  ssh:
    secure: false
output:
  default: file
#  git:
#    user: Oxidized
#    email: oxidized@example.com
#    repo: ~/.config/oxidized/oxidized.git
  file:
    directory: /home/oxidized/.config/oxidized/configs
source:
  default: csv
  csv:
    file: /home/oxidized/.config/oxidized/router.db
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
      username: 2
      password: 3
    vars_map:
      enable: 4
      telnet_port: 5
    gpg: false
model_map:
  Cisco: ios
  Juniper: junos
  Huawei: vrp
  Mikrotik: routeros
  Zyxel: zynos

**Comment by laf** [comment]
In the other issue you commented on, that user said switching from csv to http as the source resolved the issue. Can you do that?

**Comment by dineshdil** [comment]
to change the source from csv to http, I need to use another app which can get integrated with oxidized. CSV is easy to use & integrate.. can you suggest any app/module for http?

**Comment by laf** [comment]
LibreNMS works but that's probably hugely overkill for just feeding data to Oxidized. You can just use a static file from a web server, as long as it outputs json you can use it to test.

**Comment by danilopopeye** [comment]
can you post a sanitized version of you `router.db` too, please

**Comment by dineshdil** [comment]
10.11.4.2:ciscosmb:cisco:cisco@123
10.15.25.254:ciscosmb:cisco:Admin@123
10.11.4.38:tplink:admin:admin
10.11.4.66:Mikrotik:admin:Admin@00::1023
10.11.4.246:Mikrotik:admin:Admin
#router_ip:ios:username:password:enable_password:port

Now I have configured HTTP where CPU utilization look good but its difficult to configure for each device as LibreNMS only provide ip & os name in response. e.q.
{
        "hostname": "10.11.4.38",
        "os": "tplink"
    },

other problem: its not working with Mikrotik (RouterOS) and exit with these chars on prompt (6c;3R 6c;3R).

MikroTik v6.37.5 (bugfix)
Login: admin
Password:


  MMM      MMM       KKK                          TTTTTTTTTTT      KKK
  MMMM    MMMM       KKK                          TTTTTTTTTTT      KKK
  MMM MMMM MMM  III  KKK  KKK  RRRRRR     OOOOOO      TTT     III  KKK  KKK
  MMM  MM  MMM  III  KKKKK     RRR  RRR  OOO  OOO     TTT     III  KKKKK
  MMM      MMM  III  KKK KKK   RRRRRR    OOO  OOO     TTT     III  KKK KKK
  MMM      MMM  III  KKK  KKK  RRR  RRR   OOOOOO      TTT     III  KKK  KKK

  MikroTik RouterOS 6.37.5 (c) 1999-2017       http://www.mikrotik.com/

[?]             Gives the list of available commands
command [?]     Gives help on the command and list of arguments

[Tab]           Completes the command/word. If the input is ambiguous,
--More--(96%)
Most commands optionally preceded by integer argument k.  Defaults in brackets.
Star (*) indicates argument becomes new default.
-------------------------------------------------------------------------------
<space>                 Display next k lines of text [current screen size]
z                       Display next k lines of text [current screen size]*
<return>                Display next k lines of text [1]*
d or ctrl-D             Scroll k lines [current scroll size, initially 11]*
q or Q or <interrupt>   Exit from more
s                       Skip forward k lines of text [1]
f                       Skip forward k screenfuls of text [1]
b or ctrl-B             Skip backwards k screenfuls of text [1]
'                       Go to place where previous search started
=                       Display current line number
/<regular expression>   Search for kth occurrence of regular expression [1]
n                       Search for kth occurrence of last r.e [1]
!<cmd> or :!<cmd>       Execute <cmd> in a subshell
v                       Start up /usr/bin/vi at current line
ctrl-L                  Redraw screen
:n                      Go to kth next file [1]
:p                      Go to kth previous file [1]
:f                      Display current file name and line number
.                       Repeat previous command
-------------------------------------------------------------------------------
                a second [Tab] gives possible options

/               Move up to base level
..              Move up one level
/command        Use command at the base level
[admin@DC] > /system routerboard print
[root@localhost ~]# 6c;3R 6c;3R

**Comment by dineshdil** [comment]
Hi, Do you see anything wrong on configuration?

**Comment by danilopopeye** [comment]
@dineshdil sorry, no idea here. maybe something in the debug logs. have you look at them?

**Comment by wk** [comment]
This is an older issue, and Oxidized has seen several new releases since it has been posted. If this is still relevant, please re-attempt this on a more recent (0.24.0) version and update the issue with your findings.
