### ISSUE TITLE
SSL_connect error

### ISSUE THREAD

**Issue by papatango71** [ytti/oxidized#1026]
I apologize in advance if this is not the correct place to ask this question.....  I am getting this error when trying to start oxidized:

oxidized@nms01-eqch2
[/home/oxidized/.config/oxidized]$ oxidized
SSL_connect returned=1 errno=0 state=error: certificate verify failed
/usr/lib/ruby/2.3.0/net/http.rb:933:in `connect_nonblock': SSL_connect returned=1 errno=0 state=error: certificate verify failed (OpenSSL::SSL::SSLError)

I have updated ruby gems but that did not help.  Any help to get this resolved would be greatly appreciated.

Thank you.

-Patrick

**Comment by laf** [comment]
Guessing you've got a self signed cert or similar? You can disable ssl verification, config option should be in the docs.

**Comment by papatango71** [comment]
@Laf Thank you for pointing me in the right direction.  I thought the error was Ruby related and not something I could resolve in the Oxidized config.  Changing the input to "secure: false" fixed the issue.

Thank you.
