### ISSUE TITLE
A10 Networks TPS support

### ISSUE THREAD

**Issue by papatango71** [ytti/oxidized#1028]
The current A10 Networks module works great for the ADC platform but does not work for the TPS platform.  Below are the commands that would need to be added to a new module specifically for the TPS devices.

```
show version
show bootimage
show running-config
```

Below is what I am seeing in Oxidized:

              ! ! COMMAND: show version
            

              ! Thunder Series Unified Application Service Gateway TH4435S TPS
            

              !   Copyright 2007-2016 by A10 Networks, Inc.  All A10 Networks products are
            

              !   protected by one or more of the following US patents:
            

              !   9294503, 9294467, 9270774, 9270705, 9258332, 9253152, 9219751, 9215275
            

              !   9154584, 9154577, 9124550, 9122853, 9118620, 9118618, 9106561, 9094364
            

              !   9060003, 9032502, 8977749, 8943577, 8918857, 8914871, 8904512, 8897154
            

              !   8868765, 8849938, 8826372, 8813180, 8782751, 8782221, 8595819, 8595791
            

              !   8595383, 8584199, 8464333, 8423676, 8387128, 8332925, 8312507, 8291487
            

              !   8266235, 8151322, 8079077, 7979585, 7804956, 7716378, 7665138, 7647635
            

              !   7627672, 7596695, 7577833, 7552126, 7392241, 7236491, 7139267, 6748084
            

              !   6658114, 6535516, 6363075, 6324286, RE44701, 8392563, 8103770, 7831712
            

              !   7606912, 7346695, 7287084, 6970933, 6473802, 6374300
            

              !
            

              !       64-bit Advanced Core OS (ACOS) version 3.1.4, build 3862943797 (Aug-24-2016,20:56)
            

              !         Booted from Hard Disk primary image
            

              !
            

              !       Serial Number: TH44143115470003
            

              !       Firmware version: 5.6
            

              !       aFleX version: 2.0.0
            

              !       aXAPI version: 3.0
            

              !       Hard Disk primary image (default) version 3.1.4, build 3862943797
            

              !       Hard Disk secondary image version 3.1.3, build 71
            

              !       Compact Flash primary image (default) version 3.1.3, build 71
            

              !       Last configuration saved at &lt;removed&gt;
            

              !       Hardware: 20 CPUs(Stepping 4), Single 97G Hard disk
            

              !       Memory &lt;removed&gt;
            

              !       Hardware Manufacturing Code: 154711
            

              !       Current time is &lt;removed&gt;
            

              !       The system has been up &lt;removed&gt;
            

              ! ! COMMAND: show bootimage
            

              !                       (* = Default)
            

              !                           Version
            

              ! -----------------------------------------------
            

              ! Hard Disk primary         3.1.4.3862943797 (*)
            

              ! Hard Disk secondary       3.1.3.71
            

              ! Compact Flash primary     3.1.3.71 (*)
            

              ! ! COMMAND: show license
            

              ! Host ID: 75A047E08F3F5CF5F2112C66D7F32E539204E6BE
            

              ! COMMAND: show partition-config all
            

                               ^
            

              % Unrecognized command.Invalid input detected at &apos;^&apos; marker.
            

              
            

              ! COMMAND: show running-config all-partitions
            

                                              ^
            

              % Unrecognized command.Invalid input detected at &apos;^&apos; marker.
            

              
            

              ! ! COMMAND: show aflex all-partitions
            

              ! No such aFleX.

**Comment by danilopopeye** [comment]
@papatango71 could you provide a pull request with a new model? something like `A10TPS.rb`.

**Comment by papatango71** [comment]
@danilopopeye ....  I am not sure how to do what you are asking.  Do you have an example..??

Thank you.

**Comment by danilopopeye** [comment]
@papatango71 you can use the PR #1011 as an example 😉

**Comment by papatango71** [comment]
@danilopopeye I hope this is what you are looking for. 

https://pastebin.com/StywGBGB

If you need more from me on how to add this device please let me know.

**Comment by laf** [comment]
@papatango71 He was suggesting to use the PR #1011 as a base for you adding support for this device yourself.

**Comment by alexandrecorso** [comment]
Hello, Is it issue still on date? We are using TPS from A10 Networks and I would like to update this issue and maybe do a PR?

**Comment by alexandrecorso** [comment]
Add PR https://github.com/ytti/oxidized/pull/1733

**Comment by edielson** [comment]
how to get the configuration in the router.db file for the A10 thunder
