### ISSUE TITLE
Cisco IOS version 12.2 and 15 different configuration

### ISSUE THREAD

**Issue by wallys65** [ytti/oxidized#1029]
Dear Sirs,
I have configured Oxidized  for backup configuration of the Switch Cisco with IOS Version 12.2 and 15.0.

It isn't the same configuration, because for the command **show running-config** the "privilege" on Switch V 12.2  must be 15 ( it doesn't working with other privilege) and the file ios.rb in Oxidized is the default instead for V15 the "privilege" must be 6 and the command will be **show running-config view all** where I have copied and renamed ios.rb in ios15.rb with command modified.

Do you know this behavior ?

Have you any other solution for the IOS device with diferent versions ?

Thanks in advance
Best Regards

Walter

**Comment by rfdrake** [comment]
I think this is the same as issue #213 

I think the final proposed solution seems like the best one.   Having an ios_rbac flag on nodes that are configured for rbac means there is no weird parsing for unsupported nodes or nodes that just don't have it turned on.

**Comment by laf** [comment]
@wallys65 as pointed out this is a duplicate, please try the suggested fixes in #213 and comment there.
