### ISSUE TITLE
Oxidized with Librenms

### ISSUE THREAD

**Issue by amaizenshtein** [ytti/oxidized#1033]
Please advise , my oxidized crushes, and give me the following errors in the crush log

``` 
[root@dl1-librenms-srv01 ~]# cat /root/.config/oxidized/crash
--------------------------------------------------
2017-09-18 10:27:40 UTC
Invalid value; config files can only store string, bool or int keys [TypeError]
--------------------------------------------------
/usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/output/git.rb:193:in `[]='
/usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/output/git.rb:193:in `update_repo'
/usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/output/git.rb:171:in `update'
/usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/output/git.rb:57:in `store'
/usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/worker.rb:48:in `process'
/usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/worker.rb:15:in `block in work'
/usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/worker.rb:15:in `each'
/usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/worker.rb:15:in `work'
/usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/core.rb:36:in `run'
/usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/core.rb:28:in `initialize'
/usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/core.rb:4:in `new'
/usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/core.rb:4:in `new'
/usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/cli.rb:12:in `run'
/usr/local/share/gems/gems/oxidized-0.20.0/bin/oxidized:9:in `<top (required)>'
/usr/local/bin/oxidized:23:in `load'
/usr/local/bin/oxidized:23:in `<main>'
```

**Comment by laf** [comment]
Post your config file, you have an issue in it,

**Comment by amaizenshtein** [comment]
log: ~/.config/oxidized/oxidized.log
interval: 3600
use_syslog: false
debug: true
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 127.0.0.1:8888
vars: {}
groups:
   Arista:
     username: xxx
     password: xxx
   Juniper:
     username: xxx
     password: xxx
   PAN:
     username: xxx
     password: xxx
pid: /root/.config/oxidized/pid
input:
  default: ssh
  debug: false
  ssh:
    secure: false
output:
  default: git
  git:
    user: oxidized
    repo: "/root/.config/oxidized/configs/devices.git"
source:
  default: http
  http:
    url: http://127.0.0.1/api/v0/oxidized
    scheme: http
    delimiter: !ruby/regexp /:/
    map:
      name: hostname
      model: os
      groups: group
    headers:
      X-Auth-Token: 'df758cfca87def7d906d7ff763476589'
model_map:
  Arista: arista_eos
  Juniper: junos
  PAN: panos

**Comment by amaizenshtein** [comment]
Actually from the logs I see that instead of using the right usernames, it uses username 

D, [2017-09-18T12:25:07.916867 #13668] DEBUG -- : lib/oxidized/node.rb: Oxidized::SSH failed for dl1apfw01b.pan.local
D, [2017-09-18T12:25:07.916935 #13668] DEBUG -- : lib/oxidized/job.rb: Config fetched for dl1apfw01b.pan.local at 2017-09-18 12:25:07 UTC
W, [2017-09-18T12:25:08.050459 #13668]  WARN -- : dl1apfw01b.pan.local status no_connection, retry attempt 3
D, [2017-09-18T12:25:08.050607 #13668] DEBUG -- : lib/oxidized/worker.rb: Jobs 0, Want: 1
D, [2017-09-18T12:25:08.050707 #13668] DEBUG -- : lib/oxidized/worker.rb: Added dl1apfw01b.pan.local to the job queue
D, [2017-09-18T12:25:08.050841 #13668] DEBUG -- : lib/oxidized/job.rb: Starting fetching process for dl1apfw01b.pan.local at 2017-09-18 12:25:08 UTC
D, [2017-09-18T12:25:08.051110 #13668] DEBUG -- : lib/oxidized/input/ssh.rb: Connecting to dl1apfw01b.pan.local
D, [2017-09-18T12:25:08.050738 #13668] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
W, [2017-09-18T12:25:08.911468 #13668]  WARN -- : 10.102.250.101 raised Net::SSH::AuthenticationFailed with msg "Authentication failed for user username@10.102.250.101"
D, [2017-09-18T12:25:08.911618 #13668] DEBUG -- : lib/oxidized/node.rb: Oxidized::SSH failed for dl1apfw01b.pan.local
D, [2017-09-18T12:25:08.911684 #13668] DEBUG -- : lib/oxidized/job.rb: Config fetched for dl1apfw01b.pan.local at 2017-09-18 12:25:08 UTC
W, [2017-09-18T12:25:09.053025 #13668]  WARN -- : dl1apfw01b.pan.local status no_connection, retries exhausted, giving up
D, [2017-09-18T12:25:09.053197 #13668] DEBUG -- : lib/oxidized/worker.rb: Jobs 0, Want: 1
D, [2017-09-18T12:25:09.053388 #13668] DEBUG -- : lib/oxidized/job.rb: Starting fetching process for dl1ert01.pan.local at 2017-09-18 12:25:09 UTC
D, [2017-09-18T12:25:09.053640 #13668] DEBUG -- : lib/oxidized/input/ssh.rb: Connecting to dl1ert01.pan.local

**Comment by laf** [comment]
Add a git email address as per the config.

**Comment by amaizenshtein** [comment]
Added email, same result

**Comment by amaizenshtein** [comment]
these are the logs

D, [2017-09-18T12:45:11.837511 #2166] DEBUG -- : lib/oxidized/node.rb: Loading model "arista_eos"
E, [2017-09-18T12:45:11.839549 #2166] ERROR -- : node {:name=>"dl1apsp01.pan.local", :model=>"arista_eos", :groups=>"Arista"} raised Oxidized::ModelNotFound with message 'arista_eos not found for node 10.102.126.1'
D, [2017-09-18T12:45:11.839603 #2166] DEBUG -- : resolving DNS for dl1apsp02.pan.local...
D, [2017-09-18T12:45:11.839632 #2166] DEBUG -- : IPADDR 
D, [2017-09-18T12:45:11.843748 #2166] DEBUG -- : node.rb: resolving node key 'input', with passed global value of 'ssh' and node value ''
D, [2017-09-18T12:45:11.843849 #2166] DEBUG -- : node.rb: returning node key 'input' with value 'ssh'
D, [2017-09-18T12:45:11.843895 #2166] DEBUG -- : node.rb: resolving node key 'output', with passed global value of 'git' and node value ''
D, [2017-09-18T12:45:11.843943 #2166] DEBUG -- : node.rb: returning node key 'output' with value 'git'
D, [2017-09-18T12:45:11.843969 #2166] DEBUG -- : node.rb: resolving node key 'model', with passed global value of '' and node value 'arista_eos'
D, [2017-09-18T12:45:11.843995 #2166] DEBUG -- : node.rb: setting node key 'model' to value 'junos' from global
D, [2017-09-18T12:45:11.844019 #2166] DEBUG -- : node.rb: returning node key 'model' with value 'arista_eos'
D, [2017-09-18T12:45:11.844040 #2166] DEBUG -- : lib/oxidized/node.rb: Loading model "arista_eos"
E, [2017-09-18T12:45:11.845967 #2166] ERROR -- : node {:name=>"dl1apsp02.pan.local", :model=>"arista_eos", :groups=>"Arista"} raised Oxidized::ModelNotFound with message 'arista_eos not found for node 10.102.126.2'
D, [2017-09-18T12:45:11.846021 #2166] DEBUG -- : resolving DNS for dl1apsp03.pan.local...
D, [2017-09-18T12:45:11.846083 #2166] DEBUG -- : IPADDR 
D, [2017-09-18T12:45:11.849916 #2166] DEBUG -- : node.rb: resolving node key 'input', with passed global value of 'ssh' and node value ''
D, [2017-09-18T12:45:11.849978 #2166] DEBUG -- : node.rb: returning node key 'input' with value 'ssh'
D, [2017-09-18T12:45:11.850028 #2166] DEBUG -- : node.rb: resolving node key 'output', with passed global value of 'git' and node value ''
D, [2017-09-18T12:45:11.850076 #2166] DEBUG -- : node.rb: returning node key 'output' with value 'git'
D, [2017-09-18T12:45:11.850110 #2166] DEBUG -- : node.rb: resolving node key 'model', with passed global value of '' and node value 'arista_eos'
D, [2017-09-18T12:45:11.850137 #2166] DEBUG -- : node.rb: setting node key 'model' to value 'junos' from global
D, [2017-09-18T12:45:11.850174 #2166] DEBUG -- : node.rb: returning node key 'model' with value 'arista_eos'
D, [2017-09-18T12:45:11.850196 #2166] DEBUG -- : lib/oxidized/node.rb: Loading model "arista_eos"
E, [2017-09-18T12:45:11.851970 #2166] ERROR -- : node {:name=>"dl1apsp03.pan.local", :model=>"arista_eos", :groups=>"Arista"} raised Oxidized::ModelNotFound with message 'arista_eos not found for node 10.102.126.3'
D, [2017-09-18T12:45:11.852023 #2166] DEBUG -- : resolving DNS for dl1apdmzsw01.pan.local...
D, [2017-09-18T12:45:11.852051 #2166] DEBUG -- : IPADDR 
D, [2017-09-18T12:45:11.864057 #2166] DEBUG -- : node.rb: resolving node key 'input', with passed global value of 'ssh' and node value ''
D, [2017-09-18T12:45:11.864144 #2166] DEBUG -- : node.rb: returning node key 'input' with value 'ssh'
D, [2017-09-18T12:45:11.864184 #2166] DEBUG -- : node.rb: resolving node key 'output', with passed global value of 'git' and node value ''
D, [2017-09-18T12:45:11.864212 #2166] DEBUG -- : node.rb: returning node key 'output' with value 'git'
D, [2017-09-18T12:45:11.864235 #2166] DEBUG -- : node.rb: resolving node key 'model', with passed global value of '' and node value 'arista_eos'
D, [2017-09-18T12:45:11.864260 #2166] DEBUG -- : node.rb: setting node key 'model' to value 'junos' from global
D, [2017-09-18T12:45:11.864321 #2166] DEBUG -- : node.rb: returning node key 'model' with value 'arista_eos'
D, [2017-09-18T12:45:11.864347 #2166] DEBUG -- : lib/oxidized/node.rb: Loading model "arista_eos"
E, [2017-09-18T12:45:11.866238 #2166] ERROR -- : node {:name=>"dl1apdmzsw01.pan.local", :model=>"arista_eos", :groups=>"Arista"} raised Oxidized::ModelNotFound with message 'arista_eos not found for node 10.102.128.4'
D, [2017-09-18T12:45:11.866289 #2166] DEBUG -- : resolving DNS for dl1apdmzsw02.pan.local...
D, [2017-09-18T12:45:11.866327 #2166] DEBUG -- : IPADDR 
D, [2017-09-18T12:45:11.875710 #2166] DEBUG -- : node.rb: resolving node key 'input', with passed global value of 'ssh' and node value ''
D, [2017-09-18T12:45:11.875777 #2166] DEBUG -- : node.rb: returning node key 'input' with value 'ssh'
D, [2017-09-18T12:45:11.875817 #2166] DEBUG -- : node.rb: resolving node key 'output', with passed global value of 'git' and node value ''
D, [2017-09-18T12:45:11.875846 #2166] DEBUG -- : node.rb: returning node key 'output' with value 'git'
D, [2017-09-18T12:45:11.875869 #2166] DEBUG -- : node.rb: resolving node key 'model', with passed global value of '' and node value 'arista_eos'
D, [2017-09-18T12:45:11.875899 #2166] DEBUG -- : node.rb: setting node key 'model' to value 'junos' from global
D, [2017-09-18T12:45:11.875924 #2166] DEBUG -- : node.rb: returning node key 'model' with value 'arista_eos'
D, [2017-09-18T12:45:11.875961 #2166] DEBUG -- : lib/oxidized/node.rb: Loading model "arista_eos"
E, [2017-09-18T12:45:11.877757 #2166] ERROR -- : node {:name=>"dl1apdmzsw02.pan.local", :model=>"arista_eos", :groups=>"Arista"} raised Oxidized::ModelNotFound with message 'arista_eos not found for node 10.102.128.5'
D, [2017-09-18T12:45:11.877810 #2166] DEBUG -- : resolving DNS for dl1ets01.pan.local...
D, [2017-09-18T12:45:11.877838 #2166] DEBUG -- : IPADDR 
D, [2017-09-18T12:45:11.879467 #2166] DEBUG -- : node.rb: resolving node key 'input', with passed global value of 'ssh' and node value ''
D, [2017-09-18T12:45:11.879539 #2166] DEBUG -- : node.rb: returning node key 'input' with value 'ssh'
D, [2017-09-18T12:45:11.879577 #2166] DEBUG -- : node.rb: resolving node key 'output', with passed global value of 'git' and node value ''
D, [2017-09-18T12:45:11.879629 #2166] DEBUG -- : node.rb: returning node key 'output' with value 'git'
D, [2017-09-18T12:45:11.879656 #2166] DEBUG -- : node.rb: resolving node key 'model', with passed global value of '' and node value 'arista_eos'
D, [2017-09-18T12:45:11.879680 #2166] DEBUG -- : node.rb: setting node key 'model' to value 'junos' from global
D, [2017-09-18T12:45:11.879705 #2166] DEBUG -- : node.rb: returning node key 'model' with value 'arista_eos'
D, [2017-09-18T12:45:11.879726 #2166] DEBUG -- : lib/oxidized/node.rb: Loading model "arista_eos"
E, [2017-09-18T12:45:11.881499 #2166] ERROR -- : node {:name=>"dl1ets01.pan.local", :model=>"arista_eos", :groups

**Comment by laf** [comment]
So that's not the same result. Now you're asking a different question which looks like it's because you are trying to model_map your group names to an OS which is not what it's there for. model_map is to map the OS in your source to the OS in Oxidized. So arista_eos: eos would work.

**Comment by amaizenshtein** [comment]
do you mean to change in config to this:
model_map:
  Arista: eos

or changes in config.php are also required?

**Comment by laf** [comment]
No change the arista one as I put above. `arista_eos: eos`. The others are wrong as well.

You only need to use the map if the OS name in LIbreNMS is different than what oxidized uses.

**Comment by amaizenshtein** [comment]
See this:

[root@dl1-librenms-srv01 oxidized]# curl -H 'X-Auth-Token: df758cfca87def7d906d7ff763476589' http://127.0.0.1/api/v0/oxidized 
[
    {
        "hostname": "dl1its01.pan.local",
        "os": "arista_eos",
        "group": "Arista"
    },
    {
        "hostname": "dl1its02.pan.local",
        "os": "arista_eos",
        "group": "Arista"
    },
    {
        "hostname": "dl1apfw01a.pan.local",
        "os": "panos",
        "group": "PAN"
    },
    {
        "hostname": "dl1apdmzfw01a.pan.local",
        "os": "panos",
        "group": "PAN"
    },
    {
        "hostname": "dl1apdmzfw01b.pan.local",
        "os": "panos",
        "group": "PAN"
    },
    {
        "hostname": "dl1apfw01b.pan.local",
        "os": "panos",
        "group": "PAN"
    },
    {
        "hostname": "dl1ert01.pan.local",
        "os": "junos",
        "group": "Juniper"


Please let me know if model map is good now?
model_map:
  arista_eos: eos
  Juniper: junos
  PAN: panos

**Comment by laf** [comment]
No, stop trying to map group names. It's the OS you are mapping.

I don't think you need junos or panos ones.

**Comment by amaizenshtein** [comment]
I've 3 types of devices, I didn't use global naming, I divided them to groups,

**Comment by amaizenshtein** [comment]
Can you please provide me the right config I should use in my case, based on the file config above?

**Comment by laf** [comment]
That's fine, it doesn't matter though you only map OS' and you only map them when the names different.

**Comment by amaizenshtein** [comment]
do you mean, I can remove this part from the config file?
model_map:
  arista_eos: eos
  Juniper: junos
  PAN: panos

**Comment by laf** [comment]
No, the arista needs to be in place - see the different names? The others might not be needed, I don't know without checking. Look at what OS name oxidized uses and see

**Comment by amaizenshtein** [comment]
Looks like there is a progress, now on librenms config part I see the following, no configs

Sync status: no_connection

    Node: dl1apfw01b.pan.local
    IP: 10.102.250.101
    Model: PanOS
    Last Sync: 2017-09-18 13:04:43 UTC

    node not found

**Comment by amaizenshtein** [comment]
How the librenms pulles the config from git folders? where I should see the configs in git? what is the folder?

**Comment by amaizenshtein** [comment]
also I'm getting the following on the logs 


D, [2017-09-18T14:46:16.940782 #18575] DEBUG -- : node.rb: resolving node key 'input', with passed global value of 'ssh' and node value ''
D, [2017-09-18T14:46:16.940839 #18575] DEBUG -- : node.rb: returning node key 'input' with value 'ssh'
D, [2017-09-18T14:46:16.940874 #18575] DEBUG -- : node.rb: resolving node key 'output', with passed global value of 'git' and node value ''
D, [2017-09-18T14:46:16.940907 #18575] DEBUG -- : node.rb: returning node key 'output' with value 'git'
D, [2017-09-18T14:46:16.940929 #18575] DEBUG -- : node.rb: resolving node key 'model', with passed global value of '' and node value 'eos'
D, [2017-09-18T14:46:16.940952 #18575] DEBUG -- : node.rb: setting node key 'model' to value 'junos' from global
D, [2017-09-18T14:46:16.940975 #18575] DEBUG -- : node.rb: returning node key 'model' with value 'eos'
D, [2017-09-18T14:46:16.941004 #18575] DEBUG -- : node.rb: resolving node key 'username', with passed global value of '' and node value ''
D, [2017-09-18T14:46:16.941027 #18575] DEBUG -- : node.rb: setting node key 'username' to value 'username' from global
D, [2017-09-18T14:46:16.941056 #18575] DEBUG -- : node.rb: returning node key 'username' with value 'username'
D, [2017-09-18T14:46:16.941098 #18575] DEBUG -- : node.rb: resolving node key 'password', with passed global value of '' and node value ''
D, [2017-09-18T14:46:16.941122 #18575] DEBUG -- : node.rb: setting node key 'password' to value 'password' from global
D, [2017-09-18T14:46:16.941145 #18575] DEBUG -- : node.rb: returning node key 'password' with value 'password'

**Comment by ZacharyPuls** [comment]
You need the model_map when LibreNMS returns a different OS value than Oxidized can accept. So, if you have a device that returns this from LibreNMS:

    {
        "hostname": "dl1apfw01b.pan.local",
        "os": "palo_alto",
        "group": "PAN"
    }

, then you would need to configure your model_map like this:

    model_map:
        palo_alto: panos

You can see what models are supported [here](https://github.com/ytti/oxidized/tree/master/lib/oxidized/model), just look at the file names.

**Comment by laf** [comment]
@amaizenshtein Can this be closed now?

**Comment by amaizenshtein** [comment]
yep




Alex Maizenshtein | Principal Network Engineer | 3 x CCIE #34560 (R&S/SP/DC)
M: +972-54-6501229   | T: +972-74-7265076  | www.paloaltonetworks.com<http://www.paloaltonetworks.com/>
[cid:image001.png@01D35C59.22638AB0]
