### ISSUE TITLE
FortiOS Feature Request - Support FortiADC configuration backup

### ISSUE THREAD

**Issue by tnielsen2** [ytti/oxidized#1041]
Deleted

**Comment by jsynack** [comment]
Hello @tnielsen2  ,

Some of the items that are shown for `get system vdom-status` are more operational and that they would be changing constantly - typically you don't want this churn on the configuration database for your devices. These are better sent to a network management application or graphing application to keep long-term trending for these values.

Looking at the `get system status` on a FortiADC VM - There are only a few things that need to be excluded for this to work with the existing fortios model/driver. I can make this change later today.

One thing I noticed on a FortiADC-VM (4.8.2) is that the 'Last Reboot' time appears to change +- one second each time I run the command. Do you notice this on the hardware units? 

 For example, if you run `get system status` , and then run it again (several times) , does the 'Last Reboot' change at all?

**Comment by tnielsen2** [comment]
Sorry for the late response. No, the Last Reboot time does not change for hardware devices, unless it is upgraded or rebooted.

**Comment by tnielsen2** [comment]
Hello, any update to this? Thanks for all you do!

**Comment by tnielsen2** [comment]
Hello,

I was able to do a debug on the FortiADC and it appears that the first line of the debug is:

(M) lb01-04.ydc #


And it doesn't go any farther.

**Comment by tnielsen2** [comment]
Closing, no longer needed.
