### ISSUE TITLE
Timeout behaviour

### ISSUE THREAD

**Issue by rvandepu** [ytti/oxidized#1044]
Hi,

Question about the timeout config parameter:
We have some devices in our network with large configurations. Fetching these can take up to about 3~5 minutes. When I set the timeout value to 5 minutes, I notice that the timeout between failed device connection attempts also takes 5 minutes. Is there a different parameter for the timeout on fetching the configuration?

Also, when oxidized is unable to connect to a device (due to wrong credentials, device offline, ...), I notice that oxidized does not connect to other devices when waiting on the timeout. Is this the right behaviour? I would assume one worker thread is blocked an the rest will continue connecting to devices and fetching config.

With kind regards,
Ruben

**Comment by laf** [comment]
I don't believe that a separate timeout is available for fetching the config.

Worker threads are spawned on demand based on your interval value, if all your devices can be backed up within that time with a single thread then that's all that will be used (afaik). More threads will be spawned to complete the full cycle within that interval value.

**Comment by rvandepu** [comment]
Hi,

Thanks for the quick answer.
Would it be feasible to add a `fetch_timeout` parameter as extra config option and use this var in the code for fetching config? To make it backwards compatible: if `fetch_timeout` is not set in the config, use the regular `timeout` value and assign it to `fetch_timeout`.

I've been looking at the code, but I have 0 ruby skills...

**Comment by laf** [comment]
I'm sure it's possible :)

**Comment by wk** [comment]
In various referenced issues, interest has been expressed in:

* Being able to configure a timeout per device (node)
* Being able to configure a timeout per group
* Being able to pass the configured timeout all the way down the stack into Net::Telnet and Net:SSH

This issue can act as a meta-issue for all timeout handling refactoring work.

**Comment by spinza** [comment]
As [pointed out in other issue](https://github.com/ytti/oxidized/issues/908#issuecomment-315544697) the timeout setting mostly controls the SSH connection timeout which is only relevant for the initial connection.  

I've managed get a timeout by setting ServerAliveInterval and ServerAliveCountMax in the oxidized user's ssh config.

**Comment by wk** [comment]
In the ssh input, in addition to the SSH connection timeout (at the Net::SSH level), a timeout is also set for [each iteration of the ssh loop](https://github.com/wk/oxidized/blob/90aa9e68ed16c96f54ecd3e3e197d85850531f6e/lib/oxidized/input/ssh.rb#L95), and represents the period of time that can pass between each two instances that an input line is matched.

**Comment by powerByKoro** [comment]
Hello everyone! is there any resolve for this issue ? we currently faced this issue :(
