### ISSUE TITLE
Configure Oxidized with git 

### ISSUE THREAD

**Issue by Ondjultomte** [ytti/oxidized#1046]
Do you just install a local git repo 
https://linuxprograms.wordpress.com/2010/05/10/how-to-set-up-a-git-repository-locally/

and edit the oxid git conf accordingly?

**Comment by rvandepu** [comment]
If you use `output: git`, oxidized will create it's own git repo, as defined in the`repo` parameter. No need to set it up yourself.

You can also push the configuration to a remote repo with a hook. It's described in the documentation.

**Comment by Ondjultomte** [comment]
oxid fails to restart when I use git as output.

systemctl status oxidized -l
● oxidized.service - Oxidized - Network Device Configuration Backup Tool
   Loaded: loaded (/usr/lib/systemd/system/oxidized.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since tor 2017-09-28 15:41:04 CEST; 53s ago
  Process: 11336 ExecStart=/usr/local/bin/oxidized (code=exited, status=1/FAILURE)
 Main PID: 11336 (code=exited, status=1/FAILURE)

sep 28 15:41:04 localhost.localdomain oxidized[11336]: from /usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/core.rb:28:in `initialize'
sep 28 15:41:04 localhost.localdomain oxidized[11336]: from /usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/core.rb:4:in `new'
sep 28 15:41:04 localhost.localdomain oxidized[11336]: from /usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/core.rb:4:in `new'
sep 28 15:41:04 localhost.localdomain oxidized[11336]: from /usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/cli.rb:12:in `run'
sep 28 15:41:04 localhost.localdomain oxidized[11336]: from /usr/local/share/gems/gems/oxidized-0.20.0/bin/oxidized:9:in `<top (required)>'
sep 28 15:41:04 localhost.localdomain oxidized[11336]: from /usr/local/bin/oxidized:23:in `load'
sep 28 15:41:04 localhost.localdomain oxidized[11336]: from /usr/local/bin/oxidized:23:in `<main>'
sep 28 15:41:04 localhost.localdomain systemd[1]: oxidized.service: main process exited, code=exited, status=1/FAILURE
sep 28 15:41:04 localhost.localdomain systemd[1]: Unit oxidized.service entered failed state.
sep 28 15:41:04 localhost.localdomain systemd[1]: oxidized.service failed.

need some help to trace the issue

**Comment by rvandepu** [comment]
Could you post your configuration?

**Comment by Ondjultomte** [comment]
`diff config config.bak
25,29c25,27
<   default: git
<   git:
<     user: oxidized
<     email: kristoffer.fagerlund@atea.se
<     repo: "/home/oxidized/git/"
---
>   default: file
>   file:
>     directory: /home/oxidized/deviceconfigs`

**Comment by Ondjultomte** [comment]
It was just a issue with rights.
