### ISSUE TITLE
oxidized gather devices from the group

### ISSUE THREAD

**Issue by amaizenshtein** [ytti/oxidized#1051]
Guys,

I'm trying to run this command oxs -x username -verbose -d -r 5 —group Arista
to push new username to my Arista group devices which is gathered from Librenms API, if I want to push the config to several devices of this group, please advise how can I run it

**Comment by laf** [comment]
This is the same question you've asked over https://community.librenms.org/t/config-push/2183/5.

Can we close this?

**Comment by amaizenshtein** [comment]
Yep, you can close it
