### ISSUE TITLE
Can't SSH to Arista from oxidized server

### ISSUE THREAD

**Issue by clvnzhang** [ytti/oxidized#1054]
Hello,

  I am having an issue to connect to my arista switch from oxidized server. I have added all the necessary info to the configuration files, but I still get the raised Net::SSH::AuthenticationFailed with msg "Authentication failed error message.

Here are my configs screen shots:
[config_backup.txt](https://github.com/ytti/oxidized/files/1350406/config_backup.txt)

**Comment by clvnzhang** [comment]
router.db

![screen shot 2017-10-02 at 1 59 11 pm](https://user-images.githubusercontent.com/22844667/31099165-e78f466a-a779-11e7-80b7-11d78c14c7ca.png)

**Comment by laf** [comment]
You should enable debugging and post the debug log.

**Comment by clvnzhang** [comment]
![screen shot 2017-10-02 at 1 59 11 pm](https://user-images.githubusercontent.com/22844667/31099898-6c28edf2-a77c-11e7-859c-e9d94269720a.png)

**Comment by clvnzhang** [comment]
![screen shot 2017-10-02 at 2 17 12 pm](https://user-images.githubusercontent.com/22844667/31099947-8d4c30ac-a77c-11e7-9d90-f63e67cf41dd.png)

**Comment by laf** [comment]
Have you tried with the credentials you specify in the config direct from the oxidized host?

**Comment by clvnzhang** [comment]
Yes, I can get to the arista-a.greatergood.net with the credentials I have in the config file. I have checked many times make sure they are matching. ssh oxidized@arista-a is working.

**Comment by laf** [comment]
Has the hostname mapped to the IP correctly?

**Comment by clvnzhang** [comment]
Yes

**Comment by laf** [comment]
And you've restarted since you added them?

**Comment by clvnzhang** [comment]
Just did a restart and it still gave the error message.

**Comment by clvnzhang** [comment]
I just added another arista switch and it is also gives the same message.

**Comment by jsynack** [comment]
Is this still a problem @clvnzhang  ?

What version of EOS are you running? Is there any AAA config-conflict or anything else? Trailing spaces or other characters from your config?

 I just added two older EOS lab devices (running EOS 4.14.1F) without problems. Authentication is via AAA/tacacs+ for the oxidized user.

**Comment by empi89** [comment]
See https://github.com/ytti/oxidized/blob/master/docs/Model-Notes/EOS.md

**Comment by firozsahib** [comment]
I am also facing the same issue with arista. raised Net::SSH::AuthenticationFailed with msg "Authentication failed for user admin.

**Comment by ytti** [comment]
Did you read the note @empi89 pointed out?
