### ISSUE TITLE
Telnet debug logs are appended to

### ISSUE THREAD

**Issue by ja-frog** [ytti/oxidized#1060]
According to https://github.com/ytti/oxidized/blob/master/docs/Configuration.md#debugging, debugging should overwrite the existing logs. This works as expected with SSH. With telnet, however, it keeps appending to the file.

**Comment by wk** [comment]
@ja-frog could you give a test run to [this branch](https://github.com/wk/oxidized/tree/refactor-telnet-log) and see if it solves the issue?

**Comment by ja-frog** [comment]
@wk I should be able to do so tomorrow.

**Comment by ja-frog** [comment]
@wk I am sorry for the delay. Tried it out and it started a new debug file with each iteration as expected.

**Comment by wk** [comment]
@ja-frog thanks! I've opened #1328 to get this change in.
