### ISSUE TITLE
Class for handling models that do not request a username

### ISSUE THREAD

**Issue by ja-frog** [ytti/oxidized#1061]
I am trying to create a class to retrieve the configuration for a Calix B6 device. These aren't prompting Oxidized for a username when it tries to sign into them, only a password. From reading #573, I gather that these can be handled by dropping the stanza for username from the class for the model. I tried this, as seen in the code below, but it still seems like it is waiting on a username. 

Would someone have time to provide some guidance?

Error message in server log: <IP> raised Oxidized::PromptUndetect with msg "Password:  not matching configured prompt (?-mix:^[\w .-]+(#|>) $)"

```ruby
class B6 < Oxidized::Model

  # Calix B6 Series

  prompt /^[\w .-]+(#|>) $/
  comment  '! '

  cmd 'show version' do |cfg|
    comment cfg
  end

  cmd 'show running-config'

  cfg :ssh do
    password /^Password:/
  end

  cfg :ssh do
    if vars:enable
      post_login do
        send "enable\n"
          cmd vars(:enable)
        end
      end
    post_login 'terminal length 0'
    pre_logout do
      send "exit\n"
      send "\n\n"
    end
  end

end
```

**Comment by Fhajad** [comment]
SSH B6 should prompt you for a username (name: cli) regardless. Telnet just prompts for a password, skipping the username portion

**Comment by ja-frog** [comment]
I'm sorry, I have been away for a while.

What you say is accurate when connecting from a standard telnet or SSH client. However, when I tail the debug log for Oxidized for a B6 I am only seeing a password prompt. I verified with a packet capture that Oxidized is indeed trying to connect with SSH and not telnet.

I tried turning off exec channels just in case that is the difference yet it had no impact.

**Comment by laf** [comment]
Would you be able to put a device online for me to test?

**Comment by Fhajad** [comment]
@ja-frog I'll try your class out on some of my blades to see if I get the same issue or not. What software version are you running for comparison sake? I'm in a mix of 8.0.30.0 and 8.0.40.0.

@laf I'll let you know if it fails for me as well, then I can provide a remote session for one from my lab. These devices are basically never on direct internet (They're POTs Blades, DSL/POTs, GPON FTTH, L2 Switches, TDM to MGCP, and active ethernet "switches"). Luckily they all backup the same.

**Comment by ja-frog** [comment]
We are in the process of upgrading, so some are on 7.3.61.0 while others are running 8.0.30.0. I see the same behavior on both versions.

**Comment by ja-frog** [comment]
@Fhajad  have you had a chance to try this out in your lab?
