### ISSUE TITLE
node not found - memory leak

### ISSUE THREAD

**Issue by ngnix** [ytti/oxidized#1065]
Hello! I have oxi with zabbix, zabbix check last backup status via API http://10.110.55.100:8000/oxidized/node/show/'."$zbx_hostname
If node not found , oxidized have error and memory leak: 

Oct 16 13:53:39 nbm oxidized: 2017-10-16 13:53:39 - Oxidized::NodeNotFound - unable to find '%NODE-NAME%':
Oct 16 13:53:39 nbm oxidized: /usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/nodes.rb:92:in `find_node_index'
Oct 16 13:53:39 nbm oxidized: /usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/nodes.rb:54:in `block in show'
Oct 16 13:53:39 nbm oxidized: /usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/nodes.rb:127:in `synchronize'
Oct 16 13:53:39 nbm oxidized: /usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/nodes.rb:127:in `with_lock'
Oct 16 13:53:39 nbm oxidized: /usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/nodes.rb:53:in `show'
Oct 16 13:53:39 nbm oxidized: /usr/local/share/gems/gems/oxidized-web-0.9.2/lib/oxidized/web/webapp.rb:117:in `block in <class:WebApp>'
Oct 16 13:53:39 nbm oxidized: /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `call'
Oct 16 13:53:39 nbm oxidized: /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `block in compile!'
Oct 16 13:53:39 nbm oxidized: /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `[]'
Oct 16 13:53:39 nbm oxidized: /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
Oct 16 13:53:39 nbm oxidized: /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:994:in `route_eval'
Oct 16 13:53:39 nbm oxidized: /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
Oct 16 13:53:39 nbm oxidized: /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1015:in `block in process_route'
Oct 16 13:53:39 nbm oxidized: /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `catch'
Oct 16 13:53:39 nbm oxidized: /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `process_route'
Oct 16 13:53:39 nbm oxidized: /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:973:in `block in route!'
Oct 16 13:53:39 nbm oxidized: /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `each'
Oct 16 13:53:39 nbm oxidized: /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `route!'
Oct 16 13:53:39 nbm oxidized: /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1085:in `block in dispatch!'
Oct 16 13:53:39 nbm oxidized: /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
Oct 16 13:53:39 nbm oxidized: /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
Oct 16 13:53:39 nbm oxidized: /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
Oct 16 13:53:39 nbm oxidized: /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1082:in `dispatch!'
Oct 16 13:53:39 nbm oxidized: /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `block in call!'
Oct 16 13:53:39 nbm oxidized: /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
Oct 16 13:53:39 nbm oxidized: /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
Oct 16 13:53:39 nbm oxidized: /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
Oct 16 13:53:39 nbm oxidized: /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `call!'
Oct 16 13:53:39 nbm oxidized: /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:895:in `call'
Oct 16 13:53:39 nbm oxidized: /usr/local/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
Oct 16 13:53:39 nbm oxidized: /usr/local/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
Oct 16 13:53:39 nbm oxidized: /usr/local/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
Oct 16 13:53:39 nbm oxidized: /usr/local/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
Oct 16 13:53:39 nbm oxidized: /usr/local/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
Oct 16 13:53:39 nbm oxidized: /usr/local/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
Oct 16 13:53:39 nbm oxidized: /usr/local/share/gems/gems/rack-1.6.8/lib/rack/nulllogger.rb:9:in `call'
Oct 16 13:53:39 nbm oxidized: /usr/local/share/gems/gems/rack-1.6.8/lib/rack/head.rb:13:in `call'
Oct 16 13:53:39 nbm oxidized: /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/show_exceptions.rb:25:in `call'
Oct 16 13:53:39 nbm oxidized: /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:182:in `call'
Oct 16 13:53:39 nbm oxidized: /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:2013:in `call'
Oct 16 13:53:39 nbm oxidized: /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `block in call'
Oct 16 13:53:39 nbm oxidized: /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1787:in `synchronize'
Oct 16 13:53:39 nbm oxidized: /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `call'
Oct 16 13:53:39 nbm oxidized: /usr/local/share/gems/gems/rack-1.6.8/lib/rack/urlmap.rb:66:in `block in call'
Oct 16 13:53:39 nbm oxidized: /usr/local/share/gems/gems/rack-1.6.8/lib/rack/urlmap.rb:50:in `each'
Oct 16 13:53:39 nbm oxidized: /usr/local/share/gems/gems/rack-1.6.8/lib/rack/urlmap.rb:50:in `call'
Oct 16 13:53:39 nbm oxidized: /usr/local/share/gems/gems/rack-1.6.8/lib/rack/builder.rb:153:in `call'
Oct 16 13:53:39 nbm oxidized: /usr/local/share/gems/gems/puma-3.10.0/lib/puma/configuration.rb:225:in `call'
Oct 16 13:53:39 nbm oxidized: /usr/local/share/gems/gems/puma-3.10.0/lib/puma/server.rb:605:in `handle_request'
Oct 16 13:53:39 nbm oxidized: /usr/local/share/gems/gems/puma-3.10.0/lib/puma/server.rb:437:in `process_client'
Oct 16 13:53:39 nbm oxidized: /usr/local/share/gems/gems/puma-3.10.0/lib/puma/server.rb:301:in `block in run'
Oct 16 13:53:39 nbm oxidized: /usr/local/share/gems/gems/puma-3.10.0/lib/puma/thread_pool.rb:120:in `call'
Oct 16 13:53:39 nbm oxidized: /usr/local/share/gems/gems/puma-3.10.0/lib/puma/thread_pool.rb:120:in `block in spawn_thread'

**Comment by wk** [comment]
This is an older issue, and Oxidized has seen several new releases since it has been posted. If this is still relevant, please re-attempt this on a more recent (0.24.0) version and update the issue with your findings.
