### ISSUE TITLE
Juniper SRX Config backup not working

### ISSUE THREAD

**Issue by xq1xq1xq1** [ytti/oxidized#1068]
I am not sure if this is the correct place to ask this question, if not then please educate me.

I have installed oxidized (BTW this project is not a silly attempt at rancid but a much superior one :-) )

It works great for my ubitiqui edgeswitch and cisco switches but for some reason it's having issues with my Juniper SRX210 running junos.

My Model Map is:

model_map:
  cisco: ios
  juniper: junos

My router.db file is:
.
.
.
172.23.74.200:juniper:uuuu:xxxx::

The contents of the juniper config is:

show: Command not found.
display: Command not found.
# show: Command not found.
# show: Command not found.
# show: Command not found.
# show: Command not found.

Any suggestions on how to get juniper backing up properly?

**Comment by xq1xq1xq1** [comment]
Found Gitter was the forum for support - posted and resolved issue

**Comment by sincere32** [comment]
don't use "root"
