### ISSUE TITLE
Sudo for Cumulus Linux?

### ISSUE THREAD

**Issue by theherodied** [ytti/oxidized#1069]
For Cumulus Linux is it possible to pass sudo -i or something similar at the beginning like enable for Cisco? 

When running oxidized against a Cumulus Linux switch with a SSH user other than root will result in this section from Cumulus.rb saying you must be root. 

cfg += add_comment 'ACL'
cfg += cmd 'iptables -L -n'

Or does someone know of a better option to get the iptables list?

**Comment by wk** [comment]
Closed by #1532
