### ISSUE TITLE
HP Procurve stacking

### ISSUE THREAD

**Issue by stiltzkin10** [ytti/oxidized#1070]
Hello,

Trying to backup a HP Procurve with two members in a stack. Seems like Oxidized gets stuck during login when selecting member stack:

```
Enter switch number to connect to or <CR>:

  SN MAC Address   System Name      Device Type           Status                   
  -- ------------- ---------------- --------------------- -------------------------
  0  002347-457980 SW0         ProCurve 2810-48G    Commander Up             
  1  002347-459880 SW1      ProCurve 2810-48G    Member Up 
```               

I tried to add:  

```
expect /Enter switch number to connect to or <CR>:/ do
    send "\n"
    ""
end
```

to procurve.rb without success.

**Comment by laf** [comment]
What does just pressing enter normally do at that prompt?

Have you enabled debugging to get more info?

**Comment by stiltzkin10** [comment]
Pressing enter takes you to the stack commander (which is what you want).

The log file is full of:

` raised Timeout::Error with msg "timed out while waiting for more data"`

**Comment by laf** [comment]
Can you post the debug log pls.

**Comment by stiltzkin10** [comment]
OK, did some more troubleshooting. This solves the problem:

```
expect /Enter switch number/ do
    send "\n"
    ""
end
```

I will create a pull request for this.

**Comment by pv2b** [comment]
Hi, @stiltzkin10 

I'm just onboarding a bunch of switches into Oxidized, and I already know I'm going to run into this particular issue. Did you ever end up creating a PR for this? I wasn't able to find one by searching.

**Comment by laf** [comment]
It doesn't look it ever made it in. @stiltzkin10 would be ace if you could submit this fix.

**Comment by stiltzkin10** [comment]
Sorry for the delay everyone. I created pull request #1108
