### ISSUE TITLE
Syslog change detection LibreNMS

### ISSUE THREAD

**Issue by chasgames** [ytti/oxidized#1078]
Hi everyone,

I have syslog working on LibreNMS, and Oxidized is backing up config at my set interval.

However I can't get the syslog change detection working in Oxidized, I've set  "use_syslog: true" and restarted both librenms and oxidized, made a change on the switch, but oxidized does not run a config backup.

Any Ideas?
Thanks

**Comment by laf** [comment]
If you are using the in built syslog collector in LibreNMS then you need to configure the hooks: https://docs.librenms.org/#Extensions/Syslog/#external-hooks

If not, what syslog collector are you using?

**Comment by chasgames** [comment]
Thanks @laf perfect.

I added
$config['enable_syslog_hooks'] = 1;

and then the last config line i had to rename ios, to iosxe for my switch, and its working perfectly now.

$config['os']['iosxe']['syslog_hook'][] = Array('regex' => '/%SYS-(SW[0-9]+-)?5-CONFIG_I/', 'script' => '/opt/librenms/scripts/syslog-notify-oxidized.php');

Thanks

**Comment by laf** [comment]
Can we close this then @chasgames?
