### ISSUE TITLE
Issue with "Search in Configs"

### ISSUE THREAD

**Issue by chibi4588** [ytti/oxidized#1080]
I am having an issue upon a new Oxidized deployment when I attempt to use "Search in Configs".  I get an oxidized-web "NoMethodError at /nodes/conf_search, undifined method '[]' nil:NilClass" from file webapp.rb.  

Any thoughts on a remedy??  Thanks much!

Here is the output in the logs:

Puma starting in single mode...
* Version 3.10.0 (ruby 2.0.0-p648), codename: Russell's Teapot
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://127.0.0.1:8787

2017-10-31 16:57:04 - NoMethodError - undefined method `[]' for nil:NilClass:
	/usr/local/share/gems/gems/oxidized-web-0.9.2/lib/oxidized/web/webapp.rb:56:in `block (2 levels) in <class:WebApp>'
	/usr/local/share/gems/gems/oxidized-web-0.9.2/lib/oxidized/web/webapp.rb:53:in `map'
	/usr/local/share/gems/gems/oxidized-web-0.9.2/lib/oxidized/web/webapp.rb:53:in `each'
	/usr/local/share/gems/gems/oxidized-web-0.9.2/lib/oxidized/web/webapp.rb:53:in `block in <class:WebApp>'
	/usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `call'
	/usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `block in compile!'
	/usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `[]'
	/usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
	/usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:994:in `route_eval'
	/usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
	/usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1015:in `block in process_route'
	/usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `catch'
	/usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `process_route'
	/usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:973:in `block in route!'
	/usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `each'
	/usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `route!'
	/usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1085:in `block in dispatch!'
	/usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
	/usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
	/usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
	/usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1082:in `dispatch!'
	/usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `block in call!'
	/usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
	/usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
	/usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
	/usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `call!'
	/usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:895:in `call'
	/usr/local/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	/usr/local/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/usr/local/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
	/usr/local/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/usr/local/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/usr/local/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
	/usr/local/share/gems/gems/rack-1.6.8/lib/rack/nulllogger.rb:9:in `call'
	/usr/local/share/gems/gems/rack-1.6.8/lib/rack/head.rb:13:in `call'
	/usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/show_exceptions.rb:25:in `call'
	/usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:182:in `call'
	/usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:2013:in `call'
	/usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `block in call'
	/usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1787:in `synchronize'
	/usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `call'
	/usr/local/share/gems/gems/rack-1.6.8/lib/rack/urlmap.rb:66:in `block in call'
	/usr/local/share/gems/gems/rack-1.6.8/lib/rack/urlmap.rb:50:in `each'
	/usr/local/share/gems/gems/rack-1.6.8/lib/rack/urlmap.rb:50:in `call'
	/usr/local/share/gems/gems/rack-1.6.8/lib/rack/builder.rb:153:in `call'
	/usr/local/share/gems/gems/puma-3.10.0/lib/puma/configuration.rb:225:in `call'
	/usr/local/share/gems/gems/puma-3.10.0/lib/puma/server.rb:605:in `handle_request'
	/usr/local/share/gems/gems/puma-3.10.0/lib/puma/server.rb:437:in `process_client'
	/usr/local/share/gems/gems/puma-3.10.0/lib/puma/server.rb:301:in `block in run'
	/usr/local/share/gems/gems/puma-3.10.0/lib/puma/thread_pool.rb:120:in `call'
	/usr/local/share/gems/gems/puma-3.10.0/lib/puma/thread_pool.rb:120:in `block in spawn_thread'

**Comment by laf** [comment]
Please post your config.

**Comment by chibi4588** [comment]
Iaf,
Thanks.  Here is the config (scrubbed).

---
username: admin
password: xxxxxxxx
model: cisco
interval: 604800
use_syslog: false
debug: false
threads: 30
timeout: 35
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 127.0.0.1:8787
next_adds_job: false
vars:  {}
groups:
  XXX_XXXX_Routing_Backbone:
    vars:
      enable: xxxxxxx
models:
  eos:
    vars:
      enable: true
  powerconnect:
    vars:
      enable: XXXXX
pid: /home/oxidized/.config/oxidized/pid
input:
  default: ssh, telnet
  debug: false
  ssh:
    secure: false
output:
  default: file
  file:
    directory: /home/oxidized/deviceconfigs/*groups
source:
  default: csv
  csv:
    file: /home/oxidized/.config/oxidized/router.db
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
      group: 2
      username: 3
      password: 4
    gpg: false
model_map:
   cisco: ios

**Comment by laf** [comment]
Are the configs themselves being stored ok?

**Comment by chibi4588** [comment]
Yeah, its is just the "Search in Configs" that is broken... and I can't for the life of me figure out why (not that I am a Ruby guy by any stretch).  This is my 3rd deployment of Ox, all with the same config file.  The only thing that I see has changed between the previous 2* deployments, is the version of Puma was updated from 3.9.1 to 3.4.0.  Not sure if this would have any influence, but again, this is the only difference.

**Comment by chibi4588** [comment]
If anyone has any thoughts... would be greatly appreciated. 

Thanks!

**Comment by laf** [comment]
Maybe try Puma 3.9.1 again to see?

**Comment by laf** [comment]
No further response provided so this issue is being closed.

I've moved this to oxidized-web in the meantime.
