### ISSUE TITLE
Problem using GPG

### ISSUE THREAD

**Issue by iscieszka** [ytti/oxidized#1082]
When running oxidized with gpg enabled I receive the following error:

`undefined` method `new' for nil:NilClass
`/usr/local/rvm/gems/ruby-2.1.2/gems/oxidized-0.20.0/lib/oxidized/nodes.rb:15:in` `block in load': `undefined` method `new' for nil:NilClass (NoMethodError)

with gpg set as false oxidized runs with no problem.

Here is my config:

```---
username: admin
password: password
model: ios
interval: 300
use_syslog: false
debug: true
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 127.0.0.1:8888
next_adds_job: false
vars: {}
groups: {}
models: {}
pid: "~/.config/oxidized/pid"
input:
  default: telnet, ssh
  debug: true
  ssh:
    secure: true
output:
  default: git
  git:
    user: Oxidized
    email: o@example.com
    repo: "/var/lib/oxidized/devices.git"
source:
  default: csv
  csv:
    gpg: true
    gpg_password: 's3cret'
    file: "~/.config/oxidized/router.db.gpg"
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
      username: 2
      password: 3
model_map:
  cisco: ios
  juniper: junos
```

I encrypted the file using gpg -c and can decrypt it using gpg -d

I am a little confused on how to get the encryption to work properly. Thanks.

**Comment by laf** [comment]
Have you checked the debug logs?

Is gpgme installed? `ruby install gpgme`?

**Comment by iscieszka** [comment]
Forgot to mention I am running on Freebsd 11.1-RELEASE. I had gpgme installed but not through ruby. I installed it and it seems Gpgme is running, but I now crash with 
``decrypt_verify': No data (GPGME::Error::NoData)`
Am I formatting the file path wrong?

**Comment by laf** [comment]
The path should be fine assuming it's correct and the file exists in that location.

**Comment by iscieszka** [comment]
the path as well as the file should be correct. Could it be a problem with how i encrypted the file? I used gpg -c to encrypt it.

**Comment by laf** [comment]
@elmobp is this something you could help with?

**Comment by elmobp** [comment]
What version of gpg are you using?

**Comment by iscieszka** [comment]
I am running 2.2.1

**Comment by elmobp** [comment]
Here is a diff give that a shot? If it works Ill submit another PR I wonder why mine is working locally though :(

```
diff --git a/lib/oxidized/source/csv.rb b/lib/oxidized/source/csv.rb
index c1e310a..39111bd 100644
--- a/lib/oxidized/source/csv.rb
+++ b/lib/oxidized/source/csv.rb
@@ -21,9 +21,9 @@ class CSV < Source
   def load
     nodes = []
     file = File.expand_path(@cfg.file)
-    file = if @cfg.gpg?
+    if @cfg.gpg?
       crypto = GPGME::Crypto.new password: @cfg.gpg_password
-      crypto.decrypt(file).to_s
+      file = crypto.decrypt(file).to_s
     else
       open(file)
     end  
```

See how you go?

**Comment by iscieszka** [comment]
Gave the diff a shot but still no good. I keep getting the same error:

/usr/local/rvm/gems/ruby-2.1.8/gems/gpgme-2.0.14/lib/gpgme/ctx.rb:435:in `decrypt_verify': No data (GPGME::Error::NoData)

how did you set up the encrypted router.db file maybe I am missing something there?

**Comment by laf** [comment]
Did you rebuild the ruby gem after applying the patch?

**Comment by iscieszka** [comment]
I applied the patch, tried running and came up with same error. After that I rebuilt with same error and lastly did a clean reinstall of rvm, ruby and oxidized but always come to the same error.

**Comment by laf** [comment]
You need to build the ruby gem manually from git and apply this patch. The docs show you how to do this.

**Comment by iscieszka** [comment]
I built the gem manually from git and applied the patch but still get the same error.

**Comment by iscieszka** [comment]
So I built a CentOS vm and did the same thing on it and I am running into the same error. Am I supposed to be encrypting the router.db file in a specific way or does gpg -c router.db work fine?

**Comment by laf** [comment]
Out of interest how are you building the new gem and installing it?

**Comment by iscieszka** [comment]
for CentOS i followed the documentation first:

RHEL 7 / CentOS 7 will work out of the box with the following package list:

yum install cmake sqlite-devel openssl-devel libssh2-devel ruby gcc ruby-devel
Now let's install oxidized via Rubygems:

gem install oxidized
gem install oxidized-script oxidized-web

and came up with the same error. I then removed all the gems and built from git:

git clone https://github.com/ytti/oxidized.git
cd oxidized/
gem build *.gemspec
gem install *.gem

**Comment by iscieszka** [comment]
also got the same error second time around

**Comment by laf** [comment]
So you're missing adding the patch :)

```bash
git clone ytti/oxidized.git
cd oxidized/
wget https://gist.githubusercontent.com/laf/d0adb749b96b12de5c73f6575087ee74/raw/b2d18588e7c60b898c7632e3ee279c8c2f8448a9/gistfile1.txt
git apply gistfile1.txt
gem build *.gemspec
gem install *.gem
```

**Comment by iscieszka** [comment]
Applied the patch just as you said but still the same error. :(

**Comment by laf** [comment]
ok well hopefully @elmobp can shed some light.

**Comment by elmobp** [comment]
Ill see if I can get to it tonight been very busy!

**Comment by elmobp** [comment]
```
diff --git a/lib/oxidized/source/csv.rb b/lib/oxidized/source/csv.rb
index c1e310a..27cb49e 100644
--- a/lib/oxidized/source/csv.rb
+++ b/lib/oxidized/source/csv.rb
@@ -21,9 +21,9 @@ class CSV < Source
   def load
     nodes = []
     file = File.expand_path(@cfg.file)
-    file = if @cfg.gpg?
+    if @cfg.gpg?
       crypto = GPGME::Crypto.new password: @cfg.gpg_password
-      crypto.decrypt(file).to_s
+      file = crypto.decrypt(File.open(file)).to_s
     else
       open(file)
     end 
```

**Comment by laf** [comment]
Thanks very much @elmobp :)

@iscieszka Can you test again using this patch pls.

**Comment by iscieszka** [comment]
Awesome that seems to have worked! Oxidized seems to be running now and decrypting the file. 

My only concern is that when running oxidized in debug mode it shows the node value of 's3cret'. Is there a way to hide that? Or a way of encrypting the config file?

**Comment by laf** [comment]
Node value? You mean the passords / enable details or something the config outputs?

**Comment by iscieszka** [comment]
specifically when starting up oxidized it shows this:
 
 DEBUG -- : node.rb: resolving node key 'password', with passed global value of '' and node value 's3cret'

**Comment by laf** [comment]
It's only done when debug is enabled but no, you can't stop it happening at that point.

**Comment by iscieszka** [comment]
That's all good. Thanks for the help @laf @elmobp !

**Comment by laf** [comment]
@elmobp would you like to submit a pull request with that patch now it's confirmed working?

**Comment by elmobp** [comment]
Sure will get to it later today!

**Comment by iscieszka** [comment]
Hey, continuing off this post, when I now start up oxidized for the first time it asks for a password

I, [2017-11-15T15:06:59.155688 #36487]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
Enter passphrase

Passphrase:


If I input it it runs fine. When i stop it and start it again it does not ask for one. Should it do that?

**Comment by iscieszka** [comment]
Actually, I just tested this. Its not picking up the password from the config file, rather it uses the one I have to type in. I changed the config file to state gpg_password: 'supers3cret' while keeping the pass on the file as 's3cret'. Ran oxidized and it prompted for pass which I gave as 's3cret' and it is running. If i kill it and restart it, oxidized does not ask for a pass but runs with the one I gave it earlier.

**Comment by iscieszka** [comment]
Ran into another bug regarding this. When I change the the config file from gpg: true to gpg: false i get this 

I, [2017-11-15T17:27:28.648932 #1251]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
D, [2017-11-15T17:27:28.649015 #1251] DEBUG -- : resolving DNS for /root/.config/oxidized/router.db.gpg...
D, [2017-11-15T17:27:28.649040 #1251] DEBUG -- : IPADDR
E, [2017-11-15T17:27:28.651084 #1251] ERROR -- : node {:name=>"/root/.config/oxidized/router.db.gpg", :model=>nil, :username=>nil, :password=>nil} is not resolvable, raised Resolv::ResolvError with message 'no address for /root/.config/oxidized/router.db.gpg'
I, [2017-11-15T17:27:28.651117 #1251]  INFO -- : lib/oxidized/nodes.rb: Loaded 0 nodes
F, [2017-11-15T17:27:28.651145 #1251] FATAL -- : Oxidized crashed, crashfile written in /root/.config/oxidized/crash
source returns no usable nodes
/usr/local/lib/ruby/gems/2.3/gems/oxidized-0.21.0/lib/oxidized/core.rb:15:in `initialize': source returns no usable nodes (Oxidized::Core::NoNodesFound)
        from /usr/local/lib/ruby/gems/2.3/gems/oxidized-0.21.0/lib/oxidized/core.rb:4:in `new'
        from /usr/local/lib/ruby/gems/2.3/gems/oxidized-0.21.0/lib/oxidized/core.rb:4:in `new'
        from /usr/local/lib/ruby/gems/2.3/gems/oxidized-0.21.0/lib/oxidized/cli.rb:12:in `run'
        from /usr/local/lib/ruby/gems/2.3/gems/oxidized-0.21.0/bin/oxidized:9:in `<top (required)>'
        from /usr/local/bin/oxidized:23:in `load'
        from /usr/local/bin/oxidized:23:in `<main>'

**Comment by laf** [comment]
What's changed from when you confirmed it worked?

**Comment by iscieszka** [comment]
The first time I confirmed it worked it did not prompt me for the password. The next day it did.
I also tried to run oxidized with an unencypted router.db file but as soon as I did that it gave me the resloving DNS for /root/.config/oxidized/router.db problem.

**Comment by laf** [comment]
When it was confirmed as working, did it load the nodes in the webui and start backing up config?

The reason I think your un-encrypted one didn't work was because you still pointed the db at your encrypted file.

**Comment by iscieszka** [comment]
Yes, it loaded the nodes, and I pasted the wrong info, thats my bad. I tried with both router.db and router.db.gpg to check if it would worked. It gave me the same problem for both which i switched gpg to false.

**Comment by iscieszka** [comment]
since oxidized is not reading the gpg_password from the config my guess is this is the reason the original problem of this thread came up.

**Comment by laf** [comment]
I've tested the proposed fix and it works as expected.

The issue with gpg_password not being read is because you need to run gpg v1: https://github.com/ueno/ruby-gpgme/issues/11

The initial issue raised, I can replicate that and it's purely because gpgme isn't installed. The issues after that are due to the code from what I can see but the patch fixes that.

**Comment by iscieszka** [comment]
I have oxidized working properly now, the issue with the password can be solved if using GPG v2.1>= by adding the line:

`allow-loopback-pinentry`
to ~/.gnupg/gpg-agent.conf

and another one:

`pinentry-mode loopback`
to ~/.gnupg/gpg.conf

**Comment by laf** [comment]
@iscieszka working correctly with the patch or without?

**Comment by iscieszka** [comment]
With. Patch is good

**Comment by laf** [comment]
The patch broke non-gpg csv source so that's been fixed but breaks gpg again.

**Comment by laf** [comment]
@elmobp Any chance you can take another look at this? The patch broke non-gpg csv sources so I had to revert the change.
