### ISSUE TITLE
Removed a node from router.db, but oxidized still makes attempts

### ISSUE THREAD

**Issue by jlixfeld** [ytti/oxidized#1083]
Is there something I need to do to make oxidized re-read the router.db file if I make a change to it (ie: remove a device)?  A full oxidized reload seems a little heavy handed, so I'm hopeful there's a simple API call or something?

I tried to find some comprehensive API docs, but I couldn't find anything definitive.

Thanks!

**Comment by laf** [comment]
Have you clicked reload in the webui?

**Comment by jlixfeld** [comment]
I should have been more clear, sorry.  I was looking for a CLI method so I could automate the re-read when the router.db is changed by my backend.

**Comment by laf** [comment]
https://github.com/ytti/oxidized/blob/master/extra/auto-reload-config.runit

**Comment by jlixfeld** [comment]
Perfect!

I notice that is the same call as what is listed in README.md.  Is that considered the definitive list of Restful API calls then, or is it elsewhere?

**Comment by wk** [comment]
@jlixfeld unfortunately a definitive list does not currently exist, see #844. Closing this issue as resolved since the subject question appears to be addressed.
