### ISSUE TITLE
Backup cisco ASA - no_connection

### ISSUE THREAD

**Issue by kletteraffe11** [ytti/oxidized#1098]
Hi, 

thanks for this great tool! Everything works perfectly fine except for the backup of the ASA Firewall.

I'm using `asa` as os type in my router.db. Looking at the ssh logs i can see the connect is working fine. 

```
Type help or '?' for a list of available commands.
bb> enable
Password: ***********
bb# terminal pager 0
bb# show mode
Security context mode: single
bb# show version
```

At some point the process of getting the config just stops. The webinterface's status for the device `no_connection`. Is this a timeout problem? The configuration ist pretty big.

Thanks for the help.

**Comment by laf** [comment]
You should enable debug and post the output from the logs.

May also be worth increasing the timeout although 'pretty big' doesn't give us an idea on how big it is

**Comment by kletteraffe11** [comment]
Sorry for not providing logs. 

Increasing the timeout to 40s did the job. A full config is 1235 lines big.

**Comment by laf** [comment]
> Increasing the timeout to 40s did the job. A full config is 1235 lines big.

Odd, we have timeout set to 20s and config spanning ~3000 lines. Are the devices quite remote from the oxidized install as ours have little latency.

**Comment by kletteraffe11** [comment]
They are on the same network in the same location. No VPN or anything in between, just the routing instance.
