### ISSUE TITLE
Panos (Palo alto): Configuration files unusable for restores

### ISSUE THREAD

**Issue by pv2b** [ytti/oxidized#1102]
The current Panos model outputs configuration in a "human readable" format. This is semi-useful for diffing and auditing (although the "set" output is probably better, see PR #1101)

However, it is completely impossible to load a config file in this format on a PAN OS device, meaning that what oxidized is doing is useless for "backup" purposes (only usable for configuration auditing/logging/change tracking purposes).

Some discussion on this can be found here: https://blog.webernetz.net/palo-alto-save-load-config-through-cli/

Ideally, what should be happening instead is that Oxidized should do an XML export of the configuration file and store it. This can be done through the HTTP API. This probably needs to be a completely seperate module as well... since both output in "readable" formats and "XML" format is usable for different purposes.

It's also possible to output in XML format if using the patch in PR #1101, however, I do not know if this XML format is "loadable" in the firewall... or if the better approach is to use the sanctioned HTTP APIs.

**Comment by pv2b** [comment]
It would seem this is a dupe of #440. Oops. Posted the issue too soon. Can this be merged in somehow?

**Comment by laf** [comment]
It can't be merged, please post your comments in #440.
