### ISSUE TITLE
oxidized-web fails to install 

### ISSUE THREAD

**Issue by raisullip** [ytti/oxidized#1112]
looks like oxidized-web rack-test requires Ruby version >= 2.2.2. even when installing old versions 

[root@default-centos-72 ~]# gem install oxidized-web -v 0.0.1
Fetching: rack-2.0.3.gem (100%)
ERROR:  Error installing oxidized-web:
	rack requires Ruby version >= 2.2.2.

**Comment by laf** [comment]
Please post this in https://github.com/ytti/oxidized-web
