### ISSUE TITLE
Problème installation oxidized sur UBUNTU

### ISSUE THREAD

**Issue by btssio77** [ytti/oxidized#1114]
Bonjour,

Je suis actuellement en BTS SIO option Système infrastructure et réseau, mais essayant d'installer oxidized sur ubuntu 17.1, je tombe sur différent message d'erreur.

J'aimerais beaucoup avoir de l'aide

Merci

**Comment by laf** [comment]
Can you please post in english.

**Comment by btssio77** [comment]
Hello,

I am currently in BTS SIO option Infrastructure and Network System, but trying to install oxidized on 17.1 ubuntu, I come across different error message.

I would love to have help

Thank you

**Comment by laf** [comment]
What error message?

**Comment by btssio77** [comment]
Permission denied @ dir_s_mkdir - /home/oxidized
/usr/lib/ruby/2.3.0/fileutils.rb:253:in `mkdir': Permission denied @ dir_s_mkdir - /home/oxidized (Errno::EACCES)
        from /usr/lib/ruby/2.3.0/fileutils.rb:253:in `fu_mkdir'
        from /usr/lib/ruby/2.3.0/fileutils.rb:227:in `block (2 levels) in mkdir_p'
        from /usr/lib/ruby/2.3.0/fileutils.rb:225:in `reverse_each'
        from /usr/lib/ruby/2.3.0/fileutils.rb:225:in `block in mkdir_p'
        from /usr/lib/ruby/2.3.0/fileutils.rb:211:in `each'
        from /usr/lib/ruby/2.3.0/fileutils.rb:211:in `mkdir_p'
        from /var/lib/gems/2.3.0/gems/asetus-0.3.0/lib/asetus.rb:128:in `save_cfg'
        from /var/lib/gems/2.3.0/gems/asetus-0.3.0/lib/asetus.rb:60:in `save'
        from /var/lib/gems/2.3.0/gems/asetus-0.3.0/lib/asetus.rb:83:in `create'
        from /var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/config.rb:55:in `load'
        from /var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/cli.rb:24:in `initialize'
        from /var/lib/gems/2.3.0/gems/oxidized-0.21.0/bin/oxidized:9:in `new'
        from /var/lib/gems/2.3.0/gems/oxidized-0.21.0/bin/oxidized:9:in `<top (required)>'
        from /usr/local/bin/oxidized:22:in `load'
        from /usr/local/bin/oxidized:22:in `<main>'

**Comment by laf** [comment]
The user you are starting oxidized up as doesn't have permission to create the relevant directory structure. What user are you starting it up with?

**Comment by btssio77** [comment]
the first user is root

**Comment by laf** [comment]
Are you sure? It's complaining it can't create a dir and I doubt root can't

**Comment by btssio77** [comment]
yes i'm sure

**Comment by btssio77** [comment]
root@ubuntu-am:/etc/apt# oxidized
I, [2017-12-05T11:26:26.555579 #30069]  INFO -- : Oxidized starting, running as pid 30069
I, [2017-12-05T11:26:26.556883 #30069]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
F, [2017-12-05T11:26:26.557270 #30069] FATAL -- : Oxidized crashed, crashfile written in /root/.config/oxidized/crash
No such file or directory @ rb_sysopen - /root/.config/oxidized/router.db
/var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/source/csv.rb:28:in `initialize': No such file or directory @ rb_sysopen - /root/.config/oxidized/router.db (Errno::ENOENT)
        from /var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/source/csv.rb:28:in `open'
        from /var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/source/csv.rb:28:in `load'
        from /var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/nodes.rb:15:in `block in load'
        from /var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/nodes.rb:128:in `synchronize'
        from /var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/nodes.rb:128:in `with_lock'
        from /var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/nodes.rb:10:in `load'
        from /var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/nodes.rb:123:in `initialize'
        from /var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/core.rb:14:in `new'
        from /var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/core.rb:14:in `initialize'
        from /var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/core.rb:4:in `new'
        from /var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/core.rb:4:in `new'
        from /var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/cli.rb:12:in `run'
        from /var/lib/gems/2.3.0/gems/oxidized-0.21.0/bin/oxidized:9:in `<top (required)>'
        from /usr/local/bin/oxidized:22:in `load'
        from /usr/local/bin/oxidized:22:in `<main>'

**Comment by laf** [comment]
That's different error. You haven't created your source file with the devices in it.

**Comment by btssio77** [comment]
Ok so what i do now please ???

**Comment by laf** [comment]
Have you gone through the install docs? For csv source: https://github.com/ytti/oxidized/blob/master/docs/Sources.md#source-csv

**Comment by btssio77** [comment]
Thank you laf i have find the problem i was log at root to launch oxidized ...

**Comment by laf** [comment]
So we can close this now @btssio77 ?
