### ISSUE TITLE
post do issue, output not saved in backup file

### ISSUE THREAD

**Issue by DenisKlimek** [ytti/oxidized#1117]
Dear all,
we're trying to add support for a new device in Oxidized from ATMedia for Layer 2 decryption devices.
This device has 2 modes: A classic admin mode for the running config and a second mode called "crypt" for the cryptographic settings. To enter this mode you need to "enable" it trough "crypt enable" and with "show config" you can see now the crypto settings. This works fine for now but the output from this is not getting saved into the backup file. Do you have any ideas why?
```

class ATMEDIA < Oxidized::Model

  prompt /^.*\[?.*\]?\S:\s\>?/

  cmd 'show version' do |cfg|
    comment cfg
  end

  cmd 'show config' do |cfg|
    cfg
  end

  post do
    if vars :enable
      cmd 'crypt enable'
      send vars(:enable) + "\n"
      out = []
      cmd '\nshow config' do |cfg|
        out << cfg
        out << ".\n"
      end
      out.join "\n"
      cmd 'exit'
    end
  end

  cfg :ssh do
    pre_logout 'exit'
  end

end
```

I also tried without the variable 'out' method, but this does not work as well.

**Comment by laf** [comment]
You should enable debugging as per the readme and pastebin the log output for this device.

Does the show config after running crypt enable give you just the crypt config or all the config?

**Comment by DenisKlimek** [comment]
Attached the debug from the oxidized process itself: https://pastebin.com/U294XG9K
and a debug from the SSH session between oxidized and the device: https://pastebin.com/1Dh6ZSvR

And I did a small modification back to the "without" out variable solution: 

```
class ATMEDIA < Oxidized::Model

  prompt /^.*\[?.*\]?\S:\s\>?/

  cmd 'show version' do |cfg|
    comment cfg
  end

  cmd 'show config' do |cfg|
    cfg
  end

  post do
    if vars :enable
      cmd 'crypt enable'
      send vars(:enable) + "\n"
      cmd "\n"
      cmd 'show config' do |cfg|
        cfg
      end
      cmd 'exit'
    end
  end

  cfg :ssh do
    pre_logout 'exit'
  end

end
```

**Comment by DenisKlimek** [comment]
After some hours and some luck I saw that the missing lines has a carriage return on each new line which looks likes that this is causing the problem.

I tried to strip and gsub the lines but anytime without effect i.e.

```
  post do
    if vars :enable
      cmd 'crypt enable'
      send vars(:enable) + "\n"
      cmd "\n"
      cmd 'show config' do |cfg|
        clean cfg
      end
      cmd 'exit'
    end
  end

  cfg :ssh do
    pre_logout 'exit'
  end

  def clean cfg
    out = []
    cfg.each_line do |line|
      out = line.strip + "\n"
OR
      out = line.gsub!(/(\r|\n)/m,"")
    end
  end
```

and



This is the raw output file. I zipped it so we do not loose any characters during formatting.
https://openload.co/f/BZKg9ZcYaIE/ssh-debug.zip
