### ISSUE TITLE
We couldn’t retrieve the device information from Oxidized - IOSXE 

### ISSUE THREAD

**Issue by Majesticops** [ytti/oxidized#1118]
I have quite a devices added to Librenms as well oxidized. Oxidized is pulling the configurations for NXOS, IOS and HP. I have come across 2 devices that is running Cisco IOS-XE and oxidized is giving me the following error: We couldn’t retrieve the device information from Oxidized

**Comment by Majesticops** [comment]
Is there a debug command I can run?

**Comment by laf** [comment]
You could format all of this config / debug out you've posted or use pastebin. It's just a wall of text right now.

Is this LibreNMS giving this message and if so, can you retrieve the config from the oxidized webui? What's your LibreNMS oxidized config?

**Comment by Majesticops** [comment]
Hi

Yes this is LibreNMS giving me the message:

![image](https://user-images.githubusercontent.com/33343123/33469253-5c87363e-d66a-11e7-98cb-e333dc12545e.png)

LibreNMS config of config.php

![image](https://user-images.githubusercontent.com/33343123/33469262-788d8a04-d66a-11e7-96ab-5ca6b8a3bd52.png)

Oxidized Config

username: smartcollector
password: xxxxxxxxxxxxxx
model: junos
interval: 3600
log: ~/.config/oxidized/log
use_syslog: true
debug: true
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 127.0.0.1:8888
syslogd:
  port: 514
vars: {}
groups:
  use-netops:
    username: netops
    password: "xxxxx"
  use-netadmin:
    username: netadmin
    password: "xxxxx"
  use-mtn:
    username: M3tr0P
    password: "xxxxx"
input:
  default: ssh, telnet
  debug: true
  ssh:
   secure: false
output:
 default: git
 git:
  user: Oxidized
  email: o@example.com
  repo: " /home/librenms/.config/oxidized/default.git"
source:
  default: http
  http:
    url: http://localhost/api/v0/oxidized
    scheme: http
    delimiter: !ruby/regexp /:/
    user: username
    pass: password
    map:
      name: hostname
model: os
      username: username
      password: password
      group: group
    vars_map:
      enable: enable
    headers:
      X-Auth-Token: 'ba21501e18bc564450d3ccc7d50069a7'
model_map:
  cisco: ios
  juniper: juno
  cisco: iosxe

**Comment by Majesticops** [comment]
Did I provide the correct information?

**Comment by Majesticops** [comment]
Is there any other information I need to post?

**Comment by laf** [comment]
> When i check oxidized web interface I do not see the devices in the list.

Then the device isn't having it's config backed up so can't be displayed. Either this device is one that's excluded by LibreNMS as a default or you've elected to ignore the device specifically, the OS or the device type.

You can run a curl against the LibreNMS api to see what devices are returned.

**Comment by Majesticops** [comment]
Will provide curl output

**Comment by Majesticops** [comment]
I ran a curl as requested and the device comes up

    {
        "hostname": "10.18.255.1",
        "os": "iosxe"

**Comment by Majesticops** [comment]
I saw this error in the syslog for oxidized

Not sure what to do?

node {:name=>"10.18.255.1", :model=>"iosxe", :username=>nil, :password=>nil, :group=>nil, :vars=>{:enable=>nil}} raised Oxidized::ModelNotFound with message 'iosxe not found for node 10.18.255.1'
--



node {:name=>"10.18.255.1", :model=>"iosxe", :username=>nil, :password=>nil, :group=>nil, :vars=>{:enable=>nil}} raised Oxidized::ModelNotFound with message 'iosxe not found for node 10.18.255.1'
-

**Comment by Majesticops** [comment]
Looks like there is no model for IOSXE when I check here https://github.com/ytti/oxidized/tree/7e6dc8cce71d6e2753a4e865d8bfbcd347fe1f8a/lib/oxidized/model

**Comment by laf** [comment]
Correct, you will need to either create one, someone else has commented you can copy ios.rb to iosxe.rb and update the model names within it and this works, if it does, please submit the new model as a PR.

You could also map iosxe to ios within the oxidized config to get round this but the above is the preferred solution.

**Comment by Majesticops** [comment]
Thanks is worked.

How do I submit a PR for the attached.

Thanks

need to rename to iosxe.rb

[iosxe.txt](https://github.com/ytti/oxidized/files/1562937/iosxe.txt)

**Comment by laf** [comment]
If you fork this repo in github to your own [see here](https://help.github.com/articles/fork-a-repo/), create a new branch [see here](https://help.github.com/articles/creating-and-deleting-branches-within-your-repository/). You can then create a new file in the correct dir and use what you have. Then submit a pull request [see here](https://help.github.com/articles/creating-a-pull-request/)

**Comment by ytti** [comment]
IOS-XE is literally same parser as IOS, it's just running on top of linux instead of being self-booting. I see no point having separate models for IOS-XE and IOS.

**Comment by Majesticops** [comment]
Fair shout, how do I configure oxidized to avoid this error 
 
node {:name=>"10.18.255.1", :model=>"iosxe", :username=>nil, :password=>nil, :group=>nil, :vars=>{:enable=>nil}} raised Oxidized::ModelNotFound with message 'iosxe not found for node 10.18.255.1

**Comment by ytti** [comment]
Map iosxe to ios or set the model to ios?

**Comment by laf** [comment]
@ytti The issue with mapping iosxe to ios is that this needs to be documented and then people need to read and implement those. That doesn't happen a lot of the time so in my experience and opinion, we should have the default model for iosxe even if it's just a copy of ios. Make it easy for the users.

Your project though so choice is yours :)

**Comment by banananananananana** [comment]
Just ran into this...  :)

This post helped.

**Comment by tomecat** [comment]
It worke'd for me untill upgrade from Cisco IOS-XE 03.18.01a.SP.156-2.SP1a-ext to Cisco IOS XE 16.07.01a. After upgrade i have crush:
https://pastebin.com/kJdKCrgD

**Comment by tomecat** [comment]
It work's fine for me untill upgrade Cisco IOS XE Software, Version 03.18.01a.SP.156-2.SP1a-ext to 
Cisco IOS XE Software, Version 16.07.01a. Now I have crush: https://pastebin.com/kJdKCrgD
I suppose this happens becouse ssh reject. I'm using telnet ot login in that case, but default input is set to ssh.

**Comment by tomecat** [comment]
After set up ssh on device, change oxidized user privilige from 10 to 15 and comment out:
```
#cmd 'show vtp status' do |cfg|
#  cfg.gsub! /^$\n/, ''
#  cfg.gsub! /^/, 'VTP: ' if (!cfg.empty?)
#  comment "#{cfg}\n"
#end
```
oxidized is working again.
