### ISSUE TITLE
Need to Ignore Uptime on Fortigates/FortiOS

### ISSUE THREAD

**Issue by cjhelmkamp** [ytti/oxidized#1119]
The backup for the fortigate is registering the change in uptime and Virus-DB as changes to the config. A little research show that this problem for the uptime was addressed already with the ASAs.

`diff --git a/sac-fw-fortigate b/sac-fw-fortigate index d0ab182..06835f0 100644`
`--- a/sac-fw-fortigate`
`+++ b/sac-fw-fortigate`
`@@ -19,7 +19,7 @@`
 `# Virtual domain configuration: disable  # FIPS-CC mode: disable  # Current HA mode: a-p, master #Cluster uptime: 30 days, 7 hours, 5 minutes, 58 seconds`
`+# Cluster uptime: 30 days, 8 hours, 6 minutes, 3 seconds`
 `# Cluster state change time: N/A`
 `# Branch point: 1486`
 `# Release Version Information: GA`

`diff --git a/sac-fw-fortigate b/sac-fw-fortigate index eb25a67..d0ab182 100644`
`--- a/sac-fw-fortigate`
`+++ b/sac-fw-fortigate`
`@@ -1,7 +1,7 @@`
 `# # COMMAND: get system status`
 `# Version: FortiGate-50E v5.6.2,build1486,170816 (GA) -# Virus-DB: 53.00378(2017-11-30 01:16) -# Extended DB: 53.00378(2017-11-30 01:15)`
`+# Virus-DB: 53.00380(2017-11-30 03:15)`
`+# Extended DB: 53.00380(2017-11-30 03:15)`
 `# IPS-DB: 12.00274(2017-11-29 04:30)`
 `# IPS-ETDB: 0.00000(2001-01-01 00:00)`
 `# APP-DB: 12.00274(2017-11-29 04:30)`
`@@ -19,7 +19,7 @@`
 `# Virtual domain configuration: disable  # FIPS-CC mode: disable  # Current HA mode: a-p, master -# Cluster uptime: 30 days, 6 hours, 5 minutes, 53 seconds`
`+# Cluster uptime: 30 days, 7 hours, 5 minutes, 58 seconds`
 `# Cluster state change time: N/A`
 `# Branch point: 1486`
 `# Release Version Information: GA`

**Comment by jsynack** [comment]
Greeting @cjhelmkamp,

There is a pull request (#1047) that addresses some of these issues with the cluster uptime. 

You will need to have the `remove_secret: true` set in the config for the device or the model / group for fortios since they are implemented in `:secret` method.  

There are some other collateral changes that take place from that PR as well though - these will need a bit of polish.

If you feel comfortable editing the `fortios.rb` file yourself, you can implement just your desired changes with the following additions to the `fortios.rb` file in the `cmd 'get system status'` command block.

```
cfg.gsub! /(Virus-DB|Extended DB|IPS-DB|IPS-ETDB|APP-DB|INDUSTRIAL-DB|Botnet DB|IPS Malicious URL Database).*/, '\\1 <configuration removed>'
cfg.gsub! /(Cluster uptime:).*/, '\\1 <configuration removed>'
```

This should hold you over until the Pull-requests are processed / caught up and a new release is generated.

**Comment by cjhelmkamp** [comment]
Perfect, I have updated my fortios.rb file and it works.

Thanks

**Comment by laf** [comment]
@cjhelmkamp If you could test https://github.com/ytti/oxidized/pull/1047 that would be ace.

**Comment by cjhelmkamp** [comment]
That change did work for me. It also produced a better looking config file than just the show command. I only have the following version of FortiOS running in my environment.

`# Version: FortiGate-50E v5.6.2,build1486,170816 (GA)`

**Comment by cjhelmkamp** [comment]
Might need to add some other fields to ignore.

`diff --git a/sac-fw-fortigate b/sac-fw-fortigate index 16b6f8b..61a29d7 100644`
`--- a/sac-fw-fortigate`
`+++ b/sac-fw-fortigate`
`@@ -208,7 +208,7 @@ config system vdom-link  end  config wireless-controller inter-controller`
`     set inter-controller-mode disable`
`-    set inter-controller-key ENC 7saZC+EJF/r8HvZC7trcPLjrxr7zPBkz36+q7muv4EtEy9VhCEkeeNQ6eUa3ubegKAP8EGap6ac8uuCgRL60iXVhRm8zb1aB9jAfJlaXb/cl8ghMz6s4RyLhb0rhOiJ+qcSDPzTeHNTmjTqzdFP2WHINfqxIrBXUWYSVs9eHoBY7deZ61baAHnEKTqyK6/NednHdQg==`
`+    set inter-controller-key ENC `
`+ wh0cz70tIqsCDMUspQ6yqZyVes05FC6eXJEN2AGPFGgDHFJq4HqIOrM8w6EAm7BsRuU7lm`
`+ 3BmIr1FefuGRq/hZHYRdEqCGWJWW59Gmcub1ZjPha6EB1scY5FF4vK/EKnzoNYQX/iAsZB`
`+ yj+vCUn0VDceoLP5yJJZ3TJWUFTj7xbCm5mifNzdjO7KQV5TOBqOY0o/lQ==`
`     set inter-controller-pri primary`
`     set fast-failover-max 10`
`     set fast-failover-wait 10`
`@@ -16318,8 +16318,8 @@ config router isis`
`     set is-type level-1-2`
`     set auth-mode-l1 password`
`     set auth-mode-l2 password`
`-    set auth-password-l1 ENC 3N3YCknHXGAo8PXFypA9AAmPRbzlDbrthIEJXlGDyqJBYwW7k2IP6kgODMqGD+tML5b0W9Q/g/PInii67SJT3gzxjTrNYdFxa67KoeR3z0Nu7pYuRRJ/ke1rgOSQpH7D4ptpGDflBVgzo+DU/mFd6/WhQYzgsDU0BssiYTuPSP4QOo/O7QjkpGGPD2gjvB+MkYxQ/Q==`
`-    set auth-password-l2 ENC fKS1aAoAM3slaKeWI/gZO6aftI7YsEV/4LS9f80ivFReAmIG7fiT6gtC2q9YO3XgkSiXWLzh7mA3v8vxH1yVs0NrSS0frYKxsKtL2tkkvnfasHBhPzbCfmSRvSFoUhfBUvBS0AGFYZ0OmqVL/uKRA7jEFNJaCxRdnXVhvPRoJBlyxevtfFiv+PHl8bAr3HSHdF3CCw==`
`+    set auth-password-l1 ENC RvkGGnxNgAVLb4FoY7Sjz1SkE8pTdsurYmgqO6/Dbl1IAbYUj1xsKl+8hzR+mVBjEMY5/eebyKWtHxahJL2Ullpj0/oQqfOMuAUy6nhcIAHeBUvOjePPurVXghuUrwmaYYMRq/895R8twS/J6LftA3O9Lh5k/SmXGQjxHWibI7amF0/wGRm7H2b1Bn4GgU9onSba9A==`
`+    set auth-password-l2 ENC `
`+ VtNcGjmaBvgs49ynRzYLmqwvFXNA0lHfHN43WOLCweC5eNksk8HwXgjkMwTwKSwGkId13t`
`+ bVlfgdsAbnTs/CaOTeXcSCJZJcOXweNY7zqlzIMcy8J/2oSFGYoSFOijGLtIPlGoRIJhcj`
`+ UQ8oKrdumZlihxXuKV7GJAuQgfjS/t1EJ3JkwioZKlpjmG3PipHDyzaaNg==`
`     set auth-sendonly-l1 disable`
`     set auth-sendonly-l2 disable`
`     set ignore-lsp-errors disable`
``

**Comment by laf** [comment]
@cjhelmkamp can you test #1047 as it's now been updated.

**Comment by cjhelmkamp** [comment]
The updates work just fine on my fortigates

**Comment by laf** [comment]
Merged in now.
