### ISSUE TITLE
How to delete old versions

### ISSUE THREAD

**Issue by zeki893** [ytti/oxidized#1123]
I've been using oxidized for some time now and it's been working great. Thank you for all the work everybody been putting in.

I'm at version 7700+ on one of my devices and I was wondering is it possible to purge old configs?

**Comment by laf** [comment]
That sounds more like the model needs fixing.

You shouldn't need to purge old configs (why do you want to anyway?). You'd need to rewrite the git history to remove commits which you can do in your git repo but I'm not sure if that will break oxidized's bare repo.

**Comment by laf** [comment]
No further response provided so this issue is being closed.

If you have more information then please respond and we can re-open.

**Comment by zeki893** [comment]
I want to purge old ones because I have over 800+ versions and when I load the versioning page, it takes a good minute or two to load.

**Comment by davama** [comment]
This would be a neat setting to have.

I was trying to work around this by having some script in the background that would basically auto-purge if the repo size was over a GIg or so. (dont remember) but i could not do it using `git` since the repos oxidized creates are bare repos (which is understandable).
Something to the affect of; but works on a non-bare repo:
```
git checkout --orphan temp_branch
git add -A
git commit -am "Purging Old History"
git branch -D master
git branch -m master
```

In my case i just purge the whole thing but delete everything X old would be great!

**Comment by shepherdjay** [comment]
It seems like a git squash would be better as opposed to completely removing the history. Would something like this work? https://osso.nl/blog/squashing-old-git-history/

**Comment by davama** [comment]
@shepherdjay thanks for the link! I was trying to play with it but came across the issue of 'bare' repo. which got me going with my previous posted method

i was playing with my method which purges all history without mercy :stuck_out_tongue_closed_eyes:   but trying to make it work with the bare repo which oxidized creates

I think i got at least that part to work :smile: 
```
cd oxidized/TEST.git
git --work-tree=/home/config/oxidized/TEST.git checkout --orphan newBranch
git --work-tree=/home/config/oxidized/TEST.git commit --quiet -m "Too Large; History has been purged" 
git branch -D master
git branch -m master
```

oxidized was still able to push to the repo TEST.git. 
I am in no way a git expert, all trial and error/google. So if this is not a good way to do it in which it destroys the integrity of the git repo i would gladly love to hear another way. So far, it looks fine as far as my testing goes...

will continue to explore the purge squashing as you mentioned.
Hopefully i find something

**Comment by davama** [comment]
btw...

other way which achieved the same thing but without modifying the commit msg

https://stackoverflow.com/questions/4515580/how-do-i-remove-the-old-history-from-a-git-repository

```
cd oxidized/TEST.git
last_commit=$(git log --pretty=oneline | head -1 | awk '{print $1}')
echo $last_commit > $gitdir/info/grafts
git log --decorate
git filter-branch -- --all
```

I personally needed to have a msg saying what happened. So i didnt go with this option

**Comment by chasgames** [comment]
👍 We too looking for a purge option

**Comment by ytti** [comment]
No such option in GUI, but if someone writes it, we'd of course considering integrating it.

In the mean time, if the changes are _legit_ if you don't have trash or legacy devices, I would never consider removing old versions. I'd keep full history at least for duration of the device's useful life, probably forever. 
Never know when old data is crucial for some analysis.

If the webUI is too slow, I'd say that's the problem that needs addressing, not purging of old versions.

**Comment by davama** [comment]
Just FYI, i've been able to script this up but requires that you DO NOT have oxidized running. Or if you dont want your NMS to alert, you can create a simple "dummy" router.csv db and restart oxidized to use that dummy db instead

In a nutshell, find all git objects that are no longer valid ( YMMV ), i basically said if host is not in DNS then it's no longer valid. So purge from git repo
Here are the git cmds:
```
cd $OXIDIZED_GROUP_DIR
echo "Cleaning up $OXIDIZED_GROUP"
git filter-branch --prune-empty --index-filter "git rm --cached -f --ignore-unmatch $(cat list_of_bad_hosts.txt | sed ':a;N;$!ba;s/\n/ /g')" --tag-name-filter cat -- --all
git update-ref -d refs/original/refs/heads/master
git reflog expire --expire=now --all
git gc --prune=now
git push --set-upstream . master
git push -f .
```

Depending no how large your repo is, it may take a while.
Hope it's useful

-dave

**Comment by chasgames** [comment]
Thanks for comments ytti that makes sense, I was just concerned that my repo is at 1GB and not sure how how gradual it increases yet as its only been running a couple of months. Wasn't sure of the implications of the repo growing , e.g webUI loading, and drop down menus with LibreNMS expanding etc.. My oxidized tab sometimes times-out or takes over 20 seconds to load, which i thought was related to the loading time of oxidized dependent on how much config it has to load. 

Thanks Dave for sharing your purge script

**Comment by devicenull** [comment]
We've found that rugged is not great at creating nice git repositories... if you just `cd /home/oxidized/.config/oxidized/oxidized.git/; /usr/bin/git gc` periodically, it'll dramatically drop the size of your repository.

**Comment by ytti** [comment]
@devicenull does that still happen?https://github.com/ytti/oxidized/commit/d95084059f20c04e109b0843b2ce8cd3c6abf770#diff-fa6347d6853d72d312282cf2ef46cfca should have remedied it

**Comment by bmhughes** [comment]
Yes this still does seem to be happening i'm on 0.27.0 and I've just reduced a 30mb repo down to 2.7mb with `git gc`.

**Comment by Vento96** [comment]
> Just FYI, i've been able to script this up but requires that you DO NOT have oxidized running. Or if you dont want your NMS to alert, you can create a simple "dummy" router.csv db and restart oxidized to use that dummy db instead
> 
> In a nutshell, find all git objects that are no longer valid ( YMMV ), i basically said if host is not in DNS then it's no longer valid. So purge from git repo
> Here are the git cmds:
> 
> ```
> cd $OXIDIZED_GROUP_DIR
> echo "Cleaning up $OXIDIZED_GROUP"
> git filter-branch --prune-empty --index-filter "git rm --cached -f --ignore-unmatch $(cat list_of_bad_hosts.txt | sed ':a;N;$!ba;s/\n/ /g')" --tag-name-filter cat -- --all
> git update-ref -d refs/original/refs/heads/master
> git reflog expire --expire=now --all
> git gc --prune=now
> git push --set-upstream . master
> git push -f .
> ```
> 
> Depending no how large your repo is, it may take a while.
> Hope it's useful
> 
> -dave

Hello,

Can I kindly ask you how to remove git objects based on their date e.g if they are older than 365 days using above script?

Thank you
Kind regards
Jakub

**Comment by davama** [comment]
I would google that and test it.

You have to understand what you are looking to achieve. Are you purging objects >365 days completely or just want to squash the history of said object, but the object remains.

If the former, the above should work, but you would have to figure out how to get the objects >365 into the `list_of_bad_host.txt` file that you quoted.
