### ISSUE TITLE
Issue starting oxidized

### ISSUE THREAD

**Issue by papatango71** [ytti/oxidized#1124]
I am getting the following errors when trying to start oxidized.  

oxidized@nms01-eqch2
[/home/oxidized]$ oxidized
no implicit conversion of String into Integer
/var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/source/http.rb:44:in `dig': no implicit conversion of String into Integer (TypeError)
	from /var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/source/http.rb:44:in `block (2 levels) in load'
	from /var/lib/gems/2.3.0/gems/asetus-0.3.0/lib/asetus/configstruct.rb:21:in `each'
	from /var/lib/gems/2.3.0/gems/asetus-0.3.0/lib/asetus/configstruct.rb:21:in `each'
	from /var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/source/http.rb:42:in `block in load'
	from /var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/source/http.rb:38:in `each'
	from /var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/source/http.rb:38:in `load'
	from /var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/nodes.rb:15:in `block in load'
	from /var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/nodes.rb:128:in `synchronize'
	from /var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/nodes.rb:128:in `with_lock'
	from /var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/nodes.rb:10:in `load'
	from /var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/nodes.rb:123:in `initialize'
	from /var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/core.rb:14:in `new'
	from /var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/core.rb:14:in `initialize'
	from /var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/core.rb:4:in `new'
	from /var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/core.rb:4:in `new'
	from /var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/cli.rb:12:in `run'
	from /var/lib/gems/2.3.0/gems/oxidized-0.21.0/bin/oxidized:9:in `<top (required)>'
	from /usr/local/bin/oxidized:23:in `load'
	from /usr/local/bin/oxidized:23:in `<main>'

Any help to resolve this issue would be greatly appreciated.

**Comment by laf** [comment]
Post your config but it's either:

  - Bad config
  - Bad json from your http source
  - If you are using LibreNMS, you've got a bad token or no access to devices - check with curl manually.

**Comment by papatango71** [comment]
@laf, I am getting the following error from the LibreNMS server:

oxidized@nms01-eqch2
[/home/oxidized/.config/oxidized]$ curl --insecure -H 'X-Auth-Token: 64042c1807ba72f7f905880ac7e63ad4' https://librenms.xxxx.net/api/v0/oxidized
{
    "status": "error",
    "message": "Insufficient privileges"

The API token has not changed since the day I set up Oxidized.  Has there been an update to the API security on LibreNMS..??

**Comment by papatango71** [comment]
@laf, i just found the Announcement for the API update that will enforce user permissions.  We use LDAP for authentication so I will need to have the settings there updated to show the oxidized user as having admin rights for LibreNMS.

I disabled LDAP authentication and the tested with curl and the API worked correctly.

Thank you.
