### ISSUE TITLE
Disabling groups of devices

### ISSUE THREAD

**Issue by KlaasT** [ytti/oxidized#1125]
Hi,

I'm using oxidized with LibreNMS and want to decentralize the setup a bit to reduce the workload for the main server.

I wanted to ask if it is possible to define certain groups in oxidized which should be "disabled" so oxidized won't start working on some device groups.

That would be great. Thanks.

**Comment by laf** [comment]
That's not possible afaik, however we could add support to LibreNMS where you can specify which groups to include / exclude if that helps?

**Comment by KlaasT** [comment]
That would sound interesting :-). I think it would be useful to select devices per poller group in LibreNMS so you can have a distributed poller and a distributed oxidized for scenarios where a poller is behind some kind of NAT gateway.

**Comment by tramontano** [comment]
I'd like that too! Any update ?

**Comment by KlaasT** [comment]
@tramontano I'm afraid I'm unable to understand or write Ruby. So I'm really hoping that someone has an idea how to implement this.
