### ISSUE TITLE
HTML codes / characeters in diff function

### ISSUE THREAD

**Issue by DenisKlimek** [ytti/oxidized#1126]
The diff function shows up with the HTML codes for special characters like " and '. It then shows us `&quot;` and `&apos;` which makes it not possible to copy&paste the configs without post modification. This appears also when viewing the full current configuration instead of downloading them.

**Comment by laf** [comment]
This should have been posted to oxidized-web however I believe it's also a duplicate of ytti/oxidized-web/#42
