### ISSUE TITLE
Invalid Conf Error While restoring conf on Fortinet Firewall

### ISSUE THREAD

**Issue by amitmehtahsr** [ytti/oxidized#1127]
Hi,

I'm successfully able to take the backup of Fortinet Firewall. But it throwing error while restoring conf on the same firewall.
Please help me to fix this.

Firmware Version : v5.4.4,build6003 (GA)

```
{:name=>"172.16.3.236",
 :full_name=>"172.16.3.236",
 :ip=>"172.16.3.236",
 :group=>nil,
 :model=>"FortiOS",
 :last=>
  {:start=>2017-12-08 06:19:14 UTC,
   :end=>2017-12-08 06:20:22 UTC,
   :status=>:success,
   :time=>68.645254089},
 :vars=>nil}

```

![fortinet](https://user-images.githubusercontent.com/24204267/33756589-3d9f5fd2-dc1c-11e7-842a-ff71eef32799.png)

**Comment by laf** [comment]
I'm not really sure this is an oxidized question unless the config being backed up isn't being stored correctly.

**Comment by amitmehtahsr** [comment]
Backup process on oxidized showing "success" status as i have shared earlier. I'm facing this error only for conf which I'm taking using Oxidized. I have also observed that the oxidized adding the extra new lines in conf while taking backup of the firewall. 


```
config port

         
            edit "port1"
            next
            edit "port2"
            next
            edit "port3"
            next
            edit "port4"
            next
            edit "port5"
            next
            edit "port6"
            next
            edit "port7"
            next
            edit "port8"
            next
            edit "port9"
            next
            edit "port10"
            next
            edit "port11"
            next

         
            edit "port12"
            next
            edit "port13"
            next
            edit "port14"
            next
            edit "port15"
            next
            edit "port16"
            next
        end

```

The backup and restore working fine if I'm doing back up and restoring on Fortigate using Fortigate GUI.

**Comment by wk** [comment]
Could you provide a copy of both a Oxidized backup and a backup taken through the Fortigate GUI for the same configuration of the same device? 

It is possible that the GUI restore functionality relies on a particular filename, magic strings, or some additional directives which are generated when the GUI backup is taken, but not when the configuration is simply printed out.
