### ISSUE TITLE
Git output config failing

### ISSUE THREAD

**Issue by Kelman77** [ytti/oxidized#1128]
I am trying to output to a git repository but this fails and the process crashes. When I switch to file output oxidized is able to pull the configuration file ok. The process is run as oxidized which has full file access rights upon the output directories. The git-repo is created if it doesn't exist before the job is run.

The config file is as follows,

```
---
username: username
password: password
model: junos
interval: 3600
use_syslog: true
debug: true
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 127.0.0.1:8000
next_adds_job: false
vars: {}
groups: {}
models: {}
pid: /u01/oxidized/oxidized.pid
input:
  default: ssh, telnet
  debug: false
  ssh:
    secure: false
output:
  default: file
  debug: true
  file:
    directory: "/u01/oxidized/config/"
  git:
    user: Oxidized
    email: recipient@e-maildomain.com
    repo: "/u01/oxidized/git-repo/default.git"
source:
  default: csv
  csv:
    file: /u01/oxidized/.config/oxidized/router.db
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
      ip: 2
      username: 3
      password: 4
    vars_map:
      enable: 5
    gpg: false
hooks:
  email_output:
    type: exec
    events: [post_store, node_fail]
    cmd: '/u01/oxidized-bin/extra/oxidized-report-git-commits ~/gitdir/ | mail -s "Configuration update for ${OX_NODE_NAME}" recipient@e-maildomain.com'
    async: true
    timeout: 120
model_map:
  cisco: ios
  f5: tmos
  checkpoint: gaiaos
```
The routerdb is as follows,

F5-Device:f5:1.1.1.1:UserID:Password:Enable_Password
Checkpoint-FW:checkpoint:UserID:Password:Enable_Password
Cisco-ASA:cisco:UserID:Password:Enable_Password

The crash file is as follows,

--------------------------------------------------
2017-12-11 12:04:31 UTC
wrong argument type nil (expected String) [TypeError]
--------------------------------------------------
/usr/local/rvm/gems/ruby-2.2.2/gems/oxidized-0.21.0/lib/oxidized/output/git.rb:188:in `add'
/usr/local/rvm/gems/ruby-2.2.2/gems/oxidized-0.21.0/lib/oxidized/output/git.rb:188:in `update_repo'
/usr/local/rvm/gems/ruby-2.2.2/gems/oxidized-0.21.0/lib/oxidized/output/git.rb:171:in `update'
/usr/local/rvm/gems/ruby-2.2.2/gems/oxidized-0.21.0/lib/oxidized/output/git.rb:57:in `store'
/usr/local/rvm/gems/ruby-2.2.2/gems/oxidized-0.21.0/lib/oxidized/worker.rb:54:in `process'
/usr/local/rvm/gems/ruby-2.2.2/gems/oxidized-0.21.0/lib/oxidized/worker.rb:16:in `block in work'
/usr/local/rvm/gems/ruby-2.2.2/gems/oxidized-0.21.0/lib/oxidized/worker.rb:16:in `each'
/usr/local/rvm/gems/ruby-2.2.2/gems/oxidized-0.21.0/lib/oxidized/worker.rb:16:in `work'
/usr/local/rvm/gems/ruby-2.2.2/gems/oxidized-0.21.0/lib/oxidized/core.rb:36:in `run'
/usr/local/rvm/gems/ruby-2.2.2/gems/oxidized-0.21.0/lib/oxidized/core.rb:28:in `initialize'
/usr/local/rvm/gems/ruby-2.2.2/gems/oxidized-0.21.0/lib/oxidized/core.rb:4:in `new'
/usr/local/rvm/gems/ruby-2.2.2/gems/oxidized-0.21.0/lib/oxidized/core.rb:4:in `new'
/usr/local/rvm/gems/ruby-2.2.2/gems/oxidized-0.21.0/lib/oxidized/cli.rb:12:in `run'
/usr/local/rvm/gems/ruby-2.2.2/gems/oxidized-0.21.0/bin/oxidized:9:in `<top (required)>'
/usr/local/bin/oxidized:23:in `load'
/usr/local/bin/oxidized:23:in `<main>'
--------------------------------------------------

-bash-4.2$ ruby -v
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]

-bash-4.2$ gem list

*** LOCAL GEMS ***

asetus (0.3.0)
backports (3.10.3)
bigdecimal (default: 1.2.6)
emk-sinatra-url-for (0.2.1)
ffi (1.9.18)
haml (4.0.7)
htmlentities (4.3.4)
io-console (default: 0.4.3)
json (default: 1.8.1)
multi_json (1.12.2)
net-ssh (4.1.0)
oxidized (0.21.0)
oxidized-script (0.5.0)
oxidized-web (0.9.3)
psych (default: 2.0.8)
puma (3.11.0)
rack (1.6.8)
rack-protection (1.5.3)
rack-test (0.8.2)
rake (default: 10.4.2)
rb-fsevent (0.10.2)
rb-inotify (0.9.10)
rdoc (default: 4.2.0)
rugged (0.26.0)
sass (3.5.3)
sass-listen (4.0.0)
sinatra (1.4.8)
sinatra-contrib (1.4.7)
slop (3.6.0)
test-unit (3.0.8)
tilt (2.0.8)

Can anyone help with this at all?

**Comment by laf** [comment]
Your config is using file as the output method, you need to switch to using git. You've got git config in there as well, remove the file config and double check your git config setup against the docs.

**Comment by Kelman77** [comment]
I had git as the only output and received that crash message.

Can I push the latest config version to file as well as import to git?


-------- Original message --------

**Comment by davama** [comment]
@Kelman77 
There is this post https://github.com/ytti/oxidized/issues/425 which hasnt been implemented if im not mistaken.

Then theres is this hacky way i did https://github.com/ytti/oxidized/issues/396
hope it helps!

**Comment by laf** [comment]
Please post the crash message with just git enabled in the config and repost the config from that point.

**Comment by Kelman77** [comment]
Thanks for the assistance, the output to file and git is a nice to have, and not a necessity at this stage and as stated I could always take a snapshot of the git repo on a regular basis.

The config file is as follows,

---
username: username
password: password
model: junos
interval: 3600
use_syslog: true
debug: true
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 127.0.0.1:8000
next_adds_job: false
vars: {}
groups: {}
models: {}
pid: "/u01/oxidized/oxidized.pid"
input:
  default: ssh, telnet
  debug: false
  ssh:
    secure: false
output:
  default: git
  debug: true
  file:
    directory: "/u01/oxidized/config/"
  git:
    user: Oxidized
    email: email@server.com
    repo: "/u01/oxidized/git-repos/default.git"
source:
  default: csv
  csv:
    file: "/u01/oxidized/.config/oxidized/router.db"
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
      ip: 2
      username: 3
      password: 4
    vars_map:
      enable: 5
    gpg: false
hooks:
  email_output:
    type: exec
    events: [post_store, node_fail]
    cmd: '/u01/oxidized-bin/extra/oxidized-report-git-commits | mail -s "Configuration update for ${OX_NODE_NAME}" email@server.com'
    async: true
    timeout: 120
model_map:
  cisco: ios
  f5: tmos
  checkpoint: gaiaos

The crash output is as follows,

/usr/local/rvm/gems/ruby-2.2.2/gems/oxidized-0.21.0/lib/oxidized/output/git.rb:188:in `add': wrong argument type nil (expected String) (TypeError)
        from /usr/local/rvm/gems/ruby-2.2.2/gems/oxidized-0.21.0/lib/oxidized/output/git.rb:188:in `update_repo'
        from /usr/local/rvm/gems/ruby-2.2.2/gems/oxidized-0.21.0/lib/oxidized/output/git.rb:171:in `update'
        from /usr/local/rvm/gems/ruby-2.2.2/gems/oxidized-0.21.0/lib/oxidized/output/git.rb:57:in `store'
        from /usr/local/rvm/gems/ruby-2.2.2/gems/oxidized-0.21.0/lib/oxidized/worker.rb:54:in `process'
        from /usr/local/rvm/gems/ruby-2.2.2/gems/oxidized-0.21.0/lib/oxidized/worker.rb:16:in `block in work'
        from /usr/local/rvm/gems/ruby-2.2.2/gems/oxidized-0.21.0/lib/oxidized/worker.rb:16:in `each'
        from /usr/local/rvm/gems/ruby-2.2.2/gems/oxidized-0.21.0/lib/oxidized/worker.rb:16:in `work'
        from /usr/local/rvm/gems/ruby-2.2.2/gems/oxidized-0.21.0/lib/oxidized/core.rb:36:in `run'
        from /usr/local/rvm/gems/ruby-2.2.2/gems/oxidized-0.21.0/lib/oxidized/core.rb:28:in `initialize'
        from /usr/local/rvm/gems/ruby-2.2.2/gems/oxidized-0.21.0/lib/oxidized/core.rb:4:in `new'
        from /usr/local/rvm/gems/ruby-2.2.2/gems/oxidized-0.21.0/lib/oxidized/core.rb:4:in `new'
        from /usr/local/rvm/gems/ruby-2.2.2/gems/oxidized-0.21.0/lib/oxidized/cli.rb:12:in `run'
        from /usr/local/rvm/gems/ruby-2.2.2/gems/oxidized-0.21.0/bin/oxidized:9:in `<top (required)>'
        from /usr/local/bin/oxidized:23:in `load'
        from /usr/local/bin/oxidized:23:in `<main>'

This may possibly be down to the OS (RH7.4) as I have a successful installation running on Centos7.4.

Thanks,

Andy
________________________________

**Comment by laf** [comment]
I wouldn't have thought it would make a difference between CentOS 7.4 and RHEL 7.4.

Could you try moving `/u01/oxidized/git-repos/default.git` out of the way and also remove:

```
 file:
   directory: "/u01/oxidized/config/"
```

Restart and see what happens.

**Comment by laf** [comment]
No further response given so closing this issue, feel free to comment about trying the last suggestion and we can re-open.
