### ISSUE TITLE
Issue regarding colon in passwords

### ISSUE THREAD

**Issue by tychoo** [ytti/oxidized#1129]
Having an issue adding a device that currently has a password with a colon in the string.  Is there anyway to add this device in router.db and pass the colon as a character and not delimiter?

Thanks.

**Comment by laf** [comment]
Have you tried escaping the colon, like `\:`?

**Comment by laf** [comment]
No further response so closing this issue.

If you have any feedback please respond and we can open this up.

**Comment by funzoneq** [comment]
I don't think this was ultimately answered. I tried escaping with \: but that doesn't work. I changed the delimiter regex to not match \\:

```
source:
  default: csv
  csv:
    delimiter: !ruby/regexp /(?<!\\):/
```

My password for example is bla:bla will now be stored in router.db as bla\\:bla.

**Comment by ytti** [comment]
Personally it seems more complex than necessary solution, just use any random char as delimiter, one which you don't use in PW. Or switch to some other source which has concept of fields, such as SQL.
