### ISSUE TITLE
not saving multiple versions

### ISSUE THREAD

**Issue by dkraklan** [ytti/oxidized#1137]
I have oxidized setup to backup multiple juniper switches, and with a similar installation for another project It shows me multiple versions and the changes made as expected. However with my new install it updates when I make changes but doesn't show me previous versions. When i got to the version page it just says no available data in table

here is my config.

> username: oxidized
> password: <omitted>
> model: junos
> interval: 3600
> use_syslog: false
> debug: false
> threads: 30
> timeout: 20
> retries: 3
> prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
> rest: <omitted>:8888
> next_adds_job: false
> vars: {}
> groups: {}
> models: {}
> pid: /root/.config/oxidized/pid
> input:
>   default: ssh, telnet
>   debug: false
>   ssh:
>     secure: false
> output:
>   default: file
>   file:
>     directory: /root/.config/oxidized/configs
> source:
>   default: csv
>   csv:
>     file: /root/.config/oxidized/router.db
>     delimiter: !ruby/regexp /:/
>     map:
>       name: 0
>       model: 1
>     gpg: false
> source:
>   default: http
>   http:
>     url: http://<omitted>/api/v0/oxidized
>     map:
>       name: hostname
>       model: os
>     headers:
>       X-Auth-Token: <omitted>
> model_map:
>   cisco: ios
>   juniper: junos

**Comment by amachekhin** [comment]
Will you please try to configure output to git?
```
output:
  default: git
  git:
    user: oxidized
    email: oxidized@server.net
    repo: "/home/oxidized/git/cisco.git"
```

**Comment by laf** [comment]
As per @amachekhin's response this is because you are using flat file output which doesn't support versioning. Please check the docs for git output and that will give you what you want.
