### ISSUE TITLE
RouterOs comments on export

### ISSUE THREAD

**Issue by alangregory** [ytti/oxidized#1138]
RouterOs adds a comment for firewall dynamic rules based on time when, they are inactive, triggering a new diff on config.
Sample:
```
/ip firewall mangle
# inactive time
add action=mark-packet chain=prerouting new-packet-mark=daytime passthrough=no src-address-list=daytime time=8h-18h,mon,tue,wed,thu,fri,sat
```
It's possivel to strip it from output ?

**Comment by laf** [comment]
Most likely, is it the `# inactive time` you want to strip? If so can you provide valid output?

**Comment by alangregory** [comment]
Yes. Added idea on #1143 , do you need some backup examples ?

**Comment by laf** [comment]
I thought you meant `# inactive time` was a marker for an actual time. If that's the same all the time then why's it marking config as changed?

**Comment by alangregory** [comment]
It's just a comment that routeros adds on export, to show if the rule is active at that time. it happens just on rules with time parameters. Example of rule, if we run /export betwen 8-18h, no comment on export.
```
/ip firewall mangle
# inactive time
add action=mark-packet chain=prerouting new-packet-mark=daytime passthrough=no src-address-list=daytime time=8h-18h,mon,tue,wed,thu,fri,sat
```

**Comment by laf** [comment]
Ah so it appears / disappears based on time. No worries.
