### ISSUE TITLE
Problem with saving in gitlab using SSL

### ISSUE THREAD

**Issue by brunonetadmin** [ytti/oxidized#1140]
I´m facing a problem right now, when i implemented SSL in my Gitlab enviroment, the git sync of my repository don´t work anymore. Its there any "change" that i need to do in my config to support this?

Ps.: And i changed the repository to the https address. So, this is not the problem.

**Comment by laf** [comment]
Is the SSL cert valid? Have you tried to just do a git clone from it to see if it does indeed work?

**Comment by PeepOks** [comment]
Maybe it's related to https://github.com/ytti/oxidized/issues/1240

**Comment by wk** [comment]
Most likely related to either #1240 or #1034.
