### ISSUE TITLE
Unable to view device configs from Oxidized in LibreNMS configs tab

### ISSUE THREAD

**Issue by jms1973** [ytti/oxidized#1141]
Hi. Oxidized is collecting configs ok, but when I try to view them in LibreNMS I get the 'We couldn't retrieve the device information from Oxidized' message. If I add '/debug=true/' to the URL the PHP debug info is as follows:

Array ( [errno] => 8 [errstr] => Undefined index: HTTPS [errfile] => /opt/librenms/includes/defaults.inc.php [errline] => 942 )
--
Array ( [errno] => 8 [errstr] => Undefined index: rrdgraph_real_95th [errfile] => /opt/librenms/includes/process_config.inc.php [errline] => 44 )
Array ( [errno] => 8 [errstr] => Undefined index: custom_css [errfile] => /opt/librenms/html/index.php [errline] => 134 )
Array ( [errno] => 8192 [errstr] => call_user_func() expects parameter 1 to be a valid callback, non-static method Weathermap::menu() should not be called statically [errfile] => /opt/librenms/LibreNMS/Plugins.php [errline] => 85 )
Array ( [errno] => 8 [errstr] => Undefined index: override_device_type [errfile] => /opt/librenms/includes/common.php [errline] => 1559 )
Array ( [errno] => 8 [errstr] => Undefined index: mydomain [errfile] => /opt/librenms/includes/common.php [errline] => 1721 )
Array ( [errno] => 8 [errstr] => Undefined variable: descr [errfile] => /opt/librenms/html/includes/device-header.inc.php [errline] => 37 )
Array ( [errno] => 8 [errstr] => Undefined index: overview [errfile] => /opt/librenms/html/pages/device.inc.php [errline] => 53 )
Array ( [errno] => 8 [errstr] => Undefined index: graphs [errfile] => /opt/librenms/html/pages/device.inc.php [errline] => 60 )
Array ( [errno] => 8 [errstr] => Undefined index: health [errfile] => /opt/librenms/html/pages/device.inc.php [errline] => 73 )
Array ( [errno] => 8 [errstr] => Undefined index: ports [errfile] => /opt/librenms/html/pages/device.inc.php [errline] => 113 )
Array ( [errno] => 8 [errstr] => Undefined index: port [errfile] => /opt/librenms/html/pages/device.inc.php [errline] => 113 )
Array ( [errno] => 8 [errstr] => Undefined index: in [errfile] => /opt/librenms/html/pages/device.inc.php [errline] => 146 )
Array ( [errno] => 8 [errstr] => Undefined index: out [errfile] => /opt/librenms/html/pages/device.inc.php [errline] => 146 )
Array ( [errno] => 8 [errstr] => Undefined index: vlans [errfile] => /opt/librenms/html/pages/device.inc.php [errline] => 155 )
Array ( [errno] => 8 [errstr] => Undefined variable: loadbalancer_tabs [errfile] => /opt/librenms/html/pages/device.inc.php [errline] => 215 )
Array ( [errno] => 8 [errstr] => Undefined index: Cisco-OTV [errfile] => /opt/librenms/html/pages/device.inc.php [errline] => 254 )
Array ( [errno] => 8 [errstr] => Undefined variable: routing_tabs [errfile] => /opt/librenms/html/pages/device.inc.php [errline] => 259 )
Array ( [errno] => 8 [errstr] => Undefined index: neighbours [errfile] => /opt/librenms/html/pages/device.inc.php [errline] => 275 )
Array ( [errno] => 8 [errstr] => Undefined index: stp [errfile] => /opt/librenms/html/pages/device.inc.php [errline] => 282 )
Array ( [errno] => 8 [errstr] => Undefined index: entphysical [errfile] => /opt/librenms/html/pages/device.inc.php [errline] => 299 )
Array ( [errno] => 8 [errstr] => Undefined index: services [errfile] => /opt/librenms/html/pages/device.inc.php [errline] => 314 )
Array ( [errno] => 8 [errstr] => Undefined index: logs [errfile] => /opt/librenms/html/pages/device.inc.php [errline] => 329 )
Array ( [errno] => 8 [errstr] => Undefined index: alerts [errfile] => /opt/librenms/html/pages/device.inc.php [errline] => 335 )
Array ( [errno] => 8 [errstr] => Undefined index: alert-stats [errfile] => /opt/librenms/html/pages/device.inc.php [errline] => 341 )
Array ( [errno] => 8 [errstr] => Undefined index: rancid_configs [errfile] => /opt/librenms/html/pages/device.inc.php [errline] => 348 )
Array ( [errno] => 8 [errstr] => Undefined index: rancid_configs [errfile] => /opt/librenms/html/pages/device.inc.php [errline] => 349 )
Array ( [errno] => 8 [errstr] => Undefined index: ignore_types [errfile] => /opt/librenms/html/pages/device.inc.php [errline] => 370 )
Array ( [errno] => 2 [errstr] => in_array() expects parameter 2 to be array, null given [errfile] => /opt/librenms/html/pages/device.inc.php [errline] => 370 )
Array ( [errno] => 8 [errstr] => Undefined variable: nfsen_rrd_file [errfile] => /opt/librenms/html/pages/device.inc.php [errline] => 413 )
Array ( [errno] => 8 [errstr] => Undefined index: override_icmp_disable [errfile] => /opt/librenms/includes/common.php [errline] => 1006 )
Array ( [errno] => 8 [errstr] => Undefined index: performance [errfile] => /opt/librenms/html/pages/device.inc.php [errline] => 422 )
Array ( [errno] => 8 [errstr] => Undefined index: notes [errfile] => /opt/librenms/html/pages/device.inc.php [errline] => 429 )
Array ( [errno] => 2 [errstr] => file_get_contents(87.237.68.123:8787/node/show/ggs-sw-stk1.hns.net?format=json): failed to open stream: No such file or directory [errfile] => /opt/librenms/html/pages/device/showconfig.inc.php [errline] => 101 )
Array ( [errno] => 2 [errstr] => file_get_contents(87.237.68.123:8787/node/show/ggs-sw-stk1?format=json): failed to open stream: No such file or directory [errfile] => /opt/librenms/html/pages/device/showconfig.inc.php [errline] => 115 )
Array ( [errno] => 2 [errstr] => file_get_contents(87.237.68.123:8787/node/version?node_full=ggs-sw-stk1&format=json): failed to open stream: No such file or directory [errfile] => /opt/librenms/html/pages/device/showconfig.inc.php [errline] => 120 )
Array ( [errno] => 2 [errstr] => file_get_contents(87.237.68.123:8787/node/fetch/ggs-sw-stk1): failed to open stream: No such file or directory [errfile] => /opt/librenms/html/pages/device/showconfig.inc.php [errline] => 170 )
37 total PHP issues / errors.

If I run 'curl http://127.0.0.1:8787/node/show/hostname.com?format=json' from the command line I get:

curl: (7) Failed connect to 127.0.0.1:8787; Connection timed out

Both oxidized and librenms are running on the same box - centOS7.

Any help appreciated.

**Comment by laf** [comment]
In the debug output it looks like you've not put `http://` in front of your oxidized IP.

The fact you can't curl it on loopback means it's not listening on that IP.

This question doesn't really seem to be applicable to oxidized itself, it would be better to discuss this on gitter https://github.com/ytti/oxidized#help

**Comment by jms1973** [comment]
Wow! That was quick. Thanks for the reply.

I can get to oxidized web interface with no issues on port 8787.

Where do you mean when you say I may have not put in the http:// in front of the oxidized ip?

**Comment by jms1973** [comment]
Sorry, dumb question. I have checked /opt/librenms/includes/defaults.inc.php line 942 and it is  

$config['secure_cookies'] = $_SERVER["HTTPS"];

should this be HTTP?

**Comment by laf** [comment]
In the librenms config where you've entered your oxidized host, it looks like you've just put the IP.

**Comment by jms1973** [comment]
In the global settings? I followed this guide: https://techstat.net/how-to-integrate-oxidized-into-librenms/ and that's how they did it.

I have tried adding http:// first and this when I do that the page eventually times out.

I've tried with the 127.0.0.1 address and the actual address.

**Comment by laf** [comment]
That article is incorrect, you need to specify it as a browser would use it.

The fact it's timing out after that indicates you still can't get to that web interface from the LibreNMS install. If you can't curl it locally from the box then you have something stopping it like a firewall or incorrect config.

**Comment by jms1973** [comment]
ok i'll check iptables. thanks for the quick responses.

one more quick question if i may. should i use loopback address or actual ip address?

**Comment by laf** [comment]
If it's all local the loop back is fine but you won't get to the oxidized web interface from any remote computers at that point without proxying it using nginx or similar.

**Comment by jms1973** [comment]
Thanks. It's working now!

I had to allow 127.0.0.1 through iptables for 8787.
