### ISSUE TITLE
Trying to feed Oxidized from LibreNMS via API call

### ISSUE THREAD

**Issue by jms1973** [ytti/oxidized#1142]
The documentation states you can feed oxidized via an API call and gives a sample config:

source:
  default: http
  debug: false
  http:
    url: https://librenms/api/v0/oxidized
    map:
      name: hostname
      model: os
      group: group
    headers:
      X-Auth-Token: '01582bf94c03104ecb7953dsadsadwed'

Is there a more detailed guide than this?

**Comment by jms1973** [comment]
Specifically I have changed the URL to my librenms URL, I have generated an API token and used it under the headers, but when I add a new device in Librenms the list of nodes does not update in oxidized.

**Comment by laf** [comment]
You need to issue a reload, LibreNMS can do that: https://docs.librenms.org/#Extensions/Oxidized/#feeding-oxidized

**Comment by jms1973** [comment]
I have already selected the 'Reload Oxidized nodes list, each time a device is added' option in the global settings, so that is not the issue.

**Comment by laf** [comment]
Please use Gitter or the forum for more help on this: https://github.com/ytti/oxidized#help

The LibreNMS integration works as does the reloading of oxidized when adding devices
