### ISSUE TITLE
Fortigate backup issue

### ISSUE THREAD

**Issue by papatango71** [ytti/oxidized#1145]
I have a Fortigate 2500E firewall that is failing to back up.  When I look through the debug log file I am seeing the following error:

   edit "FAPS321C-default"
        config platform
            set type S321C
        end
        set ap-country US
--More-- tail: /home/oxidized/.config/oxidized/logs/10.74.32.83-ssh: file truncated

I have updated to  fortios.rb #1047 per https://github.com/ytti/oxidized/issues/931 but I am not seeing any change.  I have tried adding the following to remove the paging but it did not resolve any issues either.

  cfg :telnet, :ssh do
    post_login 'config system console'
    post_login 'set output standard'
    post_login 'end'

    pre_logout 'config system console'
    pre_logout 'set output more'
    pre_logout 'end'
    pre_logout "exit\n"
  end

This is the error that I am getting in /var/log/messages:

Jan 10 21:51:09 las1-admin-inf01 oxidized[101619]: 10.74.32.83 raised Timeout::Error with msg "execution expired"
Jan 10 21:51:09 las1-admin-inf01 oxidized[101619]: vr01-t09d-swlas1.network.cloud.xxx.net status no_connection, retry attempt 1
Jan 10 21:51:51 las1-admin-inf01 oxidized[101619]: 10.74.32.83 raised Timeout::Error with msg "execution expired"
Jan 10 21:51:51 las1-admin-inf01 oxidized[101619]: vr01-t09d-swlas1.network.cloud.xxx.net status no_connection, retry attempt 2

Any help to resolve this would be greatly appreciated.

Thank you.

-Patrick

**Comment by laf** [comment]
I don't think #1047 would have made a difference for you here.

Seems like it may not be matching the prompt, what prompt do you on the device if you manually login?

**Comment by tnielsen2** [comment]
I am having a similar issue, not sure if it is related or not, but since an update I have two firewalls that have multi vdom that fail to pull down.

**Comment by sfini** [comment]
@papatango71 

Hi .. The show full-configuration command give a bigger output , and it take some time to complete.
Can you try to adjust your timeout in your config file ?
Ex.
use_syslog: true
debug: true
threads: 30
timeout: 60


Simone

**Comment by papatango71** [comment]
Trent,

The timeout config resolved the issue.  But now I am getting the configs
sent via email as .bin attachments.  Any ideas why that may be happening..??

Thank you.

-Patrick

**Comment by laf** [comment]
Post your config and what you are using to send the emails.

**Comment by papatango71** [comment]
@laf, the config file for oxidized is below:




---
username: XXXX
password: XXXXXX
model: cisco
interval: 3600
use_syslog: true
log: /home/XXXX/.config/XXXX/logs/
debug: true
threads: 30
timeout: 60
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 127.0.0.1:8888
next_adds_job: false
vars: {}
groups:
  cisco_asa:
    username: XXXX
    password: XXXXXX
    vars:
      ssh_proxy: 10.104.197.195
  cisco:
    username: XXXX
    password: XXXXXX
    vars:
      ssh_proxy: 10.104.197.195
  iosxe:
    username: XXXX
    password: XXXXXX
    vars:
      ssh_proxy: 10.104.197.195
  iosxr:
    username: XXXX
    password: XXXXXX
    vars:
      ssh_proxy: 10.104.197.195
  nexus:
    username: XXXX
    password: XXXXXX
    vars:
      ssh_proxy: 10.104.197.195
  juniper:
    username: XXXX
    password: XXXXXX
    vars:
      ssh_proxy: 10.104.197.195
  opengear:
    username: XXX
    password: ssMUNsz3!
    vars:
      ssh_proxy: 10.104.197.195
  fortigate:
    username: XXXX
    password: XXXXXX
  acos:
    username: XXXX
    password: XXXXXX
    vars:
      ssh_proxy: 10.104.197.195
  arista_eos:
    username: XXXX
    password: XXXXXX
    vars:
      ssh_proxy: 10.104.197.195
pid: "/home/XXXX/.config/XXXX/pid"
input:
  default: ssh
  debug: true
  ssh:
    secure: false
output:
  default: git
  git:
    user: XXXX
    email: XXXX@las1-admin-inf01.XXX.net
    repo: "/home/XXXX/.config/XXXX"
  debug: true
source:
        default: http
        debug: true
        http:
          url: https://librenms.las1.network.cloud.XXX.net/api/v0/XXXX
          map:
            name: hostname
            model: os
            group: group
          headers:
            X-Auth-Token: '7bd7ffc3188f7a89699c7cd644f8a3a2'
model_map:
  a10: acos
  arista_eos: eos
  cisco_asa: asa
  cisco: ios
  fortigate: fortios
  iosxe: ios
  iosxr: iosxr
  juniper: junos
  nexus: nxos
  opengear: opengear

hooks:
 email_output:
   type: exec
   events: [post_store, node_fail]
   cmd: '/home/XXXX/extra/XXXX-report-git-commits ~/gitdir/ | mail -s "Oxidized updates for ${OX_NODE_NAME}" networkchanges@XXX.com'
   async: true
   timeout: 120

**Comment by laf** [comment]
The example in the docs is:

`cmd: '/home/oxidized/extra/oxidized-report-git-commits | mail -s "Oxidized updates for ${OX_NODE_NAME}" update-recipient@example.com'`

**Comment by sfini** [comment]
@papatango71 

As laf wrote i think there's something to adjust in your config.

Here an example of working config in my lab

hooks:
 post_store:
    type: exec
    events: [post_store]
    cmd: '/var/lib/gems/2.3.0/gems/oxidized-0.20.0/extra/oxidized-report-git-commits  | mail -s "Oxidized updates for ${OX_NODE_NAME}" mymail1@mycompany.it,mymail2@mycompany.it,mymail3@mycompany.it'
  node_fail:
    type: exec
    events: [node_fail]
    cmd: '/var/lib/gems/2.3.0/gems/oxidized-0.20.0/extra/oxidized-report-git-commits  | mail -s "Oxidized failed backup for ${OX_NODE_NAME}" mymail1@mycompany.it,mymail2@mycompany.it,mymail3@mycompany.it'
    async: true
    timeout: 120

**Comment by laf** [comment]
Those paths won't work for people with different versions of oxidized, you're supposed to copy the script to somewhere static.

**Comment by laf** [comment]
Closing this down now as the original question has been resolved.

**Comment by sfini** [comment]
@laf 
You're right , it was only an example of a working configuration
