### ISSUE TITLE
Defunct ssh processes 

### ISSUE THREAD

**Issue by TheHolm** [ytti/oxidized#1146]
reopening: 
https://github.com/ytti/oxidized/issues/450

"When Oxidized (0.21) is running for some time I get defunct ssh processes.I'm not sure where they come from and I wonder how I can debug this. Even more, I don't think we should get defunct processes at all."

It seems that zombies generated for proxied ssh connections to routers which are not responding.

Is something wrong with SIGCHLD handling? 

#ps ax
25822 ? Z 0:00 [ssh] 
25825 ? Z 0:00 [ssh]

#gem list

oxidized (0.21.0)
oxidized-script (0.5.0)
oxidized-web (0.9.3)

**Comment by laf** [comment]
I've reopened the other issue as that has more history in it.
