### ISSUE TITLE
Input FTP customise Filename

### ISSUE THREAD

**Issue by cppmonkey** [ytti/oxidized#1147]
Hi,

I'm trying to customise the filename requested by Zyxel.rb. I'd like it to be possible to set it via the config file.

I've tried moving `cmd 'config-0' `the `cfg :ftp do` section, which puts me within the scope to access the config variables, but the FTP request has already been attempted.

I could customise the option from input/ftp.rb but its ugly and its only applicable to the ZyXel XGS4600 series that I'm aware of

I'll be submitting a feature request to add an option for ftp passive, as these ZyXel's don't support passive mode

> Connected to xgs4600.
> 220 XGS4600 FTP version 1.0 ready at Thu Jan  7 16:33:29 2016
> Name (   ): admin
> 331 Enter PASS command
> Password:
> 230 Logged in
> Remote system type is UNIX.
> Using binary mode to transfer files.
> ftp> ls
> 200 Port command okay
> 150 Opening data connection for LIST 
> --w--w--w-   1 owner    group         8845378 Jul 01 12:00 ras-0
> --w--w--w-   1 owner    group         8845378 Jul 01 12:00 ras-1
> -rw-rw-rw-   1 owner    group        67108864 Jul 01 12:00 config
> 226 File sent OK
> ftp> 

Are there any other devices that use ftp?

**Comment by tracerrx** [comment]
I am also looking for a file-retrieve via FTP example
