### ISSUE TITLE
Oxidized crashes when started

### ISSUE THREAD

**Issue by Ondjultomte** [ytti/oxidized#1152]
so I have been running a setup of oxid for a few weeks for testing. I was tinkering with the router.db file and now I restarted the oxidized process byt:

"sudo systemctl restart oxidized"

but now it crashes, 
the crash file:
2018-01-17 14:02:17 UTC
git not found: sudo gem install ruby-git [Oxidized::OxidizedError]
--------------------------------------------------
/var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/output/gitcrypt.rb:7:in `rescue in <class:GitCrypt>'
/var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/output/gitcrypt.rb:4:in `<class:GitCrypt>'
/var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/output/gitcrypt.rb:2:in `<module:Oxidized>'
/var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/output/gitcrypt.rb:1:in `<top (required)>'
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/manager.rb:10:in `load'
/var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/manager.rb:40:in `add_output'
/var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/node.rb:155:in `resolve_output'
/var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/node.rb:22:in `initialize'
/var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/nodes.rb:19:in `new'
/var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/nodes.rb:19:in `block (2 levels) in load'
/var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/nodes.rb:15:in `each'
/var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/nodes.rb:15:in `block in load'
/var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/nodes.rb:128:in `synchronize'
/var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/nodes.rb:128:in `with_lock'
/var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/nodes.rb:10:in `load'
/var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/nodes.rb:123:in `initialize'
/var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/core.rb:14:in `new'
/var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/core.rb:14:in `initialize'
/var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/core.rb:4:in `new'
/var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/core.rb:4:in `new'
/var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/cli.rb:12:in `run'
/var/lib/gems/2.3.0/gems/oxidized-0.21.0/bin/oxidized:9:in `<top (required)>'
/usr/local/bin/oxidized:22:in `load'
/usr/local/bin/oxidized:22:in `<main>'

and journalctl:

Jan 17 15:02:17 host01 oxidized[17592]: Oxidized starting, running as pid 17592
Jan 17 15:02:17 host01 oxidized[17592]: lib/oxidized/nodes.rb: Loading nodes
Jan 17 15:02:17 host01 oxidized[17592]: resolving DNS for Unitname-RO01...
Jan 17 15:02:17 host01 oxidized[17592]: IPADDR
Jan 17 15:02:17 host01 oxidized[17592]: node.rb: resolving node key 'input', with passed global value of 'ssh' and node value ''
Jan 17 15:02:17 host01 oxidized[17592]: node.rb: returning node key 'input' with value 'ssh'
Jan 17 15:02:17 host01 oxidized[17592]: node.rb: resolving node key 'output', with passed global value of 'gitcrypt' and node value ''
Jan 17 15:02:17 host01 oxidized[17592]: node.rb: returning node key 'output' with value 'gitcrypt'
Jan 17 15:02:17 host01 oxidized[17592]: Oxidized crashed, crashfile written in /home/oxidized/.config/oxidized/crash
Jan 17 15:02:17 host01 oxidized[17592]: git not found: sudo gem install ruby-git
Jan 17 15:02:17 host01 oxidized[17592]: /var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/output/gitcrypt.rb:7:in `rescue in <class:GitCrypt>': git not found: sudo gem install ruby-git (Oxidiz
Jan 17 15:02:17 host01 oxidized[17592]:         from /var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/output/gitcrypt.rb:4:in `<class:GitCrypt>'
Jan 17 15:02:17 host01 oxidized[17592]:         from /var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/output/gitcrypt.rb:2:in `<module:Oxidized>'
Jan 17 15:02:17 host01 oxidized[17592]:         from /var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/output/gitcrypt.rb:1:in `<top (required)>'
Jan 17 15:02:17 host01 oxidized[17592]:         from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
Jan 17 15:02:17 host01 oxidized[17592]:         from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
Jan 17 15:02:17 host01 oxidized[17592]:         from /var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/manager.rb:10:in `load'
Jan 17 15:02:17 host01 oxidized[17592]:         from /var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/manager.rb:40:in `add_output'
Jan 17 15:02:17 host01 oxidized[17592]:         from /var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/node.rb:155:in `resolve_output'
Jan 17 15:02:17 host01 oxidized[17592]:         from /var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/node.rb:22:in `initialize'
Jan 17 15:02:17 host01 oxidized[17592]:         from /var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/nodes.rb:19:in `new'
Jan 17 15:02:17 host01 oxidized[17592]:         from /var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/nodes.rb:19:in `block (2 levels) in load'
Jan 17 15:02:17 host01 oxidized[17592]:         from /var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/nodes.rb:15:in `each'
Jan 17 15:02:17 host01 oxidized[17592]:         from /var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/nodes.rb:15:in `block in load'
Jan 17 15:02:17 host01 oxidized[17592]:         from /var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/nodes.rb:128:in `synchronize'
Jan 17 15:02:17 host01 systemd[1]: oxidized.service: Main process exited, code=exited, status=1/FAILURE
Jan 17 15:02:17 host01 systemd[1]: oxidized.service: Unit entered failed state.
Jan 17 15:02:17 host01 systemd[1]: oxidized.service: Failed with result 'exit-code'.
user02@host01:/home/oxidized/.config/oxidized$ cat /home/oxidized/.config/oxidized/crash

**Comment by laf** [comment]
It looks like you've changed more than the router.db file as it's complaining that git isn't installed for ruby. It gives you the command to run for this:

`sudo gem install ruby-git`

I'm closing this as it doesn't seem like an issue with oxidized, please use one of the alternative channels for further help
