### ISSUE TITLE
Dell Powerconnect 6248 / Dell Powerconnect 8024F

### ISSUE THREAD

**Issue by deeconwastaken** [ytti/oxidized#1153]
Hi, I setup oxidized, but I have Problems with some older Dell Switches.

- Dell  Powerconnect 6248 
The Switch is operated with VXWorks 6.5, I tested both powerconnect and quanta, but none could get a working config.

- Dell Powerconnect 8024F
This Switch is operated with VXWorks 6.6, same issue

Dell Powerconnect 6248
`
! 
! Image Descriptions 
! 
!  image1 : default image 
!  image2 :  
! 
! 
!  Images currently available on Flash 
! 
! --------------------------------------------------------------------
!  unit      image1      image2     current-active        next-active 
! -------------------------------------------------------------------- 
! 
!     1     3.3.4.1     3.2.1.3             image1             image1 
! System Description: Dell Ethernet Switch
! 1       Fan 4          OK

                ^
% Invalid input detected at '^' marker.
`

Dell Powerconnect 8024F
`
! 
! System Description................ Dell Ethernet Switch
! System Contact....................
! System Name.......................
! System Location...................
! Burned In MAC Address............. D067.E5AE.1806
! System Object ID.................. 1.3.6.1.4.1.674.10895.3024
! System Model ID................... PC8024F
! Machine Type...................... Powerconnect 8024F
! 
! unit image1      image2      current-active next-active
! ---- ----------- ----------- -------------- --------------
! 1    5.1.10.1    5.0.1.3     image1         image1
! 
! System Description: Dell Ethernet Switch
! ----     -----------    ------
! 1       Fan 1          OK
! 1       Fan 2          OK
! 1       Fan 3          OK

              ^
% Invalid input detected at '^' marker.
`

Can some help me what to do? Thank you.

**Comment by laf** [comment]
You need to turn debugging on and post the output. Please also post your config.

**Comment by deeconwastaken** [comment]
okay, here is the debug output and my config.

[oxi.log](https://github.com/ytti/oxidized/files/1639369/oxi.log)
[oxi.config.txt](https://github.com/ytti/oxidized/files/1639445/oxi.config.txt)

**Comment by laf** [comment]
What's the IP of the ones not working as you have a lot of connection refused messages.

What model are you using within your router.db file?

**Comment by deeconwastaken** [comment]
192.168.215.202 --> Dell Powerconnect 8024F
192.168.8.15 and 16 --> Dell Powerconnect 6248

router.db --> powerconnect

**Comment by laf** [comment]
They all have connection refused so you seem to have a general issue with reaching these devices. Check you can connect from the Oxidized host to them manually.

**Comment by deeconwastaken** [comment]
Yes, i can connect to the hosts without any problems.  I did another debug-log after a clean reboot.

[oxid.log](https://github.com/ytti/oxidized/files/1639821/oxid.log)

**Comment by laf** [comment]
Have you looked at the output yourself?

**Comment by deeconwastaken** [comment]
Okay, I know now what the problem is. I configured a user with "level 1" (read-only), but that user cannot use the "enable" command. And you can only use the "show running-config" at an enabled prompt.

**Comment by laf** [comment]
Can this now be closed?

**Comment by deeconwastaken** [comment]
Yes, this issue can be closed.
