### ISSUE TITLE
Fortigate 600D multi-vdom failing

### ISSUE THREAD

**Issue by tnielsen2** [ytti/oxidized#1156]
I have one Fortigate firewall that Oxidized is unable to pull down the configuration from. After updating my server to move Oxidized into a container (which means an update to the ruby modules), is when the problem occurred. Unfortunately, I cannot say what version of code the ruby module was on at the time it was working for this specific firewall. 

I have a snippet of my config file, and I cannot seem to find out where I can find the necessary logs in order to troubleshoot the issue. When I turn on debug: true, I still don't get any logs. Where do I find the debug output to troubleshoot the issue? The container is mounted to the proper volume, yet I don't get anything.

```
use_syslog: true
log: /root/.config/oxidized/logs
debug: false
threads: 30
timeout: 240
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 0.0.0.0:8888
next_adds_job: false
vars:
  remove_secret: false
  enable: $L1pstream
groups: {}
models: {}
pid: /root/.config/oxidized/pid
input:
  default: ssh, telnet
  debug: false
  ssh:
    secure: false
```

I verified that i can ssh to the device from the oxidized server, with the credentials provided, which places me into the correct vdom. 
I have also tried to up the "timeout" timer to ensure that it is longer than it should be (upped to 480 from 240 with no success)
Lastly, I have other Fortigate firewalls (with smaller configs, and slighly smaller models) that work just fine.

What can I do to assist with troubleshooting getting this fixed?

**Comment by laf** [comment]
Please enable debugging and pastebin the debug logs.

**Comment by tnielsen2** [comment]
I was able to resolve this issue. It was due to the timeout being so short. This particular Fortigate had a very large config and doubling the timeout fixed the issue. This is being closed.
