### ISSUE TITLE
git history lost for file renames

### ISSUE THREAD

**Issue by ghost** [ytti/oxidized#1157]
I converted my RANCID repository from SVN to GIT preserving all history and then re-organized the files in the repo to what Oxidized expects for each "node".  This worked successfully. Unfortunately git does not do a great job out of the box at preserving history of files that have been renamed. The data is there, but the logs don't show it. From the shell you need to use "git log --follow" to get the full history. It appears that Rugged via libgit2 should be able to scrape this via [find_similar](https://libgit2.github.com/libgit2/#HEAD/group/diff/git_diff_find_similar). I do not currently see where this functionality is exposed in Rugged, but it should be there.

It would be nice if this could be fixed as I would like to see full history for my devices instead of just 1 commit from the state it was when RANCID last pulled the config.

Thanks

**Comment by feld** [comment]
I found this in the Rugged docs:

```
# Detect renamed files
# Note that the status field changed from :added/:deleted to :renamed
diff.find_similar!
diff.each_delta{ |d| puts d.inspect }
#<Rugged::Diff::Delta:70144372230920 {old_file: {:oid=>"81b68f040b120c9627518213f7fc317d1ed18e1c", :path=>"txt1", :size=>14, :flags=>6, :mode=>33188}, new_file: {:oid=>"81b68f040b120c9627518213f7fc317d1ed18e1c", :path=>"foo1", :size=>14
, :flags=>6, :mode=>33188}, similarity: 100, status: :renamed>
#<Rugged::Diff::Delta:70144372230140 {old_file: {:oid=>"a7bb42f71183c162efea5e4c80597437d716c62b", :path=>"txt2", :size=>17, :flags=>6, :mode=>33188}, new_file: {:oid=>"a357de7d870823acc3953f1b2471f9c18d0d56ea", :path=>"txt2", :size=>29
, :flags=>6, :mode=>33188}, similarity: 0, status: :modified>
```

**Comment by heraldodinero** [comment]
why not planned? we have no ability to rename devices and maintain history?

**Comment by robertcheramy** [comment]
Because no one stepped in to implement this. And this is a corner case, when migrating from one system to another you may have to cope with two histories.
