### ISSUE TITLE
RedBack and D-link no_connection

### ISSUE THREAD

**Issue by xaker1** [ytti/oxidized#1158]
Hello.
I have Ericsson SE100 and D-link DGS-3620 (with cisco like cli).
Dlink:
> {:name=>"CAM.GW",
 :full_name=>"CAM.GW",
 :ip=>"192.168.1.229",
 :group=>nil,
 :model=>"IOS",
 :last=>
  {:start=>2018-01-21 17:37:09 UTC,
   :end=>2018-01-21 17:40:09 UTC,
   :status=>:no_connection,
   :time=>179.242611453},
 :vars=>nil}
> 
Ericsson:

> {:name=>"BRAS-AS1",
 :full_name=>"BRAS-AS1",
 :ip=>"192.168.1.12",
 :group=>nil,
 :model=>"IPOS",
 :last=>
  {:start=>2018-01-21 17:13:32 UTC,
   :end=>2018-01-21 17:15:54 UTC,
   :status=>:no_connection,
   :time=>142.648146239},
 :vars=>nil}

> 
logs D-link:

>                       DGS-3620-28SC Gigabit Ethernet Switch
> 
>                              Command Line Interface
>                             Firmware: Build 1.58.R004 
>            Copyright(C) 2017 D-Link Corporation. All rights reserved.
> 
> User Access Verification
> 
> Username:
> Username:  timeout expired!
> Username:
> Username:  timeout expired!
> Username:

logs RedBack:

> Trying 192.168.1.12...
Connected to 192.168.1.12.
��
BRAS-AS1
login: 
> 

plz help!

**Comment by laf** [comment]
It's really not clear what it is your are asking for here. Please post some more information and we can re-open this issue.
