### ISSUE TITLE
Temporary disable polling of a node

### ISSUE THREAD

**Issue by brwnie** [ytti/oxidized#1159]
Hello,

Is there a value I can set or method to temporary disable the polling of a node?

Thanks

**Comment by laf** [comment]
This isn't possible right now without just removing the device from whichever source input you use.

**Comment by dnyt84** [comment]
Hello,

has there been any progress on this?

Thank you,

Daniel

**Comment by athompson-merlin** [comment]
As a workaround, perhaps setting the device model to a NULL type that doesn't even attempt to poll?  Not sure if such a device exists currently, but I just ran into the same need: to temporarily stop polling a device yet leave it visible in the UI.
