### ISSUE TITLE
Issues pulling configuration from UBNT EdgeSwitch

### ISSUE THREAD

**Issue by ethanmullins** [ytti/oxidized#1162]
I can't seem to get oxidized to pull configurations from UBNT EdgeSwitches.

Doing a debug I get:

Jan 23 22:05:55 server1 oxidized[20381]: lib/oxidized/nodes.rb: Loaded 2 nodes
Jan 23 22:05:56 server1 oxidized[20381]: lib/oxidized/core.rb: Starting the worker...
Jan 23 22:05:56 server1 oxidized[20381]: lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 0 of 2
Jan 23 22:05:56 server1 oxidized[20381]: lib/oxidized/worker.rb: Added Test_Switch to the job queue
Jan 23 22:05:56 server1 oxidized[20381]: lib/oxidized/worker.rb: 1 jobs running in parallel
Jan 23 22:05:56 server1 oxidized[20381]: lib/oxidized/job.rb: Starting fetching process for Test_Switch at 2018-01-23 22:05:56 UTC
Jan 23 22:05:56 server1 oxidized[20381]: lib/oxidized/input/ssh.rb: Connecting to Test_Switch
Jan 23 22:05:56 server1 oxidized[20381]: lib/oxidized/input/ssh.rb: expecting [/\(.*\)\s[#>]/] at Test_Switch
Jan 23 22:05:57 server1 oxidized[20381]: lib/oxidized/worker.rb: 1 jobs running in parallel
Jan 23 22:05:58 server1 oxidized[20381]: lib/oxidized/worker.rb: 1 jobs running in parallel
Jan 23 22:05:58 server1 oxidized[20381]: lib/oxidized/input/cli.rb: Running post_login commands at Test_Switch
Jan 23 22:05:58 server1 oxidized[20381]: lib/oxidized/input/cli.rb: Running post_login command: nil, block: #<Proc:0x0000000295b648@/var/lib/gems/2.1.0/gems/oxidized-0.21.0/lib/oxidized/model/edgeswitch.rb:19> at Test_Switch
Jan 23 22:05:58 server1 oxidized[20381]: lib/oxidized/input/ssh.rb enable @ Test_Switch with expect: /\(.*\)\s[#>]/
Jan 23 22:05:58 server1 oxidized[20381]: lib/oxidized/input/ssh.rb: expecting [/\(.*\)\s[#>]/] at Test_Switch

Then eventually:

Jan 23 22:06:58 server1 oxidized[20381]: 111.222.333.444 raised Timeout::Error with msg "execution expired"
Jan 23 22:06:58 server1 oxidized[20381]: lib/oxidized/node.rb: Oxidized::SSH failed for Test_Switch
Jan 23 22:06:58 server1 oxidized[20381]: lib/oxidized/job.rb: Config fetched for Test_Switch at 2018-01-23 22:06:58 UTC
Jan 23 22:06:59 server1 oxidized[20381]: Test_Switch status no_connection, retry attempt 1
Jan 23 22:06:59 server1 oxidized[20381]: lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 1 of 2
Jan 23 22:06:59 server1 oxidized[20381]: lib/oxidized/worker.rb: Added Test_Switch to the job queue

It doesn't seem to be running the enable command correctly. Is it perhaps getting a prompt it isn't expecting? Let me know if any more information is needed

**Comment by laf** [comment]
You should format your logs in future or use a pastebin service.

Please post formatted config (or use pastebin again). Please also post the prompt from the device.
