### ISSUE TITLE
[feature request] Variable to collect only running configurations

### ISSUE THREAD

**Issue by zombah** [ytti/oxidized#1168]
It will be useful to have config file condition and support within models to collect only running configuration from device without stuff like versions, inventories, licenses etc.

Use case is to have multiple oxidized instances for example one to collect everything but once a day and other to collect only running config but once an hour and by demand from syslog.

**Comment by laf** [comment]
I'm not sure I see the point. If you're having a system logging in once an hour to get the config, what's the problem with it getting the rest of the info? It will only record changes if something has actually changed

**Comment by zombah** [comment]
All these things like hardware inventory, version and licences changes very rare comparing to configuration and i see no reason to check them so often. But if this feature seems not reasonable to add i can revoke my request.

**Comment by laf** [comment]
You can always see if others think it's useful and if someone is willing to code support. I can't say it would be accepted though.
