### ISSUE TITLE
unable to run as a service

### ISSUE THREAD

**Issue by waynemillskidals** [ytti/oxidized#1169]
Hi,

I am able to run oxidized successfully but **not** as a service.

If i run oxidized we can see this runs as expected

```
[root@librenms oxidized]# oxidized
I, [2018-01-28T10:17:25.332912 #13589]  INFO -- : Oxidized starting, running as pid 13589
I, [2018-01-28T10:17:25.333524 #13589]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
I, [2018-01-28T10:17:25.767081 #13589]  INFO -- : lib/oxidized/nodes.rb: Loaded 16 nodes
Puma starting in single mode...
* Version 3.9.1 (ruby 2.0.0-p648), codename: Private Caller
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://127.0.0.1:8888
```

however if we run as a service if fails?

```
[root@librenms oxidized]# systemctl status oxidized -l
● oxidized.service - Oxidized - Network Device Configuration Backup Tool
   Loaded: loaded (/usr/lib/systemd/system/oxidized.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Sun 2018-01-28 10:20:32 GMT; 2min 20s ago
  Process: 21380 ExecStart=/usr/local/bin/oxidized (code=exited, status=1/FAILURE)
 Main PID: 21380 (code=exited, status=1/FAILURE)

Jan 28 10:20:32 librenms.domain.local oxidized[21380]: from /usr/local/share/gems/gems/oxidized-0.21.0/lib/oxidized/core.rb                    :14:in `initialize'
Jan 28 10:20:32 librenms.domain.local oxidized[21380]: from /usr/local/share/gems/gems/oxidized-0.21.0/lib/oxidized/core.rb                    :4:in `new'
Jan 28 10:20:32 librenms.domain.local oxidized[21380]: from /usr/local/share/gems/gems/oxidized-0.21.0/lib/oxidized/core.rb                    :4:in `new'
Jan 28 10:20:32 librenms.domain.local oxidized[21380]: from /usr/local/share/gems/gems/oxidized-0.21.0/lib/oxidized/cli.rb:                    12:in `run'
Jan 28 10:20:32 librenms.domain.local oxidized[21380]: from /usr/local/share/gems/gems/oxidized-0.21.0/bin/oxidized:9:in `<                    top (required)>'
Jan 28 10:20:32 librenms.domain.local oxidized[21380]: from /usr/local/bin/oxidized:23:in `load'
Jan 28 10:20:32 librenms.domain.local oxidized[21380]: from /usr/local/bin/oxidized:23:in `<main>'
Jan 28 10:20:32 librenms.domain.local systemd[1]: oxidized.service: main process exited, code=exited, status=1/FAILURE
Jan 28 10:20:32 librenms.domain.local systemd[1]: Unit oxidized.service entered failed state.
Jan 28 10:20:32 librenms.domain.local systemd[1]: oxidized.service failed.
```

here is output of this file /usr/local/bin/oxidized

```
[root@librenms oxidized]# cat /usr/local/bin/oxidized
#!/usr/bin/ruby
#
# This file was generated by RubyGems.
#
# The application 'oxidized' is installed as part of a gem, and
# this file is here to facilitate running it.
#

require 'rubygems'

version = ">= 0"

if ARGV.first
  str = ARGV.first
  str = str.dup.force_encoding("BINARY") if str.respond_to? :force_encoding
  if str =~ /\A_(.*)_\z/
    version = $1
    ARGV.shift
  end
end

gem 'oxidized', version
load Gem.bin_path('oxidized', 'oxidized', version)
```

any ideas guys what im doing wrong??

Thanks

**Comment by laf** [comment]
I'm wondering if you have multiple binaries installed. Try running `/usr/local/bin/oxidized` manually rather than just `oxidized`.

Also what's the output of `gem list`

**Comment by waynemillskidals** [comment]
Hi @laf 

I can run it as you suggested without any issues

[root@librenms ~]# /usr/local/bin/oxidized

I, [2018-02-05T12:15:48.009004 #31875]  INFO -- : Oxidized starting, running as pid 31875
I, [2018-02-05T12:15:48.010753 #31875]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
I, [2018-02-05T12:15:48.573159 #31875]  INFO -- : lib/oxidized/nodes.rb: Loaded 16 nodes
Puma starting in single mode...
* Version 3.9.1 (ruby 2.0.0-p648), codename: Private Caller
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://127.0.0.1:8888
Use Ctrl-C to stop

below is an output of my gem list

[root@librenms ~]# gem list

*** LOCAL GEMS ***

asetus (0.3.0)
backports (3.8.0)
bigdecimal (1.2.0)
emk-sinatra-url-for (0.2.1)
ffi (1.9.18)
haml (4.0.7)
htmlentities (4.3.4)
io-console (0.4.2)
json (1.7.7)
multi_json (1.12.1)
net-ssh (4.1.0, 3.0.2)
net-telnet (0.1.1)
oxidized (0.21.0, 0.20.0)
oxidized-script (0.5.0, 0.4.0)
oxidized-web (0.9.3, 0.9.2)
psych (2.0.0)
puma (3.9.1)
rack (1.6.8)
rack-protection (1.5.3)
rack-test (0.7.0)
rb-fsevent (0.10.2)
rb-inotify (0.9.10)
rdoc (4.0.0)
rugged (0.26.0)
sass (3.5.1)
sass-listen (4.0.0)
sinatra (1.4.8)
sinatra-contrib (1.4.7)
slop (3.6.0)
tilt (2.0.8)
[root@librenms ~]#

Any ideas?

Thanks

**Comment by laf** [comment]
What user is the service script running oxidized as?

**Comment by waynemillskidals** [comment]
think thats the issue
/lib/systemd/system/oxidized.service
user was set as oxidized , i changed to root and now appears to be working 👍
