### ISSUE TITLE
comware 3com prompt parse error

### ISSUE THREAD

**Issue by aTanCS** [ytti/oxidized#1171]
When I login to all our 3COM switches I get this type of output. Prompt is always above the last login info line. That's why I guess prompt detection doesn't work. After 'enter' key is pressed the prompt is on the first line. Is it possible to send 'enter' before prompt detection or fix prompt regex?
switch:
```
********************************************************************************
*  Copyright(c) 2004-2009 3Com Corp. and its licensors. All rights reserved.   *
*  Without the owner's prior written consent,                                  *
*  no decompiling or reverse-engineering shall be allowed.                     *
********************************************************************************

<sw-test-3com>
%Jun 17 15:35:31:872 2000 sw-test-3com SHELL/5/LOGIN:- 1 - xxx(x.x.x.x) in unit1 login
```
oxidized
```
raised Oxidized::PromptUndetect with msg "unable to detect prompt: (?-mix:^\0*(<[\w.-]+>)$)"
```

**Comment by laf** [comment]
Is this not something to do with logging in the console? If so, it looks like it would be better for you to disable that so it's not printed out in the first place.

**Comment by tracerrx** [comment]
If you comment out the below line in comware.rb file it will work fine... 

#cfg.gsub! /^.*\e\[42D/, ''        # example how to handle pager

**Comment by aTanCS** [comment]
@laf it is a default behavior, but it can be disabled by
```
info-center source default channel 1 log state off debug state off
```
but there just too many such switches to reconfigure them all manually. So this is my plan B solution.

@tracerrx this line is already commented out in original source files.

**Comment by laf** [comment]
We don't have a pre_login function in models so I'm not sure how possible this.

**Comment by aTanCS** [comment]
I've managed to disable log printing in all switches using ssh batch script, so I guess it can be closed, if it is not possible to process in oxidized.

**Comment by laf** [comment]
I've added a model note about this OS for people to configure the devices correctly.
