### ISSUE TITLE
Probleme to login into AsyncOS 

### ISSUE THREAD

**Issue by emiliien** [ytti/oxidized#1172]
Hello everybody,
Oxidized cannot login into our ESA. I don't think it's a big deal but it's annoying.

logs :
```
W, [2018-01-31T16:06:47.205395 #768]  WARN -- : 172.16.2.101 raised Oxidized::PromptUndetect with msg "AsyncOS 11.0.0 for Cisco C190 build 274

Welcome to the Cisco C190 Email Security Appliance

NOTE: This session will expire if left idle for 30 minutes. Any uncommitted
configuration changes will be lost. Commit the configuration changes as soon as
they are made.

(Machine mail01.XXXX-XXXXXXX.com)>  not matching configured prompt (?-mix:^\r*([(][\w. ]+[)][#>]\s+)$)"
D, [2018-01-31T16:06:47.205985 #768] DEBUG -- : lib/oxidized/node.rb: Oxidized::SSH failed for ESA
D, [2018-01-31T16:06:47.206136 #768] DEBUG -- : lib/oxidized/job.rb: Config fetched for ESA at 2018-01-31 15:06:47 UTC
W, [2018-01-31T16:06:48.017745 #768]  WARN -- : ESA status no_connection, retry attempt 1
D, [2018-01-31T16:06:48.017838 #768] DEBUG -- : lib/oxidized/worker.rb: Jobs 0, Want: 1
D, [2018-01-31T16:06:48.018145 #768] DEBUG -- : lib/oxidized/worker.rb: Added ESA to the job queue
D, [2018-01-31T16:06:48.018184 #768] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2018-01-31T16:06:48.018371 #768] DEBUG -- : lib/oxidized/job.rb: Starting fetching process for ESA at 2018-01-31 15:06:48 UTC
D, [2018-01-31T16:06:48.018838 #768] DEBUG -- : lib/oxidized/input/ssh.rb: Connecting to ESA
D, [2018-01-31T16:06:48.212468 #768] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^\r*([(][\w. ]+[)][#>]\s+)$/] at ESA
D, [2018-01-31T16:06:49.018359 #768] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2018-01-31T16:06:50.018653 #768] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2018-01-31T16:06:51.018951 #768] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2018-01-31T16:06:52.019220 #768] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2018-01-31T16:06:53.019527 #768] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2018-01-31T16:06:54.019833 #768] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel

```
Can you help me ? 
Have nice day.

**Comment by laf** [comment]
This is because it's not matching your prompt.

With the user you start oxidized with `mkdir .config/model && cd .config/model` then `wget https://raw.githubusercontent.com/ytti/oxidized/master/lib/oxidized/model/asyncos.rb`

Edit `asyncos.rb` and change the `prompt` line near the top for:

`prompt /^\r*([(][\w. \-]+[)][#>]\s+)$/`

**Comment by emiliien** [comment]
Hi .
Thx a lot 
Login works better ! 
I really don't understand how the prompt works. -_-'

But my equipement don't want to be backup.
i've got a new probleme ....


`
/var/lib/gems/2.1.0/gems/oxidized-0.19.0/lib/oxidized# oxidized
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://0.0.0.0:443
D, [2018-01-31T21:10:03.914642 #1453] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^\r*([(][\w. \-]+[)][#>]\s+)$/] at ESA
D, [2018-01-31T21:10:04.721844 #1453] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2018-01-31T21:10:05.722099 #1453] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2018-01-31T21:10:06.722396 #1453] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2018-01-31T21:10:07.722710 #1453] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2018-01-31T21:10:07.928321 #1453] DEBUG -- : lib/oxidized/input/cli.rb: Running post_login commands at ESA
D, [2018-01-31T21:10:07.928498 #1453] DEBUG -- : lib/oxidized/model/model.rb Collecting commands' outputs
D, [2018-01-31T21:10:07.928666 #1453] DEBUG -- : lib/oxidized/model/model.rb Executing version
D, [2018-01-31T21:10:07.928786 #1453] DEBUG -- : lib/oxidized/input/ssh.rb version @ ESA with expect: /^\r*([(][\w. \-]+[)][#>]\s+)$/
D, [2018-01-31T21:10:07.928995 #1453] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^\r*([(][\w. \-]+[)][#>]\s+)$/] at ESA
D, [2018-01-31T21:10:08.723001 #1453] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2018-01-31T21:10:09.436588 #1453] DEBUG -- : lib/oxidized/model/model.rb Executing showconfig
D, [2018-01-31T21:10:09.436766 #1453] DEBUG -- : lib/oxidized/input/ssh.rb showconfig @ ESA with expect: /^\r*([(][\w. \-]+[)][#>]\s+)$/
D, [2018-01-31T21:10:09.436996 #1453] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^\r*([(][\w. \-]+[)][#>]\s+)$/] at ESA
D, [2018-01-31T21:10:09.723273 #1453] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2018-01-31T21:10:10.723555 #1453] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2018-01-31T21:10:11.723851 #1453] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2018-01-31T21:10:12.724026 #1453] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2018-01-31T21:10:13.724211 #1453] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2018-01-31T21:10:14.724500 #1453] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2018-01-31T21:10:15.724778 #1453] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2018-01-31T21:10:16.724981 #1453] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2018-01-31T21:10:17.725272 #1453] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2018-01-31T21:10:18.725469 #1453] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2018-01-31T21:10:19.725696 #1453] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2018-01-31T21:10:20.725949 #1453] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2018-01-31T21:10:21.726200 #1453] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2018-01-31T21:10:22.726424 #1453] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2018-01-31T21:10:23.726703 #1453] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2018-01-31T21:10:24.726996 #1453] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2018-01-31T21:10:25.727219 #1453] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2018-01-31T21:10:26.727423 #1453] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2018-01-31T21:10:27.727685 #1453] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2018-01-31T21:10:28.727873 #1453] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
W, [2018-01-31T21:10:29.437555 #1453]  WARN -- : 172.16.2.101 raised Timeout::Error with msg "execution expired"
D, [2018-01-31T21:10:29.437790 #1453] DEBUG -- : lib/oxidized/node.rb: Oxidized::SSH failed for ESA
D, [2018-01-31T21:10:29.437978 #1453] DEBUG -- : lib/oxidized/job.rb: Config fetched for ESA at 2018-01-31 20:10:29 UTC
W, [2018-01-31T21:10:29.728285 #1453]  WARN -- : ESA status no_connection, retry attempt 1
D, [2018-01-31T21:10:29.728365 #1453] DEBUG -- : lib/oxidized/worker.rb: Jobs 0, Want: 1
D, [2018-01-31T21:10:29.729120 #1453] DEBUG -- : lib/oxidized/worker.rb: Added ESA to the job queue
D, [2018-01-31T21:10:29.729208 #1453] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2018-01-31T21:10:29.729419 #1453] DEBUG -- : lib/oxidized/job.rb: Starting fetching process for ESA at 2018-01-31 20:10:29 UTC
D, [2018-01-31T21:10:29.729761 #1453] DEBUG -- : lib/oxidized/input/ssh.rb: Connecting to ESA
D, [2018-01-31T21:10:29.914027 #1453] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^\r*([(][\w. \-]+[)][#>]\s+)$/] at ESA
D, [2018-01-31T21:10:30.729431 #1453] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2018-01-31T21:10:31.729771 #1453] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
`

**Comment by laf** [comment]
Have you tested from the cli that you can login to this device using the credentials in your config / source?

**Comment by emiliien** [comment]
yes. I have no problem to connect ssh on ESA from the oxidized server.


`root@Oxidized:~/.config/oxidized# ssh user@172.16.2.101
Password for user@mail01.XXXXXXX-XXXXXXX.com:
AsyncOS 11.0.0 for Cisco C190 build 274

Welcome to the Cisco C190 Email Security Appliance

NOTE: This session will expire if left idle for 30 minutes. Any uncommitted configuration changes will be lost. Commit the configuration changes as soon as they are made.

(Machine mail01.XXXXXXX-XXXXXXX.com)>
`

**Comment by laf** [comment]
How long does showconfig take to run on the device itself?

**Comment by emiliien** [comment]
maybe around 3-4 seconds

**Comment by BaaptM** [comment]
Hi @emiliien,

I had the same issue. Modifying the prompt regex is not enough for Ironport appliance, you have to increase your timeout parameter in your config file, mine is 60 and it works!

Hope that will help.

**Comment by emiliien** [comment]
\o/ Thx !
It's works !!! 
Well done =) 
have a nice day

**Comment by hellEVIL-13** [comment]
Apr 11 16:10:35 cvs oxidized[27083]: IP.X.X.X raised Oxidized::PromptUndetect with msg "Last login: Wed Apr 11 16:07:43 2018 from IP.X.X.X#015#015#012AsyncOS 11.0.1 for Cisco IronPort C170 build 027#015#012#015#012Welcome to the Cisco IronPort C170 Messaging Gateway(tm) Appliance#015#012#015#012NOTE: This session will expire if left idle for 30 minutes. Any uncommitted#015#012configuration changes will be lost. Commit the configuration changes as soon as#015#012they are made.#015#012#015#012ironport.domen.ru>  not matching configured prompt (?-mix:^\r*([(][\w. ]+[)][#>]\s+)$)"

Apr 11 16:10:35 cvs oxidized[27083]: IP.X.X.X raised Oxidized::PromptUndetect with msg "Last login: Wed Apr 11 16:07:43 2018 from IP.X.X.X#015#015#012AsyncOS 11.0.1 for Cisco IronPort C170 build 027#015#012#015#012Welcome to the Cisco IronPort C170 Messaging Gateway(tm) Appliance#015#012#015#012NOTE: This session will expire if left idle for 30 minutes. Any uncommitted#015#012configuration changes will be lost. Commit the configuration changes as soon as#015#012they are made.#015#012#015#012ironport.domen.ru>  not matching configured prompt (?-mix:^\r*([(][\w. \-]+[)][#>]\s+)$)"
