### ISSUE TITLE
Cisco ASA: Not Matching Prompt

### ISSUE THREAD

**Issue by Fhajad** [ytti/oxidized#1174]
So Cisco ASA's are a bit goofy as everyone knows in comparison to their IOS friends. After logging it, it just gives "localname> " waiting.

Any idea how to modify so I can backup normal IOS along side ASAs?

**Comment by laf** [comment]
I backup 3000+ ASAs with zero issues. You should enable debugging and post the logs.

**Comment by Fhajad** [comment]
I tried to enable logs but it doesn't seem to make any files. All I got is what /var/log/syslog shows. Also I've sanitized the fuck out of it. I'm thinking it's something to do with the banner message or the hostname since the "with msg "CUSTOMER part, the "CUSTOMER I've sanitized down is in both items.

```
Feb  5 15:50:41 BLAHBLAH-Pi oxidized[437]: IP_GOES_HERE raised Net::OpenTimeout (rescued Timeout::Error) with msg "timed out while opening a connection to the host"
Feb  5 15:50:42 BLAHBLAH-Pi oxidized[437]: FQDN_GOES_HERE status no_connection, retry attempt 3
Feb  5 15:51:02 BLAHBLAH-Pi oxidized[437]: IP_GOES_HERE raised Oxidized::PromptUndetect with msg "CUSTOMER
JUST BANNER INFO FROM THE ASA LOGIN PAY NO MIND TO IT HERE JUST TEXT AND SPACES
Type help or '?' for a list of available commands.
CUSTOMER-FW1>  not matching configured prompt (?-mix:^([\w.@()-]+[#>]\s?)$)"
Feb  5 15:51:22 BLAHBLAH-Pi oxidized[437]: IP_GOES_HERE raised Net::OpenTimeout (rescued Timeout::Error) with msg "timed out while opening a connection to the host"
Feb  5 15:51:23 BLAHBLAH-Pi oxidized[437]: FQDN_GOES_HERE status no_connection, retries exhausted, giving up

```

Here's my config for examination as well:

```
username: DONOTSTEAL
password: PLZDONT
model: ios
interval: 3600
use_syslog: true
debug: false
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: URMAMA:8888
next_adds_job: false
hooks:
  slack:
    type: slackdiff
    events: [post_store,node_fail]
    token: JUSTNONSENESHERE
    channel: "#MORENONSENSEWHOCARES"
#  push_to_remote:
#    type:githubrepo
#    events: [nodes_done]
#    remote_repo:
#    username:
#    password:
vars:
   enable: PLZDONT
groups: {}
models: {}
pid: "/home/oxidized/.config/oxidized/pid"
log: "/home/oxidized/.config/oxidized/logs"
input:
  default: ssh, telnet
  debug: false
  ssh:
    secure: false
output:
  default: git
  git:
    user: Oxidized
    email: o@example.com
    repo: "/var/lib/oxidized/devices.git"
source:
  default: csv
  csv:
    file: "/home/oxidized/.config/oxidized/router.db"
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
    gpg: false
model_map:
  cisco: ios
  juniper: junos

```

**Comment by laf** [comment]
So the prompt matches the text you posted. Use http://rubular.com/ to test.

**Comment by Fhajad** [comment]
So based on where it is in the log, it looks like it's failing to exec up and the prompt does pass when I double check it. Yet when it runs, it's hanging up.

I removed the customers banner just to eliminate it by any chance, still getting "not matching configured prompt" though on "CUSTOMER-FW1>".

**Comment by laf** [comment]
Your config btw has debug: false, you need to set those to true.

**Comment by Fhajad** [comment]
I have debug set to true for the top, and debug set to true for input, and the log path specified in quotes (and without for fun) bit it never creates the log.

**Comment by laf** [comment]
The config you posted above shows is as false. If you're sure that you've actually got it enabled then fine.

Provide the asa firmware version, configured prompt and if you use tacacs or local users and I'll try and replicate

**Comment by Fhajad** [comment]
9.4(2)11
Prompt is IHEN-FW1>
Local users

I'm seeing up a local Pi as well to keep as a test on my internal network to try my local ASA's as well.

**Comment by Fhajad** [comment]
Okay I finally got debug to work (Reboot three times every time), and went back and double checked everything and found where one of my guys set to ios instead of ASA. After changing that and increasing the timeout, that fixed it.

Sorry for all the hassle.

**Comment by laf** [comment]
No problem, glad you got it all sorted.
