### ISSUE TITLE
Oxidized-0.21 errors out when starting

### ISSUE THREAD

**Issue by papatango71** [ytti/oxidized#1177]
I installed a new version of oxidized on a new NMS server and have not been able to get it to start.  I am getting the following error:

oxidized@las1-admin-inf01
[/home/oxidized/.config/oxidized]$ oxidized
Error loading config: (<unknown>): found character that cannot start any token while scanning for the next token at line 49 column 15
/usr/local/share/gems/gems/oxidized-0.21.0/lib/oxidized/config.rb:53:in `rescue in load': Error loading config: (<unknown>): found character that cannot start any token while scanning for the next token at line 49 column 15 (Oxidized::InvalidConfig)
	from /usr/local/share/gems/gems/oxidized-0.21.0/lib/oxidized/config.rb:50:in `load'
	from /usr/local/share/gems/gems/oxidized-0.21.0/lib/oxidized/cli.rb:24:in `initialize'
	from /usr/local/share/gems/gems/oxidized-0.21.0/bin/oxidized:9:in `new'
	from /usr/local/share/gems/gems/oxidized-0.21.0/bin/oxidized:9:in `<top (required)>'
	from /usr/local/bin/oxidized:23:in `load'
	from /usr/local/bin/oxidized:23:in `<main>'

Any help to get around this would be greatly appreciated.

**Comment by laf** [comment]
Looks like a config issue, if you use librenms you can paste it into the validator within that or just use a normal yaml validator online.

This is best discussed in the forum or gitter as it's not a bug in oxidized
