### ISSUE TITLE
Issues pulling configuration from D-Link DGS-3627G, DES-3028

### ISSUE THREAD

**Issue by KindEvilDm** [ytti/oxidized#1179]
Oxidized can't pull configuration from D-Link DGS-3627G, DES-3028. 
Log from 3200 model(witch works ok):
```
Trying 10.90.90.90...
Connected to 10.90.90.90.
                       DES-3200-26 Fast Ethernet Switch
                            Command Line Interface
UserName:admin
PassWord:******

DES-3200-26:admin#disable clipaging
```
Log from DGS-3627G:
```
Trying 10.90.90.91...
Connected to 10.90.90.91.
                      DGS-3627G Gigabit Ethernet Switch
                            Command Line Interface
UserName:admin
PassWord:*******
Fail!
UserName:
Fail!
UserName:
Fail!
```
Look at the Password line. Password is the same, but in case of DGS-3627G there is one more symbol in log.

I remember the same trouble in python scripts, and the workaround was:
```
def bulk(self, cmd, opt):  # d-link console workaround
    pass

tn = telnetlib.Telnet(host, 23, tn_timeout)
tn.set_option_negotiation_callback(bulk)  # d-link console workaround

```

I don't know ruby, and I can't fix it by myself..
Any help to resolve this problem would be greatly appreciated.
Thanks.

**Comment by laf** [comment]
Can you please post the raw logs from oxidized debug being enabled?

Are you sure it's not using a different password?

**Comment by KindEvilDm** [comment]
Suddenly, pulling from DGS-3627G is working now.. But 3028 still have a problem.

https://pastebin.com/PKRQhDx1 here is oxidized log
Password is the same, I'm sure.
Again, log from ./config/oxidized/logs for this device: 
```
DES-3028 
------------------------
No public services.
Disconnect please.
------------------------
UserName:admin
PassWord:*******
Fail!

```
There are too much symbols in password.

**Comment by laf** [comment]
In that output `10.90.90.90` isn't detecting the prompt. Are you using a custom model for dlink out of interest?

Can you post what a normal login session looks like to that device from you manually connecting?

**Comment by KindEvilDm** [comment]
This is the normal login session looks like:
```
DES-3028 
------------------------
No public services.
Disconnect please.
------------------------
UserName:admin
PassWord:******

DES-3028:5#

```
It isn't detecting the prompt because it's getting "Fail!" instead of "DES-3028:5#" (because of wrong password)
I'm using a custom model with only one modification:
```
  cfg :telnet do
    username /\r*?[uU]ser?[nN]ame:/
    password /\r*?[pP]ass?[wW]ord:/
  end
```
In default oxidized dlink.rb it looks only for "Username" and "Password", but a half of D-Link models shows "UserName" and "PassWord".

**Comment by KindEvilDm** [comment]
Some new info about this situation.
Sometimes oxidized send wrong password, sometimes all ok. 
Logs:

```
W, [2018-02-08T17:15:21.077224 #20159]  WARN -- : 10.90.0.149 raised Oxidized::PromptUndetect with msg "unable to detect prompt: (?-mix:^(\r*[\w.@():-]+[#>]\s?)$)"
W, [2018-02-08T17:15:21.992325 #20159]  WARN -- : 10.90.0.149 status no_connection, retry attempt 1
I, [2018-02-08T17:15:27.018913 #20159]  INFO -- : Configuration updated for access/10.90.0.149
```

```
Trying 10.90.0.149...
Connected to 10.90.0.149.
              DES-3028 Fast Ethernet Switch Command Line Interface
                            Firmware: Build 2.54.B03
           Copyright(C) 2008 D-Link Corporation. All rights reserved.
UserName:admin
PassWord:*******
Fail!

Trying 10.90.0.149...
Connected to 10.90.0.149.
              DES-3028 Fast Ethernet Switch Command Line Interface
                            Firmware: Build 2.54.B03
           Copyright(C) 2008 D-Link Corporation. All rights reserved.
UserName:admin
PassWord:******

DES-3028:5#disable clipaging
Command: disable clipaging

Success.  
```
Do you have any idea what's going on?

**Comment by laf** [comment]
It seems odd that the wrong password is being sent, post your config so we can see what source you are using and the config for that.

**Comment by KindEvilDm** [comment]
https://pastebin.com/d56c3PR2 there is oxidized config
router.db looks like
```
10.90.0.149:dlink:access
...
...
```

**Comment by laf** [comment]
Seems fine to me. Would you be able to give access to one of these units for testing?

**Comment by KindEvilDm** [comment]
Sorry, I can't give you access. I only can give additional info, logs, etc..
Interesting, with increasing retries counter, there is more chance for oxidized to send right password. (like in [logs](https://github.com/ytti/oxidized/issues/1179#issuecomment-364127820))
Seems problem is partly "solved".. (I guess D-Link - is problem, by itself, again =) )
If you don't need any additional info, maybe we may close this issue.

Anyway, thank you, @laf  for your attention and help.

**Comment by laf** [comment]
@KindEvilDm No problem. I don't really see how oxidized can send varying passwords on retries, that's really odd. It's the first report of this afaik so I'm happy that we pass the buck to D-Link until we hear from others :)

**Comment by L0llipop** [comment]
I also faced this problem. I found a difference in the tcpdump when sending a password:
python telnetlib
`password\n`
oxidized
``password\r\n``
I thing need to remove the simbol "\r" for model DES3526, DES3528.

**Comment by M3D3** [comment]
Hey, everybody! Same problem with Dlink 3200 . Characters in the password is more than one.

**^[[0m^[[2J^[[1;1H^[[2J^MD^M
^M DES-3200-10 Fast Ethernet Switch
^M Command Line Interface

^M Firmware: Build 1.52.B010
^M Copyright(C) 2010 D-Link Corporation. All rights reserved.
^M^MUsername:oxydized
^M^MPassword:***********
^MFail!
^M^MUsername:**

**Comment by AntonBelogolovskiy** [comment]
Hello!
I found a solution to the problem with D-Link.
Necessary before entering a login, password, etc. type Backspace (\b).
To do this, I corrected the /lib/oxidized/input/telnet.rb code:

def cmd(cmd_str, expect = @node.prompt)
      Oxidized.logger.debug "Telnet: #{cmd_str} @#{@node.name}"
      # Send 'Backspace' before command for some D-Link issues
      send("\b\b\b")
      #
      return send(cmd_str + "\r\n") unless expect

      # create a string to be passed to oxidized_expect and modified _there_
      # default to a single space so it shouldn't be coerced to nil by any models.

      out = String(' ')
      @telnet.puts(cmd_str)
      @telnet.oxidized_expect(timeout: @timeout, expect: expect, out: out)
      out
    end

**Comment by AntonBelogolovskiy** [comment]
Hello!
I found a solution to the problem with D-Link.
Necessary before entering a login, password, etc. type Backspace (\b).
To do this, I corrected the /lib/oxidized/input/telnet.rb code:

def cmd(cmd_str, expect = @node.prompt)
  Oxidized.logger.debug "Telnet: #{cmd_str} @#{@node.name}"
  #Send some 'Backspaces' before command for some D-Link issues
  send("\b\b\b")

  return send(cmd_str + "\r\n") unless expect
...
...

Everything is working fine now.
