### ISSUE TITLE
Request feature to trigger config download per-device

### ISSUE THREAD

**Issue by cfiske** [ytti/oxidized#118]
Would like the ability to tell Oxidized when a device's config has changed (as indicated by the device sending a syslog message or SNMP trap to a monitoring system) and cause it to immediately retrieve the updated config for that device only.

Ideally, also to be able to configure 'interval' on a per-model level. So we can make the interval short for models which do not support the above (sending a message on config change), and long for those which do.

**Comment by ytti** [comment]
Have you looked into this https://github.com/ytti/oxidized/blob/master/extra/syslog.rb
Does it look like something which works for you?

per-model interval is not supported right now, and 5s thought says it won't be 100% straightforward.

**Comment by cfiske** [comment]
Thanks, I had missed that. Though reading through the code there it seems like a direct call to /node/next/<device> would trigger a refresh.

Understood on the per-model interval bit. It's more of a nice-to-have than a need.

**Comment by ytti** [comment]
Yes, it's up-to-you how to trigger it. Syslog was just given as an example how to do it. It also has the added benefit that it'll add the user name as committer. So if 'cfiske' made change in ios/junos, you'd see that in git commits as well. So doing 'git blame' would so line-by-line who made each line.
