### ISSUE TITLE
ERROR:  Error installing oxidized-web:         ERROR: Failed to build gem native extension.

### ISSUE THREAD

**Issue by NetSec33** [ytti/oxidized#1184]
Hello.
I'm searching a solution at my problem. I try to install Oxidized, but when i try to install oxidized-web, i have an error message:
![2018-02-12 17_02_01-bs5lib1fr](https://user-images.githubusercontent.com/36415064/36106037-81837124-1016-11e8-95a4-24826ba703aa.png)
Somebody can help me?

**Comment by laf** [comment]
Duplicate: https://github.com/ytti/oxidized-web/issues/154
