### ISSUE TITLE
input (ssh | telnet) based on group... is it possible?

### ISSUE THREAD

**Issue by banananananananana** [ytti/oxidized#1185]
I'm trying to force oxidzed to use telnet for certain older models in my network.

my default input settings looks like this:
```
input:
  default: ssh
  debug: true
  ssh:
    secure: false
```

then i have a group called "cisco-telnet" for older devices that only use telnet:

```
groups:
  cisco-telnet:
    username: read_only
    password: kijaiosdh8i8acbnlhsai
    vars:
      enable: kjhasdkjghiasgd
    input:
     default: telnet
     debug: true
```

No matter what i do or try, oxidized keeps trying SSH to the cisco-telnet group. I have confirmed that the devices are indeed in that group. 

Any pointers?

**Comment by laf** [comment]
Why not just do:

```yaml
input:
  default: ssh, telnet
```
That way ssh will be tried and then it falls back to telnet.

**Comment by banananananananana** [comment]
Tried that as well.
@laf that was the first thing i tried actually.

this still only produces an empty ssh-debug log. 

it seems oxidized doesn't even try telnetting to the box.

the box in question:
```
oxidized$ telnet 172.24.0.50 22
Trying 172.24.0.50...
telnet: Unable to connect to remote host: Connection timed out

oxidized$ telnet 172.24.0.50 23
Trying 172.24.0.50...
Connected to 172.24.0.50.
Escape character is '^]'.


User Access Verification

Username:

```

**Comment by laf** [comment]
What is the model for this?

We use that config fine with devices that have a mix of ssh/telnet still so it does work but is still model dependent iirc.

**Comment by banananananananana** [comment]
@laf it's for a very old cisco asa.

**Comment by banananananananana** [comment]
@laf are you telling me that i should add the telnet stuff from the ios.rb, to my asa.rb file?

**Comment by laf** [comment]
Correct, the asa model doesn't have telnet support. Didn't even realise you could enable it!

**Comment by banananananananana** [comment]
@laf hahahahaha<laughing turns into crying>buhuhuhuhuhuhuhu

I'll hack something together real quick.  Librenms style.

Btw, are you the new maintainer for oxidized? If so, where do I send the beers?

**Comment by laf** [comment]
I've just been helping out, I believe some people from github themselves are taking over maintainership.

**Comment by laf** [comment]
@banananananananana Can this issue be closed btw?

**Comment by banananananananana** [comment]
@laf oxidized is doing its thang with the new asa.rb file.

let me update the ticket with a (i hope) solution for future hackers.

**Comment by banananananananana** [comment]
@laf it worked. 

thank you.

for future generations, this is what my asa.rb file looks like;


added this:
```
  cfg :telnet do
    username /^Username:/i
    password /^Password:/i
  end
```

inserted :telnet, before :ssh do.
```
  cfg :telnet, :ssh do
    if vars :enable
      post_login do
        send "enable\n"
        cmd vars(:enable)
      end
    end
    post_login 'terminal pager 0'
    post_login 'terminal length 0'
    post_login 'terminal width 0'
    pre_logout 'exit'
  end
```

**Comment by laf** [comment]
Thanks for reporting back.

**Comment by chasgames** [comment]
Thanks for posting @banananananananana  this helped me too.
