### ISSUE TITLE
Login/Secure Page

### ISSUE THREAD

**Issue by Fhajad** [ytti/oxidized#1187]
I haven't found the option if there is one already, but having some sort of option to make it so you have to give some combination of username/password to view Oxidizer screen (At least the configs the first time, then store a session) would be great for some networks. As it is, it's very easy to get access to full configs.

**Comment by laf** [comment]
This is for oxidized-web really.

https://github.com/ytti/oxidized-web/issues/106

Most people will just use a proxy in front to deal with this.
