### ISSUE TITLE
Running a Master / Slave configuration

### ISSUE THREAD

**Issue by jameskirsop** [ytti/oxidized#1189]
I've got a bunch of nodes running Oxidized at various customer sites. They're all linked back to a centralised monitoring server via an OpenVPN tunnel.

Is it possible to have Oxidized, at each of the remote nodes, send the data back to Oxidized running on the central monitoring server so that they're all collated and accessible from a single point (and GUI with [Oxidized-Web](https://github.com/ytti/oxidized-web)).

It'd be great if there was an 'Oxidized' output and input so that nodes could send changes to each other. Perhaps this already exists, but I can't seem to discern a way of achieving this from what I can see in the docs.

**Comment by laf** [comment]
That isn't something that's possible at present.

Does each site need a local install for clients to interact with? If not, why not just run one and use a proxy in the each site to handle the customer devices?

**Comment by jameskirsop** [comment]
@laf, yeah, we were looking at the proxy option - and it seems like it would be a suitable option for most circumstances. It will certainly get us to where we want to be in the interim.

I was thinking along the lines of doing something like what we're doing with rsyslog and running it on nodes and then pumping back particular events of more significant importance to the master monitoring system for processing and distribution (again via rsyslog).

In a similar way, we don't need to backup every single node to the master, but being able to have more critical devices always being backed up and diff'd would be useful, and having easy access to the backups of all devices whilst at a customers site would too be useful.

It's pretty low down on the priority list, but certainly a nice to have!

**Comment by laf** [comment]
If you output to git, why not push all nodes back to a different repo so you have say gitlab as the overview and can access all the configs in one place at least (different repos though I'm guessing).
