### ISSUE TITLE
Changes found on Cisco 3750-X on each run

### ISSUE THREAD

**Issue by olivierbeytrison** [ytti/oxidized#1190]
Hello,

Each time Oxidized run over a particular switch (Cisco 3750-X running 15.2(4)E5) it detects a weird change.

Here's the output of the git diff we receive per mail every 15 minutes :

```
diff --git a/eifrsxxxxxxxxxxxxxxxxh b/eifrxxxxxxxxxxxxxhefr.ch
index c6ac726..38b812e 100644
--- a/eifrswxxxxxxxxxxxxxxexr.ch
+++ b/eifxxxxxxxxxxxxxxxxxxr.ch
@@ -11,7 +11,7 @@
 ! 
 !
 ! Last configuration change at 18:01:22 UTC Tue Feb 13 2018 by matxxxxxu.xxxxer
-! NVRAM config last updated at 07:02:17 UTC Tue Feb 20 2018 by rancid
+! NVRAM config last updated at 07:27:07 UTC Tue Feb 20 2018 by rancid
 !
 version 15.2
 no service pad

```
Anyone did already encounter this issue ?

Oxidized is running the 0.21.0 release

**Comment by ecm75** [comment]
Yes, I encountered this issue as well.
Is seems some devices (especially clusters) sync and save the configs regularly in certain time intervalls, thus resulting in different timestamps, which cause a config save each time the device is queried by oxidized.
Either turn off the autosave function if possible (not advised!) or simply add a regex to the module to ignore the line.

**Comment by olivierbeytrison** [comment]
well it's a cisco switch. I've enabled the debug output of the ssh section and it does nothing special comparing to the other 100 switches.

But on this one the NVRAM config change match the previous run of Oxidized. Very weird. But the problem comes not from Oxidized imho.

**Comment by laf** [comment]
Yeah we see the same thing. Also happens on Cisco ASA's as well.

I was going to update the model to filter that line out for us. I'm not sure if it's something that should be in the core model or not - is that line useful to people when an actual full config change has happened?

**Comment by olivierbeytrison** [comment]
well it's an interesting line to see if someone changed the running config (and didn't save it to the startup config).

The best thing would be to ignore the line if it contains the username used by Oxidized to get the conf

What would be the config to add to ignore this line ?

**Comment by laf** [comment]
Untested and I'm not a ruby dev but:

```
    cfg.gsub! /! Last configuration change at * by oxidized/, ''
    cfg.gsub! /! NVRAM config last updated at * by oxidized/, ''
```

After: `cfg = cfg.reject { |line| line.match /^ntp clock-period / }.join` in ios.rb

**Comment by olivierbeytrison** [comment]
Thanks laf!

adding 
```
    cfg.gsub! /^! NVRAM config[^\n]*rancid/, ''
```
solved my issue :)
