### ISSUE TITLE
Sonicwalls not working - AOSW module used to work for some models, now none work.

### ISSUE THREAD

**Issue by tnielsen2** [ytti/oxidized#1191]
Are these "officially" supported? I see nothing in the supported platforms section, but figured I would give this a shot. 

Sonicwall used to be owned by Dell, and I am not sure if some of the module logic worked for certain software modules or not, but it would be great if I can help get this off of the ground.  It appears that some models cannot get past the password prompt, while others (using the same AOSW module that used to work at one point in time) can successfully login, but are unable to parse the data. 

The "show tech-support-report' command is the best information that can be backed up, short of extracting the configuration in it's proprietary format. Any hope for adding support for this?

Debug logs all show the following:

```
root@72afc84c7ad8:~/.config/oxidized/logs# cat omitted-ssh


Copyright (c) 2012 Dell | SonicWALL, Inc.



Using username 'omitted'.
Password:
% Session timed out.
```

Certain other models of Sonicwall show the following:

```
root@72afc84c7ad8:~/.config/oxidized/logs# cat omitted-ssh


Copyright (c) 2017 SonicWall, Inc.



Using username 'omitted'.
Password:

omitted@C0EAE424AB60>

```

**Comment by laf** [comment]
Do you have debug enabled as that doesn't look like it? I'd turn debugging on and then pastebin the entire log so we can see what it's doing.

If the aosw model used to work it's most likely due to the changes in prompt detection.

**Comment by tnielsen2** [comment]
This is output from the debug log. I can happily place it into pastebin if you would like. But the output is going to be the same (minus the hostname being omitted)

**Comment by laf** [comment]
Honestly that doesn't look like the output from debug. Can you show your config so we can see what you've enabled?

**Comment by tnielsen2** [comment]
Config is below
```
username: 
password: 
model: cisco
interval: 1800
use_syslog: true
log: /root/.config/oxidized/logs
debug: true
threads: 50
timeout: 960
retries: 1
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 0.0.0.0:8888
next_adds_job: false
vars:
  remove_secret: false
  enable: 
groups: {}
models: {}
pid: /root/.config/oxidized/pid
input:
  default: ssh, telnet
  debug: true
  ssh:
    secure: false

output:
  default: git
  git:
    single_repo: true
    user: root
    email: 
    repo: /root/.config/oxidized-configs/.git

source:
  default: csv
  csv:
    file: /root/.config/oxidized/router.db
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      ip: 1
      model: 2
      username: 3
      password: 4
      enable: 5
    gpg: false

model_map:
  cisco: ios
  cisco: asa
  juniper: junos
  ciscowlc: aireos
  brocade: nos
  fortigate: fortios
  sonicwall: aosw
  ironware: ironware

hooks:
  push_to_remote:
   type: githubrepo
   events: [post_store]
   remote_repo: 
   username:
   password:
   #publickey: /root/.ssh/id_rsa.pub
   #privatekey: /root/.ssh/id_rsa
```

When I list the contents of the log folder, i get the output of multiple IP addresses, and the connection method (ssh or telent) appended to it. When I cat those files, it gives me the output like provided above. 

```
root@461eff8ac6d6:~/.config/oxidized/logs# ls
10.X.21.1-ssh       10.X.21.251-ssh     10.X.21.249-ssh
root@461eff8ac6d6:~/.config/oxidized/logs#
```

Based on what you are saying, there should be a different debug format... am I looking in the wrong place?

**Comment by laf** [comment]
If you start oxidized with systemd then check `/var/log/messages` or `/var/log/syslog`
