### ISSUE TITLE
pulling config from metamko

### ISSUE THREAD

**Issue by jjtop25** [ytti/oxidized#1192]
Has anyone been able to pull a configuration from a metamako device?  There is currently no template and the normal cisco and arista templates do not seem to work.

**Comment by laf** [comment]
If you enable debugging and pastebin the output we can probably help - or provide access to a device online.

**Comment by jjtop25** [comment]
Hi sorry for the silence.  Do you want me to enable debugging on oxidized and then pastebin the debug log or paste the output from what it pulls?

**Comment by laf** [comment]
Enable debugging in oxidized and pastebin the debug output.

**Comment by jjtop25** [comment]
Here is the relevant output.

<iframe src="https://pastebin.com/embed_iframe/J2EavEFp" style="border:none;width:100%"></iframe>

Then it just keeps repeating the last message

**Comment by laf** [comment]
So it's getting to try the enable from what I can see. Do you have an enable password configured to be used in the config or the source?

**Comment by jjtop25** [comment]
In the config I do have an enable password configured.  It is the same processe as the other switches where the prompts are:

login as:
type login password
Password:
type enable
Password:
type password

**Comment by laf** [comment]
Can you pastebin your config please.

Also. have you customised the IOS model as it has this in the debug:

`D, [2018-03-02T10:47:46.599338 #69157] DEBUG -- : lib/oxidized/input/ssh.rb pwdd @ mm01 with expect: /^([\w.@()-]+[#>]\s?)$/`

The model in our git repo doesn't have `pwdd`

**Comment by jjtop25** [comment]
Below is my config 

the pwdd is the password.  I just replaced the actual password with that so as not to share it.

```
  ---
username: admin
password: pwdd1
model: cisco
interval: 3600
use_syslog: false
log: /home/oxidized/logs/log.log
debug: false
threads: 30
timeout: 120
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 127.0.0.1:8888
next_adds_job: false
vars:
  ssh_port: 22
  enable: pwdd
groups:
  default:
    username: admin
    password: pwdd1
    vars:
      enable: pwdd
  nxos:
    username: admin
    password: pwdd1
  ios:
    username: admin
    password: pwdd1
    vars:
      enable: pwdd
  fortinet:
    username: admin
    password: pwdd
  opengear:
    username: admin
    password: pwdd1
  mos:
    username: admin
    password: pwdd1
    vars:
      enable: pwdd

  eos:
    username: admin
    password: pwdd1
    vars:
      enable: pwdd


models: {}
pid: "/home/oxidized/.config/oxidized/pid"
input:
  default: ssh, telnet
  debug: false
  ssh:
    secure: false
output:
  default: git
  git:
    user: oxidized
    email: email@email.com
    repo: "/var/network-backups/default.git"
source:
  default: http
  http:
    url: http://127.0.0.1/api/v0/oxidized
    scheme: http
    delimiter: !ruby/regexp /:/
    map:
      name: hostname
      model: os
      group: group
    headers:
      X-Auth-Token: '0a36f7348c258681a17d39d661b78b87'

#source:
#  default: csv
#  csv:
#    file: "/home/oxidized/.config/oxidized/router.db"
#    delimiter: !ruby/regexp /:/
#    map:
#    name: 0
#    model: 1
#    username: 2
#    password: 3
#    enable: 4
#    ssh_port: 5
#      group: 6
#    vars_map:
#      enable: 4
#      ssh_port: 5

model_map:
  cisco: nxos
  cisco: ios
  Dell: dnos
  OpenGear: OpenGear
  juniper: junos
  huawei: vrp
  paloalto: panos
  ubiquiti: edgeos
  brocade: vyatta
  mikrotik: routeros
  FortiOS: fortios
  fortinet: fortios
  fortigate: fortios
  vyatta: vyos
  vyos: vyatta
  arista: eos
  arista_eos: eos
  eos: eos
  iosxe: iosxr
  opengear: opengear
  mos: ios
  generic: ios
gpg: false

```

**Comment by jjtop25** [comment]
any thoughts on this?

**Comment by jjtop25** [comment]
this can be closed.  The issue was that the exclude command needed to be taken out of the eos.rb file.  I created a new mos.rb without the exclude statement and it worked.
