### ISSUE TITLE
Only one host of many is polled

### ISSUE THREAD

**Issue by Noname2244** [ytti/oxidized#1194]
Hi! Im running oxid from the docker oxidized/oxidized:latest  ,  and I have a handful of switches with same settings regarding SNMP and SSH. They are all reachable and accessible from within the docker container but only one single device is being polled, this is very odd since its the same account for all units.

I have just enabled debug and will look at the output as soon as I find it.

Any ideas on how to troubleshoot this issue?

**Comment by laf** [comment]
> I have just enabled debug and will look at the output as soon as I find it.

Post the output of this. It's impossible to debug without it.

**Comment by Noname2244** [comment]
Ok I started the oxid docker manually for output and oxid can't resolve the node name
multiple lines of:
`Feb 24 09:52:35 9e034473446f oxidized[19]: node {:name=>"l4.domain.com        ", :model=>nil} is not resolvable, raised Resolv::ResolvError with message 'no address for l4.domain.com`

but I can ping and use dig for l4.domain.com both in the docker container and on the host it self so the domain can be resolved but oxid can't.
As a workaround I'll add the IP to router.db.

**Comment by Noname2244** [comment]
This is from inside the docker container:
`root@e590121cdf89:/tmp/oxidized# ping  l4.domain.com
PING l4.domain.com (10.1.1.5) 56(84) bytes of data.
64 bytes from l4.domain.com (10.1.1.5): icmp_seq=1 ttl=251 time=2.79 ms`

**Comment by laf** [comment]
Resolv is used for dns lookups. The only issues I can see in the docs for that is if you use NIS: https://ruby-doc.org/stdlib-1.9.2/libdoc/resolv/rdoc/Resolv.html#class-Resolv-label-Bugs

Can this issue be closed?
