### ISSUE TITLE
Oxidized + Librenms issue with password

### ISSUE THREAD

**Issue by tramontano** [ytti/oxidized#1195]
Hi everyone,

I had installed oxidized + librenms and works almost perfect.

I have 5000+ devices to insert at librenms (and oxidized via api), the main problem is that every device has a unique password. Since I don't have access to router.db due the integration, I am not able to set a custom password for every device.

Any thoughts?

Thank's

oxidized config file:
https://pastebin.com/ZqpbpS8A

**Comment by laf** [comment]
You don't have any options for that other than assign each device to a group then create credentials in the oxidized config for each group.

It may be easier to write something that dumps the librenms api data to a local file and merge in from your password db all the creds and use that file as the local source.

**Comment by laf** [comment]
Also, a gitter and irc channel exists for oxidized. Things like this may be better asked there.

**Comment by tramontano** [comment]
> You don't have any options for that other than assign each device to a group then create credentials in the oxidized config for each group.

I thought about that, it won't be something simple, but it's possible. 

> It may be easier to write something that dumps the librenms api data to a local file and merge in from your password db all the creds and use that file as the local source.

I've tried that, I used mysql as source (which I have a db with ip, password etc..) but by doing that I'll not have a network+backup solution, just backup.

I already have a shell script that uses mysql db to obtain the devices credentials and backup them, but the great thing about oxidized + librenms is the web interface integration with the backup mechanism, beleave me, it makes the trobleshooting a lot easier in large scale..

One more thing, is there any manual or readme file that explains how to create a model file?

**Comment by laf** [comment]
You still get the integration into LibreNMS using any source with oxidized as long as you really use git output.

**Comment by tramontano** [comment]
@laf that's it!  Thanks for quickly reply. I thought I couldn't, but it worked!!

Thanks again laf!

**Comment by 1soproni** [comment]
hi @tramontano 
I have similar issue.
Did you manage it?
Could you please share the relevant configs?

**Comment by davidmlafuente** [comment]
Hi everyone!

@tramontano do you use some kind of password management software for storing credentials?
we've started to use teampass for this purpose and i'm looking for some kind of integration between Librenms - Oxidized - Teampass.

Teampass provides api functions and can be used to retrieve credentials for each device.

I think that other approach could be to create an script that fills a credentials file to be used by oxidized instead of managing backups outside of librenms.

Any sugestions?
