### ISSUE TITLE
hello I would like to collaborate with your project by serving as a translator to Spanish

### ISSUE THREAD

**Issue by LuigiBaute** [ytti/oxidized#1196]

**Comment by laf** [comment]
Hi @LuigiBaute. Thanks for your offer of help, we don't currently have any international translations. What is it you would be looking to do, the docs or the web interface as the latter would require some work in the code base to support i18n.

**Comment by LuigiBaute** [comment]
I'm gonna make a pull request of a translated readme file, are you/guys interested? @laf

**Comment by laf** [comment]
From my perspective it would be ok, the main issue is it becoming out of date when the english version is updated.

@yeled / @ytti what are your thoughts on this?

**Comment by ytti** [comment]
I suspect after initial work the translation would drift. We don't have process or resources to ensure any type of consistency or continuity in publishing documents multilingually. 

If we accept !english README, we need not to publish english changes until other changes are also done.

I'm not ready to work on this and ensure that documents are in synchronous.

I think we can thus far get away with foreign language articles and blogs.
