### ISSUE TITLE
Save filename

### ISSUE THREAD

**Issue by escopeman** [ytti/oxidized#1197]
Hello guys, how i can set to oxidizes save the file with the ip on name like

192.168.1.1.txt

Thanks for the help

**Comment by laf** [comment]
What output are you using?

**Comment by laf** [comment]
It's not something that's natively supported, you'd need to edit: lib/oxidized/output/git.rb to add this support. I can't tell you specifically where but in the `store` function is where you need to start. Out of interest, why do you want to do this?

Maybe @yeled could offer some assistance.

**Comment by escopeman** [comment]
I have like a 300 devices to backup and on rancid we use CTRL + F do take the file.

Like:
CTRL + F
192.168.1.1

Download the file and upload at device.

Thank you for help

**Comment by laf** [comment]
Ok but what does that have to do with the .txt extension? Is it because 192.168.1.1 might match 192.168.1.10 etc?

**Comment by laf** [comment]
Ah right ok so you want it to save the file as the IP rather than the hostname? Why not just add devices by the IP rather than hostname then in the first place @escopeman?
