### ISSUE TITLE
Junos issue: ArgumentError with msg "invalid byte sequence in UTF-8"

### ISSUE THREAD

**Issue by tobzsc** [ytti/oxidized#1203]
I am experiencing a problem with one of our switches. It works for all switches except this one. It is a Juniper EX3300. Maybe the logs can help.

```
Mar  9 11:43:58 oxidizer oxidized: W, [2018-03-09T11:43:58.925239 #7987]  WARN -- : fra1-pod01-b10-as01 status no_connection, retry attempt 1
Mar  9 11:44:08 oxidizer oxidized: E, [2018-03-09T11:44:08.808136 #7987] ERROR -- : 10.25.0.44 raised ArgumentError with msg "invalid byte sequence in UTF-8", /home/oxidized/.config/oxidized/crash.10.25.0.44 saved
Mar  9 11:44:08 oxidizer oxidized: W, [2018-03-09T11:44:08.927910 #7987]  WARN -- : fra1-pod01-b10-as01 status no_connection, retry attempt 2
Mar  9 11:44:20 oxidizer oxidized: E, [2018-03-09T11:44:20.534829 #7987] ERROR -- : 10.25.0.44 raised ArgumentError with msg "invalid byte sequence in UTF-8", /home/oxidized/.config/oxidized/crash.10.25.0.44 saved
Mar  9 11:44:20 oxidizer oxidized: W, [2018-03-09T11:44:20.930958 #7987]  WARN -- : fra1-pod01-b10-as01 status no_connection, retry attempt 3
Mar  9 11:44:29 oxidizer oxidized: E, [2018-03-09T11:44:29.849548 #7987] ERROR -- : 10.25.0.44 raised ArgumentError with msg "invalid byte sequence in UTF-8", /home/oxidized/.config/oxidized/crash.10.25.0.44 saved
```

```
[root@oxidizer ~]# cat /home/oxidized/.config/oxidized/crash.10.25.0.44
2018-03-09 10:44:29 UTC
invalid byte sequence in UTF-8 [ArgumentError]
--------------------------------------------------
/usr/local/share/gems/gems/oxidized-0.21.0/lib/oxidized/model/junos.rb:11:in `gsub!'
/usr/local/share/gems/gems/oxidized-0.21.0/lib/oxidized/model/junos.rb:11:in `block in <class:JunOS>'
/usr/local/share/gems/gems/oxidized-0.21.0/lib/oxidized/model/model.rb:87:in `instance_exec'
/usr/local/share/gems/gems/oxidized-0.21.0/lib/oxidized/model/model.rb:87:in `block in cmd'
/usr/local/share/gems/gems/oxidized-0.21.0/lib/oxidized/model/model.rb:86:in `each'
/usr/local/share/gems/gems/oxidized-0.21.0/lib/oxidized/model/model.rb:86:in `cmd'
/usr/local/share/gems/gems/oxidized-0.21.0/lib/oxidized/model/model.rb:136:in `block in get'
/usr/local/share/gems/gems/oxidized-0.21.0/lib/oxidized/model/model.rb:135:in `each'
/usr/local/share/gems/gems/oxidized-0.21.0/lib/oxidized/model/model.rb:135:in `get'
/usr/local/share/gems/gems/oxidized-0.21.0/lib/oxidized/input/cli.rb:14:in `get'
/usr/local/share/gems/gems/oxidized-0.21.0/lib/oxidized/node.rb:65:in `run_input'
/usr/local/share/gems/gems/oxidized-0.21.0/lib/oxidized/node.rb:42:in `block in run'
/usr/local/share/gems/gems/oxidized-0.21.0/lib/oxidized/node.rb:37:in `each'
/usr/local/share/gems/gems/oxidized-0.21.0/lib/oxidized/node.rb:37:in `run'
/usr/local/share/gems/gems/oxidized-0.21.0/lib/oxidized/job.rb:9:in `block in initialize'
```

**Comment by tobzsc** [comment]
I have now checked with several other switches. It happens with several Juniper switches (QFX, EX). It is not in combination with a specific version or config parameter. There seems to be some other issue.

**Comment by ytti** [comment]
We treat, probably incorrectly, configurations as UTF8 strings. Any non UTF8 string (likely description, snmp location etc) will cause this.

We probably should instead feed the configuration to the models as byte stream, not UTF8 string. 

Like maybe here: https://github.com/ytti/oxidized/blob/master/lib/oxidized/model/model.rb#L82

it should be string = string.b

**Comment by laf** [comment]
@tobzsc Could you try what @ytti suggested please? You can clone the repo from github, make the change to the local file then build the gem as per the install docs.

**Comment by ytti** [comment]
sorry out = out.b after ```return false unless out```

**Comment by tobzsc** [comment]
Nice! This solved the problem. I have created a pull request. #1210

**Comment by frederic-loui** [comment]
Hi, I re-open this issue as I tested the "utf8_encoded: trigger and I still get this error: 
Junos issue: <hostname> raised ArgumentError with msg "invalid byte sequence in UTF-8", <hostname> saved. 

What is strange is that in the code I have in "model.rb":
out = out.b unless Oxidized.config.input.utf8_encoded?

--> This should means: if "utf8_encoded" is true then don't do "out = out.b" (so the config is utf8 encoded?) else "out = out" ("out = out")

My question is: Does "out = out" means that the config is not utf8 encoded and has to be treated as binary ?

Sorry if this is a stupid question but I tried both values for utf8_encoded in config global section and still got the error.

Therefore in the end how to I treat the config as binary in ruby ? 

Thanks !
Frederic

**Comment by manoafv** [comment]
Hello,

Any news on this issue please?

**Comment by rkandilarov** [comment]
Hi!

Just to note that we also seems to have the same problem with Juniper mx240.
```
:~/.config/oxidized$ oxidized
Puma starting in single mode...
* Version 3.11.4 (ruby 2.5.1-p57), codename: Love Song
....
```

But the most annoying is that due to the failure the ssh connection states forever and is eating slowly all allowed ssh sessions on the Juniper router.

**Comment by rkandilarov** [comment]
Just now red other issue https://github.com/ytti/oxidized/issues/1587 an realize that what is needed in my case is simply set the `utf8_encoded: false` in `.config/oxidized/config` under section `input` . This change does fix my problem so now my config looks like:
```
...
input:
  default: ssh
  debug: false
  ftp:
    passive: true
  utf8_encoded: false

...
```

**Comment by ciroiriarte** [comment]
Can this be applied per switch?. I have several switches happily working, but 2 x MX giving me this error. Wouldn't want to break everything because of this.
