### ISSUE TITLE
Pushing to Github using ssh stopped working

### ISSUE THREAD

**Issue by MichaelSwann** [ytti/oxidized#1204]
Hi,

I have had oxidized up and running in a docker container since January and it was happily pushing configs up to Github. Nothing changed with the configuration or the Github ssh key exists and the container has had no restarts. 

The last time a configuration was pushed to Github was 22 February 2018. This coincidences with when Github removed weak cryptographic standards. See https://blog.github.com/2018-02-23-weak-cryptographic-standards-removed/

In the logs `Rugged::SshError: failed to start SSH session: Unable to exchange encryption keys>) for event :post_store` is the error

```
Mar  9 10:27:27 oxidized-2618625911-7mzjq oxidized[17]: Configuration updated for routers/ct-office
Mar  9 10:27:27 oxidized-2618625911-7mzjq oxidized[17]: GithubRepo: Pushing local repository(/root/.config/oxidized/git-repo/routers.git/)...
Mar  9 10:27:27 oxidized-2618625911-7mzjq oxidized[17]: GithubRepo: to remote: git@github.com:Telecom/infrastructure-backups.git
Mar  9 10:27:27 oxidized-2618625911-7mzjq oxidized[17]: Hook push_to_remote (#<GithubRepo:0x0000000001510120>) failed (#<Rugged::SshError: failed to start SSH session: Unable to exchange encryption keys>) for event :post_store
Mar  9 10:27:27 oxidized-2618625911-7mzjq oxidized[17]: SlackDiff: Connecting to slack
Mar  9 10:27:28 oxidized-2618625911-7mzjq oxidized[17]: SlackDiff: Connected
Mar  9 10:27:28 oxidized-2618625911-7mzjq oxidized[17]: SlackDiff: Posting diff as snippet to #private-core
Mar  9 10:27:29 oxidized-2618625911-7mzjq oxidized[17]: SlackDiff: Finished
```

Config (was working for over a month)

```
hooks:
  push_to_remote:
    type: githubrepo
    events: [post_store]
    remote_repo: 
      routers: git@github.com:Telecom/infrastructure-backups.git
    privatekey: /root/.config/oxidized/git_id_rsa
    publickey: /root/.config/oxidized/git_id_rsa.pub
```

There are other libraries which are struggling with this issue - https://github.com/saltstack/salt/issues/46159

I was wondering if anyone else has experienced a similar issue?

I am not familiar with ruby so I am struggling to debug but will keep trying and update if I find anything.

**Comment by laf** [comment]
That link you pointed to says that libssh needs to be updated. You'd have to see if it's back ported to the distro you use as that link indicates it's in Ubuntu 17 which means it may not make it to earlier versions.

**Comment by shepherdjay** [comment]
Anyway to fix this on Centos been scouring around and Centos is running 1.4 of libssh2. I can download 1.8.0 but not familiar with cmake or how to do that.

**Comment by laf** [comment]
@shepherdjay Maybe this will help https://github.com/saltstack/salt/issues/46159#issuecomment-368869362

**Comment by esajo** [comment]
This issue still persists on centos 7 unfortunately, so git as backend of oxidized can be used but no auto push is possible.

**Comment by wk** [comment]
`Oxidized` makes use of the `rugged` library (itself a wrapper around `libgit2`), which makes use of `libssh2`.

CentOS / RHEL 7 ships with a version of libssh2 that is too old to work with the current GitHub ssh configuration, and CentOS / RHEL 8 is expected to ship with no libssh2 [at all](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/considerations_in_adopting_rhel_8/index#literal_libssh2_literal_is_not_available_in_rhel_8). 

If you wish to use the `githubrepo` functionality of `Oxidized`, you will need to either manually build and install a newer version of `libssh2` and subsequently rebuild the `rugged` gem locally against it, or make use of e.g. the `oxidized` docker container `oxidized/oxidized` which ships with a version of libssh2 that supports this.

**Comment by esajo** [comment]
Thank you for the very clear explanation, makes sense!
