### ISSUE TITLE
JUNOS: config does't backup after commit

### ISSUE THREAD

**Issue by anetrjuns** [ytti/oxidized#1206]
Hi everyone,

I have rsyslog working on LibreNMS, and Oxidized is backing up junos config at my set interval. 
 I have get the syslog change detection working in Oxidized, but can't get config backup, after any commit on Juniper SRX device.
My config is:

///File: /opt/librenms/config.php 
.
omited
.
#Enabling Syslog on LibreNMS
$config['enable_syslog'] = 1;
$config['enable_syslog_hooks'] = 1;
$config['os']['junos']['syslog_hook'][] = Array('regex' => 'mgd\[[0-9]+\]: UI_COMMIT: .*', 'script' => '/opt/librenms/scripts/syslog-notify-oxidized.php');
$config['os']['ios']['syslog_hook'][] = Array('regex' => '/%SYS-(SW[0-9]+-)?5-CONFIG_I/', 'script' => '/opt/librenms/scripts/syslog-notify-oxidized.php');
$config['os']['nxos']['syslog_hook'][] = Array('regex' => '/%VSHD-5-VSHD_SYSLOG_CONFIG_I/', 'script' => '/opt/librenms/scripts/syslog-notify-oxidized.php');
$config['os']['iosxr']['syslog_hook'][] = Array('regex' => '/%GBL-CONFIG-6-DB_COMMIT/', 'script' => '/opt/librenms/scripts/syslog-notify-oxidized.php');
$config['os']['asa']['syslog_hook'][] = Array('regex' => '/%ASA-(config-)?5-111005/', 'script' => '/opt/librenms/scripts/syslog-notify-oxidized.php');

///File: /opt/librenms/scripts/syslog-notify-oxidized.php 
.
omited
.
if (preg_match('/(SYS-(SW[0-9]+-)?5-CONFIG_I|VSHD-5-VSHD_SYSLOG_CONFIG_I): Configured from .+ by (?P<user>.+) on .*/', $msg, $matches)) {
    $username = $matches['user'];
    oxidized_node_update($hostname, $username, $msg);
} elseif (preg_match('/GBL-CONFIG-6-DB_COMMIT : Configuration committed by user \\\\\'(?P<user>.+?)\\\\\'..*/', $msg, $matches)) {
    $username = $matches['user'];
    oxidized_node_update($hostname, $username, $msg);
} elseif (preg_match('/ASA-(config-)?5-111005: (?P<user>.+) end configuration: OK/', $msg, $matches)) {
    $username = $matches['user'];
    oxidized_node_update($hostname, $username, $msg);
} elseif (preg_match('/startup-config was changed by (?P<user>.+) from telnet client .*/', $msg, $matches)) {
    $username = $matches['user'];
    oxidized_node_update($hostname, $username, $msg);

///File: /root/.config/oxidized/config 
.
omited
.
model: junos
interval: 3600
use_syslog: false
debug: false
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 127.0.0.1:8888
next_adds_job: false
vars: {}
groups: {}
models: {}
pid: /root/.config/oxidized/pid
input:
  default: ssh, telnet
  debug: false
  ssh:
    secure: false
output:
  default: git
  git:
    user: Oxidized
    email: o@example.com
    repo: "/root/.config/oxidized/configs/config.git"
source:
  default: csv
  csv:
    file: /root/.config/oxidized/router.db
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
      username: 2
      password: 3
    vars_map:
      enable: 4
    gpg: false
model_map:
  cisco: ios
  juniper: junos
  hp: procurve

I think that the problem is in the script.
Any ideas?
Thanks.

**Comment by laf** [comment]
Sorry it's not really clear what you are saying is the issue is. Can you provide more info?

Also, please wrap config between \`\`\` \`\`\` to format it correctly.

**Comment by anetrjuns** [comment]
Thank you for response.

I can't get config backup automatically after configuration changes on my Juniper device.

"
#Enabling Syslog on LibreNMS
$config['enable_syslog'] = 1;
$config['enable_syslog_hooks'] = 1;
$config['os']['junos']['syslog_hook'][] = Array('regex' => 'mgd[[0-9]+]: UI_COMMIT: .*', 'script' => '/opt/librenms/scripts/syslog-notify-oxidized.php'); 
"

**Comment by laf** [comment]
This seems more like a LibreNMS question than oxidized. If you use librenms for syslog then I'd suggest asking on the librenms forum or discord channel
