### ISSUE TITLE
Issues connecting to Cisco SMB

### ISSUE THREAD

**Issue by SaaldjorMike** [ytti/oxidized#121]
I've seen the issue #40 and thought I'd check it out. Already fetching information from my Cisco IOS, Cisco IOS-XE and Cisco ASA devices, but seems like I'm having issues with the Cisco SMB.

I've included some debugging information here:
https://bpaste.net/show/4e8120eb2f30

Any suggestions on how to proceed?

**Comment by ytti** [comment]
Are you using 'ciscosmb' as device model? #40 was solved in
https://github.com/ytti/oxidized/blob/master/lib/oxidized/model/ciscosmb.rb

**Comment by SaaldjorMike** [comment]
Yes I am using ciscosmb as the device model.
Since the source contains 'ciscosb' I've added the following to the config:
```
model_map:
  ciscosb: ciscosmb
```

I also added the following to fetch my IOS-XE device as a IOS device, which seems to work fine:
```
  iosxe: ios

**Comment by ytti** [comment]
I'm not really familiar with ciscosmb, don't have access to any. Maybe @thetamind can help.

Looking at your messages:
---
172.17.102.6 raised Net::SSH::AuthenticationFailed with msg "Authentication failed for user user@ip"
---

This implies we're trying SSH authentication. And If I understand from   @thetamind output, his devices do not support SSH authentication at all, instead SSH AUTH always succeeds, and then device presents its own auth in higher level after SSH.

When you login to it manually via SSH, does it honor your SSH username? if you do 'ssh -v user@host' does it still ask for username? Or still device offers user prompt? What is the output produced?
Does it work with telnet?

**Comment by SaaldjorMike** [comment]
No it does not honour the SSH username. Yes it still asks for the username even if i use 'ssh user@host'.
Output from the verbose SSH command can be seen here:
https://bpaste.net/show/7384cc76735e

I have not tried telnet, which is not something I'd like to run.

**Comment by ytti** [comment]
https://github.com/ytti/oxidized/blob/master/lib/oxidized/input/ssh.rb#L27

Can you change that line to:
:auth_methods => %w(publickey password none),

and tell how it affects the situations

**Comment by SaaldjorMike** [comment]
Unfortunately the same result: https://bpaste.net/show/17ef8c22f9e7

**Comment by ytti** [comment]
Does the debug also claim that authentication failed with same message?

Is it possible to have remote access to the device?

**Comment by ytti** [comment]
You might want to also try to move the 'none' as first auth_method, instead of last

**Comment by SaaldjorMike** [comment]
@ytti: You're a hero! Seems like adding it to the start of the auth_method fixes my problem with these devices.
