### ISSUE TITLE
Input FTP

### ISSUE THREAD

**Issue by supaflybro** [ytti/oxidized#1214]
Can somebody explain how to use FTP input?

**Comment by ytti** [comment]
Look at zynos model

**Comment by supaflybro** [comment]
Ok, i get it. 
Another question, is there any way to impliment next schema? Cisco routers upload config to ftp -> oxidized reads file and adds changes to git repo.
Security policy does not allow you to connect to some ssh routers :(

**Comment by ytti** [comment]
No currently, no. We'd need to add FTP listener thread and another job to remove ready strings from the FTP listener during poll cycle.

It wouldn't be hard to do, maybe 10h of work.

**Comment by wk** [comment]
@supaflybro if this is something you're interested in (or in working toward) please create a feature request and mention this issue. Closing this for now as the original subject question has been addressed.
