### ISSUE TITLE
Unable to complete NetScaler config pull

### ISSUE THREAD

**Issue by nihilexmachina** [ytti/oxidized#1215]
Hello, I'm trying to pull the config from a NetScaler MPX but it doesn't work. Seems that oxidized is expects a regex pattern and, afaik, it should match the prompt but nothing happens after that:

```
D, [2018-03-13T15:14:58.212352 #22378] DEBUG -- : lib/oxidized/job.rb: Starting fetching process for ██████████████.██.████████.█████ at 2018-03-13 14:14:58 UTC
D, [2018-03-13T15:14:58.212146 #22378] DEBUG -- : lib/oxidized/worker.rb: Added ██████████████.██.████████.█████ to the job queue
D, [2018-03-13T15:14:58.213174 #22378] DEBUG -- : lib/oxidized/input/ssh.rb: Connecting to ██████████████.██.████████.█████
D, [2018-03-13T15:14:58.213268 #22378] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 1 of 2 - ended: 4 of 59
D, [2018-03-13T15:14:58.213799 #22378] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2018-03-13T15:14:58.490179 #22378] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/\w*>$/] at ██████████████.██.████████.█████
D, [2018-03-13T15:14:59.219817 #22378] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 1 of 2 - ended: 4 of 59
[...]
W, [2018-03-13T15:22:59.513309 #22378]  WARN -- : 10.201.31.115 raised Oxidized::PromptUndetect with msg "Last login: Tue Mar 13 15:14:59 2018 from ██.███.██.██
 Done
████████████ - Primary - nsroot>  not matching configured prompt (?-mix:\w*>$)"
D, [2018-03-13T15:22:59.513545 #22378] DEBUG -- : lib/oxidized/node.rb: Oxidized::SSH failed for ██████████████.██.████████.█████
D, [2018-03-13T15:22:59.513717 #22378] DEBUG -- : lib/oxidized/job.rb: Config fetched for ██████████████.██.████████.█████ at 2018-03-13 14:22:59 UTC
D, [2018-03-13T15:23:00.349537 #22378] DEBUG -- : Exec: Execute: "echo -e \"Backup failure for: $OX_NODE_GROUP \\ $OX_NODE_NAME \\n\" >> /var/log/oxidized/backup_failure-`date +%Y_%m_%d`"
W, [2018-03-13T15:23:00.362342 #22378]  WARN -- : ██████████████.██.████████.█████ status no_connection, retries exhausted, giving up
```
The SSH debug returns the same prompt provided in the logs:
```
Last login: Tue Mar 13 13:23:10 2018 from ██.███.██.██
 Done
████████████ - Primary - nsroot>
```

Any ideas?
Thanks in advance.

**Comment by laf** [comment]
It's hard to test the regex works when you've masked the data like that, you should just replace with some alternative text.

However it looks like it is matching so most likely some bad characters before or after the prompt. Can you see anything like that opening the debug file in vi?

**Comment by nihilexmachina** [comment]
Hi there,

Sorry about the excessive masking:

```
D, [2018-03-13T15:14:58.212352 #22378] DEBUG -- : lib/oxidized/job.rb: Starting fetching process for loadbalancer01.foo.bar at 2018-03-13 14:14:58 UTC
D, [2018-03-13T15:14:58.212146 #22378] DEBUG -- : lib/oxidized/worker.rb: Added for loadbalancer01.foo.bar to the job queue
D, [2018-03-13T15:14:58.213174 #22378] DEBUG -- : lib/oxidized/input/ssh.rb: Connecting to for loadbalancer01.foo.bar
D, [2018-03-13T15:14:58.213268 #22378] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 1 of 2 - ended: 4 of 59
D, [2018-03-13T15:14:58.213799 #22378] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2018-03-13T15:14:58.490179 #22378] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/\w*>$/] at for loadbalancer01.foo.bar
D, [2018-03-13T15:14:59.219817 #22378] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 1 of 2 - ended: 4 of 59
[...]
W, [2018-03-13T15:22:59.513309 #22378]  WARN -- : 10.201.31.115 raised Oxidized::PromptUndetect with msg "Last login: Tue Mar 13 15:14:59 2018 from 10.0.0.100
 Done
loadbalancer01 - Primary - nsroot>  not matching configured prompt (?-mix:\w*>$)"
D, [2018-03-13T15:22:59.513545 #22378] DEBUG -- : lib/oxidized/node.rb: Oxidized::SSH failed for for loadbalancer01.foo.bar
D, [2018-03-13T15:22:59.513717 #22378] DEBUG -- : lib/oxidized/job.rb: Config fetched for for loadbalancer01.foo.bar at 2018-03-13 14:22:59 UTC
D, [2018-03-13T15:23:00.349537 #22378] DEBUG -- : Exec: Execute: "echo -e \"Backup failure for: $OX_NODE_GROUP \\ $OX_NODE_NAME \\n\" >> /var/log/oxidized/backup_failure-`date +%Y_%m_%d`"
W, [2018-03-13T15:23:00.362342 #22378]  WARN -- : for loadbalancer01.foo.bar
status no_connection, retries exhausted, giving up
```
At first, seemed that It wasn't matching anything so I changed the default regex to a more simple one (the one in the code). I used Rubular to text the regest and seems to be maching it correctly yet it doesn't proceed with the execution afterwards.

At first I configured this regex to make sure that it was matching the whole prompt string, but didn't work either:
`/^\w*\s\S\s\w*\s\S\s\w*>$/`
Instead of the actual regex:
`/w*>$/`

I preemptively apologize for any inconvenience based in my coding ignorance, I'm not really used to it (based on my IT career) and I really appreciate any effort put into this.

**Comment by laf** [comment]
You could try this prompt maybe: `^[\S ]+\>\s*$`

**Comment by nihilexmachina** [comment]
Hi there,

It worked! Thank you very much!

**Comment by laf** [comment]
@nihilexmachina If that is a standard prompt for this device then the model should be updated, would you like to submit a pull request to update it?

**Comment by nihilexmachina** [comment]
@laf  we have a few other NetScalers and I'd like to try this new prompt in those since they essentially are not the same type. Maybe there is a difference betweeen NetScaler MPX (the one we fixed right now), SDX and VPX. I'll get back to you as soon as I tested this in the other NS flavors.

**Comment by nihilexmachina** [comment]
Hi there. My most sincere apologies, we received the tools server a week ago.
We had to fight a lot to get the server and now I'm starting to add devices. I'll test the other NetScalers as soon as I can.

**Comment by jameskirsop** [comment]
FWIW, our VPX running 12.1 does not have the hostname before the `>`.

However, can confirm that #1658 doesn't break anything for us.

This issue should be closed.
