### ISSUE TITLE
web interface not working after gem update

### ISSUE THREAD

**Issue by jjtop25** [ytti/oxidized#1216]
Hello,

Today the gem update command was run on our server.  Now we are getting a 502 Bad Gateway error when accessing the web interface.  Did something change that may have caused this?  Nothing else has changed on the servers.  The error that is in the nginx log is.

` connect() failed (111: Connection refused) while connecting to upstream, client: x.x.x.x, server: [server.domain.com], request: "GET /nodes HTTP/1.1", upstream: "http://127.0.0.1:8888/nodes", host: "server:8080", referrer: "http://server:8080/nodes"`

**Comment by jjtop25** [comment]
looks like the puma version got updated to an incompatible version.  Downgraded pump and it started working.

**Comment by wk** [comment]
@jjtop25 could you comment on which version of puma is the latest you've found to be compatible, and which is the earliest you've found to be incompatible?

**Comment by jjtop25** [comment]
Hi,
I found the compatible version was 3.11.0.  I cannot remember what versions past that did not work.

**Comment by wk** [comment]
@jjtop25 thank you!

**Comment by wk** [comment]
@jjtop25 in #1237 a user with a very similar problem has reported that simply re-installing the entire ecosystem of gems - rather than downgrading puma, has solved the problem for them and oxidized-web is up and running with puma `3.11.3`. 

Would you be willing to attempt the same in your environment and see if you can reproduce this so that the root cause can be narrowed down?

**Comment by jjtop25** [comment]
I can give it a shot, but probably not until Friday.  So the steps are uninstall all gems, reinstall the oxidized packages and see if that works?

**Comment by wk** [comment]
Exactly so.

The expected outcome is that you'll be able to reproduce the experience of @wolf2668 in #1237 and ytti/oxidized-web will run with puma `3.11.3`. If that does not turn out to be the case, this might require further investigation, and locking up the puma version to `3.11.0` in ytti/oxidized-web in the interim.

Looking forward to your feedback!

**Comment by chasgames** [comment]
I think this is related to my recent fresh install error:

# oxidized
/usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- puma/puma_http11 (LoadError)

so i uninstalled Puma 3.11.3 

and ran  gem install puma -v 3.11.0

Now it works

**Comment by jjtop25** [comment]
removing all the gems and reinstalling them seemed to have worked.
