### ISSUE TITLE
blank hostname

### ISSUE THREAD

**Issue by rsaeba** [ytti/oxidized#1217]
Hi,

Thanks for Oxidized, great project !
Now, I've some issues with some fortinet hosts.
Backups are correct, but on the oxidized web-ui, some rows are blank in the hostname column.
![blankhostnames](https://user-images.githubusercontent.com/37365413/37396504-5f44476c-2779-11e8-8ed1-1ec4bbbe5612.jpg)
Can you help me please ?

Thanks a lot !

rsaeba

**Comment by yzguy** [comment]
If this is a UI issue, then it would probably be more relevant to put it under https://github.com/ytti/oxidized-web, as this repo is that actual "web" part of Oxidized

**Comment by rsaeba** [comment]
Alright, sorry :)
Done
https://github.com/ytti/oxidized-web/issues/157
