### ISSUE TITLE
TFTP/SSH to get configs?

### ISSUE THREAD

**Issue by rhysxevans** [ytti/oxidized#1220]
Hi

I have the following scenario. I need to back up the config of 200+ devices, that dont support a "show run" type "interface". The devices do have the option to backup their config files to a TFTP server, on a trigger (that would be setup beforehand).

Now I have 2 options that I can think of

1) From oxidized server access the tftp server (via tftp) and read the the relevant config file, where config file name is the router name as defined in router.db 
2) SSH into the TFTP server, and "cat" the config file,  where config file name is the router name as defined in router.db

I suppose in both cases we would need to define the "path" on the server to the config directory aswell

Are any of the above options possible ? If so any pointers would be appreciated (please note I am not a coder / developer of any sort)

Thanks

**Comment by ytti** [comment]
https://github.com/ytti/oxidized/blob/4a67e27742c0ab8ed6cd8421d34c01c0de588705/lib/oxidized/model/alvarion.rb

Another example of trivial tftp model would be

```
cmd "filename"
cfg :tftp {}
```

**Comment by rhysxevans** [comment]
Hi

Thanks, for the response. Please forgive my ignorance

So essentially you are saying option 1 above is a workable solution ?

If so I would need to 

1) I would need to create a new "model.rb" file and define this in the config file
2) My router.db would need to look something like
          routername,tftpserverip,model
    Where routername = filename 

Thanks

**Comment by ytti** [comment]
In this case you'd need something more complicated.

Router name would be always same, but you'd have different variable for each file name. For each router (same ip every time) we'd run same model, but the model would ask for file as per the variable.

I'm not even sure if we would load multiple nodes with same name, so I'm not sure if this would work.

I think what would work, is if you have DNS entry once for every node pointing to the same tftp server, then tftpserver has filename as node name. 

But it might be more appealing to actually make Oxidized the TFTP receiver.

Note, I'm not ready to invest time to do any of the above, sorry.

**Comment by rhysxevans** [comment]
ok, thanks. 

I will look into alternative methods
