### ISSUE TITLE
OLT Fiberhome

### ISSUE THREAD

**Issue by kiq-moraes** [ytti/oxidized#1225]
Hi,
Hello,
Our oxidized is working well, collecting backups of switchs and routers from ubiquiti, mirkotik, huawei and datacom routers.
But we need to start saving Fiberhome OLT information.
Has anyone tried? Can you tell if it's possible to implement?
I thank you all.
Caíque.

**Comment by laf** [comment]
It's definitely possible to implement. You should start of by copying an existing model for a device that acts similar to this one.

Please see the docs on creating models: https://github.com/ytti/oxidized/blob/master/docs/Creating-Models.md
