### ISSUE TITLE
Issues with storing configs in git repo

### ISSUE THREAD

**Issue by SaaldjorMike** [ytti/oxidized#123]
I currently have an installation where I started out having only a file output defined, this seems to work perfectly fine. But now I want to move to a git repo, but adding the name, email and repo to a git output, then setting this output as a default seems to not create any files within the git repo. Nothing weird is within the debug log. It contains the usual information that shows that it connects to the devices, runs a few commands and exits.

Suggestions to help me debugging this are very much welcome :-)

**Comment by ytti** [comment]
So you have something like this:

output:
  default: git
  git:
    user: Oxidized
    email: o@example.com
    repo: "/home/ytti/.config/oxidized/oxidized.git"

And it runs happily, but file is not created?

**Comment by SaaldjorMike** [comment]
Yes. Exactly.

**Comment by ytti** [comment]
Yes, it is supposed to create the repo. It does care about indentation, any chance there might be problem there?

**Comment by SaaldjorMike** [comment]
Oh. Stupid me. I assumed that I had to create the repo manually and then Oxidized would then merely add the files to the repo. After removing the repo that I manually created, it seems to work as expected. Sorry for wasting your time.

**Comment by ytti** [comment]
Might still be a bug. There seems to be no particular reason why we couldn't use pre-init repos, and I think that has worked in the past. But it should be bare repo, not checkout.

**Comment by SaaldjorMike** [comment]
I merely did a "git init", thus non-bare.

**Comment by SaaldjorMike** [comment]
I would maybe suggest adding some debugging info somewhere to tell the user that the git repo is not a bare repo.

**Comment by ytti** [comment]
You didn't get any message in syslog?

**Comment by SaaldjorMike** [comment]
I dont see any. :(
