### ISSUE TITLE
telnet/ssh from jumbox

### ISSUE THREAD

**Issue by lplazaparis** [ytti/oxidized#1235]
Hello,

Firs, I would like to thanks the developers for this tool, I think is great!  We got on our switches/routers ACLs that only allow connections from our jumpbox server and I would like to know if is possible to configure oxidizide to use our jumpbox when connecting by ssh/telnet to our devices.

Thanks,

Luis

**Comment by laf** [comment]
SSH input supports proxy which should do what you are looking for.

**Comment by lplazaparis** [comment]
thanks @laf, do you know if I can use proxy for telnet as well?

**Comment by laf** [comment]
We don't currently support it but it does look like Net::Telnet does so support could possibly be added.

**Comment by awlx** [comment]
Is the goal to connect via SSH to the jumphost and jump from there via Telnet? Or already Telnet to the jumphost?

**Comment by lplazaparis** [comment]
Hi @awlx,

yes you are correct, my is goal is to connect via SSH to the jumphost and jump from there via Telnet and this something that I should be able to do using Proxy as @laf said. I haven't have time to see it is possible to add Net::Telnet as he suggested.

**Comment by awlx** [comment]
I will look into this to solve the problem and make a PR if successful :). 

It seems that someone already thought about such stuff:
http://www.rubydoc.info/gems/net-ssh-telnet/0.0.2/Net/SSH/Telnet
