### ISSUE TITLE
Issue with Prompt SonicOS 6.5

### ISSUE THREAD

**Issue by stich86** [ytti/oxidized#1236]
Hi guys,

i'm trying to backup my Sonicwall Firewalls with Oxizided but i'm hanving problem to match the prompt at login:

All my sonicwall are running SonicOS 6.5, this is an example of login prompt:

```
Copyright (c) 2017 SonicWall, Inc.

Using username 'admin'.
Password:

admin@NSA4600-UK>
```

but i got this error on oxi log:

```
D, [2018-03-20T10:28:20.055737 #15777] DEBUG -- : lib/oxidized/input/ssh.rb: Connecting to nsa4600-vip.XXXX
D, [2018-03-20T10:28:20.306801 #15777] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^.*@\w*> $/] at nsa4600-vip.XXXX
W, [2018-03-20T10:28:40.308135 #15777]  WARN -- : 10.100.254.254 raised Oxidized::PromptUndetect with msg "

Copyright (c) 2017 SonicWall, Inc.

Using username 'admin'.
Password:

admin@NSA4600-UK>  not matching configured prompt (?-mix:^.*@\w*> $)"
D, [2018-03-20T10:28:40.308321 #15777] DEBUG -- : lib/oxidized/node.rb: Oxidized::SSH failed for nsa4600-vip.XXXX
```

Can you help me to resolve this issue?

Thanks!

**Comment by stich86** [comment]
ok i've fixed the prompt issue using this regex:

`  prompt /.*@.*> $/`

now i've a problem with SSH timeout. Config is very large, and Oxidized exits for timeout.

Is it possible to increate for a single session or globally?

Thanks

**Comment by ytti** [comment]
Only globally, but we definitely should make this node/group/model var, as it's not atypical to have few outlier boxes.

**Comment by wk** [comment]
Closing this as the actual subject issue is resolved. Further discussion about timeout customization probably belongs in #1044. 

@stich86 there is no SonicOS model currently in master, I see that @rgnv had PR #950 that included SonicOS support, but appears to have closed it after code review. 

If there is a clean and working SonicOS model out there, don't hesitate to PR it in!
