### ISSUE TITLE
API down

### ISSUE THREAD

**Issue by wolf2668** [ytti/oxidized#1237]
Hi,

Today I restart oxidized to load a new model file but now when I try to access to oxidized, I have this error : 
`wget 127.0.0.1:8888/nodes `
`--2018-03-20 12:14:29--  http://127.0.0.1:8888/nodes `
`Connecting to 127.0.0.1:8888... failed: Connection refused.`

`wget 127.0.0.1/nodes `
`--2018-03-20 12:22:39--  http://127.0.0.1/nodes `
`Connecting to 127.0.0.1:80... connected.`
`HTTP request sent, awaiting response... 502 Bad Gateway`
`2018-03-20 12:22:39 ERROR 502: Bad Gateway.`

My versions are : 
oxidized (0.21.0)
oxidized-script (0.5.0)
oxidized-web (0.9.3)

Backups are done, the log file show it, but I cannot have informations about them via the API.

I hope someone can help !
Thanks !

**Comment by laf** [comment]
Seems quite explanatory there, oxidized isn't listening on 8888 so either it's running on a different port or it's failed to start.

**Comment by wolf2668** [comment]
I have this line in my config file : 

`rest: 127.0.0.1:8888`

I have a script that checks if a backup is done or not and it was working on 8888.
Oxidized is working, the log file shows that configurations are reached but I cannot interact with it...

**Comment by laf** [comment]
Run `lsof -i:8888` see if it is actually running. If it is, maybe a firewall in the way.

**Comment by wolf2668** [comment]
Nothing is running on 8888...
The firewall in place do not block this traffic

A `ps aux | grep oxidized` shows : 
`oxidized  8639 21.0 35.3 886820 551820 ?       Ssl  12:10  30:14 /usr/bin/ruby2.3 /usr/local/bin/oxidized`

**Comment by wk** [comment]
Verify that you haven't pulled a too new version of puma for oxidized-web to run in the meanwhile, and downgrade if necessary. See #1216.

**Comment by wolf2668** [comment]
Yes I made a gem update the last week, it's maybe that. I start downgrading to see which version is compatible.

**Comment by wk** [comment]
Per #1216 the last known good compatible version is `3.11.0` (rubygems currently at `3.11.3`). Please report your findings when you establish if this is related to the issue you've been experiencing.

**Comment by wolf2668** [comment]
I did an uninstall of all gems and a reinstall oxidized, oxidized-script and oxidized-web and it's working now. The puma version is `3.11.3` so it's not the puma version...
This is the list of all gems install with the version
```
asetus (0.3.0)
backports (3.11.1)
bigdecimal (1.2.8)
did_you_mean (1.0.0)
emk-sinatra-url-for (0.2.1)
ffi (1.9.23)
haml (4.0.7)
htmlentities (4.3.4)
io-console (0.4.5)
json (1.8.3)
minitest (5.9.0)
multi_json (1.13.1)
net-ssh (4.1.0)
net-telnet (0.1.1)
oxidized (0.21.0)
oxidized-script (0.5.0)
oxidized-web (0.9.3)
power_assert (0.2.7)
psych (2.1.0)
puma (3.11.3)
rack (1.6.9)
rack-protection (1.5.5)
rack-test (0.8.3)
rake (10.5.0)
rb-fsevent (0.10.3)
rb-inotify (0.9.10)
rdoc (4.2.1)
rugged (0.26.0)
sass (3.5.5)
sass-listen (4.0.0)
sequel (5.6.0)
sinatra (1.4.8)
sinatra-contrib (1.4.7)
slop (3.6.0)
sqlite3 (1.3.13)
test-unit (3.1.7)
tilt (2.0.8)
```

I close this issue, thanks for your time !
