### ISSUE TITLE
Sorting configurations

### ISSUE THREAD

**Issue by malkovitch** [ytti/oxidized#124]
HI there !

I wanted to know if it was possible to sort configurations, like with CVS and RANCID.

This is an example of what i'm looking for :

3 devices configuration : hp_conf; cisco_conf; alcatel_conf
3 directories :  CISCO, HP, ALCATEL

I would like to place each file into the appropriate directory. They will be in different location on oxidized-web.

 It should look like http://localhost:8888/nodes/MY_DIRECTORY(i.e:cisco)/devices_configurations

And I want the same page (/nodes) in each directories, where i can refresh the page and update configuration.

Is it possible ?

Thanks

**Comment by ytti** [comment]
I think what you want are 'groups', you can pass in your node list another field 'group' which coudl then be 'cisco', 'hp', 'alcatel', 'router', 'switch', 'poland', 'lab'....

If configuration backend is 'file' then they'll go into that directory. If configuration backend is 'git' then new repo is created with that name, but there is toggle in git settings to instead use single repo with multiple directories.

**Comment by malkovitch** [comment]
I already tried groups but it didn't do what I expected. I'm gonna try with git then, it should do the trick !

Your tool is awesome by the way. Thank you for everything.

**Comment by ytti** [comment]
How didn't it do what was expected in file?

If file directory  is

/foo/bar/configs/default

then if node has group, it'll go

/foo/bar/configs/group/node

if it does not have group, it'll go

/foo/bar/configs/default/node

**Comment by malkovitch** [comment]
That's not what I meant ^^

Files go in /foo/bar/configs/group/node it works fine. But I want to see those folders on the web interface with files inside.

When I go on the web interface I can see all devices configurations in http://@IP:8888/nodes.

What I want look likes this : 

![image](https://cloud.githubusercontent.com/assets/12733654/7983997/cc9cab02-0ac5-11e5-9419-bbeaed94dba8.png)

![image](https://cloud.githubusercontent.com/assets/12733654/7983978/b95aeb58-0ac5-11e5-90ca-415c991f867f.png)

So i can navigate through folders and see my files.

**Comment by ytti** [comment]
Ok. I think this should be filed in oxidized-web. Quick solution would be to use git and periodically push repo to something like gitlab or github, to get extensive GUI support for blame etc.

**Comment by malkovitch** [comment]
Ok i'm gonna try this.

Thanks

**Comment by malkovitch** [comment]
I'v another question, how many devices can oxidized handle ?

**Comment by ytti** [comment]
Dunno, I've ran it with 3k or so devices.
