### ISSUE TITLE
git - username for ssh remote push

### ISSUE THREAD

**Issue by PeepOks** [ytti/oxidized#1240]
Currently username "git" is hardcoded when using hook push_to_remote and ssh authentication. For some environments that could be a problem and error "#<Rugged::SshError: username does not match previous request>" is seen in logs.

It would be better if username would be taken from git repo URL or username config parameter.
Usually, git repo URL contains username. For example:  **gitlab**@git.devinfra:network/nw-confbackups.git

If username can't be found in URL or config parameter then "git" would be used.

**Comment by vppencilsharpener** [comment]
Have you tried changing the remote_repo line to be:
`remote_repo: ssh://gitlab@git.devinfra:network/nw-confbackups.git`

Mine has git@ in it, so this may or may not work, but this is the format I am using.

**Comment by tazmad** [comment]
> Have you tried changing the remote_repo line to be:
> remote_repo: ssh://gitlab@git.devinfra:network/nw-confbackups.git

Mine is actually set as:
`remote_repo: ssh://APKAJ7DIEVDJLHPORKRHA@git-codecommit.eu-west-1.amazonaws.com/v1/repos/oxidized`

and I am still getting the error.

**Comment by PeepOks** [comment]
When I look at githubrepo.rb file then at line 54 when there is parameter `username: 'git'`
If I changed username then ssh authentication started to work.

**Comment by vppencilsharpener** [comment]
Sorry, I saw that format somewhere (can't find where right now) and was hoping it would work. Modifying the /lib/oxidized/hook/githubrepo.rb file is a work around, but would not support different user names for different repos.

I agree that it should pull the username from the repo string and then default to 'git' if one is not present. 

--
In the githubrepo.rb file, is it possible to parse the remote_repo value and then pass the username portion into the credentials definition? 

If regex can be used the parsing should be fairly easy to parse. 
Something like this: `(?:(.+)(?::\/\/))?(?:(.+)(?:@))?(.+):(.+)`
First group is the protocol, second is the username, third is the server and fourth is the repository.

Unfortunately my knowledge of Ruby is limited to coping what others have done so I'm not sure I can help beyond this.

**Comment by wk** [comment]
@vppencilsharpener @PeepOks @tazmad It would be great if you could test [this branch](https://github.com/wk/oxidized/tree/githubrepo-username).

It should:
* Use the `username` key specified in hook configuration if one is present (_NOT RECOMMENDED_, provided mainly for consistency when used in conjunction with a `password` key and for backwards compatibility).
* Use the username extracted from the repository URI if one is present (_RECOMMENDED_).
* Default to 'git' if all else fails.
