### ISSUE TITLE
Question for web interface and nginx integration

### ISSUE THREAD

**Issue by bruccoo3000** [ytti/oxidized#1246]
Hello all,

Need some assistance from the pro's!

I have oxidized setup and starting to back up equipment and am looking to integrate nginx to provide a username and password before seeing the configurations of the devices.

I have oxidized setup as follows as best as I understand the documents:
I have the following set in the oxidized config file:
rest: 127.0.0.1:8888

And then I have the following setup on my nginx config file in the server clause:
auth_basic "Restricted Access, for lab use only";
auth_basic_user_file /etc/nginx/.htpasswd;
location / {
    proxy_pass http://192.168.1.1:8888/;

I am not getting a prompt for a username and password.

I am definitely missing something here.

I thought I wouldn't have to change the oxidized file in order for the proxy_pass to work but I know the connection between both settings is off.

Any help will be appreciated and thanks in advance.

**Comment by waza-ari** [comment]
There is an [example for nginx reverse proxy configuration](https://github.com/ytti/oxidized/blob/master/extra/oxidized.nginx) in the extra directory of the repository.

The authentication settings need to go either in the server or in the location block. Have a look at the [official nginx documentation](https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/)

**Comment by laf** [comment]
I'm closing this issue down as it's not directly related to Oxidized.

**Comment by bruccoo3000** [comment]
Thanks for the link!  That's what I needed.  Got it working.
