### ISSUE TITLE
Aruba Prompt Conflict

### ISSUE THREAD

**Issue by vppencilsharpener** [ytti/oxidized#1254]
The most recent merge (#1182) for the aosw.rb file (resolving Issue #1000) broke compatibility for our Aruba Instant Controller (IAP). To get it working again I had to revert to making spaces optional in the prompt.

Based on the history of the aosw.rb file and other issues. I believe there may be a conflict in the prompt requirements for different devices, models or firmware revisions.

I'm hoping that we can get a few people with different devices and versions to provide information (device/version and prompt) that will allow us to find a solution. 

To support my theory I have this information:

- The prompt on my IAP system is `hostname#`, without any spaces
- The prompt on my Mobility Access Switch is `(hostname) #`, with a space between
- Issue #663 is an IAP prompt problem and lists the prompt as `ap1#` (This was resolved by the user with a local model change). This supports that the IAP versions do not contain a space in the prompt. 
- The AOSW model did not support a prompt without a space until Merge Request #704, which may have caused the problem seen in issue #1000
- Issue #1000 was started as an IAP specific problem, but looks like the original creator abandoned it and it migrated a little bit in Feb. It was resolved by a prompt change, but does not list any device, version or prompt information where the fix was tested.
- Using the previous version of the model I have not seen the "changing config without real changes" problem described midway down issue #1000 

---
My device Info:

Aruba IAP-115, IAP-205, IAP-215 & IAP-325 - (Instant) v6.4.4.8 - Prompt: `hostname#` (no space)
Aruba IAP-115, IAP-205, IAP-215 & IAP-325 - (Instant) v6.5.4.0 - Prompt: `hostname#` (no space)
Aruba MAS S2500-24P - ArubaOS Version 7.4.1.4 - Prompt: `(hostname) #` (has space)

@thanegill @chipgwyn Any chance you can add your device, firmware and prompt info to this issue.

**Comment by thanegill** [comment]
Aruba 3600, Aruba 3400 - v6.4.4.15 Promt: `(hostname) #` (has space)

**Comment by vppencilsharpener** [comment]
@thanegill Do you have any experience with other Aruba equipment? Is the Instant/IAP stuff the only one that uses parentheses? 

I'm wondering if I can rework the prompt to only require the space after the close parentheses.

**Comment by vppencilsharpener** [comment]
Do you have any thoughts on using something like this `^(\(.+\)\s|[^\(\)\s]+)[#>]` for the prompt?

I am testing it now with my IAP and MAS devices.

**Comment by laf** [comment]
What about: `^\(?.+\)?(\s?)[#>]`

Works with:

http://rubular.com/r/y25cHx44Kp

**Comment by vppencilsharpener** [comment]
@laf The previous version, from merge #704 had a very similar prompt, just without the group around the `\s?`. It was causing problems for some users (#1000) with different devices and was reverted to the current version (space required) by merge #1182.

Trying to make everyone happy, the proposed prompt requires a space ONLY when parentheses are present.

**Comment by laf** [comment]
You should submit this as a pull request then :) @vppencilsharpener

**Comment by davama** [comment]
Propose this prompt instead:

`^([\w\(.@-]+(\)?\s?)[#>]\s?)$`

https://rubular.com/r/kTbM6HlCeBxPiu

I can submit PR if need be

**Comment by davama** [comment]
@vppencilsharpener 
I had issues too with the prompt, so i went ahead and submitted PR.

Hope this meets your needs as well.

Thanks!

**Comment by raunz** [comment]
Current master aosw.rb need an update to also include ":" in pattern:
```
<   prompt /^([\w\(.@-]+(\)?\s?)[#>]\s?)$/
---
>   prompt /^([\w\(:.@-]+(\)?\s?)[#>]\s?)$/
```
Aruba OS wifi virtual-controllers prompt name is derived from first access-point name, which by default is access-points MAC address. Here's an example:
```
20:a6:cd:ce:bd:4c#
```
I'll open a PR to improve pattern.
