### ISSUE TITLE
Unable to detect prompt with a very simple device

### ISSUE THREAD

**Issue by morgens** [ytti/oxidized#1271]
Hello everyone. 
I'm having a problem adding a very simple class to oxidized.

I would like to grab config from Zyxel Keenetic devices, which I have plenty in my network.

So I created a simple class like that:
```
class KeeneticVOX < Oxidized::Model
  # Zyxel Keenetic VOX

  comment '# '

  cmd 'more startup-config'

  cfg :telnet do
    username /^Login:/
    password /^Password:/
  end

end
```

and specified a device in router.db
But I see only errors in logs:
```
W, [2018-04-11T13:55:42.423870 #1111]  WARN -- : 10.0.12.1 raised Oxidized::PromptUndetect with msg "unable to detect prompt: (?-mix:^([\w.@-]+[#>]\s?)$)"
W, [2018-04-11T13:55:43.366851 #1111]  WARN -- : azs-12 VOX status no_connection, retries exhausted, giving up
```
I can track successful logins by oxidized to this router, and the output of specified in this class command should look something like that:
```
Login: admin
Password: **********
(config)> more startup-config
! $$$ Model: ZyXEL Keenetic VOX
! $$$ Version: 2.0
! $$$ Agent: http/ci
! $$$ Last change: Tue, 25 Jul 2017 06:07:22 GMT
! $$$ Md5 checksum: 61d0d6b632650d2f5423fa0a3f085802
```

What am I doing wrong? Should I specify a prompt in class? I'm not that great with regular expressions.
I also tried enabling debug mode, but oxidized wouldn't start with that.
I installed oxidized just recently and have a few dozens of routeros devices backuping by it. It's great! But this issue is driving me crazy.
Any advice?

**Comment by laf** [comment]
So the prompt you've shown above doesn't match the regex `^([\w.@-]+[#>]\s?)$`.

You should specify a regex within the new model that will match the prompts on these devices. Lots of examples in existing models you can take a look at.

**Comment by laf** [comment]
You will need to pastebin the full logs when debug is turned on for this device.

**Comment by morgens** [comment]
That's what I have in logs if I enable debug.
https://pastebin.com/zXJ1Spyg

That's what I have in telnet logs.
https://pastebin.com/yReQ0nMG

For some reason I have 1 successfull backup for this particular host, and I have it's config in oxidized storage. But when I make any changes to the config and run oxidized backup again, it doesn't capture anthing, like in the first pastebin. Nothing was captured during that backup.

**Comment by wk** [comment]
Support for the Zyxel Keenetic product range has been introduced in #1286

**Comment by taro-75** [comment]
Hello,
I have the same problem with router oneos6 "Oneaccess when i use oneos.rb 

raised Oxidized::PromptUndetect with msg "unable to detect prompt: (?-mix:^([\w.@()-]+#\s?)$)"
 
when i use 

  prompt /(\(config >\))*/
  comment '# '
  cmd 'more startup-config'
  cfg :telnet do
    username /^Login:/
    password /^Password:/
  end
end

--> The connection to the router work fine but i can't have my running config in the output file !!
This is my output:
#Username

Need help please
