### ISSUE TITLE
Probleme to login into AsyncOS

### ISSUE THREAD

**Issue by hellEVIL-13** [ytti/oxidized#1272]
not work for me :( https://github.com/ytti/oxidized/issues/1172
```
Apr 11 16:10:35 cvs oxidized[27083]: IP.X.X.X raised Oxidized::PromptUndetect with msg "Last login: Wed Apr 11 16:07:43 2018 from IP.X.X.X#015#015#012AsyncOS 11.0.1 for Cisco IronPort C170 build 027#015#012#015#012Welcome to the Cisco IronPort C170 Messaging Gateway(tm) Appliance#015#012#015#012NOTE: This session will expire if left idle for 30 minutes. Any uncommitted#015#012configuration changes will be lost. Commit the configuration changes as soon as#015#012they are made.#15#012#015#012ironport.domen.ru> not matching configured prompt (?-mix:^\r*([(][\w. ]+[)][#>]\s+)$)"

Apr 11 16:10:35 cvs oxidized[27083]: IP.X.X.X raised Oxidized::PromptUndetect with msg "Last login: Wed Apr 11 16:07:43 2018 from IP.X.X.X#015#015#012AsyncOS 11.0.1 for Cisco IronPort C170 build 027#015#012#015#012Welcome to the Cisco IronPort C170 Messaging Gateway(tm) Appliance#015#012#015#012NOTE: This session will expire if left idle for 30 minutes. Any uncommitted#015#012configuration changes will be lost. Commit the configuration changes as soon as#015#012they are made.#15#012#015#012ironport.domen.ru> not matching configured prompt (?-mix:^\r*([(][\w. -]+[)][#>]\s+)$)"
```

AsyncOS 11.0.1 for Cisco IronPort C170 build 027

Welcome to the Cisco IronPort C170 Messaging Gateway(tm) Appliance

NOTE: This session will expire if left idle for 30 minutes. Any uncommitted configuration changes will be lost. Commit the configuration changes as soon as they are made.

ironport.domen.ru>

my cli without ()

in log of c170

User logged out from session because of inactivity timeout.

if edit prompt to:

prompt "ironport.domen.ru> " than work

and first config show error
Encoding::UndefinedConversionError at /node/version/diffs
"\xD0" from ASCII-8BIT to UTF-8

**Comment by hellEVIL-13** [comment]
AsyncOS 11.0.1 for Cisco IronPort C170 build 027

Welcome to the Cisco IronPort C170 Messaging Gateway(tm) Appliance

NOTE: This session will expire if left idle for 30 minutes. Any uncommitted configuration changes will be lost. Commit the configuration changes as soon as they are made.

ironport.domen.ru>

my cli without ()

**Comment by wk** [comment]
Since thee device returns the prompt without the brackets (which are currently expected by the model), you can try something like `/^\r*([(]?[\w. ]+[)]?[#>]\s+)$/` as a prompt instead.

Guessing about the encoding error will require seeing logs of the interaction between the device and oxidized. You could follow the steps outlined [here](https://github.com/ytti/oxidized/blob/master/docs/Configuration.md#debugging) and append the collected logs to this issue.

**Comment by hellEVIL-13** [comment]
Yes, this prompt works for me, thanks a lot

**Comment by wk** [comment]
I've created #1339 to introduce this prompt change into master.

Are you still experiencing `Encoding::UndefinedConversionError` errors and expect to be adding logs to this issue, or can the issue be now closed?

**Comment by hellEVIL-13** [comment]
I understand that this does not apply to oxydized and the problem in gems / htmlentities is 4.3.4, yes I think you can close.
