### ISSUE TITLE
Comware 3 and 7 issue

### ISSUE THREAD

**Issue by majordom21** [ytti/oxidized#1278]
Hello, 

I'm a newbie with this software. I'm learning how to use it. I've got only comware switches.

Comware 3 : old 3 com (42100, 5500)
Comware 5 : HP 3600
Comware 7 : HP 5120 5130

Everything is OK with comware 5 but I've got issue with comware 3&7.

**"raised Timeout::Error with msg "execution expired""**

I found in your doc your command "**info-center source default channel 1 log state off debug state off**" but it does not resolv the problem.

I don't know well enough to understand why ? If someone can help me I'd appreciate.

--
Dom

Sorry for my english

**Comment by martinohansen** [comment]
@majordom21 can you elaborate on what you did to solve this on issue on Comware 7? Thanks.

**Comment by majordom21** [comment]
I wrote `timeout: 600` in the config file. The switch to analyse is a 5 devices stack. It need more time

**Comment by martinohansen** [comment]
Solved the issue in #1583, thanks.
