### ISSUE TITLE
LibreNMS-Oxidized integration. sync status:success but no config is shown

### ISSUE THREAD

**Issue by Ryuraiden** [ytti/oxidized#1298]
Hello @ytti ,

As the title says, In libre, i see the "Config" tab, and inside  is the following in the picture
![image](https://user-images.githubusercontent.com/18699556/39098097-e2335c34-4665-11e8-8cab-b0b9b8e83853.png)

My oxidized.service is working fine and taking backup of my cisco devices. I have googled and searched but with no luck. 

On "LibreNMS External settings" i've enabled everything and sat the url to http://127.0.0.1:8888

Oxidized service is run by the oxidized user. Oxidized is installed on same server as LibreNMS.
This is my oxidized config:

---
username: oxidized
password: password
model: ios
interval: 3600
use_syslog: false
debug: false
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 127.0.0.1:8888
next_adds_job: false
vars: {}
groups: {}
models: {}
pid: "/home/oxidized/.config/oxidized/pid"
input:
  default: ssh, telnet
  debug: false
  ssh:
    secure: false
output:
  default: file
  file:
    directory: "/home/oxidized/.config/oxidized/configs"
source:
  default: csv
  csv:
    file: "/home/oxidized/.config/oxidized/router.db"
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
    gpg: false
model_map:
  cisco: ios
  juniper: junos

pls help med fixing this issue

**Comment by davama** [comment]
As the librenms docs say
```
Integrating LibreNMS with Oxidized brings the following benefits:

Config viewing: Current, History, and Diffs all under the Configs tab of each device
```

It is not very clear but i belive you need output `git` for that to work

At least that us how we have it in our enviroment.
Also, do librenms and oxidized live in the same host? because your oxidized api is in 127.0.0.1:8888

Hope that helps

**Comment by laf** [comment]
This isn't an oxidized question and you should direct your question to LibreNMS: https://docs.librenms.org/#Support/
