### ISSUE TITLE
Release 0.22.0

### ISSUE THREAD

**Issue by ytti** [ytti/oxidized#1313]
1. get PR's in, at least selected ones
 2. update changelog
 3. set docker to build tags
 4. any issues that should be solved?

**Comment by jsynack** [comment]
Was @laf still suffering from a worker deadlock issue?

**Comment by laf** [comment]
@jsynack The PR I put in that fixes that for us has been merged so would be in 0.20.0.

That hasn't resolved some other issues for slow downs that other see according to those who responded.

**Comment by ytti** [comment]
For better or worse, done.
