### ISSUE TITLE
crash when runned by systemd

### ISSUE THREAD

**Issue by FlorianDoublet** [ytti/oxidized#132]
I'm actually on Debian 8 (Jessie) and would like to run oxidized as a service.
But it failed with a very simple script  in /lib/systemd/system/oxidized.service : 

[Unit]
Description=Oxidized Server

[Service]
ExecStart=/usr/bin/oxidized

[Install]
WantedBy=multi-user.target

but if I launch it with "systemctl start oxidized.service " it crash.
Then I do "system status oxidized.service" to check the error and I get this :

Jun 16 16:15:24 oxidized oxidized[13652]: no implicit conversion of nil into String
Jun 16 16:15:24 oxidized oxidized[13652]: /var/lib/gems/2.1.0/gems/oxidized-0.7.1/bin/oxidized:12:in `rescue in <top (required)>': unini...meError)
Jun 16 16:15:24 oxidized oxidized[13652]: from /var/lib/gems/2.1.0/gems/oxidized-0.7.1/bin/oxidized:7:in `<top (required)>'
Jun 16 16:15:24 oxidized oxidized[13652]: from /usr/bin/oxidized:23:in `load'
Jun 16 16:15:24 oxidized oxidized[13652]: from /usr/bin/oxidized:23:in `<main>'
Jun 16 16:15:24 oxidized systemd[1]: oxidized.service: main process exited, code=exited, status=1/FAILURE
Jun 16 16:15:24 oxidized systemd[1]: Unit oxidized.service entered failed state.

(but if I run by myself /usr/bin/oxidized it work)

**Comment by FlorianDoublet** [comment]
the exact message is " /var/lib/gems/2.1.0/gems/oxidized-0.7.1/bin/oxidized:12:in `rescue in <main>': uninitialized constant Oxidized::CFG (NameError) "

**Comment by ytti** [comment]
What was the problem and solution?

**Comment by FlorianDoublet** [comment]
Sorry, I was going the propose the script in extra.
In fact it's just because I don't mentionned the user !

So with just : 

[Unit]
Description=Oxidized Server

[Service]
ExecStart=/usr/bin/oxidized
User=root
[Install]
WantedBy=multi-user.target

Oxidized is now a service, start stop and restart work (and it's smaller than the oxidized.init)

**Comment by ytti** [comment]
Yeah send PR and we'll add it to extra!

On 17 June 2015 at 10:03, Florian Doublet <notifications@github.com> wrote:

> Sorry, I was going the propose the script in extra.
> In fact it's just because I don't mentionned the user !
>
> So with just :
>
> [Unit]
> Description=Oxidized Server
>
> [Service]
> ExecStart=/usr/bin/oxidized
> User=root
> [Install]
> WantedBy=multi-user.target
>
> Oxidized is now a service, start stop and restart work (and it's smaller
> than the oxidized.init)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ytti/oxidized/issues/132#issuecomment-112682733>.
>



-- 
  ++ytti
