### ISSUE TITLE
Arris C4 CMTS - Temp gsub - Illegal/unsupported escape sequence

### ISSUE THREAD

**Issue by cppmonkey** [ytti/oxidized#1321]
https://github.com/ytti/oxidized/blob/d3c5d49c2045bce7891f45259b58495fd690f3fd/lib/oxidized/model/c4cmts.rb#L20

`    cfg.gsub! /\s+[\-\d]+\s+C\s+[\(\s\d]+\s+\F\)/, ''	# remove temperature readings
`

RubyMine flags the \F as illegal/unsupported escape sequence.

Best guess is they wanted to specify the string will end with F (Fahrenheit) but this doesn't need to escaped.

I'd submit a pull request to correct this, but I don't have the hardware to validate the changes still function.

**Comment by wk** [comment]
https://github.com/ruby/ruby/blob/trunk/re.c suggests that `\F` is indeed a non-existent meta-character and will be treated as `F`. It should be safe to drop the escape character.
