### ISSUE TITLE
hillstone device backup error,pls help

### ISSUE THREAD

**Issue by macaty** [ytti/oxidized#1335]
1.new modle
[root@netconfig model]# cat stoneos.rb 
class Stoneos < Oxidized::Model
  prompt /^\r?[\w.\(\)-]+[#>]$/
  comment '# '
  
  cmd :all do |cfg|
    cfg = cfg.lines.to_a[1..-2].join
  end

  cmd :secret do |cfg|
    cfg
  end

  cmd 'show configuration running' do |cfg|
    cfg
  end

  cmd 'show version' do |cfg|
    comment cfg
  end

  cfg :telnet do
    username(/^login:/)
    password(/^Password:/)
  end

  cfg :telnet, :ssh do
    pre_logout 'exit'
  end
end
2. log
I, [2018-05-08T09:25:12.803318 #1]  INFO -- : lib/oxidized/nodes.rb: Loaded 1 nodes
D, [2018-05-08T09:25:13.476223 #1] DEBUG -- : lib/oxidized/core.rb: Starting the worker...
D, [2018-05-08T09:25:13.476949 #1] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 0 of 1
D, [2018-05-08T09:25:13.485664 #1] DEBUG -- : lib/oxidized/worker.rb: Added NHhillstone to the job queue
D, [2018-05-08T09:25:13.485844 #1] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2018-05-08T09:25:13.486036 #1] DEBUG -- : lib/oxidized/job.rb: Starting fetching process for NHhillstone at 2018-05-08 09:25:13 UTC
D, [2018-05-08T09:25:13.489646 #1] DEBUG -- : lib/oxidized/input/ssh.rb: Connecting to NHhillstone
D, [2018-05-08T09:25:13.631125 #1] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^\r?[\w.\(\)-]+[#>]$/] at NHhillstone
D, [2018-05-08T09:25:14.489219 #1] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2018-05-08T09:25:15.489709 #1] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2018-05-08T09:25:16.490201 #1] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2018-05-08T09:25:17.490598 #1] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2018-05-08T09:25:18.491061 #1] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel

3.logs 

[root@netconfig logs]# cat 192.168.71.206-ssh 
SG-6000(M)#

**Comment by macaty** [comment]
[stoneos_log.zip](https://github.com/ytti/oxidized/files/1983244/stoneos_log.zip)

**Comment by wk** [comment]
It appears like your device may be returning a white space at the end of the prompt which you do not match, you could try `/^\r?[\w.()-]+[#>](\s)?$/` as a prompt instead and see if that gets you further.

**Comment by macaty** [comment]
it works , thx a lots.
[stoneos.rb.zip](https://github.com/ytti/oxidized/files/1986066/stoneos.rb.zip)

**Comment by laf** [comment]
@macaty If this is a new model can you submit a pull request so others can benefit from this? Please ensure you update the https://github.com/ytti/oxidized/blob/master/docs/Supported-OS-Types.md as well.
