### ISSUE TITLE
Fail to run "git index no longer exists"

### ISSUE THREAD

**Issue by subkhanave** [ytti/oxidized#1337]
Oxidized won't start since it cannot found git index, but its there
What should I do?

```
[root@localhost oxidized]# cat crash
--------------------------------------------------
2018-05-09 02:44:18 UTC
failed to read index: '/home/oxidized/.config/oxidized/oxidized.git/index' no longer exists [Rugged::IndexError]
--------------------------------------------------
/usr/local/share/gems/gems/oxidized-0.21.0/lib/oxidized/output/git.rb:184:in `index'
/usr/local/share/gems/gems/oxidized-0.21.0/lib/oxidized/output/git.rb:184:in `update_repo'
/usr/local/share/gems/gems/oxidized-0.21.0/lib/oxidized/output/git.rb:171:in `update'
/usr/local/share/gems/gems/oxidized-0.21.0/lib/oxidized/output/git.rb:57:in `store'
/usr/local/share/gems/gems/oxidized-0.21.0/lib/oxidized/worker.rb:54:in `process'
/usr/local/share/gems/gems/oxidized-0.21.0/lib/oxidized/worker.rb:16:in `block in work'
/usr/local/share/gems/gems/oxidized-0.21.0/lib/oxidized/worker.rb:16:in `each'
/usr/local/share/gems/gems/oxidized-0.21.0/lib/oxidized/worker.rb:16:in `work'
/usr/local/share/gems/gems/oxidized-0.21.0/lib/oxidized/core.rb:36:in `run'
/usr/local/share/gems/gems/oxidized-0.21.0/lib/oxidized/core.rb:28:in `initialize'
/usr/local/share/gems/gems/oxidized-0.21.0/lib/oxidized/core.rb:4:in `new'
/usr/local/share/gems/gems/oxidized-0.21.0/lib/oxidized/core.rb:4:in `new'
/usr/local/share/gems/gems/oxidized-0.21.0/lib/oxidized/cli.rb:12:in `run'
/usr/local/share/gems/gems/oxidized-0.21.0/bin/oxidized:9:in `<top (required)>'
/usr/local/bin/oxidized:23:in `load'
/usr/local/bin/oxidized:23:in `<main>'
--------------------------------------------------
[root@localhost oxidized]# 
```

**Comment by laf** [comment]
Is the file / dir owned by the correct user?

**Comment by subkhanave** [comment]
yes, the files are owned by oxidized user, no issue file owner
I have this experience twice after server reboot unplanned then the git repo preventing the oxidized to run

If I delete the dir oxidized.git the proccess would run normally but I lose all the data.
Since oxidized use git bare repo, how to make sure if the repo is not corrupted? and how to repair it?

**Comment by laf** [comment]
Maybe give this a try: https://rewoo.wordpress.com/2012/02/14/recover-a-corrupt-git-bare-repository/

**Comment by subkhanave** [comment]
thanks laf , already done that but still no luck
if I clone the bare repo it says empty repo

**Comment by laf** [comment]
@subkhanave Might be worth moving the dir out of the way and let oxidized recreate it. You will lose what you had but I don't have any other suggestions.

**Comment by subkhanave** [comment]
sadly since I do not have any options I need to create new git. Why every unplanned reboot crashed the git repo
is there any way to backup/clone git bare repo?

thanks

**Comment by laf** [comment]
I've never experienced a corrupt git dir from a system crash before.

You should just be able to copy the dir to make a backup.
