### ISSUE TITLE
File storage - Append suffix to file name

### ISSUE THREAD

**Issue by Mattz0r** [ytti/oxidized#1349]
Hello,

I've been trying to search for this, as I don't like creating issues really!

Basically we require configs to be stored locally but I would like to append the timestamp to the file name...

Is this possible, without using version control software.

**Comment by wk** [comment]
There is no feature for this currently, but you could do one of two things:

* Modify `lib/oxidized/file.rb` to include a timestamp in the generated filename
* Define a new output type within a model to include a filename (see the `Advanced` section in  `docs/Creating-Models.md`)

It is, however, indeed strongly recommended to simply use a RCS like `git` to keep a history of configuration files.

**Comment by ytti** [comment]
We could implement masking/flag 

```
output:
  file:
    name: /dir/%y-%m-%dT%h:%m/%node
```

Some such

**Comment by Mattz0r** [comment]
OK Thanks, will have a look.
