### ISSUE TITLE
"Get all logs" function

### ISSUE THREAD

**Issue by RichiH** [ytti/oxidized#135]
Sometimes, it might be nice to have a snapshot of all logfiles at a given time.

This is highly optional, but dumping all logfiles of all configured devices in a timestamped directory and _not_ checking this into Git may be nice in some situations.

**Comment by ytti** [comment]
Can you elaborate? We only should have syslog, no other files. And we cannot know where they go, if anywhere.
Crashfiles and debugging files are separate, but perhaps not relevant.

And if I've misunderstood, and there is an issue, is it oxidized or oxidized-web?

**Comment by ytti** [comment]
Any update?

**Comment by ytti** [comment]
Closed due to inactivity.

**Comment by RichiH** [comment]
I will implement this as a local change to the models. It was too controversial for proper upstream, anyway.
