### ISSUE TITLE
CTC Union - Custom RB

### ISSUE THREAD

**Issue by nubduck** [ytti/oxidized#1353]
Hello, this is my first time trying to do custom RBs for the subject device ranges.
I have already verified the Model/Class to be "CTCU" and made some minor changes in the codes below. I adopted the format from ios.rb into the following.

ctcu.rb: https://pastebin.com/uwGT5wLa
Debug Output file: https://pastebin.com/QNjt1k2V
Logs: oxidized[27129]: <ip> raised Timeout::Error with msg "timed out while waiting for more data"

Any help would be great, I can offer remote access to sample devices if necessary. After all that is done, will put a pull request back :)

Thanks again!

**Comment by laf** [comment]
It's because `^MSwitch#` isn't detected as a prompt. Your regex would need to include support for picking up the `^M` control character.
