### ISSUE TITLE
Unable to Pull Cisco ASA Config

### ISSUE THREAD

**Issue by Neggly** [ytti/oxidized#1354]
I am trying to configure an ASA with Oxidized but the log file keeps telling me "status no_connection" and goes through it's attempts.  I have tried many different configurations with no success.  I have put my current configuration below.  Can someone help me figure out why I cannot pull this config?

**config group:**
```
groups:
  asadev:
    username: myusername
    password: mypw
    enable:          <-----(Currently nothing here. I have tried 'blank' here)
```

**router.db**
`10.12.1.1:ios:asadev`

Edit1: I have confirmed that I can connect to the device using ssh.

**Comment by cppmonkey** [comment]
Have you tried setting it to true?
`enable: true`

Having checked the code, that wouldn't work, but if you change it to the following
_lib/oxidized/model/asa.rb Ln 46-55_
`cfg :ssh do
    if vars :enable
      post_login do
        send "enable\n"
        unless vars(:enable).is_a? TrueClass
          cmd vars(:enable)
        end
      end
    end
    post_login 'terminal pager 0'
    pre_logout 'exit'
  end`

I found it in _lib/oxidized/model/neatgear.rb_

**Comment by laf** [comment]
@Neggly You should just need to set it to `''`:

`enable: ''`
