### ISSUE TITLE
Modifying ruby scripts to exclude information

### ISSUE THREAD

**Issue by dfsbagwellj** [ytti/oxidized#1355]
At my company we use Cisco ACE load balancers.  While I am able to scrape configuration off them successfully, I'm finding that a new scrape is having to be done every hour due to change in the amount of free memory and updated kernel updates.  We are not worried too much about that information here.  I am having similar issues with inconsequential VTP updates on a few cisco switches as well.  My question is, can the .rb scripts for IOS and ACSW be modified to NOT check for that information?

**Comment by nubduck** [comment]
Not too familiar with ACSW, but you can always modify the ios.rb.

Just delete/comment out this section starting: https://github.com/ytti/oxidized/blob/master/lib/oxidized/model/ios.rb#L108

**Comment by dfsbagwellj** [comment]
Thank you for your reply.  Since you marked what to comment out I understand a bit better how the ruby script works.  I think to resolve my ACSW issue I need to comment out the "show version" line in the script.  That is the command that reports memory free and kernel uptime. I'll make these modifications and see what happens and report back.

**Comment by dfsbagwellj** [comment]
So, update time.  I was able to comment out the VTP command in the IOS script and that worked pretty well.  However, for 3500 series switches I would have to comment out the entirety of the "show version" command in order to stop the hourly spam coming from them.  Our solution will be to upgrade these switches to 3750 with the most current code for them.  Oxidized doesn't generate spam with them when they are polled, so that should resolve the issue.  We do have a 3750 running older code that is spamming config changes, but I suspect a code upgrade would resolve the issue.  Instead, we are going to upgrade that 3750 to a newer switch that should not have an issue.
