### ISSUE TITLE
Oxidized as a service CentOS 7.1

### ISSUE THREAD

**Issue by Lukiko** [ytti/oxidized#1358]
Does the oxidized.service extra still work? I've moved it to the correct location /etc/systemd/system but calling it does nothing.

![oxidized_status](https://user-images.githubusercontent.com/12966742/40813744-6fa091a0-650a-11e8-9181-1c630771adea.JPG)

There is nothing in /usr/local/bin. Is it supposed to be this way?

**Comment by Lukiko** [comment]
Thank you for your help! I resolved the issue due to a per-user rvm installation as well as rvm requiring /bin/ in the filepath being changed to /wrappers/ or it won't execute.

I did update the oxidized-web issue though - it seems oxidized-web (0.10.1) is no longer working with the new release.

**Comment by ytti** [comment]
What error are you getting, I didn't test anything at all, so I'm not surprised, but I'll fix it ofc.

**Comment by Lukiko** [comment]
@ytti thank you for the new release! I just posted a new issue in oxidized-web. It may be related to oxidized-web using/requiring oxidized 0.21.0. I posted the crash and logs in there. Thank you again!

**Comment by wk** [comment]
@Lukiko issue ytti/oxidized-web#168 appears to be resolved; is this issue also resolved for you and can both be closed?

**Comment by Lukiko** [comment]
Yes please close both. Thank you again!
