### ISSUE TITLE
tplink model can not loign into TL-SG3210 1.0 switch

### ISSUE THREAD

**Issue by sq9mev** [ytti/oxidized#1367]
Telnet session log:

```
***************** User Access Login ********************

User:

 Login invalid.

***************** User Access Login ********************

User:

 Login invalid.

***************** User Access Login ********************

User:

 Login invalid.
```

First thing i've notices is that username regexp in https://github.com/ytti/oxidized/blob/5cfdbaa959b86d2c8e65963a828ab309302c9020/lib/oxidized/model/tplink.rb#L44 does not match device username prompt, so, a've changed it to match it (`username /^User:/`) but it's not enough. Session log with altered username  regexp:

```

***************** User Access Login ********************

User:

 Login invalid.

***************** User Access Login ********************

User:oxidized
Password:

 Login invalid.

***************** User Access Login ********************

User:USERNAME-PASSWORD(NOT ENABLE-PASSWORD)
Password:

 Login invalid.
```

Notice, 1st login attempt - username is empty, 2nd attempt - correct username is used, but no password is sent; in the last, 3rd attempt user password (not enable password) is send as a username. I can not imagine what exactly happens here…

Seems to me like some magic-chars issue, but not sure how to debug this issue.

Does the session log contain all chars sent over the wire, or is it filtered with cmd:all in https://github.com/ytti/oxidized/blob/5cfdbaa959b86d2c8e65963a828ab309302c9020/lib/oxidized/model/tplink.rb#L20 or expects in https://github.com/ytti/oxidized/blob/5cfdbaa959b86d2c8e65963a828ab309302c9020/lib/oxidized/model/tplink.rb#L8 and https://github.com/ytti/oxidized/blob/5cfdbaa959b86d2c8e65963a828ab309302c9020/lib/oxidized/model/tplink.rb#L15

?

**Comment by sq9mev** [comment]
I've tried to dump telnet session over the wire using tcpdump and analyze it with wireshark… oxidized sends `\radmin\r` as username, so i've removed the expect (see https://github.com/lubiewiatr/oxidized/commit/f463858f0fea344af2f29aa39c28c4cb231cf8b7) and my config was collected correctly.

However, this expect is probably required for some reason (possibly it'srequired by TL-SG3424P 2.0 - see #703, #728).

To sume up my proposal is:

1. extend username regexp to match `User:` as well
1. modify regexp in oxidized/lib/oxidized/model/tplink.rb to match anything but 'User:', so behaviour for devices emitting `User ?[Nn]ame` would remain as before.

What do you think?

**Comment by sq9mev** [comment]
There's another problem - we have another tplink device,  Hardware Version     - T1600G-28TS 2.0 Software Version     - 2.0.0 Build 20160922 Rel.68676(s), which does not require enable password. In all our devices enabling is required to successfully collect config.
See https://github.com/ytti/oxidized/blob/5cfdbaa959b86d2c8e65963a828ab309302c9020/lib/oxidized/model/tplink.rb#L49-L53 - enable is emitted when var enable is set in router.db, but semanticaly enable is not boolean meaning "emit enable or not", it's string containing enable password, so setting it for device which does not require enable password is senseless, and posiibly might be dangerous, if someone sets enable password for eg. "reset" or "reboot" or sth like this.

**Comment by wk** [comment]
> 1. extend username regexp to match User: as well
> 2. modify regexp in oxidized/lib/oxidized/model/tplink.rb to match anything but 'User:', so behaviour for devices emitting User ?[Nn]ame would remain as before.

Sounds reasonable. Not modifying behavior for existing users of the model is a big plus.

> - enable is emitted when var enable is set in router.db, but semanticaly enable is not boolean meaning "emit enable or not", it's string containing enable password, so setting it for device which does not require enable password is senseless, and posiibly might be dangerous, if someone sets enable password for eg. "reset" or "reboot" or sth like this.

In Oxidized, this is exactly the meaning of `enable` setting in a source, and many models use this construction. The argument that passing a dangerous string is dangerous can also be made about usernames and passwords, as the target node may be configured in a manner that does not require a username or password at all, displays an unusual prompt, or behaves unexpectedly otherwise.

While it is possible to introduce a dedicated `enable_required` knob, and check for it in all models that send enable, this seems like a cumbersome, backwards incompatible workaround for a somewhat questionable concern. I am unable to find a single issue in the issue history (spanning +/- 4 years) of actual adverse effects as a consequence of this being observed by users.

**Comment by sq9mev** [comment]
> While it is possible to introduce a dedicated enable_required knob, […]

This would be senseless, this is pretty clear. My proposal for this model is:

https://github.com/lubiewiatr/oxidized/blob/8604aa7ba445cd0f7c7c56b43d203aa588009125/lib/oxidized/model/tplink.rb#L48-L54

This way dummy enable password is not required in router.db for devices that does not require enable password (but requires enable mode to collect config), but on the other hand, `enable` would be emitted for all devices using this model. Don't know which is better, but most of devices supports very limitted set of commands in not-enabled mode…

**Comment by naeternitas** [comment]
I have some trooble with  all my tplink devices
TL-SG5412F 1.0
T1600G-52TS
T2600G-28TS
all of them giving to me same error in connection log
 cat /root/.config/oxidized/logs/*
***************** User Access Login ********************

User:

 Login invalid.

***************** User Access Login ********************

User:

 Login invalid.

***************** User Access Login ********************

User:

 Login invalid.
