### ISSUE TITLE
oxidized not starting - "undefined method `new' for nil:NilClass"

### ISSUE THREAD

**Issue by bydunai** [ytti/oxidized#1371]
So, I'm trying to play with oxidized in a docker format.
I've run into some problems trying to make a use of groups and then noticed that version 0.22 was released.
So I've started off with a clean slate - I erased all docker images and containers.
I executed this command:
`docker run -v /etc/oxidized:/root/.config/oxidized -p 8888:8888/tcp -t oxidized/oxidized:latest`
And docker successfully downloaded all necessary stuff for itself.
The container has run but now it gives me such mistakes:

```
Jun  7 17:46:28 bc91bf79b656 oxidized[2074]: Oxidized starting, running as pid 2074
Jun  7 17:46:28 bc91bf79b656 oxidized[2074]: lib/oxidized/nodes.rb: Loading nodes
Jun  7 17:46:28 bc91bf79b656 oxidized[2074]: Oxidized crashed, crashfile written in /root/.config/oxidized/crash
undefined method `new' for nil:NilClass
/var/lib/gems/2.3.0/gems/oxidized-0.22.0/lib/oxidized/nodes.rb:15:in `block in load': undefined method `new' for nil:NilClass (NoMethodError)
	from /var/lib/gems/2.3.0/gems/oxidized-0.22.0/lib/oxidized/nodes.rb:128:in `synchronize'
	from /var/lib/gems/2.3.0/gems/oxidized-0.22.0/lib/oxidized/nodes.rb:128:in `with_lock'
	from /var/lib/gems/2.3.0/gems/oxidized-0.22.0/lib/oxidized/nodes.rb:10:in `load'
	from /var/lib/gems/2.3.0/gems/oxidized-0.22.0/lib/oxidized/nodes.rb:123:in `initialize'
	from /var/lib/gems/2.3.0/gems/oxidized-0.22.0/lib/oxidized/core.rb:14:in `new'
	from /var/lib/gems/2.3.0/gems/oxidized-0.22.0/lib/oxidized/core.rb:14:in `initialize'
	from /var/lib/gems/2.3.0/gems/oxidized-0.22.0/lib/oxidized/core.rb:4:in `new'
	from /var/lib/gems/2.3.0/gems/oxidized-0.22.0/lib/oxidized/core.rb:4:in `new'
	from /var/lib/gems/2.3.0/gems/oxidized-0.22.0/lib/oxidized/cli.rb:12:in `run'
	from /var/lib/gems/2.3.0/gems/oxidized-0.22.0/bin/oxidized:8:in `<top (required)>'
	from /usr/local/bin/oxidized:23:in `load'
	from /usr/local/bin/oxidized:23:in `<main>'
```
I'm using the same config and the same router.db as before.
Here they are.
> config
```
---
username: test
password: test
model: junos
resolve_dns: false
interval: 3600
use_syslog: true
debug: true
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 0.0.0.0:8888
next_adds_job: false
vars: {}
groups:
  mt:
    username: configer
    password: some_password
    ssh_port: 50222
models: {}
//  routeros:
//    username: configer
//    password: some_password
//    input: ssh
pid: "/root/.config/oxidized/pid"
input:
  default: ssh, telnet
  debug: false
  ssh:
    secure: false
  ftp:
    passive: true
  utf8_encoded: true
output:
  default: git
  git:
    user: oxidized
    email: oxidized@b.bydunai.net
    repo: "/root/.config/oxidized/configs.git"
source:
  default: csv
  csv:
    file: "/root/.config/oxidized/router.db"
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
      username: 2
      password: 3
      ip: 4
      group: 6
    vars_map:
      ssh_port: 5
    gpg: false
model_map:
  cisco: ios
  juniper: junos
```
>router.db:
`b:routeros:::192.168.67.1:50222:mt`

Could you please help me with this?

**Comment by ytti** [comment]
Yeah I'm sure I broke it here:
https://github.com/ytti/oxidized/commit/ea181e93f90ada5d74921cab7ba89e308b9ea1e3 

I just now need to understand how.

So you have just one node in the whole system?

Can you you write
oxidized -v

it seems like it has not been able to load the 'routeros' model, or at least has not passed the class to the node.

**Comment by ytti** [comment]
It might work after docker finishes building
https://hub.docker.com/r/oxidized/oxidized/builds/

**Comment by bydunai** [comment]
Alright, it starts now, thank you.
But it seems, oxidized doesn't notice `ip` field inside router.db.
config and router.db haven't change since I posted them earlier.
```
2018-06-07 18:53:19 UTC
getaddrinfo: Name or service not known [SocketError]
--------------------------------------------------
/usr/lib/ruby/vendor_ruby/net/telnet.rb:350:in `initialize'
/usr/lib/ruby/vendor_ruby/net/telnet.rb:350:in `open'
/usr/lib/ruby/vendor_ruby/net/telnet.rb:350:in `block in initialize'
/usr/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
/usr/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
/usr/lib/ruby/vendor_ruby/net/telnet.rb:349:in `initialize'
/var/lib/gems/2.3.0/gems/oxidized-0.22.0/lib/oxidized/input/telnet.rb:22:in `new'
/var/lib/gems/2.3.0/gems/oxidized-0.22.0/lib/oxidized/input/telnet.rb:22:in `connect'
/var/lib/gems/2.3.0/gems/oxidized-0.22.0/lib/oxidized/node.rb:66:in `run_input'
/var/lib/gems/2.3.0/gems/oxidized-0.22.0/lib/oxidized/node.rb:43:in `block in run'
/var/lib/gems/2.3.0/gems/oxidized-0.22.0/lib/oxidized/node.rb:38:in `each'
/var/lib/gems/2.3.0/gems/oxidized-0.22.0/lib/oxidized/node.rb:38:in `run'
/var/lib/gems/2.3.0/gems/oxidized-0.22.0/lib/oxidized/job.rb:9:in `block in initialize'
```
web-interface:
```
{:name=>"b",
 :full_name=>"mt/b",
 :ip=>"b",
 :group=>"mt",
 :model=>"RouterOS",
 :last=>
  {:start=>2018-06-07 18:53:19 UTC,
   :end=>2018-06-07 18:53:19 UTC,
   :status=>:no_connection,
   :time=>0.010043352},
 :vars=>{:ssh_port=>"50222"}}
```

**Comment by ytti** [comment]
By default we resolve:
https://github.com/ytti/oxidized/blob/master/lib/oxidized/config.rb#L23

If we don't resolve, it should use the IP:
https://github.com/ytti/oxidized/blob/master/lib/oxidized/node.rb#L18-L20

**Comment by bydunai** [comment]
That's right. Do you find my config correct?

**Comment by ytti** [comment]
Dunno I think this has been broken for a year. Since 2017 February we use name as IP if we don't have resolution on. I'm sure there was some logic to it, but I can't think of what, and I've change the logic.

When docker builds it might work for you, but honestly I'm not anymore sure what the expected logic is regarding passing node, and ip and which should be used and how (before or after resolution).

**Comment by bydunai** [comment]
Sooo... I'm not sure I get it.
I thought that logic is this.
`name` - some hostname that is used for identification of a host. If name resolution is enabled, and there is no explicit `ip` value for this host, it should be attempted to be resolved.
Am I missing something?

**Comment by ytti** [comment]
I can't tell you what the logic should be, I don't remember all demands, there has been all kind of corner cases how people want it to behave. But let's see if the latest push fixes it for you,

**Comment by bydunai** [comment]
Yeap, the last docker image recognizes `ip` at router.db again, as it was at 0.21 version.
But then again, I have this weird problem with oxidized not using data provided at group section.
So, again, the config is the same as before. Here is the output:
```
sudo docker run -v /etc/oxidized:/root/.config/oxidized -p 8888:8888/tcp -t oxidized/oxidized:latest
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/my_init.d/10_syslog-ng.init...
Jun  7 20:46:54 ef060b804a7a syslog-ng[9]: syslog-ng starting up; version='3.5.6'
Jun  7 20:46:54 ef060b804a7a syslog-ng[9]: WARNING: you are using the pipe driver, underlying file is not a FIFO, it should be used by file(); filename='/dev/stdout'
*** Running /etc/rc.local...
Jun  7 20:46:55 ef060b804a7a syslog-ng[9]: EOF on control channel, closing connection;
*** Booting runit daemon...
*** Runit started as PID 15
Jun  7 20:46:55 ef060b804a7a cron[21]: (CRON) INFO (pidfile fd = 3)
Jun  7 20:46:55 ef060b804a7a cron[21]: (CRON) INFO (Running @reboot jobs)
A server is already running. Check /root/.config/oxidized/pid
Jun  7 20:46:56 ef060b804a7a oxidized[28]: Oxidized starting, running as pid 28
Jun  7 20:46:56 ef060b804a7a oxidized[28]: lib/oxidized/nodes.rb: Loading nodes
Jun  7 20:46:57 ef060b804a7a oxidized[28]: lib/oxidized/nodes.rb: Loaded 1 nodes
Puma starting in single mode...
* Version 3.11.4 (ruby 2.3.1-p112), codename: Love Song
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://0.0.0.0:8888
Use Ctrl-C to stop
Jun  7 20:46:57 ef060b804a7a oxidized[28]: 192.168.67.1 raised Net::SSH::AuthenticationFailed with msg "Authentication failed for user @192.168.67.1"
Jun  7 20:47:17 ef060b804a7a oxidized[28]: 192.168.67.1 raised Oxidized::PromptUndetect with msg "unable to detect prompt: (?-mix:\[\w+@\S+(\s?\S+)*\]\s?>\s?$)"
Jun  7 20:47:18 ef060b804a7a oxidized[28]: b status no_connection, retry attempt 1
Jun  7 20:47:18 ef060b804a7a oxidized[28]: 192.168.67.1 raised Net::SSH::AuthenticationFailed with msg "Authentication failed for user @192.168.67.1"
Jun  7 20:47:38 ef060b804a7a oxidized[28]: 192.168.67.1 raised Oxidized::PromptUndetect with msg "unable to detect prompt: (?-mix:\[\w+@\S+(\s?\S+)*\]\s?>\s?$)"
Jun  7 20:47:39 ef060b804a7a oxidized[28]: b status no_connection, retry attempt 2
Jun  7 20:47:39 ef060b804a7a oxidized[28]: 192.168.67.1 raised Net::SSH::AuthenticationFailed with msg "Authentication failed for user @192.168.67.1"
```
As in web interface I can see that at least it defined my only host to the correct group:
```
{:name=>"b",
 :full_name=>"mt/b",
 :ip=>"192.168.67.1",
 :group=>"mt",
 :model=>"RouterOS",
 :last=>nil,
 :vars=>{:ssh_port=>"50222"}}
```
But it didn't use username neither password from config:
```
groups:
  mt:
    username: configer
    password: some_password
    ssh_port: 50222
```

**Comment by ytti** [comment]
Can you look at logs, there should be quite bit of debugging information regarding resolving those keys:

https://github.com/ytti/oxidized/blob/master/lib/oxidized/node.rb#L200-L234

**Comment by bydunai** [comment]
I'm looking into logs, but I don't see any clue why oxidized doesn't use info provided in groups to log into devices.

**Comment by bydunai** [comment]
It does the job if I redisign csv scheme, moving all "variables" to the end.
Like this.
```
---
username: test
password: test
model: junos
resolve_dns: false
interval: 3600
use_syslog: true
debug: true
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 0.0.0.0:8888
next_adds_job: false
vars: {}
groups:
  mt:
    username: configer
    password: some_password
    ssh_port: 50222
  cisco:
    username: dindon
    password: some_password
  lab:
    username: configer
    password: some_password
models: {}
//  routeros:
//    username: configer
//    password: whats_in_there+
//    input: ssh
pid: "/root/.config/oxidized/pid"
input:
  default: ssh, telnet
  debug: false
  ssh:
    secure: false
  ftp:
    passive: true
  utf8_encoded: true
output:
  default: git
  git:
    user: oxidized
    email: oxidized@b.bydunai.net
    repo: "/root/.config/oxidized/configs.git"
source:
  default: csv
  csv:
    file: "/root/.config/oxidized/router.db"
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      group: 1      
      model: 2
      ip: 3
      username: 5
      password: 6
    vars_map:
      ssh_port: 4
    gpg: false
model_map:
  cisco: ios
  juniper: junos
```
```
b:mt:routeros:192.168.67.1:50222
cap:mt:routeros:192.168.67.4:22
vmx:lab:junos:172.172.100.0:22
```
I.e., it seems oxidized treats "empty" field `::` as a value. So to expell it from using it must be at the end of csv scheme and surrounding `::` must be removed.
I feel confused as I saw many examples over the web which stated that `::` is a normal thing in the middle of csv line.

**Comment by ytti** [comment]
Oh right, we've changed that. Because sometimes users have enable password but it's empty string! So we need to able to express empty string.

Here is the interpolation: https://github.com/ytti/oxidized/blob/master/lib/oxidized/source/source.rb#L13-L19

So you want 'nil' or 'false', and it'll change from empty string into nil or false.

But this should be in log, whole this chain of resolution is there, and it should say it took "" from node level, overwriting the group level.

**Comment by ytti** [comment]
I wish you'd look more into the logging issue, as it SHOULD work, and I've seen bug reports where they are added, it would have cleared up the situation to you immediately.

**Comment by bydunai** [comment]
Maybe I don't fully understand you.
Where should I see that logging which explains oxidized' behaviour?

**Comment by ytti** [comment]
If you have debugging enabled, as you have, it should be where ever you store log. In your case it seems like you're not using log file but syslogger, so it's where ever you've configured your syslogger to store them.

**Comment by bydunai** [comment]
I have debugging enabled.
All those messages I've show are also inside docker, /var/log/syslog.
There are no more details however.

**Comment by ytti** [comment]
You have ```use_syslog: true``` it means to use syslog, not to write file:
https://github.com/ytti/oxidized/blob/master/lib/oxidized.rb#L40-L50

**Comment by bydunai** [comment]
Got it.
Turned on custom log and now I see all the decisons oxidized makes.
Thank you a lot!
