### ISSUE TITLE
whitespace in nodes list

### ISSUE THREAD

**Issue by PeepOks** [ytti/oxidized#1373]
If there is whitespace in end of device or group name("some.device " or "routers ") then it should be striped.
If whitespace happnes to be end of name and when adding configuration to git then folder names also contain whitespace in end of name.

I didn't notice this until I saw two folders with seemingly same name.

**Comment by PeepOks** [comment]
Sometimes it could happen that unseen whitespace slips into source nodes list. These are really hard to notice. If I would find/notice these whitespaces in source nodes list file then I would remove them. I find that it would be best if oxidized would remove these little user mistakes before they cause some mess to the system. Same goes for so-called "special chars" what could also cause some problems.
I can't imagine any real-world scenario where whitespace is needed in start or end of string/word and I think it's pretty common that stings are stripped before they are used somewhere.

I use csv as input.
```
source:
  default: csv
  debug: false
  csv:
    file: "~/.config/oxidized/router.db"
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
      group: 2
      username: 3
      password: 4
    vars_map:
      enable: 5
```
router.db file
```
#Source of device configs
#name/IP:model:group[:username:password]
some.switch.local:cisco:switches 
some2.switch.local:cisco:switches:admin:admin
```

**Comment by ytti** [comment]
It's easy to make editor complain about trailing white spaces and remove them on save, something programmers often do. What you're proposing is moving the opinion from editor to compiler, I'm not sure if this is good idea.
For username and at least password it's obvious someone might want trailing white space. I agree it seems to me people shouldn't want it for names. But I still think it's better to be unopinionated here.
 
vim: ```autocmd BufWritePre *.db :%s/\s\+$//e```
vsc: ```files.trimTrailingWhitespace": true```

**Comment by PeepOks** [comment]
We can close this issue. I will use some other methods to clean nodes list from unwanted symbols.
