### ISSUE TITLE
Complete configuration file not backed up

### ISSUE THREAD

**Issue by jdenoy** [ytti/oxidized#1377]
Hello,

seems that for some reasons, I cannot get complete configuration file backed up.

When debug enabled, I see the complete configuration file in the logs directory, and when choosing either file or git output, I get only a partial backup.

Here's the ouput of the # of lines in the backup file : 
```
root@d5645d2eb9a7:~/.config/oxidized/configs# cat 192.168.100.254 | wc -l
3931
```
Here's the ouput of the # of lines in the debug file : 
```
root@d5645d2eb9a7:~/.config/oxidized/configs# cat ../logs/192.168.100.254-ssh |wc -l
89964
```
Here is the end of the backup that show partial backup (redacted to remove private informations):
```
root@d5645d2eb9a7:~/.config/oxidized/configs# tail -n 25 192.168.100.254 
--         </member>
--         <member>
--           <type>1</type>
--           <host-ip-addr>**<redacted>**</host-ip-addr>
--         </member>
--       </addr-group-member>
--     </address-group>
--     <address-group>
--       <name>**<redacted>**</name>
--       <description/>
--       <property>16</property>
--       <addr-group-member>
--         <member>
--           <type>3</type>
--           <start-ip-addr>**<redacted>**</start-ip-addr>
--           <end-ip-addr>**<redacted>**</end-ip-addr>
--         </member>
--       </addr-group-member>
--     </address-group>
--     <address-group>
--       <name>**<redacted>**</name>
--       <description/>
--       <property>16</property>
--       <addr-group-member>
--         <member>
root@d5645d2eb9a7:~/.config/oxidized/configs# 

```

Here is the end of the debug of the backup that show that the prompt detection works fine (redacted to remove private informations) :

```
root@d5645d2eb9a7:~/.config/oxidized/configs# tail -n25 ../logs/192.168.100.254-ssh
      <comment>Generated by Policy Manager</comment>
    </revision>
  </revision-history>
  <policy-routing-list/>
  <load-balance-list/>
  <policy-filter-list/>
  <hotspot-list/>
</profile>

WG<master>#show sysinfo
--
-- System Information
--
system name         : Membre_2
system model        : M300
contact             : <redacted>
location            : <redacted>
system time         : 10:58:16CEST 06/11/2018
up time             : 454 days 21 hours 57 minutes 53 seconds
serial number       : <redacted>
version             : 11.11.4.B513167
cpu utilization     : 9%(1 min)  10%(5 min)  9%(15 min)
memory usage        : 3945020 kB(total)  303180 kB(free)  3641840 kB(used)
time zone           : GMT+1:00 Amsterdam; Copenhagen; Madrid; Paris; Vilnius
WG<master>#exit
```

The model used to backup the configuration is firewareos.

**Comment by laf** [comment]
Could be the device timing out or prompt is being found in the config possibly?

**Comment by jdenoy** [comment]
No it is not because when you activate the "log" function you get the complete configuration file in it.
It is just not save correctly either in a file repo or a git repo.

**Comment by ytti** [comment]
This is certainly problem with prompt detection. Either wrong prompt or we're outputting prompt and not consuming.
Common reason is ```send "enable\n"``` which prints prompt, but which is left unconsumed.

In such case, we can fix model so that send is replace by cmd which expects to see enable prompt and we can set enable password to ```false``` so that enable is not send at all.

Generally using ```send``` in models is always sketchy, they should never cause output to generate prompt, if they do, prompt desync occurs are it's all race condition where is beginning and end of command.

**Comment by jdenoy** [comment]
Fixed with update of code
