### ISSUE TITLE
Import from Zabbix via API

### ISSUE THREAD

**Issue by Misairu** [ytti/oxidized#1378]
Trying to import list of hosts from Zabbix with API.
Script returns those json code:
```
{
	"jsonrpc":"2.0",
	"result": [
		{
		"hostid":"12041",
		"host":"sw_dlink",
		"inventory": 
			{
				"hostid":"12041",
				"model":"dlink",
				"tag":"admin",
				"asset_tag":"secretpassword",
				"notes":"enable"
			},
		"interfaces":[
			{
				"ip":"10.10.10.10"
			}]
		}
	],
	"id":1
}
```
"Source" part of oxidized config looks like this:
```
source:
  default: http
  debug: true
  http:
    url: http://127.0.0.1/zabbix-host-get-api.php
    scheme: http
    delimiter: !ruby/regexp /:/
    map:
      name: host
      model: inventory.model
      ip: interfaces.ip
      username: inventory.tag
      password: inventory.asset_tag
    vars_map:
      enable: inventory.notes
```
But it crushes with message
`no implicit conversion of String into Integer [TypeError]`

Tried to map all variables with adding prefix "result." but getted same error.
Need your help

**Comment by ytti** [comment]
Your interfaces is an array, we don't have array navigation support. So what it is complaining is you're trying to navigate array interfaces with key 'ip'.

**Comment by Misairu** [comment]
It's not a complaint, just a feedback and an ask. Cause I have a problem and " you're my only hope".
Is it possible to make this supportnes of array navigation? Both services has API and I really do not want come to the Dark side and use database connection.

**Comment by ytti** [comment]
Try this branch https://github.com/ytti/oxidized/tree/feature-string_navigation

**Comment by ytti** [comment]
If you can't test, or it doesn't work, can you open sanitised API access for me. I'd come from 91.198.120.1.

**Comment by ytti** [comment]
I suspect I need to further need to add ```http.device_root``` navigation key, to describe where the device array exists in the JSON.

**Comment by ytti** [comment]
You probably should do something like

```
http:
  hosts_location: result
  map:
    ip: interfaces[0].ip
```

**Comment by Misairu** [comment]
Thank you a lot for your support 
**feature-string_navigation** works great with importing.
But now prompt detection failed.
```
I, [2018-06-13T15:44:31.867347 #21350]  INFO -- : Oxidized starting, running as pid 21350
I, [2018-06-13T15:44:31.891462 #21350]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
I, [2018-06-13T15:44:31.927619 #21350]  INFO -- : lib/oxidized/nodes.rb: Loaded 1 nodes
W, [2018-06-13T15:44:52.420001 #21350]  WARN -- : 10.10.10.10 raised Oxidized::PromptUndetect with msg "unable to detect prompt: (?-mix:^(\r*[\w.@():-]+[#>]\s?)$)"
W, [2018-06-13T15:44:53.326084 #21350]  WARN -- : sw_dlink status no_connection, retry attempt 1
```
I cheked master branch, gem install - all 0.23 versions are same working.
Then notised  #1385 and tried fix-1385_telnet branch and has no succes. Same result.
Copy of version 0.22 installed few days ago  - still work fine with this.

So I installed feature-string_navigation branch and overwrite lib/oxidized/input/telnet.rb file. Then all working great.

**Comment by ytti** [comment]
Thanks, I'll merge the feature-string_navigation and continue to work on the telnet issue on #1385

**Comment by laf** [comment]
Tested this against LibreNMS api to make sure no regression, seems to work ok still.

Also tested against the provided json output with this config:

```yaml
  http:
    url: https://url/something.json
    hosts_location: result
    scheme: https
    delimiter: !ruby/regexp /:/
    map:
      name: host
      model: inventory.model
      username: inventory.tag
      password: inventory.asset_tag
      ip: interfaces[0].ip
```

Again, works fine.
