### ISSUE TITLE
SSH auth methods in (Arista, F5) in Oxidized-0.22

### ISSUE THREAD

**Issue by amaizenshtein** [ytti/oxidized#1379]
Hi Guys,

After deploying Oxidized-0.22, I'm unable anymore to backup Arista devices , please advise if anyone is facing the same issue

**Comment by amaizenshtein** [comment]
Guys, I fixed it, there was an issue with ssh.rb file, whoever writes the code, needs to add keyboard-interactive
in the auth methods, and it will fix the issue

**Comment by PeepOks** [comment]
I have same problem with F5(tmos) devices with latest oxidized build.

**Comment by wk** [comment]
The authentication methods passed to the SSH library have been made configurable in 0.22.0. Unfortunately it appears this change was  omitted from the changelog.

@amaizenshtein the [EOS](https://github.com/ytti/oxidized/blob/master/docs/Model-Notes/EOS.md) model notes mention this SSH configuration, as well as how to modify EOS to no longer require keyboard-interactive.

@amaizenshtein, @PeepOks, if you do need keyboard-interactive, there is absolutely no need to modify the code. See [Configuration](https://github.com/ytti/oxidized/blob/master/docs/Configuration.md) under SSH Authentication Methods.

**Comment by wk** [comment]
@ytti this calls for a retroactive changelog update to avoid users mistaking this for a regression

**Comment by PeepOks** [comment]
I did try add authentication method under config but it made all ssh connections crash.
```ERROR -- : 10.143.64.13 raised NoMethodError with msg "undefined method `each' for "none, publickey, password, keyboard-interactive":String", /root/.config/oxidized/crash.10.143.64.13 saved```

config file part:
```
vars:
  remove_secret: true
  auth_methods: none, publickey, password, keyboard-interactive
groups: {}
```

**Comment by wk** [comment]
This should probably be an array of strings in the configuration, ["none", "publickey", "password"]

**Comment by ytti** [comment]
@wk ok with changelog change, seems reasonable, but ultimately it won't be read either (not a dig, unreasonable expectation) so we just have to recognise the issues and instruct users.

**Comment by wk** [comment]
Once @PeepOks confirms that passing an array works as expected, I'll bundle this into a documentation update.

**Comment by PeepOks** [comment]
following fixed problem:
```
vars:
  auth_methods: ["none", "publickey", "password", "keyboard-interactive"]
```

**Comment by wk** [comment]
@PeepOks thanks for the verification, that is a documentation bug.
