### ISSUE TITLE
Oxidized Cache ?

### ISSUE THREAD

**Issue by darkounet** [ytti/oxidized#138]
Hi,

Do you have any kind of cache for router.db ?

I have a router.db with 150 switchs ( works fine ) but when I added more than 1000 switch they don't appear in the web GUI.

When I try in a new VM with a new install of Oxidized, it works fine.

So I want to know if you have a way to clear the cache or were to find it 

Thank you

**Comment by ytti** [comment]
You need to issue reload, the web page should have reload button, but you can do it with curl/fetch/wget too.

**Comment by darkounet** [comment]
hmmm. 

It doesn't work 

```Showing 1 to 50 of 148 entries```


```cat /srv/oxidized/router.db | wc -l > 1293 ```

Also tried to kill oxidized process & restart.

**Comment by ytti** [comment]
There is no cache right now, only runtime. 

Are you sure  your configuration file is reading that specific location? Anything interesting in syslogs?

**Comment by darkounet** [comment]
Yes, 
Oxidized is looking for the good file 

```
mv router.db router.db.1
oxidized -d
No such file or directory @ rb_sysopen - /srv/oxidized/router.db
/var/lib/gems/2.1.0/gems/oxidized-0.7.2/lib/oxidized/source/csv.rb:21:in `initialize': No such file or directory @ rb_sysopen - /srv/oxidized/router.db (Errno::ENOENT)
...


mv router.db.1 router.db

oxidized -d
Puma 2.11.3 starting...
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://0.0.0.0:8888

and always have 148 entries

```

**Comment by darkounet** [comment]
here is my config
```
---
username: xxxx
password: xxxx
interval: 43200
model: comware
log: "/var/log/oxidized/logs"
debug: true
threads: 30
timeout: 20
retries: 3
rest: 0.0.0.0:8888
vars: {}
groups: {}
input:
  default: ssh, telnet
  debug: /tmp/debug_input 
  ssh:
    secure: false
output:
  default: git
  git:
      user: Oxidized
      email: oxidized@local.net
      repo: "/srv/oxidized/git/"
source:
  default: csv
  csv:
    file: "/srv/oxidized/router.db"
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      username: 1
      password: 2
      group: 3
    vars_map:
      enable: 4
model_map:
  cisco: ios
  juniper: junos
  hp: comware
```

**Comment by ytti** [comment]
And exactly same router.db on fresh VPC works? Peculiar, there are not state outside runtime.

**Comment by darkounet** [comment]
Yes, both deploy via scp

**Comment by ytti** [comment]
So what is different in the fresh where identical config works and the one where it does not work? Because there is no state, so that makes me confused. 
Is it the first 148 that get in, always? If you remove last of them, does the next one up in the list get its place and end up being gathered?

**Comment by darkounet** [comment]
hmmm. I've find my mistake.

my router.db doesn't include IP field, and if the name isn't find in the /etc/hosts file, it doesn't appear in oxidized.

So I have fix this by adding all my switch in the hosts file and added the IP field in router.db.

Now it's OK.

sorry for inconvenience

**Comment by ytti** [comment]
No worries, happy that you were able to solve it!
