### ISSUE TITLE
Recent change to telnet.rb causes logins not to be detected

### ISSUE THREAD

**Issue by hunnymonster** [ytti/oxidized#1385]
Hi all

The [recent change](https://github.com/ytti/oxidized/commit/194b6893bde341c4fc3ba4c8041d9a6b6775a97d#diff-c42fecf428133cca9b1884c510475dd0) to  /lib/oxidized/input/telnet.rb has caused all of my telnet only devices (currently a sizable but reducing list) to fail to login...

Each one shows that the telnet transport is working (log file shows the banner etc) but times out... reverting to the previous telnet.rb resolves the issue.

None of them is presenting anything unusual as the login prompt - all are "Username:"

**Comment by ytti** [comment]
Can you try this
https://github.com/ytti/oxidized/tree/fix-1385_telnet

**Comment by ytti** [comment]
Actually no need to test that, it won't work.

The new code also relies on #expect accepting array of expects, that needs to be addressed too.

**Comment by hunnymonster** [comment]
I shall await further instructions :)

**Comment by ytti** [comment]
ok now the telnet.rb has been changed, 100% untested :(

**Comment by ytti** [comment]
I had bunch of NBSP characters, so if anyone tried, it was certainly broken. Might be still broken, but not sure anymore how.

**Comment by hunnymonster** [comment]
Certainly appears to work on a sample size of 1...

**Comment by ytti** [comment]
I added one more commit to the branch, it should be no-op, so if it already did work, it still should work. But yeah SHOULD is hardly a guarantee.

**Comment by hunnymonster** [comment]
Confirming that it still works with the latest update.

**Comment by ytti** [comment]
Hmm. I'm not actually sure why it would work :). I don't think the code is sending new line after user and password. Are you sure you're testing the right code?

**Comment by hunnymonster** [comment]
Pretty sure I am - dug in to the commits and the one I took was 8 minutes old when I took it (just before my last reply)

**Comment by ytti** [comment]
i don't get why it works, strange. Let me add the new line and see if it breaks it :>

**Comment by ytti** [comment]
there is now one more commit in the branch, if you don't mind testing that as well.

Any chance you're actually running different oxidized via rvm or something?

**Comment by ytti** [comment]
@Misairu does this work for you?

**Comment by hunnymonster** [comment]
My oxidized is running on bare metal Ubuntu, Ruby 2.5.1p37... I'll not be able to test until the morning now though.

**Comment by Misairu** [comment]
Just checked master branch. Prompt detection do not working.

**Comment by ytti** [comment]
it's not in master it's in https://github.com/ytti/oxidized/tree/fix-1385_telnet

**Comment by Misairu** [comment]
Same result

**Comment by ytti** [comment]
Heh, strange, seems to work for @hunnymonster 

Can someone provide me any sanitised telnet host reachable from 91.198.120.1

**Comment by Misairu** [comment]
I will check it tomorrow

**Comment by ytti** [comment]
unless of course the new line broke it, but i can't figure out how it could work without the new line :>

**Comment by hunnymonster** [comment]
In around 10 hours, I shall be back at my desk and able to test. When I do so, I shall confirm which git submit I'm testing...

**Comment by ytti** [comment]
@Misairu and for you it does not work, but 0.22.0 does work?

Remember you cannot just take 0.22.0 and telnet.rb, you also have to take cli.rb, better to just take the branch to avoid knowing what to take and what not to.

**Comment by hunnymonster** [comment]
My gem list (at least the oxidized ones)

```
root@####:~# gem list | grep oxidized
oxidized (0.23.0)
oxidized-script (0.5.1)
oxidized-web (0.11.1)
root@####:~#
```

**Comment by Misairu** [comment]
Just checked current fix-1385 telnet branch
Prompt detection works
```
                       DES-3200-26 Fast Ethernet Switch
                            Command Line Interface

                           Firmware: Build 4.00.024
           Copyright(C) 2012 D-Link Corporation. All rights reserved.
UserName:admin
PassWord:*********

Director:admin#
```
But after warned about connection
```
I, [2018-06-14T14:43:09.376971 #12399]  INFO -- : Oxidized starting, running as pid 12399
I, [2018-06-14T14:43:09.377586 #12399]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
I, [2018-06-14T14:43:09.388794 #12399]  INFO -- : lib/oxidized/nodes.rb: Loaded 1 nodes
W, [2018-06-14T14:43:10.651265 #12399]  WARN -- : sw_dlink status no_connection, retry attempt 1
W, [2018-06-14T14:43:11.651992 #12399]  WARN -- : sw_dlink status no_connection, retry attempt 2
W, [2018-06-14T14:43:12.652300 #12399]  WARN -- : sw_dlink status no_connection, retry attempt 3
W, [2018-06-14T14:43:13.652633 #12399]  WARN -- : sw_dlink status no_connection, retries exhausted, giving up
```

**Comment by ytti** [comment]
@Misairu I'm not sure what are you telling.

Are you telling me it can login to the device, but you won't get config out? It just stays at the prompt?

Which model is this? dlink.rb appears to expect lowercase username and password. Does this model work with 0.22.0?

**Comment by Misairu** [comment]
@ytti I tested clear branch **fix-1385 telnet**  with minimal modifications:

- source csv (cause zabbix json with arrays not supported on this branch)
- D-Link DES-3200-26 switch with dlink model. I modified dlink.rb lines 29-30 (username => UserName and password => PassWord). Already submited this issue #1389

Result:
 Yes, its stays at the prompt after successful auth.

**Comment by ytti** [comment]
Can you give me access to a sanitised device? I'd come from 91.198.120.1.

My best guess is that prompt detection doesn't work.

**Comment by ytti** [comment]
https://github.com/ytti/oxidized/blob/master/lib/oxidized/model/dlink.rb#L29-L30

Is this verbatim what you have? As that's obviously wrong.

**Comment by Misairu** [comment]
@ytti For current testing I use this code
```
  cfg :telnet do
    username /\r*UserName:/
    password /\r*PassWord:/
  end
```
If code in master branch is not correct, please update it. I'm really newbie in Ruby. Using this one with old branch **feature-string_navigation** + telnet.rb from gem 0.22 and it's working fine.

P.S. About telnet access - give me few minutes

**Comment by ytti** [comment]
It's more regexp problem than ruby problem as it's {] instead of []. But I'll fix that, after we get this telnet thing sorted.

**Comment by wk** [comment]
The `dlink.rb` typo is mine, apologies. Corrected in #1396

**Comment by Misairu** [comment]
@ytti Is it any way to send you access data privately
I'm afraid to show my external ip address in order to avoid DDoS attacks

**Comment by ytti** [comment]
email to saku@ytti.fi will work

**Comment by ytti** [comment]
Thanks @Misairu this should be now fixed, after you confirm, I'll merge the branch to master

**Comment by Misairu** [comment]
Thank you for your support.
May I disconnect lab?

**Comment by ytti** [comment]
yeah you can disconnect it, many thanks for setting it up

**Comment by cppmonkey** [comment]
Hi,

Sorry to reopen this, but I'm finding our Netgear M5300's aren't responding... well they are but the logs just show a password prompt.

I suspect I need to add the password line mentioned in https://github.com/ytti/oxidized/pull/1396/files

I'll give that a go and likely submit a pull request if things start working.
Our Xyzel XGS4600-32F's are happy, but they already has the password line within xyzelcli

**Comment by pedrosiqr** [comment]
Hi guys,

my telnet doesn't work to get backup from mikrotik device. On debug i see that:

`MikroTik v6.43.8 (stable)
Login: admin
Password:








^M  MMM      MMM       KKK                          TTTTTTTTTTT      KKK
^M  MMMM    MMMM       KKK                          TTTTTTTTTTT      KKK
^M  MMM MMMM MMM  III  KKK  KKK  RRRRRR     OOOOOO      TTT     III  KKK  KKK
^M  MMM  MM  MMM  III  KKKKK     RRR  RRR  OOO  OOO     TTT     III  KKKKK
^M  MMM      MMM  III  KKK KKK   RRRRRR    OOO  OOO     TTT     III  KKK KKK
^M  MMM      MMM  III  KKK  KKK  RRR  RRR   OOOOOO      TTT     III  KKK  KKK

^M  MikroTik RouterOS 6.43.8 (c) 1999-2018       http://www.mikrotik.com/

[?]             Gives the list of available commands
^Mcommand [?]     Gives help on the command and list of arguments

^M[Tab]           Completes the command/word. If the input is ambiguous,
^M                a second [Tab] gives possible options

^M/               Move up to base level
^M..              Move up one level
^M/command        Use command at the base level
^M^[[9999B^M^[[9999B^[Z  ^[[6n^M^M^M^M[admin@Pedro - ENG] >                                                          ^M[admin@Pedro - ENG] >`

My versions
Ubuntu 17.10 (server)
oxidized (0.25.1)
oxidized-script (0.6.0)
oxidized-web (0.12.1)

ruby 2.3.3p222 (2016-11-21) [x86_64-linux-gnu]

Anyone can help me?
