### ISSUE TITLE
High CPU utilization after gem update to 0.23

### ISSUE THREAD

**Issue by dalamanster** [ytti/oxidized#1393]
Hello, 

after upgrading to 0.23 from 0.22 I am observing high CPU utilization. This is cause by oxidized service.
TOP:
  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND                                                                                                                   
  481 oxidized  20   0  870200  65836   7072 S 99.9  6.5 867:11.89 oxidized   

```
[panenkar@custconfig ~]$ cat /etc/centos-release
CentOS Linux release 7.5.1804 (Core) 

[panenkar@custconfig ~]$ uname -a
Linux custconfig 3.10.0-862.3.2.el7.x86_64 #1 SMP Mon May 21 23:36:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

Restarting the service or whole server doesn't help. I check /var/log/messages but no interesting logs are there.
Is anyone of you have the same issue? Or any hints? Thank you

My oxidized config:
```
username: cisco
password: cisco
model: cisco
interval: 86400
use_syslog: true
log: /home/oxidized/.config/oxidized/logs/
debug: false
threads: 20
timeout: 60
retries: 2
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 127.0.0.1:8888
next_adds_job: true
pid: /home/oxidized/.config/oxidized/pid
vars:
  remove_secret: false
input:
  default: ssh,telnet
  debug: false
  ssh:
    secure: false
output:
  default: git
  git:
    user: oxidized
    email: custconfig@example.com
    repo: "/home/oxidized/oxidized/git"
source:
  default: csv
  csv:
    file: /home/oxidized/.config/oxidized/router.db
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
      group: 2
      username: 3
      password: 4
    vars_map:
      enable: 5
    gpg: false
groups:
 [output omitted - just passwords and usernames here for the groups]
model_map:
  cisco: ios
  cisco-custom: ioscustom
  cisco-catos: catos
  cisco-asa: asa
  cisco-wlc: aireos
  cisco-mds: nxos
  cisco-nexus: nxos
  fortigate: fortios
  f5: tmos
  juniper: junos
  mikrotik: routeros
  ubiquiti: airos
hooks:
 [output omitted - deleting the hooks didnt help]

```

**Comment by ytti** [comment]
If you disable rest/web, does the problem persist? Not suggesting you do that persistently, just trying to narrow the problem scope down.

**Comment by wk** [comment]
The output of `strace -f -p <PID>` may also help understand what the process is actually busy with.

**Comment by dalamanster** [comment]
I disabled rest by deleting "rest: 127.0.0.1:8888" in config and reloading service / server. Is this what you meant ? However, it didn't help.

**Comment by ytti** [comment]
You still have puma running, it shouldn't be running if you don't have rest.

**Comment by dalamanster** [comment]
Ok removing the "rest" line from the config didn't do anything. After changing 
rest: 127.0.0.1:8888  to rest: false
the CPU is now in normal values. 

However we need the Web interface.

**Comment by wk** [comment]
Could you run `gem list` and append the output to this ticket?

**Comment by dalamanster** [comment]
The situation changed. After next 15 minutes, the CPU load rised again to >90% 

```
  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND                                
 6116 oxidized  20   0  766640  65148   5608 S 99.9  6.4  12:59.85 oxidized 

[oxidized@custconfig ~]$  ps -eo pcpu,pid,user,args | sort -k 1 -r | head -10
%CPU   PID USER     COMMAND
52.9  6116 oxidized /usr/bin/ruby /usr/local/bin/oxidized
```

this is gem list

`[oxidized@custconfig ~]$ gem list

*** LOCAL GEMS ***

asetus (0.3.0)
backports (3.8.0)
bigdecimal (1.2.0)
charlock_holmes (0.7.6)
emk-sinatra-url-for (0.2.1)
ffi (1.9.18)
haml (5.0.4, 4.0.7)
htmlentities (4.3.4)
io-console (0.4.2)
json (1.7.7)
multi_json (1.12.1)
net-ssh (4.1.0, 3.0.2)
net-telnet (0.1.1)
oxidized (0.23.0, 0.22.0, 0.21.0, 0.20.0)
oxidized-script (0.5.1, 0.5.0, 0.4.0)
oxidized-web (0.11.1, 0.10.2, 0.9.3, 0.9.2)
psych (2.0.0)
puma (3.9.1)
rack (1.6.8)
rack-protection (1.5.3)
rack-test (0.7.0)
rb-fsevent (0.10.2)
rb-inotify (0.9.10)
rdoc (4.0.0)
rugged (0.26.0)
sass (3.4.25)
sass-listen (4.0.0)
sinatra (1.4.8)
sinatra-contrib (1.4.7)
slop (3.6.0)
temple (0.8.0)
tilt (2.0.7)`

**Comment by wk** [comment]
Thanks for the feedback. It might be helpful to:

* Upgrade oxidized to the just released 0.24.0 version
* Uninstall older versions of oxidized gems and libraries using `gem uninstall --version <version>`
* Restart the oxidized process

If this does not resolve the issue, it would be helpful to understand what exactly is oxidized busy doing on your system. Please see the instructions for enabling debugging and attach a debug log from a period of time before and after the CPU spinning is observed to this issue (right after a restart, and after CPU ramps up).

**Comment by ytti** [comment]
Which oxidized-web version? We recently fixed bug which made browsing node list expensive.

**Comment by dalamanster** [comment]
I upgraded to the latest version 0.24.0 and deleted old gems. Now the processor load is low. 

However, I probably found the root cause elsewhere. 
I performed updates of oxidized just by issuing "gem update oxidized"
Other gems were not updated... I think this was the problem. probably old version of PUMA (3.91) with new oxidized (?) 

This is current list:

```
[root@custconfig panenkar]# gem list

*** LOCAL GEMS ***

asetus (0.3.0)
backports (3.11.3, 3.8.0)
bigdecimal (1.3.5, 1.2.0)
charlock_holmes (0.7.6)
emk-sinatra-url-for (0.2.1)
ffi (1.9.25, 1.9.18)
haml (5.0.4, 4.0.7)
htmlentities (4.3.4)
io-console (0.4.6, 0.4.2)
json (2.1.0, 1.7.7)
multi_json (1.13.1, 1.12.1)
net-ssh (4.1.0, 3.0.2)
net-telnet (0.1.1)
oxidized (0.24.0)
oxidized-script (0.5.1)
oxidized-web (0.11.1)
psych (2.0.0)
puma (3.11.4, 3.9.1)
rack (1.6.8)
rack-protection (2.0.3, 1.5.3)
rack-test (0.7.0)
rb-fsevent (0.10.3, 0.10.2)
rb-inotify (0.9.10)
rdoc (4.0.0)
rugged (0.27.1, 0.26.0)
sass (3.5.6, 3.4.25)
sass-listen (4.0.0)
sinatra (1.4.8)
sinatra-contrib (1.4.7)
slop (4.6.2, 3.6.0)
temple (0.8.0)
tilt (2.0.8, 2.0.7)

[root@custconfig panenkar]#  ps -eo pcpu,pid,user,args | sort -k 1 -r | head -10
%CPU   PID USER     COMMAND
 0.7  6096 oxidized puma 3.11.4 (tcp://127.0.0.1:8888) [/]
 0.1   479 root     /usr/bin/vmtoolsd
 0.0     9 root     [rcu_sched]
 0.0   999 oxidized -bash
 0.0   998 oxidized sshd: oxidized@pts/2
 0.0   995 root     sshd: oxidized [priv]
 0.0   970 panenkar -bash
 0.0   969 panenkar sshd: panenkar@pts/1
 0.0   967 root     sshd: panenkar [priv]

```

Thank you both for quick support and great work doing here

**Comment by BroadbandCommunicationsNorth** [comment]
Hello,

I have the same issues with 100% loading CPU after upgrade, unfortunately I can't remember which version it was. It was about 2 months ago. A few days ago I decided to upgrade oxidized hoping it will fix 100% CPU issue. New version (v.0.26.3) required Ruby 2.3, I had to install Oxidized from zero. However, upgrade didn't help. 

System CentOS 7

Oxidize and Ruby were installed according to this:
https://github.com/ytti/oxidized/blob/master/README.md#centos-oracle-linux-red-hat-linux

In /usr/lib/systemd/system/oxidized.service changed ExecStart for using new Ruby
ExecStart=/usr/bin/scl enable rh-ruby23 -- /usr/local/bin/oxidized


gem list

*** LOCAL GEMS ***

asetus (0.3.0)
backports (3.13.0)
bigdecimal (1.2.8)
charlock_holmes (0.7.6)
did_you_mean (1.0.0)
emk-sinatra-url-for (0.2.1)
ffi (1.10.0)
haml (5.0.4)
htmlentities (4.3.4)
io-console (0.4.5)
json (1.8.3.1)
multi_json (1.13.1)
net-ssh (5.2.0)
net-telnet (0.1.1)
oxidized (0.26.3)
oxidized-script (0.6.0)
oxidized-web (0.13.1)
psych (2.1.0.1)
puma (3.11.4)
rack (1.6.11)
rack-protection (1.5.5)
rack-test (0.7.0)
rb-fsevent (0.10.3)
rb-inotify (0.10.0)
rdoc (4.2.1)
rugged (0.28.1)
sass (3.7.4)
sass-listen (4.0.0)
sinatra (1.4.8)
sinatra-contrib (1.4.7)
slop (3.6.0)
temple (0.8.1)

cat ./config 
---
username: USER
password: XXXXXXXXXXX
model: cisco
resolve_dns: true
interval: 3600
use_syslog: false
debug: false
threads: 30
timeout: 140
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 127.0.0.1:9888
next_adds_job: false
vars: {
   enable: XXXXXXXXXXX
   }
groups: {}
models: {}
pid: /home/oxidized/.config/oxidized/pid
log: /home/oxidized/.config/oxidized/logs/oxidized.log
stats:
  history_size: 10
input:
  default: ssh, telnet
  debug: false
  ssh:
    secure: false
  ftp:
    passive: true
  utf8_encoded: true
output:
  default: git
  file:
    directory: /home/oxidized/.config/oxidized/configs
  git:
    user: oxidized
    email: oxidized@xxxxx.xx
    repo: "/home/oxidized/oxidized/git"
source:
  default: csv
  csv:
    file: /home/oxidized/.config/oxidized/router.db
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
      ip: 2
    gpg: false
model_map:
  cisco: ios
  juniper: junos
hooks:
  name_for_example_hook1:
    type: exec
    events: [node_success]
#    cmd: 'echo "Node success $OX_NODE_NAME job status $OX_JOB_STATUS" >> /tmp/ox_node_success.log'
    cmd: 'zabbix_sender -z zabbix.server -s $OX_NODE_NAME -k BackupConfigSuccess -o $OX_JOB_STATUS;'
  name_for_example_hook2:
    type: exec
    events: [node_fail]
#    cmd: 'echo "Doing long running stuff for $OX_NODE_NAME, job status $OX_JOB_STATUS, job time $OX_JOB_TIME" >> /tmp/ox_node_stuff.log; sleep 60'
    cmd: 'zabbix_sender -z zabbix.server -s $OX_NODE_NAME -k BackupConfigFail -o $OX_JOB_STATUS; sleep 60'
#    async: true
#    timeout: 120


root@oxidized oxidized]# ps -eo pcpu,pid,user,args | sort -k 1 -r | head -10
%CPU   PID USER     COMMAND
91.4  9905 oxidized puma 3.11.4 (tcp://127.0.0.1:9888) [/]
 0.0     9 root     [rcu_sched]
 0.0  9997 oxidized sh -c zabbix_sender -z zabbix.server -s $OX_NODE_NAME -k BackupConfigFail -o $OX_JOB_STATUS; sleep 60
 0.0   992 root     [irq/16-vmwgfx]
 0.0  9902 oxidized /bin/bash /var/tmp/scl8hDdVp
 0.0  9899 oxidized /usr/bin/scl enable rh-ruby23 -- /usr/local/bin/oxidized
 0.0   982 root     [ttm_swap]
 0.0    91 root     [kauditd]
 0.0     8 root     [rcu_bh]
