### ISSUE TITLE
edgecos - remove temperature from show system

### ISSUE THREAD

**Issue by kamils85** [ytti/oxidized#1394]
Could you please remove the temperature from edgecos? It's coming from "show system".

 ! 
 ! System Temperature:
 ! Unit 1
-!  Temperature 1:  34 degrees    
+!  Temperature 1:  35 degrees    
 ! 
 ! Unit 1

**Comment by wk** [comment]
@kamils85 the change introduced in #1399 should scrub the temperature data away. Could you verify if the version in master solves the issue for you?

**Comment by kamils85** [comment]
@wk that's the temperature gone. Thanks

```
! 
! System Temperature:
! Unit 1
! Temperature 1: <removed>
! Unit 1
! 
```
