### ISSUE TITLE
Since update to 0.24.0 - Cisco configs truncated, some Procurve not polled correctly

### ISSUE THREAD

**Issue by hunnymonster** [ytti/oxidized#1401]
Since updating to Oxidized 0.24.0 the config is not retrieved correctly for a number of devices - example in code block below:

```
! 
! 
! VTP: Cisco IOS Software, C3750 Software (C3750-IPBASE-M), Version 12.2(35)SE5, RELEASE SOFTWARE (fc1)
! VTP: Copyright (c) 1986-2007 by Cisco Systems, Inc.
! VTP: Compiled Thu 19-Jul-07 19:15 by nachen
! VTP: Image text-base: 0x00003000, data-base: 0x01080000
! VTP: ROM: Bootstrap program is C3750 boot loader
! VTP: BOOTLDR: C3750 Boot Loader (C3750-HBOOT-M) Version 12.2(25r)SEE4, RELEASE SOFTWARE (fc1)
! VTP: BGHAC-SW02 uptime is 5 days, 10 hours, 39 minutes
! VTP: System returned to ROM by power-on
! VTP: System restarted at 23:02:39 BST Sat Jun 9 2018
! VTP: System image file is "flash:c3750-ipbase-mz.122-35.SE5/c3750-ipbase-mz.122-35.SE5.bin"
! VTP: cisco WS-C3750G-48PS (PowerPC405) processor (revision F0) with 118784K/12280K bytes of memory.
! VTP: Processor board ID FOC1046Z6TY
! VTP: Last reset from power-on
! VTP: 2 Virtual Ethernet interfaces
! VTP: 52 Gigabit Ethernet interfaces
! VTP: The password-recovery mechanism is enabled.
! VTP: 512K bytes of flash-simulated non-volatile configuration memory.
! VTP: Base ethernet MAC Address       : 00:1A:2F:B2:60:80
! VTP: Motherboard assembly number     : 73-10216-08
! VTP: Power supply part number        : 341-0108-03
! VTP: Motherboard serial number       : FOC104615G4
! VTP: Power supply serial number      : DCA1042A0BS
! VTP: Model revision number           : F0
! VTP: Motherboard revision number     : B0
! VTP: Model number                    : WS-C3750G-48PS-S
! VTP: System serial number            : FOC1046Z6TY
! VTP: Top Assembly Part Number        : 800-26853-01
! VTP: Top Assembly Revision Number    : A0
! VTP: Version ID                      : V05
! VTP: CLEI Code Number                : CNMWN00ARC
! VTP: Hardware Board Revision Number  : 0x09
! VTP: Switch   Ports  Model              SW Version              SW Image            
! VTP: ------   -----  -----              ----------              ----------          
! VTP: *    1   52     WS-C3750G-48PS     12.2(35)SE5             C3750-IPBASE-M      
! VTP: Configuration register is 0xF
! 
! VTP Version                     : 2
! Configuration Revision          : 83
! Maximum VLANs supported locally : 1005
! Number of existing VLANs        : 61
! VTP Operating Mode              : Client
! VTP Domain Name                 : #######
! VTP Pruning Mode                : Enabled
! VTP V2 Mode                     : Disabled
! VTP Traps Generation            : Disabled
! MD5 digest                      : 0x21 0x4F 0xA7 0x19 0xA0 0x63 0x91 0x64 
! Configuration last modified by 10.254.11.1 at 5-23-18 13:33:24
NAME: "GigabitEthernet1/0/51", DESCR: "1000BaseSX SFP"
PID:                     , VID:     , SN: AGM1447L1E2     

NAME: "GigabitEthernet1/0/52", DESCR: "1000BaseSX SFP"
PID:                     , VID:     , SN: AGM1105J38F     
```

No running config retrieved at all...

On the Procurve (predominantly 2512 & 2524) - the telnet session establishes, logs in and then does nothing to retrieve - just times out leading to failure.

**Comment by ytti** [comment]
Any chance to get sanitised system online?

**Comment by ytti** [comment]
Is the C3750 also fetched via telnet?

**Comment by ytti** [comment]
If c3750 is also telnet, it's likely the same issue in both boxes, and hopefully just one of them, which ever is easiest to put online in sanitised manner, would be sufficient.

**Comment by hunnymonster** [comment]
Possibly - need to think how to put one online... In the middle of a LAN refresh project in a healthcare setting

**Comment by ytti** [comment]
I'm surprised no more complain in a week, if it is actually broken. Still very happy to work on this, if I can get access to affected device.

**Comment by hunnymonster** [comment]
@ytti where in the world are you? Might be easier for me to physically send you the device :)

**Comment by hunnymonster** [comment]
I wonder if there's some show through from 0.23.0... if I get a chance on Monday, I'll try a clean install of all of the gems.

Big day - two stacks to replace (300+ connections) - planned downtime nil... Tis a good game...

**Comment by ytti** [comment]
@hunnymonster I'm in Cyprus, it's usually highest tier to ship things to inside EU.

I'm sorry for any trouble caused, and I'm very much willing to work on to solve the telnet issue.

**Comment by hunnymonster** [comment]
No trouble to me - like a good boy, I've got a production monitor and a test system... Would a wireshark capture of a session be any use? (Given its telnet and not encrypted at all)

Trying to think how to get you visibility at least.

**Comment by rvandepu** [comment]
Hi, I've been having this problem with multiple Cisco switches (2960 & 2950), even before the latest version. If I recall correctly, the problem was gone after disabling the retrieval of VTP information. I'll try that again.

If you need more information to troubleshoot this, please tell me what you need.

**Comment by ytti** [comment]
This is interesting, and might give us reason what is going on. If VTP output has some string which matches to prompt, we become desynchronised, VTP output stops there, and the next command output stops even before it starts, because we see the VTP's actual prompt and so forth.

**Comment by hunnymonster** [comment]
I have run up an entirely new instance of oxidized 0.24.0 and my Cisco issue has cleared. The Procurve one persists but only on HP Procurve 2524 (coincidentally, they're the only devices I have using local logins)

**Comment by jerebernard** [comment]
I'm have the same issue for new HP Procurve model ex : 2920-24G.
For the moment I didn't find any  solution

**Comment by martinohansen** [comment]
We're also affected on HPE 2530 / J9772A switches running version: YA.15.12.0007 & YA.15.17.0009. We have the following in our log.

```
W, [2018-10-23T12:00:41.574423 #621]  WARN -- : 192.168.0.2 raised Oxidized::PromptUndetect with msg "Your previous successful login (as operator) was from 192.168.0.1 SWITCH>  not matching configured prompt (?-mix:^\r?([\w.-]+# )$)"
W, [2018-10-23T12:00:42.472674 #621]  WARN -- : SWITCH status no_connection, retry attempt 1
W, [2018-10-23T12:01:13.695231 #621]  WARN -- : 192.168.0.2 raised Oxidized::PromptUndetect with msg "Your previous successful login (as operator) was from 192.168.0.1 SWITCH>  not matching configured prompt (?-mix:^\r?([\w.-]+# )$)"
W, [2018-10-23T12:01:14.481242 #621]  WARN -- : SWITCH status no_connection, retry attempt 2
W, [2018-10-23T12:01:45.589876 #621]  WARN -- : 192.168.0.2 raised Oxidized::PromptUndetect with msg "Your previous successful login (as operator) was from 192.168.0.1 SWITCH>  not matching configured prompt (?-mix:^\r?([\w.-]+# )$)"
W, [2018-10-23T12:01:46.490674 #621]  WARN -- : SWITCH status no_connection, retry attempt 3
W, [2018-10-23T12:02:17.647341 #621]  WARN -- : 192.168.0.2 raised Oxidized::PromptUndetect with msg "Your previous successful login (as operator) was from 192.168.0.1 SWITCH>  not matching configured prompt (?-mix:^\r?([\w.-]+# )$)"
W, [2018-10-23T12:02:18.498470 #621]  WARN -- : SWITCH status no_connection, retries exhausted, giving up
```

Let me know i you need more information. Thanks.

**Comment by mrplow87** [comment]
In oxidized 0.26.3 the issue is still present.

**Comment by martinohansen** [comment]
@mrplow87 using the `ssh.rb` from 0.21.0 does not resolve our issue, unfortunately. The command `no banner` is not available on: YA.15.12. 

We're properly just gonna update the switches, thanks for the input.

**Comment by wk** [comment]
Is this issue still active in a current version of Oxidized?

**Comment by jerebernard** [comment]
Hello, Yes still the issue on some procurve version

**Comment by DarkCatapulter** [comment]
I've also had this issue on my company procurve switches, though I solved it by changing the regex pattern. Though I'm not confident with doing a PR with my solution.

**Comment by dhapheto** [comment]
> 
> 
> I've also had this issue on my company procurve switches, they are running in older versions and we're not gonna upgrade them any time soon. I solved it by changing the regex pattern, though I'm not confident with doing a PR with my sol

**Comment by dhapheto** [comment]
> 
> 
> I've also had this issue on my company procurve switches, they are running in older versions and we're not gonna upgrade them any time soon. I solved it by changing the regex pattern, though I'm not confident with doing a PR with my solution.

Hi DarkCatapulter,

Could you please share your regex pattern ?
Thanks in advance

**Comment by gbeekmans** [comment]
Just another report that the latest version of Oxidized as of yesterday (showing as 0.28.0) is having issues with pulling config files from older devices. I'm having some issues with HP 3500yl and HP 2510 switches that run very old firmware. The 2530s with latest & greatest firmware don't have issues.

I, too, worked around the issues by copying ssh.rb from oxidized-0.21.0 into /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/input which makes SSH work again to those switches and pull configuration.

With the 0.28 version of ssh.rb, it can't SSH, period. The errors it encounters is "raised IOError with msg "closed stream" and then falls back to telnet which can't seem to deal with the various control characters that HP likes to output. Could just be an issue in the procurve.rb model. I have no Ruby experience to understand where to start fixing this.

There have been various similar reports of this problem.

**Comment by davama** [comment]
have you tried using a different reget prompt for those particular old switches?
perhaps create an altername `procurveold.rb` model with that adjusted prompt.

maybe something like this.
```
cat  ~/.config/oxidized/model/procurveold.rb 
require 'oxidized/model/procurve.rb'

class PROCURVEOLD < Procurve
  prompt /^<myregex>$/
end
```

Havent tested...so you can look around how others have created their own modules
