### ISSUE TITLE
Model by group

### ISSUE THREAD

**Issue by dracmic** [ytti/oxidized#1404]
Hello,

Is any possibility to do a model map by group? I have two types of Zyxel Switches and one is not working on ssh only on telnet.

Best regards.

**Comment by ytti** [comment]
Models are mapped at load time, we can't at this time remap them before fetch. But I'm not sure I understand what the problem is. If you set input default to ```ssh, telnet``` it'll try ssh first then telnet, and you should be fine.

**Comment by dracmic** [comment]
Hello ytti,

Actually i hvae GS1900-8 and GS1900-24, the GS1900-24 is almost as CISCO IOS and GS1900-8 is acting like a old CATOS. The GS1900-8 doesn't even login it needs some pre_login stuff.

**Comment by dracmic** [comment]
Yeah ytti, but guess what bot are seen as ZYNOS, that why I asked if it is possible model by group.

**Comment by ytti** [comment]
Well if they are different models, they should be different models. If they are entirely different UI, like you say, IOS and CatOS, they certainly are not same OS and shouldn't be same model.

So from my POV, we need to make new model and you should in your source state that it's different model.

**Comment by dracmic** [comment]
Base model is the same GS1900.

**Comment by deajan** [comment]
@dracmic Would you mind testing the following https://github.com/deajan/oxidized/blob/zynos-gs-compat/lib/oxidized/model/zynos.rb ?
Also, do you use zynos as backend for GS-1900-24 since the OS is totally different than GS-1900-8 ?
