### ISSUE TITLE
Error when searching configs from main menu :: NoMethodError at /nodes/conf_search

### ISSUE THREAD

**Issue by papatango71** [ytti/oxidized#1409]
I am receiving the following errors when trying to search from the main Oxidized menu.

Jun 18 21:18:43 cdg1-admin-inf01 oxidized[565]: 2018-06-18 21:18:43 - NoMethodError - undefined method `output' for nil:NilClass:
Jun 18 21:18:43 cdg1-admin-inf01 oxidized[565]: /usr/local/share/gems/gems/oxidized-0.24.0/lib/oxidized/nodes.rb:174:in `block in yield_node_output'
Jun 18 21:18:43 cdg1-admin-inf01 oxidized[565]: /usr/local/share/gems/gems/oxidized-0.24.0/lib/oxidized/nodes.rb:128:in `synchronize'
Jun 18 21:18:43 cdg1-admin-inf01 oxidized[565]: /usr/local/share/gems/gems/oxidized-0.24.0/lib/oxidized/nodes.rb:128:in `with_lock'
Jun 18 21:18:43 cdg1-admin-inf01 oxidized[565]: /usr/local/share/gems/gems/oxidized-0.24.0/lib/oxidized/nodes.rb:172:in `yield_node_output'
Jun 18 21:18:43 cdg1-admin-inf01 oxidized[565]: /usr/local/share/gems/gems/oxidized-0.24.0/lib/oxidized/nodes.rb:60:in `fetch'
Jun 18 21:18:43 cdg1-admin-inf01 oxidized[565]: /usr/local/share/gems/gems/oxidized-web-0.11.1/lib/oxidized/web/webapp.rb:56:in `block (2 levels) in <class:WebApp>'
Jun 18 21:18:43 cdg1-admin-inf01 oxidized[565]: /usr/local/share/gems/gems/oxidized-web-0.11.1/lib/oxidized/web/webapp.rb:54:in `map'
Jun 18 21:18:43 cdg1-admin-inf01 oxidized[565]: /usr/local/share/gems/gems/oxidized-web-0.11.1/lib/oxidized/web/webapp.rb:54:in `each'
Jun 18 21:18:43 cdg1-admin-inf01 oxidized[565]: /usr/local/share/gems/gems/oxidized-web-0.11.1/lib/oxidized/web/webapp.rb:54:in `block in <class:WebApp>'
Jun 18 21:18:43 cdg1-admin-inf01 oxidized[565]: /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `call'
Jun 18 21:18:43 cdg1-admin-inf01 oxidized[565]: /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `block in compile!'
Jun 18 21:18:43 cdg1-admin-inf01 oxidized[565]: /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `[]'
Jun 18 21:18:43 cdg1-admin-inf01 oxidized[565]: /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
Jun 18 21:18:43 cdg1-admin-inf01 oxidized[565]: /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:994:in `route_eval'
Jun 18 21:18:43 cdg1-admin-inf01 oxidized[565]: /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
Jun 18 21:18:43 cdg1-admin-inf01 oxidized[565]: /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1015:in `block in process_route'
Jun 18 21:18:43 cdg1-admin-inf01 oxidized[565]: /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `catch'
Jun 18 21:18:43 cdg1-admin-inf01 oxidized[565]: /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `process_route'
Jun 18 21:18:43 cdg1-admin-inf01 oxidized[565]: /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:973:in `block in route!'
Jun 18 21:18:43 cdg1-admin-inf01 oxidized[565]: /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `each'
Jun 18 21:18:43 cdg1-admin-inf01 oxidized[565]: /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `route!'
Jun 18 21:18:43 cdg1-admin-inf01 oxidized[565]: /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1085:in `block in dispatch!'
Jun 18 21:18:43 cdg1-admin-inf01 oxidized[565]: /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
Jun 18 21:18:43 cdg1-admin-inf01 oxidized[565]: /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
Jun 18 21:18:43 cdg1-admin-inf01 oxidized[565]: /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
Jun 18 21:18:43 cdg1-admin-inf01 oxidized[565]: /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1082:in `dispatch!'
Jun 18 21:18:43 cdg1-admin-inf01 oxidized[565]: /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `block in call!'
Jun 18 21:18:43 cdg1-admin-inf01 oxidized[565]: /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
Jun 18 21:18:43 cdg1-admin-inf01 oxidized[565]: /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
Jun 18 21:18:43 cdg1-admin-inf01 oxidized[565]: /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
Jun 18 21:18:43 cdg1-admin-inf01 oxidized[565]: /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `call!'
Jun 18 21:18:43 cdg1-admin-inf01 oxidized[565]: /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:895:in `call'
Jun 18 21:18:43 cdg1-admin-inf01 oxidized[565]: /usr/local/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
Jun 18 21:18:43 cdg1-admin-inf01 oxidized[565]: /usr/local/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
Jun 18 21:18:43 cdg1-admin-inf01 oxidized[565]: /usr/local/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
Jun 18 21:18:43 cdg1-admin-inf01 oxidized[565]: /usr/local/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
Jun 18 21:18:43 cdg1-admin-inf01 oxidized[565]: /usr/local/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
Jun 18 21:18:43 cdg1-admin-inf01 oxidized[565]: /usr/local/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
Jun 18 21:18:43 cdg1-admin-inf01 oxidized[565]: /usr/local/share/gems/gems/rack-1.6.8/lib/rack/nulllogger.rb:9:in `call'
Jun 18 21:18:43 cdg1-admin-inf01 oxidized[565]: /usr/local/share/gems/gems/rack-1.6.8/lib/rack/head.rb:13:in `call'
Jun 18 21:18:43 cdg1-admin-inf01 oxidized[565]: /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/show_exceptions.rb:25:in `call'
Jun 18 21:18:43 cdg1-admin-inf01 oxidized[565]: /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:182:in `call'
Jun 18 21:18:43 cdg1-admin-inf01 oxidized[565]: /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:2013:in `call'
Jun 18 21:18:43 cdg1-admin-inf01 oxidized[565]: /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `block in call'
Jun 18 21:18:43 cdg1-admin-inf01 oxidized[565]: /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1787:in `synchronize'
Jun 18 21:18:43 cdg1-admin-inf01 oxidized[565]: /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `call'
Jun 18 21:18:43 cdg1-admin-inf01 oxidized[565]: /usr/local/share/gems/gems/rack-1.6.8/lib/rack/urlmap.rb:66:in `block in call'
Jun 18 21:18:43 cdg1-admin-inf01 oxidized[565]: /usr/local/share/gems/gems/rack-1.6.8/lib/rack/urlmap.rb:50:in `each'
Jun 18 21:18:43 cdg1-admin-inf01 oxidized[565]: /usr/local/share/gems/gems/rack-1.6.8/lib/rack/urlmap.rb:50:in `call'
Jun 18 21:18:43 cdg1-admin-inf01 oxidized[565]: /usr/local/share/gems/gems/rack-1.6.8/lib/rack/builder.rb:153:in `call'
Jun 18 21:18:43 cdg1-admin-inf01 oxidized[565]: /usr/local/share/gems/gems/puma-3.11.4/lib/puma/configuration.rb:225:in `call'
Jun 18 21:18:43 cdg1-admin-inf01 oxidized[565]: /usr/local/share/gems/gems/puma-3.11.4/lib/puma/server.rb:632:in `handle_request'
Jun 18 21:18:43 cdg1-admin-inf01 oxidized[565]: /usr/local/share/gems/gems/puma-3.11.4/lib/puma/server.rb:446:in `process_client'
Jun 18 21:18:43 cdg1-admin-inf01 oxidized[565]: /usr/local/share/gems/gems/puma-3.11.4/lib/puma/server.rb:306:in `block in run'
Jun 18 21:18:43 cdg1-admin-inf01 oxidized[565]: /usr/local/share/gems/gems/puma-3.11.4/lib/puma/thread_pool.rb:120:in `call'
Jun 18 21:18:43 cdg1-admin-inf01 oxidized[565]: /usr/local/share/gems/gems/puma-3.11.4/lib/puma/thread_pool.rb:120:in `block in spawn_thread'

I have updated to the latest Oxidized version as well as updated all gems modules and I am still getting this error.  My config file is below:

---
username: oxidized
password: xxxxx
model: cisco
interval: 3600
use_syslog: true
log: /home/oxidized/.config/oxidized/logs/
debug: true
threads: 30
timeout: 40
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 127.0.0.1:8888
next_adds_job: false
vars: {}
groups:
  cisco_asa:
    username: oxidized
    password: xxx
    vars:
      ssh_proxy: 10.104.197.195
  cisco:
    username: oxidized
    password: xxx
    vars:
      ssh_proxy: 10.104.197.195
  iosxe:
    username: oxidized
    password: xxx
    vars:
      ssh_proxy: 10.104.197.195
  iosxr:
    username: oxidized
    password: xxx
    vars:
      ssh_proxy: 10.104.197.195
  nexus:
    username: oxidized
    password: xxx
    vars:
      ssh_proxy: 10.104.197.195
  juniper:
    username: oxidized
    password: xxx
    vars:
      ssh_proxy: 10.104.197.195
  opengear:
    username: root
    password: ssMUNsz3!
    vars:
      ssh_proxy: 10.104.197.195
  fortigate:
    username: oxidized
    password: xxx
    vars:
      ssh_proxy: 10.104.197.195
  acos:
    username: oxidized
    password: xxx
    vars:
      ssh_proxy: 10.104.197.195
  arista_eos:
    username: oxidized
    password: xxx
    vars:
      ssh_proxy: 10.104.197.195
pid: "/home/oxidized/.config/oxidized/pid"
input:
  default: ssh
  debug: true
  ssh:
    secure: false
output:
  default: git
  git:
    user: oxidized
    email: oxidized@cdg1-admin-inf01.xxx.net
    repo: "/home/oxidized/.config/oxidized"
  debug: true
source:
        default: http
        debug: true
        http:
          url: https://librenms.cdg1.network.cloud.xxx.net/api/v0/oxidized
          map:
            name: hostname
            model: os
            group: group
          headers:
            X-Auth-Token: 'xxxxx'
model_map:
  a10: acos
  arista_eos: eos
  cisco_asa: asa
  cisco: ios
  fortigate: fortios
  iosxe: ios
  iosxr: iosxr
  juniper: junos
  nexus: nxos
  opengear: opengear

hooks:
 email_output:
   type: exec
   events: [post_store, node_fail]
   cmd: '/home/oxidized/extra/oxidized-report-git-commits ~/gitdir/ | mail -s "Oxidized updates for ${OX_NODE_NAME}" networkchanges@xxxx.com'
   async: true
   timeout: 120

Any help getting this resolved will be greatly appreciated...

Thank you.

-Patrick

**Comment by wk** [comment]
This appears to be related to `oxidized-web` rather than `oxidized` itself; please retry this with the latest version of both `oxidized` and `oxidized-web`, and if the issue persists, re-open the issue under the `ytti/oxidized-web` repository.
