### ISSUE TITLE
Issue with Fortinet Multiple VDOM Backup

### ISSUE THREAD

**Issue by ldgomes** [ytti/oxidized#1419]
Hi,

I am actually working with oxidized to backup all my devices (Cisco Nexus, IOS, Fortinet, Juniper, Palo Alto ..)

Everything is working fine exept for my Foritnet Firewalls.
It's a cluster configured in VDOM ( 5 VDOM).
Full Configuration is quite big, about 6M.
Backup is done via ssh.

Job seems to be launched correctly, but it hangs after a few minutes.

I have been reading Fortinet issues posted and I already:
- Changed the timeout value in oxidized config file to a bigger one : 480
- Disabled paging on the system console configuration 
     config system console
         set output standard
      end
- Debug as been activated, making a tail -f I can see configuration fetching, but very very slow.

See below debug output during the fortinet backup process:

oxidized@S2-EX3PJ-N001 ~]$ oxidized
I, [2018-06-26T08:56:20.444779 #29351]  INFO -- : Oxidized starting, running as pid 29351
I, [2018-06-26T08:56:20.445532 #29351]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
D, [2018-06-26T08:56:20.445757 #29351] DEBUG -- : resolving DNS for fw-in3pj-c001...
D, [2018-06-26T08:56:20.445810 #29351] DEBUG -- : IPADDR
D, [2018-06-26T08:56:20.446657 #29351] DEBUG -- : node.rb: resolving node key 'model', with passed global value of '' and node value 'fortios'
D, [2018-06-26T08:56:20.446722 #29351] DEBUG -- : node.rb: setting node key 'model' to value 'ios' from global
D, [2018-06-26T08:56:20.446775 #29351] DEBUG -- : node.rb: returning node key 'model' with value 'fortios'
D, [2018-06-26T08:56:20.446821 #29351] DEBUG -- : lib/oxidized/node.rb: Loading model "fortios"
D, [2018-06-26T08:56:20.447482 #29351] DEBUG -- : lib/oxidized/model/model.rb Added all to the commands list
D, [2018-06-26T08:56:20.447571 #29351] DEBUG -- : lib/oxidized/model/model.rb Added secret to the commands list
D, [2018-06-26T08:56:20.447622 #29351] DEBUG -- : lib/oxidized/model/model.rb Added get system status to the commands list
D, [2018-06-26T08:56:20.447937 #29351] DEBUG -- : node.rb: resolving node key 'input', with passed global value of 'ssh, telnet' and node value ''
D, [2018-06-26T08:56:20.448031 #29351] DEBUG -- : node.rb: returning node key 'input' with value 'ssh, telnet'
D, [2018-06-26T08:56:20.506386 #29351] DEBUG -- : node.rb: resolving node key 'output', with passed global value of 'git' and node value ''
D, [2018-06-26T08:56:20.506463 #29351] DEBUG -- : node.rb: returning node key 'output' with value 'git'
D, [2018-06-26T08:56:20.528233 #29351] DEBUG -- : node.rb: resolving node key 'username', with passed global value of '' and node value ''
D, [2018-06-26T08:56:20.528309 #29351] DEBUG -- : node.rb: setting node key 'username' to value 'backup' from global
D, [2018-06-26T08:56:20.528357 #29351] DEBUG -- : node.rb: returning node key 'username' with value 'backup'
D, [2018-06-26T08:56:20.528389 #29351] DEBUG -- : node.rb: resolving node key 'password', with passed global value of '' and node value ''
D, [2018-06-26T08:56:20.528421 #29351] DEBUG -- : node.rb: setting node key 'password' to value 'XXXXXXXX' from global
D, [2018-06-26T08:56:20.528464 #29351] DEBUG -- : node.rb: returning node key 'password' with value 'XXXXXX'
I, [2018-06-26T08:56:20.528541 #29351]  INFO -- : lib/oxidized/nodes.rb: Loaded 1 nodes
D, [2018-06-26T08:56:20.821591 #29351] DEBUG -- : lib/oxidized/core.rb: Starting the worker...
D, [2018-06-26T08:56:20.821681 #29351] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 0 of 1
D, [2018-06-26T08:56:20.830092 #29351] DEBUG -- : lib/oxidized/worker.rb: Added fw-in3pj-c001 to the job queue
D, [2018-06-26T08:56:20.830763 #29351] DEBUG -- : lib/oxidized/job.rb: Starting fetching process for fw-in3pj-c001 at 2018-06-26 06:56:20 UTC
D, [2018-06-26T08:56:20.860356 #29351] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2018-06-26T08:56:20.870754 #29351] DEBUG -- : AUTH METHODS::["none", "publickey", "password"]
D, [2018-06-26T08:56:20.874521 #29351] DEBUG -- : lib/oxidized/input/ssh.rb: Connecting to fw-in3pj-c001
* Version 3.11.4 (ruby 2.0.0-p648), codename: Love Song
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://127.0.0.1:8888
Use Ctrl-C to stop
D, [2018-06-26T08:56:21.018898 #29351] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^([-\w\.\~]+(\s[\(\w\-\.\)]+)?\~?\s?[#>$]\s?)$/] at fw-in3pj-c001
D, [2018-06-26T08:56:21.824284 #29351] DEBUG -- : lib/oxidized/input/cli.rb: Running post_login commands at fw-in3pj-c001
D, [2018-06-26T08:56:21.824396 #29351] DEBUG -- : lib/oxidized/model/model.rb Collecting commands' outputs
D, [2018-06-26T08:56:21.824479 #29351] DEBUG -- : lib/oxidized/model/model.rb Executing get system status
D, [2018-06-26T08:56:21.824587 #29351] DEBUG -- : lib/oxidized/input/ssh.rb get system status @ fw-in3pj-c001 with expect: /^([-\w\.\~]+(\s[\(\w\-\.\)]+)?\~?\s?[#>$]\s?)$/
D, [2018-06-26T08:56:21.824864 #29351] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^([-\w\.\~]+(\s[\(\w\-\.\)]+)?\~?\s?[#>$]\s?)$/] at fw-in3pj-c001
D, [2018-06-26T08:56:21.871107 #29351] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2018-06-26T08:56:22.232269 #29351] DEBUG -- : lib/oxidized/model/model.rb Executing config global
D, [2018-06-26T08:56:22.232380 #29351] DEBUG -- : lib/oxidized/input/ssh.rb config global @ fw-in3pj-c001 with expect: /^([-\w\.\~]+(\s[\(\w\-\.\)]+)?\~?\s?[#>$]\s?)$/
D, [2018-06-26T08:56:22.232647 #29351] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^([-\w\.\~]+(\s[\(\w\-\.\)]+)?\~?\s?[#>$]\s?)$/] at fw-in3pj-c001
D, [2018-06-26T08:56:22.635520 #29351] DEBUG -- : lib/oxidized/model/model.rb Executing get hardware status
D, [2018-06-26T08:56:22.635646 #29351] DEBUG -- : lib/oxidized/input/ssh.rb get hardware status @ fw-in3pj-c001 with expect: /^([-\w\.\~]+(\s[\(\w\-\.\)]+)?\~?\s?[#>$]\s?)$/
D, [2018-06-26T08:56:22.636038 #29351] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^([-\w\.\~]+(\s[\(\w\-\.\)]+)?\~?\s?[#>$]\s?)$/] at fw-in3pj-c001
D, [2018-06-26T08:56:22.871417 #29351] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2018-06-26T08:56:23.041226 #29351] DEBUG -- : lib/oxidized/model/model.rb Executing end
D, [2018-06-26T08:56:23.041336 #29351] DEBUG -- : lib/oxidized/input/ssh.rb end @ fw-in3pj-c001 with expect: /^([-\w\.\~]+(\s[\(\w\-\.\)]+)?\~?\s?[#>$]\s?)$/
D, [2018-06-26T08:56:23.041610 #29351] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^([-\w\.\~]+(\s[\(\w\-\.\)]+)?\~?\s?[#>$]\s?)$/] at fw-in3pj-c001
D, [2018-06-26T08:56:23.444185 #29351] DEBUG -- : lib/oxidized/model/model.rb Executing show full-configuration | grep .
D, [2018-06-26T08:56:23.444295 #29351] DEBUG -- : lib/oxidized/input/ssh.rb show full-configuration | grep . @ fw-in3pj-c001 with expect: /^([-\w\.\~]+(\s[\(\w\-\.\)]+)?\~?\s?[#>$]\s?)$/
D, [2018-06-26T08:56:23.444597 #29351] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^([-\w\.\~]+(\s[\(\w\-\.\)]+)?\~?\s?[#>$]\s?)$/] at fw-in3pj-c001
D, [2018-06-26T08:56:30.949608 #29351] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2018-06-26T08:56:31.949946 #29351] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2018-06-26T08:56:32.957364 #29351] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2018-06-26T08:56:34.011429 #29351] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2018-06-26T08:43:47.058267 #29278] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2018-06-26T08:43:48.058717 #29278] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
**W, [2018-06-26T08:43:48.568468 #29278]  WARN -- : 10.10.4.3 raised Timeout::Error with msg "execution expired"
D, [2018-06-26T08:43:48.568548 #29278] DEBUG -- : lib/oxidized/node.rb: Oxidized::SSH failed for fw-in3pj-c001**
D, [2018-06-26T08:43:49.170811 #29278] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel

**W, [2018-06-26T08:49:06.130365 #29278]  WARN -- : 10.10.4.3 raised Errno::ECONNRESET with msg "Connection reset by peer - send(2)"
D, [2018-06-26T08:49:06.130461 #29278] DEBUG -- : lib/oxidized/node.rb: Oxidized::SSH failed for fw-in3pj-c001**

Any idea/help will be appreciated.

Thanks a lot.

**Comment by laf** [comment]
Are you sure you aren't hitting a timeout still?
