### ISSUE TITLE
Corrupted loose reference file: HEAD

### ISSUE THREAD

**Issue by darkounet** [ytti/oxidized#142]
I have a problem during the start of oxidized process :

This is the output 

```
Corrupted loose reference file: HEAD
/var/lib/gems/2.1.0/gems/oxidized-0.7.2/lib/oxidized/output/git.rb:167:in `empty?': Corrupted loose reference file: HEAD (Rugged::ReferenceError)
        from /var/lib/gems/2.1.0/gems/oxidized-0.7.2/lib/oxidized/output/git.rb:167:in `update_repo'
        from /var/lib/gems/2.1.0/gems/oxidized-0.7.2/lib/oxidized/output/git.rb:153:in `update'
        from /var/lib/gems/2.1.0/gems/oxidized-0.7.2/lib/oxidized/output/git.rb:46:in `store'
        from /var/lib/gems/2.1.0/gems/oxidized-0.7.2/lib/oxidized/worker.rb:40:in `process'
        from /var/lib/gems/2.1.0/gems/oxidized-0.7.2/lib/oxidized/worker.rb:14:in `block in work'
        from /var/lib/gems/2.1.0/gems/oxidized-0.7.2/lib/oxidized/worker.rb:14:in `each'
        from /var/lib/gems/2.1.0/gems/oxidized-0.7.2/lib/oxidized/worker.rb:14:in `work'
        from /var/lib/gems/2.1.0/gems/oxidized-0.7.2/lib/oxidized/core.rb:37:in `run'
        from /var/lib/gems/2.1.0/gems/oxidized-0.7.2/lib/oxidized/core.rb:30:in `initialize'
        from /var/lib/gems/2.1.0/gems/oxidized-0.7.2/lib/oxidized/core.rb:11:in `new'
        from /var/lib/gems/2.1.0/gems/oxidized-0.7.2/lib/oxidized/core.rb:11:in `new'
        from /var/lib/gems/2.1.0/gems/oxidized-0.7.2/lib/oxidized/cli.rb:9:in `run'
        from /var/lib/gems/2.1.0/gems/oxidized-0.7.2/bin/oxidized:9:in `<top (required)>'
        from /usr/local/bin/oxidized:23:in `load'
        from /usr/local/bin/oxidized:23:in `<main>'
```

**Comment by ytti** [comment]
Did it ever work? Can you checkout the repo manually? Can you commit to the repo manually?

**Comment by darkounet** [comment]
when i try ```git log ```

```fatal: Not a git repository (or any parent up to mount point /srv)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).```

On every repositories ... :(

**Comment by ytti** [comment]
Did it ever work?  Can you create new repo with git CLI?

**Comment by darkounet** [comment]
It works since 2 weeks, and now unable to start oxidized

**Comment by ytti** [comment]
Yes but does git work on any repo locally? If 'git log' is failing for repo, then I don't think oxidized can work either.
Now we just need to figure out if anything works with git in the system.

**Comment by darkounet** [comment]
yes it works, 

when i tried git log, I saw the change node per node.

**Comment by ytti** [comment]
I'm confused, above you say 'git log' does not work, but complains on every repo. But now you say it does work? Did something change or did I misunderstand?

Can  you commit to the repo locally? Mayby just add file, commit, remove file commit?

**Comment by darkounet** [comment]
no, currently it's doesn't work, it worked last week, and this morning we have this error.

when I add a file , commit , push & co I always have the same message :

```
fatal: Not a git repository (or any parent up to mount point /srv)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
``


I have a another question, groups are named i.e 018000001a , in the /etc/oxidized/config I have define repo var like this : repo: "/srv/oxidized/oxidized.git", but in fact I have all my groups repository in /srv/oxidized/018000001a.git/ , it is normal ?

I think I have to move my repositories and retry to launch oxidized daemon...

**Comment by ytti** [comment]
Yes that is normal. Ratioanale is that you'd do somethig like this

repo: "/foo/bar/configs/default.git"

then any group would be
/foo/bar/configs/group.git

I don't know what to tell you about the git issue, seems the repo is broken. Can you create new repo from the CLI in the same filesystem, or does that complain too?
git init 
git touch foo
git add .
git commit -a -m 'fooo'

**Comment by darkounet** [comment]
the giti init work, I have made a backup of all the repositories and re run the daemon.

I'm currently working on a new output for gitlab which permit us to save on an external repository

**Comment by ytti** [comment]
How was this solved? Do we know what that issue was?

**Comment by darkounet** [comment]
The git repositories was broken. don't have more informations.
