### ISSUE TITLE
HP Procurve does not work with old firmware

### ISSUE THREAD

**Issue by mcullmann** [ytti/oxidized#1422]
Hi everybody,

I am really new into oxidized, that means I installed it yesterday. I have about 100 HP Procurve Switches and only a few does not work. I think I figured out, that the reason are older firmware versions. 

I guess the procurve.rb does not match the login page I get from this switches. 

For a few Switches I will be able to update, but for most of them, I will need months to get a time slot. Is there a work around for my problem?

This is the login screen I get:

login as: XXXadminXXX
We'd like to keep you up to date about:
  * Software feature updates
  * New product announcements
  * Special events
Please register your products now at:  www.hp.com/networking/register

XXXadminXXX@XXXIPXXX's password:
HP J8697A Switch 5406zl
Software revision K.15.15.0008

Copyright (C) 1991-2014 Hewlett-Packard Development Company, L.P.

                   RESTRICTED RIGHTS LEGEND
 Confidential computer software.  Valid license from HP required for possession,
 use or copying. Consistent with FAR 12.211 and 12.212, Commercial Computer
 Software, Computer Software Documentation, and Technical Data for Commercial
 Items are licensed to the U.S. Government under vendor's standard commercial
 license.
                   HEWLETT-PACKARD DEVELOPMENT COMPANY, L.P.
                   20555 State Highway 249, Houston, TX 77070

Press any key to continue

Thank you in advance for any help

**Comment by mrplow87** [comment]
Try changing the motd and exec banners to be empty as a workaround.

From `show run`:
```
banner exec " "
banner motd " "
```

You have to call it with a delimiter, so you'll actually enter `banner motd a`, then type a single space, then "a" and press enter. Same for exec.

```
switch(config)# banner motd a

Enter TEXT message.  End with the character'a'

  a

switch(config)#
```

The exec banner is not available on all HP Procurve models, though. But your 5406zl is one of them.

**Comment by deajan** [comment]
In my case I had a HP J9728A 2920-48G Switch with the same behavior.

In oxidized logs I got:
```
WARN -- : DEVICE_IP raised IOError with msg "closed stream"
```

I could get rid of the problem by disabling banners switch side and ssh keepalive oxidized side.

On switch:
```
conf
no banner exec
no banner motd
```

In oxidized config:
```
vars:
  ssh_no_keepalive: true
```

The latter resolving a lot of issues it seems.

**Comment by davama** [comment]
We had similar issues with our banner but that was because there was a space at the very beginning of the banner.

```
[ ]banner msg blabla
```

So we simply had to remove that space from the banner

```
banner msg blabla
```
