### ISSUE TITLE
oxidized with git output: rugged not found

### ISSUE THREAD

**Issue by alzhur** [ytti/oxidized#1423]
Fresh install of oxidized, clean vm with FreeBSD 11.1.
First, I've installed oxidized from packages, but it was very old version (like 0.21).
So, I've updated it with "gem update".
Configuration with output to file works fine, but I need history of changes -> switch to git output.
But if I change config to git output, oxidized crashed at start with message

> rugged not found: sudo gem install rugged

"gem list" shows rugged 0.27.2 installed
Files of rugged and oxidized exists in subfolders of /usr/local/lib/ruby/gems/2.4/gems/
ruby version 2.4.4p296
Any help?
PS Most likely, this is not problem with oxidized, but with my setup, but I'm completely newbee with RUBY and can not resolve it myself.

**Comment by ytti** [comment]
Are the file permission readable to your Oxidized user?

**Comment by alzhur** [comment]
@ytti Which file(s) do you mean?
You suspect what installing rugged gem with root user creates some file with no read permission for all?
/usr/local/lib/ruby/gems/2.4/gems/rugged-0.27.2/* have permissions 755.

**Comment by ytti** [comment]
I guess ktrace/kdump to see what it is trying to open and what is the reason it fails. 

When you installed rugged, did it actually compile? As it's just C bindings to libgit it needs to be compiled.

You could change this line: https://github.com/ytti/oxidized/blob/master/lib/oxidized/output/git.rb#L6

```
rescue LoadError => error
  Oxidized.logger.debug error
  Oxidized.logger.debug error.message
  raise ...
```

**Comment by alzhur** [comment]
Looks like it was some problem with rugged/libgit compilation.
I've removed rugged v0.27.2 installed with gem, and re-installed pre-compiled v0.27.1 form pkg, and now oxidized starts fine.
