### ISSUE TITLE
web ui config diff/display pages error when encountering non-ascii characters

### ISSUE THREAD

**Issue by puphime** [ytti/oxidized#1425]
as in the title, the web ui throws an exception when the config in question has a non-standard character
in this particular case the fortiOS config contains replacement HTML for blocked pages containing:

`Wykryto próbę dostępu do strony www podlegającej filtrowaniu.<br>
W przypadku pewności że została zablokowana nieprawidłowa strona prosimy o informację w systemie Helpdesk wraz z treścią poniższego komunikatu.`

this results in an Encoding::UndefinedConversionError at /node/version/view or /node/version/diffs ("\xC3" from ASCII-8BIT to UTF-8) in file: encoder.rb location: encode line: 25

Backtrace is attached bc github backticks delete all the whitespace for some reason

[backtrace.txt](https://github.com/ytti/oxidized/files/2149611/backtrace.txt)

**Comment by wk** [comment]
You are using a very old version of `oxidized` and `oxidized-web`. This issue has been resolved in ytti/oxidized-web#148. Please upgrade to 0.24/0.11.1.

**Comment by puphime** [comment]
thanks, turns out my supervisor somehow installed an old version and i didnt realise
