### ISSUE TITLE
Oxidized Slow pulling up backup configs LibreNMS

### ISSUE THREAD

**Issue by 07stuntar1** [ytti/oxidized#1426]
Hi, I am use Oxidized with Librenms. I am using the Git but it seems to take about 10-15 mins to load the backup date.  We have about 3,000 devices. Any fix to this?

**Comment by wk** [comment]
Could you specify the versions of oxidized and oxidized-web you use (`gem list | grep oxidized`)?

Is this an issue you are experiencing with the oxidized web interface when attempting to review the backup status?

**Comment by laf** [comment]
Also, load what exactly, the config for a specific device or the list of devices we show under the tools menu?

**Comment by 07stuntar1** [comment]
Hi sorry for the late response. For some reason it didn't show that someone responded. 

oxidized (0.21.0, 0.20.0, 0.19.0)
oxidized-script (0.5.0, 0.4.0, 0.3.1)
oxidized-web (0.9.3, 0.9.2, 0.9.1, 0.8.0)

@laf When I am trying to view the config backup page. So when I select a cisco switch, configs it takes about 10-15 mins to load before actually seeing the config.  I cant seem to figure out the issue.

**Comment by laf** [comment]
> @laf When I am trying to view the config backup page. So when I select a cisco switch, configs it takes about 10-15 mins to load before actually seeing the config. I cant seem to figure out the issue.

Ok but is this in the LibreNMS webui or the Oxidized webui?

**Comment by 07stuntar1** [comment]
LibreNMS webui. For some reason my Oxidized webui is not coming up. Everything is backing up. I type the webpage and port 8888 but nothing comes up. Firewall is off too

**Comment by laf** [comment]
If the oxidized web interface isn't coming up then librenms won't be able to get the config because it needs oxidized webui.

`ls -i:8888` - Does that show oxidized is running on that port?

**Comment by 07stuntar1** [comment]
tcp        0      0 127.0.0.1:8888          0.0.0.0:*               LISTEN      2089/puma 3.9.1 (tc
It works in librenms. I can pull up the switches.

**Comment by laf** [comment]
Is librenms installed on the same server? What is your config in librenms for oxidized?

**Comment by chasgames** [comment]
I've always had the same issue, never found out the cause. Happy to help troubleshoot. LibreNMS is on the same server as Oxidized.

After clicking the config tab, eventually presented with 504 Gateway Time-out.  Sometimes i noticed even the oxidized web interface doesn't load but lsof shows it listening like below. A restart of oxidized normally helps to fix it, but still slow in general.

sudo lsof -i:8888
```
COMMAND    PID     USER   FD   TYPE    DEVICE SIZE/OFF NODE NAME
oxidized 64683 oxidized    8u  IPv4 984304503      0t0  TCP *:ddi-tcp-1 (LISTEN)
```

gem list | grep oxidized
```
oxidized (0.24.0, 0.21.0)
oxidized-script (0.5.0)
oxidized-web (0.11.1, 0.9.3)
```

Any ideas?

**Comment by chasgames** [comment]
I ran a suggestion from another thread ```git gc --auto``` on the oxidized repo. It went from 3GB to 61MB which is pretty insane.

At the moment everything is loading at a reasonable speed, not fast, but no timeouts. Will keep an eye on it.

**Comment by ytti** [comment]
Prior to this commit on every run we added trash to git, regardless if data changed or not
https://github.com/ytti/oxidized/commit/d95084059f20c04e109b0843b2ce8cd3c6abf770

I hope that after that commit the git repository does not grow when there are no changes.

**Comment by chasgames** [comment]
Great, thanks very much ytti. I will update and test.

**Comment by chasgames** [comment]
Unfortunately still the same on Oxidized v.0.26.3.

Seems a little better in terms of repo grow rate, so I think the commit helped the storage usage not grow so fast.

Perhaps the slow pulling of configs is a different reason, It looks like its worse with devices with >300 versions etc..

I have devices with only a few versions and these load fairly instantly.

I can also observe the same timeouts with these devices in oxidized-web, but I only seem to get it when oxidized has been running for a while. After a systemctl restart oxidized,  they load OK after 10 seconds or so.

**Comment by DenisKlimek** [comment]
We are facing the same issue here aswell. Oxidized (0.21.0 / 0.26.3) is running with about 650 devices and 17k commits. I did `git gc --auto` which gave us some better performence for now. We will continue monitoring if the performence stays so or not.

**Comment by chasgames** [comment]
How do i find what it's stuck on when loading versioning, perhaps checking puma http logs somehow ? I have no output with debug set to true (latest versions on all)
