### ISSUE TITLE
Prompt HPE Procurve doesn't match the regex

### ISSUE THREAD

**Issue by cedricbix** [ytti/oxidized#1429]
Hello All,

I'm trying to setup and oxidized server on our infra. Installation work's well, but I can't get the switchs conf.

I've bellow error in the terminal.

![prtscr capture](https://user-images.githubusercontent.com/9820746/42167240-b70df39a-7e0d-11e8-8a27-e2e810828b76.jpg)

I've modify the the /var/lib/gems/2.3.0/gems/oxidized-0.24.0/lib/oxidized/model/procurve.rb file to change the regex for the following one : 
`  prompt /^([\*]+)(\n)([\*A-Za-z 0-9()\-',.]+)(\n)([\*A-Za-z 0-9()\-',.]+)(\n)([\*A-Za-z 0-9()\-',.]+)(\n)([\*]+)(\n)(\n)<SW-[A-Z0-9]*[A-Z0-9]>$/`

I've test the regex on different online tester. It seems to be the good one. 

Could you help me to make it works, please ?

THanks and regard,

Cédric

**Comment by laf** [comment]
You don't need to match the banner, just the `<SW-SR19>` part of the prompt. `^\r?([<>\w.-]+)([ #]+)` works for that but I'm no regex master.

You should also just copy the origin procurve.rb file to your local dir to change it, that will mean it persists between updates: https://github.com/ytti/oxidized/blob/master/docs/Creating-Models.md#extending-an-existing-model-with-a-new-command

**Comment by cedricbix** [comment]
Hello Laf,

Thanks, It works now. As you said, just need to match the <SW-SR19> part.

Thanks,

Cédric

**Comment by laf** [comment]
You should submit a pull request with your changes.
