### ISSUE TITLE
Oxidized as a service not running/crashing

### ISSUE THREAD

**Issue by bruccoo3000** [ytti/oxidized#1430]
Hello all,

Need some assistance with setting up oxidized to run as service.

Here is what happens when I invoke the service:
```
`==== AUTHENTICATING FOR org.freedesktop.systemd1.manage-units ===
Authentication is required to manage system services or units.
Authenticating as: oxidized
Password:
==== AUTHENTICATION COMPLETE ===
[oxidized@oxidized system]$ sudo systemctl status oxidized -l
● oxidized.service - Oxidized - Network Device Configuration Backup Tool
   Loaded: loaded (/usr/lib/systemd/system/oxidized.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2018-07-02 11:24:55 EDT; 2s ago
 Main PID: 11042 (oxidized)
   CGroup: /system.slice/oxidized.service
           └─11042 /usr/bin/ruby /usr/local/bin/oxidized

Jul 02 11:24:55 oxidized.ad.nadlab.com systemd[1]: Started Oxidized - Network Device Configuration Backup Tool.
Jul 02 11:24:55 oxidized.ad.nadlab.com systemd[1]: Starting Oxidized - Network Device Configuration Backup Tool...
Jul 02 11:24:55 oxidized.ad.nadlab.com oxidized[11042]: I, [2018-07-02T11:24:55.887596 #11042]  INFO -- : Oxidized starting, running as pid 11042
Jul 02 11:24:55 oxidized.ad.nadlab.com oxidized[11042]: I, [2018-07-02T11:24:55.888986 #11042]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
[oxidized@oxidized system]$ sudo systemctl status oxidized -l
● oxidized.service - Oxidized - Network Device Configuration Backup Tool
   Loaded: loaded (/usr/lib/systemd/system/oxidized.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2018-07-02 11:24:55 EDT; 14s ago
 Main PID: 11042 (oxidized)
   CGroup: /system.slice/oxidized.service
           └─11042 /usr/bin/ruby /usr/local/bin/oxidized

Jul 02 11:24:55 oxidized.ad.nadlab.com systemd[1]: Started Oxidized - Network Device Configuration Backup Tool.
Jul 02 11:24:55 oxidized.ad.nadlab.com systemd[1]: Starting Oxidized - Network Device Configuration Backup Tool...
Jul 02 11:24:55 oxidized.ad.nadlab.com oxidized[11042]: I, [2018-07-02T11:24:55.887596 #11042]  INFO -- : Oxidized starting, running as pid 11042
Jul 02 11:24:55 oxidized.ad.nadlab.com oxidized[11042]: I, [2018-07-02T11:24:55.888986 #11042]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
[oxidized@oxidized system]$ sudo systemctl status oxidized -l
● oxidized.service - Oxidized - Network Device Configuration Backup Tool
   Loaded: loaded (/usr/lib/systemd/system/oxidized.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Mon 2018-07-02 11:25:12 EDT; 9s ago
  Process: 11042 ExecStart=/usr/local/bin/oxidized (code=exited, status=1/FAILURE)
 Main PID: 11042 (code=exited, status=1/FAILURE)

Jul 02 11:25:12 oxidized.ad.nadlab.com oxidized[11042]: from /usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:70:in `require'
Jul 02 11:25:12 oxidized.ad.nadlab.com oxidized[11042]: from /usr/local/share/gems/gems/puma-3.11.4/lib/puma/launcher.rb:4:in `<top (required)>'
Jul 02 11:25:12 oxidized.ad.nadlab.com oxidized[11042]: from /usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:70:in `require'
Jul 02 11:25:12 oxidized.ad.nadlab.com oxidized[11042]: from /usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:70:in `require'
Jul 02 11:25:12 oxidized.ad.nadlab.com oxidized[11042]: from /usr/local/share/gems/gems/puma-3.11.4/lib/rack/handler/puma.rb:15:in `config'
Jul 02 11:25:12 oxidized.ad.nadlab.com oxidized[11042]: from /usr/local/share/gems/gems/puma-3.11.4/lib/rack/handler/puma.rb:62:in `run'
Jul 02 11:25:12 oxidized.ad.nadlab.com oxidized[11042]: from /usr/local/share/gems/gems/oxidized-web-0.11.1/lib/oxidized/web.rb:29:in `block in run'
Jul 02 11:25:12 oxidized.ad.nadlab.com systemd[1]: oxidized.service: main process exited, code=exited, status=1/FAILURE
Jul 02 11:25:12 oxidized.ad.nadlab.com systemd[1]: Unit oxidized.service entered failed state.
Jul 02 11:25:12 oxidized.ad.nadlab.com systemd[1]: oxidized.service failed.`
```

Here is some system information:
[oxidized@oxidized system]$ uname -a
Linux oxidized.ad.nadlab.com 3.10.0-862.3.3.el7.x86_64 #1 SMP Fri Jun 15 04:15:27 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

[oxidized@oxidized system]$ cat /etc/*release
CentOS Linux release 7.5.1804 (Core)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.5.1804 (Core)
CentOS Linux release 7.5.1804 (Core)

Gem Lists:
[oxidized@oxidized system]$ gem list

*** LOCAL GEMS ***

activesupport (5.2.0)
asetus (0.3.0)
backports (3.11.3)
bigdecimal (1.3.5, default: 1.3.4)
bundler (default: 1.16.2)
bundler-unload (1.0.2)
charlock_holmes (0.7.6)
cmath (default: 1.0.0)
concurrent-ruby (1.0.5)
csv (3.0.0, default: 1.0.0)
date (default: 1.0.0)
did_you_mean (1.2.1, 1.2.0)
emk-sinatra-url-for (0.2.1)
etc (1.0.1, default: 1.0.0)
executable-hooks (1.5.0, 1.4.2)
fcntl (default: 1.0.0)
ffi (1.9.25)
fiddle (default: 1.0.0)
fileutils (1.1.0, default: 1.0.2)
gem-wrappers (1.4.0, 1.3.2)
haml (5.0.4)
htmlentities (4.3.4)
i18n (1.0.1)
io-console (default: 0.4.6)
ipaddr (default: 1.2.0)
json (default: 2.1.0)
minitest (5.11.3, 5.10.3)
multi_json (1.13.1)
mustermann (1.0.2)
net-ssh (5.0.2, 4.1.0)
net-telnet (0.1.1)
openssl (2.1.1, default: 2.1.0)
oxidized (0.24.0)
oxidized-script (0.5.1)
oxidized-web (0.11.1)
power_assert (1.1.3, 1.1.1)
psych (default: 3.0.2)
puma (3.11.4)
rack (2.0.5, 1.6.10)
rack-protection (2.0.3, 1.5.5)
rack-test (1.0.0, 0.7.0)
rake (12.3.1, 12.3.0)
rb-fsevent (0.10.3)
rb-inotify (0.9.10)
rdoc (6.0.4, default: 6.0.1)
rubygems-bundler (1.4.5, 1.4.4)
rubygems-update (2.7.7)
rugged (0.27.2)
rvm (1.11.3.9)
sass (3.5.6)
sass-listen (4.0.0)
scanf (default: 1.0.0)
sdbm (default: 1.0.0)
sinatra (2.0.3, 1.4.8)
sinatra-contrib (2.0.3, 1.4.7)
slop (4.6.2, 3.6.0)
stringio (default: 0.0.1)
strscan (default: 1.0.0)
temple (0.8.0)
test-unit (3.2.8, 3.2.7)
thread_safe (0.3.6)
tilt (2.0.8)
tzinfo (1.2.5)
webrick (default: 1.4.2)
xmlrpc (0.3.0)
zlib (default: 1.0.0)

I have followed the instructions for CentOS by following these directions:
#For RHEL / CentOS 7 put it in /etc/systemd/system/
#and call it with systemctl start oxidized.service

I have also changed the owner of the oxidized.service from "root" to "oxidized" and back to see if that causes any difference. It does not.

What else should I be looking at or am going down the incorrect path?

Thanks

**Comment by laf** [comment]
As the oxidized user, try just running `oxidized` and see if it starts that way.

You shouldn't need login details for the oxidized user though, how did you add that user in?

**Comment by bruccoo3000** [comment]
laf, I have no issues running the oxidized application by invoking it by command.  That part seems fine.
The issue comes up when I run it and lately in background it'll stop once I stop my ssh connection to the server oxidized is running on.  Thinking running it as a service would remedy that situation.

The user "oxidized" was created during the installation process of CentOS 7 and marked as an administrator.

**Comment by laf** [comment]
Sounds like it's launching in your session rather than as a daemon. Pastebin the output of ` cat /etc/systemd/system/oxidized.service`

**Comment by bruccoo3000** [comment]
Here's the requested output:
[oxidized@oxidized ~]$ cat /etc/systemd/system/oxidized.service
#For debian 8 put it in /lib/systemd/system/
#For RHEL / CentOS 7 put it in /etc/systemd/system/
#and call it with systemctl start oxidized.service

[Unit]
Description=Oxidized - Network Device Configuration Backup Tool
After=network-online.target multi-user.target
Wants=network-online.target

[Service]
ExecStart=/usr/local/bin/oxidized
User=oxidized
KillSignal=SIGKILL

[Install]
WantedBy=multi-user.target

**Comment by bruccoo3000** [comment]
Hello, any other information required?

**Comment by laf** [comment]
Unfortunately I've got nothing else to suggest. Starting oxidized via systemctl for me works as expected :(

**Comment by bruccoo3000** [comment]
Hmmmm, ok.  I have it running daemonized now and that seems to be ok for a bit.  I'll monitor and see what I can do.

Thanks again

**Comment by franco433** [comment]
could you help me whit the following error, the mentioned object 10.252.28.210 no longer exists on the router .db

I, [2019-09-04T14:46:53.425822 #6734]  INFO -- : Oxidized starting, running as pid 6734
I, [2019-09-04T14:46:53.426446 #6734]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
I, [2019-09-04T14:46:53.470048 #6734]  INFO -- : lib/oxidized/nodes.rb: Loaded 42 nodes
Puma starting in single mode...
* Version 3.11.4 (ruby 2.5.1-p57), codename: Love Song
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://127.0.0.1:8888
Use Ctrl-C to stop
F, [2019-09-04T14:46:57.766949 #6734] FATAL -- : Oxidized crashed, crashfile written in /home/oxidized/.config/oxidized/crash
failed to insert entry: invalid object specified - 10.252.28.210
