### ISSUE TITLE
Problem when including telnet in config file

### ISSUE THREAD

**Issue by mortendamm71** [ytti/oxidized#1431]
Oxidized runs without problem when this config
input:
  default: ssh

However, if I change the config to
input:
  default: ssh, telnet

Oxidized crashed with the outputs (debug: true)

I, [2018-07-04T12:28:14.209570 #8421]  INFO -- : Oxidized starting, running as pid 8421
I, [2018-07-04T12:28:14.210611 #8421]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
D, [2018-07-04T12:28:14.210854 #8421] DEBUG -- : resolving DNS for 10.1.1.22...
D, [2018-07-04T12:28:14.210916 #8421] DEBUG -- : IPADDR 
D, [2018-07-04T12:28:14.211039 #8421] DEBUG -- : node.rb: resolving node key 'input', with passed global value of 'ssh, telnet' and node value ''
D, [2018-07-04T12:28:14.211109 #8421] DEBUG -- : node.rb: returning node key 'input' with value 'ssh, telnet'
F, [2018-07-04T12:28:14.347372 #8421] FATAL -- : Oxidized crashed, crashfile written in /home/oxidized/.config/oxidized/crash
telnet not found for node 10.1.1.22
Traceback (most recent call last):
        19: from /opt/rh/rh-ruby25/root/usr/local/bin/oxidized:23:in `<main>'
        18: from /opt/rh/rh-ruby25/root/usr/local/bin/oxidized:23:in `load'
        17: from /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/oxidized-0.21.0/bin/oxidized:9:in `<top (required)>'
        16: from /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/oxidized-0.21.0/lib/oxidized/cli.rb:12:in `run'
        15: from /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/oxidized-0.21.0/lib/oxidized/core.rb:4:in `new'
        14: from /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/oxidized-0.21.0/lib/oxidized/core.rb:4:in `new'
        13: from /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/oxidized-0.21.0/lib/oxidized/core.rb:14:in `initialize'
        12: from /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/oxidized-0.21.0/lib/oxidized/core.rb:14:in `new'
        11: from /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/oxidized-0.21.0/lib/oxidized/nodes.rb:123:in `initialize'
        10: from /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/oxidized-0.21.0/lib/oxidized/nodes.rb:10:in `load'
         9: from /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/oxidized-0.21.0/lib/oxidized/nodes.rb:128:in `with_lock'
         8: from /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/oxidized-0.21.0/lib/oxidized/nodes.rb:128:in `synchronize'
         7: from /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/oxidized-0.21.0/lib/oxidized/nodes.rb:15:in `block in load'
         6: from /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/oxidized-0.21.0/lib/oxidized/nodes.rb:15:in `each'
         5: from /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/oxidized-0.21.0/lib/oxidized/nodes.rb:19:in `block (2 levels) in load'
         4: from /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/oxidized-0.21.0/lib/oxidized/nodes.rb:19:in `new'
         3: from /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/oxidized-0.21.0/lib/oxidized/node.rb:21:in `initialize'
         2: from /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/oxidized-0.21.0/lib/oxidized/node.rb:144:in `resolve_input'
         1: from /opt/rh/rh-ruby25/root/usr/local/share/gems/gems/oxidized-0.21.0/lib/oxidized/node.rb:144:in `map'
/opt/rh/rh-ruby25/root/usr/local/share/gems/gems/oxidized-0.21.0/lib/oxidized/node.rb:146:in `block in resolve_input': telnet not found for node 10.1.1.22 (Oxidized::MethodNotFound)

Telnet from command line works great
telnet>

Thanks for helping

**Comment by ytti** [comment]
How did you install the Oxidized? We support gem and docker, and both of these methods install telnet. It looks like in your installation you do not have telnet installed. Use ```gem install telnet``` or which ever method you are using for package management,

**Comment by mortendamm71** [comment]
Thanks,
gem install net-telnet
Solved the issue
