### ISSUE TITLE
Error installing oxidized-web: Failed to build gem native extension.

### ISSUE THREAD

**Issue by Mngom** [ytti/oxidized#1433]
Hello,
I need help installing "oxidized-web" on an AWS linux instance.
Here's what happens when I call the command: gem install oxidized-web.

Building native extensions.  This could take a while...
ERROR:  Error installing oxidized-web:
        ERROR: Failed to build gem native extension.

        /home/ec2-user/.rvm/rubies/ruby-2.5.1/bin/ruby extconf.rb
checking for -licui18n... no
which: no brew in (/home/ec2-user/.rvm/gems/ruby-2.5.1/bin:/home/ec2-user/.rvm/gems/ruby-2.5.1@global/bin:/home/ec2-user/.rvm/rubies/ruby-2.5.1/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/ec2-user/.composer/vendor/bin:/home/ec2-user/.rvm/bin:/home/ec2-user/.local/bin:/home/ec2-user/bin)
checking for -licui18n... no

***************************************************************************************
*********** icu required (brew install icu4c or apt-get install libicu-dev) ***********
***************************************************************************************
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/home/ec2-user/.rvm/rubies/ruby-2.5.1/bin/$(RUBY_BASE_NAME)
        --with-icu-dir
        --without-icu-dir
        --with-icu-include
        --without-icu-include=${icu-dir}/include
        --with-icu-lib
        --without-icu-lib=${icu-dir}/lib
        --with-icui18nlib
        --without-icui18nlib
        --with-icui18nlib
        --without-icui18nlib

Gem files will remain installed in /home/ec2-user/.rvm/gems/ruby-2.5.1/gems/charlock_holmes-0.7.6 for inspection.
Results logged to /home/ec2-user/.rvm/gems/ruby-2.5.1/gems/charlock_holmes-0.7.6/ext/charlock_holmes/gem_make.out

**Comment by wk** [comment]
Have you attempted doing as the error message suggests and installing libicu and libicu-dev packages prior to installing the gem?

**Comment by majordom21** [comment]
thanx. apt-get install libicu-dev make the deal
