### ISSUE TITLE
not matching configured prompt (?-mix:^\(?.+\)?\s[#>])" Aruba 325 

### ISSUE THREAD

**Issue by Olegsplit** [ytti/oxidized#1434]
Device: Aruba 325 firmware 6.5.4.4
In version Oxidized-0.21.0 work fine.
In version Oxidized-0.24.0 have problem:
`not matching configured prompt (?-mix:^\(?.+\)?\s[#>])"`

Fix:
change in file aows.rd next line:
`prompt /^\(?.+\)?\s[#>]/`
on
`prompt /^\(?.+\)?\s?[#>]/`

And restart oxidized.

**Comment by laf** [comment]
This has been changed from that to the current one previously. Can you show the prompt it's trying to match?
