### ISSUE TITLE
debug log location?

### ISSUE THREAD

**Issue by jlixfeld** [ytti/oxidized#1441]
Hi,

I have ```debug: true``` in the config root level, and in the input level, but I don't see where they are getting written to.

I'm using ```/etc/oxidized``` as OXIDIZED_HOME.

I poked through the code, and found a reference for debugs being written to the crash directory, but they don't seem to be getting written there either.

Am I missing something else?

```log: /etc/oxidized/logs/oxidized.log``` produces logs in the named file without issue.

```
oxidized@monitor:/etc/oxidized$ tree -L 1 $OXIDIZED_HOME
/etc/oxidized
├── config
├── crash
├── extra
├── logs
├── model
├── oxidized.git
├── pid
└── router.db

5 directories, 3 files
oxidized@monitor:/etc/oxidized$ ls -al
total 64
drwxr-x---   7 oxidized oxidized  4096 Jul  9 12:09 .
drwxr-xr-x 106 root     root      4096 Jul  9 10:28 ..
-rw-r-----   1 oxidized oxidized   897 Jul  9 12:08 config
drwxr-x---   2 oxidized oxidized  4096 Jul  9 12:07 crash
drwxr-x---   2 oxidized oxidized  4096 Jul  9 09:41 extra
drwxr-x---   2 oxidized oxidized 20480 Jul  9 11:00 logs
drwxr-x---   2 oxidized oxidized  4096 Jul  9 11:35 model
drwxr-x---   6 oxidized oxidized  4096 Jul  9 12:10 oxidized.git
-rw-r--r--   1 oxidized oxidized     5 Jul  9 12:09 pid
-rw-r-----   1 oxidized oxidized 10578 Jul  9 11:45 router.db
oxidized@monitor:/etc/oxidized$ ls -al crash/
total 8
drwxr-x--- 2 oxidized oxidized 4096 Jul  9 12:07 .
drwxr-x--- 7 oxidized oxidized 4096 Jul  9 12:09 ..
oxidized@monitor:/etc/oxidized$
```

**Comment by ytti** [comment]
Definitely should be in ```/etc/oxidized/logs/ip-ssh```:

Root:
```
https://github.com/ytti/oxidized/blob/master/lib/oxidized/config.rb#L6-L8
```

File:
```
https://github.com/ytti/oxidized/blob/master/lib/oxidized/input/ssh.rb#L24
```


Looking at your previous issue, perhaps they are related. Anything in your ~oxidized/config/? Do we know for certain that runtime also sees OXIDIZED_HOME?

If nothing obviously wrong, we probably need to add debugging in ```ssh.rb```, like before line #24 ```Oxidized.logger.debug "Config::Log: " + Oxidized::Config::Log```

**Comment by jlixfeld** [comment]
Indeed, a `systemd` newb.

After much poking and prodding, adding the appropriate `Environment` tag to the `oxidized.service` file is one of the many news that are now required if using `systemd`, because any of the old ways seem to have been rendered useless in this new world:

```
[Service]
Environment="OXIDIZED_HOME=/etc/oxidized"
```

Perhaps adding `#Environment="OXIDIZED_HOME=/etc/oxidized"` to the bottom of the `[Service]` tag with some verbiage in `README.md > Configuration` describing how to make it work in a `systemd` world?

Or I could try a PR?
