### ISSUE TITLE
MLNXOS - AuthenticationFailed with msg "Authentication failed for user

### ISSUE THREAD

**Issue by quartist** [ytti/oxidized#1446]
Hi,

we try to backup mellanox SX1012, but we have an error: AuthenticationFailed with msg "Authentication failed for user login@ip.
SSH form cli works. Log is empty.
Please help.

**Comment by ytti** [comment]
Not much to go by with the information you provided. Are you sure you're trying same credentials in SSH CLI as Oxidized?
If so, perhaps see https://github.com/ytti/oxidized/blob/master/docs/Configuration.md#ssh-auth-methods

**Comment by scbx** [comment]
I had the same issue - https://github.com/ytti/oxidized/blob/master/docs/Configuration.md#ssh-auth-methods helped. Thanks @ytti
