### ISSUE TITLE
Change node hostname but keep using previous hostname config file 

### ISSUE THREAD

**Issue by subkhanave** [ytti/oxidized#1449]
I changed my switch hostname from ACS-001 to ACS-002, same switch but with different hostname
I need to update on oxidized from hostname ACS-001 to ACS-002, tried change on router.db it creates new hostname with blank config backup although it's the same IP. I guess oxidized treat each node based on hostname. 

Is there anyway to achieve this?

**Comment by ytti** [comment]
You don't tell what output you are using, but I assume you're using git output, otherwise I don't understand the question.

And I understand you want to keep file history in git, even when filename changes.

This is, in my book, not a Oxidized issue, but a Git issue. 

In your repository rename (mv) the file and commit and push. Git will detect this as rename and you will have file with new name with old history, and Oxidized will happily keep on piling on the new file.

 1. mv ACS-001 ACS-002
 2. git commit -m "Rename ACS-001 to ACS-002" ACS-002
 3. git push

**Comment by subkhanave** [comment]
Hi, yes sorry for not mentioning git output

I'm new to git, I couldn't find the repo
Also how about router.db file?

**Comment by ytti** [comment]
```
 1. Stop Oxidized
 2. Rename git
 3. Update router.db
```
In your configuration file there should be stanza describing where the repo lives. There are lot of Git resources and forums available online.

**Comment by subkhanave** [comment]
Hi,
Do you mean I need to clone the bare repo then commit?

oxidized@localhost oxidized.git]$ ls -ltrh
total 32K
drwxr-xr-x   4 oxidized oxidized   31 May  9 15:53 refs
drwxr-xr-x   2 oxidized oxidized   21 May  9 15:53 info
drwxr-xr-x   2 oxidized oxidized   27 May  9 15:53 hooks
-rw-r--r--   1 oxidized oxidized   73 May  9 15:53 description
-rw-r--r--   1 oxidized oxidized   23 May  9 15:53 HEAD
-rw-r--r--   1 oxidized oxidized  113 May  9 15:53 config
-rw-r--r--   1 oxidized oxidized 7.0K Jul 13 16:25 index
drwxr-xr-x 260 oxidized oxidized 8.0K Jul 13 16:48 objects
[oxidized@localhost oxidized.git]$ 
[oxidized@localhost oxidized.git]$ pwd
/home/oxidized/.config/oxidized/oxidized.git
[oxidized@localhost oxidized.git]$

**Comment by ytti** [comment]
Yes, you can clone it, then change, then commit, then push.

**Comment by subkhanave** [comment]
Hi @ytti 
Can you please reopen this issue? 

I already changed the filename using "git mv" and commit then push, but after I update the router.db to the new hostname the history config is gone.

I need to rollback the router.db to previous hostname (without changing the filename in git to previous hostname) , after that I can find my history config.

It seems changing hostname in router.db is creating new filename, although I had update it using git mv.

Step I took:
old hostname: ACS-001
new hostname: ACS-002

`git mv ACS-001 ACS-002`
`git commit -m "Rename file ACS-001 to ACS-002"`
`git push` 

update router.db, change line
`ACS-001:cisco`
to
`ACS-002:cisco`
start oxidized

on web GUI: ACS-002 with no previous config, no ACS-001 found

Rollback:
stop oxidized
rollback router.db to previous, change line
`ACS-002:cisco`
to
`ACS-001:cisco`
start oxidized

on web GUI: ACS-001 with previous config found, no ACS-002 found

**Comment by subkhanave** [comment]
Does anyone have idea how to rename?

**Comment by ewysong** [comment]
@subkhanave 4 years after your comment, but I was researching how to do the same thing, and the solution I found was to use the script at https://gist.github.com/emiller/6769886

I ran the following on an Ubuntu 20.04 host running Oxidized:
```sudo systemctl stop oxidized
sudo su - oxidized
bash
mkdir configs.git.clone && cd configs.git.clone
git clone /home/oxidized/configs.git/
cd configs
Create the file "git-mv-with-history" with the contents of the script from https://gist.github.com/emiller/6769886
chmod +x git-mv-with-history
./git-mv-with-history <old name>=<new name> (when ran this will take a long time depending on git history size)
Ex: ./git-mv-with-history firewall_A=firewall_B
# move script out of repo so its not committed as well
mv git-mv-with-history ..
# can't commit without setting email
git config --global user.email "oxidized@xyz.com"
# can't commit without setting name
git config --global user.name "Oxidized"
git commit -m "rename device firewall_A to firewall_B with git-mv-with-history script"
# Uses git filter-branch which rewrites history, so --force is needed
git push --force
cd ~
rm -rf configs.git.clone/
exit
exit
sudo systemctl start oxidized```

After that, rename your host in LibreNMS (if you're using it) and you'll see the previous history.
