### ISSUE TITLE
[Procurve] show system power-supply

### ISSUE THREAD

**Issue by thanegill** [ytti/oxidized#1453]
Since #1176 was merged I get flapping configs outputs whenever the wattage changes on my switches. 

```
switch-name# show system power-supply 

Power Supply Status: 

  Member  PS#   Model     Serial      State           AC/DC  + V        Wattage   Max   
  ------- ----- --------- ----------- --------------- ----------------- --------- ------
  1       1     JL085A    CN75GZ83SY  Powered         AC 120V/240V        48       250
  1       2     JL085A    CN75GZ840B  Powered         AC 120V/240V        34       250
  2       1     JL085A    CN75GZ83U4  Powered         AC 120V/240V        47       250
  2       2     JL085A    CN75GZ8625  Powered         AC 120V/240V        33       250
  3       1     JL085A    CN79GZ82G2  Powered         AC 120V/240V        21       250
  3       2     JL085A    CN79GZ82CQ  Powered         AC 120V/240V        25       250
```
This is a 3810 stack running 16.02. The Wattage column changes constantly. Almost every time a config is pulled. 

It looks like the output on some hp/procurve systems show usage and some don't.

**Comment by davama** [comment]
@thanegill Noticed that too. Using this gsub for that, might need to mod for you case.

```
    cfg.gsub! /(^(\s|\s+)[1-4]\s+\S+\s+(\S+|Powered|Not Present)).*/, '\\1'
```
If you want to undo the PR that's fine too.

**Comment by davama** [comment]
@rbeumer
Typo?
How does your config look?

**Comment by rbeumer** [comment]
@davama 
My apologies, it seems I was too hasty. When I test it now it works flawlessly.

**Comment by RaceFPV** [comment]
Just updating to let everyone know I saw the same issue as well with Aruba switches across multiple models and the gsub provided by davama cleaned it up enough that I don't get config changes at every wattage uptick/downtick.

**Comment by davama** [comment]
> If you want to undo the PR that's fine too.

As i mentioned before we can undo it, if that is the consensus.

Now our setup uses custom models with our own edits so having 'show system....' is not needed since we can easily add to our own model. https://github.com/ytti/oxidized/issues/1384

It was originally added to the distribution model to have all hardware info within the config backup but with custom models now it's not really needed.

Whatever is decided is fine

**Comment by laf** [comment]
Seems like it would be worthwhile having a PR for the gsub fix if someone can do that?

**Comment by systeembeheerder** [comment]
@laf I tried both gusbs but still have "Watt updates". My vote would be to remove #1176
