### ISSUE TITLE
Configs from NXOS truncated.

### ISSUE THREAD

**Issue by DmitryBlind** [ytti/oxidized#1458]
Hello.
I got similar issue with https://github.com/ytti/oxidized/issues/1401 but with NXOS.
I have 2 Cisco Nexus 7000 switches. I use VDC (virtual device context) at both switches.Each switch have 3 context. Each context have separated management IP. 
With default setting oxidized collect full configuration from 2 contexts.From last context configuration truncated. 
I try use telnet, remove "show version" and "show inventory", replacing "show running-config" with "show running-config vdc-all" but configs still truncated.
Any ideas?

**Comment by ytti** [comment]
Do you use enable password? Do you actually get enable password prompt when writing 'enable'? If you do, then set your enable password to ```false```

**Comment by DmitryBlind** [comment]
I have enable: false.
I got "show running-config" output but it truncated after several lines. When i remove "show version" and "show inventory" output config truncated at middle object-group.
When i leave only "show running-config vdc-all" in nxos.rb i got truncated config after switch to first vdc, but in ssh.log i got full output.

**Comment by DmitryBlind** [comment]
Suddenly i fix it.
I swap 'show running-config' and 'show inventory' in nxos.rb.
