### ISSUE TITLE
oxidized[24813]: ssh not found for node

### ISSUE THREAD

**Issue by jasonyates** [ytti/oxidized#1459]
Installed oxidized via gem on Amazon Linux using Ruby 2.4.4

Install was successful but when migrating my working configuration over from another install, it fails with the following error. I've installed ssh and net-ssh manually via gem but it still fails.

Jul 24 10:02:17 ip-10-40-103-31 systemd[1]: Started Oxidized - Network Device Configuration Backup Tool.
Jul 24 10:02:17 ip-10-40-103-31 systemd[1]: Starting Oxidized - Network Device Configuration Backup Tool...
Jul 24 10:02:17 ip-10-40-103-31 oxidized[24813]: ssh not found for node 1.1.1.1

--------------------------------------------------
2018-07-24 09:58:06 UTC
ssh not found for node 1.1.1.1 [Oxidized::MethodNotFound]
--------------------------------------------------
/usr/local/share/gems/gems/oxidized-0.24.0/lib/oxidized/node.rb:152:in `block in resolve_input'
/usr/local/share/gems/gems/oxidized-0.24.0/lib/oxidized/node.rb:150:in `map'
/usr/local/share/gems/gems/oxidized-0.24.0/lib/oxidized/node.rb:150:in `resolve_input'
/usr/local/share/gems/gems/oxidized-0.24.0/lib/oxidized/node.rb:23:in `initialize'
/usr/local/share/gems/gems/oxidized-0.24.0/lib/oxidized/nodes.rb:20:in `new'
/usr/local/share/gems/gems/oxidized-0.24.0/lib/oxidized/nodes.rb:20:in `block (2 levels) in load'
/usr/local/share/gems/gems/oxidized-0.24.0/lib/oxidized/nodes.rb:16:in `each'
/usr/local/share/gems/gems/oxidized-0.24.0/lib/oxidized/nodes.rb:16:in `block in load'
/usr/local/share/gems/gems/oxidized-0.24.0/lib/oxidized/nodes.rb:128:in `synchronize'
/usr/local/share/gems/gems/oxidized-0.24.0/lib/oxidized/nodes.rb:128:in `with_lock'
/usr/local/share/gems/gems/oxidized-0.24.0/lib/oxidized/nodes.rb:10:in `load'
/usr/local/share/gems/gems/oxidized-0.24.0/lib/oxidized/nodes.rb:123:in `initialize'
/usr/local/share/gems/gems/oxidized-0.24.0/lib/oxidized/core.rb:14:in `new'
/usr/local/share/gems/gems/oxidized-0.24.0/lib/oxidized/core.rb:14:in `initialize'
/usr/local/share/gems/gems/oxidized-0.24.0/lib/oxidized/core.rb:4:in `new'
/usr/local/share/gems/gems/oxidized-0.24.0/lib/oxidized/core.rb:4:in `new'
/usr/local/share/gems/gems/oxidized-0.24.0/lib/oxidized/cli.rb:12:in `run'
/usr/local/share/gems/gems/oxidized-0.24.0/bin/oxidized:8:in `<top (required)>'
/usr/local/bin/oxidized:23:in `load'
/usr/local/bin/oxidized:23:in `<main>'

**Comment by ytti** [comment]
Perhaps wrong permissions? If you try in shell as Oxidized user:

```
irb
require "net/ssh"
```

does that work?

**Comment by jasonyates** [comment]
Aha. For some reason it was missing io-console.

 gem install io-console 

Fixed it. It's running as expected now.
