### ISSUE TITLE
Oxidized output file

### ISSUE THREAD

**Issue by rongtler** [ytti/oxidized#1462]
Hi everyone, 

I have two questions about the oxidized output file. Here is my output config:

```
output:
  file:
    directory: /home/oxidized/.config/oxidized/configuration
```

1/ When I first run oxidized, it creates a most recent running config file with the name correspond to the IP address of my device. So as long as I keep oxidized running, will oxidized continuously getting and storing the config or it only pulls the config only once at the beginning? If oxidized keep pulling the config file while it's running, what is the time interval to repeat a config pull?

2/ If I want to change the filename which is stored by oxidized, which file should I edit? For example, I need oxidized to get the most recent running config and stores it in the format: `IP-address_dd:mm:yy-hh:mm:ss`, so that I can have different versions of the config by time. I think that I should edit the `file.rb` file in the `oxidized/lib/oxidized/output` directory, particularly the following function:

```
def store node, outputs, opt = {}
      file = File.expand_path @cfg.directory
      if opt[:group]
        file = File.join File.dirname(file), opt[:group]
      end
      FileUtils.mkdir_p file
      file = File.join file, node
      open(file, 'w') { |fh| fh.write outputs.to_cfg }
      @commitref = file
    end
```

However, I'm lack of ruby coding skill in order to do this task. Hope someone can help me out.

Thanks for reading!

**Comment by laf** [comment]
> 1/ When I first run oxidized, it creates a most recent running config file with the name correspond to the IP address of my device. So as long as I keep oxidized running, will oxidized continuously getting and storing the config or it only pulls the config only once at the beginning? If oxidized keep pulling the config file while it's running, what is the time interval to repeat a config pull?

Oxidized will keep trying to get the config based on the interval value.



> 2/ If I want to change the filename which is stored by oxidized, which file should I edit? For example, I need oxidized to get the most recent running config and stores it in the format: `IP-address_dd:mm:yy-hh:mm:ss`, so that I can have different versions of the config by time. I think that I should edit the `file.rb` file in the `oxidized/lib/oxidized/output` directory, particularly the following function:

Just switch to git output, it's exactly designed for versioning of the files and provides diffs.

**Comment by madhatterfounder** [comment]
Search your OS for the correct file.rb, for me it was (gem installer)

/var/lib/gems/3.0.0/gems/oxidized-0.29.0/lib/oxidized/output/file.rb

Using an editor, delete the "store method" section only, and replace it with this.

    def store(node, outputs, opt = {})
      file = File.expand_path(@cfg.directory)
      file = File.join(File.dirname(file), opt[:group]) if opt[:group]
      FileUtils.mkdir_p(file)  
      timestamp = Time.now.strftime("%d-%m-%Y_%H-%M-%S")
      file = File.join(file, "#{node}_#{timestamp}")  
      File.write(file, outputs.to_cfg)
      @commitref = file
    end

Save, and restarted oxidized. 

Now, every time a config is saved, the filename is appended with the current time.
