### ISSUE TITLE
git configuration key error

### ISSUE THREAD

**Issue by haniehrajabi** [ytti/oxidized#1463]
Hi there,
I am trying to install oxidized on Centos7. 
can you please let me know what is the problem with my configuration:

```username: oxidized
password: xxxxxxxx
model: junos
interval: 600
log: /var/lib/oxidized/.config/oxidized/log
use_syslog: true
debug: true
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
pid: /var/lib/oxidized/.config/oxidized/oxidized.pid
rest: 0.0.0.0:8888
input:
  default: ssh, telnet
  debug: false
  ssh:
    secure: false
output:
  default: git
  git:
    user: oxidized
    single_repo: true
    repo: /var/lib/oxidized/.config/oxidized/devices.git
source:
  default: csv
  csv:
    file: /var/lib/oxidized/.config/oxidized/router.db
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      ip: 1
      model: 2
      username: 3
      password: 4
  model_map:
    juniper: junos
```
my crash report: Invalid value; config files can only store string, bool or int keys [TypeError]

 
```
/var/lib/oxidized/.gem/ruby/gems/oxidized-0.24.0/lib/oxidized/output/git.rb:192:in `[]='  
```

Thank you

**Comment by haniehrajabi** [comment]
adding the email key seems fixed the crash!

**Comment by wk** [comment]
Can this issue be closed as resolved?

**Comment by m0yellow** [comment]
Unfortunately I'm the one to report the bug as still existing.
I tried to activated personalized commits, and crashed it.
I'm unfamiliar with ruby debugging. Do you need tracebacks/coredump/debugoutput from me?

**Comment by ytti** [comment]
Leave ```default: git``` in config, but remove the whole ```git``` block, then restart oxidized, then look and modify the generated ```git``` block.
