### ISSUE TITLE
IOS Module updated recently, cannot pull down config

### ISSUE THREAD

**Issue by tnielsen2** [ytti/oxidized#1467]
After a recent update, Oxidized no longer works with the IOS module.
The username that I log into, gives me an escalated privilege prompt, however does not pull down the config. The debug log shows this, but after the module issues the "enable" command, nothing happens. 

```
root@2e4e90abd73e:~/.config/oxidized/logs# tail -f 10.150.21.247-ssh

=============================================================================
This device is managed by Ansible! Think before you make manual changes!
=============================================================================
Logging you in automatically...

usw1.hdos#enable
usw1.hdos#
```

Config file is below:
```
---
username: !OMITTED!
password: !OMITTED!
model: cisco
interval: 1800
use_syslog: true
log: /root/.config/oxidized/logs
debug: true
threads: 50
timeout: 960
retries: 1
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 0.0.0.0:8888
next_adds_job: false
vars:
  remove_secret: false
  enable: !OMITTED!
groups: {}
models: {}
pid: /root/.config/oxidized/pid
input:
  default: ssh, telnet
  debug: true
  ssh:
    secure: false

output:
  default: git
  git:
    single_repo: true
    user: root
    email: !OMITTED!
    repo: !OMITTED!

source:
  default: csv
  csv:
    file: /root/.config/oxidized/router.db
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      ip: 1
      model: 2
      username: 3
      password: 4
      enable: 5
    gpg: false

model_map:
  cisco: ios
  cisco: asa
  juniper: junos
  ciscowlc: aireos
  brocade: nos
  fortigate: fortios
  sonicwall: aosw
  ironware: ironware

hooks:
  push_to_remote:
   type: githubrepo
   events: [post_store]
   remote_repo: !OMITTED!
   username: tnielsen2
   password: !OMITTED!
```
Let me know if there is anything else I can do/provide in order to help solve this issue.

Thanks!

**Comment by ytti** [comment]
This is because you claim you need to enable, so it's enabling and expecting enable prompt.

So either you need to claim you do not need to enable (i.e. ```false```), or you need to claim you do need to enable, but there won't be any prompt (i.e. ```true```).

Change your enable password to one of those and you're golden. It didn't actually work for you previously either, it was race condition and if it always returned same config, that's very lucky.

**Comment by tnielsen2** [comment]
Thanks for the guidance. This fixed my issue.
