### ISSUE TITLE
remove_secret removes configuration as well

### ISSUE THREAD

**Issue by fatman00** [ytti/oxidized#1468]
Hi

The remove_secret configuration removes configuration parameters as well from IOS devices.

I have take a configuration backup before and after enabling the feature:
-snmp-server community public RO
+snmp-server community <configuration removed>

The RO(Read-Only) parameter is removed with the community string.
Line 27 in ios.rb will remove an ACL if applied to SNMP as well.

**Comment by wk** [comment]
Without knowing the community the parameter was relevant to, what is the utility in knowing the parameters?

**Comment by fatman00** [comment]
To know what ACL have been applied to SNMP. Maybe the Community should be replaced with ******(Stars) and not just removed?
