### ISSUE TITLE
source returns no usable nodes

### ISSUE THREAD

**Issue by rygumcmxci** [ytti/oxidized#1469]
CentOS 7: 

LibreNMS - Installed and running already 

Oxidized installed: Unable to start

Config passes the YAML validation tool located in LibreNMS: 

Error: 

source returns no usable nodes
/usr/local/share/gems/gems/oxidized-0.24.0/lib/oxidized/core.rb:15:in `initialize': source returns no usable nodes (Oxidized::Core::NoNodesFound)
        from /usr/local/share/gems/gems/oxidized-0.24.0/lib/oxidized/core.rb:4:in `new'
        from /usr/local/share/gems/gems/oxidized-0.24.0/lib/oxidized/core.rb:4:in `new'
        from /usr/local/share/gems/gems/oxidized-0.24.0/lib/oxidized/cli.rb:12:in `run'
        from /usr/local/share/gems/gems/oxidized-0.24.0/bin/oxidized:8:in `<top (required)>'
        from /usr/local/bin/oxidized:23:in `load'
        from /usr/local/bin/oxidized:23:in `<main>'

Current config: 
---
username: Username
password: "Password" # only works in double quotes for some reason
interval: 86400
use_syslog: true
debug: true
threads: 30
timeout: 20
retries: 2
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: Server_IP_Address:8080
vars:
  enable: Enable_Password
groups: {}
pid: "/home/oxidized/.config/oxidized/pid"
input:
  default: ssh
  debug: false
  ssh:
    secure : false
output:
  default: git
  git:
      user: oxidized
      email: Company_Email@My_Company.com
      repo: "/home/oxidized/.config/oxidized/oxidized.git"
source:
  default: csv
  csv:
    file: "/home/oxidized/.config/oxidized/router.db"
    delimiter: !ruby/regexp/:/
    map:
      name: 0
      model: 1
model_map:
  cisco: ios
  juniper: junos

Router.db file:

Device_IP:ios

Any ideas on how I can get oxidized started and integrated successfully with librenms?

**Comment by bl4kd3th** [comment]
Try changing the delimiter line to:
```
delimiter: !ruby/regexp /:/
```
looks like you are missing a space

**Comment by rygumcmxci** [comment]
I just made made this correction and it fixed it! Thanks for being my second pair of eyes, you are literally a savior!

**Comment by wk** [comment]
Closing this issue as it appears to be resolved.
