### ISSUE TITLE
Case sensitivity with hosts file

### ISSUE THREAD

**Issue by masonke** [ytti/oxidized#147]
ubuntu 14.04

Just started using oxidized and have all my devices listed in /etc/hosts and my router.db in /data/oxidized/devices.
The 80 entries in router.db were all lower case and the hosts file uppercase or CamelCase.

When I started oxidized, the log spooled messages like this:
.......
E, [2015-07-15T20:15:27.674726 #4200] ERROR -- : node {:name=>"router-01", :model=>"ios"} is not resolvable, raised Resolv::ResolvError with message 'no address for router-01'
E, [2015-07-15T20:15:27.678240 #4200] ERROR -- : node {:name=>"router-02", :model=>"ios"} is not resolvable, raised Resolv::ResolvError with message 'no address for router-02'
......

The devices were in the hosts file as 
10.70.255.1 ROUTER-01
10.70.255.2 Router-02

Changing the hosts file to all lower case solved the problem.  Seems like some sort of case sensitivity?

**Comment by ytti** [comment]
Looks like you may need to upgrade ruby to get rid of it:

https://bugs.ruby-lang.org/issues/10550

We could somewhat easily replace the standard library with homegrown solution if upgrading ruby isn't an option and this is a breaking problem.

**Comment by ytti** [comment]
Any update? If not, I assume it's not huge issue and ruby upgrade is viable solution.

**Comment by ytti** [comment]
Closing on lack of activity, assuming ruby upgrade is sufficient solution.

**Comment by dorkmatt** [comment]
Seems relevant even in early 2016, as the current Ubuntu LTS 14.04.4 release only offers ruby 2.0.0p384 which still carries this bug.

**Comment by mattie47** [comment]
Also just hit this issue.

Thanks for pasting the log!

Changing my DNS entries to lowercase fixed my issue.
