### ISSUE TITLE
Cisco ASR9K fails with status=>:no_connection

### ISSUE THREAD

**Issue by victorseth** [ytti/oxidized#1474]
Hello,

Some devices, all them are ASR9001 Cisco IOSXR version 6.2, fails to save configuration with "timeout"

> W, [2018-07-30T16:03:21.515421 #20910]  WARN -- : {IP_DEVICE} raised Timeout::Error with msg "timed out while waiting for more data"
> W, [2018-07-30T16:03:21.616946 #20910]  WARN -- : {NAME_DEVICE} status no_connection, retries exhausted, giving up

I use a modified script for Cisco (the vanilla fails because we use tacacs and the user enter already with "enable"). We use:

>     post_login 'terminal length 0'
>     post_login 'terminal width 0'

To stop the timeout from expecting any input to continue showing the configuration.
But it still not working.

My Oxidized version is 0.20.0. I read changelogs from new version but I didn't find anything about this.

**Comment by ytti** [comment]
You shouldn't need to modify anything, just don't pass enable password to the node, or pass it as ```false``` which is interpreted same as not needing enable.

**Comment by victorseth** [comment]
I also omitted anything but "running-config". That's the only thing I changed. It works for every Cisco, but ASR9K, it still fails with "timeout"

**Comment by cr41gc** [comment]
I have the same issue backing up IOSXR (Cisco ASR 9K's). Here's a crash file:
```
2018-07-30 22:13:52 UTC
Can't get PTY [Oxidized::SSH::NoShell]
--------------------------------------------------
/usr/local/share/gems/gems/oxidized-0.24.0/lib/oxidized/input/ssh.rb:113:in `block (2 levels) in shell_open'
/usr/local/share/gems/gems/net-ssh-4.1.0/lib/net/ssh/connection/channel.rb:614:in `call'
/usr/local/share/gems/gems/net-ssh-4.1.0/lib/net/ssh/connection/channel.rb:614:in `do_failure'
/usr/local/share/gems/gems/net-ssh-4.1.0/lib/net/ssh/connection/session.rb:685:in `channel_failure'
/usr/local/share/gems/gems/net-ssh-4.1.0/lib/net/ssh/connection/session.rb:540:in `dispatch_incoming_packets'
/usr/local/share/gems/gems/net-ssh-4.1.0/lib/net/ssh/connection/session.rb:237:in `ev_preprocess'
/usr/local/share/gems/gems/net-ssh-4.1.0/lib/net/ssh/connection/event_loop.rb:99:in `each'
/usr/local/share/gems/gems/net-ssh-4.1.0/lib/net/ssh/connection/event_loop.rb:99:in `ev_preprocess'
/usr/local/share/gems/gems/net-ssh-4.1.0/lib/net/ssh/connection/event_loop.rb:27:in `process'
/usr/local/share/gems/gems/net-ssh-4.1.0/lib/net/ssh/connection/session.rb:216:in `process'
/usr/local/share/gems/gems/net-ssh-4.1.0/lib/net/ssh/connection/session.rb:178:in `block in loop'
/usr/local/share/gems/gems/net-ssh-4.1.0/lib/net/ssh/connection/session.rb:178:in `loop'
/usr/local/share/gems/gems/net-ssh-4.1.0/lib/net/ssh/connection/session.rb:178:in `loop'
/usr/local/share/gems/gems/oxidized-0.24.0/lib/oxidized/input/ssh.rb:137:in `block in expect'
/usr/share/ruby/timeout.rb:66:in `timeout'
/usr/local/share/gems/gems/oxidized-0.24.0/lib/oxidized/input/ssh.rb:136:in `expect'
/usr/local/share/gems/gems/oxidized-0.24.0/lib/oxidized/input/cli.rb:59:in `login'
/usr/local/share/gems/gems/oxidized-0.24.0/lib/oxidized/input/ssh.rb:57:in `connect'
/usr/local/share/gems/gems/oxidized-0.24.0/lib/oxidized/node.rb:66:in `run_input'
/usr/local/share/gems/gems/oxidized-0.24.0/lib/oxidized/node.rb:43:in `block in run'
/usr/local/share/gems/gems/oxidized-0.24.0/lib/oxidized/node.rb:38:in `each'
/usr/local/share/gems/gems/oxidized-0.24.0/lib/oxidized/node.rb:38:in `run'
/usr/local/share/gems/gems/oxidized-0.24.0/lib/oxidized/job.rb:9:in `block in initialize'
```

I'm using Oxidized 0.24.0 with net-ssh 5.0.2 is that's relevant.

**Comment by laf** [comment]
Probably worth enabling debug and pastebin the output from one of the devices debug files.

**Comment by ZacharyPuls** [comment]
I know it's not super helpful, but I wanted to throw in that we are backing up ~10 ASR9Ks in production right now, with no issues. IOS-XR 6.1.4.

Our vty config looks like this:
line default
 exec-timeout 15 0
 transport input ssh telnet
 transport output none
!
vty-pool default 0 99
