### ISSUE TITLE
Github push to remote not working

### ISSUE THREAD

**Issue by tnielsen2** [ytti/oxidized#1478]
Hello,

I am having some difficulty getting my github webhook to work. 

I am running in a container. I have recently added new devices to my router.db file, however they are not updating to github.

As soon as I get my slack hook indicating a diff, I can run a "git status" in the local repo directory, and what I see is that the file is "deleted" from the git branch.

I am not sure why this is occurring. It is apparent that the application is seeing a change and modifying existing files, but why isn't it adding the new files to the repo?

Also, I am not sure why it is not pushing to the upstream repo... i can log into the container and do a git add, git commit, and a git push, and it all pushes upstream (indicating that all my deploy keys are working from the CLI).

Below is an example of the con01-08 node showing "deleted'. See my config at the very bottom.

```
root@bd2cdb3e612f:~/.config/oxidized-configs# git log
commit cb38b306050b2ddc0ce5389e3cf9b35094bb7542
Author: root <example@example.com>
Date:   Tue Jul 31 22:29:49 2018 +0000

    update /con01-08.lab.labww.internal

commit 7a3dda193454d24e3d1195c15a786600915e2d42
Author: root <example@example.com>
Date:   Tue Jul 31 22:19:25 2018 +0000

    update /fw.lab.labww.internal

commit 59623b24ad50dbc476badfaaedd3f6b0af7d8153
Author: root <example@example.com>
Date:   Tue Jul 31 22:18:58 2018 +0000

    update /wlc01-04.lab.labww.internal

commit b7b6b2c56e0cac0e140e29cda01694f066dc99b0
Author: root <example@example.com>
Date:   Tue Jul 31 22:18:49 2018 +0000

    update /av.lab.labww.internal

commit c778774f1a92f1d7a9822e58b39120b84f148561
Author: root <example@example.com>
Date:   Tue Jul 31 22:18:37 2018 +0000

    update /fw.lab.labww.internal

commit f03b3e36535b88d7c39663068364e8b9935aea1a
Author: root <example@example.com>
Date:   Tue Jul 31 22:18:26 2018 +0000

    update /ring9.lab.labww.internal

commit d83a4efb493469253c78da747a3e061b43fc6f58
Author: Trent Nielsen <tnielsen@YITOL5002.local>
Date:   Tue Jul 31 14:46:05 2018 -0700

    Initial commit
root@bd2cdb3e612f:~/.config/oxidized-configs#  git status
On branch master
Your branch is ahead of 'origin/master' by 6 commits.
  (use "git push" to publish your local commits)
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   av.lab.labww.internal
	deleted:    con01-08.lab.labww.internal
	modified:   fw.lab.labww.internal
	modified:   fw.lab.labww.internal
	modified:   ring9.lab.labww.internal
	modified:   wlc01-04.lab.labww.internal

no changes added to commit (use "git add" and/or "git commit -a")
root@bd2cdb3e612f:~/.config/oxidized-configs#
```

```
---
username: admin
password: password
model: cisco
interval: 1800
use_syslog: true
log: /root/.config/oxidized/logs
debug: true
threads: 100
timeout: 1200
retries: 2
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 0.0.0.0:8888
next_adds_job: false
vars:
  remove_secret: false
  enable: false
groups: {}
models: {}
pid: /root/.config/oxidized/pid
input:
  default: ssh, telnet
  debug: true
  ssh:
    secure: false

output:
  default: git
  git:
    single_repo: true
    user: root
    email: tnielsen@yamholdings.com
    repo: "/root/.config/oxidized-configs/.git"

source:
  default: csv
  csv:
    file: /root/.config/oxidized/router.db
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      ip: 1
      model: 2
      username: 3
      password: 4
      enable: 5
    gpg: false

model_map:
  cisco: ios
  asa: asa
  juniper: junos
  ciscowlc: aireos
  brocade: nos
  fortigate: fortios
  sonicwall: aosw
  ironware: ironware
  opengear: opengear

models:
  asa:
    username: admin
    password: password
    vars:
      enable: password

hooks:
  push_to_remote:
    type: githubrepo
    events: [post_store]
    remote_repo: https://github.com/labtechnology/oxidized-configs.git
    publickey: /root/.ssh/oxidized_configs.pub
    privatekey: /root/.ssh/oxidized_configs
  slack:
    type: slackdiff
    events: [post_store]
    token: omitted
    channel: "#it-alerts-network"
```

**Comment by tnielsen2** [comment]
To add, this used to work, up until a recent update (we have a Jenkins job that rebuilds our container every time there is an update)

**Comment by tnielsen2** [comment]
After trying a number of different things, I have disabled the git hook, and defaulted to file output method. I then use a Jenkins job to SSH to the box and push the files to my private Github repo. I will leave this case open for a time, in case any further troubleshooting needs to be done on my end to assist your development team.  Otherwise, if it goes unanswered I will just close it.

Thanks!

**Comment by laf** [comment]
Are you pointing the hook to a git repo you've created? By default oxidized creates a bare repo which you can't just run git status in without first checking the bare repo out to another directory.

If you can, I'd suggest moving the repo dir out of the way, create the folder `/root/.config/oxidized-configs/` and update your oxidized to point straight to that, restart oxidized and it should create a new repo within `/root/.config/oxidized-configs/`.

**Comment by tnielsen2** [comment]
Yes, The git hook is configured to push to a Github repo that already exists. Forgive me if I am using the wrong terminology or verbiage, CI/CD code methodologies and Docker is something fairly new to me, and I still get confused with some of the verbiage associated with it. 

Are you stating, that every time my container starts, it needs to create a new repo? Or is the application capable of contributing to an existing repo?

I am running a container with a mounted volume. The volume on the Docker host is mounted inside of the container, which is where the oxidized config repo is pulled/cloned to. The output of the configs is pointed to this directory for the "git output" method in my config. 

Every time the container rebuilds after a ytti repo change (we have a Jenkins job that watches the ytti repo for changes then triggers a rebuild automatically), the container restarts, with the config repo already up to date, mounted in the container. 

Having it set up this way has worked for months up until approximately the past 30 days. Sometime between now and then, the application is unable to add new nodes that have appeared in the router.db config,  making them "appear" in my git log as deleted. However, it able to modify existing nodes, but not push them upstream to Github.  Sometime in this past 30 days, pushes to remote stopped occurring, and I was left with the problem that I describe.  

I hope this helps, and I hope I am being clear. I apologize, I am unsure if I have this configured incorrectly, and I get the impression that the way I was doing it worked, but wasn't intended to work that way.

**Comment by laf** [comment]
I'm still not 100% sure what you are doing and I'm not 100% sure if it should even work how you are doing it but it seems you are pointing the output of oxidized git to an existing repo: `repo: "/root/.config/oxidized-configs/.git"`. As far as I'm aware this should be a bare repo which oxidized will create when it needs to. If you mount that into your docker container then it will survive an update.

**Comment by tnielsen2** [comment]
As you are stating, this repo did start as a bare repo once upon a time ago and has survived many updates. Something happened, and I am not sure what that "something" is. 

For now, I am going to leave it how it is and close the case, since my work-around is operational, and is doing the same thing the hook is supposed to be doing. When the next round of changes need to occur, I will purge and restart the repo as you have suggested. 

Thank you for your assistance on the issue. I really appreciate it.
