### ISSUE TITLE
gem 0.7.3

### ISSUE THREAD

**Issue by darkounet** [ytti/oxidized#148]
It is possible to upgrade the gem ? 

Regards

**Comment by ytti** [comment]
Ye I guess we could do release, @nopedial

**Comment by nopedial** [comment]
I'll go through the latest changes and release sometimes this week

**Comment by darkounet** [comment]
Ok thank you! :smile:

**Comment by darkounet** [comment]
:up:

**Comment by ytti** [comment]
we'll do release RSN, it'll have hooks too

**Comment by ytti** [comment]
Sorry for lagging, 0.8.0 has been released now.
