### ISSUE TITLE
Previously working Oxidized installation (for more than a year) crashing

### ISSUE THREAD

**Issue by bdg-robert** [ytti/oxidized#1480]
I've just discovered that my Oxidized installation which has been running flawlessly for quite some time now is suddenly crashing.

Logs from ~oxidized/.config/oxidized/log:

```
I, [2018-08-01T10:52:51.329318 #5640]  INFO -- : Oxidized starting, running as pid 5640
I, [2018-08-01T10:52:51.343664 #5640]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
F, [2018-08-01T10:52:51.361899 #5640] FATAL -- : Oxidized crashed, crashfile written in /home/oxidized/.config/oxidized/crash
I, [2018-08-01T10:53:51.576694 #6410]  INFO -- : Oxidized starting, running as pid 6410
I, [2018-08-01T10:53:51.590438 #6410]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
F, [2018-08-01T10:53:51.612945 #6410] FATAL -- : Oxidized crashed, crashfile written in /home/oxidized/.config/oxidized/crash
I, [2018-08-01T10:54:51.828942 #7189]  INFO -- : Oxidized starting, running as pid 7189
I, [2018-08-01T10:54:51.844305 #7189]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
F, [2018-08-01T10:54:51.867344 #7189] FATAL -- : Oxidized crashed, crashfile written in /home/oxidized/.config/oxidized/crash
```

Contents of ~oxidized/.config/oxidized/crash:

```
--------------------------------------------------
2018-08-01 15:54:51 UTC
no implicit conversion of String into Integer [TypeError]
--------------------------------------------------
/var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/source/http.rb:43:in `[]'
/var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/source/http.rb:43:in `block (2 levels) in load'
/var/lib/gems/2.3.0/gems/asetus-0.3.0/lib/asetus/configstruct.rb:21:in `each'
/var/lib/gems/2.3.0/gems/asetus-0.3.0/lib/asetus/configstruct.rb:21:in `each'
/var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/source/http.rb:42:in `block in load'
/var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/source/http.rb:38:in `each'
/var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/source/http.rb:38:in `load'
/var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/nodes.rb:15:in `block in load'
/var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/nodes.rb:126:in `synchronize'
/var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/nodes.rb:126:in `with_lock'
/var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/nodes.rb:10:in `load'
/var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/nodes.rb:121:in `initialize'
/var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/core.rb:14:in `new'
/var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/core.rb:14:in `initialize'
/var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/core.rb:4:in `new'
/var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/core.rb:4:in `new'
/var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/cli.rb:12:in `run'
/var/lib/gems/2.3.0/gems/oxidized-0.19.0/bin/oxidized:9:in `<top (required)>'
/usr/local/bin/oxidized:23:in `load'
/usr/local/bin/oxidized:23:in `<main>'
--------------------------------------------------
```

When I paste the config in the YAML checker included with LibreNMS it does show the error:

`Malformed inline YAML string: { at line 12 (near "vars: {").
`

Line 12 is the vars section:

```
vars: {
   enable: <password removed>
}
```

Our enable password does include an exclamation mark, so I'm working if it needs to be escaped? I've tried wrapping it in single and double quotes and placing a backslash before the bang.

There have been no recent changes to the configuration. I do keep the system updated with apt-get. We've also recently begun using MikroTik devices, so perhaps this is my derp and I need to define the model somewhere?

Thanks in advance for any assistance!

**Comment by ytti** [comment]
It's complaining about the {}, remove those. Those would be only allowed in inline context, but you're not using inline config.

**Comment by bdg-robert** [comment]
Thanks for the quick reply, ytti.

I pulled the brackets out of the config and attempted to restart oxidized, however it's still crashing with the same output in the crash file.

Config file now contains:

```
vars:
   enable: <password removed>


```

**Comment by ytti** [comment]
What is in your line 12? If it crashes with complain about '{'. Are you sure you changed the correct file? Are you confident you know where your oxidized root is?

**Comment by bdg-robert** [comment]
This was working up until about a week ago and I haven't touched the config or installation since I set it up almost a year ago.

Here's the full sanitized config:

```
username: <removed>
password: <removed>
interval: 3600
log: ~/.config/oxidized/log
use_syslog: false
debug: false
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 0.0.0.0:8888
vars:
   enable: <removed>

groups:
  special_ssh:
     password: <removed>
pid: "/home/oxidized/.config/oxidized/pid"
input:
  default: ssh
  debug: true
  ssh:
    secure: false
output:
  default: git
  debug: false
  git:
    user: Oxidized
    email: <removed>
    repo: "~/.config/oxidized/config-repos/default.git"
source:
    default: http
    debug: true
    http:
      url: https://<removed>/api/v0/oxidized
      secure: false
      map:
        name: hostname
        model: os
        group: group
      headers:
        X-Auth-Token: '<removed>'
model_map:
  airos-af: airos

```

**Comment by bdg-robert** [comment]
Also, the LibreNMS configuration check tool is what complained about the brackets, not Oxidized itself.

**Comment by ytti** [comment]
And there is no chance this is situation where you have config file in say /etc/ somewhere and another in ~/config/oxidized/config and you're looking at wrong one?

Are you sayling line 12 is 'vars:'? Yet you get complaint about {?

**Comment by bdg-robert** [comment]
I'm unaware of another configuration file. I'm the only operator of this server, and I've made no changes. When you ask if there is another, is there a way I can verify?

Oxidized isn't complaining about line 12 and { - it just crashes with the crash output I've provided above. LibreNMS oxidized configuration check tool is what complained about the brackets when I pasted the config into it after I noticed Oxidized wasn't working - I did this because another issue here referenced someone using it to validate their configuration.

**Comment by ytti** [comment]
It seems to break on the HTTP mapping. I think you are getting array from the HTTP, not object.

**Comment by bdg-robert** [comment]
I do import nodes from LibreNMS - are you suggesting there has been a change there?

**Comment by bdg-robert** [comment]
Thanks, ytti.

The root cause of the problem has been found and corrected.

Explanation: Recent turnover in our organization caused us to get rid of shared generic accounts, and as a result, the LibreNMS API key that was generated under that generic user did not have sufficient privileges to access the node list (the user used to be an admin and was changed to "normal user" permissions). Adjusting the user account to have global read permissions resolved the issue.
