### ISSUE TITLE
SSH error with NOKIA ISAM

### ISSUE THREAD

**Issue by mlorentz75** [ytti/oxidized#1482]
SSH connection to NOKIA (former Alcatel Lucent) ISAM was working fine in 0.21.0 but fails with 0.24.0:

```
D, [2018-08-06T15:11:12.383462 #25537] DEBUG -- : lib/oxidized/input/ssh.rb info configure flat @ <removed> with expect: /^([\w.:\>@-]+(#|#\s))$/
D, [2018-08-06T15:11:12.383759 #25537] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^([\w.:\>@-]+(#|#\s))$/] at <removed>
D, [2018-08-06T15:11:12.552670 #25537] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
W, [2018-08-06T15:11:13.388123 #25537]  WARN -- : <removed-ip> raised IOError with msg "closed stream"
D, [2018-08-06T15:11:13.388506 #25537] DEBUG -- : lib/oxidized/node.rb: Oxidized::SSH failed for <removed>
```

After patching ssh.rb in 0.24.0 things were working again:

```
@@ -28,7 +28,7 @@
       ssh_opts = {
         port:         port.to_i,
         paranoid:     secure,
-        keepalive:    true,
+#        keepalive:    true,
         password:     @node.auth[:password], :timeout => Oxidized.config.timeout,
         number_of_password_prompts: 0,
       }
```

I'd suggest making SSH keepalive configurable by variable if that's the root cause?

BTW. This suspiciously looks related: https://github.com/ytti/oxidized/issues/1436

**Comment by wk** [comment]
Thank you for the report and investigation. PR #1489 addresses this by making ssh keepalive configurable, this will allow adding a field to your source (for example, via csv):

```yaml
    map:
      name: 0
      model: 1
      username: 2
      password: 3
    vars_map:
      ssh_port: 4
      enable: 5
      ssh_keepalive: 6
```

The ssh_keepalive field can then be set to ```false``` where keepalive is not desired. Default remains on.

It would be great if you could test the PR in your environment and report back, potentially also submitting a PR with model notes for the relevant model documenting this behavior.

**Comment by mlorentz75** [comment]
Thank you @wk - PR #1489 works just fine. Just adding
```
 vars:
  ssh_no_keepalive: true
```
to the config file turned of SSH keepalive for all nodes, which is currently ok for my setup.

**Comment by wk** [comment]
Thanks for testing!
