### ISSUE TITLE
 oxidized-report-git-commits - how to stop triggering diff for uptime

### ISSUE THREAD

**Issue by Kitesurfer0** [ytti/oxidized#1485]
diff --git a/saupar-acc04-c2950g b/saupar-acc04-c2950g
index 2c304be..f816693 100644
--- a/saupar-acc04-c2950g
+++ b/saupar-acc04-c2950g
@@ -6,7 +6,7 @@
 ! VTP: Compiled Fri 28-Jul-06 15:16 by weiliu
 ! VTP: Image text-base: 0x80010000, data-base: 0x8056A000
 ! VTP: ROM: Bootstrap program is C2950 boot loader
-! VTP: Drivers_uplink_level4 uptime is 3 days, 15 hours, 43 minutes
+! VTP: Drivers_uplink_level4 uptime is 3 days, 16 hours, 46 minutes
 ! VTP: System returned to ROM by power-on
 ! VTP: System restarted at 16:33:42 AEST Sun Aug 5 2018
 ! VTP: System image file is "flash:/c2950-i6q4l2-mz.121-22.EA8a.bin"

Should be an easy fix?

**Comment by systeembeheerder** [comment]
See https://github.com/ytti/oxidized/blob/master/docs/Configuration.md#removing-secrets

Guess you need something like
```
cfg.gsub! /^(VTP: Drivers_uplink_level4 uptime).*/, '\\1 <uptime removed>'
```
in the relevant model.rb
