### ISSUE TITLE
Sending a failed signal in a model

### ISSUE THREAD

**Issue by jameskirsop** [ytti/oxidized#1487]
I've got a [model for Ruckus ZoneDirector's](https://github.com/jameskirsop/oxidized/blob/zonedirector-support/lib/oxidized/model/zonedirector.rb) mostly working but I've found that Oxidized reports success even if the user can't `enable`.

What's the best way to let Oxidized know that if it can't `enable` after connecting to the ZD, that it's actually failed?

**Comment by stacymarkel** [comment]
Yes, you are correct, the user cannot enable it. 
You should run an output and send the report directly.
If you have any router related problem, to visit [Linksys Support Number](http://www.linksysroutersupportnumber.com/)

**Comment by laf** [comment]
So you don't need to send an enable password?

Might be worth showing what happens on the cli.

**Comment by jameskirsop** [comment]
Nope, once you're logged in with an administrative account, typing `enable` doesn't prompt for a password; however, if there is a(nother) user already logged in and 'enabled', you can't get to an enable prompt. It's this later scenario I'm trying to catch.

A _successful_ connection:
```
$ ssh 10.0.12.3 -l %username%

Please login: %username%
Password: 
Welcome to the Ruckus Wireless ZoneDirector 1100 Command Line Interface
ruckus> enable
ruckus# 
```

A _failed_ connection:
```
$ ssh 10.0.12.3 -l %username%

Please login: %username%
Password: 
Welcome to the Ruckus Wireless ZoneDirector 1100 Command Line Interface
ruckus> enable
A privileged user is already logged in. Please try again later or use {force} option to login.
ruckus> 
```

**Comment by systeembeheerder** [comment]
Just tried this model with a Zonedirector 1200, Version 10.1.0.0 build 1515. Would be nice if this model could be included by default.

**Comment by jameskirsop** [comment]
@systeembeheerder I think I'd like to get the enable issue sorted before I submit a PR to have this included in the main release.

**Comment by jameskirsop** [comment]
I'm still trying to figure out how to do this. It's frustrating that Oxidized thinks that an error message is a successful backup - but I can't see any other current model that sends failed signals when an enable prompt fails (without a password).

@laf, do you know of a way of achieving what I'm trying to do?

**Comment by ataias** [comment]
@jameskirsop I am wondering, isn't it safe to simply use `enable force` here? Oxidized will just run `show` commands, right? It shouldn't cause any problems.
