### ISSUE TITLE
Adtrans not being fed by LibreNMS to Oxidized

### ISSUE THREAD

**Issue by johnreejetflores** [ytti/oxidized#1488]
Here's my Oxidized config

--
interval: 86400
log: /home/oxidized/.config/oxidized/log
debug: true
threads: 30
timeout: 20
retries: 2
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 0.0.0.0:8888
vars: {}
groups:
  edgeos:
    username: username
    password: password
  adtranaos:
    username: username
    password: password
    vars: password
input:
  default: ssh, telnet
  debug: true
  ssh:
    secure: false
output:
  default: file
  file:
    directory: "/home/oxidized/.config/oxidized/configs"
source:
  default: http
  debug: true
  http:
    url: http://librenms.url/api/v0/oxidized
    map:
      name: hostname
      model: os
      group: group
      ip: ip
    headers:
      X-Auth-Token: 'Token_Here'
model_map:
  cisco: ios
  juniper: junos
  EDGE: edgeos
  ADTRAN: adtranaos

curl to LibreNMS API:
`    {
        "hostname": "ip_address",
        "os": "edgeos",
        "ip": "",
        "group": "edgeos"
    },
    {
        "hostname": "ip_address",
        "os": "adtran-aos",
        "ip": "",
        "group": "adtranaos"
    },`

The edgeos are being fed successfully and I'm seeing them on my Oxidized GUI but not the Adtran devices.

> ip_address on the API call are my devices' ip addresses

**Comment by wk** [comment]
An Adtran model for AOS (developed on Total Access) has been introduced in #1576
