### ISSUE TITLE
API Help

### ISSUE THREAD

**Issue by Rosiak** [ytti/oxidized#149]
Hi there,

How would the API call look if i wanted to ask for all the config versions, for a single device, and output to json?
And afterwards do a diff API call(And output to json, if that's possible)? 

Thx!

**Comment by ytti** [comment]
We don't support anything like this today. It could be implemented, and some of the diff stuff has been (which I was maybe less than thrilled).
None of this stuff can be output model agnostic, as say flat file output has no concept of diffs.

Personally I would just push the git repo to gitlab instance and have gitlab send emails on changes.

**Comment by Rosiak** [comment]
Right.

I'm just looking for a way to get a list of the stored configs, for a specific device.
Then when i have those titles/names/etc. I can fetch the specific configs through the API and do the diff myself in another system.

Or would you still recommend Gitlab for this part?

**Comment by ytti** [comment]
@FlorianDoublet did quite bit of work towards that stuff, but I don't think what you ask is possible now.

I would recommend gitlab, github or any other such service. But if there is user demand to implement this natively in oxidized, I'm not opposing it, strongly at least :)

**Comment by FlorianDoublet** [comment]
It's not possible now. So you want all the configs for one device in a json, and do a diff with it, why ?

**Comment by Rosiak** [comment]
@FlorianDoublet 
At the moment I'm looking at integrating Oxidized with other systems.
I want to be able to list the different config versions stored for that device(Say timestamp, version). And from that data generate links/API calls to fetch the specific configs. 

Much like the WEBUI does today, but being able to do this through the API.

Forget the diff part for now, since external systems will be able to do this when they are able to fetch the different configs from the API.

Here's some screenshots from the current UI of what I would like to be able to do through the API:
Fetch specific config version from device http://snag.gy/AonQ0.jpg

Get list of versions stored for a device:
http://snag.gy/fKVmi.jpg

Sorry for my rather bad explanation.

**Comment by FlorianDoublet** [comment]
I'm not sure to understand what you want exactly, but I think it's for the node "fw01" all the complete configuration for each version, right ?

**Comment by Rosiak** [comment]
I want a list of the config versions stored for a specific device.
And I want to be able to fetch the config for a specific version, from a device.

Makes sense?

**Comment by MrRJ45** [comment]
This is something that I also needed, so I have added this to oxidized-web here: ytti/oxidized-web@9cf03925ae3b2edcee377aa5c307a3037f7f8fe7

I've also added the author name and commit message to the output, and to the GUI.

I think this means we can close this issue?

**Comment by ytti** [comment]
Fixed by 9cf0392

thanks a bunch @MrRJ45
