### ISSUE TITLE
Issue pulling config from ASA

### ISSUE THREAD

**Issue by liudnaz** [ytti/oxidized#1491]
Hi, 
i have Cisco ASA 5516 in lab (running: Cisco Adaptive Security Appliance Software Version 9.6(4)12 ) and can't pull config from it. For some reason session is timing out. I tried to increase timeout to 120 but didn't helped me at all.
At the moment i suspect (i'm not that deep into programming yet) that maybe "terminal pager 0" is executed before going into enable mode or not executed at all and when any command with more output issued on device, it starts to page out output, hence sessions are timing out. Here's my error log from running "oxs 172.26.16.1 -v -d 'sho ver'" command on host
....
I, [2018-08-17T13:11:58.408402 #20223]  INFO -- : lib/oxidized/nodes.rb: Loaded 1 nodes
D, [2018-08-17T13:11:58.408654 #20223] DEBUG -- : AUTH METHODS::["none", "publickey", "password"]
D, [2018-08-17T13:11:58.408806 #20223] DEBUG -- : lib/oxidized/input/ssh.rb: Connecting to 172.26.16.1
D, [2018-08-17T13:11:58.553007 #20223] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^\r*([\w.@()-\/]+[#>]\s?)$/] at 172.26.16.1
D, [2018-08-17T13:11:59.356442 #20223] DEBUG -- : lib/oxidized/input/cli.rb: Running post_login commands at 172.26.16.1
D, [2018-08-17T13:11:59.356683 #20223] DEBUG -- : lib/oxidized/input/cli.rb: Running post_login command: "terminal pager 0", block: nil at 172.26.16.1
D, [2018-08-17T13:11:59.356801 #20223] DEBUG -- : lib/oxidized/input/ssh.rb terminal pager 0 @ 172.26.16.1 with expect: /^\r*([\w.@()-\/]+[#>]\s?)$/
D, [2018-08-17T13:11:59.357086 #20223] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^\r*([\w.@()-\/]+[#>]\s?)$/] at 172.26.16.1
D, [2018-08-17T13:11:59.759978 #20223] DEBUG -- : lib/oxidized/model/model.rb Executing sho ver
D, [2018-08-17T13:11:59.760222 #20223] DEBUG -- : lib/oxidized/input/ssh.rb sho ver @ 172.26.16.1 with expect: /^\r*([\w.@()-\/]+[#>]\s?)$/
D, [2018-08-17T13:11:59.760663 #20223] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^\r*([\w.@()-\/]+[#>]\s?)$/] at 172.26.16.1
execution expired
/var/lib/gems/2.3.0/gems/oxidized-0.24.0/lib/oxidized/input/ssh.rb:138:in `sleep': execution expired (Timeout::Error)
        from /var/lib/gems/2.3.0/gems/oxidized-0.24.0/lib/oxidized/input/ssh.rb:138:in `block (2 levels) in expect'
        from /var/lib/gems/2.3.0/gems/net-ssh-4.1.0/lib/net/ssh/connection/event_loop.rb:98:in `ev_preprocess'
        from /var/lib/gems/2.3.0/gems/net-ssh-4.1.0/lib/net/ssh/connection/event_loop.rb:27:in `process'
        from /var/lib/gems/2.3.0/gems/net-ssh-4.1.0/lib/net/ssh/connection/session.rb:216:in `process'
        from /var/lib/gems/2.3.0/gems/net-ssh-4.1.0/lib/net/ssh/connection/session.rb:178:in `block in loop'
        from /var/lib/gems/2.3.0/gems/net-ssh-4.1.0/lib/net/ssh/connection/session.rb:178:in `loop'
        from /var/lib/gems/2.3.0/gems/net-ssh-4.1.0/lib/net/ssh/connection/session.rb:178:in `loop'
        from /var/lib/gems/2.3.0/gems/oxidized-0.24.0/lib/oxidized/input/ssh.rb:137:in `block in expect'
        from /usr/lib/ruby/2.3.0/timeout.rb:106:in `timeout'
        from /var/lib/gems/2.3.0/gems/oxidized-0.24.0/lib/oxidized/input/ssh.rb:136:in `expect'
        from /var/lib/gems/2.3.0/gems/oxidized-0.24.0/lib/oxidized/input/ssh.rb:129:in `cmd_shell'
        from /var/lib/gems/2.3.0/gems/oxidized-0.24.0/lib/oxidized/input/ssh.rb:74:in `cmd'
        from /var/lib/gems/2.3.0/gems/oxidized-0.24.0/lib/oxidized/model/model.rb:103:in `cmd'
        from /var/lib/gems/2.3.0/gems/oxidized-script-0.5.1/lib/oxidized/script/script.rb:23:in `cmd'
        from /var/lib/gems/2.3.0/gems/oxidized-script-0.5.1/lib/oxidized/script/cli.rb:41:in `run'
        from /var/lib/gems/2.3.0/gems/oxidized-script-0.5.1/bin/oxs:5:in `<top (required)>'
        from /usr/local/bin/oxs:23:in `load'
        from /usr/local/bin/oxs:23:in `<main>'

here's output of crash log:

undefined method `join' for nil:NilClass [NoMethodError]
--------------------------------------------------
/var/lib/gems/2.3.0/gems/oxidized-0.24.0/lib/oxidized/model/asa.rb:60:in `block in single_context'
/var/lib/gems/2.3.0/gems/oxidized-0.24.0/lib/oxidized/model/model.rb:114:in `instance_exec'
/var/lib/gems/2.3.0/gems/oxidized-0.24.0/lib/oxidized/model/model.rb:114:in `cmd'
/var/lib/gems/2.3.0/gems/oxidized-0.24.0/lib/oxidized/model/asa.rb:59:in `single_context'
/var/lib/gems/2.3.0/gems/oxidized-0.24.0/lib/oxidized/model/asa.rb:42:in `block in <class:ASA>'
/var/lib/gems/2.3.0/gems/oxidized-0.24.0/lib/oxidized/model/model.rb:164:in `instance_eval'
/var/lib/gems/2.3.0/gems/oxidized-0.24.0/lib/oxidized/model/model.rb:164:in `block in get'
/var/lib/gems/2.3.0/gems/oxidized-0.24.0/lib/oxidized/model/model.rb:163:in `each'
/var/lib/gems/2.3.0/gems/oxidized-0.24.0/lib/oxidized/model/model.rb:163:in `get'
/var/lib/gems/2.3.0/gems/oxidized-0.24.0/lib/oxidized/input/cli.rb:14:in `get'
/var/lib/gems/2.3.0/gems/oxidized-0.24.0/lib/oxidized/node.rb:66:in `run_input'
/var/lib/gems/2.3.0/gems/oxidized-0.24.0/lib/oxidized/node.rb:43:in `block in run'
/var/lib/gems/2.3.0/gems/oxidized-0.24.0/lib/oxidized/node.rb:38:in `each'
/var/lib/gems/2.3.0/gems/oxidized-0.24.0/lib/oxidized/node.rb:38:in `run'
/var/lib/gems/2.3.0/gems/oxidized-0.24.0/lib/oxidized/job.rb:9:in `block in initialize'

**Comment by liudnaz** [comment]
Small update:
"oxs 172.16.18.1 'sho inve'" seems to be always working (so far) and returning output, but not other commands.

**Comment by laf** [comment]
What does the devices prompt look like?

**Comment by liudnaz** [comment]
hi, here's my login sequence

testlab/pri/act> ena
Password: *****
testlab/pri/act#

**Comment by laf** [comment]
Prompt is fine.

I'd turn on debug and pastebin the output, it still looks like it's getting to a point of not being able to work out the prompt.

**Comment by liudnaz** [comment]
Strange thing is that for different commands i'm running via oxs i'm getting different errors in debug output. see bellow. 

the one bellow works just fine, and i'm getting inventory:
oxs 172.16.18.1 -d 'sh inv'
 
and those two are failing, as probably rest of commands i've tried
 oxs 172.16.18.1 -d 'sh ver' 

 --- skipped ---
D, [2018-08-20T09:20:07.008483 #23718] DEBUG -- : lib/oxidized/model/model.rb Executing sh ip addr
D, [2018-08-20T09:20:07.008728 #23718] DEBUG -- : lib/oxidized/input/ssh.rb sh ip addr @ 172.16.18.1 with expect: /^\r*([\w.@()-\/]+[#>]\s?)$/
D, [2018-08-20T09:20:07.008953 #23718] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^\r*([\w.@()-\/]+[#>]\s?)$/] at 172.16.18.1
                           ^
ERROR: % Invalid input detected at '^' marker.


 oxs 172.16.18.1 -d 'sh ver'
 
 --- skipped ---
D, [2018-08-20T09:21:26.887938 #23723] DEBUG -- : lib/oxidized/model/model.rb Executing sh ver
D, [2018-08-20T09:21:26.888184 #23723] DEBUG -- : lib/oxidized/input/ssh.rb sh ver @ 172.16.18.1 with expect: /^\r*([\w.@()-\/]+[#>]\s?)$/
D, [2018-08-20T09:21:26.888445 #23723] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^\r*([\w.@()-\/]+[#>]\s?)$/] at 172.16.18.1
execution expired
/var/lib/gems/2.3.0/gems/oxidized-0.24.0/lib/oxidized/input/ssh.rb:138:in `sleep': execution expired (Timeout::Error)
        from /var/lib/gems/2.3.0/gems/oxidized-0.24.0/lib/oxidized/input/ssh.rb:138:in `block (2 levels) in expect'
        from /var/lib/gems/2.3.0/gems/net-ssh-4.1.0/lib/net/ssh/connection/event_loop.rb:98:in `ev_preprocess'
        from /var/lib/gems/2.3.0/gems/net-ssh-4.1.0/lib/net/ssh/connection/event_loop.rb:27:in `process'
        from /var/lib/gems/2.3.0/gems/net-ssh-4.1.0/lib/net/ssh/connection/session.rb:216:in `process'
        from /var/lib/gems/2.3.0/gems/net-ssh-4.1.0/lib/net/ssh/connection/session.rb:178:in `block in loop'
        from /var/lib/gems/2.3.0/gems/net-ssh-4.1.0/lib/net/ssh/connection/session.rb:178:in `loop'
        from /var/lib/gems/2.3.0/gems/net-ssh-4.1.0/lib/net/ssh/connection/session.rb:178:in `loop'
        from /var/lib/gems/2.3.0/gems/oxidized-0.24.0/lib/oxidized/input/ssh.rb:137:in `block in expect'
        from /usr/lib/ruby/2.3.0/timeout.rb:106:in `timeout'
        from /var/lib/gems/2.3.0/gems/oxidized-0.24.0/lib/oxidized/input/ssh.rb:136:in `expect'
        from /var/lib/gems/2.3.0/gems/oxidized-0.24.0/lib/oxidized/input/ssh.rb:129:in `cmd_shell'
        from /var/lib/gems/2.3.0/gems/oxidized-0.24.0/lib/oxidized/input/ssh.rb:74:in `cmd'
        from /var/lib/gems/2.3.0/gems/oxidized-0.24.0/lib/oxidized/model/model.rb:103:in `cmd'
        from /var/lib/gems/2.3.0/gems/oxidized-script-0.5.1/lib/oxidized/script/script.rb:23:in `cmd'
        from /var/lib/gems/2.3.0/gems/oxidized-script-0.5.1/lib/oxidized/script/cli.rb:41:in `run'
        from /var/lib/gems/2.3.0/gems/oxidized-script-0.5.1/bin/oxs:5:in `<top (required)>'
        from /usr/local/bin/oxs:23:in `load'
        from /usr/local/bin/oxs:23:in `<main>'

p.s. sorry if output is to long, not 100% sure how to use pastebin yet. and if you know specific command you want me to run please let me know.

**Comment by liudnaz** [comment]
issue resolved. 
needed to add enable secret in configuration file under vars: section, otherwise it was not going into enable mode, hence commands were failing
...
vars:
  enable: enAbleVerySecret:)
...
