### ISSUE TITLE
Web UI Groups: by location

### ISSUE THREAD

**Issue by rygumcmxci** [ytti/oxidized#1492]
Hi I wanted to see if there was any way to categorize devices by location using the "Group" tab in the web interface. 

I was looking around and wasn't able to find any documentation that addressed this. I have 13 sites that I will be running config backups on and would like to be able to sort them by location. 

![image](https://user-images.githubusercontent.com/25889428/44490692-db61a880-a613-11e8-8210-a5afec1f8016.png)

Thanks

**Comment by mattie47** [comment]
Yeah. 

For reference my modified librenms config.php file:

```
// Match SNMP location and assign a group for within Oxidized
$config['oxidized']['group']['location'][] = array('regex' => '/loc1/', 'group' => 'campus');
$config['oxidized']['group']['location'][] = array('regex' => '/loc2/', 'group' => 'iris');
$config['oxidized']['group']['location'][] = array('regex' => '/loc3/', 'group' => 'hub');
$config['oxidized']['group']['location'][] = array('regex' => '/Network Operations Center/', 'group' => 'noc');
$config['oxidized']['group']['location'][] = array('regex' => '/TstNet/', 'group' => 'testnet');
$config['oxidized']['group']['location'][] = array('regex' => '/iot/', 'group' => 'iot');
```

This uses SNMP Location and matches on a string within the location, then puts the devices in a specific oxidized group

**Comment by rygumcmxci** [comment]
Thanks a bunch, Matt. I will give this a try tomorrow when I get into the office. Hopefully I can get it working without issue.

**Comment by mattie47** [comment]
Sorry there's a little bit more to it than just that, but the libreNMS docs explains things pretty well:

https://docs.librenms.org/#Extensions/Oxidized/

**Comment by rygumcmxci** [comment]
Ok, it looks like I was able to get the group thing situated, but the documentation in regards to  LibreNMS feeding Oxidized is kind of confusing. I ran through a couple of different configurations, tested them, and none of them worked. 

What exactly needs to be done to get this working?

**Comment by mattie47** [comment]
>  but the documentation in regards to LibreNMS feeding Oxidized is kind of confusing.

Yeah - I do remember thinking the same when I set it up.

Bear in mind (and perhaps this isn't documented), ensure you've restarted oxidized after setting up the API connections between the two.

Have you got libreNMS talking to oxidized?

1. Create the API token

![image](https://user-images.githubusercontent.com/4696925/44557562-2d7d0800-a793-11e8-9536-c816c448ac04.png)

2. Point LibreNMS at Oxidized

Note: My URL will probably be different from yours. I'm using oxidized with Nginx sitting in front of it. If you haven't configured a reverse proxy such as nginx, you'll probably be something like `http://oxidizedaddress:8888`

![image](https://user-images.githubusercontent.com/4696925/44557599-60bf9700-a793-11e8-839b-a8f0f81e8601.png)

3. Configure Oxidized to use LibreNMS API token

This is what I have in my oxidized config file:

```
source:
   default: http
   debug: true
   http:
     url: http://librenms.<domain>/api/v0/oxidized
     map:
      name: hostname
      model: os
      group: group
     headers:
      X-Auth-Token: '83af4c205MAGICTOKENac'
```

Hope that helps.

**Comment by rygumcmxci** [comment]
Awesome, thanks again! This is literally the last part I need to iron out before I go live and push this to production. I'll take another jab at this tomorrow when I get into the office, hopefully I'll be able to get this setup by the end of the day tomorrow.

**Comment by rygumcmxci** [comment]
My Setup: 
Centos 7 physical server: 
- LibreNMS
- Oxidized

I was already to get Oxidized integrated with LibreNMS, but can't seem to get it right with pushing new nodes from LibreNMS > Oxidized. 

When I made the change the Oxidized web interface becomes unavailable. 

Oxidized configuration file: (which does not work)

https://pastebin.com/gv8LnBTK

Any suggestions or help?

**Comment by mattie47** [comment]
Whoops!

Sorry I just realised I left out one crucial step.

You need to configure device groups within libreNMS first, then the config.php configured groups will work.

See the attached webm video (unzip it):
 
[LibreNMS.zip](https://github.com/ytti/oxidized/files/2321957/LibreNMS.zip)


The docs also explains this: https://docs.librenms.org/#Extensions/Device-Groups/

If you need other help with Oxidized, there's also the oxidized forum on https://community.librenms.org/c/help/oxidized

Thanks,

matt
