### ISSUE TITLE
Cisco iOS - only executing 'show vtp status' not 'show running-config'

### ISSUE THREAD

**Issue by ndom91** [ytti/oxidized#1494]
Hi All,

So I have everything setup and running well, except my cisco configs are only the output of the `show vtp status` command. 

According to [https://github.com/ytti/oxidized/blob/master/lib/oxidized/model/ios.rb](https://github.com/ytti/oxidized/blob/master/lib/oxidized/model/ios.rb) it should also execute `show running-config` which is the config output I really want, but it does not seem to output that. 

I am outputting to a private gitlab repo, whcih is working fine.

You can find my config at my pastebin here: [https://paste.iamnico.xyz/3oERWS5Gzi](https://paste.iamnico.xyz/3oERWS5Gzi)

Any idea what I can do to force `show running-config`?

Thanks!

**Comment by ytti** [comment]
Have you specified enable password? Is it empty string? If so, change that to ```false```

**Comment by ndom91** [comment]
Yes I have a default enable password (it's the same on all devices) in the config. 

If I set `:enablepass` in the router.db - does that try to use the string "enablepass" as password or simply apply the default pw from config?

**Comment by ytti** [comment]
It simply uses the password you configured as your enable password.

When you write ```enable``` on your Cisco device, what happens? Does it query for a password or return immediately to a prompt?

**Comment by ndom91** [comment]
Right, but which string does it use as password? The one written after the hostname, username, password, etc. in the router.db file? Because in there I simply have written `:enablepass` at the end, instead of the actual password. As you can see in my config above, the enable pass is at position 5:


```bash
map:
      name: 0
      model: 1
      username: 2
      password: 3
    vars_map:
      enable: 4
```

On the ciscos themselves, after I type enable and hit enter it asks for a password, and then after inputting the correct password, the prompt changes.

**Comment by ndom91** [comment]
Okay nevermind, in the `router.db` source DB I needed to actually enter the cisco "enable" pw. Now it works :+1:
