### ISSUE TITLE
Issues pulling configuration from D-Link DGS-1100-16/ME

### ISSUE THREAD

**Issue by ravenich** [ytti/oxidized#1495]
Oxidized can't pull configuration from D-Link DGS-1100-16/ME.
**oxidized.debug.log:** - https://pastebin.com/t2gg9270
config:
`---
username: adm
password: P@ssword
model: dlink
resolve_dns: false
interval: 3600
use_syslog: false
log: /home/oxidized/.config/oxidized/log
debug: true
threads: 30
timeout: 180
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 127.0.0.1:8888
next_adds_job: false
vars: {}
groups: {}
models: {}
pid: "/home/oxidized/.config/oxidized/pid"
input:
  default: telnet
  ssh:
   secure: false
output:
  default: git
  git:
   user: Oxidized
   email: oxidized@oxidized.com
   repo: "~/.config/oxidized/oxidized.git"
source:
  default: csv
  csv:
    file: "~/.config/oxidized/router.db"
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
      username: 2
      password: 3
    vars_map:
      enable: 4
model_map:
  cisco: ios
  juniper: junos`

telnet 192.168.101.2:
`Trying 192.168.101.2...
Connected to 192.168.101.2.
Escape character is '^]'.

UserName:adm
PassWord:********
DGS-1100-16/ME:admin#logout
Command : logout

Success.

**********
* Logout *
**********
Connection closed by foreign host.`

**Comment by ravenich** [comment]
Dump from wireshark: 
1 - telnet 192.168.101.2
![1](https://user-images.githubusercontent.com/10392669/44570920-0967f980-a788-11e8-9490-58be2bc4b69c.png)
2 - oxidized
![2](https://user-images.githubusercontent.com/10392669/44570928-108f0780-a788-11e8-9ad4-33a5db4f8add.png)

**Comment by ravenich** [comment]
dump from oxidized telnet connection - https://ufile.io/p4u83

**Comment by wk** [comment]
Possible duplicate of #1541, could you see if #1542 resolves the issue for you, and if you can reproduce it via ssh (with #1542 applied)?

**Comment by ravenich** [comment]
#1542 doesn't resolve my issue. Logs are the same.
Unfortunately this switch doesn't have a SSH.

**Comment by wk** [comment]
Thanks for testing! Can you confirm if you are testing this on 0.24.0 or the latest master of Oxidized?

Additionally, since the file hoster you have uploaded the pcap to has since expired the file, could you take a new pcap with #1542 applied and include it in this issue?

**Comment by ravenich** [comment]
I testing #1542 on 0.24.0. Just changed the prompt line in the /var/lib/gems/2.3.0/gems/oxidized-0.24.0/lib/oxidized/model/dlink.rb file. 
Pcap file: https://ufile.io/lw1dv

If it nessecary i can test on the latest master.

**Comment by wk** [comment]
Thanks for the detal. Now that I've had a chance to look through the pcap, this indeed seems to be some lower level issue with telnet, not an issue with the model. 

This is *not* a duplicate of #1541 (although if telnet would have worked, that would have been the next bug you'd hit).

Could you append the output of 'ruby -v' and 'gem list net-telnet' to this issue? Does this instance of oxidized successfully collect configuration over telnet from any other devices, and if not, would that be something you'd be in a position to try?

Could you also specify which firmware version of this device is on the other side?
