### ISSUE TITLE
oxidized: /usr/bin/env: ruby_executable_hooks: No such file or directory

### ISSUE THREAD

**Issue by jvrrn** [ytti/oxidized#1499]
Hello,

I have installed rvm & oxidized, I am able to run oxidized manually from the oxidized user account,
however the service fails to start:

systemd: Started Oxidized - Network Device Configuration Backup Tool.
systemd: Starting Oxidized - Network Device Configuration Backup Tool...
systemd: oxidized.service: main process exited, code=exited, status=127/n/a
oxidized: /usr/bin/env: ruby_executable_hooks: No such file or directory
systemd: Unit oxidized.service entered failed state.
systemd: oxidized.service failed.

I am unsure what the problem is

Any ideas?

**Comment by GitStoph** [comment]
I'm having this issue as well. Did you ever get it resolved?

**Comment by jvrrn** [comment]
yes
/usr/lib/systemd/system/oxidized.service   needs the correct environment variables

I went with SCL inthe end, so your may be different

/usr/lib/systemd/system/oxidized.service:
[Unit]
Description=Oxidized - Network Device Configuration Backup Tool
After=network-online.target multi-user.target
Wants=network-online.target

[Service]
Environment="PATH=/opt/rh/rh-ruby23/root/usr/local/bin:/opt/rh/rh-ruby23/root/usr/bin"
Environment="LD_LIBRARY_PATH=/opt/rh/rh-ruby23/root/usr/local/lib64:/opt/rh/rh-ruby23/root/usr/lib64"
Environment="MANPATH=/opt/rh/rh-ruby23/root/usr/local/share/man:/opt/rh/rh-ruby23/root/usr/share/man"
Environment="PKG_CONFIG_PATH=/opt/rh/rh-ruby23/root/usr/local/lib64/pkgconfig:/opt/rh/rh-ruby23/root/usr/lib64/pkgconfig"
Environment="XDG_DATA_DIRS=/opt/rh/rh-ruby23/root/usr/local/share:/opt/rh/rh-ruby23/root/usr/share"
ExecStart=/opt/rh/rh-ruby23/root/usr/local/bin/oxidized
User=oxidized
KillSignal=SIGKILL
[Install]
WantedBy=multi-user.target
