### ISSUE TITLE
Problem with Alcatel OmniStack LS 6248P connection telnet

### ISSUE THREAD

**Issue by rharo1** [ytti/oxidized#1502]
Hello guys, please i need some help with a new model... i need to backup a config from a Alcatel OmniStack LS 6248P, my switch just connect through telnet and ask for username and password... i create a new model omnistack.rb and change the prompt and some commands but it´s look like it´s not input the username/password correctly, i see at the switch the log said to me that oxidized is trying to connect with username "terminal datadump" (post_login).

**Output from telnet connection:**
[oxidized@sr486 ~]$ telnet 10.0.64.20
Trying 10.0.64.20...
Connected to 10.0.64.20.
Escape character is '^]'.

User Name:<user>
Password:********

SW8088#

**The new model call omniswitch.rb**
``class OMNISWITCH < Oxidized::Model
  prompt /.*/
  comment  '! '

  cmd 'show version' do |cfg|
    comment cfg
  end

  cmd 'show system' do |cfg|
    comment cfg
  end

  cmd 'show running-config' do |cfg|
    cfg
  end

  cfg :telnet do
    username /^User Name:/
    password /^Password:/
  end

  cfg :telnet, :ssh do
    post_login 'terminal datadump'
    pre_logout 'exit'
  end
end
``

**Log message from switch:**
31-Aug-2018 14:36:59 :%AAA-W-REJECT: New telnet connection for user exit, source <IP-OXIDIZED> destination <IP-SWITCH>  REJECTED

31-Aug-2018 14:36:59 :%AAA-W-REJECT: New telnet connection for user show system, source <IP-OXIDIZED>  destination <IP-SWITCH>   REJECTED

31-Aug-2018 14:36:59 :%AAA-W-REJECT: New telnet connection for user terminal datadump, source <IP-OXIDIZED>  destination <IP-SWITCH>  REJECTED

**Comment by wk** [comment]
With such a broad `prompt` match, Oxidized will start executing commands the moment the first character from the device is seen (as the prompt is, essentially, any character at all). 

Try constraining the prompt or omitting it completely, as the default seems to match your use case:

```ruby
irb(main):002:0> "SW8088#".match /^([\w.@-]+[#>]\s?)$/
=> #<MatchData "SW8088#" 1:"SW8088#">
```
