### ISSUE TITLE
Clean/fresh install on Debian: only partial Cisco configurations received

### ISSUE THREAD

**Issue by mwatkins-911** [ytti/oxidized#1508]
admin@oxidized:~$ cat /etc/debian_version 
9.5

cisco@oxidized:~$ cat router.db
172.20.20.81:ios
172.20.20.20:ios

cisco@oxidized:~$ cat config
---
username: configuser
password: ********
vars: {}
model: cisco
resolve_dns: true
interval: 3600
use_syslog: false
debug: true
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: false
next_adds_job: false
groups: {}
models: {}
pid: "/home/cisco/.config/oxidized/pid"
stats:
  history_size: 10
input:
  default: ssh, telnet
  debug: false
  ssh:
    secure: false
  ftp:
    passive: true
  utf8_encoded: true
output:
  file:
    directory: "/home/cisco/configs"
source:
  default: csv
  csv:
    file: "/home/cisco/router.db"
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
    gpg: false
model_map:
  cisco: ios
  juniper: junos

cisco@oxidized:~$ oxidized 
I, [2018-09-07T08:44:41.606990 #14488]  INFO -- : Oxidized starting, running as pid 14488
I, [2018-09-07T08:44:41.608009 #14488]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
D, [2018-09-07T08:44:41.608237 #14488] DEBUG -- : resolving DNS for 172.20.20.81...
D, [2018-09-07T08:44:41.608379 #14488] DEBUG -- : IPADDR 
D, [2018-09-07T08:44:41.608739 #14488] DEBUG -- : node.rb: resolving node key 'model', with passed global value of '' and node value 'ios'
D, [2018-09-07T08:44:41.608872 #14488] DEBUG -- : node.rb: setting node key 'model' to value 'cisco' from global
D, [2018-09-07T08:44:41.608988 #14488] DEBUG -- : node.rb: returning node key 'model' with value 'ios'
D, [2018-09-07T08:44:41.609101 #14488] DEBUG -- : lib/oxidized/node.rb: Loading model "ios"
D, [2018-09-07T08:44:41.610820 #14488] DEBUG -- : lib/oxidized/model/model.rb Added all to the commands list
D, [2018-09-07T08:44:41.610949 #14488] DEBUG -- : lib/oxidized/model/model.rb Added secret to the commands list
D, [2018-09-07T08:44:41.611079 #14488] DEBUG -- : lib/oxidized/model/model.rb Added show version to the commands list
D, [2018-09-07T08:44:41.611195 #14488] DEBUG -- : lib/oxidized/model/model.rb Added show vtp status to the commands list
D, [2018-09-07T08:44:41.611304 #14488] DEBUG -- : lib/oxidized/model/model.rb Added show inventory to the commands list
D, [2018-09-07T08:44:41.611418 #14488] DEBUG -- : lib/oxidized/model/model.rb Added show running-config to the commands list
D, [2018-09-07T08:44:41.611738 #14488] DEBUG -- : node.rb: resolving node key 'input', with passed global value of 'ssh, telnet' and node value ''
D, [2018-09-07T08:44:41.611859 #14488] DEBUG -- : node.rb: returning node key 'input' with value 'ssh, telnet'
D, [2018-09-07T08:44:41.706841 #14488] DEBUG -- : node.rb: resolving node key 'output', with passed global value of 'file' and node value ''
D, [2018-09-07T08:44:41.707215 #14488] DEBUG -- : node.rb: returning node key 'output' with value 'file'
D, [2018-09-07T08:44:41.708823 #14488] DEBUG -- : node.rb: resolving node key 'username', with passed global value of '' and node value ''
D, [2018-09-07T08:44:41.708954 #14488] DEBUG -- : node.rb: setting node key 'username' to value 'mwatkins' from global
D, [2018-09-07T08:44:41.709086 #14488] DEBUG -- : node.rb: returning node key 'username' with value 'mwatkins'
D, [2018-09-07T08:44:41.709191 #14488] DEBUG -- : node.rb: resolving node key 'password', with passed global value of '' and node value ''
D, [2018-09-07T08:44:41.709307 #14488] DEBUG -- : node.rb: setting node key 'password' to value 'Welcome1' from global
D, [2018-09-07T08:44:41.709417 #14488] DEBUG -- : node.rb: returning node key 'password' with value 'Welcome1'
D, [2018-09-07T08:44:41.709610 #14488] DEBUG -- : resolving DNS for 172.20.20.20...
D, [2018-09-07T08:44:41.709800 #14488] DEBUG -- : IPADDR 
D, [2018-09-07T08:44:41.709989 #14488] DEBUG -- : node.rb: resolving node key 'model', with passed global value of '' and node value 'ios'
D, [2018-09-07T08:44:41.710102 #14488] DEBUG -- : node.rb: setting node key 'model' to value 'cisco' from global
D, [2018-09-07T08:44:41.710224 #14488] DEBUG -- : node.rb: returning node key 'model' with value 'ios'
D, [2018-09-07T08:44:41.710357 #14488] DEBUG -- : node.rb: resolving node key 'input', with passed global value of 'ssh, telnet' and node value ''
D, [2018-09-07T08:44:41.710518 #14488] DEBUG -- : node.rb: returning node key 'input' with value 'ssh, telnet'
D, [2018-09-07T08:44:41.711006 #14488] DEBUG -- : node.rb: resolving node key 'output', with passed global value of 'file' and node value ''
D, [2018-09-07T08:44:41.711149 #14488] DEBUG -- : node.rb: returning node key 'output' with value 'file'
D, [2018-09-07T08:44:41.711256 #14488] DEBUG -- : node.rb: resolving node key 'username', with passed global value of '' and node value ''
D, [2018-09-07T08:44:41.711379 #14488] DEBUG -- : node.rb: setting node key 'username' to value 'mwatkins' from global
D, [2018-09-07T08:44:41.711518 #14488] DEBUG -- : node.rb: returning node key 'username' with value 'mwatkins'
D, [2018-09-07T08:44:41.711619 #14488] DEBUG -- : node.rb: resolving node key 'password', with passed global value of '' and node value ''
D, [2018-09-07T08:44:41.711771 #14488] DEBUG -- : node.rb: setting node key 'password' to value 'Welcome1' from global
D, [2018-09-07T08:44:41.711888 #14488] DEBUG -- : node.rb: returning node key 'password' with value 'Welcome1'
I, [2018-09-07T08:44:41.712054 #14488]  INFO -- : lib/oxidized/nodes.rb: Loaded 2 nodes
D, [2018-09-07T08:44:41.712214 #14488] DEBUG -- : lib/oxidized/core.rb: Starting the worker...
D, [2018-09-07T08:44:41.712318 #14488] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 0 of 2
D, [2018-09-07T08:44:41.712557 #14488] DEBUG -- : lib/oxidized/worker.rb: Added /172.20.20.81 to the job queue
D, [2018-09-07T08:44:41.712671 #14488] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2018-09-07T08:44:41.712862 #14488] DEBUG -- : lib/oxidized/job.rb: Starting fetching process for 172.20.20.81 at 2018-09-07 08:44:41 UTC
D, [2018-09-07T08:44:41.713063 #14488] DEBUG -- : lib/oxidized/input/ssh.rb: Connecting to 172.20.20.81
D, [2018-09-07T08:44:41.713224 #14488] DEBUG -- : AUTH METHODS::["none", "publickey", "password"]
D, [2018-09-07T08:44:42.511331 #14488] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^([\w.@()-]+[#>]\s?)$/] at 172.20.20.81
D, [2018-09-07T08:44:42.712987 #14488] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2018-09-07T08:44:43.314400 #14488] DEBUG -- : lib/oxidized/input/cli.rb: Running post_login commands at 172.20.20.81
D, [2018-09-07T08:44:43.314676 #14488] DEBUG -- : lib/oxidized/input/cli.rb: Running post_login command: nil, block: #<Proc:0x0055a8d9fa4d80@/var/lib/gems/2.3.0/gems/oxidized-0.24.0/lib/oxidized/model/ios.rb:135> at 172.20.20.81
D, [2018-09-07T08:44:43.314820 #14488] DEBUG -- : lib/oxidized/input/cli.rb: Running post_login command: "terminal length 0", block: nil at 172.20.20.81
D, [2018-09-07T08:44:43.314928 #14488] DEBUG -- : lib/oxidized/input/ssh.rb terminal length 0 @ 172.20.20.81 with expect: /^([\w.@()-]+[#>]\s?)$/
D, [2018-09-07T08:44:43.315176 #14488] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^([\w.@()-]+[#>]\s?)$/] at 172.20.20.81
D, [2018-09-07T08:44:43.713309 #14488] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2018-09-07T08:44:43.717066 #14488] DEBUG -- : lib/oxidized/input/cli.rb: Running post_login command: "terminal width 0", block: nil at 172.20.20.81
D, [2018-09-07T08:44:43.717189 #14488] DEBUG -- : lib/oxidized/input/ssh.rb terminal width 0 @ 172.20.20.81 with expect: /^([\w.@()-]+[#>]\s?)$/
D, [2018-09-07T08:44:43.717426 #14488] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^([\w.@()-]+[#>]\s?)$/] at 172.20.20.81
D, [2018-09-07T08:44:44.119298 #14488] DEBUG -- : lib/oxidized/model/model.rb Collecting commands' outputs
D, [2018-09-07T08:44:44.119468 #14488] DEBUG -- : lib/oxidized/model/model.rb Executing show version
D, [2018-09-07T08:44:44.119599 #14488] DEBUG -- : lib/oxidized/input/ssh.rb show version @ 172.20.20.81 with expect: /^([\w.@()-]+[#>]\s?)$/
D, [2018-09-07T08:44:44.119817 #14488] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^([\w.@()-]+[#>]\s?)$/] at 172.20.20.81
D, [2018-09-07T08:44:44.523382 #14488] DEBUG -- : lib/oxidized/model/model.rb Executing show vtp status
D, [2018-09-07T08:44:44.523577 #14488] DEBUG -- : lib/oxidized/input/ssh.rb show vtp status @ 172.20.20.81 with expect: /^([\w.@()-]+[#>]\s?)$/
D, [2018-09-07T08:44:44.523787 #14488] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^([\w.@()-]+[#>]\s?)$/] at 172.20.20.81
D, [2018-09-07T08:44:44.713603 #14488] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2018-09-07T08:44:44.925948 #14488] DEBUG -- : lib/oxidized/model/model.rb Executing show inventory
D, [2018-09-07T08:44:44.926116 #14488] DEBUG -- : lib/oxidized/input/ssh.rb show inventory @ 172.20.20.81 with expect: /^([\w.@()-]+[#>]\s?)$/
D, [2018-09-07T08:44:44.926322 #14488] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^([\w.@()-]+[#>]\s?)$/] at 172.20.20.81
D, [2018-09-07T08:44:45.328253 #14488] DEBUG -- : lib/oxidized/model/model.rb Executing show running-config
D, [2018-09-07T08:44:45.328424 #14488] DEBUG -- : lib/oxidized/input/ssh.rb show running-config @ 172.20.20.81 with expect: /^([\w.@()-]+[#>]\s?)$/
D, [2018-09-07T08:44:45.328653 #14488] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^([\w.@()-]+[#>]\s?)$/] at 172.20.20.81
D, [2018-09-07T08:44:45.713927 #14488] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2018-09-07T08:44:45.730771 #14488] DEBUG -- : lib/oxidized/input/cli.rb Running pre_logout commands at 172.20.20.81
D, [2018-09-07T08:44:45.730899 #14488] DEBUG -- : lib/oxidized/input/ssh.rb exit @ 172.20.20.81 with expect: nil
D, [2018-09-07T08:44:45.862047 #14488] DEBUG -- : lib/oxidized/node.rb: Oxidized::SSH ran for 172.20.20.81 successfully
D, [2018-09-07T08:44:45.862210 #14488] DEBUG -- : lib/oxidized/job.rb: Config fetched for 172.20.20.81 at 2018-09-07 08:44:45 UTC
I, [2018-09-07T08:44:46.715264 #14488]  INFO -- : Configuration updated for /172.20.20.81
D, [2018-09-07T08:44:46.715334 #14488] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 1 of 2
D, [2018-09-07T08:44:46.715446 #14488] DEBUG -- : lib/oxidized/worker.rb: Added /172.20.20.20 to the job queue
D, [2018-09-07T08:44:46.715468 #14488] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2018-09-07T08:44:46.715601 #14488] DEBUG -- : lib/oxidized/job.rb: Starting fetching process for 172.20.20.20 at 2018-09-07 08:44:46 UTC
D, [2018-09-07T08:44:46.715780 #14488] DEBUG -- : lib/oxidized/input/ssh.rb: Connecting to 172.20.20.20
D, [2018-09-07T08:44:46.715936 #14488] DEBUG -- : AUTH METHODS::["none", "publickey", "password"]
D, [2018-09-07T08:44:47.650904 #14488] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^([\w.@()-]+[#>]\s?)$/] at 172.20.20.20
D, [2018-09-07T08:44:47.715668 #14488] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2018-09-07T08:44:48.453797 #14488] DEBUG -- : lib/oxidized/input/cli.rb: Running post_login commands at 172.20.20.20
D, [2018-09-07T08:44:48.453999 #14488] DEBUG -- : lib/oxidized/input/cli.rb: Running post_login command: nil, block: #<Proc:0x0055a8d9f4f1a0@/var/lib/gems/2.3.0/gems/oxidized-0.24.0/lib/oxidized/model/ios.rb:135> at 172.20.20.20
D, [2018-09-07T08:44:48.454145 #14488] DEBUG -- : lib/oxidized/input/cli.rb: Running post_login command: "terminal length 0", block: nil at 172.20.20.20
D, [2018-09-07T08:44:48.454270 #14488] DEBUG -- : lib/oxidized/input/ssh.rb terminal length 0 @ 172.20.20.20 with expect: /^([\w.@()-]+[#>]\s?)$/
D, [2018-09-07T08:44:48.454565 #14488] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^([\w.@()-]+[#>]\s?)$/] at 172.20.20.20
D, [2018-09-07T08:44:48.715936 #14488] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2018-09-07T08:44:48.856457 #14488] DEBUG -- : lib/oxidized/input/cli.rb: Running post_login command: "terminal width 0", block: nil at 172.20.20.20
D, [2018-09-07T08:44:48.856607 #14488] DEBUG -- : lib/oxidized/input/ssh.rb terminal width 0 @ 172.20.20.20 with expect: /^([\w.@()-]+[#>]\s?)$/
D, [2018-09-07T08:44:48.856816 #14488] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^([\w.@()-]+[#>]\s?)$/] at 172.20.20.20
D, [2018-09-07T08:44:49.258989 #14488] DEBUG -- : lib/oxidized/model/model.rb Collecting commands' outputs
D, [2018-09-07T08:44:49.259181 #14488] DEBUG -- : lib/oxidized/model/model.rb Executing show version
D, [2018-09-07T08:44:49.259293 #14488] DEBUG -- : lib/oxidized/input/ssh.rb show version @ 172.20.20.20 with expect: /^([\w.@()-]+[#>]\s?)$/
D, [2018-09-07T08:44:49.259481 #14488] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^([\w.@()-]+[#>]\s?)$/] at 172.20.20.20
D, [2018-09-07T08:44:49.716216 #14488] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2018-09-07T08:44:49.887457 #14488] DEBUG -- : lib/oxidized/model/model.rb Executing show vtp status
D, [2018-09-07T08:44:49.887673 #14488] DEBUG -- : lib/oxidized/input/ssh.rb show vtp status @ 172.20.20.20 with expect: /^([\w.@()-]+[#>]\s?)$/
D, [2018-09-07T08:44:49.887886 #14488] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^([\w.@()-]+[#>]\s?)$/] at 172.20.20.20
D, [2018-09-07T08:44:50.290156 #14488] DEBUG -- : lib/oxidized/model/model.rb Executing show inventory
D, [2018-09-07T08:44:50.290377 #14488] DEBUG -- : lib/oxidized/input/ssh.rb show inventory @ 172.20.20.20 with expect: /^([\w.@()-]+[#>]\s?)$/
D, [2018-09-07T08:44:50.290622 #14488] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^([\w.@()-]+[#>]\s?)$/] at 172.20.20.20
D, [2018-09-07T08:44:50.716480 #14488] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2018-09-07T08:44:50.893440 #14488] DEBUG -- : lib/oxidized/model/model.rb Executing show running-config
D, [2018-09-07T08:44:50.893628 #14488] DEBUG -- : lib/oxidized/input/ssh.rb show running-config @ 172.20.20.20 with expect: /^([\w.@()-]+[#>]\s?)$/
D, [2018-09-07T08:44:50.893867 #14488] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^([\w.@()-]+[#>]\s?)$/] at 172.20.20.20
D, [2018-09-07T08:44:51.295999 #14488] DEBUG -- : lib/oxidized/input/cli.rb Running pre_logout commands at 172.20.20.20
D, [2018-09-07T08:44:51.296177 #14488] DEBUG -- : lib/oxidized/input/ssh.rb exit @ 172.20.20.20 with expect: nil
D, [2018-09-07T08:44:51.455025 #14488] DEBUG -- : lib/oxidized/node.rb: Oxidized::SSH ran for 172.20.20.20 successfully
D, [2018-09-07T08:44:51.455262 #14488] DEBUG -- : lib/oxidized/job.rb: Config fetched for 172.20.20.20 at 2018-09-07 08:44:51 UTC
I, [2018-09-07T08:44:51.717352 #14488]  INFO -- : Configuration updated for /172.20.20.20
D, [2018-09-07T08:44:51.717425 #14488] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 2 of 2
D, [2018-09-07T08:44:51.717476 #14488] DEBUG -- : lib/oxidized/worker.rb: Running :nodes_done hook
D, [2018-09-07T08:44:52.717733 #14488] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 0 of 2
D, [2018-09-07T08:44:53.718083 #14488] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 0 of 2
D, [2018-09-07T08:44:54.718516 #14488] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 0 of 2
D, [2018-09-07T08:44:55.718979 #14488] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 0 of 2
D, [2018-09-07T08:44:56.719515 #14488] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 0 of 2
D, [2018-09-07T08:44:57.719974 #14488] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 0 of 2
D, [2018-09-07T08:44:58.720417 #14488] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 0 of 2
D, [2018-09-07T08:44:59.720905 #14488] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 0 of 2
D, [2018-09-07T08:45:00.721421 #14488] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 0 of 2
D, [2018-09-07T08:45:01.721844 #14488] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 0 of 2
D, [2018-09-07T08:45:02.722271 #14488] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 0 of 2
D, [2018-09-07T08:45:03.722704 #14488] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 0 of 2
D, [2018-09-07T08:45:04.723152 #14488] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 0 of 2
…continues indefinitely...

Cisco switch configuration only shows output from some initial commands, doesn't show device configuration from "show run":

cisco@oxidized:~$ cat configs/172.20.20.20
! Cisco IOS Software, C3750E Software (C3750E-UNIVERSALK9-M), Version 15.2(1)E1, RELEASE SOFTWARE (fc2)
! 
! Image: Software: C3750E-UNIVERSALK9-M, 15.2(1)E1, RELEASE SOFTWARE (fc2)
! Image: Compiled: Fri 22-Nov-13 06:27 by prod_rel_team
! Image: flash:c3750e-universalk9-mz.152-1.E1.bin
! Chassis type: WS-C3750X-24S
! Memory: main 524288K
! Processor ID: FDO1730P287
! CPU: PowerPC405
! 
! VTP: VTP Version capable             : 1 to 3
! VTP: VTP version running             : 1
! VTP: VTP Domain Name                 : 
! VTP: VTP Pruning Mode                : Disabled
! VTP: VTP Traps Generation            : Disabled
! VTP: Device ID                       : c08c.60bb.d480
! VTP: Configuration last modified by 172.20.20.20 at 0-0-00 00:00:00
! VTP: Feature VLAN:
! VTP: --------------
! VTP: VTP Operating Mode                : Transparent
! VTP: Maximum VLANs supported locally   : 1005
! VTP: Number of existing VLANs          : 39
! VTP: Configuration Revision            : 0
! VTP: MD5 digest                        : 0xEC 0x3E 0xBB 0x18 0x8A 0xA2 0x2A 0x7A 
! VTP:                                     0x51 0x73 0x76 0x5E 0x5C 0x0B 0xDD 0xCA 
! 
! NAME: "1", DESCR: "WS-C3750X-24S"
! PID: WS-C3750X-24S-S   , VID: V04  , SN: FDO1730P287
! 
! NAME: "Switch 1 - Power Supply 0", DESCR: "FRU Power Supply"
! PID: C3KX-PWR-350WAC   , VID: V03D , SN: DCB172791UH
! 
! NAME: "GigabitEthernet1/0/1", DESCR: "1000BaseLX SFP"
! PID: SFP-GE-L            , VID: V01  , SN: F788X22         
! 
! NAME: "GigabitEthernet1/0/2", DESCR: "1000BaseBX10-D SFP"
! PID: GLC-BX-D            , VID: V01  , SN: F7867YK         
! 
! NAME: "GigabitEthernet1/0/3", DESCR: "1000BaseLX SFP"
! PID: GLC-LH-SMD          , VID: V01  , SN: F788X1Y         
! 
! NAME: "GigabitEthernet1/0/4", DESCR: "1000BaseLX SFP"
! PID: GLC-LH-SMD          , VID: V01  , SN: F785PLS         
! 
! NAME: "GigabitEthernet1/0/5", DESCR: "1000BaseBX10-U SFP"
! PID: GLC-BX-U            , VID: V01  , SN: F785TCQ         
! 
! NAME: "GigabitEthernet1/0/6", DESCR: "1000BaseLX SFP"
! PID: GLC-LH-SMD          , VID: V01  , SN: F7883AD         
! 
! NAME: "GigabitEthernet1/0/7", DESCR: "1000BaseBX10-D SFP"
! PID: GLC-BX-D            , VID: V01  , SN: F785C1J         
! 
! NAME: "GigabitEthernet1/0/8", DESCR: "1000BaseBX10-D SFP"
! PID: GLC-BX-D            , VID: V01  , SN: F785RE8         
! 
! NAME: "GigabitEthernet1/0/9", DESCR: "1000BaseLX SFP"
! PID: GLC-LH-SMD          , VID: V01  , SN: F7883AC         
! 
! NAME: "GigabitEthernet1/0/10", DESCR: "1000BaseLX SFP"
! PID: GLC-LH-SMD          , VID: V01  , SN: F788VQ3         
! 
! NAME: "GigabitEthernet1/0/11", DESCR: "1000BaseLX SFP"
! PID: SFP-GE-L            , VID: V01  , SN: F7883D6         
! 
! NAME: "GigabitEthernet1/0/12", DESCR: "1000BaseBX10-D SFP"
! PID: GLC-BX-D            , VID: V01  , SN: F784SKH         
! 
! NAME: "GigabitEthernet1/0/13", DESCR: "1000BaseBX10-D SFP"
! PID: GLC-BX-D            , VID: V01  , SN: F785RE7         
! 
! NAME: "GigabitEthernet1/0/14", DESCR: "1000BaseBX10-D SFP"
! PID: GLC-BX-D            , VID: V01  , SN: F7867Z9         
! 
! NAME: "GigabitEthernet1/0/15", DESCR: "1000BaseBX10-D SFP"
! PID: GLC-BX-D            , VID: V01  , SN: F7867WQ         
! 
! NAME: "GigabitEthernet1/0/16", DESCR: "1000BaseLX SFP"
! PID: GLC-LH-SMD          , VID: V01  , SN: F788VQ2         
! 
! NAME: "GigabitEthernet1/0/17", DESCR: "1000BaseBX10-U SFP"
! PID: GLC-BX-U            , VID: V01  , SN: F78BRZU         
! 
! NAME: "GigabitEthernet1/0/18", DESCR: "1000BaseBX10-D SFP"
! PID: GLC-BX-D            , VID: V01  , SN: F78JBLX         
! 
! NAME: "GigabitEthernet1/0/19", DESCR: "1000BaseBX10-D SFP"
! PID: GLC-BX-D            , VID: V01  , SN: F7889MK         
! 
! NAME: "GigabitEthernet1/0/20", DESCR: "1000BaseBX10-U SFP"
! PID: GLC-BX-U            , VID: V01  , SN: F788BEA         
! 
! NAME: "GigabitEthernet1/0/21", DESCR: "10/100/1000BaseTX SFP"
! PID: GLC-T               , VID: V04  , SN: F788XAS         
! 
! NAME: "GigabitEthernet1/0/22", DESCR: "10/100/1000BaseTX SFP"
! PID: GLC-T               , VID: V04  , SN: F78FG74         
! 
! NAME: "GigabitEthernet1/0/23", DESCR: "1000BaseLX SFP"
! PID: SFP-GE-L            , VID: V01  , SN: F78E5HP         
! 
! NAME: "GigabitEthernet1/0/24", DESCR: "10/100/1000BaseTX SFP"
! PID: GLC-T               , VID: V04  , SN: F788X52         
! 
! NAME: "Switch 1 - FRULink Slot 1 - FRULink Module", DESCR: "FRULink 1G Module"
! PID: C3KX-NM-1G        , VID: V01  , SN: FDO14510BJU
! 
! NAME: "GigabitEthernet1/1/1", DESCR: "1000BaseBX10-D SFP"
! PID: GLC-BX-D            , VID: V01  , SN: F785RE6         
! 
! NAME: "GigabitEthernet1/1/2", DESCR: "1000BaseBX10-D SFP"
! PID: GLC-BX-D            , VID: V01  , SN: F7867YF         
! 
! NAME: "GigabitEthernet1/1/3", DESCR: "1000BaseBX10-D SFP"
! PID: GLC-BX-D            , VID: V01  , SN: F7867YJ         
! 
! NAME: "GigabitEthernet1/1/4", DESCR: "10/100/1000BaseTX SFP"
! PID: GLC-T               , VID: V04  , SN: F788X53         
! 
! 

cisco@oxidized:~$

Any ideas what might be causing this? Happy to run additional commands and provide further information, if necessary.

Thanks in advance,

- Matt

**Comment by rbeumer** [comment]
In the logs folder you should have files for your device containing the output for the SSH/telnet session. That might give yo a hint

**Comment by mwatkins-911** [comment]
Ah, I'd missed the fact that generating logs of the SSH session has it's own debug flag. I enabled it and oxidised started logging the session output. Turns out it wasn't attempting to get enable access, so fixing my configuration got everything working. Thanks for your help.
