### ISSUE TITLE
FortiOS.rb - new exclusion required for Fortiswitches

### ISSUE THREAD

**Issue by SoulGit** [ytti/oxidized#1510]
Hi - 

Under the current model, Fortiswitch check-ins result in a new diff each time due to key rotation.  On the Fortigate, the statement "END ENCRYPTED PRIVATE KEY" is used as the delimiter for the regex match, however in the Fortiswitch, the text is "END RSA PRIVATE KEY" resulting in a mis-match.

I'll create a pull request for the required update.

**Comment by wk** [comment]
This looks good. Thank you for resolving this!
