### ISSUE TITLE
HP ProCurve (Aruba) Switch - timed out while waiting for more data

### ISSUE THREAD

**Issue by deeconwastaken** [ytti/oxidized#1512]
Hi,

I have trouble getting the config from all of my HP 2530-8G-PoEP Switches (J9774A).

I updated oxidized to the latest version via gem, the Switches have the latest firmware. I "disables" exec and motd banners as told in #1422 

The telnet log from all switches show some strange characters:

`
^[[2J^[[?7h^[[1;23r^[[?6l^[[1;1H^[[?25l^[[1;1H ^[[1;1r^[[1;1H^[[1;24r^[[1;1H^[[24;1HUsername: ^[[?25h$
^[[?25h^[[24;18H^[[1;24r^[[24;1H^[[24;1HPassword: ^[[?25h^[[24;1H^[[?25h^[[24;11H^[[1;1H^[[?25l^[[24;$
^[[?25h^[[24;11H^[[1;24r^[[24;1H^[[?6l^[[1;24r^[[?7h^[[2J^[[1;1H^[[1920;1920H^[[6n^[[1;1H

Your previous successful login (as manager) was on 1990-01-01 00:22:43
 from 192.168.8.190
^[[1;24r^[[24;1H^[[24;1H^[[2K^[[24;1H^[[?25h^[[24;1H^[[24;1HLB-IS0200# ^[[24;1H^[[24;12H^[[24;1H^[[?2$
`

**Comment by deeconwastaken** [comment]
The LogFile shows the following entries:
`W, [2018-09-10T10:57:23.355092 #22528]  WARN -- : 192.168.8.20 raised Net::ReadTimeout (rescued Timeout::Error) with msg "timed out while waiting for more data"
W, [2018-09-10T10:57:23.941392 #22528]  WARN -- : 192.168.8.20 status no_connection, retry attempt 1
W, [2018-09-10T10:57:34.357956 #22528]  WARN -- : 192.168.8.20 raised Net::ReadTimeout (rescued Timeout::Error) with msg "timed out while waiting for more data"
W, [2018-09-10T10:57:34.944547 #22528]  WARN -- : 192.168.8.20 status no_connection, retries exhausted, giving up`

**Comment by rbeumer** [comment]
Do you really need telnet? With SSH there is no expect needed so that might give you a quick fix.

**Comment by laf** [comment]
Out of interest why? Telnet is not secure and regardless of maybe being on an internal network it should be disabled if ssh can be used.
