### ISSUE TITLE
Rugged::SshError: Failed to authenticate SSH session

### ISSUE THREAD

**Issue by fitzplb** [ytti/oxidized#1517]
Hi, I'm having a problem pushing to Git. I'm seeing this error in the logs:

`ERROR -- : Hook push_to_remote (#<GithubRepo:0x00000000cb1c40>) failed (#<Rugged::SshError: Failed to authenticate SSH session: Unable to send userauth-publickey request>) for event :post_store`

If I test my connection to Git it works fine using this:

`ssh -T git@github.mydomain.com`

I'm running the exact same container image, same config and same SSH key pair at a different location and it works there fine. Any ideas?

**Comment by jerebernard** [comment]
Same issue for me, I continue to troubleshoot...

**Comment by sollie** [comment]
I was experiencing the same issue. I initially tried using an ed25519 key-pair.

Swapping to RSA-keys solved this issue for me.

**Comment by fitzplb** [comment]
@sollie sounds like a different issue to me. This is an RSA key pair that I have proved I can authenticate to my Github with. The same key pair works in a different container in a different datacentre using the same image and connecting to the same Github enterprise server

**Comment by sollie** [comment]
Ah, ok. My error message was identical and my testing before changing keys produced the same result.
Missed the part about it working at a different site initially. Sorry about that.

**Comment by laf** [comment]
Have you tested this as the same user oxidized is running as?

If you are running this via containers, surely that means that everything in the containers are the same so that should rule out code / config and it might be env variables in starting the container or something outside of those setups?

**Comment by fitzplb** [comment]
@laf thanks for looking into this. When testing we're doing `docker exec` into the containers and running `ssh -T` or `git pull/push` commands manually to confirm we can successfully authenticate using the SSH key that is in the container. 
The git user is set using `git config --global user.name "oxidized"`. 

There's only 2 differences between the env variables being supplied when starting the containers. The first is that we pass in the datacentre location which is obviously different. We've tried using this env variable to point each instance at a separate remote Git repo, i.e. `github.mydomain.com/infrastructure/network_config_site1` and `github.mydomain.com/infrastructure/network_config_site2` but that didn't make any difference. The second is that the API key used to contact LibreNMS and populate the nodes to be backed up is different as each site has it's own instance of LibreNMS. 

My colleague @thrashlisaro might be able to provide more detail as he has also spent some time trying to make this work.

**Comment by tomasell** [comment]
I've the same issue running Oxidized v0.24 and Rugged v0.27.4

If I try to push local bare repository to remote (`git push origin master`) , it works.

**Comment by activekerrar** [comment]
Same issue here, but running on Centos 7.5 (no docker). Oxidized v0.24.0 and Rugged v0.27.4.

```
Oct 03 08:58:57 jprhal03 oxidized[22469]: I, [2018-10-03T08:58:57.904248 #22469]  INFO -- : Configuration updated for /myswitch1
Oct 03 08:58:57 jprhal03 oxidized[22469]: I, [2018-10-03T08:58:57.904766 #22469]  INFO -- : GithubRepo: Pushing local repository(/home/oxidized/.config/oxidized/oxidized.git/)...
Oct 03 08:58:57 jprhal03 oxidized[22469]: I, [2018-10-03T08:58:57.906087 #22469]  INFO -- : GithubRepo: to remote: git@gitlab.domain.com:ops/oxidized.git
Oct 03 09:00:57 jprhal03 oxidized[22469]: E, [2018-10-03T09:00:57.930562 #22469] ERROR -- : Hook push_to_remote (#<GithubRepo:0x00000002889e40>) failed (#<Rugged::SshError: Failed to authenticate SSH session: Unable to send userauth-publickey request>) for event :post_store
```

Verified that ssh works fine:
```
oxidized@jprhal03:~/.config/oxidized$ ssh -T git@gitlab.domain.com
Welcome to GitLab, @oxidized!
```

And that process is running under oxidized user:
```
oxidized@jprhal03:~/.config/oxidized$ ps -aux | grep oxidized
oxidized 22469  1.7  2.4 793504 46356 ?        Ssl  08:58   1:06 puma 3.11.4 (tcp://127.0.0.1:8888) [/]
```

**Comment by fitzplb** [comment]
I've found the solution to my problem. My SSH private key a the second site contained a blank line after `-----END RSA PRIVATE KEY-----`. It worked fine with `git clone/push` commands but didn't work when Oxidized used it - is that due to Oxidized using rugged/libssh2 whereas git doesn't maybe? 

Anyway, you can put this down to user error - I hadn't spotted the blank line in the key file at the second site so I was incorrect in saying I had identical SSH keys in both sites. 

@jerebernard @tomasell @activekerrar - does this help you?

**Comment by activekerrar** [comment]
Unfortunately it did not fix my issue. There are no blank lines or extra spaces at the end of the files.

**Comment by benjojo** [comment]
For those who hit this who may have generated a key on OSX, Check that it has produced a 'normal' looking id_rsa file. My OSX install (where I made the key) made a key with:

`-----BEGIN OPENSSH PRIVATE KEY-----` as it's banner

**Comment by behindcurtain3** [comment]
For what it's worth I ran into this same problem and fixed it by removing the docker container, recreating the keys and recreating the container.

**Comment by tyler-8** [comment]
If you have `-----BEGIN OPENSSH PRIVATE KEY-----` in your private key you need to change it to PEM format.

https://serverfault.com/questions/939909/ssh-keygen-does-not-create-rsa-private-key

`ssh-keygen -p -m PEM -f ~/.ssh/id_rsa`

**Comment by Len4i** [comment]
@tyler-8, Thank you.
That was the issue.

**Comment by activekerrar** [comment]
For those still having this issue, please ensure that the version of libssh2 is at least 1.8.2. If you are running a distro like Centos 7.5 (like I was), you'll likely find that the version is very old (Centos 7.5 only has 1.4.3). I verified that the exact same configuration works perfectly fine on Fedora 30, which has libssh2 1.8.2.

To find a compatible distro, look at this list: https://repology.org/project/libssh2/versions

You might be able to compile and install the 1.8.2 version as well, but this is an exercise for the reader and beyond the scope of this short msg. :)

**Comment by sshmanko** [comment]
@activekerrar I am having the same issue with **libssh2 v1.9.0** (also tried 1.8.2, both statically compiled) on Centos 6. Oxidized 0.26.3, rugged 0.28.3.
```ssh git@git.local
PTY allocation request failed on channel 0
Hi username!  You've successfully authenticated, but GitHub does not provide shell access.```
not sure how to debug this as previous messages are:
```DEBUG -- : GithubRepo: Authenticating using ssh keys as <username>```

**Comment by activekerrar** [comment]
@sshmanko I believe you are having a different issue than is described above. The fix I suggested was focused on those getting the "Rugged::SshError: Failed to authenticate SSH session: Unable to send userauth-publickey request" error in the logs. Are you receiving this error? If unsure, add "debug: true" to the top section of your config file and retry.

**Comment by sshmanko** [comment]
@activekerrar the issue might be different, but the error message is exactly the same:
```
D, [2019-09-06T13:50:51.251386 #19589] DEBUG -- : GithubRepo: Authenticating using ssh keys as 'username'
E, [2019-09-06T13:50:51.251626 #19589] ERROR -- : Hook push_to_remote (#<GithubRepo:0x0000000000b81258>) failed (#<Rugged::SshError: Failed to authenticate SSH session: Unable to send userauth-publickey request>) for event :post_store```

**Comment by handyscripts** [comment]
I solved this by adding ssh:// to the front of my git@github.com/abc/repo.git link.
