### ISSUE TITLE
D-Link DES-1210-28/ME: timed out while waiting for more data

### ISSUE THREAD

**Issue by loskiq** [ytti/oxidized#1519]
Doesn't work with DES-1210-28/ME, while other switch models does work. But I see in the logs of the switch that oxidized is connected to the switch and sends the command `disable clipaging`

```
W, [2018-09-12T11:58:56.394296 #645]  WARN -- : 192.168.249.17 raised Net::ReadTimeout (rescued Timeout::Error) with msg "timed out while waiting for more data"
W, [2018-09-12T11:58:56.917507 #645]  WARN -- : ololo status no_connection, retry attempt 1
W, [2018-09-12T11:59:17.411140 #645]  WARN -- : 192.168.249.17 raised Net::ReadTimeout (rescued Timeout::Error) with msg "timed out while waiting for more data"
W, [2018-09-12T11:59:17.952693 #645]  WARN -- : ololo status no_connection, retry attempt 2
W, [2018-09-12T11:59:38.438458 #645]  WARN -- : 192.168.249.17 raised Net::ReadTimeout (rescued Timeout::Error) with msg "timed out while waiting for more data"
W, [2018-09-12T11:59:39.028510 #645]  WARN -- : ololo status no_connection, retry attempt 3
W, [2018-09-12T11:59:59.545813 #645]  WARN -- : 192.168.249.17 raised Net::ReadTimeout (rescued Timeout::Error) with msg "timed out while waiting for more data"
W, [2018-09-12T12:00:00.056363 #645]  WARN -- : ololo status no_connection, retries exhausted, giving up
```

**Comment by loskiq** [comment]
?

**Comment by wk** [comment]
Duplicate of #1541, resolved in #1542

**Comment by wk** [comment]
Could you post the full logs of the interaction with the device after turning on [debugging](https://github.com/ytti/oxidized/blob/master/docs/Configuration.md#debugging)?

Is this perhaps a duplicate of #1541, closed by #1542?

**Comment by wk** [comment]
Potential duplicate of #1495

**Comment by loskiq** [comment]
@wk this is a not duplicate. I'm attached logs and tcpdump

Full logs in debug mode [log.txt](https://github.com/ytti/oxidized/files/2407579/log.txt)
tcpdump: https://drive.google.com/file/d/1CCNqm-qsX8r5uM54ZlHs3am5O3MedR3o/view?usp=sharing

**Comment by wk** [comment]
The pcap is indeed a little inconsistent with the expectations, but does look like a duplicate of #1541. 

The prompt of your device `DES-1210-28/ME:5#` should not have been detected before the change introduced in #1542 due to the presence of a forward slash (`/`). 

It is not immediately clear to me why the initial `show switch` command is executed in your situation, but that could be an unrelated issue. The eventual Timeout::Error appears to be the result of the subsequent prompt (at the completion of the `show switch` command) not being detected, and the device eventually terminating the session due to what looks to be a 20 second timeout.

Are you running these tests on the latest version of master with #1542 included? If not, please try it out. Additionally, could you attempt this over SSH (if the device supports it) to determine if the behavior between ssh and telnet inputs changes?

**Comment by loskiq** [comment]
@wk yes, of course, I'm running these tests on the latest version of master with #1542, but it still does not work. I'm attached full logs and tcpdump after the change introduced in #1542 

log: https://pastebin.com/FLJGPd3D
tcpdump: https://drive.google.com/file/d/1J7nRWFAVUz5QWdjuxFldBVIP5C1Gz4P7/view?usp=sharing

**Comment by wk** [comment]
Possible candidate for including a [control sequence cleanup similar to the one here](https://github.com/ytti/oxidized/blob/master/lib/oxidized/model/procurve.rb#L8-L16) into the model as workaround.

**Comment by loskiq** [comment]
@wk don't work :(

**Comment by freedomwarrior** [comment]
Have the same issue with d-link des 1210/10me after fixing this one [#1541](https://github.com/ytti/oxidized/issues/1541)

**Comment by wildarp** [comment]
I have the same problem with DES-1210-28/ME 
Log:
W, [2018-10-26T05:30:31.067018 #131]  WARN -- : 10.7.8.192 raised Net::ReadTimeout (rescued Timeout::Error) with msg "timed out while waiting for more data"

Switch log:
 11    Oct 25 12:22:00:CLI-6:Telnet session timed out( IP: 10.7.9.254 )

**Comment by wildarp** [comment]
its works if change in dlink.rb prompt to
prompt /# $/
but then its not work for another Dlink models, how to create new model for example dlink1210.rb ?
Can anyone help ?

**Comment by wildarp** [comment]
I created new model dlink1210.rb but Oxidized does not start, renamed dlink1210.rb to dlinknew.rb and its works, why  model names does not support digits?

**Comment by spirkaa** [comment]
I have the same problem with latest build of docker container with DES-1210-28/ME

**Comment by wildarp** [comment]
I don`t think it is problem with docker, in DLink you have to run the command 
# disable clipaging
In dlink.rb
-----------------
class Dlink < Oxidized::Model
  # D-LINK Switches

  prompt /# $/
-----------------

**Comment by DerTFL** [comment]
Hi. For DGS-1210-10/ME i have this tcpdump:
```
0000   00 00 00 00 00 00 00 00 00 00 00 00 08 00 45 00   ..............E.
0010   00 36 a8 ce 00 00 3a 06 dd a1 0a 31 85 04 0a 40   .6....:....1...@
0020   60 dd 00 17 dd 72 6e ca aa 7b cf c0 38 a2 80 18   `....rn..{..8...
0030   23 ff 13 76 00 00 01 01 08 0a 11 49 a2 1f e5 35   #..v.......I...5
0040   a0 10 0d 0a                                       ....
0000   00 00 00 00 00 00 00 00 00 00 00 00 08 00 45 00   ..............E.
0010   00 52 a8 cf 00 00 3a 06 dd 84 0a 31 85 04 0a 40   .R....:....1...@
0020   60 dd 00 17 dd 72 6e ca aa 7d cf c0 38 a2 80 18   `....rn..}..8...
0030   23 ff e4 53 00 00 01 01 08 0a 11 49 a2 1f e5 35   #..S.......I...5
0040   a0 10 1b 5b 32 37 6d 0d 20 20 20 20 20 20 20 20   ...[27m.        
0050   20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 0d                  .
0000   00 00 00 00 00 00 00 00 00 00 00 00 08 00 45 00   ..............E.
0010   00 47 a8 d0 00 00 3a 06 dd 8e 0a 31 85 04 0a 40   .G....:....1...@
0020   60 dd 00 17 dd 72 6e ca aa 9b cf c0 38 a2 80 18   `....rn.....8...
0030   23 ff 41 4d 00 00 01 01 08 0a 11 49 a2 1f e5 35   #.AM.......I...5
0040   a0 10 0d 44 47 53 2d 31 32 31 30 2d 31 30 2f 4d   ...DGS-1210-10/M
0050   45 3a 35 23 20                                    E:5# 

```
And this regexp work for me now:
```
^(\e\[27m)?(\r*[\w\s.@()\/:-]+[#>]\s?)$
```
So, please edit prompt in ```dlink.rb``` to this and test
```
  prompt /^(\e\[27m)?(\r*[\w\s.@()\/:-]+[#>]\s?)$/
```
