### ISSUE TITLE
Trigger resolving of hostname

### ISSUE THREAD

**Issue by rvandepu** [ytti/oxidized#1522]
Hi,

We're in the process of revamping our OOB network to an L3 network instead of a stretched L2 domain. This includes changing IP addressing.

I noticed Oxidized was failing to pull config from migrated nodes because it was trying to connect on the old IP. As I understand, Oxidized resolves all hostnames when the process starts. I tried a reload of the router.db file (GET /reload), but this did not trigger a new resolve.

Is it possible to trigger resolving of all, or specific hosts without restarting the oxidized process?

**Comment by User4574** [comment]
I have noticed this too, though it is causing me different issues.

Is there a reason it is done this way (resolve at start, then connect to IP) rather than just passing the hostname to Net::SSH.start and letting it resolve then?

**Comment by laf** [comment]
I don't know the reason why oxidized uses IP in the ssh connection but it's been like that since the first commit.

That means I also don't know if the project would accept a pull request changing that.
