### ISSUE TITLE
Output two types of files

### ISSUE THREAD

**Issue by 07stuntar1** [ytti/oxidized#1527]
Is there a way to output the Git files and txt files?

**Comment by laf** [comment]
Have you tried adding both outputs? I've never tried it to see.

However, why do you need both. Git basically has the text files included in it.

**Comment by myclau** [comment]
I also try to do it.

my solution is do it in hook:
`
output:
  default: git
  git:
    user: Oxidized
    email: o@test.com
    repo: /root/.config/oxidized/devices.git

hooks:
  dump_config:
    type: exec
    events: [post_store]
    cmd: '. /xxx/dumpconfig.sh'
    timeout: 10

`

and put a bash script file in /xxx/dumpconfig.sh
`#!/bin/bash
set -o errexit
echo "[Dump config] clone config from local bare git "
mkdir -p /root/.config/oxidized/export/.git
cp -r /root/.config/oxidized/devices.git/* /root/.config/oxidized/export/.git
cd /root/.config/oxidized/export
git config --local --bool core.bare false
git reset --hard
echo "[Dump config] completed"
`
and the file config file will be in /root/.config/oxidized/export
