### ISSUE TITLE
Junos SECRET-DATA

### ISSUE THREAD

**Issue by beh0ld** [ytti/oxidized#1535]
Hi! Need some help, please. I want to see hash in web interface rather than

        _encrypted-password /* SECRET-DATA */; ## SECRET-DATA_

I removed from _junos.rb_

_cmd :secret do |cfg|
cfg.gsub!(/community (\S+) {/, 'community <hidden> {')
cfg.gsub!(/ "\$\d\$\S+; ## SECRET-DATA/, ' <secret removed>;')
cfg
end_
and set _remove_secret: false_ in config, but no change, in web i see /* SECRET-DATA */ again.

**Comment by sollie** [comment]
The login class of your user needs to have "permissions secret" on Junos.

https://www.juniper.net/documentation/en_US/junos/topics/concept/access-login-class-overview.html

**Comment by ytti** [comment]
This is problem with your configuration, the data arrives already with 'secret-data' when you request the configuration, Oxidized doesn't do anything to it. You need to change your user's privileges, so that they will see the actual configuration.

**Comment by beh0ld** [comment]
Thanks a lot, guys!
