### ISSUE TITLE
ciscosmb not working, SSH asking for User Name after connection

### ISSUE THREAD

**Issue by itscassa** [ytti/oxidized#154]
I'm having the issue that some Cisco SMB devices don't work. I think this is because of the following:
```
# ssh user@rtr1




User Name:user
Password:*******


rtr1#
```

The error I get in the log:
```
W, [2015-08-06T10:35:54.281587 #1374]  WARN -- : rtr1 no_connection, retries exhausted, giving up
W, [2015-08-06T10:36:03.773497 #1374]  WARN -- : ip raised Timeout::Error with msg "execution expired"
```

I've tried some regexp in the model, but haven't got it working yet.

**Comment by itscassa** [comment]
Meh, seems like it isn't the problem

**Comment by ytti** [comment]
Just for posterity, what was the issue.

Perhaps in Timeout::Error we should return which regexp it was waiting for? Maybe it would help troubleshooting.

**Comment by itscassa** [comment]
The problem was that the command `show running-config` was taking longer than the timeout

**Comment by ytti** [comment]
Yeah we should probably add in the message what command was sent, what regexp we expected to help troubleshooting, I'll look into this.
