### ISSUE TITLE
Undefined method "closed?" for Telnet on Cisco switches?

### ISSUE THREAD

**Issue by OnlyTheShadowKnows** [ytti/oxidized#1543]
We have a handful of Cisco 2950/2960 switches that are throwing errors in Oxidized.  I just got handed this project to get them all working again and I'm at a loss as to what's causing the issue.  I have confirmed that the username and password specified in config is correct and can telnet (or SSH) to the switch and that username has all the requisite permissions to do a configuration dump.  This same username and password combination are used on several other switches that exhibit no issues whatsoever. 

On a particular non-working switch, I see this in the log file:

E, [2018-09-21T12:39:09.102700 #27206] ERROR -- : x.x.x.x raised NoMethodError with msg "undefined method 'closed?' for #<Net::Telnet:0x007f6dc18eeb18>", /home/oxidized/.config/oxidized/crash.x.x.x.x saved

W, [2018-09-21T12:39:09.288592 #27206]  WARN -- : switch-hostname-here status no_connection, retry attempt 1

E, [2018-09-21T12:39:11.086623 #27206] ERROR -- : x.x.x.x raised NoMethodError with msg "undefined method 'closed?' for #<Net::Telnet:0x00000001066b60>", /home/oxidized/.config/oxidized/crash.x.x.x.x saved

W, [2018-09-21T12:39:11.290024 #27206]  WARN -- : switch-hostname-here status no_connection, retry attempt 2

E, [2018-09-21T12:39:22.078740 #27206] ERROR -- : x.x.x.x raised NoMethodError with msg "undefined method 'closed?' for #<Net::Telnet:0x000000010776e0>", /home/oxidized/.config/oxidized/crash.x.x.x.x saved

W, [2018-09-21T12:39:22.293998 #27206]  WARN -- : switch-hostname-here status no_connection, retry attempt 3

E, [2018-09-21T12:39:24.113889 #27206] ERROR -- : x.x.x.x raised NoMethodError with msg "undefined method 'closed?' for #<Net::Telnet:0x00000001263e90>", /home/oxidized/.config/oxidized/crash.x.x.x.x saved

W, [2018-09-21T12:39:24.295213 #27206]  WARN -- : switch-hostname-here status no_connection, retries exhausted, giving up

In the crash file specified, I get the below:

2018-09-21 18:44:45 UTC
undefined method 'closed?' for #<Net::Telnet:0x000000010808a8> [NoMethodError]
--------------------------------------------------
/usr/local/rvm/gems/ruby-2.1.2/gems/oxidized-0.21.0/lib/oxidized/input/telnet.rb:67:in 'disconnect'
/usr/local/rvm/gems/ruby-2.1.2/gems/oxidized-0.21.0/lib/oxidized/input/cli.rb:15:in 'get'
/usr/local/rvm/gems/ruby-2.1.2/gems/oxidized-0.21.0/lib/oxidized/node.rb:66:in 'run_input'
/usr/local/rvm/gems/ruby-2.1.2/gems/oxidized-0.21.0/lib/oxidized/node.rb:43:in 'block in run'
/usr/local/rvm/gems/ruby-2.1.2/gems/oxidized-0.21.0/lib/oxidized/node.rb:38:in 'each'
/usr/local/rvm/gems/ruby-2.1.2/gems/oxidized-0.21.0/lib/oxidized/node.rb:38:in 'run'
/usr/local/rvm/gems/ruby-2.1.2/gems/oxidized-0.21.0/lib/oxidized/job.rb:9:in 'block in initialize'

(Backticks in above output changed to single quotes due to github fomatting)
I confirmed the oxidized username and password does work over telnet for this particular switch from the machine running Oxidized.  I can't think of anything that would cause this to not work.  The firmware on the switch is Cisco IOS version 12.1(22)EA2 

Your help is greatly appreciated.  Thank you in advance.

Edit:  I can't get the formatting right on this.

**Comment by wk** [comment]
You are running a rather old version of Oxidized. Please consider upgrading to 0.24.0 before investigating this further.

**Comment by OnlyTheShadowKnows** [comment]
Upgraded, will advise.  Thank you.

**Comment by OnlyTheShadowKnows** [comment]
There's an issue with charlock_holmes and centos 7 that won't let me upgrade oxidized-web, (yes libicu-devel is installed).  Without it, I can't perform the upgrade.  Since charlock_holmes is not Oxidized, I filed an issue with that developer for assisance:  https://github.com/brianmario/charlock_holmes/issues/136

Thank you for your time, will re-open if I am able to get that blocker sorted.

**Comment by wk** [comment]
Make sure you have gcc-c++ package installed, as well as zlib development next to libicu-devel as these are all required to build charlock_holmes successfully.

**Comment by OnlyTheShadowKnows** [comment]
Hello wk:

I have checked all required packages (gcc-c++, zlib and zlib-devel, libicu and libicu-devel).  In each instance of attempting installation of oxidized-web/charlock_holmes, I get the below error:

/home/oxidized # gem install oxidized-web
Building native extensions.  This could take a while...
ERROR:  Error installing oxidized-web:
	ERROR: Failed to build gem native extension.

    current directory: /usr/local/rvm/gems/ruby-2.1.2/gems/charlock_holmes-0.7.6/ext/charlock_holmes
/usr/local/rvm/rubies/ruby-2.1.2/bin/ruby -r ./siteconf20180924-30038-17w6bqx.rb extconf.rb
checking for main() in -licui18n... yes
checking for main() in -licui18n... yes
checking for unicode/ucnv.h... yes
checking for main() in -lz... yes
checking for main() in -licuuc... yes
checking for main() in -licudata... yes
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/local/rvm/rubies/ruby-2.1.2/bin/ruby
	--with-icu-dir
	--without-icu-dir
	--with-icu-include
	--without-icu-include=${icu-dir}/include
	--with-icu-lib
	--without-icu-lib=${icu-dir}/lib
	--with-icui18nlib
	--without-icui18nlib
	--with-icui18nlib
	--without-icui18nlib
	--with-zlib
	--without-zlib
	--with-icuuclib
	--without-icuuclib
	--with-icudatalib
	--without-icudatalib
extconf.rb:60:in '<main>': undefined method '<<' for nil:NilClass (NoMethodError)

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /usr/local/rvm/gems/ruby-2.1.2/extensions/x86_64-linux/2.1.0/charlock_holmes-0.7.6/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /usr/local/rvm/gems/ruby-2.1.2/gems/charlock_holmes-0.7.6 for inspection.
Results logged to /usr/local/rvm/gems/ruby-2.1.2/extensions/x86_64-linux/2.1.0/charlock_holmes-0.7.6/gem_make.out

I have checked the mkmf.log and I see a lot of compiler tests but none of them return any errors from what I can tell.  The gem_make.out file is just a copy of the error above.

**Comment by OnlyTheShadowKnows** [comment]
Closing this issue.  There were other things at play that were causing oxidized to not work with the Cisco switches.  The issue was resolved and oxidized worked as expected.  Thank you.
