### ISSUE TITLE
Silent failure when enable not configured correctly

### ISSUE THREAD

**Issue by candlerb** [ytti/oxidized#1546]
I had an odd situation of a bunch of IOS switches where the basic inventory was shown (so I knew it was logging in OK), but the config part was completely missing.

I had to turn on full ssh/telnet debugging to find the problem.  When I did, I found this:

```
ix-coresw1>show running-config
show running-config
      ^
% Invalid input detected at '^' marker.

ix-coresw1>exit
```

So it turns out the problem was that enable mode had not been selected.  However no indication of the error was visible in the output at all, and the switch status was green in the web UI.

Looking in `ios.rb` I see that errors are explicitly hidden:

```
  cmd :all do |cfg|
    # cfg.gsub! /\cH+\s{8}/, ''         # example how to handle pager
    # cfg.gsub! /\cH+/, ''              # example how to handle pager
    # get rid of errors for commands that don't work on some devices
    cfg.gsub! /^% Invalid input detected at '\^' marker\.$|^\s+\^$/, ''
    cfg.each_line.to_a[1..-2].join
  end
```

And the top of the `show running-config` command is also trimmed:

```
  cmd 'show running-config' do |cfg|
    cfg = cfg.each_line.to_a[3..-1]
```

I think for critical commands like "show running-config" it would be a good idea *not* to hide these errors - either by including the error output in the generated config, or by making the whole pull fail which would turn the status to red in the web UI.

**Comment by ytti** [comment]
I think your first proposal of having error in config is not very useful, as then you'd need to develop some method to grep the configs for these errors to report, and if you're going to do that, you might as well verify the config size is reasonable, which it won't be if commands don't succeed. 

Second option that we simply fail if single command fails is more plausible, we could do that, however currently several model specifically cover multiple devices os versions where in some versions command will fail and that's fine, as it's not yet supported. 

So what we'd really need is ability to discriminate between mandatory command and non-mandatory command and way for model to determine if run was success.
This is entirely possible and not very hard to add in backward compatible manner.

**Comment by candlerb** [comment]
Yes, I think that's a good approach. Quite a few commands should be mandatory, including "enable" itself.  At the moment, if I set the wrong enable password, it just sails on past:

```
ix-coresw1>enable
Password:
% Access denied

ix-coresw1>terminal length 0
ix-coresw1>terminal width 0
... etc
```
