### ISSUE TITLE
[Git output] Howto?

### ISSUE THREAD

**Issue by itscassa** [ytti/oxidized#155]
Hi,

I'm trying to push the router configs to a git server. I've tried to clone a bare repo and to clone it normally, but both didn't work.

What is the correct way to set this up?

Thank you.

**Comment by ytti** [comment]
Oxidized will happily create bare repo when it needs to store git config. It can be created for oxidized, but perhaps easier to let it create it.
After that, syncing it to you upstream server (gitlab? github? bitbucket?) would be easiest in crontab by pulling your bare repo to local checkout then push it to upstream.

**Comment by itscassa** [comment]
Thank you.

When I do this, I'm getting the following error:
```
ArgumentError at /node/version
wrong number of arguments (at least 1)
file: versions.haml location: count line: 39
```

**Comment by ytti** [comment]
Uhh ohhh. I'm now not anymore sure what is the problem.

From first post I understood you can't get configs stored in git.

From second post it seems like you're trying to use API, but that is not working. 

So just to help me, have you successfully fetched config and store it in git? If not, then perhaps we shouldn't think about API just yet, let's fix the first issue first.

When in CLI you do something like

git clone /my/bare/repo /tmp/oxidized

Do you get configs there?

**Comment by itscassa** [comment]
@ytti I've done it now by setting single_repo to false and the following bash script
```
#!/bin/bash
for old in /home/user/.config/oxidized/repos/*.git
do
  cd /home/user/oxidized/bitbucket/
  base=`basename $old`
  rm -rf "${base%.*}"
  git clone $old
done
cd /home/user/oxidized/bitbucket/
rm -rf */*.git/
git add -A
git commit -m "Updates"
git push -u origin master -f

```

**Comment by ytti** [comment]
I'm still confused. You shouldn't need 'git add -a' nor 'git commit'. 

You should just need to do

git pull    # pulls from the local bare repo, to local checkout
git push  # pushes to your bitbucket repo

Essentially synching the two repos. Now you're recommitting, which seems completely wrong. More work, and you may potentially destroy important metadata in commit messages (like if you extract username from syslog, oxidized can mark commit done by actual user who did the change, so 'git blame' will show which user changed which line).
