### ISSUE TITLE
Git Push  when manually reload config

### ISSUE THREAD

**Issue by jerebernard** [ytti/oxidized#1568]
Hello,
On the web portal when we manually reload the config git push is not done. 
It could be good to have the config push on the GIT during this sequence.
Regards,

**Comment by ytti** [comment]
How are you pushing your configs outside the web portal reload?

**Comment by jerebernard** [comment]
Actually every backup every is down every 4hours and export/push to the git in the same time. I just seen than when we click on reload a new backup of the selected device is done. But this backup is not push on the config. We have to wait every 4hours to have the push done. I think it could be good for exemple in case of a intervention on a device to reload the config to have a backup just before a big change.

**Comment by ytti** [comment]
How is the push done specifically, how have you automated it to occur.

**Comment by jerebernard** [comment]
I have installed oxidized with docker container and this is my config for output : 
output:
  default: git
  git:
    user: Oxidized
    email: backup@info.xxx.fr
    single_repo: true
    repo: "/tmp/oxidized.git"
  file:
    directory: "/root/.config/oxidized/configs"

hooks:
  push_to_remote:
    type: githubrepo
    events: [post_store]
    remote_repo: git@gitlab.xxx.fr:xxx/oxidized.git
    publickey: /root/.config/oxidized/git.pub
    privatekey: /root/.config/oxidized/git.key

**Comment by ytti** [comment]
And you're saying if you ask node to be updated from webUI the ```post_store``` hook does not fire? It definitely should fire if there are changes in the config.

**Comment by jerebernard** [comment]
Yes for me it doesn't fire. It just store the new config locally but without any push. I can only see a push when every 4 hours when the automatic backup is done.

**Comment by ytti** [comment]
You're right, we're calling Nodes#fetch, which calls Output#fetch and hooks are not ran. We should call Worker#process.

**Comment by jerebernard** [comment]
Yes it could a simplify utilisation.

**Comment by ytti** [comment]
I'm not going to fix it, not at least now, but if someone wants to do it, above should be good starting point how to fix it.

**Comment by jerebernard** [comment]
Thanks
