### ISSUE TITLE
[HP Procurve] Backup failed OS not compatible

### ISSUE THREAD

**Issue by jerebernard** [ytti/oxidized#1569]
Hello All,

Backup doesn't work for this model : HP J9726A 2920.
Using the debug this the error message I got : 
Specific Log Connection : ```
HP J9726A 2920-24G Switch

Software revision WB.15.16.0005

Copyright (C) 1991-2014 Hewlett-Packard Development Company, L.P.

                   RESTRICTED RIGHTS LEGEND
 Confidential computer software.  Valid license from HP required for possession,
 use or copying. Consistent with FAR 12.211 and 12.212, Commercial Computer
 Software, Computer Software Documentation, and Technical Data for Commercial
 Items are licensed to the U.S. Government under vendor's standard commercial
 license.
                   HEWLETT-PACKARD DEVELOPMENT COMPANY, L.P. 
                   20555 State Highway 249, Houston, TX 77070

[1;15r[1;1H
```
SSH Debug : ```

W, [2018-10-02T11:45:23.811950 #30]  WARN -- : network/switch.xxx.lan status no_connection, retry attempt 1
W, [2018-10-02T11:45:26.203435 #30]  WARN -- : 192.168.1.1 raised IOError with msg "closed stream"
```
Any Idea ?

**Comment by jerebernard** [comment]
Anyone with a solution ? Backup of new firmware HP Procurve looks difficult

**Comment by davama** [comment]
More info...

config?
db file? are you using procurve model?
is ssh allowed?

looks to me like you have a banner when you log into your switch. At least in my case, i've noticed that if there is an empty space in front of the banner oxidized complains but your oxidized log doesnt say that. can oxidized reach it? Using the latest HEAD branch?

> Anyone with a solution ? Backup of new firmware HP Procurve looks difficult

im assuming you meant "config" not firmware...have you looked at other tickets to see if someone else had similar issue?

**Comment by jerebernard** [comment]
Hello,
Regarding the config it's configured to use procurve model which works for a lot of procurve switches except all procurve switches using software : Software revision WB.15.X or WB.16.X.
On my side this software is used by  2920-48G, 2920-48G-POE+, 2920-24G.
I have removed all banners : no banner exec, no banner motd, no banner last-login.
I'm using the last head branch.
From oxidized when i'm doing a manual SSH it works.
In the central log I got this : 
`D, [2019-11-29T10:28:02.477005 #30] DEBUG -- : resolving DNS for switch...
D, [2019-11-29T10:28:12.620484 #30] DEBUG -- : lib/oxidized/worker.rb: Added network/switch to the job queue
D, [2019-11-29T10:28:12.620586 #30] DEBUG -- : lib/oxidized/job.rb: Starting fetching process for switch at 2019-11-29 10:28:12 UTC
D, [2019-11-29T10:28:12.621229 #30] DEBUG -- : lib/oxidized/input/ssh.rb: Connecting to switch
D, [2019-11-29T10:28:13.622016 #30] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/(^\r|\e\[24;[0-9][hH])?([\w\s.-]+# )($|(\e\[24;[0-9][0-9]?[hH]){3})/] at switch
D, [2019-11-29T10:28:15.432890 #30] DEBUG -- : lib/oxidized/node.rb: Oxidized::SSH failed for switch
D, [2019-11-29T10:28:15.432967 #30] DEBUG -- : lib/oxidized/job.rb: Config fetched for switch at 2019-11-29 10:28:15 UTC
W, [2019-11-29T10:28:15.622624 #30]  WARN -- : network/switch status no_connection, retry attempt 1`
In the debug log I got this : 
`HP J9726A 2920-24G Switch
Software revision WB.15.14.0007
Copyright (C) 1991-2014 Hewlett-Packard Development Company, L.P.

                   RESTRICTED RIGHTS LEGEND
 Confidential computer software.  Valid license from HP required for possession,
 use or copying. Consistent with FAR 12.211 and 12.212, Commercial Computer
 Software, Computer Software Documentation, and Technical Data for Commercial
 Items are licensed to the U.S. Government under vendor's standard commercial
 license.
                   HEWLETT-PACKARD DEVELOPMENT COMPANY, L.P. 
                   20555 State Highway 249, Houston, TX 77070

[1;15r[1;1H`
