### ISSUE TITLE
Send diffs email

### ISSUE THREAD

**Issue by itscassa** [ytti/oxidized#157]
Rancid has the option to send emails with diffs, it would be great if this would be added to oxidized.

**Comment by ytti** [comment]
This is likely duplicate of #60 

Personally I'm currently leaving this task to gitlab. Perhaps you can leave it to bitbucket, for now?

**Comment by itscassa** [comment]
That's actually a pretty good idea. Will try to find one for Bitbucket.

**Comment by itscassa** [comment]
Got it. https://confluence.atlassian.com/display/BITBUCKET/Email+Diff+service+management
