### ISSUE TITLE
Integrate oxid with switch archive

### ISSUE THREAD

**Issue by Noname2244** [ytti/oxidized#1578]
Problem, update the config in oxidized upon executing wr on a switch.
with archive on the switch you can save the conf to tftp scp etc.
Oxid is polling at intervals,  it would be nice to have oxid track a directory and incorporate changes in oxid when you save config on a switch.

Instead of polling too frequently

**Comment by ytti** [comment]
Apologies if I misunderstood, but it looks like you're asking 'how can I fetch configuration when configuration changes'. You have API you can use to trigger fetch on anything you want.

Example of how to monitor for example syslog to fetch config upon config change: https://github.com/ytti/oxidized/blob/master/extra/syslog.rb

**Comment by dalamanster** [comment]
@ytti This is very interesting feature. However, it is not working for me.. I see syslogs in /var/log/messages but config poll is not triggered. 
Can you check if this is enough for running it ? 

- copy syslog.rb and rest_client.rb to extra folder
- edit oxidized config file with: 
```
syslogd:
  port: 514
```
- run " sudo setcap 'cap_net_bind_service=+ep' /usr/bin/ruby"

**Comment by wk** [comment]
The `syslog.rb` integration script includes configuration within the script, such as the specific messages that are expected, a naming map if one is necessary, as well as additional commented out configuration for reading the syslog messages from a file (where a real syslog daemon has written them) or by listening to syslog directly on a specific port (the default). 

In this specific case, it appears that you expect to read the messages from a file, but the script as-is would attempt to directly listen on the syslog port (which is currently occupied by your syslog server).

The script will require tweaking for this use case.
