### ISSUE TITLE
execution expired

### ISSUE THREAD

**Issue by itscassa** [ytti/oxidized#158]
Hi,

I'm having the issue that I'm getting the following error:
```
D, [2015-08-07T15:35:14.465733 #29678] DEBUG -- : SSH: show run-config @ hostname
W, [2015-08-07T15:36:04.466787 #29678]  WARN -- : ip raised Timeout::Error with msg "execution expired"
D, [2015-08-07T15:36:04.488229 #29678] DEBUG -- : ip raised Errno::ECONNREFUSED with msg "Connection refused - connect(2)"
W, [2015-08-07T15:36:04.846205 #29678]  WARN -- : hostname status no_connection, retries exhausted, giving up
```

I've tried to set the timeout to a higher value, but this didn't help. It would be helpful if it is possible to disable timeouts or set it to a higher value for specific commands.

**Comment by ytti** [comment]
Have you debug session for the SSH output? Since it's possible it's prompt issue? Perhaps prompt is wrongly set and it's not detecting prompt, waiting forever.

**Comment by itscassa** [comment]
The config is just too big. prompt isn't the problem.

**Comment by ytti** [comment]
So how long timeout do you need to set, for it to work? Because you said you tried setting it higher, but it didn't work, so how can you know it even will work?

**Comment by itscassa** [comment]
Hmm, seems you were right. After the command `show run-config`, it first asks to press Enter before it shows the configuration.

Is it possible to do this with a model script?

**Comment by ytti** [comment]
Yeah we have 'expect' like functionality which waits for a pattern and does an action on pattern.

However, I would first research into disabling this prompt/feature, perhaps there is a way.

If not, here is an example on how to use expect:
https://github.com/ytti/oxidized/blob/master/lib/oxidized/model/ios.rb#L7

**Comment by itscassa** [comment]
Unfortunately there is no way to disable this, so I fixed it using expect.

Thank you for your information.
