### ISSUE TITLE
Unable to fetch configuration for netscreen devices

### ISSUE THREAD

**Issue by blcak** [ytti/oxidized#1580]
Hi, 

I am fairly new to using oxidized for my organisation. The docs and tutorials got me good start thanks to the maintainers. As I was adding our old netscreen devices, I got the error which I am pretty much stuck with. Please find the error below:

oxidized     | E, [2018-10-07T10:57:38.754096 #28] ERROR -- : xx.xx.xx.xx raised NameError with msg "uninitialized constant OpenSSL::Digest::DSS1", xx.xx.xx.xx saved
oxidized     | W, [2018-10-07T10:57:58.755010 #28]  WARN -- : xx.xx.xx.xx raised Net::OpenTimeout (rescued Timeout::Error) with msg "timed out while opening a connection to the host"
oxidized     | W, [2018-10-07T10:57:59.751022 #28]  WARN -- : /some-netscreen-fw status no_connection, retry attempt 1
oxidized     | E, [2018-10-07T10:58:00.753827 #28] ERROR -- : xx.xx.xx.xx raised NameError with msg "uninitialized constant OpenSSL::Digest::DSS1", xx.xx.xx.xx saved
oxidized     | W, [2018-10-07T10:58:20.754973 #28]  WARN -- : xx.xx.xx.xx raised Net::OpenTimeout (rescued Timeout::Error) with msg "timed out while opening a connection to the host"
oxidized     | W, [2018-10-07T10:58:20.757486 #28]  WARN -- : /some-netscreen-fw status no_connection, retry attempt 2
oxidized     | E, [2018-10-07T10:58:21.757313 #28] ERROR -- : xx.xx.xx.xx raised NameError with msg "uninitialized constant OpenSSL::Digest::DSS1", xx.xx.xx.xx saved
oxidized     | W, [2018-10-07T10:58:41.758647 #28]  WARN -- : xx.xx.xx.xx raised Net::OpenTimeout (rescued Timeout::Error) with msg "timed out while opening a connection to the host"
oxidized     | W, [2018-10-07T10:58:41.763000 #28]  WARN -- : /some-netscreen-fw status no_connection, retry attempt 3
oxidized     | E, [2018-10-07T10:58:42.753781 #28] ERROR -- : xx.xx.xx.xx raised NameError with msg "uninitialized constant OpenSSL::Digest::DSS1", xx.xx.xx.xx saved
oxidized     | W, [2018-10-07T10:59:02.754769 #28]  WARN -- : xx.xx.xx.xx raised Net::OpenTimeout (rescued Timeout::Error) with msg "timed out while opening a connection to the host"
oxidized     | W, [2018-10-07T10:59:02.767890 #28]  WARN -- : /some-netscreen-fw status no_connection, retries exhausted, giving up

I searched for it in internet found someone saying, it could be some kex algorithms being deprecated in new openssl version, tried updating the net-ssh gem to 5.0.2 still the same. Any pointers on how to fix it would really be a great great great help. 
Thanks..

**Comment by wk** [comment]
You are hitting net-ssh/net-ssh#503. This is indeed solved in net-ssh 5.0.2, but unfortunately, 5.0.2 introduces a dependency on Ruby 2.2.6 (vs 2.0 for net-ssh 4.x) - which is newer than what Oxidized currently targets.

Simply installing net-ssh 5.0.2 side by side will have no effect, and removing the net-ssh 4.2.0 gem manually with break the dependency and cause oxidized to error at startup.

There are two things you can potentially do here:
* Rebuild net-ssh 4.2.0 on a system with OpenSSL < 1.1.0, and run oxidized on it.
* Build the oxidized gem from source yourself after modifying the dependency in the specfile to a newer version of net-ssh on the existing OpenSSL >= 1.1.0 system.

@ytti this issue is another case for bumping the minimum supported Ruby version.

**Comment by blcak** [comment]
Thanks @wk for the help I just build the oxidized with Dockerfile before the phusion was bumped up to version 0.11 and it is working great.

**Comment by rbrayner** [comment]
I have forked the oxidized repo and created an older branch. This Dockerfile worked to me, using the phusion/baseimage:0.10.1 version:

https://github.com/rbrayner/oxidized/tree/older

**Comment by klinnex** [comment]
Hi, I have the same issues with the docker images.

Can you update the docker ?

**Comment by cron410** [comment]
I can confirm the provided Docker container by @rbrayner does work as expected. Thank you!
