### ISSUE TITLE
Not working with HP Switch 5406zl (J8697A)

### ISSUE THREAD

**Issue by aratnikovmxmgt** [ytti/oxidized#1581]
Greetings!
Right now I have an issue that do not allow me to grab configuration via oxidized.
Product Name: HP Switch 5406zl (J8697A)
Version: K.15.16.0005, ROM K.15.30
Configuration in router.db looks like that
`ip_address:procurve:::Group_1`
```
W, [2018-10-08T11:02:41.493316 #3173]  WARN -- : ip_address raised IOError with msg "closed stream"
W, [2018-10-08T11:03:01.463725 #3173]  WARN -- : ip_address raised Oxidized::PromptUndetect with msg "unable to detect prompt: (?-mix:^\r?([\w.-]+# )$)"
W, [2018-10-08T11:03:01.934399 #3173]  WARN -- : Group_1/ip_address status no_connection, retry attempt 1
```
Same happens with:
HP Switch 5406Rzl2 (J9850A)
KB.15.16.0006, ROM KB.15.01.0001

3 devices and same problem. 
Work fine in rancid with `ip_address;hp;up`

**Comment by Noname2244** [comment]
I have a similar problem
This is from the log file for that host:

```
HP J9850A Switch 5406Rzl2

Software revision KB.16.05.0007



 (C) Copyright 2018 Hewlett Packard Enterprise Development LP

                      RESTRICTED RIGHTS LEGEND
 Confidential computer software. Valid license from Hewlett Packard Enterprise
 Development LP required for possession, use or copying. Consistent with FAR
 12.211 and 12.212, Commercial Computer Software, Computer Software
 Documentation, and Technical Data for Commercial Items are licensed to the
 U.S. Government under vendor's standard commercial license.

^[[1;13r^[[1;1H^[[24;1HPress any key to continue^[[13;1H^[[?25h^[[24;27H
```

**Comment by davama** [comment]
I've been curious about this post...

```
W, [2018-10-08T11:03:01.463725 #3173]  WARN -- : ip_address raised Oxidized::PromptUndetect with msg "unable to detect prompt: (?-mix:^\r?([\w.-]+# )$)"
```
Found that usually when i cannot backup an `HP` switch it is because of my configured `banner`(s). If they have an empty space [` `]  which causes oxidized to complain.

Im still testing myself but just quickly i was able to backup on some of my models but not all

|Model | pass | fail |
| ---- | ---- | ---- |
|HP J8692A Switch 3500yl-24G | x | |
|HP J8693A Switch 3500yl-48G | x | |  
|HP J8697A Switch 5406zl | x |  |
|HP J8698A Switch 5412zl | x  |  |
|HP J9310A Switch 3500yl-24G-PoE+ | x |  |  
|HP J9311A Switch 3500yl-48G-PoE+ |   | x |
|HP J9471A Switch 3500-24-PoE |   | x | |
|HP J9573A 3800-24G-PoE+-2SFP+ | x |  
|HP J9574A 3800-48G-PoE+-4SFP+ |   | x |

Will try to figure out the failed ones....

**Comment by WiXZlo** [comment]
@davama Try to use ssh.rb from version 0.21. In new version I have same troubles with procurve models. (https://github.com/ytti/oxidized/issues/1436)

**Comment by davama** [comment]
@WiXZlo that's an interesting thread. I vaguely remember it, will give it a shot and see what happens.
But before i do ill see if i can solve the failed ones without v0.21 

Thanks for the info

**Comment by davama** [comment]
Well...with those failed ones it works now...cant say it was the same switches i tried but i did updated my oxidized to the latest

**Comment by Ondjultomte** [comment]
I had a similar issue with Aruba switches, I solved it by updating to 0.24 and changing model from aruba to procurve.

**Comment by azharkamal** [comment]
could you some body here tell me how to upagred ssh.rb

**Comment by WiXZlo** [comment]
> 
> 
> could you some body here tell me how to upagred ssh.rb

https://github.com/ytti/oxidized/issues/1607#issuecomment-441173641

**Comment by eduardocalfaia** [comment]
Hi Guys,
I have the same issue. May you have any solution for this?
aised Oxidized::PromptUndetect with msg "unable to detect prompt: (?-mix:^\r?([\w\s.-]+# )$)"

Thanks

**Comment by deajan** [comment]
I had success with elder HP switches using this: https://github.com/ytti/oxidized/issues/1422#issuecomment-516422450
