### ISSUE TITLE
ssh-proxy issue

### ISSUE THREAD

**Issue by frederic-loui** [ytti/oxidized#1582]
Hi all,

I'm opening this issue as I could not find suitable answer via my favorite search engine.
I’m struggling to make ssh_proxy to work but It seems that this is more tricky than expected.

Therefore, all the questions:

1- I have a bastion server that can access to my routers.
    This server can be accessed using <bastion-server-login> with <bastion-server-password> 
    I’m using oxidized and use the ssh_proxy and set it to <bastion-server-ip> as per the documentation. 
    But I don’t know where to put the <bastion-server-user-login> and the <bastion-server-user-password> in oxidized config file.
    my bastion is accessible via (SSH pubkey, SSH password) method
    my router are accessible via (SSH password) method though

2- I tried to remove the login/password using SSH priv/pub key pair toward the bastion. And it is so far working.
   I would like to config so that my bastion is accessed via SSH key but my router are accessed via password.
   But I could not find the relevant resources using my google skills

Looking at the log my oxidized is stuck trying SSH password method toward the Bastion (which is the proxy_ssh)

I can of course give you the logs if needed … But did not want to clutter this request.

Thanks for this piece of software !

all the best
Frederic

**Comment by frederic-loui** [comment]
Hi again,

I think that I nailed the issue, (but not sure if all the conditions i'm listing are involved:)
1- According to log, oxidized is using "ssh -W host:port" trigger
2- When I' using this trigger manually via ssh using CLI, the connection "hang" at the final host.
     Authentication via proxy (empty key passphrase) is working though.
3- According to resource in the web, "-W host:port" trigger might not work as the option appeared in 5.4
4- In addition to that, not sure if this is another issue, my oxidized host is behind a firewall using a NAT(ed) address and for sone reason, routers does not populate the IP HEADER as expected and SSH hangs.

However, the proxy connection is OK with SSH jump syntax, "-J user@jumpserver" i'll test this using the this then and get back to you.

PS: These are some thoughts, if you think you have already experience the issue please let me know :-)

All the best 
Frederic

**Comment by frederic-loui** [comment]
EDIT: Found the issue. (Silly question --> silly mistake)
I ran oxidized in container form and of course I did not put the SSH key during container run time.
So this led Oxidized kept asking me the password for the SSH PROXY server. I mention it as I might not be the only person with that ... If you want to test Oxidized with docker, test SSH from the container itself. 

One last question though, i administratively did manage to use key in order to get on the jump server.
In case password method is only allowed, is there a way to specify SSH login/password for the proxy server somewhere ?

With this problem, I had to learn ruby and study the code, which is OK regarding SSH connection.
Thanks then !

In absence of answer to my question you can close this issue. 👍

**Comment by roedie** [comment]
@frederic-loui You can specify the username using username@some.proxy.host but AFAIK you cannot specify the password.

**Comment by frederic-loui** [comment]
Hi @roedie. Thanks for your answer !
