### ISSUE TITLE
How can I get data from device's config and update node's msg with it?

### ISSUE THREAD

**Issue by myclau** [ytti/oxidized#1586]
I want to change the commit message with who last modify

So I am trying to get the last modify before it save to git
```Ruby
cmd 'show version | include modified' do |cfg|
      puts "===> message"
      puts cfg
      @message=cfg
      
end
```
Next I need to send a PUT request to `http://localhost:8888/node/next/#{@node.name}`
with `{msg: #{@message}}`

but I did not know how can I do it, are there any way to do it?

**Comment by laf** [comment]
You need to call the API. This has been asked before so I suggest taking a look at old issues, i.e: https://github.com/ytti/oxidized/issues/516
