### ISSUE TITLE
Junos issue: ArgumentError with msg "invalid byte sequence in UTF-8"

### ISSUE THREAD

**Issue by frederic-loui** [ytti/oxidized#1587]
(PS: I'm not sure how to re-open an issue so that i created a new one)

Hi, I'm reopening issue [https://github.com/ytti/oxidized/issues/1203](url) re-open this issue as I tested the "utf8_encoded: trigger and I still get this error: 

Junos issue: raised ArgumentError with msg "invalid byte sequence in UTF-8", saved.

What is strange is that in the code I have in "model.rb":
out = out.b unless Oxidized.config.input.utf8_encoded?

--> This should means: if "utf8_encoded" is true then don't do "out = out.b" (so the config is utf8 encoded?) else "out = out" ("out = out")

My question is: Does "out = out" means that the config is not utf8 encoded and has to be treated as binary ?

Sorry if this is a stupid question but I tried both values for utf8_encoded in config global section and still got the error.

Therefore in the end how to I treat the config as binary in ruby ?

Thanks !
Frederic

**Comment by ytti** [comment]
It's not global, it's under ```input```. Setting it to ```false``` means we force encoding to be binary blob, by default it's ```true``` which means we assume encoding is UTF8.

**Comment by frederic-loui** [comment]
Oh ... Thanks for your answer... I real the code too quickly !
