### ISSUE TITLE
Qxidized - can’t logon with Radius user 

### ISSUE THREAD

**Issue by lill-peter** [ytti/oxidized#1589]
Hi,
Is there any one how get Oxidized to work with a Radius user account?
I have tried different setting in router.db for example
1.
#Switches
10.10.0.10:aos:user@domain:password

#Switches
10.10.0.10:aos:domain\user:password

When I do a simple Putty SSH session I use this login credentials
domain\user

**Comment by ytti** [comment]
Try double \\

**Comment by lill-peter** [comment]
I change the Connection Request Policy on the MS Network Policy Server. 
Connection-------------Value  
User Namn ------------(domain)\\(su-)\w+

to 
User Namn ------------(su-)\w+
