### ISSUE TITLE
Several Beginner's Questions

### ISSUE THREAD

**Issue by MarcusCaepio** [ytti/oxidized#1600]
Hi all,
I started with oxidized this morning and I have the basic running ( I guess).
But I have several questions for the further working.
First of all, this is my config, for reference:

```
---
interval: 3600 #interval in seconds
log: ~/.config/oxidized/log
debug: false
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
crash:
  directory: ~/.config/oxidized/crashes
  hostnames: false
rest: 1.2.3.4:8888
pid: ~/.config/oxidized/oxidized.pid
groups: {}
input:
  default: ssh
  debug: true
  ssh:
    secure: false
output:
  default: git
  git:
    user: Oxidized
    email: o@example.com
    repo: "~/cisco-configs.git"
source:
  default: csv
  csv:
    file: ~/.config/oxidized/router.db
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
      username: 2
      password: 3
    vars_map:
      enable: 4
models:
  ios:
    username: myuser
    password: mypass
  asa:
    username: myuser
    password: mypass
    vars:
      enable: myenapass
hooks:
  push_to_remote:
    type: githubrepo
    events: [post_store]
    remote_repo: git@mygitlabserver:myproject/cisco-configs.git
    publickey: /home/oxidized/.ssh/id_rsa.pub
    privatekey: /home/oxidized/.ssh/id_rsa
```
And my router.db:
```
fw1:asa
switch1:ios
```

Here are my questions:
1) My output is ~/cisco-configs.git. A ls -l on this dir gives me:
```
-rw-rw-r-- 1 oxidized oxidized  233 Okt 19 11:22 config
-rw-rw-r-- 1 oxidized oxidized   73 Okt 19 11:22 description
-rw-rw-r-- 1 oxidized oxidized  111 Okt 19 11:22 FETCH_HEAD
-rw-rw-r-- 1 oxidized oxidized   23 Okt 19 11:22 HEAD
drwxrwxr-x 2 oxidized oxidized 4096 Okt 19 11:22 hooks
-rw-rw-r-- 1 oxidized oxidized  153 Okt 19 11:22 index
drwxrwxr-x 2 oxidized oxidized 4096 Okt 19 11:22 info
drwxrwxr-x 9 oxidized oxidized 4096 Okt 19 11:37 objects
drwxrwxr-x 5 oxidized oxidized 4096 Okt 19 11:22 refs
```
Where are the real device's config files stored? As I am pushing them to my remote gitlab repo, where the files are pushed with <devicename>, I cannot find them on my local server
2)
I have oxidized running as service via the systemctl script. When I add a router to the router.db, what do I have to do, to make this active? Restart the service? Click reload in the webgui? Is there a way to have an auto reload on change of router.db?
3)
What happens with devices, which are deleted in the router.db file? A first step did nothing with the old files in the remote git repo. Is this correct? If yes, how can I enable auto delete in the remote repo, when I delete a device in router.db?

Thanks in advance!

**Comment by davama** [comment]
@MarcusCaepio 

> Where are the real device's config files stored? As I am pushing them to my remote gitlab repo, where the files are pushed with , I cannot find them on my local server

Are you familiar with git? if you do a `git show` it will show you the last commit on your git repo.
`git ls-tree HEAD` will show you your objects and their hash. you can then `git show <hash>` to see the contents of the objects. We use a web frontend to view all our git repos `cgit`

> I have oxidized running as service via the systemctl script. When I add a router to the router.db, what do I have to do, to make this active? Restart the service? Click reload in the webgui? Is there a way to have an auto reload on change of router.db?

Yes, restart the service when your db updates

> What happens with devices, which are deleted in the router.db file? A first step did nothing with the old files in the remote git repo. Is this correct? If yes, how can I enable auto delete in the remote repo, when I delete a device in router.db?

Nothing, the object remains. If you want to delete the object from git then you will have to handle that with git. There was an issue here that discussed that. I would search for it or just google it.

hope this is useful

**Comment by MarcusCaepio** [comment]
Hey @davama thanks a lot for the answers.
I just found out, that a simple git clone of my ".git" also show the plain files.
And in my gitlab the files are also shown,  so I am fine with it (I just started with git a few time ago. So I am just a little familiar yet :D ). 

Last question for now: 
When I delete a file in my remote gitlab (which is automatically a commit) could this be a problem for the local oxidized git? If I think right, oxi has to pull the remote repo first, then do the changes, commit and push again. Does it do this?

**Comment by lwillek** [comment]
Hey @MarcusCaepio,
Actually, you just push any local change into your remote git: as long as the remote repository allows that, everything is fine. (i.e. this is not a oxidized question, this is more a general git question. Maybe https://git-scm.com/book/en/v2 helps you)

Regarding your first question "Where are the real device's config files stored?", @davama gave excellent answers (its just git). I had exact the same question/problem in the beginning and this is how I solved it:

relevant config snippet:
```
...
output:
  default: git
  git:
      user: Oxidized
      email: oxidized@example.com
      repo: "~/.config/oxidized/git"
hooks:
  dump_config:
    type: exec
    events: [post_store]
    cmd: "/home/oxidized/.config/oxidized/dump_config.sh"
    timeout: 10
  push_to_remote:
    type: githubrepo
    events: [post_store]
    ...
```
and this is the file `/home/oxidized/.config/oxidized/dump_config.sh`:
```
#!/usr/bin/env bash
set -o errexit
oxidized_repo="~/.config/oxidized/git/"
switch_config="~/switchconfig/"
echo "[dump config] clone from local bare git "
mkdir -p  ${switch_config}/.git
rsync -a --delete-during ${oxidized_repo}  ${switch_config}/.git
cd  ${switch_config}
git config --local --bool core.bare false
git reset --hard
echo "[dump config] completed"
```

hth, have fun
