### ISSUE TITLE
raised Net::SSH::AuthenticationFailed with msg "Authentication failed for user admin

### ISSUE THREAD

**Issue by firozsahib** [ytti/oxidized#1601]
Getting the below error for arista switches.

raised Net::SSH::AuthenticationFailed with msg "Authentication failed for user admin.

Credentials are working if we try to login separately.

This is how I am giving the model map
model_map:
  nexus: nxos
  pa: panos
  arista: eos

Thanks,
Firoz

**Comment by ytti** [comment]
Have you seen this? https://github.com/ytti/oxidized/blob/master/docs/Model-Notes/EOS.md

**Comment by rasssta** [comment]
Out of curiosity. Why was keyboard-interactive removed from default allowed methods in oxidized? It was working in 0.21 but not working in 0.25 (until adding it manually as allowed).

**Comment by wk** [comment]
See discussion [here](https://github.com/ytti/oxidized/issues/1414#issuecomment-399517607).
