### ISSUE TITLE
Repeated adding/deleting whole configurations

### ISSUE THREAD

**Issue by facyber** [ytti/oxidized#1603]
Hello everyone.

We are trying to move from RANCID to Oxidized and we successfully migrated RANCID history and configs from SVN to Git and Oxidized and we integrated it with the LibreNMS, but strange thing happens. At each cycle, Oxidized for some random Cisco routers and switches fetch configuration like it was deleted and at next cycle, it adds it back. For example:

One cycle:

```
-version 15.3
-no service pad
-service tcp-keepalives-in
-service tcp-keepalives-out
-service timestamps debug datetime msec localtime show-timezone
-service timestamps log datetime msec localtime show-timezone
-service password-encryption
-service sequence-numbers
...and so on till the end.
```

Next cycle:

```
+version 15.3
+no service pad
+service tcp-keepalives-in
+service tcp-keepalives-out
+service timestamps debug datetime msec localtime show-timezone
+service timestamps log datetime msec localtime show-timezone
+service password-encryption
+service sequence-numbers
...and so on till the end.
```

This is happening only for Routers and Switches, not for WLCs and Firewalls. I noticed #468 is similar issue but instead of the whole configuration, in that issue they had problem with only two line of codes and our issue is not periodic, but at each cycle which is 1 hour.

Anyone knows what could cause this issue?

Here's our configuration file:

```
username: **********
password: **********
model: ios
resolve_dns: true
interval: 3600
use_syslog: false
debug: false
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 127.0.0.1:5148
next_adds_job: false
vars: {}
groups: {}
models: {}
pid: "/var/lib/oxidized/pid"
stats:
  history_size: 10
input:
  default: ssh, telnet
  debug: false
  ssh:
    secure: false
  ftp:
    passive: true
  utf8_encoded: true
output:
  default: git
  git:
    user: Oxidized
    email: **********
    repo: "/var/lib/oxidized/git-repos/default.git"
source:
  default: http
  debug: false
  http:
    url: https://**********/api/v0/oxidized
    map:
      name: hostname
      model: os
      group: group
    headers:
      X-Auth-Token: '**********'
model_map:
  cisco: ios
  ciscowlc: aireos
  pfsense: pfsense
hooks:
  success_output:
      type: exec
      events: [post_store]
      cmd: '/var/lib/oxidized/oxidized-report-git-commits >> /var/lib/oxidized/reports/success/${OX_NODE_GROUP}'
      async: true
      timeout: 120
  fail_output:
      type: exec
      events: [node_fail]
      cmd: '/var/lib/oxidized/oxidized-report-git-commits >> /var/lib/oxidized/reports/fail/${OX_NODE_GROUP}'
      async: true
      timeout: 120
  success_send:
      type: exec
      events: [nodes_done]
      cmd: '/var/lib/oxidized/oxidized-email-report'
      async: true
      timeout: 120
```

**Comment by facyber** [comment]
What could be the cause of this? Some specific command/feature or maybe something with Oxidized configuration file?

Any suggestions how to avoid this?

**Comment by ytti** [comment]
Would need to troubleshoot to know. You could turn on input debugging and then monitor the file on each run with tail -f, to determine what is actually read from terminal. This will narrow the problem, do we actually see the output but just not catch it or do we not even see the the output.

**Comment by facyber** [comment]
I just noticed I forgot to send comment, I just typed it yesterday...

I executed **tail -f *** in log folder and watched in other terminal systemctl process when will update some device, but when it did I haven't noticed anything strange, any warning or similar. One of the latest updates were:

```
-!
-! No configuration change since last restart
-version 15.3
-no service pad
-service tcp-keepalives-in
-service tcp-keepalives-out
-service timestamps debug datetime msec localtime show-timezone
-service timestamps log datetime msec localtime show-timezone
-service password-encryption
-service sequence-numbers
...
```
```
+!
+! No configuration change since last restart
+version 15.3
+no service pad
+service tcp-keepalives-in
+service tcp-keepalives-out
+service timestamps debug datetime msec localtime show-timezone
+service timestamps log datetime msec localtime show-timezone
+service password-encryption
+service sequence-numbers
+!
...
```

**Comment by ytti** [comment]
Did you turn input debugging on, and watched file on the name of the device? Which contains the input that ssh/telnet is reading from the device. 

That is what we need to know. We need to know did we get the correct data in both iterations, or did we not see the config at all.

**Comment by facyber** [comment]
Yes, debugging was on for input.

I just followed couple of devices's logs and I noticed that sometimes when Oxidized connects on device, it doesn't enter into **Enable mode** like it should, but in **User EXEC mode** and from there it can not execute **show running-config** command and it just exit and sees as the configuration is deleted because it didn't fetch any configuration.

Output:

```
router_name>show running-config
                  ^
% Invalid input detected at '^' marker.

router_name>exit
```

I checked this with some other devices who showed up in the last cycle and it is the same thing it first tries ssh and it generates the top message in _<ip_address>-ssh_ file in log folder, and then there is _<ip_address>-telnet_ file but in it is only banner message, then the following output and that's it.

```
User Access Verification

Username: <username>
Password:
```
I also tried to all those devices connect via ssh and the same username from Oxidized config file and everything is allright, it instantly puts me in Enable mode.

I presume when the next cycle come, it successfully connects to device and enters into Enable mode and then fetch configuration and reads it as a new configuration.

Could there be some problem with Cisco IOS, or maybe there are too many devices and it didn't had enough time or something to connect to Enable mode?

**Comment by ytti** [comment]
Perhaps observe what happens on next run too.

Do you have enable password defined for the device?

**Comment by ytti** [comment]
Maybe your TACACS authorisation fails sometimes, and doesn't get autoenabled? Perhaps if you try manually multiple times with Oxidized credentials, you may be able to reproduce it.

**Comment by facyber** [comment]
I am looking at a log for one file that now just updated and everything is fine, it goes straight to Enable mode and execute successfully all commands.

I also tried to manually multiple times ssh (with Oxidized credentials ofc), but I can't reproduce it, every time I logged in, it puts me straight in Enable mode.

I thought also that maybe TACACS is making some problems, because AAA is used to access the devices, but as I don't have access to TACACS servers I can't see it's logs. I will to try to ask somebody who have to check them.

Do you have any other suggestion what might be or what should I try/debug next?

**Comment by facyber** [comment]
As far as I know it goes straight to Enable mode, no `enable` command is executed, so I agree that there is some problem with Cisco as this happens only for Cisco devices, but not for firewalls for example.

Capturing traffic/logs on TACACS is next thing to try then. Thanks!

**Comment by ytti** [comment]
If it's Cisco's fault you should be able to recreate this without Oxidized. Perhaps rate-issue? Too many requests at the same time and TACACS is not responding?

**Comment by facyber** [comment]
Sorry for late answer, I haven't got email notification for your reply which is weird.

I am not sure how to recreate this without Oxidized.

Too many requests could be a cause, but we are using RANCID and we don't have problem like this one, but then again it is limited to network devices only, not the firewalls too.

**Comment by facyber** [comment]
Hi @ytti 

Just wanted to say that we "solved" the problem. It's more of a detour than an actual solution.

Since we couldn't determine why this problem still occurred, and we noticed that it only occur in user EXEC mode from which it can not execute command `show running-config`, in the ios.rb model we deleted the "**>**" from the second line so it looks like this right now:

`prompt /^([\w.@()-]+[#]\s?)$/`

Since command can be executed only from privileged mode, there is no need to execute anything from user EXEC mode.

It is not the best way but it is sort of a solution that works for us. We will leave it this way for couple of days for testing purposes, but for now this works.

**Comment by timwsuqld** [comment]
We're also having this issue. It would be good if we could configure oxidized to have a minimum config size, so if something less is returned (like an empty file) we know that it's invalid.

**Comment by ytti** [comment]
This is certainly something you could do, if you'd extend distribution model with your own. You could either hardcode in the model raise "too short config" if cfg.size < 1234. Or even raise "too short config" if cfg.size < vars(ios_minimum_config_size).

**Comment by timwsuqld** [comment]
@ytti would you be ok with a patch that could apply this globally? I feel most people would want their config to not suddenly disappear when an issue occurs, and so being able to apply this to all models would allow them to set a threshold of minimum config sizes.

**Comment by ytti** [comment]
probably, you'd likely want to subclass some exception like ShortConfig, Config, OxidizedError, Exception. Then you'd probably want to rescue it appropriately and log it.
