### ISSUE TITLE
Unable to start oxidized

### ISSUE THREAD

**Issue by rygumcmxci** [ytti/oxidized#1604]
OS: CentOS 7 | Nginx

I have LibreNMS w/ Oxidized setup up and working on a physical server in our test environment and now I am moving this to a VM for production. 

Oxidized is integrated with LibreNMS up and running on my physical server (no issues at all), LibreNMS is the source and oxidized automatically adds devices for back ups when they are added to LibreNMS. 

LibreNMS is setup up on the VM and functioning fine and during the install of Oxidized I am receiving this error: 

[oxidized@oxidized ~]$ systemctl status oxidized -l
â— oxidized.service - Oxidized - Network Device Configuration Backup Tool
   Loaded: loaded (/etc/systemd/system/oxidized.service; disabled; vendor preset: disabled)
   Active: inactive (dead)

Oct 24 12:32:49 oxidized.twg.pvt systemd[1]: Started Oxidized - Network Device Configuration Backup Tool.
Oct 24 12:32:49 oxidized.twg.pvt systemd[1]: Starting Oxidized - Network Device Configuration Backup Tool...
Oct 24 12:32:49 oxidized.twg.pvt oxidized[15086]: I, [2018-10-24T12:32:49.330376 #15086]  INFO -- : Oxidized starting, running as pid 15086
Oct 24 12:32:49 oxidized.twg.pvt oxidized[15086]: I, [2018-10-24T12:32:49.331005 #15086]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
Oct 24 12:32:49 oxidized.twg.pvt oxidized[15086]: F, [2018-10-24T12:32:49.331116 #15086] FATAL -- : Oxidized crashed, crashfile written in /root/.config/oxidized/crash
Oct 24 12:32:49 oxidized.twg.pvt oxidized[15086]: No such file or directory - /root/.config/oxidized/router.db
[oxidized@oxidized ~]$ 

CRASH FILE: 

[oxidized@oxidized ~]$ sudo cat /root/.config/oxidized/crash
[sudo] password for oxidized: 
--------------------------------------------------
2018-10-24 19:32:49 UTC
No such file or directory - /root/.config/oxidized/router.db [Errno::ENOENT]
--------------------------------------------------
/usr/local/share/gems/gems/oxidized-0.24.0/lib/oxidized/source/csv.rb:28:in `initialize'
/usr/local/share/gems/gems/oxidized-0.24.0/lib/oxidized/source/csv.rb:28:in `open'
/usr/local/share/gems/gems/oxidized-0.24.0/lib/oxidized/source/csv.rb:28:in `load'
/usr/local/share/gems/gems/oxidized-0.24.0/lib/oxidized/nodes.rb:15:in `block in load'
/usr/local/share/gems/gems/oxidized-0.24.0/lib/oxidized/nodes.rb:128:in `synchronize'
/usr/local/share/gems/gems/oxidized-0.24.0/lib/oxidized/nodes.rb:128:in `with_lock'
/usr/local/share/gems/gems/oxidized-0.24.0/lib/oxidized/nodes.rb:10:in `load'
/usr/local/share/gems/gems/oxidized-0.24.0/lib/oxidized/nodes.rb:123:in `initialize'
/usr/local/share/gems/gems/oxidized-0.24.0/lib/oxidized/core.rb:14:in `new'
/usr/local/share/gems/gems/oxidized-0.24.0/lib/oxidized/core.rb:14:in `initialize'
/usr/local/share/gems/gems/oxidized-0.24.0/lib/oxidized/core.rb:4:in `new'
/usr/local/share/gems/gems/oxidized-0.24.0/lib/oxidized/core.rb:4:in `new'
/usr/local/share/gems/gems/oxidized-0.24.0/lib/oxidized/cli.rb:12:in `run'
/usr/local/share/gems/gems/oxidized-0.24.0/bin/oxidized:8:in `<top (required)>'
/usr/local/bin/oxidized:23:in `load'
/usr/local/bin/oxidized:23:in `<main>'
--------------------------------------------------
[oxidized@oxidized ~]$ 

My Config: 

* Anything in all caps is a variable that I changed due to it being sensitive data

https://pastebin.com/TxZnqmTs

CURL: 

I ran curl with my auth token and everything was fine. 

curl -H 'X-Auth-Token: YOUR_TOKEN' https://YOUR_URL/api/v0/oxidized

Any help or insight is much appreciated.

**Comment by laf** [comment]
The fact that output says you're using a file as the source it looks like you've got more than one config file.

Check `~/.config/oxidized/config` and `/etc/oxidized/config`

**Comment by rygumcmxci** [comment]
Thanks for the quick response laf, I did some digging in the system and found a second config file (don't know how it got there). 

After removing it and restarting everything I was able to get Oxidized started. 

Thanks.
