### ISSUE TITLE
[FR] Ability to change passwords on switches (aka execute custom commands)

### ISSUE THREAD

**Issue by paszczus** [ytti/oxidized#1606]
Hi,
Since oxidized is able to execute commands to pull configurations from switch, it would be extremely helpful to execute custom commands, for example to automate process of password retention on some switches. Example for Cisco switch:

ssh to switch
username/password or key
configure terminal
username [foo] privilege 15 password 0 [password]
end
write mem

Is there an option to add this feature ?

**Comment by wk** [comment]
A separate project [`oxidized-script`](https://github.com/ytti/oxidized-script) that builds upon elements of Oxidized exists to facilitate remote command execution.

The project scope of Oxidized itself is that of a configuration differ, and it is an explicit design goal for it not to alter the state of devices - as well as to execute comfortably with read-only privileges.
