### ISSUE TITLE
Procurve oxidized

### ISSUE THREAD

**Issue by NextOne86** [ytti/oxidized#1607]
Hi guys, I got this issue: 
 WARN -- : 0.0.0.0 raised Oxidized::PromptUndetect with msg "Your previous successful login (as manager) was on 2018-10-26 16:47:15
 from 0.0.0.0
switchName#  not matching configured prompt (?-mix:^\r?([\w.-]+# )$)"

It seems I get access to the switch but then nothing....
------------------------------------------------------------------------------
My configuration:

username: name
password: pass
model: Procurve
interval: 3600
use_syslog: false
debug: false
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 127.0.0.1:8888
next_adds_job: false
vars: {}
groups: {}
models: {}
pid: "/home/oxidized/.config/oxidized/pid"
input:
  default: ssh
  debug: true
  ssh:
    secure: false
output:
  file:
    directory: "/home/oxidized/deviceconfigs"
source:
  default: csv
  csv:
    file: "/home/oxidized/.config/oxidized/router.db"
    delimiter: !ruby/regexp /:/
    map:
      ip: 0
      model: 1
      username: 2
      password: 3
model_map:
  hp: Procurve
--------------------------------------------------------------------------------
router.db:

#Switches
1.1.1.1:procurve:user:password

**Comment by NextOne86** [comment]
This is what I got from the debug:
W, [2018-10-29T15:28:46.168267 #34901]  WARN -- : 10.4.0.36 raised Oxidized::PromptUndetect with msg "Your previous successful login (as manager) was on 2018-10-29 15:26:03
 from 10.4.96.21
FD_PS/D#  not matching configured prompt (?-mix:^\r?([\w.-]+# )$)"
D, [2018-10-29T15:28:46.168319 #34901] DEBUG -- : lib/oxidized/node.rb: Oxidized::SSH failed for
D, [2018-10-29T15:28:46.168351 #34901] DEBUG -- : lib/oxidized/job.rb: Config fetched for  at 2018-10-29 14:28:46 UTC
W, [2018-10-29T15:28:46.473552 #34901]  WARN -- :  status no_connection, retry attempt 2
D, [2018-10-29T15:28:46.473607 #34901] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 0 of 1
D, [2018-10-29T15:28:46.473660 #34901] DEBUG -- : lib/oxidized/worker.rb: Added  to the job queue
D, [2018-10-29T15:28:46.473815 #34901] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2018-10-29T15:28:46.473751 #34901] DEBUG -- : lib/oxidized/job.rb: Starting fetching process for  at 2018-10-29 14:28:46 UTC
D, [2018-10-29T15:28:46.473991 #34901] DEBUG -- : AUTH METHODS::["none", "publickey", "password"]
D, [2018-10-29T15:28:46.474023 #34901] DEBUG -- : lib/oxidized/input/ssh.rb: Connecting to
D, [2018-10-29T15:28:47.211294 #34901] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^\r?([\w.-]+# )$/] at
D, [2018-10-29T15:28:47.473916 #34901] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2018-10-29T15:28:48.474063 #34901] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2018-10-29T15:28:49.474206 #34901] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
Any Idea?

**Comment by systeembeheerder** [comment]
What is the make and model of the switch? Can you ssh into the switch?

**Comment by NextOne86** [comment]
The model is: hp procurve 5412zl
Yes I can ssh into it.

**Comment by aratnikovmxmgt** [comment]
We have similar problem with 5406zl [Link to the issue on GitHub](https://github.com/ytti/oxidized/issues/1581)

**Comment by mrplow87** [comment]
Does it work if you use ```ssh.rb``` from v0.21? https://github.com/ytti/oxidized/issues/1436

**Comment by NextOne86** [comment]
> Does it work if you use `ssh.rb` from v0.21? #1436

Where can I take the old version?

Thanks

**Comment by WiXZlo** [comment]
> Where can I take the old version?
> 
> Thanks

Download archive from https://github.com/ytti/oxidized/releases
or
``
gem install oxidized -v 0.21
``

**Comment by NextOne86** [comment]
> > Where can I take the old version?
> > Thanks
> 
> Download archive from https://github.com/ytti/oxidized/releases
> or
> `gem install oxidized -v 0.21`

Thank you. Do I need to enable it or it will be set automatically instead of the 0.24?

**Comment by martinohansen** [comment]
The issue is present in both 0.21 and the latest version of Oxidized 0.25.1

Did anyone manage to solve this issue? Thanks.

**Comment by cdshow** [comment]
Something is wrong in your prompt detection regex as the debug log says it is looking for: /^\r?([\w.-]+# )$/
The config you posted says : /^([\w.@-]+[#>]\s?)$/
The regex it is using likely is overiding your config prompt with data from the Procurve.rb file.
The regex that is being used does not match: sky-blwsw01-hp>

I think if you change the prompt regex in the procurve.rb file you will fix your issue.
If not post a sanitized ssh log from the device as well as the procurve.rb file being used.
------
I was running into an issue on our HP Procurve 1920S switches.  I solve this portion of my problem by creating a new hpe.rb and using the following regex prompt detection:
prompt /^\r?([\(\)\w\s-]+[>|#])$/

I don't know if that would help you or not.  Looks very similar to your regex except for the possibility of the ( and ) characters.

**Comment by berilslv** [comment]
> Something is wrong in your prompt detection regex as the debug log says it is looking for: /^\r?([\w.-]+# )$/
> The config you posted says : /^([\w.@-]+[#>]\s?)$/
> The regex it is using likely is overiding your config prompt with data from the Procurve.rb file.
> The regex that is being used does not match: sky-blwsw01-hp>
> 
> I think if you change the prompt regex in the procurve.rb file you will fix your issue.
> If not post a sanitized ssh log from the device as well as the procurve.rb file being used.
> 
> I was running into an issue on our HP Procurve 1920S switches. I solve this portion of my problem by creating a new hpe.rb and using the following regex prompt detection:
> prompt /^\r?([()\w\s-]+[>|#])$/
> 
> I don't know if that would help you or not. Looks very similar to your regex except for the possibility of the ( and ) characters.

Try'd your suggestion. Still it's not working. Im facing the same for ARUBA device. But this issue appears only when i try to check config as operator. When i set manager credentials @ router.db , oxidized fetches config succesfully!
My DEBUG when running operator:operator: 
https://pastebin.com/ZmBv29ef
DEBUG when entering credentials manage:manager
https://pastebin.com/GGLy1yVa 

maybe author have the same issue, that permissions is not allowing to fetch conf?
And yes, how can i make operator fetch config? Setting manager access is not that secure...

**Comment by cdshow** [comment]
Can you also send the logs\#.#.#.#-ssh for the relevant failing switch BOTH for operator:operator and also for manager:manager?  I don't need to know the IP but do need the contents of that file.

You may have to have debug enabled for the ssh log to be written I don't recall off hand.  That **should** show what is happening in the actual ssh session for each login.

Chris

**Comment by cdshow** [comment]
From the log you sent, this shows that when logging in as operator it is likely a different prompt:
D, [2019-02-15T14:48:05.894759 #25206] DEBUG -- : lib/oxidized/input/ssh.rb s33kr3t @ ARUBA2530 8G PoEE with expect: /^([\w.@-]+[#>]\s?)$/
D, [2019-02-15T14:48:05.894921 #25206] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^([\w.@-]+[#>]\s?)$/] at ARUBA2530 8G PoEE
D, [2019-02-15T14:48:06.493006 #25206] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
...
... continues until timeout

Compare that to what happens on manager: manager
D, [2019-02-15T14:50:34.260018 #25463] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^([\w.@-]+[#>]\s?)$/] at ARUBA2530 8G PoEE
D, [2019-02-15T14:50:34.546512 #25463] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2019-02-15T14:50:35.547441 #25463] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2019-02-15T14:50:35.982794 #25463] DEBUG -- : lib/oxidized/input/cli.rb: **Running post_login commands at ARUBA2530 8G PoEE**

When you just ssh as operator what is the login prompt after login look like?  Same for manager?  This Regex /^([\w.@-]+[#>]\s?)$/ has to match the prompt to let the script continue with post_login and other commands.  
https://www.regextester.com/
Manually ssh into each system and look at the prompt for both operator vs manager and paste the output in the the regextester's test string section.  Alternately you may need to use ssh -vX user@ip to see a FULLY verbose output of what ssh is doing from the source machine to the destination.

**Comment by berilslv** [comment]
> **From the log you sent, this shows that when logging in as operator it is likely a different prompt:**
> 
> D, [2019-02-15T14:48:05.894759 #25206] DEBUG -- : lib/oxidized/input/ssh.rb s33kr3t @ ARUBA2530 8G PoEE with expect: /^([\w.@-]+[#>]\s?)$/
> D, [2019-02-15T14:48:05.894921 #25206] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^([\w.@-]+[#>]\s?)$/] at ARUBA2530 8G PoEE
> D, [2019-02-15T14:48:06.493006 #25206] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
> ...
> ...end snip....
> W, [2019-02-15T14:48:25.896656 #25206] WARN -- : 172.16.1.149 raised Timeout::Error with msg "execution expired"
> 
> **Compare that to what happens on manager**
> D, [2019-02-15T14:50:34.260018 #25463] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^([\w.@-]+[#>]\s?)$/] at ARUBA2530 8G PoEE
> D, [2019-02-15T14:50:34.546512 #25463] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
> D, [2019-02-15T14:50:35.547441 #25463] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
> D, [2019-02-15T14:50:35.982794 #25463] DEBUG -- : lib/oxidized/input/cli.rb: **Running post_login commands at ARUBA2530 8G PoEE**
> 
> When you just ssh as operator what is the login prompt after login look like? Same for manager? This Regex /^([\w.@-]+[#>]\s?)$/ has to match the prompt to let the script continue with post_login and other commands.
> https://www.regextester.com/
> Manually ssh into each system and look at the prompt for both operator vs manager and paste the output in the the regextester's test string section. Alternately you may need to use ssh -vX user@ip to see a FULLY verbose output of what ssh is doing from the source machine to the destination.
> 
> ---Edit ---
> Doesn't operator login require the enable command which then requires the manager login/password?
> 
> Can you include the aruba.rb or whatever config file you are using as well?

Hi cdshow,

Thanks for your great answer! hmm did it manually... most interesting part is that after logging into aruba with operator , show config appears to be invalid command, but with manager , it's working! So it means that some sort of command lines are disabled for operator! So if i'll need to monitor/backup 40 arubas it's gonna be painfull...
and yes, there is no seperate .RB file, im using the same procurve.rb

**Comment by cdshow** [comment]
You can "enable" from operator to have access to the show config command.  Alternately you could just sign in with an account that has manager privileges which would give you immediate access to the configuration data.  SNMP MAY allow you to perform a backup as well but I don't think oxidized can handle that.  Is there a reason that you don't want to use a manager level account, the reason that is required on the HP devices is that sensitive data is included in the "backup".

**Comment by mincebert** [comment]
Hi.  I have the same issue: I only installed oxidized last week so I'm not too familiar but I've been trying to understand the code and what's going on with this failing.

I have several ProCurves - some are succeeding and some are failing, so I'm trying to work out why.  I've recorded the raw data from the SSH session and am trying to understand the difference.  One of the complications seems to be that the prompt "switchname# " is not just on a line by itself but surrounded by some control characters and there is no carriage return (nor one that matches the 'expect' line).

I think this is handled by the 'expect' methods below the 'comment' line in the procurve model doing replacements (by calling data.gsub) on the input data, resulting in the prompt on its own on a line and then matching the defined 'prompt' regexp.

This sort-of recursive matching makes what's going on incredibly difficult to troubleshoot.  However, if the 'expect' lines do the substitution after each character is read (and don't wait until a carriage return), then I can't, at the moment, see why it isn't working.  However, having confirmation that's how it works would help me look further.

**Comment by cdshow** [comment]
What do the ~/oxidized/logs/ip-ssh and/or ip-telnet file(or whatever your folder structure is) show?  Have you tried to ssh or telnet from the server to the device does that work correctly?  Within oxidized Is debug enabled? If so in the router.db disable all devices by putting a # in front of them except for one of the ones with an issue.  Run oxidized manually from command prompt from the user you are running it as, what does the log say?  Some of the hp switches are comware and not procurve and require a slightly different set of commands/prompts.  The key to troubleshooting with oxidized is to watch the logs both ssh/telnet and oxidized itself.  Pretty straightforward errors from what I have seen/experienced. 

If you can send the relevant ssh log and the oxidized log in a new thread so things don't get confusing I would be happy to look at it for/with you.
Chris

**Comment by berilslv** [comment]
Chris,
Whats the right line for config file to enable ssh/telnet logging?
folder "log" appears to be empty even if use_syslog: enable
To make thing's cleaner, here is my config:
https://pastebin.com/KshZXp4V

**Comment by mincebert** [comment]
Hi.  Thanks for your reply -- I've opened issue 1705 for this.

Sorry for hijacking an existing issue but it seemed several people are having the same problem and I thought it was best to continue one of those.

Thanks for your help.

**Comment by eduardocalfaia** [comment]
Hi @NextOne86,
Have you fixed your issue with oxidized and  hp procurve 5412zl?

Thanks
