### ISSUE TITLE
Slow version REST API with git backend

### ISSUE THREAD

**Issue by empi89** [ytti/oxidized#1616]
We are using oxidized with librenms integration and git output. The load time of the config page in librenms increased drastically over time and we found that it is was due to the oxidized node/version API with a load time of about 15 seconds at about 20k git commits. I also tried to git gc the repo and store the repo in a ram disk, but as the CPU spikes to 100% the problem seems not to be io bound.

I checked the code and found that the implementation at https://github.com/ytti/oxidized/blob/master/lib/oxidized/output/git.rb#L73 (def version node, group), especially the commit.diff slows down the API. I am wondering if it might be possible to add a per device caching there to reduce the queries to the whole git repo. I have already checked if rugged suggests another way of implementing the functionality but it seems that it is already implemented in the suggested fashion. What do you think regarding a cache at this part of the code?

As a workaround we have disabled the versioning feature of the librenms extension to reduce load time again.

**Comment by zombah** [comment]
Check ```git gc``` for you repos they may require housekeeping
