### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by aratnikovmxmgt** [ytti/oxidized#1617]
No issue here, I just really want to say huge thanks to all maintainers of this project!
Oxidized really helping me a lot everyday. Good day to everyone, who helped and helping right now to develop new features and solve issues. All of you are the best!

Cheers!

**Comment by laf** [comment]
This has to be the best issue here right now.

Thanks for taking the time out to thank the people involved.

<3

**Comment by MarcusCaepio** [comment]
I also want to thank you guys!
