### ISSUE TITLE
PowerConnect broken as of 1fd5e27

### ISSUE THREAD

**Issue by f0rkz** [ytti/oxidized#1618]
The following lines:

https://github.com/ytti/oxidized/blob/master/lib/oxidized/model/powerconnect.rb#L44
https://github.com/ytti/oxidized/blob/master/lib/oxidized/model/powerconnect.rb#L46

Will both evaluate as a true statement.

Powerconnect switches working previously to this commit now expect a password prompt. Unfortunately, switches without a password prompt for enable fail this expect check and fail to download the configuration.

**Comment by ytti** [comment]
What is your enable password and what is your expectation? 

If you expect to enable but not enter enable password set enable password to 'true', if you do not expect to enable set enable password to 'false' if you expect to enable and send enable password set it to something else.

**Comment by f0rkz** [comment]
Cool, thanks for that. That actually makes a lot of sense.

**Comment by f0rkz** [comment]
Yep. Fixed it right up. Thanks again.
