### ISSUE TITLE
Config of a deleted host

### ISSUE THREAD

**Issue by bydunai** [ytti/oxidized#1622]
Hi.
Not an issue, but rather a question.
I use mysql as a backend of hosts source.
So, devices in that table come and go but I still want to have a config of a device that is no there anymore.
As I can't find it in web-gui, how should I access it? I guess using git, but I can't figure out how exactly. Could you give an example?

**Comment by mrplow87** [comment]
Yes, a git backend is a good option. Refer to the guide on how to add the git output to your config: 
https://github.com/ytti/oxidized/blob/master/docs/Outputs.md#output-git

The remote repository will keep the configuration of removed hosts. But be aware, if you use the same hostnames, you'll have to dig into old commits to get the old configuration.

**Comment by bydunai** [comment]
I'm already using git.
I'm interested in finding device configuration in git after device removal from db.

**Comment by rtau** [comment]
You just need to clone the git repository somewhere, checkout the master branch. Each device config should be in its own file.

**Comment by laf** [comment]
Or use the git hook and push to something like gitlab or gogs.
