### ISSUE TITLE
Oxidized Performance Issue

### ISSUE THREAD

**Issue by satrioyoyo** [ytti/oxidized#1624]
Hi,

I'm currently try oxidized to maintain config +-900 devices. It works perfectly until 3 month i've noticed performance issue. it takes very long time when trying open the web management & see configuration of my device. I'm using git for oxidized output.

any suggestion for oxidized performance tweaks?

Thanks.

**Comment by mrplow87** [comment]
Can you post your config? Also, did you change anything 3 months ago, like an update of Oxidized(-web) or Ruby on your box?
Does this also affect polling your devices or is it just the oxidized-web part that is slow?

**Comment by satrioyoyo** [comment]
nope, i just modified groups to match with my favor & leave it running.
Yes. it also affecting polling performance.

this is my oxidized config:

======configuration start========
username: someusername
password: somerandompassword
model: cisco
interval: 3600
use_syslog: true
debug: false
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: someurl
next_adds_job: true
vars: {}
groups:
  tacacs:
    username: someusername
    password: somerandompassword
  cisco:
    username: someusername
    password: somerandompassword
  mikrotik:
    username: someusername
    password: somerandompassword
  huawei:
    username: someusername
    password: somerandompassword
  huawei-pe:
    username: someusername
    password: somerandompassword
  timos:
    username: someusername
    password: somerandompassword
  zte:
    username: someusername
    password: somerandompassword
  dasan:
    username: someusername
    password: somerandompassword

models: {}
pid: "/home/oxidized/.config/oxidized/pid"
input:
  default: telnet, ssh
  debug: false
  ssh:
    secure: false
output:
  default: git
  git:
    single_repo: true
    user: Oxidized
    email: address@domain.com
    repo: "/home/oxidized/.config/oxidized/git-repos/devices.git"
  file:
    directory: /home/oxidized/.config/oxidized/configs/
source:
  default: http
  debug: false
  http:
    url: https:someprivateurl
    scheme: https
    secure: false
    map:
      name: hostname
      model: os
      group: group
    headers:
      X-Auth-Token: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'

hooks:
  write_log_for_failed_nodes:
    type: exec
    events:
    - node_fail
    cmd: echo "Doing long running stuff for $OX_NODE_NAME" >> /home/oxidized/.config/oxidized/logs/ox_node_fail.log;
      sleep 60
    async: true
    timeout: 120
  write_log_for_store_operations_nodes:
    type: exec
    events:
    - post_store
    cmd: echo "Config written for for $OX_NODE_NAME" >> /home/oxidized/.config/oxidized/logs/ox_node_store.log;
      sleep 60
    async: true
    timeout: 120
==========configuration end==============

thanks

**Comment by mrplow87** [comment]
Please use markdown for your config block. It's not readable with no indentation :/

**Comment by laf** [comment]
This is probably related to #887

No fix is known for that but I'll be honest and say we don't see the same issues.
