### ISSUE TITLE
Cisco APIC-ACI prompt is not matching

### ISSUE THREAD

**Issue by Kitesurfer0** [ytti/oxidized#1628]
Hi Guys, 

I've created a new module to back up Cisco APIC(ACI) and prompt is not matching, however regexp is matching it (tried on Rubular)

class ACI < Oxidized::Model
  prompt /([\w.@()-]+[#>]\s?)$/
  comment  '! '

I'm trying to match the following output:

Last login: 2018-11-14T13:57:36.000+11:00 UTC
APICACI#

What's wrong? 

Error message:
W, [2018-11-14T14:26:06.166347 #10480]  WARN -- : 10.x.x.x raised Oxidized::PromptUndetect with msg "Last login: 2018-11-14T14:25:22.000+11:00 UTC
APICACI#  not matching configured prompt (?-mix:([\w.@()-]+[#>]\s?)$)"

**Comment by ytti** [comment]
Works is being used very liberally here. Now any line with character and # will be considered prompt, which means end of output for that command, and for next  command the previous actual prompt is seen before any output, for empty data.

Probably the problem with the original prompt is that the prompt does not end after #, there likely is some trash after that.

**Comment by Kitesurfer0** [comment]
Can you suggest a pattern which will parse only printable output?  I can't see anything after #, something is weird here.

**Comment by MuFFinZ84** [comment]
Thanks for the headsup, regexp is not my strong side

**Comment by shepherdjay** [comment]
Anyone have luck with this? I did a putty capture and got this:

```
Last login: 2021-05-25T17:47:02.000-06:00 UTC
%                                                                               
 

APIC01# 
```

But I haven't found a regex to match it either correctly

**Comment by netzbus** [comment]
can anyone share APIC module?

**Comment by chrisch80** [comment]
I would be also interessted in the APIC module. Can somebody share it or put it the git?

**Comment by chrisch80** [comment]
Can somebody share this module?
