### ISSUE TITLE
Huawei unable to detect prompt: (?-mix :^(<[\w.-]+>)$)"

### ISSUE THREAD

**Issue by freenessgit** [ytti/oxidized#1629]
I am running for a huawei device USG6620 firewall（OS：V500R001C60SPC300），but it fails，what do I should？ thanks for your help.

**Comment by Kitesurfer0** [comment]
Try to remove ^ usually it helps with multi-line prompt

**Comment by vlanbill** [comment]
my devices include USG6680 6630 5150 2200, and I have encountered the same issue. Who can help me?please.
to solve this problem, I have tried to emit the ^ in vrf.rb and execute the "undo banner enable" in the device , but it fails.

this is the message received after enter the password:

fan@85.12.89.240's password: 

Note: The max number of VTY users is 5, and the current number
      of VTY users on line is 1.
<HLW-Dmzyu_Cgsvpn_DX_FW>

anybody help me?

**Comment by phylocko** [comment]
> <HLW-Dmzyu_Cgsvpn_DX_FW>

Hello, for this case should work the following:

`^(<\S+>)$`

**Comment by vlanbill** [comment]
thanks for your heIp!


 
---Original---
