### ISSUE TITLE
Brocade NOS timestamp in config file part 2

### ISSUE THREAD

**Issue by f0rkz** [ytti/oxidized#1633]
Configuration shows a system uptime in the `show version` part of the configuration. Submitting a PR to fix this.

**Comment by f0rkz** [comment]
@wk check out my latest commit: b894a81

**Comment by f0rkz** [comment]
Regex has been updated.

**Comment by wk** [comment]
Thanks! PR pulled!

**Comment by f0rkz** [comment]
Worked perfectly!
