### ISSUE TITLE
REST API reload error with http output

### ISSUE THREAD

**Issue by ldufl** [ytti/oxidized#1640]
Hi,
I use the http method as output in my config.
When I try to reload the nodes via the REST API with http://127.0.0.1:8888/oxidized/reload, I have this error :

``NoMethodError: private method `load' called for #<Oxidized::Http:0x0000561455e234d8>
        /var/lib/gems/2.5.0/gems/oxidized-0.24.0/lib/oxidized/nodes.rb:15:in `block in load'
        /var/lib/gems/2.5.0/gems/oxidized-0.24.0/lib/oxidized/nodes.rb:128:in `synchronize'
        /var/lib/gems/2.5.0/gems/oxidized-0.24.0/lib/oxidized/nodes.rb:128:in `with_lock'
        /var/lib/gems/2.5.0/gems/oxidized-0.24.0/lib/oxidized/nodes.rb:10:in `load'
        /var/lib/gems/2.5.0/gems/oxidized-web-0.11.1/lib/oxidized/web/webapp.rb:74:in `block in <class:WebApp>'
        /var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `call'
        /var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `block in compile!'
        /var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
        /var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:994:in `route_eval'
        /var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
        /var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1015:in `block in process_route'
        /var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `catch'
        /var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `process_route'
        /var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:973:in `block in route!'
        /var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `each'
        /var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `route!'
        /var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1085:in `block in dispatch!'
        /var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
        /var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
        /var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
        /var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1082:in `dispatch!'
        /var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `block in call!'
        /var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
        /var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
        /var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
        /var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `call!'
        /var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:895:in `call'
        /var/lib/gems/2.5.0/gems/rack-protection-1.5.5/lib/rack/protection/xss_header.rb:18:in `call'
        /var/lib/gems/2.5.0/gems/rack-protection-1.5.5/lib/rack/protection/path_traversal.rb:16:in `call'
        /var/lib/gems/2.5.0/gems/rack-protection-1.5.5/lib/rack/protection/json_csrf.rb:18:in `call'
        /var/lib/gems/2.5.0/gems/rack-protection-1.5.5/lib/rack/protection/base.rb:49:in `call'
        /var/lib/gems/2.5.0/gems/rack-protection-1.5.5/lib/rack/protection/base.rb:49:in `call'
        /var/lib/gems/2.5.0/gems/rack-protection-1.5.5/lib/rack/protection/frame_options.rb:31:in `call'
        /var/lib/gems/2.5.0/gems/rack-1.6.10/lib/rack/nulllogger.rb:9:in `call'
        /var/lib/gems/2.5.0/gems/rack-1.6.10/lib/rack/head.rb:13:in `call'
        /var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/show_exceptions.rb:25:in `call'
        /var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:182:in `call'
        /var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:2013:in `call'
        /var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `block in call'
        /var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1787:in `synchronize'
        /var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `call'
        /var/lib/gems/2.5.0/gems/rack-1.6.10/lib/rack/urlmap.rb:66:in `block in call'
        /var/lib/gems/2.5.0/gems/rack-1.6.10/lib/rack/urlmap.rb:50:in `each'
        /var/lib/gems/2.5.0/gems/rack-1.6.10/lib/rack/urlmap.rb:50:in `call'
        /var/lib/gems/2.5.0/gems/rack-1.6.10/lib/rack/builder.rb:153:in `call'
        /var/lib/gems/2.5.0/gems/puma-3.12.0/lib/puma/configuration.rb:225:in `call'
        /var/lib/gems/2.5.0/gems/puma-3.12.0/lib/puma/server.rb:658:in `handle_request'
        /var/lib/gems/2.5.0/gems/puma-3.12.0/lib/puma/server.rb:472:in `process_client'
        /var/lib/gems/2.5.0/gems/puma-3.12.0/lib/puma/server.rb:332:in `block in run'
        /var/lib/gems/2.5.0/gems/puma-3.12.0/lib/puma/thread_pool.rb:133:in `block in spawn_thread'``

If I change my config and I set the output to file mode instead of http, the REST reload command works again!
Thanks
Ludo

**Comment by laf** [comment]
Can you post your config so we can replicate it please.

**Comment by ldufl** [comment]
This is my config attached.
Like I said, if I set the output to file, the reload REST command work fine.
If I set the source to http, I have the error.
[config.txt](https://github.com/ytti/oxidized/files/2680116/config.txt)

**Comment by wk** [comment]
Is this issue still present for you in the current version of Oxidized (0.28.0)?

**Comment by ldufl** [comment]
Hi,
I don't work anymore in the IT team where this instance is installed.
I forward your question about this issue to soiut@univ-smb.fr.
Thanks
	
Ludovic DUFLOT 
Service Informatique - MUST 
LAPP/IN2P3/CNRS – SceM USMB 
9 chemin de Bellevue - BP 110 - ANNECY LE VIEUX 
74941 ANNECY CEDEX 
Tél : +33 4 50 09 16 44

----- Mail original -----
De: "Wild Kat" <notifications@github.com>
À: "ytti/oxidized" <oxidized@noreply.github.com>
Cc: "Ludovic Duflot" <ludovic.duflot@univ-smb.fr>, "Author" <author@noreply.github.com>
Envoyé: Mardi 19 Mai 2020 09:37:58
Objet: Re: [ytti/oxidized] REST API reload error with http output (#1640)





Is this issue still present for you in the current version of Oxidized (0.28.0)?
