### ISSUE TITLE
no implicit conversion of String into Integer 

### ISSUE THREAD

**Issue by l3xi** [ytti/oxidized#1642]
Hello,
I'm trying to call the Netbox API (it's OK with CSV file)
This is my config:
[config.txt](https://github.com/ytti/oxidized/files/2615641/config.txt)

But keep getting the error message you can find in crash file: 
[log.txt](https://github.com/ytti/oxidized/files/2615647/log.txt)
[crash.txt](https://github.com/ytti/oxidized/files/2615645/crash.txt)

Curl is working fine :
[curl.txt](https://github.com/ytti/oxidized/files/2615650/curl.txt)

Thanks.
l3xi.

**Comment by tkspuk** [comment]
It's fixed?

**Comment by tkspuk** [comment]
@l3xi I have the same requirement, this has been working fine？

**Comment by l3xi** [comment]
@tkspuk no, but I wrote a python based on Avtandilko project (https://github.com/Avtandilko/NetBoxPython/blob/master/NetBoxPython.py)
My python do actually more than the API call I wanted to use, that's why I've closed this issue.
