### ISSUE TITLE
after upgrade Mikrotik to version 6.43.4 oxidized stuck+high cpu usage

### ISSUE THREAD

**Issue by corpcz** [ytti/oxidized#1646]
Hi,

after an upgrade Mikrotik device to the verzion 6.43.4 oxidized stuck on this device + 100% cpu load. If I exclude it from Oxidized everything running well.

Librenms+oxidized

*** LOCAL GEMS ***

asetus (0.3.0)
backports (3.11.4)
bigdecimal (1.2.8)
charlock_holmes (0.7.6)
did_you_mean (1.0.0)
emk-sinatra-url-for (0.2.1)
ffi (1.9.25)
haml (5.0.4)
htmlentities (4.3.4)
io-console (0.4.5)
json (1.8.3)
minitest (5.8.4)
multi_json (1.13.1)
net-ssh (4.1.0)
net-telnet (0.1.1)
oxidized (0.24.0)
oxidized-script (0.5.1)
oxidized-web (0.11.1)
power_assert (0.2.7)
psych (2.0.17)
puma (3.12.0)
rack (1.6.10)
rack-protection (1.5.5)
rack-test (0.7.0)
rake (10.5.0)
rb-fsevent (0.10.3)
rb-inotify (0.9.10)
rdoc (4.2.1)
rugged (0.27.5)
sass (3.6.0)
sass-listen (4.0.0)
sinatra (1.4.8)
sinatra-contrib (1.4.7)
slop (3.6.0)
temple (0.8.0)
test-unit (3.1.7)
tilt (2.0.8)

**Comment by InsaneSplash** [comment]
Strange, I have a number of 6.43.4 ROS (FW also 6.43.4) devices and don't see the same issue... what model Mikrotik are you using?
