### ISSUE TITLE
Telnet connection failing,  I need an example how to handle banner for ios.rb

### ISSUE THREAD

**Issue by lplazaparis** [ytti/oxidized#1649]
Hello,

Oxidized Telnet connection is failing because the below banner before the prompt.  I have test it without the banner and works fine.

What can I do on my config to fix it?

I already changed the prompt on ios.rb to mact Username(HAD): and this is working fine too.

The banner is like:

```
Connected to 10.18.152.200 (10.18.152.200).
Escape character is '^]'.

*******************************************************************************************
*                                        WARNING!                                         *
*                                                                                         *
* Warning, this system is subject to full monitoring and auditing.  Access to, monitoring *
* of, management of, maintenance of, including other electronic and physical interaction  *
* without explicit legislative, contractual and policy permission is an offence under     *
*International Laws; violators will be prosecuted.                        *
*                                                                                         *
*                                        WARNING!                                         *
*******************************************************************************************

Username(HAD): 
```

Oxidized error:

W, [2018-12-03T10:19:36.474330 #6050]  WARN -- : 10.18.152.200 raised Oxidized::PromptUndetect with msg "unable to detect prompt: (?-mix:^([\w.@()-]+[#>]\s?)$)"
D, [2018-12-03T10:19:36.474535 #6050] DEBUG -- : lib/oxidized/node.rb: Oxidized::Telnet failed for 10.18.152.200

Thanks for your help!

PS: works fine with SSH

**Comment by ytti** [comment]
I don't think the banner is problem here, your username prompt is ```Username(HAD):``` we expect ```Username:```. Where does the ```(HAD)``` come from, are you getting prompt from TACACS? Can you remove the ```(HAD)```?

**Comment by lplazaparis** [comment]
(HAD) is from TACACS and I added it to ios.rb and work fine:
#Modified by lp
#  cfg :telnet do
#    username /^username:/
#    password /^password:/
   cfg :telnet do
   username /^[Uu]sername(HAD):\s?/
   password /^[Pp]assword(HAD):\s?/ 

I have tried removing (HAD) and either it doesn't work :(

Any other ideas?

**Comment by ytti** [comment]
That is very strange (HAD) is not correct, that's not matching literal parenthesis, that's matching UsernameHAD and storing HAD. You'd need /Username\(HAD\):/

**Comment by lplazaparis** [comment]
I have removed (HAD) and it is working. Strange that it works with ssh... 

Thanks again! your tool rocks!

**Comment by ytti** [comment]
I don't find it strange it works with SSH, considering SSH uses it's own authentication, and does not present the CLI authentication prompts.

**Comment by lplazaparis** [comment]
I still puzzle, it still failing for the majority of the devices and all of them got same prompt :(

Not working:
Connected to 10.16.51.17.
Escape character is '^]'.

*******************************************************************************************
*                                        WARNING!                                         *
*                                                                                         *
* Warning, this system is subject to full monitoring and auditing.  Access to, monitoring *
* of, management of, maintenance of, including other electronic and physical interaction  *
* without explicit legislative, contractual and policy permission is an offence under     *
*  International Laws; violators will be prosecuted.                        *
*                                                                                         *
*                                        WARNING!                                         *
*******************************************************************************************

username: 

W, [2018-12-03T23:10:18.830695 #10745]  WARN -- : 10.16.50.77 raised Oxidized::PromptUndetect with msg "unable to detect prompt: (?-mix:^([\w.@()-]+[#>]\s?)$)"
D, [2018-12-03T23:10:18.831135 #10745] DEBUG -- : lib/oxidized/node.rb: Oxidized::Telnet failed for 10.16.50.77

Working:

Connected to 10.16.50.166.
Escape character is '^]'.

*******************************************************************************************
*                                        WARNING!                                         *
*                                                                                         *
* Warning, this system is subject to full monitoring and auditing.  Access to, monitoring *
* of, management of, maintenance of, including other electronic and physical interaction  *
* without explicit legislative, contractual and policy permission is an offence under     *
* Australian and International Laws; violators will be prosecuted.                        *
*                                                                                         *
*                                        WARNING!                                         *
*******************************************************************************************

hrcyh352-edwa-eth line 514 

username:

D, [2018-12-03T23:10:55.999224 #10745] DEBUG -- : Telnet: terminal length 0 @10.16.50.166
D, [2018-12-03T23:10:56.225738 #10745] DEBUG -- : lib/oxidized/input/cli.rb: Running post_login command: "terminal width 0", block: nil at 10.16.50.166
D, [2018-12-03T23:10:56.225917 #10745] DEBUG -- : Telnet: terminal width 0 @10.16.50.166

any ideas?

**Comment by ytti** [comment]
Can you show manual telnet login to both boxes, so that we see username, password and prompt

**Comment by lplazaparis** [comment]
Sorry for the late respond, different time zones.

it was failing because those devices had wrong TACACS. 

Thanks Again.
