### ISSUE TITLE
Logs Is a directory @ rb_sysopen

### ISSUE THREAD

**Issue by KARMA-UA** [ytti/oxidized#1656]
Hello!
Why it does not want to work when specifying settings for logs.
`log: "/opt/oxidized/.config/oxidized"`
I get the following error:
```
sudo -u oxidized oxidized
Is a directory @ rb_sysopen - /opt/oxidized/.config/oxidized
```
Here is the data of my system:
oxidized -v
`0.24.0-107-gc0c8513`
uname
`Debian GNU/Linux 9 (stretch)`
Thx!

**Comment by laf** [comment]
That setting is the path to a file not a directory so change it to `log: /opt/oxidized/.config/oxidized/debug.log` or something.

**Comment by KAPMA** [comment]
Thx!
Add the manual ;)

**Comment by KAPMA** [comment]
I noticed that when you start, the logs folder is created.
`/opt/oxidized/.config/oxidized/**logs**`
Therefore, I can not use this path (Is a directory @ rb_sysopen - /opt/oxidized/.config/oxidized/logs)
I changed to:
`log: /opt/oxidized/.config/oxidized/logs/logs`

**Comment by Glorf** [comment]
Up
I'm currently looking forward to deploy oxidized with config stored in kubernetes configmap, and so I cannot allow program to create any additional files in configuration directory. Please, make it possible to delegate all files generated by oxidized to other places in filesystem

**Comment by ytti** [comment]
@Glorf what is the specific issue, what is being created which should not be and what should happen instead.

**Comment by Glorf** [comment]
Hi @ytti, thanks for fast response
I mount my configmap in /root/.config/oxidized so config file resides there and that directory is automatically set read-only. I setup log parameter in config file to point to /storage/, where I mounted my volume. But when I run oxidized, I get `Read-only file system @ dir_s_mkdir - /root/.config/oxidized/logs`
Apparently oxidized tries to mkdir logs directory in configuration root even if it's told explicitly to store logs elsewhere. In my case, creating any directories in configuration root is not an option, as it's read-only

**Comment by ytti** [comment]
There is currently no way to set explicitly log directories, we need to write logs and crash and they'll be written in oxidized home, which ever that may be. You can of course configure oxidized home to reside in /storage/ or whatever.

I will also accept reasonable PR to configure log/crash directories.

**Comment by Glorf** [comment]
Ok, thanks
I'll probably try to make a PR next week
How do you suggest to have this resolved? Is just passing runtime conditional parameter for Config::Log and Config::Crash root directory to the oxidized binary sufficient?
