### ISSUE TITLE
reliative_require error after 0.25.0 version update

### ISSUE THREAD

**Issue by zlesnr** [ytti/oxidized#1661]
Seeing this after a version update today.  I've not had a chance to dig in.  Could this be related to the new version?

```
/usr/lib/ruby/gems/2.4.0/gems/oxidized-0.25.0/bin/oxidized:7:in `require_relative': cannot load such file -- /usr/lib/ruby/gems/2.4.0/gems/oxidized-0.25.0/lib/oxidized/cli (LoadError)
        from /usr/lib/ruby/gems/2.4.0/gems/oxidized-0.25.0/bin/oxidized:7:in `<top (required)>'
        from /usr/bin/oxidized:23:in `load'
        from /usr/bin/oxidized:23:in `<main>'
```

**Comment by hunnymonster** [comment]
Exact same issue here

Traceback (most recent call last):
        3: from /usr/local/bin/oxidized:23:in `<main>'
        2: from /usr/local/bin/oxidized:23:in `load'
        1: from /var/lib/gems/2.5.0/gems/oxidized-0.25.0/bin/oxidized:7:in `<top (required)>'
/var/lib/gems/2.5.0/gems/oxidized-0.25.0/bin/oxidized:7:in `require_relative': cannot load such file -- /var/lib/gems/2.5.0/gems/oxidized-0.25.0/lib/oxidized/cli (LoadError)

**Comment by laf** [comment]
Maybe try and re-install 0.25 (ensure all other versions have been removed). I've just installed on CentOS 7 and it starts fine after.

**Comment by ytti** [comment]
Can you check if this is permission issue?

```
find -type f /usr/lib/ruby/gems/2.4.0/gems/oxidized-0.25.0/|xargs chmod 644
find -type d /usr/lib/ruby/gems/2.4.0/gems/oxidized-0.25.0/|xargs chmod 755
chmod 755 /usr/lib/ruby/gems/2.4.0/gems/oxidized-0.25.0/bin/oxidized
```

umask may have broken permissions on commit.

**Comment by hunnymonster** [comment]
Yep - broken permissions - resolved by:

chmod -Rc 644 *
chmod -Rc a+X *

in both oxidized-0.25.0 & oxidized-web-0.12.0

**Comment by ytti** [comment]
Which umask do you have? Does this problem happen if you set umask to 022 before gem install?

**Comment by hunnymonster** [comment]
Umask is whatever is default in the ruby 2.5.0 install for Ubuntu in the blinkbox repo... Not near it just now to tell you what that is.

**Comment by ytti** [comment]
umask is not ruby thing, but gem honours umask. I want to ensure the umask during installation were 022 or something like that, but not 077.

**Comment by hunnymonster** [comment]
Well nothing changed from default in install packages here

**Comment by ytti** [comment]
I pushed .1 version, which should fix the problem.

**Comment by hunnymonster** [comment]
Certainly appears to work with no alterations necessary.

**Comment by hunnymonster** [comment]
> Which umask do you have? Does this problem happen if you set umask to 022 before gem install?

For completeness - umask is set to 0022

root@nmn:~# umask
0022
root@nmn:~#

**Comment by ytti** [comment]
Thanks for confirming, closing.
