### ISSUE TITLE
Problem with fetching config on Dell N-series after upgrade from 0.24 to 0.25.1

### ISSUE THREAD

**Issue by Slepwin** [ytti/oxidized#1667]
I have a a problem with fetching config on Dell N-series Powerconnect after upgrade from 0.24 to 0.25.1.
I have few Powerconnect switches with tacacs auth. (PC6248, N3024) and enable vars for powerconnect in oxidized config (without enable vars i can't run into enable mode in PC6248)
After upgrades to 0.25.1 oxidized stuck in prompt after login into N3024 switch, this switch auth. with level 15 and no need enable.
hostname#
enable

If i disable vars in config for Powerconnect i can fetch config from N3024, but can't from PC6248.
I'm use oxidized with LibreNMS and not use router.db

**Comment by deeconwastaken** [comment]
Hello, did you find a solution for this issue? I have a lot of Dell N3048 Series.
