### ISSUE TITLE
Haml::TempleEngine: Option :outvar is invalid

### ISSUE THREAD

**Issue by smart2128** [ytti/oxidized#1670]
After 0.25.1 upgrade, oxidized issues 4 rows of the message in subject every time I switch between nodes, stats and migration pages.
Is there a way to suppress it?

Thank you in advance,
Vincenzo

**Comment by wk** [comment]
Please open this issue under ytti/oxidized-web instead as it focuses on functionality of the optional web interface element rather than oxidized proper.
