### ISSUE TITLE
Using SSH proxy and network host password contains special characters

### ISSUE THREAD

**Issue by Noname2244** [ytti/oxidized#1672]
So I finally got SSH proxy to work, but the password to our WLC contains special characters ie @# etc.
I tried to escape the characters in router.db   \@xxxxx\#   etc. but that didn't work, then I tried '@xxxxx#' and that didn't work either.

Now I needs some help when to try next. I know that using ' in the config file works fine when connecting "directly" to networkhosts, without a jumpserver/proxy  does the proxy affect the handeling of the password string?

**Comment by ytti** [comment]
I don't think @ or # are special characters from Oxidized POV.

Here is how we process CSV: https://github.com/ytti/oxidized/blob/master/lib/oxidized/source/csv.rb#L21-L46

So you'd have some problems having new line in password as well as field separator in password, other than that, I don't think we care.

Oxidised itself does not differentiate password use in proxy and non-proxy use.

**Comment by Noname2244** [comment]
Odd, I removed the # and @ from the password, remained only a alphanumeric password and it worked just fine.

**Comment by ytti** [comment]
I can't explain it right now. Especially as you say it works without proxy, but there isn't anything in the proxy code which deals with passwords.
