### ISSUE TITLE
No such file or directory @ rb_sysopen - oxidized

### ISSUE THREAD

**Issue by kevhjelm** [ytti/oxidized#1677]
I'm trying to push a config onto a device using oxs
with the command:

sudo oxs -x 192.168.20.1

I'm getting a error saying
No such file or directory @ rb_sysopen - oxidized
any fix to this?
oxidized -v
0.25.1

**Comment by wk** [comment]
Please open this issue under ytti/oxidized-script as this is an oxs rather than oxidized proper issue.
