### ISSUE TITLE
Dreaded not matching configured prompt error

### ISSUE THREAD

**Issue by firestormv1** [ytti/oxidized#1697]
Running with two  HP procurve switches that are configured to present hostname.tld> as the prompt.  I can't get them to work with Oxidized.  I've disabled MOTD, it's specifically choking on the hostname prompt from the SSH Session. 

W, [2019-01-28T02:13:14.216088 #30]  WARN -- : x.x.x.x raised Oxidized::PromptUndetect with msg "hostname.tld>  not matching configured prompt (?-mix:^\r?([\w.-]+# )$)"
W, [2019-01-28T02:13:14.557574 #30]  WARN -- : /x.x.x.x status no_connection, retry attempt 1

For one host, it's host001.sub.sub.tld and the other host is host002-poe.sub.sub.tld.  Both hosts are in router.db according to their IP addresses.  I am more than willing to change the hostname (and the SSH prompts post-login) to match the regex, however I can't for the life of me figure out what the regex is expecting.  I know regex is a dark art, but I spent an hour trying to reverse engineer this and came up more frustrated than I started.

Can someone point me in the right direction of what the prompt should be to pass the regex?

Thank you.

**Comment by cdshow** [comment]
Look at the log folder located in the oxidized directory.  Look for the ip address-ssh or ip address-telnet file and see what is showing up.  
Not sure what the regex you are using with ?-mix...  is looking for but this one should work if prompt is as you describe:
^\r?([\(\)\w\s.-]+)(>|#)\s?$
That one looks for the beginning of a line with some characters that ends with either a # or > possibly followed by a space.  A tool like this is helpful: https://www.regextester.com/ Post the regex in the top and the sting you are trying to match in the bottom i.e. in this case the login prompt which should be recorded in the log file mentioned (oxidized/logs/ipaddr-ssh) above and that SHOULD show you if it will work or not.  I tested with your examples and that regex seems to work.
