### ISSUE TITLE
Run oxidezed for a single fetch

### ISSUE THREAD

**Issue by tomasell** [ytti/oxidized#170]
Is it possibile to run `oxidized` to fetch the configuration of a single host, then exit with status for modified/not-modified/failure? E.g.
```
$ oxidized 10.0.0.1 ios admin pass
```

**Comment by ytti** [comment]
No, this is not possible. But perhaps one of two solutions may work for you

a) http get /next/host - move host to head of the queue, to be fetched as first threat comes available
b) gem install oxidized-script, "oxs 10.0.0.1 'show run'#

**Comment by heruan** [comment]
:+1: for single command-line fetch. I don't know Ruby, but given the modularity of oxidized I think it would be quite straightforward to create and run a single job without having the daemon start. It would be very useful to integrate oxidized when you have another scheduler (e.g. Zabbix).

**Comment by ytti** [comment]
That's very good point. If you have centralised manager to push configs to networks in single place, it would be logical that that tool also calls one off scheduling of config fetch.
This other scheduler could even inject person who made the change into the query, so oxidized will pass it to git, having 'git blame' view of who made the changes.

It wouldn't probably be very complicated to do this, but I've not thought about in the code at all the possibility of two oxidised instances running at the same time. It likely won't be an issue.

We would have two possible ways to do it

1) keep oxidized running as daemon, which does nothing and add API call to one-off fetch. This would guarantee that no two instances run. But then again, you'd maybe have more run-time state then you want

2) don't run oxidized as daemon, fetch once and quit. No guarantees that two processes aren't run at the same time. 


I think 2) is better model, even with the unknowns, might just mean that some stuff needs to be fixed once found.

**Comment by heruan** [comment]
I agree 2) would be better, and I wouldn't be concerned about multiple instances running at the same time, that will be a problem of who starts the instance (e.g. the external scheduler). Keeping the Zabbix example, it would run that script which will create a standalone `Job` with a `Node` created from the command arguments (something like `oxidized-script`) but will fetch configuration and store it as specified in the `output` config; the the command will exit with a status code that could be 0: not modified, 1: modified, -1: error occurred.

**Comment by heruan** [comment]
Something like this: https://github.com/heruan/oxidized-fetch
It's a simplified version of `oxidized-script` which calls `Node.run` and saves the configuration on the `output` specified in the oxidized's config.
```bash
$ oxf -m ios -g core 10.0.0.242
```
(I also added  the `-g` option to specify the group.)

**Comment by ytti** [comment]
Cool.
Should we

 1. have it as separate repo
 2. integrate in oxidized cli
 3. integrate in oxidized-script cli

I'm happy which each, and will accept pull request for 2+3 and will create repo with commit permissions for you for 1.

**Comment by ytti** [comment]
No response. I'm happy to to accept PR for 2. or 3.
