### ISSUE TITLE
Error with switch Mellanox and Netgear

### ISSUE THREAD

**Issue by FlochonR** [ytti/oxidized#1700]
Hello,

I use oxidized to backup the config of my switch Mellanox ONYX but I have this error : 
```AuthenticationFailed with msg "Authentication failed for user login@ip```

I'm sure of my credentials because I can connect to my switch by ssh. I choose the model mlnxos, perhaps is it wrong ? Mellanox ONYX isn't supported ?

I have also an error with my switch Netgear : 
```
raised Oxidized::PromptUndetect with msg "
(M4300-52G-PoE+) > not matching configured prompt (?-mix:^(\([\w\s\-.]+\)\s[#>])$)"
```

Here I choose the model netgear.

I don't understand well my mistakes. Can someone help me ?

Thanks,

**Comment by githua-zhao** [comment]
Hi
I also encountered the same problem. Is your problem solved?

**Comment by FlochonR** [comment]
Hello,
No, I didn't solve the problem and I took an other software

Your regards,

**Comment by githua-zhao** [comment]
I problem is solved. add 'keyboard-ineractive' in ssh.rb.
vim /var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/input/ssh.rb
auth_methods = vars(:auth_methods) || %w[none publickey password keyboard-interactive]

**Comment by githua-zhao** [comment]
Hi,
my problem is solved, add 'keyboard-ineractive' in ssh.rb.
vim /var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/input/ssh.rb
auth_methods = vars(:auth_methods) || %w[none publickey password keyboard-interactive]

regards

**Comment by ytti** [comment]
https://github.com/ytti/oxidized/pull/1175

It is configurable as variable because some models require keyboard-interactive (broken SSH implementation) and some models must not offer it.
