### ISSUE TITLE
Zyxel GS1900 telnet - possible expect issue

### ISSUE THREAD

**Issue by inc0gnitus** [ytti/oxidized#1703]
I am having an issue backing up a Zyxel GS1900 switch via telnet. The issue is that there is pagination when doing a "show running-config". You can not shut off pagination and there is no other method of grabbing the config that I've found from these units. As far as I can tell, the "expect" block in my model file is being completely ignored. I have tried many different expect prompts, and used a regex checker to verify they all work. Tcpdump doesn't show any whacky characters, just "--More--".

Here is the zyxelgs1900.rb model:

```
class ZyxelGS1900 < Oxidized::Model

  prompt /^.*# $/
  comment  '! '

  expect /--More--/ do |data, re|
    send ' '
    data.sub re, ''
  end

  #cfg << cmd('show run')
  cmd 'show run' do |cfg|
    cfg
  end

  cfg :telnet do
    username /^(User name|.*Username):/
    password /^\r?Password:/
  end

  cfg :telnet do
    pre_logout do
      send "exit\r"
    end
  end
end
```

I wrote a small expect script, separate from Oxidized:

```
#!/usr/bin/expect -f
set user username
set password password
set timeout 30
spawn telnet switchname
expect "Username: "
sleep 1
send "$user\r"
sleep 1
expect "Password:"
sleep 1
send "$password\r"
expect "switchname# "
sleep 1
send "show run\r"
expect {
    "More" {send -- " "; exp_continue}
}
sleep 5
expect "switchname# "
send "exit\rexit\r"
```

The expect script works just fine. The Oxidized model does not. The debug log for a specific device doesn't show anything:

```
Username: =username
Password: *********
switchname# 
```

In /var/log/messages, Oxidized logs a timeout:

`[2019-02-15T11:24:59.883280 #19733]  WARN -- : ###.###.###.### raised Net::ReadTimeout (rescued Timeout::Error) with msg "timed out while waiting for more data"`

A tcpdump shows login and executing "show run", and then output stopping at "--More--". The expect block isn't firing off. 

In my model file, if I change the cmd from "show run" to anything that doesn't paginate (eg, "show run int 1", "show version", etc), it all works just fine. So the issue is that the expect block is not being used during the "show run" command. I can't for the life of me figure out why.

oxidized (0.25.1)
oxidized-script (0.6.0)
oxidized-web (0.12.1)

ruby --version
ruby 2.4.5p335 (2018-10-18 revision 65137) [x86_64-linux]

OS is Centos 7. 

This used to work in an older version of Oxidized. I think it was 0.21.0 or something like that, so I wonder if the changes to telnet.rb is the cause. I've tried tweaking it but I can't seem to get the expect stuff to actually work.

**Comment by inc0gnitus** [comment]
Does anyone know if there's a way to access the hostname in a model file such as the above? I can't get this to work, but I can pull from an external script. The problem is, I have to at least pass the hostname, but I can't for the life of me figure out how to do that.

For example:

```
post do
   extconfig = `/home/oxidized/zyxelgs1900.expect sw1.example.com`
   extconfig.gsub! /^spawn telnet .*/, ''
   extconfig.gsub! /^Trying .*/, ''
   extconfig.gsub! /^Connected to .*/, ''
   extconfig.gsub! /^Escape character is .*/, ''
   extconfig.gsub! /^[\[H^[\[J/, ''
   extconfig.gsub! /^[\[A^[\[2K/, ''
   extconfig.gsub! /^--More--/, ''
   extconfig.gsub! /^Username: .*/, ''
   extconfig.gsub! /^Password: .*/, ''
   extconfig.gsub! /^.*# $/, ''
   extconfig.gsub! /System Up Time: .*/, ''
   extconfig.gsub! /^\s*$/, ''
   extconfig
end
```

This is in zyxelgs1900.rb in my oxidized model directory. This works. It calls the external expect script, which logs in and grabs everything, and then filters some of the returned lines. I'm specifying the switch hostname in the model file, but to make this work correctly, I need to pass the hostname. I tried vars(:name) and vars(:ip) and that doesn't appear to work.

Anyone have an idea on this?

**Comment by inc0gnitus** [comment]
I ended up passing the host by adding to var_map in the config file (myhost):

```
    map:
      name: 0
      ip: 1
      model: 2
      group: 3
      username: 4
      password: 5
    vars_map:
      enable: 6
      myhost: 0
```

In that way, I can at least access what host the new model file is being run against. Using that, I call my external expect script and capture the output, which works fine. Not ideal, but it works for now and I'm hoping to stop using those models anyways. 

If anyone is interested, here's my model and expect files.

```
class ZyxelGS1900 < Oxidized::Model

  prompt /.*# $/
  comment  '! '

  cmd 'show vlan' do |cfg|
    cfg.gsub! /^.*# $/, ''
    comment cfg
  end

  post do
   mycmd = "/home/oxidized/zyxelgs1900.expect USERNAME PASSWORD "
   mycmd << vars(:myhost)

   extconfig = `#{mycmd}`
   extconfig.gsub! /^spawn telnet .*/, ''
   extconfig.gsub! /^Trying .*/, ''
   extconfig.gsub! /^Connected to .*/, ''
   extconfig.gsub! /^Escape character is .*/, ''
   extconfig.gsub! /ESC\[HESC\[J/, ''
   extconfig.gsub! /ESC\[AESC\[2K/, ''
   extconfig.gsub! /^--More--/, ''
   extconfig.gsub! /^Username: .*/, ''
   extconfig.gsub! /^Password: .*/, ''
   extconfig.gsub! /^.*# $/, ''
   extconfig.gsub! /System Up Time: .*/, ''
   extconfig.gsub! /^\s*$/, ''
   extconfig
  end

  cfg :telnet do
    username /^(User name|.*Username):/
    password /^\r?Password:/
  end

  cfg :telnet do
    pre_logout do
      send "exit\n"
    end
  end
```

and the expect script:

```
#!/usr/bin/expect -f

set user [lindex $argv 0];
set password [lindex $argv 1];
set host [lindex $argv 2];

set timeout 10
spawn telnet $host
expect "Username: "
sleep 1
send "$user\r"
sleep 1
expect "Password:"
sleep 1
send "$password\r"
expect -re ".*# $"
sleep 1
send "show run\r"
expect {
    "More" {send -- " "; exp_continue}
    -re ".*# $" {send -- "exit\rexit\r"}
}
```

The entire reason I have to do this is due to pagination and the expect block in model files apparently not working correctly. Using tcpdump, I can tell that it never gets past the first --More--. Which seems like a bug, but what do I know?

**Comment by deajan** [comment]
Hey,

I'm really glad I found your script here, owning a GS1900-8 switch and trying to backup my config.
I was previously trying to write a zyxel GS model but those switches are real pain in the ***.
SSH won't accept pre-filled user and will behave like Telnet on those, and there are no "no page" or "no-more" command to remove the "--more--" part.

Anyway, I lightly adapted your script which works great for me, doing the switch backup directly in SSH instead of telnet.

Here's my version of zyxelgs.rb (renamed the class because Ruby complained about the name)
```
class ZyxelGS < Oxidized::Model

  prompt /^.*# $/
  comment  '! '

  expect /--More--/ do |data, re|
    send ' '
    data.sub re, ''
  end

  cmd 'show running-config' do |cfg|
    cfg
  end

  cfg :telnet, :ssh do
    username /^(User name|.*Username):/
    password /^\r?Password:/
  end

  cfg :telnet do
    pre_logout do
      send "exit\r"
    end
  end

  cfg :ssh do
    pre_logout do
      send "exit\n"
      send "exit\n"
    end
  end
end
```

If you're still having the issue with --more--, willing to share my data / tests with you.

Btw, I'd like to make a PR for that model and document it.
Mind if I do or do you prefer doing so yourself ?

Again, thanks alot for sharing !!!

**Comment by deajan** [comment]
Yet a better integration which also avoids diffs due to system uptime: https://github.com/deajan/oxidized/blob/zynos-gs-compat/lib/oxidized/model/zynos.rb
