### ISSUE TITLE
send post_login keystroke

### ISSUE THREAD

**Issue by kevhjelm** [ytti/oxidized#1704]
I'm having issues where oxidized can't send an enter keystroke. When logging into my device it asks "Press enter to continue" this stops oxidized from getting the config since I can't send a keystroke . I tried to play around with the model.rb to try to send a keystroke

> 

  cfg :ssh do
    post_login "\r\n"  #entering keystroke  
    post_login do
      pw = vars(:enable)
      pw ||= ""
      send "enable\r\n"
      cmd pw
    end
    post_login 'terminal length 0'
    post_login 'terminal width 0'
    pre_logout "exit\nexit\nY\r\n"
  

end

> 

-----
Is there another way to do this within the model.rb, in the ssh-log I get:

> 

^[[2J^[[18;1H^[[2K^[[19;1H^[[2K^[[20;1H^[[2K^[[2J^[[4;14HLast login: SAT 2019-02-1$
^[[5;14HFailed retries since last login:  1
^[[10;0HPress ENTER to continue
^[[24;1H

> 

---
Is it something wrong with my prompt? is there a pre_login function ?

**Comment by cdshow** [comment]
I think you need to add a line similar to this one I use for a different model:
  expect /Press any key to continue(\e\[\??\d+(;\d+)*[A-Za-z])*$/ do
    send ' '
    ""
  end
...................................
Yours might need to be more like:
  expect /Press ENTER to continue(\e\[\??\d+(;\d+)*[A-Za-z])*$/ do
    send '\r\n'
  end

If that doesn't work look at your exact SSH text compared to the regex at the end of that line.  The exact text will need to match the string from your switch.

**Comment by kevhjelm** [comment]
Another thing that I tried that also seem to work is to add
prompt 'en\r\n'
in the beginning of the model.rb file
