### ISSUE TITLE
ubuntu 18.04.2 lts cant install

### ISSUE THREAD

**Issue by tpolim008** [ytti/oxidized#1708]
do we have clearer instructions on getting this up and running on Ubuntu? What are the exact steps start to finsih.. see that the docs lack some info and can't get this working... any help is great and or any clear instructions work be better.

**Comment by wk** [comment]
Hi new oxidized user!

You can find installation instructions for getting oxidized to run on Ubuntu [here](https://github.com/ytti/oxidized#debian-and-ubuntu). These instructions have been tested and confirmed working on Ubuntu 18.04 (Bionic).

Once you have oxidized installed, you can proceed to [configure](https://github.com/ytti/oxidized/blob/master/docs/Configuration.md) it to suit your needs and environment.

Your issue description is far too broad and lacks any concrete information to offer any further help. I will proceed to close it. If you encounter a specific problem, you can open a new issue and include the relevant input (commands you've executed), output (any errors which were displayed in the process), and your expectations. You can also try getting help in real time on the [gitter chat](https://gitter.im/oxidized/Lobby).

**Comment by tpolim008** [comment]
so I guess this issue is this, do I runt he ubunut debian install in that
section only, its doesn't clearly define where to start-stop.... sorry
I'm fairly new to Linux and learning. Im trying to switch from rancid to
this tool also...
