### ISSUE TITLE
Asyncos.rb pre_logout problem

### ISSUE THREAD

**Issue by gregi44** [ytti/oxidized#1709]
Hi,

I'm trying to backup ESA and WSA from cisco, so i use the model asyncos.rb.

This is the modified version for WSA:

```
class AsyncOS < Oxidized::Model
  # ESA prompt "(mail.example.com)> " or "mail.example.com> "
  prompt /^\r*([\w. \-]+[#>]\s+)$/
  comment '! '

  # Select passphrase display option
  expect /\[\S+\]>\s/ do |data, re|
    send "2\n"
    data.sub re, ''
  end

  # handle paging
  expect /-Press Any Key For More-+.*$/ do |data, re|
    send " "
    data.sub re, ''
  end

  cmd 'version' do |cfg|
    comment cfg
  end

  cmd 'showconfig' do |cfg|
    # Delete hour and date which change each run
    # cfg.gsub! /\sCurrent Time: \S+\s\S+\s+\S+\s\S+\s\S+/, ' Current Time:'
    # Delete select passphrase display option
    cfg.gsub! /Choose the passphrase option:/, ''
    cfg.gsub! /1. Mask passphrases \(Files with masked passphrases cannot be loaded using/, ''
    cfg.gsub! /loadconfig command\)/, ''
    cfg.gsub! /2. Plain passphrases/, ''
    cfg.gsub! /^2$/, ''
    # Delete space
    cfg.gsub! /\n\s{25,26}/, ''
    # Delete after line
    cfg.gsub! /([-\\\/,.\w><@]+)(\s{25,27})/, "\\1"
    # Add a carriage return
    cfg.gsub! /([-\\\/,.\w><@]+)(\s{6})([-\\\/,.\w><@]+)/, "\\1\n\\2\\3"
    # Delete prompt
    cfg.gsub! /^\r*([\w. \-]+[#>]\s+)$/, ''
    cfg
  end

  cfg :ssh do
    pre_logout "exit"
  end
end
```
I only change the prompt regex and the passphrase display option (On WSA theire is only 2 options).
It work well when i go on the ssh log, the model did everithing BUT he never send the exit.
i can see in var log message at the end of an execution.
```
DEBUG -- : lib/oxidized/input/cli.rb running pre_logout commands at *******
DEBUG -- : lib/oxidized/input/ssh.rb exit @ ****** with expect: nil
DEBUG -- : lib/oxidized/input/cli.rb running pre_logout commands at *******
DEBUG -- : lib/oxidized/input/ssh.rb exit @ ****** with expect: nil
```

But no exit in SSH log.
If you have any idea or you encouter this problem, it will be a pleasure to hear the solution.
Have a nice day.

**Comment by gregi44** [comment]
It worked on the ESA but not WSA.

**Comment by gregi44** [comment]
I see a big differrence between ESA execution and WSA.
in ESA it take 40 secondes between this 2 actions, and on WSA it's 1 seconde.
But when i test on the device it's longer on WSA
```
DEBUG -- : lib/oxidized/input/ssh.rb showconfig @ ***** with expect: /^\r*([(]?[\w. \-]+[)]?[#>]\s*)$/
DEBUG -- : lib/oxidized/input/ssh.rb expecting [/^\r*([(]?[\w. \-]+[)]?[#>]\s*)$/] at *******
```

>40S in ESA ---- 1S in WSA 

```
DEBUG -- : lib/oxidized/input/cli.rb running pre_logout commands at *******
DEBUG -- : lib/oxidized/input/ssh.rb exit @ ****** with expect: nil
```

**Comment by gregi44** [comment]
The problem is during the "handle paging".
Using this command, it doesn't emmulate correctly the press space bar, every information appear instantly.
`tail -f /home/oxidized/logs/*.*.*.*_ssh`

I tried to add a sleep, it take longer and we can se every space bar press, but still the same problem doesn't send the exit.

 ```
 # handle paging
  expect /-Press Any Key For More-+.*$/ do |data, re|
    send " "
    sleep 0.5
    data.sub re, ''
  end
```

**Comment by gregi44** [comment]
The issue is simple, but haven't found the solution yet.
On my WSA, juste before the showconfig (That take around 8+ secondes), he launch the pre_logout, so the exit command never send when the prompt is available.

**Comment by gregi44** [comment]
Still encounter the problem, if someone can help on this ...
Thanks a lot.

**Comment by gregi44** [comment]
Up.

**Comment by ytti** [comment]
One thing is that you really shouldn't use 'send' it can easily lead to all kind of problems due to race conditions, timing and synchronisation in prompt detect.
If it is at all possible to expect some string after sending string, you should always use ```cmd "string", expect_re``` this way we know where we are and we don't accidentally start consuming wrong prompts.

**Comment by gregi44** [comment]
Hi,
I tested your solution, it seems to work better but "showconfig" on ESA and WSA is really long and using cmd instead of send block the execution arround 30 second (timeout in oxidized is 120), there is a limit of "cmd" ? something like that ? it did on ESA to if i switch to "cmd" it doesn't work anymore.

Thanks for your answer by the way.

**Comment by ytti** [comment]
```cmd``` will block until it sees the expect regular expression. if you do not specify regular expression, then it is prompt.

If you have ```sleep``` in code, what are you waiting for? Make it triggered by having ```cmd``` expect that string before it returns.

**Comment by gregi44** [comment]
```
# handle paging
 expect /-Press Any Key For More-+.*$/ do |data, re|
   cmd " "
   data.sub re, ''
 end
```
This is what i got in my model file.
It work fine until he block on "-Press Any Key For More-" and trigger "space" anymore for no reason.
no idea why

**Comment by ytti** [comment]
Again, ```cmd``` blocks until it sees the regexp it is waiting.

If you don't see prompt after pressing space, it will block forever. 

If you expect _multiple_ things, you can give ```cmd``` multiple regexp to wait. Perhaps you want to give prompt and another press any key for cmd to expect.

**Comment by gregi44** [comment]
Thanks a lot.
You got it right, the regex for the prompt is triggered, i found out how to change my regex.

Old regex :
` prompt /^\r*([\w. \-]+[#>]\s+)$/`
=> this was matching on this 

> -->

```
<!--
*************************************************************
*                             NETWORK CONFIGURATION               *
*************************************************************
--> 
```

I made a new regex (Not really sexy) but i spend already too much time on this problem

New regex :
` prompt /^\r*([\w\d\. \-]{5}[\w\d\. \-]+[#>]\s+)$/`

What i found really wierd is that ESA and WSA are really closed and i haven't encounter this problem on ESA.

Thanks again @ytti 

I think you can closed this issue.
