### ISSUE TITLE
Run oxidized without username var

### ISSUE THREAD

**Issue by tomasell** [ytti/oxidized#171]
I didn't set a username (i set only password and enable var) and oxidized has crashed with this error:
```
waitfor: timed out while waiting for more data
 from /usr/lib/ruby/1.9.1/net/telnet.rb:697:in `cmd'
 from /var/lib/gems/1.9.1/gems/oxidized-0.7.2/lib/oxidized/input/telnet.rb:38:in `cmd'
 from /var/lib/gems/1.9.1/gems/oxidized-0.7.2/lib/oxidized/input/cli.rb:19:in `block in connect_cli'
 from /var/lib/gems/1.9.1/gems/oxidized-0.7.2/lib/oxidized/input/cli.rb:19:in `each'
 from /var/lib/gems/1.9.1/gems/oxidized-0.7.2/lib/oxidized/input/cli.rb:19:in `connect_cli'
```
Some devices require only password and enable password, there's a tip to run oxidized without a username?
I tried to run
```
$ oxs -m ios -p pwd -e pwdena --protocols telnet 10.0.0.1  
```

**Comment by ytti** [comment]
The model is expecting username prompt, the model could be changed to not expect username prompt. But honestly, no one should be running their Cisco's like this in in 1995 much less in 2015.
I strongly encourage to turn on AAA, use username and password and ditch enable.

**Comment by gbbromley** [comment]
We have a similar issue where by some large legacy estates managed by automation tools which are running in this mode of access. Can we get an option to have null/blank username to force 'legacy' non-user based auth?

**Comment by ytti** [comment]
Are these installations telnet only? Or is ssh without username possible?

From code POV, telnet.rb does support usernameless login:
https://github.com/ytti/oxidized/blob/master/lib/oxidized/input/telnet.rb#L22

If no username is set for node or if it is "", then it won't be used.

**Comment by gbbromley** [comment]
Our installations are telnet based.

When using oxs we get the following error:
oxs -u "" -p PASS -e ENABLE --protocols telnet -d -v -m ios switch.customer.com "sh ver"
timed out while waiting for more data
/var/lib/gems/2.1.0/gems/oxidized-0.8.1/lib/oxidized/input/telnet.rb:105:in `waitfor': timed out while waiting for more data (Timeout::Error)
	from /usr/lib/ruby/2.1.0/net/telnet.rb:696:in `cmd'
	from /var/lib/gems/2.1.0/gems/oxidized-0.8.1/lib/oxidized/input/telnet.rb:41:in `cmd'
	from /var/lib/gems/2.1.0/gems/oxidized-0.8.1/lib/oxidized/input/cli.rb:19:in `block in connect_cli'
	from /var/lib/gems/2.1.0/gems/oxidized-0.8.1/lib/oxidized/input/cli.rb:19:in `each'
	from /var/lib/gems/2.1.0/gems/oxidized-0.8.1/lib/oxidized/input/cli.rb:19:in `connect_cli'
	from /var/lib/gems/2.1.0/gems/oxidized-script-0.1.1/lib/oxidized/script/script.rb:109:in `connect'
	from /var/lib/gems/2.1.0/gems/oxidized-script-0.1.1/lib/oxidized/script/script.rb:87:in `initialize'
	from /var/lib/gems/2.1.0/gems/oxidized-script-0.1.1/lib/oxidized/script/cli.rb:69:in `new'
	from /var/lib/gems/2.1.0/gems/oxidized-script-0.1.1/lib/oxidized/script/cli.rb:69:in `connect'
	from /var/lib/gems/2.1.0/gems/oxidized-script-0.1.1/lib/oxidized/script/cli.rb:11:in `run'
	from /var/lib/gems/2.1.0/gems/oxidized-script-0.1.1/bin/oxs:5:in `<top (required)>'
	from /usr/local/bin/oxs:23:in `load'
	from /usr/local/bin/oxs:23:in `<main>'

**Comment by gbbromley** [comment]
Additional embedding the information into router.db also fails to work e.g.
switchA.customer.com:ios:group::PASS:ENABLE
switchB.customer.com:ios:group::PASS:ENABLE

With the config file containing:
source:
  default: csv
  csv:
    file: ~/.config/oxidized/router.db
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
      group: 2
      username: 3
      password: 4
    vars_map:
      enable: 5

**Comment by ytti** [comment]
Can you try this change in 'telnet.rb'
https://github.com/ytti/oxidized/commit/58a2939718195c01722545e60b5d6c5c2777aa48

I believe this issue was fixed by: @skoef at
https://github.com/ytti/oxidized/pull/193

**Comment by gbbromley** [comment]
Yep that appears to fix oxs script above, will try router.db and update

**Comment by gbbromley** [comment]
From the debug logs for telnet I get the following errors:
can't convert Asetus::ConfigStruct to String (Asetus::ConfigStruct#to_str gives Asetus::ConfigStruct)
Trying 10.44.128.39...
can't convert Asetus::ConfigStruct to String (Asetus::ConfigStruct#to_str gives Asetus::ConfigStruct)
Trying 10.44.128.39...
can't convert Asetus::ConfigStruct to String (Asetus::ConfigStruct#to_str gives Asetus::ConfigStruct)
Trying 10.44.128.39...
can't convert Asetus::ConfigStruct to String (Asetus::ConfigStruct#to_str gives Asetus::ConfigStruct)
Trying 10.44.128.40...
can't convert Asetus::ConfigStruct to String (Asetus::ConfigStruct#to_str gives Asetus::ConfigStruct)
Trying 10.44.128.40...
can't convert Asetus::ConfigStruct to String (Asetus::ConfigStruct#to_str gives Asetus::ConfigStruct)
Trying 10.44.128.40...
can't convert Asetus::ConfigStruct to String (Asetus::ConfigStruct#to_str gives Asetus::ConfigStruct)
Trying 10.44.128.40...
can't convert Asetus::ConfigStruct to String (Asetus::ConfigStruct#to_str gives Asetus::ConfigStruct)

tcpdump reveals that connections are being made to the network.

Have tried username as "" and null within router.db and config.

**Comment by gbbromley** [comment]
OK fixed, changing group reference back to default and works with router.db which looks like:
SWITCHNAME:ios:default::PASS:ENABLE

Using a username of "" appears to cause issues waiting for a username prompt. e.g.
SWITCHNAME:ios:default:"":PASS:ENABLE

**Comment by supertylerc** [comment]
@tomasell @gbbromley 

Can this issue be closed?

**Comment by tomasell** [comment]
You can close this issue, thanks!

**Comment by ytti** [comment]
Thanks!
