### ISSUE TITLE
After Update from 0.24 to 0.26.3: Timeout::Error with msg "execution expired"

### ISSUE THREAD

**Issue by MarcusCaepio** [ytti/oxidized#1716]
Hi all,
I just updated to the latest version via "gem update oxidized oxidized-script oxidized-web"
Now I cannot get the configs of my ios devices anymore.
Configs are all the same but I get the error: Timeout::Error with msg "execution expired"

What's wrong here?

After falling back to 0.24, it seems to work again (thank god I had a snapshot....)
One thing I found out: After updating, I wasn't able to use "service oxidized xxx" with the oxidized user anymore.

**Comment by wk** [comment]
There is insufficient information in this issue to be able to offer any feedback. Please include complete logs and configuration of your installation and specify which version is 'latest' - as Oxidized 0.26 has recently been released.

**Comment by MarcusCaepio** [comment]
Will post the info tomorrow, when I am back at the office.

**Comment by MarcusCaepio** [comment]
So, I am doing the whole upgrade process again:
Before Update (some data anonymous):
Ubuntu 16.04.5 LTS
Oxidized Version 0.24 installed like described at: https://github.com/ytti/oxidized#debian-and-ubuntu

```
root@oxidized:/home/oxidized/.config/oxidized# cat config
---
interval: 43200 #interval in seconds
log: ~/.config/oxidized/log
debug: false
threads: 30
timeout: 30
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
crash:
  directory: ~/.config/oxidized/crashes
  hostnames: false
rest: 127.0.0.1:8888
pid: ~/.config/oxidized/oxidized.pid
groups: {}
input:
  default: ssh
  debug: false
  ssh:
    secure: false
output:
  default: git
  git:
    user: oxidized
    email: oxidized@domain.de
    repo: "~/cisco-configs.git"
source:
  default: csv
  csv:
    file: ~/.config/oxidized/router.db
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
      username: 2
      password: 3
    vars_map:
      enable: 4
models:
  ios:
    username: bot
    password: 123
    vars:
      enable: 456
  asa:
    username: bot
    password: 123
    vars:
      enable: 456
  nxos:
    username: bot
    password: 123
  pfsense:
    username: bot
    password: 123
hooks:
  push_to_remote:
    type: githubrepo
    events: [post_store]
    remote_repo: git@gitlab.domain.de:cisco/cisco-configs.git
    publickey: /home/oxidized/.ssh/id_rsa.pub
    privatekey: /home/oxidized/.ssh/id_rsa
```

Update running like described here (as root): https://github.com/ytti/oxidized/issues/308 to Oxidized v.0.26.3
After updating oxidized ,oxidized-web, oxidized-script and running (as root) "service oxidized restart" I am not longer able to get the configs of the ios devices. Logfile:

```
I, [2019-03-07T08:34:41.598841 #15069]  INFO -- : Oxidized starting, running as pid 15069
I, [2019-03-07T08:34:41.599813 #15069]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
I, [2019-03-07T08:34:41.724175 #15069]  INFO -- : lib/oxidized/nodes.rb: Loaded 72 nodes
W, [2019-03-07T08:36:11.218208 #15069]  WARN -- : 1.1.1.1 raised Timeout::Error with msg "execution expired"
W, [2019-03-07T08:36:12.102745 #15069]  WARN -- : /ios1.domain.de status no_connection, retry attempt 1
W, [2019-03-07T08:36:45.234618 #15069]  WARN -- : 1.1.1.1 raised Timeout::Error with msg "execution expired"
W, [2019-03-07T08:36:46.108806 #15069]  WARN -- : /ios1.domain.de status no_connection, retry attempt 2
W, [2019-03-07T08:37:19.232960 #15069]  WARN -- : 1.1.1.1 raised Timeout::Error with msg "execution expired"
W, [2019-03-07T08:37:20.115271 #15069]  WARN -- : /ios1.domain.de status no_connection, retry attempt 3
W, [2019-03-07T08:37:53.252995 #15069]  WARN -- : 1.1.1.1 raised Timeout::Error with msg "execution expired"
W, [2019-03-07T08:37:54.121141 #15069]  WARN -- : /ios1.domain.de status no_connection, retries exhausted, giving up
W, [2019-03-07T08:38:27.250416 #15069]  WARN -- : 1.1.1.2 raised Timeout::Error with msg "execution expired"
W, [2019-03-07T08:38:28.127094 #15069]  WARN -- : /ios2.domain.de status no_connection, retry attempt 1
W, [2019-03-07T08:39:01.255138 #15069]  WARN -- : 1.1.1.2 raised Timeout::Error with msg "execution expired"
W, [2019-03-07T08:39:02.132799 #15069]  WARN -- : /ios2.domain.de status no_connection, retry attempt 2
W, [2019-03-07T08:39:35.253769 #15069]  WARN -- : 1.1.1.2 raised Timeout::Error with msg "execution expired"
W, [2019-03-07T08:39:36.138986 #15069]  WARN -- : /ios2.domain.de status no_connection, retry attempt 3
W, [2019-03-07T08:40:09.261877 #15069]  WARN -- : 1.1.1.2 raised Timeout::Error with msg "execution expired"
W, [2019-03-07T08:40:10.144913 #15069]  WARN -- : /ios2.domain.de status no_connection, retries exhausted, giving up
W, [2019-03-07T08:40:43.494748 #15069]  WARN -- : 1.1.1.3 raised Timeout::Error with msg "execution expired"
W, [2019-03-07T08:40:44.151324 #15069]  WARN -- : /ios3.domain.de status no_connection, retry attempt 1
```

**Comment by MarcusCaepio** [comment]
Looks like it's the same as in https://github.com/ytti/oxidized/issues/1665. But the workaround here does not work for every switch I got.

**Comment by ytti** [comment]
What is your enable password? You need to have ```nil``` to indicate no password prompt is expected. Empty enable password means we expect passport prompt and we send just newline.

**Comment by MarcusCaepio** [comment]
My enable pw is a 10 long mix of chars and numbers, defined in the config file as you can see above 
(anonymized). The devices are configured in the router.db like: <fqdn>:ios.
This config works perfectly with version 0.24 and stopped working at 0.25.1

**Comment by ytti** [comment]
Have you modified enable prompt? Does it match to the regexp in the model? Why do you suspect the code in question broke it for you?

**Comment by MarcusCaepio** [comment]
It seems that in 0.24 it was ok to set an "enable" password in the config, whether the device had an "ena" password set or not. Now it seems that as soon as an "ena" password is defined, it only works on devices where an ena password is really set. As we have a mix of devices where ena passwords are set and not set, I now changed the config to
models:
  ios:
    username: bot
    password: 123
    vars:
      enable: **true**

and in the router.db I have defined the real ena password of the devices, where one is set.
Every device runs correctly again now.

**Comment by ytti** [comment]
This is because previously we didn't support all the use-cases described in https://github.com/ytti/oxidized/issues/1716#issuecomment-470539054

**Comment by graywolf-at-work** [comment]
It should be possible to detect if enable is needed based on last character of the prompt (`#` vs `>`).

**Comment by ytti** [comment]
Sure. But it doesn't tell us should we expect enable password prompt or prompt. We could of course detect that too. But unsure if that's more desirable than the code we already have, as every case already works.

**Comment by graywolf-at-work** [comment]
Yeah we were just bitten by this change after upgrading `0.21.0` -> `0.26.3` and it stopped working :) Our ops guys wondered why it's not auto-detected so I just thought I would mention the possibility here.

I'm just not sure I see any advantage, since sending the password anyway even when not needed worked just fine.

**Comment by borison89** [comment]
> What is your enable password?
> 
> 1. "" - enable, expect enable prompt, send just newline
> 2. true - enable, do not expect enable prompt
> 3. nil - do not enable
> 4. any other string - enable, expect enable prompt, send string and newline

I have some troubles with my oxidized backup
some devices with without enable password synced correctly, but devices with enable password receave error  Timeout::Error with msg "execution expired"

`---
username: 1111
password: 2222
model: junos
resolve_dns: true
interval: 3600
use_syslog: false
debug: true
threads: 30
timeout: 120
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 127.0.0.1:8888
next_adds_job: false
vars:
  enable: 3333`

**Comment by MarcusCaepio** [comment]
See my last post

**Comment by borison89** [comment]
> See my last post

I added to the configuration this changes
models:
  ios:
    username: 1111
    password: 2222
  vars:
    enable: true
with out changes for me...

**Comment by rpardim** [comment]
I made a lot of tests and finally I get this to work.

/etc/oxidized/config
```
username: user
password: pass
vars:
 enable: enablepass
 
source:
  default: csv
  csv:
    file: /etc/oxidized/router.db
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
      group: 2
      username: 3
      password: 4
    vars: (I changed here from vars_map to vars)
      enable: 5

groups:
  NOTENABLE:
    models:
      ios:
        vars:
          enable: false
```

/etc/oxidized/router.db
```
device1:ios:NOTENABLE
device2:ios:ENABLENODE:user:pass:enablepass
device3:ios:ENABLE
```
