### ISSUE TITLE
Add formal parsing 

### ISSUE THREAD

**Issue by ytti** [ytti/oxidized#1720]
This is continuation of #1689 by @rbns

@rbns if you'll check the formal branch and continue off of that, that would be great.

**Comment by rbns** [comment]
first i need to understand how things are done in the formal branch and how to hook it up correctly. i didn't had the time recently, but i'll see into it.

**Comment by ytti** [comment]
no hurry, just admitting via this ticket that i'm not probably going to put more work into it just now, but would still love this being worked on, i hope the current stuff gives direction

**Comment by ytti** [comment]
also nothing is really set to stone, if i've done something you don't agree with, it's certainly up for discussion
