### ISSUE TITLE
Working with groups

### ISSUE THREAD

**Issue by montag196** [ytti/oxidized#1721]
Hello,

how can I set intervals for only one group? And how can I decide, how many versions he save, until he delete the old versions, because we don't need all.....

Thanks and Best regards from Germany

Daniel Montag

**Comment by berilslv** [comment]
possibly it's not possible if you use GIT output. Only group as batch... but im not sure.

**Comment by montag196** [comment]
And how can I decide, how many versions he save, until he delete the old versions, because we don't need all..... When we never delete anything it is no solution for us.... This is the main problem i have.

**Comment by davama** [comment]
looks like a git issue, outside of oxidized.

you not the first to post similar question
https://github.com/ytti/oxidized/issues/1123

**Comment by montag196** [comment]
And how can I decide, how many versions he save, until he delete the old versions, because we don't need all..... When we
