### ISSUE TITLE
Help Adding Nexus 3500 on oxidized

### ISSUE THREAD

**Issue by barto95100** [ytti/oxidized#1728]
Hi,

when I test o backup nexus switch I have this error : 

`D, [2019-03-06T19:01:26.259826 #15177] DEBUG -- : lib/oxidized/worker.rb: Added /sw-nexus-01 to the job queue
D, [2019-03-06T19:01:26.259917 #15177] DEBUG -- : lib/oxidized/job.rb: Starting fetching process for sw-nexus-01at 2019-03-06 18:01:26 UTC
D, [2019-03-06T19:01:26.260000 #15177] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2019-03-06T19:01:26.260176 #15177] DEBUG -- : lib/oxidized/input/ssh.rb: Connecting to sw-nexus-01
D, [2019-03-06T19:01:26.260363 #15177] DEBUG -- : AUTH METHODS::["none", "publickey", "password"]
D, [2019-03-06T19:01:26.827797 #15177] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^([\w.@()-]+[#>]\s?)$/] at sw-nexus-01
D, [2019-03-06T19:01:27.260483 #15177] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2019-03-06T19:01:28.260770 #15177] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2019-03-06T19:01:29.261038 #15177] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2019-03-06T19:01:30.261327 #15177] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2019-03-06T19:01:31.261654 #15177] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2019-03-06T19:01:32.261983 #15177] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2019-03-06T19:01:33.262251 #15177] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2019-03-06T19:01:34.262528 #15177] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2019-03-06T19:01:35.262840 #15177] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2019-03-06T19:01:36.263103 #15177] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2019-03-06T19:01:37.263363 #15177] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2019-03-06T19:01:38.263596 #15177] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2019-03-06T19:01:39.263852 #15177] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2019-03-06T19:01:40.264070 #15177] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2019-03-06T19:01:41.264310 #15177] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2019-03-06T19:01:42.264558 #15177] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2019-03-06T19:01:43.264868 #15177] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2019-03-06T19:01:44.265179 #15177] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2019-03-06T19:01:45.265447 #15177] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2019-03-06T19:01:46.265734 #15177] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
W, [2019-03-06T19:01:46.828396 #15177]  WARN -- : 10.2.1.251 raised Oxidized::PromptUndetect with msg "Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Copyright (c) 2002-2014, Cisco Systems, Inc. All rights reserved.
The copyrights to certain works contained in this software are
owned by other third parties and used and distributed under
license. Certain components of this software are licensed under
the GNU General Public License (GPL) version 2.0 or the GNU
Lesser General Public License (LGPL) Version 2.1. A copy of each
such license is available at
http://www.opensource.org/licenses/gpl-2.0.php and
http://www.opensource.org/licenses/lgpl-2.1.php
SW-ITX-CORE-1#  not matching configured prompt (?-mix:^([\w.@()-]+[#>]\s?)$)"
D, [2019-03-06T19:01:46.828577 #15177] DEBUG -- : lib/oxidized/node.rb: Oxidized::SSH failed for sw-nexus-01
D, [2019-03-06T19:01:47.266041 #15177] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2019-03-06T19:01:48.266353 #15177] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2019-03-06T19:01:49.266621 #15177] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2019-03-06T19:01:50.266938 #15177] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2019-03-06T19:01:51.267287 #15177] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2019-03-06T19:01:52.267556 #15177] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2019-03-06T19:01:53.267839 #15177] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2019-03-06T19:01:54.268088 #15177] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2019-03-06T19:01:55.268357 #15177] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2019-03-06T19:01:56.268641 #15177] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2019-03-06T19:01:57.268975 #15177] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2019-03-06T19:01:58.269287 #15177] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2019-03-06T19:01:59.269631 #15177] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2019-03-06T19:02:00.269958 #15177] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2019-03-06T19:02:01.270283 #15177] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2019-03-06T19:02:02.270611 #15177] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2019-03-06T19:02:03.270898 #15177] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2019-03-06T19:02:04.271167 #15177] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2019-03-06T19:02:05.271428 #15177] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2019-03-06T19:02:06.271731 #15177] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
W, [2019-03-06T19:02:06.829461 #15177]  WARN -- : 10.2.1.251 raised Net::OpenTimeout (rescued Timeout::Error) with msg "timed out while opening a connection to the host"`

Do you have idea what's the problem ? 

thank for your help :)

**Comment by jarner** [comment]
What does your config and router.db file look like for this? I have Nexus 9k's polling just fine using the nxos. https://github.com/ytti/oxidized/blob/master/docs/Supported-OS-Types.md

**Comment by barto95100** [comment]
Hoooooo, It's OK I don't understand on router.db to change ios (switch 2960) to nxos (for nexus)

Now it's great

Thank you 👍
