### ISSUE TITLE
Custom SSH Port?

### ISSUE THREAD

**Issue by etern4ever** [ytti/oxidized#173]
Looking at this to replace the Rancid we have running.  But from the documentation and using the conversion tool, it appears you can't use custom SSH Ports?

Is that correct or am I missing something?  I haven't looked through the code yet because I don't know Ruby.

**Comment by ytti** [comment]
Not currently supported. It wouldn't be too hard to add it, I'm willing to do it.

Do you need it on globally, applicable to every node, or per-node, like column in router.db?

**Comment by etern4ever** [comment]
column in router.db would be perfect.  Thanks!

**Comment by ytti** [comment]
Can you check if 9844a72c0487d33c38d4 fixes this issue?

```
source:
  cvs:
    vars_map:
      ssh_port: 4
```

I'd love if you could also test telnet_port.

**Comment by etern4ever** [comment]
I will test this soon for you.

**Comment by ytti** [comment]
It definitely had precedence issue at least, fixed it just now. But no clue still if it actually works. If not, I'll actually test next time.

**Comment by etern4ever** [comment]
I tested with two devices and it appears to be working fine.  I will be spinning up VMs for the rancid replacement project soon.  Will let you know if it hit any hiccups with a larger number of devices.

**Comment by ytti** [comment]
Closing as reported working
