### ISSUE TITLE
HP V1910-24G config issue

### ISSUE THREAD

**Issue by krtek666** [ytti/oxidized#1732]
Hi there,

I tried search here to get the answer, but nothing worked for me.
I have Librenms vm with Oxidized and Librenms as a Ozidized source in config.
I am getting:
`
          ^
  % Unrecognized command found at '^' position.
          ^
  % Unrecognized command found at '^' position.
         ^
 % Unrecognized command found at '^' position.
`

I think it is due to not passing the password 512900 after system sends _cmdline-mode. I do not know where to define the comware_cmdline variable as I do not use router.db. I have tried to put it in oxidized config, but that did not work for me:
`username:
password:
model: vrp
resolve_dns: true
interval: 3600
use_syslog: false
log: "~/.config/oxidized/logs/oxidized.log"
debug: enable
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 127.0.0.1:8888
next_adds_job: false
vars:
 enable: true
 comware_cmdline: 512900
groups: {}
models: {}
pid: "~/.config/oxidized/pid"
crash:
  directory: "~/.config/oxidized/crashes"
  hostnames: false
stats:
  history_size: 10
input:
  default: ssh, telnet
  debug: false
  ssh:
    secure: false
  ftp:
    passive: true
  utf8_encoded: true
output:
  default: git
  git:
      user: Oxidized
      email: oxidized@example.com
      repo: "~/.config/oxidized/oxidized.git"
source:
        default: http
        debug: false
        http:
          url: http://127.0.0.1/api/v0/oxidized
          map:
            name: hostname
            model: os
            group: group
          headers:
            X-Auth-Token: 'blablabla'
model_map:
  huawei: vrp
  hp: Comware
`
Anyone can please shed a light on how to use the variables?
Thanks a lot.

**Comment by berilslv** [comment]
hi , just add another value  = 
vars_map:
   comware_cmdline: 4(your indexing number)

**Comment by krtek666** [comment]
Thanks for help. I am not sure how I could use the vars_map if I am not using router.db, but I got it to work.
I declared the comware_cmdline in Oxidized config global vars as below:
<pre>
<code>rest: 127.0.0.1:8888 /br
next_adds_job: false
vars:
  comware_cmdline: "512900"
groups: {}
models: {}</code>
</pre>

**Comment by berilslv** [comment]
Great! Please close the ticket! ;)
