### ISSUE TITLE
Issue backup with vrp.rb for router Huawei AR29-21

### ISSUE THREAD

**Issue by kvadime** [ytti/oxidized#1734]
Please help if you can.
I have issue backup with vrp.rb for router Huawei AR29-21
in the output file I received:  _% Too many parameters found at '^' position._

I see in file vrp.rb: 
----------------------------------------------
  cmd 'display current-configuration all' do |cfg|
      cfg
-------------------------------------------------
But my model Huawei ar29-21 : 
     no support command: "display current-configuration all"
           support command: "display current-configuration"
I try delit word "all" in vrp.rb, but it does not work.

This router have just privilege level 1-3. I use level 3. From this user I easy make display current-configuration, without command system-view

**Comment by jarner** [comment]
When you edited the file, did the change save? If it did you have to restart oxidized in order for the change to take effect.

**Comment by kvadime** [comment]
Obviously I save in restarted the Oxidized. But that did not help

**Comment by kvadime** [comment]
I finded solution for me. I just use for Huawei, model from comware.rb. Is work.
