### ISSUE TITLE
HTTP Input in docker doesn't work missing mechanize

### ISSUE THREAD

**Issue by cchance27** [ytti/oxidized#1737]
I noticed that the http input fails to work in docker, managed to get it working by doing 

apt install make zlib1g-dev
gem install mechanize

Is it possible to have that included so that the http input works by default in docker, as it's infinitely useful

**Comment by ytti** [comment]
Hmm. Good point. Docker probably needs to include everything that might possibly be needed, as ad-hoc addition of what is actually needed is not feasible.

**Comment by cchance27** [comment]
Indeed. Not sure if anything else isn't included as only use telnet/ssh/http for my network but base image should include all required for the plugins to work as my solution to hacking it to work only works till the pod gets recreated and refreshed back to stock
