### ISSUE TITLE
Email Notification on Failed Attempts

### ISSUE THREAD

**Issue by etern4ever** [ytti/oxidized#174]
Another thing rancid provides is a notification when the config isn't able to be pulled for 24+ hours.

I assume my only option is the use the API, loop through all the devices doing a node/show, and looking at the status/dates?

**Comment by ytti** [comment]
The webpage already has list of nodes not seen in +24hours, available as JSON too.

We also added hooks support last week (not in  master yet, in feature branch, pending testing) and hooks would allow some triggered behaviour when certain conditions are met.
One of the conditions when hook can be called are 'node success' and 'node fail'.

**Comment by etern4ever** [comment]
This will work, I guess you need to build the actions that happen when one of these trigger yourself.

Thanks!

**Comment by supertylerc** [comment]
@etern4ever- can this be closed?

**Comment by ytti** [comment]
Closing due to lack of comments. Please reopen if needed.
