### ISSUE TITLE
Cambium Canopy backups causes constant diff

### ISSUE THREAD

**Issue by cchance27** [ytti/oxidized#1740]
When performing backups from cambium canopy devices every time the backup runs it creates a new diff this seems to be due to a line in the config that shows the timestamp the config was pulled.

The cfgUtcTimestamp changes constantly, if we can exclude that from the config backup it would solve the issue.

```
@@ -498,7 +498,7 @@
    "priorityPrecedence": 0
   }
  },
+ "cfgUtcTimestamp": "2019-03-14T18:33:33Z",
  "configFileParameters": {
   "rebootIfRequired": false,
   "setToDefaults": false
```

**Comment by ytti** [comment]
Copy the model into ~/.config/oxidized/model/ directory and modify it to  change the timestamp to say NNNNN.

something like

```ruby
cfg = JSON.parse(cfg)
cfg["cfgUtcTimestamp"] = "0000-00-00T00:00:00Z" if cfg.has_key?("cfgUtcTimestamp")
JSON.pretty_generate(cfg)
```

or 

```ruby
cfg.each_line.map do |line|
   key, value = line.split(": ")
  if key == '"cfgUtcTimestamp"'
    key + ": " + "0000-00-00T00:00:00Z"
  else
    line
  end
end
```

**Comment by cchance27** [comment]
hmmm odd I tried that but it seemed to somehow break the backups completely like the model stopped updating even though I made a change to its configuration, removed the cambium.rb from the /model directory and restarted the docker instance and it started backing up everything again (literally everything because all the timestamps changed)

**Comment by ytti** [comment]
I wrote those as inspiration, not as tested working code. So it wouldn't seem odd to me if there is problem in the  code or if it was misapplied.
