### ISSUE TITLE
Oxidized as service/auto-start

### ISSUE THREAD

**Issue by berilslv** [ytti/oxidized#1745]
Hi guys,
Looking for help configuring oxidized as auto start service. Im failing several days and im getting nuts.
I hope somebody can help me in this case.
So my config is:
It's been build on new user=oxidized
Config/router/etc. is living @ 

> /home/oxidized/.config/oxidized 

> $ which oxidized
> /usr/local/rvm/gems/ruby-2.3.5/bin/oxidized

 @ /etc/systemd/system/ i have copied file oxidized.service which looks like this:

> > [Unit]
> Description=Oxidized - Network Device Configuration Backup Tool
> After=network-online.target multi-user.target
> Wants=network-online.target
> 
> [Service]
> ExecStart=/usr/local/rvm/gems/ruby-2.3.5/bin/oxidized
> User=oxidized
> KillSignal=SIGKILL
> #Environment="OXIDIZED_HOME=/etc/oxidized"
> 
> [Install]
> WantedBy=multi-user.target

After reboot , and typing systemctl start oxidized.service , im getting error message:

> [oxidized@localhost ~]$ systemctl status oxidized.service -l
> ● oxidized.service - Oxidized - Network Device Configuration Backup Tool
>    Loaded: loaded (/etc/systemd/system/oxidized.service; enabled; vendor preset: disabled)
>    Active: failed (Result: exit-code) since Mon 2019-03-18 09:10:55 EET; 10s ago
>   Process: 4742 ExecStart=/usr/local/rvm/gems/ruby-2.3.5/bin/oxidized (code=exited, status=127)
>  Main PID: 4742 (code=exited, status=127)
> 
I guess i have missed something only i dont know where to dig.
If more info is required to determine issue, please let me know.

P.S im using RVM ruby version 2.3.7

**Comment by WiXZlo** [comment]
Use wrapper, where used corret variables.
My service on centos 7:
`
ExecStart=/usr/local/rvm/gems/ruby-2.3.8/wrappers/oxidized
`

**Comment by berilslv** [comment]
> Use wrapper, where used correct variables.
> My service on centos 7:
> `ExecStart=/usr/local/rvm/gems/ruby-2.3.8/wrappers/oxidized`

thanks, i found another , maybe not that good solution, but nohup & is working for my case. 
But i'll try your suggestion. Thanks mate!

**Comment by NatalNW** [comment]
> Use wrapper, where used correct variables.
> My service on centos 7:
> `ExecStart=/usr/local/rvm/gems/ruby-2.3.8/wrappers/oxidized`

It worked for me, thanks
my service:
> ExecStart=/etc/oxidized/.rvm/gems/ruby-2.6.3/wrappers/oxidized
