### ISSUE TITLE
QuantaOS terminal pager ( --more-- )

### ISSUE THREAD

**Issue by kpostrup** [ytti/oxidized#1749]
I am using oxidized-0.26.3 and I have about 10 Quanta LB9 and X3 switches that currently is not working with Oxidized. I am using the **QuantaOS** model.

I get the following warnings in `oxidized.log`:
```
W, [2019-03-19T15:56:10.876785 #25102]  WARN -- : x.x.x.x raised Oxidized::PromptUndetect with msg "
(switchname) #
(switchname) #--More-- or (q)uit not matching configured prompt (?-mix:^\((\w|\S)+\) (>|#)$)"
```
It looks like the current QuantaOS module does not take care of paging / terminal length.
We could simply disable the pager (on a per session basis) when logging in, by running:
```
no pager
```

**Comment by wk** [comment]
Overriding or extending models with Oxidized is [quite straightforward](https://github.com/ytti/oxidized/blob/master/docs/Creating-Models.md). You should be able to take the existing `quantaos.rb` file, and extend it by locating the line that says `post_login 'terminal length 0'` and adding another line that says `post_login 'no pager'` after it - saving the result as `quantaos.rb` in your `~/.config/oxidized/model/` directory within your installation.

If this works and solves your problem after restarting Oxidized, don't hesitate to create a PR with this change (ideally, after validating that the `no pager` command exists across other QuantaOS devices and software versions).

**Comment by kpostrup** [comment]
Thank you. I'll do that.
