### ISSUE TITLE
Model Addition/Change Documentation

### ISSUE THREAD

**Issue by etern4ever** [ytti/oxidized#175]
So..  When adding or changing a model (I haven't dug into the code.  Still learning ruby), I assume I need to put/change them in the installed directory?  

IE ./var/lib/gems/2.1.0/gems/oxidized-0.7.2/lib/oxidized/model/

**Comment by etern4ever** [comment]
NM... looking through issues, I found my answer.  I can put them in the config path, correct?

/etc/oxidized/model/ or ~/.config/oxidized/model/

**Comment by ytti** [comment]
Yeah you can have them there locally, easier for hacking or if you need to use model which you don't want to commit to upstream or upstream is evil and does not accept.
