### ISSUE TITLE
D-Link handle ' System locked by other session!'

### ISSUE THREAD

**Issue by ABATAPA** [ytti/oxidized#1752]
Hello!

When D-Link devices save or transfer config (on other VT, from TFTP etc), the config is locked for reading.
When you try to read it issued " the system is blocked by another session!", but oxidized knows nothing about it and and considers the config changed (and clean). 8( 
Needs include such a response in the error handler and consider the attempt unsuccessful.

Example:

diff --git a/NAME b/NAME
index cad7f21..a35facb 100644
+++ b/NAME
@@ -2838,2486 +2838,5 @@
 # 
 # 
 
\+ System locked by other session!

**Comment by alexanderek** [comment]
Hello from 2023. Is there any solution? )
