### ISSUE TITLE
Oxidized can't retrive cisco configuration

### ISSUE THREAD

**Issue by lindachtg** [ytti/oxidized#1755]
I installed oxidized in ubuntu, but somehow it can't retrive cisco configuration. 

Have no idea why it doesn't have "show running-config",  could someone help to look into this issue?  Thank you!

Result as below:

! Cisco IOS Software, 7200 Software (C7200P-SPSERVICESK9-M), Version 12.4(15)T14, RELEASE SOFTWARE (fc2)
! 
! Image: Software: C7200P-SPSERVICESK9-M, 12.4(15)T14, RELEASE SOFTWARE (fc2)
! Image: Compiled: Tue 17-Aug-10 16:18 by prod_rel_team
! ROM Bootstrap: Version 12.4(12.2r)T, RELEASE SOFTWARE (fc1)
! Image: disk2:c7200p-spservicesk9-mz.124-15.T14.bin
! Chassis type: 7206VXR
! Memory: main 1966080K/65536K
! Processor ID: 37071050
! CPU: NPE-G2, MPC7448 CPU at 1666Mhz, Implementation 0, Rev 2.2
! Memory: nvram 2045K
! Memory: pcmcia ATA slot2 254464K
! Memory: flash 65536K
! 
! VTP: show vtp status
! 
! NAME: "Chassis", DESCR: "Cisco 7206VXR, 6-slot chassis"
! PID: CISCO7206VXR      , VID:    , SN: 37071050   
! 
! NAME: "NPE-G2 0", DESCR: "Cisco 7200 Series Network Processing Engine NPE-G2"
! PID: NPE-G2            , VID: V03 , SN: JAF1443AKCA
! 
! NAME: "disk2", DESCR: "256MB Compact Flash Disk for NPE-G2"
! PID: MEM-NPE-G2-FLD256 , VID:    , SN:            
! 
! NAME: "module 1", DESCR: "FastEthernet"
! PID: PA-FE-TX          , VID:    , SN: 8534105    
! 
! NAME: "module 2", DESCR: "2 Port Fast Ethernet/ISL 100BaseTX Port Adapter"
! PID: PA-2FEISL-TX=     , VID:    , SN: 16794595   
! 
! NAME: "module 3", DESCR: "POS Port Adapter (SM)"
! PID: PA-POS-OC3SMI=    , VID:    , SN: 27101759   
! 
! NAME: "module 4", DESCR: "POS Port Adapter (SM)"
! PID: PA-POS-OC3SMI=    , VID:    , SN: 24465287   
! 
! NAME: "Power Supply 1", DESCR: "Cisco 7200 AC Power Supply"
! PID: PWR-7200-AC       , VID:    , SN:            
! 
! NAME: "Power Supply 2", DESCR: "Cisco 7200 AC Power Supply"
! PID: PWR-7200-AC       , VID:    , SN:            
! 
! 

And ios.rb shown below:

class IOS < Oxidized::Model
  prompt /^([\w.@()-]+[#>]\s?)$/
  comment  '! '

  # example how to handle pager
  # expect /^\s--More--\s+.*$/ do |data, re|
  #  send ' '
  #  data.sub re, ''
  # end

  # non-preferred way to handle additional PW prompt
  # expect /^[\w.]+>$/ do |data|
  #  send "enable\n"
  #  send vars(:enable) + "\n"
  #  data
  # end

  cmd :all do |cfg|
    # cfg.gsub! /\cH+\s{8}/, ''         # example how to handle pager
    # cfg.gsub! /\cH+/, ''              # example how to handle pager
    # get rid of errors for commands that don't work on some devices
    cfg.gsub! /^% Invalid input detected at '\^' marker\.$|^\s+\^$/, ''
    cfg.cut_both
  end

  cmd :secret do |cfg|
    cfg.gsub! /^(snmp-server community).*/, '\\1 <configuration removed>'
    cfg.gsub! /^(snmp-server host \S+( vrf \S+)?( version (1|2c|3))?)\s+\S+((\s+\S*)*)\s*/, '\\1 <secret hidden> \\5'
    cfg.gsub! /^(username .+ (password|secret) \d) .+/, '\\1 <secret hidden>'
    cfg.gsub! /^(enable (password|secret)( level \d+)? \d) .+/, '\\1 <secret hidden>'
    cfg.gsub! /^(\s+(?:password|secret)) (?:\d )?\S+/, '\\1 <secret hidden>'
    cfg.gsub! /^(.*wpa-psk ascii \d) (\S+)/, '\\1 <secret hidden>'
    cfg.gsub! /^(.*key 7) (\d.+)/, '\\1 <secret hidden>'
    cfg.gsub! /^(tacacs-server (.+ )?key) .+/, '\\1 <secret hidden>'
    cfg.gsub! /^(crypto isakmp key) (\S+) (.*)/, '\\1 <secret hidden> \\3'
    cfg.gsub! /^(\s+ip ospf message-digest-key \d+ md5) .+/, '\\1 <secret hidden>'
    cfg.gsub! /^(\s+ip ospf authentication-key) .+/, '\\1 <secret hidden>'
    cfg.gsub! /^(\s+neighbor \S+ password) .+/, '\\1 <secret hidden>'
    cfg.gsub! /^(\s+vrrp \d+ authentication text) .+/, '\\1 <secret hidden>'
    cfg.gsub! /^(\s+standby \d+ authentication) .{1,8}$/, '\\1 <secret hidden>'
    cfg.gsub! /^(\s+standby \d+ authentication md5 key-string) .+?( timeout \d+)?$/, '\\1 <secret hidden> \\2'
    cfg.gsub! /^(\s+key-string) .+/, '\\1 <secret hidden>'
    cfg.gsub! /^((tacacs|radius) server [^\n]+\n(\s+[^\n]+\n)*\s+key) [^\n]+$/m, '\1 <secret hidden>'
    cfg
  end

  cmd 'show version' do |cfg|
    comments = []
    comments << cfg.lines.first
    lines = cfg.lines
    lines.each_with_index do |line, i|
      slave = ''
      slaveslot = ''

      if line =~ /^Slave in slot (\d+) is running/
        slave = " Slave:"
        slaveslot = ", slot #{Regexp.last_match(1)}"
      end

      comments << "Image:#{slave} Compiled: #{Regexp.last_match(1)}" if line =~ /^Compiled (.*)$/

      comments << "Image:#{slave} Software: #{Regexp.last_match(1)}, #{Regexp.last_match(2)}" if line =~ /^(?:Cisco )?IOS .* Software,? \(([A-Za-z0-9_-]*)\), .*Versi
on\s+(.*)$/

      comments << "ROM Bootstrap: #{Regexp.last_match(3)}" if line =~ /^ROM: (IOS \S+ )?(System )?Bootstrap.*(Version.*)$/

      comments << "BOOTFLASH: #{Regexp.last_match(1)}" if line =~ /^BOOTFLASH: .*(Version.*)$/

      comments << "Memory: nvram #{Regexp.last_match(1)}" if line =~ /^(\d+[kK]) bytes of (non-volatile|NVRAM)/

      comments << "Memory: flash #{Regexp.last_match(1)}" if line =~ /^(\d+[kK]) bytes of (flash memory|flash internal|processor board System flash|ATA CompactFlash)
/i

      comments << "Memory: pcmcia #{Regexp.last_match(2)} #{Regexp.last_match(3)}#{Regexp.last_match(4)} #{Regexp.last_match(1)}" if line =~ /^(\d+[kK]) bytes of (Fl
ash|ATA)?.*PCMCIA .*(slot|disk) ?(\d)/i

      if line =~ /(\S+(?:\sseries)?)\s+(?:\((\S+)\)\s+processor|\(revision[^)]+\)).*\s+with (\S+k) bytes/i
        sproc = Regexp.last_match(1)
        cpu = Regexp.last_match(2)
        mem = Regexp.last_match(3)
        cpuxtra = ''
        comments << "Chassis type:#{slave} #{sproc}"
        comments << "Memory:#{slave} main #{mem}"
        # check the next two lines for more CPU info
        comments << "Processor ID: #{Regexp.last_match(1)}" if cfg.lines[i + 1] =~ /processor board id (\S+)/i
        if cfg.lines[i + 2] =~ /(cpu at |processor: |#{cpu} processor,)/i
          # change implementation to impl and prepend comma
          cpuxtra = cfg.lines[i + 2].gsub(/implementation/, 'impl').gsub(/^/, ', ').chomp
        end
        comments << "CPU:#{slave} #{cpu}#{cpuxtra}#{slaveslot}"
      end

      comments << "Image: #{Regexp.last_match(1)}" if line =~ /^System image file is "([^"]*)"$/
    end
    comments << "\n"
    comment comments.join "\n"
  end

  cmd 'show vtp status' do |cfg|
    cfg.gsub! /^$\n/, ''
    cfg.gsub! /^/, 'VTP: ' unless cfg.empty?
    comment "#{cfg}\n"
  end

  cmd 'show inventory' do |cfg|
    comment cfg
  end

  cmd 'show running-config' do |cfg|
    cfg = cfg.each_line.to_a[3..-1]
    cfg = cfg.reject { |line| line.match /^ntp clock-period / }.join
    cfg.gsub! /^Current configuration : [^\n]*\n/, ''
    cfg.gsub! /^ tunnel mpls traffic-eng bandwidth[^\n]*\n*(
                  (?: [^\n]*\n*)*
                  tunnel mpls traffic-eng auto-bw)/mx, '\1'
  end

  cfg :telnet do
    username /^Username:/i
    password /^Password:/i
  end

  cfg :telnet, :ssh do
    # preferred way to handle additional passwords
    post_login do
      if vars(:enable) == true
        cmd "enable"
      elsif vars(:enable)
        cmd "enable", /^[pP]assword:/
        cmd vars(:enable)
      end
    end
    post_login 'terminal length 0'
    post_login 'terminal width 0'
    pre_logout 'exit'
  end

end

And the progress of ssh login to cisco

login as: linda
Using keyboard-interactive authentication.
This is TACACS+ authenticated device

Password: ********

Cisco>enable
Cisco#

**Comment by ytti** [comment]
What is value of your enable password? It should be 'true'. Which means you need to enable, but there won't be any password prompt.

**Comment by lindachtg** [comment]
Hi ytti,
Could you let me know the correct statement at ios.rb?

**Comment by ytti** [comment]
You do not need to touch ios.rb. You need to set your enable password variable as ```true``` or you need to configure your devices to autoenable.

**Comment by lindachtg** [comment]
In fact, my cisco just only key "enable", the status "cisco>" will change to "cisco#"
the oxidized configuration as following, could you show me the correct statement?


---
username: linda
password: linda
model: cisco
resolve_dns: true
interval: 3600
use_syslog: false
debug: true
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 127.0.0.1:8888
next_adds_job: false
**vars: 
  enable:** 
groups: {}
models: {}
pid: "/home/linda/.config/oxidized/pid"
stats:
  history_size: 10
input:
  default: ssh, telnet
  debug: true
  ssh:
    secure: false
  ftp:
    passive: true
  utf8_encoded: true
output:
 default: file
 file:
   directory: /home/linda/.config/oxidized/configs
output:
 default: git
 git:

**Comment by ytti** [comment]
You neeed to set ```enable: true```

**Comment by lindachtg** [comment]
I set enable: true and restart oxidized, but the problem still persist. Is there any others need to check?

===============
username: linda
password: linda
model: cisco
interval: 3600
use_syslog: true
log: /etc/oxidized/.config/oxidized/logs/
debug: true
rest: false
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
next_adds_job: false
vars:
   **enable: true**
pid: "/etc/oxidized/pid"

input:
  default: ssh
  debug: true
  ssh:
    secure: false
