### ISSUE TITLE
custom openbsd model with enable not working

### ISSUE THREAD

**Issue by vizay** [ytti/oxidized#1758]
I'm currently under way trying to build a custom implementation of the openbsd model with "enable" support (needed due to regulatory reasons for the company) but it's not behaving as expected.

First off I tried the methodology used for the regular openbsd and cumulus models, running all the commands under pre do, but didn't get that working. I then reverted back to creating the below, just to get a working prototype but not even that seems to be functioning.

### The problem
What happens is basically that as soon as I have a cmd running (like here, cat /etc/pf.conf) it never runs the command `su -` to elevate.

I've tried running without the `cmd :all do |cfg|` and then it elevates and runs the command, however no config is committed. This leads me to believe that it's at least not a problem with faulty or missing node source data (using mysql as source and the data is clearly there and correct).

It feels like I'm missing something here. I've tried analyzing pretty much all other models and this looks like it should work, but it isn't for some reason.

Thanks in advance for input on this!

### Code
```ruby
class Openbsd < Oxidized::Model

    prompt /^((\w*)@*(.*))$/
    comment '# '

    cmd :all do |cfg|
        cfg = cfg.cut_both
    end

    cfg :ssh do
        post_login do
            if vars(:enable)
                cmd "su -", /^Password:/
                cmd vars(:enable)
            end
        end
        pre_logout do
            cmd "exit" if vars(:enable)
        end
        pre_logout 'exit'
    end

    cmd 'cat /etc/pf.conf' do |cfg|
        cfg
    end
end
```
### Crashlog
> 2019-03-26 08:51:21 UTC
> undefined method `join' for nil:NilClass [NoMethodError]
> --------------------------------------------------
> /root/.config/oxidized/model/openbsd.rb:18:in `block in <class:Openbsd>'
> /var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/model/model.rb:107:in `instance_exec'
> /var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/model/model.rb:107:in `block in cmd'
> /var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/model/model.rb:106:in `each'
> /var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/model/model.rb:106:in `cmd'
> /var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/model/model.rb:152:in `block in get'
> /var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/model/model.rb:151:in `each'
> /var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/model/model.rb:151:in `get'
> /var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/input/cli.rb:14:in `get'
> /var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/node.rb:67:in `run_input'
> /var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/node.rb:44:in `block in run'
> /var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/node.rb:38:in `each'
> /var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/node.rb:38:in `run'
> /var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/job.rb:9:in `block in initialize'

### Debug log (sanitised ofc)
> DEBUG -- : lib/oxidized/worker.rb: Added nodeName to the job queue
> DEBUG -- : lib/oxidized/job.rb: Starting fetching process for nodeName at 2019-03-26 08:51:16 UTC
> DEBUG -- : lib/oxidized/input/ssh.rb: Connecting to nodeName
> DEBUG -- : AUTH METHODS::["none", "publickey", "password"]
> DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^((\w*)@*(.*))$/] at nodeName
> DEBUG -- : lib/oxidized/input/cli.rb: Running post_login commands at nodeName
> DEBUG -- : lib/oxidized/input/cli.rb: Running post_login command: nil, block: #<Proc:0x0000564739d8def8@/root/.config/oxidized/model/openbsd.rb:97> at nodeName
> DEBUG -- : lib/oxidized/input/ssh.rb su - @ nodeName with expect: /^Password:/
> DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^Password:/] at nodeName
> DEBUG -- : lib/oxidized/worker.rb: 2 jobs running in parallel
> DEBUG -- : lib/oxidized/input/ssh.rb Password @ nodeName with expect: /^((\w*)@*(.*))$/
> DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^((\w*)@*(.*))$/] at nodeName
> DEBUG -- : lib/oxidized/model/model.rb Collecting commands' outputs
> DEBUG -- : lib/oxidized/model/model.rb Executing cat /etc/pf.conf
> DEBUG -- : lib/oxidized/input/ssh.rb cat /etc/pf.conf @ nodeName with expect: /^((\w*)@*(.*))$/
> DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^((\w*)@*(.*))$/] at nodeName
> ERROR -- : 10.0.0.2 raised NoMethodError with msg "undefined method `join' for nil:NilClass", 10.0.0.2 saved
> DEBUG -- : lib/oxidized/node.rb: Oxidized::SSH failed for nodeName
> DEBUG -- : lib/oxidized/job.rb: Config fetched for nodeName at 2019-03-26 08:51:17 UTC
>  WARN -- : nodeName status no_connection, retry attempt 1

**Comment by vizay** [comment]
As an addition, I suspect the fact that it crashes is because it's being sent a cfg with no data in it, since it never elevates and thus `cat /etc/pf.conf` never runs properly.

So the main question is why enable stops working when commands are added?

**Comment by ytti** [comment]
I suspect we don't have enough lines for ```#cut_both``` and we're calling ```#join``` on nil, which is invalid. 

We likely need to modify ```cut_head``` and ```cut_tail``` implementation to return empty string when they run out of lines to cut.

**Comment by ytti** [comment]
Perhaps try this https://github.com/ytti/oxidized/blob/fix-1758/lib/oxidized/string.rb

**Comment by vizay** [comment]
@ytti Tried the patch and it's working, now I can run everything both as single cmd blocks and all commands in a pre block.

Now I just need to figure out / debug why it's not getting any data, but that could be considered another case I believe since I haven't figured out if it's on the oxidized end or node end that it's not functioning properly

**Comment by ytti** [comment]
Maybe the patch now always returns empty string, I don't know why it should, but you can try and replace the "" with "foo" :)

**Comment by vizay** [comment]
That was correct, tried passing in foo the way you suggested and that surely gave me a config with lots of foo in it :D 

With that said, I did notice after a bit of testing back and forth that running with `exec true` actually works to get data out, however now it's not running the commands within the post_login block. I'm not sure it's actually a bug or if it's just how the design of the system works, but it seems like it would be kind of helpful if it actually worked :P 

I verified that it's in fact never sending the `su -` command on the openbsd machine itself.

### Current code
``` ruby
class Openbsd < Oxidized::Model

    prompt /^((\w*)@*(.*))$/
    comment '# '

    # Add a comment between files/configs
    def add_comment(comment)
        "\n------ #{comment} ------\n"
    end

    cmd :all do |cfg|
        cfg
    end

    pre do
        cfg = add_comment('HOSTNAME')
        cfg += cmd('cat /etc/myname')

        cfg += add_comment('BGPDCONF FILE')
        cfg += cmd('cat /etc/bgpd.conf')
    end

    cfg :telnet do
        username /^Username:/
        password /^Password:/
    end

    cfg :telnet, :ssh do
        exec true
        post_login do
            if vars(:enable)
                cmd "su -", /^Password:/
                cmd vars(:enable)
            end
        end
        pre_logout do
            cmd "exit" if vars(:enable)
        end
        pre_logout 'exit'
    end
end
```
### Debug log
> DEBUG -- : lib/oxidized/worker.rb: Added nodeName to the job queue
> DEBUG -- : lib/oxidized/job.rb: Starting fetching process for nodeName at 2019-03-27 14:14:32 UTC
> DEBUG -- : lib/oxidized/input/ssh.rb: Connecting to nodeName
> DEBUG -- : lib/oxidized/input/cli.rb: Running post_login commands at nodeName
> DEBUG -- : lib/oxidized/input/ssh.rb cat /etc/myname @ nodeName with expect: /^((\w*)@*(.*))$/
> DEBUG -- : lib/oxidized/input/ssh.rb cat /etc/bgpd.conf @ nodeName with expect: /^((\w*)@*(.*))$/
> DEBUG -- : lib/oxidized/input/cli.rb Running pre_logout commands at nodeName
> DEBUG -- : lib/oxidized/node.rb: Oxidized::SSH ran for nodeName successfully
> DEBUG -- : lib/oxidized/job.rb: Config fetched for nodeName at 2019-03-27 14:14:33 UTC
>  INFO -- : Configuration updated for nodeName

**Comment by ytti** [comment]
I think you may be confused in what ```exec true``` does, the ```su``` is non-sensical with exec. What exec does it creates exec channel, runs command and returns. There is no session and no state. You can run 'su' in exec channel and return, but it does you no good for the subsequent exec channel.

I think you should simplify. First, run command that you know will print output, with or without su, like 'ls /etc'. If you get output, with the patch, then you know for some reason your su is not working. Then you can focus on that problem. 

You can also turn on input debugging via
```
input:
  debug: true
```

which will create session file, so you can see what is going on. 

I suspect everything else was correct in your initial attempt, except su is not working, so cat is returning nothing which causes cut_both to return nil. So patch likely works just fine, just there still isn't any output to work with.

**Comment by vizay** [comment]
Had a try at the original code again, with debugging on for input (thanks, I'd actually missed that for some reason, does help a lot!).

seems I get stuck on the `Password:` prompt

gonna have to dig deeper into this as it's probably the root cause for no data beeing sent.

safe to say I think the patch is working as intended, however the question is what's more clear. Generating a crash when data is non-existant or just putting empty data in there, thus not generating a config at all? :)

**Comment by ytti** [comment]
in su? Try to view the file with some editor which shows special characthers. Perhaps there is \r at start of the line or something like that, which causes regexp not to match. Quick and dirty might be to match something less complete.

**Comment by vizay** [comment]
Turned out the regexp I used was just not catching whatever special things that came out (seems to be some newline shenanigans going on).

Thanks for the assistance and guidance on this!

As I mentioned before I'm not sure the patch is needed or if it's just more clear to throw a crash at the user if nil input is sent to the cut_both function. I'll leave that decision up to you :)

**Comment by ytti** [comment]
Our option space is

1. do nothing
2. use the patch as-is, always return empty string 
3. remove ```|| ""```from the patch, so we return nil, if we cut everything

**Comment by vizay** [comment]
to my ears option 3 sounds like a good middle way. It's easy to debug and the whole system doesn't crash just because you made a mistake with one single model
