### ISSUE TITLE
Triggered updates with custom msgs

### ISSUE THREAD

**Issue by oljustice** [ytti/oxidized#1763]
I've been trying to get custom update messages with triggered updates using `/node/next` however my attempts at this using curl have been unsuccessful so far. Here is an example of my curl (sanitized):

`curl -X PUT -d '{"user":"testuser","from":"testuser@test.com,"msg":"Message number 646326"}' -k "https://oxidized-production.company.net/oxidized/node/next/border.router.net?format=json"`

I'm not getting errors however when I check the local git repo (I'm using git for output), I'm not seeing any triggered update at all, much less one with my custom message. I have been able to fetch as well as reload using other `/node` methods so I'm _fairly_ sure my config is correct and the rest api is indeed listening. I thought I would give this a shot using the ruby method however I've looked over #516, and the examples lack context. I am no ruby dev, nor am I familiar with the language (I'm more of a Python guy). How would I actually leverage `rest_client.rb`? In #516 the example below is shown:

```
rest = Oxidized::RestClient.new('localhost', 8888)
rest.next(name: 'device', user: 'username', msg: 'commit message goes here')
```

Would this go into a separate wrapper ruby file/module? Am I supposed to edit `rest_client.rb` itself accordingly? What's the 'for dummies' procedure for using this module for my purposes?

**Comment by ytti** [comment]
I think you mean 'email' not 'from'. From will just set where the commit/update came from, it's not really used for anything except logs I think.

It's not immediately obvious what, if anything is wrong in your cURL. 

Did device actually have changed config? When you look at nodes, can you observe that node is not being fetched shortly after?

The syslog.rb/rest_client.rb are mostly just formal language documents, if anything. You can of course use it in your own code, like rest_client.rb is being used in syslog.rb, by requiring it with ```require_relative relattive_path/to/rest_client.rb```

However if you prefer python, I see no point using it. In python you'd do  something like this ```requests.requests("put", myurl, json=mydict)```

**Comment by oljustice** [comment]
The device does not have a changed config. Will the `node/next` only trigger a new commit/push if there is a diff? I was under the impression that it did this regardless, even if the config is the same.

**Comment by ytti** [comment]
It will cause the device to be fetched next, if there is no change, it will not store identical copy of config. If there is change, it will commit the change with the information provided.

I don't think it's even possible in git to commit without changing. What type of use-case you have, where you would prefer always to add commit without changing data?

**Comment by oljustice** [comment]
To be honest there is no use-case for a non-changing commit other than my testing to see if it actually works :). Ultimately I'd like these triggered updates as part of our ci/cd process, as well as supporting `git blame` functionality for accountability.

**Comment by ytti** [comment]
ACK, that is exactly the purpose for them. Introduce faux change and retest your cURL.

**Comment by oljustice** [comment]
I will try this tonight and update the issue. Thanks @ytti!

**Comment by oljustice** [comment]
This works. Closing this one out.
