### ISSUE TITLE
Bad config from ubiquiti after update from 0.25.0 to version 0.26.3

### ISSUE THREAD

**Issue by MTkatchouk** [ytti/oxidized#1766]
Hi. After update from 0.25.0 to version 0.26.3 my config contains only the following lines. Previously, everything worked fine.
```
# board.sysid=0xe012
# board.cpurevision=0x00000101
# board.name=NanoStation M2
# board.shortname=N2N
# board.subtype=
# board.netmodes=7
# board.hwaddr=DC9-----FC61
# board.reboot=50
# board.upgrade=150
# board.phycount=2
# board.phy.1.maxmtu=2024
# board.phy.2.maxmtu=2024
# radio.1.name=
# radio.1.shortname=
# radio.1.bus=pci
# radio.1.subsystemid=0xe012
# radio.1.subvendorid=0x0777
# radio.1.txpower.max=28
# radio.1.txpower.min=-4
# radio.1.txpower.offset=10
# radio.1.ieee_modes=10
# radio.1.antennas=1
# radio.1.def_antenna=4
# radio.1.antenna.1.id=4
# radio.1.antenna.1.name=Built in
# radio.1.antenna.1.gain=11
# radio.1.antenna.1.builtin=1
# radio.1.antenna.1.chains=2
# radio.1.antenna.1.chain.1.id=0
# radio.1.antenna.1.chain.1.name=Horizontal
# radio.1.antenna.1.chain.2.id=1
# radio.1.antenna.1.chain.2.name=Vertical
# radio.1.distance_limit_km=0
# radio.1.chanbw="5,8,10,20,30,40"
# feature.rssi.leds=4
# feature.ext_reset=0
# airos version: XM.v6.1.8
```

**Comment by laf** [comment]
What os model are you using for this device?

**Comment by MTkatchouk** [comment]
Original Docker latest image. I rollback to 0.25.0.

**Comment by MTkatchouk** [comment]
https://hub.docker.com/r/oxidized/oxidized

**Comment by laf** [comment]
@MTkatchouk I mean the model of the ubiquiti device

**Comment by MTkatchouk** [comment]
NanoStation M2, M5,

**Comment by laf** [comment]
So that's using airos, that OS hasn't been updated in oxidized in 2 years so it's not changed between those versions.

**Comment by MTkatchouk** [comment]
May be problem in ssh transport ? Can I debug it? I have one config and two versions docker images. New version not work correct. Old version work fine.

**Comment by ytti** [comment]
Can you put sanitised device Internet accessible from 91.198.120.1, I can take a look.

**Comment by anthonyp123** [comment]
I am facing the same issue except with a powerbeam. I can make one available publically if this is still needed..

The commands should be  
'cat /etc/board.info'
'cat /etc/version' do |cfg|
    comment "airos version: #{cfg}"
 cmd 'sort /tmp/system.cfg'


All the commands are in airos.rb, but the last one does not appear to run.
