### ISSUE TITLE
Configuration backup of Zhone devices

### ISSUE THREAD

**Issue by xciter327** [ytti/oxidized#1768]
I'm trying to set-up a configuration backup of a Zhone MXK-F108. I've added the following configuration to the oxidized config file:

  zhoneolt:
    username: oxidized
    password: xxxxxxx

I confirmed the login works, however no config backup is made. In the log oxidized is complaining:

raised Oxidized::ModelNotFound with message 'slms not found for node x.y.z.r

Operating system is correctly detected by LibreNMS as Zhone MXK and I'm not sure where the "slms" model is coming from.

Suggestions are welcome.

**Comment by ytti** [comment]
I've never used LibreNMS, but I punched 'librenms slms' to google, without opening any link, I can see that LibreNMS calls the model 'slms'.

So you need something like this:
```
model_map:
  slms: zhoneolt
```

**Comment by xciter327** [comment]
Wow, thanks for the quick answer. I can confirm that did it.

**Comment by laf** [comment]
We can override models in LibreNMS so I've added a PR to do this: https://github.com/librenms/librenms/pull/10068

Once it's merged you won't need to map the models in your oxidized config but doing so also won't harm anything.

**Comment by ytti** [comment]
We probably should rename it in Oxidized and create wrapper deprecation class. Do you @laf know what is the origin/source of 'slms' being the OS name? If it is correct/current, seems better than vendorModel and more in line with how we want to name them.

@wk thoughts?
