### ISSUE TITLE
Jobs Problem?

### ISSUE THREAD

**Issue by MrRJ45** [ytti/oxidized#177]
I'm seeing an issue at the moment where nodes have "never" against them, and they wont ever backup.

If I manually start the backup then it works with no problems. It looks like no threads are running as I dont see "jobs wanted" in the log.

Any ideas where to start debugging this? :(

**Comment by ytti** [comment]
Have they been attempted unsuccessfully? After retries failed nodes are moved back of the queue, and won't be tried until iteration starts again. 
What is your interval? Are they not attempted even after interval passes?

**Comment by MrRJ45** [comment]
They haven't been attempted at all, "last => nil" and they are successful when I manually pull the config.

Interval is 14400 - every 4 hours, assuming that is in seconds!?

It may have broke when I reinstalled the server, I cant see why though.

**Comment by ytti** [comment]
Yeah that is seconds. Strange. Can you recreate it easily, if so, can you give me access to the environment where the issues can be recreated?

**Comment by MrRJ45** [comment]
It wouldnt be that easy to set it up, but I can look if need to.

Running pry on jobs.rb I see this, is that normal?

```
From: /var/lib/gems/2.1.0/gems/oxidized-0.7.2/lib/oxidized/jobs.rb @ line 41 Oxidized::Jobs#work:

    36: def work
    37:   # if   a) we want less or same amount of threads as we now running
    38:   # and  b) we want less threads running than the total amount of nodes
    39:   # and  c) there is more than MAX_INTER_JOB_GAP since last one was started
    40:   # then we want one more thread (rationale is to fix hanging thread causing HOLB)
 => 41:   binding.pry
    42:   if @want <= size and @want < @nodes.size
    43:     @want +=1 if (Time.now.utc - @last) > MAX_INTER_JOB_GAP
    44:   end
    45: end

[1] pry(#<Oxidized::Jobs>)> print @want
1=> nil
[2] pry(#<Oxidized::Jobs>)> print @size
=> nil
```

**Comment by ytti** [comment]
​Now that does not seem normal. IT should always be fixnum. Something is
off.

I think if count of nodes is 0, it currently is broken. But might be
different issue.

I think I saw jobs crash under condition where I had 1 node in router.db
and it was referring to model which did not exist. I wish I had created an
issue, as I don't remember details anymore.
​

**Comment by MrRJ45** [comment]
That was a test I did with a CSV file, and two fake devices, but it did try those despite pry showing that.

I'm going to have a look through my DB to see if I can see anything wrong.

**Comment by MrRJ45** [comment]
Ah ok, this relates to the patch to store the stats in sqlite :(

**Comment by MrRJ45** [comment]
Actually, this is a very weird issue. It may not relate directly to the new store system.

It appears to have stopped processing jobs after doing a number, or a specific device. I'm going to look into this a bit more tomorrow.

**Comment by MrRJ45** [comment]
So, it appears now I have figured how to use pry it is actually looking for jobs, "print" isnt correct - you just give it the variable name!

I think I've fixed this in worker.rb, so I'm leaving it running overnight to make sure it works as expected :)

**Comment by MrRJ45** [comment]
Looks like this is fixed with my change. What I saw with Worker.work was that the while loop was iterating over the same node again and again, never breaking that loop. It didnt do that for all nodes, but I cant see anything wrong with that node.

To fix this, I've changed this:
```ruby
          break if nextnode.last.end + CFG.interval > Time.now.utc
```
To this:
```ruby
          if nextnode.last.end + CFG.interval > Time.now.utc
            @nodes.get
            break
          end
```

That fixes it, but is that the correct fix?

**Comment by ytti** [comment]
That shouldn't pause indefinitely, right?

Eventually nextnode.last.end + CFG.interval is smaller than Time.now.utc,
as Time.now.utc keeps progressing?



I guess there might be corner case of date changing in the fly. Imagine
date being 2050-01-01 when oxidized starts, then changed to real by NTP.
This would cause it to sleep very long time. This is why we really should
use monotonic clock, not wall time. But I doubt this is your issue.


On 8 September 2015 at 08:37, MrRJ45 <notifications@github.com> wrote:

> Looks like this is fixed with my change. What I saw with Worker.work was
> that the while loop was iterating over the same node again and again, never
> breaking that loop. It didnt do that for all nodes, but I cant see anything
> wrong with that node.
>
> To fix this, I've changed this:
>
>           break if nextnode.last.end + CFG.interval > Time.now.utc
>
> To this:
>
>           if nextnode.last.end + CFG.interval > Time.now.utc
>             @nodes.get
>             break
>           end
>
> That fixes it, but is that the correct fix?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ytti/oxidized/issues/177#issuecomment-138439378>.
>



-- 
  ++ytti

**Comment by MrRJ45** [comment]
As an example, if I do this with pry, I get the below. I've replaced username/password/group/ip/name as I wouldn't want to share those :)

The first loop of the "while @jobs.size < @jobs.want" gives me the same node, until I run "@nodes.get" and it then will give me the next node, but every iteration is then that node

```
Puma 2.13.4 starting...
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://0.0.0.0:8888

From: /var/lib/gems/2.1.0/gems/oxidized-0.7.2/lib/oxidized/worker.rb @ line 22 Oxidized::Worker#work:

    11: def work
    12:   ended = []
    13:   @jobs.delete_if { |job| ended << job if not job.alive? }
    14:   ended.each      { |job| process job }
    15:   @jobs.work
    16:   while @jobs.size < @jobs.want
    17:     Log.debug "Jobs #{@jobs.size}, Want: #{@jobs.want}"
    18:     # ask for next node in queue non destructive way
    19:     nextnode = @nodes.first
    20:     unless nextnode.last.nil?
    21:       require 'pry'
 => 22:       binding.pry
    23:       if nextnode.last.end + CFG.interval > Time.now.utc
    24:         #@nodes.get
    25:         break
    26:       end
    27:     end
    28:     # shift nodes and get the next node
    29:     node = @nodes.get
    30:     node.running? ? next : node.running = true
    31:     @jobs.push Job.new node
    32:   end
    33: end

[1] pry(#<Oxidized::Worker>)> nextnode
=> #<Oxidized::Node:0x0000000176f9e8
 @auth={:username=>"username", :password=>"password"},
 @group="group",
 @input=[Oxidized::Telnet],
 @ip="ip",
 @last=#<OpenStruct start=2015-09-08 09:50:39 UTC, end=2015-09-08 09:50:39 UTC, status=:success, time=0.875752809>,
 @model=#<IOS:0x0000000189ccf8 @node=#<Oxidized::Node:0x0000000176f9e8 ...>>,
 @name="name",
 @output=Oxidized::Git,
 @prompt=/^([\w.@()-]+[#>]\s?)$/,
 @retry=0,
 @stats=#<Oxidized::Node::Stats:0x0000000189c6e0 @stats={}>,
 @vars=nil>
[2] pry(#<Oxidized::Worker>)> quit

From: /var/lib/gems/2.1.0/gems/oxidized-0.7.2/lib/oxidized/worker.rb @ line 22 Oxidized::Worker#work:

    11: def work
    12:   ended = []
    13:   @jobs.delete_if { |job| ended << job if not job.alive? }
    14:   ended.each      { |job| process job }
    15:   @jobs.work
    16:   while @jobs.size < @jobs.want
    17:     Log.debug "Jobs #{@jobs.size}, Want: #{@jobs.want}"
    18:     # ask for next node in queue non destructive way
    19:     nextnode = @nodes.first
    20:     unless nextnode.last.nil?
    21:       require 'pry'
 => 22:       binding.pry
    23:       if nextnode.last.end + CFG.interval > Time.now.utc
    24:         #@nodes.get
    25:         break
    26:       end
    27:     end
    28:     # shift nodes and get the next node
    29:     node = @nodes.get
    30:     node.running? ? next : node.running = true
    31:     @jobs.push Job.new node
    32:   end
    33: end

[1] pry(#<Oxidized::Worker>)> nextnode
=> #<Oxidized::Node:0x0000000176f9e8
 @auth={:username=>"username", :password=>"password"},
 @group="group",
 @input=[Oxidized::Telnet],
 @ip="ip",
 @last=#<OpenStruct start=2015-09-08 09:50:39 UTC, end=2015-09-08 09:50:39 UTC, status=:success, time=0.875752809>,
 @model=#<IOS:0x0000000189ccf8 @node=#<Oxidized::Node:0x0000000176f9e8 ...>>,
 @name="name",
 @output=Oxidized::Git,
 @prompt=/^([\w.@()-]+[#>]\s?)$/,
 @retry=0,
 @stats=#<Oxidized::Node::Stats:0x0000000189c6e0 @stats={}>,
 @vars=nil>
[2] pry(#<Oxidized::Worker>)>
```

**Comment by ytti** [comment]
Add also Time.now.utc.

To me it just looks like last iteration ended in less than iteration ago,
i.e. we don't want to collect it now, as iteration time has not passed.
Time.now.utc should be larger than 'end=2015-09-08 09:50:39' for it to
proceed.

On 8 September 2015 at 15:37, MrRJ45 <notifications@github.com> wrote:

> As an example, if I do this with pry, I get the below. I've replaced
> username/password/group/ip/name as I wouldn't want to share those :)
>
> The first loop of the "while @jobs.size < @jobs.want" gives me the same
> node, until I run "@nodes.get" and it then will give me the next node, but
> every iteration is then that node
>
> Puma 2.13.4 starting...
> * Min threads: 0, max threads: 16
> * Environment: development
> * Listening on tcp://0.0.0.0:8888
>
> From: /var/lib/gems/2.1.0/gems/oxidized-0.7.2/lib/oxidized/worker.rb @ line 22 Oxidized::Worker#work:
>
>     11: def work
>     12:   ended = []
>     13:   @jobs.delete_if { |job| ended << job if not job.alive? }
>     14:   ended.each      { |job| process job }
>     15:   @jobs.work
>     16:   while @jobs.size < @jobs.want
>     17:     Log.debug "Jobs #{@jobs.size}, Want: #{@jobs.want}"
>     18:     # ask for next node in queue non destructive way
>     19:     nextnode = @nodes.first
>     20:     unless nextnode.last.nil?
>     21:       require 'pry'
>  => 22:       binding.pry
>     23:       if nextnode.last.end + CFG.interval > Time.now.utc
>     24:         #@nodes.get
>     25:         break
>     26:       end
>     27:     end
>     28:     # shift nodes and get the next node
>     29:     node = @nodes.get
>     30:     node.running? ? next : node.running = true
>     31:     @jobs.push Job.new node
>     32:   end
>     33: end
>
> [1] pry(#<Oxidized::Worker>)> nextnode
> => #<Oxidized::Node:0x0000000176f9e8
>  @auth={:username=>"username", :password=>"password"},
>  @group="group",
>  @input=[Oxidized::Telnet],
>  @ip="ip",
>  @last=#<OpenStruct start=2015-09-08 09:50:39 UTC, end=2015-09-08 09:50:39 UTC, status=:success, time=0.875752809>,
>  @model=#<IOS:0x0000000189ccf8 @node=#<Oxidized::Node:0x0000000176f9e8 ...>>,
>  @name="name",
>  @output=Oxidized::Git,
>  @prompt=/^([\w.@()-]+[#>]\s?)$/,
>  @retry=0,
>  @stats=#<Oxidized::Node::Stats:0x0000000189c6e0 @stats={}>,
>  @vars=nil>
> [2] pry(#<Oxidized::Worker>)> quit
>
> From: /var/lib/gems/2.1.0/gems/oxidized-0.7.2/lib/oxidized/worker.rb @ line 22 Oxidized::Worker#work:
>
>     11: def work
>     12:   ended = []
>     13:   @jobs.delete_if { |job| ended << job if not job.alive? }
>     14:   ended.each      { |job| process job }
>     15:   @jobs.work
>     16:   while @jobs.size < @jobs.want
>     17:     Log.debug "Jobs #{@jobs.size}, Want: #{@jobs.want}"
>     18:     # ask for next node in queue non destructive way
>     19:     nextnode = @nodes.first
>     20:     unless nextnode.last.nil?
>     21:       require 'pry'
>  => 22:       binding.pry
>     23:       if nextnode.last.end + CFG.interval > Time.now.utc
>     24:         #@nodes.get
>     25:         break
>     26:       end
>     27:     end
>     28:     # shift nodes and get the next node
>     29:     node = @nodes.get
>     30:     node.running? ? next : node.running = true
>     31:     @jobs.push Job.new node
>     32:   end
>     33: end
>
> [1] pry(#<Oxidized::Worker>)> nextnode
> => #<Oxidized::Node:0x0000000176f9e8
>  @auth={:username=>"username", :password=>"password"},
>  @group="group",
>  @input=[Oxidized::Telnet],
>  @ip="ip",
>  @last=#<OpenStruct start=2015-09-08 09:50:39 UTC, end=2015-09-08 09:50:39 UTC, status=:success, time=0.875752809>,
>  @model=#<IOS:0x0000000189ccf8 @node=#<Oxidized::Node:0x0000000176f9e8 ...>>,
>  @name="name",
>  @output=Oxidized::Git,
>  @prompt=/^([\w.@()-]+[#>]\s?)$/,
>  @retry=0,
>  @stats=#<Oxidized::Node::Stats:0x0000000189c6e0 @stats={}>,
>  @vars=nil>
> [2] pry(#<Oxidized::Worker>)>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ytti/oxidized/issues/177#issuecomment-138547286>.
>



-- 
  ++ytti

**Comment by MrRJ45** [comment]
If it doesn't want to run the job for that node, it should skip it and look for another, correct?

**Comment by MrRJ45** [comment]
If I remove the Sqlite stats store then all works fine with the original code. Though I cant see the issue.

```
[1] pry(#<Oxidized::Worker>)> nextnode.last.end
=> 2015-09-08 17:55:07 UTC
[2] pry(#<Oxidized::Worker>)> CFG.interval
=> 14400
[3] pry(#<Oxidized::Worker>)> nextnode.last.end + CFG.interval
=> 2015-09-08 21:55:07 UTC
[4] pry(#<Oxidized::Worker>)> nextnode.last.end + CFG.interval > Time.now.utc
=> true
[5] pry(#<Oxidized::Worker>)>
```

The first job it wants to run is constant, it will want to run only that and not look for another. I did notice some strange behavior in previous versions, so I wonder if this is it.

Adding nodes.get to the check pushes it to the end of the nodes list from what I can see, so the worker will actively look for something to work on all of the time.

Do we think thats the right fix if you will merge the sqlite3 store? Or will you prefer it uses sequel so we dont have two very similar dependencies?

**Comment by ytti** [comment]
The node in the head of the queue should be next to need fetching, everything below it, should have been fetched more recently.
So we're only looking if the node in the head of the queue needs to be fetched, if it does not need to be  fetched, we essentially go back to main loop sleep, and re-evaluate until sufficient time has passed that it needs to be fetched.

**Comment by ytti** [comment]
I think I'd prefer to use sequel. But for now, we probably should keep it as feature branch. I'd really wish I'd have time/energy/motivation to think bit more about this store issue, and generally refactoring the infrastructure.

**Comment by MrRJ45** [comment]
I've figured the issue - "next" was resetting node.last.end to be nil to force it to be the next in the queue

I've made some changes on my side to add node.force where that is boolean, to bring it to the next in the queue and run even if it isnt due.

If @FlorianDoublet doesnt mind I am happy learning how Sequel works now I've fixed this, so I can base some code on the work already done so you would be happy merging it :)

I'm sure everybody would love the storing of the stats

**Comment by FlorianDoublet** [comment]
@MrRJ45 thanks for your review and of course you can,  moreover I can't work on it anymore for now,  so there is no problem for me,  and I'll be happy if my work can be useful :)

**Comment by MrRJ45** [comment]
I have rewritten the sql store bits, and a few other changes based on Florian's work but using Sequel.

I'm testing it at the moment, and then I'll add in support for the previous method (ie. not-persistent) for people who are using a CSV source for example.

**Comment by MrRJ45** [comment]
Closing this as its not an Issue directly relating to Oxidized
