### ISSUE TITLE
Oxidized failing authentication for Cisco IOS (Cisco 2960)

### ISSUE THREAD

**Issue by netops2devops** [ytti/oxidized#1771]
Greetings,

I'm running oxidized on FreeBSD 11.2 and I've got it working successfully with JunOS, Cisco ASA and Arista EOS but I run into the following error (copying from the debug file) when trying to setup oxidized with Cisco IOS running on one of our 2960's. 

```
Inappropriate ioctl for device [Errno::ENOTTY]
--------------------------------------------------
/usr/local/lib/ruby/gems/2.4/gems/net-ssh-4.2.0/lib/net/ssh/prompt.rb:44:in `noecho'
/usr/local/lib/ruby/gems/2.4/gems/net-ssh-4.2.0/lib/net/ssh/prompt.rb:44:in `ask'
/usr/local/lib/ruby/gems/2.4/gems/net-ssh-4.2.0/lib/net/ssh/authentication/methods/keyboard_interactive.rb:53:in `block (2 levels) in authenticate'
/usr/local/lib/ruby/gems/2.4/gems/net-ssh-4.2.0/lib/net/ssh/authentication/methods/keyboard_interactive.rb:50:in `times'
/usr/local/lib/ruby/gems/2.4/gems/net-ssh-4.2.0/lib/net/ssh/authentication/methods/keyboard_interactive.rb:50:in `block in authenticate'
/usr/local/lib/ruby/gems/2.4/gems/net-ssh-4.2.0/lib/net/ssh/authentication/methods/keyboard_interactive.rb:20:in `loop'
/usr/local/lib/ruby/gems/2.4/gems/net-ssh-4.2.0/lib/net/ssh/authentication/methods/keyboard_interactive.rb:20:in `authenticate'
/usr/local/lib/ruby/gems/2.4/gems/net-ssh-4.2.0/lib/net/ssh/authentication/session.rb:80:in `block in authenticate'
/usr/local/lib/ruby/gems/2.4/gems/net-ssh-4.2.0/lib/net/ssh/authentication/session.rb:66:in `each'
/usr/local/lib/ruby/gems/2.4/gems/net-ssh-4.2.0/lib/net/ssh/authentication/session.rb:66:in `authenticate'
/usr/local/lib/ruby/gems/2.4/gems/net-ssh-4.2.0/lib/net/ssh.rb:241:in `start'
/usr/local/lib/ruby/gems/2.4/gems/oxidized-0.21.0/lib/oxidized/input/ssh.rb:49:in `connect'
/usr/local/lib/ruby/gems/2.4/gems/oxidized-0.21.0/lib/oxidized/node.rb:65:in `run_input'
/usr/local/lib/ruby/gems/2.4/gems/oxidized-0.21.0/lib/oxidized/node.rb:42:in `block in run'
/usr/local/lib/ruby/gems/2.4/gems/oxidized-0.21.0/lib/oxidized/node.rb:37:in `each'
/usr/local/lib/ruby/gems/2.4/gems/oxidized-0.21.0/lib/oxidized/node.rb:37:in `run'
/usr/local/lib/ruby/gems/2.4/gems/oxidized-0.21.0/lib/oxidized/job.rb:9:in `block in initialize'
```

My router.db contains the FQDN of the host which is reachable from the server running oxidized and I can SSH using the same credentials I'm specifying in the oxidized config file but for some reason oxidized authentications are failing on the switch which is why oxidized is unable to discover the device. 

I am also seeing the below error message on the switch whenever the oxidized tries to authenticate with the switch. 
-----

```
Apr  9 02:10:30.479: %SSH-4-SSH2_UNEXPECTED_MSG: Unexpected message type has arrived. Terminating the connection
```

My oxidized config file looks something like this : 

```
---
use_syslog: true
log: ~/logs
debug: true
threads: 30
timeout: 120
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 127.0.0.1:8888
next_adds_job: false
pid: "/services/oxidized/.config/oxidized/pid"
groups:
  junos:
      username: <stripped>
      password: <stripped>
      vars:
        auth_methods: ["publickey", "password"]
        ssh_keys: <stripped>
  ios:
      username: <stripped>
      password: <stripped>
      vars:
	auth_methods: ["publickey", "password"]
        ssh_keys: <stripped>
        enable: <stripped>

environment:
  CONFIG_RELOAD_INTERVAL: 600
input:
  default: ssh
  debug: true
  ssh:
    secure: true
output:
  default: git
  git:
    user: oxidized
    email: 
    repo: 
model_map:
  cisco: ios
  juniper: junos
  arista: eos
```

Any pointers or help on resolution of this issue would be highly appreciated. 

Thanks!!

**Comment by laf** [comment]
Try removing the `auth_methods` from the `ios` group.

Have you tested you can login to this device from your oxidized box using the same user that oxidized runs as?

**Comment by netops2devops** [comment]
I've already tried removing auth_methods from the config for ios and it still remains the same. Yes, I've confirmed SSH login to this Cisco device from my Oxidized box using the same username that I specified in the config file.

**Comment by ytti** [comment]
It may be worthwhile to force specific ssh settings on IOS end, one at at a time, like kex, cipher and others. It may be IOS issue which you can workaround by ensuring that the part with the issue is not being negotiated.

**Comment by netops2devops** [comment]
That may be worth a shot. So far seems like an IOS bug of some sort. I've got it working with an ASA as well as EoS though which tells me oxidized is doing fine what it's supposed to. Also as a matter of fact those IOS switches are quite old and running like 15 version of code or something, so upgrading the code might be next step as well. I'll go ahead and close this ticket for now. Thanks a lot for your input.
