### ISSUE TITLE
githubrepo remote repo does not mirror local git repo

### ISSUE THREAD

**Issue by oljustice** [ytti/oxidized#1772]
I've noticed that while the remote repo updated by the githubrepo hook appears to be updated periodically, it is missing both certain devices and commits that are present in the local repo. These missing devices/commits include but are not limited to the custom message commits created using the `/node/next` API call.

I am curious if these two repos are supposed to be mirrors of one another. Does the `githubrepo` hook essentially perform a `git push` every time a config is updated? If so, this doesn't appear to be working as there are devices I've since added to my `router.db` and restarted the service and while they *do* show in the GUI and in the git repo, they are *not* present in the remote repo. Should I blow away the remote repo every time I restart the oxidized service or (in my case) essentially reboot the server? Per my other issue (#1763), I've been playing around with custom message and while they are showing up in my local repo via `git log`, I've yet to see these message reflected in the remote repo.

Tangentially related - is there a way to configure oxidized to use a worktree rather than a naked repo?

**Comment by ytti** [comment]
Well this seems confusing to me, with or without the custom messages we create the commit identically. 
I have only superficial understanding of git, but I don't understand how this could possibly happen

Commit C has custom messages

Local Commits: A=>B=>C=>D
Remote Commits: A=>B=>D

I don't think remote would accept D on B without C. I do not understand how this could possibly happen.

However, it is possible to configure Oxidized to use multiple repos, either via using groups or using different config contexts. And then it is plausible that only repo1 is being updated, and repo2, repo3 are just local.

We currently update only bare repo, if you want to have local checkout, you are welcome to checkout the bare repo anywhere where you want. I do not think the backing repo should be non-bare, to discourage people using it as anything else but data backend.

So I think more research is needed what actually is going on in your setup, are we truly missing commits, in the middle of commit history?

**Comment by ytti** [comment]
Is it possible that your pushes to upstream are failing entirely, because fast-forward is not possible and merge would be needed?

If we can't do push, we can't do push (like for example maybe you changed upstream through other sources). Then you are in situation which you need to resolve manually.

**Comment by oljustice** [comment]
i just checked the remote repo and noticed that the devices that weren't shown are now there. It shows their addition (and only a single commit) happening 'a day ago' despite the fact that I've added those routers and switches at least 3 days ago (and they were immediately reflected on the local repo). Could this be an issue around the event not functioning properly? I'm currently using the `post_store` event. Does this fire when a single node's configuration is updated or only after the entire nodes list is complete? I realize it's tough to help with no config so I've pasted a sanitized version below:

[unrelated: Is there a way to trigger a pull of the entire nodes list in a single call like `node/fetch` perhaps?]

---
username: config-backup
publickey: /root/.ssh/network-devices/id_rsa.pub
privatekey: /root/.ssh/network-devices/id_rsa
resolve_dns: true
interval: 3600
use_syslog: false
debug: true
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 0.0.0.0:8888/oxidized
next_adds_job: true
vars:
  auth_methods: [ "publickey" ]
  ssh_proxy: proxyserver@proxyserver.net
  ssh_keys: "/root/.ssh/network-devices/id_rsa"
groups: {}
models: {}
pid: "/root/.config/oxidized/pid"
crash:
  directory: "/root/.config/oxidized/crashes"
  hostnames: true
stats:
  history_size: 10
input:
  default: ssh
  debug: true
  ssh:
    secure: false
  ftp:
    passive: true
  utf8_encoded: true
output:
  default: git
  git:
    user: Oxidized
    email: oljustice@mycompany.com
    repo: "/root/.config/oxidized/configs.git"
hooks:
  push_to_remote:
    type: githubrepo
    events: [post_store]
    remote_repo: git@github.com:mycompany/oxidized-configs.git
    publickey: /root/.ssh/network-devices/id_rsa.pub
    privatekey: /root/.ssh/network-devices/id_rsa
source:
  default: csv
  csv:
    file: "/root/.config/oxidized/router.db"
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
      ip: 2
    gpg: false
  http:
    url: http://127.0.0.1/oxidized
    scheme: https
    secure: False
    delimiter: !ruby/regexp /:/
    map:
      name: hostname
      model: os
    headers:
      X-Auth-Token: 'xxxxxxxxxxxxxxxxxxxx'
model_map:
  juniper: junos
  cisco: ios
  arista: eos

**Comment by ytti** [comment]
```post_store``` happens after configuration is stored.

Could it be possible that hooks did fire but push didn't succeed for one reason or another? Logs should help.

**Comment by oljustice** [comment]
I figured it out. The user that oxidized was logging in with did not have proper permissions to the configuration level that was being changed (it's a Juniper device), so from the git perspective nothing was changing. It was just "ACCESS-DENIED".

Thanks again @ytti!
