### ISSUE TITLE
(Comware) "unable to detect prompt" issue

### ISSUE THREAD

**Issue by xiaowei-gao** [ytti/oxidized#1773]
I have a problem now, one of the H3C models does not work.

### Switch10F-01-acess
dis version 
H3C Comware Platform Software
Comware Software, Version 3.10, Release 2211P09
Copyright (c) 2004-2012 Hangzhou H3C Technologies Co., Ltd. All rights reserved.
H3C S3100-52TP-UM uptime is 24 weeks, 4 days, 6 hours, 5 minutes
H3C S3100-52TP-UM with 1 Processor 
64M     bytes SDRAM
8M      bytes Flash Memory
Config Register points to FLASH

Hardware Version is REV.B
Bootrom Version is 612
[Subslot 0] 48FE         Hardware Version is REV.B
[Subslot 1]  2GE         Hardware Version is REV.B
[Subslot 2]  2SFP        Hardware Version is REV.B

oxidized Config#
---
username: username
password: password
model: junos
resolve_dns: true
interval: 43200
use_syslog: false
debug: false
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 127.0.0.1:8888
next_adds_job: false
vars: {}
groups: {}
models: {}

### error
W, [2019-04-03T02:57:59.084387 #26978]  WARN -- : 10.212.130.98 raised IOError with msg "closed stream"
W, [2019-04-03T02:58:19.398054 #26978]  WARN -- : 10.212.130.98 raised Oxidized::PromptUndetect with msg "unable to detect prompt: (?-mix:^\0*(<[\w.-]+>).?$)"
W, [2019-04-03T02:58:19.754582 #26978]  WARN -- : /10.212.130.98 status no_connection, retry attempt 1
W, [2019-04-03T02:58:23.681352 #26978]  WARN -- : 10.212.130.98 raised IOError with msg "closed stream"
W, [2019-04-03T02:58:43.815975 #26978]  WARN -- : 10.212.130.98 raised Oxidized::PromptUndetect with msg "unable to detect prompt: (?-mix:^\0*(<[\w.-]+>).?$)"
W, [2019-04-03T02:58:44.760562 #26978]  WARN -- : /10.212.130.98 status no_connection, retry attempt 2
W, [2019-04-03T02:58:48.710853 #26978]  WARN -- : 10.212.130.98 raised IOError with msg "closed stream"
W, [2019-04-03T02:59:08.848114 #26978]  WARN -- : 10.212.130.98 raised Oxidized::PromptUndetect with msg "unable to detect prompt: (?-mix:^\0*(<[\w.-]+>).?$)"
W, [2019-04-03T02:59:09.767442 #26978]  WARN -- : /10.212.130.98 status no_connection, retry attempt 3
W, [2019-04-03T02:59:13.780131 #26978]  WARN -- : 10.212.130.98 raised IOError with msg "closed stream"
W, [2019-04-03T02:59:33.915378 #26978]  WARN -- : 10.212.130.98 raised Oxidized::PromptUndetect with msg "unable to detect prompt: (?-mix:^\0*(<[\w.-]+>).?$)"

**Comment by xiaowei-gao** [comment]
### Log display on the switch
%Apr 10 08:39:13:837 2019 Switch8F-1-acess SSH/5/fsm_move:- 1 -FSM MOVE FROM SSH_Main_Connect TO SSH_Main_VersionMatch
%Apr 10 08:39:13:837 2019 Switch8F-1-acess SSH/5/fsm_move:- 1 -FSM MOVE FROM SSH_Main_VersionMatch TO SSH_Main_SSHProcess
%Apr 10 08:39:13:855 2019 Switch8F-1-acess SSH/5/fsm_move:- 1 -FSM MOVE FROM SSH_Sub1_KEX_Init TO SSH_Sub1_KEX_GEX_Group
%Apr 10 08:39:14:115 2019 Switch8F-1-acess SSH/5/fsm_move:- 1 -FSM MOVE FROM SSH_Sub1_KEX_GEX_Group TO SSH_Sub1_KEX_GEX_Reply
%Apr 10 08:39:14:792 2019 Switch8F-1-acess SSH/5/fsm_move:- 1 -FSM MOVE FROM SSH_Sub1_KEX_GEX_Reply TO SSH_Sub1_KEX_NewKey
%Apr 10 08:39:14:792 2019 Switch8F-1-acess SSH/5/fsm_move:- 1 -FSM MOVE FROM SSH_Sub1_KEX_NewKey TO SSH_Sub1_Authentication
%Apr 10 08:39:14:799 2019 Switch8F-1-acess SSH/5/fsm_move:- 1 -FSM MOVE FROM SSH_Sub2_Service_Acc TO SSH_Sub2_Auth_Init
%Apr 10 08:39:14:827 2019 Switch8F-1-acess SSH/5/fsm_move:- 1 -FSM MOVE FROM SSH_Sub2_Auth_Init TO SSH_Sub2_Auth_Password
%Apr 10 08:39:14:937 2019 Switch8F-1-acess VTY/5/VTY_LOG:- 1 - SSH user servyou succeeded to login from 10.212.132.148 on VTY0.
%Apr 10 08:39:14:937 2019 Switch8F-1-acess SSH/5/fsm_move:- 1 -FSM MOVE FROM SSH_Sub1_Authentication TO SSH_Sub1_Channel
%Apr 10 08:39:15:143 2019 Switch8F-1-acess SSH/5/fsm_move:- 1 -FSM MOVE FROM SSH_Sub1_Channel TO SSH_Sub1_Session
%Apr 10 08:39:15:655 2019 Switch8F-1-acess SHELL/5/LOGIN:- 1 - servyou(10.212.132.148) in unit1 login
%Apr 10 08:39:16:896 2019 Switch8F-1-acess SHELL/5/CMD:- 1 -task:vt0 ip:10.212.132.148 user:servyou command:undo terminal monitor
%Apr 10 08:39:17:254 2019 Switch8F-1-acess SSH/5/fsm_move:- 1 -FSM MOVE FROM SSH_Main_SSHProcess TO SSH_Main_Dissconnect
%Apr 10 08:39:17:358 2019 Switch8F-1-acess SSH/5/err_disconnect:- 1 -The connection is closed by SSH Server
Current FSM is : SSH_Main_Disconnect
%Apr 10 08:39:17:358 2019 Switch8F-1-acess SSH/5/fsm_move:- 1 -FSM MOVE FROM SSH_Main_Disconnect TO SSH_Main_Disconnect
%Apr 10 08:39:17:973 2019 Switch8F-1-acess SHELL/5/LOGOUT:- 1 - servyou(10.212.132.148) in unit1 logout

**Comment by tkspuk** [comment]
@xiaowei-gao I have a same issue.

**Comment by eduardocalfaia** [comment]
Hi Guys,
I have the same issue with HP1910.

Thanks
