### ISSUE TITLE
Gitlab Integration

### ISSUE THREAD

**Issue by jab375** [ytti/oxidized#1777]
I'm having troubles integrating with gitlab server on the same machine as oxidized. The OS im using is ubuntu 18.04.  I can auth to the gitlab via SSH as shown below. however Rugged keeps giving errors and I'm not sure what causing them.

jbowers@ubuntu:~$ ssh -T git@gitlab.example.com
Welcome to GitLab, @jbowers!

jbowers@ubuntu:~$ oxidized 
I, [2019-04-16T12:22:29.774406 #24829]  INFO -- : Oxidized starting, running as pid 24829
I, [2019-04-16T12:22:29.776730 #24829]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
I, [2019-04-16T12:22:29.842569 #24829]  INFO -- : lib/oxidized/nodes.rb: Loaded 1 nodes
Puma starting in single mode...
* Version 3.11.4 (ruby 2.5.1-p57), codename: Love Song
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://192.168.115.131:8000
Use Ctrl-C to stop
I, [2019-04-16T12:22:43.071979 #24829]  INFO -- : Configuration updated for /ciscoswitch
I, [2019-04-16T12:22:43.072719 #24829]  INFO -- : GithubRepo: Pushing local repository(/home/jbowers/.config/oxidized/configs/default.git/)...
I, [2019-04-16T12:22:43.076362 #24829]  INFO -- : GithubRepo: to remote: git@gitlab.example.com:jbowers/network-backups.git
E, [2019-04-16T12:24:43.086675 #24829] ERROR -- : Hook push_to_remote (#<GithubRepo:0x000055632c901458>) failed (#<Rugged::SshError: Failed to authenticate SSH session: Unable to send userauth-publickey request>) for event :post_store

My hook config.         gitlab.example.com is in my OS host file as 127.0.0.1
push_to_remote:
    type: githubrepo
    events: [post_store]
    remote_repo: git@gitlab.example.com:jbowers/network-backups.git
    publickey: /home/jbowers/.ssh/id_rsa.pub
    privatekey: /home/jbowers/.ssh/id_rsa

**Comment by wk** [comment]
It is unclear from your demonstration of an ssh-based login if the same key is in fact being used, and if it originates from the file or from an ssh-agent.

Re-running the ssh based login with `-v` and an explicit key by specifying `-i .ssh/id_rsa` or similar might help in troubleshooting this further; finally, there does not appear to be an indication of the version of oxidized you're using, and the version of the various gems installed - this additional detail might also be helpful.

**Comment by jab375** [comment]
I solved the issue. I re installed OS /Oxidized and gitlab and it started to work. It might of been permission from how I originally installed. I followed codingpackets.com install guide.
