### ISSUE TITLE
Oxidized command keep running after completion

### ISSUE THREAD

**Issue by r-bhikhie** [ytti/oxidized#1778]
I've setup Oxidized on Debian 9 Stretch by following the "Debian and Ubuntu" install steps.
I managed to set up a node list with two `ios` devices and one `fortios` device.

Some envinroment info:
```
ruby 2.3.3p222 (2016-11-21) [x86_64-linux-gnu]

*** LOCAL GEMS ***

asetus (0.3.0)
bcrypt_pbkdf (1.0.1)
bigdecimal (1.2.8)
did_you_mean (1.0.0)
ed25519 (1.2.4)
io-console (0.4.5)
json (1.8.3)
minitest (5.9.0)
net-ssh (5.2.0)
net-telnet (0.1.1)
oxidized (0.26.3)
power_assert (0.2.7)
psych (2.1.0)
rake (10.5.0)
rdoc (4.2.1)
rugged (0.28.1)
slop (3.6.0)
test-unit (3.1.7)
```

Running `oxidized` from the CLI works fine, it grabs all configs and stores them however, the prompt never returns.
Running `oxidized` with `debug: true` in the config shows this after everything is done:

```
D, [2019-04-17T06:21:21.985093 #14425] DEBUG -- : lib/oxidized/worker.rb: Running :nodes_done hook
D, [2019-04-17T06:21:22.985330 #14425] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 0 of 3
D, [2019-04-17T06:21:23.985659 #14425] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 0 of 3
D, [2019-04-17T06:21:24.985981 #14425] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 0 of 3
D, [2019-04-17T06:21:25.986307 #14425] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 0 of 3
D, [2019-04-17T06:21:26.986643 #14425] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 0 of 3
D, [2019-04-17T06:21:27.986958 #14425] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 0 of 3
D, [2019-04-17T06:21:28.987253 #14425] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 0 of 3
D, [2019-04-17T06:21:29.987574 #14425] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 0 of 3
D, [2019-04-17T06:21:30.987936 #14425] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 0 of 3
D, [2019-04-17T06:21:31.988253 #14425] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 0 of 3

```

These lines keep repeating ad inifitum. I was expecting the command to exit and return to the prompt.
How do I fix this?
What other info should I include to help the troubleshoot?

**Comment by buraglio** [comment]
`oxidized --daemonize ` runs it in the background, or you can add it as a debian service to start at boot.

**Comment by r-bhikhie** [comment]
Oh, is this expected behavior? I assumed the `oxidized` would run a single job. Is there any other way of running a single job in such a way?

**Comment by ytti** [comment]
At this time there is no way to do a single job, it wouldn't be complicated to add. Basically we'd need to ensure each device gets collected once and then exit.

**Comment by r-bhikhie** [comment]
Can this be marked as a non hi-prio feature request then?
Knowing that it's intended behavior is good enough for me.

**Comment by dolphy01** [comment]
Being able to run this in a batch-mode style like this would be useful for our CI/CD setup. I could run this as a Jenkins job to grab configs and integrate success/failure criteria quite easily into our various pipelines. But that only works if I can run it and know when it's "done".

**Comment by ytti** [comment]
You could have `nodes_done` hook, which asks for status report then kills oxidized.

**Comment by dolphy01** [comment]
> You could have `nodes_done` hook, which asks for status report then kills oxidized.

This looks pretty simple to add to config, and would definitely accomplish the task. Thanks!

**Comment by dolphy01** [comment]
For what it's worth, this works exactly as I needed. I added the following to the config file:
```
hooks:
  kill_after_collection:
    type: exec
    events: [nodes_done]
    cmd: 'cat /home/oxidize/logs/pid | xargs kill'
```

Someone better at YAML than me could probably make it less brittle by defining the PID file by referencing its actual definition in the config file. 

As a side-node, this with file output works very well in conjunction with docker-compose, Jenkins, and GitHub to clone a repo, kick off this oxidize container as a one-time collect to mounted volumes, and then push any changed results back up.

**Comment by ytti** [comment]
If I were you, I'd first store the fetch status JSON, to understand failures and fetch times and such. Failures you need to know, fetch times are good to know to understand if something pathological is at foot, why are fetch times radically up or down probably deserves investigation.
