### ISSUE TITLE
Another event for Hooks, worker_done

### ISSUE THREAD

**Issue by jthunt** [ytti/oxidized#178]
Can we add another event for hooks that will trigger when the worker is done with its current job cycle?  I hope this makes sense and I am using the correct terms.

Example: Every time oxidized goes out and pulls configs for all the devices in router.db, this event would trigger at the end of that process.

**Comment by ytti** [comment]
@aakso actually suggested this while developing the feature. But what exactly is job cycle? How do we define full cycle has occurred?

Imagine the list of nodes as circle, then we have arrow pointing to one point, and the circle is rotating, when ever arrow hits node, we fetch that node.
So it should be easy, when full circle is done, we launch event.

However, the place of nodes in the circle isn't guaranteed to be static, through API you can move node to the head of the queue (if you want to get new config for $this node, right now, you move it to head of the queue). 
So this complicated our picture. 

Perhaps ghetto solution
cycle += 1
if cycle % @nodes.count == 0
  # trigger event
  cycle = 0
end


Won't guarantee, but in steady state reasonable approximation?

**Comment by etern4ever** [comment]
I understand how this could be an issue with how you are handling work (circle instead of a single batch job like rancid).   Maybe I just need a new approach to what I am trying to do then.

Is there a way to reset oxidized?  I am getting errors now when going to the versioning on oxidized-web.  I think its because I have been playing with output methods (trying to do both file and git) and deleting, etc.

**Comment by ytti** [comment]
If you're restarted oxidized, no state today should remain. But runtime there really isn't way to reset, there is only way to reload nodes.

**Comment by etern4ever** [comment]
Oh..  I found the issue..  I switched to a single git repo and that caused my error.  Switching back to the default group based git repos resolved the diff issue I was having.

**Comment by etern4ever** [comment]
FYI..   I got what I wanted to work without a worker_done event.    I just needed to think outside the box a little and learn more about git diffs.

But for others that might need it..  triggering when entering steady state should make sense and be good enough.

**Comment by aakso** [comment]
I will look into this but at the moment I'm kinda busy.

**Comment by ytti** [comment]
Any update?

**Comment by ytti** [comment]
@aakso pong

**Comment by aakso** [comment]
sorry, I forgot this and currently I'm very overloaded with work. If anyone else can submit a pull request it would be great.

**Comment by danilopopeye** [comment]
I'll see if I can get some time to hack something ugly for the moment, maybe next week.

**Comment by danilopopeye** [comment]
sorry guys, rough month here. 😞  I think only about the last week of November I can get some time free. If someone else want to tackle this, feel free 😉

**Comment by danilopopeye** [comment]
@jthunt can you have a look in the PR #971 and see if it solves your problem?
