### ISSUE TITLE
Gitlab [Nodes Done] event Support

### ISSUE THREAD

**Issue by jab375** [ytti/oxidized#1780]
Is the following hook supported? When I changed the event from post_store to nodes_done an error occurs. I want Oxidize to push the repository to gitlab after 100 devices are backed up. This should help reduce gitlab change emails because I get them per device right now.

hooks:
  push_to_remote:
    type: githubrepo
    events: [nodes_done]
    remote_repo: "git@gitlab.example.com:oxidized/configs.git"
    publickey: /opt/oxidized/.ssh/id_rsa.pub
    privatekey: /opt/oxidized/.ssh/id_rsa

Here the error I get with the above hook

Hook push_to_remote (#<GithubRepo:0x000055bf83e89c50>) failed (#<NoMethodErr

**Comment by wk** [comment]
This is not currently supported; you can find some more context [here](https://github.com/ytti/oxidized/issues/1631#issuecomment-439726659).
