### ISSUE TITLE
Add firepower support

### ISSUE THREAD

**Issue by deepminimal** [ytti/oxidized#1781]
Hi!

I found closed pull request #950 with firelinuxos.rb. Whats wrong with firelinuxos.rb? Can you add support this model?

**Comment by wk** [comment]
Possibly nothing, but the PR itself has all kinds of mixed up chunks and changes to other models which don't belong in it - and the contributor appears to never have revised the contribution to include only a correct and functioning model and related documentation.

You're welcome to start from the `firelinuxos` model from the PR you've referenced and if it works for you, re-submit it as a new PR including only the model, a changelog entry, a supported OS types entry, and any necessary documentation.

**Comment by wk** [comment]
The FirePOWER model from #950 has been merged into master.
