### ISSUE TITLE
Cisco SF350 (ciscosmb): remove "Unit Temperature" and "Fans Status" from the output

### ISSUE THREAD

**Issue by igloo777** [ytti/oxidized#1785]
Hi!
Output of _show system_ in software 'Version: 2.4.5.71' return the next data, that can change quite often, doesn't relate to config and shows the useless diff between the number of config backups:

```
Unit                Fans Status             
----   -------------------------------------
 1           Fans status is N/A          

Unit Temperature (Celsius)   Status   
---- --------------------- ---------- 
 1            41               OK    
```

I think it should be removed from the output of ciscosmb.rb module.

**Comment by wk** [comment]
Thanks for the report! Should be resolved by #1799.
