### ISSUE TITLE
JunOS SSH Command Not Found

### ISSUE THREAD

**Issue by Masterbill125** [ytti/oxidized#179]
I don't know if this is an issue. I am able to run oxidized on all my cisco gear. However when I run on our Juniper switch it doesn't make it to the CLI page. I can see oxidized login to the switch and in the logs confirms (Configuration updated) but the file only contains.  

show: Command not found.
display: Command not found.# show: Command not found.# show: Command not found.

When I SSH into the switch i have to enter cli before I am able to issue any show commands.

**Comment by n3gster** [comment]
Are you logging in as root?

On Friday, 11 September 2015, Masterbill125 <notifications@github.com>
wrote:

> I don't know if this is an issue. I am able to run oxidized on all my
> cisco gear. However when I run on our Juniper switch it doesn't make it to
> the CLI page. I can see oxidized login to the switch and in the logs
> confirms (Configuration updated) but the file only contains.
>
> show: Command not found.
> display: Command not found.# show: Command not found.# show: Command not
> found.
>
> When I SSH into the switch i have to enter cli before I am able to issue
> any show commands.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ytti/oxidized/issues/179>.
>


-- 
Sent from Gmail Mobile...

**Comment by ytti** [comment]
@n3gster got it, clearly you're logging in as root, which you really shouldn't ever do, unless recovering box or something terrible.
Please create user account, the user account by default will have JunOS CLI as its shell, so you won't reach the FreeBSD shell.

You could alternatively change the root shell to proper JunOS CLI, but it would be broken on every software upgrade.

3rd solution is to have your own junos.rb in ~/.config/oxidized/model where you add "post_login 'cli'" before the pager stuff. But I wouldn't recommend this, just create proper user, or use tacacs or radius.

**Comment by Masterbill125** [comment]
@ytti That was it! That was a huge over sight on my side. I was testing on a reformatted JunOS switch. Didn't even think about that. Thanks!!!
