### ISSUE TITLE
`single_repo` with multiple writers

### ISSUE THREAD

**Issue by vincentbernat** [ytti/oxidized#1792]
Hey!

We are using oxidized across several datacenters. In each datacenter, an installation of oxidized is backing up into a shared repository. Each datacenter has its own group and we are using `single_repo` to ensure each datacenter gets its own directory while keeping a single repository.

However, in 0.26.3, when oxidized start, all unknown groups are deleted. Is that expected?

In 0.24.0, there is not this behaviour, but I have often these transient errors:

```
Apr 29 15:27:34 librenms-XXXX oxidized[20034]: E, [2019-04-29T15:27:34.732280 #20034] ERROR -- : Hook push_to_remote (#<GithubRepo:0x00559a5b563b78>) failed (#<NoMethodError: undefined method `name' for nil:NilClass>) for event :post_store
```

Or

```
Apr 29 15:28:44 librenms-XXXX oxidized[20034]: E, [2019-04-29T15:28:44.004872 #20034] ERROR -- : Hook push_to_remote (#<GithubRepo:0x00559a5b563b78>) failed (#<Rugged::ReferenceError: cannot push non-fastforwardable reference>) for event :post_store
```

Or

```
Apr 29 15:00:44 librenms-XXXX oxidized[6651]: E, [2019-04-29T15:00:44.433393 #6651] ERROR -- : Hook push_to_remote (#<GithubRepo:0x005576a1047f50>) failed (#<Rugged::ReferenceError: cannot push because a reference that you are trying to update on the remote contains commits that are not present locally.>) for event :post_store
```

As we have many equipments, I think all these errors come from the fact that the fetch/merge/commit/push strategy is racy as an additional commit may appear after the initial fetch. Should I expect `single_repo` to work across multiple writers?

To keep everything in a single repository, an alternative would be to store each group into its own branch. Is that something that was already discussed in the past?

**Comment by penguin02007** [comment]
We have secondary data centers write to a remote branches and one datacenter acts as primary ( master branch) and merge the remote branches.

**Comment by hcbing** [comment]
@penguin02007 - are you using the githubrepo push_to_remote hook? Have you got an example of how each of the DCS write to remote branches of the same master repo?

**Comment by penguin02007** [comment]
Yes. Here is a snippet for each remote data center.

The primary is the same except it is writing to the master branch in the cmd and a cron job to merge the remote branches.

```
# Remote datacenter
hooks:
  push_to_remote:
    type: exec
    events: [post_store]
    cmd: 'git --git-dir /home/oxidized/oxidized-configs.git remote add origin git@github.com:global-ops-infra/oxidized-configs.git; git --git-dir /home/oxidized/oxidized-configs.git push -u --set-upstream origin master:new_york -f'

# cat /home/oxidized/oxidized-configs.git/config
[core]
        bare = true
        repositoryformatversion = 0
        filemode = true
[user]
        name = svc-ghe
        email = svc-ghe@github.com
[remote "origin"]
        url = git@github.com:global-ops-infra/oxidized-configs.git
        fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
        remote = origin
        merge = refs/heads/development
```

**Comment by hcbing** [comment]
@penguin02007 - So the example above, your remote DC is pushing to the a master repo on branch "new_york". I'd imagine you'd have other DCs pushing to their own respective branches as well. Did you organize each of these branches as separate folders/directories on the master repo? Still trying to figure this piece out, but having each locations pushing to branches and have a merge on master seems to be what I want too.

**Comment by penguin02007** [comment]
Different branches in the same folder. The concept is each datacenter will be in different branch and at the end they will merge into master. This should avoid conflicts as long as you don't have multiple devices defined on multiple sites.

Perhaps this should be added to documentation as it is a common questions?

**Comment by timyam** [comment]
thank you. This worked perfectly for my solution too where I had two separate instances pushing to one repo
