### ISSUE TITLE
diffs for minor switch changes

### ISSUE THREAD

**Issue by kevhjelm** [ytti/oxidized#1795]
In my oxidized I have nodes that gives  new diffes every hour, this are minor changes like change in time 
![image](https://user-images.githubusercontent.com/41345256/57077384-39d73e80-6cec-11e9-9b2f-868aef6e9a8c.png)

This has lead to over 200 diffs versions of this kind. How can I disable this? and for it to only show major changes in the config? the config looks like this:

class VSP7K_ < Oxidized::Model
  

  comment  '#'
  prompt '\n'
  cmd 'show running-config' do |cfg|
    comment cfg
  end

  cfg :ssh do
    # preferred way to handle additional passwords
    post_login do
      #send '\n'
      pw = vars(:enable)
      pw ||= ""
      send "enable\r\n"
      cmd pw
    end
    post_login '\n'
    pre_logout "exit\nexit\nY\r\n"
  end
end

**Comment by cppmonkey** [comment]
Forgive me, but I can't find said model within this or your repo.

It would be great if you'd consider submitting a pull request to add support for the Avaya Virtual Service Platforms.

Additionally, you may wish to look at this for inspiration =)
https://github.com/ytti/oxidized/blob/master/lib/oxidized/model/vrp.rb - Ln28

**Comment by kevhjelm** [comment]
I created the model myself, since I couldnt find support for VSP or ERS switches. But the model keep given multiple diffs showing time difference. Which I find strange since my code is does not indicates that it should happen
