### ISSUE TITLE
Oxidized ios.rb Authentication Failed syslog generated

### ISSUE THREAD

**Issue by Niolith** [ytti/oxidized#1796]
Hello folks,

We are experiencing an issue with Oxidized. If found a post here that advice to change : 

**/usr/local/rvm/gems/ruby-2.6.0/gems/oxidized-0.26.3/lib/oxidized/model/ios.rb**
```
if vars(:enable) == true
        cmd "enable"
      elsif vars(:enable)
        cmd "enable", /^[pP]assword:/
        cmd vars(:enable)
```

to : 
```
if vars(:enable) == true
        cmd "enable"
      elsif vars(:enable)
        cmd "enable"#, /^[pP]assword:/
        cmd vars(:enable)
```

If I change it, Oxidized is working great, but oxs command doesn't work. I have a syslog Fail authentication. 

Is it normal that I have both versions installed ? 
/usr/local/rvm/gems/ruby-2.6.0/gems/oxidized-0.26.3/lib/oxidized/model/ios.rb
/opt/oxidized/.gem/ruby/gems/oxidized-0.14.1/lib/oxidized/model/ios.rb

How to determine which version is use ?

Here are the versions that I use : 
oxidized (0.26.3)
oxidized-script (0.6.0)
oxidized-web (0.13.1)

Let me know if you need further information.
Thank you, 

Sorry for my bad english..

**Comment by davama** [comment]
Might want to submit there instead
https://github.com/ytti/oxidized-script

Whats the output when run as the oxidized user?
> which oxidized
> which gems

I would delete any old gems so that way you dont have any doubt

**Comment by Niolith** [comment]
Hello, sorry I change my post. The issue is related to Oxidized web and Oxidized-script, but the file in problem is the Gem Oxidized

**Comment by davama** [comment]
Looks like you changed then ios.rb file, is that documented officially or some monkey fix?

Dont recall but `oxidized -v` what it say?

Thatll tell you the version you running.

**Comment by Niolith** [comment]
I found the topics here : https://github.com/ytti/oxidized/issues/1665

When I do this modification some of my devices backuped, but some of us are no_connection state.

Here is my config file : 

interval: 86400
log: /opt/oxidized/log
debug: false
use_syslog: false
threads: 30
timeout: 30
retries: 1
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 192.168.0.10:8080
input:
  default: ssh, telnet
  debug: false
  ssh:
    secure: false
source:
  default: csv
  csv:
    file: /opt/oxidized/router.db
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      ip: 1
      model: 2
      group: 3
      username: 4
      password: 5
    vars_map:
      enable: 6
output:
  default: git
  git:
    user: oxidized
    email: oxidized@test.com
    repo: "/opt/oxidized/git-repos/default.git"
model_map:
  cisco: ios
