### ISSUE TITLE
ciscosmb.rb  vars:enable

### ISSUE THREAD

**Issue by menvol3** [ytti/oxidized#1797]
Hi, i have a problen with cisco small business devices

In Oxidized config i use vars: , with enable command to login in privileged mode of device.

Cisco ios.rb file has some code for it

**cfg :telnet, :ssh do
preferred way to handle additional passwords
post_login do
if vars(:enable) == true
cmd "enable"
elsif vars(:enable)
cmd "enable", /^[pP]assword:/
cmd vars(:enable)**

But in ciscosmb.rb  this code not exist.

Is it possible to add it to ciscosmb.rb, if yes please tell me what i must to do, to have it working ?

**Comment by menvol3** [comment]
nice support :)

**Comment by wk** [comment]
You're more than welcome to try this out on your installation by monkey-patching your `ciscosmb` model, replacing the enable handling as per your own example (see [here](https://github.com/ytti/oxidized/blob/master/docs/Creating-Models.md) on the how). 

Not many contributors have access to all device models, so most model improvements and bug fixes come from actual users which have the relevant devices deployed in their network - such as yourself!

Feel free to submit a pull request with the changes if this works out.

**Comment by menvol3** [comment]
I modified ciscosmb.rb file, added the part of code from ios.rb

Now it works, but not good

In ssh logs i see that oxidized logging in into Cisco switch than types enable command, than types password ant it done.

Next commands not executes. 

In Cisco switch logs i see that oxidized trying to do it over and over again, every 3-4 minutes, and than after 5 or 6 connections it start working, and all commands executes well.

How i can to fix this ?
