### ISSUE TITLE
Auto enable on IOS

### ISSUE THREAD

**Issue by Chris-GNS** [ytti/oxidized#1810]
After upgrading .24 to .26.3 some IOS devices fail to capture the config.  After debugging the logins on the devices it appears to be auto-enable issue.

From log file:
Authorized Access only
  This system is the property of Generic Network Systems, LLC
  UNAUTHORIZED ACCESS TO THIS DEVICE IS PROHIBITED.
  You must have explicit permission to access this
  device. All activities performed on this device
  are logged. Any violations of access policy will result
  in disciplinary action.

rt-1941-01#enable

As you can see the prompt is already in enable mode.

Anyone else resolve this issue?

Thanks,
C. B.

**Comment by ytti** [comment]
1. do not pass enable variable, if you do not expect to need to enable
2. set enable variable to false, if you want to pass it, but do not have password

**Comment by Chris-GNS** [comment]
I'm not sure how to do that.  Would I put it in the config or in the router.db?

**Comment by Chris-GNS** [comment]
I did find this:
 if vars(:enable) == true
        cmd "enable"
      elsif vars(:enable)
        cmd "enable", /^[pP]assword:/
        cmd vars(:enable)

I'm guessing I should set that value to false.  Is that correct?

**Comment by Chris-GNS** [comment]
Ok, I found the issue.  I set the value in config file to true.

**Comment by Chris-GNS** [comment]
It does seem the behavior has changed.  Before .26.3 I could set the username and password in the config.  Then all I would have to do is add the device name and model.  Now I have to add the username and password now in the config file or it won't work.

I tried this:
nyc-2960-01:ios:::enablepassword

It didn't work but this did:
nyc-2960-01:ios:username:password:enablepassword

This is the portion of the config that determines those values:
    map:
      name: 0
      model: 1
      username: 2
      password: 3
    vars_map:
      enable: 4

**Comment by ytti** [comment]
1. 'true' string, send enable, do not expect password prompt
2. 'false' string, do not send enable
3. any other string, including empty string, send enable, send password

Previous version did no support all of the options.
