### ISSUE TITLE
Unable to activate oxidized-0.26.3, because slop-4.6.2 conflicts with slop (~> 3.5)

### ISSUE THREAD

**Issue by around84** [ytti/oxidized#1812]
After `gem update` command oxidized was crashed with error

> [around@configs ~]$ /opt/rh/rh-ruby23/root/usr/local/bin/oxidized
> /opt/rh/rh-ruby23/root/usr/share/rubygems/rubygems/specification.rb:2288:in `raise_if_conflicts': Unable to activate oxidized-0.26.3, because slop-4.6.2 conflicts with slop (~> 3.5) (Gem::ConflictError)
>         from /opt/rh/rh-ruby23/root/usr/share/rubygems/rubygems/specification.rb:1411:in `activate'
>         from /opt/rh/rh-ruby23/root/usr/share/rubygems/rubygems.rb:196:in `rescue in try_activate'
>         from /opt/rh/rh-ruby23/root/usr/share/rubygems/rubygems.rb:193:in `try_activate'
>         from /opt/rh/rh-ruby23/root/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:125:in `rescue in require'
>         from /opt/rh/rh-ruby23/root/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:39:in `require'
>         from /opt/rh/rh-ruby23/root/usr/local/share/gems/gems/oxidized-0.26.3/lib/oxidized/cli.rb:4:in `<class:CLI>'
>         from /opt/rh/rh-ruby23/root/usr/local/share/gems/gems/oxidized-0.26.3/lib/oxidized/cli.rb:2:in `<module:Oxidized>'
>         from /opt/rh/rh-ruby23/root/usr/local/share/gems/gems/oxidized-0.26.3/lib/oxidized/cli.rb:1:in `<top (required)>'
>         from /opt/rh/rh-ruby23/root/usr/local/share/gems/gems/oxidized-0.26.3/bin/oxidized:7:in `require_relative'
>         from /opt/rh/rh-ruby23/root/usr/local/share/gems/gems/oxidized-0.26.3/bin/oxidized:7:in `<top (required)>'
>         from /opt/rh/rh-ruby23/root/usr/local/bin/oxidized:22:in `load'
>         from /opt/rh/rh-ruby23/root/usr/local/bin/oxidized:22:in `<main>'

As a temporary solution, I executed

> [around@configs ~] $ gem uninstall slop
> Successfully uninstalled slop-4.6.2

but with the next update everything will break again ...

**Comment by wk** [comment]
Why did you opt to uninstall the new slop, rather than the old slop?

**Comment by around84** [comment]
> Why did you opt to uninstall the new slop, rather than the old slop?

I don't know gem so well =) I run the `gem cleanup --dryrun` and `gem cleanup` after the upgrade, but the old versions remained in the system.
Thanks for the help, I understand that you need to read the documentation for gem.
