### ISSUE TITLE
yum install centos-release-scl

### ISSUE THREAD

**Issue by ufaro186102** [ytti/oxidized#1814]
I am trying to install oxidized on CentOS 7. When I run this command, it does not download the mirrors and instead I get: [Errno 14] curl#6 - "Could not resolve host: rep-centos-ca.upress.io; Unknown error and then I keep getting similar message and it keep saying Trying other mirrors, and then in the end it stops with no package is downloaded. I would appreciate if I can get any assistance with this issue. Thank you

**Comment by davama** [comment]
Not oxidized related.

Sounds like server cannot resolve.
Server pointing to a dns server?

> ping google.com

**Comment by ufaro186102** [comment]
Thank you, I was able to resolve it. It was a network issue.
