### ISSUE TITLE
Run the container for the first time to initialize the config:

### ISSUE THREAD

**Issue by ufaro186102** [ytti/oxidized#1815]
When I run the following command: 

docker run --rm -v /etc/oxidized:/root/.config/oxidized -p 8888:8888/tcp -t oxidized/oxidized:latest oxidized

on CentOS I get the following error message:

docker: Error response from daemon: invalid volume specification: '/etc/oxidized:root/.config' : invalid mount config for type "bind" : invalid mount path: 'root/.config/oxidized' mount path must be absolute

Please, if anyone can help I would really appreciate it. Thank you

**Comment by wk** [comment]
The error appears to be as a result of a typo where the leading slash in the 2nd part of the volume specification was omitted. 

Are you certain you've executed the command *exactly* as `docker run --rm -v /etc/oxidized:/root/.config/oxidized -p 8888:8888/tcp -t oxidized/oxidized:latest oxidized` to receive this error?
