### ISSUE TITLE
Doing a full config dump in OpenWRT

### ISSUE THREAD

**Issue by StevenHorne** [ytti/oxidized#1816]
How do I do a full dump of services installed and a full config dump in OpenWRT.
Typically, in a legible format for swift reviewing.

Is this feasible or doable?

Thanks

Steve

**Comment by wk** [comment]
Hi! It's not very clear from your question if you're looking for help with getting `Oxidized` to do something specific, or with help in using OpenWRT. If you are looking for help in using OpenWRT, their community can be found [here](https://openwrt.org/). 

If you are an Oxidized user and having a specific problem with the `openwrt` model - please provide a more detailed description of the exact way in which the output of that model defers from your expectations.
