### ISSUE TITLE
git.rb:182:in `write_tree': failed to insert entry: invalid object specified

### ISSUE THREAD

**Issue by around84** [ytti/oxidized#1821]
Good day.
Oxidized crash with the following log:
```

[around@oxidized ~]$ /home/around/.gem/ruby/gems/oxidized-0.26.3/bin/oxidized -d
Puma starting in single mode...
* Version 3.11.4 (ruby 2.3.8-p459), codename: Love Song
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://127.0.0.1:8888
Use Ctrl-C to stop
failed to insert entry: invalid object specified - ETC5-Saratov-gw
/home/around/.gem/ruby/gems/oxidized-0.26.3/lib/oxidized/output/git.rb:182:in `write_tree': failed to insert entry: invalid object specified - ETC5-Saratov-gw (Rugged::TreeError)
        from /home/around/.gem/ruby/gems/oxidized-0.26.3/lib/oxidized/output/git.rb:182:in `update_repo'
        from /home/around/.gem/ruby/gems/oxidized-0.26.3/lib/oxidized/output/git.rb:160:in `update'
        from /home/around/.gem/ruby/gems/oxidized-0.26.3/lib/oxidized/output/git.rb:57:in `store'
        from /home/around/.gem/ruby/gems/oxidized-0.26.3/lib/oxidized/worker.rb:65:in `process_success'
        from /home/around/.gem/ruby/gems/oxidized-0.26.3/lib/oxidized/worker.rb:47:in `process'
        from /home/around/.gem/ruby/gems/oxidized-0.26.3/lib/oxidized/worker.rb:16:in `block in work'
        from /home/around/.gem/ruby/gems/oxidized-0.26.3/lib/oxidized/worker.rb:16:in `each'
        from /home/around/.gem/ruby/gems/oxidized-0.26.3/lib/oxidized/worker.rb:16:in `work'
        from /home/around/.gem/ruby/gems/oxidized-0.26.3/lib/oxidized/core.rb:36:in `run'
        from /home/around/.gem/ruby/gems/oxidized-0.26.3/lib/oxidized/core.rb:29:in `initialize'
        from /home/around/.gem/ruby/gems/oxidized-0.26.3/lib/oxidized/core.rb:4:in `new'
        from /home/around/.gem/ruby/gems/oxidized-0.26.3/lib/oxidized/core.rb:4:in `new'
        from /home/around/.gem/ruby/gems/oxidized-0.26.3/lib/oxidized/cli.rb:13:in `run'
        from /home/around/.gem/ruby/gems/oxidized-0.26.3/bin/oxidized:8:in `<main>'
```
oxidized config:
```
[around@oxidized ~]$ cat /home/around/.config/oxidized/config
---
username: backup
password: backuppasswd
model: junos
resolve_dns: false
interval: 3600
use_syslog: false
debug: false
threads: 30
timeout: 60
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 127.0.0.1:8888
next_adds_job: false
vars: {}
groups: {}
models: {}
pid: "/home/around/.config/oxidized/oxidized.pid"
log: "/var/log/oxidized.log"
crash:
  directory: "/home/around/.config/oxidized/crashes"
  hostnames: false
stats:
  history_size: 10
input:
  default: ssh, telnet
  debug: false
#  debug: true
  ssh:
    secure: false
  ftp:
    passive: true
  utf8_encoded: true
output:
  default: git
  git:
    user: around
    email: around@domain
    repo: "/home/around/configs/oxidized.git"
source:
  default: csv
  csv:
    file: "/home/around/.config/oxidized/router.db"
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      ip: 1
      model: 2
      username: 3
      password: 4
    vars_map:
      enable: 5
model_map:
  juniper: junos
  cisco: ios
  dlink: dlink
```

It's a issue with git? How can i more accurately debug what causes a crash?
Thanks a lot in advance!

**Comment by feriniguez** [comment]
It also happened to me:

[root@h...1 ~]# cat /home/config/.config/oxidized/crash
--------------------------------------------------
2019-07-02 20:54:03 UTC
failed to insert entry: invalid object specified - can-f2-201-ap-1 [Rugged::TreeError]
--------------------------------------------------
/usr/local/rvm/gems/ruby-2.3.8/gems/oxidized-0.26.3/lib/oxidized/output/git.rb:182:in `write_tree'
/usr/local/rvm/gems/ruby-2.3.8/gems/oxidized-0.26.3/lib/oxidized/output/git.rb:182:in `update_repo'
/usr/local/rvm/gems/ruby-2.3.8/gems/oxidized-0.26.3/lib/oxidized/output/git.rb:160:in `update'
/usr/local/rvm/gems/ruby-2.3.8/gems/oxidized-0.26.3/lib/oxidized/output/git.rb:57:in `store'
/usr/local/rvm/gems/ruby-2.3.8/gems/oxidized-0.26.3/lib/oxidized/worker.rb:65:in `process_success'
/usr/local/rvm/gems/ruby-2.3.8/gems/oxidized-0.26.3/lib/oxidized/worker.rb:47:in `process'
/usr/local/rvm/gems/ruby-2.3.8/gems/oxidized-0.26.3/lib/oxidized/worker.rb:16:in `block in work'
/usr/local/rvm/gems/ruby-2.3.8/gems/oxidized-0.26.3/lib/oxidized/worker.rb:16:in `each'
/usr/local/rvm/gems/ruby-2.3.8/gems/oxidized-0.26.3/lib/oxidized/worker.rb:16:in `work'
/usr/local/rvm/gems/ruby-2.3.8/gems/oxidized-0.26.3/lib/oxidized/core.rb:36:in `run'
/usr/local/rvm/gems/ruby-2.3.8/gems/oxidized-0.26.3/lib/oxidized/core.rb:29:in `initialize'
/usr/local/rvm/gems/ruby-2.3.8/gems/oxidized-0.26.3/lib/oxidized/core.rb:4:in `new'
/usr/local/rvm/gems/ruby-2.3.8/gems/oxidized-0.26.3/lib/oxidized/core.rb:4:in `new'
/usr/local/rvm/gems/ruby-2.3.8/gems/oxidized-0.26.3/lib/oxidized/cli.rb:13:in `run'
/usr/local/rvm/gems/ruby-2.3.8/gems/oxidized-0.26.3/bin/oxidized:8:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.8/bin/oxidized:23:in `load'
/usr/local/rvm/gems/ruby-2.3.8/bin/oxidized:23:in `<main>'
/usr/local/rvm/gems/ruby-2.3.8/bin/ruby_executable_hooks:24:in `eval'
/usr/local/rvm/gems/ruby-2.3.8/bin/ruby_executable_hooks:24:in `<main>'
--------------------------------------------------
[root@h...1 ~]# date
mar jul  2 21:34:34 UTC 2019
[root@h...1 ~]# gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.7.9
  - RUBY VERSION: 2.3.8 (2018-10-18 patchlevel 459) [x86_64-linux]
  - INSTALLATION DIRECTORY: /usr/local/rvm/gems/ruby-2.3.8
  - USER INSTALLATION DIRECTORY: /root/.gem/ruby/2.3.0
  - RUBY EXECUTABLE: /usr/local/rvm/rubies/ruby-2.3.8/bin/ruby
  - EXECUTABLE DIRECTORY: /usr/local/rvm/gems/ruby-2.3.8/bin
  - SPEC CACHE DIRECTORY: /root/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /usr/local/rvm/rubies/ruby-2.3.8/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /usr/local/rvm/gems/ruby-2.3.8
     - /usr/local/rvm/gems/ruby-2.3.8@global
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /usr/local/rvm/gems/ruby-2.3.8/bin
     - /usr/local/rvm/gems/ruby-2.3.8@global/bin
     - /usr/local/rvm/rubies/ruby-2.3.8/bin
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /home/config/SCRIPTS
     - /home/config/SCRIPTS/root
     - /usr/local/rvm/bin
     - /root/bin
[root@h...1 ~]# 


I need to restart the oxidized service but after wo or three hours it happen again...

any ideas?

**Comment by around84** [comment]
> 
> 
> It also happened to me:
> any ideas?

In my case, the issue was that the git repository was located on the NFS share.
After moving it to the local file system, the issue disappeared.

**Comment by davama** [comment]
Interestingly we get this error too but the device does not exist on our sqlite DB....

```
failed to insert entry: invalid object specified - idn-dk1a-ter-ap-1
/usr/local/rvm/gems/ruby-2.3.8/gems/oxidized-0.26.3/lib/oxidized/output/git.rb:182:in `write_tree': failed to insert entry: invalid object specified - idn-dk1a-ter-ap-1 (Rugged::TreeError)
	from /usr/local/rvm/gems/ruby-2.3.8/gems/oxidized-0.26.3/lib/oxidized/output/git.rb:182:in `update_repo'
	from /usr/local/rvm/gems/ruby-2.3.8/gems/oxidized-0.26.3/lib/oxidized/output/git.rb:160:in `update'
```

```
Enter SQL statements terminated with a ";"
sqlite> select * from devices where name like '%idn-dk1a-ter-ap-1%';
sqlite> 
```


still investigating

**Comment by kendinitekmeleyenkedi** [comment]
Does anyone know a solution for the issue? Same issue...

`oxidized[3188751]: Oxidized crashed, crashfile written in /root/.config/oxidized/crash
oxidized[3188751]: failed to insert entry: invalid object specified - 45.xx.yy.zz
oxidized[3188751]: /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/output/git.rb:182:in `write_tree': failed to insert entry: invalid object spe>
oxidized[3188751]:         from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/output/git.rb:182:in `update_repo'
oxidized[3188751]:         from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/output/git.rb:160:in `update'
oxidized[3188751]:         from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/output/git.rb:57:in `store'
oxidized[3188751]:         from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/worker.rb:65:in `process_success'
oxidized[3188751]:         from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/worker.rb:47:in `process'
oxidized[3188751]:         from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/worker.rb:16:in `block in work'
oxidized[3188751]:         from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/worker.rb:16:in `each'
oxidized[3188751]:         from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/worker.rb:16:in `work'
oxidized[3188751]:         from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:36:in `run'
oxidized[3188751]:         from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:29:in `initialize'
oxidized[3188751]:         from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:4:in `new'
oxidized[3188751]:         from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:4:in `new'
oxidized[3188751]:         from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/cli.rb:13:in `run'
oxidized[3188751]:         from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/bin/oxidized:8:in `<top (required)>'
oxidized[3188751]:         from /usr/local/bin/oxidized:23:in `load'
oxidized[3188751]:         from /usr/local/bin/oxidized:23:in `<main>'
systemd[1]: oxidized.service: Main process exited, code=exited, status=1/FAILURE`

**Comment by Tiki10** [comment]
Hello,

Same error this morning here

--------------------------------------------------
2023-04-14 07:30:11 UTC
failed to insert entry: invalid object specified - w.x.y.z [Rugged::TreeError]
--------------------------------------------------
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/output/git.rb:182:in `write_tree'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/output/git.rb:182:in `update_repo'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/output/git.rb:160:in `update'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/output/git.rb:57:in `store'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/worker.rb:65:in `process_success'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/worker.rb:47:in `process'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/worker.rb:16:in `block in work'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/worker.rb:16:in `each'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/worker.rb:16:in `work'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:36:in `run'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:29:in `initialize'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:4:in `new'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:4:in `new'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/cli.rb:13:in `run'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/bin/oxidized:8:in `<top (required)>'
/usr/local/bin/oxidized:23:in `load'
/usr/local/bin/oxidized:23:in `<main>'
--------------------------------------------------

**Comment by Tiki10** [comment]
Fixed ! 
Go to your git devices directory and do a git status then follow the advice of the output. 

For example : 
root@nagios-eqx:/etc/oxidized/devices.git# git status
fatal: detected dubious ownership in repository at '/etc/oxidized/devices.git'
To add an exception for this directory, call:

        git config --global --add safe.directory /etc/oxidized/devices.git
root@nagios-eqx:/etc/oxidized/devices.git# git config --global --add safe.directory /etc/oxidized/devices.git
root@nagios-eqx:/etc/oxidized/devices.git# systemctl start oxidized
root@nagios-eqx:/etc/oxidized/devices.git# systemctl status oxidized
* oxidized.service - Oxidized - Network Device Configuration Backup Tool
   Loaded: loaded (/lib/systemd/system/oxidized.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2023-04-14 09:40:49 CEST; 31s ago
 Main PID: 25787 (oxidized)
    Tasks: 8 (limit: 4915)
   Memory: 29.7M
   CGroup: /system.slice/oxidized.service
           `-25787 puma 3.11.4 (tcp://w.x.y.z:8888) [/]

Apr 14 09:40:49 nagios-eqx systemd[1]: Started Oxidized - Network Device Configuration Backup Tool.
Apr 14 09:40:50 nagios-eqx oxidized[25787]: Puma starting in single mode...
Apr 14 09:40:50 nagios-eqx oxidized[25787]: * Version 3.11.4 (ruby 2.5.5-p157), codename: Love Song
Apr 14 09:40:50 nagios-eqx oxidized[25787]: * Min threads: 0, max threads: 16
Apr 14 09:40:50 nagios-eqx oxidized[25787]: * Environment: development
Apr 14 09:40:50 nagios-eqx oxidized[25787]: * Listening on tcp://w.x.y.z:8888
Apr 14 09:40:50 nagios-eqx oxidized[25787]: Use Ctrl-C to stop
root@nagios-eqx:/etc/oxidized/devices.git#

**Comment by sliddjur** [comment]
How do I do this when I run oxidized in a container?

**Comment by djrarky** [comment]
@sliddjur  - did you manage to figure that?
