### ISSUE TITLE
Dell PowerConnect 7024F - Prompt character > not detected 

### ISSUE THREAD

**Issue by DonovanEsterhuizen** [ytti/oxidized#1824]
Hi

When trying to backup the switch the telnet log displays the following:

root@monitoring:~/.config/oxidized/logs# more 192.168.16.3-telnet 

User:admin
Password:**************
uni-new-bld-core-sw>

It looks like the prompt is not detecting the **>** so it wont know to send the command enable.

When I run oxs --list-nodes its picking up that its a PowerConnect model.

Any ideas or quick fixes for this.

thanks

**Comment by DonovanEsterhuizen** [comment]
Do I need to configure something in my oxidized config to tell it to send enable command.

**Comment by DonovanEsterhuizen** [comment]
can anyone assist

**Comment by davama** [comment]
Do you have 
```
    vars_map:
      enable: enable

```
in your config ?

**Comment by DonovanEsterhuizen** [comment]
I do:

    vars_map:
      enable: enable

**Comment by davama** [comment]
TIP: https://guides.github.com/features/mastering-markdown/

**Comment by DonovanEsterhuizen** [comment]
This is debug log

User:username
Password:**************
core>

**Comment by DonovanEsterhuizen** [comment]
Sorry how would I do that.

**Comment by DonovanEsterhuizen** [comment]
Yes I did

[config.txt](https://github.com/ytti/oxidized/files/3790589/config.txt)
 Attached is the config for oxidized that I use

**Comment by davama** [comment]
```
log: ~/.config/oxidized/log
```
I am assuming this is a directory. I would change it to /var/log/oxidize/oxidized.log

https://github.com/ytti/oxidized/blob/master/extra/oxidized.logrotate

**Comment by DonovanEsterhuizen** [comment]
I have never setup logrotate for oxidized before im trying to get it working

**Comment by davama** [comment]
No need for logrotate 
It just to show you the directory/file location

**Comment by davama** [comment]
It does not have to be that location. 
Just need to make sure the log: is a file

**Comment by DonovanEsterhuizen** [comment]
log file is is there but it is empty *face palm*

**Comment by davama** [comment]
Ok
Uncomment the `log:` line in your config
Leave `debug: true`
run oxidized on the command line
> $ oxidized
You should see the output on your screen (ie STOUT)

**Comment by DonovanEsterhuizen** [comment]
correct all this to just the debug logs...

#log: /var/log/oxidized/oxidized.log
debug: true

oxidized -d
Puma starting in single mode...
* Version 3.11.4 (ruby 2.5.1-p57), codename: Love Song
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://127.0.0.1:8888
Use Ctrl-C to stop

 still dont see anything...

wt*

**Comment by davama** [comment]
> log file is is there but it is empty _face palm_

It could be a permission issue
> chown <oxidized_user> /var/log/oxidized

But you can worry about that another time if you wish to save you logs there

**Comment by davama** [comment]
> still dont see anything...

hmmm
let me think

**Comment by davama** [comment]
not sure what you could be doing.... :disappointed: 

```
[config@blabla ~]$ grep -E "log|debug:" .config/oxidized/config 
#log: /var/log/oxidized/oxidized.log
debug: true
[config@blabla ~]$ oxidized
I, [2019-10-30T19:10:27.504703 #30601]  INFO -- : Oxidized starting, running as pid 30601
D, [2019-10-30T19:10:27.505526 #30601] DEBUG -- : Hook "first_hook" registered Exec for event :post_store
D, [2019-10-30T19:10:27.505805 #30601] DEBUG -- : Hook "second_hook" registered Exec for event :post_store
I, [2019-10-30T19:10:27.588780 #30601]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
D, [2019-10-30T19:10:27.691422 #30601] DEBUG -- : resolving DNS for blablartr...
D, [2019-10-30T19:10:27.691503 #30601] DEBUG -- : IPADDR blabla
D, [2019-10-30T19:10:27.692438 #30601] DEBUG -- : node.rb: resolving node key 'model', with passed global value of '' and node value 'ios'
D, [2019-10-30T19:10:27.692497 #30601] DEBUG -- : node.rb: setting node key 'model' to value 'junos' from global
```

**Comment by davama** [comment]
using latest version?
```
oxidized --version
0.27.0
```

**Comment by DonovanEsterhuizen** [comment]
oxidized --version
0.27.00.27.0

root@uhc-monitoring:/var/log/oxidized# grep -E "log|debug:" ~/.config/oxidized/config
#log: /var/log/oxidized/oxidized.log
use_syslog: true
debug: true
  debug: true
root@uhc-monitoring:/var/log/oxidized# oxidized 
Puma starting in single mode...
* Version 3.11.4 (ruby 2.5.1-p57), codename: Love Song
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://127.0.0.1:8888
Use Ctrl-C to stop

**Comment by DonovanEsterhuizen** [comment]
if I do systemctl restart oxidized.service

then 

systemctl status oxidized.service i get the below but i dont think that is what we are looking for

Oct 30 21:18:04 uhc-monitoring oxidized[13804]: Use Ctrl-C to stop
root@uhc-monitoring:/var/log/oxidized# systemctl status oxidized.service 
● oxidized.service - Oxidized - Network Device Configuration Backup Tool
   Loaded: loaded (/etc/systemd/system/oxidized.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2019-10-30 21:18:03 SAST; 13s ago
 Main PID: 13804 (oxidized)
    Tasks: 8 (limit: 4915)
   CGroup: /system.slice/oxidized.service
           └─13804 puma 3.11.4 (tcp://127.0.0.1:8888) [/]

Oct 30 21:18:04 uhc-monitoring oxidized[13804]: Puma starting in single mode...
Oct 30 21:18:04 uhc-monitoring oxidized[13804]: * Version 3.11.4 (ruby 2.5.1-p57), codename: Love Song
Oct 30 21:18:04 uhc-monitoring oxidized[13804]: * Min threads: 0, max threads: 16
Oct 30 21:18:04 uhc-monitoring oxidized[13804]: * Environment: development
Oct 30 21:18:04 uhc-monitoring oxidized[13804]: * Listening on tcp://127.0.0.1:8888
Oct 30 21:18:04 uhc-monitoring oxidized[13804]: Use Ctrl-C to stop
Oct 30 21:18:14 uhc-monitoring systemd-journald[394]: Suppressed 681 messages from oxidized.service
Oct 30 21:18:14 uhc-monitoring oxidized[13804]: lib/oxidized/worker.rb: 1 jobs running in parallel
Oct 30 21:18:15 uhc-monitoring oxidized[13804]: lib/oxidized/worker.rb: 1 jobs running in parallel
Oct 30 21:18:16 uhc-monitoring oxidized[13804]: lib/oxidized/worker.rb: 1 jobs running in parallel
root@uhc-monitoring:/var/log/oxidized#

**Comment by davama** [comment]
```
use_syslog: true
```
Hmm, never seen that one... where is that referenced in the docs?
Eitherway set to false or comment it.

**Comment by davama** [comment]
> systemctl status oxidized.service i get the below but i dont think that is what we are looking for

no, stop the service and run `oxidized` in the command line

**Comment by DonovanEsterhuizen** [comment]
#use_syslog: true

systemctl stop oxidized.service

now its working

**Comment by davama** [comment]
and how the logs look?
what is working?
the Powerconnect backup or the debug logs..?

**Comment by davama** [comment]
Not sure how large your source DB is but you can query the API to have oxidized attempt to pull you suspect device:

```
 curl -X GET http://127.0.0.1:8888/node/fetch/<group>/<host>
```

**Comment by DonovanEsterhuizen** [comment]
lib/oxidized/worker.rb: Added /10.110.21.1 to the job queue
D, [2019-10-30T21:29:45.789090 #23583] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2019-10-30T21:29:45.789272 #23583] DEBUG -- : lib/oxidized/job.rb: Starting fetching process for 10.110.21.1 at 2019-10-30 19:29:45 UTC
D, [2019-10-30T21:29:45.789511 #23583] DEBUG -- : lib/oxidized/input/ssh.rb: Connecting to 10.110.21.1
D, [2019-10-30T21:29:45.789701 #23583] DEBUG -- : AUTH METHODS::["none", "publickey", "password"]
D, [2019-10-30T21:29:45.790163 #23583] DEBUG -- net.ssh.transport.session[3fb18a004abc]: establishing connection to 10.110.21.1:22
D, [2019-10-30T21:29:45.793933 #23583] DEBUG -- : 10.110.21.1 raised Errno::ECONNREFUSED with msg "Connection refused - connect(2) for 10.110.21.1:22"
D, [2019-10-30T21:29:45.794093 #23583] DEBUG -- : lib/oxidized/node.rb: Oxidized::SSH failed for 10.110.21.1
D, [2019-10-30T21:29:45.936638 #23583] DEBUG -- : lib/oxidized/input/cli.rb: Running post_login commands at 10.110.21.1
D, [2019-10-30T21:29:45.936943 #23583] DEBUG -- : lib/oxidized/input/cli.rb: Running post_login command: nil, block: #<Proc:0x00007f6314008380@/var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/model/powerconnect.rb:44> at 10.110.21.1
D, [2019-10-30T21:29:45.937073 #23583] DEBUG -- : lib/oxidized/input/cli.rb: Running post_login command: "terminal datadump", block: nil at 10.110.21.1
D, [2019-10-30T21:29:45.937179 #23583] DEBUG -- : Telnet: terminal datadump @10.110.21.1
D, [2019-10-30T21:29:45.996898 #23583] DEBUG -- : lib/oxidized/input/cli.rb: Running post_login command: "terminal length 0", block: nil at 10.110.21.1
D, [2019-10-30T21:29:45.997183 #23583] DEBUG -- : Telnet: terminal length 0 @10.110.21.1
D, [2019-10-30T21:29:46.060705 #23583] DEBUG -- : lib/oxidized/model/model.rb Collecting commands' outputs
D, [2019-10-30T21:29:46.061084 #23583] DEBUG -- : lib/oxidized/model/model.rb Executing show version
D, [2019-10-30T21:29:46.061217 #23583] DEBUG -- : Telnet: show version @10.110.21.1
D, [2019-10-30T21:29:46.129165 #23583] DEBUG -- : lib/oxidized/model/model.rb Executing show system
D, [2019-10-30T21:29:46.129459 #23583] DEBUG -- : Telnet: show system @10.110.21.1
D, [2019-10-30T21:29:46.789351 #23583] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2019-10-30T21:29:47.789644 #23583] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2019-10-30T21:29:48.789926 #23583] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2019-10-30T21:29:49.790269 #23583] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2019-10-30T21:29:50.790565 #23583] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2019-10-30T21:29:51.790832 #23583] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2019-10-30T21:29:52.791180 #23583] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2019-10-30T21:29:53.791555 #23583] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2019-10-30T21:29:54.791864 #23583] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2019-10-30T21:29:55.792144 #23583] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2019-10-30T21:29:56.792479 #23583] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2019-10-30T21:29:57.792784 #23583] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2019-10-30T21:29:58.793131 #23583] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2019-10-30T21:29:59.793486 #23583] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2019-10-30T21:30:00.793740 #23583] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2019-10-30T21:30:01.794025 #23583] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2019-10-30T21:30:02.794309 #23583] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2019-10-30T21:30:03.794609 #23583] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2019-10-30T21:30:04.794889 #23583] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2019-10-30T21:30:05.795216 #23583] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
W, [2019-10-30T21:30:06.217586 #23583]  WARN -- : 10.110.21.1 raised Net::ReadTimeout (rescued Timeout::Error) with msg "timed out while waiting for more data"
D, [2019-10-30T21:30:06.217703 #23583] DEBUG -- : lib/oxidized/node.rb: Oxidized::Telnet failed for 10.110.21.1
D, [2019-10-30T21:30:06.217749 #23583] DEBUG -- : lib/oxidized/job.rb: Config fetched for 10.110.21.1 at 2019-10-30 19:30:06 UTC
W, [2019-10-30T21:30:06.795843 #23583]  WARN -- : /10.110.21.1 status no_connection, retries exhausted, giving up
D, [2019-10-30T21:30:06.795964 #23583] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 1 of 34
D, [2019-10-30T21:30:06.796080 #23583] DEBUG -- : lib/oxidized/worker.rb: Added /10.110.21.247 to the job queue
D, [2019-10-30T21:30:06.796099 #23583] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2019-10-30T21:30:06.796148 #23583] DEBUG -- : lib/oxidized/job.rb: Starting fetching process for 10.110.21.247 at 2019-10-30 19:30:06 UTC
D, [2019-10-30T21:30:06.796327 #23583] DEBUG -- : lib/oxidized/input/ssh.rb: Connecting to 10.110.21.247
D, [2019-10-30T21:30:06.796430 #23583] DEBUG -- : AUTH METHODS::["none", "publickey", "password"]
D, [2019-10-30T21:30:06.796823 #23583] DEBUG -- net.ssh.transport.session[3fb18a023098]: establishing connection to 10.110.21.247:22
D, [2019-10-30T21:30:06.800587 #23583] DEBUG -- : 10.110.21.247 raised Errno::ECONNREFUSED with msg "Connection refused - connect(2) for 10.110.21.247:22"
D, [2019-10-30T21:30:06.800743 #23583] DEBUG -- : lib/oxidized/node.rb: Oxidized::SSH failed for 10.110.21.247
D, [2019-10-30T21:30:06.921268 #23583] DEBUG -- : lib/oxidized/input/cli.rb: Running post_login commands at 10.110.21.247
D, [2019-10-30T21:30:06.921463 #23583] DEBUG -- : lib/oxidized/input/cli.rb: Running post_login command: nil, block: #<Proc:0x00007f63140450a0@/var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/model/powerconnect.rb:44> at 10.110.21.247

**Comment by davama** [comment]
im assuming x.x.x.247 is your misbehaving device...

```
D, [2019-10-30T21:30:06.800587 #23583] DEBUG -- : x.xx.xx.247 raised Errno::ECONNREFUSED with msg "Connection refused - connect(2) for x.x.xx.247:22"
D, [2019-10-30T21:30:06.800743 #23583] DEBUG -- : lib/oxidized/node.rb: Oxidized::SSH failed for x.x.x.247
```

This is interesting. 
Is the device alive? accessible ? Credentials correct? :man_shrugging:

**Comment by DonovanEsterhuizen** [comment]
not that one trying to find it in the logs for you

**Comment by davama** [comment]
If not too difficult, reduce your source to that one device only.
I usually do that when im having issues with a particular device. Dont want my eyes to start crossing looking at all the logs

**Comment by DonovanEsterhuizen** [comment]
This can be closed switches to telnet
