### ISSUE TITLE
Feature Request: schedule backup kickoff via cron

### ISSUE THREAD

**Issue by hvoIIITA** [ytti/oxidized#1827]
Thanks for everyone's work.

I currently work in a small/medium service provider space and would like to see the feature to kickoff jobs via cron like in RANCID come to Oxidized. The main reason being that we run a lot of the Juniper EX2200 platform and have found that sometimes running commands on the devices can cause hanging/inefficiency. Just want to cut down on management chatter during normal business hours.

We are going to implement the syslog config change event option to do so, but most of the time it's not imperative that we have another version/backup of every commit when troubleshooting.

**Comment by wk** [comment]
This is on the roadmap as item 9 on #812 - but is not currently supported. PR for this functionality will be welcome.
