### ISSUE TITLE
POE information causing Oxidized to detect a change

### ISSUE THREAD

**Issue by clontarfx** [ytti/oxidized#1829]
Oxidized is currently pulling POE information from our switches. When the POE information changes, i.e current load/supplied wattage, it causes Oxidized to see a change and then push/commit. This is undesirable. It creates useless commits.

![image](https://user-images.githubusercontent.com/470233/59247224-38852400-8c51-11e9-85f1-5bb66ae8a546.png)

**Comment by wk** [comment]
You may want to consider including the name of the model this relates to as part of the issue. This information does not to be included as part of the subject, the issue text, or the attached screenshot.

**Comment by clontarfx** [comment]
Thanks wk. Models affected are;
 - HP 2920-48G-POE+  J9729A
 - HP 2920-24G-POE+  J9727A

**Comment by rlphnger** [comment]
Having the same issue with some of my HP/Aruba PoE switches (2930f, 2920) but 2530 does not seem to have this problem. It is causing the .git to grow a lot.

**Comment by wk** [comment]
The 'show system power-supply' command has been removed in #1798 and this output should no longer be generated by the `procurve` model.

If you run the official `oxidized/oxidized` docker image or the current git, this should have already been the case - if you run the latest release version, you'll need to either manually incorporate the new version of the model, or wait until such time a release with the change takes place.
