### ISSUE TITLE
syslog/logger truncates logs if Log.debug message exceeds syslog's size

### ISSUE THREAD

**Issue by nickhilliard** [ytti/oxidized#183]
if Log.debug logs a message which is greater than the size allowed by the o/s, the message is truncated.  This isn't really an oxidised problem per-se, but it does indicate that it would be useful to have an alternative logging to syslog/logger, i.e. direct to file.

This is relevant if you're trying to debug input data from devices.

**Comment by ytti** [comment]
This has been fixed in 1c4f886e88
