### ISSUE TITLE
Router.db need help in adding correct supported OS type

### ISSUE THREAD

**Issue by ufaro186102** [ytti/oxidized#1830]
I have 2 device:

1) PacketShaper, Blue Coat Systems
2) RiverBed

I am not sure which OS type does these 2 devices fall under.

**Comment by wk** [comment]
Neither of these device models is currently supported. You can find a list of supported devices [here](https://github.com/ytti/oxidized/blob/master/docs/Supported-OS-Types.md) and information on how to develop support for new device models for Oxidized [here](https://github.com/ytti/oxidized/blob/master/docs/Creating-Models.md).
