### ISSUE TITLE
how to rebound equipment with oxidized

### ISSUE THREAD

**Issue by sebastien34560** [ytti/oxidized#1833]
Hello, 

I have to recover the configuration of an equipment (b) but I have to go through a gateway equipment (a). how can I recover only the configuration of the equipment (b) with oxidized.

thank you for your help.

Sébastien.

**Comment by wk** [comment]
Are you perhaps looking for the [SSH Proxy](https://github.com/ytti/oxidized/blob/master/docs/Configuration.md#ssh-proxy-command) functionality? This is commonly used with bastion hosts and jumpgates where there's an intermediate host through which `Oxidized` must connect to reach the actual node.
