### ISSUE TITLE
Two instances of oxidized in the same server

### ISSUE THREAD

**Issue by infratihc** [ytti/oxidized#1837]
Hello,

Is it possible to execute two instances of the oxidized in the same server with totally separate structures? I tried to replicate all the "oxidized" folders, libs,etc.. to "oxidizedcc", but when I try to run /usr/local/bin/oxidizedcc, the output is `bin_path ': can not find gem oxidizedcc.

It's possible ?

**Comment by davama** [comment]
Thats interesting...

Why need two structures?
Using output File or Git?

**Comment by infratihc** [comment]
We are using here source: sql with the oxidized-web. It works great.
We have branch companies with different IT teams, each one has autonomy over its equipment. The idea is to run another instance of the oxidized and oxidized-web (on another port) for each branch company centralizing the oxidized processes, each branch with its independent view of your settings.

**Comment by WiXZlo** [comment]
Create new user and systemd-unit with different listening port. Web access via nginx as reverse proxy.

- user1, /home/user1/oxidized, port 8001, http://team1.example.com;
- user2, /home/user2/oxidized, port 8002, http://team2.example.com;
etc

**Comment by infratihc** [comment]
Thanks for replay

Yes, I tried to create the two structures.

I created a new user, another systemd-unit, and replicated the whole structure of lib, bin etc, to oxidizedcc to test. 

cat /lib/systemd/system/oxidizedcc.service
[Unit]
Description = Oxidized - Network Device Configuration Backup Tool
After = network-online.target multi-user.target
Wants = network-online.target
[Service]
ExecStart = /usr/local/bin/oxidizedcc 
User = oxidizedcc
KillSignal = SIGKILL
[Install]
WantedBy = multi-user.target

cat /usr/local/bin/oxidizedcc
#!/usr/bin/ruby2.3
#
# This file was generated by RubyGems.
#
# The application 'oxidized' is installed as part of a gem, and
# this file is here to facilitate running it.
require 'rubygems'
version = ">= 0.a"
if ARGV.first
  str = ARGV.first
  str = str.dup.force_encoding("BINARY") if str.respond_to? :force_encoding
  if str =~ /\A_(.*)_\z/ and Gem::Version.correct?($1) then
    version = $1
    ARGV.shift
  end
end
load Gem.bin_path('oxidizedcc', 'oxidizedcc', version)

The problem is that load Gem.bin_path still looking to oxidized.
if I dont split de whole structure, when restart the oxidized, will restart  all the structures

**Comment by laf** [comment]
Just run docker and spin up 2 containers.

**Comment by infratihc** [comment]
Great idea, I'll try.

Thank you

**Comment by wk** [comment]
It should be possible to run multiple Oxidized instances via either:
* Using multiple docker instances of the Oxidized image
* Using multiple different systemd units, each pointing to its own configuration file, and a separate file/directory for things like pid file, outputs.
* By manually starting multiple instances of oxidized with different configuration files that point to different output locations and pid files.

**Comment by infratihc** [comment]
Nice,
Thank you all for the help. It worked, with docker and 2 containers.

Tkss
