### ISSUE TITLE
problem with githubrepo hook

### ISSUE THREAD

**Issue by lsochanowski** [ytti/oxidized#1838]
configuration like bellow ,
problem is oxidize is looping with information "Authenticating using ssh keys as 'git'"
when i've try to push manualy it's working fine .. i can use workaround with exec hook but problem persist ;) 

`output:
  default: git
  git:
    user: Oxidized
    email: o@eot.pl
    repo: "/var/lib/oxidized/devices.git"
hooks:
  push_to_remote:
    type: githubrepo
    events: [post_store]
    remote_repo: git@gitlab.eot.pl:oxidized/configarchive.git
    publickey: /etc/oxidized/.ssh/id_rsa.pub
    privatekey: /etc/oxidized/.ssh/id_rsa

`

`D, [2019-06-27T11:08:34.690209 #18272] DEBUG -- : GithubRepo: Authenticating using ssh keys as 'git'
D, [2019-06-27T11:08:34.691283 #18272] DEBUG -- : GithubRepo: Authenticating using ssh keys as 'git'
D, [2019-06-27T11:08:34.692466 #18272] DEBUG -- : GithubRepo: Authenticating using ssh keys as 'git'
D, [2019-06-27T11:08:34.693549 #18272] DEBUG -- : GithubRepo: Authenticating using ssh keys as 'git'
D, [2019-06-27T11:08:34.694620 #18272] DEBUG -- : GithubRepo: Authenticating using ssh keys as 'git'
D, [2019-06-27T11:08:34.695673 #18272] DEBUG -- : GithubRepo: Authenticating using ssh keys as 'git'
D, [2019-06-27T11:08:34.696734 #18272] DEBUG -- : GithubRepo: Authenticating using ssh keys as 'git'
D, [2019-06-27T11:08:34.697775 #18272] DEBUG -- : GithubRepo: Authenticating using ssh keys as 'git'
D, [2019-06-27T11:08:34.700743 #18272] DEBUG -- : GithubRepo: Authenticating using ssh keys as 'git'
D, [2019-06-27T11:08:34.703617 #18272] DEBUG -- : GithubRepo: Authenticating using ssh keys as 'git'
^CD, [2019-06-27T11:08:34.704872 #18272] DEBUG -- : GithubRepo: Authenticating using ssh keys as 'git'
D, [2019-06-27T11:08:34.706195 #18272] DEBUG -- : GithubRepo: Authenticating using ssh keys as 'git'
D, [2019-06-27T11:08:34.707665 #18272] DEBUG -- : GithubRepo: Authenticating using ssh keys as 'git'
- Gracefully stopping, waiting for requests to finish
=== puma shutdown: 2019-06-27 11:08:34 -0400 ===
- Goodbye!
oxidized@rancid:/var/lib/oxidized/devices.git$ git push
Counting objects: 3, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 295 bytes | 0 bytes/s, done.
Total 3 (delta 2), reused 0 (delta 0)
To gitlab.eot.pl:oxidized/oxidized.git
   795c25a..cd12e55  master -> master
oxidized@rancid:/var/lib/oxidized/devices.git$
`

**Comment by wk** [comment]
This is not currently supported by oxidized, there are no facilities to ignore the outcome of the SSL certificate validation check in the context of the githubrepo hook.

This is supported [upstream](https://github.com/libgit2/rugged/pull/639) by rugged, but requires additional implementation in the githubrepo hook code. PR welcome.

**Comment by wk** [comment]
There is no indication if the same key(s) configured for `Oxidized` are being used in the manual attempt during the git push. Are the keys unlocked and un-passworded?

You may want to use a combination of `ssh-add -L` (to identify if some keys may be loaded or forwarded), and `ssh -i <filename>` pointing to the specific key files you've instructed oxidized to use while testing ssh connectivity and authentication, instead of a simple `git push`, and attempt to log in as the configured user. 

If this succeeds, your remote server may require some combination of ssh parameters which libssh2 (used by Rugged) is not compiled for on your host. Which version of `libssh2` do you currently have installed?

**Comment by lsochanowski** [comment]
```
oxidized@rancid:/var/lib/oxidized/devices.git$ ssh -i ~/.ssh/id_rsa git@gitlab.eot.pl
PTY allocation request failed on channel 0
Welcome to GitLab, @rancid1!
Connection to gitlab.eot.pl closed.
oxidized@rancid:/var/lib/oxidized/devices.git$

```


libssh2-1-dev/stable,stable,now 1.7.0-1+deb9u1 amd64 [installed]

this user have only one key :)

**Comment by tyler-8** [comment]
@lsochanowski Take a look at this comment: https://github.com/ytti/oxidized/issues/1877#issuecomment-519625816

**Comment by ciroiriarte** [comment]
I see a similar behaviour:

GithubRepo: Authenticating using ssh keys as 'git'
GithubRepo: Authenticating using ssh keys as 'git'
GithubRepo: Authenticating using ssh keys as 'git'
GithubRepo: Authenticating using ssh keys as 'git'
GithubRepo: Authenticating using ssh keys as 'git'
GithubRepo: Authenticating using ssh keys as 'git'
GithubRepo: Authenticating using ssh keys as 'git'
GithubRepo: Authenticating using ssh keys as 'git'
GithubRepo: Authenticating using ssh keys as 'git'
GithubRepo: Authenticating using ssh keys as 'git'
GithubRepo: Authenticating using ssh keys as 'git'
GithubRepo: Authenticating using ssh keys as 'git'
GithubRepo: Authenticating using ssh keys as 'git'
GithubRepo: Authenticating using ssh keys as 'git'
GithubRepo: Authenticating using ssh keys as 'git'
GithubRepo: Authenticating using ssh keys as 'git'
GithubRepo: Authenticating using ssh keys as 'git'
GithubRepo: Authenticating using ssh keys as 'git'
GithubRepo: Authenticating using ssh keys as 'git'
GithubRepo: Authenticating using ssh keys as 'git'
GithubRepo: Authenticating using ssh keys as 'git'
GithubRepo: Authenticating using ssh keys as 'git'
GithubRepo: Authenticating using ssh keys as 'git'
GithubRepo: Authenticating using ssh keys as 'git'

But no further errors. I had the key format error in previous attempts, but after converting both Public and Private keys I got no more errors, **but still no repository push**.

The key conversion stesps:

	cp .ssh/id_rsa .ssh/id_rsa-PEM
	ssh-keygen -p -m PEM -f .ssh/id_rsa-PEM
	ssh-keygen -e -m PEM -f .ssh/id_rsa.pub > .ssh/id_rsa.pub-PEM

And the config uses the *-PEM files for githubrepo hook.
