### ISSUE TITLE
Connection log shows all commands are executed, no repo created.

### ISSUE THREAD

**Issue by jj3000** [ytti/oxidized#1842]
I stumbled across the linuxgeneric.rb project and liked the idea of backing up centos servers,so I thought I'd give it a try.        

With debug enabled in my config inspecting the connection logs I can see oxidized connects to the server and successfully executes commands but no repo is created.

I have successfully configured oxidized to backup my cisco switches, routers, asas and voice gateways with no issues.    

I'm not even sure where to start in troubleshooting this issue, any help would be much appreciated! 

Thanks,

J

**Comment by davama** [comment]
Thats odd.

How logs look?
Using default linuxgeneric.rb model or extending or both?
