### ISSUE TITLE
Allow configuring jobs.AVERAGE_DURATION?

### ISSUE THREAD

**Issue by devicenull** [ytti/oxidized#1844]
For our network, the default jobs.AVERAGE_DURATION is very low... each node can take 30-60s to collect. 

This ends up causing some problems at initial startup, as oxidized doesn't spawn enough workers to actually complete a meaningful amount of work until it's been running for a little while.

We've just patched jobs.rb to set AVERAGE_DURATION=60, but this definitely seems like something that's going to need configuring per installation (or persisting it somewhere, so restarting the process doesn't forget the calculated value?)

**Comment by ytti** [comment]
This seems like a fair comment. What is acceptable 'warm up', how many nodes/time does it take for you to get reasonable AVERAGE_DURATION? What is acceptable amount of nodes/time for it?

I think there are ways we can change the algorithm to make it respond faster. Or at least bias to running too fast at start.

**Comment by devicenull** [comment]
We have ~1500 devices configured, and a 1800s interval.  Once it's been running long enough, we end up with around 12 workers at a time, which produces acceptable results.  Based on the logs, we're seeing it take about 30 minutes before it's up to a good number of workers.

This is more of an issue when we're testing new models or other config changes... restarting and then waiting for the right number of workers to get started makes troubleshooting a fairly slow process.
