### ISSUE TITLE
Disable devices to avoid requesting data

### ISSUE THREAD

**Issue by dxks** [ytti/oxidized#1849]
we want to move to oxidized from rancind. Unfortunately I could not determine a solution to disable devices, so that we can keep configuration of decomissioned devices and stop oxidized for requesting data from the devices.

Please support to disable devices.

**Comment by laf** [comment]
> we want to move to oxidized from rancind. Unfortunately I could not determine a solution to disable devices, so that we can keep configuration of decomissioned devices and stop oxidized for requesting data from the devices.

Just remove your device from the source, config isn't removed when oxidized doesn't see the device anymore.

**Comment by davama** [comment]
Use git as output
Remove decommed device from source
And use cgit or other git web frontend to view your repos
