### ISSUE TITLE
get diff didn't work on oxidized-web using apache-proxy

### ISSUE THREAD

**Issue by andretlemos** [ytti/oxidized#1851]
Hi,

I'm using oxidized-web with apache-proxy and I noticed when I tried to compare old diffs between then I got the error below:

Puma caught this error: can't modify frozen String (RuntimeError)
/usr/local/rvm/gems/ruby-2.3.8/gems/haml-5.1.1/lib/haml/parser.rb:205:in `gsub!'
/usr/local/rvm/gems/ruby-2.3.8/gems/haml-5.1.1/lib/haml/parser.rb:205:in `block in inspect'
/usr/local/rvm/gems/ruby-2.3.8/gems/haml-5.1.1/lib/haml/parser.rb:205:in `each'
/usr/local/rvm/gems/ruby-2.3.8/gems/haml-5.1.1/lib/haml/parser.rb:205:in `each_with_object'
/usr/local/rvm/gems/ruby-2.3.8/gems/haml-5.1.1/lib/haml/parser.rb:205:in `inspect'
/usr/local/rvm/gems/ruby-2.3.8/gems/haml-5.1.1/lib/haml/parser.rb:205:in `block in inspect'
/usr/local/rvm/gems/ruby-2.3.8/gems/haml-5.1.1/lib/haml/parser.rb:205:in `each'
/usr/local/rvm/gems/ruby-2.3.8/gems/haml-5.1.1/lib/haml/parser.rb:205:in `each_with_object'
/usr/local/rvm/gems/ruby-2.3.8/gems/haml-5.1.1/lib/haml/parser.rb:205:in `inspect'
/usr/local/rvm/gems/ruby-2.3.8/gems/haml-5.1.1/lib/haml/parser.rb:205:in `block in inspect'
/usr/local/rvm/gems/ruby-2.3.8/gems/haml-5.1.1/lib/haml/parser.rb:205:in `each'
/usr/local/rvm/gems/ruby-2.3.8/gems/haml-5.1.1/lib/haml/parser.rb:205:in `each_with_object'
/usr/local/rvm/gems/ruby-2.3.8/gems/haml-5.1.1/lib/haml/parser.rb:205:in `inspect'
/usr/local/rvm/gems/ruby-2.3.8/gems/haml-5.1.1/lib/haml/parser.rb:205:in `block in inspect'
/usr/local/rvm/gems/ruby-2.3.8/gems/haml-5.1.1/lib/haml/parser.rb:205:in `each'
/usr/local/rvm/gems/ruby-2.3.8/gems/haml-5.1.1/lib/haml/parser.rb:205:in `each_with_object'
/usr/local/rvm/gems/ruby-2.3.8/gems/haml-5.1.1/lib/haml/parser.rb:205:in `inspect'
/usr/local/rvm/gems/ruby-2.3.8/gems/haml-5.1.1/lib/haml/parser.rb:205:in `block in inspect'
/usr/local/rvm/gems/ruby-2.3.8/gems/haml-5.1.1/lib/haml/parser.rb:205:in `each'
/usr/local/rvm/gems/ruby-2.3.8/gems/haml-5.1.1/lib/haml/parser.rb:205:in `each_with_object'
/usr/local/rvm/gems/ruby-2.3.8/gems/haml-5.1.1/lib/haml/parser.rb:205:in `inspect'
/usr/local/rvm/gems/ruby-2.3.8/gems/rack-1.6.11/lib/rack/showexceptions.rb:105:in `inspect'
/usr/local/rvm/gems/ruby-2.3.8/gems/rack-1.6.11/lib/rack/showexceptions.rb:105:in `inspect'
/usr/local/rvm/gems/ruby-2.3.8/gems/rack-1.6.11/lib/rack/showexceptions.rb:105:in `inspect'
/usr/local/rvm/gems/ruby-2.3.8/gems/rack-1.6.11/lib/rack/showexceptions.rb:105:in `inspect'
/usr/local/rvm/gems/ruby-2.3.8/gems/rack-1.6.11/lib/rack/showexceptions.rb:105:in `inspect'
/usr/local/rvm/gems/ruby-2.3.8/gems/rack-1.6.11/lib/rack/showexceptions.rb:105:in `inspect'
/usr/local/rvm/gems/ruby-2.3.8/gems/rack-1.6.11/lib/rack/showexceptions.rb:105:in `inspect'
/usr/local/rvm/gems/ruby-2.3.8/gems/rack-1.6.11/lib/rack/showexceptions.rb:105:in `inspect'
/usr/local/rvm/gems/ruby-2.3.8/gems/rack-1.6.11/lib/rack/showexceptions.rb:105:in `inspect'
/usr/local/rvm/gems/ruby-2.3.8/gems/rack-1.6.11/lib/rack/showexceptions.rb:105:in `inspect'
/usr/local/rvm/gems/ruby-2.3.8/gems/rack-1.6.11/lib/rack/showexceptions.rb:105:in `inspect'
/usr/local/rvm/gems/ruby-2.3.8/gems/rack-1.6.11/lib/rack/showexceptions.rb:105:in `inspect'
/usr/local/rvm/gems/ruby-2.3.8/gems/rack-1.6.11/lib/rack/showexceptions.rb:105:in `inspect'
/usr/local/rvm/gems/ruby-2.3.8/gems/rack-1.6.11/lib/rack/showexceptions.rb:105:in `inspect'
/usr/local/rvm/gems/ruby-2.3.8/gems/rack-1.6.11/lib/rack/showexceptions.rb:105:in `h'
(erb):272:in `block in pretty'
(erb):269:in `each'
(erb):269:in `pretty'
/usr/local/rvm/rubies/ruby-2.3.8/lib/ruby/2.3.0/erb.rb:864:in `eval'
/usr/local/rvm/rubies/ruby-2.3.8/lib/ruby/2.3.0/erb.rb:864:in `result'
/usr/local/rvm/gems/ruby-2.3.8/gems/rack-1.6.11/lib/rack/showexceptions.rb:97:in `pretty'
/usr/local/rvm/gems/ruby-2.3.8/gems/sinatra-1.4.8/lib/sinatra/show_exceptions.rb:34:in `rescue in call'
/usr/local/rvm/gems/ruby-2.3.8/gems/sinatra-1.4.8/lib/sinatra/show_exceptions.rb:24:in `call'
/usr/local/rvm/gems/ruby-2.3.8/gems/sinatra-1.4.8/lib/sinatra/base.rb:182:in `call'
/usr/local/rvm/gems/ruby-2.3.8/gems/sinatra-1.4.8/lib/sinatra/base.rb:2013:in `call'
/usr/local/rvm/gems/ruby-2.3.8/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `block in call'
/usr/local/rvm/gems/ruby-2.3.8/gems/sinatra-1.4.8/lib/sinatra/base.rb:1787:in `synchronize'
/usr/local/rvm/gems/ruby-2.3.8/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `call'
/usr/local/rvm/gems/ruby-2.3.8/gems/rack-1.6.11/lib/rack/urlmap.rb:66:in `block in call'
/usr/local/rvm/gems/ruby-2.3.8/gems/rack-1.6.11/lib/rack/urlmap.rb:50:in `each'
/usr/local/rvm/gems/ruby-2.3.8/gems/rack-1.6.11/lib/rack/urlmap.rb:50:in `call'
/usr/local/rvm/gems/ruby-2.3.8/gems/rack-1.6.11/lib/rack/builder.rb:153:in `call'
/usr/local/rvm/gems/ruby-2.3.8/gems/puma-3.11.4/lib/puma/configuration.rb:225:in `call'
/usr/local/rvm/gems/ruby-2.3.8/gems/puma-3.11.4/lib/puma/server.rb:632:in `handle_request'
/usr/local/rvm/gems/ruby-2.3.8/gems/puma-3.11.4/lib/puma/server.rb:446:in `process_client'
/usr/local/rvm/gems/ruby-2.3.8/gems/puma-3.11.4/lib/puma/server.rb:306:in `block in run'
/usr/local/rvm/gems/ruby-2.3.8/gems/puma-3.11.4/lib/puma/thread_pool.rb:120:in `block in spawn_thread'

The problem doesn't appear when I access the Puma web directly. I'm using the output file as git.

**Comment by wk** [comment]
This appears to be a web interface issue. Please re-open this issue under the `ytti/oxidized-web` repository.
