### ISSUE TITLE
OX_NODE_NAME usage in prompt

### ISSUE THREAD

**Issue by davama** [ytti/oxidized#1857]
Hello,

Is it possible to use `OX_NODE_NAME` in `prompt` https://github.com/ytti/oxidized/blob/2f38ef19e207e23aaa1eb2e1eaefe2ca5ebff1af/lib/oxidized/model/ios.rb#L2?

That would make regex soo much easier.

Something like:
`/OX_NODE_NAME[#]/`

Thanks,
Dave

**Comment by davama** [comment]
Closing old ticket

**Comment by renoPSC** [comment]
> Hello,
> 
> Is it possible to use `OX_NODE_NAME` in `prompt`
> 
> https://github.com/ytti/oxidized/blob/2f38ef19e207e23aaa1eb2e1eaefe2ca5ebff1af/lib/oxidized/model/ios.rb#L2
> 
> ?
> That would make regex soo much easier.
> 
> Something like: `/OX_NODE_NAME[#]/`
> 
> Thanks, Dave

Dave, I have a similar question. Did you ever make this work?

**Comment by davama** [comment]
Nope

we just use regex that’ll match
