### ISSUE TITLE
Use of external scripts that write conf to stdout

### ISSUE THREAD

**Issue by deajan** [ytti/oxidized#1865]
Hello,

I'm struggling to find any documentation of oxidized can run a simple external script that returns config data.

I have some quite ugly with GUI only, where I use selenium-python to login via a headless firefox and retrieve the configuration.

I would like to write an oxidized model which just calls my script which writes the config to stdout.
Any chance there is such a mechanism in oxidized ?

Best regards.

**Comment by davama** [comment]
Not sure what you are looking for but,

We use a script that simply calls the api for the config.

It first find the group of the device from the sqllite DB then queries the api.

If you want to run a script post config pull you can look at the hooks to do that.
https://github.com/ytti/oxidized/blob/master/docs/Hooks.md

Hope that helps

**Comment by deajan** [comment]
Thanks for your answer.
I'd actually like, for some devices in a group, call an external script to get the configuration instead of using SSH / telnet since both protocols aren't handled.
Since neither SSH nor telnet work, post hooks never get executed.

From what I understand, the hooks you're talking about get executed for every device.
So I could workaround my problem by creating a hook that gets executed on `node_fail`, checks if OX_NODE_GROUP contains the group I'm targetting, and then does it's job.

The problem with that solution is that oxidized will never store the configuration my script will retrieve. That's the reason I'm asking if there's a way to call plain scripts instead of ssh / telnet / ftp.
I've checked the sources, but I'm really not a ruby guy to read those.

**Comment by davama** [comment]
So this is a device that pulls config via HTTP?
Is there a model for your device?
I believe there are models out there that do HTTP pulls.
You could create your own using templates from other models.

**Comment by deajan** [comment]
If only HTTP would work...
The device is a hp 1810-24G v2, which does not support any kind of curl / wget magic because of JS (v1 supported it).
I managed to make a selenium script (which is bad enough) in order to have a headless firefox fetch the config file.
There are alot of these switches, so my problem is real enough for me to search a solution.

**Comment by davama** [comment]
Yikes!

At that point i would make sure on latest FW or submit ticket with vendor for some form of remote pull support...

Not sure what the folks here at oxidized could do for you. I would reach out to them on the discussion forum. I believe it’s gitter.

Best,
Dave

**Comment by deajan** [comment]
The last firmware of that switch is 2016, and vendor support has been shutdown, so that's not a route I can go (neither can I just change all those switches).

I was actually searching for a very small oxidized wrapper, which would work like let's say the ftp mode, but instead of connecting, just executing a script like the following pseudo code:
```
class Uglydevice < Oxidized::Model

cfg :extscript do
    myscript = '/opt/ugly_script.sh OX_NODE_NAME OX_NODE_IP'
    cfg << `${myscript}`
end
```

where ugly_script.sh would do the behind the curtains selenium / whatever other trick may be required to fetch configs from other devices that don't do ssh/telnet nor http without js.

Anyway, thanks for your help ;)

**Comment by ytti** [comment]
I could certainly add exec/shell input method.  Something like

```
cmd "what to execute" do |output|
   ...
end
cfg :exec do
end
```

**Comment by davama** [comment]
@ytti 
This is interesting!
Out of curiosity, how would that work with multi-file in git?
https://github.com/ytti/oxidized/blob/master/docs/Creating-Models.md#advanced-features

```
...blabla
cfg :exec do
        cfg.type = "junos-set"
        cfg.name = "set"
        cfg
end
```

Thanks

**Comment by ytti** [comment]
It is entirely decoupled. So it would work like in every other model.
 

```
cmd "what to execute" do |output|
  output.type = "blaa"
  output.name =" bloo"
  output
end
```

**Comment by deajan** [comment]
Wow, that looks amazing, and would render oxidized virtually usable with every text extraction method that would is imaginable, ontop of resolving my cursed device issue :)

I'm thinking of oxidized being used to save / diff really different stuff, from service status commands to very obscure scenarios.

I'd love this to see this implemented, can sponsor a bit if needed.

**Comment by ytti** [comment]
In .config/oxidized/input/exec.rb add something like this:

```ruby
module Oxidized
  require_relative "cli"

  class Exec < Input
    include Input::CLI

    def connect(node)
      @node = node
      @node.model.cfg["exec"].each { |cb| instance_exec(&cb) }
      @log = File.open(Oxidized::Config::Log + "/#{@node.ip}-exec", "w") if Oxidized.config.input.debug?
    end

    def cmd(cmd_str)
      Oxidized.logger.debug "EXEC: #{cmd_str} @ #{@node.name}"
      # I'd really like to do popen3 with separate arguments, but that would
      # require refactoring cmd to take parameters
      %x(cmd_str)
    end

    private

    def disconnect
      true
    ensure
      @log.close if Oxidized.config.input.debug?
    end
  end
end
```

See if it works.

Having said that, we do support http mechanise to interact with web-pages. And I see no particular reason why arbitrarily weird device couldn't be supported by models with appropriate input method.
But I also understand people have some stuff they'd rather not port.

**Comment by ytti** [comment]
Remember that your model must define  cfg :exec. And your config must allow exec input method (ssh, exec, telnet, http, blaabalaa).

**Comment by ytti** [comment]
Then your model can be in .config/oxidized/model/blaablaa.rb

```
class Blaablaa < Oxidized::Model
  cmd "shell_command arguments"
  cfg :exec do
  end
```

**Comment by deajan** [comment]
Wow, awesome !
I'll try this monday.

**Comment by deajan** [comment]
So far so good, can't get this to run yet.

I've written a small hello world type script in /home/oxidized/local.sh like:
```
#!/bin/bash

echo "$(date)-$(set)" > /home/oxidized/set
echo $(set)
```

Putting exec.rb in /home/oxidized/.config/oxidized/model/exec.rb ends with error:
`exec not found for node 127.0.0.1`.
So I ended up putting the exec routine in /usr/local/rvm/gems/ruby-2.3.8/gems/oxidized-0.26.3/lib/oxidized/input/exec.rb
```
module Oxidized
  require_relative "cli"

  class Exec < Input
    include Input::CLI

    def connect(node)
      @node = node
      @node.model.cfg["exec"].each { |cb| instance_exec(&cb) }
      @log = File.open(Oxidized::Config::Log + "/#{@node.ip}-exec", "w") if Oxidized.config.input.debug?
    end

    def cmd(cmd_str)
      Oxidized.logger.debug "EXEC: #{cmd_str} @ #{@node.name}"
      # I'd really like to do popen3 with separate arguments, but that would
      # require refactoring cmd to take parameters
      %x(cmd_str)
    end

    private

    def disconnect
      true
    ensure
      @log.close if Oxidized.config.input.debug?
    end
  end
end
```

Then created an empty model in /home/oxidized/.config/oxidized/model/somemodel.rb
```
class SomeModel < Oxidized::Model

  cmd '/home/oxidized/local.sh'
  cfg :exec do
  end
end
```

Added a fake device in router.db
```
127.0.0.1:somemodel:ad:min
```

And allowed exec in input method in config
```
input:
  default: ssh, telnet, exec
  debug: true
  ssh:
    secure: false
  ftp:
    passive: true
  utf8_encoded: true
```

Now when I run oxidized, I get the following:
```
E, [2019-08-06T10:09:37.755454 #10086] ERROR -- : 127.0.0.1 raised Errno::ENOENT with msg "No such file or directory - cmd_str", 127.0.0.1 saved
W, [2019-08-06T10:09:38.751882 #10086]  WARN -- : /127.0.0.1 status no_connection, retry attempt 1
E, [2019-08-06T10:09:38.756886 #10086] ERROR -- : 127.0.0.1 raised Errno::ENOENT with msg "No such file or directory - cmd_str", 127.0.0.1 saved
W, [2019-08-06T10:09:39.753230 #10086]  WARN -- : /127.0.0.1 status no_connection, retry attempt 2
E, [2019-08-06T10:09:39.758204 #10086] ERROR -- : 127.0.0.1 raised Errno::ENOENT with msg "No such file or directory - cmd_str", 127.0.0.1 saved
W, [2019-08-06T10:09:40.754686 #10086]  WARN -- : /127.0.0.1 status no_connection, retry attempt 3
E, [2019-08-06T10:09:40.759051 #10086] ERROR -- : 127.0.0.1 raised Errno::ENOENT with msg "No such file or directory - cmd_str", 127.0.0.1 saved
W, [2019-08-06T10:09:41.756041 #10086]  WARN -- : /127.0.0.1 status no_connection, retries exhausted, giving up
```

I double checked that /home/oxidized/local.sh is executable and produces output, it does.
Guess I did something wrong, but I have no clue what.

**Comment by ytti** [comment]
It wasn't typo when I said exec needs to be in ```input```. It's not a model, it's input method (like ssh, telnet, ftp, tftp...).

**Comment by deajan** [comment]
Indeed, but having put exec.rb in the global input folder made the `exec not found` problem go away.
Putting it back in /home/oxidized/.config/oxidized/input/exec.rb gives again:
```
I, [2019-08-06T10:39:02.677293 #12797]  INFO -- : Oxidized starting, running as pid 12797
I, [2019-08-06T10:39:02.679423 #12797]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
F, [2019-08-06T10:39:02.882763 #12797] FATAL -- : Oxidized crashed, crashfile written in /home/oxidized/.config/oxidized/crash
exec not found for node 127.0.0.1
```

Verified that input/exec.rb has the right permissions too.

Sorry if I misunderstand something here.

**Comment by ytti** [comment]
so you have the crash file? Which oxidized version?

**Comment by deajan** [comment]
Oxidized v0.26.3
Crash file
```
--------------------------------------------------
2019-08-06 08:39:02 UTC
exec not found for node 127.0.0.1 [Oxidized::MethodNotFound]
--------------------------------------------------
/usr/local/rvm/gems/ruby-2.3.8/gems/oxidized-0.26.3/lib/oxidized/node.rb:155:in `block in resolve_input'
/usr/local/rvm/gems/ruby-2.3.8/gems/oxidized-0.26.3/lib/oxidized/node.rb:154:in `map'
/usr/local/rvm/gems/ruby-2.3.8/gems/oxidized-0.26.3/lib/oxidized/node.rb:154:in `resolve_input'
/usr/local/rvm/gems/ruby-2.3.8/gems/oxidized-0.26.3/lib/oxidized/node.rb:23:in `initialize'
/usr/local/rvm/gems/ruby-2.3.8/gems/oxidized-0.26.3/lib/oxidized/nodes.rb:21:in `new'
/usr/local/rvm/gems/ruby-2.3.8/gems/oxidized-0.26.3/lib/oxidized/nodes.rb:21:in `block (2 levels) in load'
/usr/local/rvm/gems/ruby-2.3.8/gems/oxidized-0.26.3/lib/oxidized/nodes.rb:16:in `each'
/usr/local/rvm/gems/ruby-2.3.8/gems/oxidized-0.26.3/lib/oxidized/nodes.rb:16:in `block in load'
/usr/local/rvm/gems/ruby-2.3.8/gems/oxidized-0.26.3/lib/oxidized/nodes.rb:130:in `synchronize'
/usr/local/rvm/gems/ruby-2.3.8/gems/oxidized-0.26.3/lib/oxidized/nodes.rb:130:in `with_lock'
/usr/local/rvm/gems/ruby-2.3.8/gems/oxidized-0.26.3/lib/oxidized/nodes.rb:10:in `load'
/usr/local/rvm/gems/ruby-2.3.8/gems/oxidized-0.26.3/lib/oxidized/nodes.rb:125:in `initialize'
/usr/local/rvm/gems/ruby-2.3.8/gems/oxidized-0.26.3/lib/oxidized/core.rb:14:in `new'
/usr/local/rvm/gems/ruby-2.3.8/gems/oxidized-0.26.3/lib/oxidized/core.rb:14:in `initialize'
/usr/local/rvm/gems/ruby-2.3.8/gems/oxidized-0.26.3/lib/oxidized/core.rb:4:in `new'
/usr/local/rvm/gems/ruby-2.3.8/gems/oxidized-0.26.3/lib/oxidized/core.rb:4:in `new'
/usr/local/rvm/gems/ruby-2.3.8/gems/oxidized-0.26.3/lib/oxidized/cli.rb:13:in `run'
/usr/local/rvm/gems/ruby-2.3.8/gems/oxidized-0.26.3/bin/oxidized:8:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.8/bin/oxidized:23:in `load'
/usr/local/rvm/gems/ruby-2.3.8/bin/oxidized:23:in `<main>'
/usr/local/rvm/gems/ruby-2.3.8/bin/ruby_executable_hooks:24:in `eval'
/usr/local/rvm/gems/ruby-2.3.8/bin/ruby_executable_hooks:24:in `<main>'
--------------------------------------------------
```

**Comment by ytti** [comment]
https://github.com/ytti/oxidized/blob/765c1085d6ef656aa3533b7487b983d8219877e1/lib/oxidized/node.rb#L155

https://github.com/ytti/oxidized/blob/765c1085d6ef656aa3533b7487b983d8219877e1/lib/oxidized/manager.rb#L34-L36

For some reason does not seem to find it, are you using default OXIDIZED_HOME or have you set it? If you have set OXIDIZED_HOME you should put model/input dirs there.

Otherwise, I'll test locally to reduce the loop time.

**Comment by deajan** [comment]
For the sake of sanity, I've rebooted my oxidized server, made a `set | grep OXIDIZED_HOME` to be sure.
I don't have OXIDIZED_HOME defined.
Also, with the same config, models are found in the same path as input (ie /home/oxidized/.config/oxidized/{input,model} ) so I guess oxidized finds the "right" home path.

**Comment by ytti** [comment]
two obvious errors, works now.

```diff
╰─ git diff|cat
diff --git a/lib/oxidized/input/exec.rb b/lib/oxidized/input/exec.rb
index 32e00fe..b9e2298 100644
--- a/lib/oxidized/input/exec.rb
+++ b/lib/oxidized/input/exec.rb
@@ -1,5 +1,5 @@
 module Oxidized
-  require_relative "cli"
+  require "oxidized/input/cli"

   class Exec < Input
     include Input::CLI
@@ -14,7 +14,7 @@ module Oxidized
       Oxidized.logger.debug "EXEC: #{cmd_str} @ #{@node.name}"
       # I'd really like to do popen3 with separate arguments, but that would
       # require refactoring cmd to take parameters
-      %x(cmd_str)
+      %x(#{cmd_str})
     end

     private
```

**Comment by ytti** [comment]
Model I used to to test:

```ruby
class Poop < Oxidized::Model
  cmd 'ls'
  cfg(:exec){}
end
```

**Comment by deajan** [comment]
Obvious errors for someone who speaks Ruby ;)
I've modded the exec.rb file, now exec method is found.

But I still have a problem. I litteraly finished using your model, and this is what I get:
```
W, [2019-08-06T11:40:55.441906 #5399]  WARN -- : /127.0.0.1 status no_connection, retry attempt 1
W, [2019-08-06T11:40:56.443333 #5399]  WARN -- : /127.0.0.1 status no_connection, retry attempt 2
W, [2019-08-06T11:40:57.444655 #5399]  WARN -- : /127.0.0.1 status no_connection, retry attempt 3
W, [2019-08-06T11:40:58.446069 #5399]  WARN -- : /127.0.0.1 status no_connection, retries exhausted, giving up
```

Router.db file has the following config where 127.0.0.1 is set so oxidized doesn't complain about non resolvable host.
```
127.0.0.1:somemodel:ad:min
```

**Comment by ytti** [comment]
could you try /bin/ls or something known to execute correctly.

If you run with debug on, do you get: 
Oxidized.logger.debug "EXEC: #{cmd_str} @ #{@node.name}"

**Comment by ytti** [comment]
For me:

```
D, [2019-08-06T12:48:26.562723 #3448] DEBUG -- : lib/oxidized/worker.rb: Added /127.0.0.1 to the job queue
D, [2019-08-06T12:48:26.563103 #3448] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2019-08-06T12:48:26.563437 #3448] DEBUG -- : lib/oxidized/job.rb: Starting fetching process for 127.0.0.1 at 2019-08-06 09:48:26 UTC
D, [2019-08-06T12:48:26.564271 #3448] DEBUG -- : lib/oxidized/input/cli.rb: Running post_login commands at 127.0.0.1
D, [2019-08-06T12:48:26.564675 #3448] DEBUG -- : lib/oxidized/model/model.rb Collecting commands' outputs
D, [2019-08-06T12:48:26.565090 #3448] DEBUG -- : lib/oxidized/model/model.rb Executing /bin/ls
D, [2019-08-06T12:48:26.565393 #3448] DEBUG -- : EXEC: /bin/ls @ 127.0.0.1
HERE with '/bin/ls'
D, [2019-08-06T12:48:26.567959 #3448] DEBUG -- : lib/oxidized/node.rb: Oxidized::Exec ran for 127.0.0.1 successfully
D, [2019-08-06T12:48:26.568276 #3448] DEBUG -- : lib/oxidized/job.rb: Config fetched for 127.0.0.1 at 2019-08-06 09:48:26 UTC
I, [2019-08-06T12:48:27.564227 #3448]  INFO -- : Configuration updated for /127.0.0.1
D, [2019-08-06T12:48:27.564357 #3448] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 1 of 1
D, [2019-08-06T12:48:27.564419 #3448] DEBUG -- : lib/oxidized/worker.rb: Running :nodes_done hook
D, [2019-08-06T12:48:28.564676 #3448] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 0 of 1
```

**Comment by deajan** [comment]
Okay, here's some fun part:

This is the log with debug disabled:
```
W, [2019-08-06T15:03:50.362628 #19395]  WARN -- : /127.0.0.1 status no_connection, retry attempt 1
W, [2019-08-06T15:03:51.364030 #19395]  WARN -- : /127.0.0.1 status no_connection, retry attempt 2
W, [2019-08-06T15:03:52.365480 #19395]  WARN -- : /127.0.0.1 status no_connection, retry attempt 3
W, [2019-08-06T15:03:53.366842 #19395]  WARN -- : /127.0.0.1 status no_connection, retries exhausted, giving up
```

This is the log with debug enabled:
```
I, [2019-08-06T15:05:09.741579 #19470]  INFO -- : Configuration updated for /127.0.0.1
```

I ended up comparing with other models, and inverted the @log and @node line in function connect to look like:
```
      @log = File.open(Oxidized::Config::Log + "/#{@node.ip}-exec", "w") if Oxidized.config.input.debug?
      @node.model.cfg["exec"].each { |cb| instance_exec(&cb) }
```

Now both debug=false and debug=true work.

I've got a very last question, is there any way to retrieve the node name / ip ?
I've tried `cmd ' /home/oxidized/local.sh #{@node.name}'` but I guess #{@node.name} isn't accessible from the models, isn't it ? Neither seems OX_NODE_NAME defined.

**Comment by ytti** [comment]
This is one approach to the problem: https://github.com/ytti/oxidized/blob/master/lib/oxidized/input/http.rb#L40

Have the input expand the string, input being something like "blaagblaa %{something} blaablaa"

**Comment by deajan** [comment]
Nice ! Thank you alot !
I said in the first place I'd fund a bit, do you have any paypal where I can pay you for the work done ?

**Comment by ytti** [comment]
That won't be necessary.

**Comment by n-piipel** [comment]
Hello! Sorry for my question...
How can I pass the node.name to my script? I really don't understand.

This way isn't working, because in cmd block isn't node.name.
`class Hikvision < Oxidized::Model

  cmd 'python hikcam.py #{@node.name}' do |cfg|
    cfg
  end

  cfg :exec do
  end

end`

And I can't pass node name from cfg block to cmd block by variable or by global variable.

And if I use cmd block inside the cfg, it works for getting data from my script, but it doesn't save data to backup file.
`class Hikvision < Oxidized::Model

  cfg :exec do
    cmd 'python hikcam.py #{@node.name}' do |cfg|
      cfg
    end
  end

end`

Send me correct examples please!
Thanks! 🙏🙏
@ytti @deajan

**Comment by Abyss777** [comment]
Hello

Is there any way to determine if an external script was unsuccessful?

Oxidized accept any output from script, even empty or with non-zero exit code. And commit that output to repository.

**Comment by Abyss777** [comment]
Improved `cmd` function

```ruby
    def cmd(cmd_str)
      Oxidized.logger.debug "EXEC: #{cmd_str} @ #{@node.name}"
      # I'd really like to do popen3 with separate arguments, but that would
      # require refactoring cmd to take parameters
      cmd = %x(#{cmd_str})
      if $?.exitstatus > 0
        raise OxidizedError, "EXEC: exit code is #{$?.exitstatus}"
      end
      if cmd.empty?
        raise OxidizedError, "EXEC: result is empty"
      end
      cmd
    end
```

will you accept a PR ?
