### ISSUE TITLE
Update Oxidized Ruby 2.3

### ISSUE THREAD

**Issue by rpgh1020** [ytti/oxidized#1879]
I know this isn't directly related to oxidized but I was hoping to get a quick response to send me down the right path.  I am running Centos7 with ruby 2.0 and need to update to ruby 2.3 for oxidized update.  What are the recommended upgrade steps to accomplish this? I noticed that after installing ruby 2.3 via scl all the previous installed gems are missing.  Thank you in advance.

**Comment by davama** [comment]
Assuming followed this?
https://github.com/ytti/oxidized#installing-ruby-23-using-rvm

`which gem` should point you to the 2.3 version of gem.

You will have to install all the needed gems under the new 2.3 directory.
I would delete the old gem entirely from the system.

**Comment by davama** [comment]
I personally had tried via scl but had issues. Dont recall what exactly but i was recommended to use RVM

**Comment by rdpettigrew** [comment]
> Assuming followed this?
> https://github.com/ytti/oxidized#installing-ruby-23-using-rvm
> 
> `which gem` should point you to the 2.3 version of gem.
> 
> You will have to install all the needed gems under the new 2.3 directory.
> I would delete the old gem entirely from the system.

Thanks for the quick reply.  I had not done the RVM install yet just SCL and reverted back my snapshot when I noticed a few things didnt seem right and figured I would do a little research before trying again. 

Sorry for the ignorance but should I be doing a gem uninstall for all gems? I have 3 different directories of gems it looks like. Should I keep the current ruby 2.0 installed? It looks like i should based off the install document dependencies.
