### ISSUE TITLE
Mikrotik config backup issue

### ISSUE THREAD

**Issue by oldnickru** [ytti/oxidized#1881]
Hi!

I've encountered strange problem with Mikrotik config backup. I have several Mikrotik routers and backup config via ssh. Everything was fine, until I tried to backup router with very large config (2k+ lines). Problem is that config from this router was only partially downloaded (about 1.5k lines of 2k+ lines). So I tried to debug this problem and that is what I found:
1) If I enable "debug: true" and "input: debug: true", and then run oxidized, my log files for Mikrotik routers are empty. Cisco routers are fine. Backup transport is ssh.
2) If I switch to telnet with debug enabled, there is some output in the Mikrotik logs files, but configuration files are not updated. Log file from router:
[10.2.9.122-telnet.txt](https://github.com/ytti/oxidized/files/3498761/10.2.9.122-telnet.txt)

3) If is use telnet there is 100% cpu load from oxidized process (both with or without debug enabled).

I tried another Mikrouter router with another RouterOS version (6.44) with the same result.

OS is Centos 7. Oxidized version is 0.26.3.

Appreciate your help.

**Comment by oldnickru** [comment]
Just to clarify: in my message by "log files" I mean files with debug output (x.x.x.x-telnet/ssh).

**Comment by wk** [comment]
There were some changes introduced to this model in #1757 which appear to address a number of the issues you're reporting. This took place shortly after 0.26.3 was released. 

Try the master branch (or the docker container, which is built from it), or simply replace that model alone in your installation by dropping the `routeros.rb` file from the current [master](https://raw.githubusercontent.com/ytti/oxidized/master/lib/oxidized/model/routeros.rb) into your ~/.config/oxidized/model/ directory and reload oxidized.

**Comment by oldnickru** [comment]
I've made a fresh test setup with VirtualBox - one oxidized VM, one Mikrotik router:
OS: Ubuntu Server 18.04.3 LTS
Mikrotik: https://download.mikrotik.com/routeros/6.44.5/chr-6.44.5.vdi

VM and Mikrotik router are in the same network (10.0.0.0/24).

Oxidized was installed from the master branch:
oxidized@oxidized:~/.config/oxidized$ oxidized -v
0.26.3-57-gea14336
Indeed, problem with CPU spikes during telnet backup was resolved in this release. But other problems remained. So I've made some tests to try to understand what is going on.

At first I've tested configuration backup from Mikrotik router with no router configuration except ip address and user. This is what I've got:
1) Backup config via ssh with debug disabled:
debug: false
input:
  default: ssh
  debug: false

Configuration was downloaded from the device.

2) Backup config via ssh with debug enabled:
debug: true
input:
  default: ssh
  debug: true

Configuration was downloaded from the device. Debug output file (logs/10.0.0.2-ssh) was empty.

3) Backup config via telnet with debug disabled:
debug: false
input:
  default: telnet
  debug: false

Configuration was downloaded from the device.

4) Backup config via telnet with debug enabled:
debug: true
input:
  default: telnet
  debug: true

Configuration was downloaded from the device.  Debug output file (logs/10.0.0.2-telnet) did not show any configuration except login banner and the first command line prompt, no command execution recorded.


After that, I've added around 3000 static routed to the Mikrotik configuration. And this is what i've got:
1) Backup config via ssh with debug disabled:
debug: false
input:
  default: ssh
  debug: false

Configuration was downloaded from the device.

2) Backup config via ssh with debug enabled:
debug: true
input:
  default: ssh
  debug: true

Configuration was partially downloaded from the device, about 2400 lines of 3000. Debug output file (logs/10.0.0.2-ssh) was empty.

3) Backup config via telnet with debug disabled:
debug: false
input:
  default: telnet
  debug: false

Configuration was not downloaded from the device. Received following errors (10.0.0.2 is Mikrotik router):
WARN -- : 10.0.0.2 raised Net::ReadTimeout (rescued Timeout::Error) with msg "timed out while waiting for more data"
WARN -- : /10.0.0.2 status no_connection, retry attempt 1
WARN -- : 10.0.0.2 raised Net::ReadTimeout (rescued Timeout::Error) with msg "timed out while waiting for more data"
WARN -- : /10.0.0.2 status no_connection, retry attempt 2
WARN -- : 10.0.0.2 raised Net::ReadTimeout (rescued Timeout::Error) with msg "timed out while waiting for more data"
WARN -- : /10.0.0.2 status no_connection, retry attempt 3
WARN -- : 10.0.0.2 raised Net::ReadTimeout (rescued Timeout::Error) with msg "timed out while waiting for more data"
WARN -- : /10.0.0.2 status no_connection, retries exhausted, giving up

4) Backup config via telnet with debug enabled:
debug: true
input:
  default: telnet
  debug: true

Configuration was not downloaded from the device. Received the same errors. And debug output file (logs/10.0.0.2-telnet) did not show any configuration except login banner and the first command line prompt, no command execution recorded.

After that I've decided to add some delay between Ubuntu Server and Mikrotik router:
$ tc qdisc add dev enp0s8 root netem delay 100ms

And tried to backup config via ssh with debug disabled:
debug: false
input:
  default: ssh
  debug: false

Configuration was partially downloaded from the device, about 2400 lines of 3000.

I may be mistaken, but it seems like there is some problem with capturing of the command line prompt on Mikrotik router. My oxidized config file and router.db file are attached.
[config.txt](https://github.com/ytti/oxidized/files/3501078/config.txt)
[router.db.txt](https://github.com/ytti/oxidized/files/3501079/router.db.txt)

**Comment by oldnickru** [comment]
I am not familiar with ruby, so I have tried to make some tests with simple expect script. It seems like adding "+cte" to the username helps a lot with mikrotik's garbage characters (colours, etc) and correct capture of the command line prompt. This option is described here: https://wiki.mikrotik.com/wiki/Manual:Console_login_process#Console_login_options
Nevertheless, it does not solve my problem. Probably it will be of any help for you.

**Comment by oldnickru** [comment]
It seems like this issue was not oxidized related nor net-ssh related. It has been resolved after mikrotik router upgrade from 6.44 to 6.48.
