### ISSUE TITLE
Fortios always changing

### ISSUE THREAD

**Issue by Edzilla2000** [ytti/oxidized#1883]
On fortios (at least on the fortigate that we manage) oxidized stores the configuration every hour believing it has changed.
It seems that it is caused by fortigate changing the encryption key every time the configuration is exported.

I understand that I can remove the secrets with remove_secret, but that makes the configuration file useless for restoring.
Is there a way to instead ignore secrets when comparing versions?

**Comment by davama** [comment]
How does removing secrets make backup useless? 
Manually configuring 1 line/5 lines in a disaster recovery situation  vs 1000 lines makes it useless?

**Comment by Edzilla2000** [comment]
I used the sentence "useless for restoring", not useless in general.
Right now, if I have a dead firewall, I only have to get the last backup, restore it on a spare firewall and it's back up in less than 10 minutes.
If I strip the secrets, the firewall doesn't accept the config file as is. That means I have to replace the missing secrets with nonsense that meet the firewall's required format, and then manually reconfigure each secret in the running firewall. I have never done that and I'm not actually sure it's possible.


So a interesting compromise in my mind would be for the diff to ignore secrets and to only trigger a change when something else changes.

The only limitation that I see with this is that if the password or certificate actually changes then the backup would not reflect it as oxidized would not trigger a change. 
But in my opinion it is better having a backup with some outdated passwords rather than nothing to restore, or having a 31GB backup folder for 170 devices for a year:
![image](https://user-images.githubusercontent.com/5339038/63023889-5c115880-bea6-11e9-9d68-ab928132690f.png)

**Comment by davama** [comment]
One option (not solution for your problem):

If im not mistaken you can increase the time to daily or weekly to mitigate the diff count.

**Comment by Edzilla2000** [comment]
I could do that, but then I might not have an up to date backup, which kinda negates the whole point of having config backups.

**Comment by raunz** [comment]
As FortiOS reencrypts the secrets every time the "show full-configuration" command is executed, I'm also looking for option to save full configuration, when configuration with removed_secret has been altered. I understand, that change of any native secret via cli/ui could be missed, but thats minor side effect.

I looked at hooks, but I could figure out how to achieve the following scenario:
- start off with default remove_secret for fortios and make git commit of remove_secret_conf
- now a real change of config is done on FortiOS device
- oxidized detect that remove_secret config has been changed
- now I would like to commit to git the config before remove_secret (the native full-config with ENC hashes).
- next run would commit to the git a version without ENC hashes and it would be unchanged until next major change of config.

Problem is that the after removing the secrets the initial cfg isn't anymore available. Could this hack be possible to achieve for FortiOS?

Another less "hackish" idea is to a attach a hook with "post_store" which makes a http request oxidized/node/next/_node_ to another Oxidized instance or FortiOS group, which makes a config backup with full hashes only when requested.
I can't add the same Forti node to router.db twice, it could require a second oxidized instance. But still the GIT repo could be the same....

PS: Useful reading about reverse-engineering the ENC values - https://forum.fortinet.com/tm.aspx?m=137961  - the reverse engineering of ENC values Oxidized doesn't seem possible.

**Comment by raunz** [comment]
Here's a working solution (not the prettiest still) to store single full config for every commit with remove_secret config. Hook is executed after post store (actual git change of remove_secret conf), which creates a new temporary node with same name, but different model. The configs with ENC hashes are stored to different location, group directory in git.
Due to https://github.com/ytti/oxidized/issues/1893 there has to be a copy of fortios model with only a name change to get over fortios model default remove_secret: true.

/etc/oxidized/config:
```
hooks:
  fortigatehash:
    type: fortioshook
    events: [post_store]
    group: "fortigates"
    model: "fortiosenc"
models:
  fortios:
    vars:
      remove_secret: true
```
$ diff /var/lib/gems/2.3.0/gems/oxidized-0.26.3/lib/oxidized/model/fortios.rb /etc/oxidized/model/fortiosenc.rb
```
1c1
< class FortiOS < Oxidized::Model
---
> class FortiOSENC < Oxidized::Model
```
$ cat /etc/oxidized/hook/fortioshook.rb
```
class FortiosHook < Oxidized::Hook
  def validate_cfg!
    raise KeyError, 'hook.group is required' unless cfg.has_key?('group')
    raise KeyError, 'hook.model is required' unless cfg.has_key?('model')
  end

  def run_hook(ctx)
    return unless ctx.node
    return unless ctx.event.to_s == "post_store"
    return unless ctx.node.model.class.name.to_s.downcase == "fortios"

    node = Oxidized::Node.new(name: ctx.node.serialize[:name], ip: ctx.node.serialize[:ip], group: cfg.group, model: cfg.model, output: 'git')
    gitoutput = node.output.new

    status, config = node.run

    if status == :success
      msg = "update #{node.group}/#{node.name}"
      msg += " from #{node.from}" if node.from
      msg += " with message '#{node.msg}'" if node.msg

      if gitoutput.store node.name, config, msg: msg, email: node.email, user: node.user, group: node.group
        log "Configuration updated in hook for #{node.group}/#{node.name}"
      end
    end
  end
end
```
With #1893 resolved, we could get rid of fortiosenc model and simplify hook with:
`node = Oxidized::Node.new(name: ctx.node.serialize[:name], ip: ctx.node.serialize[:ip], group: cfg.group, model: cfg.model, output: 'git', vars: { remove_secret: false })`

Sample log:
```
lib/oxidized/worker.rb: Added /fortigate.fw to the job queue
lib/oxidized/job.rb: Starting fetching process for fortigate.fw at 2019-09-02 14:12:26 UTC
lib/oxidized/worker.rb: Jobs running: 1 of 2 - ended: 0 of 3
lib/oxidized/input/ssh.rb: Connecting to fortigate.fw
lib/oxidized/worker.rb: 1 jobs running in parallel
AUTH METHODS::["password"]
lib/oxidized/input/ssh.rb: expecting [/^([-\w.~]+(\s[(\w\-.)]+)?~?\s?[#>$]\s?)$/] at fortigate.fw
lib/oxidized/worker.rb: Jobs running: 1 of 2 - ended: 0 of 3
lib/oxidized/worker.rb: 1 jobs running in parallel
lib/oxidized/input/cli.rb: Running post_login commands at fortigate.fw
lib/oxidized/model/model.rb Collecting commands' outputs
lib/oxidized/model/model.rb Executing get system status
lib/oxidized/input/ssh.rb get system status @ fortigate.fw with expect: /^([-\w.~]+(\s[(\w\-.)]+)?~?\s?[#>$]\s?)$/
lib/oxidized/input/ssh.rb: expecting [/^([-\w.~]+(\s[(\w\-.)]+)?~?\s?[#>$]\s?)$/] at fortigate.fw
lib/oxidized/model/model.rb Executing get hardware status
lib/oxidized/input/ssh.rb get hardware status @ fortigate.fw with expect: /^([-\w.~]+(\s[(\w\-.)]+)?~?\s?[#>$]\s?)$/
lib/oxidized/input/ssh.rb: expecting [/^([-\w.~]+(\s[(\w\-.)]+)?~?\s?[#>$]\s?)$/] at fortigate.fw
lib/oxidized/model/model.rb Executing show full-configuration | grep .
lib/oxidized/input/ssh.rb show full-configuration | grep . @ fortigate.fw with expect: /^([-\w.~]+(\s[(\w\-.)]+)?~?\s?[#>$]\s?)$/
lib/oxidized/input/ssh.rb: expecting [/^([-\w.~]+(\s[(\w\-.)]+)?~?\s?[#>$]\s?)$/] at fortigate.fw
lib/oxidized/worker.rb: Jobs running: 1 of 2 - ended: 0 of 3
lib/oxidized/worker.rb: 1 jobs running in parallel
lib/oxidized/worker.rb: Jobs running: 1 of 2 - ended: 0 of 3
lib/oxidized/worker.rb: 1 jobs running in parallel
lib/oxidized/worker.rb: Jobs running: 1 of 2 - ended: 0 of 3
lib/oxidized/worker.rb: 1 jobs running in parallel
lib/oxidized/input/cli.rb Running pre_logout commands at fortigate.fw
lib/oxidized/input/ssh.rb exit

lib/oxidized/node.rb: Oxidized::SSH ran for fortigate.fw successfully
lib/oxidized/job.rb: Config fetched for fortigate.fw at 2019-09-02 14:12:31 UTC
Configuration updated for /fortigate.fw
resolving DNS for fortigate.fw...
node.rb: resolving node key 'model', with passed global value of '' and node value 'fortiosenc'
node.rb: setting node key 'model' to value 'junos' from global
node.rb: returning node key 'model' with value 'fortiosenc'
lib/oxidized/node.rb: Loading model "fortiosenc"
lib/oxidized/model/model.rb Added all to the commands list
lib/oxidized/model/model.rb Added secret to the commands list
lib/oxidized/model/model.rb Added get system status to the commands list
node.rb: resolving node key 'input', with passed global value of 'ssh, telnet' and node value ''
node.rb: returning node key 'input' with value 'ssh, telnet'
node.rb: resolving node key 'output', with passed global value of 'git' and node value 'git'
node.rb: returning node key 'output' with value 'git'
node.rb: resolving node key 'username', with passed global value of '' and node value ''
lib/oxidized/input/ssh.rb: Connecting to fortigate.fw
AUTH METHODS::["password"]
lib/oxidized/input/ssh.rb: expecting [/^([-\w.~]+(\s[(\w\-.)]+)?~?\s?[#>$]\s?)$/] at fortigate.fw
lib/oxidized/input/cli.rb: Running post_login commands at fortigate.fw
lib/oxidized/model/model.rb Collecting commands' outputs
lib/oxidized/model/model.rb Executing get system status
lib/oxidized/input/ssh.rb get system status @ fortigate.fw with expect: /^([-\w.~]+(\s[(\w\-.)]+)?~?\s?[#>$]\s?)$/
lib/oxidized/input/ssh.rb: expecting [/^([-\w.~]+(\s[(\w\-.)]+)?~?\s?[#>$]\s?)$/] at fortigate.fw
lib/oxidized/model/model.rb Executing get hardware status
lib/oxidized/input/ssh.rb get hardware status @ fortigate.fw with expect: /^([-\w.~]+(\s[(\w\-.)]+)?~?\s?[#>$]\s?)$/
lib/oxidized/input/ssh.rb: expecting [/^([-\w.~]+(\s[(\w\-.)]+)?~?\s?[#>$]\s?)$/] at fortigate.fw
lib/oxidized/model/model.rb Executing show full-configuration | grep .
lib/oxidized/input/ssh.rb show full-configuration | grep . @ fortigate.fw with expect: /^([-\w.~]+(\s[(\w\-.)]+)?~?\s?[#>$]\s?)$/
lib/oxidized/input/ssh.rb: expecting [/^([-\w.~]+(\s[(\w\-.)]+)?~?\s?[#>$]\s?)$/] at fortigate.fw
lib/oxidized/input/cli.rb Running pre_logout commands at fortigate.fw
lib/oxidized/input/ssh.rb exit

lib/oxidized/node.rb: Oxidized::SSH ran for fortigate.fw successfully
FortiosHook: Configuration updated in hook for fortigates/fortigate.fw
lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 1 of 3
```

**Comment by ryanmerolle** [comment]
@davama where would I find:
>If im not mistaken you can increase the time to daily or weekly to mitigate the diff count.

@raunz 
Any thought to a wider solution? I think what you suggested makes sense, we just need a PR with your current approch.

**Comment by Atroskelis** [comment]
This issue is still valid. The code above doesnt seem to work combined with the githubrepo hook which also pushes files via group. Even so, if you store local and push remote, you'll still push the changes every time, which doesnt solve the problem.

One radical overall solution is simply purging the whole git every X months, to save the space.

**Comment by galcorlo** [comment]
Not sure about how to do it but,is it possible to save the configuration only if `conf_file_ver` has changed inside the configuration? This is exactly the same idea @ryanmerolle did with [ansible](https://github.com/fortinet-ansible-dev/ansible-galaxy-fortios-collection/issues/122)

**Comment by raunz** [comment]
In real life there are fortios nodes, which have: conf_file_ver=0  (e.g. Fortigate 30 series).
Software feature and capability differences hit hard on fortigates...

**Comment by p0wertiger** [comment]
Would it be possible to make a separate, additional device entry with full backup but executed only once per week, in addition to regular per-hour-without-secrets?
