### ISSUE TITLE
Aruba A2540

### ISSUE THREAD

**Issue by eltururu** [ytti/oxidized#1884]
I have different devices (Cisco, Dell, Aruba Controllers, Brocade, etc) working in Oxidized except for the Aruba 2540. I have tried using ArubaOS.rb and ProCurve.rb and none of them works. Please assist. 

All of the mentioned brands have the same login process configuration.

**Comment by davama** [comment]
logs?
is a start....

**Comment by eltururu** [comment]
10.22.4.2 raised Oxidized::PromptUndetect with msg "KELL-A2540-001>  not matching configured prompt (?-mix:^\r?([\w\s.-]+# )$)"

**Comment by davama** [comment]
https://rubular.com/r/6pvVNlB1Ozri8J

using current prompt on aruba.rb model?

**Comment by eltururu** [comment]
I am using that string you provided in procurve.rb

**Comment by davama** [comment]
> I am using that string you provided in procurve.rb

and did anything change??

**Comment by eltururu** [comment]
No, same thing.

**Comment by davama** [comment]
have you tried with the latest aruba model?
did you restart the service?
did you update oxidized?
Do you have a banner? (that can cause issues sometimes) 
Have you tried without the banner?
how does it look when a human ssh/telnets into the device?

Details...

**Comment by eltururu** [comment]
have you tried with the latest aruba model? Yes
did you restart the service? Yes
did you update oxidized? Yes
Do you have a banner? (that can cause issues sometimes) Yes, other brands I use have a banner as well. 
Have you tried without the banner? Yes, the following error: 10.22.4.2 raised IOError with msg "closed stream"
how does it look when a human ssh/telnets into the device?

This is the ssh process:

username@mypc:~$ ssh username@10.22.4.2
*********************************************************************
*         Now Entering                       |                                       *
*                                                     |                                        *
*   Unauthorized Use Prohibited    |                                        *
*********************************************************************

username@10.22.4.2's password: 

KELL-A2540-001> en
Password: 
KELL-A2540-001#

**Comment by eltururu** [comment]
Even after removal of banner, I get the following:
10.22.4.2 raised Oxidized::PromptUndetect with msg "KELL-A2540-001>  not matching configured prompt (?-mix:^\r?([\w\s.-]+# )$)"
