### ISSUE TITLE
HPE 5130 EI doesn't match regex

### ISSUE THREAD

**Issue by NatashiaMaxins** [ytti/oxidized#1886]
Device: HPE 5130 EI Switch use Comware 7
login prompt string change from `/^Username:$/` to `/^login:$/`
in cfg.
```
  cfg :telnet do
    username /^Username:$/
    password /^Password:$/
  end
```
I'd tried using `username /^Username:$/|/^login:$/`
But it didn't work.
Please give me some guide to fix it.
Thanks a lot.

**Comment by raunz** [comment]
Try 
  cfg :telnet do
    username /^(Username|login):/
    password /^Password:/
  end

Some newer HPE's (for example MSR954) have a space after login: string.

**Comment by NatashiaMaxins** [comment]
> Try
> cfg :telnet do
> username /^(Username|login):/
> password /^Password:/
> end
> 
> Some newer HPE's (for example MSR954) have a space after login: string.

Thanks for help!
It works:heart:
