### ISSUE TITLE
Oxidized - Adding a new model

### ISSUE THREAD

**Issue by caecaetano** [ytti/oxidized#1888]
Hello all

Can you help me with this issue that I'am having ?

I'am trying to add a new model into Oxidized configuration in order to get a backup configuration of a new switch, which do not have on the default models folder.

I had to create a new dellx_teste.rb for the new switch and then I typed the following commands below hoping that would be enough to make the new model appears on the drop down menu when adding a new switch at the GUI/Web page, but unfortunately It didn't work....

The new *.rb file is in the same folder of the models that I already have.

[root@srv-oxidized model]# git add dellx_teste.rb
[root@srv-oxidized model]# git commit -am 'Added modelo dellx_teste'

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'root@srv-oxidized.(none)')
[root@srv-oxidized model]# git config --global user.email "cae.caetano@domain.com" 
[root@srv-oxidized model]# git config --global user.name "Cae Caetano"           
[root@srv-oxidized model]# git add dellx_teste.rb                                
[root@srv-oxidized model]# git commit -am 'Added modelo dellx_teste'             
[master 6fd2e3d] Added modelo dellx_teste
 4 files changed, 213 insertions(+), 126 deletions(-)
 rewrite lib/oxidized/hook/githubrepo.rb (96%)
 create mode 100644 lib/oxidized/model/dellx_teste.rb
 rewrite lib/oxidized/model/tmos.rb (98%)
[root@srv-oxidized model]# 
[root@srv-oxidized model]# 

![MiissingNewAddedModel](https://user-images.githubusercontent.com/54455782/63623736-c5911580-c5d0-11e9-8ca9-d1abf993e098.JPG)

Any ideas what is missing ?

PS.: I'am beginner on this type of applications, so sorry in advance for any stupid questions....

**Comment by sh0x** [comment]
That looks like a 3rd party Oxidized UI, or a different tool integrated with Oxidized. It doesn't look like Oxidized. Check Oxidized config file to see what models are enabled in the model_map and if that doesn't work look closer into whatever UI you're using there.
