### ISSUE TITLE
Issue starting Oxidized

### ISSUE THREAD

**Issue by millerjr80** [ytti/oxidized#1892]
Hi,

I am getting the following when trying to start oxidized:

undefined method `split' for 0:Integer
```
Traceback (most recent call last):
        19: from /usr/local/bin/oxidized:23:in `<main>'
        18: from /usr/local/bin/oxidized:23:in `load'
        17: from /var/lib/gems/2.5.0/gems/oxidized-0.26.3/bin/oxidized:8:in `<top (required)>'
        16: from /var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/cli.rb:13:in `run'
        15: from /var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/core.rb:4:in `new'
        14: from /var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/core.rb:4:in `new'
        13: from /var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/core.rb:14:in `initialize'
        12: from /var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/core.rb:14:in `new'
        11: from /var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/nodes.rb:125:in `initialize'
        10: from /var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/nodes.rb:10:in `load'
         9: from /var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/nodes.rb:130:in `with_lock'
         8: from /var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/nodes.rb:130:in `synchronize'
         7: from /var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/nodes.rb:15:in `block in load'
         6: from /var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/source/http.rb:23:in `load'
         5: from /var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/source/http.rb:23:in `each'
         4: from /var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/source/http.rb:28:in `block in load'
         3: from /var/lib/gems/2.5.0/gems/asetus-0.3.0/lib/asetus/configstruct.rb:21:in `each'
         2: from /var/lib/gems/2.5.0/gems/asetus-0.3.0/lib/asetus/configstruct.rb:21:in `each'
         1: from /var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/source/http.rb:29:in `block (2 levels) in load'
/var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/source/http.rb:48:in `string_navigate': undefined method `split' for 0:Integer (NoMethodError)
```

Config is as follows:

```
---
username:  
password:  
model: junos
interval: 3600 #interval in seconds
log: ~/.config/oxidized/log
debug: false
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
crash:
 directory: ~/.config/oxidized/crashes
 hostnames: false
groups:
 juniper:
  username:  
  password:  
rest: 127.0.0.1:8888
pid: ~/.config/oxidized/oxidized.pid
output:
 default: git
 file:
 directory: ~/.config/oxidized/configs
input:
 default: ssh, telnet
 debug: false
 ssh:
  secure: false
output:
 default: git
 git:
  user: oxidized
  email:  @routingloops.co.uk
  repo: ~/.config/oxidized/oxidized.git
source:
 default: http
 debug: false
 http:
  url: http://librenms.routingloop.co.uk/api/v0/oxidized
  map:
   name: 0
   model: 1
   group: 1
  headers:
   X-Auth-Token: '01582bf94c03104ecb7953dsadsadwed'
model_map:
 juniper: junos
```

Any help would be appreciated.

**Comment by ytti** [comment]
Your http mapping is incorrect. Correct is something like:

```
        http:
          url: https://librenms/api/v0/oxidized
          map:
            name: hostname
            model: os
            group: group
```

**Comment by millerjr80** [comment]
Hi,

Thanks for your quick response, If I change it to the match your example I get the following:

oxidized@dobby:~$ oxidized -d
no implicit conversion of String into Integer
Traceback (most recent call last):
        21: from /usr/local/bin/oxidized:23:in `<main>'
        20: from /usr/local/bin/oxidized:23:in `load'
        19: from /var/lib/gems/2.5.0/gems/oxidized-0.26.3/bin/oxidized:8:in `<top (required)>'
        18: from /var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/cli.rb:13:in `run'
        17: from /var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/core.rb:4:in `new'
        16: from /var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/core.rb:4:in `new'
        15: from /var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/core.rb:14:in `initialize'
        14: from /var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/core.rb:14:in `new'
        13: from /var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/nodes.rb:125:in `initialize'
        12: from /var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/nodes.rb:10:in `load'
        11: from /var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/nodes.rb:130:in `with_lock'
        10: from /var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/nodes.rb:130:in `synchronize'
         9: from /var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/nodes.rb:15:in `block in load'
         8: from /var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/source/http.rb:23:in `load'
         7: from /var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/source/http.rb:23:in `each'
         6: from /var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/source/http.rb:28:in `block in load'
         5: from /var/lib/gems/2.5.0/gems/asetus-0.3.0/lib/asetus/configstruct.rb:21:in `each'
         4: from /var/lib/gems/2.5.0/gems/asetus-0.3.0/lib/asetus/configstruct.rb:21:in `each'
         3: from /var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/source/http.rb:29:in `block (2 levels) in load'
         2: from /var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/source/http.rb:52:in `string_navigate'
         1: from /var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/source/http.rb:52:in `each'
/var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/source/http.rb:53:in `block in string_navigate': no implicit conversion of String into Integer (TypeError)
oxidized@dobby:~$

**Comment by ytti** [comment]
What is your URL returning, it seems like it is returning array, while it should return object. Potentially  your authentication token is wrong.

**Comment by millerjr80** [comment]
Hi,

Looks like you are right about the authentication token, I get the following from the URL:

{"message":"Unauthenticated."}

Sorry to be a n00b, but how would I go about getting the authentication token correctly configured?

**Comment by ytti** [comment]
I would start by looking at librenms documentation about the matter.
https://docs.librenms.org/Extensions/Oxidized/

**Comment by millerjr80** [comment]
Hi Ytti,

I managed to get it working after creating the api token and adding it to the config. Thanks for your assistance :)
