### ISSUE TITLE
Issue with opengear.rb

### ISSUE THREAD

**Issue by sshmanko** [ytti/oxidized#1899]
I am using oxidized to backup different network devices without any issues.
However after adding new device type - OpenGear (model/opengear.rb), that contains 2 commands:
```
cmd('cat /etc/version') { |cfg| comment cfg }
cmd 'config -g config'
```
only version gets saved to the repo.

When I add a loop over second command:
```
cmd('config -g config') { |cfg| cfg }
```
configuration is correctly saved to the file.

Seems like an easy fix, however I feel I am missing something in my setup.
Please advice how to debug this?

version: oxidized 0.26.3 libssh2 1.9.0, centos6

**Comment by net-eng** [comment]
This also fixed the same issue I am having with opengear.

**Comment by rikard0** [comment]
Nearly 3 years later and still not in fixed :(
