### ISSUE TITLE
PFSense 2.4.4-RELEASE-p3 backup not working with Oxidized

### ISSUE THREAD

**Issue by seederp2p** [ytti/oxidized#1900]
Hi!

So I'm getting this with a freshly installed oxidized instance:

lib/oxidized/input/ssh.rb: Connecting to MYFW.blah.local
AUTH METHODS::["none", "publickey", "password"]
lib/oxidized/input/cli.rb: Running post_login commands at MYFW.blah.local
lib/oxidized/model/model.rb Collecting commands' outputs
lib/oxidized/model/model.rb Executing cat /cf/conf/config.xml
lib/oxidized/input/ssh.rb cat /cf/conf/config.xml @ MYFW.blah.local with expect: /^([\w.@-]+[#>]\s?)$/

I'm using a newly created account on pfsense with admin privileges.
I'm also able to do a manual cat of the XML config file.

Any hint?

**Comment by teintuc** [comment]
Hi,

I have the same problem. After some quick digging, I think it comes from ssh startup menu. 
When you ssh directly, you end up on a menu. You have to type ```8``` to enter shell mode and then type ```cat /cf/conf/config.xml```. 

I think oxidized doesn't handle the "get into shell mode" step.
I'm don't know much about ruby so I have to tinker to make it work.

**Comment by teintuc** [comment]
@seederp2p ok I found in the code you shouldn't be using the admin user.
I made an other user with ssh access and it work fine. See issue #535

**Comment by seederp2p** [comment]
> @seederp2p ok I found in the code you shouldn't be using the admin user.
> I made an other user with ssh access and it work fine. See issue #535

Already tried with a different user with the same results.

**Comment by seederp2p** [comment]
Anyone please? :(

**Comment by FlorianHeigl** [comment]
@seederp2p - use the root user (or, if you know expect a bit and got a few hours, you can detect the menu and press '8' if the menu is present)
