### ISSUE TITLE
Issue with TP-Link T1700G-28TQ

### ISSUE THREAD

**Issue by RomLecat** [ytti/oxidized#1906]
Hello,

I'm currently experiencing some errors with my TP-Link switch.
Oxidized manages to connect to it, but then the second command (show running-config) fails with invalid parameters, which is surprising since it works well when I do the exact same thing by myself.

Here's the debug log:

```
sw-distri-1>enable

sw-distri-1#mypass
------------^
Error: Bad command

sw-distri-1#

sw-distri-1#show system-info
 Master Unit ID       - 1
 System Description   - JetStream 24-Port Gigabit Stackable Smart Switch with 4 10GE SFP+ Slots
 Device Name          - sw-distri-1
 Device Location      - XXXXX
 Contact Information  - XXXXX
 MAC                  - XXXX
 System Time          - 2019-09-18 11:34:53

Device Info
Unit 1
 Unit State                 - Ready
 Hardware Version           - T1700G-28TQ 3.0
 Firmware Version           - 3.0.0 Build 20190108 Rel.62365(s)
 Bootloader Version         - TP-LINK  BOOTUTIL(v1.0.0)
 Serial Number              -
 Running Time               - 76 day - 10 hour - 20 min - 38 sec
 Power Supply Module        - Operational
 Redundant Power Supply     - Not Support


sw-distri-1#show running-config
-----------------^
Error: Invalid parameter.

sw-distri-1#

sw-distri-1#

sw-distri-1#exit

sw-distri-1>logout
```

(It's also trying to input password in a new line, which is not required since in my case enable does not require any password. But this doesn't seem to be the issue there.)

Could you please take a look ? I am willing to run tests you'd like me to.

**Comment by FlorianHeigl** [comment]
@Hakujou the `enable-admin` command is missing here.

```
floh@blackbox:~$ ssh admin@zzz
admin@zzzz's password:

sw01>en

sw01#en
enable-admin        end

sw01#enable-admin
enable-admin

sw01#enable-admin
Password:

sw01#show
show

sw01#show running-config
running-config

sw01#show running-config
!T1700G-28TQRev2
```

(seems this is worked on in #2206)

**Comment by Hakujou** [comment]
It is not needed on mine since I set:
```
aaa authentication login open none
login authentication open
```

I'm already in admin mode when I input enable:
```
ssh sw-distri-1.secure.home.lecat.network

sw-distri-1>enable

sw-distri-1#enable-admin
Already in admin level.
```

**Comment by DerTFL** [comment]
I have the same behavior on the same model.
After adding to the config:
``
aaa enable
``
It passes without an error, so for `enable-admin` to work AAA is needed.
