### ISSUE TITLE
Supermincro mbm-xem-002 "unable to detect prompt: (?-mix:^(.*)[>]((\s?)|(\s+))$)"

### ISSUE THREAD

**Issue by netwops** [ytti/oxidized#1907]
Hello,
I have a problem with switch Supermicro mbm-xem-002.  Don't work model supermicro.rb
My config:
class Supermicrosw < Oxidized::Model
  prompt /^(.*)[>]((\s?)|(\s+))$/
  comment '! '
  cmd :all do |cfg|
    cfg.each_line.to_a[2..-2].join #map{|line|line.delete("\r").rstrip}.join("\n") + "\n"
  end
  cmd 'show running-config'
  cmd 'show system information' do |cfg|
    cfg.gsub! /\s(Up Time).*/, ' \\1 <removed>'
    comment cfg
  end
  cmd 'show version' do |cfg|
    comment cfg
  end
  cmd 'show vlan' do |cfg|
    comment cfg
  end
  cfg :telnet, :ssh do
    post_login 'no cli pagination'
    pre_logout 'exit'
  end
end

**Comment by netengi** [comment]
prompt /^(.*)[>]((\s?)|(\s+))$/
