### ISSUE TITLE
Installation update for ruby dependencies

### ISSUE THREAD

**Issue by gbbromley** [ytti/oxidized#191]
Hi,

For the Installation section of the Github frontpage there is a dependency on ruby net-ssh module to be installed which appears on some platforms not to be installed after installation of ruby/ruby-dev.

Could some information be added to for requirements for SSH support within oxide e.g. gem install net-ssh

**Comment by ytti** [comment]
Not sure I follow:
https://github.com/ytti/oxidized/blob/master/oxidized.gemspec#L19

If 'gem install oxidized' is punched, then net-ssh should be installed. How did you install it?

**Comment by gbbromley** [comment]
Hi,

As per documentation on Ubuntu 15.04 (jessie/sid debian_version)

sudo apt-get install ruby ruby-dev libsqlite3-dev libssl-dev pkg-config cmake
sudo gem install oxdized
sudo gem install oxdized-script oxidized-web

The configure the system to poll some test boxes, enabling debugging for telnet/ssh logs. Noticed SSH logs never populated but telent did. Used oxs script using protocol ssh and user/pass/enable supplied to run 'sh ver' and got
unable to connect
/var/lib/gems/2.1.0/gems/oxidized-script-0.1.1/lib/oxidized/script/script.rb:108:in `connect': unable to connect (Oxidized::Script::NoConnection)
	from /var/lib/gems/2.1.0/gems/oxidized-script-0.1.1/lib/oxidized/script/script.rb:87:in `initialize'
	from /var/lib/gems/2.1.0/gems/oxidized-script-0.1.1/lib/oxidized/script/cli.rb:69:in `new'
	from /var/lib/gems/2.1.0/gems/oxidized-script-0.1.1/lib/oxidized/script/cli.rb:69:in `connect'
	from /var/lib/gems/2.1.0/gems/oxidized-script-0.1.1/lib/oxidized/script/cli.rb:11:in `run'
	from /var/lib/gems/2.1.0/gems/oxidized-script-0.1.1/bin/oxs:5:in `<top (required)>'
	from /usr/local/bin/oxs:23:in `load'
	from /usr/local/bin/oxs:23:in `<main>'

Ran tcpdump which indicated SSH was never used upon oxidized restart and telnet was. Carried out a sudo gem install net-ssh which added missing gem/library and repeated tests and all working again.

**Comment by ytti** [comment]
Strange, that really should have installed net-ssh.

Can you reproduce this in clean machine

gem list
gem install oxidized
gem list

and net-ssh not appearing there?​

On 24 September 2015 at 08:42, gbbromley <notifications@github.com> wrote:

> Hi,
>
> As per documentation on Ubuntu 15.04 (jessie/sid debian_version)
>
> sudo apt-get install ruby ruby-dev libsqlite3-dev libssl-dev pkg-config
> cmake
> sudo gem install oxdized
> sudo gem install oxdized-script oxidized-web
>
> The configure the system to poll some test boxes, enabling debugging for
> telnet/ssh logs. Noticed SSH logs never populated but telent did. Used oxs
> script using protocol ssh and user/pass/enable supplied to run 'sh ver' and
> got
> unable to connect
> /var/lib/gems/2.1.0/gems/oxidized-script-0.1.1/lib/oxidized/script/script.rb:108:in
> connect': unable to connect (Oxidized::Script::NoConnection)
> from
> /var/lib/gems/2.1.0/gems/oxidized-script-0.1.1/lib/oxidized/script/script.rb:87:in
> initialize'
> from
> /var/lib/gems/2.1.0/gems/oxidized-script-0.1.1/lib/oxidized/script/cli.rb:69:in
> new'
> from
> /var/lib/gems/2.1.0/gems/oxidized-script-0.1.1/lib/oxidized/script/cli.rb:69:in
> connect'
> from
> /var/lib/gems/2.1.0/gems/oxidized-script-0.1.1/lib/oxidized/script/cli.rb:11:in
> run'
> from /var/lib/gems/2.1.0/gems/oxidized-script-0.1.1/bin/oxs:5:in'
> from /usr/local/bin/oxs:23:in load'
> from /usr/local/bin/oxs:23:in
> '
>
> Ran tcpdump which indicated SSH was never used upon oxidized restart and
> telnet was. Carried out a sudo gem install net-ssh which added missing
> gem/library and repeated tests and all working again.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ytti/oxidized/issues/191#issuecomment-142967841>.
>



-- 
  ++ytti

**Comment by gbbromley** [comment]
Built on 14.04LTS and 15.04

14.04 appears to install and work without issues:
user@ubbytest:~$ sudo gem install oxidized
Fetching: asetus-0.3.0.gem (100%)
Fetching: slop-3.6.0.gem (100%)
Fetching: net-ssh-2.9.2.gem (100%)
Fetching: rugged-0.23.2.gem (100%)
Building native extensions.  This could take a while...
Fetching: oxidized-0.8.1.gem (100%)
Successfully installed asetus-0.3.0
Successfully installed slop-3.6.0
Successfully installed net-ssh-2.9.2
Successfully installed rugged-0.23.2
Successfully installed oxidized-0.8.1
5 gems installed
Installing ri documentation for asetus-0.3.0...
Installing ri documentation for slop-3.6.0...
Installing ri documentation for net-ssh-2.9.2...
Installing ri documentation for rugged-0.23.2...
Installing ri documentation for oxidized-0.8.1...
Installing RDoc documentation for asetus-0.3.0...
Installing RDoc documentation for slop-3.6.0...
Installing RDoc documentation for net-ssh-2.9.2...
Installing RDoc documentation for rugged-0.23.2...
Installing RDoc documentation for oxidized-0.8.1...
user@ubbytest:~$ sudo gem install oxidized-script oxidized-web
Fetching: oxidized-script-0.1.1.gem (100%)
Successfully installed oxidized-script-0.1.1
Fetching: puma-2.14.0.gem (100%)
Building native extensions.  This could take a while...
Fetching: rack-1.6.4.gem (100%)
Fetching: tilt-2.0.1.gem (100%)
Fetching: rack-protection-1.5.3.gem (100%)
Fetching: sinatra-1.4.6.gem (100%)
Fetching: backports-3.6.6.gem (100%)
Fetching: rack-test-0.6.3.gem (100%)
Fetching: multi_json-1.11.2.gem (100%)
Fetching: sinatra-contrib-1.4.6.gem (100%)
Fetching: haml-4.0.7.gem (100%)

HEADS UP! Haml 4.0 has many improvements, but also has changes that may break
your application:

* Support for Ruby 1.8.6 dropped
* Support for Rails 2 dropped
* Sass filter now always outputs <style> tags
* Data attributes are now hyphenated, not underscored
* html2haml utility moved to the html2haml gem
* Textile and Maruku filters moved to the haml-contrib gem

For more info see:

http://rubydoc.info/github/haml/haml/file/CHANGELOG.md

Fetching: sass-3.4.18.gem (100%)
Fetching: emk-sinatra-url-for-0.2.1.gem (100%)
Fetching: oxidized-web-0.5.1.gem (100%)
Successfully installed puma-2.14.0
Successfully installed rack-1.6.4
Successfully installed tilt-2.0.1
Successfully installed rack-protection-1.5.3
Successfully installed sinatra-1.4.6
Successfully installed backports-3.6.6
Successfully installed rack-test-0.6.3
Successfully installed multi_json-1.11.2
Successfully installed sinatra-contrib-1.4.6
Successfully installed haml-4.0.7
Successfully installed sass-3.4.18
Successfully installed emk-sinatra-url-for-0.2.1
Successfully installed oxidized-web-0.5.1
14 gems installed
Installing ri documentation for oxidized-script-0.1.1...
Installing ri documentation for puma-2.14.0...
Installing ri documentation for rack-1.6.4...
Installing ri documentation for tilt-2.0.1...
Installing ri documentation for rack-protection-1.5.3...
Installing ri documentation for sinatra-1.4.6...
Installing ri documentation for backports-3.6.6...
Installing ri documentation for rack-test-0.6.3...
Installing ri documentation for multi_json-1.11.2...
Installing ri documentation for sinatra-contrib-1.4.6...
Installing ri documentation for haml-4.0.7...
Installing ri documentation for sass-3.4.18...
Installing ri documentation for emk-sinatra-url-for-0.2.1...
Installing ri documentation for oxidized-web-0.5.1...
Installing RDoc documentation for oxidized-script-0.1.1...
Installing RDoc documentation for puma-2.14.0...
Installing RDoc documentation for rack-1.6.4...
Installing RDoc documentation for tilt-2.0.1...
Installing RDoc documentation for rack-protection-1.5.3...
Installing RDoc documentation for sinatra-1.4.6...
Installing RDoc documentation for backports-3.6.6...
Installing RDoc documentation for rack-test-0.6.3...
Installing RDoc documentation for multi_json-1.11.2...
Installing RDoc documentation for sinatra-contrib-1.4.6...
Installing RDoc documentation for haml-4.0.7...
Installing RDoc documentation for sass-3.4.18...
Installing RDoc documentation for emk-sinatra-url-for-0.2.1...
Installing RDoc documentation for oxidized-web-0.5.1...

after editing config file oxs runs using SSH without issues:
oxs -u root -p XXXXXXX -e XXXXXX --protocols ssh -d -v -m powerconnect 10.x.y.z "sh running-config"

15.04 appears to install without issues:
user@ubbytest2:~$ sudo gem install oxidized
Fetching: asetus-0.3.0.gem (100%)
Successfully installed asetus-0.3.0
Fetching: slop-3.6.0.gem (100%)
Successfully installed slop-3.6.0
Fetching: net-ssh-2.10.1.rc2.gem (100%)
Successfully installed net-ssh-2.10.1.rc2
Fetching: rugged-0.23.2.gem (100%)
Building native extensions.  This could take a while...
Successfully installed rugged-0.23.2
Fetching: oxidized-0.8.1.gem (100%)
Successfully installed oxidized-0.8.1
Parsing documentation for asetus-0.3.0
Installing ri documentation for asetus-0.3.0
Parsing documentation for net-ssh-2.10.1.rc2
Installing ri documentation for net-ssh-2.10.1.rc2
Parsing documentation for oxidized-0.8.1
Installing ri documentation for oxidized-0.8.1
Parsing documentation for rugged-0.23.2
Installing ri documentation for rugged-0.23.2
Parsing documentation for slop-3.6.0
Installing ri documentation for slop-3.6.0
Done installing documentation for asetus, net-ssh, oxidized, rugged, slop after 4 seconds
5 gems installed
user@ubbytest2:~$ sudo gem install oxidized-script oxidized-web
Fetching: oxidized-script-0.1.1.gem (100%)
Successfully installed oxidized-script-0.1.1
Parsing documentation for oxidized-script-0.1.1
Installing ri documentation for oxidized-script-0.1.1
Done installing documentation for oxidized-script after 0 seconds
Fetching: puma-2.14.0.gem (100%)
Building native extensions.  This could take a while...
Successfully installed puma-2.14.0
Fetching: rack-1.6.4.gem (100%)
Successfully installed rack-1.6.4
Fetching: rack-protection-1.5.3.gem (100%)
Successfully installed rack-protection-1.5.3
Fetching: tilt-2.0.1.gem (100%)
Successfully installed tilt-2.0.1
Fetching: sinatra-1.4.6.gem (100%)
Successfully installed sinatra-1.4.6
Fetching: multi_json-1.11.2.gem (100%)
Successfully installed multi_json-1.11.2
Fetching: rack-test-0.6.3.gem (100%)
Successfully installed rack-test-0.6.3
Fetching: backports-3.6.6.gem (100%)
Successfully installed backports-3.6.6
Fetching: sinatra-contrib-1.4.6.gem (100%)
Successfully installed sinatra-contrib-1.4.6
Fetching: haml-4.1.0.beta.1.gem (100%)

HEADS UP! Haml 4.0 has many improvements, but also has changes that may break
your application:

* Support for Ruby 1.8.6 dropped
* Support for Rails 2 dropped
* Sass filter now always outputs <style> tags
* Data attributes are now hyphenated, not underscored
* html2haml utility moved to the html2haml gem
* Textile and Maruku filters moved to the haml-contrib gem

For more info see:

http://rubydoc.info/github/haml/haml/file/CHANGELOG.md

Successfully installed haml-4.1.0.beta.1
Fetching: sass-3.4.18.gem (100%)
Successfully installed sass-3.4.18
Fetching: emk-sinatra-url-for-0.2.1.gem (100%)
Successfully installed emk-sinatra-url-for-0.2.1
Fetching: oxidized-web-0.5.1.gem (100%)
Successfully installed oxidized-web-0.5.1
Parsing documentation for backports-3.6.6
Installing ri documentation for backports-3.6.6
Parsing documentation for emk-sinatra-url-for-0.2.1
Installing ri documentation for emk-sinatra-url-for-0.2.1
Parsing documentation for haml-4.1.0.beta.1
Installing ri documentation for haml-4.1.0.beta.1
Parsing documentation for multi_json-1.11.2
Installing ri documentation for multi_json-1.11.2
Parsing documentation for oxidized-web-0.5.1
Installing ri documentation for oxidized-web-0.5.1
Parsing documentation for puma-2.14.0
Installing ri documentation for puma-2.14.0
Parsing documentation for rack-1.6.4
Installing ri documentation for rack-1.6.4
Parsing documentation for rack-protection-1.5.3
Installing ri documentation for rack-protection-1.5.3
Parsing documentation for rack-test-0.6.3
Installing ri documentation for rack-test-0.6.3
Parsing documentation for sass-3.4.18
Installing ri documentation for sass-3.4.18
Parsing documentation for sinatra-1.4.6
Installing ri documentation for sinatra-1.4.6
Parsing documentation for sinatra-contrib-1.4.6
Installing ri documentation for sinatra-contrib-1.4.6
Parsing documentation for tilt-2.0.1
Installing ri documentation for tilt-2.0.1
Done installing documentation for backports, emk-sinatra-url-for, haml, multi_json, oxidized-web, puma, rack, rack-protection, rack-test, sass, sinatra, sinatra-contrib, tilt after 272 seconds
14 gems installed

however the .config/oxidized directory isnt created. After fixing this and editing the config file the running the oxs script it appears to work.

So I guess something specific to my installation :(
