### ISSUE TITLE
ArubaOS 8 prompt not supported since PR #1872

### ISSUE THREAD

**Issue by daffster** [ytti/oxidized#1910]
It appears that PR #1872 broke support for ArubaOS 8.

(myfirewall) *[mynode] #' is what prompt on ArubaOS8 looks like

**Comment by aneeq009** [comment]
prompt for ArubaOS 8: works for mobility master or wireless controller. #2124 more details

https://rubular.com/r/DHHXh79HedCi5t

^([\w\(:.@-]+(\)\s?[\^\*]?\[?\w*\]?\s?)\*?[#>]\s?)$
