### ISSUE TITLE
OpenGear config incomplete

### ISSUE THREAD

**Issue by TSimmonsHJ** [ytti/oxidized#1915]
We are just starting to use Oxidized in our environment and have noticed an issue backing up one of our devices, an OpenGear ACM7008-2-LMR. 

When the backup runs, all we get is:
# OpenGear/ACM700x Version 4.5.0 b9bc8238 -- Fri Apr 26 00:31:07 UTC 2019
and no actual config.
I'm not a ruby dev, but I think I follow what's happening in the OpenGear model:
1) cmd('cat /etc/version') { |cfg| comment cfg }

 2) cmd 'config -g config'

 3) cfg :ssh do
    exec true # don't run shell, run each command in exec channel
  end

(1) cat /etc/version results in the output we get, but it looks like (2) config -g config never runs. That should return the modified portions of the device config. (3) seems to tell it to not log into the device to get a shell, but run the command on the ssh line. That works when I try it manually. 

How can I help troubleshoot this?

**Comment by sshmanko** [comment]
Opened a week ago and have a workaround:
https://github.com/ytti/oxidized/issues/1899

**Comment by TSimmonsHJ** [comment]
> Opened a week ago and have a workaround:
> #1899

Thanks, this workaround works for me as well. Sorry I didn't see it in my search.
