### ISSUE TITLE
ios.rb - Restore NVRAM config timestamp lines to config output

### ISSUE THREAD

**Issue by tyler-8** [ytti/oxidized#1921]
I'd like to have the behavior introduced in commit https://github.com/ytti/oxidized/commit/3599f9048ba3329ba75f6eda29877c905db3931f from https://github.com/ytti/oxidized/pull/1896 reverted.

That is removing critical details of when the config was actually modified on the device as well as the username that did the modification. That seems like a poor choice for default behavior - particularly since those lines have been included for all ios users up til this commit.

#456 contains a workaround that includes a method of _optionally_ ignoring these lines, which would make for a better solution if others want that behavior.

**Comment by davama** [comment]
Referring to these lines?

```
    # Ignore the Last Configuration Change and NVRAM config change
    #since ISE constantly modifies the switches
    if vars :ignore_last_config
       cfg.gsub! /^! Last configuration change at .*/, ''
       cfg.gsub! /^! NVRAM config last updated  .*/, ''
       Oxidized.logger.debug "Ignoring Last Configuration Change line #{node.name} per config variable \'ignore_last_config\'"
    end
```
https://github.com/ytti/oxidized/issues/456#issuecomment-225980372


This is pretty cool!
PR?

**Comment by seros1521** [comment]
Information about the user and the time of modification is not reliable. It is not possible to audit changes based on this information. It changes even if you only enter configuration mode. If a person makes a mistake with the switch, finds an error when he enters the configuration mode and immediately exits, this information will change, and you will consider that the change was made by a completely different person at another time (I hope you will not conduct investigations and make charges based on this information , this is a great opportunity to blame another person). In addition, this information changes only after exiting the configuration mode, and if the session is saved and not leaving the configuration mode, then the date and username will remain old forever. Thus, the only normally working way to track changes is AAA accounting of entered commands. But audit of changes based on an unreliable header in the configuration - this is really "bad practices". Please, do not push other users to this. In addition, this problem exists with the equipment of other vendors, but in their models, the change time/username is simply deleted, even without the ability to change this behavior, so do not forget about the need to ensure consistency in the behavior of models.

If you add an additional parameter to control whether this information will be deleted, then, in my opinion, the default value should provide deletion.

**Comment by ytti** [comment]
Maybe filter when no username?

**Comment by tyler-8** [comment]
@ytti I thought about that too, but that would create a diff anyway, wouldn't it? I think it's all or nothing in this case. Would you be opposed to a PR that adds the new optional flag? I think that's the best solution as it's easy for new users to get their head around, rather than sending them off to create a custom model, and also gives power users that want to remove those lines the same ease of use.

That would look like this:

```
groups:
  ise_switches:
    vars:
      ignore_last_config: true
```

**Comment by raunz** [comment]
> Maybe filter when no username?

`before
! Last configuration change at 13:07:17 UTC Mon Oct 21 2019 by poweruser
! Last configuration change at 13:07:17 UTC Mon Oct 21 2019
! No configuration change since last restart
after`

cfg.each_line.reject { |line| line.match /^! (Last|No) configuration change (at|since).*/ unless line.match /\d+\sby\s\S+$/  }.join

With this block we would keep the last configuration change line, if it contains "by username", providing basic accounting information.
