### ISSUE TITLE
Oxidized crashes (object not found, Rugged::OdbError)

### ISSUE THREAD

**Issue by crazzy** [ytti/oxidized#1928]
Our oxidized installation which has run flawlessly without any issues for over a year has recently started crashing after just a few minutes of runtime. It appears to work correctly, updates configuration for all nodes, and then suddenly without any errors at all in the log (even in debug mode) just crashes.

I tried updating to the latest version using `gem install oxidized` but that didn't solve the issue. Still the same issue. And I guess my inexperience with Ruby is the main reason that I don't understand at all what the crash dump is about.

I cannot share the log, but the one and only message that isn't normal is:

`F, [2019-10-08T14:03:42.745032 #12870] FATAL -- : Oxidized crashed, crashfile written in /home/oxidized/.config/oxidized/crash`

`
2019-10-08 12:03:42 UTC
object not found - no match for id (b2d8e03c7278b1a4ab09486c83fae863ba811c4b) [Rugged::OdbError]

/var/lib/gems/2.3.0/gems/oxidized-0.26.3/lib/oxidized/output/git.rb:182:in 'write_tree'
/var/lib/gems/2.3.0/gems/oxidized-0.26.3/lib/oxidized/output/git.rb:182:in 'update_repo'
/var/lib/gems/2.3.0/gems/oxidized-0.26.3/lib/oxidized/output/git.rb:160:in 'update'
/var/lib/gems/2.3.0/gems/oxidized-0.26.3/lib/oxidized/output/git.rb:57:in 'store'
/var/lib/gems/2.3.0/gems/oxidized-0.26.3/lib/oxidized/worker.rb:65:in 'process_success'
/var/lib/gems/2.3.0/gems/oxidized-0.26.3/lib/oxidized/worker.rb:47:in 'process'
/var/lib/gems/2.3.0/gems/oxidized-0.26.3/lib/oxidized/worker.rb:16:in 'block in work'
/var/lib/gems/2.3.0/gems/oxidized-0.26.3/lib/oxidized/worker.rb:16:in 'each'
/var/lib/gems/2.3.0/gems/oxidized-0.26.3/lib/oxidized/worker.rb:16:in 'work'
/var/lib/gems/2.3.0/gems/oxidized-0.26.3/lib/oxidized/core.rb:36:in 'run'
/var/lib/gems/2.3.0/gems/oxidized-0.26.3/lib/oxidized/core.rb:29:in 'initialize'
/var/lib/gems/2.3.0/gems/oxidized-0.26.3/lib/oxidized/core.rb:4:in 'new'
/var/lib/gems/2.3.0/gems/oxidized-0.26.3/lib/oxidized/core.rb:4:in 'new'
/var/lib/gems/2.3.0/gems/oxidized-0.26.3/lib/oxidized/cli.rb:13:in 'run'
/var/lib/gems/2.3.0/gems/oxidized-0.26.3/bin/oxidized:8:in '<top (required)>'
/usr/local/bin/oxidized:23:in 'load'
/usr/local/bin/oxidized:23:in '&lt;main&gt;'
`

(Can't get the code tags to work properly here for some reason, even after replacing the quote-style in the crashdump)

Any help what so ever with troubleshooting this would be much appreciated. I don't even know where to begin to troubleshoot this one.

For one, what does a "Rugged::OdbError" mean? And what kind of object is the ID about?

**Comment by alex67** [comment]
Good morning,

I'm also having a similar issue.

2020-02-04 15:50:21 UTC
object not found - no match for id (72e1565633463d5b0db828a690dcc587f31e365a) [Rugged::OdbError]
--------------------------------------------------
/usr/local/share/gems/gems/oxidized-0.24.0/lib/oxidized/output/git.rb:184:in `target'
/usr/local/share/gems/gems/oxidized-0.24.0/lib/oxidized/output/git.rb:184:in `update_repo'
/usr/local/share/gems/gems/oxidized-0.24.0/lib/oxidized/output/git.rb:170:in `update'
/usr/local/share/gems/gems/oxidized-0.24.0/lib/oxidized/output/git.rb:57:in `store'
/usr/local/share/gems/gems/oxidized-0.24.0/lib/oxidized/worker.rb:54:in `process'
/usr/local/share/gems/gems/oxidized-0.24.0/lib/oxidized/worker.rb:16:in `block in work'
/usr/local/share/gems/gems/oxidized-0.24.0/lib/oxidized/worker.rb:16:in `each'
/usr/local/share/gems/gems/oxidized-0.24.0/lib/oxidized/worker.rb:16:in `work'
/usr/local/share/gems/gems/oxidized-0.24.0/lib/oxidized/core.rb:36:in `run'
/usr/local/share/gems/gems/oxidized-0.24.0/lib/oxidized/core.rb:28:in `initialize'
/usr/local/share/gems/gems/oxidized-0.24.0/lib/oxidized/core.rb:4:in `new'
/usr/local/share/gems/gems/oxidized-0.24.0/lib/oxidized/core.rb:4:in `new'
/usr/local/share/gems/gems/oxidized-0.24.0/lib/oxidized/cli.rb:12:in `run'
/usr/local/share/gems/gems/oxidized-0.24.0/bin/oxidized:8:in `<top (required)>'
/usr/local/bin/oxidized:23:in `load'
/usr/local/bin/oxidized:23:in `<main>'
--------------------------------------------------

This started happening after an upgrade of oxidized.
Anyone got any idea how to resolve it?

**Comment by davama** [comment]
We've had something similar in the past:

```
2020-01-16 17:29:21 UTC
failed to insert entry: invalid object specified - jpn-ser-1er-sw-1 [Rugged::TreeError]
```
Had to do with corrupt git repo. See [link](https://howto.lintel.in/fix-git-object-file-empty-error/)

Rundown of what I did to test:

•	Created a copy of the my_repo.git  folder
```
cd oxidized
cp -rp my_repo.git my_repo_test.git
cd my_repo_test.git
```

•	Ran some git magic  (see link )
```
git fsck --full
git --work-tree=/home/config/oxidized/my_repo_test.git reset
git --work-tree=/home/config/oxidized/my_repo_test.git status 
```
•	Backup my_repo.git 
```
cp -rp my_repo.git  my_repo_backup.git
```
•	Stop oxidized
```
systemctl stop oxidized
rm -rf my_repo.git 
mv my_repo_test.git my_repo.git 
```
•	Restart oxidized
```
systemctl restart oxidized
```
•	Query the oxidized api to backup a device in my_repo group
```
curl -X GET http://127.0.0.1:9002/oxidized/node/next/my_repo/my_device
```

That's it!

Not sure if it work for you guys but the error looks similar.

**Comment by skumarmallampeta** [comment]
Hi All, I am running into a similar issue and not able to troubleshoot the issue, can you anyone please let me know the right way to resolve the issue as our current backup solution is broken.

object not found - no match for id (8f1cb139d550877796dc2043fee28f81ee6e5668) [Rugged::OdbError]
--------------------------------------------------
/var/local/opt/rh/rh-ruby25/root/usr/local/share/gems/gems/oxidized-0.26.3/lib/oxidized/output/git.rb:184:in `target'
/var/local/opt/rh/rh-ruby25/root/usr/local/share/gems/gems/oxidized-0.26.3/lib/oxidized/output/git.rb:184:in `update_repo'
/var/local/opt/rh/rh-ruby25/root/usr/local/share/gems/gems/oxidized-0.26.3/lib/oxidized/output/git.rb:160:in `update'
/var/local/opt/rh/rh-ruby25/root/usr/local/share/gems/gems/oxidized-0.26.3/lib/oxidized/output/git.rb:57:in `store'
/var/local/opt/rh/rh-ruby25/root/usr/local/share/gems/gems/oxidized-0.26.3/lib/oxidized/worker.rb:65:in `process_success'
/var/local/opt/rh/rh-ruby25/root/usr/local/share/gems/gems/oxidized-0.26.3/lib/oxidized/worker.rb:47:in `process'
/var/local/opt/rh/rh-ruby25/root/usr/local/share/gems/gems/oxidized-0.26.3/lib/oxidized/worker.rb:16:in `block in work'
/var/local/opt/rh/rh-ruby25/root/usr/local/share/gems/gems/oxidized-0.26.3/lib/oxidized/worker.rb:16:in `each'
/var/local/opt/rh/rh-ruby25/root/usr/local/share/gems/gems/oxidized-0.26.3/lib/oxidized/worker.rb:16:in `work'
/var/local/opt/rh/rh-ruby25/root/usr/local/share/gems/gems/oxidized-0.26.3/lib/oxidized/core.rb:36:in `run'
/var/local/opt/rh/rh-ruby25/root/usr/local/share/gems/gems/oxidized-0.26.3/lib/oxidized/core.rb:29:in `initialize'
/var/local/opt/rh/rh-ruby25/root/usr/local/share/gems/gems/oxidized-0.26.3/lib/oxidized/core.rb:4:in `new'
/var/local/opt/rh/rh-ruby25/root/usr/local/share/gems/gems/oxidized-0.26.3/lib/oxidized/core.rb:4:in `new'
/var/local/opt/rh/rh-ruby25/root/usr/local/share/gems/gems/oxidized-0.26.3/lib/oxidized/cli.rb:13:in `run'
/opt/rh/rh-ruby25/root/usr/local/share/gems/gems/oxidized-0.26.3/bin/oxidized:8:in `<top (required)>'
/opt/rh/rh-ruby25/root/usr/local/bin/oxidized:23:in `load'
/opt/rh/rh-ruby25/root/usr/local/bin/oxidized:23:in `<main>'
