### ISSUE TITLE
Oxidized crashes every other day with "Bus Error at ..."

### ISSUE THREAD

**Issue by fknorn** [ytti/oxidized#1932]
Hi,

I'm not sure why, but oxidized keeps randomly crashing every other day or so...

The crash starts with

```
Oct  9 21:01:02 itk-confbckp-01 oxidized[17266]: /var/lib/gems/2.5.0/gems/rugged-0.28.2/lib/rugged/repository.rb:243: [BUG] Bus Error at 0x00007f587b3f7028
```

Any clues?

**Comment by ytti** [comment]
No clues, you might want to ask at rugged issues. Perhaps kernel issue, perhaps bad hardware, perhaps rugged issue.
