### ISSUE TITLE
FAQ Page

### ISSUE THREAD

**Issue by ytti** [ytti/oxidized#1933]
We need FAQ page. 

One really common, is partial output captured etc. Which is almost always caused by prompt detection issue, either too relaxed prompt regexp or desync when we produce prompt but we don't consume it: https://github.com/ytti/oxidized/issues/1854

What else? We're missing example how to make _NEW_ model, simplest possible, we have example how and where to do modified models.

**Comment by davama** [comment]
my .02 cents:

many times there are complaints of false diffs because of some date/power/etc change.
Perhaps help understand how to use/test the `cfg.gsub!` line?
But maybe this is part of the model extension....

**Comment by wk** [comment]
It's not entirely obvious which elements belong in the model development guide, which in the FAQ, and which in a troubleshooting section (if one is not the FAQ), but having a FAQ seems sensible. I've drafted a basic variant with the issues raised by @ytti. Follow-on additions and corrections in the form of PRs are, of course, welcome.
