### ISSUE TITLE
Possibility to download backup files

### ISSUE THREAD

**Issue by tcastelle** [ytti/oxidized#1944]
This feature request is related to Issue #582 

We are looking to replace our Commercial backup product (Backbox) with oxidized which seems to be a really good product. However, it seems to rely exclusively on text configuration.

The main goal of a backup tool is to be able to restore a configuration in a quick and efficient way.
For a F5 BIGIP, the simpliest way to restore a configuration is to use what they call UCS or SCF files.
Same thing for other devices (Checkpoint Firewalls, for instance), or even for ASA Firewalls...

Those files can be generated through a command on the device, but then I don't know how to download these files on the backup server.

Maybe through a special hook that downloads the file with SCP ? Or through executing a command on the device which sends the file to the backup server on a specific directory in FTP or SCP ?

However, this does not seem to be possible with the current version of oxidized, so I open this issue as a feature request.

Regards,

Thomas

**Comment by locki-cz** [comment]
No any plans add this to some future release? Backup some custom files from remote linux server sound nice to have!

**Comment by jameskirsop** [comment]
This is also relevant for Ruckus SmartZone backups which are delivered via HTTP(s) as Gzip'd binary blobs.

I have a python script that can login over HTTPS and download the file, but I'm yet to come up with a way of getting the downloaded binary data into Oxidized.
