### ISSUE TITLE
Oxidized 0.2.7 oxidized script

### ISSUE THREAD

**Issue by sajiby3k** [ytti/oxidized#1954]
Hi,

Tried to install oxidized 2.7.0 today.

Very strange behaviour with oxidized-script.

Oxidized-script installs automatically version 0.26.3 because of dependency.

So we have two versions of oxidized installed.

Can the developer look at it? So, that oxidized-script also updated accordingly.

Thanks.

**Comment by ytti** [comment]
This is because CLI command line parser library version, I should upgrade the one in oxidized-script, but won't have time soon, earliest end of next month.

**Comment by sajiby3k** [comment]
Any ålan to update the script works with new version 0.28????

**Comment by ytti** [comment]
Yeah but dunno when, it only needs to adapted to newer Slop version for CLI parsing. I've not looked how much work it is, but it's less than nothing, as it's rather dynamic how we generate CLI options.

**Comment by mortzu** [comment]
Its fixed in master. Needs a release @ytti
