### ISSUE TITLE
Oxidized v.0.26.3 Web GUI "Last Changed" 

### ISSUE THREAD

**Issue by peterbanaszek** [ytti/oxidized#1955]
Hello all,

I've installed Oxidized on a CentOS 7 VM. I've been running backups once daily and I've noticed after a recent restart of the server the "Last Changed" column sets to unknown. We can still access the previous versions of the configs but from a glance it makes it difficult to determine how long ago a switch config was changed.

I've attached a screenshot which shows a few switches that were recently changed after the reset and the others which have set to unknown as a result of the reset. 

If this is default behavior I apologize and you can close out the issue.

![Capture](https://user-images.githubusercontent.com/16416318/67972016-3c0b4e80-fbe4-11e9-92f2-fdef1ec60dbc.PNG)

**Comment by ytti** [comment]
We don't store stats across restarts, so we don't know when the config has changed, as it's earlier than current runtime.

We of course should, there is issue about things that should be refactored, but I currently don't have any concrete plans on fixing that.

**Comment by peterbanaszek** [comment]
Okay that makes sense. Thank you for your feedback.

**Comment by tmonsores** [comment]
This is a simple fix, just get the value "date of version" from the last stored version. This information is not lost across server reboots.

<img width="486" alt="Screen Shot 2021-01-12 at 17 43 47" src="https://user-images.githubusercontent.com/13514961/104370841-3276b980-54fe-11eb-8aef-45525fb09e23.png">

**Comment by chuache86** [comment]
> This is a simple fix, just get the value "date of version" from the last stored version. This information is not lost across server reboots.
> 
> <img alt="Screen Shot 2021-01-12 at 17 43 47" width="486" src="https://user-images.githubusercontent.com/13514961/104370841-3276b980-54fe-11eb-8aef-45525fb09e23.png">

Hello @tmonsores 

Could you tell me how I should add that value in the oxidized server? In which file exactly should I modify it?
Thanks.

**Comment by mortzu** [comment]
Its an oxidized-web bug. Please open issue in the correct project
