### ISSUE TITLE
Issue with AOS7 specific type

### ISSUE THREAD

**Issue by optimuscream** [ytti/oxidized#1959]
Hello,

For this device :

Alcatel-Lucent Enterprise OS6900-X72 8.5.196.R04 GA, February 25, 2019 ---> aos7 model

I have to make adjustment to 

`lib/oxidized/model/aos7.rb`

in line 

`username /^login : /   `

to 

`username /^([\w -])*login: /`

Because login prompt is like this, machine name example (OS6900X72-MACHINE)

`OS6900X72-MACHINE login:`

Just for your information. 
And then it works.
This is an issue and also the solution.

Thanks

**Comment by davama** [comment]
You can submit a PR
