### ISSUE TITLE
poor error handling if debug log is not writable

### ISSUE THREAD

**Issue by nickhilliard** [ytti/oxidized#196]

**Comment by nickhilliard** [comment]
The error handling for debug log opening is messed up.  Instead of returning fail up the stack, it should either die or else warn on STDERR that it cannot open the debug log file for writing.  At the moment, it simply returns fail up the stack which is trapped by "Oxidized::Script" as "unable to connect".  This is completely misleading about the root cause of the problem. 

```
# chown rancid /tmp/oxidized.log-*
# ls -la /tmp/oxidized.log-*
-rw-r--r--  1 rancid  wheel   843 26 Sep 13:17 /tmp/oxidized.log-ssh
-rw-r--r--  1 rancid  wheel  1600 26 Sep 13:13 /tmp/oxidized.log-telnet
# su - oxidized
$ oxs switchname 'show version'
unable to connect
/usr/local/lib/ruby/gems/2.1/gems/oxidized-script-0.1.1/lib/oxidized/script/script.rb:108:in `connect': unable to connect (Oxidized::Script::NoConnection)
	from /usr/local/lib/ruby/gems/2.1/gems/oxidized-script-0.1.1/lib/oxidized/script/script.rb:87:in `initialize'
	from /usr/local/lib/ruby/gems/2.1/gems/oxidized-script-0.1.1/lib/oxidized/script/cli.rb:69:in `new'
	from /usr/local/lib/ruby/gems/2.1/gems/oxidized-script-0.1.1/lib/oxidized/script/cli.rb:69:in `connect'
	from /usr/local/lib/ruby/gems/2.1/gems/oxidized-script-0.1.1/lib/oxidized/script/cli.rb:11:in `run'
	from /usr/local/lib/ruby/gems/2.1/gems/oxidized-script-0.1.1/bin/oxs:5:in `<top (required)>'
	from /usr/local/bin/oxs:23:in `load'
	from /usr/local/bin/oxs:23:in `<main>'
$ ^D
# chown oxidized  /tmp/oxidized.log-*
# su - oxidized
$ ls -la /tmp/oxidized.log-*
-rw-r--r--  1 oxidized  wheel   843 Sep 26 13:17 /tmp/oxidized.log-ssh
-rw-r--r--  1 oxidized  wheel  1600 Sep 26 13:13 /tmp/oxidized.log-telnet
$ oxs switchname 'show version'
Switch      : 800546-00-06 yyyyy-xxxxx Rev 6.0 BootROM: xxxx    IMG: 15.x.x.x
PSU-1       : Internal PSU-1 800462-00-06 yyyyy-xxxxx
PSU-2       : Internal PSU-2 800462-00-04 yyyyy-xxxxx

Image   : ExtremeXOS version 15.x.x.x v15xxxx by release-manager
BootROM : x.x
Diagnostics : x.x
$
```

**Comment by ytti** [comment]
This should more appropriately have been opened on oxidized-script repo.

Problem is here:
https://github.com/ytti/oxidized-script/blob/master/lib/oxidized/script/script.rb#L109

We do store the original error class, error message and backtrace, but do not expose it. It's stored here:
https://github.com/ytti/oxidized-script/blob/master/lib/oxidized/script/script.rb#L103

error being the object, having various method such as
error.class = class that was raised
error.message = human readable short error message
error.backtrace = full backtrace of error raised

This error message is even attached to the raised error, so library user of oxidized-script can access all of the error messages, use case such as

def blaah
  @oxs.cmd 'pim'
rescue => error
  error.message # what did oxidized-script say about the failure?
  error.node_error[:telnet],messge # what did telnet say about the failure?
  error.node_error[:ssh].message    # what did ssh say about the failure?
end

Unsure what we should expose on the CLI.
