### ISSUE TITLE
Oxidized not pushing to Git

### ISSUE THREAD

**Issue by tdentafix** [ytti/oxidized#1962]
Hello,

I have modified the ruby model to match a new CLI format for an existing node in Oxidized.
The prompt regex matches and the output in the file "log-IP-ssh" looks good (e.g. we have the information we want).

In oxidized general log we can read :
```
D, [2019-11-06T18:13:55.301217 #3752] DEBUG -- : SSH: environment more false @ sr-2s-lab.lab
D, [2019-11-06T18:13:56.040706 #3752] DEBUG -- : SSH: admin show configuration @ sr-2s-lab.lab
D, [2019-11-06T18:14:08.768456 #3752] DEBUG -- : SSH: logout @ sr-2s-lab.lab
I, [2019-11-06T18:14:09.397461 #3752]  INFO -- : GithubRepo: Pushing local repository(/srv/oxidized.git/)...
I, [2019-11-06T18:14:09.397849 #3752]  INFO -- : GithubRepo: to remote: git@gitlab.blahblah.net:team/oxidized.git
D, [2019-11-06T18:14:10.041942 #3752] DEBUG -- : GithubRepo: {:total_objects=>0, :indexed_objects=>0, :received_objects=>0, :local_objects=>0, :total_deltas=>0, :indexed_deltas=>0, :received_bytes=>0}
D, [2019-11-06T18:14:10.042086 #3752] DEBUG -- : GithubRepo: nothing recieved after fetch
```

The device show as green in the GUI, but the Git repository stays desperately stuck with the old versions of the config, before the CLI change, meaning nothing is committed by oxidized.

I am out of ideas, any help will really be appreciated !

Thanks in advance !

**Comment by brunonetadmin** [comment]
I´m facing the same problem. No errors. The SSH and GIT its ok. But it not found any changes and dont start my repo and put my configuration of equipments there.
