### ISSUE TITLE
Switch to 'enable' mode for Arista EOS

### ISSUE THREAD

**Issue by ngen-brett** [ytti/oxidized#1969]
In my case, the RADIUS AVP's don't put the switch into 'enable' mode by default (as they do on Cisco). 

I've added an 'enable' command to the eos model.

**Comment by wk** [comment]
You can set the 'enable' field in your node configuration to 'True', which will cause the `arista.rb` model to send the string 'enable' without a password. See line 36 in the `arista.rb` model.
