### ISSUE TITLE
Disable password removal

### ISSUE THREAD

**Issue by ognjen011** [ytti/oxidized#1976]
Hello 

In my config for oxidized i have set remove_secret: false but for some reason passwords are still being removed. In junos.rb i have commented out the whole section:

 #cmd :secret do |cfg|
    #cfg.gsub!(/community (\S+) {/, 'community <hidden> {')
    #cfg.gsub!(/ "\$\d\$\S+; ## SECRET-DATA/, ' <secret removed>;')
  #  cfg
  #end

But the passwords are missing from the configs. Same thing for routeros i remove the line 

run_cmd = vars(:remove_secret) ? '/export hide-sensitive' : '/export'

Can someone help me out with this? Having a config without this is not that useful because it's almost impossible to restore without problems.

**Comment by YoannQueret** [comment]
On the last routerOS version 6.xx.x `/export show-sensitive` don't exist. To retreive all password you just need to use `/export`

**Comment by mortzu** [comment]
and its fixed in master: https://github.com/ytti/oxidized/blob/master/lib/oxidized/model/routeros.rb#L31
