### ISSUE TITLE
Config loader does not honor OXIDIZED_HOME

### ISSUE THREAD

**Issue by cfiske** [ytti/oxidized#1977]
Although Config::Root is correctly set to `$OXIDIZED_HOME` when it exists, the config file is not read from this location. Oxidized will only find a config in either `/etc/oxidized/config` or `$HOME/.config/oxidized/config` (which I believe is due to [Asetus](https://github.com/ytti/asetus) only looking in those locations).

Expected behavior is that setting `OXIDIZED_HOME` would cause the config to be read from there, as indicated by the [documentation](https://github.com/ytti/oxidized/blob/master/docs/Configuration.md):

> OXIDIZED_HOME may be used to set oxidized configuration directory, which defaults to ~/.config/oxidized

**Comment by mortzu** [comment]
Please provide a PR
