### ISSUE TITLE
SSH Read Buffer / Very slow download

### ISSUE THREAD

**Issue by tcastelle** [ytti/oxidized#1979]
Hello,

I am trying to use oxidized to backup a database with mysqldump. It works, however the database is quite big (around 100Mo) and oxidized is very very slow to download SQL Dump... it reaches timeout each time.

Debug shows that data is read by small chunks of 8ko or less :

D, [2019-12-03T16:52:03.104172 #68306] DEBUG -- : lib/oxidized/model/model.rb Executing mysqldump -u root  --password=**** newCMDB
D, [2019-12-03T16:52:03.104278 #68306] DEBUG -- : lib/oxidized/input/ssh.rb mysqldump -u root  --password=**** newCMDB @ bddpardi with expect: /^(\w.*|\W.*)(\$|#) /
D, [2019-12-03T16:52:03.104421 #68306] DEBUG -- socket[1eedbd4]: queueing packet nr 12 type 94 len 76
D, [2019-12-03T16:52:03.104490 #68306] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^(\w.*|\W.*)(\$|#) /] at bddpardi
D, [2019-12-03T16:52:03.305110 #68306] DEBUG -- socket[1eedbd4]: sent 144 bytes
D, [2019-12-03T16:52:03.405507 #68306] DEBUG -- socket[1eedbd4]: read 8192 bytes
D, [2019-12-03T16:52:03.405695 #68306] DEBUG -- socket[1eedbd4]: received packet nr 19 type 94 len 76
I, [2019-12-03T16:52:03.405801 #68306]  INFO -- net.ssh.connection.session[1ece0b8]: channel_data: 0 49b
D, [2019-12-03T16:52:03.406072 #68306] DEBUG -- socket[1eedbd4]: received packet nr 20 type 94 len 844
I, [2019-12-03T16:52:03.406203 #68306]  INFO -- net.ssh.connection.session[1ece0b8]: channel_data: 0 818b
D, [2019-12-03T16:52:03.406475 #68306] DEBUG -- socket[1eedbd4]: received packet nr 21 type 94 len 812
I, [2019-12-03T16:52:03.406583 #68306]  INFO -- net.ssh.connection.session[1ece0b8]: channel_data: 0 795b
D, [2019-12-03T16:52:03.406739 #68306] DEBUG -- socket[1eedbd4]: received packet nr 22 type 94 len 76
I, [2019-12-03T16:52:03.406817 #68306]  INFO -- net.ssh.connection.session[1ece0b8]: channel_data: 0 56b
D, [2019-12-03T16:52:03.407062 #68306] DEBUG -- socket[1eedbd4]: received packet nr 23 type 94 len 4124
I, [2019-12-03T16:52:03.407171 #68306]  INFO -- net.ssh.connection.session[1ece0b8]: channel_data: 0 4095b
D, [2019-12-03T16:52:03.407405 #68306] DEBUG -- socket[1eedbd4]: read 8192 bytes
D, [2019-12-03T16:52:03.407634 #68306] DEBUG -- socket[1eedbd4]: received packet nr 24 type 94 len 3948
I, [2019-12-03T16:52:03.407711 #68306]  INFO -- net.ssh.connection.session[1ece0b8]: channel_data: 0 3934b
D, [2019-12-03T16:52:03.408039 #68306] DEBUG -- socket[1eedbd4]: received packet nr 25 type 94 len 4124
I, [2019-12-03T16:52:03.408127 #68306]  INFO -- net.ssh.connection.session[1ece0b8]: channel_data: 0 4095b
D, [2019-12-03T16:52:03.408387 #68306] DEBUG -- socket[1eedbd4]: read 8192 bytes
D, [2019-12-03T16:52:03.408603 #68306] DEBUG -- socket[1eedbd4]: received packet nr 26 type 94 len 3356
I, [2019-12-03T16:52:03.408680 #68306]  INFO -- net.ssh.connection.session[1ece0b8]: channel_data: 0 3329b

Is it a read buffer configuration issue ? Is there a parameter we can use ?

My model is as follow :

class MariaDB < Oxidized::Model
  prompt /^(\w.*|\W.*)(\$|#) /
  comment '# '

  cmd :all do |cfg|
    cfg.cut_both
  end

  pre do
    bdduser = vars(:bddusername)
    bddpasswd = vars(:bddpassword)
    bddname = vars(:bddname)
    cfg = cmd "mysqldump -u #{bdduser}  --password=#{bddpasswd} #{bddname}"
    cfg
  end

  cfg :ssh do
    post_login do
      if vars(:enable) == true
        cmd "sudo su -", /^\[sudo\] password/
        cmd @node.auth[:password]
      elsif vars(:enable)
        cmd "su -", /^Password:/
        cmd vars(:enable)
      end
    end

    pre_logout do
      cmd "exit" if vars(:enable)
    end
    pre_logout 'exit'
  end
end

Regards,

Thomas

**Comment by mortzu** [comment]
Can you please reformat your paste to make it readable? (https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code)
