### ISSUE TITLE
SSH Proxy Password (Feature request)

### ISSUE THREAD

**Issue by Daemonslayer2048** [ytti/oxidized#1982]
Reading over the docs it appears ssh_proxy does not support a username and password field.

![Proxy Docs](https://github.com/ytti/oxidized/blob/master/docs/Configuration.md#ssh-proxy-command)

Possible offending code?
https://github.com/ytti/oxidized/blob/35bbc62c917a03710140d53108da0a9484b2c3a7/lib/oxidized/input/ssh.rb#L137-L146

I guess my question is why not, I have never written a line of ruby so I assume there is a reason. Would this be difficult to implement? I think it would be a significant improvement/feature and would love to help if I can. I understand this can be worked around by using an ssh config for the proxy host, but that does not seem as clean.

**Comment by ggiesen** [comment]
I'm with Daemonslayer2048. I just started testing Oxidized and ran into this problem, and unfortunately lack of separate credentials for the proxy is a non-starter for me (virtually all of my hosts are accessed through dozens of different proxies).

Ideally a list of proxies would be defined once (along with creds, port, etc) and then referenced by the node, but I could live with defining it each time per node as long as it supported separate credentials.

**Comment by Daemonslayer2048** [comment]
> Ideally a list of proxies would be defined once (along with creds, port, etc) and then referenced by the node, but I could live with defining it each time per node as long as it supported separate credentials.
Couldn't agree with this more. Again, no ruby expert but I have been using a sqlite db to store my devices. I am working on a new python based API and think if I can get that off the ground maybe I can try and learn some ruby and get the proxy feature in here. Oxidized is freaking awesome but yeah it needs a more active community and maintainers (new ones, or help or the current ones).

**Comment by MrMarioMichel** [comment]
I would love to see separate credentials at ssh proxys. I will talk to my resources I have maybe someone can help here.
