### ISSUE TITLE
Group interval

### ISSUE THREAD

**Issue by MTkatchouk** [ytti/oxidized#1985]
Hey. I use oxidized in different projects with different types of equipment. Some devices change configuration often, while others do not change configuration for months. Unfortunately oxidized does not allow you to set the interval on the group. This can significantly increase the information content of the configuration.
Here is how I see it:
---
interval: 1800
groups:
   Cisco:
     model: ios
     interval: 300
   CiscoSMB:
     model: ciscosmb
     interval: 3600
   Mikrotik:
     username: admin
     interval: 86400

**Comment by gpavinteractiv** [comment]
I am interested in this feature request too

**Comment by from88** [comment]
any news on this ? I came to this problem also.

**Comment by mortzu** [comment]
Can you please reformat your paste to make it readable? (https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code)

**Comment by berilslv** [comment]
Is it possible to set custom intervals for groups/models ?
Maybe someone have other solution how to divide timings?
