### ISSUE TITLE
Add support for MS Teams hooks

### ISSUE THREAD

**Issue by robinostlund** [ytti/oxidized#1987]
Hi, it would be helping us if it would be possible to add support for MS Teams so we could get notified if a node fails and so on.

**Comment by systeembeheerder** [comment]
Each Channel in teams has an email address. Oxidized has already email hooks. This combination works fine.

**Comment by usscarter** [comment]
As a stopgap it may work okay, but it is not as good as an actual functioning hook for teams would be. The slack plugin for instance is pretty great in that it includes diff coloring, etc. The emails that flow from teams are not that useful, as they are presented simply as view original emails for us, and dont seem to want to expand to present full information.

**Comment by rp2019433** [comment]
> Hi, it would be helping us if it would be possible to add support for MS Teams so we could get notified if a node fails and so on.

I agree with robinostlund. Would be great if we had this integration with MS Teams using web hook.

**Comment by djh00t** [comment]
Pls to be Teams integration.

**Comment by stribnet** [comment]
This would be a great add on to oxidized.

**Comment by dschwarz2011** [comment]
Has there been any traction on posting oxidized git diffs to MS teams?

**Comment by kziame175** [comment]
I'm very interested in this too.
