### ISSUE TITLE
Suggested fix for "ios.rb" broken enable password handling?

### ISSUE THREAD

**Issue by matt-watkins-1976** [ytti/oxidized#1988]
Hi,

I've encountered what I think might be a bug in the oxidized "ios.rb" script. We have a large network with several sites where equipment is configured and managed by different teams. The AAA setup and CiscoSecure ACS/TACACS+ configuration varies between devices. Some routers go straight to privilege 15 and don't require an enable password, some have the usual behaviour and need one to be supplied. Basically, we need to have the enable password defined as a field in the oxidized database, but not all devices need the enable command to actually be sent. It seems the current behaviour sends "enable" regardless of whether the database field is populated with a value. This stalls collection of the device configuration.

When this occurs, the debug log for the device simply shows:

root@test-oxidized:~/logs# cat 172.25.25.69-ssh
7200SNI-PRI#enable
7200SNI-PRI#

Looking at the code:

   post_login do
      if vars(:enable) == true
        cmd "enable"
      elsif vars(:enable)
        cmd "enable", /^[pP]assword:/
        cmd vars(:enable)
      end
    end

Could this be improved as:

    post_login do
      unless vars(:enable).empty?
        cmd "enable", /^[pP]assword:/
        cmd vars(:enable)
      end
    end

This seems to now be working reliably in our environment for devices that both need enable passwords and those that don't. I'd like to submit this as a suggested change to the upstream source?

Thanks,

- Matt

**Comment by ytti** [comment]
This is FAQ. But if you send it to nil or false, you won't try to enable. If you set it to true, you will try to enable but do not expect passsport prompt. Anything else and you expect passport prompt and send the string.

**Comment by matt-watkins-1976** [comment]
Hey, thanks for getting back to me so promptly.

Can you confirm my understanding of your answer is correct... If you have the enable field configured in the database file, you need to explicitly set the value to "nil" or "false" for devices where it is not required, otherwise it will be attempted even if the string/value is null/empty or otherwise undefined? Is this already mentioned somewhere in the documentation? Because, if so, my bad, I've clearly missed it. Could something be added as a comment in the ios.rb file, so that people reading that code know what they need to do to get their desired behaviour?

**Comment by matt-watkins-1976** [comment]
I've just tested this, and indeed, all is happy in the garden.

**Comment by ytti** [comment]
Yeah docs might be better in many case, PR's as usual accepted. Thanks.
