### ISSUE TITLE
Debugging fortios.rb behaviour

### ISSUE THREAD

**Issue by ghost** [ytti/oxidized#1989]
Hi,

The default FortiOS script doesn't work with our Fortinet load-balancing device:

Version:            FortiADC-400D v5.1.1,build0239,180919

The default prompt string doesn't match what we get, which is either of these two below:

(S) ADC400-PRI $
(S) ADC400-PRI #

The first prompt is for a read-only user with minimum privileges. Ideally this script would detect both prompts and work in either case. If I modify the bundled collection script, the following does match:

  prompt /^.*(#|$|>)$/

However, there's some complex handling going on in this script, and oxidized crashes if I change the prompt to the above:

2019-12-10 17:31:19 UTC
undefined method `map' for nil:NilClass [NoMethodError]
--------------------------------------------------
/root/.config/oxidized/model/fortios.rb:15:in `block in <class:FortiOS>'
/var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/model/model.rb:117:in `instance_exec'
/var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/model/model.rb:117:in `block in cmd'
/var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/model/model.rb:116:in `each'
/var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/model/model.rb:116:in `cmd'
/var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/model/model.rb:162:in `block in get'
/var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/model/model.rb:161:in `each'
/var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/model/model.rb:161:in `get'
/var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/input/cli.rb:14:in `get'
/var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/node.rb:67:in `run_input'
/var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/node.rb:44:in `block in run'
/var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/node.rb:38:in `each'
/var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/node.rb:38:in `run'
/var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/job.rb:9:in `block in initialize'

Also, there are some commands in the script that don't work on our equipment, such as:

The following command needs to be modified:
  get system ha status -> get system ha-status

The following doesn't work at all:
 get hardware status

I'm not sure if these should be included if they don't work on all devices?

As for the main configuration fetch command, this doesn't work either:

(S) ADC400-PRI $ show full-configuration | grep .
Parsing error at '|'. err=1
Command fail. Return code is -284 (CLI parsing error.)
(S) ADC400-PRI # show full-configuration | grep .
Parsing error at '|'. err=1
Command fail. Return code is -284 (CLI parsing error.)

This additional pipe symbol and grep statement simply does not work on this equipment. I've found a workaround, which has been to change the config on the device using:

config system console
  set output standard
end

(this behaves like the Cisco "terminal length 0" command, but is persistent across sessions)

This is confusing me, as the existing collection script seems to have a ton of code dedicated to handling paginated output. It looks to me that this specific script needs more work if it is to be useful in a broader set of scenarios. I would be happy to work with the maintainers to try and improve it?

The strange thing is that I wrote an alternative script, which I've tried to attach to this report below. Oxidized succeeds in a config fetch, marks the device green in the web interface, and reports no problems. The debug log shows all commands completing successfully. However, there's nothing in the config file that is collected and trying to show the config in the web interface simply results in an empty page. It seems my code is not registering/saving output, for some reason?

Thanks in advance for any help you can provide,

- Matt

[fortinet-modified.txt](https://github.com/ytti/oxidized/files/3946363/fortinet-modified.txt)

**Comment by matt-watkins-1976** [comment]
The prompt below has worked in the existing script with the rest of the content pretty much preserved:

^\(.\) ([^\s]+) (\$|#|>) $

A couple of the commands had to be removed/modified.
