### ISSUE TITLE
Oxidized backups of Cisco device configurations broken.

### ISSUE THREAD

**Issue by dmb1372** [ytti/oxidized#1990]
I've been running Oxidized for a couple of years now, and overall, I believe it's a great solution.  While working on some other updates recently, Oxidized ended up getting updated from 0.26.3 to 0.27.0 on one of my nodes.  Prior to the update, configs were pulled fine from all devices (e.g. -- Cisco IOS routers, Cisco ASAs, Cisco IOS switches, Cisco Nexus switches, etc.).

After the update, the only devices that configs were pulled from properly were the Cisco Nexus switches, which I suspect is due to them not requiring the 'enable' command to get into privileged exec.  Some of the output files for the devices did have some non-privileged output (i.e. -- 'show version', 'show inventory', etc.), which I suspect is that these can be run without being in privileged exec mode.  There were no configuration changes at all, the only change was the update from Oxidized 0.26.3 to 0.27.0.  I was also able to run 'oxs' for each of the Cisco devices with 'show run' and/or 'more system:run' without any issues.

I'll try to go through my config and debug output, and sanitize them, but it's quite lengthy and unfortunately I'm way behind on some critical tasks right now.  With that being said, I suspect that either commit #0bad18f60753b5def2b86d9c2ce619679fd336d1 or commit #034eeb48eaba292b9a47e7c466b2a156e80dcca4 is the culprit currently.

I suspect that the person who reported issue #1958 may be experiencing the same problem as well given the output that provided.

Thank you in advance.

**Comment by ytti** [comment]
Not much information on what actually is wrong, did you see in output that it tries or tries not to enable? What  was expected behaviour? What was behaviour? What is the enable config you have?

for enable
nil/false => do no try to enable
true => try to enable, but do not expect to be prompted for enable password
anythingelse => try to enable, expect enable prompt and send the enable password

**Comment by dmb1372** [comment]
Thank you for the fast response.  I'm going through the debug output now (there's ~8GB and ~70-80 million lines worth), but from what I recall seeing, I didn't see any messages that specifically showed it trying to enable.  I'm not sure if these would show up in debugging output or not, but I would think they would as most everything else shows up in debugging output.

Regarding the enable configs, I actually use a mix of all of the aforementioned enable configs (again, these were all working prior to the update).  Some devices are set to 'True', some devices have the enable password set, and some devices it's set to 'nil' (not defined in configs for those devices).

Expected behavior was for it to actually pull the expected output from the device ('show version', 'show inventory', 'show running-config' or 'more system:run').  Actual behavior was it would pull 'show version' and 'show inventory' output, and would attempt to pull output of 'show running-config' or 'more system:run', but there would be no output for 'show running-config' or 'more system:run' in the output file.

Reviewing debug output now, will try to get some posted shortly after I can sanitize it.

**Comment by ytti** [comment]
Not set (empty string) means we expect password prompt and then send new line (actual config people have).

**Comment by dmb1372** [comment]
Please see attached sanitized debug output and configs.
[Oxidized_Sanitized_Config_20191211.txt](https://github.com/ytti/oxidized/files/3951837/Oxidized_Sanitized_Config_20191211.txt)
[Oxidized_Debug_Output_CiscoSwitch_20191211_03.txt](https://github.com/ytti/oxidized/files/3951838/Oxidized_Debug_Output_CiscoSwitch_20191211_03.txt)
[Oxidized_Debug_Output_CiscoRouter_20191211_02.txt](https://github.com/ytti/oxidized/files/3951839/Oxidized_Debug_Output_CiscoRouter_20191211_02.txt)
[Oxidized_Debug_Output_CiscoASA_20191211_01.txt](https://github.com/ytti/oxidized/files/3951840/Oxidized_Debug_Output_CiscoASA_20191211_01.txt)

**Comment by ytti** [comment]
Oh, I'm not going to read those. I'm just asking what is going wrong, does it try to enable when it should not, does it not try to enable when it should.

**Comment by dmb1372** [comment]
As one additional follow-up note, after further review of the debugging output, oxidized may actually be attempting to enable (it doesn't explicitly say enable, but judging by the code block referenced in the debug output, it does appear that corresponds with the enable commands in the <model>.rb files.

After downgrading back to 0.26.3 from 0.27.0, everything is working correctly again, and the only two commits that I could see between those two versions that could potentially be causing the issue was the ones that I had referenced in my original submission.

**Comment by ytti** [comment]
If you don't want enable set enable 'nil' verbatim, instead of empty string.

**Comment by dmb1372** [comment]
Would the changes between 0.26.3 and 0.27.0 have broken this, as it was working fine previously?  I'm assuming more specifically the following change:

      def prompt(regex = nil)
-        @prompt || (@prompt = regex)
+        @prompt = regex || @prompt


I'm not in a position to upgrade back to 0.27.0 and test this right now, and I don't want to break my current working configs again, but I'll try to circle back around and test this as soon as I'm able to.

**Comment by ytti** [comment]
I don't see how that would break it.

**Comment by dmb1372** [comment]
Thank you for the update.  I'll update my current configs with that change.  When I'm able to upgrade to 0.27.0, I'll do so and test to see if that change fixes the issues that I was seeing.

**Comment by ytti** [comment]
It would be beneficial first to understand the problem better, then we can narrow down on solution.

**Comment by dmb1372** [comment]
My apologies, I'm not sure how better to explain it.  Using the same Oxidized config that was working on 0.26.3 that showed expected config backup output (version/inventory/etc. as well as running config output), broke upon upgrade to 0.27.0.  Upon the upgrade, the only output that I was seeing in the config backup output files for the devices was the output of 'show version', 'show vtp', and 'show inventory'.  However, it never showed any output for 'show running-config' or 'more system:run' in the output files.


As an example, the entire output from one device is below:


! Cisco IOS Software, C2960 Software (C2960-LANBASEK9-M), Version 15.0(2)SE11, RELEASE SOFTWARE (fc3)
!
! Image: Software: C2960-LANBASEK9-M, 15.0(2)SE11, RELEASE SOFTWARE (fc3)
! Image: Compiled: Sat 19-Aug-17 09:34 by prod_rel_team
! Image: flash:c2960-lanbasek9-mz.150-2.SE11.bin
! Chassis type: WS-C2960G-48TC-L
! Memory: main 65536K
! Processor ID: XXXXXXXXXXX
! CPU: PowerPC405
!
! VTP: VTP Version capable             : 1 to 3
! VTP: VTP version running             : 1
! VTP: VTP Domain Name                 :
! VTP: VTP Pruning Mode                : Disabled
! VTP: VTP Traps Generation            : Disabled
! VTP: Device ID                       : xxxx.xxxx.xxxx
! VTP: Feature VLAN:
! VTP: --------------
! VTP: VTP Operating Mode                : Transparent
! VTP: Maximum VLANs supported locally   : 255
! VTP: Number of existing VLANs          : 9
! VTP: Configuration Revision            : 0
! VTP: MD5 digest                        : 0xD3 0x26 0xFD 0x57 0x5E 0xA5 0xEB 0xCC
! VTP:                                     0x8B 0xD9 0xF4 0x10 0x58 0xB1 0xA8 0xB8
!
! NAME: "1", DESCR: "WS-C2960G-48TC-L"
! PID: WS-C2960G-48TC-L  , VID: V01  , SN: XXXXXXXXXXX
!
! NAME: "GigabitEthernet0/45", DESCR: "1000BaseSX SFP"
! PID: Unspecified       , VID:      , SN: XXXXXXXXXXX
!
! NAME: "GigabitEthernet0/46", DESCR: "1000BaseSX SFP"
! PID: Unspecified       , VID:      , SN: XXXXXXXXXXX
!
! NAME: "GigabitEthernet0/47", DESCR: "1000BaseSX SFP"
! PID: Unspecified       , VID:      , SN: XXXXXXXXXXX
!
! NAME: "GigabitEthernet0/48", DESCR: "1000BaseSX SFP"
! PID: Unspecified       , VID:      , SN: XXXXXXXXXXX
!
!

**Comment by ytti** [comment]
I'd suggest make separate config, with just one affected node, store it's input log where you will see what it tries to do. If it tries to enable or does not, you can tell what it did and what you expected.

We're now looking at symptom 'not all config is collected' we should look what is happening, what is oxidized sending to the node, what is the node replying, instead of end result.
