### ISSUE TITLE
Oxidized crash 

### ISSUE THREAD

**Issue by cst-noc** [ytti/oxidized#1991]
Hello Oxidized Comunity,

Oxidized was working fine untill we had a problem with our data center and now it doens't work anymore. 

I'd like to delete oxidized and install it again but i have not found any documentation about it. 

Really appreciate any help you can give with this issue.

This is the crash log in case you ask for it. 

![image](https://user-images.githubusercontent.com/58785251/70721236-96abc600-1ccb-11ea-8b92-9a4c3422b1a9.png)

**Comment by ytti** [comment]
It can't bind to 127.0.0.1 8888, because some process is already listening there. Either kill that process or listen on another port.

**Comment by cst-noc** [comment]
Where do i find that config file to change the port or the ip address?

**Comment by cst-noc** [comment]
the error is probably mine but i really appreciate some help

**Comment by cst-noc** [comment]
i really would like to know how to uninstall oxidized to be able to install it all over again

**Comment by davama** [comment]
The help here is free/voluntary...if you rushing ppl, thats not appreciated

Have you looked at the documentation?
You should find/create a file in $OXIDIZED_HOME/.config/oxidized

As far as removal:

Not sure how you installed in the first place
Maybe `gem uninstall oxidized`

**Comment by cst-noc** [comment]
Sorry if i am being annoying.
 
Yes, i have a config file in  $OXIDIZED_HOME/.config/oxidized and looks like this:

![image](https://user-images.githubusercontent.com/58785251/70728250-74b84080-1cd7-11ea-8830-b782d0926a69.png)

The thing is that i think i made a mess because i did not install this, and when oxidized crashed beacuse im a noob i ran the installation on docker, but i think it was installed in Ubuntu in first place.

**Comment by davama** [comment]
Remove docker for now then and find out where “original” installation is/came from.

Or start fresh...

`gem list` should show installed ruby gems
`gem env` should say where important files may exist

**Comment by cst-noc** [comment]
I removed Docker and now Oxidized start running but it doesn't establish connection to any of my devices.  

![image](https://user-images.githubusercontent.com/58785251/70732738-653cf580-1cdf-11ea-8f78-75ae82fc73cf.png)

**Comment by cst-noc** [comment]
I am testing my config file in LibreNMS and it throws me this error.

![image](https://user-images.githubusercontent.com/58785251/70749589-0e491780-1d03-11ea-86cf-de2362c8e14c.png)
