### ISSUE TITLE
Group > Model Password Precedence

### ISSUE THREAD

**Issue by DaveB91** [ytti/oxidized#1992]
Is there a way to prioritize the username/password set at the group level over the model level?

**Comment by ytti** [comment]
No but I think this is mistake, group probably should have higher precedence. It would be also possible to implement configurable precedent.

The logic is here: https://github.com/ytti/oxidized/blob/master/lib/oxidized/config/vars.rb

And have configuration option which is array which specifies the desirable precedence.
