### ISSUE TITLE
Insufficient input validation.

### ISSUE THREAD

**Issue by thomassoeby** [ytti/oxidized#1997]
When parsing devices from an sqlite source (not sure if the issue is with all sources or specifically this), it's possibly to parse an "empty" device to Oxidized, ie. hostname is 'nil'. Specifically this happened due to mistyping the case of the sqlite columns. 

When this happens, the following error is received:

Is a directory @ rb_sysopen - /home/oxidized/.config/oxidized/crashes/ [Errno::EISDIR]

The error is due to missing input validation on line 82 in node.rb while combining path + filename for the crash log.

System:

Oxidized 0.27.0, Ubuntu 18.04 LTS.

**Comment by ytti** [comment]
What is desired outcome? 

I mean, you configured it wrong, I'd like it to fail hard, so I'd fix my config? Perhaps you'd want it to continue failing hard but having more descriptive error message?

**Comment by thomassoeby** [comment]
A more descriptive error message would be the desired outcome - preferably both at the import level (no reason to be able to import a device with a blank name), and checking the inputs in node.rb prior to combining path + filename.

**Comment by ytti** [comment]
yup, this is common issue we have, quality of error reporting, it's not high concern for me, as to me the error back trace is inherently high quality error reporting. But I'll gladly accept pull requests improving error reporting quality.
