### ISSUE TITLE
how to send emial

### ISSUE THREAD

**Issue by 346315563** [ytti/oxidized#1998]
Run oxidation-report-git-commits, the following prompt appears, how to configure send-email

sudo ./oxidized-report-git-commits
./oxidized-report-git-commits: line 27: hooks:: command not found
./oxidized-report-git-commits: line 28: email_output:: command not found
./oxidized-report-git-commits: line 29: type:: command not found
./oxidized-report-git-commits: line 30: events:: command not found
./oxidized-report-git-commits: line 31: cmd:: command not found
./oxidized-report-git-commits: line 32: async:: command not found
./oxidized-report-git-commits: line 33: timeout:: command not found
Node name: 
Group name: 
Job status: 
Job time: 
$OX_REPO_COMMITREF not set

**Comment by systeembeheerder** [comment]
Don't run as root. Run as your oxidized user. Dont remove the "#" from the file. line 27 - 33 are comments. Better not editing this files at all.

**Comment by mortzu** [comment]
no-feedback -> closed
