### ISSUE TITLE
Source HTTP to PRTG - Incorrect Header Check

### ISSUE THREAD

**Issue by timothydlister** [ytti/oxidized#1999]
Hello,

I'm relatively new to Oxidized but hoping someone could point me in the right direction for troubleshooting. I'm attempting to setup a source to an HTTP API. I have my query which returns the results I want. 

Returned results are as follows when run with "curl -k"

```
{
    "prtg-version": "19.4.54.1506",
    "treesize": 21,
    "": [
        {
            "device": "TestDevice",
            "device_raw": "TestDevice",
            "host": "10.0.0.10",
            "host_raw": "10.0.0.10",
            "tags": "NXOS",
            "tags_raw": "NXOS"
        }
    ]
}

```
Unfortunately, I don't think results are being interpreted correctly as I get the following error when running oxidizer:

```
[tlister@bastion oxidized]$ oxidized
/home/tlister/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/slop-4.7.0/lib/slop.rb:23: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/home/tlister/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/slop-4.7.0/lib/slop/options.rb:27: warning: The called method `initialize' is defined here
/home/tlister/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/slop-4.7.0/lib/slop/options.rb:32: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/home/tlister/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/slop-4.7.0/lib/slop/parser.rb:13: warning: The called method `initialize' is defined here
/home/tlister/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/slop-4.7.0/lib/slop/options.rb:55: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/home/tlister/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/slop-4.7.0/lib/slop/option.rb:30: warning: The called method `initialize' is defined here
I, [2019-12-28T14:50:50.724191 #14594]  INFO -- : Oxidized starting, running as pid 14594
I, [2019-12-28T14:50:50.768537 #14594]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
F, [2019-12-28T14:50:51.052280 #14594] FATAL -- : Oxidized crashed, crashfile written in /home/tlister/.config/oxidized/crash 
incorrect header check
```

```
Crash log:
`2019-12-28 22:37:23 UTC
incorrect header check [Zlib::DataError]
--------------------------------------------------
/home/tlister/.rbenv/versions/2.7.0/lib/ruby/2.7.0/net/http/response.rb:388:in `inflate'
/home/tlister/.rbenv/versions/2.7.0/lib/ruby/2.7.0/net/http/response.rb:388:in `block in inflate_adapter'
/home/tlister/.rbenv/versions/2.7.0/lib/ruby/2.7.0/net/protocol.rb:497:in `call_block'
/home/tlister/.rbenv/versions/2.7.0/lib/ruby/2.7.0/net/protocol.rb:488:in `<<'
/home/tlister/.rbenv/versions/2.7.0/lib/ruby/2.7.0/net/protocol.rb:163:in `read'
/home/tlister/.rbenv/versions/2.7.0/lib/ruby/2.7.0/net/http/response.rb:411:in `read'
/home/tlister/.rbenv/versions/2.7.0/lib/ruby/2.7.0/net/http/response.rb:299:in `block in read_body_0'
/home/tlister/.rbenv/versions/2.7.0/lib/ruby/2.7.0/net/http/response.rb:270:in `inflater'
/home/tlister/.rbenv/versions/2.7.0/lib/ruby/2.7.0/net/http/response.rb:289:in `read_body_0'
/home/tlister/.rbenv/versions/2.7.0/lib/ruby/2.7.0/net/http/response.rb:210:in `read_body'
/home/tlister/.rbenv/versions/2.7.0/lib/ruby/2.7.0/net/http/response.rb:235:in `body'
/home/tlister/.rbenv/versions/2.7.0/lib/ruby/2.7.0/net/http/response.rb:168:in `reading_body'
/home/tlister/.rbenv/versions/2.7.0/lib/ruby/2.7.0/net/http.rb:1536:in `transport_request'
/home/tlister/.rbenv/versions/2.7.0/lib/ruby/2.7.0/net/http.rb:1492:in `request'
/home/tlister/.rbenv/versions/2.7.0/lib/ruby/2.7.0/net/http.rb:1485:in `block in request'
/home/tlister/.rbenv/versions/2.7.0/lib/ruby/2.7.0/net/http.rb:933:in `start'
/home/tlister/.rbenv/versions/2.7.0/lib/ruby/2.7.0/net/http.rb:1483:in `request'
/home/tlister/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/oxidized-0.27.0/lib/oxidized/source/http.rb:74:in `read_http'
/home/tlister/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/oxidized-0.27.0/lib/oxidized/source/http.rb:21:in `load'
/home/tlister/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/oxidized-0.27.0/lib/oxidized/nodes.rb:15:in `block in load'
/home/tlister/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/oxidized-0.27.0/lib/oxidized/nodes.rb:130:in `synchronize'
/home/tlister/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/oxidized-0.27.0/lib/oxidized/nodes.rb:130:in `with_lock'
/home/tlister/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/oxidized-0.27.0/lib/oxidized/nodes.rb:10:in `load'
/home/tlister/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/oxidized-0.27.0/lib/oxidized/nodes.rb:125:in `initialize'
/home/tlister/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/oxidized-0.27.0/lib/oxidized/core.rb:14:in `new'
/home/tlister/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/oxidized-0.27.0/lib/oxidized/core.rb:14:in `initialize'
/home/tlister/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/oxidized-0.27.0/lib/oxidized/core.rb:4:in `new'
/home/tlister/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/oxidized-0.27.0/lib/oxidized/core.rb:4:in `new'
/home/tlister/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/oxidized-0.27.0/lib/oxidized/cli.rb:13:in `run'
/home/tlister/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/oxidized-0.27.0/bin/oxidized:8:in `<top (required)>'
/home/tlister/.rbenv/versions/2.7.0/bin/oxidized:23:in `load'
/home/tlister/.rbenv/versions/2.7.0/bin/oxidized:23:in `<main>'`
```

My config file source looks like this:

```
source:
  default: http
  http:
    url: https://xxxxxxxxx/apicall
    scheme: https
    secure: false
    delimiter: !ruby/regexp /,/
    map:
      name: device
      ip: host
      #model: tags !ruby/regexp /\bios|\bdnos|\bnxos|\bftos|\bfortios|\betherhaul|\bsonicos|\bairfiber/ig
    vars_map:
      enable: enable
```

I think my problem is the way the data is being mapped/interpreted but I'm not quite sure where to look next in my troubleshooting. 

If anyone has any pointers it would be much appreciated.

Thanks,

**Comment by tmcdon89** [comment]
Don't know if this helps or not but I recently setup https source. 

My config is as follows:

> source:
  default: http
  http:
    url: https://xxxx/get-hosts.php
    scheme: https
    secure: false
    hosts_location: result
    user: xxxx
    pass: xxxx
    map:
      ip: interfaces[0].ip
      model: inventory.os
      name: host
    vars_map:
      enable: enable


My output is in JSON format as follows:

`{"jsonrpc":"2.0","result":[{"hostid":"xxxxx","host":"router","inventory":{"os":"routeros"},"interfaces":[{"ip":"x.x.x.x"}]}`

**Comment by timothydlister** [comment]
Thanks tmcdon89. I think this is definitely an issue with my json query. Still working on it but you've pointed me in the right googling direction. I think it should be something like this:

>     map:
      name: .[0].device[]
      ip: .[0].host[]

I'll update and close this issue once I can post a good working example for others.

**Comment by timothydlister** [comment]
A couple days of learning/messing with this and I've picked up a few things. Still getting the "incorrect header check" but in case someone else is ever looking at this trying to get PRTG integrated, I think it needs to look more like this:

```
{
	"prtg-version": "19.4.54.1506",
	"treesize": 21,
	"devices": [
		{
			"device": "device1",
			"device_raw": "device1",
			"host": "10.0.0.9",
			"host_raw": "10.0.0.9",
			"tags": "NXOS",
			"tags_raw": "NXOS"
		},
		{
			"device": "device2",
			"device_raw": "device2",
			"host": "10.0.0.10",
			"host_raw": "10.0.0.10",
			"tags": "NXOS",
			"tags_raw": "NXOS"
		}
	]
}
```

Source config:

```
source:
  default: http
  http:
    url: https://w.x.y.z/api/table.json?content=devices&columns=device,host,tags&output=json&filter_tags=@tag(IOS,NXOS,DNOS,FTOS,FortiOS,EtherHaul,SonicOS,AirFiber)&filter_type=@sub(device)&sortby=name&username=oxidizer&passhash=XXXXXXXX&filter_status=3&filter_status=4
    hosts_location: devices
    scheme: https
    secure: false
    map:
      name: device
      ip: host
      model: tags
```

**Comment by ytti** [comment]
Your config looks good. Perhaps your headers claim it's compressed, while it is not? Content is given to zlib which does not recognise it as compressed file.

**Comment by timothydlister** [comment]
@ytti thank you for the reply. I'll dig into that and see if I can figure it out. In the documentation for PRTG (what I'm querying) I noticed this line:

> Important: PRTG expects all data in the GET parameters to be UTF-8 encoded and URL-encoded . "

Could that be causing this error? The site is also using a self signed certificate if that makes any difference. For reference, using CURL or Postman returns the queries just fine.

Here is the response header when querying with curl:
`
HTTP/1.1 200 OK
Connection: close
Content-Type: application/json; charset=UTF-8
Content-Length: 2999
Date: Tue, 31 Dec 2019 18:32:51 GMT
Expires: 0
Cache-Control: cache, must-revalidate
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Pragma: public
Server: PRTG
`

**Comment by ytti** [comment]
Now the question is, if it's wrongly encoded or if it's correctly encoded but we fail to decode it.

**Comment by ytti** [comment]
You could configure your webserver not to accept/support deflate, so then it shouldn't (potentially) incorrectly compress it.

**Comment by timothydlister** [comment]
The web server appears to be something proprietary and/or bundled. The only configuration available  is a mediocre GUI. I've opened a ticket with them to see if there's an advanced config file somewhere but I'm not going to hold my breath.

I attempted to decompress the data manually:

```
curl -H "Accept-Encoding: gzip, deflate, sdch" "https://xyz/api/table.json?content=devices&columns=device,host,tags&output=json&filter_tags=@tag(IOS,NXOS,DNOS,FTOS,FortiOS,EtherHaul,SonicOS,AirFiber)&filter_type=@sub(device)&sortby=name&username=oxidizer&passhash=xxxxxxxx&filter_status=3&filter_status=4" -k > test
$ zlib-flate -uncompress < test
flate: inflate: data: incorrect header check
```

If I'm understanding these tools correctly, that should have shown the uncompressed results.

Since it looks like the HTTP GET being made from Oxidized has the 'deflate' flag added. Is there a way I can disable this tag from being added?

**Comment by ytti** [comment]
It seems like curl indeed should decompress it on the fly, but fails to do so, adding few debug flags might show curl attempting and failing to decompress it.


You can remove compression support from Net::HTTP, you'd need https://github.com/ytti/oxidized/blob/master/lib/oxidized/source/http.rb#L72 with 
initheader = { 'Accept-Encoding' => 'blaablaablaa' } as documented in https://ruby-doc.org/stdlib-2.6.5/libdoc/net/http/rdoc/Net/HTTP.html

But I suspect the proper solution is to fix the far end.

**Comment by timothydlister** [comment]
@ytti Thank you again for your help. 

I am going down the rabbit hole of vendor support to see if I can fix this on the far end.

For the moment, though, your suggestion has given me a workaround.

For reference, in case anyone else ever runs into this, my line 72 of source/http.rb now looks like this:
`request = Net::HTTP::Get.new(req_uri,initheader = { 'Accept-Encoding' => '' })`
