### ISSUE TITLE
Versions and diff generation performance issue

### ISSUE THREAD

**Issue by tanertas** [ytti/oxidized#2002]
I'm trying to get reasonable response time for getting versions and diffs in 1000+ devices environment. It takes 1 minute to complete "versions" page of a particular device and approx 2 minutes to get a diff from previous config.

I'm not sure these are reasonable numbers for such scale but this issue a big hit on our productivity. We tried to increase puma workers (e.g 8) and threads (e.g 16:32) but we always see that only one puma process is getting cpu time during requests. Parallelizing seems not implemented or not working on my setup.

oxidized version: 0.21.0

```
username: oxidized
password: *********
model: cisco
interval: 604800
use_syslog: false
debug: false
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 127.0.0.1:8888
next_adds_job: false
vars: {}
groups: {}
models: {}
pid: "/home/oxidized/.config/oxidized/pid"
input:
  default: ssh, telnet
  debug: false
  ssh:
    secure: false
output:
  default: git
  git:
      user: oxid
      email: oxidized@***********
      repo: "/home/oxidized/gitdevices/"
source:
  default: csv
  csv:
    file: "/home/oxidized/.config/oxidized/router.db"
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
      username: 2
      password: 3
      enable: 4
      ssh_port: 5
    vars_map:
      enable: 4
      ssh_port: 5
    gpg: false
model_map:
  cisco: ios
  juniper: junos
  hp: procurve
  alcatel-lucent: ao
```

**Comment by kmpanilla** [comment]
Also seeing this exact issue on our setup.  We have 696 devices currently.

**Comment by pogomaniak** [comment]
Try this workaround

    map:
      name: 0
      **group: 0**
      model: 1
      username: 2
      password: 3
      enable: 4
      ssh_port: 5

For every device oxidized make own git folder based by group name = device name. 

Problematic is Rugged library for accessing libgit2. For every diff scan whole git folder. This is problem with one big git folder.

**Comment by tanertas** [comment]
Is this directly applicable on running setup? I mean,
1. Will device specific git folders be created automatically?
2. Will I preserve revision history for each device?

Thanks.

**Comment by pogomaniak** [comment]
Restart oxidized is required. 

1. Yes
2. You lost history, but is possible to copy original git folder (repository.git) to local computer and open in https://github.com/gitextensions/gitextensions/.

**Comment by mortzu** [comment]
this is an oxidized-web bug. Please create an issue in the correct project
