### ISSUE TITLE
model to use for switches with Dell EMC Networking OS10-Enterprise

### ISSUE THREAD

**Issue by gpavinteractiv** [ytti/oxidized#2003]
I have a couple of the following dell switches : S4128T-ON
They run on Dell EMC Networking OS10-Enterprise

According to https://hasanmansur.com/2018/04/30/dell-emc-networking-os10-introduction/
This is a new os distinct from dnos or force10 : 
````
Dell EMC’s traditional OS offering in the DC has been OS9, the legacy FTOS or Force10 operating system. It was based on a NetBSD Kernel.
Dell EMC’s next gen OS offering for the DC is OS10, based on Debian Jesse Linux Kernel.
````

````
# show system 
Required Type        : S4128T
Current Type         : S4128T
Hardware Revision    : A03
Software Version     : 10.4.2.2
Physical Ports       : 28x10GbE, 2x100GbE
BIOS                 : 3.33.0.1-7    

# show version
Dell EMC Networking OS10-Enterprise
Copyright (c) 1999-2019 by Dell Inc. All Rights Reserved.
OS Version: 10.4.2.2
Build Version: 10.4.2.2.265
Build Time: 2019-01-14T15:15:14-0800
System Type: S4128T-ON
Architecture: x86_64
````

LibreNMS mistakenly detect the os as DellX for which, with dellx.rb, the prompt and expect do not match

However, I can either force the use of dnos.rb or ftos.rb with good results if I comment out the following command which does not exist on these switches :
````
# terminal width 0
% Error: Unrecognized command.
````

So my question, 
- should I make a pr modifying either of dnos.rb or ftos.rb for edditing out ````post_login 'terminal width 0'```` ?
- or should I create a new model ?

I guess I will also have to open an issue at LibreNMS for the misdetection

**Comment by jozefrebjak** [comment]
Hello, I have few s4112Fon switches with OS10 ,,, I am trying to grab configs from them, I used your suggestion to use `ftos.rb` for example with deleting `terminal width 0` . My librenms install reporting these switches as dell-os10 os. I am getting list of devices via API. so I added `model_map: dell-os10: ftos` and it's working for me.

**Comment by graceless70** [comment]
jozefrebjak,

Have you seen os10.rb, 
https://github.com/ytti/oxidized/blob/master/lib/oxidized/model/os10.rb  

Usage. model_map: dell-os10: os10

**Comment by michael-ironnet** [comment]
I have this working, pulling devices from librenms. 

Need to add the above model_map. I have groups specified as well, but needed to setup variable mappings on the librenms side of the house. You can verify what is being pulled by librenms via the API curl test mentioned in the librenms documentation; add "/oxidized" to the end to get it to work and replace the hostname with your own. 

curl -H 'X-Auth-Token: YOURAPITOKENHERE' https://<hostname>/api/v0/oxidized

**Comment by mortzu** [comment]
no-feedback -> closed
