### ISSUE TITLE
trying Output types state nodiff diff

### ISSUE THREAD

**Issue by alpern95** [ytti/oxidized#201]
I try today oxidized,
All is working well on to two differents types of devices
I have Cisco UCS and have added a model for ucs.rb because the "sh running" is replace by "sh configuration", and i have 3 ios devices.

My configurations are saved on file. in my home directory ~/.config/oxidized/configs/
I want to try like your doc Output type and chenge the model ios.rb
 i remove and add the lines like on the documentation. but mu 3 ios devices are not save now and are view with the no_connection status.
-----------------here is the modified lines in ...model/ios.rb ----------------
   cmd 'show version' do |state|
    state.type = 'nodiff'
    state
  end

  cmd 'show inventory' do |state|
    state.type = 'nodiff'
    state
  end

  cmd 'show running-config' do |state|
    state = state.each_line.to_a[3..-1]
    state = state.reject { |line| line.match /^ntp clock-period / }.join
    state.gsub! /^Current configuration : [^\n]*\n/, ''
    state.gsub! /^\ tunnel\ mpls\ traffic-eng\ bandwidth[^\n]*\n*(
                  (?:\ [^\n]*\n*)*
                  tunnel\ mpls\ traffic-eng\ auto-bw)/mx, '\1'
    state = Oxidized::String.new state
    state.type = 'nodiff'
    state
  end

**Comment by ytti** [comment]
Well they should be saved, but directory should be 'nodiff' on all of them, so they should be in different place. 

By Cisco UCS what do you mean exactly? What is the operating system called?

**Comment by alpern95** [comment]
Plateform UCS Cisco Unified Computing System. include switch. and i save us with oxidized..
! System version: 2.2(3d)
! UCSM:
!     Running-Vers: 2.2(3d)
!     Package-Vers: 2.2(3d)A
!     Activate-Status: Ready
!
 scope org

**Comment by alpern95** [comment]
UCS are NX-OS
---------------
Cisco UCS 6200 Series Fabric Interconnect
Password:
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Copyright (c) 2009, Cisco Systems, Inc. All rights reserved.
The copyrights to certain works contained in this software are
owned by other third parties and used and distributed under
license. Certain components of this software are licensed under
the GNU General Public License (GPL) version 2.0 or the GNU
Lesser General Public License (LGPL) Version 2.1. A copy of each
such license is available at
http://www.opensource.org/licenses/gpl-2.0.php and
http://www.opensource.org/licenses/lgpl-2.1.php

**Comment by alpern95** [comment]
I try agan and i have a crash file with an error on line 47  in  ios.rb
line 47 state = Oxidized::String.new state
----------------crash file for one device-----------
/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/oxidized-0.8.1/lib/oxidized/model/ios.rb:47:in `block in <class:IOS>'
/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/oxidized-0.8.1/lib/oxidized/model/model.rb:91:in `instance_exec'
/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/oxidized-0.8.1/lib/oxidized/model/model.rb:91:in `cmd'
/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/oxidized-0.8.1/lib/oxidized/model/model.rb:132:in `block in get'
/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/oxidized-0.8.1/lib/oxidized/model/model.rb:131:in `each'
/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/oxidized-0.8.1/lib/oxidized/model/model.rb:131:in `get'
/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/oxidized-0.8.1/lib/oxidized/input/cli.rb:13:in `get'
/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/oxidized-0.8.1/lib/oxidized/node.rb:58:in `run_input'
/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/oxidized-0.8.1/lib/oxidized/node.rb:36:in `block in run'
/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/oxidized-0.8.1/lib/oxidized/node.rb:31:in `each'
/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/oxidized-0.8.1/lib/oxidized/node.rb:31:in `run'
/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/oxidized-0.8.1/lib/oxidized/job.rb:8:in `block in initialize'

**Comment by ytti** [comment]
We have NXOS model available

**Comment by ytti** [comment]
Can you put the crashfile online somewhere? Perhaps http://p.ip.fi/

**Comment by alpern95** [comment]
Hello ytti,
About UCS 6200 Series Fabric Interconnect i use a copy of ios.rb in ucs.rb, and i juste change show running with show configuration and all work perfecly.
I see the model NXOS have "show running" that doesnt match my UCS NSOS.

About the crash, i have a crash but yesterday, when i am trying debuging, unfortunately i add a new problem. And the crash show me my mistake.

For now with the mode state , diff nodiff, my files are created in ~/oxidized/configs/x.x.x.x but empty.
and i have no crash.

~/.config/oxidized# ls -lia configs/
total 584
1984717 drwxr-xr-x 4 root root   4096 sept. 27 20:42 .
1984713 drwxr-xr-x 6 root root   4096 sept. 28 18:57 ..
1984721 -rw-r--r-- 1 root root 287182 sept. 28 18:57 1.x.x.a
1984722 -rw-r--r-- 1 root root 287182 sept. 28 18:57 1.x.x.b
1981353 -rw-r--r-- 1 root root      0 sept. 28 18:57 1.x.x.x
1981306 -rw-r--r-- 1 root root      0 sept. 28 18:57 1.x.x.y
1981366 -rw-r--r-- 1 root root      0 sept. 28 18:57 1.x.x.z
1981288 drwxr-xr-x 2 root root   4096 sept. 27 14:28 diff
1981088 drwxr-xr-x 2 root root   4096 sept. 27 14:23 nodiff

**Comment by ytti** [comment]
Looking at your model, if all have 'state.type=nodiff' they should be in the 'nodiff' directory.

Even cisco seems to claim NXOS has 'show running-config', usually 'show config' should mean it's showing the stored configuration not the active one.
http://docwiki.cisco.com/wiki/Cisco_NX-OS/IOS_Configuration_Fundamentals_Comparison

**Comment by alpern95** [comment]
Hello ytti,
I check all my config, but no file was created in nodiff directory.
Juste empty file for ech device in ~/.config/oxidized/configs/
and in input debug file all seems good.
i have created a nodiff directory in 
~/.config/oxidized/nodiff
and in 
~/.config/oxidizedconfigs/nodiff
My output config is on flat file , you recommande git in you README. is this important. can we have versionning in this conguration?
output:
  default: file
  file:
    directory: /home/alain/.config/oxidized/configs
About UCS NXOS can we open another discussion?

**Comment by ytti** [comment]
Oh right, my apologies. This feature is only implemented on git output, not file output.

The git implementation is here:
https://github.com/ytti/oxidized/blob/master/lib/oxidized/output/git.rb#L32

Similar would be needed to be added here:https://github.com/ytti/oxidized/blob/master/lib/oxidized/output/file.rb

**Comment by alpern95** [comment]
Thank i will install a local git repository for testing.

**Comment by alpern95** [comment]
I do the test now, it's work perfecly with a local git repository.
Thank for your help.
