### ISSUE TITLE
http retrievals silently fail without mechanize

### ISSUE THREAD

**Issue by ja-frog** [ytti/oxidized#2010]
Recently installed this on a CentOS 8 VM (where it worked great, btw. No need for rvm). The one problem is that http config retrievals fail without any error message unless you explicitly install the mechanize gem. Would it make more sense to add mechanize as a dependency for the oxidized gem or to update install instructions?

**Comment by ytti** [comment]
https://github.com/ytti/oxidized/blob/master/lib/oxidized/input/http.rb#L17-L21

This does not look like a silent failure.

**Comment by ja-frog** [comment]
Let me spin up a new VM and try it without mechanize again and verify.

**Comment by ja-frog** [comment]
Sorry this took so long. Spun one up today. It does give a message in /var/log/message. I had been expecting it either in the debug output from running from the command line or in the debug logs for the IP address.

That works for me. Sorry, I didn't think to look in syslogs for this.
