### ISSUE TITLE
 Which model does Topsec ngfw4000 use 

### ISSUE THREAD

**Issue by jaxzhai** [ytti/oxidized#2011]
Which model does Topsec ngfw4000 use ?

**Comment by mclee23** [comment]
hi:

try:

class Topsec < Oxidized::Model
  # Topsec
  prompt /^\r?[\w.()-]+[#>](\s)?$/
  comment '# '

  expect /^\s.*--More--.*$/ do |data, re|
    send ' '
    data.sub re, ''
  end

  cmd 'show-running' do |cfg|
    comment cfg
  end

  cfg :telnet do
    username /^(Username|login):/
    password /^[pP]assword:/
  end

  # Save system config?[y/n]:
  expect /^Save system config\?\[y\/n\]: $/ do |data, re|
    sleep 2
    send "n\r"
    data.sub re, ''
  end

  cfg :telnet, :ssh do
    pre_logout 'exit'
    sleep 2
    pre_logout 'n'
  end
end


my topsec ngfw400 work ok!

**Comment by mclee23** [comment]
Hi:

try:

class Topsec < Oxidized::Model
  # Topsec
  prompt /^\r?[\w.()-]+[#>](\s)?$/
  comment '# '

  expect /^\s.*--More--.*$/ do |data, re|
    send ' '
    data.sub re, ''
  end

  cmd 'show-running' do |cfg|
    comment cfg
  end

  cfg :telnet do
    username /^(Username|login):/
    password /^[pP]assword:/
  end

  expect /^Save system config\?\[y\/n\]: $/ do |data, re|
    sleep 2
    send "n\r"
    data.sub re, ''
  end

  cfg :telnet, :ssh do
    pre_logout 'exit'
    sleep 2
    pre_logout 'n'
  end
end


My topsec ngfw4000 work ok

**Comment by mclee23** [comment]
Hi:

Try


class Topsec < Oxidized::Model

  prompt /^\r?[\w.()-]+[#>](\s)?$/
  comment '# '

  expect /^\s.*--More--.*$/ do |data, re|
    send ' '
    data.sub re, ''
  end

  cmd 'show-running' do |cfg|
    comment cfg
  end

  cfg :telnet do
    username /^(Username|login):/
    password /^[pP]assword:/
  end

  # Save system config?[y/n]:
  expect /^Save system config\?\[y\/n\]: $/ do |data, re|
    sleep 2
    send "n\r"
    data.sub re, ''
  end

  cfg :telnet, :ssh do
    pre_logout 'exit'
    sleep 2
    pre_logout 'n'
  end
end


My topsec ngfw works ok

**Comment by mclee23** [comment]
class Topsec < Oxidized::Model

  prompt /^\r?[\w.()-]+[#>](\s)?$/
  comment '# '

  expect /^\s.*--More--.*$/ do |data, re|
    send ' '
    data.sub re, ''
  end

  cmd 'show-running' do |cfg|
    comment cfg
  end

  cfg :telnet do
    username /^(Username|login):/
    password /^[pP]assword:/
  end

  expect /^Save system config\?\[y\/n\]: $/ do |data, re|
    sleep 2
    send "n\r"
    data.sub re, ''
  end

  cfg :telnet, :ssh do
    pre_logout 'exit'
    sleep 2
    pre_logout 'n'
  end
end


My Topsec ngfw works fine!
