### ISSUE TITLE
looking at pulled configs via Git

### ISSUE THREAD

**Issue by Ray-Zuniga-M451** [ytti/oxidized#2013]
Hello i have a working oxi server. it pulls configs fine. If hypothetically I wanted to not have to go through the web gui and click on 30 devices and copy-paste their configs one at a time to a usb. 

How would I do that is git the way to do that on this app ? (assuming you can)

I already automated this using curl and i have full access to the server , so it seems like im doing things the hard way.

**Comment by wk** [comment]
Assuming your oxidized instance is configured with the `git` backend - the git repository Oxidized maintains is a 'bare' repository (i.e., you do not see the latest/current version of the actual files in the repository directory, only a hidden `.git` subdirectory), but you can always clone the contents somewhere else, or use other git commands and features to interact with it.

Create a new directory, and while inside it, use `git clone` to make a copy of the current configurations of all devices.

Example (assumes Oxidized backs up to /opt/oxidized/configs):
```bash
mkdir -p /tmp/configs # Make a new empty directory, /tmp/configs
cd /tmp/configs # change directory into the newly created /tmp/configs
git clone file:///opt/oxidized/configs # Clone the oxidized git repository currently in /opt/oxidized/configs
ls # You should now see the latest versions of all backed up configurations
```
