### ISSUE TITLE
Palo Alto panos model to backup configuration via SET.

### ISSUE THREAD

**Issue by lachlanjholmes** [ytti/oxidized#2015]
Hey All,

I got the following working on my oxidized to backup panos devices via **config-output-format set**.

But if you run it in the router.db along with the existing panos model.

Depending on the which node runs first it will save the output as that for both models ( panos.rb and panosset.rb ).

Any ideas would be great!

```
$ cat model/panosset.rb 
class PanOSset < Oxidized::Model
  # PaloAlto PAN-OS model #

  comment '! '

  prompt /^[\w.@:()-]+[#?>]\s?$/

  cmd :all do |cfg|
    cfg.each_line.to_a[2..-3].join
  end

  cmd 'show' do |cfg|
    cfg
  end

  cfg :ssh do
    post_login 'set cli pager off'
    post_login 'set cli config-output-format set'
    post_login 'configure'
    pre_logout 'exit'
    pre_logout 'set cli config-output-format default'
    pre_logout 'quit'
  end
end
```

**Comment by ytti** [comment]
You may want to read 'advanced features' and look at the junos set example here: https://github.com/ytti/oxidized/blob/master/docs/Creating-Models.md
