### ISSUE TITLE
Slack webhook node_fail

### ISSUE THREAD

**Issue by chibi4588** [ytti/oxidized#2016]
Hello, I was wondering if it was possible to create a node_fail webhook for Slack?  I only see post_store.  
Let me know if this would be a possibility. 
Thanks much!

**Comment by ytti** [comment]
Yes it is possible.

**Comment by chibi4588** [comment]
Ytti,
Thank you very much for the quick reply!  Do you have any suggestions for creating this, or who to possibly reach out to assist?

**Comment by ytti** [comment]
Reading docs and some hook should get you there

https://github.com/ytti/oxidized/blob/master/docs/Hooks.md
https://github.com/ytti/oxidized/blob/master/lib/oxidized/hook/slackdiff.rb

**Comment by vincent516** [comment]
It appears that slackdiff will only post a message if the event is post_store:

def run_hook(ctx)
    return unless ctx.node
    **return unless ctx.event.to_s == "post_store"**

Can this be changed so a message can be sent to Slack on a node_fail as well?

**Comment by jalmargyyk** [comment]
slackdiff hook is still only allowed if the event is post_store. In my opinion, all the events should be allowed.
