### ISSUE TITLE
Missing new lines in dump (0.8.1)

### ISSUE THREAD

**Issue by andrewpwade** [ytti/oxidized#202]
Ruby version: ruby 2.0.0p384

I upgraded to 0.8.1 (from 0.2.3 I think) and I have some diffs like this on my juniper devices:

```diff
-}
-# Hostname:
+}# Hostname:
```
```diff
-}
-# fpc0:
+}# fpc0:
```

```diff
-# JUNOS FIPS mode utilities [12.3R9.4]
-# Hardware inventory:
+# JUNOS FIPS mode utilities [12.3R9.4]# Hardware inventory:
```

It seems to between the config dump and the inventory dump.

**Comment by ytti** [comment]
Yeah I've broken it here:
https://github.com/ytti/oxidized/commit/d5773ab38c1bc4514be798df618bdafbe26f4f55
