### ISSUE TITLE
[Feature Request]: Create two new variables for Hook exec

### ISSUE THREAD

**Issue by davama** [ytti/oxidized#2025]
Hello,

Was looking at hook type [exec](https://github.com/ytti/oxidized/blob/master/docs/Hooks.md#hook-type-exec) and noticed that a number of environment variables have been added since I last looked at it. That's awesome!!

Was testing it to see how it looked and here is what I got:

```
OX_EVENT:post_store
OX_NODE_NAME:h-txa-1n-ap-1
OX_NODE_IP:2607:xxx:xx:xx....
OX_NODE_FROM:
OX_NODE_MSG:
OX_NODE_GROUP:USA-HT_WIFI
OX_NODE_MODEL:IOS
OX_JOB_STATUS:success
OX_JOB_TIME:5.285614301
OX_REPO_COMMITREF:474fadcc377bd10582f58296804a9a7b4f5cc613
OX_REPO_NAME:/home/config/oxidized/USA-HT_WIFI.git
``` 

We extend some models and save different data on a git subdirectory like [here](https://github.com/ytti/oxidized/blob/master/docs/Creating-Models.md#advanced-features).

Was wondering if possible to have some extra ENV variables like
```
OX_SUBREPO_TYPE = the value of cfg.type
OX_SUBREPO_NAME = the value of cfg.name
``` 
Names could be whatever make more sense...

Thank you,
Dave

**Comment by davama** [comment]
Sorry outside this request but.... if also possible to:

**IF** $OX_SUBREPO_TYPE exist, update the "git commit message" ?

something like:

```
update $OX_NODE_GROUP/$OX_NODE_NAME $OX_SUBREPO_TYPE
```

**Comment by mortzu** [comment]
Provide a PR please

**Comment by davama** [comment]
Going to give this a shot👍

adding exec.rb link for my reference:
https://github.com/ytti/oxidized/blob/master/lib/oxidized/hook/exec.rb

**Comment by davama** [comment]
No bandwidth for this.

closing
