### ISSUE TITLE
Multiple oxidized threads staying signed into Panorama

### ISSUE THREAD

**Issue by dfsbagwellj** [ytti/oxidized#2026]
We are noticing that many threads of Oxidized seem to not be cleanly signing out of our Panorama setup.  If we don't keep the idle logout timer low, it begins to get a bit crazy.  So far this seems to be the only device on our network where this is happening.  Has anyone seen this kind of behavior before?  As I type this I see around 20 logged in oxidized 'users' on my Panorama device.

**Comment by DarkCatapulter** [comment]
I have a somewhat similar issue on some older HP Procurve switches, multiple sessions with oxidized. However I have disregarded it since it's no big issue, our idle-session logout handles it.
