### ISSUE TITLE
Ssh-agent: Agent not configured

### ISSUE THREAD

**Issue by Tira007** [ytti/oxidized#2027]
Good day.
Tried to make friends with oxidized gitlab c using keys.
Not wound up...
I tried different tips to get ssh-agent.
ssh-T git@gitlab.digital-ecosystems.ru -works, welcomes me.
In logs I see such

Feb  4 19:33:00 oxidized oxidized[22433]: channel_request: 2 exit-status false
Feb  4 19:33:00 oxidized oxidized[22433]: channel_close: 2
Feb  4 19:33:00 oxidized oxidized[22433]: 192.168.100.50 delete channel 2 which closed locally and remotely
Feb  4 19:33:00 oxidized oxidized[22433]: channel_open_confirmation: 3 3 2621440 262144
Feb  4 19:33:00 oxidized oxidized[22433]: sending channel request "env"
Feb  4 19:33:00 oxidized oxidized[22433]: sending channel request "exec"
Feb  4 19:33:00 oxidized oxidized[22433]: channel_success: 3
Feb  4 19:33:00 oxidized oxidized[22433]: channel_data: 3 124b
Feb  4 19:33:00 oxidized oxidized[22433]: channel_data: 3 19b
Feb  4 19:33:00 oxidized oxidized[22433]: channel_data: 3 42b
Feb  4 19:33:00 oxidized oxidized[22433]: channel_data: 3 254b
Feb  4 19:33:00 oxidized oxidized[22433]: channel_data: 3 48b
### Feb  4 19:33:01 oxidized oxidized[22433]: could not connect to ssh-agent: Agent not configured
Feb  4 19:33:20 oxidized journal: Suppressed 2997 messages from /system.slice/oxidized.service
Feb  4 19:33:46 oxidized journal: Suppressed 1752 messages from /system.slice/oxidized.service
Feb  4 19:33:46 oxidized oxidized[22433]: negotiating protocol version
Feb  4 19:33:46 oxidized oxidized[22433]: sending KEXINIT
Feb  4 19:33:46 oxidized oxidized[22433]: got KEXINIT from server
Feb  4 19:33:46 oxidized oxidized[22433]: negotiating algorithms
**Feb  4 19:33:46 oxidized oxidized[22433]: could not connect to ssh-agent: Agent not configured
Feb  4 19:33:46 oxidized oxidized[22433]: channel_open_confirmation: 0 0 2621440 262144**
Feb  4 19:33:46 oxidized oxidized[22433]: sending channel request "env"
Feb  4 19:33:46 oxidized oxidized[22433]: sending channel request "exec"

Config:

---
model: routeros
resolve_dns: true
interval: 60
use_syslog: true
threads: 30
timeout: 180
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 0.0.0.0:8888
next_adds_job: false
vars:
  auth_methods: [ "none", "publickey", "password"]
  ssh_keys: "/root/.config/oxidized/.ssh/id_rsa"
groups: {}
models: {}
pid: "~/.config/oxidized/pid"
log: "~/.config/oxidized/logs/"
crash: "~/.config/oxidized/crashes/"
stats:
  history_size: 10
input:
  default: ssh
  debug: true
  ssh:
    secure: false
map:
  verify_host_key: never
  utf8_encoded: true
output:
  default: git
  output: debug
  git:
    repo: "~/.config/oxidized/devices/devices.git"
source:
  default: csv
  csv:
    file: "~/.config/oxidized/mikrotik/router.db"
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
      ip: 2
      port: 3
      username: 4
      password: 5
model_map:
  Cisco: ios
  mikrotik: routeros

hooks:
  push_to_remote:
    type: githubrepo
    events: [post_store]
    remote_repo: "git@github.com:Tira007/test.git"
    publickey: /opt/oxidized/.ssh/id_rsa.pub
    privatekey: /opt/oxidized/.ssh/id_rsa

**Comment by mortzu** [comment]
Can you please reformat your paste to make it readable? (https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code)
