### ISSUE TITLE
gem install oxidized don't reconized slop version

### ISSUE THREAD

**Issue by Haiironokumo** [ytti/oxidized#203]
mistake, sorry

**Comment by ytti** [comment]
I just want to elaborate bit why we don't use/accept latest slop. Very good ruby debugging tool called 'pry' requires slop3, and if your software uses slop4, then you cannot use 'pry' at the same time. And I really want to be able to use 'pry', so we have to use the older version of slop.

**Comment by Haiironokumo** [comment]
Thanks for the reply, i use 3.5 and it works well.

regards.

2015-09-29 16:28 GMT+02:00 ytti <notifications@github.com>:

> I just want to elaborate bit why we don't use/accept latest slop. Very
> good ruby debugging tool called 'pry' requires slop3, and if your software
> uses slop4, then you cannot use 'pry' at the same time. And I really want
> to be able to use 'pry', so we have to use the older version of slop.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ytti/oxidized/issues/203#issuecomment-144077284>.
>



-- 
Michaël
