### ISSUE TITLE
192.168.9.170 raised NoMethodError with msg "undefined method `join' for nil:NilClass"

### ISSUE THREAD

**Issue by NetworkIPS1** [ytti/oxidized#2031]
Hi,

I'm currently having this issue when I'm trying to back up configuration on Dell EMC S4048-ON

D, [2020-02-06T22:11:38.068218 #12522] DEBUG -- : Telnet: 1234 @192.168.9.170
D, [2020-02-06T22:11:38.108681 #12522] DEBUG -- : lib/oxidized/input/cli.rb: Running post_login command: "terminal length 0", block: nil at 192.168.9.170
D, [2020-02-06T22:11:38.108719 #12522] DEBUG -- : Telnet: terminal length 0 @192.168.9.170
D, [2020-02-06T22:11:38.149561 #12522] DEBUG -- : lib/oxidized/model/model.rb Collecting commands' outputs
D, [2020-02-06T22:11:38.149604 #12522] DEBUG -- : lib/oxidized/model/model.rb Executing show inventory
D, [2020-02-06T22:11:38.149622 #12522] DEBUG -- : Telnet: show inventory @192.168.9.170
D, [2020-02-06T22:11:38.191224 #12522] DEBUG -- : lib/oxidized/model/model.rb Executing show inventory media
D, [2020-02-06T22:11:38.191254 #12522] DEBUG -- : Telnet: show inventory media @192.168.9.170
D, [2020-02-06T22:11:38.254396 #12522] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2020-02-06T22:11:38.489208 #12522] DEBUG -- : lib/oxidized/model/model.rb Executing show running-configuration
D, [2020-02-06T22:11:38.489263 #12522] DEBUG -- : Telnet: show running-configuration @192.168.9.170
E, [2020-02-06T22:11:38.531059 #12522] ERROR -- : 192.168.9.170 raised NoMethodError with msg "undefined method `join' for nil:NilClass", 192.168.9.170 saved
D, [2020-02-06T22:11:38.531116 #12522] DEBUG -- : lib/oxidized/node.rb: Oxidized::Telnet failed for 192.168.9.170

Then, I got this on my Dell console prompt:

%SEC-5-LOGOUT: Exec session is terminated for use                                                                                                              r ips1 on line vty0 ( 192.168.9.120 ) (Reason : Admin Reset)

Crash log from /home/Oxidized/.config/oxidized/crashes

/home/Oxidized/.config/oxidized/model/os10.rb:29:in `block in <class:OS10>'
/usr/local/rvm/gems/ruby-2.3.8/gems/oxidized-0.27.0/lib/oxidized/model/model.rb:124:in `instance_exec'
/usr/local/rvm/gems/ruby-2.3.8/gems/oxidized-0.27.0/lib/oxidized/model/model.rb:124:in `cmd'
/usr/local/rvm/gems/ruby-2.3.8/gems/oxidized-0.27.0/lib/oxidized/model/model.rb:162:in `block in get'
/usr/local/rvm/gems/ruby-2.3.8/gems/oxidized-0.27.0/lib/oxidized/model/model.rb:161:in `each'
/usr/local/rvm/gems/ruby-2.3.8/gems/oxidized-0.27.0/lib/oxidized/model/model.rb:161:in `get'
/usr/local/rvm/gems/ruby-2.3.8/gems/oxidized-0.27.0/lib/oxidized/input/cli.rb:14:in `get'
/usr/local/rvm/gems/ruby-2.3.8/gems/oxidized-0.27.0/lib/oxidized/node.rb:67:in `run_input'
/usr/local/rvm/gems/ruby-2.3.8/gems/oxidized-0.27.0/lib/oxidized/node.rb:44:in `block in run'
/usr/local/rvm/gems/ruby-2.3.8/gems/oxidized-0.27.0/lib/oxidized/node.rb:38:in `each'
/usr/local/rvm/gems/ruby-2.3.8/gems/oxidized-0.27.0/lib/oxidized/node.rb:38:in `run'
/usr/local/rvm/gems/ruby-2.3.8/gems/oxidized-0.27.0/lib/oxidized/job.rb:9:in `block in initialize'

Thanks and hopefully it can be resolved

**Comment by seros1521** [comment]
Looks like #1898. Debug as described there.

**Comment by mortzu** [comment]
Can you please reformat your paste to make it readable? (https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code)
