### ISSUE TITLE
mail notification only 

### ISSUE THREAD

**Issue by mael-agro** [ytti/oxidized#2032]
hello,

I would like to receive only 1 email when all my hosts have finished being backed up instead of 1 email pare hosts .threads

my configuration:

 email_output:
        type: exec
        events: [post_store,node_fail]
        cmd: '/opt/oxidized/output/extra/oxidized-report-git-commits | mail -s "Oxidized updates for ${OX_NODE_GROUP}" test@test.fr'
        async: true
        timeout: 120

**Comment by clontarfx** [comment]
https://github.com/ytti/oxidized/blob/master/docs/Hooks.md

Isn't `nodes_done` what you're looking for?
