### ISSUE TITLE
Backup jobs get stuck in worker queue

### ISSUE THREAD

**Issue by PeepOks** [ytti/oxidized#2039]
Oxidized version: 0.27.0
Nr of nodes: ~750

I have problem that somehow some jobs get somehow stuck in worker queue. I think that causes problem I have with oxidized that time between 2 jobs for devices goes over interval time. 
Currently I have configured interval 21600(6h) and for example for one device "last update" is 2020-02-27 15:28:38 UTC and current time is 2020-02-28 06:39:42 UTC.

Time between backups starts to go over configured interval even when 1 interval(6h) has passed. Even if I use "next_adds_jobs", then this device does not get processed. 

Because debug does not show what jobs are running in parallel I have no way to guess why this happens.

I have ~10 nodes that i know that oxidized do not have connection to it and jobs for them constantly fails because of no_connection. But this should not cause an issue I have.

Over time "jobs running in parallel" increases

>D, [2020-02-27T18:58:43.352899 #53650] DEBUG -- : lib/oxidized/worker.rb: 3 jobs running in parallel
>D, [2020-02-27T18:58:44.353160 #53650] DEBUG -- : lib/oxidized/worker.rb: 3 jobs running in parallel
>D, [2020-02-27T18:58:45.353485 #53650] DEBUG -- : lib/oxidized/worker.rb: 3 jobs running in parallel

>D, [2020-02-28T06:19:37.009130 #53650] DEBUG -- : lib/oxidized/worker.rb: 5 jobs running in parallel
>D, [2020-02-28T06:19:38.009732 #53650] DEBUG -- : lib/oxidized/worker.rb: 5 jobs running in parallel

>D, [2020-02-28T06:27:12.274724 #53650] DEBUG -- : lib/oxidized/worker.rb: 6 jobs running in parallel
>D, [2020-02-28T06:27:13.275066 #53650] DEBUG -- : lib/oxidized/worker.rb: 6 jobs running in parallel

`

**Comment by ytti** [comment]
We will continually try to reget boxes if success internval is not met, this shouldn't cause any problem. If you don't want them to  be attempted for some reason, perhaps in your backend set those boxes as down or something and do not fetch over API 'down' boxes. So you reload new nodes list, without boxes you don't wish to try to fetch.

**Comment by PeepOks** [comment]
I can disable backups for devices what are unreachable for oxidized. But this should not be issue if jobs continuously fail.
Main problem for me is that time between 2 backups get very big.

When 1. cycle of backup jobs finished then I saw something strange in logs. Are following lines normal? 
>D, [2020-02-28T10:30:44.523061 #58786] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 1 of 757
>D, [2020-02-28T10:30:45.523496 #58786] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 1 of 757
>D, [2020-02-28T10:30:46.523965 #58786] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 1 of 757
>D, [2020-02-28T10:30:47.524354 #58786] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 1 of 757

**Comment by PeepOks** [comment]
I don't know why but now backups are running just fine.
Maybe adding "ssh_no_keepalive: false" to config had some affect.

Closing issue.
