### ISSUE TITLE
PAN-OS Banner Requires Acceptance Before Login

### ISSUE THREAD

**Issue by ahamilto** [ytti/oxidized#2040]
Hello, I am working on setting up Oxidized at my company and we ran into an edge-case with our Palo Alto Firewalls. They are set to require acceptance of the banner which occurs before the login prompt (see login example below). I tried to configure a solution similar to [issue 2021](https://github.com/ytti/oxidized/issues/2021) but it appears that expect blocks are not run before login.

There is a workaround which is to setup authentication using SSH keys; since an SSH key login does not allow for keyboard-interactive input, the firewall just prints the banner and then allows the login.

If there is interest in adding the ability for Oxidized to process input before the login banner, I would be happy to take a look at it; any pointers on where/how this should be done would be appreciated but I'm thinking it would be something like a "pre-login" argument to the ssh command, similar to the post-login and pre-logout events?

Thank you,
Andrew

Example PAN-OS Login over SSH with password auth and banner acceptance:
```
$ ssh firewall
Confidentiality Disclaimer:
UNAUTHORIZED ACCESS TO THIS SYSTEM IS PROHIBITED.
Do you accept and acknowledge the statement above ? (yes/no) : yes
Password:
Last login: Mon Feb 24 00:00:00 2020 from 127.0.0.1

Number of failed attempts since last successful login: 0

username@firewall(active)>
```

**Comment by deligatedgeek** [comment]
This issue has to be handled in net-ssh.  I have submitted a PR to net-ssh for exactly this issue and hopefully should be accepted next week after test fixes.

**Comment by mortzu** [comment]
@deligatedgeek any news about this?

**Comment by deligatedgeek** [comment]
@mortzu My PR for net-ssh was rejected by the maintainer, as he doesn't have time and its not a feature he is interested in.  I'm just installing the modified net-ssh from my Github repo and Oxidized is working fine.
