### ISSUE TITLE
Brocade switch backup

### ISSUE THREAD

**Issue by fonyoi** [ytti/oxidized#2041]
Hi Gentlemens,

I'm using it under librenms and want to check or know that it's possible to backup the Brocade switches configuration? I have tryed a lot thinks but was not sussefully.
May i can get some hints or tips how to doit.

+Info that i see this in the logs:
`E, [2020-03-05T15:30:01.810837 #15686] ERROR -- : node {:name=>"switch1", :model=>"fabos", :group=>nil} raised Oxidized::ModelNotFound with message 'fabos not found for node 192.168.0.100'`

Thanks.

**Comment by will-h** [comment]
This is because there is no model called 'fabos'. You'll need to include a model_map from 'fabos' to the correctly named model, which might be called 'fabricos' ? https://github.com/ytti/oxidized/blob/master/docs/Supported-OS-Types.md 

Something like:
```
model_map:
  fabos: fabricos
```
in your config file may help

**Comment by mortzu** [comment]
no-feedback -> closed
