### ISSUE TITLE
forcing oxidized to use the latest version of net-ssh.

### ISSUE THREAD

**Issue by alex67** [ytti/oxidized#2043]
Hello,

I've been reading through the [excellent] oxidized documentation put together by Saku.
I have been was wondering if there's a way to tell oxidized to use a particular version of net-ssh.

Encryption schemes are getting stronger and stronger all the time and it appears that current Cisco devices running IOS-XE no longer support the older kex algorithms used by the version of net-ssh that comes with Oxidized.  You just get this when oxidized tries to connect.
(/home/oxidized/.config/oxidized/logs/log)
W, [2020-03-06T09:27:52.093755 #50034]  WARN -- : 172.20.105.7 raised Net::SSH::Exception (rescued RuntimeError) with msg "could not settle on kex algorithm"

Apparently this version does ./.gem/specs/api.rubygems.org%443/quick/Marshal.4.8/net-ssh-6.0.0.beta2.gemspec
 support the latest kex algorithms required, which I believe is DH group14.
(from IOS-XE)
172.20.105.7(config)#ip ssh server algorithm kex ?
  diffie-hellman-group-exchange-sha1  DH_GRPX_SHA1 diffie-hellman key exchange
                                      algorithm
  diffie-hellman-group14-sha1         DH_GRP14_SHA1 diffie-hellman key exchange
                                      algorithm

I'm wondering if there's a way to tell Oxidized to use a later version of net-ssh.
Does anyone know if that can be done and if so, how?

Many thanks in advance,

Alex

**Comment by ytti** [comment]
There are no new KEX in 6. We support and by default should offer both of the KEX you show. Is it possible you've configured kex in your oxidized config? Perhaps debug what both parties are offering for KEX.

**Comment by wk** [comment]
While not relevant to this issue directly, [net-ssh 6.0.0 beta1](https://github.com/net-ssh/net-ssh/blob/master/CHANGES.txt) does appear to have introduced a new KEX in net-ssh/net-ssh#690, which has a dependency on the `x25516` gem. It also disabled many old algorithms in net-ssh/net-ssh#709 - which is likely to be a breaking change for older firmware (such as IOS-XR 5.3.x) that relies on them.

If we are to upgrade when 6.0.0 is released to gain support for `curve25519-sha256@libssh.org`, we'll probably need to pass the variable `append_all_supported_algorithms: true` to maintain current compatibility - and document the meaning of this knob.
