### ISSUE TITLE
Oxidized not starting

### ISSUE THREAD

**Issue by ancorrus** [ytti/oxidized#2045]
Hello, I'm trying to start Oxidized with a basic custom model, here it is:
class Altell < Oxidized::Model

    cmd "cat `show configuration files | awk '{print \"\/\"$1}'`"

end

And this is what i get:
oxidized@altell-nms:~/.config/oxidized/model$ oxidized
I, [2020-03-11T17:42:31.441321 #21975]  INFO -- : Oxidized starting, running as pid 21975
I, [2020-03-11T17:42:31.441858 #21975]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
D, [2020-03-11T17:42:31.449713 #21975] DEBUG -- : resolving DNS for 100.99.83.0...
D, [2020-03-11T17:42:31.449760 #21975] DEBUG -- : IPADDR
D, [2020-03-11T17:42:31.449821 #21975] DEBUG -- : node.rb: resolving node key 'model', with passed global value of '' and node value 'altell'
D, [2020-03-11T17:42:31.449851 #21975] DEBUG -- : node.rb: setting node key 'model' to value 'junos' from global
D, [2020-03-11T17:42:31.449887 #21975] DEBUG -- : node.rb: returning node key 'model' with value 'altell'
D, [2020-03-11T17:42:31.449918 #21975] DEBUG -- : lib/oxidized/node.rb: Loading model "altell"
D, [2020-03-11T17:42:31.450095 #21975] DEBUG -- : lib/oxidized/model/model.rb Added cat `show configuration files | awk '{print "/"$1}'` to the commands list
D, [2020-03-11T17:42:31.450240 #21975] DEBUG -- : node.rb: resolving node key 'input', with passed global value of 'ssh' and node value ''
F, [2020-03-11T17:42:31.450322 #21975] FATAL -- : Oxidized crashed, crashfile written in /opt/oxidized/crash
undefined method `has_key?' for nil:NilClass
Traceback (most recent call last):
        18: from /usr/local/bin/oxidized:23:in `<main>'
        17: from /usr/local/bin/oxidized:23:in `load'
        16: from /var/lib/gems/2.5.0/gems/oxidized-0.27.0/bin/oxidized:8:in `<top (required)>'
        15: from /var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/cli.rb:13:in `run'
        14: from /var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/core.rb:4:in `new'
        13: from /var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/core.rb:4:in `new'
        12: from /var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/core.rb:14:in `initialize'
        11: from /var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/core.rb:14:in `new'
        10: from /var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/nodes.rb:125:in `initialize'
         9: from /var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/nodes.rb:10:in `load'
         8: from /var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/nodes.rb:130:in `with_lock'
         7: from /var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/nodes.rb:130:in `synchronize'
         6: from /var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/nodes.rb:16:in `block in load'
         5: from /var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/nodes.rb:16:in `each'
         4: from /var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/nodes.rb:21:in `block (2 levels) in load'
         3: from /var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/nodes.rb:21:in `new'
         2: from /var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/node.rb:23:in `initialize'
         1: from /var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/node.rb:153:in `resolve_input'
/var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/node.rb:214:in `resolve_key': undefined method `has_key?' for nil:NilClass (NoMethodError)

Any help?

**Comment by ancorrus** [comment]
This was happening because I added my custom model name to `models: {}`  line in the config. Shouldn't have done that, but honestly documentation could use a bit more detail.

Hope this helps someone!

**Comment by ytti** [comment]
Thank you for your honesty, it is appreciated.
