### ISSUE TITLE
Stripped xml tag in pfSense config files

### ISSUE THREAD

**Issue by dra** [ytti/oxidized#2046]
Because of the "cut_head" call in https://github.com/ytti/oxidized/blob/master/lib/oxidized/model/pfsense.rb#L5 the first line containing the xml tag gets stripped; without this line the config file is not accepted by pfSense for a restore.
Tested with several pfSense 2.4.4

Is there any reason for this "cut_head" call?

**Comment by wk** [comment]
Presumably this has removed some undesirable output in the use case of the original contributor. These is no obvious reason to manipulate the configuration file beyond removal of volatile content.

You could make a copy of the `pfsense.rb` model file into `~/.config/oxidized/model/pfsense.rb`, make the necessary modifications (remove the complete `:all` block, lines 4-6), and if this resolves the issue - submit a PR with the change.
