### ISSUE TITLE
Cisco 3550/3560 switches include uptime with configuration stored in Git

### ISSUE THREAD

**Issue by gbbromley** [ytti/oxidized#205]
Cisco 3550/3560 switches appear to include uptime within the configuration pulled and stored in Git

Cisco 3550 diffs
diff --git a/switch3.customer.com b/switch3.customer.com
index 4edd566..ae376e0 100644
--- a/switch3.customer.com
@@ -6,7 +6,7 @@
!
! ROM: Bootstrap program is C3550 boot loader
!
-! switch3 uptime is 1 year, 38 weeks, 2 days, 3 hours, 4 minutes
! System returned to ROM by power-on
! System restarted at 09:23:02 GMT Sat Jan 4 2014
! System image file is "flash:c3550-ipbase-mz.122-25.SEE2.bin"

diff --git a/switch3.customer.com b/switch3.customer.com
index 4edd566..ae376e0 100644
+++ b/switch3.customer.com
@@ -6,7 +6,7 @@
!
! ROM: Bootstrap program is C3550 boot loader
!
+! switch3 uptime is 1 year, 38 weeks, 2 days, 4 hours, 5 minutes
! System returned to ROM by power-on
! System restarted at 09:23:02 GMT Sat Jan 4 2014
! System image file is "flash:c3550-ipbase-mz.122-25.SEE2.bin"

Cisco 3560 diffs

diff --git a/agg.customer.com b/agg.customer.com
index b164ce0..00f3162 100644
--- a/agg.customer.com
@@ -7,7 +7,7 @@
! ROM: Bootstrap program is C3560 boot loader
! BOOTLDR: C3560 Boot Loader (C3560-HBOOT-M) Version 12.2(25r)SEC, RELEASE SOFTWARE (fc4)
!
-! agg uptime is 47 weeks, 5 days, 3 hours, 28 minutes
! System returned to ROM by power-on
! System restarted at 09:25:25 GMT Thu Oct 30 2014
! System image file is "flash:c3560-ipbase-mz.122-25.SEE3/c3560-ipbase-mz.122-25.SEE3.bin"

diff --git a/agg.customer.com b/agg.customer.com
index b164ce0..00f3162 100644
+++ b/agg.customer.com
@@ -7,7 +7,7 @@
! ROM: Bootstrap program is C3560 boot loader
! BOOTLDR: C3560 Boot Loader (C3560-HBOOT-M) Version 12.2(25r)SEC, RELEASE SOFTWARE (fc4)
!
+! agg uptime is 47 weeks, 5 days, 4 hours, 29 minutes
! System returned to ROM by power-on
! System restarted at 09:25:25 GMT Thu Oct 30 2014
! System image file is "flash:c3560-ipbase-mz.122-25.SEE3/c3560-ipbase-mz.122-25.SEE3.bin"

**Comment by ytti** [comment]
Which command outputs that? We need to add ignore for 'uptime' line there.

**Comment by gbbromley** [comment]
Appears to be show version generating that output

**Comment by ytti** [comment]
https://github.com/ytti/oxidized/blob/master/lib/oxidized/model/ios.rb#L31

Looks like we're only taking first line from the output, is uptime really first line on 'sh ver'?

**Comment by gbbromley** [comment]
3560 - sh ver

agg>sh ver
Cisco IOS Software, C3560 Software (C3560-IPBASE-M), Version 12.2(25)SEE3, RELEASE SOFTWARE (fc2)
Copyright (c) 1986-2007 by Cisco Systems, Inc.
Compiled Thu 22-Feb-07 14:40 by myl
Image text-base: 0x00003000, data-base: 0x00EB11A0

ROM: Bootstrap program is C3560 boot loader
BOOTLDR: C3560 Boot Loader (C3560-HBOOT-M) Version 12.2(25r)SEC, RELEASE SOFTWARE (fc4)

agg uptime is 47 weeks, 5 days, 21 hours, 19 minutes
System returned to ROM by power-on
System restarted at 09:25:25 GMT Thu Oct 30 2014
System image file is "flash:c3560-ipbase-mz.122-25.SEE3/c3560-ipbase-mz.122-25.SEE3.bin"

cisco WS-C3560-24TS (PowerPC405) processor (revision E0) with 118784K/12280K bytes of memory.
Processor board ID CAT1116ZM5G
Last reset from power-on
1 Virtual Ethernet interface
24 FastEthernet interfaces
2 Gigabit Ethernet interfaces
The password-recovery mechanism is enabled.

512K bytes of flash-simulated non-volatile configuration memory.
Base ethernet MAC Address       : 00:1C:0E:3D:D1:80
Motherboard assembly number     : 73-9897-06
Power supply part number        : 341-0097-02
Motherboard serial number       : CAT11165P5P
Power supply serial number      : DCA111380RE
Model revision number           : E0
Motherboard revision number     : B0
Model number                    : WS-C3560-24TS-S
System serial number            : CAT1116ZM5G
Top Assembly Part Number        : 800-26160-02
Top Assembly Revision Number    : E0
Version ID                      : V02
CLEI Code Number                : COMMG00ARB
Hardware Board Revision Number  : 0x01


Switch   Ports  Model              SW Version              SW Image
------   -----  -----              ----------              ----------
*    1   26     WS-C3560-24TS      12.2(25)SEE3            C3560-IPBASE-M


Configuration register is 0xF

3550 - sh ver

switch>sh ver
Cisco IOS Software, C3550 Software (C3550-IPBASE-M), Version 12.2(25)SEE2, RELEASE SOFTWARE (fc1)
Copyright (c) 1986-2006 by Cisco Systems, Inc.
Compiled Fri 28-Jul-06 06:17 by yenanh
Image text-base: 0x00003000, data-base: 0x00A539EC

ROM: Bootstrap program is C3550 boot loader

switch uptime is 1 year, 38 weeks, 2 days, 20 hours, 56 minutes
System returned to ROM by power-on
System restarted at 09:23:02 GMT Sat Jan 4 2014
System image file is "flash:c3550-ipbase-mz.122-25.SEE2.bin"

Cisco WS-C3550-48 (PowerPC) processor (revision Q0) with 65526K/8192K bytes of memory.
Processor board ID CAT0909Z1A1
Last reset from warm-reset
Running Layer2/3 Switching Image

Ethernet-controller 1 has 12 Fast Ethernet/IEEE 802.3 interfaces

Ethernet-controller 2 has 12 Fast Ethernet/IEEE 802.3 interfaces

Ethernet-controller 3 has 12 Fast Ethernet/IEEE 802.3 interfaces

Ethernet-controller 4 has 12 Fast Ethernet/IEEE 802.3 interfaces

Ethernet-controller 5 has 1 Gigabit Ethernet/IEEE 802.3 interface

Ethernet-controller 6 has 1 Gigabit Ethernet/IEEE 802.3 interface

48 FastEthernet interfaces
2 Gigabit Ethernet interfaces

The password-recovery mechanism is enabled.
384K bytes of flash-simulated NVRAM.
Base ethernet MAC Address: 00:13:7F:B0:E2:00
Motherboard assembly number: 73-5701-10
Power supply part number: 34-0967-02
Motherboard serial number: CAT09090N42
Power supply serial number: LIT09030CUT
Model revision number: Q0
Motherboard revision number: A0
Model number: WS-C3550-48-SMI
System serial number: CAT0909Z1A1
Configuration register is 0x10F

**Comment by ytti** [comment]
Hmps. I'm confused, we only should be picking the first line of that that output. 

Can you show me your 'ios.rb' file content?

**Comment by gbbromley** [comment]
Also appears to affect Cisco 2960/2950

**Comment by gbbromley** [comment]
ios.rb from /var/lib/gems/2.1.0/gems/oxidized-0.8.1/lib/oxidized/model/ios.rb

class IOS < Oxidized::Model

  prompt /^([\w.@()-]+[#>]\s?)$/
  comment  '! '

  # example how to handle pager
  #expect /^\s--More--\s+.*$/ do |data, re|
  #  send ' '
  #  data.sub re, ''
  #end

  # non-preferred way to handle additional PW prompt
  #expect /^[\w.]+>$/ do |data|
  #  send "enable\n"
  #  send vars(:enable) + "\n"
  #  data
  #end

  cmd :all do |cfg|
    #cfg.gsub! /\cH+\s{8}/, ''         # example how to handle pager
    #cfg.gsub! /\cH+/, ''              # example how to handle pager
    cfg.each_line.to_a[1..-2].join
  end

  cmd :secret do |cfg|
    cfg.gsub! /^(snmp-server community).*/, '\\1 <configuration removed>'
    cfg.gsub! /username (\S+) privilege (\d+) (\S+).*/, '<secret hidden>'
    cfg
  end

  cmd 'show version' do |cfg|
    comment cfg.lines.first
  end

  cmd 'show inventory' do |cfg|
    comment cfg
  end

  cmd 'show running-config' do |cfg|
    cfg = cfg.each_line.to_a[3..-1]
    cfg = cfg.reject { |line| line.match /^ntp clock-period / }.join
    cfg.gsub! /^Current configuration : [^\n]*\n/, ''
    cfg.gsub! /^\ tunnel\ mpls\ traffic-eng\ bandwidth[^\n]*\n*(
                  (?:\ [^\n]*\n*)*
                  tunnel\ mpls\ traffic-eng\ auto-bw)/mx, '\1'
    cfg
  end

  cfg :telnet do
    username /^Username:/
    password /^Password:/
  end

  cfg :telnet, :ssh do
    post_login 'terminal length 0'
    post_login 'terminal width 0'
    # preferred way to handle additional passwords
    if vars :enable
      post_login do
        send "enable\n"
        send vars(:enable) + "\n"
      end
    end
    pre_logout 'exit'
  end

end

**Comment by gbbromley** [comment]
This may relate to installation within Docker and/or Centos. Not seeing these issues with Oxidized on non-Docker installations running upon Ubuntu.

**Comment by ytti** [comment]
And if you quite out the block of 'cmd 'show version'', the problem is gone?

**Comment by gbbromley** [comment]
Yes on the test machines commenting out the section:
cmd 'show version' do |cfg|
  comment cfg
end

Removes the section and appears to only see configuration rather than uptime changes. Looks like a clean function may be required like the powerconnect product.

**Comment by ytti** [comment]
Wait a minute, the line should be 

comment cfg.lines.first not comment cfg

https://github.com/ytti/oxidized/blob/master/lib/oxidized/model/ios.rb#L32


comment cfg.lines.first should take only first line of the output, which ought to be static line.

If you've edited the model to include whole 'sh ver' then this is expected, and you need to remove that uptime line or mask the uptime.

**Comment by gbbromley** [comment]
Sorry it now says:
  #cmd 'show version' do |cfg|
  #  comment cfg.lines.first
  #end

**Comment by ytti** [comment]
What ruby version are you running?

This is what it should be doing:
````
[ytti@lintukoto ~]% irb
irb(main):001:0> "moi\nhei\n jotain muuta\n".lines.first
=> "moi\n"
irb(main):002:0>
````


I.e. only take first line of the 'show version' output, so I'm quite confused.

**Comment by gbbromley** [comment]
On the test systems running Ubuntu 15.04 we have:
user@Ubby:~$ ruby --version
ruby 2.1.2p95 (2014-05-08) [x86_64-linux-gnu]

On production systems Docker systems:
[user@oxidized ~]# ruby --version
ruby 2.0.0p598 (2014-11-13) [x86_64-linux]
Inside the container:
user@oxidized:~# ruby --version
ruby 2.1.5p273 (2014-11-13) [x86_64-linux-gnu]

**Comment by gbbromley** [comment]
Could this be related to the no username in telnet sessions feature? As we are seeing the telnet based switches whihc dont use username auth pulling partial configs sometimes with just
! Password:
sometimes with:
! Password:
! show inventory output sometimes with preceding comment tag ! sometimes without
and sometimes correct expected output
! Password:
! show inventory output 
show running output

The system then diffs the the change output each time

NOTE: Currently show version is disabled

I have removed the telnet no user auth feature on one of the test systems and will monitor over the next day or so the configs for the other IOS devices with show version re-enabled,. and update next week.

**Comment by gbbromley** [comment]
It seems like the issue relates to something specific to our production Docker installations where they appear to get partial information back for telnet based devices, SSH access devices dont appear to suffer from this issue. Test machines on standard VMs dont appear to exhibit these issues.

Closing issue as it appears environment specific.

**Comment by ytti** [comment]
Very curious, if you figure it out, update me regardless.
