### ISSUE TITLE
HP Procurve enable

### ISSUE THREAD

**Issue by konax3** [ytti/oxidized#2057]
Hi to all,

I have a lot of troubles to get the config from the HP Procurve switches, after a few hours of research I be able to connect to the switch modifying the procurve.rb file, changin these lines:

  cfg :telnet do
  #username /Username:/
  #password /Password:/
     username /(Please Enter Login Name|Username):/
     password /(Please Enter Password|Password):/

but now, the switch is asking again for username and password for enable mode, but we can't to login in enable mode.
Any suggestions??

I think is similar to issue number [https://github.com/ytti/oxidized/issues/857](https://github.com/ytti/oxidized/issues/857) but i don't see any clue about if this issue was solved or not.

Thanks in advance.

**Comment by davama** [comment]
How does your logs look?

Debug?

See: https://github.com/ytti/oxidized/blob/master/docs/Configuration.md#advanced-configuration

**Comment by konax3** [comment]
Hi,
this is the debug:

_D, [2020-04-01T14:56:20.474441 #47478] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
W, [2020-04-01T14:56:21.230979 #47478]  WARN -- : 10.238.123.144 raised Oxidized::PromptUndetect with msg "unable to detect prompt: (?-mix:(^"
D, [2020-04-01T14:56:21.231093 #47478] DEBUG -- : lib/oxidized/node.rb: Oxidized::Telnet failed for ACB0284
D, [2020-04-01T14:56:21.231143 #47478] DEBUG -- : lib/oxidized/job.rb: Config fetched for ACB0284 at 2020-04-01 12:56:21 UTC
W, [2020-04-01T14:56:21.475112 #47478]  WARN -- : SES-S/ACB0284 status no_connection, retry attempt 1
D, [2020-04-01T14:56:21.475203 #47478] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 0 of 1
D, [2020-04-01T14:56:21.475261 #47478] DEBUG -- : lib/oxidized/worker.rb: Added SES-S/ACB0284 to the job queue
D, [2020-04-01T14:56:21.475286 #47478] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2020-04-01T14:56:21.475364 #47478] DEBUG -- : lib/oxidized/job.rb: Starting fetching process for ACB0284 at 2020-04-01 12:56:21 UTC
D, [2020-04-01T14:56:21.476109 #47478] DEBUG -- : lib/oxidized/input/ssh.rb: Connecting to ACB0284
D, [2020-04-01T14:56:21.476230 #47478] DEBUG -- : AUTH METHODS::["none", "publickey", "password"]
D, [2020-04-01T14:56:21.476930 #47478] DEBUG -- net.ssh.transport.session[15d38f0]: establishing connection to 10.238.123.144:22
D, [2020-04-01T14:56:21.553068 #47478] DEBUG -- net.ssh.transport.session[15d38f0]: connection established
I, [2020-04-01T14:56:21.553201 #47478]  INFO -- net.ssh.transport.server_version[15d2fe0]: negotiating protocol version
D, [2020-04-01T14:56:21.553253 #47478] DEBUG -- net.ssh.transport.server_version[15d2fe0]: local is `SSH-2.0-Ruby/Net::SSH_5.2.0 x86_64-linux'
D, [2020-04-01T14:56:21.761647 #47478] DEBUG -- net.ssh.transport.server_version[15d2fe0]: remote is `SSH-1.5-OpenSSH_2.9p1'
W, [2020-04-01T14:56:21.761867 #47478]  WARN -- : 10.238.123.144 raised Net::SSH::Exception (rescued RuntimeError) with msg "incompatible SSH"
D, [2020-04-01T14:56:21.761913 #47478] DEBUG -- : lib/oxidized/node.rb: Oxidized::SSH failed for ACB0284
D, [2020-04-01T14:56:22.476508 #47478] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel_

--------------------------------------------------------------------------------------------------------------
 
this is the debug logs of telnet:

_[oxidized@S-AFE-NET-OXD01 logs]$ vi 10.238.123.144-telnet
^[[2J^[[?7l^[[3;23r^[[?6l^[[1;1H^[[?25l^[[1;1HHP J4813A ProCurve Switch 2524
^MSoftware revision F.05.61
^M
^MCopyright (C) 1991-2007 Hewlett-Packard Co.  All Rights Reserved.

^M                           RESTRICTED RIGHTS LEGEND

^M Use, duplication, or disclosure by the Government is subject to restrictions
^M as set forth in subdivision (b) (3) (ii) of the Rights in Technical Data and
^M Computer Software clause at 52.227-7013.

^M         HEWLETT-PACKARD COMPANY, 3000 Hanover St., Palo Alto, CA 94303

8Ht^[[?25h^[[20;39H^[[20;39Hs^[[?25h^[[20;40H^[[1;1H^[[?25l^[[20;40H^[[20;1H
^M^[[?25h^[[20;40H^[[1;24r^[[21;1H^[[21;1HPlease Enter Password: ^[[?25h^[[21;1H^[[?25h^[[21;24H^[[1;1H^[[?25l^[[21;24H^[[21;1H
^M^[[?25h^[[21;24H^[[1;24r^[[22;1H^[[1;1H^[[2K
^M^[[2K
^M^[[2K
^M^[[2K
^M^[[2K
^M^[[2K
^M^[[2K
^M^[[2K
^M^[[2K
^M^[[2K
^M^[[2K
^M^[[2K
^M^[[2K
^M^[[2K
^M^[[2K
^M^[[2K
^M^[[2K
^M^[[2K
^M^[[2K
^M^[[2K
^M^[[2K
^M^[[2K
^M^[[2K
^M^[[2K^[[22;1H^[[1;24r^[[24;1H^[[24;1H^[[2K^[[24;1H^[[?25h^[[24;1H^[[24;1H**acb0284>** ^[[24;1H^[[24;10H^[[24;1H^[[?25h^[[24;10H_

the acb0284 is the prompt.

--------------------------------------------------------------------------------------------------------------
_This is my config file:
[oxidized@S-AFE-NET-OXD01 oxidized]$ vi config
username: XXXXXXXXXXXX
password: XXXXXXXXXXXX
model: junos
resolve_dns: true
interval: 86400
log: /home/oxidized/.config/oxidized/logDEBUG
use_syslog: false
debug: true
threads: 30
timeout: 45
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 0.0.0.0:8888
next_adds_job: false
vars: {}
groups:
       enable: true
models: {}
pid: "/home/oxidized/.config/oxidized/pid"
crash:
  directory: "/home/oxidized/.config/oxidized/crashes"
  hostnames: true
stats:
  history_size: 10
input:
  default: ssh, telnet
  debug: true
  ssh:
    secure: false
  ftp:
    passive: true
  utf8_encoded: true
output:
  default: git
  git:
    user: XXXXXXXXXXXXXX
    email: XXXXXXXXXXXXX
    single_repo: true
    repo: "/home/oxidized/.config/oxidized/devices.DEBUG.git"
source:
  default: csv
  csv:
    file: "/home/oxidized/.config/oxidized/devices.db.DEBUG"
    delimiter: !ruby/regexp /:/
      password: 4
      enable: 5
    gpg: false
model_map:
  juniper: junos
  cisco: ios_
--------------------------------------------------------------------------------------------------------------
this is the device file:

_[oxidized@S-AFE-NET-OXD01 oxidized]$ vi devices.db.DEBUG 
ACB0284:procurve:SES-S:XXXXXXXXXXXX:XXXXXXXXXXXXX:XXXXXXXXXXXX_

**Comment by davama** [comment]
is this log for your HP dev? cuz it's pretty clear the issue
```
W, [2020-04-01T14:56:21.230979 #47478] WARN -- : 10.238.123.144 raised Oxidized::PromptUndetect with msg "unable to detect prompt: (?-mix:(^"
```

Seeing your telnet log you get the crazy characters that HP gives...(gotta love HP!)

There has been several commits in the past on the procurve model changing the `prompt` line, I would try the different ones they had in the past. Also see if updating firmware makes a diff. Or if removing the banner makes a diffs too...

Procurve has alwasy been a pain in the butt....

**Comment by konax3** [comment]
Yes, this is the log, the switch with ip 10.238.123.144 is the acb0284.

By the way, before i've changed the procurve.rb file, i had never seen the prompt in the debug telnet, afer i changed it, i saw the prompt, therefore the oxidized is able to login in the switch. 
I think the problem is now located at enable mode because the switch asks again for username and password, but i'm not sure if the oxidized is sending the enable command, is there any way to confirm this?? maybe an echo or someting like that to confirme in the debug file??

Could be possible is not detecting the prompt because these characters?? 
acb0284> ^[[24;1H^[[24;10H^[[24;1H^[[?25h^[[24;10H_

these characters are invisible if i do a cat of the file but if i do a vi of the file they are there.

maybe the best solution could be a firmware update, thanks for the suggestion.

**Comment by davama** [comment]
>Could be possible is not detecting the prompt because these characters??
acb0284> ^[[24;1H^[[24;10H^[[24;1H^[[?25h^[[24;10H_

if you search procurve in this project or look at the history of the `procurve.rb` file there has been attempts to solve these chars issues.

Did you try removing the banner?

Regarding `enable` see here: https://github.com/ytti/oxidized/blob/master/docs/Configuration.md#privileged-mode

**Comment by konax3** [comment]
Sorry for the delay!
We need to schedule a maintenance window to upgrade the firmware but the error persist with the latest version firmware. The switch is a 2524 and the firmware F_05_80.

We don't have configured the banner. We can acces to the switch with a radius user but we access in operator mode, in the debug the prompt is detected.
The problem goes with the privilege mode, when you type enable the switch asks again for username and password and i think this is the moment when oxidized can't detect the prompt.

We've have configured the enable in our config but we can only put the password not the username and password.

have you checked the issue 857? is the same problem.
