### ISSUE TITLE
Gem Installer Not Uptodate

### ISSUE THREAD

**Issue by NerdBlender** [ytti/oxidized#2058]
Hi,

This isnt really an issue with the software, i just wondered how often the gem installer gets updated, Last one looks to be from last year, and there are some fixes in the newer commits. Is it better to move to using git to keep the install uptodate?

Thanks

**Comment by ytti** [comment]
There is no regular schedule for gem releases. Docker is build on every commit. And of course you can locally build gem for any commit you choose.
