### ISSUE TITLE
Problem with HP switches.

### ISSUE THREAD

**Issue by brancott** [ytti/oxidized#2067]
Hi guys. I have different models of HP switches (1910,1920,1950) they have two different commands for enable mode -" _cmdline-mode on" with two possible passwords and "xtd-cli-mode" with one. I need to get configs from all of them. What is the correct way to specify different credentials for these devices? 
My oxidized gets devices from LibreNMS, so I was thinking of creating overrides in LibreNMS to separate devices in groups by model so I can use different credentials for different groups.
The problem is I can't find a way to separate devices based on model, OS\hostname\location won't work in my case. Is there a way to create such groups? Or is there a better way to make it work?

**Comment by wk** [comment]
This behavior appears to be foreseen by the [comware model](https://github.com/ytti/oxidized/commit/6df0b0606de5fb4a8ec4e2dc936e75a9bd89c3a6) and the correct variation can be passed by setting the `comware_cmdline` variable with the correct per-model password.
