### ISSUE TITLE
Telnet not providing username and password on prompt

### ISSUE THREAD

**Issue by zwechou** [ytti/oxidized#2069]
I am trying to access a device through telnet. It prompts for username and password which I am providing in the config file which isn't being picked up. I tried specifying in multiple places - under models, router.db, vars but still have the same issue of timeout when username is prompted.

Here is the debug log for the device -

tail -f 172.26.13.46-telnet
                              Violators will be prosecuted
abc-abc-EM-01 line 2

username:
% username:  timeout expired!tail: 172.26.13.46-telnet: file truncated

router.db_old -

abc-abc-EM-01:cisco:xxx:yyy

config file - 
username: xxx
password: yyy
model: ios
resolve_dns: true
interval: 3600
use_syslog: true
log: "/home/rancid/.config/oxidized/logs"
debug: true
threads: 30
timeout: 300
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 127.0.0.1:8888
#rest: false
next_adds_job: false
vars:
  username: xxx
  password: yyy
groups: {}
models:
  foundry:
    username: nil
    password: yyy
  cisco:
    username: xxx
    password: yyy
pid: "/home/rancid/.config/oxidized/pid"
crash:
  directory: "/home/rancid/.config/oxidized/crashes"
  hostnames: false
stats:
  history_size: 10
input:
  default: ssh, telnet
  debug: true
  ssh:
    secure: false
  ftp:
    passive: true
  utf8_encoded: true
output:
  default: file
#  directory: "/home/rancid/.config/oxidized/output"
  file:
    directory: "/home/rancid/.config/oxidized/configs"
source:
  default: csv
  csv:
    file: "/home/rancid/.config/oxidized/router.db_old"
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
      username: 2
      password: 3
    #vars_map:
     # username: 2
     # password: 3
    gpg: false
model_map:
  cisco: ios
  juniper: junos
  fortigate: fortios
  cisco: nxos
  cisco: iosxr
  foundry: ironware

This is from /var/log/messages - 
Apr 17 19:25:59 vmwhnsoxs01 oxidized[26059]: 172.26.13.46 raised Net::SSH::Exception (rescued RuntimeError) with msg "incompatible SSH version `SSH-1.5-Cisco-1.25'"
Apr 17 19:26:32 vmwhnsoxs01 oxidized[26059]: 172.26.13.46 raised EOFError (rescued IOError) with msg "end of file reached"
Apr 17 19:26:32 vmwhnsoxs01 oxidized[26059]: /nlv-ar-em-01 status no_connection, retries exhausted, giving up
Apr 17 19:30:01 vmwhnsoxs01 systemd: Started Session 66984 of user root.
Apr 17 19:30:01 vmwhnsoxs01 systemd: Starting Session 66984 of user root.
Apr 17 19:32:51 vmwhnsoxs01 oxidized[26491]: Oxidized starting, running as pid 26491
Apr 17 19:32:51 vmwhnsoxs01 oxidized[26491]: lib/oxidized/nodes.rb: Loading nodes
Apr 17 19:32:51 vmwhnsoxs01 oxidized[26491]: lib/oxidized/nodes.rb: Loaded 1 nodes
Apr 17 19:32:52 vmwhnsoxs01 oxidized[26491]: negotiating protocol version
Apr 17 19:32:52 vmwhnsoxs01 oxidized[26491]: 172.26.13.46 raised Net::SSH::Exception (rescued RuntimeError) with msg "incompatible SSH version `SSH-1.5-Cisco-1.25'"

I have enabled the debug on the global level but no sure why I can't see the messages in logs.

Thanks,
Zwechou

**Comment by wk** [comment]
In the configuration file, it appears the value of `cisco` is overwritten multiple times:

```
cisco: ios
juniper: junos
fortigate: fortios
cisco: nxos
cisco: iosxr
```

The model specified in the device database is `cisco`:
`abc-abc-EM-01:cisco:xxx:yyy`

I expect this will result in only the last definition of the map between `cisco` and that model being utilized, and thus, Oxidized would attempt to log into your device using the `iosxr` model, which is likely not the intended outcome.

Have you attempted to change the database entry for this node from `cisco` to `ios` (and restart Oxidized) to ensure the correct model is used?

**Comment by zwechou** [comment]
wk,

That seems to have changed the behavior. I see telnet pulling the config but it is still not under the output  folder ( mine is "/home/rancid/.config/oxidized/configs"). The full config is in the log folder ("/home/rancid/.config/oxidized/logs) with the name x.x.x.x-telnet.  I don't see any errors in this file.
