### ISSUE TITLE
Ability for "Search in confs" to support regex searches within configurations

### ISSUE THREAD

**Issue by gbbromley** [ytti/oxidized#207]
Currently when using the "Search in confs" button the search terms doesnt appear to support regex. So a search for ^ip http server will return no results, but ip http server returns results for ip http server and also no ip http server.

This limits the usefulness of the search in confs function to generalistic searches, rather than specific searches to identify defective devices.

Coudl we get a regex compatible search field some time?

**Comment by ytti** [comment]
This should be opened in 'oxidized-web' instead of oxidized. I think @FlorianDoublet wrote the feature originally. I'm happy to accept pull requests for this feature, but I'm not going to do it myself.

**Comment by gbbromley** [comment]
Moved to oxidized-web issue tracker - https://github.com/ytti/oxidized-web/issues/33
