### ISSUE TITLE
edgeswitch with enable password does not work

### ISSUE THREAD

**Issue by paszczus** [ytti/oxidized#2070]
`, [2020-04-18T21:14:12.483978 #26332]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
I, [2020-04-18T21:14:12.813519 #26332]  INFO -- : lib/oxidized/nodes.rb: Loaded 1 nodes
show running-config
                        ^
% Invalid input detected at '^' marker.

(UBNT EdgeSwitch) >`

**Comment by mikecook** [comment]
dupe of https://github.com/ytti/oxidized/issues/1853
