### ISSUE TITLE
Import backup manually

### ISSUE THREAD

**Issue by B0redNab** [ytti/oxidized#2074]
Hello guys,

I searched on the documentation and a bit in the open issues and didn't find it, or missed it:
Is there a way to "manually" import a backup to Oxidized and having it display on the web interface?

I'd like to retrieve configuration without having to connect to the host from the Oxidized's VM and executing cmd. But rather, copy the file that contains the configuration of the host from it to Oxidized. 
Is it possible or not intended to?

_I have a working setup for an host (using the usual method) and just copy another file inside the default output config directory doesn't work_

Thanks in advance for your answers
Regards

**Comment by ytti** [comment]
We have exec input method, so you could create model which runs any old shell command and stores the output.

Somethinglike 


```ruby
cmd "cat /tmp/foox" do |cfg|
  cfg
end

cfg :exec {}
```

**Comment by B0redNab** [comment]
I'm not sure i understand correctly:
Using your way mean:

- i get my config file by copying it from the equipment to oxidized.
- i create a model which will display the content of the config file previously retrieved and save it to a "Oxidized config file".

If that's it, yes it could do it but, to be honest, i don't really understand how Oxidized handle file output.
That's probably a dumb question but, to be "detected" by Oxidized and showing up on the web interface, a file musst be created though a model?

**Comment by ytti** [comment]
Only way we can now get any data in, if we run it through some model. But you can create model for arbitrary shell command. So your shell command could be producing that data by any way comfortable to you.

**Comment by B0redNab** [comment]
Ok, thanks for the answer 👍

**Comment by saskuu** [comment]
> We have exec input method, so you could create model which runs any old shell command and stores the output.
> 
> Somethinglike
> 
> ```ruby
> cmd "cat /tmp/foox" do |cfg|
>   cfg
> end
> 
> cfg :exec {}
> ```

thanks for the help. 
Is it possible to transfer the IP address of the switch to the model? 
so that this model can serve multiple switches
example:
cmd "cat /tmp/$ip" do |cfg|
  cfg
end
