### ISSUE TITLE
HPE Office Connect 1920S

### ISSUE THREAD

**Issue by cgalvons** [ytti/oxidized#2076]
Hello,
I was able to set on HPE 1920S Telnet and SSH connection. I was able to copy startup-config file via tftp. However I cannot set 1920S model on Oxidized. I'm sure this model is not a comware, then I supposed to be a procurve but not luck as well. Looks like HPE 1920S is not supported by Oxidized 0.27.0 version yet.
Please, anyone has any tip to fix this unsupported model or a possible solution to fix my problem?

**Comment by systeembeheerder** [comment]
By default the ssh shell is very limited on these budget HPE's. There is a trick to access the full cli, google `_cmdlinemode on`. You could write a custom model adding those commands.
