### ISSUE TITLE
[oxidized-web] Backtrace when accessing node/versions after Ubuntu 2004 LTS Update

### ISSUE THREAD

**Issue by clontarfx** [ytti/oxidized#2077]
ArgumentError at /node/version
wrong number of arguments (given 0, expected 1+)
file: versions.haml location: count line: 24

Exceptions attached.
[ArgumentError at _node_version.zip](https://github.com/ytti/oxidized/files/4550132/ArgumentError.at._node_version.zip)

**Comment by didawubo1** [comment]
I also encountered the same problem, did you solve it？

**Comment by wk** [comment]
This has been solved in [this commit](https://github.com/ytti/oxidized/commit/d96a592be605149f8a4f8d45e8b35e1ed8f3049c), but is not part of any release just yet. Currently, it would be necessary for a user to to locally build the git version of `Oxidized` themselves to overcome this.
