### ISSUE TITLE
 undefined method `size' for nil:NilClass during gem install

### ISSUE THREAD

**Issue by lucasevabou14** [ytti/oxidized#2079]
Hello,

I'am facing a problem durring the installation on a centOS 7. on gen install oxidized-script or -web

`gem install oxidized-script oxidized-web --debug
NOTE:  Debugging mode prints all exceptions even when rescued
Exception `LoadError' at /opt/rh/rh-ruby23/root/usr/share/ruby/resolv.rb:171 - LoadError
Exception `Resolv::DNS::Config::OtherResolvError' at /opt/rh/rh-ruby23/root/usr/share/ruby/resolv.rb:551 - _rubygems._tcp.rubygems.org
Exception `Resolv::ResolvError' at /opt/rh/rh-ruby23/root/usr/share/ruby/resolv.rb:494 - DNS result has no information for _rubygems._tcp.rubygems.org
Exception `Resolv::DNS::Config::OtherResolvError' at /opt/rh/rh-ruby23/root/usr/share/ruby/resolv.rb:551 - _rubygems._tcp.rubygems.org
Exception `Resolv::ResolvError' at /opt/rh/rh-ruby23/root/usr/share/ruby/resolv.rb:494 - DNS result has no information for _rubygems._tcp.rubygems.org
Exception `Errno::EEXIST' at /opt/rh/rh-ruby23/root/usr/share/ruby/fileutils.rb:254 - File exists @ dir_s_mkdir - /opt/rh/rh-ruby23/root/usr/local/share/gems
Exception `NoMethodError' at /opt/rh/rh-ruby23/root/usr/share/rubygems/rubygems/package/tar_reader/entry.rb:135 - undefined method `size' for nil:NilClass
Exception `NoMethodError' at /opt/rh/rh-ruby23/root/usr/share/rubygems/rubygems/package/tar_reader/entry.rb:135 - undefined method `size' for nil:NilClass
ERROR:  While executing gem ... (NoMethodError)
    undefined method `size' for nil:NilClass
        /opt/rh/rh-ruby23/root/usr/share/rubygems/rubygems/package/tar_reader/entry.rb:135:in `read'
        /opt/rh/rh-ruby23/root/usr/share/rubygems/rubygems/package.rb:483:in `initialize'
        /opt/rh/rh-ruby23/root/usr/share/rubygems/rubygems/package.rb:483:in `wrap'
        /opt/rh/rh-ruby23/root/usr/share/rubygems/rubygems/package.rb:483:in `block in read_checksums'
        /opt/rh/rh-ruby23/root/usr/share/rubygems/rubygems/package/tar_reader.rb:116:in `seek'
        /opt/rh/rh-ruby23/root/usr/share/rubygems/rubygems/package.rb:482:in `read_checksums'
        /opt/rh/rh-ruby23/root/usr/share/rubygems/rubygems/package.rb:535:in `block (2 levels) in verify'
        /opt/rh/rh-ruby23/root/usr/share/rubygems/rubygems/package/tar_reader.rb:29:in `new'
        /opt/rh/rh-ruby23/root/usr/share/rubygems/rubygems/package.rb:534:in `block in verify'
        /opt/rh/rh-ruby23/root/usr/share/rubygems/rubygems/package/file_source.rb:30:in `open'
        /opt/rh/rh-ruby23/root/usr/share/rubygems/rubygems/package/file_source.rb:30:in `with_read_io'
        /opt/rh/rh-ruby23/root/usr/share/rubygems/rubygems/package.rb:533:in `verify'
        /opt/rh/rh-ruby23/root/usr/share/rubygems/rubygems/package.rb:514:in `spec'
        /opt/rh/rh-ruby23/root/usr/share/rubygems/rubygems/installer.rb:261:in `spec'
        /opt/rh/rh-ruby23/root/usr/share/rubygems/rubygems/installer.rb:697:in `verify_spec'
        /opt/rh/rh-ruby23/root/usr/share/rubygems/rubygems/installer.rb:837:in `pre_install_checks'
        /opt/rh/rh-ruby23/root/usr/share/rubygems/rubygems/installer.rb:278:in `install'
        /opt/rh/rh-ruby23/root/usr/share/rubygems/rubygems/resolver/specification.rb:97:in `install'
        /opt/rh/rh-ruby23/root/usr/share/rubygems/rubygems/request_set.rb:166:in `block in install'
        /opt/rh/rh-ruby23/root/usr/share/rubygems/rubygems/request_set.rb:156:in `each'
        /opt/rh/rh-ruby23/root/usr/share/rubygems/rubygems/request_set.rb:156:in `install'
        /opt/rh/rh-ruby23/root/usr/share/rubygems/rubygems/commands/install_command.rb:250:in `install_gem'
        /opt/rh/rh-ruby23/root/usr/share/rubygems/rubygems/commands/install_command.rb:300:in `block in install_gems'
        /opt/rh/rh-ruby23/root/usr/share/rubygems/rubygems/commands/install_command.rb:296:in `each'
        /opt/rh/rh-ruby23/root/usr/share/rubygems/rubygems/commands/install_command.rb:296:in `install_gems'
        /opt/rh/rh-ruby23/root/usr/share/rubygems/rubygems/commands/install_command.rb:203:in `execute'
        /opt/rh/rh-ruby23/root/usr/share/rubygems/rubygems/command.rb:308:in `invoke_with_build_args'
        /opt/rh/rh-ruby23/root/usr/share/rubygems/rubygems/command_manager.rb:169:in `process_args'
        /opt/rh/rh-ruby23/root/usr/share/rubygems/rubygems/command_manager.rb:139:in `run'
        /opt/rh/rh-ruby23/root/usr/share/rubygems/rubygems/gem_runner.rb:55:in `run'
        /opt/rh/rh-ruby23/root/usr/bin/gem:21:in `<main>'
`

Installation of oxidized ok 
` oxidized -v
0.27.0`

`ruby -v
ruby 2.3.8p459 (2018-10-18 revision 65136) [x86_64-linux]
`

**Comment by wk** [comment]
From the log above, this appears to be an issue with Internet connectivity or DNS on the host on which you're attempting the installation.

As this does not appear to be an issue with `Oxidized` itself but with the Ruby tooling, I'll close this issue. Additional resources to assist you in troubleshooting this may be available within the Ruby user community.

**Comment by lucasevabou14** [comment]
Hello,

`
It seems that oxidized-script-0.6-0.gem try to resolve _rubygems._tcp.api.rubygems.org that does not exist. I am not sure is the root cause.

gem install ./oxidized-script-0.6.0.gem --debug
NOTE:  Debugging mode prints all exceptions even when rescued
Exception `LoadError' at /opt/rh/rh-ruby25/root/usr/share/ruby/resolv.rb:170 - LoadError
Exception `Resolv::DNS::Config::NXDomain' at /opt/rh/rh-ruby25/root/usr/share/ruby/resolv.rb:546 - _rubygems._tcp.api.rubygems.org
Exception `Resolv::DNS::Config::NXDomain' at /opt/rh/rh-ruby25/root/usr/share/ruby/resolv.rb:546 - _rubygems._tcp.api.rubygems.org
Exception `Resolv::ResolvError' at /opt/rh/rh-ruby25/root/usr/share/ruby/resolv.rb:491 - DNS result has no information for _rubygems._tcp.api.rubygems.org
Exception `Errno::EEXIST' at /opt/rh/rh-ruby25/root/usr/share/ruby/fileutils.rb:232 - File exists @ dir_s_mkdir - /opt/rh/rh-ruby25/root/usr/local/share/gems
Exception `NoMethodError' at /opt/rh/rh-ruby25/root/usr/share/rubygems/rubygems/package/tar_reader/entry.rb:135 - undefined method `size' for nil:NilClass
Exception `NoMethodError' at /opt/rh/rh-ruby25/root/usr/share/rubygems/rubygems/package/tar_reader/entry.rb:135 - undefined method `size' for nil:NilClass
ERROR:  While executing gem ... (NoMethodError)
    undefined method `size' for nil:NilClass
        /opt/rh/rh-ruby25/root/usr/share/rubygems/rubygems/package/tar_reader/entry.rb:135:in `read'
        /opt/rh/rh-ruby25/root/usr/share/rubygems/rubygems/package.rb:495:in `initialize'
        /opt/rh/rh-ruby25/root/usr/share/rubygems/rubygems/package.rb:495:in `wrap'
        /opt/rh/rh-ruby25/root/usr/share/rubygems/rubygems/package.rb:495:in `block in read_checksums'
        /opt/rh/rh-ruby25/root/usr/share/rubygems/rubygems/package/tar_reader.rb:116:in `seek'
        /opt/rh/rh-ruby25/root/usr/share/rubygems/rubygems/package.rb:494:in `read_checksums'
        /opt/rh/rh-ruby25/root/usr/share/rubygems/rubygems/package.rb:547:in `block (2 levels) in verify'
        /opt/rh/rh-ruby25/root/usr/share/rubygems/rubygems/package/tar_reader.rb:29:in `new'
        /opt/rh/rh-ruby25/root/usr/share/rubygems/rubygems/package.rb:546:in `block in verify'
        /opt/rh/rh-ruby25/root/usr/share/rubygems/rubygems/package/file_source.rb:30:in `open'
        /opt/rh/rh-ruby25/root/usr/share/rubygems/rubygems/package/file_source.rb:30:in `with_read_io'
        /opt/rh/rh-ruby25/root/usr/share/rubygems/rubygems/package.rb:545:in `verify'
        /opt/rh/rh-ruby25/root/usr/share/rubygems/rubygems/package.rb:526:in `spec'
        /opt/rh/rh-ruby25/root/usr/share/rubygems/rubygems/installer.rb:264:in `spec'
        /opt/rh/rh-ruby25/root/usr/share/rubygems/rubygems/installer.rb:711:in `verify_spec'
        /opt/rh/rh-ruby25/root/usr/share/rubygems/rubygems/installer.rb:858:in `pre_install_checks'
        /opt/rh/rh-ruby25/root/usr/share/rubygems/rubygems/installer.rb:281:in `install'
        /opt/rh/rh-ruby25/root/usr/share/rubygems/rubygems/resolver/specification.rb:97:in `install'
        /opt/rh/rh-ruby25/root/usr/share/rubygems/rubygems/request_set.rb:277:in `block in install_into'
        /opt/rh/rh-ruby25/root/usr/share/rubygems/rubygems/request_set.rb:269:in `each'
        /opt/rh/rh-ruby25/root/usr/share/rubygems/rubygems/request_set.rb:269:in `install_into'
        /opt/rh/rh-ruby25/root/usr/share/rubygems/rubygems/request_set.rb:148:in `install'
        /opt/rh/rh-ruby25/root/usr/share/rubygems/rubygems/commands/install_command.rb:205:in `install_gem'
        /opt/rh/rh-ruby25/root/usr/share/rubygems/rubygems/commands/install_command.rb:255:in `block in install_gems'
        /opt/rh/rh-ruby25/root/usr/share/rubygems/rubygems/commands/install_command.rb:251:in `each'
        /opt/rh/rh-ruby25/root/usr/share/rubygems/rubygems/commands/install_command.rb:251:in `install_gems'
        /opt/rh/rh-ruby25/root/usr/share/rubygems/rubygems/commands/install_command.rb:158:in `execute'
        /opt/rh/rh-ruby25/root/usr/share/rubygems/rubygems/command.rb:313:in `invoke_with_build_args'
        /opt/rh/rh-ruby25/root/usr/share/rubygems/rubygems/command_manager.rb:173:in `process_args'
        /opt/rh/rh-ruby25/root/usr/share/rubygems/rubygems/command_manager.rb:143:in `run'
        /opt/rh/rh-ruby25/root/usr/share/rubygems/rubygems/gem_runner.rb:59:in `run'
        /opt/rh/rh-ruby25/root/usr/bin/gem:21:in `<main>'
`
