### ISSUE TITLE
Ironware never exit.

### ISSUE THREAD

**Issue by ghost** [ytti/oxidized#208]
I have set up oxidized for some ironware devices.

I can connect and get the configuration, but at the end it's stop at the ">" prompt. :

telnet@ro-rku-1#exit
telnet@ro-rku-1>

After that it retry. and stop again at the same point.

I just comment the logout command on the pre_logout because the command doesn't exist in my devices.

Anyone as an idea ? I try on ironware 5.2, 5.4 and 5.6

**Comment by ytti** [comment]
The model should have 2*exit, to exit from both prompts: https://github.com/ytti/oxidized/blob/master/lib/oxidized/model/ironware.rb#L81

Is this not case for you?

**Comment by Haiironokumo** [comment]
it is the case.
...
post_login ''
    post_login 'skip-page-display'
    post_login 'terminal length 0'
#    pre_logout 'logout'
    pre_logout 'exit'
    pre_logout 'exit'
  end
end

**Comment by ytti** [comment]
Hmm. What was the output line before the first exit?

**Comment by Haiironokumo** [comment]
ip ssh  key-authentication no
!
!
end

telnet@ro-rku-1#exit
telnet@ro-rku-1>

**Comment by ytti** [comment]
Strange, it really should send exit twice. Just for testing, could you try to remove the pre_logout and replace with

````
pre_logout do
  send "exit\n"
  sleep 1
  send "exit\n"
end
```

**Comment by Haiironokumo** [comment]
with this configuration it doesn't send the first exit 

ip ssh  key-authentication no
!
!
end

telnet@ro-rku-1#

that's all i have.

**Comment by ytti** [comment]
Can you put the whole file you have now in http://p.ip.fi

**Comment by Haiironokumo** [comment]
The ironware.rb or the output of the début ?

**Comment by ytti** [comment]
ironware.rb you're using

**Comment by Haiironokumo** [comment]
class IronWare < Oxidized::Model

  prompt /^.*(telnet|ssh)\@.+[#>]\s?$/
  comment  '! '
  
  #to handle pager without enable
  #expect /^((.*)--More--(.*))$/ do |data, re|
  #  send ' '
  #  data.sub re, ''
  #end

  
  #to remove backspace (if handle pager without enable)
  #expect /^((.*)[\b](.*))$/ do |data, re|
  #  data.sub re, ''
  #end

  cmd :all do |cfg|
    cfg.each_line.to_a[1..-2].join
  end

  cmd 'show version' do |cfg|
    cfg.gsub! /(^((.*)[Ss]ystem uptime(.*))$)/, '' #remove unwanted line system uptime
    cfg.gsub! /[Uu]p\s?[Tt]ime is .*/,''

    comment cfg
  end

  cmd 'show chassis' do |cfg|
    cfg.encode!("UTF-8", :invalid => :replace) #sometimes ironware returns broken encoding
    cfg.gsub! /(^((.*)Current temp(.*))$)/, '' #remove unwanted lines current temperature
    cfg.gsub! /Speed = [A-Z]{3} \(\d{2}\%\)/, '' #remove unwanted lines Speed Fans
    cfg.gsub! /current speed is [A-Z]{3} \(\d{2}\%\)/, ''
    cfg.gsub! /\d{2}\.\d deg-C/, 'XX.X deg-C'
    if cfg.include? "TEMPERATURE"
      sc = StringScanner.new cfg
      out = ''
      temps = ''
      out << sc.scan_until(/.*TEMPERATURE/)
      temps << sc.scan_until(/.*Fans/)
      out << sc.rest
      cfg = out
    end
    
    comment cfg
  end
  
  cmd 'show flash' do |cfg|
    comment cfg
  end
  
  cmd 'show module' do |cfg|
    cfg.gsub! /^((Invalid input)|(Type \?)).*$/, '' # some ironware devices are fixed config
    comment cfg
  end

  cmd 'show running-config' do |cfg|
    arr = cfg.each_line.to_a
    arr[3..-1].join unless arr.length < 3
  end

  cfg :telnet do
    # match expected prompts on both older and newer
    # versions of IronWare
    username /^(Please Enter Login Name|Username):/
    password /^(Please Enter )Password:/
  end
  #handle pager with enable
  cfg :telnet, :ssh do
    if vars :enable
      post_login do
        send "enable\r\n"
        send vars(:enable) + "\r\n"
      end
    end
    post_login ''
    post_login 'skip-page-display'
    post_login 'terminal length 0'
    pre_logout do
      send "exit\n"
      sleep 1
      send "exit\n"
    end
  end
end

**Comment by Haiironokumo** [comment]
http://p.ip.fi/72n4

**Comment by skoef** [comment]
@Haiironokumo: does the problem still occurs when you comment out `post_login 'terminal length 0'`? My ironware devices don't recognize this command and throw an error:
```
Invalid input -> length 0
Type ? for a list
```

which somehow messes up what oxidized expects to be returned next.

**Comment by Haiironokumo** [comment]
I try
```
    post_login ''
    post_login 'skip-page-display'
    #post_login 'terminal length 0'
    pre_logout do
      send "exit\n"
      sleep 1
      send "exit\n"
    end
```
and
```
    post_login ''
    post_login 'skip-page-display'
#    post_login 'terminal length 0'
#    pre_logout 'logout'
    pre_logout 'exit'
    pre_logout 'exit'
```
same result as before it never send the second exit.

when i'm logging in my device i can enter the terminal length 0.

**Comment by skoef** [comment]
I can't seem to reproduce it like that as well, however: I've found that on one of my ironware switches, the first run succeeds and when I hit refresh in the webinterface (or wait for the next run obviously) it doesn't send the `logout` command. I've been tracing the source of this, will keep you posted.

**Comment by Haiironokumo** [comment]
Can i do something to help you ?

**Comment by TibshoOT** [comment]
With ironware.rb, I have exactly the same problem.

I tested to add a cmd in main config and to just do a pre_logout with exit. Like:
```ruby
 # TOP OF IRONWARE.RB

  # maybe, only cmd 'quit' could do the job
  cmd 'quit' do |cfg|
    cfg = ''
  end

  cfg :telnet do
    # match expected prompts on both older and newer
    # versions of IronWare
    username /^(Please Enter Login Name|Username):/
    password /^(Please Enter )Password:/
  end

  #handle pager with enable
  cfg :telnet, :ssh do
    if vars :enable
      post_login do
        send "enable\r\n"
        send vars(:enable) + "\r\n"
      end
    end
    post_login ''
    post_login 'skip-page-display'
    post_login 'terminal length 0'
    pre_logout 'exit'
  end
```
In log, I successfuly got a quit + exit but I need to check if there are no fails on a long period.

**Comment by nepbcasander** [comment]
This seems to fix it for me. Looks like the device drops the tcp connection before returning a prompt. Oxidized keeps waiting for the prompt. Hope it helps.

`cmd 'show running-config' do |cfg|
    arr = cfg.each_line.to_a
    arr[2..-1].join unless arr.length < 2
  end

  cmd '' do |cfg|
    cfg = ''
    prompt = ''
  end

  cfg :telnet do
    # match expected prompts on both older and newer
    # versions of IronWare
    username /^(Please Enter Login Name|Username):/
    password /^(Please Enter )Password:/
  end

  #handle pager with enable
  cfg :telnet, :ssh do
    if vars :enable
      post_login do
        send "enable\r\n"
        send vars(:enable) + "\r\n"
      end
    end
    post_login ''
    post_login 'skip-page-display'
    post_login 'terminal length 0'
    pre_logout do
      send "logout\r\n"
      sleep 1
      send "exit\r\n"
      sleep 1
      send "exit\r\n"
    end
  end

end
`

**Comment by ytti** [comment]
Is this still relevant? Do we have PR? Is this fixed?

**Comment by nepbcasander** [comment]
Yes. No. No.

**Comment by ytti** [comment]
@nepbcasander I don't think your ```prompt = ''```does anything but set local variable in that scope.

@PANZERBARON you say that just ```pre_logout 'exit'``` works, does this work for @nepbcasander 

for OP (now deleted user) i can't understand why double 'exit' didn't work. Perhaps the second login prompt has some unprintable characters messing up prompt detection. Input debug file viewed with ```vim``` or other software which shows unprintable would be nice.

Anyone who still has this problem, I'd appreciate access to device where I can recreate this problem.

**Comment by PANZERBARON** [comment]
On ironware, 'logout' command close the session (manual testing), so the double exit did nothing when you do this:

```ruby

**Comment by ytti** [comment]
I think it is device specific. Devices which support ```logout``` are fine. This problem is on devices without ```logout```support. Hopefully I can get access to affected device, so I can fix the model.

**Comment by cardboardpig** [comment]
This also occurs on Multi-Service IronWare 5.8 and 5.9 on the MLX, CER, and CES platforms. "logout" from an elevated prompt merely drops the session to a non-elevated prompt (I know, silly right). This code was sufficient to exit the session:

`pre_logout do
      send "exit\r\n"
      sleep 1
      send "exit\r\n"
end`

Based on my limited telnet packet captures so far I do not see the second exit being sent when the following code is used:

`pre_logout 'exit'
pre_logout 'exit'`

I may be able to supply access to a CER for testing purposes in a couple of weeks.

**Comment by mystica555** [comment]
Try taking out the \r from your 'newline' commands.. These do not like DOS newlines and with \n only it seems to work beautifully
(also some input from ytti on the '"cmd" vars()' bit vs '"send"'

  #handle pager with enable
  cfg :telnet, :ssh do
    if vars :enable
      post_login do
        send "enable\n"
        cmd vars(:enable)
      end
    end
    post_login 'skip-page-display'
    pre_logout 'logout'
    pre_logout 'exit'
    pre_logout 'exit'
  end

**Comment by wendelj** [comment]
I took the knowledge from this thread and put it into a commit and I'll submit a PR for it soon. Hopefully it will work for both older and newer IronWare devices. I only have an older device to test with currently though and it works fine for me.
