### ISSUE TITLE
Cumulus model polling kernel routes

### ISSUE THREAD

**Issue by plett** [ytti/oxidized#2080]
The changes made in PR #537 added some additional features to the Cumulus model, including running `netstat -rn` to collect the kernel routing table. The other changes made in that PR seem solid, but I don't think the current route table is configuration which needs backing up.

I have frequent route changes in my network and this leads to diffs being generated for each of my Cumulus switches on each poll when no configuration has changed.

Would you welcome a PR to remove those lines, or is it functionality that other people find useful?

**Comment by ytti** [comment]
I don't think transient data, like RIB or FIB should be in distribution model. We have mechanism where people can introduce local enhancement and even store that dynamic data to different repo or directory. So I would accept PR to remove any transient data in any model.
