### ISSUE TITLE
Cambium Naming Conventions

### ISSUE THREAD

**Issue by martydingo** [ytti/oxidized#2081]
As promised here, https://github.com/ytti/oxidized/issues/2000, I've fetched the NOS names for Cambium, and it does turn out that I was on the right track. 

The conversation goes like so. 

1.

> Hiya there,
> 
> I'm just following up on an issue that's not with yourselves (https://github.com/ytti/oxidized/issues/2000) but rather I'd like to know the name of the NOS so Oxidized can get the naming conventions right.
> 
> Canopy seems to be the name for the PMP 450 series, however there's no clear name for the ePMP line.
> 
> NOS. Stands for "Network Operating System" and is pronounced "N-O-S."
> 
> If you could let me know what it's officially named, I'd be happy to then provide this information and try and get support added for the ePMP series.

2. 

> Hi Martin,
> 
> Thank you for contacting Cambium Networks. My name is Parikshit, I will assist you with this query.
> 
> As Canopy seems to be the name of PMP radios; moreover Cambium Networks is the name for the complete ePMP line.
> 
> Please let me know if you have any other queries, I will be happy to help you.
> Regards,
> 
> Regards,
> Parikshit Sukdeo Mahajan
> Technical Engineer
> Cambium Networks Global Support

3.

> Hiya there,
> 
> Just to clarify.
> 
> You’re ‘Cambium Networks’, and you install the ‘Cambium Networks’ operating system on a PMP 3000s, but you call the operating system on the PMP 450 series ‘Canopy’?

4.

> Hi Martin,
> 
> Yes, because Canopy was the earlier name, and Canopy has collaborated with Cambium Networks.
> 
> If you have any queries do let me know, I will be happy to help you.
> Regards,
> 
> Regards,
> Parikshit Sukdeo Mahajan
> Technical Engineer
> Cambium Networks Global Support

So it does seem like the PMP 450 support you guys have should be named Canopy, not Cambium, as the NOS that runs on PMP 450 is called Canopy. From there, I can then see if I can build support for Oxidized to pull from ePMP 3000's, which run on the NOS Cambium Networks.

**Comment by adamkuj** [comment]
I have a few comments to add:

The low-end PTP550 backhaul products use the the same underlying OS as the ePMP 3000's. 

PTP820 and PTP850 products are OEM'd by Ceragon, and use a NOS derived from Ceragon's CeraOS.

They have some other product lines too but I don't have experience with them.

I suggest the following oxidized model class names:

CambiumCanopy (i.e. for 450-series PTP and PMP devices - aka "Canopy" NOS)
CambiumEPMP (for EPMP3000-series devices, including low-end PTP devices - aka "Cambium Networks" NOS)
CambiumCeraOS (for Ceragon-derived products - aka CeraOS NOS)

My $0.02

**Comment by martydingo** [comment]
> I have a few comments to add:
> 
> The low-end PTP550 backhaul products use the the same underlying OS as the ePMP 3000's.
> 
> PTP820 and PTP850 products are OEM'd by Ceragon, and use a NOS derived from Ceragon's CeraOS.
> 
> They have some other product lines too but I don't have experience with them.
> 
> I suggest the following oxidized model class names:
> 
> CambiumCanopy (i.e. for 450-series PTP and PMP devices - aka "Canopy" NOS)
> CambiumEPMP (for EPMP3000-series devices, including low-end PTP devices - aka "Cambium Networks" NOS)
> CambiumCeraOS (for Ceragon-derived products - aka CeraOS NOS)
> 
> My $0.02

That's what I also proposed as such in https://github.com/ytti/oxidized/issues/2000

> @ytti Well, this model should be named along the lines of CambiumCanopy, as Canopy is the 'NOS' in use on that, but just Canopy isn't very clear. As the other models are currently not supported it's not so much a bother, but then the ePMP series of NOS would then be 'Cambium-ePMP' and so forth.

The response was

> If model does not work, it usually implies it's different NOS. You're proposing to call them VendorModel, which is not what we want to do, several models can use same NOS.

Considering that the Vendor and the NOS are identical in name for the ePMP series, then I would still hold my opinion on this naming convention. After all, it would have stopped my original issue of configuring the cambium model for support for an ePMP radio.

**Comment by NoifP** [comment]
I'd say the proposal is more along the lines of VendorFamily rather than VendorModel.

+1 for naming like 
CambiumCanopy (i.e. for 450-series PTP and PMP devices - aka "Canopy" NOS)
CambiumEPMP (for EPMP3000-series devices, including low-end PTP devices - aka "Cambium Networks" NOS)
CambiumCeraOS (for Ceragon-derived products - aka CeraOS NOS)

**Comment by martydingo** [comment]
I've actually written support for the CambiumEPMP and it's already named exactly that.

Happy to do a PR if this can get okayed by @ytti.

**Comment by NoifP** [comment]
That'd be awesome! I've just been asked by another team member to get backups going for Cambium ePMP gear (which is how I ended up here)...

**Comment by martydingo** [comment]
> That'd be awesome! I've just been asked by another team member to get backups going for Cambium ePMP gear (which is how I ended up here)...

https://github.com/ytti/oxidized/issues/2000#issuecomment-658669143 

I've written the code and the short instructions on how to install and use it

**Comment by NoifP** [comment]
Thanks @martydingo ! Champion!
