### ISSUE TITLE
[feature-request] Queue failed pushes to remotes

### ISSUE THREAD

**Issue by clontarfx** [ytti/oxidized#2082]
Current use case is oxidized is working fine, however remote gitlab repo is uncontactable. Once repo comes back online, push all queued updates.

I realise that oxidized would push any pending changes from local to remote on *next* change detected, however that means the remote repo (which may be a source of truth) will not contain changes made while it was offline until another change is detected and stored.

**Comment by ytti** [comment]
This seems like you want to periodically do some action under some constraints, for this particular use-case why care about constrains? Why not just periodically push in crontab?

**Comment by clontarfx** [comment]
Was thinking keeping it inside oxidized means we can trust it to complete the workflow on it's own. If oxidized gets a no_connection for a remote host, it can try again at a later date (either a schedule or as it would anyway on next remote push).

You're right, a sysadmin can do this their-selves via cron. But seeing oxidized is already pushing to a remote as part of it's workflow, it also knows when it's failed. Cron would be a hammer solution and not rely on oxidized at all.

**Comment by ytti** [comment]
I'm open to accepting such PR. Basically you'd need to create queue of jobs, where job is deleted only upon success and failure hook can register job.
