### ISSUE TITLE
support for dell equallogic ?

### ISSUE THREAD

**Issue by BedoM** [ytti/oxidized#2085]
hello

Oxidized support DELL equallogic ?

thank you

**Comment by wk** [comment]
This does [not appear to be a currently supported model](https://github.com/ytti/oxidized/blob/master/docs/Supported-OS-Types.md). It may be possible to follow the steps describe [here](https://github.com/ytti/oxidized/blob/master/docs/Creating-Models.md) to add support yourself by creating a model file with the required commands.

The resulting model can then be contributed back to `Oxidized` in the form of a PR for inclusion with the next release.
