### ISSUE TITLE
Radlan/PowerConnect - Temperature recorded resulting in continuous config changes

### ISSUE THREAD

**Issue by ZummiGummi** [ytti/oxidized#2088]
I have multiple Allied Telesis GS8000 switches.

They are mapped to the PowerConnect model.

```
model_map:
 radlan: powerconnect
```
This works for the most part, except that the config is recording the temperate of the switch resulting in Oxidized continuously recording changes when there aren't any.
```
 ! 
 ! Unit            Temperature (Celsius)            Status
 ! ------------------------ ------------------------ ------------------------
-! 1                        37                       OK
+! 1                        40                       OK
 
 
interface range ethernet g(1-47)
 spanning-tree portfast
```
Is there a way to prevent this?

Thanks.

**Comment by graceless70** [comment]
Have a look at my vrtx.rb #2078 

cfg.gsub! /^(\s*Unit\s*Temperature).*/, ''     # *Remove temperature table heading
cfg.gsub! /^((\-{24}\s){2}\-{24}).*$/, ''      # Remove temperature table line
cfg.gsub! /^(\s{10,11}\d).*/, ''                    # Remove temperature table values

You’ll need to adjust the regex for your situation. It will insert blank Lines that will need trimming. I used this

comment cfg.lines.to_a[5..-5].join

The numbers will need adjusting too

Good luck

**Comment by ZummiGummi** [comment]
I'm in docker, so edited 
`/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/model/powerconnect.rb`
Changed line
`if line.match(/Up\sTime|Temperature|Power Suppl(ies|y)|Fans/i) && (@stackable == true)`
to
`if line.match(/Up\sTime|Temperature|Power Suppl(ies|y)|Fans/i)`
