### ISSUE TITLE
When press button "versions" - i get error "ArgumentError at /node/version"

### ISSUE THREAD

**Issue by Otto23** [ytti/oxidized#2089]
![image](https://user-images.githubusercontent.com/10795151/81293979-8d275e00-90b1-11ea-9bfb-f203727a65a9.png)

otto@oxidized:~/.config/oxidized$ oxidized -v
0.27.0

`2020-05-07 12:34:32 - ArgumentError - wrong number of arguments (given 0, expected 1+):
	/var/lib/gems/2.5.0/gems/oxidized-web-0.13.1/lib/oxidized/web/views/versions.haml:24:in `count'
	/var/lib/gems/2.5.0/gems/oxidized-web-0.13.1/lib/oxidized/web/views/versions.haml:24:in `__tilt_70048736381680'
	/var/lib/gems/2.5.0/gems/tilt-2.0.10/lib/tilt/template.rb:170:in `call'
	/var/lib/gems/2.5.0/gems/tilt-2.0.10/lib/tilt/template.rb:170:in `evaluate'
	/var/lib/gems/2.5.0/gems/tilt-2.0.10/lib/tilt/haml.rb:24:in `evaluate'
	/var/lib/gems/2.5.0/gems/tilt-2.0.10/lib/tilt/template.rb:109:in `render'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:823:in `render'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:677:in `haml'
	/var/lib/gems/2.5.0/gems/oxidized-web-0.13.1/lib/oxidized/web/webapp.rb:241:in `out'
	/var/lib/gems/2.5.0/gems/oxidized-web-0.13.1/lib/oxidized/web/webapp.rb:165:in `block in <class:WebApp>'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `call'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `block in compile!'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:994:in `route_eval'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1015:in `block in process_route'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `catch'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `process_route'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:973:in `block in route!'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `each'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `route!'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1085:in `block in dispatch!'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1082:in `dispatch!'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `block in call!'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `call!'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:895:in `call'
	/var/lib/gems/2.5.0/gems/rack-protection-1.5.5/lib/rack/protection/xss_header.rb:18:in `call'
	/var/lib/gems/2.5.0/gems/rack-protection-1.5.5/lib/rack/protection/path_traversal.rb:16:in `call'
	/var/lib/gems/2.5.0/gems/rack-protection-1.5.5/lib/rack/protection/json_csrf.rb:18:in `call'
	/var/lib/gems/2.5.0/gems/rack-protection-1.5.5/lib/rack/protection/base.rb:49:in `call'
	/var/lib/gems/2.5.0/gems/rack-protection-1.5.5/lib/rack/protection/base.rb:49:in `call'
	/var/lib/gems/2.5.0/gems/rack-protection-1.5.5/lib/rack/protection/frame_options.rb:31:in `call'
	/var/lib/gems/2.5.0/gems/rack-1.6.13/lib/rack/nulllogger.rb:9:in `call'
	/var/lib/gems/2.5.0/gems/rack-1.6.13/lib/rack/head.rb:13:in `call'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/show_exceptions.rb:25:in `call'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:182:in `call'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:2013:in `call'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `block in call'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1787:in `synchronize'
	/var/lib/gems/2.5.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `call'
	/var/lib/gems/2.5.0/gems/rack-1.6.13/lib/rack/urlmap.rb:66:in `block in call'
	/var/lib/gems/2.5.0/gems/rack-1.6.13/lib/rack/urlmap.rb:50:in `each'
	/var/lib/gems/2.5.0/gems/rack-1.6.13/lib/rack/urlmap.rb:50:in `call'
	/var/lib/gems/2.5.0/gems/rack-1.6.13/lib/rack/builder.rb:153:in `call'
	/var/lib/gems/2.5.0/gems/puma-3.11.4/lib/puma/configuration.rb:225:in `call'
	/var/lib/gems/2.5.0/gems/puma-3.11.4/lib/puma/server.rb:632:in `handle_request'
	/var/lib/gems/2.5.0/gems/puma-3.11.4/lib/puma/server.rb:446:in `process_client'
	/var/lib/gems/2.5.0/gems/puma-3.11.4/lib/puma/server.rb:306:in `block in run'
	/var/lib/gems/2.5.0/gems/puma-3.11.4/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
`

**Comment by didawubo1** [comment]
I also encountered the same problem, did you solve it

**Comment by Otto23** [comment]
Unfortunately not

**Comment by didawubo1** [comment]
Oh, it's really unfortunate, and I haven't solved it. If it is solved, it
will be shared with you

Otto23 <notifications@github.com> 于2020年5月8日周五 下午8:02写道：

**Comment by johnwick1** [comment]
Same problem here on version 0.27.0 and using git repo

**Comment by wk** [comment]
This has been solved in [this commit](https://github.com/ytti/oxidized/commit/d96a592be605149f8a4f8d45e8b35e1ed8f3049c), but is not part of any release just yet. Currently, it would be necessary for a user to to locally build the git version of `Oxidized` themselves to overcome this.
