### ISSUE TITLE
Environment/Path Issue - New Models

### ISSUE THREAD

**Issue by MattCrumPCN** [ytti/oxidized#2090]
Hi - 

I've added a new model to my home directory /opt/oxidized/.config/oxidized/osname.rb then restarted Oxidized as a service using systemctl restart oxidized (service config is below).

I'm pulling devices from librenms and this works fine for known device types, but it doesn't work for this new device type:

`node {:name=>"1.2.3.4", :model=>"osname", :group=>"default"} raised Oxidized::ModelNotFound with message 'osname' not found for node 1.2.3.4'`

I then added the model file to the absolute path of the Ruby file structure instead, and it now loads up OK:

/opt/rh/rh-ruby23/root/usr/local/share/gems/gems/oxidized-0.27.0/lib/oxidized/model/

I think there's something wrong with my environment configuration as oxidized as a bare command does not work as the oxidized user, or as root.

Oxidized service config is as follows - please let me know if you need to see anything else:

```
#For debian 8 put it in /lib/systemd/system/
#To set OXIDIZED_HOME instead of the default:
# ~${oxidized_user}/.config/oxidized in debian 8, then uncomment
#(and modify as required) the "Environment" variable below so
#systemd sets the correct environment. Tested only on Debian 8.8.
#YMMV otherwise.
#
#For RHEL / CentOS 7 put it in /etc/systemd/system/
#and call it with systemctl start oxidized.service

[Unit]
Description=Oxidized - Network Device Configuration Backup Tool
After=network-online.target multi-user.target
Wants=network-online.target

[Service]
ExecStart=/opt/rh/rh-ruby23/root/usr/local/bin/oxidized
User=oxidized
KillSignal=SIGKILL
Environment="OXIDIZED_HOME=/opt/oxidized"
Restart=on-failure
RestartSec=300s

[Install]
WantedBy=multi-user.target
```

**Comment by ytti** [comment]
Thye model directory has model in it. ~/.config/oxidized/model/model.rb

**Comment by pflintoff** [comment]
I am having exactly the same issue.

E, [2020-06-19T15:42:21.617983 #3337] ERROR -- : node {:name=>"nyc-fw02-admin", :ip=>"10.250.1.1", :model=>"asasi", :group=>"cisco_tac"} raised Oxidized::ModelNotFound with message 'asasi not found for node 10.250.1.1'

#ls -la
-rw-r--r-- 1 oxidized oxidized 2038 Jun 19 15:42 asasi.rb
#pwd
/opt/oxidized/.config/oxidized/model

# less asasi.rb 
class ASASI < Oxidized::Model
  # Cisco ASA Single Instance model for collection of just a single context config#
  < SNIP >
  

###
This model works fine if I place it into the gem models folder.
The oxidized user that runs the process has /opt/oxidized as it's home folder.
Also we have the variable Environment="OXIDIZED_HOME=/opt/oxidized" called in the System start up file.
The file is definitely in:
/opt/oxidized/.config/oxidized/model/

**Comment by ytti** [comment]
The correct location for OXIDIZED_HOME is `$OXIDIZED_HOME/model/name.rb`, i..e. we can think that implied oxidized home is `$HOME/.config/oxidized`

**Comment by pflintoff** [comment]
Yes, that fixed it. Thanks very much.
Merging different install examples has led to a misconfiguration of $OXIDIZED_HOME
