### ISSUE TITLE
Adding a device to Oxidized..

### ISSUE THREAD

**Issue by AbuT100** [ytti/oxidized#2091]
I am unable to add a fortigate firewall device to oxidized.  getting error "no connection" on the web gui.

There are 2  previous fortios fw's that have been added to Oxidized successfully;    i am adding the new firewall to the router.db file using similar details to the previous firewalls.  The node is showing up on the web but the status is showing as unknown red and no connection.

i am able to ssh onto the fortigate fw with the credentials from the oxidized sever and have checked that the authentication is similar to the (working) other fw. 

can someone advise if there is another node setting that maybe causing this device to not poll with Oxidized?

**Comment by DarkCatapulter** [comment]
Share your oxidized config and your log output so we can better identify the problem. Make sure to set 'debug: true' in your config before sharing your log. Also make sure to not share any personal or secret information when sharing your config (usernames, passwords, domains that identify your company etc).

**Comment by AbuT100** [comment]
there is no issues with how oxidized is working it is backing up the config for 2 other Fortigate clusters but just not able to back up to fgtcl6-thn , the logs are showing timeouts no connection and retry etc, however i am able to log into that device from the oxidized server

the config is as follows:

username: Rancid
password: ******
model: junos
interval: 600
use_syslog: false
debug: false
threads: 30
timeout: 30
retries: 2
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
#rest: 172.31.47.62:8888
rest: 127.0.0.1:8888
rest_hide_enable: true
#vars: {}
vars: {remove_secret}
groups: {}
log: "/home/oxidized/.config/oxidized/log"
pid: "/home/oxidized/.config/oxidized/pid"
input:
  default: ssh, telnet
  debug: ~/.config/oxidized/log_input
  debug: false
  utf8_encoded: false
  ssh:
    secure: false
output:
  default: git
  git:
    user: Oxidized
    email: o@example.com
    repo: "/home/oxidized/devices.git"
source:
  default: csv
  csv:
    file: "/home/oxidized/.config/oxidized/router.db"
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
      username: 2
      password: 3
    vars_map:
      enable: 4
      ssh_port: 5
model_map:
  cisco: ios
  juniper: junos
  ciena: saos


Logs showing the fortigate not connecting 


W, [2020-05-19T12:15:40.041179 #3824]  WARN -- : /fgtcl6-thn.fw.vaioni.net status no_connection, retries exhausted, giving up
W, [2020-05-19T12:20:54.161364 #3824]  WARN -- : /fgtcl6-hex.fw.vaioni.net status no_connection, retry attempt 1
W, [2020-05-19T12:21:58.135935 #3824]  WARN -- : /fgtcl6-hex.fw.vaioni.net status no_connection, retry attempt 2
W, [2020-05-19T12:23:01.547707 #3824]  WARN -- : /fgtcl6-hex.fw.vaioni.net status no_connection, retries exhausted, giving up
W, [2020-05-19T12:26:43.767485 #3824]  WARN -- : /fgtcl6-thn.fw.vaioni.net status no_connection, retry attempt 1
W, [2020-05-19T12:27:46.782708 #3824]  WARN -- : /fgtcl6-thn.fw.vaioni.net status no_connection, retry attempt 2
W, [2020-05-19T12:28:49.864199 #3824]  WARN -- : /fgtcl6-thn.fw.vaioni.net status no_connection, retries exhausted, giving up
W, [2020-05-19T12:34:05.517201 #3824]  WARN -- : /fgtcl6-hex.fw.vaioni.net status no_connection, retry attempt 1
W, [2020-05-19T12:35:08.935112 #3824]  WARN -- : /fgtcl6-hex.fw.vaioni.net status no_connection, retry attempt 2
W, [2020-05-19T12:36:12.631927 #3824]  WARN -- : /fgtcl6-hex.fw.vaioni.net status no_connection, retries exhausted, giving up
W, [2020-05-19T12:39:53.082940 #3824]  WARN -- : /fgtcl6-thn.fw.vaioni.net status no_connection, retry attempt 1
W, [2020-05-19T12:40:56.099935 #3824]  WARN -- : /fgtcl6-thn.fw.vaioni.net status no_connection, retry attempt 2
W, [2020-05-19T12:41:59.159945 #3824]  WARN -- : /fgtcl6-thn.fw.vaioni.net status no_connection, retries exhausted, giving up
W, [2020-05-19T12:47:15.730751 #3824]  WARN -- : /fgtcl6-hex.fw.vaioni.net status no_connection, retry attempt 1
W, [2020-05-19T12:48:19.245712 #3824]  WARN -- : /fgtcl6-hex.fw.vaioni.net status no_connection, retry attempt 2
W, [2020-05-19T12:49:22.716075 #3824]  WARN -- : /fgtcl6-hex.fw.vaioni.net status no_connection, retries exhausted, giving up
W, [2020-05-19T12:53:02.179268 #3824]  WARN -- : /fgtcl6-thn.fw.vaioni.net status no_connection, retry attempt 1
W, [2020-05-19T12:54:05.194654 #3824]  WARN -- : /fgtcl6-thn.fw.vaioni.net status no_connection, retry attempt 2
W, [2020-05-19T12:55:08.218382 #3824]  WARN -- : /fgtcl6-thn.fw.vaioni.net status no_connection, retries exhausted, giving up
root@ip-10-2-0-62:/home/oxidized/.config/oxidized#

**Comment by AbuT100** [comment]
in the router.db

the 2 working fortigates look like 

fgtcl7-hex.fw.xx.net:fortios:admin:********::8888
fgtcl7-thn.fw.xx.net:fortios:admin:********::8888
fgtcl8-hex.fw.xx.net:fortios:admin:********::8888
fgtcl8-thn.fw.xx.net:fortios:admin:********::8888

and the below one is not working 

fgtcl6-hex.fw.xx.net:fortios:admin:********::8888
fgtcl6-thn.fw.xx.net:fortios:admin:********::8888


i have 2 more to add along with this one above they are showing similar issues. i am wondering if these were added previously and need removing fully before re-adding?

**Comment by DarkCatapulter** [comment]
I don't think you need to remove the ones that are already working. Also please read what I typed a little bit more careful next time. I told you to enable debug, and then share your log using pastebin.

Please follow these steps:

1. Enable debugging in your oxidized config file. This is done by changing `debug: false` to `debug: true`
2. Try adding your FortiGate to oxidized again. This is gonna fail, but it will generate logs.
3. Share your logs here, but this time please use https://pastebin.com/

**Comment by AbuT100** [comment]
debug logs are as follow i have removed for any other devices 

https://pastebin.com/n9C6TFRc

**Comment by AbuT100** [comment]
I have included the debug logs 

https://pastebin.com/DbPkh1Qw

**Comment by DarkCatapulter** [comment]
Looking at your debug logs, it seems like Oxidized actually manages to login and execute commands for `fgtcl6-hex.fw.xx.net`.
```lib/oxidized/input/cli.rb: Running post_login commands at fgtcl6-hex.fw.xx.net
lib/oxidized/input/ssh.rb get system status @ fgtcl6-hex.fw.xx.net with expect: /^([-\w.~]+(\s[(\w\-.)]+)?~?\s?[#>$]\s?)$/
lib/oxidized/input/ssh.rb get hardware status @ fgtcl6-hex.fw.xx.net with expect: /^([-\w.~]+(\s[(\w\-.)]+)?~?\s?[#>$]\s?)$/
lib/oxidized/input/ssh.rb config global @ fgtcl6-hex.fw.xx.net with expect: /^([-\w.~]+(\s[(\w\-.)]+)?~?\s?[#>$]\s?)$/```

**Comment by NoifP** [comment]
I'm not sure if you have already got this fixed @AbuT100 but maybe there are some things on the fortigate side? Maybe some of these will help?
* You may need to connect to the dedicated management interface IP (of the member) to be sure you are getting backups from the correct device.
* Oxidized needs to connect to the management VDOM.
* If you haven't already got dedicated management ports setup see this: https://kb.fortinet.com/kb/documentLink.do?externalID=FD32214

**Comment by davidschoefberger** [comment]
@AbuT100 did you manage to fix the issue? I'm now running into the same issue with two FortiGates after the upgrade to 7.0.11. Other FortiGates with the same version don't cause any issues.

**Comment by Faddy96** [comment]
Hi @davidschoefberger, do you see `no_connection` in your logs similar to what @AbuT100 had when creating this ticket? If so, could you please share your Oxidized logs with debug set to true?

I don't think that Oxidized is the culprit here, I would advice that you check the following on your failing FortiGate(s).

- Check that the interface configured with your FortiGate's MGMT IP-address that SSH is allowed.
- Verify that the IP of your Oxidized server is included in the FortiGate's list of Trusted Hosts (System > Administrators).

**Comment by davidschoefberger** [comment]
Hi @Faddy96,
thanks for your input! I just found the issue. It was the timeout setting, I had it at 30 seconds, already increased it to 120 seconds, same issue. Now I changed it to 300 seconds and that worked. Looks like oxidized just needs quite some time.
