### ISSUE TITLE
Rugged::ReferenceError: cannot push non-fastforwardable reference

### ISSUE THREAD

**Issue by chenhsien** [ytti/oxidized#2094]
I have created a new github repo for security reason to keep the config files. With this new repo, i got this error:
Hook push_to_remote (#<GithubRepo:0x000000000109dcc8>) failed (#<Rugged::ReferenceError: cannot push non-fastforwardable reference>) for event :post_store

This is what i have in the config file:
output:
  default: git
  git:
    user: oxidized
    email: oxidized@company.com
    repo: "/home/oxidized/.config/oxidized/gh-repos/default.git"
    type_as_directory: true
    single_repo: true

hooks:
  push_to_remote:
    type: githubrepo
    events: [post_store]
    remote_repo: https://git.company.com/naas/network-configs.git
    username: svc_p_oxidized
    password: [removed]

I read somewhere that i need to do a manual merge, I'm new to oxidized and git. May I know the steps for perform manual merge ? And where should i perform the steps ?

**Comment by wk** [comment]
The steps are roughly such:
- Create your remote repository `naas/network-configs`
- On the `Oxidized` installation, execute the following workflow:

```bash
$ cd /home/oxidized/.config/oxidized/gh-repos/default.git # change directory into your local git config repo
$ git remote add remote-repo https://git.company.com/naas/network-configs.git # add a git remote called `remote-repo` pointing to your remote repository
$ git push remote-repo -f # force-push the current state of the local git repo to the remote-repo, this will override all data in the target repository!
```

This only needs to be done once, after executing this workflow, further commits with the `githubrepo` hook should succeed.

**Comment by chenhsien** [comment]
thank you !

**Comment by JacBra** [comment]
@wk : Thanks a lot for your post!
