### ISSUE TITLE
backup fortinet firwall ，but the web UI display backup failed

### ISSUE THREAD

**Issue by jixianbo** [ytti/oxidized#2095]
W, [2020-05-15T04:00:42.845136 #27]  WARN -- : 10.0.1.30 raised Timeout::Error with msg "execution expired"
D, [2020-05-15T04:00:42.845221 #27] DEBUG -- : lib/oxidized/node.rb: Oxidized::SSH failed for ZBJRG-B1-FG12-FW-01
D, [2020-05-15T04:00:42.845265 #27] DEBUG -- : lib/oxidized/job.rb: Config fetched for ZBJRG-B1-FG12-FW-01  at 2020-05-15 04:00:42 UTC
W, [2020-05-15T04:00:43.383201 #27]  WARN -- : JRG/ZBJRG-B1-FG12-FW-01  status no_connection, retry attempt 2
D, [2020-05-15T04:00:43.383291 #27] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 0 of 1
D, [2020-05-15T04:00:43.383385 #27] DEBUG -- : lib/oxidized/worker.rb: Added JRG/ZBJRG-B1-FG12-FW-01  to the job queue
D, [2020-05-15T04:00:43.383408 #27] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel

**Comment by jixianbo** [comment]
username: username #服务不检测，此项在router.db中检测
password: password #服务不检测，此项在router.db中检测
model: junos #服务不检测，此项在router.db中检测
interval: 3600 #自动备份时间，默认3600s
log: /root/.config/oxidized/logs/oxidized.log
debug: true
threads: 50
timeout: 30
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/ #网络设备登录后匹配的提示符
rest: 0.0.0.0:8888 #web访问的地址，实际通过nginx重定向此地址
next_adds_job: false
vars:
  remove_secret: true
  ssh_no_keepalive: true
  auth_methods: ["none", "publickey", "password", "keyboard-interactive"]
groups: {}
models: {}
pid: "/root/.config/oxidized/pid"
input:
  default: ssh
  debug: false
  ssh:
   secure: false
output:
  default: file
  file:
    directory: "/root/.config/oxidized/configs" 
output:
  default: git
  git:
    user: Oxidized
    email: o@example.com
    repo: "home/oxidized/.config/oxidized/oxidized.git"
source:
  default: csv
  csv:
    file: "/root/.config/oxidized/router.db"
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
      ip: 2
      username: 3
      password: 4
      group: 5
    gpg: false
model_map: #服务不检测，此项在router.db中检测
  cisco: ios #服务不检测，此项在router.db中检测
  juniper: junos #服务不检测，此项在router.db中检
  fortigate: fortios

**Comment by jixianbo** [comment]
someone can help me

**Comment by DarkCatapulter** [comment]
I can see that you gave debugging on, Can you share your log file in [pastebin](https://pastebin.com/) so we can get a better picture of the issue?

**Comment by jixianbo** [comment]
![捕获](https://user-images.githubusercontent.com/18465462/82653865-70169180-9c52-11ea-8144-10bdf0f2c725.PNG)

**Comment by DarkCatapulter** [comment]
Have you verified that your firewalls allow your Oxidized to access them on SSH (tcp/22)?

**Comment by jixianbo** [comment]
I an sure firewalls allows oxidized server to access them used SSH,because oxidized/logs haved the firewalls configures and on oxidized server used ssh can login the firewall.

**Comment by jixianbo** [comment]
![捕获](https://user-images.githubusercontent.com/18465462/82774783-62425580-9e78-11ea-8445-4b2c642c061b.PNG)

**Comment by DarkCatapulter** [comment]
If you look in your Oxidized config, do you see the field that sais `timeout: 30`?
If you try increasing it from 30 to 200, does that fix your problem?

**Comment by DarkCatapulter** [comment]
Okay so this is what I think is happening, I experienced a similar issue as you @jixianbo today but on another model. Oxidized manages to SSH to your devices, but for some reason it cannot find your prompt. This could be because the connection to your device is slow. It could be a bug with the `fortios.rb` model, but we can't know for sure.

In your config, try changing `timeout: 30` from 30 -> 200.
