### ISSUE TITLE
API /nodes/next/ seems to crash oxidized if only one host in db

### ISSUE THREAD

**Issue by Gulars2000** [ytti/oxidized#2099]
seems to crash oxidised if only one host is defined in db.

When i did this for experimenting i get flodded with debug messages:
D, [2020-05-16T10:20:32.755818 #1] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 1 of 2 - ended: 0 of 1
D, [2020-05-16T10:20:32.755947 #1] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 1 of 2 - ended: 0 of 1
D, [2020-05-16T10:20:32.755980 #1] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 1 of 2 - ended: 0 of 1

**Comment by wk** [comment]
This appears to be a web UI issue, please re-open it under the ytti/oxidized-web repository. Closing it here meanwhile.
