### ISSUE TITLE
0.26.3 - Git Blame

### ISSUE THREAD

**Issue by jacp9** [ytti/oxidized#2102]
Hi

Oxidized version 0.26.3.

I've enabled syslog.rb to run on startup (with rest_client.rb in the same dir), and syslog config backup trigger works as expected, however, when checking git blame in gitlab (got output setup as git, and webhook push_to_remote, type: githubrepo), all changes are blamed on oxidized service user in gitlab, instead of the username commiting the actual change on the device.

Any idea what I am missing here? The device type is Juniper.

```   def jnpr(ipaddr, log, index)
      # TODO: we need to fetch 'ip/name' in mode == :file here
      user = log[index + 2][1..-2]
      msg  = log[(index + 6)..-1].join(' ')[10..-2]
      msg  = nil if msg == 'none'
      rest(user: user, msg: msg, model: 'jnpr', ip: ipaddr,
           name: getname(ipaddr))
    end
```

The actual syslog message with the username passed within.

`May 18 13:13:24  mx12 mgd[4425]: UI_COMMIT: User 'junos' requested 'commit' operation (comment: none)`

**Comment by ytti** [comment]
First thing I'd do, is add some debugging to the code, to ensure that the REST is firing. Another thing I'd consider is update to latest version.

Definitely your expectation is right, you should see the commit comment and commit user in `git blame`, but why is it not working, I cannot conclusively answer.

**Comment by jacp9** [comment]
I don't really have the skill set to debug code written in ruby, but I can try to upgrade to the latest version.

Strangely enough, I do see the commit message make it through to the gitlab, so I think that proves that the REST is firing as expected. It's just that the username is not.

**Comment by ytti** [comment]
you could for example just add `p user` in the code, to see  what it prints, you could also add `p log` to see what the log contains.

**Comment by jacp9** [comment]
thanks, I added those in and that's what it looks like:

```["<189>May", "18", "14:27:44", "mx12", "mgd[4425]:", "UI_COMMIT:", "User", "'junos'", "requested", "'commit'", "operation", "(comment:", "test)"]
"junos"
["<189>May", "18", "14:28:36", "mx12", "mgd[4425]:", "UI_COMMIT:", "User", "'junos'", "requested", "'commit'", "operation", "(comment:", "none)"]
"junos"
["<189>May", "18", "14:30:01", "mx1234", "mgd[4425]:", "UI_COMMIT:", "User", "'junos'", "requested", "'commit'", "operation", "(comment:", "new", "name-server)"]
```

I can then see webhook function as expected:

```
May 18 14:30:16 company oxidized[2557]: Configuration updated for junos-mgmt/mx1
May 18 14:30:16 company oxidized[2557]: GithubRepo: Pushing local repository(/etc/oxidized/.config/oxidized/configs.git/)...
May 18 14:30:16 company oxidized[2557]: GithubRepo: to remote: git@gitlab.lab.net:oxidized/configs.git```

Again, I can see the comment for instance "new name-server", but the gitlab blame shows:

`oxidized committed just now`

**Comment by ytti** [comment]
I'm not 100% sure what is going on. We need to investigate few things

a) is gitlab actually looking at email and translating that to something (we don't change mail)
    ==> we could clone the repo and do 'git blame file' to see what it prints 

b) we actually passing the username all the way: https://github.com/ytti/oxidized/blob/master/lib/oxidized/output/git.rb#L179
`p @user` here to see what we're actually sending. 

We know we parse the user right but we still have to know
1. We sent it in POST in rest call
2. oxidized-web passes it to oxidized while calling Nodes#next
3. git-store gets it and users it

**Comment by ytti** [comment]
I think this is just how gitlab renders it, gitlab is looking email and translates the mail to internal string. And you probably have something in gitlab with that email. If you use 'git blame' in shell, you probably see it correctly.

Observe these: 'git blame' shows actual name 'Saku Ytti' or 'ytti', but gitlab shows just 'Saku Ytti', because both names have same email, and gitlab has that email, so gitlab is showing gitlab user of the email, instead of what the commit says.

![screenshot 2020-5-18 kello 17 49 28](https://user-images.githubusercontent.com/200527/82227038-ed2ec780-992f-11ea-842d-43fe0b53f86f.png)
![screenshot 2020-5-18 kello 17 49 45](https://user-images.githubusercontent.com/200527/82227083-f7e95c80-992f-11ea-92ec-67291d8ff5ec.png)

**Comment by ytti** [comment]
If you want gitlab to show it

1. perhaps not have the email attached to gitlab user
2. perhaps open issue to gitlab to allow rendering username verbatim
3. perhaps hack the syslog.rb/rest to send manipulated email, perhaps user@your.domain

**Comment by jacp9** [comment]
You are absolutely right - the gitlab oxidized service user had e-mail address set to what the oxidized service user on the server itself was configured with.

After the e-mail address within gitlab to a different value such as noreply@example.com, I then saw correct username logged against the commit messages.

Some good troubleshooting steps on here too - I've learnt something.

Thanks for your help - much appreciated.
