### ISSUE TITLE
cat't start oxidized whit docker

### ISSUE THREAD

**Issue by echoo99** [ytti/oxidized#2104]
Can some one help me?
this is the log

[root@localhost oxidized]# docker run -v /etc/oxidized:/root/.config/oxidized -p 8888:8888/tcp -t oxidized/oxidized:latest
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/my_init.d/10_syslog-ng.init...
May 19 16:45:47 9826c504aff2 syslog-ng[15]: syslog-ng starting up; version='3.13.2'
*** Booting runit daemon...
*** Runit started as PID 24
May 19 16:45:48 9826c504aff2 cron[30]: (CRON) INFO (pidfile fd = 3)
May 19 16:45:48 9826c504aff2 cron[30]: (CRON) INFO (Running @reboot jobs)
Permission denied @ apply2files - /root/.config/oxidized/pid
Permission denied @ apply2files - /root/.config/oxidized/pid
Permission denied @ apply2files - /root/.config/oxidized/pid
Permission denied @ apply2files - /root/.config/oxidized/pid
Permission denied @ apply2files - /root/.config/oxidized/pid
Permission denied @ apply2files - /root/.config/oxidized/pid
Permission denied @ apply2files - /root/.config/oxidized/pid
Permission denied @ apply2files - /root/.config/oxidized/pid
^C

the config file is below:
[root@localhost oxidized]# cat config
---
username: username
password: password
model: junos
resolve_dns: false
log: /var/log/oxidized.log
interval: 3600
use_syslog: false
debug: false
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 127.0.0.1:8888
next_adds_job: false
vars: {}
groups: {}
models: {}
pid: "/root/.config/oxidized/pid"
crash:
  directory: "/root/.config/oxidized/crashes"
  hostnames: false
stats:
  history_size: 10
input:
  default: ssh, telnet
  debug: false
  ssh:
    secure: false
  ftp:
    passive: true
  utf8_encoded: true
output:
  default: git
  git:
    user: Mansur
    email: i@nbma.info
    repo: "/root/.config/oxidized/backup_conf/devices.git"
  file:
    directory: "/root/.config/oxidized/configs"
hooks:
  push_to_remote:
    type: githubrepo
    events: [post_store]
    user: Mansur
    email: i@nbma.info
    remote_repo: git@nbma.info:mansur/test-oxidized.git
    publickey: /root/.ssh/id_rsa.pub
    privatekey: /root/.ssh/id_rsa
source:
  default: csv
  csv:
    file: "/root/.config/oxidized/router.db"
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      ip: 1
      model: 2
      username: 3
      password: 4
    gpg: false
model_map:
  cisco: ios
  juniper: junos

**Comment by echoo99** [comment]
provide more information:
[root@localhost oxidized]# ls -lrt
total 8
-rw-r--r--. 1 oxidized root 1218 May 20 00:24 config
-rw-r--r--. 1 oxidized root   65 May 20 00:26 router.db
drwxrwxrwx. 2 oxidized root    6 May 20 00:28 logs
-rw-r--r--. 1 oxidized root    0 May 20 00:31 pid
[root@localhost oxidized]#

**Comment by wk** [comment]
The error suggests your docker container can't successfully write to the pid file which `oxidized` attempts to create at startup.

From the look of your prompt, it appears you've set up (and are editing files) in `/root/oxidized` on the host system, the volume flag you're passing to docker, however, `-v /etc/oxidized:/root/.config/oxidized`, expects you to use /etc/oxidized on the host system as a persistent host volume data location for this container.

Create the directory (`mkdir -p /etc/oxidized`), copy your configuration there (`cp /root/oxidized/* /etc/oxidized/`), chown it to be owned by root, as that's the user under which oxidized runs inside the container (`chown -R root:root /etc/oxidized`), destroy the running container `docker ps -a`, then `docker stop <container name or ID>` and `docker rm <container name or ID>`), and attempt this again with a fresh container.

**Comment by echoo99** [comment]
have been resloved
