### ISSUE TITLE
Helm chart?

### ISSUE THREAD

**Issue by jhoblitt** [ytti/oxidized#2108]
This is a request for information.  Does anyone know of an existing helm chart to deploy oxidized?  If not, are there any blockers to deploying oxidized on k8s?

**Comment by wk** [comment]
There should be no hard blockers that prevent Oxidized from running on k8s, with the possible caveat of needing a read-write PersistentVolumeClaim, as Oxidized expects to be able to both read and write to its configuration directory out of the box.
