### ISSUE TITLE
ProCurve Switches keyboard-interactive authentication fails

### ISSUE THREAD

**Issue by jaannnis** [ytti/oxidized#2109]
I got a load of HP procurve switches which oxidized is unable to log in to using keyboard-interavtive authentication.

This is the router.db:
`1.1.1.1:procurve:custom-group`

Here is my config file:
```---
username: user
password: pass
model: procurve
resolve_dns: true
interval: 3600
use_syslog: false
debug: true
threads: 30
timeout: 10
retries: 1
prompt: !ruby/regexp /[\S]?:+/
rest: 0.0.0.0:8888
next_adds_job: false
vars:
  auth_methods: [ "password", "keyboard-interactive" ]
  ssh_no_keepalive: true
models: {}
pid: "/home/oxidized/.config/oxidized/pid"
crash:
  directory: "/home/oxidized/.config/oxidized/crashes"
  hostnames: false
stats:
  history_size: 10
input:
  default: ssh
  debug: true
  ssh:
    secure: false
    no_keepalive: true
  ftp:
    passive: true
  utf8_encoded: true
output:
  default: git
  git:xxx
source:
  default: csv
  debug: false
  csv:
    file: "/home/oxidized/.config/oxidized/router.db"
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
      group: 2
```

Here is the oxidized debug:
```
D, [2020-05-28T20:31:03.806586 #26631] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 0 of 1
D, [2020-05-28T20:31:03.807067 #26631] DEBUG -- : lib/oxidized/worker.rb: Added tiger/1.1.1.1 to the job queue
D, [2020-05-28T20:31:03.807123 #26631] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2020-05-28T20:31:03.807243 #26631] DEBUG -- : lib/oxidized/job.rb: Starting fetching process for 1.1.1.1 at 2020-05-28 18:31:03 UTC
D, [2020-05-28T20:31:03.807619 #26631] DEBUG -- : lib/oxidized/input/ssh.rb: Connecting to 1.1.1.1
D, [2020-05-28T20:31:03.807849 #26631] DEBUG -- : AUTH METHODS::["keyboard-interactive"]
D, [2020-05-28T20:31:03.808857 #26631] DEBUG -- net.ssh.transport.session[2abaeaaa0490]: establishing connection to 1.1.1.1:22
D, [2020-05-28T20:31:03.809977 #26631] DEBUG -- net.ssh.transport.session[2abaeaaa0490]: connection established
I, [2020-05-28T20:31:03.810066 #26631]  INFO -- net.ssh.transport.server_version[2abaeaa9f4c8]: negotiating protocol version
D, [2020-05-28T20:31:03.810130 #26631] DEBUG -- net.ssh.transport.server_version[2abaeaa9f4c8]: local is `SSH-2.0-Ruby/Net::SSH_5.2.0 x86_64-linux'
D, [2020-05-28T20:31:03.811109 #26631] DEBUG -- net.ssh.transport.server_version[2abaeaa9f4c8]: remote is `SSH-2.0-Mocana SSH 6.3'
I, [2020-05-28T20:31:03.811666 #26631]  INFO -- net.ssh.transport.algorithms[2abaeaa9e4ec]: sending KEXINIT
D, [2020-05-28T20:31:03.811900 #26631] DEBUG -- socket[2abaeaa9fd74]: queueing packet nr 0 type 20 len 1324
D, [2020-05-28T20:31:03.811986 #26631] DEBUG -- socket[2abaeaa9fd74]: sent 1328 bytes
D, [2020-05-28T20:31:03.991226 #26631] DEBUG -- socket[2abaeaa9fd74]: read 408 bytes
D, [2020-05-28T20:31:03.991381 #26631] DEBUG -- socket[2abaeaa9fd74]: received packet nr 0 type 20 len 404
I, [2020-05-28T20:31:03.991468 #26631]  INFO -- net.ssh.transport.algorithms[2abaeaa9e4ec]: got KEXINIT from server
I, [2020-05-28T20:31:03.991607 #26631]  INFO -- net.ssh.transport.algorithms[2abaeaa9e4ec]: negotiating algorithms
D, [2020-05-28T20:31:03.991758 #26631] DEBUG -- net.ssh.transport.algorithms[2abaeaa9e4ec]: negotiated:
* kex: diffie-hellman-group14-sha1
* host_key: ssh-rsa
* encryption_server: aes256-ctr
* encryption_client: aes256-ctr
* hmac_client: hmac-sha1
* hmac_server: hmac-sha1
* compression_client: none
* compression_server: none
* language_client: 
* language_server: 
D, [2020-05-28T20:31:03.991826 #26631] DEBUG -- net.ssh.transport.algorithms[2abaeaa9e4ec]: exchanging keys
D, [2020-05-28T20:31:04.005550 #26631] DEBUG -- socket[2abaeaa9fd74]: queueing packet nr 1 type 30 len 268
D, [2020-05-28T20:31:04.005634 #26631] DEBUG -- socket[2abaeaa9fd74]: sent 272 bytes
D, [2020-05-28T20:31:04.342138 #26631] DEBUG -- socket[2abaeaa9fd74]: read 832 bytes
D, [2020-05-28T20:31:04.342332 #26631] DEBUG -- socket[2abaeaa9fd74]: received packet nr 1 type 31 len 828
D, [2020-05-28T20:31:04.343996 #26631] DEBUG -- socket[2abaeaa9fd74]: queueing packet nr 2 type 21 len 20
D, [2020-05-28T20:31:04.344090 #26631] DEBUG -- socket[2abaeaa9fd74]: sent 24 bytes
D, [2020-05-28T20:31:04.345213 #26631] DEBUG -- socket[2abaeaa9fd74]: read 16 bytes
D, [2020-05-28T20:31:04.345303 #26631] DEBUG -- socket[2abaeaa9fd74]: received packet nr 2 type 21 len 12
D, [2020-05-28T20:31:04.345691 #26631] DEBUG -- net.ssh.authentication.session[2abaeab559e4]: beginning authentication of `user'
D, [2020-05-28T20:31:04.345833 #26631] DEBUG -- socket[2abaeaa9fd74]: queueing packet nr 3 type 5 len 28
D, [2020-05-28T20:31:04.345920 #26631] DEBUG -- socket[2abaeaa9fd74]: sent 52 bytes
D, [2020-05-28T20:31:04.356998 #26631] DEBUG -- socket[2abaeaa9fd74]: read 52 bytes
D, [2020-05-28T20:31:04.357143 #26631] DEBUG -- socket[2abaeaa9fd74]: received packet nr 3 type 6 len 28
D, [2020-05-28T20:31:04.357316 #26631] DEBUG -- net.ssh.authentication.session[2abaeab559e4]: trying keyboard-interactive
D, [2020-05-28T20:31:04.357423 #26631] DEBUG -- net.ssh.authentication.methods.keyboard_interactive[2abaeab551ec]: trying keyboard-interactive
D, [2020-05-28T20:31:04.357576 #26631] DEBUG -- socket[2abaeaa9fd74]: queueing packet nr 4 type 50 len 76
D, [2020-05-28T20:31:04.357674 #26631] DEBUG -- socket[2abaeaa9fd74]: sent 100 bytes
D, [2020-05-28T20:31:04.363529 #26631] DEBUG -- socket[2abaeaa9fd74]: read 244 bytes
D, [2020-05-28T20:31:04.363644 #26631] DEBUG -- socket[2abaeaa9fd74]: received packet nr 4 type 53 len 220
I, [2020-05-28T20:31:04.363756 #26631]  INFO -- net.ssh.authentication.session[2abaeab559e4]: We'd like to keep you up to date about:
  * Software feature updates
  * New product announcements
  * Special events
Please register your products now at:  www.hpe.com/networking/register



D, [2020-05-28T20:31:04.404824 #26631] DEBUG -- socket[2abaeaa9fd74]: read 100 bytes
D, [2020-05-28T20:31:04.405034 #26631] DEBUG -- socket[2abaeaa9fd74]: received packet nr 5 type 60 len 76
D, [2020-05-28T20:31:04.405123 #26631] DEBUG -- net.ssh.authentication.methods.keyboard_interactive[2abaeab551ec]: keyboard-interactive info request
user@1.1.1.1's password: D, [2020-05-28T20:31:04.807533 #26631] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2020-05-28T20:31:05.807839 #26631] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2020-05-28T20:31:06.808149 #26631] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
```
which will then continue with the message "1 jobs running in parallel" until it eventually fails after some time.

if i directly SSH into it, it looks like this:
```
[root@server model ] # ssh user@1.1.1.1
We'd like to keep you up to date about:
  * Software feature updates
  * New product announcements
  * Special events
Please register your products now at:  www.hpe.com/networking/register


user@1.1.1.1's password: 
[root@server model ] #
```
odd thing is this works with other procurve switches, which have the same SSH shell appearance, same switch version but somehow use authentication type password and not keyboard interactive

for example device 1.1.1.2's SSH shell appearance looks identical to 1.1.1.1's:
```
[root@server yo ] # ssh user@1.1.1.2
We'd like to keep you up to date about:
  * Software feature updates
  * New product announcements
  * Special events
Please register your products now at:  www.hpe.com/networking/register


user@1.1.1.2's password: 
[root@server yo ] #
```
But when oxidized hits this device it will just use authentication method password, and will back this device up just fine. Same password, same user....

Did somehow experience anything like this?

**Comment by DarkCatapulter** [comment]
Could you please edit your comment and reformat your config and your log? It's way to much work to read this. So to help the ones that might want to help you, reformat your config and logs by doing this:

\`\`\`
*Your config here*
\`\`\`

Some text in-between.
\`\`\`
*Your log here*
\`\`\`

And you will get something that looks like this:
```
This is my config
I can extend it to multiple lines
```
And then
```
This is my log
Look how easy it is to read :)
(Please don't get me wrong, I'm not trying to bash you just teach you.)
```

**Comment by jaannnis** [comment]
Hi thank you really much for your input, waws late at night and i used single "`", should be better now.

**Comment by DarkCatapulter** [comment]
> which will then continue with the message "1 jobs running in parallel" until it eventually fails after some time.

Did you receive some Exception or Error in your logs when it "eventually fails"? For example `Oxidized::SSH failed`. And if you did, can you specify what error you received?

**Comment by jaannnis** [comment]
ok, I just let this run with a interval set of 60 and a timeout of 20 for a little over 20 minutes. The last line I receive every second is "1 jobs running in parallel" see here: https://pastebin.com/dAUiscm8

**Comment by DarkCatapulter** [comment]
Getting `DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel` spammed in your log usually means that oxidized is done with what it's doing. The reason it's spamming is probably because you're using something like `tail -f log` to constantly poll it. It will keep on like that until the next interval.

So either Oxidized ran successfully and managed to download the config, or it ran "successfully" and skipped downloading the config. I don't see any Errors or Exceptions in your log, usually if something goes wrong you will get something like, e.g. `Timeout::Error with msg "execution expired"` that will make it easy to find out why it didn't work.

Are you 100% sure that Oxidized failed to download the config from your device? Because from my perspective, it seems like it succeeds. I might be wrong of course, but might be worth to check an extra time before we continue.

**Comment by jaannnis** [comment]
I'm just running oxidized --debug, this was the console output.

Yes, I'm 100% sure oxidized doesn't even login to the device, it got it's own user and is logging logins. The user has not logged in to the switch in the past days (except for the two times I checked that login is possibly and password is correct).


Also I let oxidized with the same config mentioned above (nterval set of 60 and a timeout of 20) run for this whole day with this single switch in it's router.db, nothing but "1 jobs running in parallel" in the log. Also the WebUI doesn't state this switch as failed, it just lists it as never Last updated and Last Status in blue (never), see here: https://i.imgur.com/VJznzaL.png

**Comment by DarkCatapulter** [comment]
Sorry for answering late. Did you manage to solve your issue? If not then let's continue troubleshooting.

I'm just slightly confused since I feel like the log should provide with more info about the problem.
Also regarding your latest log that you shared through pastebin:
```
I, [2020-06-02T10:08:05.181884 #20959]  INFO -- net.ssh.authentication.session[2b0286cc0bec]: We'd like to keep you up to date about:
  * Software feature updates
  * New product announcements
  * Special events
Please register your products now at:  www.hpe.com/networking/register
```

This here proves that your Oxidized manages to SSH to your devices. Doesn't necessarily mean that Oxidized ran successfully on the device. I've had cases where Oxidized manages to SSH, but it doesn't find the prompt and therefore thinks that it failed to connect. But if that were to happen, at least you would've gotten a "Timeout Error".

I want to try focus a bit more on your device prompt, since I personally feel like that's where the problem might be. In a previous comment I can see that your device appears to have `[root@server model ] # ` as its prompt. That's a pretty weird prompt and might cause Oxidized to not be able to find it. I want you to change your device's hostname to something where you don't have the symbols `[`, `]`, and `@`. If this doesn't work then we'll continue the troubleshooting :)
