### ISSUE TITLE
TACACS authorization fails on some commands, causing faulty git history

### ISSUE THREAD

**Issue by tyler-8** [ytti/oxidized#2114]
With some models, like `ios.rb`, multiple commands are run by oxidized to pull the output back. Unfortunately, in some cases, the TACACS session is flakey and the command authorization fails momentarily. What happens however, is oxidized creates a git commit with a line `% Authorization failed.` instead of the output of `show version`, for example, while the `show running-config` output is fine. This causes quite a large diff to be made, and then another one on the next cycle where the command authorization didn't fail.

Ideally oxidized would just abort that device entirely for this cycle, rather than committing the failed authorization to the config's history.

I suspect this may be something to easily add to the model file (or a custom model file).

**Comment by seros1521** [comment]
oxidized does not see the difference between this or that conclusion, and therefore writes it to the backup. In addition, an authorization error message is generated by the server, IOS simply displays it to the user. Thus, different TACACS implementations will output different error text (my TACACS displays "Command authorization failed.").
