### ISSUE TITLE
Group-Based Credentials Not Working

### ISSUE THREAD

**Issue by bockbilbo** [ytti/oxidized#2122]
Hello,

First of all, thanks a lot @ytti and all of the project collaborators for your amazing work with this tool.

I am opening this issue due to the problems I am finding setting group specific credentials. Based on what I have read on the available documentation and issues opened in the past, I should be able to configure group credentials with:

```
groups:
  group1:
    username: user1
    password: password1
  group2:
    username: user2
    password: password2
```

However, this is not working for me. Looking at the debug logs, it seems that Oxidized is only obtaining the credentials from global and model.

This might be related to #1992 or #1637. 

I am currently running oxidized (0.28.0), oxidized-script (0.6.0) and oxidized-web (0.13.1) on CentOS 8.1, and here are my redacted testing configs:

```
---
interval: 3600
use_syslog: true
debug: false
threads: 40
timeout: 20
retries: 0
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/

crash:
  directory: "/opt/oxidized/.config/oxidized/crashes"
  hostnames: false

# Enable web interface:
rest: 127.0.0.1:8890/status
pid: "/opt/oxidized/.config/oxidized/pid"

# Set local history size to 2 files:
stats:
  history_size: 2

# Custom settings for different groups:
groups:
  group1:
    username: user1
    password: password1
  group2:
    username: user2
    password: password2
  group3:
    username: user3
    password: password3
    vars:
      enable: enpasswd1

# Settings for device models:
models:
  pfsense:
    username: user4
    password: pass4
    ssh_keys: "/opt/oxidized/.config/oxidized/ssh/id_rsa"

# Settings for data input:
input:
  debug: true
  default: ssh,telnet
  ssh:
    secure: false

# Settings for default data output:
output:
  file:
    directory: /opt/oxidized/default

# Settings for data source:
source:
  default: csv
  csv:
    file: /opt/oxidized/.config/oxidized/router.db
    delimiter: !ruby/regexp /;/
    map:
      group: 0
      name: 1
      model: 2

# Model maps to common names:
model_map:
  cisco: ios
  cisco-basic: iosbasic
  juniper: junos
  juniper-basic: junosbasic
  cisco-xr: iosxr
  cisco-xr-basic: iosxrbasic
  mikrotik: routeros
```

The _iosbasic_, _iosxrbasic_ and _junosbasic_ models are custom models based on _ios_, _iosxr_ and _junos_ that exclude the commented lines that usually precede the configuration backups.

At my router.db, I have a single entry pointing to a Cisco 3550 switch with telnet access:

```
group3;switch_hostname;cisco-basic
```

With the configurations above, Oxidized does not read the group3 credentials and the logs return the _Oxidized::PromptUndetect with msg "unable to detect prompt: (?-mix:^([\w.@()-]+[#>]\s?)$)"_ error.

If I set the username, password and enable password in the global section or as part of the _iosbasic_ model, the authentication is successful and the configurations are retrieved.

My network settings require using different username and passwords for different subsets of ios devices, so defining model based credentials as suggested by #1637 is not a viable option.

I know that I could technically clone the _ios_ model setting different class names and then use distinct model names for each device subset, but it feels like a horrible hack that should be avoided.

I wonder if I am missing something in my configurations or if perhaps this is related to some bug or missing feature. Can you help me?

Additionally, can someone explain the point of having the debug section both in global and the input sections? I have tried multiple combinations, and I only get debug logs when I set the variable as true in global. 

Thank you!

**Comment by bockbilbo** [comment]
Hello again,

It's been over a month since I submitted my issues. Can anyone guide me in the right direction?

Thanks!

**Comment by laf** [comment]
Odd, we use group based credentials perfectly fine (http source though rather than file based but doubt that matters).

**Comment by NoifP** [comment]
We use group based credentials (file based) and it works. I cannot see any issues with your config and it looks pretty similar to ours.

**Comment by rgrossmann-ewr** [comment]
> 
> 
> Odd, we use group based credentials perfectly fine (http source though rather than file based but doubt that matters).

can you provide your config? And is source: http = librenms ?

I've created Groups in librenms and added devices to these groups. the oxidized config of mine contains the group names as created in librenms

```
groups:
  DMZ:
    username: admin
    password: rokava50
    model: procurve
  LAN:
    username: manager
    password: hp@ewr2010
    model: procurve
source:
  default: http
  debug: false
  http:
    url: http://localhost/api/v0/oxidized
    map:
      name: hostname
      model: os
      group: group
    headers:
     X-Auth-Token: 'my_key'
```
But looks like oxidized takes the global credentials :-(

**Comment by basondole** [comment]
Hello

Librenms groups do not translate to oxidized groups. You have to edit oxidized config file to map the groups.

Regards
Paul SIB

**Comment by basondole** [comment]
Sorry meant you have to edit librenms config to map the groups with regular expressions

Regards
Paul SIB

**Comment by rgrossmann-ewr** [comment]
Then whatfor is the setting "Enable the return of groups to Oxidized" in librenms Global Settings --> External --> Oxidized Integration ?? Does not look like integrated :-(

But thanks you for your reply

yet i am trying to get it work with config.php

**Comment by basondole** [comment]
Hi
That config doesn't say what it does or doesn't do what it says but it is something that may change in the future. LibreNMS group does not map to oxidized group. You have to map manually by using ip or hostname or os or sysname, by editing libre `config.php` So you have to for example to edit the hostnames of your nodes to create a pattern that you would match with a regex and assign to a group of same name. In example below every node in librenms that has `hostname` or `snmp sysname` starting with `isat` will be assigned to oxidized group `isat`
Edit `/opt/librenms/config.php` to include
```
$config['oxidized']['maps']['group']['hostname'][] = array('regex' => '/^isat/', 'group' => 'isat');
$config['oxidized']['maps']['group']['sysname'][] = array('regex' => '/^isat/', 'group' => 'isat');
```
Curl will produce correct group now
```
/opt/oxidized$ curl -H "Authorization: Bearer d4b50bc1e1185492ec4f2a5a327cd22d" http://192.168.80.139/api/v0/oxidized
[
    {
        "hostname": "192.168.56.63",
        "os": "ios",
        "ip": "",
        "group": "isat"
    },
    {
        "hostname": "192.168.56.36",
        "os": "junos",
        "ip": "",
        "group": "isat"
    }]
```
 And you can view the config from within LibreNMS

**Comment by rgrossmann-ewr** [comment]
Too bad that librenms does not pass the device group on to oxidized like hostname, sysname, ip etc. This could save you double work.

But okay. As a result, I now have at least the group assignment for the network devices.

Thanks a lot and

Kind regards

Robert
