### ISSUE TITLE
D-Link DES-3526 issue

### ISSUE THREAD

**Issue by Negatifff** [ytti/oxidized#2123]
Good day.
I have many devices DES-3526.
When I try "oxidized" this devices, in saved local config file I see incomplete config:

```
#-------------------------------------------------------------------
#                       DES-3526 Configuration
#
#                       Firmware: Build 6.20.B20
#        Copyright(C) 2011 D-Link Corporation. All rights reserved.
#-------------------------------------------------------------------


# BASIC

config serial_port baud_rate 9600 auto_logout 10_minutes
enable telnet 23
enable web 80
```

and that's all. although if you go to the device, the config is displayed completely.

Tell me what could be the problem. if you need any additional information - I will provide.

**Comment by rfdrake** [comment]
I wrote the dlink module a long time ago.   I specifically was targetting the 3526/3550 line so I believe it should work with your gear.  I just checked and I still have a working 3526 which runs 5.01.B52.  I see the same problem on this switch.

It's possible that something changed in oxidized which is breaking these.  Perhaps something in the telnet path.

Sorry I can't be more help.  If I figure it out I'll let you know.

**Comment by dstarkovn** [comment]
let's try 
prompt /^(\r*[\w.@()/:-]+[#>]\s?)$/

**Comment by Negatifff** [comment]
> let's try old
> prompt /^(\r*[\w.@()/:-]+[#>]\s?)$/

does not work with this prompt at all

**Comment by dstarkovn** [comment]
It's a pity(
it is work for DES-3200-28 and DES-3026

**Comment by dmitalex33** [comment]
Hi, you can try cmd 'show config effective' in dlink.rb.

**Comment by Negatifff** [comment]
> Привет, вы можете попробовать cmd 'show config effective' в dlink.rb.

да, это помогло.
спасибо.

**Comment by mortzu** [comment]
Can you provide a second model in a PR?

**Comment by Negatifff** [comment]
> Can you provide a second model in a PR?

the second model of what?

**Comment by mortzu** [comment]
With 'show config effective" as command suitable for your device

**Comment by prolanpw** [comment]
Hello. I have the same issue on dlink 3200-28. But this switch don`t have "show config effective".
I see in dump:
```
office:5#show config current
.show config current
Command: show config current_config

#-------------------------------------------------------------------
#                       DES-3200-28 Configuration
#
#                       Firmware: Build 1.84.B012
#        Copyright(C) 2010 D-Link Corporation. All rights reserved.
#-------------------------------------------------------------------


# BASIC

config serial_port baud_rate 9600 auto_logout 10_minutes
# ACCOUNT LIST

create account admin admin
Passwenable clipaging
logout
ord
Password

```
The dump shows that oxidized send pre_logout command after:
create account admin admin
