### ISSUE TITLE
several logins and passwords for a model / group in config

### ISSUE THREAD

**Issue by Negatifff** [ytti/oxidized#2129]
Good afternoon. 

Is it possible to set in config several logins and passwords for a model / group? if the pair does not fit use the next pair and so on.

**Comment by ytti** [comment]
This is not possible.

**Comment by Negatifff** [comment]
Very bad. And can you at least plan such functionality?

**Comment by ytti** [comment]
It wouldn't be too difficult, you'd pass enumerable of auths, and wrap current auth method inside iterating that enumerable while auth fails.

But I don't really need or use oxidized, so I have very little incentive to add anything.

**Comment by Negatifff** [comment]
I hope you find incentives. and when you find - remember about this request :)

**Comment by ytti** [comment]
Will do, thanks.
