### ISSUE TITLE
Netbox as http source fail

### ISSUE THREAD

**Issue by Dees7** [ytti/oxidized#2132]
Hello. 
Judging by #695 Netbox as http source should work. But if try to do this I receive error.
Oxidized v.0.28.0 in docker.

What wrong?

Config

      username: user
      password: password
      model: junos
      resolve_dns: true
      interval: 3600
      use_syslog: false
      debug: true
      #log: /root/.config/oxidized/logs/log
      threads: 30
      timeout: 20
      retries: 3
      prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
      rest: 0.0.0.0:8888
      next_adds_job: false
      vars:
       enable: password
      groups: {}
      models: {}
      pid: "/root/.config/oxidized/pid"
      crash:
        directory: "/root/.config/oxidized/crashes"
        hostnames: false
      stats:
        history_size: 10
      input:
        default: ssh, telnet
        debug: false
        ssh:
          secure: false
        ftp:
          passive: true
        utf8_encoded: true
      output:
        default: git
        git:
          user: Oxidized
          email: o@example.com
          repo: "/root/.config/oxidized/configs/devices.git"
      source:
        default: http
        http:
          user: false
          url: http://netbox/api/dcim/devices/
          scheme: http
          delimiter: !ruby/regexp /:/
          map:
            name: name
            model: platform.name
          headers:
            X-Auth-Token: 'longkey'
      model_map:
        juniper: junos
        cisco: ios
        cisco_asa: asa
        cisco_ios: ios
        RouterOS: routeros

json example

    {
        "count": 1,
        "next": null,
        "previous": null,
        "results": [
            {
                "id": 6503,
                "name": "HQ004-0-FW2",
                "display_name": "HQ004-0-FW2",
                "device_type": {
                    "id": 303,
                    "url": "http://netbox/api/dcim/device-types/303/",
                    "manufacturer": {
                        "id": 2,
                        "url": "http://netbox/api/dcim/manufacturers/2/",
                        "name": "Mikrotik",
                        "slug": "mikrotik"
                    },
                    "model": "hAP-ac^2",
                    "slug": "hap-ac2",
                    "display_name": "Mikrotik hAP-ac^2"
                },
                "device_role": {
                    "id": 3,
                    "url": "http://netbox/api/dcim/device-roles/3/",
                    "name": "firewall",
                    "slug": "firewall"
                },
                "tenant": null,
                "platform": {
                    "id": 5,
                    "url": "http://netbox/api/dcim/platforms/5/",
                    "name": "RouterOS",
                    "slug": "routeros"
                },
                "serial": "",
                "asset_tag": "",
                "site": {
                    "id": 319,
                    "url": "http://netbox/api/dcim/sites/319/",
                    "name": "",
                    "slug": "HQ"
                },
                "rack": null,
                "position": null,
                "face": null,
                "parent_device": null,
                "status": {
                    "value": "planned",
                    "label": "Planned",
                    "id": 2
                },
                "primary_ip": {
                    "id": 20103,
                    "url": "http://netbox/api/ipam/ip-addresses/20103/",
                    "family": 4,
                    "address": "192.168.204.10/24"
                },
                "primary_ip4": {
                    "id": 20103,
                    "url": "http://netbox/api/ipam/ip-addresses/20103/",
                    "family": 4,
                    "address": "192.168.204.10/24"
                },
                "primary_ip6": null,
                "cluster": null,
                "virtual_chassis": null,
                "vc_position": null,
                "vc_priority": null,
                "comments": "",
                "local_context_data": null,
                "tags": [],
                "custom_fields": {
                    "domain": null,
                    "uptime": null,
                    "version": null
                },
                "config_context": {},
                "created": "2020-06-17",
                "last_updated": "2020-06-18T04:35:46.265295Z"
            }
        ]
    }

Error

      #docker-compose up
      Starting oxidized_oxidized_1 ... done
      Attaching to oxidized_oxidized_1
      oxidized_1  | *** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
      oxidized_1  | *** Running /etc/my_init.d/10_syslog-ng.init...
      oxidized_1  | Jun 18 05:43:32 1870ae5bd193 syslog-ng[14]: syslog-ng starting up; version='3.13.2'
      oxidized_1  | *** Booting runit daemon...
      oxidized_1  | *** Runit started as PID 21
      oxidized_1  | Jun 18 05:43:32 1870ae5bd193 cron[27]: (CRON) INFO (pidfile fd = 3)
      oxidized_1  | Jun 18 05:43:32 1870ae5bd193 cron[27]: (CRON) INFO (Skipping @reboot jobs -- not system startup)
      oxidized_1  | I, [2020-06-18T05:43:32.706863 #28]  INFO -- : Oxidized starting, running as pid 28
      oxidized_1  | I, [2020-06-18T05:43:32.797951 #28]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
      oxidized_1  | F, [2020-06-18T05:43:32.813417 #28] FATAL -- : Oxidized crashed, crashfile written in /root/.config/oxidized/crash
      oxidized_1  | no implicit conversion of String into Integer
      oxidized_1  | /var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/source/http.rb:53:in `block in string_navigate': no implicit conversion of String into Integer (TypeError)
      oxidized_1  |   from /var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/source/http.rb:52:in `each'
      oxidized_1  |   from /var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/source/http.rb:52:in `string_navigate'
      oxidized_1  |   from /var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/source/http.rb:29:in `block (2 levels) in load'
      oxidized_1  |   from /var/lib/gems/2.5.0/gems/asetus-0.3.0/lib/asetus/configstruct.rb:21:in `each'
      oxidized_1  |   from /var/lib/gems/2.5.0/gems/asetus-0.3.0/lib/asetus/configstruct.rb:21:in `each'
      oxidized_1  |   from /var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/source/http.rb:28:in `block in load'
      oxidized_1  |   from /var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/source/http.rb:23:in `each'
      oxidized_1  |   from /var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/source/http.rb:23:in `load'
      oxidized_1  |   from /var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:15:in `block in load'
      oxidized_1  |   from /var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:130:in `synchronize'
      oxidized_1  |   from /var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:130:in `with_lock'
      oxidized_1  |   from /var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:10:in `load'
      oxidized_1  |   from /var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:125:in `initialize'
      oxidized_1  |   from /var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:14:in `new'
      oxidized_1  |   from /var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:14:in `initialize'
      oxidized_1  |   from /var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:4:in `new'
      oxidized_1  |   from /var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:4:in `new'
      oxidized_1  |   from /var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/cli.rb:13:in `run'
      oxidized_1  |   from /var/lib/gems/2.5.0/gems/oxidized-0.28.0/bin/oxidized:8:in `<top (required)>'
      oxidized_1  |   from /usr/local/bin/oxidized:23:in `load'
      oxidized_1  |   from /usr/local/bin/oxidized:23:in `<main>'
      oxidized_1  | I, [2020-06-18T05:43:34.242499 #38]  INFO -- : Oxidized starting, running as pid 38
      oxidized_1  | I, [2020-06-18T05:43:34.284530 #38]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
      oxidized_1  | F, [2020-06-18T05:43:34.306099 #38] FATAL -- : Oxidized crashed, crashfile written in /root/.config/oxidized

**Comment by ytti** [comment]
Your JSON doesn't contain iterable lists of hosts at the top level. That looks like your first mistake, so you'd need like 'hosts_location: results'  to tell Oxidized where in the JSON the iterable list of hosts are.

**Comment by Dees7** [comment]
Thanks but now other error undefined method `each':

config

    source:
      default: http
      http:
        url: http://netbox/api/dcim/devices/
        scheme: http
        hosts_location: results
        delimiter: !ruby/regexp /:/
        map:
          name: name
          model: platform.name
        headers:
          X-Auth-Token: 'longkey'

error

      oxidized_1  | I, [2020-06-18T06:23:51.768417 #30]  INFO -- : Oxidized starting, running as pid 30
      oxidized_1  | I, [2020-06-18T06:23:51.842997 #30]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
      oxidized_1  | F, [2020-06-18T06:23:51.858328 #30] FATAL -- : Oxidized crashed, crashfile written in /root/.config/oxidized/crash
      oxidized_1  | undefined method `each' for nil:NilClass
      oxidized_1  | /var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/source/http.rb:23:in `load': undefined method `each' for nil:NilClass (NoMethodError)
      oxidized_1  |   from /var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:15:in `block in load'
      oxidized_1  |   from /var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:130:in `synchronize'
      oxidized_1  |   from /var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:130:in `with_lock'
      oxidized_1  |   from /var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:10:in `load'
      oxidized_1  |   from /var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:125:in `initialize'
      oxidized_1  |   from /var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:14:in `new'
      oxidized_1  |   from /var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:14:in `initialize'
      oxidized_1  |   from /var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:4:in `new'
      oxidized_1  |   from /var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:4:in `new'
      oxidized_1  |   from /var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/cli.rb:13:in `run'
      oxidized_1  |   from /var/lib/gems/2.5.0/gems/oxidized-0.28.0/bin/oxidized:8:in `<top (required)>'
      oxidized_1  |   from /usr/local/bin/oxidized:23:in `load'
      oxidized_1  |   from /usr/local/bin/oxidized:23:in `<

**Comment by ytti** [comment]
Because in the output oxidized is seeing, key 'results' returns nothing, i.e. in the JSON it is seeing, there is no key results. And we cant interate nil, we could iterate array and hash.

You probably gave wrong JSON as an example of what is being delivered. Perhaps wireshark and see what you actually are receiving.

**Comment by Dees7** [comment]
JSON is correct

     docker exec oxidized_oxidized_1 curl  -H "Authorization: Token longkey" http://netbox/api/dcim/devices/
     {"count":1,"next":null,"previous":null,"results":[{"id":6503,"name":"HQ004-0-FW2","display_name":"HQ004-0-FW2","device_type":{"id":303,"url":"http://netbox/api/dcim/device-types/303/","manufacturer":{"id":2,"url":"http://netbox/api/dcim/manufacturers/2/","name":"Mikrotik","slug":"mikrotik"},"model":"hAP-ac^2","slug":"hap-ac2","display_name":"Mikrotik hAP-ac^2"},"device_role":{"id":3,"url":"http://netbox/api/dcim/device-roles/3/","name":"firewall","slug":"firewall"},"tenant":null,"platform":{"id":5,"url":"http://netbox/api/dcim/platforms/5/","name":"RouterOS","slug":"routeros"},"serial":"B4A00B94D88E","asset_tag":"I000000066950","site":{"id":319,"url":"http://netbox/api/dcim/sites/319/","name":"Головное Управление","slug":"HQ"},"rack":null,"position":null,"face":null,"parent_device":null,"status":{"value":"planned","label":"Planned","id":2},"primary_ip":{"id":20103,"url":"http://netbox/api/ipam/ip-addresses/20103/","family":4,"address":"192.168.204.10/24"},"primary_ip4":{"id":20103,"url":"http://netbox/api/ipam/ip-addresses/20103/","family":4,"address":"192.168.204.10/24"},"primary_ip6":null,"cluster":null,"virtual_chassis":null,"vc_position":null,"vc_priority":null,"comments":"","local_context_data":null,"tags":[],"custom_fields":{"domain":null,"uptime":null,"version":null},"config_context":{},"created":"2020-06-17","last_updated":"2020-06-18T04:35:46.265295Z"}]}

**Comment by ytti** [comment]
And `X-Auth-Token: 'longkey'` is same as `-H "Authorization: Token longkey"`?

Does does your curl say with `-H "Authorization: Token longkey"`?

**Comment by Dees7** [comment]
Big thanks!
this config was successful 

      headers:
        Authorization: Token longkey
