### ISSUE TITLE
Help configuring oxidized to run as service

### ISSUE THREAD

**Issue by basondole** [ytti/oxidized#2136]
Hello,

I'm struggling to get oxidized configured to run as service on CentOS 7.6
Have tried below instructions with no luck:
- https://blog.meta.pw/installing-oxidized-on-centos-7-6
- https://packetpushers.net/install-oxidized-network-configuration-backup/

With above references I only get this far

<pre>
$ sudo systemctl status oxidized.service
● oxidized.service - Oxidized - Network Device Configuration Backup Tool
   Loaded: loaded (/etc/systemd/system/oxidized.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Sat 2020-06-20 22:46:06 EAT; 2s ago
  Process: 3947 ExecStart=/usr/local/bin/oxidized (code=exited, status=203/EXEC)
 Main PID: 3947 (code=exited, status=203/EXEC)

Jun 20 22:46:06 localhost.localdomain systemd[1]: Started Oxidized - Network Device Configuration Backup Tool.
Jun 20 22:46:06 localhost.localdomain systemd[1]: oxidized.service: main process exited, code=exited, status...EXEC
Jun 20 22:46:06 localhost.localdomain systemd[1]: Unit oxidized.service entered failed state.
Jun 20 22:46:06 localhost.localdomain systemd[1]: oxidized.service failed.
Hint: Some lines were ellipsized, use -l to show in full.
</pre>

Please help cant seem to find any other guide to give a try

**Comment by systeembeheerder** [comment]
Does oxidized run without problems when started from the shell/cli?

**Comment by basondole** [comment]
It does run on cli however needs to run "scl enable rh-ruby23 bash" when rebooted

Regards
Paul SIB

**Comment by wk** [comment]
Replacing the `ExecStart` line in the `oxidized.service` unit file with something along the lines of `ExecStart=/usr/bin/scl enable rh-ruby23 -- /usr/local/bin/oxidized` should probably do the trick. See [this](https://access.redhat.com/documentation/en-us/red_hat_software_collections/1/html/packaging_guide/sect-software_collection_initscript_support) for more information.

**Comment by basondole** [comment]
Hello @wk I have had to switch to Ubuntu 20.04, worked ok there. Hopefully the method you have suggested will help someone with similar problem in the future. Thanks a lot.

**Comment by LemonLight** [comment]
> Replacing the `ExecStart` line in the `oxidized.service` unit file with something along the lines of `ExecStart=/usr/bin/scl enable rh-ruby23 -- /usr/local/bin/oxidized` should probably do the trick. See [this](https://access.redhat.com/documentation/en-us/red_hat_software_collections/1/html/packaging_guide/sect-software_collection_initscript_support) for more information.

Hello,

I confirm that what you have suggested works perfectly. Here's an example : 

`[Unit]
Description=Oxidized - Network Device Configuration Backup Tool
After=network-online.target multi-user.target
Wants=network-online.target

[Service]
ExecStart=/usr/bin/scl enable rh-ruby23 -- /opt/rh/rh-ruby23/root/usr/local/bin/oxidized
User=oxidized
KillSignal=SIGKILL
#Environment="OXIDIZED_HOME=/etc/oxidized"
Restart=on-failure
RestartSec=300s

[Install]
WantedBy=multi-user.target`
