### ISSUE TITLE
Oxidized struggling with large configs

### ISSUE THREAD

**Issue by brna62petsto** [ytti/oxidized#2142]
Hello,

I have a problem with two routers in my environment that have configs larger than 400KB. Using default EOS model and setting input to debug I can see that oxidized has seen entire configs of both routers (logs folder), but what is actually saved to nodes folder is trimmed. There seems to be some kind of limit close to 400KB, but I can't figure it out..any ideas?

> brna62petsto@oxidized:/.config/oxidized/logs$ ll
total 856
drwxr-xr-x 2 brna62petsto brna62petsto   4096 Jun 29 15:43 ./
drwxr-xr-x 6 brna62petsto brna62petsto   4096 Jun 29 15:43 ../
-rw-rw-r-- 1 brna62petsto brna62petsto 431132 Jun 29 15:43 10.10.10.10-ssh
-rw-rw-r-- 1 brna62petsto brna62petsto 430356 Jun 29 15:44 20.20.20.20-ssh
brna62petsto@oxidized:/.config/oxidized/logs$ ll ../nodes/
total 788
drwxr-xr-x 2 brna62petsto brna62petsto   4096 Jun 29 15:28 ./
drwxr-xr-x 6 brna62petsto brna62petsto   4096 Jun 29 15:43 ../
-rw-rw-r-- 1 brna62petsto brna62petsto 399223 Jun 29 15:43 10.10.10.10
-rw-rw-r-- 1 brna62petsto brna62petsto 395249 Jun 29 15:44 20.20.20.20

Oxidized Version 3.11.4 (ruby 2.5.1-p57), codename: Love Song, running on Ubuntu 1804

**Comment by ytti** [comment]
There isn't. Your problem is likely that something is interpreted as prompt at incorrect place, considering that end-of-output.

**Comment by brna62petsto** [comment]
I don't think that is the issue. Saved nodes got cut off at the end of ACL lines 103 and 247 below and following lines look very similar

10.10.10.10:
   seq 103 permit 30.30.30.30/27 le 32
   seq 104 permit 40.40.40.40/26 le 32

20.20.20.20:
   seq 247 permit 50.50.50.50/22 le 31
   seq 248 permit 60.60.60.60/22 le 31

Any other ideas?

**Comment by ytti** [comment]
It could be still prompt issue. Like dangling prompt we didn't consume earlier. If you can put sanitised device on where this issue triggers, I can take a look.

**Comment by brna62petsto** [comment]
Unfortunately that is not possible. Thanks for your quick responses.

**Comment by mightyfenrir** [comment]
@brna62petsto did you figure out a fix for this issue ? I am facing exact same issue..

**Comment by acederlund** [comment]
I have the same issue with a WatchGuard config at the moment, it just gets cut off in the middle:

```
    <ipsec-proposal>
      <name>XXX.proposal</name>
      <description/>
      <proper
```

And it seems to be around 400kb in size as well:
```-rw-r--r-- 1 oxidized oxidized 409848 Jan 27 14:53 1.2.3.4-ssh ```

And `/var/log/messages` says this:
`Jan 28 11:39:43 localhostname oxidized[15397]: 1.2.3.4 raised Timeout::Error with msg "execution expired"`

Currently, my config has these parameters, but I guess they are only timeouts for connection attempts, not execution time:
```
threads: 30
timeout: 20
retries: 3
```

Sorry to comment on a closed issue, I can open a new issue if needed.
