### ISSUE TITLE
Unable to restart Oxidized post config file update

### ISSUE THREAD

**Issue by typiaunan** [ytti/oxidized#2144]
Hi Everyone,

I'm new to Oxidized, LibreNMS and Unix in general and I am seeking some assistance with troubleshooting an issue.
My predecessor deployed a LibreNMS installation with Oxidized backing up the configurations. The backup time was a bit aggressive so we were looking to wind up the backup schedule from every 60 seconds to every 6 hours. I updated the config file and restarted the service. I've not been able to get the service to restart even after winding back my change. 

Below is the config file as it currently stands with some organisation specific information, usernames etc. <redacted>. 

From the crashdump I can see  the following error

#######
no implicit conversion of String into Integer [TypeError]
#######

Below is the config file with the interval set back to the original:

###############
username: <redacted>
password: <redacted>
model: ios
resolve_dns: true
interval: 60
log: ~/.config/oxidized/logs/oxidized.log
use_syslog: false
debug: true
threads: 30
timeout: 10
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 0.0.0.0:8888
next_adds_job: false
vars: {}
groups: {}
models: {}
pid: "/home/oxidized/.config/oxidized/pid"
crash:
  directory: "/home/oxidized/.config/oxidized/crashes"
  hostnames: false
stats:
  history_size: 10
input:
  default: ssh, telnet
  debug: false
  ssh:
    secure: false
  ftp:
    passive: true
  utf8_encoded: true
source:
  default: http
  debug: false
  http:
    url: https://<redacted>/api/v0/oxidized
    map:
      name: hostname
      model: os
      group: group
    headers:
      X-Auth-Token: '<redacted>'
    scheme: https
    secure: false
output:
  default: git
  git:
    user: Oxidized User
    email: oxidized@<redacted>
    repo: "~/.config/oxidized/configs"
model_map:
  juniper: junos
  cisco: ios

########################################

We are seeing the following from the systemctl status oxidized.service

● oxidized.service - Oxidized - Network Device Configuration Backup Tool
   Loaded: loaded (/lib/systemd/system/oxidized.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Mon 2020-07-06 11:10:56 AEST; 4min 53s ago
  Process: 24153 ExecStart=/usr/local/bin/oxidized (code=exited, status=1/FAILURE)
 Main PID: 24153 (code=exited, status=1/FAILURE)

Jul 06 11:10:56 MONPQ03 oxidized[24153]:         from /var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/core.rb:14:in `initialize'
Jul 06 11:10:56 MONPQ03 oxidized[24153]:         from /var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/core.rb:4:in `new'
Jul 06 11:10:56 MONPQ03 oxidized[24153]:         from /var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/cli.rb:13:in `run'
Jul 06 11:10:56 MONPQ03 oxidized[24153]:         from /var/lib/gems/2.5.0/gems/oxidized-0.27.0/bin/oxidized:8:in `<top (required)>'
Jul 06 11:10:56 MONPQ03 oxidized[24153]:         from /usr/local/bin/oxidized:23:in `load'
Jul 06 11:10:56 MONPQ03 oxidized[24153]:         from /usr/local/bin/oxidized:23:in `<main>'
Jul 06 11:10:56 MONPQ03 systemd[1]: oxidized.service: Main process exited, code=exited, status=1/FAILURE
Jul 06 11:10:56 MONPQ03 systemd[1]: oxidized.service: Failed with result 'exit-code'.

#########################

We are getting the following from the oxidized logs;

I, [2020-07-06T08:55:19.865336 #2014]  INFO -- : Oxidized starting, running as pid 2014
I, [2020-07-06T08:55:19.903784 #2014]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
F, [2020-07-06T08:55:19.964129 #2014] FATAL -- : Oxidized crashed, crashfile written in /home/oxidized/.config/oxidized/crash
I, [2020-07-06T09:00:20.214856 #4076]  INFO -- : Oxidized starting, running as pid 4076
I, [2020-07-06T09:00:20.251888 #4076]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
F, [2020-07-06T09:00:20.309568 #4076] FATAL -- : Oxidized crashed, crashfile written in /home/oxidized/.config/oxidized/crash
I, [2020-07-06T09:03:52.835236 #4284]  INFO -- : Oxidized starting, running as pid 4284
I, [2020-07-06T09:03:52.875503 #4284]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
F, [2020-07-06T09:03:52.934371 #4284] FATAL -- : Oxidized crashed, crashfile written in /home/oxidized/.config/oxidized/crash
I, [2020-07-06T09:06:16.910487 #6258]  INFO -- : Oxidized starting, running as pid 6258
I, [2020-07-06T09:06:16.947509 #6258]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
F, [2020-07-06T09:06:16.987232 #6258] FATAL -- : Oxidized crashed, crashfile written in /home/oxidized/.config/oxidized/crash
I, [2020-07-06T09:11:17.208520 #8322]  INFO -- : Oxidized starting, running as pid 8322
I, [2020-07-06T09:11:17.244770 #8322]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
F, [2020-07-06T09:11:17.289727 #8322] FATAL -- : Oxidized crashed, crashfile written in /home/oxidized/.config/oxidized/crash
I, [2020-07-06T09:16:17.721898 #10311]  INFO -- : Oxidized starting, running as pid 10311
I, [2020-07-06T09:16:17.758706 #10311]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
F, [2020-07-06T09:16:17.804018 #10311] FATAL -- : Oxidized crashed, crashfile written in /home/oxidized/.config/oxidized/crash
I, [2020-07-06T09:21:18.204521 #12275]  INFO -- : Oxidized starting, running as pid 12275
I, [2020-07-06T09:21:18.241479 #12275]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
F, [2020-07-06T09:21:18.280245 #12275] FATAL -- : Oxidized crashed, crashfile written in /home/oxidized/.config/oxidized/crash
I, [2020-07-06T09:26:18.712704 #14236]  INFO -- : Oxidized starting, running as pid 14236
I, [2020-07-06T09:26:18.749938 #14236]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
F, [2020-07-06T09:26:18.791359 #14236] FATAL -- : Oxidized crashed, crashfile written in /home/oxidized/.config/oxidized/crash
I, [2020-07-06T09:31:19.212997 #16200]  INFO -- : Oxidized starting, running as pid 16200
I, [2020-07-06T09:31:19.250766 #16200]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
F, [2020-07-06T09:31:19.290909 #16200] FATAL -- : Oxidized crashed, crashfile written in /home/oxidized/.config/oxidized/crash
I, [2020-07-06T09:36:19.718702 #18191]  INFO -- : Oxidized starting, running as pid 18191
I, [2020-07-06T09:36:19.756819 #18191]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
F, [2020-07-06T09:36:19.806473 #18191] FATAL -- : Oxidized crashed, crashfile written in /home/oxidized/.config/oxidized/crash
I, [2020-07-06T09:41:20.213445 #20234]  INFO -- : Oxidized starting, running as pid 20234
I, [2020-07-06T09:41:20.251870 #20234]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
F, [2020-07-06T09:41:20.299640 #20234] FATAL -- : Oxidized crashed, crashfile written in /home/oxidized/.config/oxidized/crash
I, [2020-07-06T09:46:20.550016 #22309]  INFO -- : Oxidized starting, running as pid 22309
I, [2020-07-06T09:46:20.586479 #22309]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
F, [2020-07-06T09:46:20.638321 #22309] FATAL -- : Oxidized crashed, crashfile written in /home/oxidized/.config/oxidized/crash
I, [2020-07-06T09:51:20.960188 #24277]  INFO -- : Oxidized starting, running as pid 24277
I, [2020-07-06T09:51:20.996953 #24277]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
F, [2020-07-06T09:51:21.053982 #24277] FATAL -- : Oxidized crashed, crashfile written in /home/oxidized/.config/oxidized/crash
I, [2020-07-06T09:56:21.457446 #26243]  INFO -- : Oxidized starting, running as pid 26243
I, [2020-07-06T09:56:21.496071 #26243]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
F, [2020-07-06T09:56:21.548300 #26243] FATAL -- : Oxidized crashed, crashfile written in /home/oxidized/.config/oxidized/crash
I, [2020-07-06T10:01:21.966579 #28206]  INFO -- : Oxidized starting, running as pid 28206
I, [2020-07-06T10:01:22.002852 #28206]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
F, [2020-07-06T10:01:22.058259 #28206] FATAL -- : Oxidized crashed, crashfile written in /home/oxidized/.config/oxidized/crash
I, [2020-07-06T10:06:22.474546 #30157]  INFO -- : Oxidized starting, running as pid 30157
I, [2020-07-06T10:06:22.511484 #30157]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
F, [2020-07-06T10:06:22.557217 #30157] FATAL -- : Oxidized crashed, crashfile written in /home/oxidized/.config/oxidized/crash
I, [2020-07-06T10:11:22.956914 #32322]  INFO -- : Oxidized starting, running as pid 32322
I, [2020-07-06T10:11:22.993401 #32322]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
F, [2020-07-06T10:11:23.033088 #32322] FATAL -- : Oxidized crashed, crashfile written in /home/oxidized/.config/oxidized/crash
I, [2020-07-06T10:16:23.463934 #1902]  INFO -- : Oxidized starting, running as pid 1902
I, [2020-07-06T10:16:23.499993 #1902]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
F, [2020-07-06T10:16:23.541453 #1902] FATAL -- : Oxidized crashed, crashfile written in /home/oxidized/.config/oxidized/crash
I, [2020-07-06T10:21:23.967177 #3904]  INFO -- : Oxidized starting, running as pid 3904
I, [2020-07-06T10:21:24.005012 #3904]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
F, [2020-07-06T10:21:24.060880 #3904] FATAL -- : Oxidized crashed, crashfile written in /home/oxidized/.config/oxidized/crash
I, [2020-07-06T10:26:24.462979 #5878]  INFO -- : Oxidized starting, running as pid 5878
I, [2020-07-06T10:26:24.499209 #5878]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
F, [2020-07-06T10:26:24.545285 #5878] FATAL -- : Oxidized crashed, crashfile written in /home/oxidized/.config/oxidized/crash
I, [2020-07-06T10:31:24.952337 #7836]  INFO -- : Oxidized starting, running as pid 7836
I, [2020-07-06T10:31:24.988366 #7836]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
F, [2020-07-06T10:31:25.040356 #7836] FATAL -- : Oxidized crashed, crashfile written in /home/oxidized/.config/oxidized/crash
I, [2020-07-06T10:35:53.330618 #9880]  INFO -- : Oxidized starting, running as pid 9880
I, [2020-07-06T10:35:53.368679 #9880]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
F, [2020-07-06T10:35:53.407874 #9880] FATAL -- : Oxidized crashed, crashfile written in /home/oxidized/.config/oxidized/crash
I, [2020-07-06T10:40:53.705019 #11982]  INFO -- : Oxidized starting, running as pid 11982
I, [2020-07-06T10:40:53.741617 #11982]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
F, [2020-07-06T10:40:53.790396 #11982] FATAL -- : Oxidized crashed, crashfile written in /home/oxidized/.config/oxidized/crash
I, [2020-07-06T10:45:54.243369 #13932]  INFO -- : Oxidized starting, running as pid 13932
I, [2020-07-06T10:45:54.296159 #13932]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
F, [2020-07-06T10:45:54.349217 #13932] FATAL -- : Oxidized crashed, crashfile written in /home/oxidized/.config/oxidized/crash
I, [2020-07-06T10:50:54.713132 #15889]  INFO -- : Oxidized starting, running as pid 15889
I, [2020-07-06T10:50:54.751320 #15889]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
F, [2020-07-06T10:50:54.783822 #15889] FATAL -- : Oxidized crashed, crashfile written in /home/oxidized/.config/oxidized/crash
I, [2020-07-06T10:55:55.231015 #17842]  INFO -- : Oxidized starting, running as pid 17842
I, [2020-07-06T10:55:55.270335 #17842]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
F, [2020-07-06T10:55:55.305928 #17842] FATAL -- : Oxidized crashed, crashfile written in /home/oxidized/.config/oxidized/crash
I, [2020-07-06T11:00:55.730950 #19812]  INFO -- : Oxidized starting, running as pid 19812
I, [2020-07-06T11:00:55.770829 #19812]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
F, [2020-07-06T11:00:55.817874 #19812] FATAL -- : Oxidized crashed, crashfile written in /home/oxidized/.config/oxidized/crash
I, [2020-07-06T11:05:56.209864 #22108]  INFO -- : Oxidized starting, running as pid 22108
I, [2020-07-06T11:05:56.247038 #22108]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
F, [2020-07-06T11:05:56.310609 #22108] FATAL -- : Oxidized crashed, crashfile written in /home/oxidized/.config/oxidized/crash
I, [2020-07-06T11:10:56.737733 #24153]  INFO -- : Oxidized starting, running as pid 24153
I, [2020-07-06T11:10:56.777486 #24153]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
F, [2020-07-06T11:10:56.819077 #24153] FATAL -- : Oxidized crashed, crashfile written in /home/oxidized/.config/oxidized/crash

###################################

Below is the output from the crash logs

--------------------------------------------------
2020-07-06 01:15:57 UTC
no implicit conversion of String into Integer [TypeError]
--------------------------------------------------
/var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/source/http.rb:53:in `block in string_navigate'
/var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/source/http.rb:52:in `each'
/var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/source/http.rb:52:in `string_navigate'
/var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/source/http.rb:29:in `block (2 levels) in load'
/var/lib/gems/2.5.0/gems/asetus-0.3.0/lib/asetus/configstruct.rb:21:in `each'
/var/lib/gems/2.5.0/gems/asetus-0.3.0/lib/asetus/configstruct.rb:21:in `each'
/var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/source/http.rb:28:in `block in load'
/var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/source/http.rb:23:in `each'
/var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/source/http.rb:23:in `load'
/var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/nodes.rb:15:in `block in load'
/var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/nodes.rb:130:in `synchronize'
/var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/nodes.rb:130:in `with_lock'
/var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/nodes.rb:10:in `load'
/var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/nodes.rb:125:in `initialize'
/var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/core.rb:14:in `new'
/var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/core.rb:14:in `initialize'
/var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/core.rb:4:in `new'
/var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/core.rb:4:in `new'
/var/lib/gems/2.5.0/gems/oxidized-0.27.0/lib/oxidized/cli.rb:13:in `run'
/var/lib/gems/2.5.0/gems/oxidized-0.27.0/bin/oxidized:8:in `<top (required)>'
/usr/local/bin/oxidized:23:in `load'
/usr/local/bin/oxidized:23:in `<main>'

##############

If anyone could provide some assistance that would be great. 

Thanks

**Comment by laf** [comment]
You should check the API response from LibreNMS is still valid:

https://docs.librenms.org/API/Devices/#list_oxidized

**Comment by typiaunan** [comment]
Hi laf,

Thanks for helping. 
Error message is as per below

@MONPQ03:~$ curl -H 'X-Auth-Token: <redacted>' https://monpq03.<redacted>.int/api/v0/oxidized
curl: (60) SSL certificate problem: unable to get local issuer certificate

So looks like the API response from LibreNMS is no longer valid... 

and I can see now when using the openssl verify <certname> command 
!Output truncated
error 20 at 0 depth lookup: unable to get local issuer certificate
error monpq03.crt: verification failed

**Comment by laf** [comment]
So you need to fix that first. Once you can confirm the API for LibreNMS is working I expect Oxidized will start up perfectly fine.

You may also be able to work around this issue with `secure: false` https://github.com/ytti/oxidized/blob/master/docs/Sources.md#source-http
