### ISSUE TITLE
Can't remove devices from oxidized

### ISSUE THREAD

**Issue by maddog-nn** [ytti/oxidized#2145]
Hi,

We have intergration oxidized and librenms. From lnms have been removed couple device but these devices still present in oxidized with 'faild' status. How I can remove these devices from oxidized? 

Thank you in advance.

**Comment by laf** [comment]
You should be able to click the Reload button in the Webui of Oxidized or Reload node list from within LibreNMS to get the source refreshed and old nodes taken out.

**Comment by maddog-nn** [comment]
> You should be able to click the Reload button in the Webui of Oxidized or Reload node list from within LibreNMS to get the source refreshed and old nodes taken out.

Hello laf, thank you for your reply but this doesn't work for me.
I've cliked 'Reload node list' in LNMS(LNMS-Overview-Tools-Oxidized) and 'Reload' under oxidezed web interface but problem devices still in list in oxidized...

**Comment by maddog-nn** [comment]
Any other ideas how I can remove unused devices from oxidized?

**Comment by maddog-nn** [comment]
Today helped "Reload" and "Reload node list" on both oxidized web interface and lnms. 
Thank you!
