### ISSUE TITLE
Backup Datacom/DmOS - DM4270/4370

### ISSUE THREAD

**Issue by kiq-moraes** [ytti/oxidized#2151]
Pessoal, alguém conseguiu fazer os backups da série nova da datacom? Os DM3000 e DM4100 fazem sem problemas, mas a série nova (4270/4370) está dando erro...

**Comment by ffrediani** [comment]
I have noticed that although they are very similar the old models (DM3000 and DM4100) after successfully login it gets you directly to the command prompt, while for the newer models (4270/4370) after successfully login there are two "Welcome" messages which Oxidized may not be able interpret correctly and some exceptions need to be made on the model file.

**Comment by Zuquim** [comment]
I managed to solve the issue mentioned by @ffrediani by editing the `prompt` RegEx in the DataCom model.
Mine looks like this now: `prompt /([\n]?[\w-]+[(]*[\w-]*[)]*[#>][\s]?)$/` (the key is the `[\n]?` in the beginning).

Also, since I've been having issues regarding the `expect` method to paginate DmSwitches (I was not able to make it work as expected, ironically), I added a couple of commands to disable DataCom pagination while reading it's outputs.

Will make a PR...

**Comment by kiq-moraes** [comment]
Can you could share and post your datacom.rb file? 
Is it necessary to make any modifications to the global configuration file (config)?

**Comment by Zuquim** [comment]
@kiq-moraes [my modified datacom.rb](https://github.com/Zuquim/oxidized/blob/fix-datacom-2151/lib/oxidized/model/datacom.rb)
Make sure the RegEx I'm using works for your scenario, and keep in mind that the key to correctly match the post login prompt is the `[\n]?` in the beginning of the RegEx.

I did not have to change anything in my global configuration file.

If you have any thoughts about how to better fix this specific issue, please share them. I've never dealt with Ruby before this commit, so I'm a little lost...

**Comment by giovanitestoni** [comment]
Hi all!

I fix this just add on the cmd 'show running-config | no more '

**Comment by Zuquim** [comment]
Hey, @giovanitestoni 

I've just checked and there's no `| no more` option on neither (old OS and DmOS), but there is a `| nomore` on DmOS firmware (nothing like it available for the old firmware). Nice tip, but the main issue here is related to post login prompt detection on DmOS, not pagination.

I did add a workaround for the pagination issue on old firmware, but modifying device configuration is not allowed by the Oxidized policy, so I'll be removing it and finding some other way. Since the pagination issue affects only the old firmware, we won't be able to use your tip for that.

**Comment by giovanitestoni** [comment]
@Zuquim, 

The version of DM4370 that is working is 4.8.0 and Oxidized 0.28.
I've just put `prompt /([\n]?[\w-]+[(]*[\w-]*[)]*[#>][\s]?)$/` in the begin of code e on the cmd.

[datacom.rb.txt](https://github.com/ytti/oxidized/files/5350848/datacom.rb.txt)

`DEBUG -- : lib/oxidized/job.rb: Config fetched for sw-hw-olt-castanheira at 2020-10-08 19:06:12 UTC
DEBUG -- : lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 6 of 7
DEBUG -- : lib/oxidized/worker.rb: Added datacom/sw-dm-assentamento to the job queue
DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
DEBUG -- : lib/oxidized/job.rb: Starting fetching process for sw-dm-assentamento at 2020-10-08 19:06:12 UTC
DEBUG -- : lib/oxidized/input/ssh.rb: Connecting to sw-dm-assentamento`

**Comment by edielson** [comment]
stopped working in Oxidized version 0.29

**Comment by renadown** [comment]
Bom dia, alguém conseguiu resolver essa issue e poderia compartilhar conosco o seu arquivo datacom-4370.rb?

**Comment by aelxdc** [comment]
> Bom dia, alguém conseguiu resolver essa issue e poderia compartilhar conosco o seu arquivo datacom-4370.rb?

Bom dia !

Tive esse mesmo problema aqui, acabei resgatando aqui as configurações do arquivo .rb que usei. Eu acabei criando um novo arquivo "dmos.rb"  para não alterar o já existente "datacom.rb"

Dentro do arquivo dmos.rb:

class DmOs < Oxidized::Model
  #using Refinements

    comment '! '

    prompt /^.*#\s$/
#      #As linhas abaixo seriam necessárias caso não houvesse o "| nomore" no comando no switch, ia ser necessário para o oxidized paginar a config.
#      #  expect /^.*--More--\s+$/ do |data, re|
#      #    send ' '
#      #    data.sub re, ''
#      #  end
#
#      #descomentar as linhas abaixo caso queira que as linhas do arquivo sejam comentadas
        cmd 'show running-config | nomore'# do | cfg |
#        #    comment cfg
#        #  end

          cfg :ssh do
             pre_logout 'exit'
          end

end


Valida se vai funcionar aí pra você.
No meu caso a versão do oxidized é a 0.20.0 e o arquivo está no diretório das gems
/usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/model

**Comment by aelxdc** [comment]
> Bom dia, alguém conseguiu resolver essa issue e poderia compartilhar conosco o seu arquivo datacom-4370.rb?

Bom dia !

Tive esse mesmo problema aqui, acabei resgatando aqui as configurações do arquivo .rb que usei. Eu acabei criando um novo arquivo "dmos.rb"  para não alterar o já existente "datacom.rb"

Dentro do arquivo dmos.rb:

/class DmOs < Oxidized::Model
  #using Refinements

    comment '! '

    prompt /^.*#\s$/
#      #As linhas abaixo seriam necessárias caso não houvesse o "| nomore" no comando no switch, ia ser necessário para o oxidized paginar a config.
#      #  expect /^.*--More--\s+$/ do |data, re|
#      #    send ' '
#      #    data.sub re, ''
#      #  end
#
#      #descomentar as linhas abaixo caso queira que as linhas do arquivo sejam comentadas
        cmd 'show running-config | nomore'# do | cfg |
#        #    comment cfg
#        #  end

          cfg :ssh do
             pre_logout 'exit'
          end

end/


Valida se vai funcionar ai pra você.
No meu caso a versão do oxidized é a 0.20.0 e o arquivo está no diretorio das gems
/usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/model

**Comment by aelxdc** [comment]
> Bom dia, alguém conseguiu resolver essa issue e poderia compartilhar conosco o seu arquivo datacom-4370.rb?

Tive um problema parecido aqui com os 4370 pelo fato deles já virem com o DMOS. Acabei criando um novo arquivo "dmos.rb" pra não alterar o arquivo datacom.rb

Arquivo **/usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/model/dmos.rb**

`class DmOs < Oxidized::Model
  #using Refinements

    comment '! '

    prompt /^.*#\s$/
#      #As linhas abaixo seriam necessárias caso não houvesse o "| nomore" no comando no switch, ia ser necessário para o oxidized paginar a config.
#      #  expect /^.*--More--\s+$/ do |data, re|
#      #    send ' '
#      #    data.sub re, ''
#      #  end
#
#      #descomentar as linhas abaixo caso queira que as linhas do arquivo sejam comentadas
        cmd 'show running-config | nomore'# do | cfg |
#        #    comment cfg
#        #  end

          cfg :ssh do
             pre_logout 'exit'
          end

end`

Valida se vai funcionar pra você

**Comment by aelxdc** [comment]
> Bom dia, alguém conseguiu resolver essa issue e poderia compartilhar conosco o seu arquivo datacom-4370.rb?

> Bom dia, alguém conseguiu resolver essa issue e poderia compartilhar conosco o seu arquivo datacom-4370.rb?

Tive um problema parecido aqui com os 4370 pelo fato deles já virem com o DMOS. Acabei criando um novo arquivo "dmos.rb" pra não alterar o arquivo datacom.rb

Arquivo **/usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/model/dmos.rb**

```class DmOs < Oxidized::Model
  #using Refinements

    comment '! '

    prompt /^.*#\s$/
#      #As linhas abaixo seriam necessárias caso não houvesse o "| nomore" no comando no switch, ia ser necessário para o oxidized paginar a config.
#      #  expect /^.*--More--\s+$/ do |data, re|
#      #    send ' '
#      #    data.sub re, ''
#      #  end
#
#      #descomentar as linhas abaixo caso queira que as linhas do arquivo sejam comentadas
        cmd 'show running-config | nomore'# do | cfg |
#        #    comment cfg
#        #  end

          cfg :ssh do
             pre_logout 'exit'
          end

end```

Valida se vai funcionar pra você

**Comment by aelxdc** [comment]
> Bom dia, alguém conseguiu resolver essa issue e poderia compartilhar conosco o seu arquivo datacom-4370.rb?

> Bom dia, alguém conseguiu resolver essa issue e poderia compartilhar conosco o seu arquivo datacom-4370.rb?

> Bom dia, alguém conseguiu resolver essa issue e poderia compartilhar conosco o seu arquivo datacom-4370.rb?

Tive um problema parecido aqui com os 4370 pelo fato deles já virem com o DMOS. Acabei criando um novo arquivo "dmos.rb" pra não alterar o arquivo datacom.rb

Arquivo **/usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/model/dmos.rb**

```
class DmOs < Oxidized::Model
  #using Refinements

    comment '! '

    prompt /^.*#\s$/
#      #As linhas abaixo seriam necessárias caso não houvesse o "| nomore" no comando no switch, ia ser necessário para o oxidized paginar a config.
#      #  expect /^.*--More--\s+$/ do |data, re|
#      #    send ' '
#      #    data.sub re, ''
#      #  end
#
#      #descomentar as linhas abaixo caso queira que as linhas do arquivo sejam comentadas
        cmd 'show running-config | nomore'# do | cfg |
#        #    comment cfg
#        #  end

          cfg :ssh do
             pre_logout 'exit'
          end

end
```

Valida se vai funcionar pra você

**Comment by Albuquerque1986** [comment]
Segue um exemplo de configuração que obtive sucesso DM4050, DM4370, DM 4770, DM4170, DM4380

albuquerque@ cat /home/albuquerque/datacom_model_custom.rb
#!/usr/bin/env ruby

class Datacom < Oxidized::Model
  # Datacom DmOS Model
  # Overridding the default datacom model to fix prompt detection

  # Validated prompt that ignores banners and common ANSI codes (like DECAWM)
  # Removed start anchor to allow matching even if preceded by other chars/codes
  # Updated to include [ and ] for NAME hosts
  prompt /(\e\[\?7h)?([\w.@():\[\]-]+[#>]\s?)$/

  comment '! '

  cmd :all do |cfg|
    cfg
  end

  cmd 'show running-config | nomore' do |cfg|
    # Optional: remove comments if needed
    # cfg.gsub! /^!.*$/, ''
    cfg
  end

  cfg :ssh do
    pre_logout 'exit'
  end
end




====================================================================================================

---
resolve_dns: false
username: admin
password: password
model: datacom
interval: 86400
use_syslog: false
debug: true
threads: 30
timeout: 300
retries: 3
prompt: !ruby/regexp /^([\w.@():-]+[#>]\s?)$/
rest: 0.0.0.0:8888
vars: {}
groups: {}
models: {}
pid: "/home/oxidized/.config/oxidized/pid"
input:
  default: ssh, telnet
  debug: false
  ssh:
    secure: false
output:
  default: git
  git:
    user: Oxidized
    email: oxidized@example.com
    repo: "/home/oxidized/.config/oxidized/default.git"
source:
  default: csv
  csv:
    file: "/home/oxidized/.config/oxidized/router.db"
    delimiter: ":"
    map:
      name: 0
      ip: 4
      model: 1
      username: 2
      password: 3
    vars_map:
      ssh_port: 5

#!/bin/bash

# Este script dispara o backup manualmente para todos os nós listados no Oxidized.

echo "Iniciando trigger de backup para todos os nós..."

# Obtém a lista de nós via API e itera sobre cada um
curl -s http://localhost:8888/nodes.json | python3 -c "
import sys, json
try:
    nodes = json.load(sys.stdin)
    for n in nodes:
        print(n['name'])
except Exception as e:
    print('')
" | while read node; do
  if [ ! -z "$node" ]; then
    echo "Disparando backup para: $node"
    # Chama o endpoint /node/next para agendar o backup imediato
    curl -s -o /dev/null "http://localhost:8888/node/next/$node"
  fi
done

echo "Todos os backups foram agendados."

======================================================================================================
