### ISSUE TITLE
Cisco Catalyst 3750 Config Pull Issue

### ISSUE THREAD

**Issue by mmj1000** [ytti/oxidized#2153]
I have oxidixed installed on Ubuntu 18.04 and is working well except for one switch. It is a Cisco 3750 Catalyst. I am having an issue with oxidized pulling the config from this switch. When I start the ozidized service I receive these messages pertaining to this one switch: "lib/oxidized/input/ssh.rb show vtp status @ XXXXXX with expect: /^([\w.@()-]+[#>]\s?)$/" and "lib/oxidized/input/ssh.rb: expecting [/^([\w.@()-]+[#>]\s?)$/] at XXXXXXX". Not sure how to interpret this. Any help would be appreciated. Thanks in advance.

**Comment by swingao** [comment]
maybe your device's hostname not matching configured prompt   
the default prompt in config is   prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/

**Comment by DarkCatapulter** [comment]
Not enough info to help you out. Please do following steps.

1. Enable debug in your config if you already haven't done this.
2. Restart the oxidized service using `systemctl restart oxidized`
3. Share your log output with us.

When you share your logs, please paste it into the comment like this:

\`\`\`
_Your log here_
\`\`\`
And you will end up with something looking like this:
```
This is my log
```
This will make it easier for us to read your logs and help you out.
