### ISSUE TITLE
oxidized superclass mismatch for class http

### ISSUE THREAD

**Issue by typecookie** [ytti/oxidized#2154]
When using http as input and connected to librenms (using http as source)

possibly i am just dumb

`input:
  default: ssh, telnet, http
  debug: false
  ssh:
    secure: false
  ftp:
    passive: true
  utf8_encoded: true`

`source:
        default: http
        debug: false
        http:
          url: https://librenms/api/v0/oxidized
          map:
            name: hostname
            model: os
            group: group
          headers:
            X-Auth-Token: '01582bf94c03104ecb7953dsadsadwed'`

**Comment by typecookie** [comment]
any help on this Im willing to do some testing just need pointed in the right direction

**Comment by ytti** [comment]
Where ever this is happening, we need to change reference there to fully qualified class path or we must at least include the Input::X Source::X parent class to disambiguate.

**Comment by typecookie** [comment]
i think it is happening at least for the source in lib/oxidized/nodes.rb  and possibly rewriting the "@source" definition.
Im not sure how to redefine using the Qualified class path Ive tried putting in a couple of variants in a couple of places but i just keep breaking it.

Im a script monkey  and all my code is haky

**Comment by ytti** [comment]
If you have traceback, that would help. Somewhere we say Http, we should say Source::Http or Input::Http to disambiguate.

**Comment by typecookie** [comment]
its not traceback but i have the error log

`superclass mismatch for class HTTP [TypeError]
--------------------------------------------------
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/input/http.rb:6:in `<module:Oxidized>'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/input/http.rb:1:in `<top (required)>'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/manager.rb:9:in `load'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/manager.rb:60:in `loader'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/manager.rb:35:in `add_input'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/node.rb:155:in `block in resolve_input'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/node.rb:154:in `map'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/node.rb:154:in `resolve_input'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/node.rb:23:in `initialize'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:21:in `new'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:21:in `block (2 levels) in load'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:16:in `each'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:16:in `block in load'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:130:in `synchronize'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:130:in `with_lock'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:10:in `load'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:125:in `initialize'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:14:in `new'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:14:in `initialize'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:4:in `new'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:4:in `new'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/cli.rb:13:in `run'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/bin/oxidized:8:in `<top (required)>'
/usr/local/bin/oxidized:23:in `load'
/usr/local/bin/oxidized:23:in `<main>'`

i am grepping around for Http and am only finding that capitalization in the output/http.rb
HTTP not including readme or docs pops up 12 or so times
http is prolific 

if any of this helps or if you have a shortcut to my research how to get you a traceback

**Comment by typecookie** [comment]
I think this is the traceback needed but i dont realy know what to do with it.  it is returning http from node.rb  but i dont know where it is sending it.  

`D, [2020-07-29T15:39:51.851682 #2911] DEBUG -- : node.rb: resolving node key 'model', with passed global value of '' and node value 'routeros'
D, [2020-07-29T15:39:51.851919 #2911] DEBUG -- : node.rb: setting node key 'model' to value 'cambium' from global
D, [2020-07-29T15:39:51.852199 #2911] DEBUG -- : node.rb: returning node key 'model' with value 'routeros'
D, [2020-07-29T15:39:51.852418 #2911] DEBUG -- : lib/oxidized/node.rb: Loading model "routeros"
D, [2020-07-29T15:39:51.853649 #2911] DEBUG -- : lib/oxidized/model/model.rb Added all to the commands list
D, [2020-07-29T15:39:51.854053 #2911] DEBUG -- : lib/oxidized/model/model.rb Added /system routerboard print without-paging to the commands list
D, [2020-07-29T15:39:51.854285 #2911] DEBUG -- : lib/oxidized/model/model.rb Added /system package update print without-paging to the commands list
D, [2020-07-29T15:39:51.854586 #2911] DEBUG -- : lib/oxidized/model/model.rb Added /system history print without-paging to the commands list
D, [2020-07-29T15:39:51.855210 #2911] DEBUG -- : node.rb: resolving node key 'input', with passed global value of 'ssh, telnet, http' and node value ''
D, [2020-07-29T15:39:51.855437 #2911] DEBUG -- : node.rb: returning node key 'input' with value 'ssh, telnet, http'`

**Comment by ytti** [comment]
Bot of the HTTP classes are just under `module Oxidized`. We need to move one of them to its own name space and change every reference.
Potentially we'd do it for source, as it's less work.

In every lib/oxidized/source file:
```ruby
module Oxidized
module Source
   ..old stuff...
end
end
``` 

We almost certainly also need to update `manager.rb` `load`method, so it is bit more involved than just disambiguation.

**Comment by typecookie** [comment]
so as this is a bit out of my realm and skills (almost no ruby) can i take something else off your plate while this gets road maped

**Comment by ytti** [comment]
Yeah it may not be appropriate for first ruby contribution, than you for your offer. It is definitely a bug and frankly rather embarrassing design mistake, not a complex one to fix, so let's hope someone with some ruby background appears to the rescue.

**Comment by ytti** [comment]
As a workaround, you could copy either source/http.rb to your $OXIDIZED_HOME/source/  or ~/.config/source/ directory as any other name and change the files class name to match filename, then use that source in config, instead of http.

Like perhaps `httpsource.rb` and `HttpSource`. 

Like dunno maybe call it httpsource.rb and change class from Http to HttpSource or some such.

**Comment by typecookie** [comment]
I got this monkey fixed.   I created a source folder in /home/oxidized/.config/oxidized  copied http.rb from the gems directory renamed it sourcehttp.rb then changed the class to `class SourceHTTP < Source`  an changed the "@cfg" to `@cfg = Oxidized.config.source.sourcehttp`  this seems to work as far as being a good stable temp solution.

**Comment by ytti** [comment]
Yes that will work, and it won't break during upgrades.

**Comment by andyrosen** [comment]
I tried the work around that @typecookie suggested by copying the source http.rb file into ~/.config/oxidized/source directory and renaming the file and class to sourcehttp/SourceHTTP but am still getting a superclass mismatch when adding http to the input default.   Do I need to tell oxidized to look in that path?   Traceback output at: https://pastebin.com/kmkU7djV  -Thanks

**Comment by kimhaak** [comment]
Hi,

Was this ever fixed? 

I am facing the same issue now, it seems.

**Comment by kimhaak** [comment]
Ok, i got this workaround sorted. For the next guy:

I did what typecookie said and then i changed in the config file:

source:
    default: sourcehttp
    debug: true
    sourcehttp:
      url: http://librenms.****/api/v0/oxidized
      
I also had to install gem "mechanized"

**Comment by michieltimmers** [comment]
Anybody with ruby skills that can fix this? Would rather wait for that then do a workaround.
