### ISSUE TITLE
ZynOSGS prompt not found

### ISSUE THREAD

**Issue by y9-csillagd** [ytti/oxidized#2156]
Hy

The app is very good and I am grateful to you for it. Thank you for your work.

The error is as follows!

The prompt regex is:
prompt /^.*# $ /
However, this does not work. Can't find the prompt.

This is in the log file:
"W, [2020-07-17T08:57:22.459796 #27]  WARN -- : 10.10.9.2 raised Oxidized::PromptUndetect with msg "unable to detect prompt: (?-mix:^.*# $)"
W, [2020-07-17T08:57:23.226773 #27]  WARN -- : /sw1 status no_connection, retry attempt 2
W, [2020-07-17T08:57:45.417867 #27]  WARN -- : 192.168.1.2 raised Oxidized::PromptUndetect with msg "Copyright (c) 1994 - 2018 Zyxel Communications Corp.
GS1920#7 not matching configured prompt (?-mix:^.*# $)"
"

If I remove the "$" the save is successful.
prompt /^.*#/

The output will be when it runs:
"show running-config
7777777777777777777  Building configuration...

  Current configuration: 

vlan 1 
  name 1 
...(etc.)...
GS1920# 7"

If you need any further information, please contact me.

**Comment by bkopecssm** [comment]
Hi !
DO you resolved your issue ?
I have te same problems with GS1920. 
GS1900 works fine.
Thanks.

**Comment by y9-csillagd** [comment]
Hi @bkopecssm 

This device is also a GS1920. The solution is included in the description, but unfortunately the developer has not yet improved it.
