### ISSUE TITLE
Direct upload of configs

### ISSUE THREAD

**Issue by jameskirsop** [ytti/oxidized#2164]
Partly putting this in as a feature request, and partly as a query.

Our networking team has identified a number of devices that Oxidized doesn't support, and given their problematic CLI, it would be difficult to write a reliable Oxidized model for them (eg #1487). Other input methods (HTTP/FTP etc) would not be suitable either as they're not generally supported by the devices.

We would still like to use Oxidized as the central place for storing backups of our devices, but given the above difficulties, we would need some way of directly uploading a copied dump of the config via a browser. To us it doesn't make sense to copy this to _another_ web service (that we would have to build ourselves) so that Oxidized could pull it in via an already supported method.

I would rather invest my time to extend the functionality of Oxidized so that we could annotate particular devices with a `manual` flag and have the Oxidized-web REST framework accept a dump posted from the UI, and save that to the configured output (and do diffing etc). We understand that we would need to manually maintain the upload of these configs, but we would need to do that regardless of the system we used, and there are clear advantages of having all configurations stored in one repository.

I'm happy to work on this if people think it's a good idea. Alternatively, if there are other approaches to this problem that are worth discussing, I'd be happy to hear them.

**Comment by ytti** [comment]
We support `exec` input models which allow you to run arbitrary shell commands and store the output. I do wonder though, how was the output produced in the first place, if it's possible by some other means, it should be possible via oxidized. 

I'm open to REST API.

**Comment by jameskirsop** [comment]
>  I do wonder though, how was the output produced in the first place, if it's possible by some other means, it should be possible via oxidized.

That's a fair query, but the key word in my original post was _reliable_. We've got instances where Oxidized will falsely report success (like in the #1487), or others where the CLI appears to be too cumbersome to be able to extract useful config from programatically (or at least, that's what our network engineers tell me). We want to have _more_ certainty that the config stored for these particular devices is reliable, and at this stage it seems the most feasible solution for achieving that goal is human intervention.

I'll create a fork, try and build something (I've not seriously written Ruby in a decade) and submit some PR's along the way to make sure I'm on the right track.

**Comment by ytti** [comment]
I'm still confused what the reliable method is, and why that method isn't portable to Oxidized. But basically functionality you are asking is firing off output call without having device or model, it will preclude some functionality but is possible to retrofit without forklift. Using `exec` based model and node might be worth considering.

**Comment by jameskirsop** [comment]
I'm fine with precluding some functionality as a trade off to be able to store all our configurations in one place without having Oxidized report a successful backup when it's actually not completed the job correctly (the whole point of #1487).

**Comment by typecookie** [comment]
why not set up gitlab as the output storage for oxidized then using standard git methods store you non oxidized configs
that's how i keep my puppet configs diffed and in a common location

**Comment by jameskirsop** [comment]
> why not set up gitlab as the output storage for oxidized then using standard git methods store your non oxidized configs
> that's how i keep my puppet configs diffed and in a common location

I've already considered this and sure, I _could_ do this, but we shouldn't expect or need network engineers to know how to use Git to be able to backup configuration. We also shouldn't aim to decentralise and use _another_ tool to do part of a job that is typically handled by an established tool where possible.

These are the reasons why I wrote in my opening comment, _"We would still like to use Oxidized as the central place for storing backups of our devices ... we would need some way of directly uploading a copied dump of the config via a browser."_
