### ISSUE TITLE
Slack hook not usable

### ISSUE THREAD

**Issue by CamBanfield** [ytti/oxidized#2167]
It seems that Slack have fully removed the ability to create new "legacy" tokens and therefore it's not possible to use this hook. I have attempted generating a webhook and using this token, however it does not work. 

It may be that this integration needs updating to support the new Slack App API system?

Many thanks

**Comment by vincent516** [comment]
I was able to setup the integration with Slack recently by creating a Slack Classic App (https://api.slack.com/apps?new_classic_app=1).  I created a bot and used the Bot User OAuth Access Token in the Oxidized config file.  Give it a shot, this should work.

**Comment by h-barnhart** [comment]
Worked for me

**Comment by lowk3y** [comment]
I made slack hook working, but I don't get diff as a snippet at all. Any hints?
