### ISSUE TITLE
Feature Request: Cisco Devices, Store Running AND Startup Config

### ISSUE THREAD

**Issue by Rosiak** [ytti/oxidized#217]
For now Oxidized only cares about the running config, would be nice if it could store the startup config too!

**Comment by ytti** [comment]
You could do this already

copy ios.rb to ~/.config/oxidized/model

and add there something like

cmd 'show startup-config' do |cfg|
   cfg.type = 'startup'
   cfg
end


Now you should have new repo or directory with 'startup' config in it, depending on git settings.

**Comment by Rosiak** [comment]
Hi @ytti,
Yes I figured that. 
What I'm looking for is if this being considered merging into the Oxidized or perhaps a more refined way?

**Comment by ytti** [comment]
Not sure what default way would be comfortable for mainline, consider the concept isn't portable across vendors.

**Comment by ytti** [comment]
The suggested/proposed way to do model changes which are not relevant to all, is to make ```~/.config/oxidized/model/ios.rb``` in that file put something like

```
require 'oxidized/model/ios.rb'
class IOS < Oxidized::Model'
  cmd 'show startup-config' do |cfg|
     cfg.type = 'startup'
     cfg
  end
end
```

Now you are tracking the released model, but also adding your own local changes to it, in this case separate file named 'startup' for startup configs.

**Comment by danilopopeye** [comment]
@ytti there's a extra `'` after `Oxidized::Model` that shouldn't be there. :smiley:

**Comment by ytti** [comment]
Thanks 👍
