### ISSUE TITLE
Oxidized Service Fails to Start After Changing Source

### ISSUE THREAD

**Issue by CNSDrew** [ytti/oxidized#2171]
Good afternoon,

I've been playing around with Oxidized, and have been successful in getting it setup to run backups from a CSV file. I'm now attempting to switch gears to feed Oxidized from LibreNMS. After changing the configuration file to do so, I'm now getting an error when attempting to start the oxidized service. I've verified that the X-Auth-Token is working against the API call to LibreNMS. I'm not a very heavy Linux user at all, so I apologize if I'm simply being ignorant here, but can anyone point me in the right direction for how to fix this? Any help is appreciated!

```
My config:

username: omitted
password: omitted
model: ios
resolve_dns: true
interval: 3600
use_syslog: false
debug: false
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /[#>]/
rest: 127.0.0.1:8888
next_adds_job: false
vars: {}
groups:
 IOS-XR:
  username: omitted
  password: omitted
 IOS-XE:
  username: omitted
  password: omitted
 NX-OS:
  username: omitted
  password: omitted
 ASA:
  username: omitted
  password: omitted
models:
 iosxe:
  vars:
   enable: omitted
 ios:
  vars:
   enable: omitted
 asa:
  vars:
   enable: omitted
pid: "/root/.config/oxidized/pid"
crash:
  directory: "/root/.config/oxidized/crashes"
  hostnames: false
stats:
  history_size: 10
input:
  default: ssh, telnet
  debug: false
  ssh:
    secure: false
  ftp:
    passive: true
  utf8_encoded: true
output:
  default: git
  git:
   user: Oxidized
   email: oxidized@cns.com
   repo: "/home/admincns/oxidized/devices.git"
source:
  default: csv
  csv:
    file: "/root/.config/oxidized/router.db"
    delimiter: !ruby/regexp /:/
    map:
      name: 0
	  ip: 1
      group: 2
      model: 3
    gpg: false
model_map:
  juniper: junos
  cisco: ios
```
```
Source Configuration I attempted to use:

source:
  default: http
  debug: false
  http:
    url: http://127.0.0.1:8888/api/v0/oxidized
    map:
      name: hostname
      model: os
      group: group
    headers:
      X-Auth-Token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```
```
After restarting the Oxidized service:

systemctl status oxidized
â— oxidized.service - Oxidized - Network Device Configuration Backup Tool
   Loaded: loaded (/lib/systemd/system/oxidized.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Thu 2020-09-10 07:48:24 CDT; 12s ago
  Process: 20670 ExecStart=/usr/local/bin/oxidized (code=exited, status=1/FAILURE)
 Main PID: 20670 (code=exited, status=1/FAILURE)

Sep 10 07:48:24 librenms-01 systemd[1]: oxidized.service: Main process exited, code=exited, status=1/FAILURE
Sep 10 07:48:24 librenms-01 systemd[1]: oxidized.service: Failed with result 'exit-code'.

```
```
And here is the crash file output:

2020-09-10 12:45:31 UTC
Failed to open TCP connection to 127.0.0.1:8888 (Connection refused - connect(2) for "127.0.0.1" port 8888) [Errno::ECONNREFUSED]
--------------------------------------------------
/usr/lib/ruby/2.5.0/net/http.rb:939:in `rescue in block in connect'
/usr/lib/ruby/2.5.0/net/http.rb:936:in `block in connect'
/usr/lib/ruby/2.5.0/timeout.rb:93:in `block in timeout'
/usr/lib/ruby/2.5.0/timeout.rb:103:in `timeout'
/usr/lib/ruby/2.5.0/net/http.rb:935:in `connect'
/usr/lib/ruby/2.5.0/net/http.rb:920:in `do_start'
/usr/lib/ruby/2.5.0/net/http.rb:909:in `start'
/usr/lib/ruby/2.5.0/net/http.rb:1458:in `request'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/source/http.rb:74:in `read_http'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/source/http.rb:21:in `load'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:15:in `block in load'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:130:in `synchronize'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:130:in `with_lock'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:10:in `load'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:125:in `initialize'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:14:in `new'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:14:in `initialize'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:4:in `new'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:4:in `new'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/cli.rb:13:in `run'
/var/lib/gems/2.5.0/gems/oxidized-0.28.0/bin/oxidized:8:in `<top (required)>'
/usr/local/bin/oxidized:23:in `load'
/usr/local/bin/oxidized:23:in `<main>'
```

**Comment by CNSDrew** [comment]
I apologize, I realized I had done a rollback to a previous snapshot in VMWare to get it working again, and the X-Auth token had been removed during the rollback. I have corrected that issue, and now I'm simply getting the following error when attempting to start Oxidized:

systemctl status oxidized
â— oxidized.service - Oxidized - Network Device Configuration Backup Tool
   Loaded: loaded (/lib/systemd/system/oxidized.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Wed 2020-08-19 15:23:56 CDT; 4s ago
  Process: 13884 ExecStart=/usr/local/bin/oxidized (code=exited, status=1/FAILURE)
 Main PID: 13884 (code=exited, status=1/FAILURE)

What's the best way to find out what's going on with this?

**Comment by DarkCatapulter** [comment]
I'm sorry pal, but I'm not gonna help you unless you edit your comments and structure it up. Could you please edit your comment and reformat your config and your logs? It's way to much work to read this, especially for someone like me that likes to read from my phone. So to help the ones that might want to help you, reformat your config and logs by doing this:

\`\`\`
_Your config here_
\`\`\`
Some text in-between.

\`\`\`
_Your log here_
\`\`\`
And you will get something that looks like this:

```
This is my config
I can extend it to multiple lines
```
And then
```
This is my log
```

If you do this then I'll consider helping you out.

**Comment by twelch24** [comment]
I think this line says all:
Failed to open TCP connection to 127.0.0.1:8888 (Connection refused - connect(2) for "127.0.0.1" port 8888) [Errno::ECONNREFUSED]

You should be connecting to your librenms install, not the oxidized install.. so unless your librenms normal page is at 127.0.0.1:8888 this will fail.

**Comment by CNSDrew** [comment]
Derrrrp. I was absent mindedly trying to recreate the issue as I modified my post format, due to the first comment. I'll correct that and repost on the failure tomorrow.

**Comment by mortzu** [comment]
Used own oxidized instance instead of LibreNMS installation -> closed
