### ISSUE TITLE
Using local Git repo as output. Cant view config diffs.

### ISSUE THREAD

**Issue by SkylerBlumer** [ytti/oxidized#2172]
When ever we try to view a compare, or older versions of a config the GUI just spins. Waited many minutes and eventually got:
Proxy Error

The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request

Reason: Error reading from remote server

**Comment by elmobp** [comment]
I know this is old but you should cron a git gc on all the repo's and it will fix it https://www.atlassian.com/git/tutorials/git-gc

**Comment by davama** [comment]
This looks like a [oxideized-web](https://github.com/ytti/oxidized-web) question.

Either way i would use cgit as a web frontend for your repos

**Comment by elmobp** [comment]
@davama  its the git gc.. we seen it with some massive repo's the git repos were > 5gb at one point as it wasn't doing gc prob a good idea to add git gc hooks into web

**Comment by davama** [comment]
Ah i see.
5G+ repo on a network device?! That’s insane. 
We clean up after a year or so because then our repo become unusable. No point for keeping changes 1yr+ old

**Comment by elmobp** [comment]
it was the rate of change :|
