### ISSUE TITLE
Oxidized issue 3Com Switches

### ISSUE THREAD

**Issue by lucdnb** [ytti/oxidized#2173]
I have try to configure Oxidized in my network envirolment, and one of my problems that i've passing, the most problematic are ths 3Com switches (have a lot o them), which Oxidized dont backup them.
I have try a lot of possible solutions, but nothing has success yet.
In all of those switches log file, show that Oxidized dont have type the "system-view" command. He pass to login but nothing more:

********************************************************************************
*  Copyright(c) 2004-2009 3Com Corp. and its licensors. All rights reserved.   *
*  Without the owner's prior written consent,                                  *
*  no decompiling or reverse-engineering shall be allowed.                     *
********************************************************************************
Login authentication

Username:admin
Password:
<3Com_Switch>
~

Actually, i am trying to make Oxidized works with the default (csv file), but after tests, i've want to integrate her with LibreNMS.
Well, part of my config file is here:

source:
  default: csv
  debug: true
  csv:
    file: "/path/of/my/router.db"
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      ip: 1
      model: 2
      group: 3
      username: 4
      password: 5

Someone have a light for me? Thanks in advance!!!

**Comment by xosepe** [comment]
Hi! I have lots of 3Com switches being backup up correctly. What models are you talking about? 
In the regular ones (like 4200G, 5500, SuperStack), there are 2 key modifications you need to configure in them: 

info-center source default channel 1 log state off debug state off

and also (under "user-interface vty 0 4"): 
 screen-length 0

Apart from that, I think there are some 3Coms that work like some HP switches: CLI mode is limited by default and you need to enable the advanded view with a hidden command and a hardcoded password, like this HP
https://networkguy.de/enabling-advanced-cli-on-hp-v1910-switches/

If this the case, then you need to use the field "comware_cmdline" in your "config" file. Somethink like this: 

    map:
      name: 0
      model: 1
      ip: 2
      username: 3
      password: 4
    vars_map:
      comware_cmdline: 5

**Comment by lucdnb** [comment]
Thanks for response! There is that i was need. After apply the "screen-length 0" command, all my 3Com switches have been take the configs. 

I remeber that i was do it before, but probably with lot of tests, i left something back...  

Thanks for help, have solve my problem witch 3Com devices. Now let go to others many... Oxidized have a little of.

**Comment by lucdnb** [comment]
Problem solved.
