### ISSUE TITLE
0.28 Ironware updates not working anymore.

### ISSUE THREAD

**Issue by roedie** [ytti/oxidized#2176]
Hi,

I've just upgraded oxidized to 0.28 and now all me Ironware switches are failing. It seems like #1943 breaks is. Reverting that PR fixes it.

Regards,

Sander

**Comment by wk** [comment]
Hi!

Are you accessing the device over SSH or over Telnet? @JimKlapwijk, could you comment if the issues you've observed leading to #1943 were with devices configured for Telnet or SSH access?

**Comment by roedie** [comment]
Hi,

I am checking my devices over SSH. I've migrated them from telnet some time ago. Both had been working in the past. I can check again.

**Comment by roedie** [comment]
Just checked, I can check my devices with both telnet and ssh with the previous version of the plugin. Now I have to say these are older devices with old firmware (2014), but sending \r\n still seems very odd to me.

AFAIK \r\n is only used on Windows based OS-es.

**Comment by JimKlapwijk** [comment]
> Hi!
> 
> Are you accessing the device over SSH or over Telnet? @JimKlapwijk, could you comment if the issues you've observed leading to #1943 were with devices configured for Telnet or SSH access?

It's been almost a year and left the company since, so I don't have access to it anymore. But I believe this was SSH. 



> Hi,
> 
> I've just upgraded oxidized to 0.28 and now all me Ironware switches are failing. It seems like #1943 breaks is. Reverting that PR fixes it.
> 
> Regards,
> 
> Sander

Are you able to provide us with an error log of some sort, because _failing_ is quite a big word...
Thank you in advance!

**Comment by roedie** [comment]
I know bigger words ;-)

But, here is the output of one of them. It seems like the \r\n is now doing 2 newlines after the enable. So, the password is pasted directly on the CLI again. After that everything goes haywire:

```
SSH@fls-asd-02>enable
Password:
Error - incorrect password.
SSH@fls-asd-02>*REDACTED PASSWORD*

Invalid input -> *REDACTED PASSWORD*
Type ? for a list
SSH@fls-asd-02>

SSH@fls-asd-02>skip-page-display

Invalid input -> skip-page-display
Type ? for a list
SSH@fls-asd-02>terminal length 0

Invalid input -> terminal length 0
Type ? for a list
SSH@fls-asd-02>show version

  Copyright (c) 1996-2010 Brocade Communications Systems, Inc.
    UNIT 1: compiled on Nov 05 2012 at 21:40:52 labeled as FGS07202h
		(2878228 bytes) from Secondary FastIronLS-STK/Images/FGS07202h.
        SW: Version 07.2.02hT7e1 
  Boot-Monitor Image size = 416213, Version:05.0.00T7e5 (Fev2)
  HW: Stackable FLS648
==========================================================================
UNIT 1: SL 1: FLS-48G 48-port Management Module
 	 Serial  #: REDACTED
 	 P-ENGINE  0: type D804, rev 01
 	 P-ENGINE  1: type D804, rev 01
==========================================================================
  400 MHz Power PC processor 8248 (version 130/2014) 66 MHz bus
  512 KB boot flash memory
30720 KB code flash memory
  128 MB DRAM
STACKID 1  system uptime is 1802 days 21 hours 32 minutes 53 seconds 
The system : started=cold start	 

SSH@fls-asd-02>show chassis

The stack unit 1 chassis info: 

Power supply 1 (NA - AC - Regular) present, status ok
Power supply 2 not present

Fan 1 ok, speed (auto): 1<->2<->[[3]]
Fan 2 ok, speed (auto): 1<->2<->[[3]]
Fan 3 ok, speed (auto): 1<->2<->[[3]]

Fan controlled temperature: 53.5 deg-C

Fan speed switching temperature thresholds:
		Speed 1: NM<----->53             deg-C
		Speed 2:       37<----->55       deg-C
		Speed 3:             50<-----> 90 deg-C (shutdown)

Sensor B Temperature Readings:
	Current temperature : 53.5 deg-C
Sensor A Temperature Readings:
	Current temperature : 51.5 deg-C
	Warning level.......: 85.0 deg-C
	Shutdown level......: 90.0 deg-C
Boot Prom MAC : 001b.ed5e.cdc0
--More--, next page: Space, next line: Return key, quit: Control-c
```

**Comment by JimKlapwijk** [comment]
Thank you. Unfortunately I don't have access to any Ironware OS at the moment, so I am unable to help you further troubleshoot.
I hope that with the error someone gave you can help you further out! My sincere apologies.

**Comment by jbparrish17** [comment]
I may have this same issue, but could be unrelated. I have configured telnet for ironware devices and enabled debugging. It appears that my Ironware devices are queued, but I don't see any telnet attempts to the device at all. Logs appear like so:
`D, DEBUG -- : lib/oxidized/job.rb: Starting fetching process for 172.16.1.1 at 2020-09-17 19:13:13 UTC
D, DEBUG -- : lib/oxidized/job.rb: Config fetched for 172.16.1.1 at 2020-09-17 19:13:13 UTC
W, WARN -- : default/172.16.1.1 status fail, retry attempt 1`

**Comment by roedie** [comment]
@jbparrish17 Hmmm, I saw about the same when I was testing telnet. Did it work with the oxidized 0.27?

**Comment by alven-kim** [comment]
Hello. I had the same symptoms.
My version was 0.28 and I solved it by changing ironware.rb to version 0.21
Comparing the two versions, there were some different settings, such as Newline.

**Comment by roedie** [comment]
I'm pretty sure the newline is at least one of the problems. It seems very strange to me to send a \r\n in a telnet/ssh session. I have never seen that before.
