### ISSUE TITLE
Does oxidized support Linksys sps224g4 models ?

### ISSUE THREAD

**Issue by freedomwarrior** [ytti/oxidized#2184]
Is it possible to add them?

**Comment by systeembeheerder** [comment]
If it has an ssh shell oxidized can support it :)

Linksys Switches became Cisco Small Business. You can try the https://github.com/ytti/oxidized/blob/master/lib/oxidized/model/ciscosmb.rb model.

**Comment by mortzu** [comment]
Does it provide a CLI?
