### ISSUE TITLE
where to configure ssh key passphrase?

### ISSUE THREAD

**Issue by userthomas** [ytti/oxidized#2185]
Hello,

to login to my switches i want to use ssh with public key authentication and passphrase. 
At the moment i can see in the debug log: 
Sep 11 15:02:30 oxi oxidized[19731]: Enter passphrase for /home/oxidized/.ssh/id_rsa:E, [2020-09-11T15:02:30.668382 #19731] ERROR -- :
so i need to tell oxidized the passphrase, but where and how to configure?
Login using ssh keys without a passphrase is already working. 

Thomas

**Comment by Patrik-Netent** [comment]
The following environment variable must be assigned the passphrase.
```OXIDIZED_SSH_PASSPHRASE=key_passphrase```

**Comment by mortzu** [comment]
no-feedback -> closed
