### ISSUE TITLE
Oxidized wont daemonise if there are no nodes/devices configured yet.

### ISSUE THREAD

**Issue by ezanolin** [ytti/oxidized#2186]
I am writing an application that uses Oxidized in the back end for device backups using the HTTP source method. I use the HTTP API to query and reload Oxidized but oxidized will not run if the HTTP source response contains no nodes. This means the HTTP API wont run which means when I add a node for the first time I am unable to reload using the API call and instead have to try do a system exec to try and start oxidized ie "systemctl start oxidized.service". Is there any way to have the Oxidized and Oxidized-web service running with no nodes.

If I return empty JSON text I get
source returns no usable nodes

If I return a blank response I get
765: unexpected token at '' 

Once I add the first node/device everything works fine. My only solution at the moment is to return a dummy device entry if there are none, which means Oxidized will try a few times to back it up before giving up but does stay running. This is obviously not a great workaround.

Thank you.

**Comment by mortzu** [comment]
Can you provide a PR to fix this issue?

**Comment by JohnnyBBravo** [comment]
I'm facing the same issue.
If you (or anyone) is able to fix this, then I would be eternally grateful (sorry, I don't know how to do this myself)
Thx!!
