### ISSUE TITLE
Oxidized can't get full configuration of HPE 5130 switch

### ISSUE THREAD

**Issue by simral** [ytti/oxidized#2187]
Hi everyone, we have Oxidized server which can successfully get configuration of Cisco, Aruba and Huawei switches. But today, I observed that, it cannot get full configuration of HPE 5130 comware switch.

![image](https://user-images.githubusercontent.com/3505212/93981502-215c3e00-fd91-11ea-86a3-962449c73354.png)
It is configuration pulled by Oxidized server. It is not full configuration.
[comware.txt](https://github.com/ytti/oxidized/files/5266423/comware.txt)

**Comment by xosepe** [comment]
Hi simral! It´s strange. I have lots of HPE 5130 switches being backup correctly with an old version of oxidized and comware model. The difference with the previous HP Comware 5 is that I had to enable SSH in these Comware7 switches. With telnet it did not work at all. But I´ve never seen a case of configuration not being fully backed up.

**Comment by renadown** [comment]
does anyone have the correct model for this HP 5130?

**Comment by xosepe** [comment]
> does anyone have the correct model for this HP 5130?

Yes. It's a Comware 7 device. 
Comware.rb is its model.
