### ISSUE TITLE
/usr/lib/ruby/1.9.1/psych.rb:203:in `parse': (<unknown>): found character that cannot start any token while scanning for the next token at line 28 column 1 (Psych::SyntaxError)

### ISSUE THREAD

**Issue by msenturk** [ytti/oxidized#219]
Im getting  this error after setup configs:

/usr/lib/ruby/1.9.1/psych.rb:203:in `parse': (<unknown>): found character that cannot start any token while scanning for the next token at line 28 column 1 (Psych::SyntaxError)
        from /usr/lib/ruby/1.9.1/psych.rb:203:in `parse_stream'
        from /usr/lib/ruby/1.9.1/psych.rb:151:in `parse'
        from /usr/lib/ruby/1.9.1/psych.rb:127:in `load'
        from /var/lib/gems/1.9.1/gems/asetus-0.3.0/lib/asetus/adapter/yaml.rb:21:in `from'
        from /var/lib/gems/1.9.1/gems/asetus-0.3.0/lib/asetus/adapter/yaml.rb:8:in `from_yaml'
        from /var/lib/gems/1.9.1/gems/asetus-0.3.0/lib/asetus.rb:142:in `from'
        from /var/lib/gems/1.9.1/gems/asetus-0.3.0/lib/asetus.rb:120:in `load_cfg'
        from /var/lib/gems/1.9.1/gems/asetus-0.3.0/lib/asetus.rb:51:in `load'
        from /var/lib/gems/1.9.1/gems/oxidized-0.8.1/lib/oxidized/config.rb:46:in `<module:Oxidized>'
        from /var/lib/gems/1.9.1/gems/oxidized-0.8.1/lib/oxidized/config.rb:1:in `<top (required)>'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /var/lib/gems/1.9.1/gems/oxidized-0.8.1/lib/oxidized/core.rb:4:in `<module:Oxidized>'
        from /var/lib/gems/1.9.1/gems/oxidized-0.8.1/lib/oxidized/core.rb:1:in `<top (required)>'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /var/lib/gems/1.9.1/gems/oxidized-0.8.1/lib/oxidized.rb:5:in `<module:Oxidized>'
        from /var/lib/gems/1.9.1/gems/oxidized-0.8.1/lib/oxidized.rb:1:in `<top (required)>'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /var/lib/gems/1.9.1/gems/oxidized-0.8.1/lib/oxidized/cli.rb:3:in `<class:CLI>'
        from /var/lib/gems/1.9.1/gems/oxidized-0.8.1/lib/oxidized/cli.rb:2:in `<module:Oxidized>'
        from /var/lib/gems/1.9.1/gems/oxidized-0.8.1/lib/oxidized/cli.rb:1:in `<top (required)>'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from /var/lib/gems/1.9.1/gems/oxidized-0.8.1/bin/oxidized:8:in `<top (required)>'
        from /usr/local/bin/oxidized:23:in `load'
        from /usr/local/bin/oxidized:23:in `<main>'

-----
this is my config file :

username: username
password: passwd
model: cisco
interval: 3600
log: /home/ubuntu/.config/oxidized/log
debug: false
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
vars: {}
groups: {}
input:
  default: ssh
  debug: true
  ssh:
    secure: true
output:
  default: git
  git:
    user: oxidized
    email: oxidized@xxx.com
    repo: "~/.config/oxidized/config-repo/devices.git"
source:
  default: csv
  csv:
        file: "~/.config/oxidized/router.db"
        delemiter: !ruby/regexp /:/
  map:
        name: 0
        model: 1
model_map:
  cisco: ios
  juniper: junos

-----
router.db file like

192.168.100.14:ios
192.168.100.15:ios
192.168.100.16:ios
192.168.100.17:ios

**Comment by ytti** [comment]
The config file should start with '---' in first line, but I guess you just omitted that. Because it's complaining about line 28.

Could you paste whole config file to 'http://p.ip.fi' quickly at least 'delemiter' is typo error, unsure how it happened, because oxidized should self-create config file on first run, where this error wouldn't exist.
But that wouldn't cause misparsing of  YAML, perhaps there is indent issue, which cannot be seen, as you couldn't encapsulate the data inside ```which would preserve spaces.

**Comment by msenturk** [comment]
Yes you are right I mistakenly deleted '---' and broked yalm format a bit. After fixing config file it worked well. 
thx a lot.
