### ISSUE TITLE
External scripts from model for fetching backups

### ISSUE THREAD

**Issue by n-piipel** [ytti/oxidized#2192]
I want to use external scripts with node.name like params for fetching config from my special devices.

This way isn't working, because in cmd block isn't node.name.
```
class Hikvision < Oxidized::Model

  cmd 'python hikcam.py #{@node.name}' do |cfg|
    cfg
  end

  cfg :exec do
  end

end
```

And I can't pass node name from cfg block to cmd block by variable or by global variable.

And if I use cmd block inside the cfg, it works for getting data from my script, but it doesn't save data to backup file.
```
class Hikvision < Oxidized::Model

  cfg :exec do
    cmd 'python hikcam.py #{@node.name}' do |cfg|
      cfg
    end
  end

end
```

How can I pass the node.name to my script? I really don't understand.

Send me correct examples please!
Thanks! 🙏🙏

**Comment by ytti** [comment]
Inside pre {} or post {} block (pre means above/before the main level commands, post means below/after the main level commands, while rendering the output).

**Comment by n-piipel** [comment]
Yeh, it's working!

```
class Hikvision < Oxidized::Model

  post do
    cmd "python3.6 /root/.config/oxidized/hikcam.py #{@node.name}" do |cfg|
      cfg
    end
  end

  cfg :exec do
  end

end
```

Thank you, masters!

**Comment by jameskirsop** [comment]
@n-piipel, could you share your hikcam.py script with the community?

**Comment by oijkn** [comment]
I'm interested too if someone can share a very basic Python script example, please?
