### ISSUE TITLE
error when run /usr/local/bin/oxidized

### ISSUE THREAD

**Issue by wenyu89** [ytti/oxidized#2204]
Hi there,

my LibreNMS server is OS: Ubuntu 18.0.4, Oxidized version 0.28.0. I am trying to integrate LibreNMS with Oxidized. 

- When I run /usr/local/bin/oxidized, I have error: undefined method `include?' for nil:NilClass

- run systemctl status oxidized.service, error: Process: 6318 ExecStart=/usr/local/bin/oxidized (code=exited, status=1/FAILURE)

Can you please give me an advice?

Thank you.

**Comment by systeembeheerder** [comment]
your config?

**Comment by wenyu89** [comment]
Thanks, my config:
---
username: ssh username
password: ssh password
model: cisco
resolve_dns: true
interval: 3600
use_syslog: true
debug: false
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 127.0.0.1:8888
next_adds_job: false
#vars: {}
groups: {}
models: {}
pid: "/etc/oxidized/pid"
vars:
  remove_secret: true
  enable: switch enable password
crash:
  directory: "/etc/oxidized/crashes"
  hostnames: false
stats:
  history_size: 10
input:
  default: ssh, telnet
  debug: false
  ssh:
    secure: false
  ftp:
    passive: true
  utf8_encoded: true
output:
  default: file
  file:
    directory: "/etc/oxidized/configs"
source:
  default: http
  debug: false
  http:
    url: http:/Librenms server IP/api/v0/oxidized
    map:
      name: hostname
      model: os
      group: group
    headers:
      X-Auth-Token: 'token******'
model_map:
  juniper: junos
  cisco: ios
  nexus: nxos
  fortigate: fortios

**Comment by systeembeheerder** [comment]
config depends on spacing. Did the post remove all spacing or is it all removed from your config. See github Markup to post an exact config.

**Comment by systeembeheerder** [comment]
`` url: http:/Librenms...``
missing an ``/`` here?

**Comment by wenyu89** [comment]
Yes, I missed http://.... Thank you 👍
