### ISSUE TITLE
[BUG]: Telnet doesn't works in TP-Link switches

### ISSUE THREAD

**Issue by piterpunk** [ytti/oxidized#2205]
Connecting to a TP-Link switch using Telnet hangs in a `Login invalid` loop as seen in the debug input below (don't mind the wrong date):
```
***************** User Access Login ********************

User:

 Login invalid.
#2006-01-19 03:11:17,[User]/4/Login the CLI failed by vty0 (192.168.0.42).

***************** User Access Login ********************

User:

 Login invalid.
#2006-01-19 03:11:17,[User]/4/Login the CLI failed by vty0 (192.168.0.42).

***************** User Access Login ********************

User:

 Login invalid.
```
The login regular expression expects `User Name:` but the string sent is only `User:`

**Comment by mortzu** [comment]
With the current firmware?

**Comment by piterpunk** [comment]
Yes, tested with two firmware versions:

- 2.0.5 Build 20200109 Rel.36203
- 2.0.6 Build 20200805 Rel.57865

Today's the `2.0.6 Build 20200805 Rel.57865` is the last one available for my switch in [TP-Link's download page](https://www.tp-link.com/br/support/download/t1500g-10ps/#Firmware)

**Comment by mortzu** [comment]
Can you create a PR which accepts "User:" too?

**Comment by piterpunk** [comment]
> Can you create a PR which accepts "User:" too?

The PR #2206 already accepts `User:`, it's in line [56](https://github.com/ytti/oxidized/blob/391a345cc10661a64066bfd89f80fb179cac35e1/lib/oxidized/model/tplink.rb#L56)
