### ISSUE TITLE
git hook "cannot push non-fastforwardable reference" from Oxidized in Docker

### ISSUE THREAD

**Issue by grind42** [ytti/oxidized#2207]
Hey,
I'm using Oxidized in a Docker container - latest version. I bundled all my config and keys in the container so I don't have to have persistent storage.
When I deploy a new version of that container it's not able to push to my git repo because of "cannot push non-fastforwardable reference". I know how to fix that with persistent storage but I don't want that.
Could we just do a force push? I'm sure the option doesn't exist but it might be worth an RFE?! Or maybe you've got a better idea?

From my config:
output:
  default: git
  git:
    single_repo: true
    user: oxidized
    email: oxidized@oxidized.local
    repo: "/root/.config/oxidized/output/config-files.git"
...
hooks:
  push_to_remote:
    type: githubrepo
    events: [post_store]
    remote_repo: ssh://git@server:port/config-files.git
    privatekey: /root/.config/oxidized/.ssh/id_rsa
    publickey: /root/.config/oxidized/.ssh/id_rsa.pub

Thanks!

**Comment by marrold** [comment]
@grind42 did you find a solution to this? Thanks

**Comment by jonathanlermitage** [comment]
@grind42 Same here, did you find a solution? I'm facing the same issue 😅

**Comment by jonathanlermitage** [comment]
I did a push --force on my repositories (from Oxidized) and it seems to work, but I don't like this solution.  
I mean, what should be the source of thrust: the remote git repo, or the local repo inside Oxidized? Ideally, I should be able to modify the remote git repo (for any reason, like migrating to a new infrastructure and restoring a backup of the git server, reinstalling Oxidized, things like that), and Oxidized should be able sync with the remote repo.
