### ISSUE TITLE
 Problem for pushing data from Oxidized Docker to Gitlab (On Premise or SaaS)

### ISSUE THREAD

**Issue by sgelineau17** [ytti/oxidized#2212]
Hi,

I need your help !

I am using Oxidized and LibreNMS on a CentOS 8 VM everything works fine, my backups are sent to a gitlab running Docker using SSH.
Everything works but I would like to switch Oxidized to Docker.

My docker host now contains my gitlab and oxidized.

The Oxidized web interface is easily accessible and my devices are successfully recovered from LibreNMS, the backup begins.

The problem is that the Gitlab authentication fails yet I generated an ssh key from the root account of my docker host and I integrated it into Gitlab.

I have configured a file for ssh in /root/.ssh/config (my gitlab uses port 2222 for ssh).

When I do ssh -T gitlabq … it works fine but not with Oxidized.

I run my container with :
docker run -v /etc/oxidized:/root/.config/oxidized -v /root/.ssh:/root/.ssh -p 8888:8888/tcp -e UPDATE_CA_CERTIFICATES=true -t oxidized/oxidized:lastest

In the configuration of the tool I have correctly configured the path of the public and private ssh key (see my configuration atteched file), I see many errors in the logs of the container :

Push_to_remote hook (# <GithubRepo: 0x000055f2d5d29f10>) failed (# ) for event: post_store

Here my oxidized configuration file : 
![2020-11-10 18_00_44-PuTTY Connection Manager - Connecté à  root@man-dockerq01__etc_oxidized_output](https://user-images.githubusercontent.com/61157268/98706297-fb115280-237e-11eb-939d-32c89039d4e3.png)

1) My oxidized.git git folder does not create itself
2) I have try with the gitlab on SaaS and I have the same error
3) In the container of test I have install ping and the network container working fine

All is working fine on the Oxidized VM (CentOS 8) 

I'm desperate...
Thank you !

**Comment by Smiley-k** [comment]
Yes Yes Yes 


`When I do ssh -T gitlabq … it works fine but not with Oxidized`

I have the same problem on debian 11 , I too am desperate I have spent all day but it does not work.... i also used the same article https://codingpackets.com/blog/oxidized-gitlab-storage-backend/ but nothing works (((

**Comment by aschaber1** [comment]
I'm using the githubhook just the same. There's nothing in the code hindering you from using any git repo as a target.
