### ISSUE TITLE
failed (#<Rugged::NetworkError: unsupported URL protocol>) for event :post_store

### ISSUE THREAD

**Issue by vishnubraj** [ytti/oxidized#2217]
i using the hooks config to push the configs to gitlab server, i am getting the below error while pushing the config.
i tried uninstalling and installing rugged again, but that didnt help. Please suggest

```
hooks:
  push_to_remote:
    type: githubrepo
    events: [post_store]
    remote_repo: git@git.xxxxx.info:netops/oxidized-sjc2.git
    publickey: /opt/oxidized/.ssh/id_rsa.pub
    privatekey: /opt/oxidized/.ssh/id_rsa
```

```
Nov 19 07:02:47 oxidized2a.sjc2 oxidized[25010]: GithubRepo: Pushing local repository(/opt/oxidized/output/oxidized.git/)...
Nov 19 07:02:47 oxidized2a.sjc2 oxidized[25010]: GithubRepo: to remote: git@git.xxxxx.info:netops/oxidized-sjc2.git
Nov 19 07:02:47 oxidized2a.sjc2 oxidized[25010]: Hook push_to_remote (#<GithubRepo:0x0000000002607848>) failed (#<Rugged::NetworkError: unsupported URL protocol>) for event :post_store
```

**Comment by vishnubraj** [comment]
Can someone help with this?

**Comment by ichilton** [comment]
I just had this issue too.

As per https://github.com/ytti/oxidized/issues/1038, removing the oxidized and rugged gems, installing the  libssh2-1-dev and libgit2-dev packages and then re-installing the gems, fixed it for me.

**Comment by gbeekmans** [comment]
I just ran into this same issue today. @ichilton 's fix did not work for me. I ended up just having to update the remote_repo format from git@host: to **ssh://git@host:path/to/repo.git**

**Comment by Firefishy** [comment]
Just minor correction, format is **ssh://git@host/path/to/repo.git** note the `:` replaced with `/`

**Comment by AAm-kun** [comment]
had the same issue with Debian 12 just now using oxidized 0.30.1

solution given by [eimann](https://github.com/eimann) works

`gem install rugged -- --with-ssh `
