### ISSUE TITLE
problem with githubrepo hook

### ISSUE THREAD

**Issue by santerua** [ytti/oxidized#2219]
configuration like bellow ,
problem is oxidize is looping with information "Authenticating using ssh keys as 'git'"

Ubuntu 18.04.5 LTS
oxidized-0.28.0

log:

```
Nov 19 18:13:28 oxidized oxidized[2269]: GithubRepo: Pushing local repository(/opt/oxidized/output/configs.git/)...
Nov 19 18:13:28 oxidized oxidized[2269]: GithubRepo: to remote: https://******/********/***-company.git
Nov 19 18:13:28 oxidized oxidized[2269]: GithubRepo: Authenticating using ssh keys as 'git'
Nov 19 18:13:28 oxidized oxidized[2269]: Hook push_to_remote (#<GithubRepo:0x000055edeb0f9a18>) failed (#<ArgumentError: Invalid credential type>) for event :post_store

```
check ssh key 
```
ssh -i /opt/oxidized/.ssh/id_rsa git@****.****.dev

Welcome to GitLab, @username!
Connection to ****.****.dev closed.


```
config:
```


output:
  default: git
  git:
    single_repo: true
    user: username
    email: username@***.**.***
    repo: /opt/oxidized/output/configs.git
    publickey: /opt/oxidized/.ssh/id_rsa.pub
    privatekey: /etc/oxidized/.ssh/id_rsa


hooks:
  push_to_remote:
    type: githubrepo
    events: [post_store]
    remote_repo: "git@****.****.dev:office-infrastructure/network-backup.git"
    publickey: /opt/oxidized/.ssh/id_rsa.pub
    privatekey: /opt/oxidized/.ssh/id_rsa


```

**Comment by from88** [comment]
hello, noticed the same problem today.

**Comment by ax-kflores** [comment]
@from88 I'm running into the same issue, you mentioned that you configured certificate info? How did you resolve this?

**Comment by from88** [comment]
> @from88 I'm running into the same issue, you mentioned that you configured certificate info? How did you resolve this?

just changed the public keys. But your problem might be different.

**Comment by ax-kflores** [comment]
I resolved my issue as well, it was a format issue with the SSH key that was generated.

**Comment by from88** [comment]
> I resolved my issue as well, it was a format issue with the SSH key that was generated.

which format type fixed the situation ?

**Comment by tof-fit** [comment]
This is also a current issue for us.... would love to get some details on how others have resolved this. I have tried a few different variations on suggested solutions without any luck. I can SSH to GitHub via CLI successfully though.

**Comment by from88** [comment]
> This is also a current issue for us.... would love to get some details on how others have resolved this. I have tried a few different variations on suggested solutions without any luck. I can SSH to GitHub via CLI successfully though.

Be sure that oxidized user can read permision wise your ssh keys.

**Comment by xanarin** [comment]
I was able to dig a little bit deeper into why Oxidized only supports the "RSA" (legacy) private key format, in case it is helpful/interesting to anyone:
https://github.com/ytti/oxidized/issues/2324#issuecomment-1011509490
