### ISSUE TITLE
One file per command

### ISSUE THREAD

**Issue by mtucker502** [ytti/oxidized#2225]
Is it possible to output one file per command?

For instance if I want to run:
- show version
- show configuration
- show chassis hardware detail

But I want each of these commands to have its own unique file. Can I do this in Oxidized?

**Comment by davama** [comment]
https://github.com/ytti/oxidized/blob/master/docs/Creating-Models.md#advanced-features

**Comment by mtucker502** [comment]
Thank you @davama. Is it also possible to create sub-folders?

- "show configuration" -> ./Config/configs/device_name
- "show configuration | display set" -> ./Config/configs_set/device_name
- "show configuration | display xml" -> ./Config/configs_xml/device_name

I believe something like this _may_ work if `cfg.type` supports slashes.

Example config:
```
output:
    git:
        type_as_directory: true
```

Example model:
```
require 'oxidized/model/junos.rb'


class JunOS

    cmd 'show configuration' do |cfg|
        cfg.type = "Config/configs"
        cfg.name = "configs"
        cfg
    end

    cmd 'show configuration | display set' do |cfg|
        cfg.type = "Config/configs_set"
        cfg.name = "configs_set"
        cfg
    end

    cmd 'show configuration | display xml' do |cfg|
        cfg.type = "Config/configs_xml"
        cfg.name = "configs_xml"
        cfg
    end


end
```

**Comment by davama** [comment]
```
cfg.type = "name"
```
is already a folder but another folder `name/subname` I have personally never tried and dont know if it works.

Did you try? What happened?

If you dont want to ruin your git, I would create a temp/test git repo to play around before you know what you "can" and "want" to do

**Comment by mtucker502** [comment]
Wanted to circle back to this issue since I finally have had time to test. This works as expected so long as you have multiple.

It seems though that `cfg.name` is appended rather than being used as a directory name (example: `GROUP/config/configs_set/FQDN--configs_set`.

If I omit `cfg.name` then the filename is `FQDN--command`. If I use an empty string it ends up as `FQDN--`. My goal is to have it simply as `FQDN`. I'll investigate the models more to learn how Oxidized does this.
