### ISSUE TITLE
Looking to pull additional information in a separate file

### ISSUE THREAD

**Issue by etern4ever** [ytti/oxidized#223]
I am trying to pull additional information while logged into the device and save it in another file outside of the git repo.  I don't care about diffs, etc.

So I want to keep the existing functionality of the model but include a few more commands and the output is saved to another location in separate files per command.

I don't see a clear way of doing this.    It looks like using state changes the functionality of the model.

**Comment by etern4ever** [comment]
I think I have it..  seems like a little hack and not a great solution

  cmd '<command>' do |state|
    File.open('<file>', 'w') { |file| file.write(state) }
  end

It also seems I have to edit the model in the lib directory.  I copied the model to /etc/oxidized/model and that didn't work.  I also tried  /etc/oxidized/.model.

Is there a better way to overwrite the models without editing the lib model files?

**Comment by ytti** [comment]
This is not really possible now. If you are using git repo, we only support writing it to separate git repo or separate git file.

cmd 'blaah' do |foox|
  foox.type = 'plimplom'
  foox
end

would store it either in pimpom repo or hostname_pimpom.txt, depending on config.

**Comment by etern4ever** [comment]
Thanks ytti.

I think my hack will work for me.   What is the proper way to override the model without editing the model files in the lib directory?

**Comment by ytti** [comment]
You can copy it in ~/.config/oxidized/model/ directory, then system wide model isn't used

**Comment by etern4ever** [comment]
Thanks
