### ISSUE TITLE
Oxidized encrypt password in configuration file when source device is LibreNMS

### ISSUE THREAD

**Issue by sgelineau17** [ytti/oxidized#2231]
Hello, 

I use Oxidized and Librenms, they are connected together. My oxidized device source is LibreNMS. 
In my Oxidized config file I use the groups and models category for specify login and password. 
The accounts are only in read-only access but my company does not allow clear passwords.
I have seen methods with csv files but my source is librenms how to best secure the config file? (Encrypt Password)

Thanks

**Comment by seros1521** [comment]
https://github.com/ytti/oxidized/blob/master/docs/Configuration.md#removing-secrets
It works the same no matter which oxidized source you use.
