### ISSUE TITLE
Cisco IOS login failure with @ in username due to TACAS

### ISSUE THREAD

**Issue by jbasford-licensys** [ytti/oxidized#2235]
Hi,

Trying to backup configs on Cisco IOS routers managed by our ISP.  They have generated user/pass combos in their TACAS system, however the username has an @ symbol in it.  I can't seem to get oxidized to handle the @ correctly and need some help/guidance please.

Relevant Oxidized config:

> username: username
> password: password
> model: routeros
> crash:
>   directory: /home/oxidized/.config/oxidized/crashes
>   hostnames: false
> debug: true
> interval: 3600
> retries: 3
> threads: 30
> timeout: 20
> use_syslog: true
> pid: /home/oxidized/.config/oxidized/pid
> #log: /home/oxidized/.config/oxidized/log
> log: /home/oxidized/.config/oxidized/logs/oxidized.log
> prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
> resolve_dns: true
> rest: "0.0.0.0:8888"
> next_adds_job: false
> stats:
>   history_size: 100
> 
> #source file and structure
> source:
>   csv:
>     delimiter: !ruby/regexp /:/
>     file: /home/oxidized/.config/oxidized/router.db
>     gpg: false
>     map:
>       name: 0
>       model: 1
>       username: 2
>       password: 3
>     vars_map:
>       enable: 4
> 

Here's the routers.db file 
> 
> #name:model:user:password:enablepassword
> #Adelaide
> adlswi01pp.xxxxxxxx.com:ciscosmb:oxidized:SECURE_PASSWORD:ENABLE_PASSWORD
> adlrtr11pp.xxxxxxxx.com:ios:oxidised.access@CLIENT_ID:ANOTHER_SECURE_PASSWORD:
> 

And then here's what the log file says when it tries to connect to the service.

> Dec 21 09:42:28 bnemgt13vp oxidized[1525884]: resolving DNS for adlrtr11pp.xxxxxxxx.com...
> Dec 21 09:42:35 bnemgt13vp oxidized[1525884]: lib/oxidized/worker.rb: Added /adlrtr11pp.xxxxxxxx.com to the job queue
> Dec 21 09:42:35 bnemgt13vp oxidized[1525884]: lib/oxidized/job.rb: Starting fetching process for adlrtr11pp.xxxxxxxx.com at 2020-12-20 23:42:35 UTC
> Dec 21 09:42:35 bnemgt13vp oxidized[1525884]: lib/oxidized/input/ssh.rb: Connecting to adlrtr11pp.xxxxxxxx.com
> Dec 21 09:42:38 bnemgt13vp oxidized[1525884]: lib/oxidized/input/ssh.rb: expecting [/^([\w.@()-]+[#>]\s?)$/, /^Username:/i, /^Password:/i] at adlrtr11pp.xxxxxxxx.com
> Dec 21 09:42:39 bnemgt13vp oxidized[1525884]: lib/oxidized/input/cli.rb: Running post_login commands at adlrtr11pp.xxxxxxxx.com
> Dec 21 09:42:39 bnemgt13vp oxidized[1525884]: lib/oxidized/input/cli.rb: Running post_login command: nil, block: #<Proc:0x00007fc654405138 /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/model/ios.rb:127> at adlrtr11pp.xxxxxxxx.com
> Dec 21 09:42:39 bnemgt13vp oxidized[1525884]: lib/oxidized/input/ssh.rb enable @ adlrtr11pp.xxxxxxxx.com with expect: /^[pP]assword:/
> Dec 21 09:42:39 bnemgt13vp oxidized[1525884]: lib/oxidized/input/ssh.rb: expecting [/^[pP]assword:/] at adlrtr11pp.xxxxxxxx.com
> Dec 21 09:42:59 bnemgt13vp oxidized[1525884]: lib/oxidized/node.rb: Oxidized::SSH failed for adlrtr11pp.xxxxxxxx.com
> Dec 21 09:42:59 bnemgt13vp oxidized[1525884]: lib/oxidized/job.rb: Config fetched for adlrtr11pp.xxxxxxxx.com at 2020-12-20 23:42:59 UTC
> Dec 21 09:42:59 bnemgt13vp oxidized[1525884]: /adlrtr11pp.xxxxxxxx.com status no_connection, retry attempt 1

On the Ubuntu host that Oxidized is running on if I ssh to the router in question I am able to connect with the full username, including the @ symbol:
> ssh -oKexAlgorithms=+diffie-hellman-group1-sha1 -o PreferredAuthentications=keyboard-interactive -o PubkeyAuthentication=no  oxidised.access@CLIENT_ID@adlrtr11pp
> Password:
> PIP-LOCATION_ID-LOCATION-P247544P#
> 

If I try again with only the first part of the username it comes back with request denied:

> ssh -oKexAlgorithms=+diffie-hellman-group1-sha1 -o PreferredAuthentications=keyboard-interactive -o PubkeyAuthentication=no  oxidised.access@adlrtr11pp
> Password:
> Request Denied

How do I go about getting Oxidized to ignore the parse the @ symbol in the username as just part of the username and ignore it as a special/escape character?

Thanks,

Jay

**Comment by seros1521** [comment]
You can see the entry in your log:
```
Dec 21 09:42:39 bnemgt13vp oxidized[1525884]: lib/oxidized/input/cli.rb: Running post_login commands at adlrtr11pp.xxxxxxxx.com
```
`post_login` is executed after oxidized has logged into the device, it looks like the user with `@` is being processed correctly. Further in the log you can see the entry
```
Dec 21 09:42:39 bnemgt13vp oxidized[1525884]: lib/oxidized/input/ssh.rb enable @ adlrtr11pp.xxxxxxxx.com with expect: /^[pP]assword:/
Dec 21 09:42:39 bnemgt13vp oxidized[1525884]: lib/oxidized/input/ssh.rb: expecting [/^[pP]assword:/] at adlrtr11pp.xxxxxxxx.com
```
this means that oxidized has executed the `enable` command and is waiting for an invitation to enter the enable password from the device, but does not wait for it and is disconnected by timeout. Also in your example
```
ssh -oKexAlgorithms=+diffie-hellman-group1-sha1 -o PreferredAuthentications=keyboard-interactive -o PubkeyAuthentication=no oxidised.access@CLIENT_ID@adlrtr11pp
Password:
PIP-LOCATION_ID-LOCATION-P247544P#
```
you go to the device and judging by the `#` sign in the cli prompt, this account has privilege level 15 right away, without a separate `enable` input. Thus, you need to remove the enable password from the configuration, leave it empty so that oxidized does not try to enter the `enable` command and does not wait for the device to ask for it.

**Comment by jbasford-licensys** [comment]
Thanks seros1521 - much appreciated for your help.  I took the : out of the routers.db file and restarted Oxidized.  It's then connected to the router and pulled down the config properly.  Seems that leaving it blank after the colon still made oxidized think there was an enable password. 

Anyway it has worked - so thank you very much for your help and knowledge.
