### ISSUE TITLE
Prompt not matching Aruba virtual mobility controller

### ISSUE THREAD

**Issue by glenhodgins** [ytti/oxidized#2237]
I have an Aruba virtual controller 
Aruba Operating System Software.
ArubaOS (MODEL: ArubaMC-VA-US), Version 8.3.0.0

The logs show the prompt is not being matched.  The Aruba virtual controller adds "[mynode]" to the prompt. How can I change the regexp to match [mynode] in the prompt?

Last login: Tue Dec 22 09:34:31 2020 from 10.1.1.250
(WPP-ArubaVMC) [mynode] #

**Comment by graceless70** [comment]
[aosw8.rb.txt](https://github.com/ytti/oxidized/files/5732628/aosw8.rb.txt)

You could try this model I created earlier this year.

It does do a dump of the local-userdb which you may not want and so just remark that section out.

Good luck and merry xmas

**Comment by glenhodgins** [comment]
Thank You @graceless70. On first pass with your model I got the same error:
```
Dec 23 10:12:06 librenms oxidized[13358]: (WPP-ArubaVMC) [mynode] # not matching configured prompt (?-mix:^([\w\(:.@-]+(\)?\s?)\*\[+[\w\(:.@-]+\]\s[#>]\s?)$)"
```
With your prompt setting as a template, I set the prompt to match mine and it's working now THANKS!. 
my prompt is set to:   [\w\(:.@-]+(\)?\s?)\[+[\w]+\]\s[#>]
