### ISSUE TITLE
NGINX Display Error while choosing version on Oxidized

### ISSUE THREAD

**Issue by PutuGandi** [ytti/oxidized#2238]
**hai friend, i have problem with the oxidized. when i click version of config then i got error in my nginx .** 

![version](https://user-images.githubusercontent.com/48087652/103047490-acceb080-45c6-11eb-8630-520f237522a7.png)

**this the error:**
![NGINX-ERROR-OXI](https://user-images.githubusercontent.com/48087652/103047622-118a0b00-45c7-11eb-960f-5b366c2d9ba3.png)

did anyone get the same problem?

Thank You.

**Comment by davama** [comment]
dont see that.

posting config and nginx (if using) config might help
how logs look?

**Comment by PutuGandi** [comment]
hai @davama , thanks for your respon, these the logs look like:
` 2020/12/29 23:08:44 [error] 8590#0: *2489 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.16.38.112, server: _, request: "GET /node/version?node_full=ACS-Line-Maintenance HTTP/1.1", upstream: "http://127.0.0.1:8888/node/version?node_full=ACS-Line-Maintenance", host: "172.16.20.87", referrer: "http://172.16.20.87/nodes" `

# config:
#For more information on configuration, see:
#* Official English Documentation: http://nginx.org/en/docs/
#* Official Russian Documentation: http://nginx.org/ru/docs/

user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log;
pid /run/nginx.pid;

#Load dynamic modules. See /usr/share/nginx/README.dynamic.
include /usr/share/nginx/modules/*.conf;

events {
    worker_connections 1024;
}

http {
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                                  '$status $body_bytes_sent "$http_referer" '
                                  '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile            on;
    tcp_nopush          on;
    tcp_nodelay         on;
    keepalive_timeout   65;
    types_hash_max_size 2048;

    include             /etc/nginx/mime.types;
    default_type        application/octet-stream;

    #Load modular configuration files from the /etc/nginx/conf.d directory.
    #See http://nginx.org/en/docs/ngx_core_module.html#include
    #for more information.
    include /etc/nginx/conf.d/*.conf;

    server {
        listen       80 default_server;
        listen       [::]:80 default_server;
        server_name  _;
        root         /usr/share/nginx/html;
        auth_basic "Restricted Access";
        auth_basic_user_file /etc/nginx/.htpasswd;

        # Load configuration files for the default server block.
        include /etc/nginx/default.d/*.conf;

        location / {
          proxy_pass http://127.0.0.1:8888/;
        }

        error_page 404 /404.html;
            location = /40x.html {
        }

        error_page 500 502 503 504 /50x.html;
            location = /50x.html {
        }
    }
}
