### ISSUE TITLE
SSH Version 1

### ISSUE THREAD

**Issue by etern4ever** [ytti/oxidized#224]
We have an older device that is running SSH version 1.   In rancid, we could just add a sshcmd option to .cloginrc to resolve this issue.

add sshcmd device {ssh\ -1}

Is there an option for this in Oxidized?  It doesn't appear the SSH module that Oxidized uses falls back to this.

Thanks

**Comment by etern4ever** [comment]
Interesting..  after several attempts, it appears to have pulled the config without issue.   Nevermind.

**Comment by ytti** [comment]
Strange indeed. I don't think protocol v1 is supported by the library at all which we use. 

Maybe it fell back to telnet?
