### ISSUE TITLE
How to modify the default UTC time zone?

### ISSUE THREAD

**Issue by gavin2love** [ytti/oxidized#2241]
I started oxidized with docker and checked the configuration file. It seems that there is no corresponding attribute parameter to modify.

**Comment by MrMarioMichel** [comment]
Also environment setting does not do anything sadly :(

**Comment by CCAV668** [comment]
The same thing happened  :(

**Comment by salvapinyol** [comment]
I also want to know how to change time zone...

**Comment by DRIgnazGortngschirl** [comment]
It is not solved !

**Comment by Dogy007** [comment]
I also would like a variable to set the TimeZone.

**Comment by XDriver76** [comment]
Change Time.now.utc on Time.now and restart oxidized

/var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/job.rb
/var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/node/stats.rb
