### ISSUE TITLE
How to install on offline server

### ISSUE THREAD

**Issue by laissana** [ytti/oxidized#2243]
Hello,
I want to install oxidized on a Centos 8 server that has no access to the internet. How can I do ?
I tried to download each dependencies on the website https://rubygems.org/gems/ but it is a never ending job. 

Has someone already install oxidized on an offline server ?

Thanks in advance.

**Comment by seros1521** [comment]
You can install oxidized on a server that has access to the outside, and then copy the entire `.gem` directory from the user's home directory. This is how I make backups of old versions of oxidized and its dependencies before upgrading.
