### ISSUE TITLE
debug issue with custom ports

### ISSUE THREAD

**Issue by jthunt** [ytti/oxidized#225]
if you have multiple devices on a single IP address (but different ports due to port forwarding), the debug log gets overwritten because its based on IP address only. It doesn't include port.  

DNS names in the input file are different.   So that would work if used for debug as well.

**Comment by ytti** [comment]
In released version, we only have flat debug log :/. But I hear the problem, I guess we need to add port to the filename, if it's non-standard port.

**Comment by laf** [comment]
@ytti proposing to close in favour of #511 which has a little more discussion around it.
