### ISSUE TITLE
Mail notification 

### ISSUE THREAD

**Issue by LucasHrmn** [ytti/oxidized#2251]
Hey i'm using docker compose for oxidized.
And i want to have notifications whenever oxidized fail at contacting one device or whenever any devices fail at updating.

I used the oxidized-report-git-commit script

I intentionally disabled ssh on a switch to get an error to check if the mail is going to be working but this is a different story.

Whenever i up my docker it indeed try to contact the "disabled" switch but after the 3 tries i get this : 

```
oxidized_1  | W, [2021-01-19T13:27:18.918671 #31]  WARN -- : switch/BD-04 status no_connection, retry attempt 3
oxidized_1  | W, [2021-01-19T13:27:19.850933 #31]  WARN -- : 172.30.7.231 raised Net::SSH::AuthenticationFailed with msg "Authentication failed for user username@172.x.x.x"
oxidized_1  | W, [2021-01-19T13:27:19.919669 #31]  WARN -- : switch/BD-04 status no_connection, retries exhausted, giving up
oxidized_1  | sh: 1: /home/localadm/oxidized-report-git-commits: not found
oxidized_1  | E, [2021-01-19T13:27:19.927703 #31] ERROR -- : Exec: "/home/localadm/oxidized-report-git-commits -s \"Oxidized updates for ${OX_NODE_NAME}\" test@mail.com" failed with exit value 127

```
i gave execution perms to the file just to be sure but nothing change and even if i put the script into the /etc/oxi (where all the config, router.db...) it still says it's missing 

the hooks in the config file is untouched from the script except for the path.

eveything is in an external directory and not in the container itself

**Comment by Orcenel** [comment]
note that if i specify to run as shell

` cmd: 'sh /etc/oxidized/oxidized-report-git-commits `

with execution rights i get the following error : 

`sh: 0: Can't open /etc/oxidized/oxidized-report-git-commits`

**Comment by paulinster** [comment]
I am getting the same issue ..  Can' t get the notification when  fail

**Comment by aanyoti** [comment]
> 

Hi,

Please advise how you installed mail as per your statement below:

_"Alright so it appears that mail wasn't working correctly so after reinstalling mail i have a different error"_
