### ISSUE TITLE
which model for IBM/Lenovo switch

### ISSUE THREAD

**Issue by Zyzto** [ytti/oxidized#2254]
We are using rancid is and it's becoming trouble with some new hardware but we still have old hardware

so I found Oxidized and I am trying in it right now, first documentation of old release is much better than current ones thank you rubydocs for link in google. and it's not clear how to setup everything at first but I done initial setup.
and now I am trying to backup IBM RackSwitchs but I can't find anything relate to ibm any where other than ibm blade PR.

so is there even model for IBM RackSwitchs?

**Comment by mortzu** [comment]
There are currently to open PRs:
- https://github.com/ytti/oxidized/pull/2332
- https://github.com/ytti/oxidized/pull/974
