### ISSUE TITLE
JL254A not fully logged out

### ISSUE THREAD

**Issue by DRIgnazGortngschirl** [ytti/oxidized#2255]
I do have some JL254A where sadly the session times out after not fully logging out since a 2nd "exit" and a confirmation with "y" is required.

### Expectation:
```
SW-01# exit
SW-01> exit
Do you want to log out (y/n)? y
```

### Reality:
```
SW-01# exit
SW-01>
```

In [aoscx.rb](https://github.com/ytti/oxidized/blob/master/lib/oxidized/model/aoscx.rb) I edited it like this and made a new model. I guess that can be squished inside this module with some if else statements.

```
cfg :telnet, :ssh do
    # preferred way to handle additional passwords
    if vars :enable
      post_login do
        send "enable\n"
        cmd vars(:enable)
      end
    end
    post_login 'no page'
    pre_logout "exit"
    pre_logout "exit"
    pre_logout "y"
  end
```

**Comment by morrisb74** [comment]
If you use `logout` you don't have to do `exit` twice

**Comment by MrMarioMichel** [comment]
Hi @morrisb74 

Seems like "logout" will be able to replace these two "exit" commands but still event tho I set some sleep time one switch won't recognize the "y" to confirm lougout.

Not working Switch
```
SW-01# logout
Do you want to log out (y/n)? 
```

```
  cfg :telnet, :ssh do
    # preferred way to handle additional passwords
    if vars :enable
      post_login do
        send "enable\n"
        cmd vars(:enable)
      end
    end
    post_login 'no page'
    pre_logout "logout"
    sleep 2
    pre_logout "y"
  end
```
also using ' insead of " is not helping. Thought about newlines or formating... but no
```
    pre_logout 'logout'
    sleep 2
    pre_logout 'y'
```
