### ISSUE TITLE
no implicit conversion of nil into String

### ISSUE THREAD

**Issue by curious-kr** [ytti/oxidized#2257]
anyone know why the search config box returns error?
this is running from the docker image

TypeError at /nodes/conf_search
no implicit conversion of nil into String
file: file.rb location: read line: 39

![image](https://user-images.githubusercontent.com/7647496/106924398-073a5100-66dd-11eb-968f-1a2bc0f9f102.png)

**Comment by mortzu** [comment]
Please make an issue in https://github.com/ytti/oxidized-web
