### ISSUE TITLE
comand in bash history

### ISSUE THREAD

**Issue by amastran** [ytti/oxidized#2259]
Hi, I use oxidized to export the configuration of linux machines. Is there a way to prevent oxidized commands from being saved in bash history?
i tried to use something like "cfg + = cmd 'export HISTFILE = / dev / null'", but it doesn't work.

Thanks for the attention #

**Comment by davama** [comment]
You know ive noticed that as well and wanted to tackle this.

glad you started the thread 😆

mind sharing your cmd block?
What model are you using?

**Comment by davama** [comment]
doing a quick google search maybe an idea.

add to `bashrc` file

```
if [ "$TERM" = "vt100" ]; then # if net-ssh from ruby; because of oxidized
     set +o history
fi
```

We have this to make sure our PS1 prompt does not get adjusted.

```
if [ "$TERM" = "vt100" ]; then # if net-ssh from ruby; because of oxidized; dont set the PS1
	:
else
	# taken from /etc/bashrc but included bell '\a'; the '\[\]' tell the shell not to print them
	PS1="\[\a\][\u@\h \W]\\$ "
fi
```
