### ISSUE TITLE
Maximum command output size

### ISSUE THREAD

**Issue by pmuch78** [ytti/oxidized#2261]
Hello.
I'm using oxidized for my network devices - it works great. Now I would like to save output of 'dpkg -l | grep ii'.

I managed to get everything in log, but I get about 550 lines in output file (on this server it should be about 800 lines) - every run different size of output.
I don't know how to debug it?

**Comment by davama** [comment]
My guess is that oxidized thinks it hits the `prompt` again.

Debug option here: https://github.com/ytti/oxidized/blob/master/docs/Configuration.md

**Comment by pmuch78** [comment]
I don't think it's a problem.
Even if I run oxidized -d manually, I can't find anything useful in output, and the result is different on every pass (file in logs directory is always the same) - sometimes its 530 lines, sometimes 580, sometimes 640
I managed to make it work by changing cmd to:

  cmd 'dpkg -l | grep ii | cut -c 5- > /tmp/packages'
  cmd 'cat /tmp/packages'
  cmd 'sleep 15'

With 5 sec sleep it takes more, but not the whole output, the same without using tmp file

**Comment by pmuch78** [comment]
The stangest thing for me is that there is full output in logs, but for the reason I don't understand, it's not transferred to output (file or git). Sometimes it's cut at the newline, and sometimes in the middle of the line.

**Comment by davama** [comment]
can you provide logs?

**Comment by pmuch78** [comment]
Attached .rb model file (with 2 versions - one working, with cat & sleep, and normal - not working), and result of 2 passes executed sequentially - stderr odf oxidized -d, file from logs dir and output file.
[model.zip](https://github.com/ytti/oxidized/files/5989214/model.zip)
[pass2.zip](https://github.com/ytti/oxidized/files/5989215/pass2.zip)
[pass1.zip](https://github.com/ytti/oxidized/files/5989217/pass1.zip)
