### ISSUE TITLE
config validation (regex? templates?)

### ISSUE THREAD

**Issue by FlorianHeigl** [ytti/oxidized#2263]
I was just doing my first tests, with a single juniper switch.
No backup user created yet, so it's still using `root` and as such, ending up in a system shell until one types `cli`. I was kind of expecting this backup to not work due to that.

In fact, oxidized told me it updated the configuration:

```
oxidized_1  | I, [2021-02-16T18:55:17.435867 #26]  INFO -- : Configuration updated for /192.168.35.23
```

When checking that a bit later, I found this:

```
$ less 192.168.35.23
# show: Command not found.
# show: Command not found.
# show: Command not found.
# show: Command not found.
show: Command not found.
display: Command not found.
```

* Is there a way to define kind of a minimum standard for what should pass as an Configuration?
* Is there a way to define a list of typical error messages (per OS or global)?

I have checked the prior open/closed issues but found nothing.
For rancid, i had modified an existing nagios check to be more critical about the file sizes, but that also doesn't feel very '2020 chic'.

**Comment by brobare** [comment]
Try using a non-root user account? Seems that the root user on your juniper box is not putting you into "CLI" mode, so all of the show commands its running to collect output are being ran against the linux/freebsd shell, not the junos shell.

Also, its generally not a good security posture to login to devices directly via root.

**Comment by FlorianHeigl** [comment]
None of that relates to the current state of no error handling and no validation.
The exact thing the test was supposed to find (or, rather, it would have been to not find it)
