### ISSUE TITLE
Switchs backup Output configuration file format - DeviceName/IP-YYYY:DD:MM:HH:SS

### ISSUE THREAD

**Issue by ck-7** [ytti/oxidized#2265]
Am looking for backup configuration file format. We have more than 1000 SG300 and Aruba switches we would to take backup of every day/ week/monthly with rotationally. 
Current oxidixied not help us to save the config file in following format DeviceName or IP-YYYY:DD:MM:HH:SS. 
            EX : cisco1-2021-20-02-11-32  

confg show switch name alone. how to reproduce these with date and time format ( What even format DD:MM:YYY:HH:SS or YYYY:DD:MM:HH:SS ) 

@Mattz0r and @ytti  Please help me out of it . I seen the following thread not able to understand the thread **#1349** 

Here my config file  and router.db

**#config**
=========

---
username: cisco
password: T?EST$#2121:))??>
model: ciscosmb
interval: 7200
use_syslog: true
log: /root/.config/oxidized/logs
debug: true
threads: 30
timeout: 20
history_size: 10
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: ciscobkp:8888
next_adds_job: false
pid: "/root/.config/oxidized/pid"

input:
  default: ssh
  debug: true
  ssh:
    secure: false

output:
  file:
    directory: /root/.config/oxidized/output/configs

source:
  default: csv
  csv:
    file: /root/.config/oxidized/router.db
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      ip: 1
      model: 2
      group: 3
    vars_map: {}

model_map:
  ciscosb: ciscosmb
vars: {}

groups:
  cisco:
    username: cisco
    password: T?EST$#2121:))??>
models: {}

router.db
=======
**# name:ip:model:group
Test1:10.11.10.18:ciscosmb:cisco**

**Comment by chalarm** [comment]
output:
  file:
    name: %node-%y-%m-%d-%h:%m:%s
Is what's missing in your configuration as one can read in what ytti build.


https://github.com/ytti/oxidized/commit/3c2e58adbde2cf214584c938691074be949cc3c1

read and implement by yourself this is a non issue.

**Comment by ck-7** [comment]
[root@elogging oxidized]# systemctl status oxidized -l
● oxidized.service - Oxidized - Network Device Configuration Backup Tool
   Loaded: loaded (/usr/lib/systemd/system/oxidized.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Mon 2021-07-05 17:40:05 IST; 3min 45s ago
  Process: 19411 ExecStart=/usr/local/rvm/gems/ruby-2.5.1/wrappers/oxidized (code=exited, status=1/FAILURE)
 Main PID: 19411 (code=exited, status=1/FAILURE)

Jul 05 17:40:05 elk1-logging.solartis.net oxidized[19411]: from /usr/local/rvm/gems/ruby-2.5.1/gems/oxidized-0.28.0/lib/oxidized/core.rb:4:in `new'
Jul 05 17:40:05 elk1-logging.solartis.net oxidized[19411]: from /usr/local/rvm/gems/ruby-2.5.1/gems/oxidized-0.28.0/lib/oxidized/cli.rb:13:in `run'
Jul 05 17:40:05 elk1-logging.solartis.net oxidized[19411]: from /usr/local/rvm/gems/ruby-2.5.1/gems/oxidized-0.28.0/bin/oxidized:8:in `<top (required)>'
Jul 05 17:40:05 elk1-logging.solartis.net oxidized[19411]: from /usr/local/rvm/gems/ruby-2.5.1/bin/oxidized:23:in `load'
Jul 05 17:40:05 elk1-logging.solartis.net oxidized[19411]: from /usr/local/rvm/gems/ruby-2.5.1/bin/oxidized:23:in `<main>'
Jul 05 17:40:05 elk1-logging.solartis.net oxidized[19411]: from /usr/local/rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `eval'
Jul 05 17:40:05 elk1-logging.solartis.net oxidized[19411]: from /usr/local/rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `<main>'
Jul 05 17:40:05 elk1-logging.solartis.net systemd[1]: oxidized.service: main process exited, code=exited, status=1/FAILURE
Jul 05 17:40:05 elk1-logging.solartis.net systemd[1]: Unit oxidized.service entered failed state.
Jul 05 17:40:05 elk1-logging.solartis.net systemd[1]: oxidized.service failed.



Service getting failed after configuration  Output file like below 

     1  ---
     2  username: cisco
     3  password: TESTERQ@!@!@!
     4  model: ciscosmb
     5  interval: 7200
     6  use_syslog: true
     7  log: /root/.config/oxidized/logs
     8  debug: true
     9  threads: 30
    10  timeout: 20
    11  history_size: 10
    12  retries: 3
    13  prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
    14  rest: 10.10.10.10:8888
    15  next_adds_job: false
    16  pid: "/root/.config/oxidized/pid"
    17
    18  input:
    19    default: ssh
    20    debug: true
    21    ssh:
    22      secure: false
    23
    24  output:
    25    file:
    26      name: %node-%y-%m-%d-%h:%m:%s 
    27       directory: /root/.config/oxidized/output/cisco/
    28
    29  source:
    30    default: csv
    31    csv:
    32      file: /root/.config/oxidized/router.db
    33      delimiter: !ruby/regexp /:/
    34      map:
    35        name: 0
    36        ip: 1
    37        model: 2
    38        group: 3
    39      vars_map: {}
    40
    41  model_map:
    42    ciscosb: ciscosmb
    43  vars: {}
    44
    45  groups:
    46    cisco:
    47      username: cisco
    48      password: TESTERQ@!@!@!
    49
    50  models: {}

**Comment by mortzu** [comment]
Can you please reformat your paste to make it readable? (https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code)
