### ISSUE TITLE
Oxidized ModelNotFound for supported Aruba CX

### ISSUE THREAD

**Issue by rafasamp** [ytti/oxidized#2269]
When attempting to add two Aruba CX switches to Oxidized I receive the following error stating the model is not found:

`Feb 23 22:20:54 it04 oxidized[35577]: node {:name=>"ARUBACX", :ip=>"192.168.1.100", :model=>"aoscx", :group=>"arubaos"} raised Oxidized::ModelNotFound with message 'aoscx not found for node 192.168.1.100`

I am running Ubuntu 20.04 setup using the docs in GitHub.

**Comment by davama** [comment]
Did you search old issues where others got`ModelNotFound` and see if any of that help?

if so, what? Details?

**Comment by rafasamp** [comment]
After quite a bit of troubleshooting, and to help someone who may come along in the future, the home directory environment variable was not set correctly (following multiple separate online guides). After remedying that it began to work.

**Comment by hofikhof** [comment]
Aruba switch 6100, Aruba OS 10 - error undefined method:

D, [2022-02-17T07:01:44.954064 #16292] DEBUG -- : lib/oxidized/input/ssh.rb true @ switch-6100 with expect: /(^\r|\e\[24;[0-9][hH])?([\w\s.-]+[#>] )($|(\e\[24;[0-9][0-9]?[hH]){3})/
E, [2022-02-17T07:01:44.954758 #16292] ERROR -- : 10.1.200.10 raised NoMethodError with msg "undefined method `+' for true:TrueClass", switch-6100 saved
D, [2022-02-17T07:01:44.954887 #16292] DEBUG -- : lib/oxidized/node.rb: Oxidized::SSH failed for switch-6100
D, [2022-02-17T07:01:44.955855 #16292] DEBUG -- : 10.1.200.10 raised Errno::ECONNREFUSED with msg "Connection refused - connect(2) for "10.1.200.10" port 23"
D, [2022-02-17T07:01:44.956047 #16292] DEBUG -- : lib/oxidized/node.rb: Oxidized::Telnet failed for switch-6100
D, [2022-02-17T07:01:44.956179 #16292] DEBUG -- : lib/oxidized/job.rb: Config fetched for switch-6100 at 2022-02-17 06:01:44 UTC
W, [2022-02-17T07:01:45.773801 #16292]  WARN -- : /switch-6100 status no_connection, retry attempt 1
D, [2022-02-17T07:01:45.773936 #16292] DEBUG -- : lib/oxidized/worker.rb: Added /switch-6100 to the job queue
D, [2022-02-17T07:01:45.877274 #16292] DEBUG -- : lib/oxidized/job.rb: Starting fetching process for switch-6100 at 2022-02-17 06:01:45 UTC
D, [2022-02-17T07:01:45.877410 #16292] DEBUG -- : lib/oxidized/input/ssh.rb: Connecting to switch-6100
D, [2022-02-17T07:01:45.877462 #16292] DEBUG -- : AUTH METHODS::["none", "publickey", "password"]
D, [2022-02-17T07:01:50.180830 #16292] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/(^\r|\e\[24;[0-9][hH])?([\w\s.-]+[#>] )($|(\e\[24;[0-9][0-9]?[hH]){3})/] at switch-6100
D, [2022-02-17T07:01:58.089612 #16292] DEBUG -- : lib/oxidized/input/cli.rb: Running post_login commands at switch-6100
D, [2022-02-17T07:01:58.089694 #16292] DEBUG -- : lib/oxidized/input/cli.rb: Running post_login command: nil, block: #<Proc:0x0000555bb804bb18 /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/model/aoscx2.rb:82> at switch-6100
D, [2022-02-17T07:01:58.089720 #16292] DEBUG -- : lib/oxidized/input/ssh.rb true @ switch-6100 with expect: /(^\r|\e\[24;[0-9][hH])?([\w\s.-]+[#>] )($|(\e\[24;[0-9][0-9]?[hH]){3})/
E, [2022-02-17T07:01:58.090282 #16292] ERROR -- : 10.1.200.10 raised NoMethodError with msg "undefined method `+' for true:TrueClass", switch-6100 saved
D, [2022-02-17T07:01:58.090314 #16292] DEBUG -- : lib/oxidized/node.rb: Oxidized::SSH failed for switch-6100
