### ISSUE TITLE
Create a new Model for Technicolor : ColorOS

### ISSUE THREAD

**Issue by NathanPoret** [ytti/oxidized#2272]
Hello !

I'm currently creating a new model for Oxidized which have for objective to provide technicolor's router configuration. However, i've some **problem from send a command and so retreive the output** of this one. Here the model:
```Ruby
# /home/oxidized/.config/oxidized/model/coloros.rb
class ColorOS < Oxidized::Model
    prompt /\{\w*\}=>/
    comment '# '

    cmd :all do |cfg|
        cfg.cut_both
    end

    cmd 'config dump' do |cfg|
        comment cfg
    end

    cfg :telnet do
        username /^Username : /
        password /^Password : /
    end

    cfg :telnet, :ssh do
        pre_logout 'exit'
    end
end
```
The regex works fine: 

![image](https://user-images.githubusercontent.com/44426867/109794831-8eb0ac80-7c16-11eb-84b0-ab6cc1638644.png)

The connexion telnet works fine:

![image](https://user-images.githubusercontent.com/44426867/109794945-b0119880-7c16-11eb-888d-07f6c4f6844d.png)
*The image has been deliberately cut off*

But Oxidized can't retreive the configuration:

![image](https://user-images.githubusercontent.com/44426867/109795461-3ded8380-7c17-11eb-8c3b-a8d1be8c6098.png)

And i think that because Oxidized don't send the command i wanted (_I can see it because of this in my telnet log_):
```
Username : secret
Password : **********
------------------------------------------------------------------------

                             ______  Technicolor TG582n
                         ___/_____/\
                        /         /\\  10.2.5.6
                  _____/__       /  \\
                _/       /\_____/___ \  Copyright (c) 1999-2013, Technicolor
               //       /  \       /\ \
       _______//_______/    \     / _\/______
      /      / \       \    /    / /        /\
   __/      /   \       \  /    / /        / _\__
  / /      /     \_______\/    / /        / /   /\
 /_/______/___________________/ /________/ /___/  \
 \ \      \    ___________    \ \        \ \   \  /
  \_\      \  /          /\    \ \        \ \___\/
     \      \/          /  \    \ \        \  /
      \_____/          /    \    \ \________\/
           /__________/      \    \  /
           \   _____  \      /_____\/
            \ /    /\  \    /___\/
             /____/  \  \  /
             \    \  /___\/
              \____\/

------------------------------------------------------------------------
{secret}=>
```
But the logs indicate the opposite :

![image](https://user-images.githubusercontent.com/44426867/109797019-2d3e0d00-7c19-11eb-9c35-f31e4e3649b5.png)
![image](https://user-images.githubusercontent.com/44426867/109797483-d5ec6c80-7c19-11eb-8a03-0035a083ce53.png)
*I added additional information to display in the logs in the telnet.rb file to get the same format as in the ssh.rb file.*

Can you help me please?

**Comment by ytti** [comment]
The issue is raised here:
https://github.com/ytti/oxidized/blob/8d56ef34d010eb6e221cbe75b14c3abb75e5538c/lib/oxidized/nodes.rb#L173-L177

For some reason we don't find the node, so instead of returning node at line 175, we return `nil`, and later fail trying to call `nil#output`.

We'd need to troubleshoot line 175 loop to understand what we are iterating and what our argument is, but stab in the dark, it looks like you have spaces in your name, maybe that doesn't work, maybe we're not passing the whole name from the webcall.

**Comment by NathanPoret** [comment]
So **without space that work** :
![image](https://user-images.githubusercontent.com/44426867/109801903-67aaa880-7c1f-11eb-9d4c-0adc5363b4fb.png)

But i have a nomenclature to respect and i need to place space in my name, i'll looking up the file, I come back to you when I think I have found the solution. Thank you for your quick response!

**Comment by ytti** [comment]
You may also want to look at oxidized-web, if we're passing only the first part of the devicename before first space, which is what I'd guess is happening. So likely we need to fix it in oxidized-web so that it is calling the method correctly.

**Comment by NathanPoret** [comment]
This remains strange because even when I use Nodes with a model name that contains spaces it works (example with Mikrotik).

![image](https://user-images.githubusercontent.com/44426867/109805148-62e7f380-7c23-11eb-9015-b45a4dbcc987.png)

![image](https://user-images.githubusercontent.com/44426867/109805232-7a26e100-7c23-11eb-97db-6a8b1348a9e2.png)

**Comment by NathanPoret** [comment]
I've an update : That's work even if you have space in the name, the problem i've seen : ** That because the name is too long ???** 

![image](https://user-images.githubusercontent.com/44426867/109807751-9e37f180-7c26-11eb-96ea-e5516fedbcd7.png)

![image](https://user-images.githubusercontent.com/44426867/109807844-b3ad1b80-7c26-11eb-93cf-7d557d86c52d.png)

But NO i've test by caracter's total number (when doesn't work = 107) but that's not it. I've test with more than 107 caracters :

![image](https://user-images.githubusercontent.com/44426867/109809407-8c574e00-7c28-11eb-8912-59680402b351.png)

But that's still don't work with the original : 

![image](https://user-images.githubusercontent.com/44426867/109809756-fa037a00-7c28-11eb-8434-3c842bdc307d.png)
(*Original at the top : doesn't work, test at the bottom work*)

**Comment by NathanPoret** [comment]
Update : **The problem was the "/" caracters !** (even "\" doesn't work) So i've decide to **replace them by "," which work** !
