### ISSUE TITLE
Replicating config files to another location

### ISSUE THREAD

**Issue by fwells11** [ytti/oxidized#2274]
I have Oxidized integrated with LibreNMS and it is finding and pulling most config files (Still trying to figure out why Cisco Nexus switches are not pullable) but I don't know where the config files are stored.  The stuff in GIT is encrypted so it's not useful.  Could use some guidance please.

My sanitized config:

username:
password:
model: ios
resolve_dns: false
interval: 3600
use_syslog: false
debug: false
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 172.22.26.50:8888
next_adds_job: false
vars: {}
groups: {}
models: {}
pid: "/home/oxidized/pid"
crash:
directory: "/home/oxidized/.config/oxidized/crash"
hostnames: false
stats:
history_size: 10
input:
default: ssh, telnet
debug: false
ssh:
secure: false
utf8_encoded: true
output:
default: git
git:
user: oxidized
email: oxidized@example.com
repo: "/home/oxidized/devices.git"
http:
url: http://172.22.26.50/api/v0/oxidized
source:
default: http
debug: true
http:
url: http://172.22.26.50/api/v0/oxidized
map:
name: hostname
model: os
group: group
headers:
X-Auth-Token: ''
groups:
default: HLI_HQ
HLI_HQ:
username:
password:

**Comment by mortzu** [comment]
Can you please reformat your paste to make it readable? (https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code)
