### ISSUE TITLE
Privileged mode globally enabled doesn't work on Cisco IOS

### ISSUE THREAD

**Issue by mshuttle76** [ytti/oxidized#2277]
Hello,
i just upgraded to 0.28.0 version on Ubuntu LTS 20.04 Server and I have issues with privileged mode globally enable.
Oxidized logs on correctly into the remote device but miss elevating privileges with "enable" command. I have the issue either with ssh or telnet.
The only way to do the job it's passing the credentials throught router.db .

**Extact of config file:**

```
vars:
  enable: XXXXXXXXX
  ssh_no_keepalive: true
input:
  default: ssh, telnet
  debug: true
  ssh:
    secure: false
output:
  default: git
  git:
    user: oxidized
    email: xxxxxxx
    repo: "/home/oxidized/oxidized/devices.git"
source:
  default: csv
  csv:
    file: /home/oxidized/.config/oxidized/router.db
    delimiter: !ruby/regexp /:/
    map:
      ip: 0
      name: 1
      model: 2
      group: 3
      username: 4
      password: 5
    vars_map:
      enable: 6
      ssh_no_keepalive: 7 
    gpg: false
model_map:
  cisco: ios
```

**Extract of router.db:**
_192.168.0.137:DEVICE1:cisco:ACCESS:oxidized:PASSWORD:ENABLEPASSWORD  (working)
192.168.0.237:DEVICE2-2:cisco:ACCESS (not working)_

**the debug shows:**
_192.168.0.237>show running-config
show running-config
      ^
% Invalid input detected at '^' marker.

192.168.0.237>exit_

**Comment by FlorianB06** [comment]
Hi, any chance you have resolved the issue ? same problem here. Best regards

**Comment by mortzu** [comment]
does it help if you remove the enable: 6 from the csv input?

**Comment by Tori5310** [comment]
According to your configuration, I solve my problem of  can't enable global privilege mode. Thank you so much.
