### ISSUE TITLE
Disk space filling quickly

### ISSUE THREAD

**Issue by fwells11** [ytti/oxidized#2281]
I built an Ubuntu server recently.  It used MariaDB.  I only gave it 15Gb disk space because I assumed it would be handling mostly very small text files.  to my dismay after adding a handful of devices the disk maxed out and MariaDB would not start any longer.  

I just built another server with 50Gb disk space and paid attention to the disk space this time.  With a single device in Libre the disk space was 9.7Gb used.  I added a second device and now the disk space is 11.3 Gb used!  Something must not be configured correctly but I don't know what.  LibreNMS should have a few rows in it's Db added and the config file is just a few Kb in size.  

Appreciate any thoughts please.

**Comment by davama** [comment]
so...you using oxidized and librenms in same box?

oxidize is pretty light

librenms creats rdd files. (They huge)
Did you check where the folder with big data is?

this seems to me like a librenms issue.

**Comment by fwells11** [comment]
Thanks for your feedback.  Now that I have a server that's functional I can do some checking.  You are absolutely right, it's the RRD stuff from Libre that's using ridiculous disk space per device.   Now I need to figure out how to remove all graphs except the few that are important to me.  Hoping it's template based so it will be one and done...

**Comment by davama** [comment]
Glad you found it

i think this issue can be closed as it pertains to librenms
