### ISSUE TITLE
Oxidized updating git but no versions

### ISSUE THREAD

**Issue by Nazgulnr5** [ytti/oxidized#2283]
Edit: Solved....I fluked with the installation and there was more than once config file and I edited the wrong one.

Hi there,
I'm running a pretty new install of Oxidized (v.0.28.0) on Ubuntu. It uses git for the repo and while it shows the most up to date config version for the devices it doesn't keep versions. When I click on the 'versions' icon it shows an empty table with "No data available in table".
I checked for known issues but only found something when using groups with a single repo but we don't use groups.
Here's the Oxidized config:
resolve_dns: false
interval: 3600
use_syslog: false
debug: false
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 127.0.0.1:8888
next_adds_job: false
vars: {}
groups: {}
models: {}
pid: "/home/someuser/.config/oxidized/pid"
crash:
  directory: "/home/someuser/.config/oxidized/crashes"
  hostnames: false
stats:
  history_size: 10
input:
  default: ssh, telnet
  debug: false
  ssh:
    secure: false
  ftp:
    passive: true
  utf8_encoded: true
output:
  default: git
  git:
    user: oxidized
    email: oxidized@oxidized.local
    repo: "~/.config/oxidized/oxidized.git"
source:
  default: csv
  debug: false
  csv:
    file: "/home/oxidized/.config/oxidized/router.db"
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      ip: 1
      model: 2
      username: 3
      password: 4
    gpg: false
model_map:
cisco: ios
fortigate: FortiOS

Any ideas where it goes wrong?

**Comment by kevinli7961** [comment]
Have you solved your problem? I have the same problem
