### ISSUE TITLE
Add option for HTTP Proxy setting to connect to the remote repo

### ISSUE THREAD

**Issue by oijkn** [ytti/oxidized#2284]
Oxidized should use the `env` vars `http_proxy` and `https_proxy` during the Hook push_to_remote, so it can be used in an enviroment without direct internet access, where everything goes through an http proxy.

I tried to add this settings to repo config but that not work :
```
[http]
        proxy = http://<url>:<port>
[https]
        proxy = http://<url>:<port>
```

Actually I can't connect to remote Gitlab because I'm under a http proxy.
```
E, [2021-04-02T09:08:43.654185 #12221] ERROR -- : Hook push_to_remote (#<GithubRepo:0x0000000804f8a898>) failed (#<Rugged::OSError: failed to connect to ********: Operation timed out>) for event :node_success
```

**Comment by oijkn** [comment]
Hi, this project is always active ?

**Comment by elmobp** [comment]
My suggestion would be do it over SSH via proxy... in you oxidised user home directory make a .ssh/config with a ProxyCommand in it via nc

ie
```
Host my.gitlab.com
  ProxyCommand=nc -X 5 -x proxy_host:proxy_port %h %p
```

**Comment by oijkn** [comment]
@elmobp I can't use ssh to connect at Gitlab because our rules doesn't allow it (no ssh between VMs). The only solution is to login over HTTP.

**Comment by oijkn** [comment]
@ytti Can you help me with this problem, please? Thanks for your support.

**Comment by oijkn** [comment]
@ytti This feature is available on the latest version ?
