### ISSUE TITLE
Crashes on ssh start, never tries telnet

### ISSUE THREAD

**Issue by ja-johns** [ytti/oxidized#2285]
Puma starting in single mode...
* Version 3.11.4 (ruby 2.5.1-p57), codename: Love Song
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://127.0.0.1:8888
Use Ctrl-C to stop
#<Oxidized::Job:0x00007f59980ab330@/var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/job.rb:7 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	21: from /var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/job.rb:9:in `block in initialize'
	20: from /var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/node.rb:38:in `run'
	19: from /var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/node.rb:38:in `each'
	18: from /var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/node.rb:44:in `block in run'
	17: from /var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/node.rb:67:in `run_input'
	16: from /var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/input/ssh.rb:27:in `connect'
	15: from /var/lib/gems/2.5.0/gems/net-ssh-5.2.0/lib/net/ssh.rb:246:in `start'
	14: from /var/lib/gems/2.5.0/gems/net-ssh-5.2.0/lib/net/ssh.rb:246:in `new'
	13: from /var/lib/gems/2.5.0/gems/net-ssh-5.2.0/lib/net/ssh/transport/session.rb:90:in `initialize'
	12: from /var/lib/gems/2.5.0/gems/net-ssh-5.2.0/lib/net/ssh/transport/session.rb:223:in `wait'
	11: from /var/lib/gems/2.5.0/gems/net-ssh-5.2.0/lib/net/ssh/transport/session.rb:223:in `loop'
	10: from /var/lib/gems/2.5.0/gems/net-ssh-5.2.0/lib/net/ssh/transport/session.rb:225:in `block in wait'
	 9: from /var/lib/gems/2.5.0/gems/net-ssh-5.2.0/lib/net/ssh/transport/session.rb:190:in `poll_message'
	 8: from /var/lib/gems/2.5.0/gems/net-ssh-5.2.0/lib/net/ssh/transport/session.rb:190:in `loop'
	 7: from /var/lib/gems/2.5.0/gems/net-ssh-5.2.0/lib/net/ssh/transport/session.rb:210:in `block in poll_message'
	 6: from /var/lib/gems/2.5.0/gems/net-ssh-5.2.0/lib/net/ssh/transport/algorithms.rb:167:in `accept_kexinit'
	 5: from /var/lib/gems/2.5.0/gems/net-ssh-5.2.0/lib/net/ssh/transport/algorithms.rb:228:in `proceed!'
	 4: from /var/lib/gems/2.5.0/gems/net-ssh-5.2.0/lib/net/ssh/transport/algorithms.rb:406:in `exchange_keys'
	 3: from /var/lib/gems/2.5.0/gems/net-ssh-5.2.0/lib/net/ssh/transport/kex/diffie_hellman_group1_sha1.rb:71:in `exchange_keys'
	 2: from /var/lib/gems/2.5.0/gems/net-ssh-5.2.0/lib/net/ssh/transport/kex/diffie_hellman_group1_sha1.rb:160:in `send_kexinit'
	 1: from /var/lib/gems/2.5.0/gems/net-ssh-5.2.0/lib/net/ssh/buffer.rb:249:in `read_key'
/var/lib/gems/2.5.0/gems/net-ssh-5.2.0/lib/net/ssh/buffer.rb:336:in `read_keyblob': unsupported key type ` (NotImplementedError)
Q�/��@v�t��w��೶�HEӥT��9����g3�!AIc
                                  GS�ʍ"pu��~�?n�ᅻ`u���6�����ű8"��
                                                                �|�=���:3����J���^z~��{w4���2.=s'!O��'
Traceback (most recent call last):
	21: from /var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/job.rb:9:in `block in initialize'
	20: from /var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/node.rb:38:in `run'
	19: from /var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/node.rb:38:in `each'
	18: from /var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/node.rb:44:in `block in run'
	17: from /var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/node.rb:67:in `run_input'
	16: from /var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/input/ssh.rb:27:in `connect'
	15: from /var/lib/gems/2.5.0/gems/net-ssh-5.2.0/lib/net/ssh.rb:246:in `start'
	14: from /var/lib/gems/2.5.0/gems/net-ssh-5.2.0/lib/net/ssh.rb:246:in `new'
	13: from /var/lib/gems/2.5.0/gems/net-ssh-5.2.0/lib/net/ssh/transport/session.rb:90:in `initialize'
	12: from /var/lib/gems/2.5.0/gems/net-ssh-5.2.0/lib/net/ssh/transport/session.rb:223:in `wait'
	11: from /var/lib/gems/2.5.0/gems/net-ssh-5.2.0/lib/net/ssh/transport/session.rb:223:in `loop'
	10: from /var/lib/gems/2.5.0/gems/net-ssh-5.2.0/lib/net/ssh/transport/session.rb:225:in `block in wait'
	 9: from /var/lib/gems/2.5.0/gems/net-ssh-5.2.0/lib/net/ssh/transport/session.rb:190:in `poll_message'
	 8: from /var/lib/gems/2.5.0/gems/net-ssh-5.2.0/lib/net/ssh/transport/session.rb:190:in `loop'
	 7: from /var/lib/gems/2.5.0/gems/net-ssh-5.2.0/lib/net/ssh/transport/session.rb:210:in `block in poll_message'
	 6: from /var/lib/gems/2.5.0/gems/net-ssh-5.2.0/lib/net/ssh/transport/algorithms.rb:167:in `accept_kexinit'
	 5: from /var/lib/gems/2.5.0/gems/net-ssh-5.2.0/lib/net/ssh/transport/algorithms.rb:228:in `proceed!'
	 4: from /var/lib/gems/2.5.0/gems/net-ssh-5.2.0/lib/net/ssh/transport/algorithms.rb:406:in `exchange_keys'
	 3: from /var/lib/gems/2.5.0/gems/net-ssh-5.2.0/lib/net/ssh/transport/kex/diffie_hellman_group1_sha1.rb:71:in `exchange_keys'
	 2: from /var/lib/gems/2.5.0/gems/net-ssh-5.2.0/lib/net/ssh/transport/kex/diffie_hellman_group1_sha1.rb:160:in `send_kexinit'
	 1: from /var/lib/gems/2.5.0/gems/net-ssh-5.2.0/lib/net/ssh/buffer.rb:249:in `read_key'
/var/lib/gems/2.5.0/gems/net-ssh-5.2.0/lib/net/ssh/buffer.rb:336:in `read_keyblob': unsupported key type ` (NotImplementedError)
Q�/��@v�t��w��೶�HEӥT��9����g3�!AIc
                                  GS�ʍ"pu��~�?n�ᅻ`u���6�����ű8"��
                                                                �|�=���:3����J���^z~��{w4���2.=s'!O��'
I, [2021-04-05T22:37:25.924466 #98]  INFO -- : Oxidized starting, running as pid 98
I, [2021-04-05T22:37:25.926742 #98]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
I, [2021-04-05T22:37:25.999332 #98]  INFO -- : lib/oxidized/nodes.rb: Loaded 4 nodes
Puma starting in single mode...
* Version 3.11.4 (ruby 2.5.1-p57), codename: Love Song
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://127.0.0.1:8888

**Comment by mortzu** [comment]
Can you please reformat your paste to make it readable? (https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code)
