### ISSUE TITLE
modify prompt for ubuntu 20.04 in linuxgeneric.rb

### ISSUE THREAD

**Issue by falkheiland** [ytti/oxidized#2287]
suggestion to change 

https://github.com/ytti/oxidized/blob/8179f48545d94a1c6b3a096153f70e9eabff1e20/lib/oxidized/model/linuxgeneric.rb#L2

to

```
prompt /^(\w.*|\W.*)(:|#)(~\$)* /
```

to get ubuntu 20.04 working.

this matches

```
user@server:~$ # ubuntu non root user
user@server:/# 
user@server: 
```

**Comment by falkheiland** [comment]
i changed the prompt to:

```
prompt /^(\w.*|\W.*)(:|#) */
```

this way i could include suse enterprise as well - but i think that maybe to generic as a regex - so feel free to close the issue

**Comment by mortzu** [comment]
Please make a PR
