### ISSUE TITLE
New First time setup

### ISSUE THREAD

**Issue by averagecdn** [ytti/oxidized#2292]
New setup, first time. Followed guides to perform install, getting following error. Github is running on the local server, and I have a created a group with rw permissions to the /srv folder which contains my .git repo.

F, [2021-04-20T15:44:09.934714 #1558] FATAL -- : Oxidized crashed, crashfile written in /home/oxidized/.config/oxidized/crash
first 'failed to create temporary file '/srv/NetworkConfigs.git/objects/tmp_object_git2_XG8TuZ': Permission denied' was raised while opening git repo, then 'no implicit conversion of Rugged::Repository into String' was while trying to create git repo
Traceback (most recent call last):
        16: from /usr/local/bin/oxidized:23:in `<main>'
        15: from /usr/local/bin/oxidized:23:in `load'
        14: from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/bin/oxidized:8:in `<top (required)>'
        13: from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/cli.rb:13:in `run'
        12: from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:4:in `new'
        11: from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:4:in `new'
        10: from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:29:in `initialize'
         9: from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:36:in `run'
         8: from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/worker.rb:16:in `work'
         7: from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/worker.rb:16:in `each'
         6: from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/worker.rb:16:in `block in work'
         5: from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/worker.rb:47:in `process'
         4: from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/worker.rb:65:in `process_success'
         3: from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/output/git.rb:57:in `store'
         2: from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/output/git.rb:160:in `update'
         1: from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/output/git.rb:175:in `update_repo'
/var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/output/git.rb:175:in `write': failed to create temporary file '/srv/NetworkConfigs.git/objects/tmp_object_git2_XG8TuZ': Permission denied (Rugged::OSError)
        16: from /usr/local/bin/oxidized:23:in `<main>'
        15: from /usr/local/bin/oxidized:23:in `load'
        14: from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/bin/oxidized:8:in `<top (required)>'
        13: from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/cli.rb:13:in `run'
        12: from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:4:in `new'
        11: from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:4:in `new'
        10: from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:29:in `initialize'
         9: from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:36:in `run'
         8: from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/worker.rb:16:in `work'
         7: from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/worker.rb:16:in `each'
         6: from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/worker.rb:16:in `block in work'
         5: from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/worker.rb:47:in `process'
         4: from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/worker.rb:65:in `process_success'
         3: from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/output/git.rb:57:in `store'
         2: from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/output/git.rb:158:in `update'
         1: from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/output/git.rb:163:in `rescue in update'
/var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/output/git.rb:163:in `init_at': no implicit conversion of Rugged::Repository into String (TypeError)
        16: from /usr/local/bin/oxidized:23:in `<main>'
        15: from /usr/local/bin/oxidized:23:in `load'
        14: from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/bin/oxidized:8:in `<top (required)>'
        13: from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/cli.rb:13:in `run'
        12: from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:4:in `new'
        11: from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:4:in `new'
        10: from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:29:in `initialize'
         9: from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/core.rb:36:in `run'
         8: from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/worker.rb:16:in `work'
         7: from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/worker.rb:16:in `each'
         6: from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/worker.rb:16:in `block in work'
         5: from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/worker.rb:47:in `process'
         4: from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/worker.rb:65:in `process_success'
         3: from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/output/git.rb:57:in `store'
         2: from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/output/git.rb:158:in `update'
         1: from /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/output/git.rb:162:in `rescue in update'
/var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/output/git.rb:165:in `rescue in rescue in update': first 'failed to create temporary file '/srv/NetworkConfigs.git/objects/tmp_object_git2_XG8TuZ': Permission denied' was raised while opening git repo, then 'no implicit conversion of Rugged::Repository into String' was while trying to create git repo (Oxidized::Git::GitError)

**Comment by davama** [comment]
Which guide specifically did you follow?
Show steps you did to install
What distro?

**Comment by averagecdn** [comment]
Ubuntu 20. I folllowed https://git-scm.com/book/en/v2/Git-on-the-Server-Setting-Up-the-Server. 

I created a git user, and everything was done under this user, I installed rugged with gem (gem install rugged). Sorry I can't list every command i have been working on this for the past two days.

If there is a guide on how to set this up properly with a local git repo i am more than willing to follow it.

**Comment by davama** [comment]
So you are trying to install oxidized and want to track your changes using git, yes?

To install oxidized follow: https://github.com/ytti/oxidized#installation
To use the awesome git feature, there is really nothing special to it. Just make sure your system has `git` installed. And of course configure oxidized to use git.

If you want to have a nice web-gui to see all your git changes, you can either use https://github.com/ytti/oxidized-web or some other web git service. 

Personally use both oxidized-web and cgit which work awesome!

Hope this helps

**Comment by averagecdn** [comment]
Did you create a separate user for git or did you configure it under the oxidized user? I am running git,oxidized and libre all on the same server.

**Comment by davama** [comment]
my git repository ( the actual git files) are living in the HOME of my user running oxidized. Granted I am not running a git server like bitbucket or gitlab where real ppl are making changes to code via git. 

Site note: The git repo oxidized creates are bare repos. So cgit or oxidzed-web to have a nice gui to see changes is sufficient for us

librenms will have to query the api of oxidized if you are trying to integrate that too.. but that's a separate discussion. Docs out there for that.

**Comment by averagecdn** [comment]
So i did install oxidized-web as per the instructions i followed, how do you access the oxidized-web interface?

**Comment by averagecdn** [comment]
is it http://servername/oxidized?

**Comment by davama** [comment]
whatever you have configured on your oxidized config:
```
rest: localhost:8888
```

then on local browser: http://localhost:8888

You can use nginx to proxy your connection to make it public

**Comment by davama** [comment]
Please kindly close if you are good
