### ISSUE TITLE
Import only certain models

### ISSUE THREAD

**Issue by averagecdn** [ytti/oxidized#2295]
I am using Librenms as my source of devices, I would like to only import a specific model from libre and ignore the rest. I am not sure if there a way to filter the device models it accepts.

**Comment by davama** [comment]
did you look at librenms doc.......?
https://docs.librenms.org/Extensions/Oxidized/

under Misc....

this is an Librenms issue not oxidized

**Comment by averagecdn** [comment]
So I can't ignore based on "ios" because most devices run IOS. It doesn't appear you can block on everything except SMB/SB switch model. Is there a comprehensive list of ways you can block.

**Comment by davama** [comment]
ask the folks at Libre

**Comment by averagecdn** [comment]
Thank-you will do!
