### ISSUE TITLE
Telnet expect model function broken

### ISSUE THREAD

**Issue by rgergon** [ytti/oxidized#2296]
When using telnet (ssh is fine) the "expect" functionality in models is broken and does not work. This used to work in oxidized-0.21 but is broken at least already in 0.26-3.
I've seen a lot of weird workarounds of other peoples in PRs or unspecific issue reports where I am certain they are all caused by the same issue: The fact that expect simply doesn't work anymore when using telnet. In most cases, the model's expect for pagination handling then causes timeouts but it could be of course more advanced features.
I am not a ruby programmer so I stopped trying to fix this issue after diagnosing it, but there's some FIXME's in the code there (depending on version).
Workarounds until fixed:
* don't use expect in model
* use ssh

**Comment by candlerb** [comment]
I also find that nothing is written to `logs/x.x.x.x-telnet` except the initial username/password login (not even sending of 'enable')

Assuming this logging is done [here](https://github.com/ytti/oxidized/blob/master/lib/oxidized/input/telnet.rb#L104-L107) in `oxidized_expect`:

```
        if Oxidized.config.input.debug?
          @log.print buf
          @log.flush
        end
```

then it implies that `oxidized_expect` is not being called from somewhere else that it should be.

**Comment by jvkassi** [comment]
Hello, 

I had the same issue.
I am using 0.21.1 and everything working as expected :)
