### ISSUE TITLE
Retention when using GIT as storage

### ISSUE THREAD

**Issue by MaartenMol** [ytti/oxidized#2300]
We have been using Oxidized for sometime now but it starts to get very slow. It seems to keep all configs for all devices. While we would say to only keep X versions. Is it possible to force this so Oxidized removes older configs? Or what is the advise to get around this?

Hope to hear from you as Oxidized really delivers what we need! :)

**Comment by davama** [comment]
to clean up git you need to do that manually or script it

there are some script around here... look it up in issues

**Comment by FlorianHeigl** [comment]
see wiki: https://github.com/ytti/oxidized/wiki
don't forget there's also `git gc`
