### ISSUE TITLE
Telnet: unable to detect prompt on D-Link DES-3550/3526/3052

### ISSUE THREAD

**Issue by Tualua** [ytti/oxidized#2301]
Hello! I've got fresh install of Oxidized on Oracle Linux 8.3.
My network equipment is a bunch of Cisco 3750/2960 and D-Link DES-3550/3526/3052.

I have no problem with Cisco  as I use SSH to backup.

The only problem is D-Link switches with telnet.

I was able to to download config only from 1 DES-3550. All others are "unable to detect prompt".

Here are some logs.
Successfull attempt:

    172.17.17.148 raised Net::SSH::Disconnect with msg "connection closed by remote host"
    lib/oxidized/node.rb: Oxidized::SSH failed for cust-sw-148
    lib/oxidized/input/cli.rb: Running post_login commands at cust-sw-148
    lib/oxidized/input/cli.rb: Running post_login command: "disable clipaging", block: nil at cust-sw-$
    Telnet: disable clipaging @cust-sw-148
    lib/oxidized/model/model.rb Collecting commands' outputs
    lib/oxidized/model/model.rb Executing show switch
    Telnet: show switch @cust-sw-148
    lib/oxidized/model/model.rb Executing show vlan
    Telnet: show vlan @cust-sw-148
    lib/oxidized/model/model.rb Executing show config current
    Telnet: show config current @cust-sw-148
    lib/oxidized/worker.rb: 1 jobs running in parallel
    lib/oxidized/input/cli.rb Running pre_logout commands at cust-sw-148
    lib/oxidized/node.rb: Oxidized::Telnet ran for cust-sw-148 successfully
    lib/oxidized/job.rb: Config fetched for cust-sw-148 at 2021-05-08 06:31:39 UTC
    Configuration updated for customers/cust-sw-148
    GithubRepo: Pushing local repository(/etc/oxidized/output/network-config.git/)...
    GithubRepo: to remote: git@git.local.io:oxidized/network-config.git
    GithubRepo: Authenticating using ssh keys as 'git'
    GithubRepo: {:total_objects=>0, :indexed_objects=>0, :received_objects=>0, :local_objects=>0, :tot$
    GithubRepo: nothing received after fetch
    GithubRepo: Authenticating using ssh keys as 'git'
    lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 32 of 46

Unsuccessful attempt:

     WARN -- : customers/cust-sw-101 status no_connection, retry attempt 3
    DEBUG -- : lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 38 of 46
    DEBUG -- : lib/oxidized/worker.rb: Added customers/cust-sw-101 to the job queue
    DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
    DEBUG -- : lib/oxidized/job.rb: Starting fetching process for cust-sw-101 at 2021-05-08 07:06:49 UTC
    DEBUG -- : lib/oxidized/input/ssh.rb: Connecting to cust-sw-101
    DEBUG -- : AUTH METHODS::["none", "publickey", "password"]
    DEBUG -- net.ssh.transport.session[3f7f701950a8]: establishing connection to 172.17.17.101:22
    DEBUG -- net.ssh.transport.session[3f7f701950a8]: connection established
     INFO -- net.ssh.transport.server_version[3f7f70194a40]: negotiating protocol version
    DEBUG -- net.ssh.transport.server_version[3f7f70194a40]: local is `SSH-2.0-Ruby/Net::SSH_5.2.0 x86_64-linux'
    DEBUG -- : 172.17.17.101 raised Net::SSH::Disconnect with msg "connection closed by remote host"
    DEBUG -- : lib/oxidized/node.rb: Oxidized::SSH failed for cust-sw-101
    DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
    DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
    DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
    DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
    DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
    DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
    DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
    DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
    DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
    DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
    DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
    DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
    DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
    DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
    DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
    DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
    DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
    DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
    DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
    DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
    DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
    DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
    DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
    DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
    DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
    DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
    DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
    DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
    DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
    DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
     WARN -- : 172.17.17.101 raised Oxidized::PromptUndetect with msg "unable to detect prompt: (?-mix:^(\r*[\w\s>
    DEBUG -- : lib/oxidized/node.rb: Oxidized::Telnet failed for cust-sw-101
    DEBUG -- : lib/oxidized/job.rb: Config fetched for cust-sw-101 at 2021-05-08 07:07:19 UTC
     WARN -- : customers/cust-sw-101 status no_connection, retries exhausted, giving up

First, I thought this is firmware issue, but another 3550 with the same firmware (Build 5.01.B52) shows the same behavior.

And even succesful telnet connection to the switch gave me only part of config:

    #-------------------------------------------------------------------
    #                       DES-3550 Configuration
    #
    #                       Firmware: Build 5.01.B52
    #        Copyright(C) 2008 D-Link Corporation. All rights reserved.
    #-------------------------------------------------------------------
    
    
    # BASIC
    
    config serial_port baud_rate 9600 auto_logout 10_minutes
    enable telnet 23
    enable web 80

Could anybody help me with this issue? 

Here is an example of prompt:

    
                  DES-3550 Fast Ethernet Switch Command Line Interface
    
                                Firmware: Build 5.01.B65
                Copyright(C) 2008 D-Link Corporation. All rights reserved.
    username:

**Comment by Tualua** [comment]
Hi, as I said in original message D-Link's configured with telnet, SSH is disabled

**Comment by chalarm** [comment]
So what did you configure in oxidized's routers configuration as it's attempting to connect over SSH, show your configuration.

Side-note: your trying it on heavily EOL equipment and EOL software (2008 I'm seeing).

**Comment by Tualua** [comment]
> So what did you configure in oxidized's routers configuration as it's attempting to connect over SSH, show your configuration.
> 
> Side-note: your trying it on heavily EOL equipment and EOL software (2008 I'm seeing).

    WARN -- : 172.17.17.101 raised Oxidized::PromptUndetect with msg "unable to detect prompt: (?-mix:^(\r*[\w\s>
    DEBUG -- : lib/oxidized/node.rb: Oxidized::Telnet failed for cust-sw-101

This log entry definitely says that oxidized tried to connect with telnet. Sometimes it happens and it downloads partial config

My config

    ---
    username: admin
    password: admin
    model: junos
    resolve_dns: true
    interval: 3600
    use_syslog: false
    debug: false
    threads: 30
    timeout: 30
    retries: 3
    prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
    rest: 0.0.0.0:8888
    next_adds_job: false
    vars: {}
    groups:
      group1:
        username: admin
        password: password
        vars:
          enable: password
      group2:
        username: admin
        password: password
        vars:
          enable: password
      group3:
        username: oxidized
        password: password
        vars:
          ssh_port: 58888
      group4:
        username: oxidized
        password: password
        vars:
          ssh_port: 58888
      group5:
        username: admin
        password: password
        vars:
          enable: password
      group6:
        username: admin
        password: password
        vars:
          enable: password
    models: {}
    pid: "/etc/oxidized/.config/oxidized/pid"
    crash:
      directory: "/etc/oxidized/.config/oxidized/crashes"
      hostnames: false
    stats:
      history_size: 10
    input:
      default: ssh, telnet
      debug: false
      ssh:
        secure: false
      ftp:
        passive: true
    utf8_encoded: true
    output:
     default: git
     git:
       single_repo: true
       user: oxidized
       email: oxidized@local
       repo: /etc/oxidized/output/network-config.git
    hooks:
      push_to_remote:
        type: githubrepo
        events: [post_store]
        remote_repo: "git@git.local:oxidized/config.git"
        publickey: /home/oxidized/.ssh/id_ed25519.pub
        privatekey: /home/oxidized/.ssh/id_ed25519
    source:
      default: csv
      csv:
        file: "/etc/oxidized/router.db"
        delimiter: !ruby/regexp /:/
        map:
          name: 0
          ip: 1
          model: 2
          group: 3
        gpg: false
    model_map:
      juniper: junos
      cisco: ios

**Comment by Tualua** [comment]
> Side-note: your trying it on heavily EOL equipment and EOL software (2008 I'm seeing).

I know. It will be replaced later or in case of failure. I have spare switches
