### ISSUE TITLE
/var/log/oxidized/oxidized.log isn't being populated anymore

### ISSUE THREAD

**Issue by michieltimmers** [ytti/oxidized#2302]
Hello,

I have some problems with the general log file /var/log/oxidized/oxidized.log

I used to have entries like
D, [2017-10-19T14:06:18.636442 #29295] DEBUG -- : lib/oxidized/node.rb: Oxidized::SSH ran for host01 successfully
D, [2017-10-19T14:06:18.636517 #29295] DEBUG -- : lib/oxidized/job.rb: Config fetched for host01 at 2017-10-19 12:06:18 UTC

etcc...

As you see the entries are from 2017. But even when I set all debug options to true the files isn't being used. Also set file permissions to 777.

Below is top part of my config
`
---
interval: 3600
use_syslog: true
debug: false
threads: 2
timeout: 60
retries: 1
log: /var/log/oxidized/oxidized.log
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 127.0.0.1:8888
next_adds_job: true
vars: {}
groups: {}
`

**Comment by davama** [comment]
Im assuming restarting the service did not help...

Has the log file been rotated. Is it so large in size? I assume that because you showing us logs from 2017...

permissions on the folder/file?

**Comment by michieltimmers** [comment]
Yes I restarted the services. Even server.

I made a backup of the old log and made a new one. Permissions are as follow:

-rw-r--r--  1 oxidized oxidized    0 May 13 13:41 oxidized.log
-rw-r--r--  1 oxidized oxidized 1.3M Oct 19  2017 oxidized.log.bak

**Comment by davama** [comment]
```
#log: /var/log/oxidized/oxidized.log
debug: true
```

try this and run oxidized on the cli as your oxidized user. See if you get output.
Then leave debug on and see if log file gets populated

**Comment by michieltimmers** [comment]
Didn't seem to work. Also tried with sudo user. both same result

$ oxidized
Puma starting in single mode...
* Version 3.11.4 (ruby 2.7.0-p0), codename: Love Song
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://127.0.0.1:8888
Use Ctrl-C to stop
^C- Gracefully stopping, waiting for requests to finish
=== puma shutdown: 2021-05-13 14:44:35 +0200 ===
- Goodbye!
$ whoami
oxidized

**Comment by davama** [comment]
Did you let it try to run?
Disk space issue?

Honestly at a lost now....
Reinstall oxidized?

**Comment by clontarfx** [comment]
Make sure your oxidized daemon can read the router.db file (assuming that's the format you're using for input). As long as permissions are correct, it could be an error parsing your router.db (like wrong separator, missing data e.t.c.).

**Comment by mortzu** [comment]
no-feedback -> closed
