### ISSUE TITLE
Side by side diff of full config.

### ISSUE THREAD

**Issue by seanhol-000** [ytti/oxidized#2304]
It would be great to have a side by side comparison of full configuration, where you can choose the date to compare and see the color code for diff. similar to what is currently there but showing the full configuration.

**Comment by clontarfx** [comment]
Where would this diff exist? I assume you mean oxidized-web, as oxidized is just the daemon. Also you could use the built-in [githubrepo hook](https://github.com/ytti/oxidized/blob/master/docs/Hooks.md#hook-type-githubrepo). Using git does exactly what you've requested.

**Comment by mortzu** [comment]
Please create a PR in the oxidized-web project. Thanks
