### ISSUE TITLE
~ # oxidized     Error loading config: Tried to load unspecified class: Regexp

### ISSUE THREAD

**Issue by ciscolive** [ytti/oxidized#2305]
Error loading config: Tried to load unspecified class: Regexp

anyone else got the problem?

**Comment by grinderx** [comment]
I 'm having the same issue. Did you manage to resolve it? Thanks

**Comment by grinderx** [comment]
I 've uninstalled everything ruby wise and started from scratch. Looks much better now :)

**Comment by hotgore** [comment]
I have the same problem. What did you uninstall?

**Comment by edwardbattye** [comment]
I had this problem, seems it is caused by psych, i had the issue with psych 4.0.1 but it went away when i downgraded to 3.0.2

**Comment by kriskirkland** [comment]
"gem uninstall psych" worked as it uninstalled the 4.0.1 version but kept the default version 3.1.0. All is working again.
