### ISSUE TITLE
Problem with backup Alcatel model AOS.rb

### ISSUE THREAD

**Issue by philldias** [ytti/oxidized#2306]
Oxidized does not perform backup on alcatel AOS model switches.

I can access the equipment manually but the backup fails to run

**Script used**

Class AOS < Oxidized::Model

  comment  '! '

  cmd :all do |cfg|
    cfg.cut_both
  end

  cmd 'terminal datadump' do |cfg|
    comment cfg
  end

  cmd 'show system' do |cfg|
    cfg = cfg.each_line.find { |line| line.match 'Description' }
    comment cfg.to_s.strip
  end

  cmd 'show run' do |cfg|
    comment cfg
  end

  cmd 'show logging' do |cfg|
    comment cfg
  end

  cmd 'show version' do |cfg|
    cfg
  end

  cfg :telnet do
    username /^User Name:/
    password /^Password:/
  end

  cfg :telnet, :ssh do
    pre_logout 'exit'
  end
end

**Log**
[tvt02209@sr486 logs]$ tail -f 10.1.209.136-telnet

User Name:

**Comment by FlorianHeigl** [comment]
you need to tell your AOS version (i.e. i have it running ok now on AOS7/AOS8)

**Comment by mortzu** [comment]
no-feedback -> closed
