### ISSUE TITLE
raised Net::SSH::AuthenticationFailed with msg "Authentication failed for user

### ISSUE THREAD

**Issue by ciscolive** [ytti/oxidized#2313]
raised Net::SSH::AuthenticationFailed with msg "Authentication failed for user, but I am sure the username password can login the device mannully.

**Comment by DarkCatapulter** [comment]
You being sure that it works manually doesn't really give us any info to help you out with your problem. Need more info, we can start with these:

* How does your Oxidized config look like?
* Have you tried logging into it manually and verified that it works?
* Have you checked that you haven't entered incorrect username and password into the Oxidized config?
* Does it only fail when trying to backup a specific device or all of your devices?

(When sharing config, please make sure to remove your username and password used in the config)
