### ISSUE TITLE
Issue with output format - API (GET /nodes/stats.json)

### ISSUE THREAD

**Issue by mozmozmoz** [ytti/oxidized#2315]
Hi,

In the old Oxidized version (0.19.0), I can to GET nodes statistics with this output format:

```
#curl http://127.0.0.1:8888/nodes/stats.json
"my_node":{"
     success":[{
          "start":"2021-06-04 04:27:23 UTC",
          "end":"2021-06-04 04:27:29 UTC",
          "time":5.778305482
     }]
}
```

But, in the latest version (0.28.0), the output format is:

```
#curl http://127.0.0.1:8888/nodes/stats.json
{"my_node":"#<Oxidized::Node::Stats:0x00005617a736a460>"
```

How I can display the JSON output format like Oxidized 0.19.0 version?

Thanks in advance

**Comment by mortzu** [comment]
This is a bug. I'll will check it
