### ISSUE TITLE
Monkey patching a cmd seems to wipe all the existing cmds

### ISSUE THREAD

**Issue by pointybirds** [ytti/oxidized#2316]
Hi all,

The documentation for monkey patching existing models suggests it's possible to alter the behaviour of particular commands, e.g.:
```
cmd 'show version', clear: true do |cfg|
  ... "(new code for parsing 'show version', replaces the existing definition in the model)" ...
end
```
However when I try this, all of the other commands used by the model get removed, and only the command I'm trying to patch is retained. I'm not much of a coder but I think it's happening here in model.db:
```
      def process_args_block(target, args, block)
        if args[:clear]
          target.replace([block])
```
This seems to replace the whole array under the ':cmd' key whenever clear is set to true, not the particular element (command) inside that array.

Is this a bug, or am I doing something silly?

Kind regards

Dan

**Comment by nward** [comment]
Hi @pointybirds - I see exactly the same behaviour. Prepend will prepend before all commands. Clear will clear all cmds.

I note that if you prepend or clear on :all, or :secret, then it behaves as per the documentation.

https://github.com/ytti/oxidized/blob/8179f48545d94a1c6b3a096153f70e9eabff1e20/lib/oxidized/model/model.rb#L98-L105

I believe this should instead be:
```ruby
      def process_args_block(target, args, block)
        if args[:clear]
          target.map! { |a| a[0] == block[0] ? block : a }
        else
          method = args[:prepend] ? :unshift : :push
          target.send(method, block)
        end
      end
```

The logic here is:
- loop through the cmd list
- if the first element of each cmd (i.e. the cmd name) matches the one coming in in block, then replace it with the new one
- else, keep it the same
