### ISSUE TITLE
Issues : not matching configured prompt (?-mix:^([\w.@-]+[#>]\s?)$)"

### ISSUE THREAD

**Issue by lichao731** [ytti/oxidized#2317]
The info with equ:
1:H3C Comware Software, Version 7.1.070, Release 6126P20 (Version)
2:H3C S5130S-28P-EI (Switch info)
  5130S-28P-EI with 1 Processor
  BOARD TYPE:         S5130S-28P-EI
  DRAM:               512M bytes
  FLASH:              256M bytes
  PCB 1 Version:      VER.B
  Bootrom Version:    121
  CPLD 1 Version:     001
  Release Version:    H3C S5130S-28P-EI-6126P20
The oxidized log like this:
1:  not matching configured prompt (?-mix:^([\w.@-]+[#>]\s?)$)"
[2021-06-06T20:53:17.228999 #85862] DEBUG -- : lib/oxidized/node.rb: Oxidized::SSH failed for 172.19.254.60
2: I use ssh and telnet, but all of them are not work.
I wante to know how to solve this. Thanks so much in advance.
Best Regard fromm Archer.li.

**Comment by lichao731** [comment]
can somebody help me solve this issues ? thanks

**Comment by lichao731** [comment]
is there anyone here now? i take some days to solve ,but did not solve it.

**Comment by davama** [comment]
how does the "real" prompt look like on the CLI ?

**Comment by lichao731** [comment]
> how does the "real" prompt look like on the CLI ?
Dear davama,  prompt like the  follow 
%Jun  9 10:57:45:580 2021 5#-3F-B-BGW-01 SSHS/6/SSHS_CONNECT: SSH user admin (IP: 172.19.92.189) connected to the server successfully.
%Jun  9 10:57:46:551 2021 5#-3F-B-BGW-01 SHELL/5/SHELL_LOGIN: admin logged in from 172.19.92.189.
%Jun  9 10:58:15:101 2021 5#-3F-B-BGW-01 SHELL/5/SHELL_LOGIN: admin logged in from 172.19.92.189.
%Jun  9 10:58:24:428 2021 5#-3F-B-BGW-01 SHELL/5/SHELL_LOGOUT: admin logged out from 172.19.92.189.
%Jun  9 10:58:24:436 2021 5#-3F-B-BGW-01 SHELL/5/SHELL_LOGOUT: admin logged out from 172.19.92.189.
%Jun  9 10:58:24:447 2021 5#-3F-B-BGW-01 SHELL/5/SHELL_LOGOUT: admin logged out from 172.19.92.189.
%Jun  9 10:58:24:468 2021 5#-3F-B-BGW-01 SHELL/5/SHELL_LOGOUT: admin logged out from 172.19.92.189.
%Jun  9 10:58:24:492 2021 5#-3F-B-BGW-01 SSHS/6/SSHS_LOG: User admin logged out from 172.19.92.189 port 54312.
%Jun  9 10:58:24:492 2021 5#-3F-B-BGW-01 SSHS/6/SSHS_DISCONNECT: SSH user admin (IP: 172.19.92.189) disconnected from the server.
%Jun  9 10:58:24:496 2021 5#-3F-B-BGW-01 SSHS/6/SSHS_LOG: User admin logged out from 172.19.92.189 port 54308.
%Jun  9 10:58:24:497 2021 5#-3F-B-BGW-01 SSHS/6/SSHS_DISCONNECT: SSH user admin (IP: 172.19.92.189) disconnected from the server.
%Jun  9 10:58:27:668 2021 5#-3F-B-BGW-01 SHELL/5/SHELL_LOGOUT: admin logged out from 172.19.92.189.
%Jun  9 10:58:27:683 2021 5#-3F-B-BGW-01 SSHS/6/SSHS_LOG: User admin logged out from 172.19.92.189 port 54304.
%Jun  9 10:58:27:684 2021 5#-3F-B-BGW-01 SSHS/6/SSHS_DISCONNECT: SSH user admin (IP: 172.19.92.189) disconnected from the server.
%Jun  9 10:58:45:852 2021 5#-3F-B-BGW-01 SSHS/6/SSHS_LOG: Accepted password for admin from 172.19.92.189 port 54316.

%Jun  9 10:58:47:483 2021 5#-3F-B-BGW-01 SSHS/6/SSHS_CONNECT: SSH user admin (IP: 172.19.92.189) connected to the server successfully.
%Jun  9 10:58:48:446 2021 5#-3F-B-BGW-01 SHELL/5/SHELL_LOGIN: admin logged in from 172.19.92.189.
%Jun  9 10:59:16:901 2021 5#-3F-B-BGW-01 SHELL/5/SHELL_LOGIN: admin logged in from 172.19.92.189.
%Jun  9 11:02:43:848 2021 5#-3F-B-BGW-01 SSHS/6/SSHS_LOG: Accepted password for admin from 172.19.92.189 port 54320.

%Jun  9 11:02:44:909 2021 5#-3F-B-BGW-01 SSHS/6/SSHS_CONNECT: SSH user admin (IP: 172.19.92.189) connected to the server successfully.
%Jun  9 11:02:45:900 2021 5#-3F-B-BGW-01 SHELL/5/SHELL_LOGIN: admin logged in from 172.19.92.189.
%Jun  9 11:02:49:582 2021 5#-3F-B-BGW-01 SHELL/4/SHELL_CMD_MATCHFAIL: -User=admin-IPAddr=172.19.92.189; Command display logfile in view shell failed to be matched.
%Jun  9 11:02:52:656 2021 5#-3F-B-BGW-01 SHELL/4/SHELL_CMD_MATCHFAIL: -User=admin-IPAddr=172.19.92.189; Command display logfile in view shell failed to be matched.


my router.db like follow：
172.19.254.60:comware:admin:123456

my config like follow:
---
username: username
password: password
model: junos
resolve_dns: true
interval: 3600
log: /root/.config/oxidized/logs/oxidized.log
use_syslog: false
debug: false
threads: 30
timeout: 30
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 172.19.92.189:8888
next_adds_job: false
vars: {}
groups: {}
models: {}
pid: "/root/.config/oxidized/pid"
crash:
  directory: "/root/.config/oxidized/crashes"
  hostnames: false
stats:
  history_size: 10
input:
  default: ssh, telnet
  debug: true
  ssh:
    secure: false
  ftp:
    passive: true
  utf8_encoded: true
output:
  default: file
  file:
    directory: "/root/.config/oxidized/configs"
source:
  default: csv
  csv:
    file: "/root/.config/oxidized/router.db"
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
      username: 2
      password: 3
    gpg: false
model_map:
  juniper: junos
  cisco: ios

thanks in advance!

**Comment by lichao731** [comment]
> how does the "real" prompt look like on the CLI ?

my oxidized version is  0.28.0

**Comment by lichao731** [comment]
> how does the "real" prompt look like on the CLI ?

the log of oxidized follows
 Logfile created on 2021-06-09 15:50:35 +0800 by logger.rb/56438
I, [2021-06-09T15:50:35.826101 #21072]  INFO -- : Oxidized starting, running as pid 21072
I, [2021-06-09T15:50:35.826577 #21072]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
I, [2021-06-09T15:50:35.873512 #21072]  INFO -- : lib/oxidized/nodes.rb: Loaded 1 nodes
D, [2021-06-09T15:50:37.104012 #21072] DEBUG -- net.ssh.transport.session[3fb884008c88]: establishing connection to 172.19.254.60:22
D, [2021-06-09T15:50:37.105236 #21072] DEBUG -- net.ssh.transport.session[3fb884008c88]: connection established
I, [2021-06-09T15:50:37.105320 #21072]  INFO -- net.ssh.transport.server_version[3fb884008508]: negotiating protocol version
D, [2021-06-09T15:50:37.105346 #21072] DEBUG -- net.ssh.transport.server_version[3fb884008508]: local is `SSH-2.0-Ruby/Net::SSH_5.2.0 x86_64-linux'
D, [2021-06-09T15:50:37.116648 #21072] DEBUG -- net.ssh.transport.server_version[3fb884008508]: remote is `SSH-2.0-Comware-7.1.070'
I, [2021-06-09T15:50:37.117096 #21072]  INFO -- net.ssh.transport.algorithms[3fb88400fd1c]: sending KEXINIT
D, [2021-06-09T15:50:37.117243 #21072] DEBUG -- socket[3fb88400897c]: queueing packet nr 0 type 20 len 1324
D, [2021-06-09T15:50:37.117304 #21072] DEBUG -- socket[3fb88400897c]: sent 1328 bytes
D, [2021-06-09T15:50:37.123828 #21072] DEBUG -- socket[3fb88400897c]: read 624 bytes
D, [2021-06-09T15:50:37.123939 #21072] DEBUG -- socket[3fb88400897c]: received packet nr 0 type 20 len 620
I, [2021-06-09T15:50:37.123979 #21072]  INFO -- net.ssh.transport.algorithms[3fb88400fd1c]: got KEXINIT from server
I, [2021-06-09T15:50:37.124055 #21072]  INFO -- net.ssh.transport.algorithms[3fb88400fd1c]: negotiating algorithms
D, [2021-06-09T15:50:37.124130 #21072] DEBUG -- net.ssh.transport.algorithms[3fb88400fd1c]: negotiated:
* kex: ecdh-sha2-nistp384
* host_key: ssh-rsa
* encryption_server: aes256-ctr
* encryption_client: aes256-ctr
* hmac_client: hmac-sha2-512
* hmac_server: hmac-sha2-512
* compression_client: none
* compression_server: none
* language_client: 
* language_server: 
D, [2021-06-09T15:50:37.124148 #21072] DEBUG -- net.ssh.transport.algorithms[3fb88400fd1c]: exchanging keys
D, [2021-06-09T15:50:37.127622 #21072] DEBUG -- socket[3fb88400897c]: queueing packet nr 1 type 30 len 108
D, [2021-06-09T15:50:37.127694 #21072] DEBUG -- socket[3fb88400897c]: sent 112 bytes
D, [2021-06-09T15:50:37.267570 #21072] DEBUG -- socket[3fb88400897c]: read 432 bytes
D, [2021-06-09T15:50:37.267705 #21072] DEBUG -- socket[3fb88400897c]: received packet nr 1 type 31 len 412
D, [2021-06-09T15:50:37.269284 #21072] DEBUG -- socket[3fb88400897c]: queueing packet nr 2 type 21 len 20
D, [2021-06-09T15:50:37.269375 #21072] DEBUG -- socket[3fb88400897c]: sent 24 bytes
D, [2021-06-09T15:50:37.269422 #21072] DEBUG -- socket[3fb88400897c]: received packet nr 2 type 21 len 12
D, [2021-06-09T15:50:37.269695 #21072] DEBUG -- net.ssh.authentication.session[79f7c0]: beginning authentication of `admin'
D, [2021-06-09T15:50:37.269798 #21072] DEBUG -- socket[3fb88400897c]: queueing packet nr 3 type 5 len 28
D, [2021-06-09T15:50:37.269827 #21072] DEBUG -- socket[3fb88400897c]: sent 96 bytes
D, [2021-06-09T15:50:37.272041 #21072] DEBUG -- socket[3fb88400897c]: read 96 bytes
D, [2021-06-09T15:50:37.272135 #21072] DEBUG -- socket[3fb88400897c]: received packet nr 3 type 6 len 28
D, [2021-06-09T15:50:37.272239 #21072] DEBUG -- net.ssh.authentication.session[79f7c0]: trying none
D, [2021-06-09T15:50:37.272336 #21072] DEBUG -- socket[3fb88400897c]: queueing packet nr 4 type 50 len 44
D, [2021-06-09T15:50:37.272381 #21072] DEBUG -- socket[3fb88400897c]: sent 112 bytes
D, [2021-06-09T15:50:37.578855 #21072] DEBUG -- socket[3fb88400897c]: read 96 bytes
D, [2021-06-09T15:50:37.579016 #21072] DEBUG -- socket[3fb88400897c]: received packet nr 4 type 51 len 28
D, [2021-06-09T15:50:37.579086 #21072] DEBUG -- net.ssh.authentication.session[79f7c0]: allowed methods: password
D, [2021-06-09T15:50:37.579141 #21072] DEBUG -- net.ssh.authentication.methods.none[79a428]: none failed
D, [2021-06-09T15:50:37.579178 #21072] DEBUG -- net.ssh.authentication.session[79f7c0]: trying password
D, [2021-06-09T15:50:37.579300 #21072] DEBUG -- socket[3fb88400897c]: queueing packet nr 5 type 50 len 60
D, [2021-06-09T15:50:37.579385 #21072] DEBUG -- socket[3fb88400897c]: sent 128 bytes
D, [2021-06-09T15:50:37.621154 #21072] DEBUG -- socket[3fb88400897c]: read 80 bytes
D, [2021-06-09T15:50:37.621308 #21072] DEBUG -- socket[3fb88400897c]: received packet nr 5 type 52 len 12
D, [2021-06-09T15:50:37.621388 #21072] DEBUG -- net.ssh.authentication.methods.password[6caa34]: password succeeded
D, [2021-06-09T15:50:37.621539 #21072] DEBUG -- socket[3fb88400897c]: queueing packet nr 6 type 90 len 44
D, [2021-06-09T15:50:37.621581 #21072] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^\0*(<[\w.-]+>).?$/] at 172.19.254.60
D, [2021-06-09T15:50:37.822256 #21072] DEBUG -- socket[3fb88400897c]: sent 112 bytes
D, [2021-06-09T15:50:37.922560 #21072] DEBUG -- socket[3fb88400897c]: read 96 bytes
D, [2021-06-09T15:50:37.922710 #21072] DEBUG -- socket[3fb88400897c]: received packet nr 6 type 91 len 28
I, [2021-06-09T15:50:37.922807 #21072]  INFO -- net.ssh.connection.session[6bbd90]: channel_open_confirmation: 0 0 0 32768
I, [2021-06-09T15:50:37.922888 #21072]  INFO -- net.ssh.connection.channel[6b7f4c]: sending channel request "env"
D, [2021-06-09T15:50:37.922987 #21072] DEBUG -- socket[3fb88400897c]: queueing packet nr 7 type 98 len 44
I, [2021-06-09T15:50:37.923088 #21072]  INFO -- net.ssh.connection.channel[6b7f4c]: sending channel request "pty-req"
D, [2021-06-09T15:50:37.923157 #21072] DEBUG -- socket[3fb88400897c]: queueing packet nr 8 type 98 len 60
D, [2021-06-09T15:50:38.023404 #21072] DEBUG -- socket[3fb88400897c]: sent 240 bytes
D, [2021-06-09T15:50:38.102928 #21072] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-06-09T15:50:38.123692 #21072] DEBUG -- socket[3fb88400897c]: read 80 bytes
D, [2021-06-09T15:50:38.123810 #21072] DEBUG -- socket[3fb88400897c]: received packet nr 7 type 99 len 12
I, [2021-06-09T15:50:38.123867 #21072]  INFO -- net.ssh.connection.session[6bbd90]: channel_success: 0
I, [2021-06-09T15:50:38.123896 #21072]  INFO -- net.ssh.connection.channel[6b7f4c]: sending channel request "shell"
D, [2021-06-09T15:50:38.123993 #21072] DEBUG -- socket[3fb88400897c]: queueing packet nr 9 type 98 len 28
D, [2021-06-09T15:50:38.224253 #21072] DEBUG -- socket[3fb88400897c]: sent 96 bytes
D, [2021-06-09T15:50:38.324591 #21072] DEBUG -- socket[3fb88400897c]: read 176 bytes
D, [2021-06-09T15:50:38.326794 #21072] DEBUG -- socket[3fb88400897c]: received packet nr 8 type 93 len 28
I, [2021-06-09T15:50:38.326885 #21072]  INFO -- net.ssh.connection.session[6bbd90]: channel_window_adjust: 0 +2097152
D, [2021-06-09T15:50:38.326944 #21072] DEBUG -- socket[3fb88400897c]: received packet nr 9 type 99 len 12
I, [2021-06-09T15:50:38.326972 #21072]  INFO -- net.ssh.connection.session[6bbd90]: channel_success: 0
I, [2021-06-09T15:50:38.527410 #21072]  INFO -- net.ssh.connection.keepalive[6baa44]: sending keepalive 0
I, [2021-06-09T15:50:38.527508 #21072]  INFO -- net.ssh.connection.session[6bbd90]: sending global request keepalive@openssh.com
D, [2021-06-09T15:50:38.527625 #21072] DEBUG -- socket[3fb88400897c]: queueing packet nr 10 type 80 len 44
D, [2021-06-09T15:50:38.728160 #21072] DEBUG -- socket[3fb88400897c]: sent 112 bytes
D, [2021-06-09T15:50:38.828480 #21072] DEBUG -- socket[3fb88400897c]: read 80 bytes
D, [2021-06-09T15:50:38.828629 #21072] DEBUG -- socket[3fb88400897c]: received packet nr 10 type 82 len 12
I, [2021-06-09T15:50:38.828668 #21072]  INFO -- net.ssh.connection.session[6bbd90]: global request failure
D, [2021-06-09T15:50:38.828692 #21072] DEBUG -- net.ssh.connection.keepalive[6baa44]: keepalive response successful. Missed 0 keepalives
D, [2021-06-09T15:50:39.103204 #21072] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-06-09T15:50:39.254853 #21072] DEBUG -- socket[3fb88400897c]: read 96 bytes
D, [2021-06-09T15:50:39.355223 #21072] DEBUG -- socket[3fb88400897c]: received packet nr 11 type 94 len 28
I, [2021-06-09T15:50:39.355348 #21072]  INFO -- net.ssh.connection.session[6bbd90]: channel_data: 0 4b
D, [2021-06-09T15:50:39.355459 #21072] DEBUG -- socket[3fb88400897c]: read 496 bytes
D, [2021-06-09T15:50:39.355523 #21072] DEBUG -- socket[3fb88400897c]: received packet nr 12 type 94 len 428
I, [2021-06-09T15:50:39.355552 #21072]  INFO -- net.ssh.connection.session[6bbd90]: channel_data: 0 409b
D, [2021-06-09T15:50:40.103495 #21072] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-06-09T15:50:40.257390 #21072] DEBUG -- socket[3fb88400897c]: read 112 bytes
D, [2021-06-09T15:50:40.257567 #21072] DEBUG -- socket[3fb88400897c]: received packet nr 13 type 94 len 44
I, [2021-06-09T15:50:40.257619 #21072]  INFO -- net.ssh.connection.session[6bbd90]: channel_data: 0 16b
D, [2021-06-09T15:50:41.103741 #21072] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-06-09T15:50:42.103996 #21072] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-06-09T15:50:43.104305 #21072] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-06-09T15:50:44.104611 #21072] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-06-09T15:50:45.104941 #21072] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-06-09T15:50:46.105233 #21072] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-06-09T15:50:47.105495 #21072] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-06-09T15:50:48.105870 #21072] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-06-09T15:50:49.106223 #21072] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-06-09T15:50:50.106475 #21072] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-06-09T15:50:51.106715 #21072] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-06-09T15:50:52.106986 #21072] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-06-09T15:50:53.107336 #21072] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-06-09T15:50:54.107681 #21072] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-06-09T15:50:55.107961 #21072] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-06-09T15:50:56.108318 #21072] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-06-09T15:50:57.108676 #21072] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-06-09T15:50:58.109021 #21072] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-06-09T15:50:59.109358 #21072] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-06-09T15:51:00.109502 #21072] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-06-09T15:51:01.109641 #21072] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-06-09T15:51:02.109813 #21072] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-06-09T15:51:03.109996 #21072] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-06-09T15:51:04.110125 #21072] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-06-09T15:51:05.110283 #21072] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-06-09T15:51:06.110438 #21072] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-06-09T15:51:07.110595 #21072] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
W, [2021-06-09T15:51:07.622070 #21072]  WARN -- : 172.19.254.60 raised Oxidized::PromptUndetect with msg "

**Comment by lichao731** [comment]
I use the netmiko to backup network equ info.
