### ISSUE TITLE
Up/Down status

### ISSUE THREAD

**Issue by jjmartres** [ytti/oxidized#232]
Is there a way to specify Up/Down status for a node, to keep configuration backup even if the node is deleted ?

**Comment by ytti** [comment]
Not right now. But I'm not sure if I understand the problem. We don't ever delete/clean the git/file, so historic data will stay there forever.

**Comment by jjmartres** [comment]
If historic data stay forever, no need to mention that a device is up or down (like rancid).

Thanks for your answer
