### ISSUE TITLE
Cisco IOS Switch: SSH Password Auth fails

### ISSUE THREAD

**Issue by pdtadmin** [ytti/oxidized#2322]
Hi everyone, looking for some assistance.
I have Oxidized working right now, as it backs up my Fortios and Ruckus Devices perfectly. However, my Cisco IOS switches (2) cannot seem to log in via SSH from Oxidized. It consistently fails and I have logged into the switches directly using these same credentials.

Switch Models:
cisco WS-C3650-24TS
cisco WS-C2960X-24PS-L

Would be grateful for any tips or whether this is a bug with CISCO IOS switched currently.

Here is my config:
```
---
username: oxidize
password: ********
model: junos
interval: 3600 #interval in seconds
log: ~/.config/oxidized/log
debug: false
threads: 30
timeout: 20
retries: 1
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
crash:
  directory: ~/.config/oxidized/crashes
  hostnames: false
vars:
  enable: ********
groups: {}
rest: 0.0.0.0:8888
pid: ~/.config/oxidized/oxidized.pid
input:
  default: ssh, telnet
  debug: true
  ssh:
    secure: false
output:
  default: git
  file:
    directory: "/root/.config/oxidized/configs"
  git:
    single_repo: true
    user: pdtadmin
    email: pdt@ibsstlucia.com
    repo: "~/.config/oxidized/configs/git/Oxidized.git"
hooks:
  push_to_remote:
    type: githubrepo
    events: [post_store]
    remote_repo: https://github.com/pdtadmin/Oxidized.git
    username: pdtadmin
    password: *************
source:
  default: http
  debug: false
  http:
    url: http://172.20.99.35/api/v0/oxidized
    map:
      name: hostname
      model: os
      group: group
    headers:
      X-Auth-Token: '*********'
models:
  fortios:
    username: oxidize
    password: ********
groups:
  default:
    username: oxidize
    password: ********
model_map:
  juniper: junos
  fortigate: fortios
  cisco: ios

```
```
Logs Snippet:
W, [2021-06-08T10:42:19.133846 #17595]  WARN -- : 172.20.11.252 raised Oxidized::PromptUndetect with msg "unable to detect prompt: (?-mix:^([\w.@()-]+[#>]\s?)$)"
D, [2021-06-08T10:42:19.133933 #17595] DEBUG -- : lib/oxidized/node.rb: Oxidized::Telnet failed for ibs-hq-access-02
D, [2021-06-08T10:42:19.134012 #17595] DEBUG -- : lib/oxidized/job.rb: Config fetched for ibs-hq-access-02 at 2021-06-08 14:42:19 UTC
W, [2021-06-08T10:42:19.489653 #17595]  WARN -- : /ibs-hq-access-02 status no_connection, retry attempt 1
D, [2021-06-08T10:42:19.489728 #17595] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 3 of 4
D, [2021-06-08T10:42:19.489866 #17595] DEBUG -- : lib/oxidized/worker.rb: Added /ibs-hq-access-02 to the job queue
D, [2021-06-08T10:42:19.490033 #17595] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-06-08T10:42:19.489949 #17595] DEBUG -- : lib/oxidized/job.rb: Starting fetching process for ibs-hq-access-02 at 2021-06-08 14:42:19 UTC
D, [2021-06-08T10:42:19.490354 #17595] DEBUG -- : lib/oxidized/input/ssh.rb: Connecting to ibs-hq-access-02
D, [2021-06-08T10:42:19.490549 #17595] DEBUG -- : AUTH METHODS::["none", "publickey", "password"]
D, [2021-06-08T10:42:19.491496 #17595] DEBUG -- net.ssh.transport.session[9c4]: establishing connection to 172.20.11.252:22
D, [2021-06-08T10:42:19.493347 #17595] DEBUG -- net.ssh.transport.session[9c4]: connection established
I, [2021-06-08T10:42:19.493496 #17595]  INFO -- net.ssh.transport.server_version[9d8]: negotiating protocol version
D, [2021-06-08T10:42:19.493562 #17595] DEBUG -- net.ssh.transport.server_version[9d8]: local is `SSH-2.0-Ruby/Net::SSH_5.2.0 x86_64-linux-gnu'
D, [2021-06-08T10:42:19.496249 #17595] DEBUG -- net.ssh.transport.server_version[9d8]: remote is `SSH-1.99-Cisco-1.25'
I, [2021-06-08T10:42:19.496523 #17595]  INFO -- net.ssh.transport.algorithms[9ec]: sending KEXINIT
D, [2021-06-08T10:42:19.496908 #17595] DEBUG -- socket[a00]: queueing packet nr 0 type 20 len 1324
D, [2021-06-08T10:42:19.497032 #17595] DEBUG -- socket[a00]: sent 1328 bytes
D, [2021-06-08T10:42:19.501344 #17595] DEBUG -- socket[a00]: read 368 bytes
D, [2021-06-08T10:42:19.501511 #17595] DEBUG -- socket[a00]: received packet nr 0 type 20 len 364
I, [2021-06-08T10:42:19.501597 #17595]  INFO -- net.ssh.transport.algorithms[9ec]: got KEXINIT from server
I, [2021-06-08T10:42:19.501724 #17595]  INFO -- net.ssh.transport.algorithms[9ec]: negotiating algorithms
D, [2021-06-08T10:42:19.501887 #17595] DEBUG -- net.ssh.transport.algorithms[9ec]: negotiated:
* kex: diffie-hellman-group-exchange-sha1
* host_key: ssh-rsa
* encryption_server: aes256-ctr
* encryption_client: aes256-ctr
* hmac_client: hmac-sha1
* hmac_server: hmac-sha1
* compression_client: none
* compression_server: none
* language_client: 
* language_server: 
D, [2021-06-08T10:42:19.501946 #17595] DEBUG -- net.ssh.transport.algorithms[9ec]: exchanging keys
D, [2021-06-08T10:42:19.502156 #17595] DEBUG -- socket[a00]: queueing packet nr 1 type 34 len 20
D, [2021-06-08T10:42:19.502288 #17595] DEBUG -- socket[a00]: sent 24 bytes
D, [2021-06-08T10:42:19.510067 #17595] DEBUG -- socket[a00]: read 152 bytes
D, [2021-06-08T10:42:19.510210 #17595] DEBUG -- socket[a00]: received packet nr 1 type 31 len 148
D, [2021-06-08T10:42:19.513141 #17595] DEBUG -- socket[a00]: queueing packet nr 2 type 32 len 140
D, [2021-06-08T10:42:19.513279 #17595] DEBUG -- socket[a00]: sent 144 bytes
D, [2021-06-08T10:42:19.647348 #17595] DEBUG -- socket[a00]: read 448 bytes
D, [2021-06-08T10:42:19.647468 #17595] DEBUG -- socket[a00]: received packet nr 2 type 33 len 444
D, [2021-06-08T10:42:19.649850 #17595] DEBUG -- socket[a00]: queueing packet nr 3 type 21 len 20
D, [2021-06-08T10:42:19.649985 #17595] DEBUG -- socket[a00]: sent 24 bytes
D, [2021-06-08T10:42:19.650091 #17595] DEBUG -- socket[a00]: read 16 bytes
D, [2021-06-08T10:42:19.650189 #17595] DEBUG -- socket[a00]: received packet nr 3 type 21 len 12
D, [2021-06-08T10:42:19.650606 #17595] DEBUG -- net.ssh.authentication.session[a14]: beginning authentication of `oxidize'
D, [2021-06-08T10:42:19.650801 #17595] DEBUG -- socket[a00]: queueing packet nr 4 type 5 len 28
D, [2021-06-08T10:42:19.650880 #17595] DEBUG -- socket[a00]: sent 52 bytes
D, [2021-06-08T10:42:19.850501 #17595] DEBUG -- socket[a00]: read 52 bytes
D, [2021-06-08T10:42:19.850666 #17595] DEBUG -- socket[a00]: received packet nr 4 type 6 len 28
D, [2021-06-08T10:42:19.850829 #17595] DEBUG -- net.ssh.authentication.session[a14]: trying none
D, [2021-06-08T10:42:19.851062 #17595] DEBUG -- socket[a00]: queueing packet nr 5 type 50 len 44
D, [2021-06-08T10:42:19.851193 #17595] DEBUG -- socket[a00]: sent 68 bytes
D, [2021-06-08T10:42:19.853118 #17595] DEBUG -- socket[a00]: read 84 bytes
D, [2021-06-08T10:42:19.853273 #17595] DEBUG -- socket[a00]: received packet nr 5 type 51 len 60
D, [2021-06-08T10:42:19.853379 #17595] DEBUG -- net.ssh.authentication.session[a14]: allowed methods: publickey,keyboard-interactive,password
D, [2021-06-08T10:42:19.853496 #17595] DEBUG -- net.ssh.authentication.methods.none[a28]: none failed
D, [2021-06-08T10:42:19.853608 #17595] DEBUG -- net.ssh.authentication.session[a14]: trying publickey
D, [2021-06-08T10:42:19.853787 #17595] DEBUG -- net.ssh.authentication.agent[a3c]: connecting to ssh-agent
E, [2021-06-08T10:42:19.853870 #17595] ERROR -- net.ssh.authentication.agent[a3c]: could not connect to ssh-agent: Agent not configured
D, [2021-06-08T10:42:19.853943 #17595] DEBUG -- net.ssh.authentication.session[a14]: trying password
D, [2021-06-08T10:42:19.854136 #17595] DEBUG -- socket[a00]: queueing packet nr 6 type 50 len 60
D, [2021-06-08T10:42:19.854262 #17595] DEBUG -- socket[a00]: sent 84 bytes
D, [2021-06-08T10:42:20.492903 #17595] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-06-08T10:42:21.494179 #17595] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-06-08T10:42:21.939558 #17595] DEBUG -- socket[a00]: read 84 bytes
D, [2021-06-08T10:42:21.939809 #17595] DEBUG -- socket[a00]: received packet nr 6 type 51 len 60
D, [2021-06-08T10:42:21.939940 #17595] DEBUG -- net.ssh.authentication.session[a14]: allowed methods: publickey,keyboard-interactive,password
D, [2021-06-08T10:42:21.940041 #17595] DEBUG -- net.ssh.authentication.methods.password[a50]: password failed
E, [2021-06-08T10:42:21.940122 #17595] ERROR -- net.ssh.authentication.session[a14]: all authorization methods failed (tried none, publickey, password)
W, [2021-06-08T10:42:21.940311 #17595]  WARN -- : 172.20.11.252 raised Net::SSH::AuthenticationFailed with msg "Authentication failed for user oxidize@172.20.11.252"
D, [2021-06-08T10:42:21.940376 #17595] DEBUG -- : lib/oxidized/node.rb: Oxidized::SSH failed for ibs-hq-access-02
```

**Comment by systeembeheerder** [comment]
> my Cisco IOS switches

Make, model en firmware version? What does the prompt look like when you ssh to the switch?

**Comment by pdtadmin** [comment]
> > my Cisco IOS switches
> 
> Make, model en firmware version? What does the prompt look like when you ssh to the switch?
> edit; also fix the config layout please using the code snippet

Switch Models:
cisco WS-C3650-24TS
cisco WS-C2960X-24PS-L

After logging in to the switch through SSH, it puts me directly into the Command Line and there is no need to use an activator command like "en" or "ctrl+Y".
 Please see below:
`ibs-hq-core-sw1#`

**Comment by hunnymonster** [comment]
I have both Catalyst 2960X (WS-C2960X-24PS-L) & Catalyst 3650 (WS-C3650-24PS-S - not -L) being backed up by Oxidized. I think the only material change I made was to default to ios as model (since I don't have any JunOS devices)

```
---
username: <admin user>
password: <admin pass>
model: ios
resolve_dns: true
interval: 1200
use_syslog: false
log: /home/oxidized/.config/oxidized/log
debug: false
threads: 30
timeout: 30
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: x.x.x.x:8888
next_adds_job: false
vars: {}
groups: {}
models: {}
pid: "/etc/oxidized/pid"
crash:
  directory: "/etc/oxidized/crashes"
  hostnames: false
stats:
  history_size: 10
input:
  default: telnet,ssh
  debug: false
  ssh:
    secure: false
  ftp:
    passive: true
  utf8_encoded: true
output:
  default: git
  git:
    user: Oxidized
    email: o@example.com
    repo: "/etc/oxidized/devices.git"
source:
  default: http
  debug: false
  http:
    url: http://127.0.0.1/api/v0/oxidized
    map:
      name: hostname
      model: os
      group: group
    headers:
      X-Auth-Token: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxx'


model_map:
  cisco: ios
  ciscowlc: aireos
  asa: asa

```

**Comment by pdtadmin** [comment]
I tried changing the the default Model to ios. SSH connection to the switch is still not working. The switch uses Radius to authenticate users.

`
D, [2021-06-10T16:18:59.572926 #18767] DEBUG -- : lib/oxidized/worker.rb: Added /172.20.11.254 to the job queue
D, [2021-06-10T16:18:59.572985 #18767] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-06-10T16:18:59.573092 #18767] DEBUG -- : lib/oxidized/job.rb: Starting fetching process for 172.20.11.254 at 2021-06-10 20:18:59 UTC
D, [2021-06-10T16:18:59.573345 #18767] DEBUG -- : lib/oxidized/input/ssh.rb: Connecting to 172.20.11.254
D, [2021-06-10T16:18:59.573538 #18767] DEBUG -- : AUTH METHODS::["none", "publickey", "password"]
D, [2021-06-10T16:18:59.574555 #18767] DEBUG -- net.ssh.transport.session[f3c]: establishing connection to 172.20.11.254:22
D, [2021-06-10T16:18:59.930157 #18767] DEBUG -- net.ssh.transport.session[f3c]: connection established
I, [2021-06-10T16:18:59.930306 #18767]  INFO -- net.ssh.transport.server_version[f50]: negotiating protocol version
D, [2021-06-10T16:18:59.930368 #18767] DEBUG -- net.ssh.transport.server_version[f50]: local is `SSH-2.0-Ruby/Net::SSH_5.2.0 x86_64-linux-gnu'
D, [2021-06-10T16:18:59.936395 #18767] DEBUG -- net.ssh.transport.server_version[f50]: remote is `SSH-1.99-Cisco-1.25'
I, [2021-06-10T16:18:59.936876 #18767]  INFO -- net.ssh.transport.algorithms[f64]: sending KEXINIT
D, [2021-06-10T16:18:59.937295 #18767] DEBUG -- socket[f78]: queueing packet nr 0 type 20 len 1324
D, [2021-06-10T16:18:59.937422 #18767] DEBUG -- socket[f78]: sent 1328 bytes
D, [2021-06-10T16:18:59.940171 #18767] DEBUG -- socket[f78]: read 368 bytes
D, [2021-06-10T16:18:59.940300 #18767] DEBUG -- socket[f78]: received packet nr 0 type 20 len 364
I, [2021-06-10T16:18:59.940380 #18767]  INFO -- net.ssh.transport.algorithms[f64]: got KEXINIT from server
I, [2021-06-10T16:18:59.940503 #18767]  INFO -- net.ssh.transport.algorithms[f64]: negotiating algorithms
D, [2021-06-10T16:18:59.940678 #18767] DEBUG -- net.ssh.transport.algorithms[f64]: negotiated:
* kex: diffie-hellman-group-exchange-sha1
* host_key: ssh-rsa
* encryption_server: aes256-ctr
* encryption_client: aes256-ctr
* hmac_client: hmac-sha1
* hmac_server: hmac-sha1
* compression_client: none
* compression_server: none
* language_client: 
* language_server: 
D, [2021-06-10T16:18:59.940739 #18767] DEBUG -- net.ssh.transport.algorithms[f64]: exchanging keys
D, [2021-06-10T16:18:59.940942 #18767] DEBUG -- socket[f78]: queueing packet nr 1 type 34 len 20
D, [2021-06-10T16:18:59.941059 #18767] DEBUG -- socket[f78]: sent 24 bytes
D, [2021-06-10T16:18:59.951733 #18767] DEBUG -- socket[f78]: read 152 bytes
D, [2021-06-10T16:18:59.951852 #18767] DEBUG -- socket[f78]: received packet nr 1 type 31 len 148
D, [2021-06-10T16:18:59.954802 #18767] DEBUG -- socket[f78]: queueing packet nr 2 type 32 len 140
D, [2021-06-10T16:18:59.954956 #18767] DEBUG -- socket[f78]: sent 144 bytes
D, [2021-06-10T16:19:00.023172 #18767] DEBUG -- socket[f78]: read 448 bytes
D, [2021-06-10T16:19:00.023317 #18767] DEBUG -- socket[f78]: received packet nr 2 type 33 len 444
D, [2021-06-10T16:19:00.025583 #18767] DEBUG -- socket[f78]: queueing packet nr 3 type 21 len 20
D, [2021-06-10T16:19:00.025710 #18767] DEBUG -- socket[f78]: sent 24 bytes
D, [2021-06-10T16:19:00.025809 #18767] DEBUG -- socket[f78]: read 16 bytes
D, [2021-06-10T16:19:00.025907 #18767] DEBUG -- socket[f78]: received packet nr 3 type 21 len 12
D, [2021-06-10T16:19:00.026368 #18767] DEBUG -- net.ssh.authentication.session[f8c]: beginning authentication of `oxidize'
D, [2021-06-10T16:19:00.026538 #18767] DEBUG -- socket[f78]: queueing packet nr 4 type 5 len 28
D, [2021-06-10T16:19:00.026636 #18767] DEBUG -- socket[f78]: sent 52 bytes
D, [2021-06-10T16:19:00.227394 #18767] DEBUG -- socket[f78]: read 52 bytes
D, [2021-06-10T16:19:00.227558 #18767] DEBUG -- socket[f78]: received packet nr 4 type 6 len 28
D, [2021-06-10T16:19:00.227723 #18767] DEBUG -- net.ssh.authentication.session[f8c]: trying none
D, [2021-06-10T16:19:00.227958 #18767] DEBUG -- socket[f78]: queueing packet nr 5 type 50 len 44
D, [2021-06-10T16:19:00.228081 #18767] DEBUG -- socket[f78]: sent 68 bytes
D, [2021-06-10T16:19:00.230894 #18767] DEBUG -- socket[f78]: read 84 bytes
D, [2021-06-10T16:19:00.231052 #18767] DEBUG -- socket[f78]: received packet nr 5 type 51 len 60
D, [2021-06-10T16:19:00.231159 #18767] DEBUG -- net.ssh.authentication.session[f8c]: allowed methods: publickey,keyboard-interactive,password
D, [2021-06-10T16:19:00.231252 #18767] DEBUG -- net.ssh.authentication.methods.none[fa0]: none failed
D, [2021-06-10T16:19:00.231337 #18767] DEBUG -- net.ssh.authentication.session[f8c]: trying publickey
D, [2021-06-10T16:19:00.231518 #18767] DEBUG -- net.ssh.authentication.agent[fb4]: connecting to ssh-agent
E, [2021-06-10T16:19:00.231602 #18767] ERROR -- net.ssh.authentication.agent[fb4]: could not connect to ssh-agent: Agent not configured
D, [2021-06-10T16:19:00.231703 #18767] DEBUG -- net.ssh.authentication.session[f8c]: trying password
D, [2021-06-10T16:19:00.231973 #18767] DEBUG -- socket[f78]: queueing packet nr 6 type 50 len 76
D, [2021-06-10T16:19:00.232095 #18767] DEBUG -- socket[f78]: sent 100 bytes
D, [2021-06-10T16:19:00.317519 #18767] DEBUG -- socket[f78]: read 36 bytes
D, [2021-06-10T16:19:00.317737 #18767] DEBUG -- socket[f78]: received packet nr 6 type 52 len 12
D, [2021-06-10T16:19:00.317877 #18767] DEBUG -- net.ssh.authentication.methods.password[fc8]: password succeeded
D, [2021-06-10T16:19:00.318141 #18767] DEBUG -- socket[f78]: queueing packet nr 7 type 90 len 44
D, [2021-06-10T16:19:00.318262 #18767] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^([\w.@()-]+[#>]\s?)$/] at 172.20.11.254
D, [2021-06-10T16:19:00.518861 #18767] DEBUG -- socket[f78]: sent 68 bytes
D, [2021-06-10T16:19:00.575952 #18767] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-06-10T16:19:00.619190 #18767] DEBUG -- socket[f78]: read 52 bytes
D, [2021-06-10T16:19:00.619393 #18767] DEBUG -- socket[f78]: received packet nr 7 type 91 len 28
I, [2021-06-10T16:19:00.619537 #18767]  INFO -- net.ssh.connection.session[fdc]: channel_open_confirmation: 0 3 8192 4096
I, [2021-06-10T16:19:00.619700 #18767]  INFO -- net.ssh.connection.channel[ff0]: sending channel request "env"
D, [2021-06-10T16:19:00.619879 #18767] DEBUG -- socket[f78]: queueing packet nr 8 type 98 len 44
I, [2021-06-10T16:19:00.620037 #18767]  INFO -- net.ssh.connection.channel[ff0]: sending channel request "pty-req"
D, [2021-06-10T16:19:00.620247 #18767] DEBUG -- socket[f78]: queueing packet nr 9 type 98 len 60
D, [2021-06-10T16:19:00.720591 #18767] DEBUG -- socket[f78]: sent 152 bytes
D, [2021-06-10T16:19:00.820886 #18767] DEBUG -- socket[f78]: read 36 bytes
D, [2021-06-10T16:19:00.821065 #18767] DEBUG -- socket[f78]: received packet nr 8 type 99 len 12
I, [2021-06-10T16:19:00.821168 #18767]  INFO -- net.ssh.connection.session[fdc]: channel_success: 0
I, [2021-06-10T16:19:00.821238 #18767]  INFO -- net.ssh.connection.channel[ff0]: sending channel request "shell"
D, [2021-06-10T16:19:00.821429 #18767] DEBUG -- socket[f78]: queueing packet nr 10 type 98 len 28
D, [2021-06-10T16:19:00.921779 #18767] DEBUG -- socket[f78]: sent 52 bytes
D, [2021-06-10T16:19:01.022094 #18767] DEBUG -- socket[f78]: read 104 bytes
D, [2021-06-10T16:19:01.022280 #18767] DEBUG -- socket[f78]: received packet nr 9 type 99 len 12
I, [2021-06-10T16:19:01.022374 #18767]  INFO -- net.ssh.connection.session[fdc]: channel_success: 0
D, [2021-06-10T16:19:01.022536 #18767] DEBUG -- socket[f78]: received packet nr 10 type 94 len 44
I, [2021-06-10T16:19:01.022658 #18767]  INFO -- net.ssh.connection.session[fdc]: channel_data: 0 18b
D, [2021-06-10T16:19:01.123014 #18767] DEBUG -- : lib/oxidized/input/cli.rb: Running post_login commands at 172.20.11.254
D, [2021-06-10T16:19:01.123114 #18767] DEBUG -- : lib/oxidized/input/cli.rb: Running post_login command: nil, block: #<Proc:0x00007fa4b41e9410 /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/model/ios.rb:127> at 172.20.11.254
D, [2021-06-10T16:19:01.123282 #18767] DEBUG -- : lib/oxidized/input/ssh.rb enable @ 172.20.11.254 with expect: /^[pP]assword:/
D, [2021-06-10T16:19:01.123465 #18767] DEBUG -- socket[f78]: queueing packet nr 11 type 94 len 28
D, [2021-06-10T16:19:01.123546 #18767] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^[pP]assword:/] at 172.20.11.254
D, [2021-06-10T16:19:01.324099 #18767] DEBUG -- socket[f78]: sent 52 bytes
D, [2021-06-10T16:19:01.424432 #18767] DEBUG -- socket[f78]: read 432 bytes
D, [2021-06-10T16:19:01.424696 #18767] DEBUG -- socket[f78]: received packet nr 11 type 94 len 28
I, [2021-06-10T16:19:01.424837 #18767]  INFO -- net.ssh.connection.session[fdc]: channel_data: 0 1b
D, [2021-06-10T16:19:01.425038 #18767] DEBUG -- socket[f78]: received packet nr 12 type 94 len 28
I, [2021-06-10T16:19:01.425136 #18767]  INFO -- net.ssh.connection.session[fdc]: channel_data: 0 1b
D, [2021-06-10T16:19:01.425316 #18767] DEBUG -- socket[f78]: received packet nr 13 type 94 len 28
I, [2021-06-10T16:19:01.425427 #18767]  INFO -- net.ssh.connection.session[fdc]: channel_data: 0 1b
D, [2021-06-10T16:19:01.425606 #18767] DEBUG -- socket[f78]: received packet nr 14 type 94 len 28
I, [2021-06-10T16:19:01.425702 #18767]  INFO -- net.ssh.connection.session[fdc]: channel_data: 0 1b
D, [2021-06-10T16:19:01.425883 #18767] DEBUG -- socket[f78]: received packet nr 15 type 94 len 28
I, [2021-06-10T16:19:01.425979 #18767]  INFO -- net.ssh.connection.session[fdc]: channel_data: 0 1b
D, [2021-06-10T16:19:01.426245 #18767] DEBUG -- socket[f78]: received packet nr 16 type 94 len 28
I, [2021-06-10T16:19:01.426347 #18767]  INFO -- net.ssh.connection.session[fdc]: channel_data: 0 1b
D, [2021-06-10T16:19:01.426531 #18767] DEBUG -- socket[f78]: received packet nr 17 type 94 len 28
I, [2021-06-10T16:19:01.426628 #18767]  INFO -- net.ssh.connection.session[fdc]: channel_data: 0 2b
D, [2021-06-10T16:19:01.426829 #18767] DEBUG -- socket[f78]: received packet nr 18 type 94 len 44
I, [2021-06-10T16:19:01.426927 #18767]  INFO -- net.ssh.connection.session[fdc]: channel_data: 0 16b
D, [2021-06-10T16:19:01.577149 #18767] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
I, [2021-06-10T16:19:01.627463 #18767]  INFO -- net.ssh.connection.keepalive[1004]: sending keepalive 0
I, [2021-06-10T16:19:01.627579 #18767]  INFO -- net.ssh.connection.session[fdc]: sending global request keepalive@openssh.com
D, [2021-06-10T16:19:01.627823 #18767] DEBUG -- socket[f78]: queueing packet nr 12 type 80 len 44
D, [2021-06-10T16:19:01.828444 #18767] DEBUG -- socket[f78]: sent 68 bytes
D, [2021-06-10T16:19:01.928756 #18767] DEBUG -- socket[f78]: read 36 bytes
D, [2021-06-10T16:19:01.928985 #18767] DEBUG -- socket[f78]: received packet nr 19 type 82 len 12
I, [2021-06-10T16:19:01.929074 #18767]  INFO -- net.ssh.connection.session[fdc]: global request failure
D, [2021-06-10T16:19:01.929138 #18767] DEBUG -- net.ssh.connection.keepalive[1004]: keepalive response successful. Missed 0 keepalives
D, [2021-06-10T16:19:02.578444 #18767] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-06-10T16:19:03.579716 #18767] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-06-10T16:19:04.581072 #18767] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-06-10T16:19:05.582374 #18767] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-06-10T16:19:06.583645 #18767] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-06-10T16:19:07.584947 #18767] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-06-10T16:19:08.586205 #18767] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-06-10T16:19:09.587424 #18767] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-06-10T16:19:10.589178 #18767] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-06-10T16:19:11.590442 #18767] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-06-10T16:19:12.591750 #18767] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-06-10T16:19:13.592942 #18767] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-06-10T16:19:14.594263 #18767] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-06-10T16:19:15.595955 #18767] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-06-10T16:19:16.597209 #18767] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-06-10T16:19:17.598398 #18767] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-06-10T16:19:18.599663 #18767] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-06-10T16:19:19.600927 #18767] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-06-10T16:19:20.602340 #18767] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
W, [2021-06-10T16:19:21.124140 #18767]  WARN -- : 172.20.11.254 raised Timeout::Error with msg "execution expired"
D, [2021-06-10T16:19:21.124218 #18767] DEBUG -- : lib/oxidized/node.rb: Oxidized::SSH failed for 172.20.11.254
D, [2021-06-10T16:19:21.456651 #18767] DEBUG -- : lib/oxidized/input/cli.rb: Running post_login commands at 172.20.11.254
D, [2021-06-10T16:19:21.456738 #18767] DEBUG -- : lib/oxidized/input/cli.rb: Running post_login command: nil, block: #<Proc:0x00007fa4b40cfc28 /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/model/ios.rb:127> at 172.20.11.254
D, [2021-06-10T16:19:21.456895 #18767] DEBUG -- : Telnet: enable @172.20.11.254
D, [2021-06-10T16:19:21.603530 #18767] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-06-10T16:19:22.604706 #18767] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-06-10T16:19:23.605905 #18767] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-06-10T16:19:24.607124 #18767] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-06-10T16:19:25.608346 #18767] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-06-10T16:19:26.608911 #18767] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-06-10T16:19:27.609327 #18767] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-06-10T16:19:28.609620 #18767] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-06-10T16:19:29.609926 #18767] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-06-10T16:19:30.610233 #18767] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-06-10T16:19:31.610652 #18767] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-06-10T16:19:32.610929 #18767] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-06-10T16:19:33.611220 #18767] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-06-10T16:19:34.611532 #18767] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-06-10T16:19:35.611865 #18767] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-06-10T16:19:36.612167 #18767] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-06-10T16:19:37.612655 #18767] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-06-10T16:19:38.612959 #18767] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-06-10T16:19:39.613248 #18767] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-06-10T16:19:40.614284 #18767] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
W, [2021-06-10T16:19:41.478374 #18767]  WARN -- : 172.20.11.254 raised Net::ReadTimeout (rescued Timeout::Error) with msg "Net::ReadTimeout with "timed out while waiting for more data""
D, [2021-06-10T16:19:41.478465 #18767] DEBUG -- : lib/oxidized/node.rb: Oxidized::Telnet failed for 172.20.11.254
D, [2021-06-10T16:19:41.478566 #18767] DEBUG -- : lib/oxidized/job.rb: Config fetched for 172.20.11.254 at 2021-06-10 20:19:41 UTC
W, [2021-06-10T16:19:41.615708 #18767]  WARN -- : /172.20.11.254 status no_connection, retries exhausted, giving up
`

**Comment by mortzu** [comment]
Can you please reformat your paste to make it readable? (https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code)
