### ISSUE TITLE
Configuration updated, but no revisions..

### ISSUE THREAD

**Issue by bcookatpcsd** [ytti/oxidized#2325]
I'm new to Oxidized.. 

docker run -td --name oxidized -v /etc/oxidized:/root/.config/oxidized -p 8888:8888/tcp -t oxidized/oxidized:latest

docker logs oxidized | grep 10.120.4.5
I, [2021-06-17T19:08:37.096899 #97]  INFO -- : Configuration updated for /10.120.4.5
I, [2021-06-17T23:08:49.200262 #97]  INFO -- : Configuration updated for /10.120.4.5
I, [2021-06-18T03:09:00.313121 #97]  INFO -- : Configuration updated for /10.120.4.5
I, [2021-06-18T07:09:12.431005 #97]  INFO -- : Configuration updated for /10.120.4.5
I, [2021-06-18T11:09:23.606648 #97]  INFO -- : Configuration updated for /10.120.4.5
I, [2021-06-18T15:09:35.851014 #97]  INFO -- : Configuration updated for /10.120.4.5
I, [2021-06-18T19:09:47.961910 #97]  INFO -- : Configuration updated for /10.120.4.5
I, [2021-06-18T23:09:59.074560 #97]  INFO -- : Configuration updated for /10.120.4.5
I, [2021-06-19T03:10:10.195045 #97]  INFO -- : Configuration updated for /10.120.4.5
I, [2021-06-19T07:10:22.312804 #97]  INFO -- : Configuration updated for /10.120.4.5
I, [2021-06-19T11:10:34.426868 #97]  INFO -- : Configuration updated for /10.120.4.5
I, [2021-06-19T15:10:47.540175 #97]  INFO -- : Configuration updated for /10.120.4.5
I, [2021-06-19T19:10:58.655042 #97]  INFO -- : Configuration updated for /10.120.4.5
I, [2021-06-19T23:11:09.768999 #97]  INFO -- : Configuration updated for /10.120.4.5
I, [2021-06-20T03:11:22.877844 #97]  INFO -- : Configuration updated for /10.120.4.5
I, [2021-06-20T07:11:33.993388 #97]  INFO -- : Configuration updated for /10.120.4.5
I, [2021-06-20T11:11:45.107043 #97]  INFO -- : Configuration updated for /10.120.4.5
I, [2021-06-20T15:11:56.220843 #97]  INFO -- : Configuration updated for /10.120.4.5
I, [2021-06-20T19:12:08.328914 #97]  INFO -- : Configuration updated for /10.120.4.5
I, [2021-06-20T23:12:21.447199 #97]  INFO -- : Configuration updated for /10.120.4.5
I, [2021-06-21T03:12:31.564633 #97]  INFO -- : Configuration updated for /10.120.4.5
I, [2021-06-21T07:12:42.699185 #97]  INFO -- : Configuration updated for /10.120.4.5
I, [2021-06-21T11:12:54.814558 #97]  INFO -- : Configuration updated for /10.120.4.5
I, [2021-06-21T15:13:07.019361 #97]  INFO -- : Configuration updated for /10.120.4.5
I, [2021-06-21T19:13:19.215830 #97]  INFO -- : Configuration updated for /10.120.4.5
I, [2021-06-21T20:27:53.890910 #97]  INFO -- : Configuration updated for /10.120.4.5

but

:8888/node/version?node_full=10.120.4.5

shows zero previous configurations. 

Did I miss something? 

Thanks in advance.

**Comment by MrMarioMichel** [comment]
Do you have also added in the config that you want to save the configs into a repository ?

See more [here](https://github.com/ytti/oxidized/blob/master/docs/Outputs.md#output-git)

**Comment by mortzu** [comment]
No response -> closed
