### ISSUE TITLE
VSOL olt device

### ISSUE THREAD

**Issue by CharlyBote** [ytti/oxidized#2333]
HI all!
I'm trying to add a new device, but was I can't do it.
This device, has tree login instances, and I don't know what to do that.
I found this model (https://gist.github.com/mdpuma/0df4bc4fe6dd8d0aad6d0445902a9f63#file-vsololt-rb), but doesn't work for me.
This is the ssh output from putty.

ssh login

> 
ssh admin@xxx.xxx.xxx.xxx
admin@xxx.xxx.xxx.xxx's password:
Hello, this is gpon olt platform (version 1.00).
Copyright 2016-2028,All Rights Reserved.
User Access Verification
Entering character mode
Escape character is '^]'.
Login: admin
Password:
OLT> en
Password:
2021/05/19 15:53:19 User Login User admin logged in from xxx.xxx.xxx.xxx on vty
OLT#

And this is the oxidized debug.
my debbug

> 
D, [2021-05-19T15:26:20.933982 #54012] DEBUG -- : lib/oxidized/worker.rb: Added default/xxx.xxx.xxx.xxx to the job queue
D, [2021-05-19T15:26:20.934057 #54012] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-05-19T15:26:20.934014 #54012] DEBUG -- : lib/oxidized/job.rb: Starting fetching process for xxx.xxx.xxx.xxx at 2021-05-19 18:26:20 UTC
D, [2021-05-19T15:26:20.934141 #54012] DEBUG -- : lib/oxidized/input/ssh.rb: Connecting to xxx.xxx.xxx.xxx
D, [2021-05-19T15:26:20.934207 #54012] DEBUG -- : AUTH METHODS::["none", "publickey", "password"]
D, [2021-05-19T15:26:21.487078 #54012] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^([\w.@()-]+[#>]\s?)$/] at xxx.xxx.xxx.xxx
W, [2021-05-19T15:26:41.487479 #54012] WARN -- : xxx.xxx.xxx.xxx raised Oxidized::PromptUndetect with msg "
Hello, this is gpon olt platform (version 1.00).
Copyright 2016-2028,All Rights Reserved.
User Access Verification
Entering character mode
Escape character is '^]'.
Login: not matching configured prompt (?-mix:^([\w.@()-]+[#>]\s?)$)"
D, [2021-05-19T15:26:41.487525 #54012] DEBUG -- : lib/oxidized/node.rb: Oxidized::SSH failed for xxx.xxx.xxx.xxx
D, [2021-05-19T15:26:41.487546 #54012] DEBUG -- : lib/oxidized/job.rb: Config fetched for xxx.xxx.xxx.xxx at 2021-05-19 18:26:41 UTC
W, [2021-05-19T15:26:41.937564 #54012] WARN -- : default/xxx.xxx.xxx.xxx status no_connection, retry attempt 1

How can I fix that?

**Comment by deek-f** [comment]
maybe need to add the escape character into the code?  

[/^([\**^**\w.@()-]+[#>]\s?)$/] 

https://github.com/ytti/oxidized/blob/master/docs/Troubleshooting.md

Im only guessing here....
