### ISSUE TITLE
tftp input

### ISSUE THREAD

**Issue by Zyzto** [ytti/oxidized#2334]
I see that oxidized can use tftp and there's module but I can't find any documentation.

**Comment by MajesticFalcon** [comment]
An example can be seen on the alvarion.rb model
https://github.com/ytti/oxidized/blob/8179f48545d94a1c6b3a096153f70e9eabff1e20/lib/oxidized/model/alvarion.rb

**Comment by mortzu** [comment]
No response -> closed
