### ISSUE TITLE
Backup FortiOS managed by Fortiamanager

### ISSUE THREAD

**Issue by trif666** [ytti/oxidized#2338]
Hello everyone,

I've currently deployed Oxidized (docker install) feeded by LibreNMS

Everything works fine for almost equipments except for FW Fortigate because of a incorrect prompt due to the Fortimanager advertising.

Here is the logs for Fortigate FW :
```
W, [2021-07-30T09:34:02.553545 #27]  WARN -- : 10.204.252.16 raised Oxidized::PromptUndetect with msg "
POST WARNING : This FortiGate is currently managed by a FortiManager device.
All changes should be performed from a FortiManager to avoid conflict. How would you like to proceed?



 
(Press 'a' to accept): not matching configured prompt (?-mix:^([-\w.~]+(\s[(\w\-.)]+)?~?\s?[#>$]\s?)$)"
W, [2021-07-30T09:34:22.554484 #27]  WARN -- : 10.204.252.16 raised Net::OpenTimeout (rescued Timeout::Error) with msg "timed out while opening a connection to the host"
W, [2021-07-30T09:34:23.407444 #27]  WARN -- : /fortigate_1 status no_connection, retry attempt 1
```

I try to extend the existing model following the documentation (https://github.com/ytti/oxidized/blob/master/docs/Creating-Models.md#extending-an-existing-model-with-a-new-command) by modifying the prompt pattern with no success.

Is someone already encountered this problem ?
Have any idea of the good prompt pattern would match the message during connection to a Fortigate ?

Thanks to you ! :)

**Comment by drikusb** [comment]
just curious, what version is the FortiGate running?. We have a number of FortiManager managed devices, and whilst the GUI gives a popup about being managed by FortiManager, our SSH sessions doesn't have such a prompt.

**Comment by trif666** [comment]
Hello @drikusb,

Fortigate version is 6.4.5

It's strange because all of our Fortigate managed by the Fortimanager have this prompt confirmation : 
![image](https://user-images.githubusercontent.com/44122281/129863160-301b336c-d618-4274-8df9-4fcf120e8890.png)

For information, I've just solve my problem by adding this block to the current model (fortios.rb) : 
![image](https://user-images.githubusercontent.com/44122281/129863767-c46ce23b-8b1c-477a-a053-3bb736ee2cce.png)
