### ISSUE TITLE
Timezone

### ISSUE THREAD

**Issue by alangregory** [ytti/oxidized#234]
Add option to choose timezone.

**Comment by ytti** [comment]
I believe that timezone should be in presentation level, not earlier. Mainly because DST makes it awkward to find delta between dates.
Are you talking about git commit dates or what?

**Comment by alangregory** [comment]
Yes, at presetation level, like commit times, Last Update time

**Comment by ytti** [comment]
On oxidized-web? Because oxidized itself does not really do presentation. I think this makes sense in oxidized-web, I'm happy to accept PR, but it's not something I'm personally going to implement.

**Comment by supertylerc** [comment]
@alangregory if you're talking about [oxidized-web](https://github.com/ytti/oxidized-web), then there is a PR pending here: ytti/oxidized-web#51, which closes the similarly reported ytti/oxidized-web#16.

**Comment by ytti** [comment]
Closing as this is -web related, which has been fixed.
