### ISSUE TITLE
Backup problem Allied Telesis AT-8000GS/48 switch

### ISSUE THREAD

**Issue by wieczorr** [ytti/oxidized#2340]
Hello.

Request for help. I have a problem with the configuration backup Allied Telesis T-8000GS/48 switch. I usw "powerconnect" class.

**switch os version:**

AT-8000GS# show version 
SW version    2.0.0.27 ( date  21-Oct-2012 time  11:17:50 )
Boot version    2.0.0.1 ( date  14-Jan-2009 time  10:07:33 )
HW version    00.00.20

**ssh output when I connected to switch from linux**

[librenms@librenms oxidized]$ ssh manager@10.1.1.192

User Name:manager
Password:******

AT-8000GS# 

**debug output:**

I, [2021-08-01T15:25:01.512394 #517576]  INFO -- : Oxidized starting, running as pid 517576
I, [2021-08-01T15:25:01.513012 #517576]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
D, [2021-08-01T15:25:01.513135 #517576] DEBUG -- : resolving DNS for 10.1.1.192...
D, [2021-08-01T15:25:01.513164 #517576] DEBUG -- : IPADDR 
D, [2021-08-01T15:25:01.513222 #517576] DEBUG -- : node.rb: resolving node key 'model', with passed global value of '' and node value 'powerconnect'
D, [2021-08-01T15:25:01.513262 #517576] DEBUG -- : node.rb: setting node key 'model' to value 'fortigate' from global
D, [2021-08-01T15:25:01.513295 #517576] DEBUG -- : node.rb: returning node key 'model' with value 'powerconnect'
D, [2021-08-01T15:25:01.513314 #517576] DEBUG -- : lib/oxidized/node.rb: Loading model "powerconnect"
D, [2021-08-01T15:25:01.514057 #517576] DEBUG -- : lib/oxidized/model/model.rb Added all to the commands list
D, [2021-08-01T15:25:01.514099 #517576] DEBUG -- : lib/oxidized/model/model.rb Added secret to the commands list
D, [2021-08-01T15:25:01.514120 #517576] DEBUG -- : lib/oxidized/model/model.rb Added show version to the commands list
D, [2021-08-01T15:25:01.514136 #517576] DEBUG -- : lib/oxidized/model/model.rb Added show system to the commands list
D, [2021-08-01T15:25:01.514150 #517576] DEBUG -- : lib/oxidized/model/model.rb Added show running-config to the commands list
D, [2021-08-01T15:25:01.514363 #517576] DEBUG -- : node.rb: resolving node key 'input', with passed global value of 'ssh, telnet' and node value ''
D, [2021-08-01T15:25:01.514402 #517576] DEBUG -- : node.rb: returning node key 'input' with value 'ssh, telnet'
D, [2021-08-01T15:25:02.423824 #517576] DEBUG -- : node.rb: resolving node key 'output', with passed global value of 'git' and node value ''
D, [2021-08-01T15:25:02.423939 #517576] DEBUG -- : node.rb: returning node key 'output' with value 'git'
D, [2021-08-01T15:25:02.605995 #517576] DEBUG -- : node.rb: resolving node key 'username', with passed global value of '' and node value 'manager'
D, [2021-08-01T15:25:02.606091 #517576] DEBUG -- : node.rb: setting node key 'username' to value 'username' from global
D, [2021-08-01T15:25:02.606125 #517576] DEBUG -- : node.rb: returning node key 'username' with value 'manager'
D, [2021-08-01T15:25:02.606142 #517576] DEBUG -- : node.rb: resolving node key 'password', with passed global value of '' and node value 'password'
D, [2021-08-01T15:25:02.606160 #517576] DEBUG -- : node.rb: setting node key 'password' to value 'password' from global
D, [2021-08-01T15:25:02.606229 #517576] DEBUG -- : node.rb: returning node key 'password' with value 'password'
I, [2021-08-01T15:25:02.606320 #517576]  INFO -- : lib/oxidized/nodes.rb: Loaded 1 nodes
D, [2021-08-01T15:25:05.351231 #517576] DEBUG -- : lib/oxidized/core.rb: Starting the worker...
D, [2021-08-01T15:25:06.352346 #517576] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 0 of 1
D, [2021-08-01T15:25:06.353065 #517576] DEBUG -- : lib/oxidized/worker.rb: Added /10.1.1.192 to the job queue
D, [2021-08-01T15:25:06.353101 #517576] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-08-01T15:25:06.516067 #517576] DEBUG -- : lib/oxidized/job.rb: Starting fetching process for 10.1.1.192 at 2021-08-01 13:25:06 UTC
D, [2021-08-01T15:25:06.516246 #517576] DEBUG -- : lib/oxidized/input/ssh.rb: Connecting to 10.1.1.192
D, [2021-08-01T15:25:06.516368 #517576] DEBUG -- : AUTH METHODS::["none", "publickey", "password"]
D, [2021-08-01T15:25:07.353310 #517576] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-08-01T15:25:07.407875 #517576] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^([\w\s.@-]+(\(\S*\))?[#>]\s?)$/, /^User( Name)?:/, /^\r?Password:/] at 10.1.1.192
D, [2021-08-01T15:25:08.244434 #517576] DEBUG -- : lib/oxidized/input/ssh.rb manager @ 10.1.1.192 with expect: nil
D, [2021-08-01T15:25:08.244713 #517576] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^([\w\s.@-]+(\(\S*\))?[#>]\s?)$/, /^\r?Password:/] at 10.1.1.192
D, [2021-08-01T15:25:08.353511 #517576] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-08-01T15:25:08.666506 #517576] DEBUG -- : lib/oxidized/input/ssh.rb password @ 10.1.1.192 with expect: nil
D, [2021-08-01T15:25:08.666774 #517576] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^([\w\s.@-]+(\(\S*\))?[#>]\s?)$/] at 10.1.1.192
D, [2021-08-01T15:25:09.087346 #517576] DEBUG -- : lib/oxidized/input/cli.rb: Running post_login commands at 10.1.1.192
D, [2021-08-01T15:25:09.087435 #517576] DEBUG -- : lib/oxidized/input/cli.rb: Running post_login command: nil, block: #<Proc:0x00005639380a3490@/opt/librenms/.gem/ruby/gems/oxidized-0.28.0/lib/oxidized/model/powerconnect.rb:44> at 10.1.1.192
D, [2021-08-01T15:25:09.087481 #517576] DEBUG -- : lib/oxidized/input/ssh.rb enable @ 10.1.1.192 with expect: /[pP]assword:/
D, [2021-08-01T15:25:09.087686 #517576] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/[pP]assword:/] at 10.1.1.192
D, [2021-08-01T15:25:09.360661 #517576] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-08-01T15:25:10.361749 #517576] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-08-01T15:25:11.361944 #517576] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-08-01T15:25:12.365458 #517576] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-08-01T15:25:13.371134 #517576] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-08-01T15:25:14.373473 #517576] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-08-01T15:25:15.377477 #517576] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-08-01T15:25:16.378034 #517576] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-08-01T15:25:17.381792 #517576] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-08-01T15:25:18.382628 #517576] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-08-01T15:25:19.386384 #517576] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-08-01T15:25:20.387202 #517576] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-08-01T15:25:21.396391 #517576] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-08-01T15:25:22.396719 #517576] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-08-01T15:25:23.399213 #517576] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-08-01T15:25:24.405622 #517576] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-08-01T15:25:25.405939 #517576] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-08-01T15:25:26.415539 #517576] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-08-01T15:25:27.415814 #517576] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-08-01T15:25:28.416100 #517576] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
W, [2021-08-01T15:25:29.089458 #517576]  WARN -- : 10.1.1.192 raised Timeout::Error with msg "execution expired"
D, [2021-08-01T15:25:29.089578 #517576] DEBUG -- : lib/oxidized/node.rb: Oxidized::SSH failed for 10.1.1.192
D, [2021-08-01T15:25:29.184609 #517576] DEBUG -- : lib/oxidized/input/cli.rb: Running post_login commands at 10.1.1.192
D, [2021-08-01T15:25:29.184755 #517576] DEBUG -- : lib/oxidized/input/cli.rb: Running post_login command: nil, block: #<Proc:0x0000563937ba3328@/opt/librenms/.gem/ruby/gems/oxidized-0.28.0/lib/oxidized/model/powerconnect.rb:44> at 10.1.1.192
D, [2021-08-01T15:25:29.184810 #517576] DEBUG -- : Telnet: enable @10.1.1.192
D, [2021-08-01T15:25:29.416490 #517576] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-08-01T15:25:30.416856 #517576] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel

**router.db**

10.1.1.192:powerconnect:manager:password::22

**my oxidized config:**

username: username
password: password
model: fortigate
interval: 3600
use_syslog: false
debug: true
log: /opt/librenms/.config/oxidized/log
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 127.0.0.1:8888
next_adds_job: false
vars: {}
groups: {}
models: {}
pid: "/opt/librenms/.config/oxidized/pid"
input:
  default: ssh, telnet
  debug: false
  ssh:
    secure: false
output:
  default: git
  git:
    user: librensm
    subdirectories: true
    email: helpdesk@wp.pl
    repo: "/opt/librenms/.config/oxidized/git-repos/default.git"
  file:
    directory: "/opt/librenms/.config/oxidized/configs/"  
source:
  default: csv
  csv:
    file: "/opt/librenms/.config/oxidized/router.db"
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
      username: 2
      password: 3
      enable: 4
      ssh_port: 5
      group: 6
    vars_map:
      enable: 4
      ssh_port: 5
      comware_cmdline: 5
    gpg: false
model_map:
  cisco: ios
  juniper: junos
  huawei: vrp
  paloalto: panos
  ubiquiti: edgeos
  brocade: vyatta
  mikrotik: routeros
  fortigate: fortios
  fortinet: fortios
  vyatta: vyos
  vyos: vyatta
  Comware: comware
  AWPlus: awplus

Request for help.
Best regards
Lukasz

**Comment by mortzu** [comment]
Please edit your comment and format the paste (https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code)
