### ISSUE TITLE
Adding a new LibreNMS group to oxidized.

### ISSUE THREAD

**Issue by dymondog** [ytti/oxidized#2349]
One of my co-workers installed libreNMS with oxidized.  Some of our switches were not known to Oxidized so as a stop gap, I wrote a bash script to pull some of the the switch configs and load them into a separate repo for a new switch group.   Oxidize then served the configs and they can be viewed through LibreNMS.  I did not trouble with getting the diffs to work.

Later I wrote a .rb file that allows oxidized to pull the configs directly.  In debug mode I see ‘success’ in the log and complete files in the ~/.confi/oxidized/logs, but they are never loaded into their git repo.  I thought Oxidized might need to create the git repo, so I moved the old one to another directory to see if oxidized would create a new repo,  but it didn’t.  I didn’t set up oxidized for the other switches, and don’t see what I am missing.   All repos are named after the group they are assigned to in field 2.  I tried setting that value to another  group/repo  in hopes it would load into that working repo, but no luck  What am I missing?

**Comment by mortzu** [comment]
Please paste your config
