### ISSUE TITLE
logs written to rotated file instead of new file with logrotate

### ISSUE THREAD

**Issue by ghost** [ytti/oxidized#2351]
Hello all,

We've configured a logrotate.d file just like the one on the **extra** folder. 

```
 cat /etc/logrotate.d/oxidized 
/var/log/oxidized/oxidized.log {
    daily
    rotate 14
    size 10M
    compress
    delaycompress
}
```

Although a file is created, we still  see the logs being written to the old file:

```
ls -lh /var/log/oxidized/oxidized.log*
-rw-r--r-- 1 oxidized oxidized    0 Aug 27 00:00 /var/log/oxidized/oxidized.log
-rw-r--r-- 1 oxidized oxidized 3.6G Aug 27 10:11 /var/log/oxidized/oxidized.log.1
```

Does anyone else stumbled upon such issue? is there something missing on the logrotate config file or oxidized config file in order to this to work?

Thanks in advance

**Comment by mortzu** [comment]
You need to restart oxidized in logrotate, otherwise the file handle will still be open by the oxidized process and will point to the old file

**Comment by ronnyaa** [comment]
but when restarting oxidized. it starts on a long refresh of all hosts, not really nice  with a lot of devices. 
a  systemctl reload or HUP signal to kick in a new log file would be a nice thing.

**Comment by s66jones** [comment]
Love it when users open issues with valid problems and theyre closed with no resolution. Simple fix would be to add in something so it doesnt refresh the list of all host. Then you can restart the process whenever you need to, to reread the config file as another example.

**Comment by anubisg1** [comment]
i do have exactly the same issue here. what's the actual solution? restarting the process when you are backing up over 2 thousands hosts isn't feasible

**Comment by robertcheramy** [comment]
The automatic closing through github-actions has already been deactivated.

It remains a fact that oxidized is an open source software, and if no one steps in to implement a feature request, the issue will be closed by a maintainer.

In your case, have you tried sending a SIGHUP to oxidized? This should do exactly what you need:
https://github.com/ytti/oxidized/blob/711f3e7d50c5e04cbe3be7db50b4321ea19e5332/lib/oxidized/core.rb#L45

**Comment by anubisg1** [comment]
> The automatic closing through github-actions has already been deactivated.
> 
> It remains a fact that oxidized is an open source software, and if no one steps in to implement a feature request, the issue will be closed by a maintainer.
> 
> In your case, have you tried sending a SIGHUP to oxidized? This should do exactly what you need:
> 
> https://github.com/ytti/oxidized/blob/711f3e7d50c5e04cbe3be7db50b4321ea19e5332/lib/oxidized/core.rb#L45

no i haven't, i didn't even know this was possible as it's not documented AFAIK ... thank you, i will try this now
