### ISSUE TITLE
Unable to incorporate Continous Integration with Git hook 

### ISSUE THREAD

**Issue by MajesticFalcon** [ytti/oxidized#2354]
Oxidized seems to create a new repo and then fetch and merge. However, if you add a .gitlab-ci.yml fil to the repo, after oxidized does its second github push, it removes the file. 

Is there a way Rugged git can be used to not delete the gitlab-ci files?

**Comment by Nayruden** [comment]
This describes why you're seeing the behavior you're describing https://github.com/ytti/oxidized/issues/1805#issuecomment-904033732
