### ISSUE TITLE
Config file for enable mode on switch/router is not instinctive

### ISSUE THREAD

**Issue by annoyingKid59** [ytti/oxidized#2355]
Hi,

I tried to use oxidized, but it did not try to enable, so I could not have the switch running config. My config was:
vars: {}
enable: password

I managed to find the solution, and it worked when I write:
vars: {
enable: password
}

Is it possible to have basic config with enable inside brackets? 

Thank you for your excellent support job!

**Comment by mortzu** [comment]
Make a PR please
