### ISSUE TITLE
Can i move full device secription from config to router.db file (uth, os, etc)?

### ISSUE THREAD

**Issue by Vitus9856** [ytti/oxidized#2356]
Can i move full device secription from config to router.db file (uth, os, etc)?
Can i create config and router.db files for store all information about devices in router.db files
I mean 
---
#Core settings
pid: "/home/oxidized/.config/oxidized/pid"
crash:
    directory: "/home/oxidized/.config/oxidized/crashes"
    hostnames: true
#Run settings
use_syslog: false
debug: true
rest: 127.0.0.1:8888

#Client poll settings
resolve_dns: false
interval: 3600
threads: 1
timeout: 20
retries: 3

#Backup connect settings
#Allow low encription connection methods
auth_methods: [ “none”, “publickey”, “password”, “keyboard-interactive” ]
vars:
  ssh_encryption:
    - blowfish-cbc
    - 3des-cbc
  ssh_kex:
     - diffie-hellman-group1-sha
#Connection settings
input:
    default: ssh
    debug: true
    ssh:
        secure: false
    utf8_encoded: true
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/

#Backup client database
source:
  csv:
    file: "/home/oxidized/.config/oxidized/router.db"
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
      username: 2
      password: 3
      enable password: 4
      #auth_methods: [ "none", "publickey", "password", "keyboard-interactive" ]
      auth_methods: 5
      ssh_keys: 6
      ssh_kex: 7
      ssh_host_key: 8
      ssh_hmac: 9
      ssh_encryption: 10

model_map:
      CiscoASA: asa
      CiscoASA5506: firelinuxos
      cisco: ios
      juniper: junos
      extreme: xos
      fortigate: FortiOS
      FortiOS: fortigate

#Backup job result pro:cessing
remove_secret: false
output:
    default: file

#Backup repository settings
#output:
#  default: git
#  git:
#      user: Oxidized
#      email: oxidized@example.com
#      repo: "~/.config/oxidized/oxidized.git"

output:
     file:
           directory: ~/backup/

#Some staff

and  router.db

# name:model:username:password:enable:ssh_keys:ssh_kex:ssh_host_key:ssh_hmac:ssh_encryption:
#      name: 0
#      model: 1 [cisco: ios, juniper: junos, extreme: xos, fortigate: FortiOS]
#      username: 2
#      password: 3
#      enable password: 4
#      auth_methods: 5 [ "none", "publickey", "password", "keyboard-interactive" ]
#      ssh_keys: 6
#      ssh_kex: 7
#      ssh_host_key: 8
#      ssh_hmac: 9
#      ssh_encryption: 10
name:model:username:password:enable_password:auth_methods:etc, etc::::

**Comment by mortzu** [comment]
Please format your paste (https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code)
