### ISSUE TITLE
automatically read new devices without restart

### ISSUE THREAD

**Issue by chrisch80** [ytti/oxidized#2376]
Is it somehow possible if new devices are added that those devices are automatically added without restarting oxidized?

I know I could e.g. run a cron, but with restarting oxidized some information gets lost [#39](https://github.com/ytti/oxidized/issues/39)

Of course it would be generally good if this can be used for all type of changes: add/delete/change in the node list (mysql, router.db, whatever is used).

Thx

**Comment by feriniguez** [comment]
You can reload the node list like this:
curl -XGET http://127.0.0.1:9002/oxidized/reload

This can be done after you modify your database.
This doesn't restart the oxidized service, just load the new database.

**Comment by chrisch80** [comment]
thx
