### ISSUE TITLE
FTP input / ftp monitoring

### ISSUE THREAD

**Issue by meifi** [ytti/oxidized#2382]
Hi, 

is there any way to grab files from a ftp server? we've applications like 3CX, Sophos XG, Sophos UTM and store the backups on a ftp server like:

<ftpserverroot>
          <customerdevice1>
                  <backup1.zip>
                  <backup2.zip>
                  ...
          ....
          ....

so oxidized can check the creationdate and filesize of the last backup an archive them. or is there any other soulution?

**Comment by mortzu** [comment]
Try the FTP input: https://github.com/ytti/oxidized/blob/master/lib/oxidized/input/ftp.rb
