### ISSUE TITLE
Net::SSH::AuthenticationFailed with msg "Authentication failed for user

### ISSUE THREAD

**Issue by Jason-MK** [ytti/oxidized#2387]
Hello,

I have this template for Oxidized config

- [ ---
username: username
password: username
model: junos
resolve_dns: true
interval: 3600
use_syslog: false
debug: false
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 192.168.0.139:8888
next_adds_job: false
vars: {}
groups:
   defaultgrp:
     username: username
     password: username
   routeros:
     username: username
     password: username
     vars:
       ssh_port: 22
models: {}
pid: "/home/oxidized/.config/oxidized/pid"
crash:
  directory: "/home/oxidized/.config/oxidized/crashes"
  hostnames: false
stats:
  history_size: 10
input:
  default: ssh, telnet
  debug: false
  ssh:
    secure: false
  ftp:
    passive: true
  utf8_encoded: true
output:
  default: file
  file:
    directory: "/home/oxidized.config/oxidized/configs"
source:
  default: http
  debug: false
  http:
    url: http://192.168.0.158/api/v0/oxidized
    scheme: http
    file: "/home/oxidized/.config/oxidized/router.db"
    delimiter: !ruby/regexp /:/
    user: username
    pass: password
    map:
      name: hostname
      model: os
      username: username
      password: username
      group: group
    vars_map:
      ssh_port: ssh_port
    headers:
      X-Auth-Token: '6fc48b0036d8c750d6c0d7e90ba5225a'
model_map:
  juniper: junos
  cisco: ios
  mikrotik: routeros`
] 

But I receive this error

Net::SSH::AuthenticationFailed with msg "Authentication failed for user

I really need to know how to get it work ?

thanks in advance

Best Regards

**Comment by mortzu** [comment]
Please format your paste (https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code)
