### ISSUE TITLE
anyone uses Oxidized to backup Cisco Devices ?

### ISSUE THREAD

**Issue by Jason-MK** [ytti/oxidized#2388]
Hello,

I'm using this code to backup CSR from Cisco but I couldn't backup my CSR

---
username: username
password: password
model: junos
resolve_dns: true
interval: 3600
use_syslog: false
debug: false
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 192.168.0.139:8888
next_adds_job: false
vars: {}
groups:
   defaultgrp:
     username: username
     password: username
   routeros:
     username: username
     password: username
     vars:
       ssh_port: 22
models: {}
pid: "/home/oxidized/.config/oxidized/pid"
crash:
  directory: "/home/oxidized/.config/oxidized/crashes"
  hostnames: false
stats:
  history_size: 10
input:
  default: ssh, telnet
  debug: false
  ssh:
    secure: false
  ftp:
    passive: true
  utf8_encoded: true
output:
  default: git
  git:
      user: Oxidized
      email: oxidized@example.com
      repo: "~/.config/oxidized/oxidized.git"
source:
  default: http
  debug: false
  http:
    url: http://192.168.0.158/api/v0/oxidized
    scheme: http
    file: "/home/oxidized/.config/oxidized/router.db"
    delimiter: !ruby/regexp /:/
    user: username
    pass: username
    map:
      name: hostname
      model: os
      username: username
      password: username
      group: group
    vars_map:
      ssh_port: ssh_port
    headers:
      X-Auth-Token: '****************************************'
model_map:
  juniper: junos
  cisco: ios
  mikrotik: routeros
models:
  cisco:
    username: username
    password: password
Please can anyone help me in this problem ?

Best Regards

**Comment by mortzu** [comment]
no-feedback -> closed
