### ISSUE TITLE
oxidized with ssh proxy and telnet

### ISSUE THREAD

**Issue by joschi99** [ytti/oxidized#2389]
We are using oxidized through a ssh proxy (different jumphosts) to access switches on different sites. This is working very well as we are connecting to switches using SSH, but there are some network devices only with telnet access and at the moment we are not able to connect  to this switches:

oxidized -> SSH -> jumphost -> SSH -> Network device: OK
oxidized -> SSH -> jumphost -> telnet -> Network device: FAIL

Is there are way to do this?
#1235 seems similar case, but closed without any solution.

**Comment by mortzu** [comment]
somebody has to write this and make a PR

**Comment by lucdnb** [comment]
I have the same problem: https://github.com/ytti/oxidized/issues/2536
Unafortunelly, no solution yet.
