### ISSUE TITLE
Cisco 2950: Oxidized dont fetch running-config

### ISSUE THREAD

**Issue by Luke441** [ytti/oxidized#239]
Hello,
Problem occured only on Cisco 2950.
Oxidied fetch only show_version and show_inventory but without running-config.
On debug log everyfing looks fine.

On Cisco 2960 is OK.

Output file:
```
! Password:
! Cisco Internetwork Operating System Software
! IOS (tm) C2950 Software (C2950-I6Q4L2-M), Version 12.1(22)EA6, RELEASE SOFTWARE (fc1)
! Copyright (c) 1986-2005 by cisco Systems, Inc.
! Compiled Fri 21-Oct-05 01:59 by yenanh
! Image text-base: 0x80010000, data-base: 0x80568000
!
! ROM: Bootstrap program is C2950 boot loader
!
! <my_switch_name> uptime is 6 weeks, 14 hours, 19 minutes
! System returned to ROM by power-on
! System restarted at 23:41:43 CEST Wed Oct 7 2015
! System image file is "flash:/c2950-i6q4l2-mz.121-22.EA6.bin"
!
! cisco WS-C2950-24 (RC32300) processor (revision R0) with 21013K bytes of memory.
! Processor board ID FCZ1002Y0WB
! Last reset from system-reset
! Running Standard Image
! 24 FastEthernet/IEEE 802.3 interface(s)
!
! 32K bytes of flash-simulated non-volatile configuration memory.
! Base ethernet MAC Address: 00:16:C7:08:8A:80
! Motherboard assembly number: 73-5781-13
! Power supply part number: 34-0965-01
! Motherboard serial number: FOC09520J09
! Power supply serial number: DAB0934ER0D
! Model revision number: R0
! Motherboard revision number: A0
! Model number: WS-C2950-24
! System serial number: FCZ1002Y0WB
! Configuration register is 0xF
!
```

Telnet debug log:

```
Trying 10.57.222.68...
Connected to 10.57.222.68.


User Access Verification

Username: <my_user_name>
Password:

<my_switch_name>>terminal length 0
<my_switch_name>>terminal width 0
<my_switch_name>>enable
Password:
<my_switch_name>#show version
Cisco Internetwork Operating System Software
IOS (tm) C2950 Software (C2950-I6Q4L2-M), Version 12.1(22)EA6, RELEASE SOFTWARE (fc1)
Copyright (c) 1986-2005 by cisco Systems, Inc.
Compiled Fri 21-Oct-05 01:59 by yenanh
Image text-base: 0x80010000, data-base: 0x80568000

ROM: Bootstrap program is C2950 boot loader

<my_switch_name> uptime is 6 weeks, 14 hours, 19 minutes
System returned to ROM by power-on
System restarted at 23:41:43 CEST Wed Oct 7 2015
System image file is "flash:/c2950-i6q4l2-mz.121-22.EA6.bin"

cisco WS-C2950-24 (RC32300) processor (revision R0) with 21013K bytes of memory.
Processor board ID FCZ1002Y0WB
Last reset from system-reset
Running Standard Image
24 FastEthernet/IEEE 802.3 interface(s)

32K bytes of flash-simulated non-volatile configuration memory.
Base ethernet MAC Address: 00:16:C7:08:8A:80
Motherboard assembly number: 73-5781-13
Power supply part number: 34-0965-01
Motherboard serial number: FOC09520J09
Power supply serial number: DAB0934ER0D
Model revision number: R0
Motherboard revision number: A0
Model number: WS-C2950-24
System serial number: FCZ1002Y0WB
Configuration register is 0xF

<my_switch_name>#show inventory
NAME: "<my_switch_name>", DESCR: "Cisco Catalyst c2950 switch with 24 10/100 BaseTX ports"
PID: WS-C2950-24       , VID: R0 , SN: FCZ1002Y0WB


<my_switch_name>#show running-config
Building configuration...

Current configuration : 5349 bytes
!
! Last configuration change at 09:59:38 CET Fri Nov 13 2015 by ***
! NVRAM config last updated at 09:59:38 CET Fri Nov 13 2015 by ***
!
version 12.1
no service pad
service timestamps debug datetime msec localtime
service timestamps log datetime msec localtime
no service password-encryption
service sequence-numbers
!
hostname <my_switch_name>
.
.
Whole my config
.
.
!
end

<my_switch_name>#exit
```
ios.rb is default.
Do you have any suggestions?

**Comment by ytti** [comment]
That output looks all wrong. We should only get single line out of 'show version'. 

My immediate thought is, maybe prompt detection is broken, maybe MOTD or something hits prompt detection and it gets confused when output starts/ends.

If you're finding problems solving it, could I get access to the device, to try with my own Oxidized installation?

**Comment by brentnowak** [comment]
Confirming that I am seeing the same issue on the Cisco 2950 platform over telnet.

Cisco Internetwork Operating System Software 
IOS (tm) C2950 Software (C2950-I6K2L2Q4-M), Version 12.1(22)EA13, RELEASE SOFTWARE (fc2)

My telnet dubug is the same as Luke441.

**Comment by ytti** [comment]
Is it possible to put device online so I can reach it from predetermined IP address?

**Comment by brentnowak** [comment]
@ytti I'm afraid that I operate in a very controller environment so I can't do that.

As an experiment I commented out the 'cmd 'show version' do |cfg|' section in ios.r to see what would happen. I am no longer getting multiple lines recorded for the version command, but am rather getting all of the config marked as addition/removal every few poll intervals. One poll marks all of the config as new, then the next cycle removes it because it 'isn't there'. I really think the issue has to do with how telnet performs on the 2950 platform. 

I'm going to try to switch a test unit over to SSH to see what happens.

**Comment by ytti** [comment]
Fully understood that environment is closed. But if you have boxes, perhaps you have spare in storage that you could setup with completely different config and put it on the Internet, just to repro this issue?

**Comment by brentnowak** [comment]
Moving over to SSH (2.0) on the 2950's has solved the issue for me. We have an upcoming refresh to the 2960-X platform so I'm afraid that I don't want to spend any more time on the 2950 platform.

**Comment by ytti** [comment]
No problem, fully understood. I'll leave the bug open, with offer to fix if access is provided.

**Comment by Luke441** [comment]
Hi @ytti 
After upgrade from version 0.8 to 0.12.2 evertythink looks ok.
Now I can fech config from all of my switches by telnet.

**Comment by ytti** [comment]
Sweet, thanks!
