### ISSUE TITLE
Creating a Module for IPInfusion OcNOS

### ISSUE THREAD

**Issue by kvedder-amplex** [ytti/oxidized#2390]
Hi Folks,

I am trying to create a simple module for IPI's OcNOS that SSH's into the device and runs:

`enable`
`show running-configuration`.

my `ocnos.rb` file is this so far:

```
class ocnos < Oxidized::Model

 	cmd 'enable' do |cfg|
 		comment cfg
 	end
	
	cmd 'show running-config' do |cfg|
		comment "running config"
	end
```

my config is:
```
log: "/var/log/oxidized/oxidized.log"
debug: true
rest: 0.0.0.0:8888
timeout: 30
interval: 21600
input:
  debug: true
  default: ssh
  ssh:
    secure: false
model_map:
  ciena-sds: saos
  adtran-aos: adtran
  pmp: cambium
  ocnos: ocnos
source:
  default: csv
  csv:
    file: /etc/oxidized/ipi.db
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      ip: 1
      model: 2
output:
  default: git
  git:
    user: ###
    email: ###
    repo: ###
hooks:
  push_to_remote:
    type: githubrepo
    events: [post_store]
    remote_repo: ###
    publickey: ###
    privatekey: ###
  ocnos:
    username: ###
    password: ###
```

CSV for the DB is:
`device-dns:xxx.xxx.xxx:ocnos`

What do I need bare minimum to get this going?

**Comment by mortzu** [comment]
Can you create a PR with the model file please?

**Comment by ognjen011** [comment]
Has anyone got this to work? I am testing it out on a few ocnos devices and i am seeing Try `cmlsh --help' for more information, instead of running config.

**Comment by ognjen011** [comment]
@MheniMerz I have gotten as far as below:

class OcNos < Oxidized::Model
  comment '# '
  prompt /([\w.@-]+[#>]\s?)$/

  cfg :ssh do
    post_login 'terminal length 0'
    exec true
    pre_logout 'exit'
  end

  cmd 'show version' do |cfg|
    comment cfg
  end

  cmd 'show running-config' do |cfg|
    cfg
  end

end

But i cannot seem to force ssh connection it seems like i always end up in cmlsh  shell for those devices when i ssh through a script.

**Comment by nickhilliard** [comment]
just a thought: did you try disabling ssh exec channels?

```
vars:
  ssh_no_exec: true
```

**Comment by nickhilliard** [comment]
Can you try this and see if it works?

https://github.com/nickhilliard/oxidized/blob/master/lib/oxidized/model/ocnos.rb

ssh exec channels have been disabled.

**Comment by ognjen011** [comment]
@nickhilliard your solution seems to work i am able to get out of that weird shell and pull the config

**Comment by renadown** [comment]
_just commenting in case anyone encounters a similar issue._

i noticed that this model has a bug where, if a banner is configured to be displayed upon login, for some reason the ocnos.rb script is unable to save all the backup data. However, it still completes the task and reports that the backup was finished. When checking the backup settings, you can see that the backup is incomplete.

to resolve this bug, I removed the banner which contained:

`# SOMETHING ELSE #`
