### ISSUE TITLE
Last update "never"

### ISSUE THREAD

**Issue by leostereo** [ytti/oxidized#2392]
Hi guys  .... 
Just wanted to mention that my platform is working ok but:
When restarting oxidized , I can see some devices in blue color with "never" status for last update.
It is strange since after some ramdom time it goes green and config is available.
Other strange thing is that  oxidized ssh login attempts are every 5-10 minutes while I set interval = 3600.
So:
What is happening? 
Why ssh logins does not accurs every 3600 according interval value ?
Why my devices still in blue color evethough I can confirm the login is ok on tarjet device ?

Im running oxidized on centos 7 fresh server (I can change if needed)

Regards.
Leandro.

**Comment by davama** [comment]
Its running in mem so until oxidized tries to pull config again will the box change color

if you update the source then a reload of the oxidized service is not necessary but you can cal the api and simply reload config.

**Comment by leostereo** [comment]
Hi @davama ; Mi concern is I have 3 of 30 devices with "never" as last update after two days I launched oxidized.
When looking at the logs I can see that for success updates , there is a:
`Oxidized::SSH ran for [device name] successfully`
Line,  but for those device that never finishes updating , have following lines:
```
D, [2021-11-04T18:26:06.872092 #5858] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 0 of 1
D, [2021-11-04T18:26:06.872417 #5858] DEBUG -- : lib/oxidized/worker.rb: Added wiber_ros/12 to the job queue
D, [2021-11-04T18:26:06.872454 #5858] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2021-11-04T18:26:06.872639 #5858] DEBUG -- : lib/oxidized/job.rb: Starting fetching process for 12 at 2021-11-04 18:26:06 UTC
D, [2021-11-04T18:26:06.872925 #5858] DEBUG -- : lib/oxidized/input/ssh.rb: Connecting to 12
D, [2021-11-04T18:26:06.873107 #5858] DEBUG -- : AUTH METHODS::["none", "publickey", "password"]
D, [2021-11-04T18:26:07.017008 #5858] DEBUG -- : lib/oxidized/input/cli.rb: Running post_login commands at 12
D, [2021-11-04T18:26:07.017136 #5858] DEBUG -- : lib/oxidized/model/model.rb Collecting commands' outputs
D, [2021-11-04T18:26:07.017289 #5858] DEBUG -- : lib/oxidized/model/model.rb Executing /system routerboard print without-paging
D, [2021-11-04T18:26:07.017345 #5858] DEBUG -- : lib/oxidized/input/ssh.rb /system routerboard print without-paging @ 12 with expect: /\[\w+@\S+(\s+\S+)*\]\s?>\s?$/
D, [2021-11-04T18:26:07.025550 #5858] DEBUG -- : lib/oxidized/model/model.rb Executing /system package update print without-paging
D, [2021-11-04T18:26:07.025644 #5858] DEBUG -- : lib/oxidized/input/ssh.rb /system package update print without-paging @ 12 with expect: /\[\w+@\S+(\s+\S+)*\]\s?>\s?$/
D, [2021-11-04T18:26:07.069208 #5858] DEBUG -- : lib/oxidized/model/model.rb Executing /system history print without-paging
D, [2021-11-04T18:26:07.069308 #5858] DEBUG -- : lib/oxidized/input/ssh.rb /system history print without-paging @ 12 with expect: /\[\w+@\S+(\s+\S+)*\]\s?>\s?$/
D, [2021-11-04T18:26:07.160068 #5858] DEBUG -- : lib/oxidized/model/model.rb Executing /export
D, [2021-11-04T18:26:07.160161 #5858] DEBUG -- : lib/oxidized/input/ssh.rb /export @ 12 with expect: /\[\w+@\S+(\s+\S+)*\]\s?>\s?$/
```
I can also confirm that oxidized is loggin in/out on the tarjet logs.
So question is, why is not sucesfully updating those devices ? 
Is there other place / way to debug this ? 

Regards.

**Comment by leostereo** [comment]
Hi .... after some analisis I discovered that my mikortik router does not return promt after executing /export command.
That is the problem.
So , i need to check why is this happening.
Thanks for the support.
