### ISSUE TITLE
Wrong gem version dependencies?

### ISSUE THREAD

**Issue by alzhur** [ytti/oxidized#2396]
Ubuntu 20.04.3 LTS
```
gem install oxidized
gem install oxidized-script
gem install oxidized-web
```
First command installed oxidized 0.28.0 -ok.
Second (or third?) one also installed oxidized 0.26.3 - not ok.
And now:

```
user@hostname:~$ gem list oxidized

*** LOCAL GEMS ***

oxidized (0.28.0, 0.26.3)
oxidized-script (0.6.0)
oxidized-web (0.13.1)
```

**Comment by sajiby3k** [comment]
If you are a developer, you can make a pull to modify oxidized-script package so that it can use new slop ruby package. The oxidized-script uses old slop version. That is the problem.

**Comment by mortzu** [comment]
It is fixed in master, but not released
