### ISSUE TITLE
Squash / rebase old commits

### ISSUE THREAD

**Issue by oidz1234** [ytti/oxidized#2397]
Hello,

Is there a way to merge/squash all commits older then X date? I have tried using git rebase -i however due to the amount of commits I have (~30k) this constantly crashes. 

The reason I want to do this is because the repo takes so long to browse due to high amount of commits. I appreciate that I may be barking up the wrong tree here, let me know if this is more of a "me" problem. Thanks!

**Comment by davama** [comment]
Not a git expert here... but someone posted a how to "purge" old data from a repo. Not sure if what you are looking for but perhaps a start

I would probably stop oxidized will this is happening or make a dummy source db. Either-way, i wouldnt want for oxidized to try to update while making changes.

**Comment by chasgames** [comment]
Found it! https://github.com/ytti/oxidized/issues/1123#issuecomment-408849281

Try that oidz, let us know if it solves your issues

**Comment by davama** [comment]
@oidz1234 close this ticket pls
