### ISSUE TITLE
Use SSH jumpbox

### ISSUE THREAD

**Issue by etern4ever** [ytti/oxidized#240]
Just a Feature Request.

Would be nice to have the available to use an SSH jumpbox.  So basically, have oxidized log into a jumpbox, then from there ssh to the device in question.

I am sure I could make something work with a custom model.  But something built in would be nice.

**Comment by ytti** [comment]
Yeah I've had this request before. Essentially we'd need to look into SSH proxy configs, it is doable and seems important, but not something I intend to commit time any time soon.

**Comment by mkbt** [comment]
@etern4ever if you happen to be using Junos OS for this problem I am told there is reverse SSH access available if needed.

**Comment by ytti** [comment]
I think this is now possible via SSH proxy
https://github.com/ytti/oxidized/commit/b466a30f45c9571d8f1871c1c2f4ab9255eaf0b6

**Comment by ytti** [comment]
Closing as this can be now done.
