### ISSUE TITLE
Extending the gaiaos model

### ISSUE THREAD

**Issue by Alcap** [ytti/oxidized#2400]
Hi,

I'm looking into extendending the gaiaos model, to enable support for virtual systems (VSX). In a checkpoint gateway enabled for VSX, when you do 'show configuration' you are only displaying the configuration for VS0, which is the management VS and doesn't have the configuration of each individual VS (the ones actively passing traffic). To display the configuration of these, you need to jump into the individual VS context and run show configuration again.

This seems simple enough to achieve: I need to run one command (show virtual-system all) and then loop through these in order to run 'show configuration'.

Example of show virtual-system all:
gandalf:0> show virtual-system all
Virtual systems list
VS ID       VS NAME
0           0
1           gandalf_frodo
2           gandalf_sam
3           gandalf_merry
4           gandalf_pippin
5           gandalf_bilbo

To go about this, one would have to run the command 'set virtual-system 1', run show configuration and then continue on to do another set virtual-system 2 and so forth.

Are there any types of constructs that might be able to help me with this? Can I use regular arrays and for loops inside the models? I looked in the other modules but couldn't find one that would have a similar behaviour. If you know of one, please let me know so I can take a look at it.

**Comment by rwxd** [comment]
Hey, I published the merge request #2501 which adds the virtual system feature.
