### ISSUE TITLE
Output for Power Usage has changed in FabricOS

### ISSUE THREAD

**Issue by suom1** [ytti/oxidized#2402]
In FabricOS v8 (could be earlier) and newer the output for power usage has changed to `Power Usage:` instead of `Power Usage (Watts):`.

There are two PR's already submitted (I submitted one also before even checking) that will fix this problem. 
I have the change applied and verified working on FabricOS v8 and v9 devices (8.2.2b & 9.0.1b4).

Both #2399 and #2393 fixes this issue if merged!

**Comment by supermanchw** [comment]
i commit one , and  dont know why merge failed  !  i also see many PRs for fixing  model  problem  and failed too . this project owner have left this ?

**Comment by mortzu** [comment]
Fixed in #2393
