### ISSUE TITLE
An error with oxidized

### ISSUE THREAD

**Issue by Jason-MK** [ytti/oxidized#2405]
Hello,

I receive this error when I try to update a Cisco router

W, [2021-11-19T15:01:54.345018 #15321]  WARN -- : 192.168.62.11 raised Timeout::Error with msg "execution expired"
W, [2021-11-19T15:01:55.044232 #15321]  WARN -- : /192.168.62.11 status no_connection, retry attempt 1
W, [2021-11-19T15:02:18.355145 #15321]  WARN -- : 192.168.62.11 raised Timeout::Error with msg "execution expired"
W, [2021-11-19T15:02:19.048856 #15321]  WARN -- : /192.168.62.11 status no_connection, retry attempt 2
W, [2021-11-19T15:02:42.355197 #15321]  WARN -- : 192.168.62.11 raised Timeout::Error with msg "execution expired"
W, [2021-11-19T15:02:43.052984 #15321]  WARN -- : /192.168.62.11 status no_connection, retry attempt 3
W, [2021-11-19T15:03:06.555660 #15321]  WARN -- : 192.168.62.11 raised Timeout::Error with msg "execution expired"
W, [2021-11-19T15:03:07.057108 #15321]  WARN -- : /192.168.62.11 status no_connection, retries exhausted, giving up
I need to know what is the problem ? and How I can check what is happening ? I mean which command should to use ?

The Config file

username: test
password: test
model: junos
resolve_dns: true
interval: 3600
log: ~/.config/oxidized/log
use_syslog: false
debug: false
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
vars:
  enable: test
groups: {}
rest: 192.168.55.111:8888
input:
  default: ssh, telnet
  debug: false
  ssh:
    secure: false
output:
  default: git
  git:
      user: Oxidized
      email: oxidized@example.com
      repo: "~/.config/oxidized/oxidized.git"
source:
  default: http
  debug: false
  http:
    url: http://192.168.55.112/api/v0/oxidized
    scheme: http
    file: "/home/oxidized/.config/oxidized/router.db"
    delimiter: !ruby/regexp /:/
    map:
      name: hostname
      model: os
      username: username
      password: password
    var_map:
       enable: 4
    headers:
      X-Auth-Token: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
model_map:
  Vyatta: Vyatta
  cisco: ios
  mikrotik: routeros

Best Regards

**Comment by smart2128** [comment]
Hi Jason,
which distribution did you use for the installation?
Your subject was a bit generic and I skipped it on search, so I created a similar issue.

https://github.com/ytti/oxidized/issues/2416

Regards,
Vincenzo

**Comment by JMNSTYLZ** [comment]
Try to set the timeout to 120+

**Comment by mortzu** [comment]
Please paste the configuration file in a readable format (https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code)

**Comment by Senetus** [comment]
Plain and simple, host is not responding. Try to ssh to it directly from the same machine you run oxidized on and see if that works.
