### ISSUE TITLE
How to trigger a backup ?

### ISSUE THREAD

**Issue by Jason-MK** [ytti/oxidized#2407]
Hello I want to ask if I want to have an automatic backup once someone do something on the network devices ? 

how to do that ?

**Comment by davama** [comment]
Sorry your description was unclear 

but you can call the api to tell oxidized to go "now" and pull a backup.

I think it’s documented or you can search the issues here

**Comment by supermanchw** [comment]
you can use syslog trigger to backup on cisco or juniper ------from  readme

**Comment by mortzu** [comment]
Can I close this Issue?
