### ISSUE TITLE
Mikrotik RouterOS additional lines

### ISSUE THREAD

**Issue by srekkas** [ytti/oxidized#2408]
Hello,

I backup several mikrotik routers 6.46.5

Backup have additional lines and its triggering versioning.
I found that you can write models which can exclude it, but Ruby and regex is hard for me:)

```
#   ACTION                                   BY               POLICY             
# U item changed                             admin            write              
# U item changed                             admin            write              
# U item changed                             admin            write   
# U filter rule changed                      sysadm2          write              
# U filter rule changed                      sysadm2          write              
# U item changed                             admin            write              
# U item changed                             admin            write  
```

**Comment by davama** [comment]
What did you try?

**Comment by srekkas** [comment]
I looked at some issues, like _exclude some lines from backup#2247_

I think i need to create model file with only modifications, not all model, but looking at stock routeros.rb 
i don;t know where to start, because is different from JunOS example a bit.

**Comment by davama** [comment]
Did a quick search on Issues and found this link: https://github.com/ytti/oxidized/issues/2247
Look there.
Let us know if have any questions

**Comment by davama** [comment]
Ah just realized thats the same issue you posted

**Comment by davama** [comment]
Ok, created a folder in the HOME of the user running oxidized 

~/.config/oxidized/model or models dont recall but put your edits there.

name the file the same name as your model you are sourcing from.
Play around let us know

**Comment by srekkas** [comment]
I think I put all model and try to edit, after that if successful try put only modifications.

Thanks.

**Comment by davama** [comment]
Perfect!

**Comment by davama** [comment]
Here's a sample of how our ios extended model looks like. 
The `require 'oxidized/model/ios.rb'` is the stock ios.rb model.
 
Hope that helps you 

> cat ~/.config/oxidized/model/ios.rb 
```
require 'oxidized/model/ios.rb'

class IOS < Oxidized::Model
  prompt /^\r?(\w+\-\w+\-\w+\-*(?i)(ap|rtr|sw|olt)\-\d+[#>]\s?)$/
  
  cmd :secret, clear: true do |cfg|
    cfg.gsub! /^(snmp-server community) \S+ (.*)/, '\\1 <redacted> \\2'
    cfg.gsub! /^(username (\S+) privilege (\d+) (\S+) (\d+)).*/, '\\1 <redacted>'
    cfg.gsub! /^(radius-server key).*/, '\\1 <redacted>'
    cfg.gsub! /(pre-shared-key (\S+) (\d+)).*/, '\\1 <redacted>'
    # used for the dir cmd output
    cfg.gsub! /(^\s+|^)\d+(\s+\S+\s+\d+)\s+.*(\s+(\W+\S+$))/, '\\2 \\3'
    cfg
  end

  # currently used to audit wifi firmware upgrades
  pre do
    cmd "dir | exclude vars|event|config|lost|private|free" do |cfg|
      comment cfg
    end
  end
  # Used to periodically audit the AP Channel Assignments and co-channeling
  pre do
    cmd "sh contro do1 | incl Configured Frequency" do |cfg| 
      comment cfg
    end
  end
  pre do
    cmd "sh contro do0 | incl Configured Frequency" do |cfg|
      comment cfg
    end
  end

end
```

**Comment by srekkas** [comment]
Stupid me, I just commented

#  cmd '/system history print without-paging' do |cfg|
#    comment cfg
#  end

And first config is good, now I wait for versioning to kick in to confirm that no more unnecessary lines.

**Comment by davama** [comment]
you can put your device to the top of your queue by calling the API and tell oxidized to pull config now
```
curl -X GET http://localhost:9000/node/next/$GROUP/$HOST
```
we have groups so you can remove that if you dont

**Comment by srekkas** [comment]
Thanks but I just pressed reload on web console next to host.

https://oxidized.**domain**.com/oxidized/node/next/**group**/**name**

**Comment by srekkas** [comment]
Thanks, everythink ok.

**Comment by netravnen** [comment]
> Stupid me, I just commented
> 
> ```
> #  cmd '/system history print without-paging' do |cfg|
> #    comment cfg
> #  end
> ```
> 
> And first config is good, now I wait for versioning to kick in to confirm that no more unnecessary lines.

Better yet, [Monkey-patching blocks in existing models](https://github.com/ytti/oxidized/blob/master/docs/Creating-Models.md#monkey-patching-blocks-in-existing-models), clear the _initial_ output using `clear: true` and omit emitting the result of the command to the versioned output.

```rb
# $OXIDIZED_HOME/model/routeros.rb

require 'oxidized/model/routeros.rb'

class RouterOS < Oxidized::Model
  using Refinements

  cmd '/system history print without-paging', clear: true do |cfg|
    # Skip this command
  end

end
```
