### ISSUE TITLE
Oxidized Installation issue in Redhat Linux 8.5

### ISSUE THREAD

**Issue by nasir-reza** [ytti/oxidized#2410]
Hello Team,
I am trying to install Oxidized on Redhat Linux 8.5 . However i am getting following error while i provide "gem install oxidized" :
########## Error Message ################
Building native extensions. This could take a while...
ERROR:  Error installing oxidized:
        ERROR: Failed to build gem native extension.

    current directory: /usr/local/share/gems/gems/bcrypt_pbkdf-1.1.0/ext/mri
/usr/bin/ruby -r ./siteconf20211129-74528-gedpiz.rb extconf.rb
creating Makefile

current directory: /usr/local/share/gems/gems/bcrypt_pbkdf-1.1.0/ext/mri
make "DESTDIR=" clean
rm -f
rm -f bcrypt_pbkdf_ext.so  *.o  *.bak mkmf.log .*.time

current directory: /usr/local/share/gems/gems/bcrypt_pbkdf-1.1.0/ext/mri
make "DESTDIR="
gcc -I. -I/usr/include -I/usr/include/ruby/backward -I/usr/include -I.   -fPIC -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC -m64 -o bcrypt_pbkdf.o -c bcrypt_pbkdf.c
gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory
make: *** [Makefile:243: bcrypt_pbkdf.o] Error 1

make failed, exit code 2

Gem files will remain installed in /usr/local/share/gems/gems/bcrypt_pbkdf-1.1.0 for inspection.
Results logged to /usr/local/lib64/gems/ruby/bcrypt_pbkdf-1.1.0/gem_make.out

##########################

Requesting your kind help to resolve the issue.

**Comment by mortzu** [comment]
Can you try this?
Install `redhat-rpm-config`

$ sudo dnf install redhat-rpm-config

**Comment by nasir-reza** [comment]
> Can you try this? Install `redhat-rpm-config`
> 
> $ sudo dnf install redhat-rpm-config

######## Reply ##########
Hello mortzu,
Thanks according to your suggestion, i have installed the package and i installed the oxidized with the gem successfully.

However, when i am running the oxidized command, i am getting following error : 

I, [2021-12-02T12:56:09.310762 #90943]  INFO -- : Oxidized starting, running as pid 90943
I, [2021-12-02T12:56:09.311281 #90943]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
F, [2021-12-02T12:56:09.311514 #90943] FATAL -- : Oxidized crashed, crashfile written in /root/.config/oxidized/crash
cannot interpret as DNS name: nil
#############################
Please find my gray log conf file and router.db file as following:
########### Conf #################
---
username: username
password: password
model: ios
resolve_dns: true
interval: 3600
use_syslog: false
debug: false
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 127.0.0.1:8888
next_adds_job: false
vars: {}
groups: {}
models: {}
pid: "/root/.config/oxidized/pid"
crash:
  directory: "/root/.config/oxidized/crashes"
  hostnames: false
stats:
  history_size: 10
input:
  default: ssh, telnet
  debug: false
  ssh:
    secure: false
  ftp:
    passive: true
  utf8_encoded: true
output:
  default: file
  file:
    directory: ~/.config/oxidized/configs
source:
  default: csv
  csv:
    file: ~/.config/oxidized/router.db
    delimiter: !ruby/regexp /:/
model_map:
  juniper: junos
  cisco: ios
  cisco: asa
  cisco: iosxr
  cisco: nxos
  cisco: FireLinuxOS

######### router.db ########
NGD-DC2-OOB-AGGR-SW-01:ios

####################
 I have put local dns entry for this node. Checked the DNS resolution for this entry which is working fine. Please find the crash file output as following:

########## Crash file output #########
--------------------------------------------------
2021-12-02 07:02:32 UTC
cannot interpret as DNS name: nil [ArgumentError]
--------------------------------------------------
/usr/share/ruby/resolv.rb:1256:in `create'
/usr/share/ruby/resolv.rb:1096:in `generate_candidates'
/usr/share/ruby/resolv.rb:1125:in `resolv'
/usr/share/ruby/resolv.rb:519:in `fetch_resource'
/usr/share/ruby/resolv.rb:509:in `each_resource'
/usr/share/ruby/resolv.rb:406:in `each_address'
/usr/share/ruby/resolv.rb:116:in `block in each_address'
/usr/share/ruby/resolv.rb:115:in `each'
/usr/share/ruby/resolv.rb:115:in `each_address'
/usr/share/ruby/resolv.rb:93:in `getaddress'
/usr/local/share/gems/gems/oxidized-0.28.0/lib/oxidized/node.rb:19:in `initialize'
/usr/local/share/gems/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:21:in `new'
/usr/local/share/gems/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:21:in `block (2 levels) in load'
/usr/local/share/gems/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:16:in `each'
/usr/local/share/gems/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:16:in `block in load'
/usr/local/share/gems/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:130:in `synchronize'
/usr/local/share/gems/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:130:in `with_lock'
/usr/local/share/gems/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:10:in `load'
/usr/local/share/gems/gems/oxidized-0.28.0/lib/oxidized/nodes.rb:125:in `initialize'
/usr/local/share/gems/gems/oxidized-0.28.0/lib/oxidized/core.rb:14:in `new'
/usr/local/share/gems/gems/oxidized-0.28.0/lib/oxidized/core.rb:14:in `initialize'
/usr/local/share/gems/gems/oxidized-0.28.0/lib/oxidized/core.rb:4:in `new'
/usr/local/share/gems/gems/oxidized-0.28.0/lib/oxidized/core.rb:4:in `new'
/usr/local/share/gems/gems/oxidized-0.28.0/lib/oxidized/cli.rb:13:in `run'
/usr/local/share/gems/gems/oxidized-0.28.0/bin/oxidized:8:in `<top (required)>'
/usr/local/bin/oxidized:23:in `load'
/usr/local/bin/oxidized:23:in `<main>'
--------------------------------------------------

**Comment by mortzu** [comment]
Can you please format the pastes? Its absolutely unreadable...

**Comment by nasir-reza** [comment]
> Can you please format the pastes? Its absolutely unreadable...

Hello mortzu,
Thanks for your prompt reply. I have attached those output in text file accordingly. 

[Attachment1.txt](https://github.com/ytti/oxidized/files/7640956/Attachment1.txt)

**Comment by mortzu** [comment]
I think you forgot the map at the CSV source: https://github.com/ytti/oxidized/blob/master/docs/Sources.md

**Comment by nasir-reza** [comment]
> I think you forgot the map at the CSV source: https://github.com/ytti/oxidized/blob/master/docs/Sources.md

Hi mortzu,
Thanks. I thought that was not necessary. I will add the mapping and check again. Thanks a lot for your kind help

**Comment by nasir-reza** [comment]
Thanks a lot mortzu. Now the oxidized server is up and running. :)
