### ISSUE TITLE
Prompt issue with Dell OS10

### ISSUE THREAD

**Issue by davromaniak** [ytti/oxidized#2419]
Hi.

I recently added some switches running Dell/EMC OS10 and even when disabling the banner/motd stuff, I still get garbage that makes oxidized unable to match the prompt :

```
Dec  3 11:18:52 oxidsrv oxidized[3534621]: W, [2021-12-03T11:18:52.590096 #3534621]  WARN -- : 10.xxx.xxx.xxx raised Oxidized::PromptUndetect with msg "Linux dellsw001 4.9.210 #1 SMP Debian 4.9.210-1+deb9u1 x86_64
Dec  3 11:18:52 oxidsrv oxidized[3534621]: dellsw001#  not matching configured prompt !ruby/regexp /^([\w.@-]+[#>]\s?)$/"
Dec  3 11:18:53 oxidsrv oxidized[3534621]: W, [2021-12-03T11:18:53.057067 #3534621]  WARN -- : dellsw001 status no_connection, retry attempt 1
Dec  3 11:19:29 oxidsrv oxidized[3534621]: W, [2021-12-03T11:19:29.603559 #3534621]  WARN -- : 10.xxx.xxx.xxx raised Oxidized::PromptUndetect with msg "Linux dellsw001 4.9.210 #1 SMP Debian 4.9.210-1+deb9u1 x86_64
Dec  3 11:19:29 oxidsrv oxidized[3534621]: dellsw001#  not matching configured prompt !ruby/regexp /^([\w.@-]+[#>]\s?)$/"
Dec  3 11:19:30 oxidsrv oxidized[3534621]: W, [2021-12-03T11:19:30.065603 #3534621]  WARN -- : dellsw001 status no_connection, retry attempt 2
```

When I try to login with the backup user (called librenms in my case), I get the "Linux" line first, and a few seconds later, I get the actual prompt.

```
$ ssh librenms@10.xxx.xxx.xxx
librenms@10.xxx.xxx.xxx's password:
Linux dellsw001 4.9.210 #1 SMP Debian 4.9.210-1+deb9u1 x86_64
dellsw001#
```

Oxidized seems to be bothered by this first line and I can't find any way to remove it on the switch side.

Does anybody has any idea how I can "fix" this on the Oxidized side ?

Thanks a lot.

**Comment by davromaniak** [comment]
I was able to fix it by monkey patching the os10 class, but it's very very dirty as I went to the simplest regex for a prompt

```
require 'oxidized/model/os10.rb'
class OS10 < Oxidized::Model
        def prompt
                @prompt = /([#>]\s?)$/
        end
end
```

I'm sure I will be able fix it more reliably and cleanly, but it's good for a Friday afternoon.

Thanks.

**Comment by mortzu** [comment]
I this fixed by the merge or is this another issue?

**Comment by davromaniak** [comment]
Hi.

No, this PR doesn't fix this issue.

I thought adding this info in the doc, with something like "In case you have an issue with the prompt, create a file named ~/.config/oxidized/model/os10.rb with the following content" because I can't figure out if the issue comes from my configuration or it's an actual issue with the latest stable OS10 release.

What do you think ?

Thanks.

**Comment by ySp-chld** [comment]
If you come here with this issue, here's what fixed it for us: 
create file `~/.config/oxidized/model/os10.rb`   with content: 

```
require 'oxidized/model/os10.rb'
class OS10 < Oxidized::Model
        def prompt
                @prompt = /^(.+[#>]\s?)$/
        end
end
```
