### ISSUE TITLE
output to git issue 

### ISSUE THREAD

**Issue by Souheib-khiter** [ytti/oxidized#2421]
Hello

At the first time i used file like an output and it worked great , so need to save the both configiration when changed.
i switch the output to git i dont dont have any problem when the prosses tour but i can't find my configuration file 

here you are my config file :

username: username
password: password
model: ios
..
input:
  default: ssh, telnet
  debug: true
  ssh:
    secure: false
  ftp:
    passive: true
  utf8_encoded: true
output:
  default: git
  git:
    user: Oxidized
    email: o@example.com
    repo: "/home/oxidized/.config/oxidized/oxidized.git"

....
and here the resultat

D, [2021-12-06T17:01:29.179900 #27636] DEBUG -- net.ssh.connection.session[2abd6f8aaeec]: stream was closed after loop => shallowing exception so it will be re-raised in next loop
D, [2021-12-06T17:01:29.180482 #27636] DEBUG -- : lib/oxidized/node.rb: Oxidized::SSH ran for sw1 successfully
D, [2021-12-06T17:01:29.180544 #27636] DEBUG -- : lib/oxidized/job.rb: Config fetched for sw1 at 2021-12-06 16:01:29 UTC

and here the directory of git output but no cofiguration in it:

-rw-r--r--  1 oxidized oxidized 113 Dec  6 12:40 config
-rw-r--r--  1 oxidized oxidized  73 Dec  6 12:40 description
-rw-r--r--  1 oxidized oxidized  23 Dec  6 12:40 HEAD
drwxr-xr-x  2 oxidized oxidized  27 Dec  6 12:40 hooks
-rw-r--r--  1 oxidized oxidized 137 Dec  6 13:50 index
drwxr-xr-x  2 oxidized oxidized  21 Dec  6 12:40 info
drwxr-xr-x 10 oxidized oxidized  90 Dec  6 13:50 objects
drwxr-xr-x  4 oxidized oxidized  31 Dec  6 12:40 refs

**Comment by mortzu** [comment]
Its a bare repository. You have to clone it:
`git clone file://PATH-TO-REPO`

**Comment by Souheib-khiter** [comment]
yes, i do that and it work thank you @mortzu
