### ISSUE TITLE
Problem with HP ProCurve J9145A 2910al-24G

### ISSUE THREAD

**Issue by frank42hh** [ytti/oxidized#2426]
Hi there,
I have a strange problem with oxidized 0.28.0 and it seems like a similar one to #1436 with one difference: It doesn't happen on _every_ switch, but just for some. 

I have selected 2 switches for debugging, both are HP J9145A 2910al-24G Switch, one with Software revision W.15.14.0016 and one with Software revision W.15.14.0009, but as far as I can see, the expect output is the same for both systems (and therefore the difference in the minor version should not make a difference), and I checked IP authorized managers, which is also the same for both systems.
I can manually login via ssh on both systems just fine, and manually sending the commands works as well, and for both systems I see the login from oxidized in their event log, so oxidized does successfully log in to both switches.
But, on one system I get the expected output from procurve.rb, and on the other one I get this debug output:

```
D, [2021-12-07T17:53:51.187413 #12657] DEBUG -- : resolving DNS for hostname.domain.tld...
D, [2021-12-07T17:55:49.463970 #12657] DEBUG -- : lib/oxidized/worker.rb: Added /hostname.domain.tld to the job queue
D, [2021-12-07T17:55:49.464151 #12657] DEBUG -- : lib/oxidized/job.rb: Starting fetching process for hostname.domain.tld at 2021-12-07 16:55:49 UTC
D, [2021-12-07T17:55:49.464807 #12657] DEBUG -- : lib/oxidized/input/ssh.rb: Connecting to hostname.domain.tld
D, [2021-12-07T17:55:49.466264 #12657] DEBUG -- net.ssh.transport.session[2af429004ef0]: establishing connection to 10.7.23.115:22
D, [2021-12-07T17:55:50.580665 #12657] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/(^\r|\e\[24;[0-9][hH])?([\w\s.-]+[#>] )($|(\e\[24;[0-9][0-9]?[hH]){3})/] at hostname.domain.tld
I, [2021-12-07T17:55:52.290348 #12657]  INFO -- net.ssh.connection.session[2af428dc60a8]: 10.7.23.115 delete channel 0 which closed locally and remotely
W, [2021-12-07T17:55:52.391181 #12657]  WARN -- : 10.7.23.115 raised IOError with msg "closed stream"
D, [2021-12-07T17:55:52.391245 #12657] DEBUG -- : lib/oxidized/node.rb: Oxidized::SSH failed for hostname.domain.tld
D, [2021-12-07T17:55:52.391295 #12657] DEBUG -- : lib/oxidized/job.rb: Config fetched for hostname.domain.tld at 2021-12-07 16:55:52 UTC
W, [2021-12-07T17:55:52.465179 #12657]  WARN -- : /hostname.domain.tld status no_connection, retries exhausted, giving up
```
I have no clue how to resolve this. any ideas?

**Comment by mortzu** [comment]
oxidized can't connect to the devices. Please paste more configuration

**Comment by evega00** [comment]
Were you able to figure this out?

**Comment by frank42hh** [comment]
Nope, I wasn't able to figure this out. But since we replaced the switches in question with Cisco some time ago, I don't have the opportunity to test further anymore.
