### ISSUE TITLE
How to increase the number of nodes on the page when opening.

### ISSUE THREAD

**Issue by MrakoMaks** [ytti/oxidized#2429]
Good afternoon! I can't figure out how to increase the number of devices on the page when opening. 50 by default is too little for me. There must be a way :)
Thanks in advance!

![145600772-4b7e965a-305c-4749-a257-3968be3f559f](https://user-images.githubusercontent.com/84027393/145600981-def76b5b-3d9d-4771-84aa-b53585c29611.png)

**Comment by pfunkylol** [comment]
Have a look at https://github.com/ytti/oxidized-web/issues/127
