### ISSUE TITLE
Not seeing versions past the latest

### ISSUE THREAD

**Issue by cchance27** [ytti/oxidized#243]
If i click refresh on a device, it switches to no latest config, and then takes a new snapshot and i see the new date.. in versions i only see the latest...

also when i restart oxidized, its back to no configs available and takes fresh snapshots...

am i missing something, its like its reinitializing the git store every time... 

my output is that repo link was a nonexistent directory that it created on its own

output:
  default: git
  git:
    user: Oxidized
    email: oxidized@example.com
    repo: /root/configbackups/oxidized.git
source:
    default: http
    debug: false
    http:
      url: http://127.0.0.1/api/v0/oxidized
      scheme: http
      delimiter: !ruby/regexp /:/
      map:
        name: hostname
        model: os
      headers:
        X-Auth-Token: 7eadf014daed3018c11a9e28868c61cc

**Comment by ytti** [comment]
Is just just on oxidized-web, or do you see this in the repo as well? Do you only see 1 version in the repo?
```
git clone /root/configbackups/oxidized.git
cd oxidized
git log
```

**Comment by cchance27** [comment]
Apparently im an idiot, It was updating the date but no new copies because their was no changes, i just noticed that after saving some changes the next update did save as an updated version.
