### ISSUE TITLE
Can't remove old devices from list since changing the group name

### ISSUE THREAD

**Issue by G0nz0uk** [ytti/oxidized#2430]
Hello,

I realised that Oxidized was to trying to back up many devices that were in LibreNMS that it shouldn't.  I created a new group in LibreNMS that looks correct, but in the Oxidized portal the switches are still there that an not in the group anymore.

$config['oxidized']['maps']['group']['os'][] = array('match' => 'ios', 'group' => 'SwitchesBackup');
$config['oxidized']['maps']['group']['os'][] = array('match' => 'iosxe', 'group' => 'SwitchesBackup');
$config['oxidized']['group_support'] = true;

For example:
![image](https://user-images.githubusercontent.com/15994497/145675598-02825a32-51f7-4617-894d-4ce024e9d1a4.png)

What am I doing wrong?

**Comment by rwxd** [comment]
A restart of the oxidized service should resolve this error.
