### ISSUE TITLE
“last changed“modifiy to localtime and timezone

### ISSUE THREAD

**Issue by hfw1674** [ytti/oxidized#2431]
“last changed“modifiy to localtime and timezone

Trigger condition：
When the number of nodes is greater than 100。
probe:
![image](https://user-images.githubusercontent.com/24293072/145778533-2003f3ae-9827-456f-892f-653d267fd0c7.png)

![image](https://user-images.githubusercontent.com/24293072/145778645-a78bf877-2deb-45a5-994d-c83320f3ad4c.png)

**Comment by mortzu** [comment]
Can you please open an issue in oxidized-web?
