### ISSUE TITLE
AOSW Model not saving my conf

### ISSUE THREAD

**Issue by julesrenault** [ytti/oxidized#2438]
Hi There, when I tried to backup AOSW model I got this error, I think it’s due to regex prompt present in models/aosw. rb.I tried different regex to matching prompt and i always get an error and my conf isn’t saved.
I got 4 different devices with: 
```
(HOSTNAME) *#
```

	or

```
(HOSTNAME) #
```

I tried different regex and I get always the same error: 
```
([\w\(:.@-]+(\)?\s?)\*?[#>]\s?)$
^([\w\(.@-]+(\)?\s?)[\*]?[#>]\s?)$
([\w\(.@-]+(\)?\s?)\*?[#>]\s?)$
^([\w\(:.@-]+(\)?\s?)[#>]\s?)$
```

```
W, [2021-12-17T09:53:27.562738 #29]  WARN -- : 10.95.241.11 raised Oxidized::PromptUndetect with msg "
(NAB00-MC-01) *# not matching configured prompt (?-mix:^([\w\(:.@-]+(\)?\s?)[#>]\s?)$)"
W, [2021-12-17T09:57:27.567201 #29]  WARN -- : 10.95.241.11 raised Oxidized::PromptUndetect with msg "unable to detect prompt: (?-mix:^([\w\(:.@-]+(\)?\s?)[#>]\s?)$)"
W, [2021-12-17T10:18:56.087914 #29]  WARN -- : 10.95.241.11 raised Oxidized::PromptUndetect with msg "
(NAB00-MC-01) *# not matching configured prompt (?-mix:^([\w\(:.@-]+(\)?\s?)[#>]\s?)$)"
W, [2021-12-17T10:22:56.091910 #29]  WARN -- : 10.95.241.11 raised Oxidized::PromptUndetect with msg "unable to detect prompt: (?-mix:^([\w\(:.@-]+(\)?\s?)[#>]\s?)$)"
W, [2021-12-17T10:22:56.788260 #29]  WARN -- : /NAB00-MC-01 status no_connection, retry attempt 2
W, [2021-12-17T10:26:59.605744 #29]  WARN -- : 10.95.241.11 raised Oxidized::PromptUndetect with msg "
(NAB00-MC-01) *# not matching configured prompt (?-mix:^([\w\(:.@-]+(\)?\s?)[#>]\s?)$)"
```
ArubaOS (MODEL: Aruba7280), Version 8.7.1.3
Can someone help me to understand the problem and maybe fix it?

**Comment by mortzu** [comment]
maybe duplicate to #2381?

**Comment by julesrenault** [comment]
Yeah, I have already checked this issue, but not fixing my problem, I've got 4 devices with 2 prompt different `(HOSTNAME) #` and `(HOSTNAME) *#`.

When I test on regex tools online all working perfectly, but when is processed by oxidized I got an error...

I think I don't have understand clearly my problem, if you have more information please shared with me :)
