### ISSUE TITLE
cant see history

### ISSUE THREAD

**Issue by dushkoanton** [ytti/oxidized#2450]
Hi.I use it through docker. Successfully connected to the device and received a copy. But when I change the configuration on the device, I only update the old file.

Why my configuration files are not stored and I cannot see the history of changes?

```
username: admin
password: Passw0rd
model: routeros
resolve_dns: true
interval: 3600
use_syslog: false
debug: false
threads: 30
timeout: 140
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 0.0.0.0:8888
next_adds_job: false
vars: {}
groups: {}
models: {}
pid: "/root/.config/oxidized/pid"
crash:
  directory: "/root/.config/oxidized/crashes"
  hostnames: false
stats:
  history_size: 10
input:
  default: ssh, telnet
  debug: false
  ssh:
    secure: false
  ftp:
    passive: true
  utf8_encoded: true
output:
  default: file
  file:
    directory: "/root/.config/oxidized/configs"
source:
  default: csv
  csv:
    file: "/root/.config/oxidized/router.db"
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
      ip: 2
      username: 3
      password: 4
    vars:
      ssh_port: 5
    gpg: false
model_map:
  juniper: junos
  cisco: ios
  mikrotik: routeros
```

**Comment by davama** [comment]
Seeing history with oxidized is only possible when `output` Is git

**Comment by dushkoanton** [comment]
> Seeing history with oxidized is only possible when `output` Is git

In which version could it be stored locally? I find configuration guides and everywhere there is not a word about git, they store configs locally on a Linux machine and view the history of changes via the web
