### ISSUE TITLE
upgrading openssl and psych breaks oxidized.

### ISSUE THREAD

**Issue by Atroskelis** [ytti/oxidized#2462]
Environment is centos 7

Upgrading openssl to 3.0.0 vs 2.1.6 gives a 

> OpenSSL::PKey::PKeyError with msg "DH_set0_key"

when connecting via SSH to hosts. Probably related to [link](https://github.com/ruby/openssl/issues/93).

Using psych 4.0.3 vs 3.1.0 gives a 

> Error loading config: Tried to load unspecified class: Regexp

Related to #2305 and probably the 

> prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/

line in config file. 

Most annoying is that you need rdoc to uninstall gems which requires psych so correcting requires multiple install/uninstalls of psych

**Comment by Dr-Bone** [comment]
Hi
Today Arch upgraded psych from 4.0.4-2 to 4.0.4-4 along with many other ruby packages and I'm also now getting this error. 
Downgrading psych to 4.0.4-2 via pacman did not help unfortunately, 
Are there any plans to work on this in the near future?

**Comment by Atroskelis** [comment]
Seems even opensslv3 is on the "no work" list  as it gives an error about pkeys.
