### ISSUE TITLE
We couldn't retrieve the device information from Oxidized !!

### ISSUE THREAD

**Issue by Jason-MK** [ytti/oxidized#2466]
Hello ,

I have this problem with Oxidized on Librenms can anyone help me in this and tell me what should I do and how to debug this problem please ?

We couldn't retrieve the device information from Oxidized !!

Best Regards

**Comment by Atroskelis** [comment]
Is your oxidized service running?

**Comment by Jason-MK** [comment]
Yes of course I really need help I don't where to search for a solution ?
