### ISSUE TITLE
fortigate error ssh

### ISSUE THREAD

**Issue by hofikhof** [ytti/oxidized#2477]
Hello, what is wrong please? I need read configs from our FortiGate devices. I tried input telnet, ssh, install different versions net-ssh bz gem without success.
net-ssh version 5.2.0, oxidized 0.28.0
in debug log is this:

D, [2022-02-10T08:55:29.853030 #7045] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 0 of 1
D, [2022-02-10T08:55:29.853230 #7045] DEBUG -- : lib/oxidized/worker.rb: Added /fortigate.company.int to the job queue
D, [2022-02-10T08:55:29.853262 #7045] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2022-02-10T08:55:29.853447 #7045] DEBUG -- : lib/oxidized/job.rb: Starting fetching process for fortigate.company.int at 2022-02-10 07:55:29 UTC
D, [2022-02-10T08:55:29.853669 #7045] DEBUG -- : lib/oxidized/input/ssh.rb: Connecting to fortigate.company.int
D, [2022-02-10T08:55:29.853919 #7045] DEBUG -- : AUTH METHODS::["none", "publickey", "password"]
D, [2022-02-10T08:55:29.854578 #7045] DEBUG -- net.ssh.transport.session[4c4]: establishing connection to 10.1.230.1:22
D, [2022-02-10T08:55:29.855032 #7045] DEBUG -- net.ssh.transport.session[4c4]: connection established
I, [2022-02-10T08:55:29.855162 #7045]  INFO -- net.ssh.transport.server_version[4d8]: negotiating protocol version
D, [2022-02-10T08:55:29.855230 #7045] DEBUG -- net.ssh.transport.server_version[4d8]: local is `SSH-2.0-Ruby/Net::SSH_5.2.0 x86_64-linux-gnu'
D, [2022-02-10T08:55:29.860582 #7045] DEBUG -- net.ssh.transport.server_version[4d8]: remote is `SSH-2.0-7WO2e'
I, [2022-02-10T08:55:29.861114 #7045]  INFO -- net.ssh.transport.algorithms[4ec]: sending KEXINIT
D, [2022-02-10T08:55:29.861335 #7045] DEBUG -- socket[500]: queueing packet nr 0 type 20 len 1324
D, [2022-02-10T08:55:29.861447 #7045] DEBUG -- socket[500]: sent 1328 bytes
D, [2022-02-10T08:55:29.861548 #7045] DEBUG -- socket[500]: read 1048 bytes
D, [2022-02-10T08:55:29.861670 #7045] DEBUG -- socket[500]: received packet nr 0 type 20 len 1044
I, [2022-02-10T08:55:29.861755 #7045]  INFO -- net.ssh.transport.algorithms[4ec]: got KEXINIT from server
I, [2022-02-10T08:55:29.861893 #7045]  INFO -- net.ssh.transport.algorithms[4ec]: negotiating algorithms
D, [2022-02-10T08:55:29.862006 #7045] DEBUG -- net.ssh.transport.algorithms[4ec]: negotiated:
* kex: diffie-hellman-group-exchange-sha256
* host_key: ssh-ed25519
* encryption_server: aes256-ctr
* encryption_client: aes256-ctr
* hmac_client: hmac-sha2-512
* hmac_server: hmac-sha2-512
* compression_client: none
* compression_server: none
* language_client: 
* language_server: 
D, [2022-02-10T08:55:29.862438 #7045] DEBUG -- net.ssh.transport.algorithms[4ec]: exchanging keys
D, [2022-02-10T08:55:29.862655 #7045] DEBUG -- socket[500]: queueing packet nr 1 type 34 len 20
D, [2022-02-10T08:55:29.862761 #7045] DEBUG -- socket[500]: sent 24 bytes

D, [2022-02-10T08:55:29.926708 #7045] DEBUG -- socket[500]: read 280 bytes
D, [2022-02-10T08:55:29.927025 #7045] DEBUG -- socket[500]: received packet nr 1 type 31 len 276
D, [2022-02-10T08:55:29.931485 #7045] DEBUG -- socket[500]: queueing packet nr 2 type 32 len 268
D, [2022-02-10T08:55:29.931592 #7045] DEBUG -- socket[500]: sent 272 bytes
D, [2022-02-10T08:55:29.956053 #7045] DEBUG -- socket[500]: read 432 bytes
D, [2022-02-10T08:55:29.956264 #7045] DEBUG -- socket[500]: received packet nr 2 type 33 len 412

D, [2022-02-10T08:55:29.957910 #7045] DEBUG -- socket[500]: queueing packet nr 3 type 21 len 20
D, [2022-02-10T08:55:29.958001 #7045] DEBUG -- socket[500]: sent 24 bytes
D, [2022-02-10T08:55:29.958081 #7045] DEBUG -- socket[500]: received packet nr 3 type 21 len 12
D, [2022-02-10T08:55:29.958368 #7045] DEBUG -- net.ssh.authentication.session[514]: beginning authentication of `rancid'
D, [2022-02-10T08:55:29.958521 #7045] DEBUG -- socket[500]: queueing packet nr 4 type 5 len 28
D, [2022-02-10T08:55:29.958593 #7045] DEBUG -- socket[500]: sent 96 bytes

D, [2022-02-10T08:55:29.989991 #7045] DEBUG -- socket[500]: read 0 bytes
D, [2022-02-10T08:55:29.990118 #7045] DEBUG -- : 10.1.230.1 raised Net::SSH::Disconnect with msg "connection closed by remote host"
D, [2022-02-10T08:55:29.990180 #7045] DEBUG -- : lib/oxidized/node.rb: Oxidized::SSH failed for fortigate.company.int

**Comment by mortzu** [comment]
Please paste in a readable format (https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code)

**Comment by damiantrx** [comment]
@hofikhof how did you solve the problem? I am struggling with something similar....
