### ISSUE TITLE
Push oxidized configs to Gitlab 

### ISSUE THREAD

**Issue by Jason-MK** [ytti/oxidized#2492]
Hello ,

I’m trying since yesterday to send my Oxidized configs to Gitlab on the same machine of Oxidized !

I want to know how to debug why I cant’ see a results on the Gitlab ?

IS there any way to help ?

Best Regards

**Comment by feriniguez** [comment]
Set the debug to true in the config. You should be able to see if the github push are triggered.

You can share your hooks config if you need more help. I just have put this same thing to work with gitlab.

**Comment by Bierchermuesli** [comment]
Close or contribute some details?
