### ISSUE TITLE
FortiOS changes a lot of encryption every time config is downloaded

### ISSUE THREAD

**Issue by sgelineau17** [ytti/oxidized#2513]
Hello,

I backup dozens of Fortigate around the world. 
The device source is LibreNMS.
My Oxidized is running on docker.
In my config file I have enable this option : remove_secret: true 
but I still have plenty of backups being made.

I also noticed that in the backups the accounts are completely deleted.

I noticed while doing a diff of the two configuration versions I have that the encrypted part of this categories changes regularly:

set ENC password
set ENC proxy password
set passwd1 ENC
set passwd2 ENC
set passwd3 ENC
set private key
set auth-password-l1 ENC
set ENC password
set password2 ENC
set password3 ENC
set password4 ENC
set password5 ENC
set auth-password-l1 ENC
set auth-password-l2 ENC

Am I the only one in this situation ?

Thanks !

**Comment by pfunkylol** [comment]
Can you post the config ?
Also, after you activated the remove_secret variable, have you performed a docker stop/start ?

**Comment by sgelineau17** [comment]
Here my config (cleared config with : 

debug: false #Debug mode! Great for setup.
logs: /root/.config/oxidized/logs
interval: 3600 #interval in seconds
threads: 30
timeout: 300 #Timeout after 300 seconds.
retries: 3 #Try 3 times.
remove_secret: true #Remove secret/enable passwords from the resulting config file - does not work on all models.
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/ #Detection of the user prompt on the device.
rest: 0.0.0.0:8888 #Listening address for API/web UI endpoint.
next_adds_job: true
pid: "pid"

crash:
  directory: "/root/.config/oxidized/crashes" #Where to store the log when the application crashes
  hostnames: true
stats:
  history_size: 10 #How many past configs to keep.

input:
  default: ssh
  debug: false
  ssh:
    secure: false  #I believe this has something to do with using keys or certificates to connect to the devices.
  utf8_encoded: true

output:
 default: git #Output to a Git repository. Oxidized will create the repository based on the settings below.
 git:
   single_repo: true
   user: Oxidized #Does not need to be an actual user, this is just the name that will appear on the commits
   email: oxidized@domain.com #Again, does not need to be an actual email address.
   repo: "/home/oxidized/enterprise-network/" #Where to store the repository
 file:
   directory: "/home/oxidized/enterprise-network/" #By default, Oxidized will create a repository for each device.

hooks:
 push_to_remote:
   type: githubrepo
   events: [post_store]
   remote_repo: "git@gitlab:oxidized/enterprise-network.git"
   publickey: "/root/.config/oxidized/.ssh/id_rsa.pub"
   privatekey: "/root/.config/oxidized/.ssh/id_rsa"

source:
   default: http
   debug: true
   http:
     secure: false
     scheme: https
     url: https://ip/api/v0/oxidized
     map:
       name: hostname
       model: os
       group: group
     headers:
       X-Auth-Token: 'token'

model_map:
  aos6: aos
  ciscowlc: aireos
  fortigate: fortios

models:
  aos:
    username: 
    password: 
  aos7:
    username: 
    password: 
  fortios:
    username: 
    vars:
      ssh_port: 
      auth_mehtod: publickey
      ssh_keys: "/root/.config/oxidized/.ssh-fgt/id_rsa"

groups:
  nexus:
    username: 
    password: 
  mit:
    username: 
    password: 
  wlc:
    username: 
    password: 


Yes for sure, I have do this.

**Comment by pfunkylol** [comment]
I am using it this way and it works 

`models:
  fortios:
    vars:
      remove_secret: true`

**Comment by aschaber1** [comment]
related to https://github.com/ytti/oxidized/issues/1883

**Comment by csszep** [comment]
Hi!

It is possibe to create a simple "scp" or "sftp "model" with Oxidized to backup files from remote devices instead of capture commands output?

I backup Forti devices simply scp the "sys_config" file.

scp -i /.ssh/id_rsa $username@$host:sys_config $host_sys_config
