### ISSUE TITLE
EdgeSwitch X not supported

### ISSUE THREAD

**Issue by davidschoefberger** [ytti/oxidized#2522]
Hi,

I just tried to add an Ubiquiti EdgeSwitch X (ES-10XP) to Oxidized. Unfortunately, it's not working. Looks like the OS is different to the "old" EdgeMax.

```
sw02#  not matching configured prompt (?-mix:\(.*\)\s[#>])"
```

Best,
David

**Comment by sjthespian** [comment]
@davidschoefberger have you tried using edgetswitch instead of edgeos in your router.db? That fixed a similar problem for me.

**Comment by davidschoefberger** [comment]
@sjthespian I tried both edgeos and edgeswitch, unfortunately with the same result.
