### ISSUE TITLE
Dlink Issue DGS-1250-52X

### ISSUE THREAD

**Issue by github7485** [ytti/oxidized#2524]
Hello,

I have new Manageable Switch DGS-1250-52X. When I try to autosave configuration from oxidized, I encounter this following error message below. Just for information, account used for backup isn't used by anoher process. Could you help to me solve this issue please ?

 "ERROR: System locked by other session."

Thank You for your help at this topic

Regards

**Comment by github7485** [comment]
Hello,

Any news please on this issue described above ?

Regards

**Comment by alexanderek** [comment]
Same problem, how do I fix it?
