### ISSUE TITLE
Building docker image from Docker file

### ISSUE THREAD

**Issue by ohumeagle** [ytti/oxidized#2525]
I am trying to build the image from Docker file existing in the root directory, facing this error. 

ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    bad response Forbidden 403 (https://api.rubygems.org/quick/Marshal.4.8/nokogiri-1.13.4-x64-unknown.gemspec.rz)
    
Do you have any ideas what should I do?

**Comment by fernandolcx** [comment]
Please check #2519

**Comment by mortzu** [comment]
Can I close this as the PR is merged?
