### ISSUE TITLE
IOSXR doesn't work when "show inv" is too long

### ISSUE THREAD

**Issue by andrewohanian** [ytti/oxidized#2535]
I have a few ASR9001s that have a very lengthy "show inventory" output - maybe a few hundred lines or more.

When I use the default model and enable debugging, the output is hung in the middle of "show inventory" for two routers that have the lengthy "show inventory" output. There is an error of "no_connection" seen in LibreNMS.

If I create my own iosxr model and comment out the "show inventory" command, then it works fine.

Is there some limit for "show inventory"?

**Comment by Bierchermuesli** [comment]
there is no limit, but there is a time limit. The ASR needs some time to collect the data. 

in my case i just increased the timeout from 20 to 40 sec in oxidized/config
```
---
timeout: 40
```

I hope this helps - I guess this case issue can be close
