### ISSUE TITLE
Hook for Node Config Changed

### ISSUE THREAD

**Issue by MrRJ45** [ytti/oxidized#256]
This would be something very useful, certainly for me.

A hook which runs only when the config has changed would be good to have. Something such as node_updated I think would be appropriate.

Of course this would only work with git output as its the only way we would know it's changed.

I will work on this in the next few days if nobody has any objections or suggestions :)

**Comment by ytti** [comment]
I guess we could make it work on file quite easily too. Something like

````
old = File.read(file)
new = outputs.to_cfg
if old == new
  return :unchanged
else
  File.write(file, new)
  return :changed
end
````
and worker then fires the hook if #store returned changed.

**Comment by MrRJ45** [comment]
That sounds like a good plan :)

I am thinking too that we should be able to pass an array of hooks to Hooks.handle, that will mean less code to run this new hook.

I think that will work, so I shall test this idea.

**Comment by MrRJ45** [comment]
Having looked at this a bit more, it appears that the git store function already does this.

Its return of true means that the hook "post_store" is ran only when the config has changed. I will update the documentation as the name suggests this is ran at every store.

I'm not sure how many people use the file store, but I guess we should implement the same to get feature parity.
