### ISSUE TITLE
Dell OS10 OS label from LibreNMS contains '-'

### ISSUE THREAD

**Issue by joshspranger** [ytti/oxidized#2571]
When adding one of the new Dell OS10 switches (model S5224F-ON) to LibreNMS when the OS field is passed to Oxidized the OS version displays 'dell-os10', if you try to make a model.rb file for that OS when Oxidized loads it it fails with a /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/model/dell-os10.rb:1: syntax error, unexpected '-' I was using the os10.rb file that was on the git repository and modified the name to 'dell-os10' as well as the line 1 'class dell-os10 < Oxidized::Model'
See return from the LibreNMS API below:

 "hostname": "lc-dell-bottom.maspethfederal.com",
        "os": "dell-os10",
        "ip": "10.9.1.7",
        "group": "dell"

Not sure if this needs to be fixed here or in LibreNMS.

**Comment by mortzu** [comment]
Create an override as described on https://docs.librenms.org/Extensions/Oxidized/#creating-overrides
