### ISSUE TITLE
Mail notification

### ISSUE THREAD

**Issue by fratermine** [ytti/oxidized#2574]
Hi All,

I am running oxidized as docker and trying to send email notification . I have updated the config file as below but it doesn't work. I have the below message on the log file . Any idea on how I can make it work ?

  email_output:
    type: exec
    events: [post_store, node_fail]
    cmd: '/bin/sh /root/.config/oxidized/oxidized-report-git-commits -s Oxidized updates for $OX_NODE_NAME -r xxx@gmail.com'
    async: true
    timeout: 120

E, [2022-06-29T09:00:34.984717 #32] ERROR -- : Exec: "/bin/sh /root/.config/oxidized/oxidized-report-git-commits -s \"Oxidized updates for $OX_NODE_NAME\" -r xxxxx@gmail.com" failed with exit value 64

Appreciate any help 
Francesco

**Comment by Bierchermuesli** [comment]
Docker and mail is in general not so easy and oxidized Docker Image is not intend work with the extra scripts. It wont work for several reasons:

1. I don't think this script is placed in this path within the docker container. 
2. the docker does not have a MTA built in (also no sendmail/mail command)
3. you need a relay host if you wand sending mails from inside a docker container

I would: 
1. make fork of the Dockerfile and add `ssmtp` as package
2. modify/ fork `oxidized-report-git-commits` to use ssmtp and a smart/relay-host (-Variable)
3. make a PR
