### ISSUE TITLE
Last configuration change email notification 

### ISSUE THREAD

**Issue by babeeshmb** [ytti/oxidized#2575]
Getting frequent email notification for the Dell Switch S4148F with software version 10.5.2.9 

It is using the gem file powerconnect.rb . There is no configuration changes are actually happening on the switch but every now and then the notification emails are keep coming . Only the configuration time is changing in the notification email. How we can ignore this in the gem powerconnect.rb ? 

Email message
+! Last configuration change at Jul  01 06:46:53 2022

**Comment by systeembeheerder** [comment]
Create a custom model [1] to filter this line or don't save your unchanged config 'every now and then'. 


[1] https://github.com/ytti/oxidized/blob/master/docs/Creating-Models.md
