### ISSUE TITLE
NDMS ssh connect FAIL

### ISSUE THREAD

**Issue by istokin** [ytti/oxidized#2577]
Debug log:

I, [2022-07-05T14:28:45.006608 #4311]  INFO -- : Oxidized starting, running as pid 4311
D, [2022-07-05T14:28:45.007408 #4311] DEBUG -- : Hook "push_to_remote" registered GithubRepo for event :post_store
I, [2022-07-05T14:28:45.008000 #4311]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
D, [2022-07-05T14:28:45.008140 #4311] DEBUG -- : resolving DNS for NDMSDEVICE...
D, [2022-07-05T14:28:45.008191 #4311] DEBUG -- : IPADDR 10.14.1.1
D, [2022-07-05T14:28:45.008269 #4311] DEBUG -- : node.rb: resolving node key 'model', with passed global value of '' and node value 'ndms'
D, [2022-07-05T14:28:45.008311 #4311] DEBUG -- : node.rb: setting node key 'model' to value 'junos' from global
D, [2022-07-05T14:28:45.008357 #4311] DEBUG -- : node.rb: returning node key 'model' with value 'ndms'
D, [2022-07-05T14:28:45.008393 #4311] DEBUG -- : lib/oxidized/node.rb: Loading model "ndms"
D, [2022-07-05T14:28:45.008784 #4311] DEBUG -- : lib/oxidized/model/model.rb Added show version to the commands list
D, [2022-07-05T14:28:45.008857 #4311] DEBUG -- : lib/oxidized/model/model.rb Added show running-config to the commands list
D, [2022-07-05T14:28:45.009000 #4311] DEBUG -- : node.rb: resolving node key 'input', with passed global value of 'ssh' and node value ''
D, [2022-07-05T14:28:45.009051 #4311] DEBUG -- : node.rb: returning node key 'input' with value 'ssh'
D, [2022-07-05T14:28:45.071344 #4311] DEBUG -- : node.rb: resolving node key 'output', with passed global value of 'git' and node value ''
D, [2022-07-05T14:28:45.071518 #4311] DEBUG -- : node.rb: returning node key 'output' with value 'git'
D, [2022-07-05T14:28:45.087237 #4311] DEBUG -- : node.rb: resolving node key 'username', with passed global value of '' and node value ''
D, [2022-07-05T14:28:45.087336 #4311] DEBUG -- : node.rb: setting node key 'username' to value 'username' from global
D, [2022-07-05T14:28:45.087376 #4311] DEBUG -- : node.rb: setting node key 'username' to value 'admin' from group
D, [2022-07-05T14:28:45.087406 #4311] DEBUG -- : node.rb: returning node key 'username' with value 'admin'
D, [2022-07-05T14:28:45.087438 #4311] DEBUG -- : node.rb: resolving node key 'password', with passed global value of '' and node value ''
D, [2022-07-05T14:28:45.087470 #4311] DEBUG -- : node.rb: setting node key 'password' to value 'password' from global
D, [2022-07-05T14:28:45.087516 #4311] DEBUG -- : node.rb: setting node key 'password' to value 'P@ssw0rd1' from group
D, [2022-07-05T14:28:45.087548 #4311] DEBUG -- : node.rb: returning node key 'password' with value 'P@ssw0rd1'
I, [2022-07-05T14:28:45.087612 #4311]  INFO -- : lib/oxidized/nodes.rb: Loaded 1 nodes
D, [2022-07-05T14:28:45.338656 #4311] DEBUG -- : lib/oxidized/core.rb: Starting the worker...
D, [2022-07-05T14:28:46.339984 #4311] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 0 of 1
D, [2022-07-05T14:28:46.340312 #4311] DEBUG -- : lib/oxidized/worker.rb: Added shops/NDMSDEVICE to the job queue
D, [2022-07-05T14:28:46.340349 #4311] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2022-07-05T14:28:46.341108 #4311] DEBUG -- : lib/oxidized/job.rb: Starting fetching process for NDMSDEVICE at 2022-07-05 05:28:46 UTC
D, [2022-07-05T14:28:46.341234 #4311] DEBUG -- : lib/oxidized/job.rb: Config fetched for NDMSDEVICE at 2022-07-05 05:28:46 UTC
W, [2022-07-05T14:28:47.341886 #4311]  WARN -- : shops/NDMSDEVICE status fail, retry attempt 1
D, [2022-07-05T14:28:47.341969 #4311] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 0 of 1
D, [2022-07-05T14:28:47.342121 #4311] DEBUG -- : lib/oxidized/worker.rb: Added shops/NDMSDEVICE to the job queue
D, [2022-07-05T14:28:47.342144 #4311] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2022-07-05T14:28:47.342339 #4311] DEBUG -- : lib/oxidized/job.rb: Starting fetching process for NDMSDEVICE at 2022-07-05 05:28:47 UTC
D, [2022-07-05T14:28:47.342421 #4311] DEBUG -- : lib/oxidized/job.rb: Config fetched for NDMSDEVICE at 2022-07-05 05:28:47 UTC
W, [2022-07-05T14:28:48.343556 #4311]  WARN -- : shops/NDMSDEVICE status fail, retry attempt 2
D, [2022-07-05T14:28:48.344300 #4311] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 0 of 1
D, [2022-07-05T14:28:48.344389 #4311] DEBUG -- : lib/oxidized/worker.rb: Added shops/NDMSDEVICE to the job queue
D, [2022-07-05T14:28:48.344410 #4311] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2022-07-05T14:28:48.344608 #4311] DEBUG -- : lib/oxidized/job.rb: Starting fetching process for NDMSDEVICE at 2022-07-05 05:28:48 UTC
D, [2022-07-05T14:28:48.344689 #4311] DEBUG -- : lib/oxidized/job.rb: Config fetched for NDMSDEVICE at 2022-07-05 05:28:48 UTC
W, [2022-07-05T14:28:49.345854 #4311]  WARN -- : shops/NDMSDEVICE status fail, retry attempt 3
D, [2022-07-05T14:28:49.346074 #4311] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 0 of 1
D, [2022-07-05T14:28:49.346175 #4311] DEBUG -- : lib/oxidized/worker.rb: Added shops/NDMSDEVICE to the job queue
D, [2022-07-05T14:28:49.346233 #4311] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2022-07-05T14:28:49.346324 #4311] DEBUG -- : lib/oxidized/job.rb: Starting fetching process for NDMSDEVICE at 2022-07-05 05:28:49 UTC
D, [2022-07-05T14:28:49.346394 #4311] DEBUG -- : lib/oxidized/job.rb: Config fetched for NDMSDEVICE at 2022-07-05 05:28:49 UTC
W, [2022-07-05T14:28:50.347667 #4311]  WARN -- : shops/NDMSDEVICE status fail, retries exhausted, giving up
D, [2022-07-05T14:28:50.347981 #4311] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 1 of 1
D, [2022-07-05T14:28:50.348163 #4311] DEBUG -- : lib/oxidized/worker.rb: Running :nodes_done hook
D, [2022-07-05T14:28:51.349327 #4311] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 0 of 1
D, [2022-07-05T14:28:52.350713 #4311] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 0 of 1
D, [2022-07-05T14:28:53.352210 #4311] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 0 of 1

config:
--- resolve_dns: false
interval: 3600
use_syslog: false
debug: true
threads: 30
timeout: 30
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 192.168.1.1:8888
next_adds_job: false
vars: {}
groups:
  shops:
    username: admin
    password: P@ssw0rd1
models: {}
pid: "/home/oxidized/.config/oxidized/pid"
log: "/home/oxidized/.config/oxidized/logs/log"
crash:
  directory: "/home/oxidized/.config/oxidized/crashes"
  hostnames: false
stats:
  history_size: 10
input:
  default: ssh
  debug: true
  ssh:
    secure: false
  utf8_encoded: true
output:
  default: git
  git:
    user: oxidized
    email: oxidized@127.0.0.1
    single_repo: true
    repo: ~/.config/oxidized/test.git
hooks:
  push_to_remote:
    type: githubrepo
    events: [post_store]
    remote_repo: "http://192.168.1.1:3000/oxidized/test.git"
    username: oxidized
    password: oxidized
source:
  default: csv
  csv:
    file: "/home/oxidized/.config/oxidized/router.db"
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
      group: 2
      ip: 3
      username: 4
      password: 5
    gpg: false
    

if add input: default: telnet - all work ok!

**Comment by Firefishy** [comment]
The above logs do not have the error details. You need to enable input debug to see the error.

```
input:
  default: ssh, telnet
  debug: true
  ```
