### ISSUE TITLE
REST integration with LibreNMS and Oxidized Fails With SELinux

### ISSUE THREAD

**Issue by jharms** [ytti/oxidized#258]
Possible inclusion for the FAQ or doco relating to Oxidized/LibreNMS integration. Not a bug as such.

When the LibreNMS PHP scripts attempt to invoke the REST API with oxidized, it fails on RHEL/CENTOS. Based on debugging the PHP code within LibreNMS we had to:

1. Confirm PHP include files for LibreNMS are permitted to allow_url_fopen in php.ini (as well as generally)

2. Configure SELinux to permit outbound connections by the web server: 
setsebool -P httpd_can_network_connect 1

Once these settings were set, it worked as expected.

**Comment by supertylerc** [comment]
@jharms, unless I misunderstand, the first point seems like it should be in the LibreNMS documentation.  Regarding the second point--is this required for LibreNMS or for oxidized-web's web server?  The wording makes it sound like it's required for LibreNMS, in which case it should also be covered under LibreNMS's integration documentation for Oxidized.

Thanks!

**Comment by jharms** [comment]
Hi Tyler

Agree with you entirely re it sitting with LibreNMS. However, I thought it may be also worth adding to your side of the fence as well but it was only a suggestion.

Cheers
Jonathan

**Comment by ytti** [comment]
I'm cool with adding paragraph about LibreNMS support on README.md, and explaining there any catches. @jharms if you can edit README.md accordingly and send pool request, that would be nice, thanks!

**Comment by ytti** [comment]
I've not seen PR, if documentations need to be enhanced, I'm happy to accept one.
