### ISSUE TITLE
Mutli Login/Password

### ISSUE THREAD

**Issue by chrisgfx** [ytti/oxidized#259]
Hi,

Oxidized is a great tool and I'm using it in association with LibreNMS.
I'm wondering if it is possible to manage several different accounts on devices?
LibreNMS is not sending this type of information with its API and therefore is it possible to implement a sort of list of login/passwords with which Oxidized will try to access to devices ?

In general, it could be great to have a configuration system to choose several specific information for devices:

- model of device
- accounts to use
- commands to use
- frequency of execution of commands ?
- etc

Thanks!

**Comment by ytti** [comment]
So right now we support 
a) auth/model per node
b) auth/model per group
c) global auth/model

If LibreNMS cannot send this information with node, could it be changed to send it? I believe LibreNMS _CAN_ send model. Unsure about auth?

If LibreNMS cannot send auth, and LibreNMS won't change API so that it can send auth. What is the preferred way for Oxidized to know the auth? Seems redundant to iterate each node + their auth in router.db?

**Comment by chrisgfx** [comment]
Thank you for your quick reply.
I may missed some documentation about the way to configure Oxidized as I don't know how to deal with group or nodes configuration.

LibreNMS is sending the hostname and the model type of the device.
So in real environment, we have to deal with different login/password for different devices or sites.

Yes, it's redundant to have dynamic information with LibreNMS API and router.db file.
So the best way to deal with could be is a list of login/password and Oxidized try them sequentially.
Or Login/Password associate with a Group and the Group could be put in a configuration file or better sent as an attribute by LibreNMS API.

**Comment by supertylerc** [comment]
I think someone is working on a feature to pass groups from LibreNMS. I saw a branch in a fork that suggested it might be a work in progress, so maybe wait for that. I'll try to find where I saw that and post a link to it this weekend. 

Another option would be for LibreNMS to return usernames and passwords. @ytti might disagree, but I'd rather see the features in LibreNMS (which is very actively developed) than see workarounds in Oxidized. With that said, I'm sure @ytti would also be open to PRs to implement what you're talking about in Oxidized itself. But I'm not going to pretend to speak for him or the project. These are just my opinions. :D

**Comment by ytti** [comment]
I fully agree that librenms should either pass group or auth information. It makes no sense to use librenms API, if you end up iterating all devices in router.db as well.

And we can already today support either methods.

But perhaps I am missing something. @chrisgfx we can associate auth to a group, thanks to @supertylerc. I think thats a-ok solution, but best would be, just for librenms to pass auth details.

I don't think it's very good solution to iterate multiple auth details and try them until some succeeds.

**Comment by chrisgfx** [comment]
Thank you very much guys! :-)
I'm agree with you, the best way to treat this is from the LibreNMS API.

I found the Issue in LibreNMS: Expose a group in the api for Oxidized
https://github.com/librenms/librenms/issues/2464

That's exactly what we all need to have in order to fully use LibreNMS + Oxidized.
So I'm looking forward to see what can be done.

**Comment by laf** [comment]
@ytti @supertylerc We'll pick this up folks. Someone has already made a start on it so we'll see where they are upto on it. It's quite a requested item and we've got a good few people using Oxidized in LibreNMS to be able to help get something in place.

**Comment by ytti** [comment]
@laf great to hear, thanks. Let us know if there is anything you need us to do, to make things more simple on your side.

**Comment by SaaldjorMike** [comment]
I'm currently trying to test out a LibreNMS PR that will expose the group for each device. Checking the output from the LibreNMS API yields:
```json
[
    {
        "hostname": "dev.example.org",
        "os": "ios",
        "group": "groupname"
    }
]
```

Oxidized config for my group:
```yaml
groups:
  groupname:
    username: USER
    password: PASS
```
Any idea why Oxidized tries `username` for username and `password` as the password, instead of my group-defined credentials? My log shows:
```
D, [2016-01-11T19:09:53.507984 #2000] DEBUG -- : SSH: username @ dev.example.org
D, [2016-01-11T19:09:53.911067 #2000] DEBUG -- : SSH: password @ dev.example.org
```

**Comment by SaaldjorMike** [comment]
I've just merged a PR for LibreNMS that will give a user the possibility to expose a group through the LibreNMS API. I've now set my source in the Oxidized as the following which works perfectly fine (notice the `group: group` part of the map):
```
source:
  default: http
  http:
    url: https://dev.example.org/api/v0/oxidized
    scheme: https
    delimiter: !ruby/regexp /:/
    map:
      name: hostname
      model: os
      group: group
    headers:
      X-Auth-Token: TOKEN
```

**Comment by chrisgfx** [comment]
Wonderful! Thank you very much. :-)

**Comment by laf** [comment]
Can this be closed now?

**Comment by chrisgfx** [comment]
Hum, I tried it and it work well with the defaut group. But not for a specific group with Juniper SRX, devices that are not well managed by Oxidized as we must enter a command "cli" before being able to send show commands.

Anyway I close the issue and will dig further by myside! Thank you very much for your help. :-)
