### ISSUE TITLE
"pkeys are immutable on OpenSSL 3.0"

### ISSUE THREAD

**Issue by Chrus3** [ytti/oxidized#2602]
Not able to pull config from devices using SSL. Getting the following error message:

juniper/SW001 status no_connection, retry attempt 1
10.1.1.2 raised OpenSSL::PKey::PKeyError with msg "pkeys are immutable on OpenSSL 3.0", 10.1.1.2 saved

Running on Ubuntu 22.04.1 LTS.

**Comment by ssigle** [comment]
Im seeing the same issue. Hoping to find anyone who has found a work around.

**Comment by mxkissnr** [comment]
Same issue w. Cisco devices on Ubuntu 22.04.1 LTS

***.***.***.*** raised OpenSSL::PKey::PKeyError with msg "dh#set_pqg= is incompatible with OpenSSL 3.0", ***.***.***.***  saved

**Comment by Venkarian** [comment]
The same here on Ubuntu 22.04.1 LTS on HP Procurves.
Maybe is this because the devices does not use OpenSSL 3.0 ?

**Comment by d-0-c** [comment]
Same here with Ubiquiti devices on Ubuntu 22.04.01 (5.15.0-47-generic x86_64), OpenSSL 3.0.2-0ubuntu1.6, ruby 1:3.0~exp1
Has anyone found a solution yet?

**Comment by johnstruse** [comment]
I was running into this error on Ubuntu 22.04 as well. Instead of using the gem which hasn't been updated since mid-2020, I built and installed the latest version from Git. I ended up needing to build both `oxidized` and `oxidized-web` since I'm using the web UI.

**Comment by candlerb** [comment]
Any chance of a new release to fix this? 0.28.0 was cut in May 2020.  Thanks!

**Comment by mortzu** [comment]
Yes. I've wanted to make a release for months. But time is short...
