### ISSUE TITLE
oxidized fails to start after OS migration to Debian 11

### ISSUE THREAD

**Issue by meekser** [ytti/oxidized#2603]
I have oxidized running on Debian 10 with no issues for months now. 
After upgrading OS to Debian 11 oxidized is not able to start as it requires ruby2.5 as an interpreter, but OS version is 2.7 not.

Changing the version in /usr/local/bin/oxidized does not work as well. It crushes with the error below:
\# /usr/local/bin/oxidized
Traceback (most recent call last):
	2: from /usr/local/bin/oxidized:23:in `<main>'
	1: from /usr/lib/ruby/vendor_ruby/rubygems.rb:300:in `activate_bin_path'
/usr/lib/ruby/vendor_ruby/rubygems.rb:281:in `find_spec_for_exe': can't find gem oxidized (>= 0.a) with executable oxidized (Gem::GemNotFoundException)

Any tips on that or should I reinstall it all from scratch?

**Comment by mortzu** [comment]
You have to reinstall all the oxidized gems

**Comment by Firefishy** [comment]
This isn't an oxidized bug. Please close.

**Comment by meekser** [comment]
Thanks @mortzu - it did the trick!
