### ISSUE TITLE
IOSXE command unavailable on iosxe.rb:label:device_model 

### ISSUE THREAD

**Issue by Dellogeon** [ytti/oxidized#2604]
We are running oxidized docker on a host and we have some Cisco device running on IOSXE. Currently, we created oxidized user with privilege 10.  "show running-config" is not working on this privilege. Only "_**show running-config view full**_" can shows full configuration that we expect. BTW, this command can only be used in IOSXE device.

Checked with iosxe.rb, that is as same as ios.rb.

root@d97f3434de67:/# cat /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/model/iosxe.rb
IOS parser should work here

require_relative 'ios.rb'

IOSXE = IOS

In the ios.rb, we can see "show running-config" will be executed.

Could you advise if there is a solution that we can execute ""show running-config view full"" on IOSXE devices when we use iosxe.rb.

Cheers,
Brady

**Comment by Bierchermuesli** [comment]
funny, I was not aware `show running-config view full` exist :clown_face: 

I think there are three ways for fix this this: 

1. create a equal iosxe.rb but with desired XE commands (please make a PR)
2. lower the permission [like this](https://community.cisco.com/t5/network-management/privilege-5-access-show-running-config-not-working/m-p/3900929/highlight/true#M130040)
3. (In our case) set level 15 to the backup user via TACACS and limit the commands to certain show commands.
