### ISSUE TITLE
haml file synthax error with new version Oxidized 0.10 oxidized-web-0.6.0

### ISSUE THREAD

**Issue by alpern95** [ytti/oxidized#261]
/usr/local/rvm/gems/ruby-2.1.2/gems/oxidized-web-0.6.0/lib/oxidized/web/views/layout.haml
lines (9 10 11) replace : with =>

nano /usr/local/rvm/gems/ruby-2.1.2/gems/oxidized-web-0.6.0/lib/oxidized/web/views/head.haml
line 3 replace : with =>

And Sinatra is happy. its work

**Comment by ytti** [comment]
Is this same as ytti/oxidized-web#84

**Comment by alpern95** [comment]
Yes exactly the same.

**Comment by supertylerc** [comment]
Thanks, @alpern95.  This looks like an issue with versions of Ruby prior to 2.2.  As a workaround, if you switch to 2.2 or 2.3, the issue should no longer be present.

If you want, you can submit a PR to [oxidized-web](https://github.com/ytti/oxidized-web) to fix this for pre-2.2 users.  If not, I can submit the patch.

**Comment by supertylerc** [comment]
I opened ytti/oxidized-web#86 in the interest of fixing this sooner rather than later.

**Comment by ytti** [comment]
Fixed by d63989e536ed4e5f65cb6dbdd55ae693e37e707f

0.6.1 has been released
