### ISSUE TITLE
<NoMethodError: undefined method `proxy=' for Slack::Config:Module>) for event :post_store

### ISSUE THREAD

**Issue by captainfalcon23** [ytti/oxidized#2615]
Upgraded to latest docker image today of oxidized and it looks like there is some issue using proxy with slack hook:

E, [2022-09-01T11:28:12.256881 #29] ERROR -- : Hook slack (#<SlackDiff:0x000056298631d2c8>) failed (#<NoMethodError: undefined method `proxy=' for Slack::Config:Module>) for event :post_store

Any idea how to fix?

**Comment by captainfalcon23** [comment]
Probably likely to do with this commit...https://github.com/ytti/oxidized/pull/2576

**Comment by mc-dn** [comment]
Hi @captainfalcon23.  I made that commit.  I updated the Dockerfile for the new Ruby Slack client, but I did not build a container to test it.  It'll be a bit until I get to it, but I will test this out and get back to you.

**Comment by captainfalcon23** [comment]
Thanks @mc-dn . I ended up just using an old commit before the change was made and build my own container, but ideally would like to use the one provided by the project with the latest code :)

**Comment by mc-dn** [comment]
Thank you @ktims and @mortzu !
