### ISSUE TITLE
LibreNMS Oxidized Integration Error "pkeys are immutable on OpenSSL 3.0" - Ubuntu 22.04

### ISSUE THREAD

**Issue by nmsolutions-org** [ytti/oxidized#2616]
Hello, I'm having problems running Oxidized integrated with LibreNMS using Ubuntu 22.04, I'm having the error below in the logs:

**`raised OpenSSL::PKey::PKeyError with msg "pkeys are immutable in OpenSSL 3.0",`**

Using Ubuntu20. Using it I have no problems, it works0, does anyone know what might be next?

**Comment by mortzu** [comment]
duplicate of #2602
