### ISSUE TITLE
/usr/lib/ruby/2.5.0/net/protocol.rb:44:in `connect_nonblock': SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate) (OpenSSL::SSL::SSLError)

### ISSUE THREAD

**Issue by kalamchi75** [ytti/oxidized#2618]
Hi Guys, 

Suddenly my Oxidized crashed and I can only see this error in the log:

/usr/lib/ruby/2.5.0/net/protocol.rb:44:in `connect_nonblock': SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate) (OpenSSL::SSL::SSLError)

I was working fine for long time. I have always used HTTP. 
Not sure why it suddenly started complaining about SSL and the service won't start at all. 

HELP PLEASE

**Comment by Firefishy** [comment]
There is likely a HTTP -> HTTPS redirect happening somewhere. If self signed certificate used on the device, an option might be to import the cert into the trusted certificate store. Example see: https://manpages.ubuntu.com/manpages/jammy/man8/update-ca-certificates.8.html

This isn't a bug with oxidzed. It is specific to your usage.
