### ISSUE TITLE
Mix of Timezones

### ISSUE THREAD

**Issue by mark-herring-FIS** [ytti/oxidized#2623]
We are running Oxidized v.0.28.0 on a VM in the UK configured with it's date correctly set (as of September 21st 2022) to the BST timezone. We currently have 322 devices setup and when Oxidized runs we end up with a random mix of UTC and BST times in the Last Update column of the web GUI. Has anyone else seen this or dare I ask, fixed it? We assumed rightly/wrongly that this column should display the times in the timezone that the server is configured in i.e. in this case BST.

**Comment by dMailonG** [comment]
This is most likely a oxidized-web bug, not a oxidized one.
Check this [pull request](https://github.com/ytti/oxidized-web/pull/228) and it's [accompanying issue](https://github.com/ytti/oxidized/issues/2544).

**Comment by channdy** [comment]
I am currently facing this issue too and hope that there is a fixed

**Comment by mortzu** [comment]
Please create an issue at https://github.com/ytti/oxidized-web
