### ISSUE TITLE
PKey Error with OpenSSL 3.0

### ISSUE THREAD

**Issue by pjcolonna** [ytti/oxidized#2627]
I'm migrating to a new Ubuntu 22.02 server, using nginx, from our existing LibreNMS/Oxidized installation which was Ubuntu 20.02 with Apache. Everything seems to work with the integration between LibreNMS and Oxidized, but Oxidized is throwing errors trying to communicate with the same nodes that were in the previous router.db file. Config file was also migrated over from the previous server to the new server as well. The error I'm seeing in the crash log is as follows:
 
2022-09-29 19:35:28 UTC
dh#set_pqg= is incompatible with OpenSSL 3.0 [OpenSSL::PKey::PKeyError]
--------------------------------------------------
/var/lib/gems/3.0.0/gems/net-ssh-5.2.0/lib/net/ssh/transport/kex/diffie_hellman_group1_sha1.rb:124:in `set_pqg'
/var/lib/gems/3.0.0/gems/net-ssh-5.2.0/lib/net/ssh/transport/kex/diffie_hellman_group1_sha1.rb:124:in `generate_key'
/var/lib/gems/3.0.0/gems/net-ssh-5.2.0/lib/net/ssh/transport/kex/diffie_hellman_group1_sha1.rb:55:in `initialize'
/var/lib/gems/3.0.0/gems/net-ssh-5.2.0/lib/net/ssh/transport/algorithms.rb:398:in `new'
/var/lib/gems/3.0.0/gems/net-ssh-5.2.0/lib/net/ssh/transport/algorithms.rb:398:in `exchange_keys'
/var/lib/gems/3.0.0/gems/net-ssh-5.2.0/lib/net/ssh/transport/algorithms.rb:228:in `proceed!'
/var/lib/gems/3.0.0/gems/net-ssh-5.2.0/lib/net/ssh/transport/algorithms.rb:167:in `accept_kexinit'
/var/lib/gems/3.0.0/gems/net-ssh-5.2.0/lib/net/ssh/transport/session.rb:210:in `block in poll_message'
/var/lib/gems/3.0.0/gems/net-ssh-5.2.0/lib/net/ssh/transport/session.rb:190:in `loop'
/var/lib/gems/3.0.0/gems/net-ssh-5.2.0/lib/net/ssh/transport/session.rb:190:in `poll_message'
/var/lib/gems/3.0.0/gems/net-ssh-5.2.0/lib/net/ssh/transport/session.rb:225:in `block in wait'
/var/lib/gems/3.0.0/gems/net-ssh-5.2.0/lib/net/ssh/transport/session.rb:223:in `loop'
/var/lib/gems/3.0.0/gems/net-ssh-5.2.0/lib/net/ssh/transport/session.rb:223:in `wait'
/var/lib/gems/3.0.0/gems/net-ssh-5.2.0/lib/net/ssh/transport/session.rb:90:in `initialize'
/var/lib/gems/3.0.0/gems/net-ssh-5.2.0/lib/net/ssh.rb:246:in `new'
/var/lib/gems/3.0.0/gems/net-ssh-5.2.0/lib/net/ssh.rb:246:in `start'
/var/lib/gems/3.0.0/gems/oxidized-0.28.0/lib/oxidized/input/ssh.rb:27:in `connect'
/var/lib/gems/3.0.0/gems/oxidized-0.28.0/lib/oxidized/node.rb:67:in `run_input'
/var/lib/gems/3.0.0/gems/oxidized-0.28.0/lib/oxidized/node.rb:44:in `block in run'
/var/lib/gems/3.0.0/gems/oxidized-0.28.0/lib/oxidized/node.rb:38:in `each'
/var/lib/gems/3.0.0/gems/oxidized-0.28.0/lib/oxidized/node.rb:38:in `run'
/var/lib/gems/3.0.0/gems/oxidized-0.28.0/lib/oxidized/job.rb:9:in `block in initialize'

So, it looks like it's an issue with the DH groups that oxidized is using to communicate with the nodes via SSH, but I can't figure out how to fix it. The same config works fine on the existing server, so it has to have something to do with the upgrade to the new versions, but I'm at the end of my Linux knowledge at this point. Any pointers would be great.

**Comment by Firefishy** [comment]
Might be fixed in https://github.com/ytti/oxidized/pull/2570. I had similar OpenSSL 3.0 issue and master branch worked for me.

**Comment by pjcolonna** [comment]
Thank you for the info. I've updated net-ssh to version 7.0.0 (it had been at 5.2.0) but I don't see the spec/input/ssh_spec.rb file on my device. If I try and run the git pull https://github.com/ytti/oxidized.git command, I get a fatal error immediately.

**Comment by pjcolonna** [comment]
Rectified the issue, I rolled back my vm and reinstalled based off the git pull in #2570 and it works great now. I appreciate the assistance!
