### ISSUE TITLE
RouterOS 7  show-sensitive

### ISSUE THREAD

**Issue by DaveB91** [ytti/oxidized#2628]
Is it possible to build some logic into the RouterOS model file to detect if the target is version 7, and if so, instead of running just `/export` to run `/export show-sensitive`?
RouterOS 6 and earlier by default did this; however since RouterOS 7, the default is to hide-sensitive

The issue I am seeing is that previously the expectation was that Oxidized backups of devices had things like WiFi / PPP passwords, and now they don't - This makes it reasonably painful if you have to rely on the backup to rebuild a box.

**Comment by DaveB91** [comment]
I went and looked at the routeros.db file in your github after I posted this, and it looks like you have already done it - Updating mine now!

**Comment by mortzu** [comment]
can be closed?

**Comment by DaveB91** [comment]
Yes
