### ISSUE TITLE
output issue

### ISSUE THREAD

**Issue by pw19930507** [ytti/oxidized#2633]
How do I configure oxygenated config when I want to use both Output git and output file?
thanks

**Comment by gruffatremi** [comment]
As I have searched before, I think it is impossible to have 2 different outputs. 
You could output it to file and then do a cron task to push it to git?

**Comment by KiliorSelf** [comment]
> As I have searched before, I think it is impossible to have 2 different outputs. You could output it to file and then do a cron task to push it to git?
> 
> Look at #425 #426
Same conclusion here. I've done this way but versionning doesn't work if default output is set on "file".
