### ISSUE TITLE
Running under Supervisor

### ISSUE THREAD

**Issue by MrRJ45** [ytti/oxidized#264]
Just updated to 0.10 and had an issue with it attempting to create "/pid" which of course there is no permission for.

Changing line 61 in cli.rb to the following fixed this, how are other people running this?

@pidfile = File.expand_path("~/oxidized.pid")

**Comment by ytti** [comment]
Right. We probably want that file in Oxidized::Config::Root. I suppose it's now in relation to your working directory, and you're starting it in root?

Depends of course how it'll fit to the requirements of @ElvinEfendi

**Comment by justinjahn** [comment]
I had this issue as well.  My workaround was done using a custom systemd service file:

    [Unit]
    Description=Oxidized - Network Device Configuration Backup Tool

    [Service]
    WorkingDirectory=/home/oxidized
    PIDFile=/home/oxidized/pid

    ExecStart=/usr/local/bin/oxidized
    ExexReload=/bin/kill -HUP $MAINPID

    User=oxidized
    Group=oxidized

    [Install]
    WantedBy=multi-user.target

I'd imagine changing an initd or upstart file would be fairly straightforward as well.

HTH.

**Comment by MrRJ45** [comment]
It runs setting HOME to the path for the "oxidized" user it runs as, so ~ works fine in my use case.

If we store it in Oxidized root, no matter how people are running it should be able to write to that I would think :)

**Comment by MrRJ45** [comment]
I'll mark this as Closed as d46e75e should fix this
