### ISSUE TITLE
Dlink telnet authentication problem: extra character in password.

### ISSUE THREAD

**Issue by slopropul** [ytti/oxidized#2645]
Hi. I observe similar problems on the following models of Dlink switches:

DES-3028 H/W:A1
DES-3052 H/W:A1
DES-3200-{10,28,52} H/W: A1, B1
DES-3526 H/W: any
DES-3550 H/W: any

There are **no problems with other models of Dlink switches**.

A similar problem is described here https://github.com/ytti/oxidized/issues/1179

So, example:

switch - Dlink DES-3028 HW:A1
input - telnet
model - dlink
username - 'AbCd'
password - '12345'

_Result:_

```
             DES-3028 Fast Ethernet Switch Command Line Interface
                            Firmware: Build 2.94.B21
           Copyright(C) 2008 D-Link Corporation. All rights reserved.
User Access Verification
Username:AbCd
Password:******
Fail!
User Access Verification
Username:
Fail!
User Access Verification
Username:
```

We see an extra character in the password.

If line 38 in /input/telnet.rb is replaced
from
`return send(cmd_str + "\r\n") unless expect`
to
`return send(cmd_str) unless expect`

_Result:_

```
   DES-3028 Fast Ethernet Switch Command Line Interface
                            Firmware: Build 2.94.B21
           Copyright(C) 2008 D-Link Corporation. All rights reserved.
User Access Verification
Username:AbCdA
```

We see that the extra character is the first character of the username.
Experiments to change the first character of the username confirmed this.

Manual telnet is ok.
Any ideas?

**Comment by M3D3** [comment]
Привет, всем! Такая же проблема с Dlink 3200

**^[[0m^[[2J^[[1;1H^[[2J^MD^M
^M                        DES-3200-10 Fast Ethernet Switch
^M                             Command Line Interface

^M                           Firmware: Build 1.52.B010
^M           Copyright(C) 2010 D-Link Corporation. All rights reserved.
^M^MUsername:oxydized
^M^MPassword:***********
^MFail!
^M^MUsername:**

**Comment by AntonBelogolovskiy** [comment]
Hello!
I found a solution to the problem with D-Link.
Necessary before entering a login, password, etc. type Backspace (\b).
To do this, I corrected the /lib/oxidized/input/telnet.rb code:

def cmd(cmd_str, expect = @node.prompt)
      Oxidized.logger.debug "Telnet: #{cmd_str} @#{@node.name}"
      # Send 'Backspace' before command for some D-Link issues
      send("\b\b\b")
      #
      return send(cmd_str + "\r\n") unless expect

      # create a string to be passed to oxidized_expect and modified _there_
      # default to a single space so it shouldn't be coerced to nil by any models.

      out = String(' ')
      @telnet.puts(cmd_str)
      @telnet.oxidized_expect(timeout: @timeout, expect: expect, out: out)
      out
    end

**Comment by AntonBelogolovskiy** [comment]
Hello!
I found a solution to the problem with D-Link.
Necessary before entering a login, password, etc. type Backspace (\b).
To do this, I corrected the /lib/oxidized/input/telnet.rb code:

def cmd(cmd_str, expect = @node.prompt)
Oxidized.logger.debug "Telnet: #{cmd_str} @#{@node.name}"
# Send some 'Backspaces' before command for some D-Link issues
send("\b\b\b")
#
return send(cmd_str + "\r\n") unless expect

Everything is working fine now.

**Comment by AntonBelogolovskiy** [comment]
"Hello!
I found a solution to the problem with D-Link.
Necessary before entering a login, password, etc. type Backspace (\b).
To do this, I corrected the /lib/oxidized/input/telnet.rb code:

def cmd(cmd_str, expect = @node.prompt)
Oxidized.logger.debug "Telnet: #{cmd_str} @#{@node.name}"
#Send some 'Backspaces' before command for some D-Link issues
send("\b\b\b")

return send(cmd_str + "\r\n") unless expect
...
...

Everything is working fine now."

**Comment by AntonBelogolovskiy** [comment]
Hello!
I found a solution to the problem with D-Link.
Necessary before entering a login, password, etc. type Backspace (\b).
To do this, I corrected the /lib/oxidized/input/telnet.rb code:

def cmd(cmd_str, expect = @node.prompt)
Oxidized.logger.debug "Telnet: #{cmd_str} @#{@node.name}"
#Send some 'Backspaces' before command for some D-Link issues
send("\b\b\b")

return send(cmd_str + "\r\n") unless expect
...
...

Everything is working fine now.

**Comment by AntonBelogolovskiy** [comment]
Hello!
I found a solution to the problem with D-Link.
Necessary before entering a login, password, etc. type Backspace (\b).
To do this, I corrected the /lib/oxidized/input/telnet.rb code:

def cmd(cmd_str, expect = @node.prompt)
  Oxidized.logger.debug "Telnet: #{cmd_str} @#{@node.name}"
  #Send some 'Backspaces' before command for some D-Link issues
  send("\b\b\b")

  return send(cmd_str + "\r\n") unless expect
...
...

Everything is working fine now.
