### ISSUE TITLE
PID file access error

### ISSUE THREAD

**Issue by gruffatremi** [ytti/oxidized#2663]
Hello, when I am trying to run the new version with non root user, I have the issue of not having access to the pid file anymore. 

Thanks for the help !
![image](https://user-images.githubusercontent.com/71137818/202860700-ac2af2f2-a1b8-400e-b8a1-b8169996bcaa.png)

**Comment by a1ad** [comment]
You need to change the pid file location in the config file to: pid: "/home/oxidized/.config/oxidized/pid" like all the other file locations, look at this: https://github.com/ytti/oxidized/issues/2664

**Comment by gruffatremi** [comment]
Ok yes I feel so stupid, I change the location in my Docker compose file but not in the oxidized config file... I forgot it has link to root folder...

**Comment by a1ad** [comment]
Join the club :)
