### ISSUE TITLE
Problem with hirschmann

### ISSUE THREAD

**Issue by StanislasRo** [ytti/oxidized#2672]
Hello,

I want to add hirschmann switches to my oxidized conf.
I think I'm doing something wrong but I can't find what.
I can only connect with telnet while my other devices work with SSH.

**Part of my oxidized config :**
groups:
    group3:
        vars:
            username: xxx
            password: xxx
input:
  default: ssh, telnet
  debug: false
  ssh:
    secure: false
  utf8_encoded: true
source:
  default: csv
  csv:
    file: /home/oxidized/.config/oxidized/router.db
    delimiter: !ruby/regexp /:/
    map:
      name: 0
 ername: 1
      password: 2
      group: 3
      model: 4
model_map:
  asa: asa
  cisco: ios
  nexus: nxos
  hirschmann: hirschmann

Exemple of my router.db :
#### ip:username:password:group:modele

xxx:xxx:xxx:group3:hirschmann

With debug, I get these logs :
DEBUG -- : resolving DNS for xxx...
DEBUG -- : lib/oxidized/worker.rb: Added group3/xxx to the job queue
DEBUG -- : lib/oxidized/job.rb: Starting fetching process for xxx at 2022-11-30 09:39:44 UTC
DEBUG -- : lib/oxidized/input/ssh.rb: Connecting to xxx
DEBUG -- : xxx raised Errno::ECONNREFUSED with msg "Connection refused - connect(2) for xxx:22"
DEBUG -- : lib/oxidized/node.rb: Oxidized::SSH failed for xxx
DEBUG -- : lib/oxidized/input/cli.rb: Running post_login commands at xxx
DEBUG -- : lib/oxidized/input/cli.rb: Running post_login command: "enable", block: nil at xxx
DEBUG -- : Telnet: enable @xxx
DEBUG -- : Telnet: show sysinfo @xxx
WARN -- : xxx raised Net::ReadTimeout (rescued Timeout::Error) with msg "timed out while waiting for more data"
DEBUG -- : lib/oxidized/node.rb: Oxidized::Telnet failed for xxx
DEBUG -- : lib/oxidized/job.rb: Config fetched for xxx at 2022-11-30 09:40:04 UTC
WARN -- : group3/xxx status no_connection, retry attempt 1

I can connect from oxidized VM and use commands like show run on it.

Do you have any idea of what can I do to add these switches ?

Thanks and have a good day !

Stan

**Comment by StanislasRo** [comment]
Solution found, I had to change something on hirschmann.rb configuration file.

**Comment by StanislasRo** [comment]
Hello, I'm out of office but next week I can help you !

**Comment by StanislasRo** [comment]
8th May is public holiday in France, I'll be at work tomorrow

**Comment by StanislasRo** [comment]
Hello, I changed the following file : /var/lib/gems/2.5.0/gems/oxidized-0.26.3/lib/oxidized/model/hirschmann.rb

**From**
class Hirschmann < Oxidized::Model
  prompt /^[(\w\s)]+\s[>|#]+?$/

  comment '## '

  # Handle pager
  expect /^--More--.*$/ do |data, re|
    send 'a'
    data.sub re, ''
  end

  cmd :all do |cfg|
    cfg.cut_both
  end

  cmd 'show sysinfo' do |cfg|
    cfg.gsub! /^System Up Time.*\n/, ""
    cfg.gsub! /^System Date and Time.*\n/, ""
    cfg.gsub! /^CPU Utilization.*\n/, ""
    cfg.gsub! /^Memory.*\n/, ""
    cfg.gsub! /^Average CPU Utilization.*\n/, ""
    comment cfg
  end

  cmd 'show running-config' do |cfg|
    cfg.gsub! /^users.*\n/, ""
    cfg
  end

  cfg :telnet do
    username /^User:/
    password /^Password:/
  end

  cfg :telnet, :ssh do
    post_login 'enable'
    pre_logout 'logout'
  end
end


**To**
class Hirschmann < Oxidized::Model
  prompt /^[\(\w\s\w\)]+\s[>|#]+?$/

  comment '## '

  cmd :all do |cfg|
    cfg.each-line.to_a[1..-2].join
  end

  cmd 'show running-config' do |cfg|
    cfg
  end

  cfg :telnet do
    username /^User:/
    password /^Password:/
  end

  cfg :telnet, :ssh do
    post_login 'enable'
    pre_logout 'logout'
  end
end

**Comment by Frowwny** [comment]
What does your router.rb file and config file look like when using the Hirschmann.

Thanks,

Christian Welch
Wave Technologies
214-517-2081
________________________________

**Comment by Frowwny** [comment]
What does your router.rb and config file look like?

Christian Welch
Wave Technologies
Cell: 214-517-2081

**Comment by Frowwny** [comment]
I am still getting the error message saying unable to detect prompt.
________________________________

**Comment by StanislasRo** [comment]
Hello, my router.rb looks like that : 
#### ip:username:password:group:model

And my config file looks like :
username : default username
password : default password
model : default model
resolve_dns: false
interval: 86400
log: file log
use_syslog: false
debug: false
threads: 30
timeout: 20
retries: 2
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: ip:port
next_adds_job: false
vars: {}
groups
    group3:
        vars:
            auth_methods: ["password", "none", "public_key", "keyboard-interactive"]
            username : default username
            password : default password
pid: file pid
crash:
  directory: file crash
stats:
  history_size: 10
input:
  default: ssh, telnet
  debug: false
  ssh:
    secure: false
  utf8_encoded: true
output:
  default: file
  file:
    directory: directory file
source:
  default: csv
  csv:
    file: file router.db
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      username: 1
      password: 2
      group: 3
      model: 4
model_map:
  hirschmann: hirschmann
