### ISSUE TITLE
Variables available in models

### ISSUE THREAD

**Issue by mark-herring-FIS** [ytti/oxidized#2673]
This is more of a question than an issue, so I hope it doesn't get removed. I was wondering if it's possible to retrieve the name of the device from within the model? I'm not a Ruby programmer and this one has currently beaten me. I've found if I use #{name} that seems to return the name of the Class (might be wrong but that is what it looks like). Is there another variable like this that will give me what I need?
Any help appreciated.

**Comment by ytti** [comment]
Could you try just node please. `#{node.name}`

We should expose `node` in model.rb here:
```ruby   
117	    attr_accessor :input, :node
```

And in node.rb we should expose the node to the model:
```ruby
    35	      @model.node = self
```

**Comment by ytti** [comment]
Hmm actually it probably won't work in top level `cmd` because that is class scope not instance scope, where as `node` is exposed only on the instance scope. We could work around this by something like this

```ruby
pre do ## or post do, doesn't matter, post/pre is just position of the output
   cmd "type #{node.name}"
end
```

You don't need the block, if you're not modifying the string.

**Comment by mark-herring-FIS** [comment]
> Hmm actually it probably won't work in top level `cmd` because that is class scope not instance scope, where as `node` is exposed only on the instance scope. We could work around this by something like this
> 
> ```ruby
> pre do ## or post do, doesn't matter, post/pre is just position of the output
>    cmd "type #{node.name}"
> end
> ```
> 
> You don't need the block, if you're not modifying the string.

ytti, you were absolutely spot on, this worked a treat. The file has come back in a somewhat odd-looking fashion though. In the web GUI we are seeing the xml heavily corrupted. I switched debug on, and the logs are showing: -

...
^[[31;1H        <NumSimultaneousAccepts>20</NumSimultaneousAccepts>                     ^[[31;44HltaneousAccepts>
^[[32;1H        <TimedCacheExpirySecs>60</TimedCacheExpirySecs>                         ^[[32;22HpirySecs>60</TimedCacheExpirySecs>
^[[33;1H        <LocalIP>10.254.225.57</LocalIP>
^[[34;1H        <DisabledPrompt>This account has been disabled</DisabledPrompt>         ^[[34;17HdPrompt>This account has been disabled</DisabledPrompt>
^[[35;1H        <OTPSeparator>*</OTPSeparator>                                          ^[[35;31Hparator>
^[[36;1H        <PasswordPrompt>Password: </PasswordPrompt>
^[[37;1H        <UserNamePrompt>Username: </UserNamePrompt>                             ^[[37;32He: </UserNamePrompt>
...

If I'm not wrong these seem to be VT100 cursor position escape codes. All we want is the XML file with its proper formatting (which incidentally is what we see if we log in and run the command interactively).

Any ideas welcome.

**Comment by ytti** [comment]
Seems fairly trivial string manipulation problem to remove the control codes. We have one example at least in `procurve` model but there are plenty of other solutions. Not really oxidized problem.

**Comment by mark-herring-FIS** [comment]
Thanks, ytti. I did look at the `procurve` model but it didn't seem to work for this case. I'll have another play and see if I can get it working.
