### ISSUE TITLE
Cisco IOS "show version" issues

### ISSUE THREAD

**Issue by MrRJ45** [ytti/oxidized#268]
I have just noticed an issues with the "show version" function in ios.rb, at least when using Telnet

Looking at the code it was running this:

```comment cfg.lines.first```

However, the first entry in the array was "show version".

It looks like something has changed meaning that the command itself is echo'd back and included in the text. The second line is the correct version string.

```comment cfg.lines[1]``` fixes this for me, but this may of course break other peoples installs.

It looks like this broke when I upgraded to Oxidized 0.10

**Comment by ytti** [comment]
Hmm. 
https://github.com/ytti/oxidized/blob/master/lib/oxidized/model/ios.rb#L22

Should remove the first and last line.

**Comment by MrRJ45** [comment]
I've just modified that line so it doesnt strip the first line. The first two lines are:

====================== show version ======================
show version

So, it is stripping the first... not sure where that first line is coming from.

**Comment by ytti** [comment]
Aaah, right:
https://github.com/ytti/oxidized/blob/master/lib/oxidized/model/model.rb#L82

@ElvinEfendi  is this something you feel strongly about?

I would prefer not to have it, but if it's very important that we do have it, I think it should be added in model.rb after the model has been processed. Now it's injected there before.
Perhaps cleanest solution would be to make output decorator method, which is called if output: decorate: true is set?

**Comment by ElvinEfendi** [comment]
@ytti it is not very important. I put it there just to separate/group the output for clarity. I'll remove it asap because I've just realized that a lot of model parsing relies on line numbers.

How would you place that decoration for each command execution after the output has been processed? In my understanding this would require another parsing of the output to identify which command output starts and ends where - which does not worth it, imho.

**Comment by ytti** [comment]
https://github.com/ytti/oxidized/blob/master/lib/oxidized/model/model.rb#L92

Couldn't you here just add 'string' to the 'out'. Or perhaps even make a decorator hook, passing the string and out, and expecting string in return.

**Comment by ytti** [comment]
I'm open to adding decorators in one way or another. But if wanted better to have separate issue, closing.
