### ISSUE TITLE
docker no longer works for me been running for some time.

### ISSUE THREAD

**Issue by LoveSkylark** [ytti/oxidized#2681]
my oxidized: docker is failing to to start after an upgrade. 
logs are showing the error: "/bin/chown: invalid user: ‘root:root’"

I thought the docker was using 30000:30000?

**Comment by LoveSkylark** [comment]
Sorry info was badly written.

It appear that in the new docker version the root user has been phased out but there er still some references to it in the my_init.d files:

*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/my_init.d/10_syslog-ng.init...
 /bin/chown: invalid user: ‘root:root’
*** /etc/my_init.d/10_syslog-ng.init failed with status 1
*** Killing all processes...

**Comment by Lavaburn** [comment]
Also related to this, I am getting error '/etc/container_environment': Permission denied when running as oxidized user
