### ISSUE TITLE
SwOS model not working due to HTTP Digest

### ISSUE THREAD

**Issue by BeryJu** [ytti/oxidized#2685]
Relevant PR #2674

SwOS seems to use HTTP Digest auth in the browser (the initial WWW-Authenticate header is received on `/sys.b`), however this model implementation seems to only use HTTP basic

Identical behaviour on both CSS106-1G-4P-1S and CSS326-24G-2S+

**Comment by Foberski** [comment]
Hi, shame this is not working. However when i execute this command it does seem to download something, might this help?

sudo wget -q --user admin --ask-password "http://192.168.1.1/backup.swb"

**Comment by BeryJu** [comment]
That does seem to work, however only with a non-blank password, assuming that wget does all of the "heavy lifting" for Digest auth. I'll try in oxidized with password too

**Comment by antonxoxlov** [comment]
Will work continue on implementing support for digest auth in input/http.rb?

**Comment by 0xc0decafe** [comment]
Well, I tried just that, but input/http.rb seems to be borked. I never get any debug output even when I explicitly add it to _get_http()_  .... I theory I've solved the issue (by using ``require "net/http/digest_auth"``), in praxis i don't think http.rb ever woked xD

That said, why is this issue closed? To my understanding its unresolved and very valid.

**Comment by Xeudoron** [comment]
> Well, I tried just that, but input/http.rb seems to be borked. I never get any debug output even when I explicitly add it to _get_http()_ .... I theory I've solved the issue (by using `require "net/http/digest_auth"`), in praxis i don't think http.rb ever woked xD

Hi there, how can I add `require "net/http/digest_auth"` into the /lib/oxidized/input/http.rb? I am running docker compose, but was unable to verify it. When building with Dockerfile I see that it does `gem install oxidized-web`, from which I suppose my changes do not apply.

I tried copying my custom `http.rb` into `/var/lib/gems/3.0.0/gems/oxidized-0.29.1/lib/oxidized/input/`, but that did not change the outcome.

Thank you
