### ISSUE TITLE
How to use vars from router.db in model?

### ISSUE THREAD

**Issue by metaIhead** [ytti/oxidized#2687]
for example:
 in router.db
router1:model:somelogin:p@ssword:172.0.0.2:22

pseudocode
cmd 'echo #node.password'

and get p@ssword

**Comment by aschaber1** [comment]
https://github.com/ytti/oxidized/blob/39ac226d90cc5855e74bdd7906b90a627c11aa24/lib/oxidized/node.rb#L25

hey, maybe try auth.password. I'm not sure, but maybe this helps.
