### ISSUE TITLE
MOTD causing ios.rb issues

### ISSUE THREAD

**Issue by murrant** [ytti/oxidized#269]
I am getting the following error when fetching from my IOS devices that have an MOTD set.  It seems as though the prompt regex isn't working correctly.  It is odd that it puts both the motd and prompt on the same line.  After the third attempt, it must throw some safety checks out the window, because it succeeds in fetching the config then.

```
raised Oxidized::PromptUndetect with msg "**DO NOT ATTEMPT LOGIN UNLESS AUTHORIZED. ALL LOGIN ATTEMPTS ARE LOGGED!!**algona.rtr# not matching configured prompt (?-mix:^([\w.@()-]+[#>]\s?)$)"
```

**Comment by ytti** [comment]
It probable changed from ssh to telnet after 3rd time, and didn't experience same issue over other protocol?
Can you verify manually ssh and telnet, to see if they look different? Perhaps you need to add newline to the end of the MOTD?

**Comment by murrant** [comment]
Yes, it was falling back to telnet, I had enabled that for testing something else and forgot.
Adding a new line at the end of the MOTD in the device's config did work around the issue nicely.

**Comment by ytti** [comment]
Just to elaborate bit on this.

Most platforms we support rely on screen-scraping to determine when command starts and end, the crucial indicator for this is detecting a prompt. 
If you didn't have new line on MOTD, then your prompt likely started somewhere else than start of line, which we subsequently didn't detect as prompt, and kept waiting forever to see prompt, so we could issue a command.

Of course we could make prompt detection more relaxed, but then there is risk that we'll detect prompt somewhere where it is not, like perhaps MOTD content could be determined to be a prompt, if we detect prompt where there is none, whole program is again broken.

Some platforms, like Juniper JunOS support opening multiple SSH exec channels over single SSH tcp connection, when this is possible, we are able to collect commands without employing any screen-scraping. This is vastly more reliable, but unfortunately not well supported by vendors.
