### ISSUE TITLE
powerconnect - Last lane is missing

### ISSUE THREAD

**Issue by thomasbruchet** [ytti/oxidized#2692]
Hello

On my backup of Dell PowerConnect, the last lane is missing. 

show run on system

```
sntp client poll timer 64
sntp unicast client enable
sntp unicast client poll
sntp anycast client enable
sntp server xx.xx.xx.xx poll
sntp server xx.xx.xx.xx poll

```

Oxidized:
```
sntp client poll timer 64
sntp unicast client enable
sntp unicast client poll
sntp anycast client enable
sntp server xx.xx.xx.xx poll
```

How can I fix that ?

**Comment by thomasbruchet** [comment]
Up
Is anyone can provide some help on this issue ?

**Comment by shlermoulodi** [comment]
Might be cause of this.. https://github.com/ytti/oxidized/blob/637434b94055d4227aaae295958157a9af0cd788/lib/oxidized/model/powerconnect.rb#L12

this cuts off a few lines at the end of the output.

**Comment by thomasbruchet** [comment]
Your are right. 
I've edited the model /var/lib/gems/2.5.0/gems/oxidized-0.28.0/lib/oxidized/model/powerconnect.rb int the docker container, changed -3 to -2 and that work.
`cfg.each_line.to_a[1..-2].join `

Thank you
