### ISSUE TITLE
Oxidized cant connect devices using SSH key in RHEL9

### ISSUE THREAD

**Issue by syl4r1337** [ytti/oxidized#2693]
He had to change LibreNMS + Oxidized from RHEL8 -> RHEL9. Password logging works fine, but login with key gives this kind of error: _raised OpenSSL::PKey::PKeyError with msg "EVP_DigestSignInit: invalid digest"_

I have tried to google this for few days, but not that many hits, and it's also pretty difficult because I really have no idea how Ruby works or have any knowledge of this sort of things at all. Found some post that says that I should get oxidized from the github instead of the gem repo and i've tried that. Probably it's because I have no idea how it's supposed to work, I still get the same 0.28.0 version no matter if it's from gem repo or github. Is that the newest one or is it not and I'm having this issue because of some old version of Oxidized?

**Comment by syl4r1337** [comment]
Some update: It seems that the key auth works with Junos devices and some HPE devices with newer software. With Cisco devices I get the error. 

When migrated the Oxidized to newer platfom it naturally got updated. So it seems that there might be something that prevents connecting to Cisco devices because of some crypto related legacy stuff?

**Comment by dlonghi** [comment]
From RHEL 9.x to Cisco IOS XR, I am able to ssh to the device using this paramenter:

`ssh -oKexAlgorithms=+diffie-hellman-group14-sha1 user@cisco-ios-xr-router.local.net`
