### ISSUE TITLE
Arbitrary unresolvable 'name' with a resolvable dns entry in another field

### ISSUE THREAD

**Issue by ACP-shaun** [ytti/oxidized#2694]
Hi,

I've been trying to setup oxidized to use an arbitrary device name like 'siteXyzRouter1' but use DNS to resolve the host to connect to, such as Router1.something.here.com

My source map looks like this:
```
map:
      name: 0
      model: 1
      ip: 2
      group: 3
```

my router.db csv looks like this:
`siteXyzRouter1:juniper:Router1.something.here.com:GroupName
`

Log output looks like this:
`node {:name=>"siteXyzRouter1", :model=>"junos", :ip=>"Router1.something.here.com", :group=>"GroupName"} is not resolvable, raised Resolv::ResolvError with message 'no address for siteXyzRouter1'`

It works fine if I either put a resolvable dns name in the 'name' field, or an IP address in the 'ip' field.

I've yet to find configuration that will get name resolution on the 'ip' field, or find a field appropriate for setting a name of a device not intended for dns resolution.

I'd like to avoid having to write a hosts file to provide the local name resolution if at all possible.

Thanks!

**Comment by Baeth** [comment]
2026 and the isue remains...
