### ISSUE TITLE
Create a model with expect - Cisco 1900

### ISSUE THREAD

**Issue by lucdnb** [ytti/oxidized#2702]
Hi team.
I know that the developers guys (@ytti ) have no more responding to us, so I'll try some our community help here.

I have a needance to create a model for a Cisco 1900 model, wich no one existing model works.

This Cisco model have an "User Interface Menu" before ask for credentials, showing "Press any key to continue.".
After, it pass to a other user interaction in witch ask for "K" key to enter in CLI mode.

I havent success to create a model with "expect" to handle it.

Has anyone ever had a problem with this?

**Comment by mortzu** [comment]
Take a look at https://github.com/ytti/oxidized/blob/master/lib/oxidized/model/linksyssrw.rb

**Comment by systeembeheerder** [comment]
> Cisco 1900 model,

Cisco 1900 Series Integrated Services Router? Cisco Catalyst 1900 Series Switches? Which "model" is it exact? 
Both use https://github.com/ytti/oxidized/blob/master/lib/oxidized/model/ios.rb


No need to point to the developers; both ios.rb and linksyssrw are very well supported.
