### ISSUE TITLE
Automatically reloading the list of nodes

### ISSUE THREAD

**Issue by mikebryant** [ytti/oxidized#271]
When using the HTTP source, it would be useful if Oxidized automatically called the reload method every X seconds (configurable)

I'm happy to try writing this, I could for example add something to the start of the Worker.work method, or add a separate thread to do so.. What would be the preferred style of implementation?

**Comment by ytti** [comment]
The reload isn't exactly cheap now. I've wanted to change the core behaviour quite a much, move state from memory to sqlite. And only state in memory is the nodes currently being fetched.
This would also make reload much cheaper operation. 

Worker#work runs really often, so it's not really applicable place for potentially expensive operation. Right now I'm thinking, how will any solution be superior to crontab having curl .../reload.json every so often?

**Comment by mikebryant** [comment]
I wasn't thinking of reloading each iteration, but of using that as a place to check for last update time, and if it's over the set interval, reload and set a new update time. 

I could do it with a crontab, but I'm looking at deploying this in a docker environment, so I guess I'd need to change the current docker file to put in a process supervisor, that then runs an instance of cron and oxidized.. And possibly have it parse the same config file, so configuration would still be in one place. 

The motivation for having it inside the oxidized process would be simpler deployments, with less moving parts - then a user can just tweak one value in the config file.

**Comment by laf** [comment]
In LibreNMS we've done this by calling reload in the API when a new device is added. Maybe you could do something similar within whatever application your are using to feed the data to Oxidized?

**Comment by mikebryant** [comment]
I suppose that might be possible.. Would be handy to have it immediately update, certainly.
I'll still need a periodic refresh, as I can't guarantee such an api call will be successful. (Given things like chaos monkey and unreliable transports). I need to make sure it'll heal itself eventually.

**Comment by ytti** [comment]
Same system which does it triggered. Could also do it nightly to fix any chaos monkeys?

**Comment by mikebryant** [comment]
Scheduled tasks in the other app would be a problem. I guess if this isn't something that's wanted in Oxidized itself, I'll write a Dockerfile that includes a supervisor and cron for my deployment.

Do you want any pull requests relating to this, or shall I just maintain it separately?

**Comment by ytti** [comment]
I'ma happy to accept PR's for the docker file, but I don't think the scheduled HTTP GET is universal enough. Perhaps if you make it configurable, via environment variable or something?

**Comment by mikebryant** [comment]
Yeh, as I said in the first comment, I want the interval to be configurable. (And that includes setting it to 0 / empty meaning not enabled - which I'd have as the default)

I want this as an optional feature I can then turn on, rather than a new default behaviour.

Environment variable is probably the best way.
