### ISSUE TITLE
[githubrepo] SSH git repos don't work when building from Dockerfile

### ISSUE THREAD

**Issue by ktims** [ytti/oxidized#2711]
The `rugged` ruby module must be built with the `--with-ssh` option to include support for SSH git repos. When the current `Dockerfile` runs, it calls `gem install rugged --with-ssh`, which installs the latest version. However, the `gemspec` pins the version of rugged at a specific version (1.5.0.1), which is currently different than the latest (1.5.1). So something (Bundler?) installs the gemspec version without `--with-ssh`, and this version is used at runtime.

I'm not a Ruby dev, so I'm not sure the best way to fix this. I tried modifying the Dockerfile to run `gem install -g Gemfile rugged -- --with-ssh` instead, but this seems to install all the listed dependencies and not just `rugged` as I intended, though I'm not sure that's really a problem, it's probably what the Dockerfile should be doing anyway? Pinning the version in the Dockerfile is another solution, but seems like it will easily go out of sync and cause the same problem in the future.

**Comment by westerterp** [comment]
Same issue here since around the beginning of Febuary. That coincides with a new release of `rugged` (https://rubygems.org/gems/rugged/versions)

Wouldn't the quick n' dirty "fix" be to increase the version used in the `gempsec`? https://github.com/ytti/oxidized/blob/master/oxidized.gemspec#L26

**Comment by packettoobig** [comment]
See my comment there :  https://github.com/ytti/oxidized/issues/1038#issuecomment-1472141340
I 
as @westerterp says, I think we should change https://github.com/ytti/oxidized/blob/master/oxidized.gemspec#L26
From 
```
  s.add_runtime_dependency 'rugged',  '~> 1.5.0.1'
```
To
```
  s.add_runtime_dependency 'rugged',  '>= 1.5.0'
```

We could even do
```
  s.add_runtime_dependency 'rugged',  '>= 1.5.0, <1.6.0'
```
Just in case they include breaking changes in 1.6.
