### ISSUE TITLE
Append version to Docker Image

### ISSUE THREAD

**Issue by terrytrent** [ytti/oxidized#2713]
As of 4 years ago all docker images are tagged with latest - I would like to be able to see the docker images tagged with appropriate version numbers so I can see what was changed in each version, and which oxidized tagged version is running in the container.

**Comment by ytti** [comment]
There was build commit in Docker latest in `oxidized --version`. During [rake install]
](https://github.com/ytti/oxidized/blob/master/Rakefile#L37) we [manipulate]
](https://github.com/ytti/oxidized/blob/master/lib/oxidized/version.rb#L4-L18) version string to reflect latest commit. 

@ctomkow you're welcome to change the process as you feel.

**Comment by ctomkow** [comment]
Hi @ytti. Thanks for responding. For now, I will work on a PR for some github actions to tag the built container images with the a commit tag (reflecting how oxidized --verison displays things) and maybe a secondary tag with a build date (for a sequential build order).

Regarding the project needs, I totally agree. The need for support by organizations is a pain point for open source software for sure. This is demonstrated by the recent conversations about the core-js dev/maintainer (if you heard about that).

I do development work for my organisation, and while I cannot be a full-time maintainer, I can start contributing where I can. I haven't written Ruby before, but I am familiar with build/release/packaging. This seems to be a pain-point for many (that are unfamiliar with software development) that I can help with.
