### ISSUE TITLE
Problem with systemd service and PID creation?

### ISSUE THREAD

**Issue by sorano** [ytti/oxidized#272]
I am trying to get oxidized running as a non-root user using the systemd script (oxidized.service) found in /extra.

However it doesn't want to start correctly with systemctl. The problem seems to be when I start the service it wants to create a pid file under root (/) where there is no permissons to create it.

I installed oxidized following the Debian instructions.

My server is running Ubuntu 15.10.
ruby -v
ruby 2.1.5p273 (2014-11-13) [x86_64-linux-gnu]

which oxidized
/usr/local/bin/oxidized

cat /lib/systemd/system/oxidized.service 
```
#For debian 8 put it in /lib/systemd/system/
#and call it with systemctl start oxidized.service

[Unit]
Description=Oxidized - Network Device Configuration Backup Tool

[Service]
ExecStart=/usr/local/bin/oxidized
User=oxidized

[Install]
WantedBy=multi-user.target
```

Trying to start the service:

sudo systemctl start oxidized.service
sudo systemctl status oxidized.service
```
 oxidized.service - Oxidized - Network Device Configuration Backup Tool
   Loaded: loaded (/lib/systemd/system/oxidized.service; disabled; vendor preset: enabled)
   Active: inactive (dead)

jan 19 14:33:18 nms systemd[1]: Started Oxidized - Network Device Configuration Backup Tool.
jan 19 14:33:19 nms oxidized[30182]: Permission denied @ rb_sysopen - /pid
```
So the above fails since it cannot create the pid file.

However, if I run the oxidized binary without the script as oxidized user it starts:

sudo su oxidized
oxidized@nms:~$ pwd
/home/oxidized

oxidized 
I, [2016-01-19T14:48:07.104027 #2093]  INFO -- : Oxidized starting, running as pid 2093

cat /home/oxidized/pid
2093

I am wondering if it is possible to control where oxidized tries to create it's PID file?

**Comment by laf** [comment]
I believe this is the same issue as: https://github.com/ytti/oxidized/issues/264

A pr was merged to fix this.

**Comment by sorano** [comment]
It sure looks like the same issue. :+1: 

I'll close this issue :)
