### ISSUE TITLE
Ubiquiti ToughSwitch aka EdgeSwitch 5/8XP

### ISSUE THREAD

**Issue by bdg-robert** [ytti/oxidized#2722]
With version 2.x of the software for the ToughSwitch line (now rebranded to EdgeSwitch XP), they've changed how the device identifies itself from airos to edgeswitch. Unfortunately, this is problematic because the [edgeswitch model](https://github.com/ytti/oxidized/blob/master/lib/oxidized/model/edgeswitch.rb) does not work for this version - it should still function identically to how the [airos model](https://github.com/ytti/oxidized/blob/master/lib/oxidized/model/airos.rb) retrieves its configs.

Can the edgeswitch model be updated to account for this? I'm willing to do the work, but I need some guidance.

Cheers.

**Comment by mortzu** [comment]
Just backup the EdgeSwitch XP as airos model?
