### ISSUE TITLE
opengear no_connection

### ISSUE THREAD

**Issue by chrisch80** [ytti/oxidized#2740]
Hello,

I would like to add opengear devices to oxidized (0.28.0), but for some reason it is not working.

I have enabled debug in the config:

```
`# /opt/oxidized/.config/oxidized/config
---
username: <removed>
password: <removed>
model: cisco
resolve_dns: true
interval: 43200
use_syslog: true
log: /opt/oxidized/.config/oxidized/logs/
debug: true
rest: false
threads: 30
timeout: 1200
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
next_adds_job: false
pid: "/opt/oxidized/pid"
rest: 127.0.0.1:8443/oxidized
vars:
  remove_secret: false
input:
  default: ssh, telnet
  debug: true
  ssh:
    secure: false
output:
  default: git
  git:
    user: Oxidized
    email: <removed>
    single_repo: true
    repo: "/var/lib/oxidized/devices.git"
  debug: true
source:
  default: sql
  debug: true
  sql:
    adapter: mysql2
    host: localhost
    database: oxidized
    table: nodes
    user: <removed>
    password: <removed>
    query: "SELECT * FROM nodes WHERE n_enabled = True"
    map:
      name: n_name
      ip: n_ip
      model: n_model
      group: n_group
model_map:
  cisco-iosxe: ios
... <removed some parts>
  opengear: opengear

groups:
  <name removed>:
    username: <removed>
    password: <removed>
  <name removed>:
    username: <removed>
    password: <removed>
models: {}

hooks:
  export_git_to_file:
    type: exec
    events: [post_store]
    cmd: 'cd /opt/oxidized/output/files/ && git pull'
    async: true
    timeout: 40
  log2file_node_fail:
    type: exec
    events: [node_fail]
    cmd: 'DATETIME=$(/usr/bin/date "+%Y-%m-%d %H:%M:%S"); echo "$DATETIME: Node fail $OX_NODE_NAME, $OX_EVENT, $OX_NODE_IP, $OX_NODE_FROM, $OX_NODE_MSG, $OX_NODE_GROUP, $OX_NODE_MODEL, $OX_JOB_STATUS, $OX_JOB_TIME, $OX_REPO_COMMITREF, $OX_REPO_
NAME" >> /opt/oxidized/.config/oxidized/logs/ox_node_failed.log'
  email_output:
    type: exec
    events: [post_store, node_fail]
    cmd: '/opt/oxidized/.config/oxidized/oxidized-report-git-commits.sh | mail -s "Oxidized updates for ${OX_NODE_NAME}" <removed>'
    async: true
    timeout: 120
```

There is nothing in the debug file:
```logs/10.10.20.4-ssh```

Also no crash file available for this device/ip.

In logs/ox_node_failed.log I can see the follwoing:
```2023-04-05 04:35:38: Node fail at-vie03a-con03, node_fail, 10.10.20.4, , , Consolenswitch, OpenGear, no_connection, 0.010392857, , /var/lib/oxidized/devices.git```

It is not clear for my why the connection should not work.
If I try it manualy with ssh and this user/password it is working fine.

Is there something else what I can debug?

thx

**Comment by mortzu** [comment]
Please format your paste: https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code

**Comment by chrisch80** [comment]
In the meantime I also checked [Troubleshooting.md](https://github.com/ytti/oxidized/blob/master/docs/Troubleshooting.md) but was not able to solve my issue. The Prompt is not the issue.

**Comment by chrisch80** [comment]
Does somebody have oxidzed successfully running with Opengear Model: IM7248-2-DAC Firmware: 4.13.3

**Comment by gbbromley** [comment]
Yes we are using Oxidized to backup OpenGear products from 8port ACMs to 48 port IM series. Our issues are captured in https://github.com/ytti/oxidized/issues/2432 which also includes a workaround to support a greater list of SSH encryption, cipher, key algorithms which allows Oxidized via Net::SSH to connect to carry out backups.

**Comment by chrisch80** [comment]
thx @gbbromley, I also see such ssh errors in /var/log/syslog (and I always tought that in debug mode I should find all logs in the oxidized log itself.
