### ISSUE TITLE
with latest docker-image push isnt possible anymore

### ISSUE THREAD

**Issue by quotengrote** [ytti/oxidized#2753]
After updatting to the new image with the `latest`-Tag following errors occurs after oxidized tries to push to a git repository.

## error

```
I, [2023-04-16T09:46:16.616885 #33]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
I, [2023-04-16T09:46:16.617525 #33]  INFO -- : lib/oxidized/nodes.rb: Loaded 4 nodes
I, [2023-04-16T09:52:52.168165 #33]  INFO -- : Configuration updated for /rb5009.grote.lan
I, [2023-04-16T09:52:52.168404 #33]  INFO -- : GithubRepo: Pushing local repository(/var/lib/oxidized/devices.git/)...
I, [2023-04-16T09:52:52.168432 #33]  INFO -- : GithubRepo: to remote: ssh://gitea@git.mgrote.net:2222/mg/oxidized-configs.git
E, [2023-04-16T09:52:52.221168 #33] ERROR -- : Hook push_to_remote (#<GithubRepo:0x0000557d6e474f78>) failed (#<Rugged::SshError: invalid or unknown remote ssh hostkey>) for event :post_store
```

the host key on the git-server did not change.

## config
```
source:
  default: csv
  csv:
    file: /home/oxidized/.config/oxidized/router.db
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      ip: 1
      model: 2
      username: 3
      password: 4
    vars_map:
      enable: 5

# enable WebGUI
rest: 0.0.0.0:8888

# debug
# debug: true

output:
  default: git
  git:
    user: oxidized
    email: oxidized@grote.lan
    repo: "/var/lib/oxidized/devices.git"

hooks:
  push_to_remote:
    type: githubrepo
    events: [post_store]
    remote_repo: ssh://gitea@git.mgrote.net:2222/mg/oxidized-configs.git
    publickey: /ssh/id_rsa.pub
    privatekey: /ssh/id_rsa

```

**Comment by aschaber1** [comment]
Hello, could you please try running this command to add the ssh key to your known_hosts file and see if this fixes it?
Make sure to replace `~oxidized` if you are running it as a different user and make sure it shows to the home directory of the user oxidized is run as.

```
ssh-keyscan -p 2222 git.mgrote.net >> ~oxidized/.ssh/known_hosts
```

**Comment by quotengrote** [comment]
Interestingly i tried that already, but after creating `~oxidized/.ssh/known_hosts` explicit before key-scan it works now.

```
   13  mkdir ~oxidized/.ssh/
   14  ssh-keyscan -p 2222 git.mgrote.net >> ~oxidized/.ssh/known_hosts
```

after that:

```
I, [2023-04-16T10:14:52.634734 #33]  INFO -- : Configuration updated for /rb5009.grote.lan
I, [2023-04-16T10:14:52.635007 #33]  INFO -- : GithubRepo: Pushing local repository(/var/lib/oxidized/devices.git/)...  
I, [2023-04-16T10:14:52.635047 #33]  INFO -- : GithubRepo: to remote: ssh://gitea@git.mgrote.net:2222/mg/oxidized-configs.git   
Reloading config...  
I, [2023-04-16T10:16:16.645255 #33]  INFO -- : lib/oxidized/nodes.rb: Loading nodes 
I, [2023-04-16T10:16:16.645907 #33]  INFO -- : lib/oxidized/nodes.rb: Loaded 4 nodes   
```

Thanks!

**Comment by aschaber1** [comment]
Perfect, now I'm thinking is this a security feature (then it's missing docs), or a bug :|

**Comment by aschaber1** [comment]
@mortzu , what's your opinion on this?

**Comment by westerterp** [comment]
Push to remote Git repo over SSH was broken for me also.
Can confirm this workaround works for me too.

Note that only creating the ```~oxidized/.ssh/known_hosts``` file is not enough, the keys need to be in it.
Meaning it isn't a matter of not being able to create the file, but a matter of missing entries in that file.

**Comment by quotengrote** [comment]
What got me wondering is that the keys were existent in that file. But somehow disapperead.
But yes, of course, the keys must be present.

**Comment by DanielWeeber** [comment]
This is no solution for the docker container though, as the known_hosts file does not exist anymore after restarting the container.
We need be able to setup a known_hosts file via the push_to_remote configuration

**Comment by DanielWeeber** [comment]
Workaround: Switch to https and use a ACCESS_TOKEN for authentication.

**Comment by dermotw** [comment]
> Workaround: Switch to https and use a ACCESS_TOKEN for authentication.

Or add the following to your docker-compose:

`- ./known_hosts:/home/oxidized/.ssh/known_hosts:ro`

**Comment by quotengrote** [comment]
> > Workaround: Switch to https and use a ACCESS_TOKEN for authentication.
> 
> Or add the following to your docker-compose.yml:
> 
> `- ./known_hosts:/home/oxidized/.ssh/known_hosts:ro`

Thats what i am using right now, but i dont know why it worked before.
The Container was multiple times recreated without issues.

A potential (insecure) solution could be to run `ssh-keyscan -p 22 <host> >> ~oxidized/.ssh/known_hosts` on every Containerstart.

**Comment by amtypaldos** [comment]
Anything new on this? rugged 0.28.5 does not work with github since it only can use SHA1, and now rugged 1.6.3 requires  a known hosts file.

**Comment by amtypaldos** [comment]
I just used a ed25519 key and that was supported, only issue now is the known hosts file.

**Comment by BrunoBlanes** [comment]
> I just used a ed25519 key and that was supported, only issue now is the known hosts file.

I am currently facing this issue, is there a workaround?

**Comment by PasserDreamer** [comment]
I got another issue.
```
I, [2023-09-21T04:13:16.263335 #31]  INFO -- : GithubRepo: Pushing local repository(/home/oxidized/.config/oxidized/backup_conf/devices.git/)...
I, [2023-09-21T04:13:16.263431 #31]  INFO -- : GithubRepo: to remote: ssh://git@git.***.***:7022/it/config-backup.git
E, [2023-09-21T04:13:16.383139 #31] ERROR -- : Hook push_to_remote (#<GithubRepo:0x00005640ff7460f8>) failed (#<Rugged::SshError: remote rejected authentication: Failed getting response>) for event :post_store
```
My config:
```
hooks:
  push_to_remote:
    type:        githubrepo
    events:      [post_store]
    remote_repo: ssh://git@git.***.***:7022/it/config-backup.git
    publickey:   /home/oxidized/.config/oxidized/gitlab/gitlab.pub
    privatekey:  /home/oxidized/.config/oxidized/gitlab/gitlab.key
```
~oxidized/.ssh/config
```
host git.***.***
  User git
  Port 7022
  IdentityFile /home/oxidized/.config/oxidized/gitlab/gitlab.key
  IdentitiesOnly yes
```
~oxidized/.ssh/known_hosts
```
[git.***.***]:7022 ssh-rsa  ~~~
[git.***.***]:7022 ecdsa-sha2-nistp256 ~~~
[git.***.***]:7022 ssh-ed25519  ~~~
```
```
ssh -T git.***.***
Welcome to GitLab, @Oxidized!
```
gitlab.key
```
-----BEGIN RSA PRIVATE KEY-----
~~~
-----END RSA PRIVATE KEY-----
```
No space after ---
I cannot figure out what to do.

**Comment by robertcheramy** [comment]
@PasserDreamer - please open a separate issue if your problem is not related to this one.

To this issue: I use oxidized in a podman-container with podman-compose an map the whole .ssh folder to a local volume. This way I have a permanent known_hosts and a place to strore my ssh-keys.

My docker-compose.yml looks like
```
services:
  oxidized:
    container-name: oxidized
(...)
    volumes:
       - ./oxidized-ssh:/home/oxidized/.ssh
```

**Comment by YellowJacket51** [comment]
I am still having the same issue.
