### ISSUE TITLE
Oxidized Struggling with very large configs

### ISSUE THREAD

**Issue by LAwLzaWU1A** [ytti/oxidized#2755]
I am not sure if I am doing this right so please let me know if you need anything else.

I have ran into a problem with Oxidized where it won't backup devices with too large config files. I fixed the issue on some devices by increasing the timeout in the oxidized config, but right now I have it set to 1200 seconds and it's still not enough for my largest device. The device I am currently struggling with has over 500 000 lines of config, over 20MB when saved to a text file.

Is it possible to increase the speed at which Oxidize fetched the config? Or is my only option to keep increasing the timeout until it finally works? Another idea I had was to have Oxidized use multiple accounts to sign in to the device, each with access to only part of the full config and thus backup the single device as if it were multiple devices, but that's something I'd rather avoid if possible.

I am running Oxidized 0.28.0 if that matters, and I am saving to a git hosted on the same machine. All other devices works fine, including a 60K lines long config that over 1.5MB in size.

**Comment by electrocret** [comment]
For a config that large, no standard config backup tool, such as Oxidized, will be successful. 

If I were in your position, I would see if the device you're backing up has the ability to push its config to an external file server, and if so, script out the copy, then set it to a cron.

**Comment by aschaber1** [comment]
Or maybe see if the device has options to fetch the config via (t)ftp.

**Comment by electrocret** [comment]
> Or maybe see if the device has options to fetch the config via (t)ftp.

Yep, that's what I was getting at, I guess I should have name dropped a protocol. :)

Have the device push/copy its config to a separate server rather than try to pull it through SSH like Oxidized and most other backup tools do.

**Comment by aschaber1** [comment]
I understand your idea is that the network device puts its config to a server. Did I get that right?

My idea was to check, if the device  is able to serve as a T(FTP) Server that provides you with the config.

But both would be viable alternatives to pull a large config through ssh anyway💡

**Comment by electrocret** [comment]
Interesting, never thought or tried turning a device into a TFTP server.

**Comment by electrocret** [comment]
If the platform is designed to have large configs, and it's not poorly maintained configs, it may have a built in external backup feature.
I know Cisco ACI can't be backed up with Oxidized, however it has a built in config backup tool that lets you essentially create a cron on it where it FTP/SFTP/SCP's its config to an external server.

**Comment by LAwLzaWU1A** [comment]
It is possible to backup using FTP, but I was hoping to get everything into Oxidized in order to consolidate all devices in the same place and same web-GUI. But it's understandable that the tool can't do it. I was just hoping to I was missing something to make it work.

**Comment by aschaber1** [comment]
There's an ftp input for oxidized. Don't know how it works though. 

https://github.com/ytti/oxidized/blob/master/lib/oxidized/input/ftp.rb
