### ISSUE TITLE
Preferred method to autostart oxidized?

### ISSUE THREAD

**Issue by masonke** [ytti/oxidized#276]
Using ubuntu 14.0.4
What is the preferred method to auto start oxidized when the O/S comes up?  With all the options, what seems to work best for most folks?

**Comment by ytti** [comment]
I believe 14.04 uses upstart still, not systemd, so I'd probably start with
https://github.com/ytti/oxidized/blob/master/extra/oxidized.upstart

**Comment by masonke** [comment]
So copy the file to /etc/init and change the file name to oxidized.conf ?

**Comment by ytti** [comment]
I don't use it myself, hopefully, yes :).

**Comment by masonke** [comment]
Will let you know

**Comment by ytti** [comment]
i assume script was OK. If not, reopen.
