### ISSUE TITLE
sending email when configs update occur

### ISSUE THREAD

**Issue by masonke** [ytti/oxidized#277]
Most likely this is painfully obvious and I just missed it. 

How can I get oxidized to send an email when there is a diff in the device configuration? Would this be more of a git function?

I was trying to make oxidized-report-git-commits work, but cannot find the script update-local-repo.sh that it calls. 

Thanks

**Comment by ytti** [comment]
@nickhilliard might help with the deployment of that, perhaps update README or file itself on use instructions. 

This is not at all obvious and it's quite often requested feature. We didn't have any way of doing it, until hook system was implemented. I always personally felt, that what ever you're using to manage your git (gitlab, gitorious, github, stash, bitbucket...) will send the diff emails, so NIH'ing this in Oxidized to me seemed like unnecessary, but I'm obviously biased.

**Comment by nickhilliard** [comment]
oops.  see #278. ```update-local-repo.sh``` was the secret development name of the script.

**Comment by DervMan** [comment]
When running the Oxidized script will generate output is updated, I'm going to try and send any output from Oxidized to my email address. It's a bit crude but will work for now and means I can stop using RANCID ;-)

Here's what I see
I, [2016-01-26T15:10:32.721843 #485]  INFO -- : Configuration updated for /ROUTER
