### ISSUE TITLE
Docker container fails to locate files when using docker-compose.yml script 

### ISSUE THREAD

**Issue by andrewburke1** [ytti/oxidized#2770]
New to docker, but when using the docker compose to bring up the container it fails to locate the needed files, however docker shows the container online and using the correct ports.  If I use the below the container launches without issues, brings up the web interface and pulls my lab device config.  I tried making modifications to the docker-compose.yml file with no luck.  Out of ideas ATM and don't see where the issue is.  

running: docker compose up -d which triggers the docker-compose.yml script brings up the container only and opens up port 8888, but no web page is available.  
 
docker compose logs from above script.
oxidized-oxidized-1  | No such file or directory @ rb_sysopen - /home/oxidized/.config/oxidized/router.db

Running the below works as expected, brings up the web interface and device without any issues.
 
docker run -v /etc/oxidized:/home/oxidized/.config/oxidized -p 8888:8888/tcp -t oxidized/oxidized:latest

rhel9 (running as oxidized user w/admin rights and part of docker group)
oxidized- 0-29.1
docker- 23.0.4

**Comment by yoakim** [comment]
Can we see the docker-compose file?

**Comment by andrewburke1** [comment]
Sure, absolutely.  Right now its the same as the one off the install guide, but I tried to modify it to the docker run command with no luck and changed it back to what it was prior.

---
version: "3"
services:
  oxidized:
    restart: always
    image: oxidized/oxidized:latest
    ports:
      - 8888:8888/tcp
    environment:
      CONFIG_RELOAD_INTERVAL: 600
    volumes:
       - config:/home/oxidized/.config/oxidized/
volumes:
  config:

**Comment by yoakim** [comment]
I see, seeing that without compose it works, i guess that you have your router.db inside /etc/oxidized on your host machine.
Something like this should work, but i guess this below is what you tried?
Also you can also go into your container to check your containers files using
docker exec -it <container name> bash

`version: "3"
services:
oxidized:
restart: always
image: oxidized/oxidized:latest
ports:
- 8888:8888/tcp
environment:
CONFIG_RELOAD_INTERVAL: 600
volumes:
- /etc/oxidized:/home/oxidized/.config/oxidized/`

**Comment by andrewburke1** [comment]
Yup, was the first thing I tried and seemed logical at first but I didn't think about removing the leading config: in the line.  Your suggestion worked.  That worked and brought web interface up along with my lab device.  Thank you very much.
