### ISSUE TITLE
Release 0.29.1 breaks pfsense and opnsense config

### ISSUE THREAD

**Issue by jcheger** [ytti/oxidized#2771]
Docker version 0.29.1 return empty files for pfsense and opnsense, with only version as content.

config file:
> &lt;!-- OPNsense 23.1.6 --&gt;

and no more

Version 0.29.0 does work as expected.

**Comment by DanielWeeber** [comment]
can confirm here

**Comment by 4pack** [comment]
I can confirm as well.

```
<!-- PFsense 2.6.0-RELEASE -->
```

**Comment by netforce** [comment]
"docker version 0.29.1" does not break pfsense backups, Oxidized Release 0.29.1 breaks. 
Issue title is not valid. 

But yes, Oxidized release 0.29.1 on docker breaks.

**Comment by DanielWeeber** [comment]
What an unproductive comment.

**Comment by netforce** [comment]
re-introducing the cut_head in the model/pfsense.rb solves the issue of not having any backup at all.

  cmd :all do |cfg|
    cfg.cut_head
  end

**Comment by cmbcbe** [comment]
i have a temporary fix consisting of creating a custom model for 0.29.1 wich i named pfsensefix, just change your router.db from pfsense to pfsensefix and create the model pfsensefix.rb with this content

`class PfSenseFix < Oxidized::Model
  using Refinements

  # use other use than 'admin' user, 'admin' user cannot get ssh/exec. See issue #535

  cmd :all do |cfg|
    cfg.cut_head
  end

  cmd :secret do |cfg|
    cfg.gsub! /(\s+<bcrypt-hash>).+?(<\/bcrypt-hash>)/, '\\1[secret hidden]\\2'
    cfg.gsub! /(\s+<password>).+?(<\/password>)/, '\\1[secret hidden]\\2'
    cfg.gsub! /(\s+<lighttpd_ls_password>).+?(<\/lighttpd_ls_password>)/, '\\1[secret hidden]\\2'
    cfg
  end

  cmd 'cat /cf/conf/config.xml' do |cfg|
    raise "<pfsense> missing in config file!" unless cfg.include? "<pfsense>"

    cfg.gsub! /\s<revision>\s*<time>\d*<\/time>\s*.*\s*.*\s*<\/revision>/, ''
    cfg.gsub! /\s<last_rule_upd_time>\d*<\/last_rule_upd_time>/, ''
    cfg
  end

  # The comment output has to be at the end since and XML file may not start
  # with a comment.

  cmd 'cat /etc/version' do |version|
    xmlcomment "PFsense #{version}"
  end

  cfg :ssh do
    exec true
    pre_logout 'exit'
  end
end
`

**Comment by LoZio** [comment]
@cmbcbe Thanks for the reply, I think you should format the content of your reply as code to make it more readable

**Comment by moisseev** [comment]
@netforce 
> The `<!-- PFsense 2.6.0-RELEASE -->` version tag is still missing from the backup, but that beats at least having no config backup at all. It just shows `<!-- PFsense --> ` now.

It's because `cfg.cut_head` removes the version line. You can use `cfg.cut_head(lines = 0)` instead.

It's also not necessary to touch stock model files or create a custom model. Monkey-patching is a more convenient workaround.

`~/.config/oxidized/model/pfsense.rb`: 
```rb
require 'oxidized/model/pfsense.rb'

class PfSense < Oxidized::Model
  using Refinements

  cmd :all do |cfg|
    cfg.cut_head(lines = 0)
  end
end
```

**Comment by francisconascimento** [comment]
> @netforce
> 
> It's also not necessary to touch stock model files or create a custom model. Monkey-patching is a more convenient workaround.
> 

I apologise, I'm probably a bit dim, I tried both fixes (reverting the previous one), 'systemcl restart oxidized' ... still the same issue.

Any bright ideas as I'm going to start pulling my hair.

**Comment by robertcheramy** [comment]
The bug was introduced with e47d719aff64950f8cd7313f27d85846915db837 , but I do not understand why.  Using `cmd :all do |cfg|` as proposed in this issue surely solves the problem, but I think that it should work without `cmd :all` at all.
lib/oxidized/model/model.rb is a very nice peace of code, but an overkill for my little ruby knowledge. I'm still trying to understand it in order to find the root of this issue.

**Comment by francisconascimento** [comment]
> I see two possible fixes:
> 
>     * have input/ssh.rb to return a String
> 
>     * have `process_cmd_output` to cope with Net::SSH::Connection::Session::StringWithExitstatus
> 

I'm not an experienced programmer and Ruby is a complete blackhole to me, however I think I understand what you're saying, config-wise.

I'd think "have `process_cmd_output` to cope with Net::SSH::Connection::Session::StringWithExitstatus" sounds like a better option to me. I take it you mean something like "if String then This, elseif StringWithExitstatus then That" (apologies for my crude pseudo-language example)?!?!

I can easily imagine something else breaks in the future if we opt for "have input/ssh.rb to return a String".

My £0.05.

@ytti, a penny for your thoughts, sir?!

Thanks

**Comment by robertcheramy** [comment]
I was away from office last week and could not work on the issue, but thought about it.
As the Model class expects a string and does nothing with the Information coming from ssh/ftp/scp/whatever (error have to be treated there), we have provide a String as the output of the Input.cmd method.
I will write a PR in the next days.

**Comment by da-oxi** [comment]
> i have a temporary fix consisting of creating a custom model for 0.29.1 wich i named pfsensefix, just change your router.db from model pfsense to pfsensefix and create the model **pfsensefix.rb** with this content
> 
> ```
> class PfSenseFix < Oxidized::Model
>   using Refinements
> 
>   # use other use than 'admin' user, 'admin' user cannot get ssh/exec. See issue #535
> 
>   cmd :all do |cfg|
>     cfg.cut_head
>   end
> 
>   cmd :secret do |cfg|
>     cfg.gsub! /(\s+<bcrypt-hash>).+?(<\/bcrypt-hash>)/, '\\1[secret hidden]\\2'
>     cfg.gsub! /(\s+<password>).+?(<\/password>)/, '\\1[secret hidden]\\2'
>     cfg.gsub! /(\s+<lighttpd_ls_password>).+?(<\/lighttpd_ls_password>)/, '\\1[secret hidden]\\2'
>     cfg
>   end
> 
>   cmd 'cat /cf/conf/config.xml' do |cfg|
>     raise "<pfsense> missing in config file!" unless cfg.include? "<pfsense>"
> 
>     cfg.gsub! /\s<revision>\s*<time>\d*<\/time>\s*.*\s*.*\s*<\/revision>/, ''
>     cfg.gsub! /\s<last_rule_upd_time>\d*<\/last_rule_upd_time>/, ''
>     cfg
>   end
> 
>   # The comment output has to be at the end since and XML file may not start
>   # with a comment.
> 
>   cmd 'cat /etc/version' do |version|
>     xmlcomment "PFsense #{version}"
>   end
> 
>   cfg :ssh do
>     exec true
>     pre_logout 'exit'
>   end
> end
> ```
> 
> https://git.cmbc.be/public/oxidized/src/branch/main/model/pfsensefix.rb

thank you, bro
it really helped me
