### ISSUE TITLE
Oxidized fails to start with hooks section (undefined method `each' for nil:NilClass)

### ISSUE THREAD

**Issue by stranger838383** [ytti/oxidized#2772]
Hello!

I try to implement the email notification with hooks for [node_fail] event.
Below is  my pretty obvious hooks section in the Oxidized config:

hooks:  
email_output:
    type: exec
    events: [node_fail]
    cmd: '/home/oxidized/.config/oxidized/extra/oxidized-report-git-commits | mail -s "Oxidized updates for ${OX_NODE_NAME}"  -r oxidized@domain.com   my@domain.com'
    async: true
    timeout: 120

Script oxidized-report-git-commits is executable, but when I start Oxidized it crashes because of:
Apr 27 13:31:23 domain.com oxidized[2114361]: undefined method `each' for nil:NilClass
Apr 27 13:31:23 domain.com oxidized[2114361]:         cfg.hooks.each do |name, h_cfg|
Apr 27 13:31:23 domain.com oxidized[2114361]:                  ^^^^^

Ruby version :  ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux]
Psych version:  (3.0.2)

I`m not Ruby expert so could please anyone help me on finding the root cause and possible solutions?

Thanks!

**Comment by eyitayoafolabi** [comment]
This looks like a yaml syntax error in config ..
