### ISSUE TITLE
issue with dell os10 model

### ISSUE THREAD

**Issue by K3v1n2023** [ytti/oxidized#2778]
Hi guys, 
I use model dell-os10: os10 and i think something is wrong because the first line of the running not appear in oxidized .

**Running-conf on switch** 
! Version 10.5.4.4
! Last configuration change at May  04 07:50:00 2023
!
ip vrf default
!
iscsi enable
iscsi target port 860

**Running-conf in oxidized**
! 
!
iscsi enable
iscsi target port 860
iscsi target port 3260

**Comment by K3v1n2023** [comment]
Thoses lines not exist in the OS10 model
```
 **cmd 'show running-configuration' do |cfg|
    cfg.each_line.to_a[2..-1].join
  end**
```

In place i can find the lines below : 
```
cmd 'show running-config' do |cfg|
    cfg.sub(/^(sflow \S+ destination owner \S+ timeout )\d+$/, '! \1<timeout>')
  end
```

**Comment by yoakim** [comment]
Did you modify your repo?

https://github.com/ytti/oxidized/blob/master/lib/oxidized/model/os10.rb

**Comment by yoakim** [comment]
Did you restart the service end refetch the config?

**Comment by K3v1n2023** [comment]
yes i have restart the service, but i dont know how to refetch the conf .
Can you explain to me how to do that ?

**Comment by yoakim** [comment]
Yes, just click the little refresh/circle icon in the web interface, for the particular node (under actions).

**Comment by K3v1n2023** [comment]
Hi , I have try it now but nothing change.

I have try to comment thoses lines but the nothing change 
in /var/lib/gems/2.7.0/gems/oxidized-0.28.0/lib/oxidized/model/os10.rb
```
 cmd 'show inventory' do |cfg|
    comment cfg
  end

  cmd 'show inventory media' do |cfg|
    comment cfg
  end
```
