### ISSUE TITLE
Brocade old fabricOS (v5.3.0a) not working

### ISSUE THREAD

**Issue by mdiunip** [ytti/oxidized#2785]
Hi, i can't get any brocade device to work. The backup shows completed but the content is always this:

```
# rbash: chassisshow: command not found
rbash: configshow: command not found
```
note that i tried editing the commands in fabricos.rb to lowercase, originally was (chassisShow.. ) without luck.

Any ideas?

Thanks

**Comment by falkenbe** [comment]
Hi @mdiunip ,

I'm neither a FabricOS expert nor an Oxidized expert but I did just finish getting my Brocade switch backed up with Oxidized.  `command not found` sounds like an issue with the way your oxidized user is configured on the switch.

- Do you have the same problem if you manually ssh to the switch using the same username & password Oxidized is configured to use and run `chassisShow` or `configShow`?
- Can you run those commands if you manually ssh to the switch as an administrative user?

**Comment by mdiunip** [comment]
Hi @falkenbe, thanks for answering.
At first i was thinking there could be a problem with the password, maybe some special character, but its not.
I tried also with the admin user and even with the root user. I have no problem manually ssh.

Using the root user i get:

```
# sh: chassisshow: command not found
sh: configshow: command not found
```
Notice sh instead of rbash.

I think maybe those switches are too old, Fabric OS is v5.3.0a. I have no problem with more recent switches i have with v8.2.1c

**Comment by falkenbe** [comment]
My Brocades are running v8.2.x too, and like you said they play nice with Oxidized.

Have you tried forcing Oxidized to use the shell ssh channel instead of the exec channel?
```yaml
vars:
  ssh_no_exec: true
```
If everything works when you manually ssh to the switch then the `command not found` error makes me think that your shell's PATH isn't getting set correctly.  Maybe older FabricOS doesn't set the path properly for the exec ssh channel.

**Comment by mdiunip** [comment]
Thank you @falkenbe, I didn't try because i saw this in the fabricos.rb:

```
  # Brocade Fabric OS model #
  ## FIXME: Only ssh exec mode support, no telnet, no ssh screenscraping
```

I tried now without luck, connection fails without exec.
