### ISSUE TITLE
Setup help

### ISSUE THREAD

**Issue by rhythmtone** [ytti/oxidized#2786]
Hello,
I fixed the `unsafe_load' for Psych:Module #2769 bug ( https://github.com/ytti/oxidized/issues/2769 ) but I still cannot get this stack to load properly, can someone please tell me what I am doing wrong?

It states that there is no router.db - but if you look at the output below, there clearly IS a router.db

Thanks

<pre>
administrator@DO-SVR-R220:/etc/oxidized$ sudo docker run -v /etc/oxidized:/home/oxidized/.config/oxidized -p 8888:8888/tcp -t oxidized/oxidized:latest
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/my_init.d/10_syslog-ng.init...
May  9 18:23:44 aa778a613161 syslog-ng[14]: syslog-ng starting up; version='3.35.1'
*** Booting runit daemon...
*** Runit started as PID 23
May  9 18:23:45 aa778a613161 cron[30]: (CRON) INFO (pidfile fd = 3)
May  9 18:23:45 aa778a613161 cron[30]: (CRON) INFO (Running @reboot jobs)
I, [2023-05-09T18:23:45.516858 #32]  INFO -- : Oxidized starting, running as pid 32
I, [2023-05-09T18:23:45.517890 #32]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
F, [2023-05-09T18:23:45.519230 #32] FATAL -- : Oxidized crashed, crashfile written in /home/oxidized/.config/oxidized/crash
No such file or directory @ rb_sysopen - /etc/oxidized/router.db
I, [2023-05-09T18:23:46.726302 #39]  INFO -- : Oxidized starting, running as pid 39
I, [2023-05-09T18:23:46.726830 #39]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
F, [2023-05-09T18:23:46.728113 #39] FATAL -- : Oxidized crashed, crashfile written in /home/oxidized/.config/oxidized/crash
No such file or directory @ rb_sysopen - /etc/oxidized/router.db
I, [2023-05-09T18:23:47.936318 #41]  INFO -- : Oxidized starting, running as pid 41
I, [2023-05-09T18:23:47.936934 #41]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
F, [2023-05-09T18:23:47.938348 #41] FATAL -- : Oxidized crashed, crashfile written in /home/oxidized/.config/oxidized/crash
No such file or directory @ rb_sysopen - /etc/oxidized/router.db
I, [2023-05-09T18:23:49.146811 #43]  INFO -- : Oxidized starting, running as pid 43
I, [2023-05-09T18:23:49.147320 #43]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
F, [2023-05-09T18:23:49.147386 #43] FATAL -- : Oxidized crashed, crashfile written in /home/oxidized/.config/oxidized/crash
No such file or directory @ rb_sysopen - /etc/oxidized/router.db
^C*** Shutting down runit daemon (PID 23)...
*** Running /etc/my_init.post_shutdown.d/10_syslog-ng.shutdown...
May  9 18:23:50 aa778a613161 syslog-ng[14]: syslog-ng shutting down; version='3.35.1'
*** Init system aborted.
*** Killing all processes...
administrator@DO-SVR-R220:/etc/oxidized$ ls
config  crash  logs  oxidized  oxidized-latest  router.db
administrator@DO-SVR-R220:/etc/oxidized$ 
</pre>

**Comment by yoakim** [comment]
Why is your log saying this?
`No such file or directory @ rb_sysopen - /etc/oxidized/router.db`

This should be more correct according to your -v argument.
`No such file or directory @ rb_sysopen - /home/oxidized/.config/oxidized/router.db`

Did you change any paths in your config?

**Comment by rhythmtone** [comment]
`No such file or directory @ rb_sysopen - /etc/oxidized/router.db`
- I have no idea why it is saying this, that was the genesis of the question - router.db file does exist in that location - you can see if in my first post when I type 'ls'
- the old config was:
`file: /etc/oxidized/router.db`
Here is the new config below with the resulting outputs, still does not work:

  GNU nano 7.2                                                                config                                                                          
vars: {}
groups: {}
group_map: {}
models: {}
pid: "/home/oxidized/.config/oxidized/pid"
crash:
  directory: "/home/oxidized/.config/oxidized/crashes"
  hostnames: false
stats:
  history_size: 10
input:
  default: ssh, telnet
  debug: false
  ssh:
    secure: false
  ftp:
    passive: true
  utf8_encoded: true
output:
  default: file
source:
  default: csv
  csv:
    file: ~/.config/oxidized/router.db
    delimiter: !ruby/regexp /:/
    map:
      ip: 0
      model: 1
      username: 2
      password: 3
    vars_map:
      enable: 5

------------

administrator@DO-SVR-R220:/etc/oxidized$ sudo docker run -v /etc/oxidized:/root/oxidized/.config/oxidized -p 8888:8888/tcp -t oxidized/oxidized:latest
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/my_init.d/10_syslog-ng.init...
May 12 17:14:22 f5cb174979e4 syslog-ng[14]: syslog-ng starting up; version='3.35.1'
*** Booting runit daemon...
*** Runit started as PID 23
May 12 17:14:23 f5cb174979e4 cron[31]: (CRON) INFO (pidfile fd = 3)
May 12 17:14:23 f5cb174979e4 cron[31]: (CRON) INFO (Running @reboot jobs)
edit ~/.config/oxidized/config
I, [2023-05-12T17:14:25.427324 #40]  INFO -- : Oxidized starting, running as pid 40
F, [2023-05-12T17:14:25.429774 #40] FATAL -- : Oxidized crashed, crashfile written in /home/oxidized/.config/oxidized/crash
no source csv config, edit ~/.config/oxidized/config
I, [2023-05-12T17:14:26.630542 #42]  INFO -- : Oxidized starting, running as pid 42
I, [2023-05-12T17:14:26.631194 #42]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
F, [2023-05-12T17:14:26.631300 #42] FATAL -- : Oxidized crashed, crashfile written in /home/oxidized/.config/oxidized/crash
No such file or directory @ rb_sysopen - /home/oxidized/.config/oxidized/router.db
I, [2023-05-12T17:14:27.835346 #44]  INFO -- : Oxidized starting, running as pid 44
I, [2023-05-12T17:14:27.835917 #44]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
F, [2023-05-12T17:14:27.837292 #44] FATAL -- : Oxidized crashed, crashfile written in /home/oxidized/.config/oxidized/crash
No such file or directory @ rb_sysopen - /home/oxidized/.config/oxidized/router.db
^C*** Shutting down runit daemon (PID 23)...
*** Running /etc/my_init.post_shutdown.d/10_syslog-ng.shutdown...
May 12 17:14:28 f5cb174979e4 syslog-ng[14]: syslog-ng shutting down; version='3.35.1'
*** Init system aborted.
*** Killing all processes...

**Comment by yoakim** [comment]
Yes but that is in your local system, not in the container.
When you start the container, you can go inside it and watch the file system to see how it looks.
`docker exec -it <container name> bash`

I'd start with going into /home/oxidized/.config/oxidized and see whats in there.

**Comment by rhythmtone** [comment]
> Yes but that is in your local system, not in the container. When you start the container, you can go inside it and watch the file system to see how it looks. `docker exec -it <container name> bash`
> 
> I'd start with going into /home/oxidized/.config/oxidized and see whats in there.
> 
> Also in your last docker run you mounted the wrong target path, it's not matching the config file.

You are correct, there is nothing in there in that path inside the container OS.

However, I am simply following the installation instructions from the main page, so it still does not make sense why this does not work - am I supposed to manually copy the router.db from /etc/oxidized/router.db INTO the container to /home/oxidized/.config/oxidized ???

Yes, I am a noob, so I do not understand what is wrong, but there really should be better documentation on how to make this work "out of the box".

Thanks

INSTALL DOCUMENTATION from WEBSITE BELOW:

`Running with Docker

Currently, Docker Hub automatically builds the master branch as [oxidized/oxidized](https://hub.docker.com/r/oxidized/oxidized/), you can make use of this container or build your own.

To build your own, clone git repo:

git clone https://github.com/ytti/oxidized

Then, build the container locally (requires docker 17.05.0-ce or higher):

docker build -q -t oxidized/oxidized:latest oxidized/

Once you've built the container (or chosen to make use of the automatically built container in Docker Hub, which will be downloaded for you by docker on the first run command had you not built it), proceed as follows:

Create a configuration directory in the host system:

mkdir /etc/oxidized

Run the container for the first time to initialize the config:

Note: this step in only required for creating the Oxidized configuration file and can be skipped if you already have one.

docker run --rm -v /etc/oxidized:/home/oxidized/.config/oxidized -p 8888:8888/tcp -t oxidized/oxidized:latest oxidized`

**Comment by rhythmtone** [comment]
Following those instructions, the file exists in the local system (Main OS) path below:

> /etc/oxidized/router.db

But the documentation is unclear on how to actually use this file inside the container.

Thanks

**Comment by yoakim** [comment]
Can you try this?

`docker run -v /etc/oxidized/:/home/oxidized/.config/oxidized -p 8888:8888/tcp -t oxidized/oxidized:latest`

**Comment by yoakim** [comment]
Strange, I'm not sure what version of oxidized you have pulled, i know there is another version that uses root for running oxidized, which may be the case here.

Try and upgrade your image with 
docker pull oxidized/oxidized:latest

and run again

**Comment by h3romoto** [comment]
Hi, I've been trying to fix this for at least a week now. When I set this up months ago, it worked just fine. I am running oxidized and librenms containers on Rocky 8. I am using the latest container image for oxidized. Librenms container(s) working just fine.

Oxidized container broke when I tried changing the output from file to fit. When it failed I reverted back to the previous config that I had backed up. It hasn't worked ever since. I most likely have a typo somewhere. Please help.

Here are the things I tried in order to troubleshoot:
- Running compose file both as oxidized user and then as root user
- Double-checking my config file (yaml syntax)
- Checked librenms http token (using Postman get request). This works fine.

Here is my compose file and config file:
cat /etc/oxidized/config
`
---
username: user
password: passwd
model: junos
resolve_dns: true
interval: 3600
use_syslog: false
debug: true
threads: 30
use_max_threads: false
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 0.0.0.0:8888
next_adds_job: false
vars: {}
groups:
  nxos:
    username: user
    password: passwd
group_map: {}
pid: "/root/.config/oxidized/pid"
crash:
  directory: "/root/.config/oxidized/crashes"
  hostnames: true
stats:
  history_size: 100
input:
  default: ssh, telnet
  debug: true
  ssh:
    secure: false
  ftp:
    passive: true
  utf8_encoded: true
output:
  default: file
  file:
    directory: "/root/.config/oxidized/configs"
source:
  default: http
  debug: true
  http:
    url: http://ipaddress:8000/api/v0/oxidized
    map:
      name: hostname
      model: os
      group: group
    headers:
      X-Auth-Token: mytoken
models:
  cisco:
    username: user
    password: passwd
    vars:
      enable: enablepasswd
`

-----------------------------
cat oxidized-docker-compose.yml
`
# docker-compose.yml
# docker-compose file for oxidized that will start along with docker daemon
---
version: "3"
services:
  oxidized:
    restart: always
    image: oxidized/oxidized:latest
    ports:
      - target: 8888
        published: 8888
        protocol: tcp
    environment:
      CONFIG_RELOAD_INTERVAL: 600
    volumes:
       - /etc/oxidized/:/root/.config/oxidized/
`

What am I missing here? 

Let me know if I can provide more info. Thank you for your help.

**Comment by rhythmtone** [comment]
> Strange, I'm not sure what version of oxidized you have pulled, i know there is another version that uses root for running oxidized, which may be the case here.
> 
> Try and upgrade your image with docker pull oxidized/oxidized:latest
> 
> and run again

The problem with doing that is THEN I run into this bug and the container won't load at all:
https://github.com/ytti/oxidized/issues/2769

So I am having to pull the latest image, and then manually fix that bug before doing anything ... but I will try it and post the results.

Thanks

**Comment by rhythmtone** [comment]
So I finally got back to this, and I was correct - if I pull the latest image, then the container won't run at all, failing with bug: https://github.com/ytti/oxidized/issues/2769

And if I fix that bug with the instructions in that post, then we are right back to where we started:

> No such file or directory @ rb_sysopen - /etc/oxidized/router.db

See results of what I am describing below - this is incredibly frustrating that there appears to be no solution currently, can someone please assist further? Thank you

>
administrator@DO-SVR-R220:~$ sudo docker pull oxidized/oxidized:latest
[sudo] password for administrator: 
latest: Pulling from oxidized/oxidized
2b55860d4c66: Already exists 
8e058277d049: Already exists 
cac814e1eefd: Already exists 
96294db5ec5e: Pull complete 
ec934efba26b: Pull complete 
cbf9ce1349ea: Pull complete 
0d005560ac99: Pull complete 
0f33d9fbe0d7: Pull complete 
acf2fcdff9d4: Pull complete 
350897b6a1bd: Pull complete 
e4b4f966b293: Pull complete 
5d40a5b5366a: Pull complete 
852aef9ff8dd: Pull complete 
f8dc34af6561: Pull complete 
77db4b834b48: Pull complete 
8523da8db2f5: Pull complete 
Digest: sha256:c62b3ba4fed4e750c44fa9affeffc6a1ad978bba034323c248341aae37fe8dd4
Status: Downloaded newer image for oxidized/oxidized:latest
docker.io/oxidized/oxidized:latest
administrator@DO-SVR-R220:~$ sudo docker list images
docker: 'list' is not a docker command.
See 'docker --help'
administrator@DO-SVR-R220:~$ sudo docker image list
REPOSITORY                 TAG       IMAGE ID       CREATED        SIZE
oxidized/oxidized          latest    6e1c36d0fab7   6 days ago     1.06GB
<none>                     <none>    06f9428631ff   13 days ago    1.06GB
oxidized                   latest    3481c00b7ff5   13 days ago    1.06GB
win10-2                    latest    fe58e8c5402b   2 weeks ago    44.5GB
vm-inst                    latest    55b2af986255   2 weeks ago    1.68GB
ubuntukvm18-04-installed   latest    3e19ae66ec0e   2 weeks ago    37.4GB
docker                     latest    70cbbc2855e3   3 weeks ago    318MB
ubuntu                     22.04     08d22c0ceb15   2 months ago   77.8MB
ubuntu                     18.04     3941d3b032a8   2 months ago   63.1MB
administrator@DO-SVR-R220:~$ 
administrator@DO-SVR-R220:~$ 
administrator@DO-SVR-R220:~$ sudo docker run -v /etc/oxidized/:/home/oxidized/.config/oxidized -p 8888:8888/tcp -t oxidized/oxidized:latest
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/my_init.d/10_syslog-ng.init...
May 23 14:49:51 d108f28965e0 syslog-ng[14]: syslog-ng starting up; version='3.35.1'
*** Booting runit daemon...
*** Runit started as PID 22
May 23 14:49:52 d108f28965e0 cron[29]: (CRON) INFO (pidfile fd = 3)
May 23 14:49:52 d108f28965e0 cron[29]: (CRON) INFO (Running @reboot jobs)
Error loading config: undefined method `unsafe_load' for Psych:Module
Did you mean?  safe_load
Error loading config: undefined method `unsafe_load' for Psych:Module
Did you mean?  safe_load
Error loading config: undefined method `unsafe_load' for Psych:Module
Did you mean?  safe_load
Error loading config: undefined method `unsafe_load' for Psych:Module
Did you mean?  safe_load
^C*** Shutting down runit daemon (PID 22)...
*** Running /etc/my_init.post_shutdown.d/10_syslog-ng.shutdown...
May 23 14:49:57 d108f28965e0 syslog-ng[14]: syslog-ng shutting down; version='3.35.1'
*** Init system aborted.
*** Killing all processes...
administrator@DO-SVR-R220:~$ 
<

**Comment by rhythmtone** [comment]
I tried it with the "home" path in my run command, instead of the "root" path, same result:

>
administrator@DO-SVR-R220:/etc/oxidized$ sudo docker run -v /etc/oxidized:/home/oxidized/.config/oxidized -p 8888:8888/tcp -t oxidized/oxidized:latest
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/my_init.d/10_syslog-ng.init...
May 23 20:18:37 e29d162716e4 syslog-ng[14]: syslog-ng starting up; version='3.35.1'
*** Booting runit daemon...
*** Runit started as PID 23
May 23 20:18:38 e29d162716e4 cron[31]: (CRON) INFO (pidfile fd = 3)
May 23 20:18:38 e29d162716e4 cron[31]: (CRON) INFO (Running @reboot jobs)
I, [2023-05-23T20:18:38.387915 #30]  INFO -- : Oxidized starting, running as pid 30
I, [2023-05-23T20:18:38.388469 #30]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
F, [2023-05-23T20:18:38.388544 #30] FATAL -- : Oxidized crashed, crashfile written in /home/oxidized/.config/oxidized/crash
No such file or directory @ rb_sysopen - /etc/oxidized/router.db
I, [2023-05-23T20:18:39.597206 #39]  INFO -- : Oxidized starting, running as pid 39
I, [2023-05-23T20:18:39.597864 #39]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
F, [2023-05-23T20:18:39.599262 #39] FATAL -- : Oxidized crashed, crashfile written in /home/oxidized/.config/oxidized/crash
No such file or directory @ rb_sysopen - /etc/oxidized/router.db
I, [2023-05-23T20:18:40.810930 #41]  INFO -- : Oxidized starting, running as pid 41
I, [2023-05-23T20:18:40.811462 #41]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
F, [2023-05-23T20:18:40.811534 #41] FATAL -- : Oxidized crashed, crashfile written in /home/oxidized/.config/oxidized/crash
No such file or directory @ rb_sysopen - /etc/oxidized/router.db
^C*** Shutting down runit daemon (PID 23)...
*** Running /etc/my_init.post_shutdown.d/10_syslog-ng.shutdown...
May 23 20:18:41 e29d162716e4 syslog-ng[14]: syslog-ng shutting down; version='3.35.1'
*** Init system aborted.
*** Killing all processes...

**Comment by yoakim** [comment]
Can you move your router.db and config to /home/administrator/oxidized-latest (i guess thats where that folder is located) and then mount that path instead of /etc/oxidized?

**Comment by rhythmtone** [comment]
> > > Can you move your router.db and config to /home/administrator/oxidized-latest (i guess thats where that folder is located) and then mount that path instead of /etc/oxidized?
> > 
> > 
> > I got this working, thanks for your help, I appreciate it - must be the permissions issue to /etc/oxidized directory?
> > Once it "saw" the router.db file in the main OS home directory that you suggested /home/administrator/oxidized-latest/ - then it worked fine - it was just a matter of setting up / troubleshooting the config, etc.
> > Probably should update the setup instructions / documentation - maybe I can assist with that using my config as a sandbox.
> > I only had one final question - how did you know that my path was /home/administrator/ ? I do not see that anywhere in my previous posts ... ?
> > Thanks
> 
> No problem my friend. And yes, permission issue was my thoughts when writing the suggestion.
> 
> I can see in your prompt that your username is administrator, hence your home folder is called administrator :)

Okay that makes sense, thank you. And I have learned a lot more about how this works from this thread.

But it still bears one question, because I had the same problem on another test system - it DOES work in the path that you suggested, but how do you fix the permissions to make it work in a system folder, for example:

/etc/oxidized/
or
/appdata/oxidized/

There MUST be a way to make this work outside of the user's personal folder, in a system folder - is there some documentation on how to do this?

I would like to know because some of my systems were set up with root account, for better or worse, and there IS no home folder for root user on the system - and these systems have the EXACT same problem - permissions issue.

Thank you

**Comment by yoakim** [comment]
I understand your question, did you try it with your server with your root user yet?
I'm no linux export though.

In your current server, what is the permissions on your /etc/oxidized?
Also, which user are you running docker as?

**Comment by rhythmtone** [comment]
I finally got back around to this, and it does work fine, even in a custom path - not the user's home folder - it was a problem with the file path(s) and/or not using the root user.

Thanks again for all of your help, I GREATLY appreciate it!
