### ISSUE TITLE
Variable Cisco Enable password in Group

### ISSUE THREAD

**Issue by chrisgfx** [ytti/oxidized#281]
Hi,

Is it possible to include the option to let the Variable Cisco enable password specific to a group ?
If the account has not the full privilege, the show run can't be type by Oxydized.
...
vars:
  enable: cisco <= Global configuration
groups:
 Network:
  username: user_login
  password: user_password
  enable : enable_password <= Specific configuration

Thanks

**Comment by ytti** [comment]
It should work exactly like that, just put 'vars'  before.

´´´
groups:
  Network:
    vars:
      enable: poop
````

**Comment by chrisgfx** [comment]
Great! Just tested it and it works as expected.

Thank you Ytti! :+1:
