### ISSUE TITLE
Can't get config files from all my Huawei Switch

### ISSUE THREAD

**Issue by Floo29** [ytti/oxidized#2811]
Hi, 

I use Oxidized to export some config files from several switch (Cisco/SMB, HP/Procurve) and Huawei.

And I have an issue for almost all my Huawei switches, I can't get the config files from them except on 2 switch using SSH.

I have 10 Switches S5735-L24P4X-A1 all in this version 5.170 S5735-L1-V200R021C00SPC100 and the patch is s5735-l1-v200r021sph012.pat. And I have 1 switch S6730-H24X6C version S6730-H-V200R021C00SPC100 and patch s6730-h-v200r021sph012.pat

And Oxidized can get the config file only on 2 switch S5735-L24P4X-A1.

Unfortunately, I don't have any logs from ssh, well I do but they're empty... and I don't know why it works for only 2 switch.

I tried to add another user on these switches, same problem here.
I checked the SSH connection manually, it works for all of them.

I tried to update Oxidized, it seems to be up to date, I don't know what else to do, I'm stuck here.

Am I the only one to experiencing this kind of issue ?

Thanks in advance for your help

**Comment by nota-user** [comment]
I had a problem where I couldn't get backups of a couple of switches. It turned out that this was either due to the too long device name (namely on the commutator), or it had the "/" symbol in it. It may sound silly, but I'll check my switches

**Comment by Floo29** [comment]
Hello nota-user,

Thanks for your reply, in my case, no "/" in the name of the switches and the longest name I have on my switches are the two which I can backup x)
