### ISSUE TITLE
Oxidized can't start using the official Docker image

### ISSUE THREAD

**Issue by mikegleasonjr** [ytti/oxidized#2819]
I have been using Oxidized for a year now but since the last few releases, it can't start anymore:

```
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/my_init.d/10_syslog-ng.init...
Jun  7 20:55:34 oxidized-ix-chart-6657dcc79b-z9z8x syslog-ng[14]: syslog-ng starting up; version='3.35.1'
*** Booting runit daemon...
*** Runit started as PID 22
Error loading config: undefined method `unsafe_load' for Psych:Module
Did you mean?  safe_load
Error loading config: undefined method `unsafe_load' for Psych:Module
Did you mean?  safe_load
Error loading config: undefined method `unsafe_load' for Psych:Module
Did you mean?  safe_load
[...]
```

**Docker**

- Volume: `/home/oxidized/.config/oxidized`
- Volume: `/home/oxidized/.ssh`

**`config` file**

```
---
username: <redacted>
password: <redacted>
model: junos
resolve_dns: true
interval: 3600
use_syslog: false
log: "/home/oxidized/.config/oxidized/logs/oxidized.log"
debug: false
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 0.0.0.0:8888
next_adds_job: false
vars:
  ssh_keys: "/home/oxidized/.ssh/id_rsa"
groups: {}
models: {}
#pid: "/run/oxidized.pid"
crash:
  directory: "/var/db/oxidized/crashes"
  hostnames: false
stats:
  history_size: 10
input:
  default: ssh, telnet
  debug: false
  ssh:
    secure: false
  ftp:
    passive: true
  utf8_encoded: true
output:
  default: git
  file:
    directory: "/home/oxidized/.config/oxidized/configs"
  git:
    user: <redacted>
    email: <redacted>
    repo: "/home/oxidized/.config/oxidized/configs.git"
model_map:
  juniper: junos
  cisco: ios
source:
  csv:
    file: "/home/oxidized/.config/oxidized/router.db"
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
      username: 2
      password: 3
      enable_password: 4
    gpg: false
```

**`router.db`**

```
host1.redacted:routeros:<redacted>:<redacted>:true
host2.redacted:openwrt:<redacted>::false
```

**Comment by yoakim** [comment]
I saw that you wrote in #2769 , did you try that fix or no?
I guess no fix has been merged yet to the official image.

**Comment by yoakim** [comment]
What changes?
What you need to do until the docker image is updated is to build it yourself.   

Clone the repo, edit gemspec-file and build it then run it. Use docker-compose aswell.

**Comment by E-t-z** [comment]
Same issue, you kind of expect official image to work, if provided.
Unfortunately it is not the case this time.

Fix, mentioned in #2769 seems to work, but as soon as you restart container, everything is broken once more.

**Comment by waja** [comment]
I can confirm that https://hub.docker.com/layers/oxidized/oxidized/latest/images/sha256-1fff3daae15249777636750e0dd45d5501d51df2c788171f0c3ac3710ce45bd5?context=explore works as expected, which seems to have https://github.com/ytti/oxidized/pull/2809 included

**Comment by E-t-z** [comment]
Can confirm, but now it crashes with different error:

<html>
<body>


2023/07/05 10:09:33 | stdout | /usr/lib/ruby/3.0.0/net/protocol.rb:227:in `rbuf_fill': [1mend of file reached ([1;4mEOFError[m[1m)[m
-- | -- | --
2023/07/05 10:09:33 | stdout | end of file reached
2023/07/05 10:09:33 | stdout | F, [2023-07-05T07:09:33.536083 #766] FATAL -- : Oxidized crashed, crashfile written in /home/oxidized/.config/oxidized/crash


</body>
</html>

**Comment by E-t-z** [comment]
Ok fine, I am using https (it did work before 0.29 with current config), did some config adjustments and, still:
<html>
<body>


2023/07/05 10:38:25 | stdout | from /usr/lib/ruby/3.0.0/net/protocol.rb:46:in `ssl_socket_connect'
-- | -- | --
2023/07/05 10:38:25 | stdout | /usr/lib/ruby/3.0.0/net/protocol.rb:46:in `connect_nonblock': [1mSSL_connect returned=1 errno=0 peeraddr=(null) state=error: unexpected eof while reading ([1;4mOpenSSL::SSL::SSLError[m[1m)[m
2023/07/05 10:38:25 | stdout | SSL_connect returned=1 errno=0 peeraddr=(null) state=error: unexpected eof while reading
2023/07/05 10:38:25 | stdout | F, [2023-07-05T07:38:25.581594 #277] FATAL -- : Oxidized crashed, crashfile written in /home/oxidized/.config/oxidized/crash


</body>
</html>
