### ISSUE TITLE
model_map issue

### ISSUE THREAD

**Issue by andreas1o** [ytti/oxidized#282]
Hi I have a problem with model_map I can't seem to get around
I have a couple of Fortigate that never gets mapped to FortiOS ( from Librenms )

I'm running version 0.10 
gem list oxidized

*** LOCAL GEMS ***

oxidized (0.10.0)
oxidized-script (0.1.1)
oxidized-web (0.6.1)

Config snippet from the configuration of oxidized 

```
source:
  default: http
  debug: false
  http:
    url: http://10.230.1.215/api/v0/oxidized
    scheme: http
    delimiter: !ruby/regexp /:/
    map:
      name: hostname
      model: os
      group: group
    model_map:
     cisco: ios
     juniper: junos
     extreme: xos
     fortigate: FortiOS
     hpmsm: procurve
    output:
      default: file
      file:
        directory: /home/admin1o/.config/oxidized/configs
    headers:
      X-Auth-Token: 'X'
```

output from the http get for that host when I run 

curl -H 'X-Auth-Token: X' http://10.230.1.215/api/v0/oxidized

    {
        "hostname": "solnapsesna0002-fw003",
        "os": "fortigate",
        "group": "default"
    },

Error in the logfile 

E, [2016-01-25T21:32:19.735645 #25774] ERROR -- : node {:name=>"solnapsesna0001-fw003", :model=>"fortigate", :group=>"default"} raised Oxidized::ModelNotFound with message 'fortigate not found for node X

I tried both definin the model_map outside of the source and inside of the source.

**Comment by ytti** [comment]
model_map is main-level, it's not specific to single source. Right now it's inside source+http, but it needs to be on the main/top-level

Does the problem persist when you move 'model_map' to top level?

**Comment by andreas1o** [comment]
Yes same issue. 

model_map:
  cisco: ios
  juniper: junos
  extreme: xos
  fortigate: FortiOS
  FortiOS: fortigate

**Comment by ytti** [comment]
Have you tried

fortigate: fortios

without the caps, I think we #downcase it, but worth a shot anyhow. If this works, I'll fix it so that we're case insensitive.

Do rest of them work? Like librenms tells device is 'cisco' and it still works?

**Comment by andreas1o** [comment]
Yes that did it =) It is indeed case sensitive. 

Consider it fixed thanks.

**Comment by MLyszyk** [comment]
For the model_map, what part goes where? Like, what is on the left side of the ":" and what is on the right

**Comment by sjas** [comment]
```
model_map:
    input_data: modelfile
```

input_data is the mapping that you have from the source definition
modelfile ist hte name of the file without `.rb` extension
