### ISSUE TITLE
connection port network device

### ISSUE THREAD

**Issue by xoma11** [ytti/oxidized#2820]
Hi! I have installed and configured oxidized it's complicated. Documentation is missing. I also noticed a problem
my config file
`     name: 0
      model: 1
      ip: 2
      port: 3
      username: 4
      password: 5
`
my router.db
`mikrotik02:routeros:10.10.10.10:2222:user:pass`
and  I can't connect to 10.10.10.10 port 2222 everytime oxidized truid to 22 - 23 port
Log file:
`10.10.10.10 raised Errno::ECONNREFUSED with msg "Connection refused - connect(2) for "10.10.10.10" port 23"`
why I cant change port ssh?

Solution:
map:
   name:0
    vars_map:
     ssh_port: 6

**Comment by nota-user** [comment]
In file /etc/oxidized/config change it
source:
  default: csv
  csv:
    file: "/home/oxidized/.config/oxidized/router.db"
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      ip: 1
      model: 2
      username: 3
      password: 4
    gpg: false
