### ISSUE TITLE
Name and IP mismatch

### ISSUE THREAD

**Issue by cchamerski** [ytti/oxidized#2829]
In oxidized web, the name column has the device's IP address instead of the hostname. I am not using DNS resolution, but I've added the hosts in the /etc/hosts file.
My config file has the following mapping:
`source:
  default: csv
  csv:
    file: "/home/oxidized/.config/oxidized/router.db"
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      ip: 1
      model: 2`

![image](https://github.com/ytti/oxidized/assets/127331418/75e5ce25-ddb4-44e9-9d7f-8242015133d7)

**Comment by yoakim** [comment]
How does the router.db looks like?

**Comment by cchamerski** [comment]
This is it:
```# /opt/oxidized/.config/oxidized/router.db

# hostname:ip:model:group
AGG01:10.111.33.1:ex3400-24t:juniper
MGT01:10.111.33.8:ex3400-24t:juniper
MGT02:10.111.33.3:ex3400-24t:juniper
MGT03:10.111.33.4:ex3400-24t:juniper

**Comment by cchamerski** [comment]
Here's the config file @yoakim :

```username: omitted
password: omitted
model: junos
resolve_dns: true
interval: 3600
use_syslog: false
debug: false
threads: 30
use_max_threads: false
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 0.0.0.0:8888
next_adds_job: false
vars: {}
groups: {}
group_map: {}
models: {}
pid: "/home/oxidized/.config/oxidized/pid"
crash:
  directory: "/home/oxidized/.config/oxidized/crashes"
  hostnames: false
stats:
  history_size: 10
input:
  default: ssh, telnet
  debug: false
  ssh:
    secure: false
  ftp:
    passive: true
  utf8_encoded: true
output:
  default: file
  file:
    directory: "/home/oxidized/.config/oxidized/configs"
source:
  default: csv
  csv:
    file: "/home/oxidized/.config/oxidized/router.db"
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      ip: 1
      model: 2
    gpg: false
model_map:
  juniper: junos
  cisco: ios`

**Comment by cchamerski** [comment]
I've looked inside the docker image and it looks like it's using different router.db config. I wonder why it's not synching with the external router.db file. Should I delete it?
