### ISSUE TITLE
Error loading config: undefined method `unsafe_load' for Psych:Module

### ISSUE THREAD

**Issue by noodleslin** [ytti/oxidized#2839]
[root@Oxidized-v-szzb ~]# oxidized -d
Error loading config: undefined method `unsafe_load' for Psych:Module
Did you mean?  safe_load

Somebody help me !

**Comment by yoakim** [comment]
#2769

**Comment by noodleslin** [comment]
> [第2769章](https://github.com/ytti/oxidized/issues/2769)

[root@Oxidized-v-szzb oxidized]# oxidized -d
Error loading config: undefined method `unsafe_load' for Psych:Module
Did you mean?  safe_load
[root@Oxidized-v-szzb oxidized]#  gem install psych -v 3.3.2 
Building native extensions. This could take a while...
Successfully installed psych-3.3.2
Parsing documentation for psych-3.3.2
Done installing documentation for psych after 0 seconds
1 gem installed
[root@Oxidized-v-szzb oxidized]# oxidized -d
Error loading config: undefined method `unsafe_load' for Psych:Module
Did you mean?  safe_load

**Comment by noodleslin** [comment]
Somebody help me !

**Comment by minhngoc25a** [comment]
Read this: https://www.freecodecamp.org/news/how-to-format-code-in-markdown/#:~:text=There%20are%20two%20ways%20to,will%20apply%20syntax%20highlighting%20to.

**Comment by noodleslin** [comment]
> Read this: https://www.freecodecamp.org/news/how-to-format-code-in-markdown/#:~:text=There%20are%20two%20ways%20to,will%20apply%20syntax%20highlighting%20to.
It's no use

**Comment by AndreyPilipenko** [comment]
this have this mistake

xidized-oxidized-1  | Did you mean?  safe_load
oxidized-oxidized-1  | Error loading config: undefined method `unsafe_load' for Psych:Module
oxidized-oxidized-1  | Did you mean?  safe_load
oxidized-oxidized-1  | Error loading config: undefined method `unsafe_load' for Psych:Module
oxidized-oxidized-1  | Did you mean?  safe_load
oxidized-oxidized-1  | Error loading config: undefined method `unsafe_load' for Psych:Module
