### ISSUE TITLE
skip diff uptime

### ISSUE THREAD

**Issue by asepkampak** [ytti/oxidized#284]
hai, how can i skip diff uptime device? i always get notification about diff uptime device, although no configuration change. so annoying every hour get mail notificaton about uptime device. the device is cisco 2960.
thanks

**Comment by supertylerc** [comment]
@asepkampak, do you know which command is displaying the uptime?  I don't have a 2960 to test.  :(

**Comment by laf** [comment]
I'm running a WS-C2960S-24TS-L at home and don't see that issue. I don't think I'm upto date codebase. If needs be I can update and see if it still works ok.

**Comment by ytti** [comment]
https://github.com/ytti/oxidized/blob/master/lib/oxidized/model/ios.rb#L32

uptime ought to come from 'sh ver', and we're only taking first line.

I seem to recall someone else complained similar stuff, but as I recall the troubleshooting was somehow dead-end.

If you're running latest can you do
 1. try both 'telnet' and 'ssh' and tell if both have same problem
 2. let us know what is the output stored for 'show ver'
 3. can you setup mock 2960 which exhibits this problem somewhere Internet reachable (mock, so no company information etc, just minimal config to reproduce).

**Comment by asepkampak** [comment]
1. only telnet works, ssh not yet configured because using old ios version, theres no crypto key generate rsa command.

2. here show version output. > show version
Cisco IOS Software, C2960 Software (C2960-LANBASE-M), Version 12.2(25)SEE3, RELEASE SOFTWARE (fc2)
Copyright (c) 1986-2007 by Cisco Systems, Inc.
Compiled Thu 22-Feb-07 13:57 by myl
Image text-base: 0x00003000, data-base: 0x00AA3380

ROM: Bootstrap program is C2960 boot loader
BOOTLDR: C2960 Boot Loader (C2960-HBOOT-M) Version 12.2(25r)SEE1, RELEASE SOFTWARE (fc1)

comp_MAIN_switch uptime is **6 weeks, 5 days, 7 hours, 22 minutes**
System returned to ROM by power-on
System restarted at 03:00:00 JAVT Fri Dec 11 2015
System image file is "flash:c2960-lanbase-mz.122-25.SEE3/c2960-lanbase-mz.122-25.SEE3.bin"

cisco WS-C2960-24TC-L (PowerPC405) processor (revision E0) with 61440K/4088K bytes of memory.
Processor board ID FOC1129X1TN
Last reset from power-on
3 Virtual Ethernet interfaces
24 FastEthernet interfaces
2 Gigabit Ethernet interfaces
The password-recovery mechanism is enabled.

64K bytes of flash-simulated non-volatile configuration memory.
Base ethernet MAC Address       : 00:1C:F9:B8:EF:80
Motherboard assembly number     : 73-9832-07
Power supply part number        : 341-0097-02
Motherboard serial number       : FOC11290C7L
Power supply serial number      : AZS112815QU
Model revision number           : E0
Motherboard revision number     : A0
Model number                    : WS-C2960-24TC-L
System serial number            : FOC1129X1TN
Top Assembly Part Number        : 800-26671-03
Top Assembly Revision Number    : A0
Version ID                      : V03
CLEI Code Number                : COM3K00BRB
Hardware Board Revision Number  : 0x01


Switch   Ports  Model              SW Version              SW Image
------   -----  -----              ----------              ----------
*    1   26     WS-C2960-24TC-L    12.2(25)SEE3            C2960-LANBASE-M


Configuration register is 0xF

3. yes i will give you access to my switch, but not here. can you give mail address or something else to send access information.

again, i found cisco 3560G version 12.2(50)SE1  have same issue.

**Comment by ytti** [comment]
My email address is saku@ytti.fi thanks!

**Comment by asepkampak** [comment]
solved by @ytti  thanks

**Comment by ytti** [comment]
Fixed by 3a3d523f7f7c

**Comment by ytti** [comment]
Just to elaborate on the thread as well why this happened. If user is not enebled, we did this

send('enable')
send(secret)

The problem here is, that send(secret) will produce prompt on the device, which send() does not read. 

So our prompt accounting is broken, as we have spurious prompt on the line. Depending on network latencies, computer speed, weighting of Cthulhu's dices, we 'sh ver' might end up outputting 'password:' or, as in OP's case, whole 'sh ver'.

Solution was to eat the extra prompt by changing send(secret) to cmd(secret) which expects to see prompt.
