### ISSUE TITLE
pfSense config fails

### ISSUE THREAD

**Issue by LoZio** [ytti/oxidized#2842]
Using 0.28.0-64-gcb11391
I have 4 pfSenses. One is 2.6 and the configuration is received correctly.
Previous ones (<2.6) get the attached error page:
```
NoMethodError at /node/version/view
undefined method `output' for nil:NilClass
file: nodes.rb location: block in yield_node_output line: 176
```
Attached is the html page renamed to txt
[error.txt](https://github.com/ytti/oxidized/files/11881533/error.txt)

**Comment by LoZio** [comment]
Tested again with 0.29.1, same resulr.
Attached the debug.
[debug.log](https://github.com/ytti/oxidized/files/11881716/debug.log)

**Comment by macaddict89** [comment]
looks like this is the issue: #2771
