### ISSUE TITLE
Oxidized Config in GUI

### ISSUE THREAD

**Issue by cipherjcipher** [ytti/oxidized#2845]
Hello, 

For some reason, our configs are not showing correctly. They are shown in the format below. It was working fine before; something changed, and we can't get it back.  We would rather not reinstall if possible. Thank you for any help!

<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <title>TypeError at &#x2F;node&#x2F;fetch&#x2F;x.x.x.x</title>
 
  <script type="text/javascript">
  //<!--
  function toggle(id) {
    var pre  = document.getElementById("pre-" + id);
    var post = document.getElementById("post-" + id);
    var context = document.getElementById("context-" + id);

**Comment by mortzu** [comment]
Please open an issue in https://github.com/ytti/oxidized-web
