### ISSUE TITLE
Issue with pushing to Git repo when ssh-rsa key not in known_hosts

### ISSUE THREAD

**Issue by NielsH** [ytti/oxidized#2849]
Hi all,

We recently encountered an issue where pushing our config to Git fails with the following error:
```
Hook push_to_remote (#<GithubRepo:0x00007f1dae733340>) failed (#<Rugged::SshError: failed to set hostkey preference: The requested method(s) are not currently supported>) for event :post_store
```

 After some debugging, we discovered that the cause was that in our `~/.ssh/known_hosts`, we only have the `ecdsa-sha2-nistp256` key of our Git server. Once we add the `ssh-rsa` key to the `~/.ssh/known_hosts` file, it works as intended.

I believe this is an error in Rugged, and unrelated to Oxidized itself, and it is something we can work around. However my concern is that this is not seen in the monitoring. We use the following Nagios Monitoring script from https://github.com/ytti/oxidized/issues/67, which we had to modify slightly on line 13, and now contains:

```ruby
#!/usr/bin/env ruby

## contrib via https://github.com/ytti/oxidized/issues/67

require 'open-uri'
require 'json'

critical = false
pending = false
critical_nodes = []
pending_nodes = []

json = JSON.parse(URI.open("http://localhost:8888/nodes.json").read)
json.each do |node|
  next if !ARGV.empty? && (ARGV[0] != node['name'])

  if node['last'].nil?
    pending_nodes << node['name']
    pending = true
  elsif node['last']['status'] != 'success'
    critical_nodes << node['name']
    critical = true
  end
end

if critical
  puts '[CRIT] Unable to backup: ' + critical_nodes.join(',')
  exit 2
elsif pending
  puts '[WARN] Pending backup: ' + pending_nodes.join(',')
  exit 1
else
  if ARGV.empty?
    puts '[OK] Backup of all nodes completed successfully.'
  else
    puts '[OK] Backup of node ' + ARGV[0] + ' completed successfully.'
  end
  exit 0
end
```

We would like for a failed `push_to_remote` hook that the backup is marked as failed. Currently it is marked as a successs. Because of this we were unaware that our backups were failing for quite some time. Could this behavior be changed?

We are running:
- Debian 11
- Ruby 3.1.4
- Rugged 1.6.3
- Oxidized 0.29.1

**Comment by BrunoBlanes** [comment]
Hey, I am currently facing this issue, could you please guide me on your workaround? Thanks!

**Comment by NielsH** [comment]
Hi @BrunoBlanes 
We have no workaround for the lack of monitoring in case of such a failure.

However, to get the backups working again we just added all the keys to the `~/.ssh/known_hosts` file.

```
ssh-keyscan -H $ip >> ~/.ssh/known_hosts;
```

Substitute $ip for your git backend and switches/routers you are making backups of.

**Comment by BrunoBlanes** [comment]
Thanks @NielsH that did the trick.
