### ISSUE TITLE
Password protect Oxidized web interface

### ISSUE THREAD

**Issue by DervMan** [ytti/oxidized#285]
Started using Oxidize yesterday but struggling to find many examples etc, or even the IRC for it! So please forgive me if this question has been answered before. Is it possible to use basic auth on the Oxidized web interface, just want to stop other people from seeing the device configurations?

Thanks!

**Comment by ytti** [comment]
No worries, you're dead on, documents are lacking.

Right now it's not possible to have authentication. It wouldn't be particularly hard to add that, but I fear that if we do it, then next guy wants tacacs, radius, pam etc auth, then we're reimplementing lot of stuff better implemented by smarter people of nginx, apache etc. 
So lot of people have something like nginx or apache in front of oxidized, with oxidized serving only at 127.0.0.1, then you can capitalise on all the features provided by proper web server.

Having said that, other people have requested this as well:
https://github.com/ytti/oxidized-web/issues/85

**Comment by DervMan** [comment]
Great, I'll keep an eye on the website! Many thanks.

Incidentally is there an IRC channel or fourm for Oxidize?

**Comment by ytti** [comment]
I've sporadically hanged on freenode and ircnet #oxidized, but I'm right now recovering from server HW broken, so I'm not hanging on all channels I used to. 
I think I'll ditch ircnet and just keep #oxidized on freenode

**Comment by ytti** [comment]
Closing this. I'm not saying we'll never do this, but at any rate it's oxidized-web issue, not oxidized.
