### ISSUE TITLE
Dependency issue

### ISSUE THREAD

**Issue by AndreyPilipenko** [ytti/oxidized#2852]
Hello! When I start the docker container oxidized](https://github.com/ytti/oxidized I have error 
---------
oxidized-oxidized-1  | Error loading config: undefined method `unsafe_load' for Psych:Module
oxidized-oxidized-1  | Did you mean?  safe_load
oxidized-oxidized-1  | Error loading config: undefined method `unsafe_load' for Psych:Module
oxidized-oxidized-1  | Did you mean?  safe_load
oxidized-oxidized-1  | Error loading config: undefined method `unsafe_load' for Psych:Module
oxidized-oxidized-1  | Did you mean?  safe_load
--------------
Only helps me when I connect to the container and execute 
root@eef882eba7f0:/# apt update
root@eef882eba7f0:/# apt install make
root@eef882eba7f0:/# gem install psych -v 3.3.2
------------

**Comment by AndreyPilipenko** [comment]
Not sure why oxidized shoes passing start if it doesn't work

**Comment by yoakim** [comment]
What image id do you have on your docker image?

**Comment by AndreyPilipenko** [comment]
Thank you so much looks like I had an old image
