### ISSUE TITLE
CiscoSMB config file output not clean

### ISSUE THREAD

**Issue by securactive-hlm** [ytti/oxidized#287]
Hi, 

config file output of CiscoSMB devices (tested on three different) is not clean : 

see output : 

show running-config
^Mconfig-file-header
sw-test-desk-1
v1.4.1.3 / R800_NIK_1_4_194_194
CLI v1.0
set system mode switch

file SSD indicator encrypted
...

I would expect to have first line deleted.
And I don't understand why  ^M stands at the beginning of second line

@ytti : output is coming from the test switch on which you debugged previous ssh prompt problem.

Regards

**Comment by ytti** [comment]
I think this fixes it:
https://github.com/ytti/oxidized/commit/a8ffc4d243c61d6757c07dd24e93c68d42147bdd

Are you running latest from github? I think I'll publish 0.10.2

**Comment by ytti** [comment]
Try with 0.11.0

**Comment by securactive-hlm** [comment]
Ok I'll test that and do a feedback.

**Comment by securactive-hlm** [comment]
I confirm 0.11 makes it, thanks
