### ISSUE TITLE
New ProCurve prompt regex broke some models

### ISSUE THREAD

**Issue by cjwbath** [ytti/oxidized#2871]
The new prompt regex for procurve in 0.29.1 includes a load of extra VT100 control char matching:
`/(^\r|\e\[24;[0-9][hH])?([\w\s.-]+(\((config|vlan-[0-9]{1,4}|y\/n)\)|\(o\)nce)?[#>:?\]] {1,2})($|(\e\[24;[0-9][0-9]?[hH]){3})/`

This appears to be somehow overly greedy and break config fetching for certain older procurve models such as 5412zl chassis and 2610.

I did not debug in depth - nonprinting characters coupled with such a complicated regex gave me a headache. However, when I reverted to the previous prompt regex `/^\r?([\w\s.-]+# )$/` things started working properly again. We have many different models of ProCurve including 2930F, 2510, 2530, 2540, 3810M, 2920, 2810, 2610, 2620, 5412R and the old prompt regex works for them all so wondering what specific case was fixed with the new one?

Attached is a debug dump (i.e. with _debug: true_ configured and retrieved from the logs directory) which hopefully I have managed to sanitize without ruining the control characters sequences:
[procurve-2610-example.txt](https://github.com/ytti/oxidized/files/12048511/procurve-2610-example.txt)

**Comment by n1c0x** [comment]
Hello, 
I have the same problem, only with 2510 and 2610 models (2520, 2530 are working fine. 
The config is not polled entirely, and the polled information have the CPU utilization and packets Rx and Tx. Which means, it is polled everytime there is a change, so very frequently. 

I also have 0.29.1 oxidized version. 

Here is a debug log from a 2610 model 

<pre>
D, [2023-09-07T10:17:42.187470 #2529152] DEBUG -- : lib/oxidized/worker.rb: Added /lvr-2610-r16-1.salm.int to the job queue
D, [2023-09-07T10:17:42.188172 #2529152] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2023-09-07T10:17:42.187565 #2529152] DEBUG -- : lib/oxidized/job.rb: Starting fetching process for lvr-2610-r16-1.salm.int at 2023-09-07 08:17:42 UTC
D, [2023-09-07T10:17:42.188414 #2529152] DEBUG -- : lib/oxidized/input/ssh.rb: Connecting to lvr-2610-r16-1.salm.int
D, [2023-09-07T10:17:42.188531 #2529152] DEBUG -- : AUTH METHODS::["none", "publickey", "password"]
D, [2023-09-07T10:17:43.189367 #2529152] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2023-09-07T10:17:44.190607 #2529152] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2023-09-07T10:17:45.191830 #2529152] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2023-09-07T10:17:46.025962 #2529152] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/(^\r|\e\[24;[0-9][hH])?([\w\s.-]+(\((config|vlan-[0-9]{1,4}|y\/n)\)|\(o\)nce)?[#>:?\]] {1,2})($|(\e\[24;[0-9][0-9]?[hH]){3})/] at lvr-2610-r16-1.salm.int
D, [2023-09-07T10:17:46.193078 #2529152] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2023-09-07T10:17:47.194306 #2529152] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2023-09-07T10:17:47.248896 #2529152] DEBUG -- : lib/oxidized/input/cli.rb: Running post_login commands at lvr-2610-r16-1.salm.int
D, [2023-09-07T10:17:47.248996 #2529152] DEBUG -- : lib/oxidized/input/cli.rb: Running post_login command: "no page", block: nil at lvr-2610-r16-1.salm.int
D, [2023-09-07T10:17:47.249023 #2529152] DEBUG -- : lib/oxidized/input/ssh.rb no page @ lvr-2610-r16-1.salm.int with expect: /(^\r|\e\[24;[0-9][hH])?([\w\s.-]+(\((config|vlan-[0-9]{1,4}|y\/n)\)|\(o\)nce)?[#>:?\]] {1,2})($|(\e\[24;[0-9][0-9]?[hH]){3})/
D, [2023-09-07T10:17:47.249307 #2529152] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/(^\r|\e\[24;[0-9][hH])?([\w\s.-]+(\((config|vlan-[0-9]{1,4}|y\/n)\)|\(o\)nce)?[#>:?\]] {1,2})($|(\e\[24;[0-9][0-9]?[hH]){3})/] at lvr-2610-r16-1.salm.int
D, [2023-09-07T10:17:47.658141 #2529152] DEBUG -- : lib/oxidized/model/model.rb Collecting commands' outputs
D, [2023-09-07T10:17:47.658258 #2529152] DEBUG -- : lib/oxidized/model/model.rb Executing show version
D, [2023-09-07T10:17:47.658300 #2529152] DEBUG -- : lib/oxidized/input/ssh.rb show version @ lvr-2610-r16-1.salm.int with expect: /(^\r|\e\[24;[0-9][hH])?([\w\s.-]+(\((config|vlan-[0-9]{1,4}|y\/n)\)|\(o\)nce)?[#>:?\]] {1,2})($|(\e\[24;[0-9][0-9]?[hH]){3})/
D, [2023-09-07T10:17:47.658647 #2529152] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/(^\r|\e\[24;[0-9][hH])?([\w\s.-]+(\((config|vlan-[0-9]{1,4}|y\/n)\)|\(o\)nce)?[#>:?\]] {1,2})($|(\e\[24;[0-9][0-9]?[hH]){3})/] at lvr-2610-r16-1.salm.int
D, [2023-09-07T10:17:48.069329 #2529152] DEBUG -- : lib/oxidized/model/model.rb Executing show modules
D, [2023-09-07T10:17:48.069413 #2529152] DEBUG -- : lib/oxidized/input/ssh.rb show modules @ lvr-2610-r16-1.salm.int with expect: /(^\r|\e\[24;[0-9][hH])?([\w\s.-]+(\((config|vlan-[0-9]{1,4}|y\/n)\)|\(o\)nce)?[#>:?\]] {1,2})($|(\e\[24;[0-9][0-9]?[hH]){3})/
D, [2023-09-07T10:17:48.069666 #2529152] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/(^\r|\e\[24;[0-9][hH])?([\w\s.-]+(\((config|vlan-[0-9]{1,4}|y\/n)\)|\(o\)nce)?[#>:?\]] {1,2})($|(\e\[24;[0-9][0-9]?[hH]){3})/] at lvr-2610-r16-1.salm.int
D, [2023-09-07T10:17:48.195598 #2529152] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2023-09-07T10:17:48.680097 #2529152] DEBUG -- : lib/oxidized/model/model.rb Executing show interfaces transceiver
D, [2023-09-07T10:17:48.680179 #2529152] DEBUG -- : lib/oxidized/input/ssh.rb show interfaces transceiver @ lvr-2610-r16-1.salm.int with expect: /(^\r|\e\[24;[0-9][hH])?([\w\s.-]+(\((config|vlan-[0-9]{1,4}|y\/n)\)|\(o\)nce)?[#>:?\]] {1,2})($|(\e\[24;[0-9][0-9]?[hH]){3})/
D, [2023-09-07T10:17:48.680438 #2529152] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/(^\r|\e\[24;[0-9][hH])?([\w\s.-]+(\((config|vlan-[0-9]{1,4}|y\/n)\)|\(o\)nce)?[#>:?\]] {1,2})($|(\e\[24;[0-9][0-9]?[hH]){3})/] at lvr-2610-r16-1.salm.int
D, [2023-09-07T10:17:49.085553 #2529152] DEBUG -- : lib/oxidized/model/model.rb Executing show flash
D, [2023-09-07T10:17:49.085633 #2529152] DEBUG -- : lib/oxidized/input/ssh.rb show flash @ lvr-2610-r16-1.salm.int with expect: /(^\r|\e\[24;[0-9][hH])?([\w\s.-]+(\((config|vlan-[0-9]{1,4}|y\/n)\)|\(o\)nce)?[#>:?\]] {1,2})($|(\e\[24;[0-9][0-9]?[hH]){3})/
D, [2023-09-07T10:17:49.085962 #2529152] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/(^\r|\e\[24;[0-9][hH])?([\w\s.-]+(\((config|vlan-[0-9]{1,4}|y\/n)\)|\(o\)nce)?[#>:?\]] {1,2})($|(\e\[24;[0-9][0-9]?[hH]){3})/] at lvr-2610-r16-1.salm.int
D, [2023-09-07T10:17:49.196813 #2529152] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2023-09-07T10:17:49.487850 #2529152] DEBUG -- : lib/oxidized/model/model.rb Executing show system-information
D, [2023-09-07T10:17:49.487922 #2529152] DEBUG -- : lib/oxidized/input/ssh.rb show system-information @ lvr-2610-r16-1.salm.int with expect: /(^\r|\e\[24;[0-9][hH])?([\w\s.-]+(\((config|vlan-[0-9]{1,4}|y\/n)\)|\(o\)nce)?[#>:?\]] {1,2})($|(\e\[24;[0-9][0-9]?[hH]){3})/
D, [2023-09-07T10:17:49.488179 #2529152] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/(^\r|\e\[24;[0-9][hH])?([\w\s.-]+(\((config|vlan-[0-9]{1,4}|y\/n)\)|\(o\)nce)?[#>:?\]] {1,2})($|(\e\[24;[0-9][0-9]?[hH]){3})/] at lvr-2610-r16-1.salm.int
D, [2023-09-07T10:17:49.889903 #2529152] DEBUG -- : lib/oxidized/model/model.rb Executing show system information
D, [2023-09-07T10:17:49.889977 #2529152] DEBUG -- : lib/oxidized/input/ssh.rb show system information @ lvr-2610-r16-1.salm.int with expect: /(^\r|\e\[24;[0-9][hH])?([\w\s.-]+(\((config|vlan-[0-9]{1,4}|y\/n)\)|\(o\)nce)?[#>:?\]] {1,2})($|(\e\[24;[0-9][0-9]?[hH]){3})/
D, [2023-09-07T10:17:49.890240 #2529152] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/(^\r|\e\[24;[0-9][hH])?([\w\s.-]+(\((config|vlan-[0-9]{1,4}|y\/n)\)|\(o\)nce)?[#>:?\]] {1,2})($|(\e\[24;[0-9][0-9]?[hH]){3})/] at lvr-2610-r16-1.salm.int
D, [2023-09-07T10:17:50.092258 #2529152] DEBUG -- : lib/oxidized/model/model.rb Executing show running-config
D, [2023-09-07T10:17:50.092365 #2529152] DEBUG -- : lib/oxidized/input/ssh.rb show running-config @ lvr-2610-r16-1.salm.int with expect: /(^\r|\e\[24;[0-9][hH])?([\w\s.-]+(\((config|vlan-[0-9]{1,4}|y\/n)\)|\(o\)nce)?[#>:?\]] {1,2})($|(\e\[24;[0-9][0-9]?[hH]){3})/
D, [2023-09-07T10:17:50.092698 #2529152] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/(^\r|\e\[24;[0-9][hH])?([\w\s.-]+(\((config|vlan-[0-9]{1,4}|y\/n)\)|\(o\)nce)?[#>:?\]] {1,2})($|(\e\[24;[0-9][0-9]?[hH]){3})/] at lvr-2610-r16-1.salm.int
D, [2023-09-07T10:17:50.197962 #2529152] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2023-09-07T10:17:50.294524 #2529152] DEBUG -- : lib/oxidized/input/cli.rb Running pre_logout commands at lvr-2610-r16-1.salm.int
D, [2023-09-07T10:17:50.294604 #2529152] DEBUG -- : lib/oxidized/input/ssh.rb logout
y
n @ lvr-2610-r16-1.salm.int with expect: nil
D, [2023-09-07T10:17:51.199195 #2529152] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2023-09-07T10:17:52.200463 #2529152] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2023-09-07T10:17:52.539977 #2529152] DEBUG -- : lib/oxidized/node.rb: Oxidized::SSH ran for lvr-2610-r16-1.salm.int successfully
D, [2023-09-07T10:17:52.540097 #2529152] DEBUG -- : lib/oxidized/job.rb: Config fetched for lvr-2610-r16-1.salm.int at 2023-09-07 08:17:52 UTC
I, [2023-09-07T10:17:53.207390 #2529152]  INFO -- : Configuration updated for /lvr-2610-r16-1.salm.int
I, [2023-09-07T10:17:53.207721 #2529152]  INFO -- : GithubRepo: Pushing local repository(/home/oxidized/.config/oxidized/git-repos/default.git/)...
I, [2023-09-07T10:17:53.207753 #2529152]  INFO -- : GithubRepo: to remote: git@vsm-infra-git.salm.int:oxidized/switch-config.git
D, [2023-09-07T10:17:53.280595 #2529152] DEBUG -- : GithubRepo: Authenticating using ssh keys as 'git'
D, [2023-09-07T10:17:53.608196 #2529152] DEBUG -- : GithubRepo: {:total_objects=>0, :indexed_objects=>0, :received_objects=>0, :local_objects=>0, :total_deltas=>0, :indexed_deltas=>0, :received_bytes=>0}
D, [2023-09-07T10:17:53.608282 #2529152] DEBUG -- : GithubRepo: nothing received after fetch
D, [2023-09-07T10:17:53.676622 #2529152] DEBUG -- : GithubRepo: Authenticating using ssh keys as 'git'
D, [2023-09-07T10:17:54.112471 #2529152] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 18 of 197
</pre>

Below my oxidized config

<pre>
---
# Configuration reference
# https://github.com/ytti/oxidized/blob/master/docs/Configuration.md

rest: 0.0.0.0:8888
username: username
password: password
interval: 3600
resolve_dns: true
log: /var/log/oxidized/oxidized.log
debug: false
source:
  default: http
  debug: true
  http:
    url: http://localhost/api/v0/oxidized
    map:
        name: hostname
        model: os
        group: group
    headers:
        X-Auth-Token: 'TOKEN'

model_map:
  cisco: ios
  hp: procurve
  arubaos-cx: aoscx
  ftd: firelinuxos
  ciscowlc: aireos

groups:
  ftd
    username: username
    password: password
    model: ftd

output:
  default: git
  git:
    single_repo: true
    user: oxidized
    email: oxidized@groupe.schmidt
    repo: "/home/oxidized/.config/oxidized/git-repos/default.git"
  file:
    directory: "/home/oxidized/.config/oxidized/configs"

hooks:
  push_to_remote:
    type: githubrepo
    events: [post_store]
    remote_repo: "git@vsm-infra-git.salm.int:oxidized/switch-config.git"
    publickey: /home/oxidized/.ssh/id_rsa.pub
    privatekey: /home/oxidized/.ssh/id_rsa
</pre>

And an example of the 3 last polled "configs"

Version 495 :
<pre>
! Image stamp:    /sw/code/build/nemo
!                 Mar  5 2018 17:13:51
!                 R.11.122
!                 712
! Boot Image:     Primary
! Invalid input: modules
! Invalid input: transceiver
! Image           Size(Bytes)   Date   Version
! -----           ----------  -------- -------
! Primary Image   : 4051243   03/05/18 R.11.122
! Secondary Image : 3793156   04/01/09 R.11.30 
! Boot Rom Version: R.10.06
! Current Boot    : Primary
! 
! 
!  Status and Counters - General System Information
! 
!   System Name        : LVR-2610-R16-1                                  !   ROM Version        : R.10.06          Serial Number      : CN831ZU02B  
! 
 
  IP Mgmt  - Pkts Rx : 125,132,383      Packet   - Total   : 3020        
             Pkts Tx : 83,242,627       Buffers    Free    : 2906        
</pre>

Version 494 : 
<pre>
! Image stamp:    /sw/code/build/nemo
!                 Mar  5 2018 17:13:51
!                 R.11.122
!                 712
! Boot Image:     Primary
! Invalid input: modules
! Invalid input: transceiver
! Image           Size(Bytes)   Date   Version
! -----           ----------  -------- -------
! Primary Image   : 4051243   03/05/18 R.11.122
! Secondary Image : 3793156   04/01/09 R.11.30 
! Boot Rom Version: R.10.06
! Current Boot    : Primary
! 
!   System Contact     : 
!   System Location    : 
! 
!   MAC Age Time (sec) : 300    
! 
!   Time Zone          : 60   
!   Daylight Time Rule : Middle-Europe-and-Portugal
! 
! 
  ROM Version        : R.10.06          Serial Number      : CN831ZU02B  
 
  Up Time            : 126 days         Memory   - Total   : 83,989,008  
  CPU Util (%)       : 34                          Free    : 72,348,384  
</pre>

Version 493 :
<pre>
! Image stamp:    /sw/code/build/nemo
!                 Mar  5 2018 17:13:51
!                 R.11.122
!                 712
! Boot Image:     Primary
! Invalid input: modules
! Invalid input: transceiver
! Image           Size(Bytes)   Date   Version
! -----           ----------  -------- -------
! Primary Image   : 4051243   03/05/18 R.11.122
! Secondary Image : 3793156   04/01/09 R.11.30 
! Boot Rom Version: R.10.06
! Current Boot    : Primary
! 
!   System Contact     : 
!   System Location    : 
! 
!   MAC Age Time (sec) : 300    
! 
!   Time Zone          : 60   
!   Daylight Time Rule : Middle-Europe-and-Portugal
! 
! 
!   Software revision  : R.11.122         Base MAC Addr      : 001ffe-6f2280
 
  Up Time            : 126 days         Memory   - Total   : 83,989,008  
  CPU Util (%)       : 35                          Free    : 72,348,448  
</pre>

**Comment by dfritz79** [comment]
Same too me. I have some 2530 Procurve with older and newer firmware. The newer still work. On older debug log of ssh connection is empty but there is a telnet login try (not configured)

**Comment by MarcHagen** [comment]
I've posted an resolution some time ago please try that on. https://github.com/ytti/oxidized/issues/2833#issuecomment-1601750050

**Comment by robertcheramy** [comment]
This has been closed by PR #3071
