### ISSUE TITLE
Add the ability to configure `pubkey_algorithms` following Net:SSH 7.1.x upgrade

### ISSUE THREAD

**Issue by danpoltawski** [ytti/oxidized#2875]
Following the upgrade to Net:SSH 7.1.0 we had one device type which was logging a failed ssh public key authentication attempt followed immediately by a successful authentication attempt. 

After some difficult debugging (https://github.com/net-ssh/net-ssh/pull/918) it turned out to be caused by https://github.com/net-ssh/net-ssh/pull/838 where by the SSH connection is established by attempting to authenticate with `rsa-sha2-256` and then falling back to `ssh-rsa`.

We don't want these failed logins appearing in our logs so came up with [this patch](https://github.com/ytti/oxidized/commit/3735977d7df1d207a4b59d8515b6524b7f47a6b6) to set the Net::SSH options to force only `ssh-rsa`. It would be good to expose this as a configuration option so it doesn't require a patch.

**Comment by zzambers** [comment]
Possibly already fixed by this PR: https://github.com/net-ssh/net-ssh/pull/891

Additionally reading of [PubkeyAcceptedAlgorithms](https://man.openbsd.org/ssh_config#PubkeyAcceptedAlgorithms) from ssh config file could also be implemented.
