### ISSUE TITLE
Version 0.28 is missing on dockerhub

### ISSUE THREAD

**Issue by j-lahitte** [ytti/oxidized#2879]
Hi, glad to see that Oxidized has new releases and that the dockerhub repo is maintained again.

Just wanted to note that before those 0.29.x releases, there was a working 0.28 version using the"latest" tag on dockerhub, but there was no numbered tag for this version. Therefore we've been pulling latest for a few years with no problem thinking that the repo wouldn't ever be updated again.

Now the latest tag has been replaced a newer 0.29.x release, which is normal, but the 0.28 version using latest previously is now missing on the repo. Is it possible to restore this version on the repo and tag it as 0.28.x-something ? The digest was : 

`8c95b0c99d7f924d34179275cc91909087eaa34a1a6582e328060f428eecd254`

We use it in our production environment and are not ready to move to 0.29 yet so that'd be great.

Thanks !

**Comment by bbrendon** [comment]
Hi @j-lahitte Did you figure this out? I can't get past some ssh issues in 0.29 (https://github.com/ytti/oxidized/issues/2929) and was hoping to roll back but I'm having the same issue you are.

**Comment by j-lahitte** [comment]
Hi, well we still have a copy of the old version on our mirror so that's our a workaround for now, but that'd be nice to have it on dockerhub.
