### ISSUE TITLE
Debug files are named the same as crash files

### ISSUE THREAD

**Issue by fhibler** [ytti/oxidized#288]
Whilst troubleshooting some things I figured out that, if ```debug: true``` in the config file there are always crash files in the log dir, beside the oxidized run was successful. If my understanding of Ruby is correct it's this particular line which is the reason for it?

https://github.com/ytti/oxidized/blob/421ae43ee9546ca0b1c45a9eaf6daa769ab4e9ac/lib/oxidized/input/ssh.rb#L24

According to my train of thoughts it would make way more sense to rename the crash-*-ssh files to debug-*-ssh if they are written by the debug mode instead of the Crash mode. What do you think about it?

**Comment by stefanplug** [comment]
+1 from me if this is indeed the case, this could prevent a witch hunt for crashes.
