### ISSUE TITLE
"source returns no usable nodes" error after docker host reboot

### ISSUE THREAD

**Issue by n1c0x** [ytti/oxidized#2897]
Hello everyone, 
I know, this error appears a lot of times here, but I couldn't find any solution. I read my config files multiple times to see if there is a typo somewhere, but didn't find anything. 

I installed oxidized and LibreNMS a few weeks ago on the same server, but each in its own docker container (multiple docker container for libreNMS). All the container are in the same docker network, which is a bridge. 

Everything worked fine until I restarted my host server. Since then, Oxidized is unable to start, with the following error : 

```
I, [2023-08-02T09:12:01.964453 #2635]  INFO -- : Oxidized starting, running as pid 2635
I, [2023-08-02T09:12:02.020787 #2635]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
I, [2023-08-02T09:12:02.043168 #2635]  INFO -- : lib/oxidized/nodes.rb: Loaded 0 nodes
F, [2023-08-02T09:12:02.043231 #2635] FATAL -- : Oxidized crashed, crashfile written in /home/oxidized/.config/oxidized/crash
source returns no usable nodes
```

Here is my oxidized config file : 

```
---
rest: 0.0.0.0:8888
username: top_secret_username
password: top_secret_password
interval: 3600
resolve_dns: true
use_syslog: false
threads: 30
use_max_threads: false
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
next_adds_job: true
vars: {}
groups: {}
group_map: {}
models: {}
pid: "/home/oxidized/.config/oxidized/pid"
crash:
  directory: "/home/oxidized/.config/oxidized/crashes"
  hostnames: false
stats:
  history_size: 10
input:
  default: ssh
  debug: false
  ssh:
    secure: false
  utf8_encoded: true
source:
  default: http
  debug: false
  http:
    url: http://docker_host:8001/api/v0/oxidized
    map:
      name: hostname
      model: os
      group: group
    headers:
      X-Auth-Token: 'token'
  csv:
    file: "/home/oxidized/.config/oxidized/router.db"
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
    gpg: false
output:
  default: git
  git:
    user: oxidized
    email: o@example.com
    repo: "/home/oxidized/.config/oxidized/git-repos/default.git"
  file:
    directory: "/home/oxidized/.config/oxidized/configs"
```

If I set `default: csv` instead of `default: http` in the input, everything works fine. 
I already renewed the LibreNMS API token multiple times, with multiple rights (Admin and Global Read) with no success. 
If I set `debug: true` in the oxidized file, I don't have any logs in the logs folder. 

Running curl from the oxidized container to the libreNMS container works fine, I get the list of all the devices which are in LibreNMS : 

```
root@1835b2f94b92:/home/oxidized# curl -H 'X-Auth-Token: token' http://docker_host:8001/api/v0/oxidized
[ . . . ]
```

**Comment by adammmmm** [comment]
Now I don't know which version of oxidized you're using but I had a similar issue (just not via librenms) when installing from scratch the other day. I tried downgrading to an older version and found https://github.com/ytti/oxidized/pull/2847 (which added pagination support) to be the culprit in my case, so I just went with 0.29.1 which works perfectly.

**Comment by n1c0x** [comment]
I rolled back the 0.29.1 version and it worked like a charm. Thank you @adammmmm for your help. 
I don't know if I should close the issue, because it doesn't work with the current version.

**Comment by ZummiGummi** [comment]
I'm having the same problem as OP, no changes from last month in my setup, other than updating container images.
LibreNMS and Oxidized in containers, with Oxidized connecting to the LibreNMS API to get the list of devices.
Oxidized is crashing with error.
> source returns no usable nodes
> I, [2023-08-07T01:39:38.850875 #64]  INFO -- : Oxidized starting, running as pid 64
> I, [2023-08-07T01:39:38.933186 #64]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
> I, [2023-08-07T01:39:38.978464 #64]  INFO -- : lib/oxidized/nodes.rb: Loaded 0 nodes
> F, [2023-08-07T01:39:38.978546 #64] FATAL -- : Oxidized crashed, crashfile written in /home/oxidized/.config/oxidized/crash
> 

Container build 0.29.1-15-gdafa835 is working (commit before pagination change), container build 0.29.1-16-g82e434b which is the commit with pagination causes Oxidized to fail with the above error.

**Comment by jamiereid** [comment]
I was having the same issue. Hosting Oxidized and LibreNMS on the same host, in different docker containers. Downgrading to 0.29.1 has resolved the issue.

**Comment by davama** [comment]
Hello,

Im the guy who created the PR.
Saw this ticket and thought id give it a try.

I quickly whipped a librenms instance and added two hosts. Using this configuration:

```
source:
  default: http
  debug: false
  http:
    url: "http://librenms:8000/api/v0/devices"
    scheme: http
    secure: false
    delimiter: !ruby/regexp /:/
    hosts_location: devices
    read_timeout: 300
    map:
      name: sysName
      model: os
      ip: hostname
      group: location
    headers:
      X-Auth-Token: 'blabla'
```

oxidized pulled devices no issue

```
oxidized              | I, [2023-08-23T17:47:09.053585 #26]  INFO -- : Oxidized starting, running as pid 26
oxidized              | I, [2023-08-23T17:47:09.131392 #26]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
oxidized              | I, [2023-08-23T17:47:09.393873 #26]  INFO -- : lib/oxidized/nodes.rb: Loaded 2 nodes
oxidized              | Puma starting in single mode...
oxidized              | * Version 3.11.4 (ruby 3.0.2-p107), codename: Love Song
oxidized              | * Min threads: 0, max threads: 16
oxidized              | * Environment: development
oxidized              | * Listening on tcp://127.0.0.1:8888
oxidized              | Use Ctrl-C to stop
oxidized              | I, [2023-08-23T17:47:20.922963 #26]  INFO -- : Configuration updated for WIFI1/ap-2
oxidized              | I, [2023-08-23T17:47:31.029825 #26]  INFO -- : Configuration updated for WIFI1/ap-1
```

I could also see the log for the query in librenms container

```
librenms             | <ip-redacted> - - [23/Aug/2023:19:47:09 +0200] "GET /api/v0/devices HTTP/1.1" 200 4522 "-" "Ruby"
```

my oxidized version:

```
> docker exec -i oxidized oxidized --version
0.29.1-26-g39bb8cc
```

Just for kicks, i mounted the previous version of `http.rb` file with from [before](https://github.com/ytti/oxidized/blob/41ebd79a42002bb2e4093e62653e59d8bd330a54/lib/oxidized/source/http.rb) the PR and it still passed...

notice the same md5sum

```
> git clone https://github.com/ytti/oxidized
> cd oxidized
> git checkout -b new_branch 41ebd79a42002bb2e4093e62653e59d8bd330a54
Switched to a new branch 'new_branch'
> md5sum lib/oxidized/source/http.rb 
26d859a0936c209b6dc4353b304692f8  lib/oxidized/source/http.rb

> docker exec -it oxidized sh -c "oxidized --version;  md5sum /var/lib/gems/3.0.0/gems/oxidized-0.29.1/lib/oxidized/source/http.rb"
0.29.1-26-g39bb8cc
26d859a0936c209b6dc4353b304692f8  /var/lib/gems/3.0.0/gems/oxidized-0.29.1/lib/oxidized/source/http.rb
```

my logs with old http.rb version

`librenms             | ... - - [23/Aug/2023:19:55:10 +0200] "GET /api/v0/devices HTTP/1.1" 200 4522 "-" "Ruby"`

```
I, [2023-08-23T17:55:10.714483 #25]  INFO -- : Oxidized starting, running as pid 25
I, [2023-08-23T17:55:10.791672 #25]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
I, [2023-08-23T17:55:11.075233 #25]  INFO -- : lib/oxidized/nodes.rb: Loaded 2 nodes
Puma starting in single mode...
* Version 3.11.4 (ruby 3.0.2-p107), codename: Love Song
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://127.0.0.1:8888
Use Ctrl-C to stop
```

Not sure what the issue is... :confused: 

Hope this helps!

Best

**Comment by ZummiGummi** [comment]
Thanks for checking on this @davama 

The LibreNMS documentation shows that the URL Oxidized can use to get devices is, `https://librenms/api/v0/oxidized`

Which returns a list that looks like this,

> {
>         "hostname": "myswitch",
>         "os": "switchos",
>         "ip": "127.0.0.1"
>     },

While the URL you tried is `http://librenms/api/v0/devices` which returns a list that looks like this

> {
>             "device_id": 47,
>             "inserted": null,
>             "hostname": "xxx",
>             "sysName": "xxx",
>             "display": null,
>             "ip": "xxx",
>             "overwrite_ip": null,
>             "community": "xxx",
>             "authlevel": null,
>             "authname": null,
>             "authpass": null,
>             "authalgo": null,
>             "cryptopass": null,
>             "cryptoalgo": null,
>             "snmpver": "v2c",
>             "port": 161,
>             "transport": "udp",
>             "timeout": null,
>             "retries": null,
>             "snmp_disable": 0,
>             "bgpLocalAs": null,
>             "sysObjectID": "xxx",
>             "sysDescr": "xxx",
>             "sysContact": null,
>             "version": "xxx",
>             "hardware": "xxx",
>             "features": "xxx",
>             "location_id": 40,
>             "os": "xxx",

There are also mapping differences in the Oxidized config between yours and the config that LibreNMS has documented. 
https://docs.librenms.org/Extensions/Oxidized/#feeding-oxidized

**Comment by davama** [comment]
Interesting! 

so the special `/oxidized` endpoint returns a list

vs

the regular api `/devices` endpoint returns a dict.

I would add that the `/oxidized` endpoint doesn’t allow for grouping since only returns three fields, so thats lame.

let’s see if i can fix it with a list

**Comment by ytti** [comment]
`node_data += string_navigate(data, @cfg.hosts_location) if @cfg.hosts_location?`

I think if you just remove the +, it should work. You are trying to do `list = list + hash`, which won't work.

**Comment by davama** [comment]
@ytti !
I dont think ive seen you comment in a while 
Glad you still around 

I’ll test and submit a PR

thank you for the tip!

**Comment by davama** [comment]
@ytti 

doing some simple tests by removing `+`. I noticed that the `node_data` object returns an empty `[]` list. So this leads me to believe something is either not right with the `string_navigate` function or the line calling the function...

If i use the OPs config and add a `hosts_location: ""` key as an empty string, it works as intended with librenms `/oxidized` endpoint with and without the `+`

**Comment by ytti** [comment]
```var = something if condition``` initialises `var`as a nil if condition is false and it is not initialised.

In the original code, we already assigned value to the `var` so we don't overwrite is as `nil` on false branch. In the current code this is not the case, we don't use the original value at all. 

You could refactor the condition to cover false branch. Or you could refactor and simply remove the entire node_data out of branches. 

Such as 

```ruby
def method
   if not pagination
       data = blaa
       data = blaa if condition
       return data
   end

   #pagination code
end
```

**Comment by ytti** [comment]
To clarify

# current code
```ruby
data = JSON.parse(response.body)
node_data += string_navigate(data, @cfg.hosts_location) if @cfg.hosts_location?
```
If we don't zoom in to `hosts_location`, we return `nil`, because there is no action on `false` branch

# working1
```ruby
node_data = JSON.parse(response.body)
node_data = string_navigate(data, @cfg.hosts_location) if @cfg.hosts_location?
``` 
We already have node_data value in case `hosts_location`is not defined

# working2
```ruby
data = JSON.parse(response.body)
node_data = @cfg.hosts_location? ?  string_navigate(data, @cfg.hosts_location) : data
```
We cover the false branch, and assign data then

# working3
```ruby
data = JSON.parse(response.body)
node_data = string_navigate(data, @cfg.hosts_location) if @cfg.hosts_location?
node_data = node_data or data
```
We assign data if node_data is false


However, personally I think all these are unidiomatic. Because having the node_data out of the conditions is unnecessary. These cases are same:

# case1
```ruby
def method
   str = ""
   if condition
     str = "foo"
   else
     str = "bar"
   end
   str
end
```

# case2
```ruby
def method
  if condition
    "foo"
  else
    "bar"
  end
end
````
Ruby implicitly returns last value, so the 'if' statement returns the branch it evaluates, and because the if is last statement, the `method` returns the last valued `if`branch. I feel this is cleaner than `case1`, because if we have lot of conditions or long bodies in condition, we don't have to look at top and bottom to know how to actually pass values out of the method.

# case3
```ruby
def method
   if condition
     return "foo"
   end
  "bar"
end
```
In this case we remove the other branch entirely, by returning early. This is isn't outright better than `case2`, but if we have two branches, one of them contains very little code, another lot of code. It is lot cleaner to pick the simple branch, check for that, and return early. Then write the long case, so it's not under the if at all.

Therefore I think the example I gave in previous comment is the most desirable way to do it.

**Comment by davama** [comment]
Update:

I think i have something functional.
Would be nice if someone can confirm too

Thanks!

@ytti fyi

**Comment by ZummiGummi** [comment]
@davama , this has fixed the problem for me. 
I pulled the latest container image and manually updated the http.rb file with your updated one and it's working again.

**Comment by davama** [comment]
@ZummiGummi 
Thank you for the feedback 

can you post that on the PR?
