### ISSUE TITLE
Docker auth issues

### ISSUE THREAD

**Issue by LoveSkylark** [ytti/oxidized#2898]
I just upgraded Oxidized in docker and now it broken:

I have been running it as root because if I trye to run it with the user oxidized I get this error:
   "PermissionError: [Errno 13] Permission denied: '/etc/container_environment'"
 
With root it but then Oxidizes is unable to read the mounted config file:
│ chown: changing ownership of '/home/oxidized/.config/oxidized/config': Read-only file system                                                                                          
│ I, [2023-08-02T13:31:13.097722 #65]  INFO -- : Oxidized starting, running as pid 65                                                                                                   
│ I, [2023-08-02T13:31:13.202058 #65]  INFO -- : lib/oxidized/nodes.rb: Loading nodes                                                                                                   
│ I, [2023-08-02T13:31:13.257493 #65]  INFO -- : lib/oxidized/nodes.rb: Loaded 0 nodes                                                                                                  
│ F, [2023-08-02T13:31:13.257676 #65] FATAL -- : Oxidized crashed, crashfile written in /home/oxidized/.config/oxidized/crash  
 
file inside pod:
-rw-r--r-- 1 root     root     1313 Aug  2 13:30 config
drwxr-xr-x 6 oxidized oxidized 4096 Jul 26 18:05 core.git/
-rw-r--r-- 1 oxidized oxidized  693 Aug  2 13:32 crash
drwxr-xr-x 2 oxidized oxidized 4096 Jan 12  2023 logs/

**Comment by LoveSkylark** [comment]
Nice your fix for versioning for the docker builds just saved my as.

Last working version is: 0.29.1-12-gdab52d0

**Comment by benamormed98** [comment]
You are running Oxidized as oxidized User, but your config file is belong to the root user.

**Comment by LoveSkylark** [comment]
> You are running Oxidized as oxidized User, but your config file is belong to the root user.

I know, I'm building the file with a Helm configMap and that is created by the user that's making the pod, if I change the user from root to oxidized (3000 UID/GID) the oxidized image refuse to load.  So you have to install oxidized as root, then use it as oxidized (witch is problem all by itself).

My problem  is that I have been using this for a year now as is (with config file owned by root) , I have working example for comparison of this setup that has not been upgraded. 

This failure was introduce in version [0.29.1-13-gfd3608e](https://hub.docker.com/layers/oxidized/oxidized/0.29.1-13-gfd3608e/images/sha256-23da4c5e5922a25cb9821885d58f8c12a684f9f98bf841f84f01e83710b00837?context=explore), if I revert to [0.29.1-12-gdab52d0](https://hub.docker.com/layers/oxidized/oxidized/0.29.1-12-gdab52d0/images/sha256-1fff3daae15249777636750e0dd45d5501d51df2c788171f0c3ac3710ce45bd5?context=explore) everything starts working again.

**Comment by benamormed98** [comment]
But i think you can install the image as root user, but when you mount the volume from host to oxidized you have to set the OXIDIZED_HOME, you have to change all the root files to home oxidized ( like PID, output, source ,etc)
