### ISSUE TITLE
PowerConnect sflow timeout changes

### ISSUE THREAD

**Issue by Madpilot0** [ytti/oxidized#290]
Hello,

On a Dell PowerConnect 6248P the timeout command for sflow in the running configuration counts down. This gives me a different version every hour.

-sflow 1 destination owner 1 timeout 4271304700
+sflow 1 destination owner 1 timeout 4271301081

Is there a way to ignore this difference when comparing?

Thanks!

**Comment by ytti** [comment]
Is this for 'show running-config'?

https://github.com/ytti/oxidized/blob/master/lib/oxidized/model/powerconnect.rb

You can copy this file in ~/.config/oxidized/model

And modify it, something like this maybe:

```
cmd 'show running-config' do |cfg|
   sub(/^(sflow 1 destination owner 1 timeout )\d+$/, '! \1<timeout>')
end
````

send pull request when you get desirable output

**Comment by Madpilot0** [comment]
Using that method nets me this error

`raised NoMethodError with msg "undefined method 'sub' for #<PowerConnect:0x00000001694c08>",`

changing to
```
cmd 'show running-config' do |cfg|
	  cfg.sub(/^(sflow 1 destination owner 1 timeout )\d+$/, '! \1<timeout>')
end
```

works for me.

**Comment by ytti** [comment]
Yeah that was my bad.. Send a pull request with that change and we'll integrate it.

**Comment by ytti** [comment]
Actually it looks like ''sflow 1' and 'owner 1' might be variables?

so maybe
````
      cfg.sub(/^(sflow \S+ destination owner \S+ timeout )\d+$/, '! \1<timeout>')
```

**Comment by Madpilot0** [comment]
Yes you are right.

Just tested it and it works. I'll send a pull request soon.
