### ISSUE TITLE
Defined output directory not used

### ISSUE THREAD

**Issue by DokH** [ytti/oxidized#2901]
I just got to know oxidized and came across a silly issue.
When run, the configs are not dropped in de directory I defined, but in the one above.

In config I have:
```
output:
  file:
    directory: "/opt/oxidized/configs/dummy"
```
[Yes, I have it in a dedicated OXIDIZED_HOME=/opt/oxidized directory]

So configurations are actually dropped under 
`/opt/oxidized/configs` (which even gets created automatically)
instead of
`/opt/oxidized/configs/dummy` (which is not created automatically, but even created manually it is not used)

But the dummy directory in the path is required in the config as otherwise the configs are dropped under `/opt/oxidized`

**Comment by robertcheramy** [comment]
This is the intended behaviour for devices without groups, when you are using groups for other devices.
The work around is to add a dummy directory to your path, so here, it would be `/opt/oxidized/configs/dummy/dummy`
