### ISSUE TITLE
Issue saving configuration

### ISSUE THREAD

**Issue by difi80211g** [ytti/oxidized#2905]
I am trying to back up a Fortigate FortiOS.  Oxidized seems to crash when it is trying to save the configuration. This is the crash error:

can't convert Asetus::ConfigStruct to String (Asetus::ConfigStruct#to_str gives Asetus::ConfigStruct)
/var/lib/gems/3.0.0/gems/oxidized-0.29.1/lib/oxidized/output/git.rb:161:in `new': can't convert Asetus::ConfigStruct to String (Asetus::ConfigStruct#to_str gives Asetus::ConfigStruct) (TypeError)
        from /var/lib/gems/3.0.0/gems/oxidized-0.29.1/lib/oxidized/output/git.rb:161:in `update'
        from /var/lib/gems/3.0.0/gems/oxidized-0.29.1/lib/oxidized/output/git.rb:58:in `store'
        from /var/lib/gems/3.0.0/gems/oxidized-0.29.1/lib/oxidized/worker.rb:65:in `process_success'
        from /var/lib/gems/3.0.0/gems/oxidized-0.29.1/lib/oxidized/worker.rb:47:in `process'
        from /var/lib/gems/3.0.0/gems/oxidized-0.29.1/lib/oxidized/worker.rb:16:in `block in work'
        from /var/lib/gems/3.0.0/gems/oxidized-0.29.1/lib/oxidized/worker.rb:16:in `each'
        from /var/lib/gems/3.0.0/gems/oxidized-0.29.1/lib/oxidized/worker.rb:16:in `work'
        from /var/lib/gems/3.0.0/gems/oxidized-0.29.1/lib/oxidized/core.rb:36:in `run'
        from /var/lib/gems/3.0.0/gems/oxidized-0.29.1/lib/oxidized/core.rb:29:in `initialize'
        from /var/lib/gems/3.0.0/gems/oxidized-0.29.1/lib/oxidized/core.rb:4:in `new'
        from /var/lib/gems/3.0.0/gems/oxidized-0.29.1/lib/oxidized/core.rb:4:in `new'
        from /var/lib/gems/3.0.0/gems/oxidized-0.29.1/lib/oxidized/cli.rb:13:in `run'
        from /var/lib/gems/3.0.0/gems/oxidized-0.29.1/bin/oxidized:8:in `<top (required)>'
        from /usr/local/bin/oxidized:25:in `load'
        from /usr/local/bin/oxidized:25:in `<main>'

The debug logs shows it pull the backup but the saving seems to crash it.  I am trying to save to a local git repositiory.

D, [2023-08-11T09:34:57.966103 #778713] DEBUG -- : lib/oxidized/input/cli.rb Running pre_logout commands at <ip>
D, [2023-08-11T09:34:57.966200 #778713] DEBUG -- : lib/oxidized/input/ssh.rb exit
 @ <ip> with expect: nil
D, [2023-08-11T09:34:57.974358 #778713] DEBUG -- : lib/oxidized/node.rb: Oxidized::SSH ran for <ip> successfully
D, [2023-08-11T09:34:57.974446 #778713] DEBUG -- : lib/oxidized/job.rb: Config fetched for <ip> at 2023-08-11 13:34:57 UTC
F, [2023-08-11T09:34:58.002695 #778713] FATAL -- : Oxidized crashed, crashfile written in /opt/oxidized/.config/oxidized/crash

Any suggestions what could be causing the crash?

**Comment by ritzbhuj** [comment]
Hi there,
Do you have groups in your configuration?

**Comment by difi80211g** [comment]
Yes, I have groups but they are the same

**Comment by ritzbhuj** [comment]
It seems like you might be using a single repo for all your configs with multiple groups.

I took this from the outputs.md file. See if it works for you:

- If you would like to use groups and a single repository, you can force this with the single_repo config.

output: default: git git: single_repo: true repo: "/var/lib/oxidized/devices.git"

**Comment by difi80211g** [comment]
Thanks, that helped.  i was able to get it resolved.
