### ISSUE TITLE
"Enable" requires username and password

### ISSUE THREAD

**Issue by asummerell-debug** [ytti/oxidized#2907]
Hopefully someone can help, or point me in the right direction. I have everything up and running, and it's great. However, some of our devices require a username and password for "enable", not just a password. Is this something that can be done? 

I can provide much greater detail and logs if it is possible. Just didn't want to load up a bunch for something that can't be done.

Thanks!

**Comment by robertcheramy** [comment]
You can specify an enable password for each model in the configuration:
```
models:
  asa:
    vars:
      enable: YOUR-SECRET-PASSWORD
```

**Comment by asummerell-debug** [comment]
Thanks for the reply. I have that configured for my devices that only require a password for enable, and that works. However, we have some devices that require a username and password for "enable", not just a password.

**Comment by robertcheramy** [comment]
Could you name which devices types need a username and a password?

**Comment by asummerell-debug** [comment]
Ruckus switches running ver 9.0 firmware and above running AAA for auth.

**Comment by dlehman83** [comment]
I'm having this same issue.  I've never used ruby so trying to figure its syntax on the fly too.  
I copied the ironware model to oxidized home directory to make local edits for now.  But they are not working.  

I'm not 100% sure how I tell it to send the username then password or where "enable" is defined.  
When I run a tail -f on the log here is what I get

```
SSH@switch>enable

Login:
```
Here is my two attempted modifications so far. 
Coding the actual username into the model is not correct, but was just testing.  
```
 else
        post_login do
          send "enable\r\n"
          username /^Login:$/
          #send "myusername\r\n"
          cmd vars(:enable)

        end
```


Thank you
