### ISSUE TITLE
Can't access web via docker compose

### ISSUE THREAD

**Issue by any4one** [ytti/oxidized#2920]
I followed all the steps, but I can't seem to find a way to access the UI.

VM: Ubuntu 22.04
Docker: Docker version 24.04
docker compose version 2.19.1

config file

sername: username
password: password
model: junos
resolve_dns: true
interval: 3600
use_syslog: false
debug: false
threads: 30
use_max_threads: false
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 0.0.0.0:8888
next_adds_job: false
vars: {}
groups: {}
group_map: {}
models: {}
pid: "/root/.config/oxidized/pid"
crash:
directory: "/root/.config/oxidized/crashes"
hostnames: false
stats:
history_size: 10
input:
default: ssh, telnet
debug: false
ssh:
secure: false
ftp:
passive: true
utf8_encoded: true
output:
default: file
source:
default: csv
csv:
file: "/root/.config/oxidized/router.db"
delimiter: !ruby/regexp /:/
map:
name: 0
model: 1
ip: 2
gpg: false
model_map:
juniper: junos
cisco: ios

result after curl 

   Trying 127.0.0.1:8888...
* Connected to 127.0.0.1 (127.0.0.1) port 8888 (#0)
> GET / HTTP/1.1
> Host: 127.0.0.1:8888
> User-Agent: curl/7.81.0
> Accept: */*
> 
* Recv failure: Connection reset by peer
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer

**Comment by robertcheramy** [comment]
- How are you running the docker container? Is the port from the containter forwarded to the local host (comand line option -p 8888:8888/tcp)?
- Maybe the port 8888 ist already been used (you can check with "ss -topln | grep 8888")? Try the option -p 8887:8888/tcp to publish the containter port 8888 to local port 8887
- If you started the containter twice, the port 8888 will be in used from the first container. Check with podman ps (or docker ps). The ports redirections are also listed there.

**Comment by robertcheramy** [comment]
Closed as no input from submitter.
