### ISSUE TITLE
I have installed oxidized and having permission issue while running oxidized

### ISSUE THREAD

**Issue by vivekbhosalethane** [ytti/oxidized#2922]
We have installed librenms on Centos 8 and also installed Oxidized on same VM.
[oxidized@localhost ~]$ oxidized
Permission denied @ rb_sysopen - /root/.config/oxidized/pid
======================================

Here is my config file

[root@localhost oxidized]# cat config
---
username: username
password: password
model: junos
resolve_dns: true
interval: 3600
use_syslog: false
debug: false
threads: 30
use_max_threads: false
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 192.168.230.130:8888
next_adds_job: false
vars: {}
groups: {}
group_map: {}
models: {}
pid: "/root/.config/oxidized/pid"
crash:
  directory: "/root/.config/oxidized/crashes"
  hostnames: false
stats:
  history_size: 10
input:
  default: ssh, telnet
  debug: false
  ssh:
    secure: false
  ftp:
    passive: true
  utf8_encoded: true
output:
  default: file
source:
        default: http
        debug: false
        http:
          url: https://192.168.230.130/api/v0/oxidized
          map:
            name: hostname
            model: os
            group: group
          headers:
            X-Auth-Token: '8e0e972a099927d4df42e1076de0688e'
model_map:
  juniper: junos
  cisco: ios
------------------------------------------------------------------------
Can you please help/understand on above permission error

**Comment by MLyszyk** [comment]
It most likely seems that the Oxidized account can't reach/access the "/root/..." directories. Try having the necessary files in and paths pointing towards the Oxidized account and their directories --> /home/oxidized/.config/oxidized/....

"It is recommended practice to run Oxidized using its own username. This username can be added using standard command-line tools:

useradd -s /bin/bash -m oxidized
It is recommended NOT to run Oxidized as root."

**Comment by vivekbhosalethane** [comment]
Thanks for the comment.

It's done and working fine in test environment

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
