### ISSUE TITLE
Upgrade Path 0.28 -> 0.29

### ISSUE THREAD

**Issue by rbr-acs** [ytti/oxidized#2932]
Hi,

what is the right Upgradepath from 0.28 to 0.29, after installed ruby 3 there ist no gem update. After uninstalled and installed the new version with ruby 3 over "rvm" the binary path changed to  "/usr/local/rvm/gems/ruby-3.0.0/bin/oxidized".

Execute Error are 

root@ACSEWRC01:~# /usr/local/rvm/gems/ruby-3.0.0/bin/oxidized
Error loading config: undefined method `unsafe_load' for Psych:Module
Did you mean?  safe_load

System

root@ACSEWRC01:~# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

root@ACSEWRC01:~# ruby -v
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-linux]

**Comment by realtkco** [comment]
gem install psych -v 3.3.2
