### ISSUE TITLE
Unable to grab Dell OS6 config starting with version 6.8.1

### ISSUE THREAD

**Issue by theherodied** [ytti/oxidized#2944]
Oxidized version 0.29.1 on Debian 12.

Starting with Dell OS6 version 6.8.1 - 6.8.1.3, Oxidized is unable to grab the whole config. It throws this error.

`! 
! Machine Description............... Dell Networking Switch
! System Model ID................... N3248PXE-ON
! Machine Type...................... Dell Networking N3248PXE-ON
! Serial Number..................... XXXXXXXXXXXXXXXXXXXX
! Manufacturer...................... 0xbc00
! Burned In MAC Address............. 185A.58C6.B9A0
! System Object ID.................. 1.3.6.1.4.1.674.10895.3109
! CPU Version....................... C3338
! SOC Version....................... BCM56771_A0
! HW Version........................ 2
! CPLD Versions..................... System 01.06  CPU 00.07
! Image File........................ N3200v6.8.1.3
! Software Capability............... Stack Limit = 12, VLAN Limit = 4093
! 
! unit active      backup      current-active next-active
! ---- ----------- ----------- -------------- --------------
! 1    6.8.1.3     6.7.1.22    6.8.1.3        6.8.1.3
! 2    6.8.1.3     6.7.1.22    6.8.1.3        6.8.1.3
! 3    6.8.1.3     6.7.1.22    6.8.1.3        6.8.1.3
! 4    6.8.1.3     6.7.1.22    6.8.1.3        6.8.1.3
! 
! System Description: Dell Networking Switch
                               ^
% Invalid input detected at '^' marker.`

Everything worked fine up to OS6 6.7.1.22.

**Comment by andrewh** [comment]
Seems like a usage question for the [forum](https://community.librenms.org/c/help/oxidized/10) rather than a bug or issue with Oxidized itself.

We had the same issue on OS10 and use a custom prompt:

```ruby
require 'oxidized/model/os10.rb'
class OS10 < Oxidized::Model
  def prompt
    @prompt = /([#>]\s?)$/
  end
end
```
