### ISSUE TITLE
Extra lines in RouterOS commits

### ISSUE THREAD

**Issue by Mascherus** [ytti/oxidized#2947]
Hello!

A problem has arisen that when collecting configuration files from Mikrotik, there are constantly extra commits to Git:

```
-# 2023-09-19 12:28:10 by RouterOS 7.11
+# 2023-09-19 13:28:29 by RouterOS 7.11^M

```
Please tell me how can I force Oxidized to ignore these changes?

**Comment by Mascherus** [comment]
I see in [#2928](https://github.com/ytti/oxidized/issues/2928) issue was fixed, but doesn't work in my case?

**Comment by sgrimee** [comment]
@Mascherus did you compile from master? The fix is in the master branch but they have not made a release with it yet.
I compiled it from source yesterday and it works for me.

**Comment by sgrimee** [comment]
That does not have the fix. You need to build oxidized from source at this time, from the master branch.

**Comment by Mascherus** [comment]
Thank you! We will try.
