### ISSUE TITLE
JunOS.RB

### ISSUE THREAD

**Issue by realtkco** [ytti/oxidized#2958]
Wouldn't it make much more sense for the config to be tagged with "| display set" so you can restore from a backup of a config much easier? 

[Line 46 junos.rb](https://github.com/ytti/oxidized/blob/52c1f987ab3c051ff0b3f467a9a2e1c7f15b7d4f/lib/oxidized/model/junos.rb)

It would look similar to edgeos's config as well.

**Comment by adammmmm** [comment]
> Wouldn't it make much more sense for the config to be tagged with "| display set" so you can restore from a backup of a config much easier?
> 
> [Line 46 junos.rb](https://github.com/ytti/oxidized/blob/52c1f987ab3c051ff0b3f467a9a2e1c7f15b7d4f/lib/oxidized/model/junos.rb)
> 
> It would look similar to edgeos's config as well.
Speaking from personal preference, the normal configuration style is much more readable than "set" once you get used to it.
It's very easy to restore a normal style junos configuration through the various load options: https://www.juniper.net/documentation/us/en/software/junos/cli/topics/ref/command/load.html

**Comment by realtkco** [comment]
Yep, I see. Makes alot more sense and is very prefrence based. Closed & Thanks.
