### ISSUE TITLE
Creating-Models to trendnet switch

### ISSUE THREAD

**Issue by jairochavezm** [ytti/oxidized#2960]
Could you help me create a file for Trendnet Switch?

TRENDnet, Inc. Model: TI-PG102i 
    Boot Code Version  V1.2.3.S0
    Firmware Version  V1.0.11.S0

Librenms Version	23.9.1
ubuntu:~# oxidized --version
0.29.1

systemd[1]: Started Oxidized - Network Device Configuration Backup Tool.
oxidized[298435]: Puma starting in single mode...
oxidized[298435]: * Version 3.11.4 (ruby 3.0.2-p107), codename: Love Song

How would I configure a ".rb" file in oxidized if on the trendnet switch after the "enable" command to access privileged mode, it requests a username and password, how to send the username and password in the configuration after the enable command.
I show you the connection example:
1.- SSH connection to the switch:
ssh 10.0.0.1
2.- The user "admin" is entered without a password (It only supports the "admin" user for the SSH connection, I don't know why.):
login as: admin
3.- Go directly to the "TI-PG102i>" prompt:
TI-PG102i>
4.- Enter the "enable" command
TI-PG102i>enable
5.- After entering the "enable" command, it requests the user and password credentials:
user: userExample
password: passwordExample
6.- After entering the credentials, go directly to the "TI-PG102i#" prompt:
TI-PG102i#

It is at this point where you can execute commands such as:

TI-PG102i# **show system-info**
CLI auto-logout: 5 minutes.
CPU loading: 3.23%
Memory info: total 127708 KB, free 119124 KB, usage 6.72%

TI-PG102i# **show running-config**

**Comment by jairochavezm** [comment]
I have updated the switch to the most recent version and even so the login method is the same:
   Boot Code Version  V1.2.3.S0
    Firmware Version  V1.0.15.S0

![image](https://github.com/ytti/oxidized/assets/106102541/3132159d-f9e0-45bb-ab36-4f5219c37489)

 The trendnet brand has confirmed that it will not modify the login method via ssh or telnet in its future firmware:

The terminal emulation window should display a prompt for user name and
password.
Enter the user name and password. By default:
Console User Name: admin
Note: User Name and Password are case sensitive.
Enable Mode/Privileged Exec User Name: admin
Enable Mode/Privileged Exec Password: admin

**Comment by rexhaugen** [comment]
I just installed the same model in my environment and it's on the same firmware version.  I was able to get the following to back up the config, though my config is basic with only a single SNMP community.  Before exporting the first config, it is necessary to run the following command on the switch to change its shell output setting, though I have also included the logic for it through a custom variable called 'pagination':
```
configure terminal
set length 29999
end
```

**trendnet.rb:**
```
class TRENDnet < Oxidized::Model
  using Refinements

  prompt /^(\r?[\w.@_()-]+[#>]\s?)$/
  comment '! '

  def filter(cfg)
    cfg.gsub! /\r\n?/, "\n"
    cfg.gsub! prompt, ''
  end

  cmd :secret do |cfg|
    cfg.gsub! /^(snmp community).*/, '\\1 <configuration removed>'
    cfg
  end

  cmd 'show model' do |cfg|
    cfg = filter cfg
    comment cfg
  end

  cmd 'show running-config' do |cfg|
    cfg
  end

  cfg :ssh, :telnet do
    username /^login as:$/

    post_login do
      if vars :enable
        cmd "enable", /^[Uu]ser:$/
        cmd vars(:enable), /^[Pp]assword:$/
        cmd @node.auth[:password], /^(\r?[\w.@_()-]+[#>]\s?)$/
      end
      if vars(:pagination) == true
        cmd 'configure terminal'
        cmd 'set length 29999'
        cmd 'end'
      end
    end

    pre_logout 'exit'
  end
end
```

**config:**
```
models:
  trendnet:
    vars:
      auth_methods: [ "none" ]
      enable: <enable-username>
      pagination: true
      remove_secret: true
source:
  default: csv
  csv:
    file: "/home/oxidized/.config/oxidized/router.db"
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      ip: 1
      model: 2
      username: 3
      password: 4
```

**router.db:**
`<friendly-name>:<switch-IP>:trendnet:admin:<enable-password>`
