### ISSUE TITLE
split device names

### ISSUE THREAD

**Issue by andershagman** [ytti/oxidized#2962]
Hi
I collect device list from Netbox and that works fine.
The problem is if a switch is a stack the device name is not the same as the stack name.
Example:
Stack name: london-l2
Switch names:
london-l2 sw1
london-l2 sw2

"london-l2 sw1" has the IP address.
I want to split the name to get only london-l2.

Is it possible?

**Comment by robertcheramy** [comment]
I think you have to wrap the name in Netbox or in the script that gets the devicelist from netbox.
Oxidized jut uses the devicenames you give in the devicelist.

**Comment by andershagman** [comment]
I can not change the names in Netbox.
It is not a script. It´s built in in Oxidized with source http.

**Comment by robertcheramy** [comment]
This is a Netbox problem then. Netbox is the source of truth and has to pass the right DNS Name to oxidized.

**Comment by andershagman** [comment]
It is not a DNS name it is an inventory name. 
Can I manipulate the file name instead?

**Comment by andershagman** [comment]
I see that you have split functions elsewhere in the code. So is it possible to define your own and refer to that in the config file?

example
var:
  name: splitfunc(name)

**Comment by winterheart** [comment]
You can use Export Templates in Netbox, where you can customize names with Jinja2 templates. So in Netbox names will be unchanged and Oxidized will use split names in way what you want.
https://github.com/wrouesnel/docker.netbox/blob/master/netbox/src/netbox/docs/additional-features/export-templates.md
