### ISSUE TITLE
How to trigger a config backup from rsyslog on Oxidized v.0.29.1?

### ISSUE THREAD

**Issue by mathewfer** [ytti/oxidized#2964]
Hi

I just installed Oxidized v.0.29.1 on a VM and it is all working fine to retrieve the config with periodic config pull.
I use SSH key to access the devices and they work fine too. I can access the devices config and diff on server IP at port 8888 (web interface). I also have GitLab running on the same VM and it too can get the config from Oxidized for better versioning.

Now, I want to setup Oxidized to pull config from syslog when a configuration changes occur on a device.
I installed Rsyslog and it is working fine on UDP port 514. Devices config changes are in "/var/log/messages" file as it is the default file name in "https://github.com/ytti/oxidized/blob/master/extra/syslog.rb"

Question:
What are the steps to integrate Oxidized with Rsyslog to trigger config backup?
If this is tested and working, can you please post a working config files etc?
Thanks in advance. I hope I posted this in the correct place. 

I searched internet but so far, I could not find a working Oxidized configurations to get this working. I found many with LibreNMS but I want only Oxidized with Rsyslog solution.

I found these two files, "syslog.rb" and "rest_client.rb" but I can not understand how to use them.
I am not good at Ruby but I can work with Python if that is supported/possible to get this done.

https://github.com/ytti/oxidized/blob/master/extra/syslog.rb
https://github.com/ytti/oxidized/blob/master/extra/rest_client.rb

/var/log/messages:

```
oxidizeduser@linux-srv:~$ sudo cat /var/log/messages | grep SYS-5-CONFIG_I
Oct 12 23:14:17 10.1.1.20 34: Oct 12 23:14:16.775: %SYS-5-CONFIG_I: Configured from console by console
Oct 12 23:24:15 10.1.1.20 35: Oct 12 23:24:14.535: %SYS-5-CONFIG_I: Configured from console by console
```

oxidized/config file:

```
---
interval: 3600
use_syslog: true
next_adds_job: true
log: /opt/oxidized/.config/oxidized/logs/
debug: false
rest: 0.0.0.0:8888
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp '/^([\w.@-]+[#>]\s?)$/'
next_adds_job: false
pid: "/opt/oxidized/pid"
vars:
  remove_secret: true
  auth_methods: [ "publickey" ]
  ssh_keys: "/opt/oxidized/.ssh/id_rsa_device"
  cumulus_routing_daemon: frr
  cumulus_use_nclu: true
input:
  default: ssh
  debug: false
  ssh:
    secure: false
output:
  default: git
  git:
    single_repo: true
    user: oxidized
    email: oxidized@oxidized.local
    repo: /opt/oxidized/output/configs.git
hooks:
  push_to_remote:
    type: githubrepo
    events:
    - post_store
    remote_repo: "http://localhost/oxidized/configs.git"
    username: oxidized
    password: <password>
source:
  default: csv
  csv:
    file: /opt/oxidized/.config/oxidized/router.db
    delimiter: ":"
    map:
      name: 0
      ip: 1
      model: 2
      group: 3
      username: 4
    vars_map:
      cumulus_routing_daemon: 4
model_map:
  juniper: junos
  cisco: ios
  exos: xos
groups: {}
```

oxidized/router.db:

```
# name:ip::model:group:username
CiscoR1:10.1.1.20:ios:lab:admin
```

Thanks

**Comment by mathewfer** [comment]
Hi 
As I do not see any replies, I assume this is currently not supported natively in Oxidized.

If anyone knows, please let me know how to make an API call via web UI to trigger a config backup.
There is a script running as a service to catch logs by rsyslog, with pattern matching and it can be used but it is not very clear how to make an API call to Oxidized web UI.

Hope to see a way to get this done with Oxidized

**Comment by slinderud** [comment]
Hey,

I also struggled to get this working. So instead of debugging, i just made some scripts instead.
Documented here: https://github.com/gathering/tgmanage/tree/main/tools/oxidized

You probably have to tweak it a little bit to get it working with Cisco. But should be perfectly doable.
If you have any questions, or find a smarter way to do this, please reach out :)

**Comment by mathewfer** [comment]
Thank you for the reply and I will try this.
Importantly, this "http://127.0.0.1:8888/node/next/${host}" helped me as I was not aware how to do the REST API call.
With this I should be able to do a tweak for Cisco. In fact. I need Juniper too. Thanks again
