### ISSUE TITLE
Enable diffie-hellman-group1-sha1 key exchange method via Oxidized config

### ISSUE THREAD

**Issue by aleyval** [ytti/oxidized#2965]
Hi team,

I have an Oxidized instance running in a pod in a Kubernetes cluster, that I use to backup configurations on my infrastructures. There are around 650 target devices.

Among them, ~10% are not backed up. My hypothesis is that it is because they use old key exchange method : only diffie-hellman-group1-sha1 is allowed. In order to debug, I tried accessing them via SSH from the ubuntu that hosts the cluster. By modifying the ssh_config and adding the following, I'm able to successfully access the device. 
```
Host x.x.x.x
    KexAlgorithms +diffie-hellman-group1-sha1
    Ciphers aes128-cbc,3des-cbc,aes192-cbc,aes256-cbc
```
I tried doing the same configuration at the container level, but it didn't work. It seems that Oxidized is hence using its own SSH configuration.

While scrolling through the logs, here's an example of what was found related to that kind of error.
`W, [timestamp #34]  WARN -- : x.x.x.x raised Net::SSH::ConnectionTimeout (rescued RuntimeError) with msg "Net::SSH::ConnectionTimeout"`

It then loops into these kinds of logs : 
```
W, [timestamp  #34]  WARN -- : x.x.x.x raised Net::OpenTimeout (rescued Timeout::Error) with msg "timed out while opening a connection to the host"
D, [timestamp  #34] DEBUG -- : lib/oxidized/node.rb: Oxidized::Telnet failed for Device
D, [timestamp  #34] DEBUG -- : lib/oxidized/job.rb: Config fetched for Device at date UTC
W, [timestamp  #34]  WARN -- : /Device status no_connection, retry attempt 3
D, [timestamp  #34] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 0 of 1 - ended: 42 of 601
D, [timestamp  #34] DEBUG -- : lib/oxidized/worker.rb: Added /Device to the job queue
D, [timestamp  #34] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
...
D, [timestamp  #34] DEBUG -- : lib/oxidized/input/ssh.rb: Connecting to Device
D, [timestamp  #34] DEBUG -- : AUTH METHODS::["none", "publickey", "password"]
D, [timestamp  #34] DEBUG -- net.ssh.transport.session[3f7f1a081f00]: establishing connection to x.x.x.x:22
```

Any suggestions on the topic ? Do you think it is related to sha1 issues ? If so, any workarounds or solutions to allow this method on Oxidized ?

Thanks a lot & regards,

Antonin L

**Comment by robertcheramy** [comment]
You could try to map a local directory  with the .ssh folder of oxidized, here as an example in a docker-compose.yml file:
```
services:
  oxidized:
    (...)
    volumes:
      - ./oxidized-ssh:/home/oxidized/.ssh
```
Then you can edit the `config` file in oxidized-ssh.

**Comment by kajtzu** [comment]
Oxidized uses the ruby Net::SSH library instead of OpenSSH (or whatever ssh binary you have around). Probably the best, before spending time fixing the supposed problem, would be that you enable debug on the input level in the config so you can get protocol debug out of your non-working sessions.

**Comment by aleyval** [comment]
Hi ! I was not able to fix the issue by mapping a local config to the ssh folder in Oxidized : it didn't seem to fix the issue in my environment.
@kajtzu , could you elaborate on your suggestion ? How would you enable debug in the config ? Would it give more context of what is not working in the logs ?

Thanks

**Comment by kajtzu** [comment]
Please see the top of https://github.com/ytti/oxidized/blob/master/docs/Configuration.md

**Comment by ajsiersema** [comment]
Use the `config` file, put the exceptions in a group (i.e. devices with older ssh implementations.)
Configure the SSH key algo's / ciphers for the group.
E.g. :
```
groups:
  old_ssh:
    vars:
      ssh_kex: diffie-hellman-group1-sha1
      ssh_encryption: aes192-cbc
      ssh_host_key: ssh-dss
```
