### ISSUE TITLE
Docker: Official Image on Docker Hub

### ISSUE THREAD

**Issue by waja** [ytti/oxidized#297]
I stumbled upon an Image on [Docker Hub](https://hub.docker.com/r/oxidized/oxidized/) which looks like it's an official one. Said that, do you think it would be a good idea to have one?
As the build can be [automated](https://docs.docker.com/docker-hub/builds/) there should not be much work to keep it updated, after the initial setup, I guess.

**Comment by ytti** [comment]
Yeah it's official. If someone wants to automate it, I'm sure @nopedial is happy to share credentials.

**Comment by mikebryant** [comment]
I'd be happy to set up the configuration for this

**Comment by nopedial** [comment]
Happy to add you guys as collaborators, let me know your dockerhub logins.

**Comment by mikebryant** [comment]
@nopedial `mikebryant`

**Comment by nopedial** [comment]
@mikebryant done - let me know when you make progress so I can test

**Comment by mikebryant** [comment]
@nopedial When I log in to dockerhub, I don't see anything different - the oxidized organisation doesn't give me any sort of access to change things.

**Comment by nopedial** [comment]
@mikebryant you are definitely added as collaborators to the repo - you should be able to push to the repo but not much else - there is no organization and teams for oxidized, just the repo.

**Comment by nopedial** [comment]
I've converted the user to an organization and added you as owner - let me know if you are able to change things now.

**Comment by mikebryant** [comment]
@nopedial Awesome, that's working for me now.

@ytti Would I be able to get collaborator access to the ytti/oxidized github repo?
Need to add a webhook to make the automated builds work, and dockerhub doesn't seem to want to let me make an automated build for a repo I'm not a collaborator on

**Comment by ytti** [comment]
@mikebryant no problem

**Comment by mikebryant** [comment]
I believe this is now working

**Comment by waja** [comment]
Is this also working for tags or just for master?

**Comment by mikebryant** [comment]
Only master - currently the Dockerfile uses the gem version rather than the repository contents, so tagged builds wouldn't necessarily reflect the right version.

**Comment by nopedial** [comment]
@mikebryant I feel using the repository content might make more sense, what are your feelings on this?

**Comment by mikebryant** [comment]
I'd be happy with that.

My only concerns/thoughs are about oxidized-web - are we happy for the docker build of oxidized to just pull in the latest version at the time of said build?

**Comment by nopedial** [comment]
I think it would be fine, any concerns from your side @ytti ?

**Comment by ytti** [comment]
no concerns here

**Comment by ytti** [comment]
I think this is done deal. Reopen if issues.
