### ISSUE TITLE
Only one character of the password is entered

### ISSUE THREAD

**Issue by Luanpablo100** [ytti/oxidized#2976]
Hello!

### Scenario
I have a switch from the manufacturer Intelbras on my network, I'm from Brazil, and this is a national brand. I couldn't identify a switch template that would work for it, so I decided to create one myself.
I am following the Cisco SMB and FTOS switch templates as a basis.
Below you can see the .rb file I created, which I momentarily named "vlinkos.rb".

### Template
```
class VlinkOs < Oxidized::Model
  using Refinements

  comment  '! '

  expect /Press <Enter> to continue.../ do
    send "\n"
    ""
  end

  cmd :all do |cfg|
    cfg.gsub! /^% Invalid input detected at '\^' marker\.$|^\s+\^$/, ''
    cfg.gsub! /(uptime is)(\s.+)/, '\\1 <removed>' # Omit changing uptime info
    cfg.each_line.to_a[2..-2].join
  end

  cmd :secret do |cfg|
    cfg.gsub! /^(snmp-server community).*/, '\\1 <configuration removed>'
    cfg.gsub! /secret (\d+) (\S+).*/, '<secret hidden>'
    cfg.gsub! /password (\d+) (\S+).*/, '<secret hidden>'
    cfg.gsub! /^(tacacs-server key \d+) (\S+).*/, '\\1 <secret hidden>'
    cfg
  end

  cmd 'show version' do |cfg|
    comment cfg
  end

  cmd 'show running-config' do |cfg|
    cfg = cfg.each_line.to_a[3..-1].join
    cfg
  end

  cfg :telnet do
    username /^Login:/
    password /^Password:/
  end

  cfg :telnet, :ssh do
    if vars :enable
      post_login do
        send "enable\n"
        cmd vars(:enable), /Password:./
        #cmd vars(:enable), /SWITCH>./

      end
    end

    post_login 'terminal length 0'
    post_login 'terminal width 0'
    pre_logout 'exit'
    pre_logout 'exit'
  end
end
```

### Problem
The reason for creating this Issue is that I am having problems providing the enable password, right after connecting via ssh, if you see the photo I attached, you can see that only one character of the password was entered, which I have no idea of. whatever (clues about having written the password before being able to write it).

I've already tried several methods, such as placing the enable and password input commands in other places, using post_login and expect, and I even put the line that should write the password in place of the line that writes "enable", to see if it would be written incorrectly (suppose the password is "password"), like "d" or "p", but it was written normally, "password".

A detail to be mentioned is that if the "enable" command is not executed, the execution of the other "show..something" commands works normally, but in this case, of course, I cannot display any useful information.

If you would like to read some logs here, feel free to ask.

Photo of degub and relevant part of the code:
![image](https://github.com/ytti/oxidized/assets/62774555/5e58d7da-3a6f-4e9e-85cb-041002205c3d)

**Comment by jefersontrc** [comment]
Hello, I share your colleague's problem, we have a large fleet of switches from the manufacturer Intelbras, I have also tried several customized configurations and I always end up with the same problem, apparently the enable password is not entered correctly or even the command is not executed.

**Comment by renadown** [comment]
does anyone have the correct model for this Intelbras?
