### ISSUE TITLE
Ubiquiti EdgeSwitch Model

### ISSUE THREAD

**Issue by doogieconsulting** [ytti/oxidized#300]
Hi,

It would be great to have a Ubiquiti EdgeSwitch model defined within Oxidized. I have absolutely zero experience in Ruby (mainly work in SQL / R for BI) and i have several dozen of these scattered around. I have hobbled together a very basic rb file that works in a limited way but a proper definition would be great.

Thanks!

**Comment by ytti** [comment]
Doesn't it run EdgeOS? Isn't this correct: https://github.com/ytti/oxidized/blob/master/lib/oxidized/model/edgeos.rb

If not, I'm happy to walk you through how to create new model yourself or if you prefer not to do it yourself, give me access to unsupported device and I'll create model for it.

**Comment by ytti** [comment]
Do you know if the operating system has some name? EdgeSwitch sounds like name of the product, not name of the operating system?

Frankly it does not matter how limited it is, if it's sufficient to you, the user of the switch, it's good enough to me. If some other user needs more, they're welcome to contribute.

I have no problem accepting this as pull request, I'd like the operating system name figured out and the indents fixed (that might be just the paste) and it's good to go.

**Comment by doogieconsulting** [comment]
It actually is just EdgeSwitch. I also concur it is confusing to have the name of the OS represent the name of the product. It is just a custom linux package. Here is a sample of the config header
![2016-02-01_16-09-43](https://cloud.githubusercontent.com/assets/17012039/12731299/41f02eaa-c8fe-11e5-9a91-9c0f599ebd26.png)

Ubiquiti also is no help, simply listing the firmware as EdgeSwitch firmware.

My paste did not work out so well, sorry about that. i will send through a pull request to you.

**Comment by ytti** [comment]
I'm still not convinced the OS is called EdgeSwitch. Sometimes it's a huge chore to find out OS name.

**Comment by doogieconsulting** [comment]
The only other terminology i have ever found is EdgeMAX EdgeSwitch. The problem with the EdgeMax designation (my original naming) is that the edgeos routers are also EdgeMax products although UBNT calls these EdgeMAX EdgeRouter. Here are the most recent release pages for both products

EdgeMax EdgeSwitch
http://community.ubnt.com/t5/EdgeMAX-Updates-Blog/EdgeMAX-EdgeSwitch-software-release-v1-3-0/ba-p/1426736

EdgeMax EdgeRouter
[http://community.ubnt.com/t5/EdgeMAX-Updates-Blog/EdgeMAX-EdgeRouter-software-release-v1-7-0/ba-p/1287631](url) 

Here is the print out of the core system info from one of the switches
![switchoutput](https://cloud.githubusercontent.com/assets/17012039/12732125/0ad531f0-c902-11e5-977e-34a2783cfdaa.png)


i also tried hex dumping the stk firmware file but all I can get is gibberish.

Thoughts? Happy to keep looking.

**Comment by laf** [comment]
In librenms we define the os as edgeswitch as well, it was the only thing we could see to use :/

**Comment by doogieconsulting** [comment]
yea, i wrote the file for the oxidized/librenms config integration so i just fell back on what already exists. I have posted the question over in the Ubiquiti forums so hopefully we will get an answer once and for all!

[http://community.ubnt.com/t5/EdgeSwitch/EdgeRouter-vs-EdgeSwitch-software-name/m-p/1469710#U1469710](url)

**Comment by ytti** [comment]
Anything in 'strings <image>' :)

On 1 February 2016 at 23:46, doogieconsulting <notifications@github.com>
wrote:

> yea, i wrote the file for the oxidized/librenms config integration so i
> just fell back on what already exists. I have posted the question over in
> the Ubiquiti forums so hopefully we will get an answer once and for all!
>
>
> http://community.ubnt.com/t5/EdgeSwitch/EdgeRouter-vs-EdgeSwitch-software-name/m-p/1469710#U1469710
> <http://url>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ytti/oxidized/issues/300#issuecomment-178209642>.
>



-- 
  ++ytti

**Comment by doogieconsulting** [comment]
nothing. 180000 lines of nonsense as far as i can tell. It is attached if you want to give it a glance. 
[COMMAND RUN: sudo strings ES-es48.v1.3.0.4831995.s.txt](https://github.com/ytti/oxidized/files/113106/COMMAND.RUN.sudo.strings.ES-es48.v1.3.0.4831995.s.txt)

Here is a link to the source firmware file as well
[http://dl.ubnt.com/firmwares/edgemax/EdgeSwitch/v1.3.0/ES-es48.v1.3.0.4831995.stk](url)

I also used my AirConsole to log the startup sequence. Everywhere a software package is mentioned is just says EdgeSwitch. File below
[EdgeSwitch Boot Sequence.txt](https://github.com/ytti/oxidized/files/113108/EdgeSwitch.Boot.Sequence.txt)

The startup menu proved little use either
[EdgeSwitch Startup Menu.txt](https://github.com/ytti/oxidized/files/113113/EdgeSwitch.Startup.Menu.txt)

**Comment by ytti** [comment]
I'll admit defeat. Let's call it EdgeSwitch :)
