### ISSUE TITLE
Swos not working

### ISSUE THREAD

**Issue by skalg** [ytti/oxidized#3002]
Hi, I'm running oxidized in docker and i'm on the latest version.
Got it to work with routeros(mikrotik) based firmware but this is not working with the swos firmware version.
I can pull the config from shell with wget : wget http://admin:admin123@192.168.0.99/backup.swb
But in oxidized i'm getting this errors :
```
oxidized_1  | Dec  8 16:20:19 60b7b9846223 oxidized[32]: swos/00276 status fail, retry attempt 1
oxidized_1  | Dec  8 16:20:20 60b7b9846223 oxidized[32]: swos/00276 status fail, retry attempt 2
oxidized_1  | Dec  8 16:20:21 60b7b9846223 oxidized[32]: swos/00276 status fail, retry attempt 3
oxidized_1  | Dec  8 16:20:22 60b7b9846223 oxidized[32]: swos/00276 status fail, retries exhausted, giving up
```
Here's my router.db
`
00276:192.168.0.99:swos:swos
`

And my config
```
resolve_dns: false
interval: 3600
use_syslog: true
log: /home/oxidized/.config/oxidized/logs/
debug: true
threads: 30
use_max_threads: false
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 0.0.0.0:8000/oxidized
next_adds_job: false
vars: {}
groups:
  swos:
    username: admin
    password: admin123
group_map: {}
models: {}
pid: "/home/oxidized/.config/oxidized/pid"
crash:
  directory: "/home/oxidized/.config/oxidized/crashes"
  hostnames: false
stats:
  history_size: 10
input:
  default: ssh, telnet
  debug: false
  ssh:
    secure: false
  http:
    ssl_verify: false
  ftp:
    passive: truee
  utf8_encoded: true
output:
  default: git
  git:
    user: Oxidized
    email: admin@admin.com
    repo: "/home/oxidized/.config/oxidized/configs/devices.git"
source:
  default: csv
  csv:
    file: "/home/oxidized/.config/oxidized/router.db"
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      ip: 1
      model: 2
      group: 3
    gpg: false
model_map:
  swos: swos
```

If anyone can help me diagnose this issue i would be grateful ! 
_(PS, i've tried to enable debug but didn't got more output)_

**Comment by lazynooblet** [comment]
I think is related to #2685

**Comment by JavokhirN** [comment]
I have the same problem now, did you get any solution?

**Comment by skalg** [comment]
> I have the same problem now, did you get any solution?

Nop, for all the swos switches I now use this script : https://github.com/Maycx10/SwOS_backup

**Comment by skalg** [comment]
I've abandoned it and decided to go with Ansible... way less hassle.

**Comment by Cooperfibra** [comment]
Did someone find the workaround for this problem? I've the oxidized+librenms and the routeros devices works with no problem but swos have the same problem

**Comment by owirtifo** [comment]
@skalg In the input section, default should be specified as default: ssh, http:
```
input:
  default: ssh, http
  debug: true
  ssh:
    secure: false
  ftp:
    passive: true
  http:
    secure: false
  utf8_encoded: true
```
