### ISSUE TITLE
Introducing model maintainers to oxidized

### ISSUE THREAD

**Issue by robertcheramy** [ytti/oxidized#3023]
@ytti proposed to create the function of "model maintainers" as possibility to have a low entry barrier and low effort way for people to take responsibility for "their" model for "their" favorite hardware.
This issue documents the effort on the way to "model maintainers".
If you already which to become a maintainer for a specific model, you can post a commentary here, until we have defined how do to it after this issue has been closed.

**Comment by ytti** [comment]
Looks good to me, I noticed at least one spelling error (which means there likely are more, as I'm not particularly good at noticing them), so maybe run through ispell, but I have no high level notes, I think it's what Oxidized needs.
