### ISSUE TITLE
Hook event nodes_done only has sparse env set (OX_EVENT=nodes_done)

### ISSUE THREAD

**Issue by frittentheke** [ytti/oxidized#3031]
The hooks and event mechanism is awesome to extend Oxidized with your own workflows.

But when triggering hooks with the nodes_done event, there only is `OX_EVENT=nodes_done` in env.
It would be awesome to know if all nodes were fetched successfully or if there were failures.
I expected the `OX_JOB_STATUS` and `OX_JOB_TIME` to at least be available.

**Comment by frittentheke** [comment]
Can I revive this?

**Comment by robertcheramy** [comment]
@frittentheke - reopened as requested.
If you want this Issue to be resolved, give ruby a try and make Pull Request ;-)
