### ISSUE TITLE
How filter access (by password or IP list) on WEB GUI   (port 8888) ?

### ISSUE THREAD

**Issue by getienne53** [ytti/oxidized#3035]
Hello world,

Oxidized is a good software :-)

The Web GUI on port 8888 is simple and effective.

However, I am looking for a way to restrict access to the WEB / Rest API site, either with a **password** or with a **list of authorized IPs** to prevent anyone from being able to recover the switch backups.

I think i need to do some conf on the PUMA module but I don't find where to make these modifications.

Does somebody have an idea ?

Best regards

**Comment by lucasvmx** [comment]
- Set oxidized to listen only in 127.0.0.1:8888 and make nginx to redirect requests to this port. 
- Redirect host port 81 to container port 888

Do something like this on /etc/nginx/nginx.conf:

```
	server {
		listen 80;
		server_name host.com;

		location / {
			auth_basic "restrict";
			auth_basic_user_file /etc/apache2/.htpasswd; 
			proxy_pass http://127.0.0.1:81;
			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header X-Forwarded-Proto $scheme;
		}
	}
```

use apache htpasswd and save password to /etc/apache2/.htpasswd

**Comment by getienne53** [comment]
Thanks Lucas

I understand your approach which consists of using a reverse proxy like NGinx, HaProxy or Traefik on the front of Puma server.

I'm waiting to see if anyone knows how to integrate an access-list or password directly into Puma.

If it's not the case, I will follow the process you suggest.

Have a good day :-)

**Comment by getienne53** [comment]
No more information about Puma config...

So I followed Lucas's recommendation with Nginx, and it works well.

In detail, on a Debian 11 distribution, that give :

In the _.config/oxidized/config_ file:
    **rest:127.0.0.1:8888**
**apt install nginx apache2-utils**
added the following paragraph in _/etc/nginx.nginx.conf_:

 server {
                listen 80;
                server_name ct-oxid.xxx;

                location / {
                        auth_basic "restrict";
                        auth_basic_user_file /etc/apache2/.htpasswd;
                        proxy_pass http://127.0.0.1:8888;
                        proxy_set_header Host $host;
                        proxy_set_header X-Real-IP $remote_addr;
                        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                        proxy_set_header X-Forwarded-Proto $scheme;
                }
        }

**htpasswd -c /etc/apache2/.htpasswd** _user_

Bye

**Comment by Zakariaa222** [comment]
Hello everyone,

I'm having a problem with the restriction on the Oxidized web interface. Initially, I configured access to the interface on port 9090. Later, for security reasons, I'd like to implement a username and password to access the Oxidized web interface. I installed and configured nginx on the machine, but when I type the server's IP address into the address bar, it asks for a login and password, then displays a 403 Forbidden error. Here is the nginx configuration:                                                                                           server {
    listen 80;
    server_name 192.168.195.159;

    auth_basic "Oxidized Restricted Access";
    auth_basic_user_file /etc/nginx/.oxidized_htpasswd;

    location / {
        proxy_pass http://127.0.0.1:9090;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
} 

And here is the oxidized config:
---
username: username
password: password
model: junos
resolve_dns: true
interval: 3600
debug: false
run_once: false
threads: 30
use_max_threads: false
timeout: 20
timelimit: 300
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
next_adds_job: false
vars: {}
groups: {}
group_map: {}
models: {}
pid: "/root/.config/oxidized/pid"
#extensions:
  #oxidized-web:
    #load: true
    #listen: 0.0.0.0
    #port: 9090
web:
  host: 127.0.0.1
  port: 9090

Does the web extension need to be activated or not? Could you please guide me to the solution?

<img width="2560" height="312" alt="Image" src="https://github.com/user-attachments/assets/9ef752de-f936-41ab-bae2-74aee3a3e7de" />

**Comment by getienne53** [comment]
@Zakariaa222 

hello,
I'm not an Oxydized expert, but from what I understand, you need to enable Oxydized's internal REST API so that Nginx, which is the front end, can forward the access request after the password is entered.

In my **.config/oxidized/config** file, I have:

**rest: 127.0.0.1:8888**

 (8888 being my internal port; which corresponds to your 9090)

_username: user
password: nil
model: cisco
resolve_dns: true
interval: 43200
use_syslog: false
debug: false
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 127.0.0.1:8888
next_adds_job: false
vars: {}
groups:
<snip>_

**Comment by Zakariaa222** [comment]
Thank you for your reply, It works now.
