### ISSUE TITLE
backups through ipsec tunnel not working after upgrade deb11 -> deb12

### ISSUE THREAD

**Issue by tonoitp** [ytti/oxidized#3042]
My oxidized has two gateways:
A mikrotik CHR and a Cisco asa. Each of those gateways has IPSEC tunnels to other routers & networks.
Everything works fine on my debian 11 platform.

On a fresh debian 12 install (I copied the config and router.db files over) 
- Everything behind the ASA gateway works just like under Debian 11
- But oxidized can not login to any device behind the mikrotik gateway. Not the remote router, nor the remote switches. Where it worked under debian 11.

**Comment by robertcheramy** [comment]
This looks unrelated to oxidized and can't be solved with the description you provide.

**Comment by tonoitp** [comment]
Thought so too at first, but without touching the router configs,
a fresh oxidized on deb11 works while and deb12 doesn't. (same config & router.db files)
I'll gather logs

**Comment by netdiver** [comment]
Are you able to manually ssh or telnet into those unreachable devices?

**Comment by tonoitp** [comment]
Yes, if I add the option "-o MACs=hmac-sha2-256"
Added it to ssh config to be default, and tried it in the oxidized config file. No change in oxidized behavior

**Comment by netdiver** [comment]
I believe that ssh operations on oxidized are not managed by ssh command in OS, but by a ruby gem named Net:SSH
https://github.com/net-ssh/net-ssh
So I don't think that any setting to ssh in OS can lead to a correct behaviour of Oxidized.
