### ISSUE TITLE
oxidized-web error :: Puma caught this error: wrong number of arguments (given 3, expected 1..2) (ArgumentError)

### ISSUE THREAD

**Issue by papatango71** [ytti/oxidized#3052]
I have been struggling to get past this error with oxidized-web.  The errors below are what show up in the browser when trying to access the webUI for oxidized.

Puma caught this error: wrong number of arguments (given 3, expected 1..2) (ArgumentError)
/home/oxidized/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rack-1.6.13/lib/rack/urlmap.rb:35:in `initialize'
/home/oxidized/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rack-1.6.13/lib/rack/urlmap.rb:35:in `new'
/home/oxidized/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rack-1.6.13/lib/rack/urlmap.rb:35:in `block in remap'
/home/oxidized/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rack-1.6.13/lib/rack/urlmap.rb:23:in `each'
/home/oxidized/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rack-1.6.13/lib/rack/urlmap.rb:23:in `map'
/home/oxidized/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rack-1.6.13/lib/rack/urlmap.rb:23:in `remap'
/home/oxidized/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rack-1.6.13/lib/rack/urlmap.rb:19:in `initialize'
/home/oxidized/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rack-1.6.13/lib/rack/builder.rb:161:in `new'
/home/oxidized/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rack-1.6.13/lib/rack/builder.rb:161:in `generate_map'
/home/oxidized/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rack-1.6.13/lib/rack/builder.rb:145:in `to_app'
/home/oxidized/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/rack-1.6.13/lib/rack/builder.rb:153:in `call'
/home/oxidized/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/puma-3.11.4/lib/puma/configuration.rb:225:in `call'
/home/oxidized/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/puma-3.11.4/lib/puma/server.rb:632:in `handle_request'
/home/oxidized/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/puma-3.11.4/lib/puma/server.rb:446:in `process_client'
/home/oxidized/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/puma-3.11.4/lib/puma/server.rb:306:in `block in run'
/home/oxidized/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/puma-3.11.4/lib/puma/thread_pool.rb:120:in `block in spawn_thread'

I have tried everything that has come up using Google but no joy.  I am not a Ruby guru so any help to get past this issue would be greatly appreciated.

puma (6.4.2, 3.11.4)
oxidized (0.29.1)
oxidized-web (0.13.1)

**Comment by CTV-2023** [comment]
Did you manage to find a workaround ? Same issue for me no a new install on Debian 12. 
Using rvm / ruby 3.3.0
puma (6.4.2, 3.11.4)
oxidized (0.29.1)
oxidized-web (0.13.1)

I saw this issue https://github.com/getsentry/sentry-ruby/issues/2067, so I tried to uninstall puma 3.11.4 and only keep 6.4.2 but installing oxidized-web reinstalls puma 3.11.4 (and doesn't seem to start if I ignore dependencies on install)

**Comment by patrick-vaporio** [comment]
I have not found a workaround for this issue.  I am still working through it, hoping to find a solution.

**Comment by CTV-2023** [comment]
> I have not found a workaround for this issue. I am still working through it, hoping to find a solution.
I think I made it work with ruby 3.1.0

**Comment by patrick-vaporio** [comment]
I was able to get oxidized-web working again with ruby 3.2.3.  There is something in ruby 3.3.0 that breaks oxidized-web.
