### ISSUE TITLE
Mikrotik SwOS unathorized file...

### ISSUE THREAD

**Issue by makanys** [ytti/oxidized#3054]
Hello,

Try to work with mikrotik swos switches, but always get unathorized contains html file only, but with wget it's working. The router.db is correct in the debug log:
D, [2024-02-07T14:02:34.161787 #17444] DEBUG -- : lib/oxidized/job.rb: Starting fetching process for MikrotikSW1 at 2024-02-07 14:02:34 UTC
D, [2024-02-07T14:02:34.162803 #17444] DEBUG -- : lib/oxidized/input/cli.rb: Running post_login commands at MikrotikSW1
D, [2024-02-07T14:02:34.163187 #17444] DEBUG -- : lib/oxidized/model/model.rb Collecting commands' outputs
D, [2024-02-07T14:02:34.163435 #17444] DEBUG -- : lib/oxidized/model/model.rb Executing /backup.swb
D, [2024-02-07T14:02:34.241180 #17444] DEBUG -- : lib/oxidized/node.rb: Oxidized::HTTP ran for MikrotikSW1 successfully
D, [2024-02-07T14:02:34.241662 #17444] DEBUG -- : lib/oxidized/job.rb: Config fetched for MikrotikSW1 at 2024-02-07 14:02:34 UTC

Thank you for help!

**Comment by derhelge** [comment]
Hi @makanys 

you could give it a try with the master branch. It should be fixed since #3074

**Comment by makanys** [comment]
Hi, I found. Need install gem install net-http-digest_auth and it's work
