### ISSUE TITLE
Debian 12 Gem install fails

### ISSUE THREAD

**Issue by Acadian69** [ytti/oxidized#3082]
Attempting to install on Debian 12 Bookworm.

The first part of the gem is fine, but installing the 2nd part I get extconf failed exit code 1

gem install oxidized-script oxidized-web

If I look at 

/var/lib/gems/3.1.0/extensions/x86_64-linux/charlock_xxxx-0.7.7/mkmf.log

I see

/usr/bin/ld: cannot find -licui18n: No such file or directory
collect2: error: ld returned 1 exit status
checked program was:

I tried to google /usr/bin/ld: cannot find -licui18n

Thanks

**Comment by elmobp** [comment]
```
sudo apt install libicu-dev
```

**Comment by Acadian69** [comment]
Thanks elmobp.

I must have not copied the whole gem install line. 

Worked this time.

**Comment by CTV-2023** [comment]
Hi, did you manage to make the API work ? I'm hitting this issue on Debian 12, I don't know if it's specific to my ruby version or using because I'm using rvm...
https://github.com/ytti/oxidized/issues/3052
