### ISSUE TITLE
[Question] Can 2 Oxidized instances push to same github repo?

### ISSUE THREAD

**Issue by baylanger** [ytti/oxidized#3085]
Hello,

Is it possible to run 2 oxidized instances, on different servers/locations, and use the same backend git repo?

I just tried that and the last push from server B deleted the config files from server A. I bet next time server A uploads a config file, config files from server B will get deleted. I believe it's how git is interface within the app that prevents this to work at all.

Is there a way to make this happen? If not, I'll either create another git repo or open the firewall to fetch from the same instance. Obviously.. I was trying to avoid have 2 repos or open the firewall.

Thanx!

**Comment by robertcheramy** [comment]
The [githubrepo.rb](https://github.com/ytti/oxidized/blob/master/lib/oxidized/hook/githubrepo.rb) hook just pushes the local repository to remote. There is a fetch & merge in the code, but as soon as there are conflicts, it will [give up](https://github.com/ytti/oxidized/blob/1694ff3fa64145b514b5f93d2e0824f12175204c/lib/oxidized/hook/githubrepo.rb#L47).

So - you should use two repositories.

**Comment by Aprazor** [comment]
have you guys found any solution to this or this doesn't work at all?

**Comment by robertcheramy** [comment]
> So - you should use two repositories.

If not clear enough: **DO NOT** use two oxidized instances on one git repository.
