### ISSUE TITLE
when 'use_max_threads' is true, and 'threads' is equal or higher than the nodes to query, oxidized enters an endless loop

### ISSUE THREAD

**Issue by 0x00af** [ytti/oxidized#3095]
Running oxidized 0.29.1

I'm testing ways to get all configs of network devices in a kinda snapshot-y way (just like #457 or #2527).

When I run oxidized against a certain number of devices, oxidized enters an endless loop without doing anything useful anymore when `threads` is equal or higher than the number of devices to query, and `use_max_threads` is true. If debug is enabled, it fills the storage in a matter of minutes.

For my test set I have 16 devices in a mysql2 source, all are of the same type.

When I do this:
```
threads: 15
use_max_threads: true
```
everything is fine.

But as soon as I go to `threads: 16` or above, the debug log is filled with this:

```
D, [2024-03-05T01:12:00.723297 #28736] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 16 of 17 - ended: 0 of 16
D, [2024-03-05T01:12:00.723304 #28736] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 16 of 17 - ended: 0 of 16
D, [2024-03-05T01:12:00.723310 #28736] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 16 of 17 - ended: 0 of 16
D, [2024-03-05T01:12:00.723317 #28736] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 16 of 17 - ended: 0 of 16
D, [2024-03-05T01:12:00.723324 #28736] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 16 of 17 - ended: 0 of 16
D, [2024-03-05T01:12:00.723330 #28736] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 16 of 17 - ended: 0 of 16
D, [2024-03-05T01:12:00.723337 #28736] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 16 of 17 - ended: 0 of 16
D, [2024-03-05T01:12:00.723343 #28736] DEBUG -- : lib/oxidized/worker.rb: Jobs running: 16 of 17 - ended: 0 of 16
```

I assume this to be some kind of array index error in a scheduler.

**Comment by ytti** [comment]
Does #3060 solve this?

**Comment by 0x00af** [comment]
I installed oxidized using `gem install oxidized`, which would probably be the 0.29.1 from last April. The `jobs.rb` did not have the mentioned line to begin with.

I installed it from git now, and everything works, yes.
Thank you.
