### ISSUE TITLE
Hot to catch "node not found" via API?

### ISSUE THREAD

**Issue by michieltimmers** [ytti/oxidized#3101]
Hello,

I have a cronjob/script that fetches http://localhost:8888/nodes.json and sends me and email if status != success 

But I have noticed that some of my devices have never had a proper backup and then the oxidized webgui shows this with "node not found" when I click on the configuration icon.

But these nodes are not represented in the nodes.json file.

Is there a way to also catch these problem via the API, or any other way?

**Comment by robertcheramy** [comment]
You should maybe check/parse the logs/output of oxidized.

**Comment by robertcheramy** [comment]
Closed as no reaction from @michieltimmers
