### ISSUE TITLE
Oxidized web console doesn't show "Last Status" 

### ISSUE THREAD

**Issue by margeu** [ytti/oxidized#3113]
From the console I see the "Last Status" field not colored red or green depending on the status.

**Comment by margeu** [comment]
![oxidized](https://github.com/ytti/oxidized/assets/32653608/a2949de0-7003-4358-b27d-c008a1298d1b)

In the browser see problem in oxidized.css

**Comment by robertcheramy** [comment]
This issue is not related to oxidized. Please check with your "console" provider.
