### ISSUE TITLE
SSH proxy failed backup until disconnect/timeout

### ISSUE THREAD

**Issue by romainsi** [ytti/oxidized#3114]
Hello,

First thanks for you job.
I've a problem with backing up a Mikrotik router via ssh proxy, ok with direct ssh access.

I use docker with last version of oxidized (0.29.1-207-gea40b51), I generated an rsa key to the oxidized user, and added the mapping for the ssh proxy which works fine (I see ssh session on first equipement for proxy and on the final router) but the connection (forward then ssh on the router) never ends (so no backup even when I change the router configuration).
But when I force the closure of this session (the proxy part or the ssh client part), or when I reboot the router, the backup is carried out correctly (with data).

On the web interface of the routerOS, when I close client ssh, I see the backup performed correctly, but average run time is necessarily very long, since it depends on the time I took to close the connection (1195.83s for example in my last test).

From what I understand, the session doesn't close properly at the end of the information retrieval command, so the backup never takes place.

Thanks for your help.

**Comment by robertcheramy** [comment]
As I neither use Mikrotik nor ssh proxy, it's quite difficult form me to help.

From your description, if the ssh session never ends, the `quit` is not enought to close the session:
https://github.com/ytti/oxidized/blob/c79826af0aca087f5798432224922b648524b137/lib/oxidized/model/routeros.rb#L61

How do you logout when using a proxy? Do you have to enter something else as just `quit` ?

**Comment by romainsi** [comment]
Hi,

The pre_logout command seems to be good for classic and proxy connections.
when I log on to the docker and I testing this :
`docker exec -it <oxidized-container-name> bash`
`su oxidized`
`ssh -J <IP-routerOS-forProxy> oxidized@<IP-Router-forBackup>`
`[oxidized@<IP-Router-forBackup>] > quit`

a simple 'quit' disconnects client and proxy and sends me back to the oxidized bash terminal.

**Comment by romainsi** [comment]
To make this work temporarily, I've set up a script that disconnects my SSH user 'oxidized' on the end device every hour.
I deduce that there's a problem with the routeros template ...
