### ISSUE TITLE
Sonicos Model: '-' in name of device is not supported

### ISSUE THREAD

**Issue by marmack95** [ytti/oxidized#3128]
Hello,
the sonicos model not works if device name use a '-'.

Sonicos model use as prompt:
`prompt /^\w+@\w+[>]\(?.+\)?\s?/`

\w correspond to [a-zA-Z0-9_].
I extend sonicos model with this one and it works now:
`prompt /^\w+@[a-zA-Z0-9-]+[>]\(?.+\)?\s?/`

NB: Oxidized 0.30.1 - Docker version

**Comment by robertcheramy** [comment]
Please make a PR for this.
