### ISSUE TITLE
Contribution: Sonicwall SonicOS 4.x model

### ISSUE THREAD

**Issue by marmack95** [ytti/oxidized#3135]
Hello,

Old Sonicwall are not supported by Oxidized.
SonicOS 4.x don't offer possibility to export configuration from cli.

This basic model (not hide password & does not exclude dynamic informations as uptime), let you grab some information about it.

NB: don't forget to set ssh_kex

Tested on SonicWall Pro 4100 - SonicOS 4.2.
I use Oxidized 0.30.1-14-g2bfd3f2 (docker version).

[sonicos4.txt](https://github.com/ytti/oxidized/files/15077750/sonicos4.txt)

**Comment by marmack95** [comment]
This version remove prompt (xxx>) from file.
[sonicos4.txt](https://github.com/ytti/oxidized/files/15096563/sonicos4.txt)

**Comment by robertcheramy** [comment]
If you think your models can be integrated in Oxidized, please make a PR: https://github.com/ytti/oxidized/blob/master/CONTRIBUTING.md#how-to-contribute-content
Also consider becoming a model maintainer for them:
https://github.com/ytti/oxidized/blob/master/CONTRIBUTING.md#model-maintainers

If you just want your contribution to be posted here for users to see them (no integration in Oxidized), I would close the issue.

**Comment by marmack95** [comment]
I'm sorry I'm not familiar with Git/Github/Ruby: create models for oxidized was my first experience with ruby.
And as I will change of job this year, I will not be able to maintain all my contributions.

You can close my issues (i publish it for community), or create a folder "model-unmaintain-create-by-community".
