### ISSUE TITLE
ERROR -- : Hook push_to_remote SshError: remote rejected authentication: Failed getting response

### ISSUE THREAD

**Issue by Skull0ne** [ytti/oxidized#3148]
Hi

I tried to reconfigure the git hook from user/password to ssh key but I can't find the solution.

The config : 
```
hooks:
  push_to_remote:
    type: githubrepo
    events: [post_store]
    remote_repo: "ssh://git@GIT_URL/infrastructure/oxidized.git"
    privatekey: "/home/oxidized/.ssh/id_rsa"
    publickey: "/home/oxidized/.ssh/id_rsa.pub"
```

For the remote_repo I also tried "git@GIT_URL:infrastructure/oxidized.git".

The id_rsa key starts with "-----BEGIN RSA PRIVATE KEY-----" and there is no line return at the end. 

.ssh folder and key files are owned by the user.

Known_hosts contains the info for my git repo.

I'm able to git clone the repo manually and commit into it : 
```
oxidized@898fd87005f4:~$ git clone ssh://git@GIT_URL/infrastructure/oxidized.git
Cloning into 'oxidized'...
remote: Enumerating objects: 6885, done.
remote: Counting objects: 100% (6885/6885), done.
remote: Compressing objects: 100% (2483/2483), done.
remote: Total 6885 (delta 4401), reused 6878 (delta 4399), pack-reused 0
Receiving objects: 100% (6885/6885), 7.49 MiB | 40.16 MiB/s, done.
Resolving deltas: 100% (4401/4401), done.

[...]

oxidized@898fd87005f4:~/oxidized$ git push
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 8 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 316 bytes | 316.00 KiB/s, done.
Total 3 (delta 2), reused 0 (delta 0), pack-reused 0
To ssh://GIT_URL/infrastructure/oxidized.git
   61e0ee5..7a7ecd4  main -> main
```

I've added "IdentitiesOnly yes" to my .ssh/config for my gitlab host, without that I couldn't clone the repo.

LIBSSH2 version : 
```
ii  libssh2-1:amd64              1.10.0-3                                amd64        SSH2 client-side library
```

I tried to enable the debug mode with it didn't give much.

Error : 
```
I, [2024-04-30T21:07:04.171384 #32]  INFO -- : GithubRepo: Pushing local repository(/home/oxidized/.config/oxidized/oxidized.git/)...
I, [2024-04-30T21:07:04.171438 #32]  INFO -- : GithubRepo: to remote: ssh://git@GIT_URL/infrastructure/oxidized.git
E, [2024-04-30T21:07:04.338160 #32] ERROR -- : Hook push_to_remote (#<GithubRepo:0x000055d2585ec358>) failed (#<Rugged::SshError: remote rejected authentication: Failed getting response>) for event :post_store
```

Thanks

**Comment by nota-user** [comment]
You added ssh key in container for user "oxidized"?

**Comment by YellowJacket51** [comment]
I am having this issue too. Were you able to fix your issue?

Oxidized version: 0.30.1
Gitlab version: 17.0.1

**Comment by Skull0ne** [comment]
no still ongoing

**Comment by robertcheramy** [comment]
Have you tested https://github.com/ytti/oxidized/blob/master/docs/Troubleshooting.md#oxidized-does-not-push-to-a-remote-git-repository-hook-githubrepo ?

**Comment by Skull0ne** [comment]
@robertcheramy Yes, I've done it for both root & oxidized user within the pod

**Comment by robertcheramy** [comment]
Please have a look at #1517 . If it solves your Problem, please report it here, I would try to document how to solve the issue in docs/Troubleshooting.md .

**Comment by Skull0ne** [comment]
I restarted from scratch (setup wasn't mine initially) and it's working (git clone repo, docker build, new repositories, setting the right owner/perms on the folders). 
I faced another issue but it was related to GIT because my key was configured twice in /var/opt/gitlab/.ssh/authorized_keys, removed the old one and pod was able to pull the repo.
