### ISSUE TITLE
Prompt for username and password on Cisco SMB

### ISSUE THREAD

**Issue by SaaldjorMike** [ytti/oxidized#315]
Problem is that we now removed the part that matches the prompt for username and password, which forces me to change it back locally for now.

See:
https://github.com/ytti/oxidized/commit/c39e8ebb2e19d718d039dc0c659d76b4469a750f

**Comment by ytti** [comment]
This is related to #262 

On possible solution

```
cfg :ssh do
  if vars(:ciscosmb_cli_auth)
      username /^User Name:/
      password /^\r?Password:$/
  end
end
````
Then in config

```
source:
  cvs:
   vars_map:
      ciscosmb_cli_auth: 5
```

To discriminate which box gets which style of auth. 



More automatic would be in ```ssh.rb``` to detect if there is password prompt, but I'd like to avoid that, if it's acceptable to communicate it via config.

**Comment by ytti** [comment]
I wonder what is the best solution to this.

 * vars, like proposed
 * unique model (maybe base model, and versioned models which require the base and repoen?

**Comment by roedie** [comment]
I just ran into this issue on an SG500 stack.

The vars option is not too bad. But, the amount of vars in the router.db is getting annoyingly long now in my config ;-)

So, if it is somehow possible to discriminate the box by some automatic way, that would get my vote.

**Comment by ytti** [comment]
Perhaps net/ssh library can be queried what auth was used, if auth was 'none', then we could assume login/user is configured. And it would make this dynamic.

**Comment by roedie** [comment]
Aw crap, I just noticed in #262 that it's possible to reconfigure the switch to do ssh the 'right' way. Since I'm on a recent firmware version I did that. My problem is gone now.

So, to be honest, I would then go for the vars method, since you have the option of letting the device do the right thing.

**Comment by ytti** [comment]
We now support detecting if SSH wants terminal auth or not.
