### ISSUE TITLE
passwords with special characters (dollar sign and space)

### ISSUE THREAD

**Issue by JoeyChen-NTUT** [ytti/oxidized#3150]
I just read follow issue

https://github.com/ytti/oxidized/issues/964

but in my case my password such like 
`$P@$$w0rd 123`

I just rewrite config to 
`\$P@\$\$w0rd\ 123`

but still got authentication failed

how to correct it thanks

**Comment by marmack95** [comment]
I don't have problems with '$'.
Try to espace only space.

As space is a separator, try to replace space with encoded character '\x00'.

**Comment by JoeyChen-NTUT** [comment]
I just remove space in my password but still not work with dollar sign

**Comment by marmack95** [comment]
Enable debug and check it.
It could be a problem of prompt, for example (https://github.com/ytti/oxidized/issues/3128)

**Comment by robertcheramy** [comment]
Enclose your password within single quotes:
```
---
username: oxidized
password: '$P@$$w0rd 123'
```
