### ISSUE TITLE
Contribution: miscellaneous models

### ISSUE THREAD

**Issue by marmack95** [ytti/oxidized#3156]
Hello,

to complete the models i already publish here: [SonicOS 4.x](https://github.com/ytti/oxidized/issues/3135), [Synology Nas](https://github.com/ytti/oxidized/issues/3133), [Vmware ESXi](https://github.com/ytti/oxidized/issues/3137).

You will find here some others models that could be usefull to community:
 - eaton: Eaton with Gigabit Network Card 2.x (UPS Device / ssh)
 - eatonold: Eaton with ConnectUPS Web/SNMP Card V4.38 (UPS Device / telnet)
 - dlinkcam: D'link IP Cam DCS-2230 (IP Cam / http)
 - dellme4: Dell EMC PowerVault ME4024 (SAN / ssh) -> it's have stability problems, even with lastest firmware.. i'm still trying to find a solution.

3 samples of extended models:
 - HP Comware switch (comware model)
 - Huawei Switch (vrp model)
 - Sonicwall firewall (sonicos model)

[dellme4.txt (ssh)](https://github.com/ytti/oxidized/files/15223505/dellme4.txt)
[dlinkcam.txt](https://github.com/ytti/oxidized/files/15223507/dlinkcam.txt)
[eaton.txt](https://github.com/ytti/oxidized/files/15223508/eaton.txt)
[eatonold.txt](https://github.com/ytti/oxidized/files/15223511/eatonold.txt)
[extended_hp.txt](https://github.com/ytti/oxidized/files/15223512/extended_hp.txt)
[extended_huawei.txt](https://github.com/ytti/oxidized/files/15223513/extended_huawei.txt)
[extended_sonicos.txt](https://github.com/ytti/oxidized/files/15223514/extended_sonicos.txt)

**Comment by marmack95** [comment]
Dell advice to script using HTTP API for Dell EMC PowerVault ME4024.
Dell give an example in python [here](https://www.dell.com/support/manuals/fr-fr/powervault-me4024/me4_series_cli_pub/using-a-script-to-access-the-cli?guid=guid-9ae5ccd6-a207-42df-b2f3-1e02a487a354&lang=en-us): it's a little bit complicated for me.

**Comment by marmack95** [comment]
I was able to wrote a model for Dell EMC PowerVault ME4024 which use the HTTP API.

I'm inspired from:
 - the panos_api.rb model
 - a python-to-ruby online converter to convert Dell sample code documentation.

I choose to use JSON (with indentation) and not XML.
I don't notice stability problem.

[dellme4.txt (https api)](https://github.com/ytti/oxidized/files/15296352/dellme4.txt)

**Comment by robertcheramy** [comment]
If you think your models can be integrated in Oxidized, please make a PR: https://github.com/ytti/oxidized/blob/master/CONTRIBUTING.md#how-to-contribute-content
Also consider becoming a model maintainer for them:
https://github.com/ytti/oxidized/blob/master/CONTRIBUTING.md#model-maintainers

If you just want your contribution to be posted here for users to see them (no integration in Oxidized), I would close the issue.

**Comment by marmack95** [comment]
As explain in other issue, I'm sorry I'm not familiar with Git/Github/Ruby: create models for oxidized was my first experience with ruby.
And as I will change of job this year, I will not be able to maintain all my contributions.

If you let this issue open, i will maybe add 2 others models (i'm looking for a way to backup Dell Drac and Canon Printer with Oxidized). And i would like to wrote a FAQ.

**Comment by marmack95** [comment]
I was not able to create models for Canon Printer ...

I'm working now on Dell iDrac (7/8/9) model : i'm using RESTful API.
https://dl.dell.com/manuals/common/dell-emc-restful-server-config-idrac-api.pdf
Dell give sample of code in python (page 10 and next.)
But I don't find how to use payload on http request with oxidized.

**Comment by marmack95** [comment]
I succeed to wrote a Dell iDrac 7/8/9 model :-)
It's use HTTPS Rest Api: you need to enable Redfish on iDrac if you disable it.

Tested on:
 - Dell iDRAC9 / FW 3.00.00.00 / Suggested timeout: 30s
 - Dell iDRAC7/8 / FW 2.40.40.40 / Suggested timeout: 120s

This model don't only export iDrac configuration but also : Bios, LifeCycle, Raid, Nic.
Passwords are not included: you can modified it if you need.
Export format is set on XML.

[dellidrac.txt](https://github.com/user-attachments/files/15787155/dellidrac.txt)

**Comment by marmack95** [comment]
> I was not able to create models for Canon Printer/Fiery ...

I discovered that Oxidized use/include Mechanize library: which permit to simulate HTML4 Web navigator.
But the Canon printer login page use a javascript button to crypt password and next login...
Mechanize not support Javascript.
Someone have a advice ?

**Comment by marmack95** [comment]
> I discovered that Oxidized use/include Mechanize library: which permit to simulate HTML4 Web navigator. But the Canon printer login page use a javascript button to crypt password and next login... Mechanize not support Javascript. Someone have a advice ?

I succeed to wrote a model for Canon printer iR-ADV in 2 parts:
- part 1: init export (could take 2-5 min).
- part 2: download file.
I execute part1 on all my printers, and next i execute part2.

I was forced to use Watir: there is a lot of javascript on Canon web interface.
Watir is not integrated to oxidized but call by it: so error are not well managed.

But it's works well.
Each part take 20-30s: it's more efficient than wait 2-5 min export per device.

I use oxidized docker version, so i install:
- watir:	'gem install watir webdrivers watir-webdriver selenium-webdriver'
- firefox:	install firefox-esr from debian-src (best choice) or firefox-current from mozilla depot
- geckodriver:
1. apt install wget
2. wget https://github.com/mozilla/geckodriver/releases/download/v0.34.0/geckodriver-v0.34.0-linux64.tar.gz
3. tar -xvf geckodriver
4. mv geckodriver /usr/bin

Tested on 25 devices:
- Canon iRADV C257 / FW 35.44
- Canon iRADV C5550 / FW 75.44
- Canon iRADV C5735 / FW 35.44
- Canon iRADV C5840 / FW 25.49

**Comment by marmack95** [comment]
My canonimp models were creating performance issues because they wouldn't close the browser. They close it now if the device cannot be reached and at the end of processing.
Files are now removed at the end from the download folder.
Some comments have been added.

I also create model for Fiery P2 (should work with some others linux base models).
As interface used a lot of javascript, it used watir (+ firefox + geckodriver) and zlib (export use 2 seperates files).
It take beteween 30s to 1min.
It was tested on Canon iR-ADV C5700 with Fiery P2 PSv1.1 (web interface v3.2.94).

[canonimp_p1.txt](https://github.com/user-attachments/files/16015863/canonimp_p1.txt)
[canonimp_p2.txt](https://github.com/user-attachments/files/16015865/canonimp_p2.txt)
[fiery.txt](https://github.com/user-attachments/files/16015866/fiery.txt)

**Comment by marmack95** [comment]
Based on Linux model, i wrote a specific model for Quest QoreStor 7.x (installed on CentOS 8.x).
[questqorestor.txt](https://github.com/user-attachments/files/16032152/questqorestor.txt)

**Comment by robertcheramy** [comment]
Closing the issue @marmack95 ment to share his developments without submitting a PR.
