### ISSUE TITLE
Web API /next returns status 500 if node is waiting to poll

### ISSUE THREAD

**Issue by ktims** [ytti/oxidized#3163]
When calling `/next/<node>` from an external service to notify Oxidized of config changes, the API sometimes responds with 500 Internal Server Error, particularly at startup.

Apparently this is due to the underlying `next` implementation only searching the list of nodes that aren't currently 'running' a poll job. If the node is currently 'running', then it will not be found, and this will _raise_ which is not caught, not return _nil/false_ which would be.

https://github.com/ytti/oxidized/blob/9594ae132dc16df41d96a487df1d7bf79bb79679/lib/oxidized/nodes.rb#L72

**Comment by Haeki** [comment]
I noticed the same problem as well.
I implemented a [fix](https://github.com/ytti/oxidized/pull/3250) that works in our oxidized installation

**Comment by laf** [comment]
Flagging to close this issue as it's been fixed in #3250
