### ISSUE TITLE
Git error due to unproper shutdown

### ISSUE THREAD

**Issue by bram-pangestu** [ytti/oxidized#3165]
Hi all,

My oxidized stopped working due to unproper machine shutdown; thus give error on Git.
Kindly need your advice to fix it.

Below is the result when run "git status" command.

Regards,
Bram

````
On branch master
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted
	deleted:    information redacted

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	hooks/
	info/
	objects/
	refs/

no changes added to commit (use "git add" and/or "git commit -a")
```
`

**Comment by robertcheramy** [comment]
One easy solution would be do delete your git repository and let oxidized repopulate it. You will loose your history by doing this.

More sophisticated solutions need a good understanding of git and its data structure, and it is quite impossible to resolve this from remote. You should read and understand https://git-scm.com/book/en/v2/Git-Internals-Plumbing-and-Porcelain (and probably the whole git book). This should help you to understand where the problem is.

A few random ideas (without warranty that it should work or even break the repository).
- First, make a backup of your git repository to prevent data loss
- run `git gc` (Garbage collection)
- run `git reset --hard` (This will throw away uncomited changes)
- You could rebuild the index (no Idea if it helps):
```
rm index
git ls-tree -r HEAD | git update-index --index-info
```

**Comment by bram-pangestu** [comment]
> One easy solution would be do delete your git repository and let oxidized repopulate it. You will loose your history by doing this.
> 
> More sophisticated solutions need a good understanding of git and its data structure, and it is quite impossible to resolve this from remote. You should read and understand https://git-scm.com/book/en/v2/Git-Internals-Plumbing-and-Porcelain (and probably the whole git book). This should help you to understand where the problem is.
> 
> A few random ideas (without warranty that it should work or even break the repository).
> 
> * First, make a backup of your git repository to prevent data loss
> * run `git gc` (Garbage collection)
> * run `git reset --hard` (This will throw away uncomited changes)
> * You could rebuild the index (no Idea if it helps):
> 
> ```
> rm index
> git ls-tree -r HEAD | git update-index --index-info
> ```

Hi Robert,

Thank you for the explanation and suggestion.
I have gave your suggestion a shot; sadly it is no success.
So i followed your first sentence, i deleted my git repository and let oxidized repopulated it.

Regards,
Bram
