### ISSUE TITLE
change default ssh port

### ISSUE THREAD

**Issue by Dazza0311** [ytti/oxidized#3173]
I am trying to change the default SSH port, all our devices use a generic custom port.

I however am not using groups, so I need to change the port used by Oxidized.

**Comment by yoakim** [comment]
Hello again,

Try this under your vars key in config:

```
vars: 
  ssh_port: 1234
```

**Comment by Dazza0311** [comment]
haha thanks again, it did the trick

**Comment by yoakim** [comment]
:D glad to help
