### ISSUE TITLE
RouterOS 7.15 - error in logs

### ISSUE THREAD

**Issue by hats0id** [ytti/oxidized#3180]
Hello dear. Thak you very much.

After updating from 7.14.3 to 7.15 an error appeared in logs:
executing script from sshd failed, please check it manually

But configuration was backed up successfully, at least all changes.

Before update in logs were only two records:

user xxx logged in from 172.16.254.243 via ssh
user xxx logged out from 172.16.254.243 via ssh

**Comment by hats0id** [comment]
Little update - i have noticed that this error appears only on CHR VM. On hardware Mikrotik devices i do not see this error. Any ideas?

**Comment by systeembeheerder** [comment]
Can confirm

```
oxidized@app01:~$ ssh chr.domain.net '/system routerboard print'
bad command name routerboard (line 1 column 9)
```

For 15.x this adds an error to the Mikrotik log ``executing script from sshd failed, please check it manually``. For earlier versions, it's also an invalid command but it won't add an error to the mikrotik log.

The best solution would be to skip ``/system routerboard print`` for CHR.
