### ISSUE TITLE
Rocky Linux PromptUndetect

### ISSUE THREAD

**Issue by vkratsberg** [ytti/oxidized#3186]
Hello,

We use oxidized to monitor changes of configuration files on our servers and everything is working great with CentOS 7.  We recently migrated a few servers to Rocky Linux and can no longer use oxidized because of PromptUndetect.  See error message below.

===============================================

W, [2024-06-05T01:55:16.609148 #135]  WARN -- : prism201.eqx.ams.prod raised Oxidized::PromptUndetect with msg "Last login: Wed Jun  5 01:54:35 2024 from 10.195.225.39

+++++++++++++++++: System Data :+++++++++++++++++++
+ Hostname = prism201.eqx.ams.prod
+ Address = ['10.240.10.121', '10.240.9.121', '10.240.10.122', '172.17.0.1', '10.240.8.121']
+ Kernel = 5.14.0-362.18.1.el9_3.0.1.x86_64
+ Uptime =  01:54:57 up 20 days,  6:35, 18 users,  load average: 1.20, 1.69, 1.85
+ System Type = PowerEdge R450
+ Ansible Created =
+ Total Memory = 130767064 kB
+ Free Memory  = 113487436 kB
+++++++++++++++++++++++++++++++++++++++++++++++++++

[svc-net-services@prism201 ~]$  not matching configured prompt (?-mix:^(\[.+@.+\]*))"

====================================================

The prompt on Rocky Linux is identical to centos and regex test matches the prompt successfully:

<img width="1001" alt="Screenshot 2024-06-04 at 22 01 37" src="https://github.com/ytti/oxidized/assets/11032416/dd6c4ca3-238e-4244-bf23-99cf4f103395">

I even tried disabling MOTD and hushing "Last login: Wed Jun  5 01:54:35 2024 from 10.195.225.39" message and oxidized still returns:

W, [2024-06-05T01:43:32.858176 #135]  WARN -- : prism201.eqx.ams.prod raised Oxidized::PromptUndetect with msg "[svc-net-services@prism201 ~]$  not matching configured prompt (?-mix:^(\[.+@.+\]*))"

Did anyone experience the same issue and was able to resolve it ? 
Thank you

**Comment by ytti** [comment]
> The prompt on Rocky Linux is identical to centos and regex test matches the prompt successfully:

Is it possible you are over confident in your test methodology? How did you deliver the output to the program? Are you confident the mechnism you used to deliver the output, keeps the output unmodified? Is it possible the output has ANSI codes which you didn't deliver to your test case?

**Comment by ytti** [comment]
Also is you regexp intentional? Do you really mean to say '0 or more closing brackets' is the end of the regexp? Maybe you actually wanted something like: ```^\[\S+@\S+\s \S+\]\$\S*$``` or something like that?

**Comment by vkratsberg** [comment]
Hi,

Thank you for your response.

I tried updating the regex as you suggested:

[image: Screenshot 2024-06-05 at 22.35.25.png]

But still get this:

===================================================

W, [2024-06-06T02:29:45.778465 #134]  WARN -- : prism201.eqx.ams.prod
raised Oxidized::PromptUndetect with msg "Last login: Thu Jun  6 02:27:40
2024 from 10.195.212.124


+++++++++++++++++: System Data :+++++++++++++++++++
+ Hostname = prism201.eqx.ams.prod
+ Address = ['10.240.10.121', '10.240.9.121', '10.240.10.122',
'172.17.0.1', '10.240.8.121']
+ Kernel = 5.14.0-362.18.1.el9_3.0.1.x86_64
+ Uptime =  02:29:26 up 21 days,  7:10,  2 users,  load average: 0.46,
0.59, 0.78
+ System Type = PowerEdge R450
+ Ansible Created =
+ Total Memory = 130767064 kB
+ Free Memory  = 113148476 kB
+++++++++++++++++++++++++++++++++++++++++++++++++++


***@***.*** ~]$  not matching configured prompt (?-mix:\S+@
\S+\s\S+\]\$\S*$)"
W, [2024-06-06T02:29:45.898552 #134]  WARN -- :
prismlb/prism201.eqx.ams.prod status no_connection, retry attempt 1
***@***.***:/#

===================================================

How did you deliver the output to the program?  You mean MOTD/Banner stuff
? I just copied everything from the device and pasted it into the tester,
just like i did for other devices.

Are you confident the mechnism you used to deliver the output, keeps the
output unmodified? Yes, because when I disable MOTD and hust
lastlogin notification, i am still getting promtpUndetect even though the
prompt is just this: ***@***.*** ~]$

W, [2024-06-05T01:43:32.858176 #135
<https://github.com/ytti/oxidized/issues/135>] WARN -- :
prism201.eqx.ams.prod raised Oxidized::PromptUndetect with msg
***@***.*** ~]$ not matching configured prompt
***@***.***+]*))"

Is it possible the output has ANSI codes which you didn't deliver to your
test case? Not sure, how do I test it ?

**Comment by ytti** [comment]
You can try 'set|grep PS' and 'set|grep PROMPT' to see what your prompt is. 

But quick inconclusive test is, does it have colours? If so, it has ANSI codes, for example if the opening bracket is colored, your string doesn't start with bracket, but escape, and regexp will never match.

If in doubt, please talk to someone in your organisation who is more familiar with Linux.

**Comment by vkratsberg** [comment]
The prompt is not colorized and in fact, this new Rocky Linux VM used the same provisioning tools we use for our Centos VMs, so they are identical.  However, Centos works well and Rocky doesn't.

**Comment by ytti** [comment]
It doesn't need to be colorised, it could still have ANSI codes, or there could be a control character, like \r, in front of the opening bracket. You could review the output in an editor which displays ansi and control characters as is.

Or you could change your prompt to something like TESTPROMPT and change the regexp to .*TESTPROMPT.* and see if it matches and see if ^TESTPROMPT.* stops working. To narrow down what is going on.

**Comment by vkratsberg** [comment]
I compared two devices.  prism072 -- centos7 and prism201 -- rocky.  I redirected ssh session into a file and reviewed with od -c command for presence of ANSI and other hidden characters.  Both look identical to me, however prism072 works fine with oxidized and prism201 doesn't.  Not sure what else i can do here.

vkratsberg/Desktop > od -c prism201.ams
0000000    L   a   s   t       l   o   g   i   n   :       T   h   u
0000020    J   u   n           6       2   2   :   3   6   :   2   8
0000040    2   0   2   4       f   r   o   m       1   0   .   1   2   1
0000060    .   1   6   .   2   2   8  \r  \r  \n  \r  \n  \r  \n   +   +
0000100    +   +   +   +   +   +   +   +   +   +   +   +   +   +   +   :
0000120        S   y   s   t   e   m       D   a   t   a       :   +   +
0000140    +   +   +   +   +   +   +   +   +   +   +   +   +   +   +   +
0000160    +  \r  \n   +       H   o   s   t   n   a   m   e       =
0000200    p   r   i   s   m   2   0   1   .   e   q   x   .   a   m   s
0000220    .   p   r   o   d   .   s   q   u   a   r   e   s   p   a   c
0000240    e   .   n   e   t  \r  \n   +       A   d   d   r   e   s   s
0000260        =       [   '   1   0   .   2   4   0   .   1   0   .   1
0000300    2   1   '   ,       '   1   0   .   2   4   0   .   9   .   1
0000320    2   1   '   ,       '   1   0   .   2   4   0   .   1   0   .
0000340    1   2   2   '   ,       '   1   7   2   .   1   7   .   0   .
0000360    1   '   ,       '   1   0   .   2   4   0   .   8   .   1   2
0000400    1   '   ]  \r  \n   +       K   e   r   n   e   l       =
0000420    5   .   1   4   .   0   -   3   6   2   .   1   8   .   1   .
0000440    e   l   9   _   3   .   0   .   1   .   x   8   6   _   6   4
0000460   \r  \n   +       U   p   t   i   m   e       =           2   2
0000500    :   3   6   :   5   7       u   p       2   2       d   a   y
0000520    s   ,           3   :   1   7   ,           1       u   s   e
0000540    r   ,           l   o   a   d       a   v   e   r   a   g   e
0000560    :       4   .   8   9   ,       4   .   6   4   ,       2   .
0000600    9   5  \r  \n   +       S   y   s   t   e   m       T   y   p
0000620    e       =       P   o   w   e   r   E   d   g   e       R   4
0000640    5   0  \r  \n   +       A   n   s   i   b   l   e       C   r
0000660    e   a   t   e   d       =      \r  \n   +       T   o   t   a
0000700    l       M   e   m   o   r   y       =       1   3   0   7   6
0000720    7   0   6   4       k   B  \r  \n   +       F   r   e   e
0000740    M   e   m   o   r   y           =       1   1   3   0   7   1
0000760    0   8   8       k   B  \r  \n   +   +   +   +   +   +   +   +
0001000    +   +   +   +   +   +   +   +   +   +   +   +   +   +   +   +
*
0001040    +   +   +   +   +   +   +   +   +   +   +  \r  \n  \r  \n  \r
0001060   \n 033   ]   0   ;   s   v   c   -   n   e   t   -   s   e   r
0001100    v   i   c   e   s   @   p   r   i   s   m   2   0   1   :   ~
0001120   \a 033   [   ?   2   0   0   4   h   [   s   v   c   -   n   e
0001140    t   -   s   e   r   v   i   c   e   s   @   p   r   i   s   m
0001160    2   0   1       ~   ]   $      \r  \n
0001172
vkratsberg/Desktop >
vkratsberg/Desktop > od -c prism072.ewr
0000000    L   a   s   t       l   o   g   i   n   :       T   h   u
0000020    J   u   n           6       2   1   :   4   3   :   1   4
0000040    2   0   2   4       f   r   o   m       1   0   .   1   9   5
0000060    .   2   2   1   .   4   8  \r  \r  \n  \r  \n  \r  \n   +   +
0000100    +   +   +   +   +   +   +   +   +   +   +   +   +   +   +   :
0000120        S   y   s   t   e   m       D   a   t   a       :   +   +
0000140    +   +   +   +   +   +   +   +   +   +   +   +   +   +   +   +
0000160    +  \r  \n   +       H   o   s   t   n   a   m   e       =
0000200    p   r   i   s   m   0   7   2   .   d   r   t   .   e   w   r
0000220    .   p   r   o   d   .   s   q   u   a   r   e   s   p   a   c
0000240    e   .   n   e   t  \r  \n   +       A   d   d   r   e   s   s
0000260        =       [   u   '   1   0   .   1   9   2   .   1   0   7
0000300    .   1   9   8   '   ]  \r  \n   +       K   e   r   n   e   l
0000320        =       5   .   1   7   .   1   -   1   .   e   l   7   .
0000340    e   l   r   e   p   o   .   x   8   6   _   6   4  \r  \n   +
0000360        U   p   t   i   m   e       =           2   2   :   3   7
0000400    :   5   2       u   p       3       d   a   y   s   ,
0000420    3   :   2   2   ,           1       u   s   e   r   ,
0000440    l   o   a   d       a   v   e   r   a   g   e   :       1   .
0000460    7   5   ,       1   .   7   9   ,       1   .   6   7  \r  \n
0000500    +       S   y   s   t   e   m       T   y   p   e       =
0000520    P   o   w   e   r   E   d   g   e       R   6   3   0  \r  \n
0000540    +       A   n   s   i   b   l   e       C   r   e   a   t   e
0000560    d       =      \r  \n   +       T   o   t   a   l       M   e
0000600    m   o   r   y       =       5   2   8   2   7   7   6   3   2
0000620        k   B  \r  \n   +       F   r   e   e       M   e   m   o
0000640    r   y           =       5   1   9   1   5   7   0   3   6
0000660    k   B  \r  \n   +   +   +   +   +   +   +   +   +   +   +   +
0000700    +   +   +   +   +   +   +   +   +   +   +   +   +   +   +   +
*
0000740    +   +   +   +   +   +   +  \r  \n  \r  \n  \r  \n 033   ]   0
0000760    ;   s   v   c   -   n   e   t   -   s   e   r   v   i   c   e
0001000    s   @   p   r   i   s   m   0   7   2   :   ~  \a 033   [   ?
0001020    1   0   3   4   h   [   s   v   c   -   n   e   t   -   s   e
0001040    r   v   i   c   e   s   @   p   r   i   s   m   0   7   2
0001060    ~   ]   $      \r  \n
0001066

**Comment by ytti** [comment]
They both clearly have ANSI codes, look at where \r\n is, and how much data there is before the visible prompt `[svc` starts.

There is ```\r\n0333]0;````, which is color reset, which follows unbracketed `svc-net-services...` followed by BEL (\a) and again reset. 
You would need to see ```\r\n[svc``` to have matching prompt, because you're doing ```^[```, mandating that opening bracket follows after \n.

Perhaps there is some reason (TERM use?) why the oxidized SSH session used against centos doesn't print these, and the SSH session used against rock linux does. 

Before prompt starts there is ```033   [   ?   2   0   0   4   h``` or ```033   [   ?  1   0   3   4   h```` which to me is not sensical at all, like I don't understand what they are trying to do with those codes. 

But definitely the prompt is not what you think it is, and you may need to figure out, why it's working in centos, your prompt is not starting with opening bracket after new line, in either of the examples.

**Comment by ytti** [comment]
The first time in the output seen the svc-net-services@prismNNN is seen, that is the xterm title being set, second time is actual prompt. I don't know what the 2004h and 1034h try to do, and why that's different. 

At any rate, if you actually provided representative output of what prompt is seen, neither would work. And if one works, then  that devices must not be using that prompt, when reached by Oxidized (could be related to TERM difference).

**Comment by ytti** [comment]
You can use exec mode, in which case you don't need to detect prompt.

```
cfg :ssh do
   exec true
```

**Comment by vkratsberg** [comment]
Thank you @ytti.  Using exec mode worked like a charm.
