### ISSUE TITLE
SSH problem to certain devices

### ISSUE THREAD

**Issue by roedie** [ytti/oxidized#319]
While ssh-ing to some network devices I get the error:

Net::SSH::Disconnect with msg "disconnected: Protocol error: expected packet type 30, got 34 (2)"

It seems to be related to the handshake packet size being too long(?). We've fixed the problem by adding the following to line 35 of lib/oxidized/input/ssh.rb:

:encryption => ["blowfish-cbc", "3des-cbc"],
:kex => "diffie-hellman-group1-sha1")

This doesn't look like the best solution to me, but I'm not sure what is. Do you have a solution?

**Comment by ytti** [comment]
This might be bit of a pickle. If we change it now to that, we may be break some other systems and we won't support all relevant options, others which may be more secure for same compute cost. 

One option is, that we'll allow these to be set via variables. So in config you'd have
```
vars:
  ssh_encryption:
    - blowfish-cbc
    - 3des-cbc
  ssh_kex:
     - diffie-hellman-group1-sha
```

And in ssh.rb we'd have something like this

```
ssh_opts = {
   ....
}
ssh_opts[:encryption] = vars(:ssh_encryption) if vars(:ssh_encryption)
ssh_opts[:kex] = vars(:ssh_kex) if vars(:sss_kex)

@ssh = Net::SSH.start(@node.ip, @node.auth[:username], ssh_opts
```




As vars are available automatically globally, group level and node level, this would further allow to handle some node specific corner cases where single encryption/kex combo cannot satisfy all devices.


If you can test that, and submit PR, I'll merge it.
