### ISSUE TITLE
Timing issue with Extreme x440

### ISSUE THREAD

**Issue by roedie** [ytti/oxidized#320]
When using telnet to backup an Extreme 440 the poll hangs if the config is not saved. It seems the 'n' to take care of the save prompt is sent to fast.

Using SSH all is fine.

**Comment by ytti** [comment]
The 'n' is send with 'pre_logout' without block, this translates to ```cmd 'n'```, which further means we're waiting for a prompt.

In this instance we just want to puke 'n' and not try to wait for a prompt, because one may not exist, if I understood correctly. 

So it should be something like
```
pre_logout do
  send 'n'
end
```

@tobiasa1

**Comment by tobiasa1** [comment]
Hi,

I can try it out tomorrow when I'm at office. I have many different Extreme to verify on.

**Comment by ytti** [comment]
I lieeeeed. ```pre_logout "exit"``` does not wait for prompt. So original should have worked.

**Comment by roedie** [comment]
I do see when using SSH the 'n' is being sent to the X440, but it is done with 1.5msec or so. So when using telnet the 'Save configuration' prompt isn't there yet, the X440 ignores the 'n' and waits for the user to press the 'n'. At least, that's the theory...

Debug using telnet:
```
D, [2016-02-19T12:15:12.639568 #2205] DEBUG -- : Telnet: disable clipaging @x.x.x.x
D, [2016-02-19T12:15:12.937902 #2205] DEBUG -- : Telnet: show version @x.x.x.x
D, [2016-02-19T12:15:13.111712 #2205] DEBUG -- : Telnet: show diagnostics @x.x.x.x
D, [2016-02-19T12:15:14.137252 #2205] DEBUG -- : Telnet: show licenses @x.x.x.x
D, [2016-02-19T12:15:14.677934 #2205] DEBUG -- : Telnet: show switch @x.x.x.x
D, [2016-02-19T12:15:14.844234 #2205] DEBUG -- : Telnet: show configuration @x.x.x.x
D, [2016-02-19T12:15:22.346915 #2205] DEBUG -- : Telnet: exit @x.x.x.x
W, [2016-02-19T12:15:42.814666 #2205]  WARN -- : x.x.x.x raised Timeout::Error with msg "timed out while waiting for more data"
W, [2016-02-19T12:15:43.126306 #2205]  WARN -- : x.x.x.x status no_connection, retry attempt 1
```
Last lines of log:
```
#
# Module vsm configuration.
#
* SW04.7 # exit
^MDo you wish to save your configuration changes to primary.cfg? (y/N) 
```
Using SSH:
```
D, [2016-02-19T12:20:50.593928 #2240] DEBUG -- : SSH: disable clipaging @ x.x.x.x
D, [2016-02-19T12:20:51.005903 #2240] DEBUG -- : SSH: show version @ x.x.x.x
D, [2016-02-19T12:20:51.423640 #2240] DEBUG -- : SSH: show diagnostics @ x.x.x.x
D, [2016-02-19T12:20:52.748313 #2240] DEBUG -- : SSH: show licenses @ x.x.x.x
D, [2016-02-19T12:20:53.163442 #2240] DEBUG -- : SSH: show switch @ x.x.x.x
D, [2016-02-19T12:20:53.792760 #2240] DEBUG -- : SSH: show configuration @ x.x.x.x
D, [2016-02-19T12:21:00.569919 #2240] DEBUG -- : SSH: exit @ x.x.x.x
D, [2016-02-19T12:21:00.570458 #2240] DEBUG -- : SSH: n @ x.x.x.x
I, [2016-02-19T12:21:01.694833 #2240]  INFO -- : Configuration updated for /x.x.x.x
```
Last lines of log:
```
#
# Module vsm configuration.
#
* SW04.7 # exit
^MDo you wish to save your configuration changes to primary.cfg? (y/N) No
^M
```

**Comment by ytti** [comment]
So this is my misunderstanding of how Net::Telnet works.

I'm passing the Net::Telnet 'cmd' method 'match' with value of 'nil', with expectation that this means we're not waiting for anything.
But as I read the Net::Telnet sources, there is no way to turn off pattern matching in 'cmd' method. So we're actually waiting for nil. But because somethings work, I think we'll return nil on EOF. So it's kind of fluke that any telnet stuff works.

Workaround is
post_login do
  send "exit\n"
  send "n\n"
end

This will use different method, not cmd, and won't wait for prompt.

ssh.rb works correctly, and when expect is set to 'nil', it won't wait for anything.

Fixing the telnet.rb seems like I'd need to redefine the Net::Telnet 'cmd' method completely, perhaps 'waitfor' method too.

**Comment by roedie** [comment]
Tested with:
```
pre_logout do
  send "exit\n"
  send "n\n"
end
```
and this does the trick. Do you want a PR which fixes models where this is used?

**Comment by ytti** [comment]
Yeah go for it.

**Comment by roedie** [comment]
As far as I'm concerned this one can be closed.
