### ISSUE TITLE
http input log

### ISSUE THREAD

**Issue by marmack95** [ytti/oxidized#3206]
Hello,

I use the last docker version of oxidized.

When i use a http model, file, the log file is always empty.
Which is difficult to debug.

Stderr and Stdout appear in docker log.

If is not a bug, you can close this ticket.

**Comment by robertcheramy** [comment]
I can read in the source code that ssh logs more than http.
This ist not a bug, perhaps an enhancement request. No one is likely to work on it, so I close it now.
If you want more logs in the http input, feel free to make a Pull Request.
