### ISSUE TITLE
Raisecom switch fails backup - but full backup is stored in the log file.

### ISSUE THREAD

**Issue by jcabrerap** [ytti/oxidized#3212]
I've been having issues with succesfully pulling the backups from all our Raisecom switches.

With the model that it is included on the oxidized repository the job outright fails to log in, but when using another model that I made for testing it goes as far as executing both `show version` and `show running-configuration` but it fails after sending the `exit` command.

When I look at the logs at `/home/oxidized/oxidized-conf/logs` there is the full config displayed and I can see that the `exit` command was sent.

 **config:** https://pastebin.com/uYD9GE1s

**model:** https://pastebin.com/dnR6y2Yc

**debug error:** https://pastebin.com/PbiFbSea

The only thing I haven't tried yet is switching to ssh.

Any clues on what can be the issue?

EDIT: I failed to mention that I'm having the same issue in both the latest docker image that I set up for testing and our production installation in a Ubuntu Server.

**Comment by ytti** [comment]
You could try to add ', IOError' [here](https://github.com/ytti/oxidized/blob/master/lib/oxidized/input/telnet.rb#L66)

i.e. ```rescue Errno::ECONNRESET, IOError```

**Comment by jcabrerap** [comment]
Awesome! This fixed the issue!

Thanks for the quick reply ytti.
