### ISSUE TITLE
no source http url config

### ISSUE THREAD

**Issue by waja** [ytti/oxidized#3216]
Hi there,

I'm using the docker image `oxidized/oxidized:latest`, which seems (re-)build with every commit. My setup broke around 2 hours ago with the fault `no source http url config`.

the relevant config part:

```
source:
  default: http
  debug: true
  http:
    url: https://librenms/api/v0/oxidized
    map:
      name: hostname
      model: os
      group: group
    vars_map:
      ssh_port: ssh_port
      telnet_port: telnet_port
    headers:
      X-Auth-Token: a647688a9ab5f52fc4a61e0f9a870733
```

Fetching the oxidized config via librenms api works as expected.

Rolling back to the image `oxidized/oxidized:0.30.1` fixed the issue for me.

Looking into the commit history and the time of incident may suggest that the cause might be #3198.

Cheers, Jan.

**Comment by ytti** [comment]
I believe this is because we call super on initialize, which resets the http config to json config @sargon 

We may want to call super first, then set @cfg.

**Comment by ytti** [comment]
Can you try this

```diff
diff --git a/lib/oxidized/source/http.rb b/lib/oxidized/source/http.rb
index 257d55c..484cd6d 100644
--- a/lib/oxidized/source/http.rb
+++ b/lib/oxidized/source/http.rb
@@ -2,8 +2,8 @@ module Oxidized
   require "oxidized/source/jsonfile"
   class HTTP < JSONFile
     def initialize
-      @cfg = Oxidized.config.source.http
       super
+      @cfg = Oxidized.config.source.http
     end

     def setup
```

**Comment by waja** [comment]
> Can you try this

As I'm just running the container, it is very hard to modify the file (on the fly).

**Comment by ytti** [comment]
> > Can you try this
> 
> As I'm just running the container, it is very hard to modify the file (on the fly).

Ok, let's hope @sargon can test it.

**Comment by frankuit** [comment]
> Can you try this
> 
> ```diff
> diff --git a/lib/oxidized/source/http.rb b/lib/oxidized/source/http.rb
> index 257d55c..484cd6d 100644
> --- a/lib/oxidized/source/http.rb
> +++ b/lib/oxidized/source/http.rb
> @@ -2,8 +2,8 @@ module Oxidized
>    require "oxidized/source/jsonfile"
>    class HTTP < JSONFile
>      def initialize
> -      @cfg = Oxidized.config.source.http
>        super
> +      @cfg = Oxidized.config.source.http
>      end
> 
>      def setup
> ```

Can confirm this works:

First i had: oxidized -d
no source http url config, edit ~/.config/oxidized/config
/var/lib/gems/3.1.0/gems/oxidized-0.30.1/lib/oxidized/source/http.rb:13:in `setup': no source http url config, edit ~/.config/oxidized/config (Oxidized::NoConfig)

Applied fix to move @cfg = Oxidized.config.source.http
1 line down, and now:
oxidized -d
Puma starting in single mode...
* Puma version: 6.4.2 (ruby 3.1.2-p20) ("The Eagle of Durango")
*  Min threads: 0
*  Max threads: 5
*  Environment: development
*          PID: 557029
* Listening on http://127.0.0.1:8888
Use Ctrl-C to stop
^C- Gracefully stopping, waiting for requests to finish

**Comment by waja** [comment]
I'm very happy to test this fix, when it's available via a docker image.

**Comment by waja** [comment]
Okay ... `oxidized/oxidized:latest` works as expected again.
