### ISSUE TITLE
How to ignore fortigate backup config password difference for versions difference check

### ISSUE THREAD

**Issue by KevinTang8888** [ytti/oxidized#3227]
Hi 

I have Oxidized backup fortigate FW config working. because every time the password is difference during the backup config check. so the config version difference change a lot.
Can I ignore the password change during the config version checking? please see the attached picture of the config difference for password checking.

Thanks
![FortiGate backup versions with password](https://github.com/user-attachments/assets/9c68e9b7-f1b5-4a8a-a159-6c1f5778d81f)

**Comment by systeembeheerder** [comment]
config:
```
models:
  fortios:
    vars:
      remove_secret: true
```

**Comment by systeembeheerder** [comment]
Duplicate of #3176

**Comment by KevinTang8888** [comment]
Thanks, it has fixed my issue.

**Comment by sysblade** [comment]
But does it actually still backup the whole configuration including the secrets ? Because it sounds like it would just skip all the secrets (and so make the config incomplete)
