### ISSUE TITLE
Don't hardcode `~/.config/oxidized/config`

### ISSUE THREAD

**Issue by WilliamDEdwards** [ytti/oxidized#3229]
The path `~/.config/oxidized/config` is hardcoded in several places, mostly (if not only) in messsages AFAICS. 

This is incorrect and confusing, as the `~/.config/oxidized` part is dynamic - based on the `OXIDIZED_HOME` environment variable.

**Comment by robertcheramy** [comment]
26f48bd was a small step in this direction, thanks for the hint I should have checked the whole code.
