### ISSUE TITLE
Can't have Oxidized use different credentials depending on the device/group?

### ISSUE THREAD

**Issue by MLyszyk** [ytti/oxidized#3230]
Having issues with Oxidized here. 
I initially have our username and password set in the config file at the top at a global level, which seems to be the set Oxidized is using by default. In the groups section, I have 2 different groups -->
comware:
username: oxidized
password: {password}

comware_qa:
username: qa.oxidized
password: {password}

In my inventory file, I have various devices but they all look like either of the four after trying to get this to work -->
testSwitch:comware:oxidized:{password}
testSwitch2:comware_qa:qa.oxidized:{password}
testSwitch3:comware:comware_qa
testSwitch4:comware:qa.comware:{password}

However, when I restart oxidized and check the journalctl -fu output, I see oxidized is still using the default "oxidized" account on the devices I need it to use the "qa.oxidized" account on. I commented out the "username:" and "password:" config lines at the global level and restarted oxidized, but now the journalctl output is saying "Failed authentication for user username:<device name/ip>". 

How can I get this config file and/or inventory file to work with oxidized where it can go through the inventory and use the specific credential set that is assigned to that group referenced in the inventory file? It seems like it wants and only uses the credential set that is placed at the top of the config file at the global level, and doesn't even bother to use the groups: section.

Anyone have ideas or pointers? :)

**Comment by MLyszyk** [comment]
The password fields above are blank but I meant to have <password> there as a placeholder. So yes, I do have a password value there, I don't know why it shows blank in this thread :)

**Comment by MLyszyk** [comment]
I meant to have {password}

**Comment by MLyszyk** [comment]
I am fairly confident that oxidized is only using the credential set that is configured at the global level/top of the config file, and not the credential sets I have in the "groups: " section. For instance, at the global level, I have 2 sets -->
username: oxidized
password: APassword
username: qa.oxidized
password: BPassword

If I comment out the 1st set and run oxi, it will go through the inventory and error out on those devices needing the 1st set since it is using the 2nd set. If I swap the sets and re-run it, then it'll work on those taking the 1st set and not the 2nd set. If I comment out both sets, then I get an error saying "Authentication failed for user username@{IP}". If I un-comment out both sets and run oxi, it goes through the inventory only using the 2nd set and not the 1st set. So basically, it seems that oxidized only wants to use the credential sets that are at the global level/very top of the config file, and not the ones in the "groups: " section, but it can only use 1 set at the global level?

Can anyone assist me please? I just want oxidized to go through the inventory file and whichever group is assigned to it, it will use that set and pull the config --> device1:comware:oxidized:APassword || device2:comware_qa:qa.oxidized:BPassword || device:comware:comware_qa --> whichever works to have oxidized be able to go through all of them and use the correct credential set depending on what is configured in the inventory.rb "router.rb" file.

**Comment by MLyszyk** [comment]
I feel like it might be a simple fix or workaround, is there a support team outside of git or the gitty forum to contact?

**Comment by MLyszyk** [comment]
Here's my full oxidized config file EXCLUDING THE HOOKS SECTION FOR EMAIL AND THE COPY SECTION. If additional config or other data is needed please let me know :)  -->
`---
username: oxidized
password: APassword
#username: qa.oxidized
#password: BPassword
model: comware
#model: h3c
model: panos
model: fsos
model: fs
model: fsnsg
model: cnos
resolve_dns: true
interval: 3600
use_syslog: false
debug: false
threads: 30
timeout: 30
retries: 2
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
#rest: 127.0.0.1:8888
next_adds_job: false
vars:
  auth_methods: [ "none", "publickey", "password", "keyboard-interactive" ]
groups:
  comware:
    username: oxidized
    password: APassword
  comware_qa:
    username: qa.oxidized
    password: BPassword
  hpe:
    username: oxidized
    password: APassword
  hpe_qa:
    username: qa.oxidized
    password: BPassword
  panos:
    username: oxidized
    password: APassword
  panos_qa:
    username: qa.oxidized
    password: TBPassword
  #tmos:
    #username:
    #password:
  fs:
    username: oxidized
    password: APassword
  fs_qa:
    username: qa.oxidized
    password: BPassword
models: {}
pid: "/home/oxidized/.config/oxidized/pid"
crash:
  directory: "/home/oxidized/.config/oxidized/crashes"
  hostnames: false
stats:
  history_size: 10
input:
  default: ssh
  debug: false
  ssh:
    secure: true
  utf8_encoded: true
output:
  default: git
  file:
    directory: "/home/oxidized/configs"
  git:
    user: oxidized
    email: coolpeople@domain.com
    repo: "/home/oxidized/.config/oxidized/DeviceConfigs.git"
    enabled: true
    auto_commit: true
source:
  default: csv
  csv:
    file: "/home/oxidized/.config/oxidized/CE_Devices.db"
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
    gpg: false
model_map:
  comware: comware
  #comware_qa: comware
  #comware: comware_qa
  panos: panos
  fs: fs
  fs: fsos
  fsnsg: fsnsg
  fsos: fsos
  fsos: fs
  fs: cnos
  cnos: cnos
  cnos: fs
 copy_configs:
   type: exec
   events: [post_store]
   cmd: 'cp -r /home/oxidized/.config/oxidized/DeviceConfigs.git/* /home/oxidized/configs/'
   cmd: 'git archive master --remote /home/oxidized/.config/oxidized/DeviceConfigs.git/ ${OX_NODE_NAME} | tar -x -C /home/ox>
   async: true
   timeout: 5120
   path: /home/oxidized/.config/oxidized/config
`

**Comment by MLyszyk** [comment]
This case is still open, would really appreciate some assistance please. Any other areas I can get support from?

**Comment by MLyszyk** [comment]
@ytti @robertcheramy Assistance please :)

**Comment by ytti** [comment]
Have you tried after this? https://github.com/ytti/oxidized/commit/60dd78672bfa6f78c6b159f50b4cc08acd081d1e

**Comment by MLyszyk** [comment]
@ytti I'm not too familiar with github and oxidized fully yet, what am I look at here exactly? Do I need to make my config look like that??

**Comment by MLyszyk** [comment]
@ytti I don't have a node.rb in that directory, but I do have a /home/oxidized/.config/oxidized/lib/oxidized/refinements.rb file. This is what is inside -->
module Refinements
  # Use the 'refine' keyword to define refinements for the String class
  refine String do
    attr_accessor :type, :cmd, :name

    # @return [String] copy of self with last line removed
    def cut_tail(lines = 1)
      return "" if length.zero?

      each_line.to_a[0..(-1 - lines)].join
    end

    # @return [String] copy of self with first line removed
    def cut_head(lines = 1)
      return "" if length.zero?

      each_line.to_a[lines..-1].join
    end

    # @return [String] copy of self with first and last lines removed
    def cut_both(head = 1, tail = 1)
      return "" if length.zero?

      each_line.to_a[head..(-1 - tail)].join
    end

    # sets @cmd and @name unless @name is already set
    def set_cmd(command)
      @cmd = command
      @name ||= @cmd.to_s.strip.gsub(/\s+/, '_') # what to do when command is proc? #to_s seems ghetto
    end

    # Initializes the String instance variables from another String instance
    # when the given str is an instance of String with Oxidized refinements applied
    def init_from_string(str = '')
      raise TypeError unless str.instance_of?(String)

      @cmd  = str.instance_variable_get(:@cmd)
      @name = str.instance_variable_get(:@name)
      @type = str.instance_variable_get(:@type)
    end
  end
end

**Comment by MLyszyk** [comment]
@ytti I feel like we are semi-close to figuring this out given that oxidized is capable of doing what I want it to do it seems, but just need help figuring it out! I appreciate the link you provided me as it does offer some sort of guidance, but I could still use a professional hand to help finish this off please :) 
Do I need to create a "node.rb" file with all that included, maybe switch out some placeholders? Or is there more to it that I'm not seeing? My company and I enjoy using oxidized, and I feel like this might be the last obstacle to getting us 110% comfortable and happy utilizing oxidized, which is a great tool.

**Comment by robertcheramy** [comment]
What @ytti means is that your issue may be have already been addressed in the development version (master branch on github). Can you test it and tell us if you still have an issue?

**Comment by MLyszyk** [comment]
@robertcheramy Hey Robert! That's what I am trying to figure out exactly, as I am not too familiar with github fully. Is the link @ytti provided above the "development version (master branch)"? If so, how do I test that? When I open it, it brings me to a section of that lengthy code, rows 198 | 198 - 230 | 240 (?). I assume red "-" means code that was taken out, so only focusing on the green "+" lines of code. Am I creating a node.rb file in that /home/oxidized/.config/oxidized/lib/oxidized directory with only the green lines of code from rows 198 - 230 / 240??

I apologize if I am misunderstanding or not fully grasping what @ytti means, as I am still trying to learn and get familiar with github!! :/

**Comment by MLyszyk** [comment]
@aschaber1 Hey Alex! :)
Could you take a look at this thread when you get the chance please and let me know if you have any additional input or solutions? Or by what @ytti and @robertcheramy are talking about with that commit change doc? Thank you 3 honestly for the product which my company loves very much, and I am not trying to be a burden, I just want this to work and then I can help with issues I am aware of/familiar with.

**Comment by robertcheramy** [comment]
@MLyszyk please stop asking everyone you think of, it won't help you further.

To build/run oxidized from git, please read https://github.com/ytti/oxidized/blob/master/README.md#build-from-git
You can also use the latest docker image, read https://github.com/ytti/oxidized/blob/master/README.md#running-with-docker and https://github.com/ytti/oxidized/blob/master/README.md#running-with-podman-compose
You can also run directly from git, see https://github.com/ytti/oxidized/blob/master/README.md#running-with-podman-compose

As you see, there is a lot of documentation to read if you want your issue to be fixed, and you will need to invest some time into it. If you do not have the time, you will have to wait for next release to try if you issue has been fixed there. If not, you'll have to hope that someone find it worth to invest time into it. If you can't wait, search and pay someone to to it for you.

**Comment by MLyszyk** [comment]
Understood, apologies. However, I made some recent changes that somewhat made progress but I am still having issues, but might be easier to identify and resolve.
I have been modifying the models section and such and assigned them credentials, and then I commented out the global credentials at the top. Now when oxidized runs, it doesn't say the "username" account is being used anymore for devices with the global credentials commented out. It's actually using credentials configured specifically somewhere in the config file. However, while the devices that take the "oxidized" account are working with these changes, the devices that take the "qa.oxidized" account are still not. It seems Oxidized is either struggling to use the group credentials or the credentials defined in the models section. When I restart oxidized and check logs, this is what I see -->

Jul 30 16:26:38 linuxsvr01.coolpeoplecom oxidized[346602]: E, [2024-07-30T16:26:38.683307 #346602] ERROR -- : node {:name=>"Txau41ms", :model=>"Comware_qa", :group=>"Comware_qa"} raised Oxidized::ModelNotFound with message 'Comware_qa not found for node 10.10.10.1
Jul 30 16:26:38 linuxsvr01.coolpeople.com oxidized[346602]: E, [2024-07-30T16:26:38.685448 #346602] ERROR -- : node {:name=>"Txau42ls", :model=>"Comware_qa", :group=>"Comware_qa"} raised Oxidized::ModelNotFound with message 'Comware_qa not found for node 10.10.10.2
Jul 30 16:26:38 linuxsvr01.coolpeople.com oxidized[346602]: E, [2024-07-30T16:26:38.687539 #346602] ERROR -- : node {:name=>"Txau43ms", :model=>"Comware_qa", :group=>"Comware_qa"} raised Oxidized::ModelNotFound with message 'Comware_qa not found for node 10.10.10.3

I have a "Comware_qa.rb" model script that is identical to the "comware.rb" model file other than "Class Comware < Oxidized::Model" being turned into "Class Comware_qa < Oxidized::Model". These are located in /home/oxidized/.config/oxidized/lib/oxidized/model/

This is what I have for those 3 in the inventory file -->
Txau41ms:Comware_qa:Comware_qa:qa.oxidized:BPassword
Txau42ls:Comware_qa:Comware_qa:qa.oxidized:BPassword
Txau43ms:Comware_qa:Comware_qa:qa.oxidized:BPassword

This is what I have in the config file -->
---
#----Directed Oxidized to the Models directory----
model_dir: /home/oxidized/.config/oxidized/lib/oxidized/model/

#----Global Credentials. Commented out to use group/model-specific credentials------
#username: oxidized
#password: APassword
#username: qa.oxidized
#password: BPassword

#-----Models (Unsure if section is needed or wrong)-----------
model: comware
#model: Comware_qa
#model: h3c
model: panos
model: fsos
model: fs
model: fsnsg
model: cnos

#----Additional Settings------
resolve_dns: true
interval: 3600
use_syslog: false
debug: false
threads: 30
timeout: 30
retries: 2
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
#rest: 127.0.0.1:8888
next_adds_job: false
vars:
  auth_methods: [ "none", "publickey", "password", "keyboard-interactive" ]

#-------Groups---------
groups:
  comware:
    username: oxidized
    password: APassword
    model: comware
    #models:
      #comware:
        #username: comware_username
        #password: comware_password
  Comware_qa:
    username: qa.oxidized
    password: BPassword
    model: Comware_qa
    #models:
      #comware:
        #username: qa_comware_username
        #password: qa_comware_password
  <Other groups not struggling>

#-------------Models section-------------
#models: {}
models:
  comware:
    username: oxidized
    password: APassword
  Comware_qa:
    username: qa.oxidized
    password: BPassword
  <Other Models not struggling>

#------Additional Log/File Settings, No need to re-configure-----
pid: "/home/oxidized/.config/oxidized/pid"
crash:
  directory: "/home/oxidized/.config/oxidized/crashes"
  hostnames: false
stats:
  history_size: 10
input:
  default: ssh
  debug: false
  ssh:
    secure: true
  utf8_encoded: true
output:
  default: git
  file:
    directory: "/home/oxidized/configs"
  git:
    user: oxidized
    email: someonesupercool@gmail.com
    repo: "/home/oxidized/.config/oxidized/DeviceConfigs.git"
    enabled: true
    auto_commit: true

#------Source(s) for Oxidized to gather data from-----
source:
  default: csv
  csv:
    file: "/home/oxidized/.config/oxidized/CE_Devices.db"
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
      group: 2
      #username: 3
      #password: 4
    gpg: false

#-----Model map section, might be where issues are occuring------
model_map:
  comware: comware
#  Comware_qa: comware_qa
  comware_qa: Comware_qa
  Comware_qa: Comware_qa
  hp: comware
  #comware: comware_qa
  panos: panos
  fs: fs
  fs: fsos
  fsnsg: fsnsg
  fsos: fsos
  fsos: fs
  fs: cnos
  cnos: cnos
  cnos: fs

Despite what the devices have set in the inventory file, it seems Oxidized is trying to use the model_map section to help direct it. However, I have been toying with it and it still struggles to either find the Comware_qa model or struggles to use the qa.oxidized credential set for qa.oxidized devices while it is using the correct set for the oxidized devices.
