### ISSUE TITLE
Stats REST endpoint returns invalid values

### ISSUE THREAD

**Issue by danwalkeruk** [ytti/oxidized#3234]
I'm writing a monitoring script to check the 'last' status of a backup fetch. Appending .json to the /nodes path works fine, but if I do the same for stats I get object references back as the values, where I would expect dictionaries of values to be:

GET /nodes/stats.json, returns:

```
    {
        "example1-host.net": "#<Oxidized::Node::Stats:0x00007fbe3a321f18>",
        "example2-host.net": "#<Oxidized::Node::Stats:0x00007fbe3a36a6a0>",
        "example3-host.net": "#<Oxidized::Node::Stats:0x00007fbe3a2ce278>",
        ...
    }
```

Admittedly there aren't many docs on the REST API or how it should work, but I stumbled across this PDF (https://www.trex.fi/2014/oxidized-trex.pdf) showing an ancient version of Oxidized, but the REST endpoint for /nodes/stats seems to return the expected values there.

I don't see any other open issues for this, so I'm not sure as to whether this is a non-issue for some reason, or whether no one else is using that part of the API.

**Comment by yoakim** [comment]
Hello!

Pretty sure i stumbled on this aswell when I wrote some kind of monitoring to check the status due to the lack of documentation.
I think this is what you are looking for: https://<URL>/nodes?format=json

Cheers

**Comment by danwalkeruk** [comment]
> Hello!
> 
> Pretty sure i stumbled on this aswell when I wrote some kind of monitoring to check the status of all devices. I think this is what you are looking for: https://YOUR-URL/nodes?format=json
> 
> Cheers

Thanks, but that just return the JSON for /nodes, which I could already get with .json appended.

It look like this has been an issue for a while: https://github.com/ytti/oxidized-web/issues/182

**Comment by yoakim** [comment]
Sorry, you are correct. I was trying to do the same thing as you with the stats endpoint, but i ended up just using the last field from the above URL.

**Comment by danwalkeruk** [comment]
> Sorry, you are correct. I was trying to do the same thing as you with the stats endpoint, but i ended up just using the last field from the above URL.

No worries, appreciate the reply.

It seems to be that the Stats objects need to be serialised, unfortunately I don't know Ruby so can't submit a PR for that. 

I was trying to avoid using /nodes.json as if Oxidized is restarted then all 'last' fetch times are set to 'never' and monitoring checks start alerting. I have an interval of 1hr, but around 3000 devices, so it takes time to fetch them all and for monitoring to recover.

Perhaps there is an argument to be made that 'last' status should be stored in the database? This would only really work with a sql based source, though, and then for things like router.db inputs you would need some sort of status.json file or similar.

**Comment by yoakim** [comment]
Yeah I understand the problems, if my oxidized would restart my daily report would have 1000 failed devices.
I'm not sure how flexible and how much logic you can put into your monitoring services though.
Because if you just do some logic like this maybe you can work around it?
```
if device["last"] == None:
  do_nothing() #because here you know it didnt even try
else:
  #now we know that last is not None, hence it tried to backup the device and there is a status
  if device["last"]["status"] == 'success':
    do_nothing()
  else: #config fetch tried, and its not a success
    send_notification()
```

And yea, you can always use another database to save state, altough a bit hacky.

**Comment by robertcheramy** [comment]
This is an oxidized-web issue and an issue have been opened there.
I'm closing this issue, please go on in the issue in oxidized-web.
