### ISSUE TITLE
Oxidized is in a loop with a device?

### ISSUE THREAD

**Issue by MLyszyk** [ytti/oxidized#3242]
Hey all,

I believe something weird is going on with this device(s) that Oxidized is pulling. We are getting numerous emails of config changes for a device that seems to be in a loop. For instance, one email for the switch will say this -->
```
interface eth-0-7
  flowcontrol receive on
- switchport access vlan 3438
+ switchport access vlan 2094
 !
 interface eth-0-8
  flowcontrol receive on
- switchport access vlan 2482
+ switchport access vlan 2095
```

Then, the next email will say this -->
```
interface eth-0-7
  flowcontrol receive on
- switchport access vlan 2094
+ switchport access vlan 3438
 !
 interface eth-0-8
  flowcontrol receive on
- switchport access vlan 2095
+ switchport access vlan 2482
```

Then, after those 2 being sent, it'll send another email that says this -->
```
interface eth-0-7
  flowcontrol receive on
- switchport access vlan 3438
+ switchport access vlan 2094
 !
 interface eth-0-8
  flowcontrol receive on
- switchport access vlan 2482
+ switchport access vlan 2095
```

And then it just keeps on going, and it's not just that interface it does this with but the overall switch config. Is there a database that Oxidized is using to hold the pulled configurations of a device that gets used for comparison against newly pulled configs for that device? Maybe if I remove the existing file, the next time it'll pull will be that device's "first time"? But I assume that means I'll lose all configuration iterations that have occurred which can be seen on our Oxidized-Web. 

Any ideas or tips?

Thanks!

**Comment by robertcheramy** [comment]
Please give more context:
- which version of oxidized are you running?
- give your oxidized configuration (with everything you don't want to share like passwords remove/modified)
- which model are you using?

It seems like a configuration flapping to me, oxidized just informs you that the configuration changed.
Check on the device that the configuration did not change.

**Comment by robertcheramy** [comment]
Closing issue as no user input.
