### ISSUE TITLE
Lost Aruba switches after update

### ISSUE THREAD

**Issue by stopping7** [ytti/oxidized#3247]
Hello!
I've just updated my Oxidized from 0.28.0 to 0.30.1 and now my Aruba 2930F switches are not updating as they did before. 
I get the following error message in the log:

> E, [2024-08-14T10:30:19.787775 #1200] ERROR -- : 10.1.0.2 raised NoMethodError with msg "undefined method `cut_both' for "show version\n\nImage stamp:    /ws/swbuildm/rel_beluru_qaoff/
> code/build/lvm(swbuildm_rel_beluru_qaoff_rel_beluru)\n                Jul 19 2023 02:38:00\n                WC.16.11.0013\n                422\nBoot Image:     Primary\n\nBoot ROM Versi
> on:    WC.16.01.0010\nActive Boot ROM:     Primary\n\site1-switch01.example.net# ":String
> 

In logs/10.1.0.2-ssh it ends with:

> Boot ROM Version:    WC.16.01.0010
> Active Boot ROM:     Primary
> 
> site1-switch01.example.net#

Not sure what the problem could be, anyone have a clue? I would really appreciate the help, thank you!

Edit: I tried downgrading to 0.29.1 and got the same error.

**Comment by robertcheramy** [comment]
Do you have a custom model for the Aruba 2930F?
I thin 0.29 introduced refinements, which needs to be called in every model: https://github.com/ytti/oxidized/blob/48885d460c8175fc4c98f433d802682ea91d0250/docs/Creating-Models.md?plain=1#L21
the method cut_both is defined in https://github.com/ytti/oxidized/blob/48885d460c8175fc4c98f433d802682ea91d0250/lib/refinements.rb#L21

**Comment by stopping7** [comment]
Added using Refinements and that did the trick. Thank you!
