### ISSUE TITLE
OXIDIZED_HOME being ignored

### ISSUE THREAD

**Issue by AvrumFeldman** [ytti/oxidized#3255]
In oxidized v0.30.1 the OXIDIZED_HOME seems to be completely ignored.

When running the first time `oxidized` the base config file gets created in  ~/.config/oxidized/config and on subsequent `oxidized` the errors show attempted loading of the default config file and not from the OXIDIZED_HOME path.

Even if I move the config file from ~/.config/oxidized/config to the $OXIDIZED_HOME  path on subsequent  `oxidized` the config file gets recreated at the default path of ~/.config/oxidized/config.

**Comment by robertcheramy** [comment]
I cannot reproduce. The error message did not use OXIDIZED_HOME, I fixed this in 26f48bd.

Are you sure OXIDZED_HOME is set? Try `export | grep OXIDIZED_HOME` before running oxidized.

**Comment by robertcheramy** [comment]
Closing issue as no response from user.
