### ISSUE TITLE
I would like to see an explanation of each setting item in the oxidized config in the document.

### ISSUE THREAD

**Issue by ts0818** [ytti/oxidized#3267]
I would like an explanation of what values should be set for each setting item in the oxidized config. It is not clear which values are related to router.db from the information in the current document.

▼ Target documents
https://github.com/ytti/oxidized/blob/master/docs/Configuration.md

**Comment by skiera6** [comment]
From what I can see, everything is explained in the documentation. If you want detailed information about each configuration setting for Oxidized, here’s a general guide:

- For misc configuration, refer to the [Configuration.md](https://github.com/ytti/oxidized/blob/master/docs/Configuration.md).
- If you’re looking for hooks (e.g., for notifications or events after configuration changes), go to [docs/hooks.md](https://github.com/ytti/oxidized/blob/master/docs/Hooks.md).
- For information related to outputs (how and where configuration backups are stored), check out [docs/outputs.md](https://github.com/ytti/oxidized/blob/master/docs/Outputs.md).
- If you're working with router.db-related settings (which is often tied to your source configuration), refer to [docs/source.md](https://github.com/ytti/oxidized/blob/master/docs/Sources.md). This is where you define how Oxidized pulls device information (from a file, HTTP, or another system like NetBox).

Each section of the documentation is broken down by feature, so navigate accordingly depending on what you need to configure.

**Comment by ts0818** [comment]
Thank you for your reply.

This question was based on the assumption that there was no list of setting items like the one below.

> https://docs.spring.io/spring-boot/appendix/application-properties/index.html

There was no explanation of each item in the "Oxidized" document that you collaborated with,
I did not know the total number of items that can be set, so I checked.

**Comment by skiera6** [comment]
I'll work on creating YARD documentation that is hopefully better and more comprehensive.

**Comment by ts0818** [comment]
Thank you for your reply.

Thank you for your consideration.
I would appreciate it if you could create a document that even a first-time reader can understand.
