### ISSUE TITLE
Not able to configure Cisco switch SG350-28P 28-Port Gigabit PoE Managed Switch

### ISSUE THREAD

**Issue by zahidshaikh121991** [ytti/oxidized#3277]
I have installed and configured Oxidized backup solution on ubuntu.   I want to add some of the Cisco switches to oxidized. Below is the model of one of the cisco switch

"SG350-28P 28-Port Gigabit PoE Managed Switch"

In config i use os : "ios" .  

I am getting below error messages which running oxidized. 

10.255.249.50 raised Net::SSH::ConnectionTimeout (rescued RuntimeError) with msg "Net::SSH::ConnectionTimeout"
10.255.249.50 raised EOFError (rescued IOError) with msg "end of file reached"

**Comment by robertcheramy** [comment]
You probably need ciscosmb
https://github.com/ytti/oxidized/blob/master/lib/oxidized/model/ciscosmb.rb

**Comment by zahidshaikh121991** [comment]
The Above worked. Thanks for the info
