### ISSUE TITLE
How to determine whether acquisition of configuration information of the target device was successful or failed

### ISSUE THREAD

**Issue by ts0818** [ytti/oxidized#3286]
Is there a way to determine whether Oxidized succeeded or failed in acquiring configuration information from the target device?
I don't understand how errors are handled within Oxidized.
If you have any information on the total number of cases where acquisition fails, please let me know.

Will I need to customize the Oxidized library?

**Comment by robertcheramy** [comment]
You can use oxidized-web, which provide Stats and device status, also with a rest API.
