### ISSUE TITLE
Issue Adding Dell Switch "Dell Networking N2048P" to oxidized

### ISSUE THREAD

**Issue by zahidshaikh121991** [ytti/oxidized#3296]
Issue Adding Dell Switch "Dell Networking N2048P"  to oxidized backup. 

I have installed Oxidized on an "Ubuntu 22.04.1 LTS (Jammy Jellyfish)" . Oxidized version is "0.30.1".  

I am trying to add a dell Switch to oxidized.  Below is the switch details. 

-----------------------------------------------------------

Machine Description............... Dell Networking Switch
System Model ID................... N2048P
Machine Type...................... Dell Networking N2048P

------------------------------------------------------------

I tried using all the dell models ( powerconnect, aosw, dellx, os6, os10 ) . None of them works.   

Can anyone let me know which model will suit best to the above dell device.

**Comment by yoakim** [comment]
Yes, try DNOS

**Comment by zahidshaikh121991** [comment]
@robertcheramy can you look into this please ?

**Comment by robertcheramy** [comment]
Look into the models files an check which one has the commands you would run in your switch.
If none match, you'll have to write a model yourself.

The NoMethodError message you get comes from one of the join in the dnos.rb, but you first need to find out which model matches your Hardware.

**Comment by yoakim** [comment]
Can you write "show version" in your switch and post the output here?

**Comment by zahidshaikh121991** [comment]
SFSW01>show version

Machine Description............... Dell Networking Switch
System Model ID................... N2048P
Machine Type...................... Dell Networking N2048P
Serial Number..................... CN0H3MDW2829862R0048A05
Manufacturer...................... 0xbc00
Burned In MAC Address............. 6400.6AEB.9BB9
System Object ID.................. 1.3.6.1.4.1.674.10895.3056
SOC Version....................... BCM56340_A0
HW Version........................ 5
CPLD Version...................... 13

unit active      backup      current-active next-active
---- ----------- ----------- -------------- --------------
1    6.2.6.6     6.2.6.6     6.2.6.6        6.2.6.6
2    6.2.6.6     6.2.6.6     6.2.6.6        6.2.6.6

**Comment by yoakim** [comment]
It seems from your output that you are not in enabled mode?
Is this the case when oxidized is authenticating aswell?

**Comment by zahidshaikh121991** [comment]
yes that is correct.  After i login to the swtich. I need to first go in enable mode. then the command "show running-config" works

**Comment by zahidshaikh121991** [comment]
So, i am assuming when the oxidized logs in ,  it is not running the commands in enable mode

**Comment by yoakim** [comment]
Do you have your enable password specified in the router.db?

**Comment by zahidshaikh121991** [comment]
no. to login into enable mode in that server, we do not require password.  we just type "enable" and hit enter

**Comment by robertcheramy** [comment]
Set an empty enable variable for the device (supposing you are using dnos):
```
models:
  dnos:
    vars:
      enable: ''
```

**Comment by zahidshaikh121991** [comment]
Setting an empty enable variable worked. Thanks guys..  Closing this thread
