### ISSUE TITLE
Issue with regex to get device specs from "show version" for ASR series router.

### ISSUE THREAD

**Issue by roshnaraman** [ytti/oxidized#3297]
I found a problem with the ios.rb file when getting "Chassis type" and "CPU" for ASR routers.

**Current result:**
```
! Image: Software: PPC_LINUX_IOSD-UNIVERSALK9_NPE-M, 16.8.1b, RELEASE SOFTWARE (fc1)
! Image: Compiled: Sat 14-Apr-18 12:07 by mcpre
! Image: bootflash:/asr920-universalk9_npe.16.08.01b.SPA.bin
! **Chassis type: processor**
! Memory: main 900278K/6147K
! Processor ID: CAT2304V309
! **CPU:** 
! Memory: nvram 32768K
```
**Expected result:**
```
! Image: Software: PPC_LINUX_IOSD-UNIVERSALK9_NPE-M, 16.8.1b, RELEASE SOFTWARE (fc1)
! Image: Compiled: Sat 14-Apr-18 12:07 by mcpre
! Image: bootflash:/asr920-universalk9_npe.16.08.01b.SPA.bin
! **Chassis type: ASR-920-24TZ-M**
! Memory: main 900278K/6147K
! Processor ID: CAT2304V309
! **CPU:  Freescale P2020** 
! Memory: nvram 32768K
```

**Observation:**

This issue is caused by the regex "(\S+(?:\sseries)?)\s+(?:\((**\S+**)\)\s+processor|\(revision[^)]+\)).*\s+with (\S+k) bytes/i" where it expects a single word for processor(highlighted in bold). 
Ref: https://github.com/ytti/oxidized/blob/e794481c8582e08d58b76da590e689d9f35b81f3/lib/oxidized/model/ios.rb#L77C1-L78C1

As for ASR series router there are two words for processor(Freescale P2020)
result returned as below
`cisco ASR-920-24TZ-M (Freescale P2020) processor (revision 1.2 GHz) with 900278K/6147K bytes of memory`

Thanks

**Comment by robertcheramy** [comment]
Could you provide a [YAML-Simulation](https://github.com/ytti/oxidized/blob/master/examples/device-simulation/README.md#creating-a-yaml-file-with-device2yamlrb) file for the device?

Details on how to do it in the link above, the short version is:
```
# Adapt when not using a debian-based distro
sudo apt install git ruby-net-ssh
git clone git@github.com:ytti/oxidized.git
cd oxidized/examples/device-simulation
# Replace user and devicename to appropriate values
./device2yaml.rb user@devicename -c cmdsets/ios -o yaml/asr900_26.8.1b.yaml
```

The script waits 5 seconds between the commands, and outputs what the device returns. You can press "ESC" if you see the prompt and want to pass to next command.

The result will be stored in `oxidized/examples/device-simulation/yaml/asr900_26.8.1b.yaml`. Replace anything you do not want to share with dummy values, and either directly submit a pull request or post it here or directly to me, with the authorisation to include the file of part of in oxidized under the project license.

**Comment by roshnaraman** [comment]
Hi Robert,

As requested I have raised PR https://github.com/ytti/oxidized/pull/3308
with asr router simulation.

Please let me know if I missed anything.

Thanks
Roshna
