### ISSUE TITLE
[question]Naming rules for model class name and model class file name

### ISSUE THREAD

**Issue by ts0818** [ytti/oxidized#3311]
Are there any naming rules for the following?
・model class
・File name of model class

For example, in Java,
Basically, I think Pascal case is used.

I checked the model class of Oxidized, but
The class name is all capital letters, or I don't understand the naming convention.

▼Reference
https://github.com/ytti/oxidized/tree/master/lib/oxidized/model

**Comment by robertcheramy** [comment]
The model is a ruby Class, and should use [CapitalCase](https://rubystyle.guide/#camelcase-classes). The file of the model is written lowercase ([snake_case](https://rubystyle.guide/#snake-case-files) to be precise - you just don't need underscore here.).
