### ISSUE TITLE
Patch to strip additional uptime line in recent version of Nokia SROS md-cli.

### ISSUE THREAD

**Issue by edwinkalle** [ytti/oxidized#3315]
Recent versions of Nokia SROS have an additional "System up time" line in "show system information":

`A:user@nokia# show system information | match "System Up Time"
System Up Time         : 33 days, 19:46:50.24 (hr:min:sec)
System Up Time (64-bit): 33 days, 19:46:50.24 (hr:min:sec)`

patch attached.
[srosmd-uptime.patch](https://github.com/user-attachments/files/17703295/srosmd-uptime.patch)

**Comment by robertcheramy** [comment]
Please provide a [YAML simulation file](https://github.com/ytti/oxidized/blob/master/docs/Issues.md#sumbit-a-yaml-simulation-file) for your device.
```
./device2yaml.rb user@devicename -c cmdsets/srosmd -o yaml/srosmd_HW_SW.yaml
```

**Comment by robertcheramy** [comment]
Please submit a pull request directly or explicit allow me to include the provided device simulation file into oxidized under the project license.
