### ISSUE TITLE
[question]About how to inherit things other than model.rb

### ISSUE THREAD

**Issue by ts0818** [ytti/oxidized#3316]
Regarding how to inherit things other than model.rb,
It's not mentioned in the document, but
Is it possible to inherit something other than model.rb as in the issue below?

https://github.com/ytti/oxidized/issues/2579
https://github.com/ytti/oxidized/issues/3118

If possible, I would like it to be included in the documentation.

https://github.com/ytti/oxidized/blob/master/docs/Creating-Models.md

**Comment by skiera6** [comment]
What is your end goal? It seems more of a ruby programming question than oxidized specific one.

**Comment by ts0818** [comment]
Thank you for your reply.

The fact that it was raised as an issue means that there are people who want to use the method that was raised as an issue.
I thought it would be useful for people who don't have any knowledge of Ruby if it was described in the official documentation.

official reference
https://github.com/ytti/oxidized/blob/master/docs/Creating-Models.md

<h2>Extending an existing another model with a new command</h2>

It is possible to inherit things other than model.rb.

```
require 'oxidized/model/ios.rb'

class IOSExtra < IOS
  using Refinements

  cmd 'show history' do |cfg|
    comment cfg
  end

end
```

**Comment by robertcheramy** [comment]
People who don't have any knowledge of Ruby won't have the idea to inherit from another class. This would only confuse them.

What you ant to do is described here: https://github.com/ytti/oxidized/blob/master/docs/Creating-Models.md#advanced-features
