### ISSUE TITLE
Feature Request: API to pull JSON from https://oxidize.domain.com/nodes?format=json

### ISSUE THREAD

**Issue by G0nz0uk** [ytti/oxidized#3337]
Hello,

A wonderful tool thank you!

We are looking for a way to look a the JSON file at https://oxidize.domain.com/nodes?format=json so we can use this to build a dashboard in Grafana using it's JSON plugin.  I was wondering if there is a way to do this please?

If we can get the JSON output into Grafana on regular intervals we can also alerts on when backups fail etc and show the health status like on the dashboard you created.

Thanks

**Comment by robertcheramy** [comment]
Please read https://github.com/ytti/oxidized/blob/master/docs/Issues.md and submit your issue in oxidized-web.
