### ISSUE TITLE
Accepting a policy banner

### ISSUE THREAD

**Issue by Steve-M-C** [ytti/oxidized#3339]
We've got mandatory policy messages that are displayed before you are allowed to login to our SonicWalls, which means that the SSH session looks like this:
```



Copyright (c) 2024 SonicWall, Inc.



Anyone using this system must abide by XXXXX policies and is hereby notified that all XXXXX systems and activities are monitored.


Accept The Policy Banner (yes)?
yes:
```

After typing "yes" and pressing enter at the "yes:" prompt, it then lets you authenticate with the username and password. I'm not sure how to handle this in the model file?

**Comment by Steve-M-C** [comment]
I i_think_ I've managed to sort it - I've added the following after the prompt config in the sonicos.rb file:

 ```
 expect /yes: / do |data, re|
    send "yes\n"
    data.sub re, ''
  end

```
Is it worth adding that to the official model file? Along with possibly tweaking the "prompt" to accept dashes in the hostname:
`
prompt /^\w+@[\w-]+[>]\(?.+\)?\s?/`

**Comment by robertcheramy** [comment]
I've already updated the prompt in de6b5fd69ba8192d9321ce7bf4ad5ea5b77f1089 .

I think adding the expect would be an added value for other users. In order to avoid false positives, I would match on a longer string than `yes: `, for example (untested):
```
expect /Accept The Policy Banner \(yes\)\?\nyes: $/ do |data, re|
   send "yes\n"
   data.sub re, ''
 end
```
If you try this and it works, I can add it to the model.

**Comment by Steve-M-C** [comment]
> I've already updated the prompt in [de6b5fd](https://github.com/ytti/oxidized/commit/de6b5fd69ba8192d9321ce7bf4ad5ea5b77f1089) .
> 
> I think adding the expect would be an added value for other users. In order to avoid false positives, I would match on a longer string than `yes: `, for example (untested):
> 
> ```
> expect /Accept The Policy Banner \(yes\)\?\nyes: $/ do |data, re|
>    send "yes\n"
>    data.sub re, ''
>  end
> ```
> 
> If you try this and it works, I can add it to the model.

That _almost_ works - I had to add a \r before the "\nyes:" part, which did the trick. So the working version is:

```
expect /Accept The Policy Banner \(yes\)\?\r\nyes: $/ do |data, re|
   send "yes\n"
   data.sub re, ''
 end
```

Thanks for the assist!
