### ISSUE TITLE
Unexpected Prompt Edgeswitch

### ISSUE THREAD

**Issue by jpc2000** [ytti/oxidized#337]
When using oxidized to backup an Edgeswitch, I get this in the error logs:

raised Oxidized::PromptUndetect with msg "
Feb 24 10:40:35 cfms-oxidized oxidized: (accswitch7) > not matching configured prompt (?-mix:[(]\w*\s\w*[)] [\s>]*[\s>])"

We're using the Edgeswitch with an enabled password (as our security policies require us to) but cannot get it to connect via SSH to the edgeswitch. In terms of telnet, we get the following: raised Timeout::Error with msg "timed out while waiting for more data" on a User login prompt.

The current configuration of the edgeswitch model file is:

class EdgeSwitch < Oxidized::Model

# Ubiquiti EdgeSwitch #

  comment '!'

  prompt /[(]\w*\s\w*[)] [\s#>]*[\s#>]/

  cmd 'show running-config' do |cfg|
    comment cfg.each_line.reject { |line| line.match /System Up Time.*/ or line.match /Current SNTP Synchronized Time.*/ }.join
  end

  cfg :telnet do
    username /Username:\s/
    password /^Password:\s/
  end

  cfg :telnet, :ssh  do
    post_login 'enable'
    post_login 'terminal length 0'
    pre_logout 'exit'
    pre_logout 'exit'
  end

Any idea's on what's missing?

**Comment by ytti** [comment]
```prompt /[(]\w\s\w[)] [\s#>]*[\s#>]/```

Looks wonky to me. I think you'll want

```prompt /[()\w-]+\s*[#>]\s*/ or something```

You can play with this in irb:
```
[ytti@lintukoto ~]% irb
irb(main):001:0> prompt = '(accswitch7)'
=> "(accswitch7)"
irb(main):002:0> prompt.match /regexp/
=> nil
irb(main):003:0>
```

**Comment by ytti** [comment]
Is this still relevant?

**Comment by ytti** [comment]
Closing due inactivity, please reopen if needed.
