### ISSUE TITLE
Alcatel OmniStack LS 6200

### ISSUE THREAD

**Issue by pitoganzado** [ytti/oxidized#346]
Hi, i'm having issues connecting to the switchs Alcatel OmniStack LS 6200, this switchs dont allow username in the remote access :| 

**oxs -m aos -d -v -p blablabla --protocols telnet 1.1.1.9 sh config**

**timed out while waiting for more data**
/usr/local/rvm/gems/ruby-2.1.2/gems/oxidized-0.12.2/lib/oxidized/input/telnet.rb:108:in `waitfor': timed out while waiting for more data (Timeout::Error)
        from /usr/local/rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/net/telnet.rb:696:in `cmd'
        from /usr/local/rvm/gems/ruby-2.1.2/gems/oxidized-0.12.2/lib/oxidized/input/telnet.rb:44:in `cmd'
        from /usr/local/rvm/gems/ruby-2.1.2/gems/oxidized-0.12.2/lib/oxidized/model/model.rb:82:in `cmd'
        from /usr/local/rvm/gems/ruby-2.1.2/gems/oxidized-script-0.1.2/lib/oxidized/script/script.rb:22:in `cmd'
        from /usr/local/rvm/gems/ruby-2.1.2/gems/oxidized-script-0.1.2/lib/oxidized/script/cli.rb:16:in `run'
        from /usr/local/rvm/gems/ruby-2.1.2/gems/oxidized-script-0.1.2/bin/oxs:5:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.1.2/bin/oxs:23:in `load'
        from /usr/local/rvm/gems/ruby-2.1.2/bin/oxs:23:in `<main>'
        from /usr/local/rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
        from /usr/local/rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'

Telnet LOG i see this:

Connected to 1.1.1.9 .

Password:**
Password:

any tips to solve this?

**Comment by ytti** [comment]
If you don't pass the node 'username' it won't expect 'username' prompt. As some 'source' may have difficulty of passing non-truthy values also empty string is considered as no username.

**Comment by pitoganzado** [comment]
I already try the empty string in the username field, but same error happens

**Comment by ytti** [comment]
is it possible to arrange login to a device? (potentially with sensitive config removed)

**Comment by pitoganzado** [comment]
Problem solved, i use the "powerconnect" from DELL and after a couple of small changes is working now with Alcatel OmniStack LS 6200 :+1: 
Thank you!

**Comment by optimuscream** [comment]
Sorry for necrobump the thread , but can you share the changes for the model ? . I have the same issue.
Thank you.
