### ISSUE TITLE
Gems update failing

### ISSUE THREAD

**Issue by DervMan** [ytti/oxidized#349]
When trying to perform an update to oxidized, which has always worked in the past, I'm getting this error. Any suggestions on how to fix?

# gem update
Updating installed gems
Updating net-ssh
ERROR:  Error installing net-ssh:
        net-ssh requires Ruby version >= 2.0.
Updating slop
ERROR:  Error installing slop:
        slop requires Ruby version >= 2.0.0.
Nothing to update

**Comment by ytti** [comment]
You will now need ruby 2.0 or newer. Ruby 1.9 has been EOL for bit over a year now.

RHEL, CentOS, OSX, Debian, Ubuntu all ship with 2.0 or newer.

**Comment by ytti** [comment]
I assume answer is satisfactory, if not please reopen.

**Comment by infotek** [comment]
using:
Ubuntu 14.04.5 LTS, Trusty Tahr
error when running "gem install oxidized"

net-ssh requires Ruby version >= 2.0

fix:

apt install ruby2.0 ruby2.0-dev rubygems-integration

ln -fs /usr/bin/erb2.0 /usr/bin/erb
ln -fs /usr/bin/rdoc2.0 /usr/bin/rdoc
ln -fs /usr/bin/ri2.0 /usr/bin/ri
ln -fs /usr/bin/ruby2.0 /usr/bin/ruby
ln -fs /usr/bin/testrb2.0 /usr/bin/testrb
ln -fs /usr/bin/gem2.0 /usr/bin/gem

rerun "gem install oxidized"

**Comment by ytti** [comment]
You erally don't need those symbolic links, in fact it sounds dangerous.

If you have multiple rubies installed, you should use the correct 'gem' name to install oxidized I.e.i your 'gem' is 1.8, and 'gem20' is 2.0,then 'gem20 install oxidized' will install it right.

Other option is to just remove older ruby, dpkg --purge, which is what you should have done.
