### ISSUE TITLE
Help with remote repo

### ISSUE THREAD

**Issue by melliott-sis** [ytti/oxidized#350]
Hello.  I'm new to oxidized.  I've got a test setup working and can backup to file.  I've tried to setup the hook for a remote git repo and I'm getting an error.  I've installed the rugged gem and a few others (below).  I'm sure I'm missing something obvious but ruby is not my forte.  Any help is greatly appreciated!

Version:
```
#oxidized -v
0.12.2
```

Hooks config:

```
hooks:
  push_to_remote:
    type: githubrepo
    events: [node_success, post_store]
    remote_repo: git@github.com:snip/snip.git
```

Logs:
```
I, [2016-02-26T21:27:48.048262 #69823]  INFO -- : Oxidized starting, running as pid 69823
I, [2016-02-26T21:27:48.165515 #69823]  INFO -- : Loaded 1 nodes
E, [2016-02-26T21:27:51.570607 #69823] ERROR -- : Hook push_to_remote (#<GithubRepo:0x007f1d8ca71128>) failed (#<NameError: uninitialized constant GithubRepo::Rugged>) for event :node_success
I, [2016-02-26T21:27:51.571674 #69823]  INFO -- : Configuration updated for /test-switch
E, [2016-02-26T21:27:51.575164 #69823] ERROR -- : Hook push_to_remote (#<GithubRepo:0x007f1d8ca70c28>) failed (#<NameError: uninitialized constant GithubRepo::Rugged>) for event :post_store
```

Installed gems:

```
# gem list

*** LOCAL GEMS ***

asetus (0.3.0)
backports (3.6.8)
bigdecimal (1.2.3)
clipboard (1.0.6)
commander (4.1.6)
emk-sinatra-url-for (0.2.1)
githubrepo (0.3.0)
haml (4.0.7)
highline (1.6.21)
httparty (0.13.7)
io-console (0.4.2)
json (1.8.1)
json_pure (1.8.3)
minitest (4.7.5)
multi_json (1.11.2)
multi_xml (0.5.5)
net-ssh (3.0.2)
os (0.9.6)
oxidized (0.12.2)
oxidized-script (0.1.2)
oxidized-web (0.6.1)
psych (2.0.2)
puma (2.16.0)
rack (1.6.4)
rack-protection (1.5.3)
rack-test (0.6.3)
rake (10.1.0)
rdoc (4.1.0)
rugged (0.23.3)
sass (3.4.21)
sinatra (1.4.7)
sinatra-contrib (1.4.6)
slop (3.6.0)
test-unit (2.1.0.0)
tilt (2.0.2)
```

**Comment by ytti** [comment]
It looks like 'rugged' is not loaded at all, if you don't have output git configured.

I'm not sure if this is intentional or not. @ElvinEfendi can comment. But for now, quick fix would be to enable output for git.

**Comment by ElvinEfendi** [comment]
`githubrepo` hook(also `rugged`) requires you to use `git` as the output, it does not know what to do when the output is not `git`. I think we can use https://developer.github.com/v3/repos/contents/#create-a-file to upload files to a repository when the output type is `file`. But I'm not planning to implement this in near future. Patches are welcome though :)

**Comment by wylieswanson** [comment]
Just adding that I have the same issue, and would love to store to one of my private remote repos in this way.

**Comment by melliott-sis** [comment]
Thanks for the help.  I think I'm getting closer.  I'm getting a different error now. Debug logs below

```
I, [2016-02-29T18:14:47.932637 #119697]  INFO -- : Oxidized starting, running as pid 119697
D, [2016-02-29T18:14:47.949436 #119697] DEBUG -- : Hook "write_log_for_failed_nodes" registered Exec for event :node_fail
D, [2016-02-29T18:14:47.949679 #119697] DEBUG -- : Hook "write_log_for_store_operations_nodes" registered Exec for event :post_store
D, [2016-02-29T18:14:47.952348 #119697] DEBUG -- : Hook "push_to_remote" registered GithubRepo for event :node_success
D, [2016-02-29T18:14:47.952456 #119697] DEBUG -- : Hook "push_to_remote" registered GithubRepo for event :post_store
I, [2016-02-29T18:14:48.076774 #119697]  INFO -- : Loaded 1 nodes
D, [2016-02-29T18:14:48.477641 #119697] DEBUG -- : Jobs 0, Want: 1
D, [2016-02-29T18:14:49.779800 #119697] DEBUG -- : SSH: terminal length 0 @ snip
D, [2016-02-29T18:14:50.182231 #119697] DEBUG -- : SSH: show version @ snip
D, [2016-02-29T18:14:50.585204 #119697] DEBUG -- : SSH: show inventory @ snip
D, [2016-02-29T18:14:50.987995 #119697] DEBUG -- : SSH: show running-config @ snip
D, [2016-02-29T18:14:51.398484 #119697] DEBUG -- : SSH: exit @ snip
I, [2016-02-29T18:14:51.479653 #119697]  INFO -- : GithubRepo: Pushing local repository(/etc/oxidized/git/configs.git/)...
E, [2016-02-29T18:14:51.479982 #119697] ERROR -- : Hook push_to_remote (#<GithubRepo:0x007ffae65bccd0>) failed (#<TypeError: wrong argument type Asetus::ConfigStruct (expected String)>) for event :node_success
```

**Comment by danilopopeye** [comment]
#<TypeError: wrong argument type Asetus::ConfigStruct (expected String)>

@melliott-sis can you post you config?

**Comment by melliott-sis** [comment]
I did have a misconfiguration.  When I was experimenting, I had changed the config from what I had originally posted above.  Reverting back to that resolved the string error.  I am still having some issues authenticating.  I've got ssh_agent running and I am able to authenticate to github with ssh -T git@github.com.  

If I leave out any authentication (which should use ssh-agent?), I get this error:
`Hook push_to_remote (#<GithubRepo:0x007f8f8a79ed40>) failed (#<Rugged::SshError: error authenticating: no auth sock variable>) for event :node_success`

Specifying a publickey/privatekey produces:
`Hook push_to_remote (#<GithubRepo:0x007fa6b3deb258>) failed (#<Rugged::SshError: Failed to authenticate SSH session: Callback returned error>) for event :node_success`
I know the keys are good though. :disappointed: 

Username/password gives me:
`Hook push_to_remote (#<GithubRepo:0x007f38b896e4f0>) failed (#<ArgumentError: Invalid credential type>) for event :node_success`

I know this isn't necessarily a support forum so I can post these questions elsewhere if that is preferred.  Just let me know.

**Comment by ElvinEfendi** [comment]
> events: [node_success, post_store]

Why do you trigger it twice? Githubrepo hook should be called after `post_store` only

**Comment by melliott-sis** [comment]
Because I was copying someone else's work off of a blog post :)
I'll make the change and let you know if it resolves the issue.

**Comment by melliott-sis** [comment]
Same problems unfortunately.  I'll poke around in rugged support.  It looks like my problem lies there, not with oxidized.

**Comment by ytti** [comment]
In the original query, the problem is that rugged isn't even loaded, which implies git output isn't configured. If git is configured, this message should not occur, if it does, it's not rugged problem, it's problem of rugged not being loaded.

**Comment by melliott-sis** [comment]
Just as a sanity check I set everything up on a different server and got it working without much trouble.  I think there is something wrong on the original server I was working on.

**Comment by alarig** [comment]
Hello,

I have the same issue. I’m not using git but gitcrypt.

**Comment by GennadySpb** [comment]
For those looking how to resolve `NameError: uninitialized constant GithubRepo::Rugged` on triggering **githubrepo** hook:
you should use `output: git` (not `output: file`). This will trigger load ruby gem Rugged on oxidized startup/loading stage.

For details check https://github.com/ytti/oxidized/blob/master/docs/Outputs.md#output-git & https://github.com/ytti/oxidized/blob/master/docs/Outputs.md#output-file
