### ISSUE TITLE
Procurve prompt

### ISSUE THREAD

**Issue by Ultra2D** [ytti/oxidized#356]
The following code in lib/oxidized/model/procurve.rb could be improved.

    # FIXME: this is way too unsafe
    prompt /.*?(\w+# ).*/m

Unfortunately, I could not find a way to force the type of terminal to 'none' in stead of the default 'vt100' for a single session. Setting it to 'none' permanently would work, but that will make managing the switch (directly) very hard. So we're stuck with control characters.

The following line does not filter out all possible control characters, but does work for me on HP Procurve 2510/2610/2900/2910/3800/5400:

    prompt /(\e\[\??\d+(;\d+)*[A-Za-z]?)+([\w.-]+[#>] )(\e\[\??\d+(;\d+)*[A-Za-z]?)+$/

It does not start matching from the beginning of the line, because the output actually includes the previous input (which seems to be split by control characters every 10 characters).

The control characters do not end up in the saved config files, so the best way might be to save the output to a temporary file, and parse that file (or use some shortcut that achieves the same).

**Comment by ytti** [comment]
Does it fix any particular issue? I'm hesitant to introduce complex regexp magic.

Is 'none' valid terminal type? We could send that in SSH, does HP honour that?

**Comment by Ultra2D** [comment]
The current regexp does work, but it is very broad. You will only run into problems when using the pattern in an option that allows spaces (e.g. motd, contact, RADIUS key).

'none' is valid as a config option, but I don't think you can request it.
> \# console terminal
 ansi                  uses ANSI terminal escape sequences.
 none                   uses a raw mode with no terminal escape sequences.
 vt100                 uses VT100 terminal escape sequences.

This does not work:
> TERM=none ssh user@switch
TERM=ansi ssh user@switch

The regexp could be a lot simpler if the control sequences are filtered first. For example, after modifying lib/oxidized/input/ssh.rb as below the debug log is free of them (except `^[E` after each command entered):

            #@log.print data
            @log.print data.gsub(/\e\[\??\d+(;\d+)*[A-Za-z]/, '')

Note that I removed the final `?`.

**Comment by ytti** [comment]
We currently force vt100 in our SSH, but we could force 'none' if that is something common and not HP invention. However of course if HP does not honour SSH sent term anyhow, then it does not matter.

We could add some sort of input_filter in config :ssh, :telnet, where if input_filter is set, then that input_filter is ran before storing data read from input. So then in HP model we could configure that regex as input_filter.

**Comment by Ultra2D** [comment]
HP does not honour SSH sent term as far as I can tell. My test was directly from shell. Changing 'vt100' to 'none' in lib/oxidized/input/ssh.rb does not work either.

input_filter sounds great. Don't you mean output_filter though? And shouldn't it run on all data read? It's "before storing data" that is throwing me off, that would mean it might not help detecting the prompt, as that data does not have to be stored.

**Comment by ytti** [comment]
I mean input_filter as in, filter applied to the 'input' (which is telnet, ssh, ftp...). And yes, we should run it before any prompt detect or anything is done. 

Infact I think we can already do this today with 'expect' in the model, it's done before prompt detection or anything in SSH, so if we expect for control-keys and return string without them, it maybe should do what you want it to do.

**Comment by Ultra2D** [comment]
I'm a bit out of my depth here. You mean add something like below to procurve.rb ? I just copied that from another file and added the regexp, so I could be way off. Also, it does not seem to work.

    expect /\e\[\??\d+(;\d+)*[A-Za-z]/ do |data, re|
      send ' '
      data.sub re, ''
    end

**Comment by ytti** [comment]
You don't need to send anything in this example, but otherwise I think it should have worked. Unsure why it didn't.

**Comment by Ultra2D** [comment]
Now I see, should use gsub:

    expect /\e\[\??\d+(;\d+)*[A-Za-z]/ do |data, re|
      data.gsub re, ''
    end

As mentioned before, the previous command is repeated in the output and could end up on the final line.The command is followed by "\eE". This gives two possibilities to match the prompt:

    prompt /^\r?([\w -]+\eE)?([\w-]+# )$/ #full
    prompt /([\w-]+# )$/ #short

The short version will match `E<hostname> #` after the `no page` command (at least).
"\r?" is needed for 2510 and 2610 (at least).

I would prefer the full version. And please let me know if I should create a pull request.

**Comment by ytti** [comment]
Unfortunately I don't have procurve to test, and I don't see any other committers in the file who could help. So you're on your own on this one :)

I'm happy to accept it, I think it likely makes it safer, but of course with regexps there always are dragons, but we'll cross that bridge when we come to it.

I also think the full is better option.
