### ISSUE TITLE
F5/TMOS secrets and -q option for tmsh

### ISSUE THREAD

**Issue by colin-stubbs** [ytti/oxidized#359]
tmos.rb does not filter out "privacy-password-encrypted" secrets which also change regularly every time the config is pulled.

tmsh commands do not use the -q argument, which avoids situations in which prompts may stall the command.

e.g. 

[colinstubbs.adm@bigip01:Standby:Changes Pending] ~ # tmsh -h
usage: tmsh <options ...> <command>
  An option may be specified once. A command may follow the options, in
  which case the shell exits after executing the command.
  -a do not update the command history file
  -c run a command, a command with multiple arguments must be in quotes,
     this must be the last option specified
  -d <address or host name> connect to mcpd at the specified location
  -e disable video effects (bold, color, ...)
  -f allow saving configuration on secondary slot in cluster environment
  -g don't check mcpd phase when saving configuration
  -h show this list
  -l run as a login shell, job control is disabled, not valid with a command
  -m all messages sent to and received from mcpd to tmsh.out
  -q the shell will not ask the user any questions, this option does not
     have an affect in interactive mode
  -r <version> run TMSH syntax in the specified version.
  -s print debug information for statistics commands to tmsh.out
  -v print current TMSH version
[colinstubbs.adm@bigip01:Standby:Changes Pending] ~ #

Suggest the attached patch.
[oxidize_tmos.txt](https://github.com/ytti/oxidized/files/164597/oxidize_tmos.txt)

**Comment by ytti** [comment]
Sure send pull request with proposed change, looks good to me.

**Comment by ytti** [comment]
ping, can you send pull request?

**Comment by ytti** [comment]
This was solved in a PR.
