### ISSUE TITLE
Issue trying to connect and no_connection error

### ISSUE THREAD

**Issue by chris-gibbs** [ytti/oxidized#360]
[edit] deleted, not related to enable variable in config. [/edit]

**Comment by chris-gibbs** [comment]
Looks like I jumped the gun. It doesn't seem to be related to the enable variable.

Happening for multiple nodes. Sometimes it connects and other times errors out with (only one node show but happening to multiple nodes.

D, [2016-03-09T21:35:05.751002 #15463] DEBUG -- : 10.50.0.104 raised Net::SSH::Disconnect with msg "connection closed by remote host"
W, [2016-03-09T21:35:06.650225 #15463]  WARN -- : rtr1 status no_connection, retry attempt 1
D, [2016-03-09T21:35:06.650349 #15463] DEBUG -- : Jobs 0, Want: 1
D, [2016-03-09T21:36:06.770653 #15463] DEBUG -- : 10.50.0.104 raised Net::SSH::Disconnect with msg "connection closed by remote host"
W, [2016-03-09T21:36:07.663458 #15463]  WARN -- : rtr1 status no_connection, retry attempt 2
D, [2016-03-09T21:36:07.663577 #15463] DEBUG -- : Jobs 0, Want: 1
D, [2016-03-09T21:37:07.810243 #15463] DEBUG -- : 10.50.0.104 raised Net::SSH::Disconnect with msg "connection closed by remote host"
W, [2016-03-09T21:37:08.676543 #15463]  WARN -- : rtr1 status no_connection, retry attempt 3
D, [2016-03-09T21:37:08.676704 #15463] DEBUG -- : Jobs 0, Want: 1

Same thing happening using oxs.

No issues using SSH from command line to these routers and switches.

**Comment by chris-gibbs** [comment]
Looks like might be related to 

https://github.com/net-ssh/net-ssh/issues/93

**Comment by ytti** [comment]
Would it be possible to have sanitised device remotely available to recreate the problem locally?

**Comment by chris-gibbs** [comment]
Found a stack trace in a couple of crash reports showing that gem had pulled down a beta of net-ssh. 

Uninstalled and installed version 3.0.2. Seems to have fixed the issue but might pop up again when net-ssh-3.1.0 is released.

2016-03-13 01:21:04 UTC
undefined local variable or method `options' for #<Net::SSH::HostKeys:0x00000001d14768> [NameError]
--------------------------------------------------
/var/lib/gems/2.1.0/gems/net-ssh-3.1.0.beta3/lib/net/ssh/known_hosts.rb:20:in `add_host_key'
/var/lib/gems/2.1.0/gems/net-ssh-3.1.0.beta3/lib/net/ssh/verifiers/secure.rb:46:in `block in process_cache_miss'
/var/lib/gems/2.1.0/gems/net-ssh-3.1.0.beta3/lib/net/ssh/errors.rb:87:in `call'
/var/lib/gems/2.1.0/gems/net-ssh-3.1.0.beta3/lib/net/ssh/errors.rb:87:in `remember_host!'
/var/lib/gems/2.1.0/gems/net-ssh-3.1.0.beta3/lib/net/ssh/verifiers/strict.rb:18:in `rescue in verify'
/var/lib/gems/2.1.0/gems/net-ssh-3.1.0.beta3/lib/net/ssh/verifiers/strict.rb:15:in `verify'
/var/lib/gems/2.1.0/gems/net-ssh-3.1.0.beta3/lib/net/ssh/verifiers/lenient.rb:15:in `verify'
/var/lib/gems/2.1.0/gems/net-ssh-3.1.0.beta3/lib/net/ssh/transport/kex/diffie_hellman_group1_sha1.rb:173:in `verify_server_key'
/var/lib/gems/2.1.0/gems/net-ssh-3.1.0.beta3/lib/net/ssh/transport/kex/diffie_hellman_group1_sha1.rb:68:in `exchange_keys'
/var/lib/gems/2.1.0/gems/net-ssh-3.1.0.beta3/lib/net/ssh/transport/algorithms.rb:363:in `exchange_keys'
/var/lib/gems/2.1.0/gems/net-ssh-3.1.0.beta3/lib/net/ssh/transport/algorithms.rb:200:in `proceed!'
/var/lib/gems/2.1.0/gems/net-ssh-3.1.0.beta3/lib/net/ssh/transport/algorithms.rb:191:in `send_kexinit'
/var/lib/gems/2.1.0/gems/net-ssh-3.1.0.beta3/lib/net/ssh/transport/algorithms.rb:146:in `accept_kexinit'
/var/lib/gems/2.1.0/gems/net-ssh-3.1.0.beta3/lib/net/ssh/transport/session.rb:209:in `block in poll_message'
/var/lib/gems/2.1.0/gems/net-ssh-3.1.0.beta3/lib/net/ssh/transport/session.rb:187:in `loop'
/var/lib/gems/2.1.0/gems/net-ssh-3.1.0.beta3/lib/net/ssh/transport/session.rb:187:in `poll_message'
/var/lib/gems/2.1.0/gems/net-ssh-3.1.0.beta3/lib/net/ssh/transport/session.rb:224:in `block in wait'
/var/lib/gems/2.1.0/gems/net-ssh-3.1.0.beta3/lib/net/ssh/transport/session.rb:222:in `loop'
/var/lib/gems/2.1.0/gems/net-ssh-3.1.0.beta3/lib/net/ssh/transport/session.rb:222:in `wait'
/var/lib/gems/2.1.0/gems/net-ssh-3.1.0.beta3/lib/net/ssh/transport/session.rb:87:in `initialize'
/var/lib/gems/2.1.0/gems/net-ssh-3.1.0.beta3/lib/net/ssh.rb:228:in `new'
/var/lib/gems/2.1.0/gems/net-ssh-3.1.0.beta3/lib/net/ssh.rb:228:in `start'
/var/lib/gems/2.1.0/gems/oxidized-0.12.2/lib/oxidized/input/ssh.rb:29:in `connect'
/var/lib/gems/2.1.0/gems/oxidized-0.12.2/lib/oxidized/node.rb:61:in `run_input'
/var/lib/gems/2.1.0/gems/oxidized-0.12.2/lib/oxidized/node.rb:40:in `block in run'
/var/lib/gems/2.1.0/gems/oxidized-0.12.2/lib/oxidized/node.rb:35:in `each'
/var/lib/gems/2.1.0/gems/oxidized-0.12.2/lib/oxidized/node.rb:35:in `run'
/var/lib/gems/2.1.0/gems/oxidized-0.12.2/lib/oxidized/job.rb:8:in `block in initialize'

**Comment by ytti** [comment]
Hmmm that is strange, it shouldn't pull unreleased versions. It does not immediately look like Oxidised issue, but we will definitely support running on 3.1.0 once it is out. Thanks for the heads up.

**Comment by stevejbauer** [comment]
I have started seeing this issue as well running with ruby 2.3, net-ssh 3.1.1.  When doing a netstat -na to look at the connection table, one can see that there is a ssh connection to the switch.  The other really interesting part is that this setup works correctly when talking to our HP procurve switches.  It only seems to be failing on the cisco switches.

I have enabled debug mode and will post more information when I get some.

**Comment by stevejbauer** [comment]
After doing some more testing on this in debug mode, it appears that when a person uses ssh, it does not acknowledge that it has made the connection to a cisco switch.  This is oxidized version 0.13.1 using net-ssh version 3.1.1.  If I configure the cisco switch to only support telnet, then it works fine.  Let me know if there is something else that you would like me to try.

**Comment by ytti** [comment]
Is it possible to have sanitised device setup against which I can test?

**Comment by stevejbauer** [comment]
Are you looking for an oxidized setup that you could test against some cisco hardware?

**Comment by ytti** [comment]
Any box where failure is reproducible easily and config is non-discrete.

**Comment by slinderud** [comment]
Hey,

I solved this issue by downgrading net-ssh to 3.0.1:
gem install net-ssh -v 3.0.1

Could you try this and report back? Might have to uninstall net-ssh 3.1.1 first

**Comment by ytti** [comment]
For now we can make our dependencies more strict. Currently we state we want 3.0 at least 3.0.2, but any newer 3.x is OK.

I can change that so that it must be 3.0.2 exactly until upstream have solved their issue.

**Comment by stevejbauer** [comment]
So far net-ssh version 3.0.2 appears to be working fine with Ruby 2.3.

**Comment by fonzinc** [comment]
I can also confirm that downgrading net-ssh from 3.1.1 to 3.0.2 has resolved the issue I was seeing. Might be a good idea to hold the version at 3.0.2 until upstream is fixed.

**Comment by wiad** [comment]
I was having this problem to with net-ssh 3.1.1. Downgrading to 3.0.2 seem to work flawlessly.

**Comment by bartdebruijn** [comment]
I'm still having this issue when trying to connect to Cisco boxes. Junipers work fine.

**Comment by papatango71** [comment]
bartdebruijn... checking to see if you are still having issues or not... If not, what did you do to correct the issue..??  

Thank you.

-Patrick
