### ISSUE TITLE
Document remove secret

### ISSUE THREAD

**Issue by Ultra2D** [ytti/oxidized#362]
It took me some effort to figure out how to enable the remove secret feature ("remove_secret" appears only once in the repository). Could not hurt to document it.

**Comment by ytti** [comment]
Pull requests for README.md accepted :)

**Comment by ytti** [comment]
I personally reaaally dislike the feature, but implemented it as many want it. I don't understand value of config backups which can't be used to restore the configs.
I guess companies why use it, generate 100% of configs from systems, and thus never actually use configs to restore devices. Good for them actually :/

**Comment by Ultra2D** [comment]
Ok, didn't know about that. I stumbled upon the feature, figured it would be easy to add for the Procurve model, and had to enable it to test it.

**Comment by ytti** [comment]
I will happily accept better docs for the feature, even though I don't like it, it does not mean it's not useful.
