### ISSUE TITLE
Vyos support

### ISSUE THREAD

**Issue by sliddjur** [ytti/oxidized#364]
Hello, it would be nice to have vyos support in oxidized

**Comment by ytti** [comment]
https://github.com/ytti/oxidized/blob/master/lib/oxidized/model/vyatta.rb

Is it this?

**Comment by ytti** [comment]
That may be misnamed, if the real name is vyos.

**Comment by sliddjur** [comment]
E, [2016-03-21T14:42:40.066711 #11618] ERROR -- : node {:name=>"vyosrouter.example.com", :model=>"vyos", :group=>nil} raised Oxidized::ModelNotFound with message 'vyos not found for node 1.2.3.4'

Fed from librenms source.

Vyos and Vyatta are two different OSes

**Comment by ytti** [comment]
Are you sure? What if you map to vyos to vyatta, that does not produce working results?

If so, if they are different, we can surely create model for it, but we'll need access to one of such device.

**Comment by laf** [comment]
vyos is a fork of vyatta (I use neither) but I would have thought the vyatta model would work fine for vyos.

**Comment by sliddjur** [comment]
@ytti thanks this worked
```
model_map:
  vyos: vyatta
```
@laf also edgeos model file is exactly the same as vyatta

thanks for the help
