### ISSUE TITLE
Push local repo to AWS Codecommit.

### ISSUE THREAD

**Issue by KevinG9012** [ytti/oxidized#365]
I'm trying to get my local repo to push to our AWS Codecommit remote repo. I thought that using the GitHubRepo push hook post_store would work. I'm attempting to get it to work via SSH but am receiving an Error "Hook push_to_remote (#<GithubRepo:0x00000002741330>) failed (#<ArgumentError: Invalid credential type>) for event :post_store"

I can connect to the repo manually using SSH no problem. I'm wondering what is being asked for in the "publickey" for authentication? Do I paste the entire public key? Any information or ideas on how to get this working would be appreciated. I've also tried to just do a post_store where I call a script to push to the remote repo which didn't work. Also, I'm running this in Docker.

**Comment by KevinG9012** [comment]
Now I'm receiving this error when it attempts to push.

Hook push_to_remote (#<GithubRepo:0x000000027cd3a8>) failed (#<Rugged::ReferenceError: Cannot push non-fastforwardable reference>) for event :post_store

**Comment by KevinG9012** [comment]
I switched to SSH and was able to get it working. Instead of using the githubrepo hook I just used a [post_store] and in the command did 'git --git-dir /path/to/git/repo/here/.git push'. Leaving this comment in case anyone else has issues.

**Comment by ytti** [comment]
Sorry I missed this, I don't personally use the hook, so one option to get attention of authors is to use @ytti based on what you see on commits of the file. Happy you were able to find a workaround.

**Comment by ElvinEfendi** [comment]
@KevinG9012 can you post the GitHubRepo hook config you have?

**Comment by KevinG9012** [comment]
This is what I'm currently using

hooks:
   push_to_remote:
     type: exec
     events: [post_store]
     cmd: 'git --git-dir /tmp/repository/.git push'

Previously I was trying to use the GitHubRepo hook with CodeCommit. It looked like it was able to connect once but consistently had errors that wouldn't allow me to push anything. It said that the local repo was ahead and wouldn't push. I tried multiple setups  with the GitHubRepo, using no username, putting the AWS SSH Key ID for the public key actually seemed to be the only way to get it to even connect once. I tried putting the filepath to the Codecommit credentials in the publickey. I tried just putting the full publickey there. Many different approaches. I know it's made for github, I was just trying to see if I could get it to work for Codecommit.

hooks:
  push_to_remote:
    type: githubrepo
    events: [post_store]
    remote_repo: git-codecommit.us-east-1.amazonawsexample.com
    publickey:

**Comment by ElvinEfendi** [comment]
@KevinG9012 I think it's just not-so-ideal naming. It should actually work with any git repository.
> It said that the local repo was ahead and wouldn't push.

Yes, that's a constraint put by this hook. It can not handle the situation when remote is ahead of local repo. If you first do `git clone` or `git pull` manually in the local repo to sync it with remote then GithubRepo hook will work.

**Comment by KevinG9012** [comment]
The remote should not have been ahead of this though. I'm trying to find the exact error it threw, it had to do with a scenario where someone else was making changes to the repo and mine was behind so it would overwrite theirs. I'm using oxidized to pull configs from F5's in AWS. Then I'm having Oxidized push them to a repo on Codecommit. There's nothing else using the repo that would have made changes to it. That's what I was thinking, that it should work just fine with any git repository.
