### ISSUE TITLE
Request to add support for Netonix switches

### ISSUE THREAD

**Issue by gr0mit1** [ytti/oxidized#366]
I would like to manage Netonix switches using Oxidized.

The config is in a .json file, accessable via ssh according to the following commands:

cmdline
cat config.json
exit

The "exit" gets you back to the CLI.

Any chance of taking a look at this?  I'm happy to make available a switch for testing on a public IP if anyone wants to have a crack.  i've tried doing it myself but have not managed to get it working!

**Comment by ytti** [comment]
I'll take crack at it. You can send access details to saku@ytti.fi hopefully will have time no later than weekend.
