### ISSUE TITLE
Very High CPU

### ISSUE THREAD

**Issue by PENorris** [ytti/oxidized#369]
Upgraded from .10 to .12 on Ubuntu 14.04 as well as pulling Ruby 2.0.  Config and routers.db files are identical, but CPU usage on oxidized is racing the CPU until it's run is complete.  Debug and logs show nothing out of the ordinary.  

How can I troubleshoot the cause of this?

**Comment by ytti** [comment]
I'm having difficulties pointing any culprit.

One thing that touches scheduling is:
https://github.com/ytti/oxidized/pull/289

But it looks sensible to me. But still, best option I can come up with.

Could you try to revert this:
https://github.com/ytti/oxidized/pull/289/files?diff=unified

Try reverting the sort first, just remove that line, see if it helps, if not revert jobs.rb too. To me jobs.rb change definitely looks good, and fixes what is essentially a bug. But then again it would be most logical explanation.

**Comment by ytti** [comment]
If you can try also just change #ceil back to #to_i - nothing else  than just this.

Also it would be nice to see your output during run with debug on. Like how many threads are running and how many is it wanting.

**Comment by PENorris** [comment]
I apologize, the original version was .9 if that changes your answer. I've tried with 4 threads and 1 thread and the result is the same.  I'm going to try your suggestions now.

**Comment by ytti** [comment]
There was LOT of changes between 0.9.0 and 0.10.0. If the #289 reversion does not help it, it would be super helpful if you'd install specific versions with 'gem' and tell which is last that works and first that does not work.

**Comment by PENorris** [comment]
#289 didn't resolve.  I'll work through the revisions

**Comment by PENorris** [comment]
This appears to be some ruby 2+ specific issue.  I've reverted to 0.9.0 and it still persists.  Moving back to ruby 1.9 resolves it.  Unless you have any suggestions on that front, feel free to close.

**Comment by ytti** [comment]
Which specific ruby version for sake of posterity. It should work and we prefer ruby 2.  This is up-to-date ruby2.0 in ubuntu 14.04?

**Comment by PENorris** [comment]
Yes, the 2.0.0.484-1ubuntu2.2 version in 14.04.

**Comment by ytti** [comment]
Might be ruby specific issue, if you're at all willing, you can try with other versions

curl -sSL https://get.rvm.io | bash -s stable
rvm install 2.0
gem install oxidized
rvm install 2.1
gem install oxidized
rvm install 2.2
gem install oxidized

 If it works on 2.0 already, then probably no point trying others, then it's just some patch release problem.

**Comment by PENorris** [comment]
I haven't had time to revisit this until now.  I can tell you though, that certain types of devices cause the CPU race condition.  A cisco 3560 is fine, but for some reason a 2960x will cause it.  I can enter 100 switches fine but if I enter only 1 2960x or 1 2911 router, it causes a race.  Are there no debugs I can get about this?

**Comment by ytti** [comment]
Can you give me access to single device which causes the high cpu?

**Comment by PENorris** [comment]
Give me a day or two to get time to do this.  This is a government installation, so I'll need to put one in a DMZ for you.

**Comment by PENorris** [comment]
This has been resolved by moving to HTTP source from csv.  It could be related to my indentation in config that caused #424  as well. Up to date on 0.14.2 now. 
 Closing, thanks again for the assistance.

**Comment by dineshdil** [comment]
I have installed oxidized and configured for 17 nodes but its eating high CPU and taking a long time even to attempts for backup. I tried with 3 nodes also but the same problem.

oxidized -v
0.20.0
ruby -v
ruby 2.2.6p396 (2016-11-15 revision 56800) [x86_64-linux]

I have tried with ruby 1.9, 2.0 2.1 but same problem.

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
15566 oxidized  20   0 1079.2m  64.7m   4.7m S 100.3  0.4  21:17.33 oxidized

Samples: 48K of event 'cycles:ppp', Event count (approx.): 27581136044
Overhead  Shared Object       Symbol
   7.08%  libruby.so.2.0.0    [.] 0x00000000000fe03a
   6.12%  libruby.so.2.0.0    [.] rb_thread_check_ints
   4.92%  libruby.so.2.0.0    [.] 0x00000000000fe20c
   4.02%  libruby.so.2.0.0    [.] 0x00000000000fe03e
   3.88%  libruby.so.2.0.0    [.] 0x00000000000fe030
   3.50%  libruby.so.2.0.0    [.] onigenc_mbclen_approximate
   3.46%  libruby.so.2.0.0    [.] 0x00000000000fe041
   3.26%  libruby.so.2.0.0    [.] 0x00000000000fe80b
   2.95%  libruby.so.2.0.0    [.] 0x00000000000fe216
   2.71%  libruby.so.2.0.0    [.] 0x0000000000100617
   2.39%  libruby.so.2.0.0    [.] 0x00000000000fe212
   1.86%  libruby.so.2.0.0    [.] 0x00000000000fe1c7
   1.76%  libruby.so.2.0.0    [.] rb_thread_check_ints@plt
   1.70%  libruby.so.2.0.0    [.] 0x00000000000fe1e2
   1.70%  libruby.so.2.0.0    [.] 0x00000000000fe83a
   1.66%  libruby.so.2.0.0    [.] 0x0000000000188c28
   1.63%  libruby.so.2.0.0    [.] 0x00000000000fea23
   1.61%  libruby.so.2.0.0    [.] onigenc_mbclen_approximate@plt
   1.55%  libruby.so.2.0.0    [.] 0x00000000000fea7c
   1.43%  libruby.so.2.0.0    [.] 0x0000000000100619
   1.39%  libruby.so.2.0.0    [.] 0x00000000000fe9ff
   1.32%  libruby.so.2.0.0    [.] 0x00000000000fe201
   1.30%  libruby.so.2.0.0    [.] 0x00000000000fe1e5
   1.23%  libruby.so.2.0.0    [.] 0x00000000000fe1b0
   1.17%  libruby.so.2.0.0    [.] 0x00000000000ff1ac
   1.17%  libruby.so.2.0.0    [.] 0x00000000000fea44
   1.17%  libruby.so.2.0.0    [.] 0x00000000000fea14
   1.15%  libruby.so.2.0.0    [.] 0x000000000010060a
   1.02%  libruby.so.2.0.0    [.] 0x000000000010061d
