### ISSUE TITLE
Ubiquiti AirFiber support?

### ISSUE THREAD

**Issue by paszczus** [ytti/oxidized#371]
We have Ubiquiti AirFiber device and i see in debug logs:

> E, [2016-03-24T22:11:42.171388 #13504] ERROR -- : node {:name=>"172.16.224.10", :model=>"airos-af", :group=>"airos"} raised Oxidized::ModelNotFound with message 'airos-af not found for node 172.16.224.10'
> resolving DNS for 172.16.224.11…

Is AirFiber supported in current oxidized?

**Comment by ytti** [comment]
It might be this:

https://github.com/ytti/oxidized/blob/master/lib/oxidized/model/airos.rb

So you need to change model name to 'airos' or add mapping from airos-af to airos.

**Comment by paszczus** [comment]
Commands from that url are working fine or AirFiber too.
I am using librenms API as devices source and i have already set mapping from airos-af to airos

**Comment by ytti** [comment]
So all good?

**Comment by paszczus** [comment]
Not really. I'm still getting same error and cannot get configuration for that device(s).

**Comment by ytti** [comment]
So what is your error now? If you've set mapping, then clearly your complaint can't be anymore the same as it was.

**Comment by paszczus** [comment]
How i can change model mapping? All i can do is to put device with model "airos-af" to group "airos"

**Comment by ytti** [comment]
```
model_map:
  airos-af: airos
```

Unsure if '-' is allowed, so you could try also:

```
model_map:
  "airos-af": airos
```

**Comment by paszczus** [comment]
:))) thank you again!
