### ISSUE TITLE
Can't reload `router.db` without web interface

### ISSUE THREAD

**Issue by RichiH** [ytti/oxidized#38]
This should be possible without restarting oxidized, especially since you lose some data when restarting (last update time).

    kill -SIGUSR1 123

would b e a good options, imo.

**Comment by fhibler** [comment]
Fixed in db165b5e1ebb3091a49029d739b68a913bc75db6

kill -HUP 123 should work then

**Comment by RichiH** [comment]
Thanks!

**Comment by fhibler** [comment]
Just opened #79
Oxidized seems to die on HUP reload.

**Comment by ytti** [comment]
Fixed in 4908e399dd
