### ISSUE TITLE
Key-Based SSH not working

### ISSUE THREAD

**Issue by murrant** [ytti/oxidized#380]
I'm currently using oxidized:13.1 and net-ssh:3.0.2.  I upgraded from a 2.x net-ssh release and had issues with a newer version, so I settled on 3.0.2.
And my oxidized no longer connects to devices it uses key-based ssh for.  Issuing ssh as the user I run the script connects right away without prompt.

Did the default behavior change?  How can I make key-based ssh work again?

**Comment by ytti** [comment]
Behaviour has not changed intentionally. Is it possible to put some sanitised device online which I can test against?

**Comment by ytti** [comment]
Is this still relevant?

**Comment by murrant** [comment]
I'll update and check.
