### ISSUE TITLE
f5 snmpv3 not ignoring dynamic hash keys

### ISSUE THREAD

**Issue by etfeet** [ytti/oxidized#382]
The config update for the F5's currently track the snmp v3 hashes which change every time the config is generated so if you diff we're constantly see lines like this:

     sys-location "San Diego"
     users {
         ilibrenms_1 {
-            auth-password-encrypted JIYXNlJQ.Kh=VJMh9>M5VTdSRlc_K:D5L>bYHPKI_`Le>5+
             auth-protocol sha
             oid-subset .1
             privacy-password-encrypted 
@@ -6242,7 +6242,7 @@ sys snmp {
             username librenms
         }

I was able to find this patch which seems to fix it - Can we get this merged?
https://github.com/ytti/oxidized/issues/359

**Comment by ytti** [comment]
I'm hoping for #359 author to send pull request

**Comment by orealez** [comment]
Hi ytti, I'll create another pull request for this to keep things separate. The tmsh -q option issue is different from this one.

**Comment by orealez** [comment]
Actually, looks like the pull request has picked up both now, forgot to tag.

Pull request 385.

**Comment by orealez** [comment]
For anyone back tracking on this, this issue is not specific to SNMPv3 and applies across quite a bit of F5 BIG-IP configuration which now encrypts secrets with a master key. Encrypted output changes regularly.

My modifications from pull request 385 add additional filtering for various plaintext and encrypted secrets that appear in tmsh command outputs, but they *attempt* to avoid modifying iRule output.

The changes do an OK job of that, but it still hits a few iRule statements, example of filtered lines below from one of our v11.6.1 boxes.

[root@box config_report]# grep "secret removed" bigip01.localdomain
    admin-encrypted-password <secret removed>
    form-password <secret removed>
    admin-encrypted-password <secret removed>
    secret <secret removed>
        account_management_mac_sms_new_password <secret removed> }
        account_registration_mac_sms_new_password <secret removed> }
        uri_handler_ter_change_password <secret removed>
    form-password <secret removed>
    form-password <secret removed>
    form-password <secret removed>
    form-password <secret removed>
    form-password <secret removed>
    form-password <secret removed>
    form-password <secret removed>
    form-password <secret removed>
    form-password <secret removed>
    form-password <secret removed>
                password <secret removed>
                password <secret removed>
    account-password <secret removed>
    account-password <secret removed>
    encrypted-password <secret removed>
    encrypted-password <secret removed>
    password <secret removed>
    password <secret removed>
    cookie-encryption-passphrase <secret removed>
    passphrase <secret removed>
    passphrase <secret removed>
    passphrase <secret removed>
    passphrase <secret removed>
    passphrase <secret removed>
    passphrase <secret removed>
    passphrase <secret removed>
    passphrase <secret removed>
    passphrase <secret removed>
    passphrase <secret removed>
    passphrase <secret removed>
    passphrase <secret removed>
    passphrase <secret removed>
    passphrase <secret removed>
    java-sign-key-passphrase-encrypted <secret removed>
            community-name <secret removed>
    trap-community <secret removed>
            community <secret removed>
            auth-password-encrypted <secret removed>
            privacy-password-encrypted <secret removed>
[root@box config_report]#

**Comment by ytti** [comment]
PR has been accepted, assuming this is safe to close
