### ISSUE TITLE
rest api does not convert timezones

### ISSUE THREAD

**Issue by etfeet** [ytti/oxidized#386]
If the OS is running in a local timezone region ie Americas/Los_Angeles the rest api will show that all changes are -7 hours or whatever the time difference is between local time and UTC time.

if I do a config change it will show last updated 7 hours ago and xx minutes. The underlying git repo will shows xx minutes.

root@ubuntu-librenms:/var/lib/oxidized# date
Fri Apr  8 12:07:57 PDT 2016

rest api shows last updated 2016-04-08 19:00:07 UTC
If you select the versions it shows:

version xx  date: 1 	7 hours 14 min ago

last update was 14 minutes ago. However, the timezone is not being converted...
git shows last commit was 14 minutes ago.

**Comment by ytti** [comment]
I don't consider this a bug personally, I think you should convert in the presentation lawyer the UTC to what ever you want, not in API.

But I'll consider PR request with option where you can pass the API TZ you want time to be converted to.

**Comment by etfeet** [comment]
Yeah, I agree with you on the servers being in UTC. However, it would be nice if the documentation mentioned that the servers need to be in UTC TZ - took me a while to figure out that was the problem.

**Comment by ytti** [comment]
No, servers don't need to be in UTC at all, you can run servers in what ever TZ you want, I usually un in UTC. But even in servers, the HW clock is in UTC, it's the presentation layer (date) which then converts it (per-user!) to what ever TZ you want.

So on your serve, by setting correct environment variable, I will get different timezone than you,  even though both of us are accessing same UTC HW clock.

**Comment by ytti** [comment]
closing this as no further comments seen. Please re-open if explanation is not satisfactory. 

In presentation layer (oxidized-web) we do convert TZ already.

**Comment by clay584** [comment]
I have set the TZ env var for the oxidized user as well as in the systemd init script and the /nodes page shows "last update" to be correct, displayed in the local timezone, but when looking at /node/version, it shows "Dates" as 4 hours ago (I am EDT - TZ="America/New_York").

**Comment by ytti** [comment]
The webUI should be converting them to browser-time. JSON/API should be UTC. Is this not the case?

**Comment by clay584** [comment]
I do not believe this is the case.

/nodes
![image](https://cloud.githubusercontent.com/assets/2114016/19099683/bdb3b742-8a86-11e6-87a8-a7bf1eef6241.png)

/node/version
![image](https://cloud.githubusercontent.com/assets/2114016/19099705/f2aa7170-8a86-11e6-9bf3-2a8e3f6c7e38.png)

current system time from my computer:
![image](https://cloud.githubusercontent.com/assets/2114016/19099666/963116f6-8a86-11e6-877c-2789eae17d8e.png)

**Comment by ytti** [comment]
We have this:

https://github.com/ytti/oxidized-web/blob/8300bf6aa389c1d280c6cc67949323305c141823/lib/oxidized/web/public/scripts/oxidized.js#L38

which should convert the time, if class is 'time'.

But it looks like this comperes time to UTC time:
https://github.com/ytti/oxidized-web/blob/8300bf6aa389c1d280c6cc67949323305c141823/lib/oxidized/web/views/versions.haml#L28

And we definitely don't want to change the code unconditionally to change to UTC time, because we want it only to show browser time on JS, not on proper API, which should be be UTC.

Maybe @supertylerc has some idea

**Comment by danilopopeye** [comment]
> And we definitely don't want to change the code unconditionally to change to UTC time, because we want it only to show browser time on JS, not on proper API, which should be be UTC.

maybe we can just convert every date in the browser. wdyt?

**Comment by ytti** [comment]
6d5d9c3ac7f this should fix the problem

**Comment by clay584** [comment]
Thanks you guys!

**Comment by BrunoBlanes** [comment]
I am seeing this issue on the latest version built from git, something changed?
