### ISSUE TITLE
Feature request: Support for multi-context Cisco ASA's

### ISSUE THREAD

**Issue by yostie** [ytti/oxidized#388]
Attempting to backup individual firewall contexts for a multi-context ASA and it is failing when attempting to pull the config down when executing "more system:running-config".  In a multi-context ASA, the only context with access to the file system where you can run that is the System context.  Once you are in the system context, all the context configs are stored on flash and can be read with the "more" command.  I have many firewall contexts and would love to see this feature added as right now I cannot back up any of these configs with Oxidized.  

If you decide to add this as a feature, the easiest thing to do might be to have Oxidized SSH into the admin context, perform a "changeto context system", then run a "show run context" and parse out all the names of the contexts and their associated filename on disk.  From there, execute the "more disk0:/<context_filename>" to display the config.  This will show all the encrypted passwords that are normally showing with the "more system:running-config".  It would be nice to have it backup the config in the System context itself which can have the "more system:running-config" executed on it.

For the time being, I may try to modify your code and just have it do a "show run".

**Comment by ytti** [comment]
I see no reason why this couldn't be added in the model.

I've actually never logged into an ASA (which I'm surprised myself, considering how common it is, and considering how many different kit I've logged into).

Maybe @thakala @sts @nickhilliard @gcotone desire to chime in

**Comment by laf** [comment]
@ytti This can be closed now as #859 resolves this afaik.
