### ISSUE TITLE
Persistent `Last Status` and `Last Time` in web interface

### ISSUE THREAD

**Issue by RichiH** [ytti/oxidized#39]
Can you cache those values and re-use them so they are not lost when restarting `oxidized`?

**Comment by will-h** [comment]
Data persistance-across-restarts would be super-handy (I just came here to open a ticket about this ;). I have a service check checking for each node to ensure we have a recent copy of the config, and of course it alerts if Oxidized has been restarted, since return time is now 'never'. 

Of course, the webinterface could return mtime of the device's config file, but this is probably not a great solution.

**Comment by ytti** [comment]
The status for each node includes last success and last fail, so you could skip alarm if a) both are never or b) success is less than 2-3 * iteration cycle, this might be sufficient workaround for now.

But still, I think this is relates to the most important refactor oxidized needs, to move state from memory into sqlite or similar. It's not hard thing to do, and brings other benefits to us as well.

**Comment by RichiH** [comment]
Jftr, doing two factor alarming is possible but more effort and less
resilient.

Richard

Sent by mobile; excuse my brevity.

**Comment by darkounet** [comment]
:up:

**Comment by darkounet** [comment]
or maybe a way to store state in a .yml file or .json ?

**Comment by darkounet** [comment]
Any update ? :D

**Comment by ytti** [comment]
Nope, sorry. I'm not working on this currently. I want to have node queue, node statistics etc in disk, not in memory. It's probably gonna take me 3-5 working days, which I'm not ready to contribute at present.

**Comment by MrRJ45** [comment]
Having rewritten some bits I now have all of a nodes stats in the db. I am ignoring the max of 10 stats, do we want to keep stats in the db for a long time?

What else do we think needs to be persisted?

**Comment by MajesticFalcon** [comment]
BUMP

**Comment by ytti** [comment]
This is not gonna happen before I'll refactor the core, and I have no idea when that might happen.

**Comment by casdr** [comment]
Is there any progress / planning on this? We have around 500 devices in Oxidized and this will help debugging and testing a lot.

**Comment by PeepOks** [comment]
Is there any ETA. for this feature. It would be very helpful if last-status is not lost after oxidized service reload.

**Comment by ytti** [comment]
I have no plans to work on this right now. It's important, but mainly the stats keeping would be side-effect of important change of moving state to sqlite, reducing memory footprint significantly in larger installations.
