### ISSUE TITLE
SQL adapter gem not installed: LoadError

### ISSUE THREAD

**Issue by davama** [ytti/oxidized#392]
Hello, trying to setup oxidized with sqlite db. I followed the wiki for sql source but at a lost to what to search for next.
this is the config file
_....
source:
  default: sql
  sql:
    adapter: sqlite
    database: "/home/config/amer.db"
    table: devices
    map:
      name: name
      model: model
      username: <username>
      password: <password>
    vars_map:
      enable: enable_

when i run oxidized i get: 
_SQL adapter gem not installed: LoadError: cannot load such file -- sqlite3
_
the crash file says:
_SQL adapter gem not installed: LoadError: cannot load such file -- sqlite3 [Oxidized::OxidizedError]
_
These are the gems installed:
_asetus (0.3.0)
backports (3.6.8)
bigdecimal (1.2.0)
emk-sinatra-url-for (0.2.1)
haml (4.0.7)
io-console (0.4.2)
json (1.7.7)
multi_json (1.11.2)
net-ssh (3.0.2)
oxidized (0.13.1, 0.12.2)
oxidized-script (0.1.2)
oxidized-web (0.7.0, 0.6.1)
psych (2.0.0)
puma (2.16.0)
rack (1.6.4)
rack-protection (1.5.3)
rack-test (0.6.3)
rdoc (4.2.2, 4.0.0)
rugged (0.23.3)
sass (3.4.21)
sequel (4.33.0)
sinatra (1.4.7)
sinatra-contrib (1.4.6)
slop (3.6.0)
tilt (2.0.2)_

Any input as to where to look?

Thank you
Dave

**Comment by ytti** [comment]
```SQL adapter gem not installed: LoadError: cannot load such file -- sqlite3```

complains that the adapter to chose, ```sqlite3``` cannot be loaded, probably because it's not installed.

Try ```gem install sqlite3```

**Comment by davama** [comment]
I really though i tried that. 
That was it.
Thanks!
