### ISSUE TITLE
get junos configuration over netconf

### ISSUE THREAD

**Issue by teadur** [ytti/oxidized#397]
It would be really nice if you could use netconf to pull configuration from junos device:

http://www.juniper.net/documentation/en_US/junos13.3/topics/reference/tag-summary/netconf-junos-xml-protocol-get-configuration.html

**Comment by supertylerc** [comment]
Is there a reason to use NETCONF? Is there a shortcoming that the current methodology has?

The problem with using NETCONF is that it requires pulling in an additional gem, plus its dependencies, without any real benefit besides "it's the cool thing." And using NETCONF for Junos would mean doing things differently for Junos than every other vendor, plus expecting end users to be familiar with or look up NETCONF RPCs for gathering data they want when extending Oxidized.

**Comment by benbacardi** [comment]
Netconf has it's uses, but I don't believe this is one of them. The added complexity doesn't provide any additional benefit for running a series of short show commands, IMO.

**Comment by teadur** [comment]
Actualy the reason came from pretty strange place, currently the latest vMX juniper software based router has its ssh implementations broken so running sho config brakes the ssh session, was looking for alternative to rancid because of that.

Maybe it could be optional extra feature and normaly junos would default to ssh ?

**Comment by supertylerc** [comment]
If you're managing the box normally and you type show configuration, it force closes your SSH session? Or does this happen only with Oxidized? If it happens with any SSH implementation, then it's a critical bug in vMX that the vendor should address immediately as it makes normal operation of the device nearly impossible. Not to speak for @ytti, but projects should not be in the business of working around a vendor's critical bugs.

**Comment by teadur** [comment]
It happens with any ssh imlemenations and sure it is critical bug and vendor should adress it.
But the feature request isnt about working around vendor bug, its about getting configuration over netconf. If you guys arent intersted in implementing netconf then so be it, just an idea. I'll give it a try maybe i can fork the project and be able to implement it myself but its doubtful.

**Comment by ytti** [comment]
I'm personally not gonna work on this, not on any foreseeable future. I wouldn't be that hard to add and I could accept PR for it. Pretty much you add input/netconf.rb and then cfg :netconf in models where it's supported, and you're done.
It wouldn't add extra cruft on any other parts of the project so it wouldn't impact complexity much at all.

**Comment by wk** [comment]
Closing this, as the issue has recently celebrated its 2nd birthday, but no additional users have expressed interest in the feature or in working toward it.

@teadur If you have successfully implemented a netconf input, or are still working on it, a PR would be very welcome!
