### ISSUE TITLE
Debian 8 requires libssh-2-1-dev?

### ISSUE THREAD

**Issue by hklygre** [ytti/oxidized#398]
On Debian 8.4, pushing to gitlab over ssh does not work when installing oxidized per the instructions in the README, giving the error 
`E, [2016-04-18T21:56:30.467242 #2749] ERROR -- : Hook push_to_remote (#<GithubRepo:0x00000002157848>) failed (#<Rugged::NetworkError: Unsupported URL protocol>) for event :post_store`

Installing libssh-2-1-dev before removing and reinstalling the 'rugged' gem clears this error.

`root@bgo-int-app01:~# ldd /var/lib/gems/2.1.0/extensions/x86_64-linux/2.1.0/rugged-0.24.0/rugged/rugged.so
        linux-vdso.so.1 (0x00007ffe50fae000)
        libssh2.so.1 => /usr/lib/x86_64-linux-gnu/libssh2.so.1 (0x00007f1cfcd2d000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f1cfcb25000)
        libssl.so.1.0.0 => /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007f1cfc8c5000)
        libcrypto.so.1.0.0 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007f1cfc4c9000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f1cfc2c5000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f1cfc0aa000)
        libruby-2.1.so.2.1 => /usr/lib/x86_64-linux-gnu/libruby-2.1.so.2.1 (0x00007f1cfbc2e000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f1cfba11000)
        libgmp.so.10 => /usr/lib/x86_64-linux-gnu/libgmp.so.10 (0x00007f1cfb78e000)
        libcrypt.so.1 => /lib/x86_64-linux-gnu/libcrypt.so.1 (0x00007f1cfb557000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f1cfb256000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f1cfaeab000)
        libgcrypt.so.20 => /lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007f1cfabc9000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f1cfd26d000)
        libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007f1cfa9b7000)

root@bgo-int-app01:~# dpkg -S /usr/lib/x86_64-linux-gnu/libssh2.so.1
libssh2-1:amd64: /usr/lib/x86_64-linux-gnu/libssh2.so.1
`

**Comment by TibshoOT** [comment]
Taking a look at https://github.com/libgit2/libgit2#optional-dependencies , it doesn't seem to exist a strict dependency on libssh-dev for building rugged gem .

Didn't you encounter any error when installing oxidized ?

Did you test to only setup libssh2 (no -dev) before reinstalling it ?

**Comment by hklygre** [comment]
No, sorry, you're right - rugged compiles and installs without it, but using a githubrepo-hook to push to a local gitlab-installation fails with the message "Rugged::NetworkError: Unsupported URL protocol" if libssh-2-1-dev wasn't installed when rugged was installed.  (obviously an ssh-URL for the repo).

This is a run-time error, not a compile/install-time error.  libssh2 (no -dev) was installed the first time I tried installing rugged.

- Håvard

**Comment by TibshoOT** [comment]
Ok, thanks for feedback.

Honnestly, I didn't try to push via SSH but if you're right, we need to update README to add some indications.

Tib

**Comment by hklygre** [comment]
Sure.  I was just using the example from the cookbook in README.md... (and it works, too)
Storing the configs on our gitlab server is the main purpose of using oxidized for me.

**Comment by TibshoOT** [comment]
Yes, seems legit. I clearly understand your way of using Oxidized.

Can you confirm that your issue was resolved after setuping libssh-2-1-dev ?

Thanks,

Tib

**Comment by hklygre** [comment]
That is correct.  I needed to install libssh2-1-dev _before_ installing the rugged gem (as that gets compiled during installation, and obviously autodetects whether the library is installed.)

**Comment by bartdebruijn** [comment]
Seconded, installing libssh2-1-dev before installing rugged fixes this issue.

**Comment by TibshoOT** [comment]
Ok, we can close this issue, README has been updated for Debian setup. :)
