### ISSUE TITLE
CentOS Init Script

### ISSUE THREAD

**Issue by vertras** [ytti/oxidized#399]
I'm having trouble getting an init script working for oxidized. I copied `oxidized.init.d` from `extras` into `/etc/init.d`

when I try to start the service, it fails:
```
[root@oxiserver oxidized]# service oxidized start
Starting oxidized (via systemctl):  Job for oxidized.service failed because the control process exited with error code. See "systemctl status oxidized.service" and "journalctl -xe" for details.
                                                           [FAILED]
[root@oxiserver oxidized]# service oxidized status
● oxidized.service - SYSV: Oxidized - Network Device Configuration Backup Tool
   Loaded: loaded (/etc/rc.d/init.d/oxidized)
   Active: failed (Result: exit-code) since Tue 2016-04-19 15:03:56 CDT; 7s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 10101 ExecStart=/etc/rc.d/init.d/oxidized start (code=exited, status=1/FAILURE)

Apr 19 15:03:56 oxiserver systemd[1]: Starting SYSV: Oxidized - Network Device Configuration Backup Tool...
Apr 19 15:03:56 oxiserver oxidized[10101]: Starting Oxidized: /bin/bash: oxidized: command not found
Apr 19 15:03:56 oxiserver oxidized[10101]: [17B blob data]
Apr 19 15:03:56 oxiserver systemd[1]: oxidized.service: control process exited, code=exited status=1
Apr 19 15:03:56 oxiserver systemd[1]: Failed to start SYSV: Oxidized - Network Device Configuration Backup Tool.
Apr 19 15:03:56 oxiserver systemd[1]: Unit oxidized.service entered failed state.
Apr 19 15:03:56 oxiserver systemd[1]: oxidized.service failed.
```
But if i run `oxidized` or `oxidized --daemonize` it works just fine. Am I missing something obvious?
Running on CentOS 7, ruby 2.1.2, and doing everything as root.

**Comment by ytti** [comment]
It looks like your 'bash' environment does not even see whole 'oxidized' script in path.

You're not using RVM or something else which might be needed for it it work?

**Comment by vertras** [comment]
yeah, I installed RVM from the steps in the readme

**Comment by ytti** [comment]
Ok then you'll need to call it via RVM. Right now your bash environment does not load RVM, so it can't find oxidized. Either install it natively via gem (provided your Centos has new enough ruby) or make sure your init script loads RVM.

**Comment by yostie** [comment]
I have the same problem.  @vertras if you get it fixed, can you post the steps you took to do it?

Thanks

**Comment by vertras** [comment]
OK, I think I have this working now. In a nutshell, I ditched rvm and installed native ruby. I also ended up switching the service from init to systemd. Thanks @ytti for pointing me in the right direction. 
@yostie Let me know if you need some more detail and I'll try to remember what I did.

**Comment by davama** [comment]
@vertras 
can you please post what you did? how does your unit/service file look?
THanks

**Comment by yostie** [comment]
@vertras, i would love to see details on what you did...

**Comment by vertras** [comment]
ok, so here's a rough outline. all of this was run as root. all of this may not be necessary, but I did a couple of these steps at the same time, so I'm not sure what made it work.
- get rid of rvm: `rvm implode`
- install ruby: `yum install ruby ruby-devel`
- my oxidized config files were stored in `/root`. moved them to `/etc/oxidized`.
- update references in `/etc/oxidized/config` from `/root` to new location
- reinstall oxidized with the steps in the readme
```
gem install oxidized
gem install oxidized-script oxidized-web
```
- delete oxidized init file from `/etc/init.d`
- copy systemd script from `/usr/local/share/gems/gems/oxidized-0.13.1/extra/oxidized.service` to `/etc/systemd/system/`
- add the following lines to `oxidized.service` in the [Unit] section
```
After=network.target network-online.target
Requires=network-online.target
```
here is my full file @davama: https://gist.github.com/vertras/b908dbf258914749e5f032b6abde3057
(reason for this: once I got oxidized to start, it was trying to start before the network service and couldn't bind to an ip)

at this point you should be able to control oxidized with systemctl
`systemctl start oxidized` to start it
`systemctl status oxidized` to get the status
if that works, you can set it to run at boot with `systemctl enable oxidized`

**Comment by ytti** [comment]
can this be closed? I'm also accepting PR for README.md update or script in /extra directory

**Comment by yostie** [comment]
@vertras I confirmed your process did work.  I did it on a fresh install and not on my running box.  Thanks!
