### ISSUE TITLE
Docker container not starting

### ISSUE THREAD

**Issue by lwhitworth** [ytti/oxidized#400]
Following the instructions for using the docker container, I get to the point of running

`docker run -v /etc/oxidized:/root/.config/oxidized -p 8888:8888/tcp -t oxidized/oxidized:latest`

The container starts but instantly starts spewing out:

```
runsv auto-reload-config: fatal: unable to start ./run: access denied
runsv oxidized: fatal: unable to start ./run: access denied
```
I've tried it on a couple of hosts just to see if that played any part, same error on both.  Am I missing something?

**Comment by mikebryant** [comment]
They need to be executable, this was changed in b9ff876ac5e090b46a67e222706972e58028f7d1
@ytti was this intentional?

**Comment by ytti** [comment]
No. I must have normalised permissions with find|xargs chmod and forgot binaries :/
