### ISSUE TITLE
Support Tripplite SNMPWEBCARD

### ISSUE THREAD

**Issue by murrant** [ytti/oxidized#403]
The config can be fetched by http with http auth.
ex:
```wget --user=user--password=password http://1.2.3.4/paconfig.ini```

**Comment by ytti** [comment]
If you can give me access to it, I can create support. 

It'll take bit of time, I'm traveling at the moment.

**Comment by murrant** [comment]
How can I get this info to you privately?

**Comment by ytti** [comment]
saku@ytti.fi email would work

**Comment by murrant** [comment]
Wow, these things are a pile.  I'm not sure when I'll be able to get you access.
