### ISSUE TITLE
undefined method `join' for nil:NilClass

### ISSUE THREAD

**Issue by lkowolowski** [ytti/oxidized#404]
I'm seeing an odd issue that the google hasn't solved. I've tried setting this up on 2 systems and gotten the same results. Any pointers or cluebats on what I've done wrong? I've created a config and routers.db that are pretty simple:
config:
```
---
username: oxidized
input:
  default: ssh
  debug: /home/oxidized/.config/oxidized/oxidized_log_input
  ssh:
    secure: false
output:
  default: file
  file:
    directory: "/home/oxidized/.config/oxidized/configs"
source:
  default: csv
  csv:
    file: "/home/oxidized/.config/oxidized/router.db"
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
```

router.db:
`s50n-1.domain.com:ftos`

running oxidized results in an undefined method. I'm guessing something isn't installed, but I'm not seeing something obvious.

```
$ oxidized
I, [2016-04-25T22:26:35.534459 #39942]  INFO -- : Oxidized starting, running as pid 39942
I, [2016-04-25T22:26:35.679886 #39942]  INFO -- : Loaded 1 nodes
Puma 2.16.0 starting...
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://127.0.0.1:8888
E, [2016-04-25T22:26:42.440653 #39942] ERROR -- : 172.17.32.250 raised NoMethodError with msg "undefined method `join' for nil:NilClass", /home/oxidized/.config/oxidized/crash.172.17.32.250 saved
W, [2016-04-25T22:26:43.486447 #39942]  WARN -- : s50n-1.domain.com status no_connection, retry attempt 1
E, [2016-04-25T22:26:49.772589 #39942] ERROR -- : 172.17.32.250 raised NoMethodError with msg "undefined method `join' for nil:NilClass", /home/oxidized/.config/oxidized/crash.172.17.32.250 saved
W, [2016-04-25T22:26:50.831336 #39942]  WARN -- : s50n-1.domain.com status no_connection, retry attempt 2
E, [2016-04-25T22:26:56.906562 #39942] ERROR -- : 172.17.32.250 raised NoMethodError with msg "undefined method `join' for nil:NilClass", /home/oxidized/.config/oxidized/crash.172.17.32.250 saved
W, [2016-04-25T22:26:57.088328 #39942]  WARN -- : s50n-1.domain.com status no_connection, retry attempt 3
E, [2016-04-25T22:27:03.351519 #39942] ERROR -- : 172.17.32.250 raised NoMethodError with msg "undefined method `join' for nil:NilClass", /home/oxidized/.config/oxidized/crash.172.17.32.250 saved
W, [2016-04-25T22:27:04.236393 #39942]  WARN -- : s50n-1.domain.com status no_connection, retries exhausted, giving up
^C$
```

**Comment by TibshoOT** [comment]
Hello,

Can you paste /home/oxidized/.config/oxidized/crash.172.17.32.250 ?

Thank you,

Tib

**Comment by ytti** [comment]
I'm guessing missing config, we're not very graceful on bad config. It'll create sensible config itself, but it seems many people create config from scratch missing something, and then we'll fail in non-obvious way.

So yeah, give output of one of those files. Or run with debugging on, so we'll get backtrace, it'll probably show which missing config value we're trying to access.

**Comment by lkowolowski** [comment]
$ cat crash.172.17.32.250
2016-04-25 22:27:03 UTC
undefined method `join' for nil:NilClass [NoMethodError]
--------------------------------------------------
/usr/local/lib/ruby/gems/2.2/gems/oxidized-0.13.1/lib/oxidized/model/ftos.rb:26:in `block in <class:FTOS>'
/usr/local/lib/ruby/gems/2.2/gems/oxidized-0.13.1/lib/oxidized/model/model.rb:92:in `instance_exec'
/usr/local/lib/ruby/gems/2.2/gems/oxidized-0.13.1/lib/oxidized/model/model.rb:92:in `cmd'
/usr/local/lib/ruby/gems/2.2/gems/oxidized-0.13.1/lib/oxidized/model/model.rb:133:in `block in get'
/usr/local/lib/ruby/gems/2.2/gems/oxidized-0.13.1/lib/oxidized/model/model.rb:132:in `each'
/usr/local/lib/ruby/gems/2.2/gems/oxidized-0.13.1/lib/oxidized/model/model.rb:132:in `get'
/usr/local/lib/ruby/gems/2.2/gems/oxidized-0.13.1/lib/oxidized/input/cli.rb:14:in `get'
/usr/local/lib/ruby/gems/2.2/gems/oxidized-0.13.1/lib/oxidized/node.rb:61:in `run_input'
/usr/local/lib/ruby/gems/2.2/gems/oxidized-0.13.1/lib/oxidized/node.rb:40:in `block in run'
/usr/local/lib/ruby/gems/2.2/gems/oxidized-0.13.1/lib/oxidized/node.rb:35:in `each'
/usr/local/lib/ruby/gems/2.2/gems/oxidized-0.13.1/lib/oxidized/node.rb:35:in `run'
/usr/local/lib/ruby/gems/2.2/gems/oxidized-0.13.1/lib/oxidized/job.rb:8:in `block in initialize'
$

**Comment by TibshoOT** [comment]
Doesn't your equipment need an password ? Is it configured for direct access ?

In your config directory, do you have 172.17.32.250.log ? Do you see any error in it ?

Thanks

**Comment by lkowolowski** [comment]
It is configured for direct access. Still requires enable password. Now I'm seeing entries in the host specific log. I can move forward. Thanks!
