### ISSUE TITLE
Telnet to ASR9001 (IOSXR) fails...

### ISSUE THREAD

**Issue by cr1ll3** [ytti/oxidized#410]
oxs -m iosxr -u **masked** -p **masked** -v -d --protocols telnet **masked** -x show run
resolving DNS for **masked**...
D, [2016-05-03T09:27:24.757775 #7731] DEBUG -- : Telnet: terminal length 0 @**masked**
timed out while waiting for more data
/var/lib/gems/2.1.0/gems/oxidized-0.13.1/lib/oxidized/input/telnet.rb:107:in `waitfor': timed out while waiting for more data (Timeout::Error)
	from /usr/lib/ruby/2.1.0/net/telnet.rb:696:in `cmd'
	from /var/lib/gems/2.1.0/gems/oxidized-0.13.1/lib/oxidized/input/telnet.rb:43:in `cmd'
	from /var/lib/gems/2.1.0/gems/oxidized-0.13.1/lib/oxidized/input/cli.rb:20:in `block in connect_cli'
	from /var/lib/gems/2.1.0/gems/oxidized-0.13.1/lib/oxidized/input/cli.rb:20:in `each'
	from /var/lib/gems/2.1.0/gems/oxidized-0.13.1/lib/oxidized/input/cli.rb:20:in `connect_cli'
	from /var/lib/gems/2.1.0/gems/oxidized-script-0.1.2/lib/oxidized/script/script.rb:110:in `connect'
	from /var/lib/gems/2.1.0/gems/oxidized-script-0.1.2/lib/oxidized/script/script.rb:88:in `initialize'
	from /var/lib/gems/2.1.0/gems/oxidized-script-0.1.2/lib/oxidized/script/cli.rb:73:in `new'
	from /var/lib/gems/2.1.0/gems/oxidized-script-0.1.2/lib/oxidized/script/cli.rb:73:in `connect'
	from /var/lib/gems/2.1.0/gems/oxidized-script-0.1.2/lib/oxidized/script/cli.rb:12:in `run'
	from /var/lib/gems/2.1.0/gems/oxidized-script-0.1.2/bin/oxs:5:in `<top (required)>'
	from /usr/local/bin/oxs:23:in `load'
	from /usr/local/bin/oxs:23:in `<main>'

User Access Verification

Username: **masked**
Password: Trying **masked**...
Connected to **masked**.

User Access Verification

Username: **masked**
Password: Trying **masked**...
Connected to **masked**.

User Access Verification

Username: **masked**
Password:

**Comment by ytti** [comment]
Maybe turn on input debugging 

```
input:
  debug: true
```

It looks bit strange, I think it should have succeeded in auth, as it sent 'term len 0'.

**Comment by cr1ll3** [comment]
I do have debug enabled (I also use the -d flag with oxs) but in the output to the file is the same..

**Comment by ytti** [comment]
Do you specifically have

```
input:
  debug: true
```

which is different to 
```
debug: true
```

which is what ```-d``` flag does.

the input debug should create ```log-ip-telnet``` file for the session, it will be overwritten by next attempt, so you might want to 'tail -f' it.

**Comment by cr1ll3** [comment]
I do.

This is what my config-file looks like;

cat ~/.config/oxidized/config
---
username: **masked**
password: **masked**
interval: 3600
threads: 30
retries: 3
rest: **masked**:8888
input:
  debug: true
source:
  default: http
  debug: false
  http:
    url: http://127.0.0.1/api/v0/oxidized
    scheme: https
    delimiter: !ruby/regexp /:/
    map:
      name: hostname
      model: os
    headers:
      X-Auth-Token: '**masked**'
output:
  default: git
  git:
    user: **masked**
    email: **masked**
    repo: "~/.config/oxidized/oxidized.git"

And the tail from the log-file

c@librenms:~/.config/oxidized$ tail -f log-**masked**-telnet

Username: **masked**
Password: Trying **masked**...
Connected to **masked**.


User Access Verification

Username: **masked**
Password: Trying **masked**...
Connected to **masked**.


User Access Verification

Username: **masked**
Password: Trying **masked**...
Connected to **masked**.


User Access Verification

Username: **masked**
Password: Trying **masked**...
Connected to **masked**.


User Access Verification

Username: **masked**
Password: Trying **masked**...
Connected to **masked**.


User Access Verification

Username: **masked**
Password:

**Comment by ytti** [comment]
Do you get same failure and traceback in ```oxidized``` as you do in ```oxs```


I am way confused about the ```terminal length 0``` it does not fit with the input debug file. the ```terminal length 0``` implies login was success and we saw prompt and sent it ```terminal length 0``` but didn't get prompt afterwards.

**Comment by cr1ll3** [comment]
This is running oxidized

> W, [2016-05-04T09:10:32.978787 #13703]  WARN -- : **masked** raised Timeout::Error with msg "timed out while waiting for more data"
> W, [2016-05-04T09:10:33.011052 #13703]  WARN -- : **masked** status no_connection, retry attempt 1
> D, [2016-05-04T09:10:33.011444 #13703] DEBUG -- : Jobs 0, Want: 1
> W, [2016-05-04T09:10:53.969457 #13703]  WARN -- : **masked** raised Timeout::Error with msg "timed out while waiting for more data"
> W, [2016-05-04T09:10:54.017776 #13703]  WARN -- : **masked** status no_connection, retry attempt 2
> D, [2016-05-04T09:10:54.018114 #13703] DEBUG -- : Jobs 0, Want: 1
> W, [2016-05-04T09:11:14.936012 #13703]  WARN -- : **masked** raised Timeout::Error with msg "timed out while waiting for more data"
> W, [2016-05-04T09:11:15.023206 #13703]  WARN -- : **masked** status no_connection, retry attempt 3
> D, [2016-05-04T09:11:15.023367 #13703] DEBUG -- : Jobs 0, Want: 1
> W, [2016-05-04T09:11:35.952477 #13703]  WARN -- : **masked** raised Timeout::Error with msg "timed out while waiting for more data"
> W, [2016-05-04T09:11:36.028270 #13703]  WARN -- : **masked** status no_connection, retries exhausted, giving up

**Comment by ytti** [comment]
When running oxidized, log-ip-telnet also freezes after password prompt, you never see actual prompt?

What did the crash-ip file show?


If we don't progress from password, likely there is some special character in password prompt, view the log-ip-telnet with some program capable of printing those, maybe vim.
If we do progress from password, then we need to know how far.

The data you're showing is bit inconsistent, the traceback shows we've logged in and trying to issue 'term len 0', but the captured data shows we've not progressed from password prompt, strange.

**Comment by cr1ll3** [comment]
There's no crash-ip file.

This is interesting however, did as you said and viewed the log-file in vi and password-prompt seems to be

> Username: 
> ^MPassword:

Unlike other cisco switches/routers im able to login to where it's just

> Username:
> Password:

**Comment by ytti** [comment]
https://github.com/ytti/oxidized/blob/master/lib/oxidized/model/ios.rb

copy this to ~/.config/oxidized/model/ios.rb

change /^Password/ to /^\r?Password/

and see if it helps

**Comment by cr1ll3** [comment]
That did the trick! Thank you.

Just for reference; It's IOSXR model, not IOS.
