### ISSUE TITLE
Cant see versions under node display

### ISSUE THREAD

**Issue by callumbnz** [ytti/oxidized#413]
Hi,

When I click on the 'versions' icon under the node display, I get a correct list of versions, I can do diff's across the versions OK - but if I click on the  'configuration' button - I get a version not found message - my config file is below - any ideas?

```
---
username: omitted
password: omitted 
model: junos
interval: 3600
use_syslog: false
debug: false
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 0.0.0.0:8888
vars: {}
groups: {}
input:
  default: ssh, telnet
  ssh:
    secure: false
output:
  default: git
  git:
    single_repo: true
    user: Oxidized
    email: omitted
    repo: "/var/lib/oxidized/devices.git"
source:
  default: csv
  csv:
    file: /etc/oxidized/router.db
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
      username: 2
      password: 3
      group: 4
model_map:
  cisco: ios
  juniper: junos
```

**Comment by callumbnz** [comment]
suspect it is related to the last commit #60cd198 bumping the version to 0.14

**Comment by ytti** [comment]
@PANZERBARON yup, @callumbnz is right, too bad I didn't catch it.

Changing this https://github.com/ytti/oxidized/blob/master/lib/oxidized/output/git.rb#L106

To this:

```        
if group && group != '' && !@cfg.single_repo?
  repo = File.join File.dirname(repo), group + '.git'
elsif group
  node = File.join group, node
end
```

Might fix it, if you care to try.

**Comment by callumbnz** [comment]
Yup - that fixed it - cheers 👍

**Comment by ytti** [comment]
thanks for verifying

**Comment by rush131** [comment]
Hi, just did a fresh install today, and I have the same problem. The fix ytti recommended is already in my version of oxidized, but I get the same problem as described. Here is my config:

---
username: username
password: password
model: junos
interval: 3600
use_syslog: false
debug: false
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 0.0.0.0:8080
vars: {}
groups: {}
input:
  default: ssh, telnet
  debug: false
  ssh:
    secure: false
output:
  default: git
  file:
    directory: "/etc/oxidized/configs"
  git:
    single_repo: true
    user: Oxidizied
    email: oxidized@bla.com
    repo: "/etc/oxidized/devices.git"
source:
  default: csv
  csv:
    file: "/etc/oxidized/router.db"
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
      username: 2
      password: 3
    vars_map:
      enable: 4
model_map:
  cisco: ios
  juniper: junos
  mikrotik: routeros

**Comment by ytti** [comment]
You get list of versions, but trying to open one of them produces version not found?

And you're sure you're looking at correct installation (there might be multiple versions installed).

**Comment by rush131** [comment]
Thats right, I see a list of versions, screenshot: https://snag.gy/sPFCpA.jpg

Then when I click on "Configuration" button, I get: https://snag.gy/qYlRsC.jpg

This is a fresh install on a new server, pulled the code yesterday, and I have checked the file that you mentioned here (https://github.com/ytti/oxidized/blob/master/lib/oxidized/output/git.rb#L106) and I see the change in my local files.

**Comment by ytti** [comment]
This is likely #423 so maybe it's something that for you would have worked in 0.14.0 but was just broken in 0.14.1 while fixing this issue
