### ISSUE TITLE
Diffs/break lines false detection ussing comware.rb 

### ISSUE THREAD

**Issue by amarti2038** [ytti/oxidized#415]
Hi,

We are getting diffs without doing config changes in our HP 5900 (comware) devices. Do you have some idea about how to solve the issue? did you found something similar with other devices?

diff --git a/xxx-5900 b/xxx-5900
index 4f1793e..0eb05de 100644
--- a/xxx-5900
+++ b/xx-5900
@@ -2244,7 +2244,7 @@ vlan 3038
 #
 vlan 3039
  name CONxxx3039
-#
+#
 vlan 3040
  name CONxxx3040
 #

Regards,
Albert M.

**Comment by ytti** [comment]
Look at the raw files with vim or something. I'm guessing rogue ^M or something.

**Comment by amarti2038** [comment]
hi,

exactly, I just found the char with the git diff HEAD~3
-vlan 3029
+vlan 3029^M

do you know how to scape it in ruby?
I just test it with:
  cmd 'display current-configuration' do |cfg|
     cfg.gsub!(/password (\S+).*/, 'password (secret removed)')
     cfg.gsub! '^M', ''
     cfg.gsub! '\r\n', '\n'
     cfg.gsub! '0x0D', ''
     cfg.gsub! /[^\x20-\x7F\x0D\x0A]/, ''
     cfg
  end

but nothing works xD

regards,
albert

**Comment by ytti** [comment]
It is indeed \r, so maybe just ```cfg = cfg.delete \r``` or ```cfg = cfg.gsub /\r/, ''```` you can put it under ```cfg :all```block to impact all commands.

**Comment by amarti2038** [comment]
Works! would be nice if you push it to the comware.rb model.

**Comment by ytti** [comment]
Pull requests accepted.
