### ISSUE TITLE
I can't use it with a old switch Foundry

### ISSUE THREAD

**Issue by VDGAyanami** [ytti/oxidized#418]
Hi, I'm traying to write a simple class to add the olds foundry switchs, like FES2402, the ironview.rb work very well with the new models like ICX-6430, but not with the olds one.

ths debug is:

I, [2016-05-12T10:11:03.324876 #29965]  INFO -- : Loaded 158 nodes
D, [2016-05-12T10:11:03.689656 #29965] DEBUG -- : Jobs 0, Want: 1
Puma 2.16.0 starting...
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://0.0.0.0:8888
D, [2016-05-12T10:11:05.504063 #29965] DEBUG -- : SSH:  @ 10.xx.21.40
D, [2016-05-12T10:11:05.908782 #29965] DEBUG -- : SSH: skip-page-display @ 10.xx                                                                                                                                                                           .21.40
D, [2016-05-12T10:11:06.347687 #29965] DEBUG -- : SSH: show configuration @ 10.x                                                                                                                                                                        x.21.40
D, [2016-05-12T10:11:09.658199 #29965] DEBUG -- : SSH: quit @ 10.xx.21.40
D, [2016-05-12T10:11:09.658394 #29965] DEBUG -- : SSH: exit @ 10.xx.21.40

^[[AW, [2016-05-12T10:11:29.664883 #29965]  WARN -- : 10.xx.21.40 raised Timeout::Error with msg "execution expired"
W, [2016-05-12T10:11:29.693549 #29965]  WARN -- : 10.xx.21.40 status no_connection, retries exhausted, giving up
D, [2016-05-12T10:11:29.693593 #29965] DEBUG -- : Jobs 0, Want: 1

thanks,

**Comment by ytti** [comment]
You might want to do

```
input:
  debug: true
```

Then in oxidzed's directory you'll have something like 1.1.1.1-ssh.log which you can 'tail -f' to follow what's happening on the session. It may prove invaluable clues how to modify the model.

**Comment by VDGAyanami** [comment]
The problem is at the very last cmd, the last pre_logout command 'exit' is not send at switch, the prompt change after the first 'exit' and the switch close the connection only if received two 'exit' command.

SSH@FDRY48_Etg4_40#exit
SSH@FDRY48_Etg4_40>

at my model foundry.rb I have:

#handle pager with enable
  cfg :ssh do
    post_login ''
    post_login 'skip-page-display'
  #  exec true
    # pre_logout 'kill ssh 1'
    pre_logout 'exit'
    pre_logout 'exit'
  end

thanks.

**Comment by ytti** [comment]
What is the prompt? It seems like it's maybe not recognising the prompt.

**Comment by VDGAyanami** [comment]
the prompt is: SSH@FDRY48_Etg4_40#

after the first cmd 'exit' become: SSH@FDRY48_Etg4_40>

**Comment by ytti** [comment]
I mean in the model/config etc. 

Does the model/config allow for >, like [#>]?

**Comment by VDGAyanami** [comment]
Hi, I use the same that ironware.rb:
my file:

class Foundry < Oxidized::Model

  prompt /^.*(telnet|ssh)\@.+[>#]\s?$/i
  comment  '! '

  #to handle pager without enable
  #expect /^((.*)--More--(.*))$/ do |data, re|
  #  send ' '
  #  data.sub re, ''
  #end


  #to remove backspace (if handle pager without enable)
  #expect /^((.*)[\b](.*))$/ do |data, re|
  #  data.sub re, ''
  #end

  #cmd :all do |cfg|
    # sometimes ironware inserts arbitrary whitespace after commands are
    # issued on the CLI, from run to run.  this normalises the output.
  #  cfg.each_line.to_a[1..-2].drop_while { |e| e.match /^\s+$/ }.join
  #end


  cmd 'show configuration' do |cfg|
    cfg
  end


  #handle pager with enable
  cfg :ssh do
    post_login ''
    post_login 'skip-page-display'
  #  exec true
    # pre_logout 'kill ssh 1'
    pre_logout 'exit'
    pre_logout 'exit'
  end

end

**Comment by ytti** [comment]
well that 'prompt' should match, unless there are >1 white space after the '>' can you look in capture file what exactly follows '>'. And if there are unprintable characters in the prompt line, like ^M. You can view the debug file with 'vim' or other which will display unprintables.

**Comment by VDGAyanami** [comment]
hi, this is the capture file:

 no spanning-tree^M
!^M
interface ethernet 48^M
 no spanning-tree^M
!^M
interface ethernet 49^M
 no spanning-tree^M
!^M
interface ethernet 50^M
 no spanning-tree^M
!^M
!^M
!^M
lldp run^M
!^M
!^M
ip ssh  idle-time 5^M
!^M
!^M
end^M
^M
SSH@FDRY48_Etg4_40#exit^M
SSH@FDRY48_Etg4_40>

and the console:

I, [2016-05-20T15:22:21.760411 #23327]  INFO -- : Oxidized starting, running as pid 23327
I, [2016-05-20T15:22:21.852032 #23327]  INFO -- : Loaded 158 nodes
Puma 2.16.0 starting...
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://0.0.0.0:8888
W, [2016-05-20T15:23:02.136934 #23327]  WARN -- : 10.XX.XX.Xx raised Timeout::Error with msg "execution expired"
W, [2016-05-20T15:23:02.212486 #23327]  WARN -- : 10.XX.XX.XX status no_connection, retries exhausted, giving up

Thanks.

**Comment by ytti** [comment]
There should be full crash log with backtrace, can I see it. I want to know which line is raising the Timeout::Error.

**Comment by VDGAyanami** [comment]
Hi, Sorry, but I can't find any crash log file :(.

2016-05-20 16:00 GMT-04:00 ytti <notifications@github.com>:

> There should be full crash log with backtrace, can I see it. I want to
> know which line is raising the Timeout::Error.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ytti/oxidized/issues/418#issuecomment-220704521>
>



-- 
Julian Anaya

**Comment by ytti** [comment]
Is it possible to get access to one of the non-working devices with sanitised config?

**Comment by VDGAyanami** [comment]
Sorry but is not possible..

2016-05-24 10:17 GMT-04:00 ytti <notifications@github.com>:

> Is it possible to get access to one of the non-working devices with
> sanitised config?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ytti/oxidized/issues/418#issuecomment-221285286>
>



-- 
Julian Anaya

**Comment by ytti** [comment]
You could try 

```
pre_logout do
  send "exit\r\n"
  send ”exit\r\n"
end
```

Even of that works, I don't like it, because I don't understand why your version does not work. But obviously I cannot troubleshoot it very much without a device.

Why do you have ```post_login ''```

**Comment by VDGAyanami** [comment]
Thanks, this solution works, but why you don't like it??

2016-05-26 10:31 GMT-04:00 ytti <notifications@github.com>:

> You could try
>
> pre_logout do
>   send "exit\r\n"
>   send ”exit\r\n"
> end
>
> Even of that works, I don't like it, because I don't understand why your
> version does not work. But obviously I cannot troubleshoot it very much
> without a device.
>
> Why do you have post_login ''
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ytti/oxidized/issues/418#issuecomment-221888134>
>



-- 
Julian Anaya

**Comment by ytti** [comment]
I don't like why I don't understand why your solution does not work. I don't like the prospect that there might be bug in ssh.rb/telnet.rb/model.rb which is causing your observed behaviour.

**Comment by ytti** [comment]
Will close this. I'm happy review if I can get access to affected device.

**Comment by avs262** [comment]
I may be experiencing the same issue. 

The last command oxidized runs is 'show running-config' then the execution expires.

`W, [2019-04-24T19:52:55.524855 #8637]  WARN -- : x.x.x.x raised Timeout::Error with msg "execution expired"
D, [2019-04-24T19:52:55.524930 #8637] DEBUG -- : lib/oxidized/node.rb: Oxidized::SSH failed for x.x.x.x`

Then within the tail log the last line is:
`--More--, next page: Space, next line: Return key, quit: Control-c`

This is a Foundry switch and I'm using the IronWare model.
