### ISSUE TITLE
Error on startup getting fed HTTP from LibrenNMS

### ISSUE THREAD

**Issue by PENorris** [ytti/oxidized#424]
I'm getting the following error on startup with oxidized 0.14.1 trying to ingest HTTP from librenms API. The JSON returned appears correct, and I'll attach a sample output.  Any ideas on a possible cause?

sjcmis@netmon:~$ oxidized -d
resolving DNS for ...
cannot interpret as DNS name: nil
/usr/lib/ruby/2.3.0/resolv.rb:1226:in `create': cannot interpret as DNS name: nil (ArgumentError)
        from /usr/lib/ruby/2.3.0/resolv.rb:1066:in `generate_candidates'
        from /usr/lib/ruby/2.3.0/resolv.rb:1095:in `resolv'
        from /usr/lib/ruby/2.3.0/resolv.rb:522:in `fetch_resource'
        from /usr/lib/ruby/2.3.0/resolv.rb:512:in `each_resource'
        from /usr/lib/ruby/2.3.0/resolv.rb:409:in `each_address'
        from /usr/lib/ruby/2.3.0/resolv.rb:117:in `block in each_address'
        from /usr/lib/ruby/2.3.0/resolv.rb:116:in `each'
        from /usr/lib/ruby/2.3.0/resolv.rb:116:in `each_address'
        from /usr/lib/ruby/2.3.0/resolv.rb:94:in `getaddress'
        from /var/lib/gems/2.3.0/gems/oxidized-0.14.1/lib/oxidized/node.rb:17:in `initialize'
        from /var/lib/gems/2.3.0/gems/oxidized-0.14.1/lib/oxidized/nodes.rb:18:in `new'
        from /var/lib/gems/2.3.0/gems/oxidized-0.14.1/lib/oxidized/nodes.rb:18:in `block (2 levels) in load'
        from /var/lib/gems/2.3.0/gems/oxidized-0.14.1/lib/oxidized/nodes.rb:14:in `each'
        from /var/lib/gems/2.3.0/gems/oxidized-0.14.1/lib/oxidized/nodes.rb:14:in `block in load'
        from /var/lib/gems/2.3.0/gems/oxidized-0.14.1/lib/oxidized/nodes.rb:110:in `synchronize'
        from /var/lib/gems/2.3.0/gems/oxidized-0.14.1/lib/oxidized/nodes.rb:110:in `with_lock'
        from /var/lib/gems/2.3.0/gems/oxidized-0.14.1/lib/oxidized/nodes.rb:10:in `load'
        from /var/lib/gems/2.3.0/gems/oxidized-0.14.1/lib/oxidized/nodes.rb:105:in `initialize'
        from /var/lib/gems/2.3.0/gems/oxidized-0.14.1/lib/oxidized/core.rb:14:in `new'
        from /var/lib/gems/2.3.0/gems/oxidized-0.14.1/lib/oxidized/core.rb:14:in `initialize'
        from /var/lib/gems/2.3.0/gems/oxidized-0.14.1/lib/oxidized/core.rb:4:in `new'
        from /var/lib/gems/2.3.0/gems/oxidized-0.14.1/lib/oxidized/core.rb:4:in `new'
        from /var/lib/gems/2.3.0/gems/oxidized-0.14.1/lib/oxidized/cli.rb:12:in `run'
        from /var/lib/gems/2.3.0/gems/oxidized-0.14.1/bin/oxidized:9:in `<top (required)>'
        from /usr/local/bin/oxidized:22:in `load'
        from /usr/local/bin/oxidized:22:in `<main>'

Sample JSON
[
    {
        "hostname": "metro-e_adminc3560_1.co.st-johns.fl.us",
        "os": "ios"
    },
    {
        "hostname": "selibcat3550pwr_1.co.st-johns.fl.us",
        "os": "ios"
    },
    {
        "hostname": "selibc2821srst.co.st-johns.fl.us",
        "os": "ios"
    },
    {
        "hostname": "rbcat3560g48pwr_1.co.st-johns.fl.us",
        "os": "ios"
    },
    {
        "hostname": "nwannexcat3560-24ps_1.co.st-johns.fl.us",
        "os": "ios"
    },
    {
        "hostname": "utiladminc3560_1.co.st-johns.fl.us",
        "os": "ios"
    },
...

included config as well

```
username: username
password: password
model: ios
interval: 43200
log: /var/log/oxidized/log
threads: 2
timeout: 10
retries: 2
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 127.0.0.1:8888
vars: {}
groups: {}
input:
  default: ssh, telnet
  ssh:
    secure: false
output:
  default: git
  git:
    user: sjcmis
    email: o@example.com
    repo: "/opt/oxidized/oxidized.git"
source:
  default: http
  debug: true
  http:
    url: http://netmon.co.st-johns.fl.us/api/v0/oxidized
    scheme: http
    delimiter: !ruby/regexp /:/
  map:
    name: hostname
    model: os
    group: group
  headers:
      X-Auth-Token: 'TOKEN'
  vars_map:
      enable: 4
model_map:
  cisco: ios
```

**Comment by ytti** [comment]
Looks like we're trying to resolve ```nil``` value. Is there full JSON available? Maybe some is missing hostname or has empty hostname?

**Comment by PENorris** [comment]
I don't see anything like that in the output.  Including here.  All this is internal, so I'm not really concerned about posting it. 
[json_output.txt](https://github.com/ytti/oxidized/files/272983/json_output.txt)

**Comment by ytti** [comment]
Your map is key for ```source``` it should be key for ```http```, so move it few spaces to the right. As mapping does not work, we don't have expected fields, and we're returning for unknown key.

**Comment by PENorris** [comment]
That's absolutely it.  Thanks of the help.
