### ISSUE TITLE
How to limit the number of version files for every node?

### ISSUE THREAD

**Issue by manasi199** [ytti/oxidized#427]
Currenty I have 80 versions for my node. Is there a maximum limit to the number of versions for every node and how do we change that?

The following is the config file

username: admin
password:
model: eos
interval: 3600
use_syslog: false
debug: false
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 10.85.128.173:8000
vars: {}
groups: {}
input:
  default: ssh, telnet
  debug: false
  ssh:
    secure: false
output:
  default: git
  git:
    user: Oxidized
    email: 
    repo: "/home/arista/.config/oxidized/devices.git"
source:
  default: csv
  csv:
    file: "/home/arista/.config/oxidized/router.db"
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
model_map:
  cisco: ios
  juniper: junos
  arista: eos

**Comment by ytti** [comment]
There is no maximum limit for file versions in Git. It would probably also be complicated to reduce versions in Git.

**Comment by manasi199** [comment]
Ok.Thanks.

**Comment by ytti** [comment]
If you really need this, I would ask in git related forums how to accomplish. I am sure there is a way, like there is a way to delete something from git repo, it's just not entirely trivial. I'm closing this, as this isn't something I'm looking to support directly off output/git.rb, and likely would not accept patch if it was added.

Good luck.

**Comment by manasi199** [comment]
Ok.Thank You
