### ISSUE TITLE
Trying to run Oxidized as a service in Solaris (SmartOS zone)

### ISSUE THREAD

**Issue by KebabatronGTR1000v** [ytti/oxidized#428]
Hi,

I can run oxidized fine from the cli, but I'm trying to get it to run as a service now and its crashing with the error below:

I'm a newbie to all this so it doesn't mean much to me.  I had a quick look at the files at the line numbers its referencing and couldn't see anything obvious.

I think its something to do with it not knowing about the config file, but not sure?

The svcadm is exectuting the following:

/opt/local/bin/ruby21 /opt/local/bin/oxidized /root/.config/oxidized/config

Any ideas?!
Cheers!
Jon.

```
`[ May 22 08:55:47 Executing start method ("/opt/local/bin/ruby21 /opt/local/bin/oxidized /root/.config/oxidized/config"). ]
no implicit conversion of nil into String
/opt/local/lib/ruby/gems/2.1.0/gems/oxidized-0.14.2/bin/oxidized:12:in `rescue in <top (required)>': undefined method `config' for Oxidized:Module (NoMethodError)
        from /opt/local/lib/ruby/gems/2.1.0/gems/oxidized-0.14.2/bin/oxidized:7:in `<top (required)>'
        from /opt/local/bin/oxidized:23:in `load'
        from /opt/local/bin/oxidized:23:in `<main>'
[ May 22 08:55:47 Stopping because service exited with an error. ]
[ May 22 08:55:47 Failing too quickly, throttling. ]`
```

**Comment by ytti** [comment]
I'm stumped. Essentially it's crashing because Oxidized module does not define #config method. But it does, here: https://github.com/ytti/oxidized/blob/master/lib/oxidized.rb#L24

Do you have >1 ```lib/oxidized.rb``` file in system, and is some of them missing that. My only thought is somehow broken installation.

**Comment by KebabatronGTR1000v** [comment]
It seems to run fine from the cli.  Maybe SmartOS (solaris) does something
under the hood.

I'll check for that file...

**Comment by ytti** [comment]
What's the status of this issue?

**Comment by KebabatronGTR1000v** [comment]
Gave up on it used oxidised on debian

**Comment by ytti** [comment]
Ok,  if you want to give it another go, let me know. If you can setup sanitsed solaris box, I'm happy to take a shot at it, I'm pretty confident I can get it working.

**Comment by KebabatronGTR1000v** [comment]
OK when I get chance I will... Cheers!
