### ISSUE TITLE
Fails silently with broken router.db

### ISSUE THREAD

**Issue by RichiH** [ytti/oxidized#43]
https://github.com/ytti/oxidized/issues/32

Sorry for re-opening, but this is not closed.

At the very least, it should print lines it can not interpret so the admin sees what's happening. Ideally, also expose that information in the web UI. Maybe create & link a "warning" page if any warnings occur.

**Comment by ytti** [comment]
Any update?

**Comment by ytti** [comment]
Closed due to inactivity.

**Comment by RichiH** [comment]
Dunno, you could at least try and see if you always have the required number of fields coming out of the CSV.

Also, erroring out loudly while starting is, imo, preferably over simply not starting at all.

I did _not_ try the current version against this, though.

**Comment by ytti** [comment]
I guess the minimum amount of fields is 1, as rest can use default (model, user, password etc). So any linetrash line could be considered hostname. Now it would tell that it couldn't resolve those.

When does it not start at all? I think it would start with 0 nodes just fine?
