### ISSUE TITLE
Brocade NOS timestamp in config file..

### ISSUE THREAD

**Issue by ThomasADavis** [ytti/oxidized#432]
Node name: env-d8-brocade-sw2
Group Name: brocade
Job Time: 10.388331618
Git Commit ID: 692204065399f2f157abfa03cb3b8a6c59565a19
Git Repo: 
Local working dir: 

diff --git a/env-d8-brocade-sw2 b/env-d8-brocade-sw2
index 622eed3..b70d32e 100644
--- a/env-d8-brocade-sw2
+++ b/env-d8-brocade-sw2
@@ -83,7 +83,7 @@
 ! Factory Part Num:      	40-1000925-06
 ! Factory Serial Num:    xxxxxxxxx
 ! Manufacture:           	Day:  9  Month:  9  Year: 15
-! Update:                	Day: 22  Month:  5  Year: 2016
+! Update:                	Day: 23  Month:  5  Year: 2016
 ! 
 ! Airflow direction : Port side EXHAUST
 ! 

The Update: line changes once a day.  How do I get rid of it?   I tried to add it the nos.rb file; it's coming from the 'show chassis' command.

ie:

  cmd 'show chassis' do |cfg|
    comment cfg.each_line.reject { |line| line.match /Time/ or line.match /Update:/ }.join
  end

does not seem to get rid of it.

**Comment by ytti** [comment]
I see no reason why that wouldn't work. I can't help to notice that in your diff there is diff for the same line, with no particular changes visible.

Are you sure you've changed the correct file? There is 'nos.rb' for every oxidized version you've installed.

**Comment by ThomasADavis** [comment]
I'll check again.  The tick is the day went from 22 to 23.  That line updates once a day, and it's the current date (eh, why?)

**Comment by ytti** [comment]
One bet is to put the fine in ~/.config/oxidized/model/ directory, which is then used, instead of distribution version.

**Comment by ThomasADavis** [comment]
Ok, I did that.  Have to wait now and see if it works.  This only happens once a day.

**Comment by ytti** [comment]
You could XIIT. Copy the old repo to safe keeping. Do some commit on the repo. Wait for next run. It'll commit, because document has changed.

**Comment by ThomasADavis** [comment]
Copying the model over to the .config directory worked; as soon as I restarted the daemon, it sent email showing the Update line was removed from the config (old vs. new).

So, yea, for Brocade NOS v7, it needs the line as posted above, otherwise it changes every day.

Should I generate a PR for this?

**Comment by ytti** [comment]
Yes please generate PR. You can mark on the commit message fixes #432 somewhere, and after I accept the PR, it should close the ticket with reference to the commit.

**Comment by ThomasADavis** [comment]
Done; please see #459

**Comment by ytti** [comment]
Thanks!
