### ISSUE TITLE
Override options per device is not working?

### ISSUE THREAD

**Issue by FTBZ** [ytti/oxidized#434]
I'm implementing Oxidized and I can't use login/password per device. Only the default in the configuration is working. It's annoying because we have a mix of many device types with different access. I'm missing something?

**Comment by ytti** [comment]
We do support authentication:

 1. global
 2. per group
 3. per device

Why it's not working is hard to say. Your configuration and example of source data should help forward.

**Comment by FTBZ** [comment]
OK, I didn't use group. I set username / password in the config file and try to use specific password in router.db. If I set password in router.db it take always the config username/password and never try the router.db password. It's right?

**Comment by ytti** [comment]
It's not right. It should work, but why it does not work, is very difficult to tell, without seeing your configuration.

**Comment by FTBZ** [comment]
> ---
> username: XXXX
> password: XXXXX
> interval: 60
> use_syslog: false
> debug: false
> threads: 30
> timeout: 20
> retries: 3
> prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
> rest: oxidized.xxx.xxx:8888
> vars: {}
> groups: {}
> input:
>   default: ssh
>   debug: false
>   ssh:
>     secure: false
> output:
>   default: git
>   git:
>     user: Oxidized
>     email: XXX
>     repo: "/var/oxidized/devices.git"
> source:
>   default: csv
>   csv:
>     file: "/root/.config/oxidized/router.db"
>     delimiter: !ruby/regexp /:/
>     map:
>       name: 0
>       model: 1
> model_map:
>   cisco: iOS
>   juniper: junos
> vars:
>    enable: XXXX

This is a test configuration, not a production one. "enable" was added because the information in router.db were not used.

**Comment by ytti** [comment]
You don't map ```username``` or ```password``` to any field in the router.db

**Comment by FTBZ** [comment]
Thanks! Stupid me.
