### ISSUE TITLE
F5 login into tmsh mode instead of bash shell

### ISSUE THREAD

**Issue by joshrain** [ytti/oxidized#437]
when i login to an f5 device i am given the tmsh shell instead of bash.

the tmos.rb model expects a bash shell.

i tried to modify tmos.rb to first run the following cmd:

cmd('run /util bash') { |cfg| comment cfg }  ## this is so it enters bash mode and run the remaining cmds but it hangs.

**Comment by ytti** [comment]
I don't have any F5 device, so I can't really comment. Maybe @mikebryant can chime in.

**Comment by mikebryant** [comment]
It's not something we've tested - we just configured the F5s to allow bash shell logins for the collector user.

**Comment by ytti** [comment]
It would be terrible tax to pay, as we cannot run ```exec``` mode then, as we won't know which type of commands to send. Unless of we make some ```tmos_bash: false``` variable.

I would discourage this.

**Comment by ytti** [comment]
@joshrain is it acceptable to make bash user?

**Comment by nowell29morris** [comment]
This is a bit of a stretch, but what if calling bash was used like an enable password?  Correct me if I am wrong, but setting yourself to enable mode is like calling a new shell inside of your first shell.  Why not call bash?

I am facing this same difficulty with F5s on 11.X and priv users are domain driven.  I will have to give this a shot, and unfortunately go through about four people to ask them to set the shell of my user to bash in the AD unix utils.

**Comment by ytti** [comment]
We can definitely do it, it just means 'exec' mode won't, and we need to do screen scraping. 
As long as it works for @joshrain @mikebryant and @nowell29morris I'm happy with it.

If it were my device, I'd make oxidized users shell bash, to avoid evils screen scraping.

**Comment by nowell29morris** [comment]
The problem we are facing here is a design decision F5 made for this version.  You can either have privileged accounts locally or via the domain, but not both.  When you use a domain account, privileged or not, you cannot specify bash as your shell like you could in a traditional /etc/passwd sense.  Maybe we make tmos.rb and tmos11.rb so that in these specific instance/version of tmos you can sacrifice 'enable' for bash.  Or am I requesting too much at this point? :)

**Comment by ytti** [comment]
I get that. I don't think we need two models. I'm ok changing this into screen-scraping, after which it's easy to enter bash shell, like you explained.

**Comment by matt-wells-m451** [comment]
I've taken over this item for nowell29morris.  First thanks for all the help on this one.  
What action items can I do to assist on this one?

**Comment by clay584** [comment]
F5 devices configured with local or remote authentication allow for setting tmsh or advanced shell (bash) for the default shell for a user.  If a user is not set for advanced shell, then simply running "run util bash" from tmsh will drop you straight into bash.  If this is the case, you could just run "run util bash" upon successful login, and then doing whatever the rb module does, then issue "exit" to go back into tmsh, and then "quit" to gracefully disconnect.

**Comment by Patrik-Netent** [comment]
There is no way to jump to bash when using remote authorization. Refer to https://support.f5.com/csp/article/K10272 for more information.

![image](https://user-images.githubusercontent.com/53431903/62141559-0efd8600-b2ed-11e9-9b56-0d39139522ca.png)

**Comment by oroomans** [comment]
I got the same issue. 

I tried to adapt tmos.rb by adding this line at the beginning of the file : 

cmd "bash" 

to force to switch to bash context, but then it just hangs after the command is sent. 
I don't see anything in the debug. 

I'm not used to ruby so not sure of what I'm doing :).

**Comment by lucdnb** [comment]
Hi friends.
I know that this topic have a lot of time, but i've need make this solution works too.
So, searching for a mode to do, I've think if maybe we can send a tmsh command "inside" a bash but inside the tmsh (default terminal). Yes, crazy idea.

But it works. Just edit the "tmos.rb" file, puting the follow command before each "tmsh" command:
run /util bash -c
An example line: 'run /util bash -c "tmsh -q show sys version"'
or e.g. in the "tmos.rb" file we have:
cmd('run /util bash -c "tmsh -q show sys version"') { |cfg| comment cfg }

It works great and fill my needance.

Cheers.

**Comment by Reidy10** [comment]
Hi @lucdnb 

I would like to get this working as you have suggested, but my attempt at it hasn't worked thus far. Would it be possible for you to share your tmos.rb in full? Do you have it your .config/oxidized/model directory? Last question, to activate it do I need to restart the oxidized.service?

Thanks

**Comment by lucdnb** [comment]
Hello @Reidy10
Assuming that your F5 device enter in "tmsh" shell directly via SSH connection, you have to told to Oxidized model to run this: 'run /util bash -c' before the command:

<img width="290" alt="image" src="https://user-images.githubusercontent.com/69991829/211050027-f073367b-d83f-4cc1-86c1-ef9cfb7eeedf.png">

Remember to create a backup for your model (.rb file), maybe you will have use the default tmos.rb file for other F5.

Attached my 'tmos.rb' file that I edited to accomplish my requirements (rename it for .rb).

[tmos.txt](https://github.com/ytti/oxidized/files/10361406/tmos.txt)

Yes, you need to restart the Oxidized proccess when you make changes in models or config file.
When you make changes just on 'router.db' file, you don't need to restart the proccess, just click "Reload" button at Oxidized web interface.

**Comment by eslott** [comment]
I wanted to follow up on this specific issue. I updated my tmos.rb file with the above RB, however, I'm getting the same output. Was there anything else that needed to be done?
