### ISSUE TITLE
Interval Setting

### ISSUE THREAD

**Issue by R4v3nH0lm** [ytti/oxidized#438]
New guy here. 

Really like the project but while deploying in my lab I wanted to shorten the interval for rapid checking of changes made to my devices. After reviewing the documentation there is not mention of what unit of measurement the interval uses (ie: minutes, seconds, mili-seconds). After starting oxidized with a interval of 1 the time stamps came back ranging showing a interval of 8 or 9 seconds:
I, [2016-05-25T18:02:01.986619 #10358]  INFO -- : Configuration updated for /192.168.0.10
I, [2016-05-25T18:02:10.994656 #10358]  INFO -- : Configuration updated for /192.168.0.10
I, [2016-05-25T18:02:19.001771 #10358]  INFO -- : Configuration updated for /192.168.0.10
I, [2016-05-25T18:02:28.009091 #10358]  INFO -- : Configuration updated for /192.168.0.10
I, [2016-05-25T18:02:36.016057 #10358]  INFO -- : Configuration updated for /192.168.0.10
I, [2016-05-25T18:02:44.023574 #10358]  INFO -- : Configuration updated for /192.168.0.10
I, [2016-05-25T18:02:52.030231 #10358]  INFO -- : Configuration updated for /192.168.0.10
I, [2016-05-25T18:03:01.038663 #10358]  INFO -- : Configuration updated for /192.168.0.10
I, [2016-05-25T18:03:10.046078 #10358]  INFO -- : Configuration updated for /192.168.0.10
I, [2016-05-25T18:03:18.055078 #10358]  INFO -- : Configuration updated for /192.168.0.10
I, [2016-05-25T18:03:26.060271 #10358]  INFO -- : Configuration updated for /192.168.0.10

It may be that part of the offset is from the amount of time a polling takes to complete but figured it was best to ask for a definitive answer.

**Comment by ytti** [comment]
Yeah documents are lacking. The interval number is in seconds. Obviously the work of logging into given device and getting config takes longer, so probably 8-9s is as fast as we can do single device. We won't try to do single device multiple times in parallel.

**Comment by R4v3nH0lm** [comment]
Got it, thanks for the info Ytti.
