### ISSUE TITLE
run set of commands on nodes

### ISSUE THREAD

**Issue by davama** [ytti/oxidized#449]
I know that oxidized purpose is for backup configuration. This question goes outside of that scope.

What if i want to run a set of commands on all my, let's say procurve, switches?
Ex:
```
conf terminal
logging facility local3
end
wr mem
```
Changes would obviously need to be non-destructive (_user's discretion_)

If you haven't shut me off to the idea at this point, this is was i was imagining. :-)

So, have some directory defined in ~/.config/oxidized/config file
`external_cmds: /dir/to/run/cmds/
`
In that directory one would have file(s) to run for specific devs depending on HW type
```
ios.txt
procurve.txt
nxos.txt
etc
```
Inside those txt files one would have the line(s) they want to run. 
In my example i would have the `logging cmds` inside the procurve.txt file.

Of course there would be some reference in the \<dev\>.rb files to the `external_cmds` directory  defined in config and restarting the oxidized service will need to happen.
Hope it makes sense.

Granted, one can just script the changes and voilà but just a thought.

Thank you for the continued support!

Dave

**Comment by ytti** [comment]
I beat myself up regularly for not making Oxidized client to a more general purpose router API.

We have [oxidized-script)[ytti/oxidized-script] which can be used to programmatically access devices, it even has CLI to send commands from flat ascii file.

Unfortunately the solution isn't as clear from implementation point of view as it should be, were Oxidized redesigned into API and client.

Or are you meaning use case which is not really addressed by ```oxidized-script```?

**Comment by davama** [comment]
The [oxidized-script](https://github.com/ytti/oxidized-script) is pretty sweet. Dint know we could do that. This will actually help facilitating HP scripting. (always had issues with these guys)

But i was just wondering more of an automated solution. 
[Oxidized](https://github.com/ytti/oxidized) goes and _pulls_ config from device. Could we _put_ a set of commands if one wanted to?

```
cmd1
cmd2
cmd3
```

Let it ride for a week, check configs for who didnt get added and then pull the change from the oxidized process.

Thanks

**Comment by ytti** [comment]
```oxidized-script```` has CLI ```oxs``` which can push set of commands from file to a device. But maybe your use-case somehow ties into configuration generation, I may not fully understand it yet.

**Comment by davama** [comment]
Yes configuration generation is the phrase. (again all this is possible via script or some network management tool, need some hard $$$ for that)

Basically automate changes to the devices using the already running oxidized process. (which hits every device all the time, if it fails it'll just loop again and retry)

Hope it's clearer now.

Thanks

**Comment by ytti** [comment]
I'm sure what advantages that'll give to user compared to doing the provisioning work from oxidized-script.

**Comment by davama** [comment]
Hehe
Advantage? aside from being efficient/lazy (call it what you will) :P , probably none

I guess a manual oxidized-script push it is. (which i started to use. very neat)
Thanks! :D 
dave

**Comment by danilopopeye** [comment]
@davama can we close this issue?

**Comment by davama** [comment]
Closing.
Thanks
