### ISSUE TITLE
Provide upstart, systemd, initd scripts

### ISSUE THREAD

**Issue by ytti** [ytti/oxidized#45]
Provide example of startup scripts for common systems

**Comment by MrRJ45** [comment]
I'm using supervisord on Debian to run, and keep oxidized running:

[program:oxidized]
command=/usr/local/bin/oxidized
autostart=true
autorestart=true
user=oxidized
stderr_logfile=/var/log/oxidized.err.log
stdout_logfile=/var/log/oxidized.out.log
environment=HOME='/home/oxidized/'

**Comment by ytti** [comment]
@sts  @andrewpwade @MrRJ45
 
How do we solve this issues?

Is it sufficient to have those examples in /extra? Do we need to do more?

**Comment by andrewpwade** [comment]
If you were to integrate init scripts, the right place would probably be in a package (deb/rpm etc), but you're currently not packaging oxidized. Personally I would find it too much of a burden to worry about upstart/init/systemd (and packaging and packaging guidelines). 

You could document some example startup script configurations if you wanted to be nice, but really, oxidized does not need any special configuration.

**Comment by MrRJ45** [comment]
I would agree, oxidized is aimed at people who *should* be technical enough to copy an example file to the appropriate location. :)

**Comment by ytti** [comment]
Closing as we have 3 examples, which seems to be sufficient to get cracking.
