### ISSUE TITLE
Package oxidized for Debian (and Ubuntu)

### ISSUE THREAD

**Issue by wk** [ytti/oxidized#453]
A packaged release of oxidized for Debian and Ubuntu made available as part of upstream in the upcoming releases of these distributions would reduce deployment complexity for existing (non-developer) users, especially those less familiar with Ruby and its ecosystem. It would also benefit new users looking to experiment with oxidized.

Currently, the bits and pieces all exist in the repository, including init scripts for both upstart and systemd.

An invocation of [gem2deb](https://wiki.debian.org/Teams/Ruby/Packaging) on oxidized on a recent release of Ubuntu (Xenial) encounters two issues:
- [x] Version-locked dependency on slop v3.4 has to be eliminated, ytti/oxidized#452
- [ ] Generated debian/control file has to be manually corrected to match release epoch for ruby-net-ssh

Further, the following additional work is required for a turn-key package
- [ ] Generated package needs to have upstart and systemd init scripts slipstreamed from /extra

**Comment by ytti** [comment]
I am not going to do this. I'm happy to accept PR for this.
