### ISSUE TITLE
Where do I put custom models?

### ISSUE THREAD

**Issue by refj** [ytti/oxidized#455]
Hi,

Thanks for oxidized.

What is the best way to include custom models? I would like to keep the custom models out of the standard gem path so I can upgrade oxidized in future and version control them with git.

Br,
Rasmus

**Comment by ytti** [comment]
You can put models in ~/config/oxidized/model directory.

I encourage doing pull request if it is commercially available device.

**Comment by refj** [comment]
Great!

When we're done tinkering I submit a pull request.
