### ISSUE TITLE
Last Configuration Change constantly updated

### ISSUE THREAD

**Issue by nebriv** [ytti/oxidized#456]
We've started to deploy Oxidized to all of our network equipment and have noticed a strange occurrence with the Last Configuration Change line being changed but no other changes taking place on the device. We are seeing this on a Cisco Switch 3560X. Heres an example:

!
!
-! Last configuration change at 14:20:32 UTC Tue May 31 2016 by *username*
+! Last configuration change at 09:29:53 UTC Thu Jun 2 2016
! NVRAM config last updated at 14:29:48 UTC Tue May 31 2016
!

Is there anyway to ignore these lines IF there are no other changes to the config? We can't seem to figure out what is causing the last config change line to constantly change otherwise I'd try to fix that first.

**Comment by ytti** [comment]
Perhaps someone enters config mode and exits it, without changing config?

You should see 'show log' someone entering config mode. Or if you do TACACS command accounting, you should see it in TACACS logs.

It would be trivial to filter these from backups, and I'm ready to do it, if someone gives rationale why it might be normal behaviour to regularly jump in config mode without changing config.

**Comment by nebriv** [comment]
Thats what we were thinking as well. I've checked around with the team to see if they were hitting the affected switches and it doesn't seem like it. I'll check the logs as well though to confirm.

I think it'd make since to filter it from backups (or perhaps add it as a variable?) to avoid cluttering up the git repos. Although some people might want to know, and have a record, if someone is opening config mode and then not changing anything.

**Comment by ytti** [comment]
Aren't you curious why it is happening? I mean, it seems like it exposed situation that you didn't know that is happening and situation you think should not be occurring?

**Comment by nebriv** [comment]
Yeah absolutely - thats why it piqued my interest in the first place. We'll look into solving the root cause first. Thanks!

**Comment by nebriv** [comment]
Alright - I think we've got this figured out.

The affected devices are only switches we have Cisco ISE deployed on. Correlating the logs on the switches to the update times on Oxidized shows that ISE is connecting to the switch (via SNMP) at that time. 

So this is definitely something we can safely ignore. Would it be possible to make this a config variable per group, so that way you can enable for switches, but not for other devices that ISE doesn't communicate with?

**Comment by ytti** [comment]
I propose that you complain to Cisco, stop them from entering config if they don't plan to change configs, creating false positives. But of course that'll take time to fix. In the mean time, maybe something like this:

```
vi ~/.config/oxidized/model/ios.rb
require 'oxidized/model/ios'
class IOS 
    cmd 'show running-config' do |cfg|
      cfg = cfg.each_line.to_a[3..-1]
      cfg = cfg.reject { |line| line.match /^ntp clock-period / }.join
      cfg.gsub! /^Current configuration : [^\n]*\n/, ''
      cfg.gsub! /^Last configuration change at/, '' if vars(:__nebriv_cisco_ise)
      cfg.gsub! /^\ tunnel\ mpls\ traffic-eng\ bandwidth[^\n]*\n*(
                  (?:\ [^\n]*\n*)*
                  tunnel\ mpls\ traffic-eng\ auto-bw)/mx, '\1'
     
      cfg
  end
end
```

not tested, but idea is that you make your own model, based on existing model where you ignore that line if variable __nebriv_cisco_ise is set.

**Comment by nebriv** [comment]
For future reference if anyone has this issue. I modified the ios model to include the following lines:
```
  cmd 'show running-config' do |cfg|
    cfg = cfg.each_line.to_a[3..-1]
    cfg = cfg.reject { |line| line.match /^ntp clock-period / }.join
    cfg.gsub! /^Current configuration : [^\n]*\n/, ''
    **if vars :ignore_last_config
       cfg.gsub! /^! Last configuration change at .*/, ''
       cfg.gsub! /^! NVRAM config last updated  .*/, ''
       Oxidized.logger.debug "Ignoring Last Configuration Change line #{node.name} per config variable \'ignore_last_config\'"
    end**
    cfg.gsub! /^\ tunnel\ mpls\ traffic-eng\ bandwidth[^\n]*\n*(
                  (?:\ [^\n]*\n*)*
                  tunnel\ mpls\ traffic-eng\ auto-bw)/mx, '\1'
    cfg
  end
```

I then modified my config to include the variable:
```
groups:
  ise_switches:
    vars:
      ignore_last_config: true
```

Thanks for your help ytti, and for Oxidized in general!
