### ISSUE TITLE
fix memory leak

### ISSUE THREAD

**Issue by ytti** [ytti/oxidized#46]
Oxidized probably leaks memory:

aug 14th
rancid   14581  5.1 26.6 1186764 271472 pts/9  Sl+  Jul29 1191:01 ruby /var/rancid//.rvm/gems/ruby-2.1.2/bin/oxidized 

aug 19th
rancid   14581  5.5 27.6 1187792 281764 pts/9  Sl+  Jul29 1683:14 ruby /var/rancid//.rvm/gems/ruby-2.1.2/bin/oxidized                                                            

This is with some 4k nodes (with 1h rotation), some new boxes may have been added in between, but shouldn't explain the increase.

I've done some research into this, but it's not exactly trivial to troubleshoot memory use in MRI. It might also be better if instead trying to fix this, we refactor Nodes class out or at least make keep in memory at once only nodes being worked on, store it in disk in SQLite and get data from there. Would also give persistence on stats etc.

**Comment by marnovdm** [comment]
Just wanted to confirm that it appears to be leaking memory here as well. Left it running for a week with just a bit under 900 devices and at the moment the web-ui is extremely slow. It does seem to be still running config backups though.

    oxidized 18397  4.7  5.8 757044 121136 ?       Ssl  Nov03 466:59 /usr/bin/ruby2.1 /usr/local/bin/oxidized

    root@cbu001:~ # free -m
                 total       used       free     shared    buffers     cached
    Mem:          2010       1938         71          7        150        179
    -/+ buffers/cache:       1608        402
    Swap:          951         11        940

And ps wauxf shows defunct python processes;

    oxidized 18397  4.7  5.8 757044 121120 ?       Ssl  Nov03 467:21 /usr/bin/ruby2.1 /usr/local/bin/oxidized
    oxidized 29855  0.0  0.0      0     0 ?        Z    Nov05   0:02  \_ [python] <defunct>
    oxidized 29963  0.0  0.0      0     0 ?        Z    Nov05   0:01  \_ [python] <defunct>
    oxidized 29998  0.0  0.0      0     0 ?        Z    Nov05   0:01  \_ [python] <defunct>
    oxidized 30000  0.0  0.0      0     0 ?        Z    Nov05   0:01  \_ [python] <defunct>
    oxidized 11008  0.0  0.0      0     0 ?        Z    Nov05   0:02  \_ [python] <defunct>
    oxidized  4602  0.0  0.0      0     0 ?        Z    Nov05   0:04  \_ [python] <defunct>
    oxidized  5894  0.0  0.0      0     0 ?        Z    Nov06   0:01  \_ [python] <defunct>
    oxidized  5896  0.0  0.0      0     0 ?        Z    Nov06   0:01  \_ [python] <defunct>
    oxidized  5898  0.0  0.0      0     0 ?        Z    Nov06   0:02  \_ [python] <defunct>
    oxidized  5902  0.0  0.0      0     0 ?        Z    Nov06   0:01  \_ [python] <defunct>
    oxidized 17670  0.0  0.0      0     0 ?        Z    Nov06   0:07  \_ [python] <defunct>
    oxidized 27117  0.0  0.0      0     0 ?        Z    Nov06   0:03  \_ [python] <defunct>
    oxidized 27162  0.0  0.0      0     0 ?        Z    Nov06   0:04  \_ [python] <defunct>
    oxidized 27236  0.0  0.0      0     0 ?        Z    Nov06   0:04  \_ [python] <defunct>
    oxidized 27256  0.0  0.0      0     0 ?        Z    Nov06   0:05  \_ [python] <defunct>
    oxidized 27263  0.0  0.0      0     0 ?        Z    Nov06   0:04  \_ [python] <defunct>
    oxidized 27286  0.0  0.0      0     0 ?        Z    Nov06   0:05  \_ [python] <defunct>
    oxidized 30892  0.0  0.0      0     0 ?        Z    Nov06   0:04  \_ [python] <defunct>
    oxidized  6992  0.0  0.0      0     0 ?        Z    Nov06   0:01  \_ [python] <defunct>
    oxidized  6998  0.0  0.0      0     0 ?        Z    Nov06   0:04  \_ [python] <defunct>
    oxidized  7005  0.0  0.0      0     0 ?        Z    Nov06   0:05  \_ [python] <defunct>
    oxidized  7010  0.0  0.0      0     0 ?        Z    Nov06   0:04  \_ [python] <defunct>
    oxidized  7487  0.0  0.0      0     0 ?        Z    Nov06   0:04  \_ [python] <defunct>
    oxidized 13813  0.0  0.0      0     0 ?        Z    Nov07   0:04  \_ [python] <defunct>
    oxidized 13819  0.0  0.0      0     0 ?        Z    Nov07   0:03  \_ [python] <defunct>
    oxidized 13831  0.0  0.0      0     0 ?        Z    Nov07   0:02  \_ [python] <defunct>
    oxidized 13939  0.0  0.0      0     0 ?        Z    Nov07   0:01  \_ [python] <defunct>
    oxidized 14010  0.0  0.0      0     0 ?        Z    Nov07   0:02  \_ [python] <defunct>
    oxidized  6196  0.0  0.0      0     0 ?        Z    06:25   0:02  \_ [python] <defunct>
    oxidized  6201  0.0  0.0      0     0 ?        Z    06:25   0:03  \_ [python] <defunct>
    oxidized  6244  0.0  0.0      0     0 ?        Z    06:26   0:02  \_ [python] <defunct>
    oxidized  6460  0.0  0.0      0     0 ?        Z    06:27   0:01  \_ [python] <defunct>
    oxidized 18028  0.8  0.0      0     0 ?        Z    08:59   0:05  \_ [python] <defunct>
    oxidized 18042  0.2  0.0      0     0 ?        Z    08:59   0:01  \_ [python] <defunct>

Though those could be my python eventhandler which I'm still testing, don't know if Oxidized does anything with Python itself or only Ruby.

After a Oxidized restart the memory use looks like this:

    ps wauxf | grep oxidized
    oxidized 18836 82.9  1.3  93052 27928 ?        Rsl  09:13   1:03 /usr/bin/ruby2.1 /usr/local/bin/oxidized

                 total       used       free     shared    buffers     cached
    Mem:          2010       1828        182          7        150        180
    -/+ buffers/cache:       1496        513
    Swap:          951         11        940

I hope this is somewhat useful in analysing the issue. If I can provide any more information please let me know!

**Comment by ytti** [comment]
Huh, why would there be python processes, we don't use it for anything, that's strange.

Anyhow I think the whole core is wrong now to keep state in memory. We should have nodes, queues etc in sqlite, and only in memory have the nodes which are running in threads right now.

I have idea how to do it, but I'm not currently actually in need for it, so motivation is low to refactor the  core to move state to disk.
I don't think it's very sensible to even try to fix this, as regardless how you fix it, notion that the more devices you have, the more memory you need is broken, especially when getting node information fast isn't important at all, sqlite is more than fast enough for that.

**Comment by marnovdm** [comment]
The python processes are probably an event handler (hook) for oxidized which I'm testing, so not an issue with this project then.

I'll monitor memory usage for the next few weeks, we'll probably have to run smaller instances. Thanks for your response!

**Comment by udhos** [comment]
I think I'm hitting this leak with oxidized-0.14.3.

**Comment by ytti** [comment]
How do you diagnose it. How many nodes you have. How long has process been running.  Are you running any hooks? What source you're using? How often you reload source? Which ruby are you running?

Memory debugging in ruby is absolutely PITA in MRI, in JVM it would be much better.

**Comment by udhos** [comment]
oxidized 0.14.3
ruby 2.1.5p273
router.db entries: 1150

No hooks.
Outputting to both filesystem and git.

Some config parameters:
 interval: 43200 # 12 hours
 debug: true
 threads: 60
 timeout: 1800

Last time it took 9 hours to grow to about VM=723M RSS=442M then was removed by oom-killer.

Trying to figure out whether its memory usage would stabilize if it had more room to expand.

**Comment by ytti** [comment]
Could you try with ruby2.3? (rvm might be convenient way to install it temporarily and just for oxidized user, literally two commands to install and set it up).

Would be also indeed good if you could even graph it and have bit more spare, to see if it always constant rate or if it starts to level or pick up pace.

**Comment by andreas1o** [comment]
I have this issue also with 

ruby --version
ruby 2.2.5p319 (2016-04-26 revision 54774) [x86_64-linux-gnu]
oxidized --version
0.18.0
router.db 
268 devices 


interval: 3600
log: /home/X/.config/oxidized/log
debug: true
threads: 30
timeout: 120
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: X:8888
vars: {}
input:
  default: ssh, telnet
  debug: /home/X/.config/oxidized
  ssh:
    secure: false
output:
  default: git
  git:
    user: X
    email: X
    repo: "/home/X/.config/oxidized/configs/"
model_map:
  cisco: ios
  juniper: junos
  extreme: xos
  fortigate: fortios
  Fortios: fortigate
  hpmsm: procurve
groups:
  default:
    username: X
    password: X
  cust-external:
    username: X
    password: X
  hoteluppsala:
    username: X
    password:X
  xite-internal:
    username: X
    password: X
source:
  default: csv
  csv:
    file: /home/X/.config/oxidized/router.db
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
      username: 2
      password: 3
    vars_map:
      ssh_port: 4


I will monitor this over time and see how the memory grows. What commands do you want me to run to see this ?

**Comment by ytti** [comment]
I don't anymore have access to device with sufficient scale to see this issue. Some growth is expected at least until 10 runs have passed.
Best bet would be try with ruby2.3 to see how it compares in memory use. Troubleshooting itself is not exactly trivial and not practically reasonable to do remotely over github issues.

**Comment by wk** [comment]
This has not been seen in the wild for a number of years, and many changes have taken place since this bug has been observed across the entire stack (Ruby interpreter, Oxidized, dependencies).

Closing this as stale.
