### ISSUE TITLE
Dockerfile is missing rugged

### ISSUE THREAD

**Issue by dandunckelman** [ytti/oxidized#461]
I'm trying to use the docker container to test this along with the ability to push to a remote git repo (in our case, it's in a private Gitlab server).  When I start the container, I get this error (added newlines for readability):
```
E, [2016-06-06T20:43:05.217935 #20] ERROR -- : Hook push_to_remote_gitlab_repo (#<GithubRepo:0x00000001b17208>)
  failed (#<NameError: uninitialized constant GithubRepo::Rugged>) for event :post_store
```

I assume the Dockerfile simply needs to add `gem install rugged`, but I'll test it out locally and hopefully have a PR to follow

**Comment by dandunckelman** [comment]
Unfortunately, adding the install of the **rugged** gem didn't make the error go away.

**Comment by dandunckelman** [comment]
Err, nvm.  That wouldn't solve it as the gem is installed when the oxidized gem is installed.

**Comment by ytti** [comment]
@ElvinEfendi or @danilopopeye might know right off the bat what is going wrong. But it indeed seems like rugged is not loaded. My initial suspicion is that you've not setup output to git, and thus rugged is not loaded, and thus push_to_remote_gitlab_repo does not work (no git repo, nothing to push).

**Comment by dandunckelman** [comment]
Found out that I needed to add `default: git` to the **output** section, which seemed to solve it.

**Comment by GennadySpb** [comment]
thanks @dandunckelman thanks for the tip!

For those looking how to resolve `NameError: uninitialized constant GithubRepo::Rugged` on triggering **githubrepo** hook:
you should use `output: git` (not `output: file`). This will trigger load ruby gem Rugged on oxidized startup/loading stage.

For details check https://github.com/ytti/oxidized/blob/master/docs/Outputs.md#output-git & https://github.com/ytti/oxidized/blob/master/docs/Outputs.md#output-file
