### ISSUE TITLE
organizing/renaming outputs?

### ISSUE THREAD

**Issue by perceptionexe** [ytti/oxidized#464]
I'm trying to find a way to modify the filename that outputs are stored as, on a node by node basis.  Is there a map variable for this?  Is there a way to write to a varying destinations?

For example, i'm trying to get outputs for multiple switches to write to a specific directory (say, a folder called switches), and have each file represented by that switch's specific moniker.  In turn, i'd like the outputs for my firewalls to be written to a different directory (say, a folder called firewalls) and also have filenames based on moniker.

Part of my problem is that the majority of the devices i'm pulling from are NAT'd, so I specify a different SSH ports using 'var_map' but the files are still saved as the hostname/IP, which has several devices behind it just at different ports.

Thank you!

**Comment by ytti** [comment]
You should be able to accomplish this with groups. 

But I would accept hook also which allows name changes.

**Comment by perceptionexe** [comment]
would you mind providing me with an example of either please, I am not sure I understand.

**Comment by danilopopeye** [comment]
same as 👉  #511
