### ISSUE TITLE
syslog.rb + Rest API with URI

### ISSUE THREAD

**Issue by ldep30** [ytti/oxidized#466]
Hi,

I've already managed to setup Oxidized to trigger config retrieval via the Syslog extra module, which works fine with a standard configuration :

```
rest: 127.0.0.1:8888
syslogd:
  port: 1514
```

However, I'm now facing issues when using a relative URI in the rest parameter of the Oxidized config file :

```
rest: 127.0.0.1:8888/oxidized
syslogd:
  port: 1514
```
Configuration retrieval is not triggered in this case.

I need to specify the /oxidized path for reverse-proxy and other management constraints.

By looking at [https://github.com/ytti/oxidized/blob/master/extra/rest_client.rb#L5](https://github.com/ytti/oxidized/blob/master/extra/rest_client.rb#L5), it seems that HOST, PORT and URI paths are hard-coded when doing the API call, ignoring the extra URI part specified in the config file.

The Web GUI works fine as well as management functions (config reloading, ...).

Am I missing something ?

Thanks !

**Comment by ytti** [comment]
Yeah  it's not supporting config. You could add support, do something like ```URI.join CFG.rest, 'node/next',opt[:name].to_s```

**Comment by ldep30** [comment]
Thanks for your help.
I'll first try to manually specify the /oxidized path in rest_client.rb, like that :

`@web.put '/oxidized/node/next/' + opt[:name].to_s, data`

**Comment by ytti** [comment]
I'm absolutely confident you're able to make it read oxidized config. I'd happily accept pull request on the change.

**Comment by ldep30** [comment]
I've created the pull request : #467
