### ISSUE TITLE
Cisco ASA only part running-config backed up

### ISSUE THREAD

**Issue by laf** [ytti/oxidized#470]
Hi Folks,

I'm seeing an issue with Cisco ASA devices where we are seeing only part of the config being backed up. However the point at which it breaks varies.

I can use oxs to see the same issue, running:

`oxs hostname.com 'more system:running-config'`

I can see anywhere from a few lines to 100+ lines of config before it stops with no further output.

Running `more system:running-config` on the firewall itself results in the full config being returned.

Any thoughts on how best to debug this?

**Comment by ytti** [comment]
https://github.com/ytti/oxidized/blob/master/lib/oxidized/model/asa.rb#L55

Change this to ```cmd``` from ```send``` and see if issue is remedied.

```send``` does not wait for prompt, printed prompts are unconsumed. ```cmd``` waits for prompt.

This means, actual ```show run``` might terminate immediately, because it saw prompt from enable password. Ending in desync between command start and command end.

**Comment by laf** [comment]
Thank you for the quick response @ytti.

Unfortunately that doesn't appear to have resolved the issue using oxs at least to test. Not sure if I need to restart the daemon testing it this way or not?

**Comment by ytti** [comment]
Restart shouldn't be needed. If that isn't it, then I fear it might be prompt detection issue.

You could hack the model and do something like this:

```
puts '---start command xyx----'
puts cfg
puts --end command xyz----'
```

To see if the cmd blocks are getting sensible config.

**Comment by laf** [comment]
Sorry to have hassled you on this @ytti :(

It looks like the issue was an old asa.rb in ~/.config/oxidized/model/ :(

Seems to be working as expected now.

**Comment by ytti** [comment]
I still think the send/cmd in enable is legit bug and fixing it :)

**Comment by laf** [comment]
For feedback I'm running the cmd line instead of send and it's gone through 1k+ devices with no issues :)
