### ISSUE TITLE
net-ssh 3.1.0.rc2 in docker image

### ISSUE THREAD

**Issue by mycahb2** [ytti/oxidized#472]
oxidized/oxidized:latest currently still has net-ssh 3.1.0rc2 which isn't compatible with cisco devices.

We have to modify the default image to install 3.0.2 before it backs up properly, which makes upgrading frustrating.

**Comment by danilopopeye** [comment]
@mycahb2 this was already fixed here [Gemfile.lock#L6](https://github.com/ytti/oxidized/blob/f4b98d972a6a17dc363c8b214b5d8aa162f5fa37/Gemfile.lock#L6) by @ElvinEfendi.
When @ytti cut the new gem version this problem should be fixed.

**Comment by L0uac** [comment]
+1 for this problem

**Comment by ytti** [comment]
I believe this is solved, we shouldn't accept 3.1 anymore.

**Comment by mycahb2** [comment]
Just did a `docker pull` got the following:

oxidized/oxidized                 latest              sha256:e217cb4d0f40af0f175f4d9037adf91b83fd20fdd8045fe571ddc4aea9e19a26   39 hours ago        547.9 MB

and within the container:

# gem list

*** LOCAL GEMS ***

asetus (0.3.0)
backports (3.6.8)
bigdecimal (1.2.4)
emk-sinatra-url-for (0.2.1)
ffi (1.9.14)
haml (4.1.0.beta.1)
io-console (0.4.3)
json (1.8.1)
minitest (4.7.5)
multi_json (1.12.1)
**net-ssh (3.1.0.rc2)**
net-telnet (0.1.1)
oxidized (0.16.3)
oxidized-web (0.7.1)
psych (2.0.5)
puma (2.16.0)
rack (1.6.4)
rack-protection (1.5.3)
rack-test (0.6.3)
rake (10.1.0)
rb-fsevent (0.9.7)
rb-inotify (0.9.7)
rdoc (4.1.0)
rugged (0.25.0b7)
sass (3.5.0.pre.rc.1)
sass-listen (3.0.7)
sinatra (1.4.7)
sinatra-contrib (1.4.7)
slop (3.6.0)
test-unit (2.1.9.0)
tilt (2.0.5)

**Comment by ytti** [comment]
Hmps. https://github.com/ytti/oxidized/blob/master/oxidized.gemspec#L24

Maybe 3.1.0rc2 is less than 3.1, and passes those requirements.

**Comment by mycahb2** [comment]
I did a docker build and it pulls it in when it runs:
`RUN gem install oxidized oxidized-web --no-ri --no-rdoc`

https://rubygems.org/gems/oxidized/versions/0.13.1 looks like it installs: net-ssh >= 3.0.2, ~> 3.0

**Comment by ytti** [comment]
Ok we need newer docker image. This is fixed in Oxidized itself.

**Comment by mycahb2** [comment]
The image in the docker hub was created 43 hours ago, after the latest commit to github I think.

```
# docker images

REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
oxidized/oxidized   latest              e217cb4d0f40        43 hours ago        547.9 MB
```

**Comment by ytti** [comment]
If if installs 0.13.1 it's not installing new. @mikebryant @nopedial

**Comment by mycahb2** [comment]
If I change line 6 in the Dockerfile from:

` apt-get install -y ruby2.1 ruby2.1-dev libsqlite3-dev libssl-dev pkg-config make cmake`

to

` apt-get install -y ruby2.2 ruby2.2-dev libsqlite3-dev libssl-dev pkg-config make cmake`

It installs the correct dependencies.  It appears to be an issue with the version of gem running in the ruby 2.1 install.

**Comment by ytti** [comment]
that sounds strange, but might as well run 2.3, makes more sense. @mikebryant @nopedial

**Comment by mycahb2** [comment]
Would you object to me testing and submitting a PR?  I'd love to see this in the docker hub so we can update normally again.

**Comment by ytti** [comment]
Sure thing

**Comment by mycahb2** [comment]
PR submitted https://github.com/ytti/oxidized/pull/564

**Comment by ytti** [comment]
Thanks, merged.
