### ISSUE TITLE
Hook push to remote : Issue (Unsupported URL protocol)

### ISSUE THREAD

**Issue by limace255** [ytti/oxidized#473]
Hi all,

We try to use oxidized, with following concernes :

backup networks equipments
push configs to internal git server (gitlab)
When launching oxidized (in debug mode), we have this in the logs :

```
I, [2016-06-17T11:53:52.466907 #12943] INFO -- : GithubRepo: Pushing local repository(/root/.config/oxidized/oxidized.git/)...
I, [2016-06-17T11:53:52.467765 #12943] INFO -- : GithubRepo: to remote: routers:"git@git_server:PATH/test.git"
E, [2016-06-17T11:53:52.469240 #12943] ERROR -- : Hook push_to_remote (#GithubRepo:0x0000000212f3e8) failed (#) for event :post_store
```

Our configuration file :
``` yaml
hooks:
push_to_remote:
type: githubrepo
events: [post_store]
remote_repo:
routers:"git@git_server:PATH/test.git"
publickey: "/root/.ssh/id_rsa.pub"
privatekey: "/root/.ssh/id_rsa"
```
Did we make something wrong ?

Thanks in advance !

**Comment by limace255** [comment]
Hi all,

We try to use oxidized, with following concernes :+1: 

- backup networks equipments
- push configs to internal git server (gitlab)

When launching oxidized (in debug mode), we have this in the logs :+1: 

I, [2016-06-17T11:53:52.466907 #12943]  INFO -- : GithubRepo: Pushing local repository(/root/.config/oxidized/oxidized.git/)...
I, [2016-06-17T11:53:52.467765 #12943]  INFO -- : GithubRepo: to remote: routers:"git@git_server:PATH/test.git"
E, [2016-06-17T11:53:52.469240 #12943] ERROR -- : Hook push_to_remote (#<GithubRepo:0x0000000212f3e8>) failed (#<Rugged::NetworkError: Unsupported URL protocol>) for event :post_store

Our configuration file :+1: 

hooks:
  push_to_remote:
    type: githubrepo
    events: [post_store]
    remote_repo:
        routers:"git@git_server:PATH/test.git"
    publickey: "/root/.ssh/id_rsa.pub"
    privatekey: "/root/.ssh/id_rsa"

Did we make something wrong ?

Thanks in advance !

**Comment by laf** [comment]
If it helps, here's our config. We use groups but only utilise a single gitlab repo to store them:

```
hooks:
  push_to_remote:
    type: githubrepo
    events: [post_store]
    remote_repo: git@gitlab.example.com:/Oxidized/network_config.git
    publickey: /home/oxidized/.ssh/id_rsa.pub
    privatekey: /home/oxidized/.ssh/id_rsa
```

**Comment by limace255** [comment]
Just tried with this :

hooks:
  push_to_remote:
    type: githubrepo
    events: [node_success, post_store]
    remote_repo: git@10.10.10.10:/PATH/backup.git
    publickey: /root/.ssh/id_rsa.pub
    privatekey: /root/.ssh/id_rsa

Still failing with same error :-(

Micael.

**Comment by ytti** [comment]
Remove the ```node_success``` event.

Do you have crash files in ~/config/oxidized directory, when running in debug mode, do you get backtrace? What is your full config?

**Comment by limace255** [comment]
Hi ytti,

Nothing in crash file, unfortunately.
In debug mode, only errors when we have "node_success" event activated (in fact, if I only keep it, I don't see any hook related to push_remote, don't know if it's expected or not).

Here is our config file : 

---
username: username
password: password
model: junos
interval: 3600
use_syslog: false
log: "/root/.config/oxidized/log/oxidized.log"
debug: true
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 10.104.224.24:8888
vars: {}
groups: {}
input:
  default: ssh, telnet
  debug: false
  ssh:
    secure: false
output:
  default: git
  git:
    user: USER
    email: mail@mail.com
    single_repo: true
    repo: /root/.config/oxidized/oxidized.git
hooks:
  push_to_remote:
    type: githubrepo
    events: [post_store]
    remote_repo: git@10.10.10.10:/PATH/backup.git
    publickey: /root/.ssh/id_rsa.pub
    privatekey: /root/.ssh/id_rsa
source:
  default: csv
  csv:
    file: "/etc/oxidized/router.db"
model_map:
  cisco: ios
  juniper: junos
  F5: tmos
  fortigate: fortios
  screenos: screenos

Thank you for all your work,
limace255

**Comment by ytti** [comment]
If there are no changes, then post_store for it returns false value which causes post_store not to trigger.

Make some change in config and see if post_store hook triggers.

**Comment by limace255** [comment]
Hi again,

post_store hook is triggered, but fails, whereas I use ssh ot http protocol.

Part of config concerning the hook : 

WITH_http : 

hooks:
  push_to_remote:
    type: githubrepo
    events: [post_store]
    remote_repo: "http://10.10.10.255/PATH/oxidized.git"
    username: USER
    password: PASS
    #publickey: ~/.ssh/id_rsa.pub
    #privatekey: ~/.ssh/id_rsa


WITH_ssh : 

hooks:
  push_to_remote:
    type: githubrepo
    events: [post_store]
    remote_repo: USER@10.10.10.255/PATH/oxidized.git
    publickey: ~/.ssh/id_rsa.pub
    privatekey: ~/.ssh/id_rsa


Logs : 

WITH_http : 

I, [2016-06-22T15:04:55.709485 #648]  INFO -- : Configuration updated for /f5-1
I, [2016-06-22T15:04:55.711065 #648]  INFO -- : GithubRepo: Pushing local repository(/home/oxidized/backup.git/)...
I, [2016-06-22T15:04:55.711739 #648]  INFO -- : GithubRepo: to remote: http://10.10.10.255/PATH/oxidized.git
D, [2016-06-22T15:04:55.964291 #648] DEBUG -- : GithubRepo: {:total_objects=>0, :indexed_objects=>0, :received_objects=>0, :local_objects=>0, :total_deltas=>0, :indexed_deltas=>0, :received_bytes=>0}
D, [2016-06-22T15:04:55.965017 #648] DEBUG -- : GithubRepo: nothing recieved after fetch
E, [2016-06-22T15:04:56.167699 #648] ERROR -- : Hook push_to_remote (#<GithubRepo:0x00000001336340>) failed (#<Rugged::ReferenceError: Cannot push non-fastforwardable reference>) for event :post_store


WITH_ssh : 

I, [2016-06-22T15:11:09.939081 #688]  INFO -- : GithubRepo: Pushing local repository(/home/oxidized/backup.git/)...
I, [2016-06-22T15:11:09.941695 #688]  INFO -- : GithubRepo: to remote: ssh://10.10.10.255/PATH/oxidized.git
D, [2016-06-22T15:11:09.941993 #688] DEBUG -- : GithubRepo: Using https auth
E, [2016-06-22T15:11:09.942421 #688] ERROR -- : Hook push_to_remote (#<GithubRepo:0x00000001552368>) failed (#<Rugged::NetworkError: Unsupported URL protocol>) for event :post_store

I think there's something wrong (certainly our part) about the remote_repo line inside push_to_remote hook... Can someone take a look ?

Best regards,
limace255

**Comment by ytti** [comment]
Does pushing manually work? How does manual and oxidized triggered pushes look at server logs?

**Comment by danilopopeye** [comment]
> Rugged::ReferenceError: Cannot push non-fastforwardable reference

Rugged is saying that there is changes in your upstream repository and it can't push your changes because a merge is required.

> GithubRepo: to remote: ssh://10.10.10.255/PATH/oxidized.git

shouldn't it be `remote_repo: USER@10.10.10.255:/PATH/oxidized.git` ?

**Comment by limace255** [comment]
In fact I think both are possible , cf https://git-scm.com/docs/git-push : 

The following syntaxes may be used with them:

ssh://[user@]host.xz[:port]/path/to/repo.git/

git://host.xz[:port]/path/to/repo.git/

http[s]://host.xz[:port]/path/to/repo.git/

@ytti : in fact my colleague told me push was broken too :-'

Let's try to fix it first

**Comment by wylieswanson** [comment]
I have the same problem;

I, [2016-06-29T19:19:00.938062 #31506]  INFO -- : Configuration updated for /mgmt.domain.com
I, [2016-06-29T19:19:00.938584 #31506]  INFO -- : GithubRepo: Pushing local repository(/home/wylie/.config/oxidized/trustcor-oxidized.git/)...
I, [2016-06-29T19:19:00.938935 #31506]  INFO -- : GithubRepo: to remote: git@git.domain.com:/domain/domain-oxidized.git
D, [2016-06-29T19:19:01.082675 #31506] DEBUG -- : GithubRepo: {:total_objects=>0, :indexed_objects=>0, :received_objects=>0, :local_objects=>0, :total_deltas=>0, :indexed_deltas=>0, :received_bytes=>0}
D, [2016-06-29T19:19:01.082821 #31506] DEBUG -- : GithubRepo: nothing recieved after fetch
E, [2016-06-29T19:19:01.224804 #31506] ERROR -- : Hook push_to_remote (#<GithubRepo:0x007faad6e13f88>) failed (#<Rugged::ReferenceError: Cannot push non-fastforwardable reference>) for event :post_store

using following config against internal GitHub Enterprise

output:
  default: git
  git:
    user: wylie
    email: wylie@domain.com
    repo: "/home/wylie/.config/oxidized/domain-oxidized.git"

hooks:
  push_to_remote:
    type: githubrepo
    events: [post_store]
    remote_repo: git@git.domain.com:/domain/domain-oxidized.git
    publickey: /home/wylie/.config/oxidized/id_rsa.pub
    privatekey: /home/wylie/.config/oxidized/id_rsa


^ key has been installed with write/access to specific repo in ghe

**Comment by danilopopeye** [comment]
> Cannot push non-fastforwardable reference

Rugged is telling you to merge te changes before it can push them. Can you try to push it manually and see if there are any conflicts?

**Comment by limace255** [comment]
Hi all,

Some news since the last time !

We have fixed "local to remote" push issues, so now, when launching oxidized : 

- git (local) works perfectly
- git (remote) still NOK
- manual push (from local to remote) works well ('git push origin master')

Logs : 
I, [2016-07-05T15:46:55.110164 #19936]  INFO -- : GithubRepo: Pushing local repository(/home/oxidized/backup-network/.git/)...
I, [2016-07-05T15:46:55.111233 #19936]  INFO -- : GithubRepo: to remote: backup@10.10.10.10:backup/backup-network.git
E, [2016-07-05T15:46:55.112584 #19936] ERROR -- : Hook push_to_remote (#<GithubRepo:0x000000026b0588>) failed (#<Rugged::NetworkError: Unsupported URL protocol>) for event :post_store

lim

**Comment by ytti** [comment]
@limace255 is this issue now resolved?

**Comment by limace255** [comment]
Hi ytti, thanks for your interest.
We now manually push to Gitlab (through crontab); quite bad, but it works, bosses are happy :)

**Comment by ytti** [comment]
If you want to move to hook based system and have problems, please reopen the case. There is fix which hopefully helps you in #503.

I'm sure we can get it working for you too. Nothing wrong with crontab solution though.

**Comment by marrold** [comment]
I believe the actual fix for @limace255 's issue is the following-

`sudo apt-get install libssh2-1-dev`
`sudo gem uninstall rugged`
`sudo gem install rugged`

I had a similar issue and found the 'fix' here- https://github.com/jbox-web/redmine_git_hosting/issues/440
`

**Comment by luitzifa** [comment]
@marrold unfortunately this is not working for me...

**Comment by lst123** [comment]
I've got the same an error:
`E, [2016-06-29T19:19:01.224804 #31506] ERROR -- : Hook push_to_remote (#<GithubRepo:0x007faad6e13f88>) failed (#<Rugged::ReferenceError: Cannot push non-fastforwardable reference>) for event :post_store
`
My oxidezed hooks looked like that:
```
hooks:
  push_to_remote:
    type: githubrepo
    events: [post_store]
    remote_repo: git@gitlab.local:noc/net_backup.git
    publickey: /home/oxidized/.ssh/id_rsa.pub
    privatekey: /home/oxidized/.ssh/id_rsa
```
When I replaced it with (added / to the url):
```
hooks:
  push_to_remote:
    type: githubrepo
    events: [post_store]
    remote_repo: git@gitlab.local:/noc/net_backup.git
    publickey: /home/oxidized/.ssh/id_rsa.pub
    privatekey: /home/oxidized/.ssh/id_rsa
```
and recreate repo, everything started to work as expected.
Maybe this will help someone.

**Comment by danilopopeye** [comment]
> #<Rugged::ReferenceError: Cannot push non-fastforwardable reference>

this is another problem. it says rugged can't push to a repository that has changed.
