### ISSUE TITLE
After installation

### ISSUE THREAD

**Issue by arko95** [ytti/oxidized#476]
After installed Oxidized as a service, fill the routers.db . How it will track a configuration change on devices in real time ? With syslog ? But it could be disabled , so there is another way to do it ?
If it´s not tracking a config change ,  the interval settings in the config is the interval between each sheduled config fetch ?

**Comment by ytti** [comment]
It's not tracking configuration changes, there are some example code in /extra which allows you to setup such system, or at least gives an idea how to do it.

By default it will periodically fetch configs, interval describes how often config should be fetched.
