### ISSUE TITLE
MySQL Setup

### ISSUE THREAD

**Issue by mweinelt** [ytti/oxidized#482]
Hi,

at least for using mysql as the source I had to install

gems:
- `sequel`
- `mysql2`

apt:
- `libmysqlclient-dev` (to build the native extension)

Please add that information to the documentation.

**Comment by ytti** [comment]
pull requests for README.md are gladly accepted

**Comment by MajesticFalcon** [comment]
Has this been implemented by @mweinelt  but not committed?

**Comment by ytti** [comment]
Nothing needs to be implemented, @mweinelt is just talking about lack of documentation how to set this up.
About 'sequal' gem, the sql model will complain, so it's somewhat obvious. 

But we can use plethora of database drivers, it doesn't have to be mysql2. So at that point it quickly becomes that we need to duplicate sequal docs, or at least list what drivers sequal supports and how to install them (on which OS should we document the installation process?).

**Comment by MajesticFalcon** [comment]
This can be closed
