### ISSUE TITLE
CentOS 7 systemd

### ISSUE THREAD

**Issue by justinoreilly** [ytti/oxidized#483]
How would I go about having oxidized startup and be controlled with systemd? I took a look in the extras directory and see that there was a service script but unfortunately that was of no help once it was put in place.

```
[root@oxidized bin]# systemctl status oxidized.service
● oxidized.service - Oxidized - Network Device Configuration Backup Tool
   Loaded: loaded (/usr/lib/systemd/system/oxidized.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Sat 2016-06-25 00:57:19 EDT; 4s ago
  Process: 2518 ExecStart=/usr/local/rvm/gems/ruby-2.1.2/gems/oxidized-0.14.3/bin/oxidized (code=exited, status=127)
 Main PID: 2518 (code=exited, status=127)

Jun 25 00:57:19 oxidized.xxxx.xxxxxxxxxxxxxxx.com systemd[1]: Started Oxidized - Network Device Configuration Backup Tool.
Jun 25 00:57:19 oxidized.xxxx.xxxxxxxxxxxxxxx.com systemd[1]: Starting Oxidized - Network Device Configuration Backup Tool...
Jun 25 00:57:19 oxidized.xxxx.xxxxxxxxxxxxxxx.com oxidized[2518]: /usr/bin/env: ruby: No such file or directory
Jun 25 00:57:19 oxidized.xxxx.xxxxxxxxxxxxxxx.com systemd[1]: oxidized.service: main process exited, code=exited, status=127/n/a
Jun 25 00:57:19 oxidized.xxxx.xxxxxxxxxxxxxxx.com systemd[1]: Unit oxidized.service entered failed state.
Jun 25 00:57:19 oxidized.xxxx.xxxxxxxxxxxxxxx.com systemd[1]: oxidized.service failed.
```

I followed the installation instructions in the README by Installing Ruby 2.1.2 using RVM then dependencies for oxidized and then finally the oxidized gems.

**Comment by danilopopeye** [comment]
I haven't used rvm in a long time, but as far as I remember you need to call its wrappers directly.
something like its mentioned here [#direct-calling-rvm-generated-wrappers](https://rvm.io/deployment/cron#direct-calling-rvm-generated-wrappers)

**Comment by shailigum** [comment]
If you don't mind using ruby 2.0.0.598, install ruby with yum instead of RVM (if you're already running RVM make sure you **completely** remove it/ruby prior to re-installing ruby via yum, I find that a simple `rvm implode` leads to instabilities).  

Then run a fresh installation of oxidized/web/script via gem and copy the oxidized.service file in /extras to /etc/systemd/system/.  This should allow you call it via systemd/systemctl.

More on this in #399

**Comment by murrant** [comment]
This is what I use:
```
[Unit]
Description=Oxidized - Network Device Configuration Backup Tool

[Service]
ExecStart=/usr/local/bin/oxidized
WorkingDirectory=/var/lib/oxidized
User=oxidized

[Install]
WantedBy=multi-user.target
```

You may have to adjust for your setup.  I have a user 'oxidized' that it runs as.  /var/lib/oxidized is the home directory for that user and my data directory.

**Comment by danilopopeye** [comment]
ping @justinoreilly

**Comment by ytti** [comment]
closed due to inactivity, @justinoreilly please reopen if needed
