### ISSUE TITLE
Cisco IOS - User Name: not matching configured prompt

### ISSUE THREAD

**Issue by casdr** [ytti/oxidized#485]
I'm getting the following error when getting a config for some IOS devices:

    User Name: not matching configured prompt

I've tried adding a username and password config to :ssh, but then other (more) devices crash.

Is this a known issue?

**Comment by ytti** [comment]
Do you have backtrace  from crashfiles you can share? Do you have output log from the session which does not work?

**Comment by casdr** [comment]
@ytti 

- SSH log: empty
- Telnet log: connection refused
- No crash file for specific device
- Main log file:
```
W, [2016-06-28T12:21:16.864333 #21768]  WARN -- : [ip removed] raised Oxidized::PromptUndetect with msg "



User Name: not matching configured prompt (?-mix:^([\w.@()-]+[#>]\s?)$)"
D, [2016-06-28T12:21:16.886140 #21768] DEBUG -- : [ip removed] raised Errno::ECONNREFUSED with msg "Connection refused - connect(2)"
```

**Comment by ytti** [comment]
What Cisco device is this? 


You need to look at the:
```
output:
  log: true
```

with 'tail -f' or something, as it'll be overwritten.

'User Name:' does not sound cisco-ish device. And is this SSH? Are you getting User Name prompt when using SSH?

**Comment by casdr** [comment]
Thanks for the heads up! This is a Cisco SG300 so I should use the ciscosmb model.

It's running great now :)
