### ISSUE TITLE
Cisco ASA raised Timeout::Error with msg "execution expired"

### ISSUE THREAD

**Issue by skaarup1986** [ytti/oxidized#486]
Hi,
I keep getting this error when trying to take backup of my ASA firewalls.  
My ASA firewalls are running Version 9.1(2)  and oftware Version 9.1(3)  and oxidized-0.14.3 .

Debug output:
Type help or '?' for a list of available commands.
^MHostname>

**Comment by ytti** [comment]
It looks like the prompt has \r you should add \r? to prompt regexp

**Comment by skaarup1986** [comment]
Thank you for the quick response. At which position of the regex should i insert it? 
prompt /^\r*([\w.@()-\/]+[#>]\s?)$/

**Comment by ytti** [comment]
Aah there is \r* already, that should suffice. 

Do you have crash file for the device in ~/.config/oxidized?

Can you turn on input session debug?
```
input:
  debug: true
``` 

The log will be in ~/.config/oxidized you need to view it with 'tail -f file' or something, as it will be overwritten after every attempt. 

Both crash file and session log would be helpful.

**Comment by skaarup1986** [comment]
Hi Ytti,

looks like its a "enable" issue as "Terminal pager 0" only works in privileged mode.   

Debug:
Type help or '?' for a list of available commands.
hostname> terminal pager 0
             ^
ERROR: % Invalid input detected at '^' marker.
ERROR: Command authorization failed
hostname> show version

Cisco Adaptive Security Appliance Software Version 9.1(3) 
Device Manager Version 7.3(1)101

Compiled on Mon 16-Sep-13 16:07 PDT by builders
System image file is "disk0:/asa913-smp-k8.bin"
Config file at boot was "startup-config"

Hostname up 90 days 1 hour

Hardware:   ASA5515, 8192 MB RAM, CPU Clarkdale 3058 MHz, 1 CPU (4 cores)
            ASA: 4096 MB RAM, 1 CPU (1 core)
Internal ATA Compact Flash, 8192MB
BIOS Flash MX25L6445E @ 0xffbb0000, 8192KB

Encryption hardware device : Cisco ASA-55xx on-board accelerator (revision 0x1)
                             Boot microcode        : CNPx-MC-BOOT-2.00
                             SSL/IKE microcode     : CNPx-MC-SSL-PLUS-T020
                             IPSec microcode       : CNPx-MC-IPSEC-MAIN-0026
                             Number of accelerators: 1
Baseboard Management Controller (revision 0x1) Firmware Version: 2.4


 0: Int: Internal-Data0/0    : address is f40f.1b76.c609, irq 11
 1: Ext: GigabitEthernet0/0  : address is f40f.1b76.c60d, irq 10
<--- More --->

Crash file: 
--------------------------------------------------
2016-06-27 11:47:07 UTC
no output file config, edit ~/.config/oxidized/config [Oxidized::NoConfig]
--------------------------------------------------
/usr/local/lib/ruby/gems/2.0.0/gems/oxidized-0.14.3/lib/oxidized/output/file.rb:15:in `setup'
/usr/local/lib/ruby/gems/2.0.0/gems/oxidized-0.14.3/lib/oxidized/manager.rb:19:in `load'
/usr/local/lib/ruby/gems/2.0.0/gems/oxidized-0.14.3/lib/oxidized/manager.rb:40:in `add_output'
/usr/local/lib/ruby/gems/2.0.0/gems/oxidized-0.14.3/lib/oxidized/node.rb:160:in `resolve_output'
/usr/local/lib/ruby/gems/2.0.0/gems/oxidized-0.14.3/lib/oxidized/node.rb:20:in `initialize'
/usr/local/lib/ruby/gems/2.0.0/gems/oxidized-0.14.3/lib/oxidized/nodes.rb:18:in `new'
/usr/local/lib/ruby/gems/2.0.0/gems/oxidized-0.14.3/lib/oxidized/nodes.rb:18:in `block (2 levels) in load'
/usr/local/lib/ruby/gems/2.0.0/gems/oxidized-0.14.3/lib/oxidized/nodes.rb:14:in `each'
/usr/local/lib/ruby/gems/2.0.0/gems/oxidized-0.14.3/lib/oxidized/nodes.rb:14:in `block in load'
/usr/local/lib/ruby/gems/2.0.0/gems/oxidized-0.14.3/lib/oxidized/nodes.rb:110:in `synchronize'
/usr/local/lib/ruby/gems/2.0.0/gems/oxidized-0.14.3/lib/oxidized/nodes.rb:110:in `with_lock'
/usr/local/lib/ruby/gems/2.0.0/gems/oxidized-0.14.3/lib/oxidized/nodes.rb:10:in `load'
/usr/local/lib/ruby/gems/2.0.0/gems/oxidized-0.14.3/lib/oxidized/nodes.rb:105:in `initialize'
/usr/local/lib/ruby/gems/2.0.0/gems/oxidized-0.14.3/lib/oxidized/core.rb:14:in `new'
/usr/local/lib/ruby/gems/2.0.0/gems/oxidized-0.14.3/lib/oxidized/core.rb:14:in `initialize'
/usr/local/lib/ruby/gems/2.0.0/gems/oxidized-0.14.3/lib/oxidized/core.rb:4:in `new'
/usr/local/lib/ruby/gems/2.0.0/gems/oxidized-0.14.3/lib/oxidized/core.rb:4:in `new'
/usr/local/lib/ruby/gems/2.0.0/gems/oxidized-0.14.3/lib/oxidized/cli.rb:12:in `run'
/usr/local/lib/ruby/gems/2.0.0/gems/oxidized-0.14.3/bin/oxidized:9:in `<top (required)>'
/usr/local/bin/oxidized:23:in `load'
/usr/local/bin/oxidized:23:in `<main>'

**Comment by skaarup1986** [comment]
Snip from my config file:

username: XXXXXXX
password: XXXXXX
model: junos
interval: 3600
use_syslog: false
debug: false
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
vars:
  enable: XXXXXXX

**Comment by skaarup1986** [comment]
Hi Ytti, 
It was a configuration error on my site, sorry for wasting your time.  

Changed:
vars:
enable: XXXXXXX

to:

vars: {
 enable: XXXXX
}


FYI the cookbook doesn't mention the {}  .
