### ISSUE TITLE
Sequel not found

### ISSUE THREAD

**Issue by totosh** [ytti/oxidized#495]
Hi,
I'm trying to setup oxidized with sqlite db but i get this error :
sequel not found: sudo gem install sequel

So i install sequel
$ gem install sequel
$ sequel -v
sequel 4.36.0

But i still get this error above.

Crash log :
2016-07-12 17:11:38 UTC
sequel not found: sudo gem install sequel [Oxidized::OxidizedError]

/usr/local/rvm/gems/ruby-2.1.2/gems/oxidized-0.15.0/lib/oxidized/source/sql.rb:6:in `rescue in <class:SQL>'
/usr/local/rvm/gems/ruby-2.1.2/gems/oxidized-0.15.0/lib/oxidized/source/sql.rb:3:in `<class:SQL>'
/usr/local/rvm/gems/ruby-2.1.2/gems/oxidized-0.15.0/lib/oxidized/source/sql.rb:2:in `<module:Oxidized>'
/usr/local/rvm/gems/ruby-2.1.2/gems/oxidized-0.15.0/lib/oxidized/source/sql.rb:1:in `<top (required)>'
/usr/local/rvm/rubies/ruby-2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/rvm/rubies/ruby-2.1.2/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/rvm/gems/ruby-2.1.2/gems/oxidized-0.15.0/lib/oxidized/manager.rb:10:in `load'
/usr/local/rvm/gems/ruby-2.1.2/gems/oxidized-0.15.0/lib/oxidized/manager.rb:53:in `add_source'
/usr/local/rvm/gems/ruby-2.1.2/gems/oxidized-0.15.0/lib/oxidized/nodes.rb:13:in `block in load'
/usr/local/rvm/gems/ruby-2.1.2/gems/oxidized-0.15.0/lib/oxidized/nodes.rb:111:in `synchronize'
/usr/local/rvm/gems/ruby-2.1.2/gems/oxidized-0.15.0/lib/oxidized/nodes.rb:111:in `with_lock'
/usr/local/rvm/gems/ruby-2.1.2/gems/oxidized-0.15.0/lib/oxidized/nodes.rb:10:in `load'
/usr/local/rvm/gems/ruby-2.1.2/gems/oxidized-0.15.0/lib/oxidized/nodes.rb:106:in `initialize'
/usr/local/rvm/gems/ruby-2.1.2/gems/oxidized-0.15.0/lib/oxidized/core.rb:14:in `new'
/usr/local/rvm/gems/ruby-2.1.2/gems/oxidized-0.15.0/lib/oxidized/core.rb:14:in `initialize'
/usr/local/rvm/gems/ruby-2.1.2/gems/oxidized-0.15.0/lib/oxidized/core.rb:4:in `new'
/usr/local/rvm/gems/ruby-2.1.2/gems/oxidized-0.15.0/lib/oxidized/core.rb:4:in `new'
/usr/local/rvm/gems/ruby-2.1.2/gems/oxidized-0.15.0/lib/oxidized/cli.rb:12:in `run'
/usr/local/rvm/gems/ruby-2.1.2/gems/oxidized-0.15.0/bin/oxidized:9:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.1.2/bin/oxidized:23:in `load'
/usr/local/rvm/gems/ruby-2.1.2/bin/oxidized:23:in `<main>'
/usr/local/rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'

Totosh.

**Comment by ytti** [comment]
It seems you've installed ruby via rvm, but you also have system ruby installed. With 'gem' you installed the sequel to system ruby directory. You should have first switched to your rvm installation, before running gem.

**Comment by totosh** [comment]
Ho right. -_-
I had updated my ruby version to 2.1.8 with rvm before installing sequel, therefore the version didn't match !
Thank you.
