### ISSUE TITLE
Procurve: long lines wrap to new line

### ISSUE THREAD

**Issue by davama** [ytti/oxidized#496]
Not sure if an HP or configuration issue but when oxidized retrieves the config and a line is >81 characters, part of that line wraps to a new line.

**Example:**
Configured on the switch. While in the switch "sh run" or "sh run | in sflow" outputs as so:
`sflow 1 sampling A1-A4,B1-B4,E4,F2,F4,I1-I24,J1-J24,K1-K24,L1-L24,Trk59-Trk60 1000`

Config line in the backup from oxidzed. If i use oxidized-script, i get the same result.
```
sflow 1 sampling A1-A4,B1-B4,E4,F2,F4,I1-I24,J1-J24,K1-K24,L1-L24,Trk59-Trk60
 1000
```

Is there  some line in oxidized where one can set the width (like terminal linux $COLUMNS)
Somewhere else to look at?

Thanks
Dave

**Comment by ytti** [comment]
I don't have procurve to test on. But you might start by capturing the session and looking how it looks like on-the-wire, during telnet/ssh and during oxidized.

For oxidized:
```
input:
  debug: true
```

may help a bit, it'll create in ~/config/oxidized session log for the box, you may need to be quick to copy it to safety, as it'll get overwritten by new attempts.

Be sure to check the files on viewer which will show special characters. I wouldn't be too surprised if on-the-wire there is new line and then some ansi codes to remove the new line.

**Comment by davama** [comment]
> start by capturing the session and looking how it looks like on-the-wire, during telnet/ssh and during oxidized

What do you mean? I dont understand

i've enabled debug: true as suggested. Ran oxidized on the foreground but nothing interesting comes up.

> Be sure to check the files on viewer which will show special characters. I wouldn't be too surprised if on-the-wire there is new line and then some ansi codes to remove the new line.

How do i do this? `cat, grep, vim, tail` ?

**Comment by ytti** [comment]
Hey

```
debug: true
```

Is different to
```
input:
  debug: true
``` 

The latter will create file by the name of the device in ~/.config/oxidized/ directory containing thee telnet/ssh session. Put that online.

Also do normal ssh/telnet without oxidized, likee ```ssh box|tee log.txt```  and put ```log.txt``` online.

**Comment by davama** [comment]
Thanks for the clarification.

Outputs are here: [link](https://gist.github.com/davama/346490cb48ae0c999c64f5adc13c6394) line 84 and line 5 show the "sflow" lines
On the ssh-log file all i ran was "sh run | in sflow"

Thanks
Dave

**Comment by ytti** [comment]
And this log is from your normal CLI session, not oxidized?

In this log file, we can clearly see that there is new line in the config before the ```1000```

**Comment by davama** [comment]
> And this log is from your normal CLI session, not oxidized?

First log from Oxidized, second from normal `ssh host | tee log.txt`

Yes, i see the new line too but why? any way to fix?
Note vlan 1 output:
```
vlan 1^M
   name "DEFAULT_VLAN"^M
   no untagged^M
 A1-A4,B1-B4,E4,F2,G1-G4,H1-H4,I1-I24,J1-J24,K1-K24,L1-L24,Trk1-Trk2,Trk58-Trk60^M
   untagged F4^M
   no ip address^M
   exit^M
```

The `no untagged` line has one too but actual command, 'no untagged <ports>`, is way over 81 characters long so it wraps to the next line.

HP hardware has always given us issues when it comes to scripting...

**Comment by ytti** [comment]
Yeah HP CLI is horribad. I don't really know how to solve this correctly.

We probably would need to run it through terminal emulator. Unless @Ultra2D has time/ideas.

Personally, I'm not super interested in procurve, I don't have one and I don't plan getting one. I'm pretty sure we can detect string after new line which 'negates' new line, and do fugly regexp hack remove new line. But I'm not gonna spend time figuring how to do it, sorry.
I will obviously accept pull request to fix this.

**Comment by Ultra2D** [comment]
In the link from  https://github.com/ytti/oxidized/issues/496#issuecomment-232337347 the output from SSH is on one line, right?
Is the output of https://github.com/ytti/oxidized/issues/496#issuecomment-232349651 from SSH or Oxidized?

**Comment by davama** [comment]
> In the link from #496 (comment) the output from SSH is on one line, right?Outputs:

Yes, provided links to raw files: [oxidized](https://gist.githubusercontent.com/davama/346490cb48ae0c999c64f5adc13c6394/raw/3f027ac17eaf4273b52773c07b3b65e6ebfd6200/oxidized-input-debug-log) [ssh](https://gist.githubusercontent.com/davama/346490cb48ae0c999c64f5adc13c6394/raw/3f027ac17eaf4273b52773c07b3b65e6ebfd6200/ssh-log) 

>Is the output of #496 (comment) from SSH or Oxidized?

The `vlan 1oxidized

**Comment by Ultra2D** [comment]
So it is fine via SSH, but in both cases Oxidized is wrapping. Did you understand it that way too @ytti ?

**Comment by davama** [comment]
I feel like im close. 
NOTE: dont know nothing about ruby. all trial and error.

so i replaced the `cmd 'show running-config'` line with:
```
  cmd 'show running-config' do |cfg|
    cfg.gsub! /^sflow 1 polling$\n ((\S+) 60)$/, 'sflow 1 polling \\1'
    cfg.gsub! /^sflow 1 sampling$\n ((\S+) 1000)$/, 'sflow 1 sampling \\1'
    cfg.gsub! /^   no untagged$\n ((\S+))$/, '   no untagged \\1'
    #cfg.gsub! /^   untagged$\n ((\S+))$/, '   untagged \\1'
    cfg.gsub! /^   untagged$\n ((\S+,))$\n([A-L](\S+)[0-9]$)/, '   untagged \\2'
    cfg
  end
```

I've been playing with it trying to get things to work.
So far i've been able to get two lines that should be one line to come out as one line. (ie sflow , untagged commands)

There are commands that oxidized saves it as three lines because it's so long. This is how oxidized saves it:
```
   untagged
E14-E21,F1-F7,F9-F10,F13,F15-F21,F24,G2-G24,H1-H20,I7-I8,I13-I15,I21,J1-J24,K7,
K9-K16,K19,K22-K24,L1-L19
```

So im trying to create a gsub where it makes those 3 line and makes it into one line.
```
cfg.gsub! /^   untagged$\n ((\S+,))$\n([A-L](\S+)[0-9]$)/, '   untagged \\1\\2'
```

I cant seem to get the second group to work. The above seems to repeat the 1st group twice.

Anything im missing?

Also how can i create a group using optional substring. Where some string is optional but is part of a group which i can call in my replace section? In Regex i believe you use `pattern(option1|option2)` but the `()` are for groups if my ruby is correct.

Thanks

**Comment by davama** [comment]
I think i got it!

I changed my code to this:
```
  cmd 'show running-config' do |cfg|
    cfg.gsub! /^(sflow 1 polling)$\n\s((\S+)\s60)$/, '\\1 \\2'
    cfg.gsub! /^(sflow 1 sampling)$\n\s((\S+)\s1000)$/, '\\1 \\2'
    cfg.gsub! /^(sflow 1 sampling)\s(\S+)\n\s60$/, '\\1 \\2 60'
    cfg.gsub! /^(sflow 1 sampling) (\S+)\n\s1000$/, '\\1 \\2 1000'

    cfg.gsub! /^(\s+)(no untagged)$\n\s((\S+))$/, '\\1\\2 \\3'
    cfg.gsub! /^(\s+)(untagged)$\n\s([A-L]\S+)$\n([A-L]\S+)$/, '\\1\\2 \\3\\4'
    cfg
  end
```
Granted it's not a fix all but works for our specific needs.

Thanks
Dave

Closing

**Comment by davama** [comment]
Reopening....

I was thinking, could the reason this happens with oxidized have anything to do with the terminal window sizing?

Was trying to test using the hooks but the valid events are only post ssh process.
Something like this for example: `stty rows 1000 cols 1000`

Thanks

**Comment by ytti** [comment]
Can you reproduce this in CLI with different stty settings? We don't have terminal, we don't fork OpenSSH, we use SSH library. We could pass environment variables via SSH to the far end.

**Comment by davama** [comment]
Unfortunately i was not. I tried with `xterm`,  `roxterm` and putty. All same behavior

```
stty size
35 235
stty cols 10
stty size
35 10
ssh <procurve-host>
show running-config
exit
stty size
35 10
```

during the session nothing changed. i could get the whole config without any line wrappings. changing terminal size made no difference pre-ssh login.

If i shrunk that actual window of my term session **then i could get the lines to wrap** when showing running-config. ( which is expected )
```
**change the actual window size of terminal**
stty size
12 46
ssh <host>
<lines would wrap>
```

Anything else to try? 
Is it possible to set the size of the actual `ssh` session when sshing into procurve?
idk something like: `ssh <setsize> <host>`

Thanks!

**Comment by ytti** [comment]
If you can't get it to behave correctly from CLI with OpenSSH, I guess there is no much point looking into what we can tell the net-ssh library.

We probably just need to unwrap them in post.

**Comment by davama** [comment]
> We probably just need to unwrap them in post.

which is exactly what i've been doing. see comment on [Aug 19](https://github.com/ytti/oxidized/issues/496#issuecomment-241076852).

Every now and then we notice new lines that wrap and so we have to update the procurve.rb file.

Well, worth the shot.

Thanks!

**Comment by Mad-Onion** [comment]
I had the same problem with my Procurve 2910al-48G. I could resolve it by adding the `:chars_wide => 1000` parameter to the _opts-array in the ssh-request-pty.
Line 96 in `input/ssh.rb`:

    ch.request_pty (_opts={:term=>'vt100', :chars_wide => 1000}) do |_ch, success_pty|

This parameter seems to get evaluated by the switch - maybe someone could test this with other machines!

**Comment by davama** [comment]
@Mad-Onion thanks for the reply. 

I was really hoping for a quick simple solution. Fortunately that does work but unfortunately it looks like the "secrets" are still present or the `:secret` block is being ignored in the procurve.rb file.

why would that be the case?

**Comment by Mad-Onion** [comment]
@davama did you enable the remove-secrets-feature in the main `config`-file?

    rest: 127.0.0.1:8888
    vars:
      remove_secret: true
    groups: {}

I tested it successfully

**Comment by davama** [comment]
yes, it's enabled

```
rest: 127.0.0.1:9002
rest_hide_enable: true
vars:
  remove_secret: true
```

Without the `:chars_wide => 1000` the secrets are removed. with it they are not.

For sanity sake i tried again. 
1st. removed all my gsub lines after `show running-config` which unwrap lines which become wrapped
`cfg.gsub! /^(sflow 1 polling)\n\s(\S+)\n((-|[A-L]|[0-9])\S+)\s60$/, '\\1 \\2\\3 60' # if "<ports>" gets cut into two lines`
Pulled the config and long lines wrap to the next line as expected.
2nd. changed the input/ssh.rb file as you suggested
`ch.request_pty (_opts={:term=>'vt100',:chars_wide=>1000}) do |_ch, success_pty|`
Repulled the config and lines no longer wrap but manager passwords appear.

before:
`password manager user-name "manager" sha1 <redacted>`
after:
`password manager user-name "manager" sha1 <passwordishere>`

It is of note that im am using custom `*.rb` files in ~/.config/oxidized/model/ directory. By custom i mean adding lines to the secret block and a few other show commands where needed.

oxidized version 0.15.0

What version you running? @Mad-Onion 

Thanks!

**Comment by Mad-Onion** [comment]
@davama I'm currently running 0.17.0

**Comment by davama** [comment]
Hmmm...
Let me try with latest pull...
Will report back
Thanks

**Comment by davama** [comment]
Ok, i figured out my issue. Turns out that the actual password string would wrap to the new line. The gsub i had in placed accommodated for that. Now that it does NOT wrap i had to change that gsub line. 

**NOTE**
Found an interesting behavior with output file. When the config is saved it is placed at the same level as the last directory in the tree. It would save it to `/home/config/` instead of `/home/config/repository/` directory. Had to change the config file to this and it saves where i want it to...
```
output:
   default: file
   file:
     directory: /home/config/repository/dummydirectorythatdoesnotexist/.
```
This might be related to the fact that i use nested groups. See #396 

So... i guess it works with changing the input/ssh.rb file: 

`ch.request_pty (_opts={:term=>'vt100',:chars_wide=>1000}) do |_ch, success_pty|`

This is great!! 

Created PR: https://github.com/ytti/oxidized/pull/591

Thanks @Mad-Onion 
Closing for good

**Comment by Mad-Onion** [comment]
@ytti will you implement this fix in the sources?

**Comment by Mad-Onion** [comment]
Thanks a lot, this solution is even better!
