### ISSUE TITLE
net/telnet isn't bundled in Ruby 2.3 any longer

### ISSUE THREAD

**Issue by danilopopeye** [ytti/oxidized#504]
We'll need to update the dependencies if we'd like to support ruby 2.3

```
* Net::Telnet
  * Net::Telnet is extracted to net-telnet gem. It's unmaintain code.
    [Feature #11083]
```

ref .: [NEWS-2.3.0](https://github.com/ruby/ruby/blob/trunk/doc/NEWS-2.3.0#L299-L301)

**Comment by ytti** [comment]
How can we do this in gemfile so that we also keep supporting earlier rubies? Or should we move the check to ```telnet.rb``` itself.

**Comment by danilopopeye** [comment]
just use the [plataforms](http://bundler.io/man/gemfile.5.html#PLATFORMS-platforms-) option :tada: 
``` ruby
gem 'net-telnet', plataforms: :ruby_23
```

Haven't tested it here, but remember using it in the past without problems. :+1:

**Comment by ytti** [comment]
Cool, thanks.

**Comment by ytti** [comment]
Hmm. Can I give that to add_runtime_dependency, does not seem like it.

**Comment by danilopopeye** [comment]
``` ruby
if defined?(RUBY_VERSION) && RUBY_VERSION > '2.3'
  s.add_runtime_dependency 'net-telnet'
end
```

ref.:  [elasticsearch.gemspec](https://github.com/elastic/elasticsearch-ruby/blob/cde7cbb25e3503986561e6a87bc1d403476a6d6f/elasticsearch/elasticsearch.gemspec)

**Comment by danilopopeye** [comment]
just tested and it works now on 2.3 :clap: 

could you cut a new version, please

**Comment by ytti** [comment]
done.
