### ISSUE TITLE
Custom Server

### ISSUE THREAD

**Issue by infinitydon** [ytti/oxidized#506]
Hello,

Please I need to use oxidized to backup a server that is based on Linux shell (no wrappers like junos, ios, etc). I could not find a generic template to use or is there one (may be I am missing sthg).

Shell prompt is like this:

**_===MME01 user@eqm01s0fp2 ANCB ~ #_**

The following are the commands that I need to run to get the active config:

**gsh export_config_active**
**cat ConfigFile_from_export**
**cat /etc/works/dns/named.conf**

**Comment by danilopopeye** [comment]
you can create a custom model for it. what is the name of the OS running? can you point to the page of the device?

``` ruby
class YOURSONAMEHERE < Oxidized::Model
  cmd 'gsh export_config_active'
  cmd 'cat ConfigFile_from_export'
  cmd 'cat /etc/works/dns/named.conf'

  cfg :ssh
end
```

this will probably work if you put it under `.config/oxidized/models/yoursonamehere.rb` then include a device using this new model in your `router.db`, something like:

``` csv
ip-or-dns:yoursonamehere:group-name-if-used:username:password
```

**Comment by infinitydon** [comment]
Thanks for the response @danilopopeye 

I have created the sgsnmme.rb file:

[root@localhost model]# more sgsnmme.rb
class sgsnmme < Oxidized::Model
  cmd 'gsh export_config_active'
  cmd 'cat ConfigFile_from_export'

  cfg :ssh
end

Also i edited my router.db file:

sgsn.mme.net:sgsnmme:user:pass2016

But I am getting the error below:

I, [2016-07-22T15:27:50.467629 #21628]  INFO -- : Oxidized starting, running as pid 21628
I, [2016-07-22T15:27:50.468099 #21628]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require': /usr/local/share/gems/gems/oxidized-0.15.0/lib/oxidized/model/sgsnmme.rb:1: class/module name must be CONSTANT (SyntaxError)
class sgsnmme < Oxidized::Model
               ^
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/share/gems/gems/oxidized-0.15.0/lib/oxidized/manager.rb:10:in `load'
        from /usr/local/share/gems/gems/oxidized-0.15.0/lib/oxidized/manager.rb:47:in `add_model'
        from /usr/local/share/gems/gems/oxidized-0.15.0/lib/oxidized/node.rb:169:in `resolve_model'
        from /usr/local/share/gems/gems/oxidized-0.15.0/lib/oxidized/node.rb:19:in `initialize'
        from /usr/local/share/gems/gems/oxidized-0.15.0/lib/oxidized/nodes.rb:19:in `new'
        from /usr/local/share/gems/gems/oxidized-0.15.0/lib/oxidized/nodes.rb:19:in `block (2 levels) in load'
        from /usr/local/share/gems/gems/oxidized-0.15.0/lib/oxidized/nodes.rb:15:in `each'
        from /usr/local/share/gems/gems/oxidized-0.15.0/lib/oxidized/nodes.rb:15:in `block in load'
        from /usr/local/share/gems/gems/oxidized-0.15.0/lib/oxidized/nodes.rb:111:in `synchronize'
        from /usr/local/share/gems/gems/oxidized-0.15.0/lib/oxidized/nodes.rb:111:in `with_lock'
        from /usr/local/share/gems/gems/oxidized-0.15.0/lib/oxidized/nodes.rb:10:in `load'
        from /usr/local/share/gems/gems/oxidized-0.15.0/lib/oxidized/nodes.rb:106:in `initialize'
        from /usr/local/share/gems/gems/oxidized-0.15.0/lib/oxidized/core.rb:14:in `new'
        from /usr/local/share/gems/gems/oxidized-0.15.0/lib/oxidized/core.rb:14:in `initialize'
        from /usr/local/share/gems/gems/oxidized-0.15.0/lib/oxidized/core.rb:4:in `new'
        from /usr/local/share/gems/gems/oxidized-0.15.0/lib/oxidized/core.rb:4:in `new'
        from /usr/local/share/gems/gems/oxidized-0.15.0/lib/oxidized/cli.rb:12:in `run'
        from /usr/local/share/gems/gems/oxidized-0.15.0/bin/oxidized:9:in `<top (required)>'
        from /usr/local/bin/oxidized:23:in `load'
        from /usr/local/bin/oxidized:23:in `<main>'

The node documentation is on an intranet and is not accessible to the public

**Comment by infinitydon** [comment]
I changed sgsmme to Sgsnmme (capital S) and the oxidized daemon was able to start but still not working, I got the following crash information:

`
2016-07-22 14:35:28 UTC
no block given [LocalJumpError]
--------------------------------------------------
/usr/local/share/gems/gems/oxidized-0.15.0/lib/oxidized/input/ssh.rb:22:in `instance_exec'
/usr/local/share/gems/gems/oxidized-0.15.0/lib/oxidized/input/ssh.rb:22:in `block in connect'
/usr/local/share/gems/gems/oxidized-0.15.0/lib/oxidized/input/ssh.rb:22:in `each'
/usr/local/share/gems/gems/oxidized-0.15.0/lib/oxidized/input/ssh.rb:22:in `connect'
/usr/local/share/gems/gems/oxidized-0.15.0/lib/oxidized/node.rb:61:in `run_input'
/usr/local/share/gems/gems/oxidized-0.15.0/lib/oxidized/node.rb:38:in `block in run'
/usr/local/share/gems/gems/oxidized-0.15.0/lib/oxidized/node.rb:33:in `each'
/usr/local/share/gems/gems/oxidized-0.15.0/lib/oxidized/node.rb:33:in `run'
/usr/local/share/gems/gems/oxidized-0.15.0/lib/oxidized/job.rb:9:in `block in initialize'
`

**Comment by danilopopeye** [comment]
hum, seems the `cfg` always need a block. can you try this?

``` ruby
cfg :ssh do
  # nothing
end
```

**Comment by infinitydon** [comment]
Thanks for the help so far @danilopopeye 

It is not giving any errors again, below is the snippet I used based on your response 

`class SGSNMME < Oxidized::Model
  prompt /^([>=~#])/
  cmd 'gsh export_config_active'
  cmd 'cat ConfigFile_from_export'

  cfg :ssh do
   pre_logout do
    send "exit\n"
   end
  end
end`

I had to experiment with the prompt, the default one is not working.

But the remaining issue is that it does not get all the config before exiting from the node which means it is getting a partial config (I think this is because the prompt regex is causing this which I noticed in the debug log).

May be am not getting the prompt  regex correctly or how do I tell oxidized to get the full config before continuing?

Thanks so far

**Comment by infinitydon** [comment]
Please can anyone help me further?

Oxidized is not capturing all the config.

I am thinking may be it is my Prompt definition that is causing this?

Any idea will be welcomed...

@danilopopeye  Many thanks for your help so far, I appreciate

**Comment by ytti** [comment]
If this is linux box running openssh, then there is no reason to do screenscraping, we don't need to wait for prompt at all, as we can run each command in new exec() channel, knowing exactly when command starts and end.

You can do this by saying

```
cfg :ssh do
  exec true
end
```

then each command will be ran in its own ```exec``` channel, and no shell will be spawned.

**Comment by infinitydon** [comment]
Many thanks @ytti 

Oxidized is now picking all the configurations...

Thanks to all, much appreciated.
