### ISSUE TITLE
screenOS versioning error (get system with current bandwith)

### ISSUE THREAD

**Issue by mediumo** [ytti/oxidized#508]
There is a problem with the "get system" part of the screenos model.
This happens at least on SSG320 Firewalls.

the output of the "get system" command includes a current bandwidth reading of the interfaces, e.g.:

> ! Interface ethernet0/2:
> !   description ethernet0/2
> !   *manage ip *.*.*.*, mac **.**.**.**
> !   route-deny disable
> !   bandwidth: physical 1000000kbps, configured egress [gbw 0kbps mbw 0kbps]
> !              configured ingress mbw 0kbps, current bw 622kbps
> !              total allocated gbw 0kbps

fix could be something like:

`cfg.gsub! /(current bw ).*/, '\\1<removed>'`

in the get system command, since the current bandwith isn't really necessary on config dumps.

Regards
Olaf

**Comment by ytti** [comment]
sure, do a pull request for the change

**Comment by mediumo** [comment]
pull-request created: #510
