### ISSUE TITLE
HP Procurve stacking (commander)

### ISSUE THREAD

**Issue by remydb** [ytti/oxidized#509]
When backing up an HP Procurve switch which is configured as a 'commander' switch with stacking the backups via Oxidized fail with the following logs:

```
Jul 25 17:24:42 server1 oxidized[12229]: 10.0.0.1 raised Oxidized::PromptUndetect with msg "unable to detect prompt: (?-mix:^\r?([\w -]+\eE)?([\w.-]+# )$)"
Jul 25 17:24:42 server1 oxidized[12229]: sw00_abc_def status no_connection, retry attempt 2
```

The reason is that there's an extra prompt for these switches. After logging in it shows a list of all the stack members and asks which one you wish to connect to. This looks like this:

```
  Stack Members

  SN MAC Address   System Name      Device Type Status
  -- ------------- ---------------- ----------- -------------------------
  0  000000-000000 sw00             HP 2524    Commander Up
  1  000000-000001 sw01             HP 2524    Member Up
  3  000000-000002 sw02             HP 2512    Member Up
  4  000000-000003 sw03             HP 2524    Member Up
  5  000000-000004 sw04             HP 2524    Member Up
  6  000000-000005 sw05                        Member Up
  7  000000-000006 sw06                        Member Up
  8  000000-000007 sw07             HP 2524    Member Up
  9  000000-000008 sw08             HP Switch  Member Up
  10 000000-000009 sw09                        Member Up
Enter switch number to connect to or <CR>:
```

Pressing enter will send you to the CLI of the local commander switch, which is what we want. So sending an extra "\n" after logging in should fix the problem, I think.

**Comment by ytti** [comment]
I don't have procurve and they are full of pain. You could add to the model expect /Enter switch number/, and send new line when expect is triggered.

**Comment by remydb** [comment]
After playing around a bit with the expects and such I got it to work. Cheers!

**Comment by HannesWad** [comment]
Hello remydb, 

may I kindly ask for your solution using the expects? 

Best regards
Hannes

**Comment by HannesWad** [comment]
Sorry @danilopopeye , I am new to Github. Those labels are like questions?
If so: I have one stack with two pieces of this device_model: HP ProCurve Switch 2510G-24 (J9279A)

The output where I have to choose a stack member looks like this:
```
  Stack Members

  SN MAC Address   System Name      Device Type           Status
  -- ------------- ---------------- --------------------- -------------------------
  0  002661-283600 Sw1               ProCurve 2510G-24    Commander Up
  1  002661-292540 Sw2               ProCurve 2510G-24    Member Up
Enter switch number to connect to or <CR>:
```

Thanks!

**Comment by remydb** [comment]
@HannesWad I fixed it by adding the following to the procurve.rb file:

```
  expect /Enter switch number/ do
    send "\n"
    ""
  end

```

Before the following line:
```
  expect /Press any key to continue(\e\[\??\d+(;\d+)*[A-Za-z])*$/ do
```

**Comment by HannesWad** [comment]
@remydb Thank you very much for answering!
I tried your solution, but could net get it working.
Next week I will try more!

**Comment by danilopopeye** [comment]
@HannesWad if you still have this problem, can you please open another issue?

**Comment by HannesWad** [comment]
@danilopopeye Yes, sure. 
But for the moment I will try to get this working on my own.
Maybe I will be able to get rid of this HP stack, this would be the best solution. ;-)
