### ISSUE TITLE
multiple devices behind single IP cause conflicts in logging

### ISSUE THREAD

**Issue by shailigum** [ytti/oxidized#511]
Opening thread to discuss options for enhancing logging to offer better debug for multiple devices behind a single IP (NAT scenarios).

Potential solutions include a) naming log files based on hostname instead of IP, or b) as @ytti suggested also include the port alongside IP for log files in the event a hostname is not used.

Option 'b' may be more flexible for a varying userbase since not everyone uses hostnames. 

Thoughts?

**Comment by shailigum** [comment]
Another option would to just include both - Hostname and IP in the title, adding useful at-a-glance information to the file itself and also causing no issues for those who don't use hostname:

In ssh/telnet.rb the line 24:

`@log = File.open(Oxidized::Config::Log + "/#{@node.ip}-ssh", 'w') if Oxidized.config.input.debug?`

Could be updated to include both `node.name` and `node.ip`, something to the effect of:

`@log = File.open(Oxidized::Config::Log + "/#{@node.name}_#{@node.ip}-ssh", 'w') if Oxidized.config.input.debug?`

**Comment by ytti** [comment]
we could also have configurable name, with substitutions for %i %h %p %m (m for method, like ssh/telnet).

I'm happy to accept PR for this. But no repetition of substitution, should be done in single place.

**Comment by ytti** [comment]
Probably easiest would be:

 1. outputs are passed node object, not string literal
 2. output.rb has generic method which returns string literal node name
 3. all outputs call the generic method

OR

 1. output.rb has class method to mangle the name
 2. worker.rb calls store with mangled name from output class method


thet method itself could probably be something like

```
def self.to_s node
  name = Oxidized.output.name_format.dup
  name.gsub! /%n/, node.name
  name.gsub! /%i/, node.ip 
  name.gsub! /%p/, node.vars[:telnet_port] if node.vars[:telnet_port]
  name.gsub! /%p/, node.vars[:ssh_port] if node.vars[:ssh_port]
  name.gsub! /%g/, node.group if node.group
  ### other subs we might want, maybe input/output/model as string?
  name
end
```

But maybe also hook, in case someone wants to do some mangling from external sources
