### ISSUE TITLE
Modify author and message in Commit

### ISSUE THREAD

**Issue by arko95** [ytti/oxidized#516]
Hello 

We would like to do a call at API with https://github.com/ytti/oxidized-web/blob/master/lib/oxidized/web/webapp.rb#L103 to modify the Author and message for Commit  with https://github.com/ytti/oxidized/blob/master/extra/rest_client.rb. How we could do it ? Could you give me some tips ?

**Comment by ytti** [comment]
Do these help:
https://github.com/ytti/oxidized/blob/master/extra/syslog.rb
https://github.com/ytti/oxidized/blob/master/extra/rest_client.rb

**Comment by arko95** [comment]
Yes it could helps,  but the idea it´s when we get the node configuration , be able to change the author and the default message 'updated < node_name >'. We want to get a personalized message and author name and then push it to our remote git . 
We are thinking to use oxidized-web RESTful API to do so . 

What we need to figure out it's how to use this endpoint to change author and message  ? : 
```
 # use this to attach author/email/message to commit
      put '/node/next/?:group?/:node' do
        node, @json = route_parse :node
        opt = JSON.load request.body.read
        nodes.next node, opt
        redirect url_for('/nodes') unless @json
        @data = 'ok'
        out
      end "
```

How to format json data to send with PUT method?
Can we use the [rest_client.rb](https://github.com/ytti/oxidized/blob/master/extra/rest_client.rb) to do this?

**Comment by ytti** [comment]
The syslog.rb and rest_client.rb have example how to accomplish

 1. give commit message and author
 2. ask oxidized to fetch config for node, attaching message and author to it

So you can only put this information in, before you ask oxidized to fetch some config.

What is your actual practical use case. Will the message and author be static always? Or will you somehow determine case-by-case what it will be, if so, how will you determine it?

**Comment by arko95** [comment]
What we want to do : Set a big interval of 24h for the automatic fetch of Oxidized. Then when one user modify some configuration during this interval, we wants that this user be able input  the node name, his author, a message to commit, and proceed to fetch of config . Exactly as button update (with glyphicon-repeat) do,  in the oxidized-web interface.

**Comment by ytti** [comment]
syslog.rb does that automatically, provided you're using junos which allows commit messages, in ios it'll just include the username.

But if you want to do this manually, then that's fine. Just have some script you use to edit device, and in the script after user exists device, you could ask 'fetch config?' and you could ask for commit message. Then you'll just lauch curl for the /next, like in rest_client.rb.

**Comment by arko95** [comment]
We figured out , how to do it , thank you .

**Comment by zyio** [comment]
Hi @arko95, any chance you could update this with your solution to help anyone else stumbling across this thread with similar issues in the future?

**Comment by danilopopeye** [comment]
@arko95 you could do a request like this:

```
PUT /node/next/:device
{
  "user": "username",
  "msg": "commit message goes here"
}
```
or with the `rest_client.rb`

``` ruby
rest = Oxidized::RestClient.new('localhost', 8888)
rest.next(name: 'device', user: 'username', msg: 'commit message goes here')
```

ref.: [lib/oxidized/nodes.rb](https://github.com/ytti/oxidized/blob/master/lib/oxidized/nodes.rb#L70-L72) & [extra/rest_client.rb](https://github.com/ytti/oxidized/blob/master/extra/rest_client.rb#L19-L22)

**Comment by myclau** [comment]
> @arko95 you could do a request like this:
> 
> ```
> PUT /node/next/:device
> {
>   "user": "username",
>   "msg": "commit message goes here"
> }
> ```
> or with the `rest_client.rb`
> 
> ```ruby
> rest = Oxidized::RestClient.new('localhost', 8888)
> rest.next(name: 'device', user: 'username', msg: 'commit message goes here')
> ```
> 
> ref.: [lib/oxidized/nodes.rb](https://github.com/ytti/oxidized/blob/master/lib/oxidized/nodes.rb#L70-L72) & [extra/rest_client.rb](https://github.com/ytti/oxidized/blob/master/extra/rest_client.rb#L19-L22)

Thanks for inspiration,

As I not very good at Ruby, So I do it in another way.

first creat a hook type using `exec` and using events `post_store` in config file, make sure you put it above `push_to_remote`

```
update_node_msg:
    type: exec
    events: [post_store]
    cmd: "bash /home/oxidized/.config/oxidized/script/update_node_msg.sh"
    timeout: 10
```
In update_node_msg.sh
```bash
#!/bin/bash
cd /home/oxidized/.config/oxidized/devices.git

msg=$(git show master:${OX_NODE_NAME} | grep "! Configuration last modified by")
msg=${msg/! /}
echo "[Info] Node Message: ${msg}"
jsonbody="{\"msg\":\"${msg}\"}"
echo "[Info] Update Node message for ${OX_NODE_NAME}"
curl -s -S -H 'Content-Type: application/json' -X PUT \
-d "${jsonbody}\"  \
http://localhost:8888/node/next/${OX_NODE_NAME}
echo "[Info] Updated"

```


Hope it can help for non Ruby guys.
