### ISSUE TITLE
interval settings

### ISSUE THREAD

**Issue by arko95** [ytti/oxidized#521]
Hello 

Is it possible to set a different interval by node or by group ?  We have some F5 that have some dynamic pool changing configuration  everytime, and we would like for them to set a bigger interval

**Comment by ytti** [comment]
This is not possible today. Why not normalise the config in model and remove dynamically changing config?

**Comment by danilopopeye** [comment]
@arko95 can we close this issue?

**Comment by arko95** [comment]
hello , yes , I do it
