### ISSUE TITLE
SSH Proxy/Jumpbox

### ISSUE THREAD

**Issue by ProLive** [ytti/oxidized#527]
Not an issue, more a question.
Are there any configuration examples on how to actually use this feature? Can't seem to get it to work. Could an example be provided if say the router we are trying to backup is 192.168.1.1 and the jumpbox/SSH proxy we are trying to use is 192.168.2.1.
Also, can you use seperate usernames and passwords for each the end device and SSH proxy?

**Comment by ytti** [comment]
You define variable ```ssh_proxy_host```, then we'll fork 'ssh' to connect there. So your normal ssh commands will be honoured, including authentication details.

**Comment by ProLive** [comment]
Thanks, how do you define a username and password for the SSH Proxy?

**Comment by ytti** [comment]
You do it in your ssh config, usually openssh config. Most people I guess will use keys. If 'ssh' works from CLI, it should work with oxidized.

**Comment by ytti** [comment]
Can this be closed?

**Comment by ProLive** [comment]
I don't quite understand how to make it work through an SSH proxy, but sure, I will seek assistance elsewhere.

**Comment by danilopopeye** [comment]
@ProLive this Gentoo doc seems to cover it well: https://wiki.gentoo.org/wiki/SSH_jump_host.
if you could connect via SSH to the device using your jumpbox, oxidized should be able to do it also.

here's a configuration example based on the info you provided: :smile: 

``` yaml
# config.db
192.168.1.1:ios:routers:192.168.2.1
```
``` yaml
# config
input:
  default: csv
  csv:
    map:
      name: 0
      model: 1
      group: 2
    vars_map:
      ssh_proxy: 4
```

**Comment by danilopopeye** [comment]
@ProLive the above info was suffice? can we close this issue?

**Comment by laf** [comment]
@ytti This looks like this can be closed, the OP hasn't responded to the last two replies in over 6 months.
