### ISSUE TITLE
TypeError - no implicit conversion of Oxidized::Node into String:

### ISSUE THREAD

**Issue by SmokuSCB** [ytti/oxidized#529]
Hi,
I'm trying to get oxidized to work with the WatchGuard device (firewareos). I was able to connect to the WatchGuard oxidized, but when trying enter to configurations in the action menu in the node list gets a following error: 

> 2016-08-17 12:03:54 - TypeError - no implicit conversion of Oxidized::Node into String:
>         /usr/local/share/gems/gems/oxidized-0.16.2/lib/oxidized/output/file.rb:35:in `join'
>         /usr/local/share/gems/gems/oxidized-0.16.2/lib/oxidized/output/file.rb:35:in `fetch'
>         /usr/local/share/gems/gems/oxidized-0.16.2/lib/oxidized/nodes.rb:61:in `block in fetch'
>         /usr/local/share/gems/gems/oxidized-0.16.2/lib/oxidized/nodes.rb:174:in `block in yield_node_output'
>         /usr/local/share/gems/gems/oxidized-0.16.2/lib/oxidized/nodes.rb:126:in `synchronize'
>         /usr/local/share/gems/gems/oxidized-0.16.2/lib/oxidized/nodes.rb:126:in `with_lock'
>         /usr/local/share/gems/gems/oxidized-0.16.2/lib/oxidized/nodes.rb:170:in `yield_node_output'
>         /usr/local/share/gems/gems/oxidized-0.16.2/lib/oxidized/nodes.rb:60:in `fetch'
>         /usr/local/share/gems/gems/oxidized-web-0.7.1/lib/oxidized/web/webapp.rb:79:in `block in <class:WebApp>'
>         /usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `call'
>         /usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `block in compile!'
>         /usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `[]'
>         /usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
>         /usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:994:in `route_eval'
>         /usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
>         /usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:1015:in `block in process_route'
>         /usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `catch'
>         /usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `process_route'
>         /usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:973:in `block in route!'
>         /usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `each'
>         /usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `route!'
>         /usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:1085:in `block in dispatch!'
>         /usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
>         /usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
>         /usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
>         /usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:1082:in `dispatch!'
>         /usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `block in call!'
>         /usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
>         /usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
>         /usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
>         /usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `call!'
>         /usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:895:in `call'
>         /usr/local/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
>         /usr/local/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
>         /usr/local/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
>         /usr/local/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
>         /usr/local/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
>         /usr/local/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
>         /usr/local/share/gems/gems/rack-1.6.4/lib/rack/nulllogger.rb:9:in `call'
>         /usr/local/share/gems/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
>         /usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/show_exceptions.rb:25:in `call'
>         /usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:182:in `call'
>         /usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:2013:in `call'
>         /usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `block in call'
>         /usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:1787:in `synchronize'
>         /usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `call'
>         /usr/local/share/gems/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in `block in call'
>         /usr/local/share/gems/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `each'
>         /usr/local/share/gems/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `call'
>         /usr/local/share/gems/gems/rack-1.6.4/lib/rack/builder.rb:153:in `call'
>         /usr/local/share/gems/gems/puma-2.16.0/lib/puma/server.rb:557:in `handle_request'
>         /usr/local/share/gems/gems/puma-2.16.0/lib/puma/server.rb:404:in `process_client'
>         /usr/local/share/gems/gems/puma-2.16.0/lib/puma/server.rb:270:in `block in run'
>         /usr/local/share/gems/gems/puma-2.16.0/lib/puma/thread_pool.rb:106:in `call'
>         /usr/local/share/gems/gems/puma-2.16.0/lib/puma/thread_pool.rb:106:in `block in spawn_thread' 

My config:
```
username: redacted
password: redacted
model: firewareos
interval: 3600
log: /home/oxidized/.config/oxidized/log
use_syslog: false
debug: true
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: redacted:8888
vars: {}
groups: {}
pid: /home/oxidized/.config/oxidized/pid
input:
  default: ssh, telnet
  debug: false
  ssh:
    secure: false
output:
  file:
    directory: /home/oxidized/.config/oxidized/configs
source:
  default: csv
  csv:
    file: /home/oxidized/.config/oxidized/router.db
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
      username: 2
      password: 3
    vars_map:
      ssh_port: 4
model_map:
  cisco: ios
  juniper: junos

```
I running Oxidized on fresh installed and updated Centos 7 with selinux in permissive mode. I would be grateful for any suggestion or help. Thx,

**Comment by ytti** [comment]
Can you change output to git and see if you can recreate. This looks like bug file output and/or oxidized-web. But would be nice to have confirmation that on git output it works for you.

**Comment by SmokuSCB** [comment]
You were right, I checked and after the change output to git error does not occur. As for me, it is enough solution to my problem. Thx

**Comment by ytti** [comment]
I think this was broken in de2a9d18a5847 now we pass node object (which is sensible) to output, but file output was not updated to the change. @danilopopeye can you confirm?

**Comment by danilopopeye** [comment]
@ytti yeah, seems like it. I'll make a PR today.

**Comment by danilopopeye** [comment]
@SmokuSCB could you please test my changes above? :point_up:

**Comment by sorano** [comment]
Just setup a new oxidzed install (gem install) with file output configuration and experienced this issue.

oxidized -v
0.16.3

Manually replacing /var/lib/gems/2.3.0/gems/oxidized-0.16.3/lib/oxidized/output/file.rb with the changes from https://github.com/ytti/oxidized/commit/699136c8c3a1a409a2eaa19019ec6df6bb4b61e0 solved the problem. So I guess its safe to merge this fix into the gem.

**Comment by ytti** [comment]
I hope to release 0.17.0 today or weekend.
