### ISSUE TITLE
SAOS Paging

### ISSUE THREAD

**Issue by ijg0** [ytti/oxidized#530]
When using OXS and running a "config show" it fails to page and gets stuck:

`[more 0%] (q,g,space,enter)`

I haven't been able to test using Oxidized yet as we have a separate issue with it not connecting correctly.

(Also of note there is a typo in readme.md with is listed as SOAS instead os SAOS).

**Comment by ytti** [comment]
Is it possible to get access to sanitised SAOS device? I'd login from 91.198.120.1, you can supply authentication details to saku@ytti.fi

**Comment by jgroom33** [comment]
@ijg0  a pre-request command should be supplied to disable the | more
Review the device documentation to determine the proper command to disable paging

**Comment by laf** [comment]
@ijg0 Have you tried what @jgroom33 has recommended?

**Comment by ijg0** [comment]
@laf - I worked through this with @ytti. The cause wasn't confirmed but was believed to be fixed after upgrading net-ssh (see issue 565).

**Comment by laf** [comment]
@ijg0 So can this be closed if it's now resolved?

**Comment by jgroom33** [comment]
system shell set global-more off
^ correct pre-request line
or if you want something less persistent:
system shell session set more off

**Comment by laf** [comment]
Thanks @jgroom33. Closing now but feel free to respond if anyone has any further questions.
