### ISSUE TITLE
Cannot connect to pfsense

### ISSUE THREAD

**Issue by OBenned** [ytti/oxidized#535]
Hi guys.

Im having some issues with the pfsense part of oxidized, it doesent seem to complete the connection properly, the only message i get when trying to connect is:

```
D, [2016-08-19T16:26:31.543146 #2433] DEBUG -- : lib/oxidized/worker.rb: Added xxx.xxx.xxx.xxx to the job queue
D, [2016-08-19T16:26:31.543188 #2433] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2016-08-19T16:26:31.543294 #2433] DEBUG -- : lib/oxidized/job.rb: Starting fetching process for xxx.xxx.xxx.xxx at 2016-08-19 14:26:31 UTC
D, [2016-08-19T16:26:31.543486 #2433] DEBUG -- : lib/oxidized/input/ssh.rb: Connecting to xxx.xxx.xxx.xxx
D, [2016-08-19T16:26:31.712795 #2433] DEBUG -- : lib/oxidized/input/cli.rb: Running post_login commands at xxx.xxx.xxx.xxx
D, [2016-08-19T16:26:31.712901 #2433] DEBUG -- : lib/oxidized/model/model.rb Collecting commands' outputs
D, [2016-08-19T16:26:31.712976 #2433] DEBUG -- : lib/oxidized/model/model.rb Executing cat /cf/conf/config.xml
D, [2016-08-19T16:26:31.713024 #2433] DEBUG -- : lib/oxidized/input/ssh.rb cat /cf/conf/config.xml @ xxx.xxx.xxx.xxx with expect: /^([\w.@-]+[#>]\s?)$/
D, [2016-08-19T16:26:32.543592 #2433] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2016-08-19T16:26:33.543922 #2433] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2016-08-19T16:26:34.544262 #2433] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2016-08-19T16:26:35.544553 #2433] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2016-08-19T16:26:36.544841 #2433] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2016-08-19T16:26:37.545133 #2433] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2016-08-19T16:26:38.545448 #2433] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2016-08-19T16:26:39.545823 #2433] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2016-08-19T16:26:40.546136 #2433] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2016-08-19T16:26:41.546498 #2433] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2016-08-19T16:26:42.546888 #2433] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2016-08-19T16:26:43.547298 #2433] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2016-08-19T16:26:44.547661 #2433] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2016-08-19T16:26:45.548076 #2433] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2016-08-19T16:26:46.548422 #2433] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2016-08-19T16:26:47.548747 #2433] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2016-08-19T16:26:48.549081 #2433] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2016-08-19T16:26:49.549388 #2433] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2016-08-19T16:26:50.549781 #2433] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2016-08-19T16:26:51.550123 #2433] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2016-08-19T16:26:52.550443 #2433] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2016-08-19T16:26:53.550780 #2433] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2016-08-19T16:26:54.551127 #2433] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2016-08-19T16:26:55.551478 #2433] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2016-08-19T16:26:56.551846 #2433] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2016-08-19T16:26:57.552191 #2433] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2016-08-19T16:26:58.552524 #2433] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2016-08-19T16:26:59.552850 #2433] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2016-08-19T16:27:00.553199 #2433] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
```

I have discussed the issue in here earlier: https://github.com/ytti/oxidized/pull/525#issuecomment-241054206

The problem right now is that nothing is getting in the input log

**Comment by ytti** [comment]
What does ```gem list net-ssh``` say? If it says newer than 3.0.x, can you install 3.0.2 and uninstall rest?

**Comment by OBenned** [comment]
It says: net-ssh (3.0.2)
So i would need to uninstall what?

**Comment by ytti** [comment]
No that's fine.

Can you sanitise one device and make it reachable from 91.198.120.1, so that I can investigate why it does not work.

**Comment by OBenned** [comment]
I have a device ready, should i DM you details on github?

**Comment by ytti** [comment]
saku@ytti.fi email will be fine

**Comment by OBenned** [comment]
Should be on its way now

**Comment by ytti** [comment]
This does not work even from OpenSSH client:

```ssh -vvv admin@185.85.7.48 "cat /cf/conf/config.xml"```

will hang forever after:
```debug1: Sending command: cat /cf/conf/config.xml
debug2: channel 0: request exec confirm 1
debug3: send packet: type 98
debug2: callback done
debug2: channel 0: open confirm rwindow 0 rmax 32768
debug2: channel 0: rcvd adjust 2097152
debug3: receive packet: type 99
debug2: channel_input_status_confirm: type 99 id 0
debug2: exec request accepted on channel 0
debug3: receive packet: type 98
debug1: client_input_channel_req: channel 0 rtype keepalive@openssh.com reply 1
debug3: send packet: type 100
debug3: receive packet: type 98
debug1: client_input_channel_req: channel 0 rtype keepalive@openssh.com reply 1
debug3: send packet: type 100
...
```

**Comment by ytti** [comment]
@stokbaek do you see this behaviour in latest release? It looks like 'exec' mode simply isn't working anymore.

**Comment by stokbaek** [comment]
@ytti @OBenned I have tried updating to 0.16.2 and mine works fine. The pfsense I tried on was a plain installation with pretty much no configuration. I tried with custom user and with root. Both works for me.

What version of PfSense are you using @OBenned?

**Comment by OBenned** [comment]
The box i tested with is: 2.3.1
Can it be because of the interactive menu on login?

**Comment by stokbaek** [comment]
@OBenned no when it runs as exec mode will it skip the menu. It works on 2.3.1 and 2.3.2 for me. Haven't tested other versions.

**Comment by OBenned** [comment]
Hmm, thats really weird

**Comment by ytti** [comment]
@stokbaek and it works for you from OpenSSH CLI too? Because then we can completely exclude/ignore oxidized. If it works from OpenSSH CLI for you, but not for @OBenned then we can solely focus why your devices behave differently, and is this some configuration setting on the boxes.

**Comment by stokbaek** [comment]
@ytti Yes, it works with OpenSSH CLI too here. My PfSense is a clean installation with SSH module enabled from the CLI menu. This is the only change I have made

**Comment by OBenned** [comment]
I agree, just tried with my pfsense box at home, same problem.
can it be something in my oxidized install thats not setup correctly?

**Comment by ytti** [comment]
@OBenned I don't understand how it can be oxidized issue, when it does not even work from OpenSSH CLI for you. 

This should work:
```ssh admin@a.b.c.d "cat /cf/conf/config.xml"```

If it does not work, Oxidized can't work either.

**Comment by OBenned** [comment]
Okay, did try now to use root user, and that works.
But that doesen't make sense since @stokbaek can get it to work with a custom user

**Comment by stokbaek** [comment]
@OBenned if you haven't granted the admin user ssh rights, this is not something it as standard, will it fail.

**Comment by OBenned** [comment]
Yeah i know, but the user has ssh rights on the pfsense

**Comment by stokbaek** [comment]
@OBenned I just tried with admin. I cant get this user to work either. This seems to be a problem with the admin user. I got no problem using another user I made named oxidized

**Comment by grantemsley** [comment]
The actual problem here is that the admin user is actually 'root' when accessing via SSH. If you specify the user as root, it works fine.
