### ISSUE TITLE
Docker instructions

### ISSUE THREAD

**Issue by OzNetNerd** [ytti/oxidized#540]
Hi there,

I believe there might be an error in the "Running with Docker" instructions. The "run container the first time" step creates a container while the "run container again" does not run the container again, it actually creates a second container as per the output below:

```
[will@localhost ~]$ sudo docker ps -a
CONTAINER ID        IMAGE                      COMMAND             CREATED             STATUS                     PORTS                    NAMES
2ab5eaa10ece        oxidized/oxidized:latest   "/sbin/my_init"     29 seconds ago      Up 27 seconds              0.0.0.0:8888->8888/tcp   berserk_hamilton
9078cd3c407e        oxidized/oxidized:latest   "oxidized"          7 minutes ago       Exited (0) 7 minutes ago                            cranky_ritchie
```

If I understand the process correctly, the only reason why the first container is created is so that it can create the `/etc/oxidized/config` on the host (persistent storage). 

If this is correct then so long as you create the config file manually, as well as the `/etc/oxidized/router.db` file, you don't actually need to create the first container. You can jump straight to configuring the second one:

`root@bla:~# docker run -v /etc/oxidized:/root/.config/oxidized -p 8888:8888/tcp -t oxidized/oxidized:latest`

I have done this and it appears to be working OK.

```
[will@localhost ~]$ sudo docker ps
CONTAINER ID        IMAGE                      COMMAND             CREATED             STATUS              PORTS                    NAMES
a8ff75dccb15        oxidized/oxidized:latest   "/sbin/my_init"     46 minutes ago      Up 46 minutes       0.0.0.0:8888->8888/tcp   modest_stallman

```

**Comment by danilopopeye** [comment]
> If I understand the process correctly, the only reason why the first container is created is so that it can create the /etc/oxidized/config on the host (persistent storage).

yes, you understood correctly.



> If this is correct then so long as you create the config file manually, as well as the /etc/oxidized/router.db file, you don't actually need to create the first container. You can jump straight to configuring the second one:

updated the docs in #542.

thanks for point this out. 👏
