### ISSUE TITLE
Alvarion support

### ISSUE THREAD

**Issue by MajesticFalcon** [ytti/oxidized#546]
Support for getting backups from Alvarion equipment

**Comment by ytti** [comment]
Can you put sanitised version of device online, so that it is reachable via 91.198.120.1. Email authentication details to saku@ytti.fi

**Comment by MajesticFalcon** [comment]
I was hoping I could take care of this one. It will require a new input 'tftp' which uses the same commands as your 'ftp'. I already have a script that backs them up, I am just trying to figure out how to put it into your software

**Comment by ytti** [comment]
Cool, let me know if you need help. Yeah by looking at the zyxel model which uses ftp, I think you can add tftp input method and model which uses it.
