### ISSUE TITLE
Instantiate method 

### ISSUE THREAD

**Issue by MajesticFalcon** [ytti/oxidized#549]
We need an alias for pre do and post do

Possibly 

`Instantiate do
  Node.instance_method
end`

**Comment by ytti** [comment]
I'd like to protect model makers from too much technical detail about ruby. So I don't think 'instansiate' would be correct. 

Behaviour/implementation can be, from my POV, exactly same as pre or post. I'm not yet even sure if alias is needed, not unless there is some clear word to describe which will be considerably more self-documenting/helpful than pre/post
