### ISSUE TITLE
Prompt waiting on enable for catos

### ISSUE THREAD

**Issue by boudreau** [ytti/oxidized#551]
Hi, got oxidized running with most of my other devices. But the catos don't seem to go through the enable step.

in the input telnet log:
Connected to xxx.xxx.xxx.xxx.

User Access Verification

Username: nocncs
Password:
bronfman-c6k> Trying xxx.xxx.xxx.xxx...
Connected to xxx.xxx.xxx.xxx.
<rinse and repeat>

and the syslog:
Sep  2 08:25:17 odin oxidized[39592]: bronfman-c6k.xxxxx.xx status no_connection, retry attempt 3
Sep  2 08:25:39 odin oxidized[39592]: xxx.xxx.xxx.xxx raised Oxidized::PromptUndetect with msg "unable to detect prompt: (?-mix:^[\w.@-]+> \(enable\) $)"

It does that with all our old catos devices.

the config:
<snip>
```
interval: 7200
use_syslog: true
#Listen on http://127.0.0.1:8888/ for API
rest: 127.0.0.1:8888
debug: false
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
groups:
  catos:
    username: nocncs
    password: xxxxxxxx
    vars:
      enable: xxxxxxxx
pid: /home/oxidized/.config/oxidized/pid
input:
  default: ssh, telnet
  debug: /tmp/oxidized/log_input
  ssh:
    secure: false
<snip>
```

Any ideas?

Thanks

**Comment by ytti** [comment]
The model is done for autoenabled CatOS. I can fix the model if you give me access to sanitised device from 91.198.120.1. You can send auth credentials to saku@ytti.fi.

If this is not possible, you should look at catos.rb and say ios.rb to see how to implement enable support to catos.rb.

**Comment by boudreau** [comment]
Sorry don't have access to a spare one. I'll take a look and keep you informed.

Thanks

**Comment by ytti** [comment]
I'm confident you're able to do it after looking at ios.rb. Just make sure prompt matches on both scenarios and that post_login handles enable conditionally.

You can try to put your modified model in ~/.config/oxidized/model/catos.rb so that modified version is used instead of distribution.

Good luck.

**Comment by boudreau** [comment]
ok, thanks for the tip

**Comment by boudreau** [comment]
Got it working, here is my file:

more catos.rb
class Catos < Oxidized::Model

#prompt /^[\w.@-]+> \(enable\) $/
#prompt /^[\w.@-]+> $/
  prompt /^[\w.@-]+> (\(enable\) )?$/
  comment '# '

  cmd :all do |cfg|
    cfg.each_line.to_a[1..-2].join
  end

  cmd 'show system' do |cfg|
    cfg = cfg.gsub /(\s+)\d+,\d+:\d+:\d+(\s+)/, '\1X\2'
    comment cfg
  end

  cmd 'show version' do |cfg|
    cfg = cfg.gsub /\d+(K)/, 'X\1'
    cfg = cfg.gsub /^(Uptime is ).*/, '\1X'
    comment cfg
  end

  cmd 'show conf all' do |cfg|
    cfg = cfg.sub /^(#time: ).*/, '\1X'
    cfg.each_line.drop_while { |line| not line.match /^begin/ }.join
  end

  cfg :telnet do
    username /^Username: /
    password /^Password:/
  end

  cfg :telnet, :ssh do
    post_login 'set length 0'
    # preferred way to handle additional passwords
    if vars :enable
      post_login do
        send "enable\n"
        cmd vars(:enable)
      end
    end
    pre_logout 'exit'
  end

end

**Comment by ytti** [comment]
Cool, send pull request for the model.

**Comment by boudreau** [comment]
I just did the pull request
