### ISSUE TITLE
Support for ruby 1.9.3 failing

### ISSUE THREAD

**Issue by MajesticFalcon** [ytti/oxidized#553]
##@##  ~ $ ruby -v
ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]
##@## ~ $ sudo gem install oxidized
ERROR:  Error installing oxidized:
	net-ssh requires Ruby version >= 2.0.
This is caused by ruby's library 'net-ssh' major version 3 starting to require ruby version >= 2.0
Oxidized requires net-ssh > 3.0

**Comment by ytti** [comment]
We don't support 1.9.3
https://github.com/ytti/oxidized/blob/master/oxidized.gemspec#L21

1.9.3 has been end-of-support for over 1.5 years. And to my knowledge every stable release of every Linux distribution ships with 2.0 or newer. 

https://www.ruby-lang.org/en/news/2015/02/23/support-for-ruby-1-9-3-has-ended/

**Comment by MajesticFalcon** [comment]
Submitted PR to fix the README which indicates support for Ruby 1.9.3
