### ISSUE TITLE
Email notification on failed devices

### ISSUE THREAD

**Issue by sakthimaan** [ytti/oxidized#561]
Please send email notification to Network admins if backup is getting failed for any of the devices. 
Also add support for send device configuration changes in email.

**Comment by ytti** [comment]
I'd like to say these are important to me, but they are not. 

I imagine vast majority of organisations already have stash, github, gitlab or equivalent installation, one which can already send diffs, reusing this reduces complexity for the organisation.

I also think emails are overused, email is not ticketing system, it's extremely poor guarantee that things are actually acted upon. We can get JSON data from node's configuration fetch information, we can easily inject this JSON data to any monitoring system, to get actual actionable alerts in your  normal alerting system.

Having said, that I'm not going to close this case. I maybe completely wrong, I may be missing obvious use cases.  So I'd like other people to participate and give their opinion on the matter.

I would definitely accept hooks for either of the problem. I might accept it in core. I'm not going to develop it.

**Comment by rfdrake** [comment]
I like your idea of having a git hook send the change notice.  It would allow the email to be customized according to business logic, maybe highlight certain changed lines in the diff.

Here is something I found while searching "git post commit hook email diff"

http://stackoverflow.com/questions/552360/git-hook-to-send-email-notification-on-repo-changes

I think a good change to oxidized would be to add documentation with an example of how to setup the git email hook.  People coming from rancid might expect the emails.  Even if some people can be convinced the methodology is wrong, others might still miss the emails.

**Comment by ytti** [comment]
We have this hook ```https://github.com/ytti/oxidized/blob/master/extra/oxidized-report-git-commits```

**Comment by lobo5519** [comment]
Partial agreement - I am using Gitlab which already has the ability to send an email (or generate a ticket) on a change with the diff. I think the more important feature is to generate and email/ticket on failing to login to a device. I'm not sure how else to detect that. 

Oxidized-web isn't proactive and I actually just disabled it due to lack of authentication and the configs are available.

**Comment by ytti** [comment]
You have access to JSON data of devices, I know some companies have very advanced metrics and graphs about device config backup performance based on the JSON stats of devices.

Regardless what your monitoring system is, it should be somewhat easy to digest the JSON data and produce custom alerts.
