### ISSUE TITLE
Add support for Stormshield/Netasq UTM

### ISSUE THREAD

**Issue by rverchere** [ytti/oxidized#563]
Stormshield is a french company providing UTMs.

It would be nice to support configuration saving for these equipments (especially former Netasq appliances).

Thanks!

**Comment by ytti** [comment]
If you can offer me sanitised access to a device, I'm happy to look into it. I'd come from 91.198.120.1. You can send auth details to saku@ytti.fi.

**Comment by rverchere** [comment]
I'll try to find one, I'll let you know!

**Comment by bennic** [comment]
Hi,

Can you please help me to develop it ?

**Comment by jbperrin88** [comment]
i'm ok to help for this kind of devices !

**Comment by jbperrin88** [comment]
you can make it VM way in GNS3 ! easily

**Comment by kocha9** [comment]
Hi, any update on this topic? I'm really looking forward for it

**Comment by bennic** [comment]
Hello Nop, nothing.
I made something by myself which complete the backup.

Benjamin
