### ISSUE TITLE
net-ssh 3.1.0.rc2 issue with Debian/Ruby2.1

### ISSUE THREAD

**Issue by ijg0** [ytti/oxidized#565]
Similar issue to #472 but we are using Debian Jessie (8.5) without Docker. As such we don't have an easy upgrade path to Ruby 2.2 or 2.3 to resolve the net-ssh version issue.

**Comment by ytti** [comment]
You've installed oxidized via gem? Which release? And it installed net-ssh 3.1.0rc2? And if you remove net-ssh completely with gem, and reintall oxidized, it'll fetch net-ssh 3.1.0rc2?

**Comment by ijg0** [comment]
All correct. We are using oxidized-0.16.3.gem

**Comment by ytti** [comment]
It might be that I don't understand how dependency is set correctly.

If you don't mind, try this:

  1. clone the repo
  2. edit ```oxidized.gemspec```
  3. move the dependencies in an array,  ```[ '>= 3.0.0', '<3.1' ]```
  4. build the package ```rake build```
  5. install it ```gem install pkg/oxidized-0.16.3.gem```

Of course uninstall net-ssh and oxidized first. 

Will that still install incorrect net-ssh or correct?

**Comment by ijg0** [comment]
Oddly it still pulls net-ssh 3.1.0rc2.

As a work around installing net-ssh 3.0.2 before oxidized solves the issue.

**Comment by ytti** [comment]
I don't understand what's going on here :(
