### ISSUE TITLE
HP Procurve 1920

### ISSUE THREAD

**Issue by alexal12** [ytti/oxidized#566]
Is it possible to add support of HP procurve switch 1920?

log :

W, [2016-09-16T08:30:51.762207 #4003]  WARN -- : 10.90.80.10 raised Oxidized::PromptUndetect with msg "

---
- Copyright (c) 2010-2015 Hewlett-Packard Development Company, L.P.          *
- Without the owner's prior written consent,                                 *
- no decompiling or reverse-engineering shall be allowed.                    *
  ******************************************************************************

<xxx-switch-xxxx> not matching configured prompt (?-mix:^\r?([\w -]+\eE)?([\w.-]+# )$)"

**Comment by ytti** [comment]
If you can give access to sanitised version I'll do my best, but HP procurve is so far the worst device to do screenscraping with.

I'd come from 91.198.120.1. You can send authentication details to saku@ytti.fi

**Comment by laf** [comment]
@alexal12 The procurve model has been updated about 5 times since your original issue, have you updated recently to test this? If so and it still doesn't work, have you provided the info needed that ytti has asked for?

**Comment by WiXZlo** [comment]
HP1910 works excellent as model Comware with 
 `   vars_map:`
  `    comware_cmdline: 6`
For 1910 password "512900", for 1920 password "Jinhua1920unauthorized"
