### ISSUE TITLE
Possible subscription to coveralls.io?

### ISSUE THREAD

**Issue by MajesticFalcon** [ytti/oxidized#567]
What do you think about adding the code coverage from coveralls.io?

I am curious how many more tests need to be written. I would be open to writing them. @ytti

**Comment by ytti** [comment]
Tons, we're very poorly tested. This sounds like a great idea.

**Comment by danilopopeye** [comment]
> I am curious how many more tests need to be written.

I've tried to write a few more but right now its kind of painful to do it. (no offense @ytti ❤️)
I think that coveralls will be useful if/when we decided to refactor some major parts so we can test it.

**Comment by ytti** [comment]
None taken, it is always painful post-fact, because then you don't have to think about testing when writing, which leads to hard to test code (which is polite way to say untestable code). I didn't really expect oxidized to become useful to others, it was stop-gap solution to specific problem.

**Comment by danilopopeye** [comment]
after a major refactoring and a proper test suite, this __should__ be used. closing until that time 😉
