### ISSUE TITLE
TypeError - no implicit conversion of Oxidized::Node into String:

### ISSUE THREAD

**Issue by realnakrul** [ytti/oxidized#568]
Hi
I am trying to run oxidized on Ubuntu 16.04.1 LTS with LibreNMS
This is my config:
---
rest: 0.0.0.0:8888
source:
    default: http
    insecure: true
    debug: true
    http:
      url: http://127.0.0.1/api/v0/oxidized
      scheme: http
      delimiter: !ruby/regexp /:/
      map:
        name: hostname
        model: os
        group: group
      headers:
        X-Auth-Token: c6af72e72cbcce781e1d2d443344e831
output:
  file:
    directory: "/var/lib/oxidized/configs/"
groups:
  default:
    username: aaa
    password: aaa

But when I start oxidized I get:
at CLI:
I, [2016-09-19T09:03:19.500436 #24504]  INFO -- : Configuration updated for default/192.168.1.1
2016-09-19 09:03:39 - TypeError - no implicit conversion of Oxidized::Node into String:
at WebGUI when trying to see config of the device:

TypeError at /node/fetch/default/192.168.1.1
no implicit conversion of Oxidized::Node into String
file: file.rb location: join line: 33 

Also I noticed that folder /var/lib/oxidized/configs is empty. I get config in /var/lib/oxidized/default

But my output config is: 
directory: "/var/lib/oxidized/configs/" 

What I am doing wrong?

**Comment by ytti** [comment]
You're not doing nothing wrong. It's just broken. If you switch to ```git``` it'll work. This was fixed in https://github.com/ytti/oxidized/pull/547 but it's not included in any released version.

**Comment by realnakrul** [comment]
Dear ytti, 
Thank you for reply. 
Then it worth to update readme.md not to confuse people with installation procedure. Could you tell me how can I switch to git? I am Cisco engineer, but unfortunatelly I am not so skilled with linux.

**Comment by ytti** [comment]
I don't think it's worth to mention bugs in README.md, what I should do is release new version. Which I will do hopefully during the weekend. I want to build one model for a user before releasing new one, but I have some deadlines approaching from my salaried work, which I obviously cannot ignore.

The documents explain how to change your output to ```git```, most of our users are using git output instead of file output, to get version history, instead of only 1 latest config.

**Comment by realnakrul** [comment]
Dear ytti
Thank you for reply. There was misunderstanding from my side :) You mean switch OUTPUT to git, but I though that I needed to install Oxidized from github (git pull and etc. instead of gem install oxidized). With git output it works fine.
