### ISSUE TITLE
Constant updates when using Alcatel SR 7750 (Timos)

### ISSUE THREAD

**Issue by andershson** [ytti/oxidized#569]
When doing command:

```
admin display-config index
```

The router generates a date:

```
# TiMOS-C-13.0.R3 cpm/hops64 ALCATEL SR 7750 Copyright (c) 2000-2015 Alcatel-Lucent.
# All rights reserved. All use subject to applicable license agreements.
# Built on Wed May 20 16:02:43 PDT 2015 by builder in /rel13.0/b1/R3/panos/main

# Generated SAT AUG 20 13:35:56 2016 UTC
    system
        thresholds
        exit
    exit
...
exit all

# Finished SAT AUG 20 13:35:56 2016 UTC

```

This storing this in git will generate a new version every time..
Even if there is not configuration change.

**Comment by ytti** [comment]
I'm happy to accept pull request for the model to filter out/replace the timestamp.

**Comment by pozar** [comment]
Any update on this?  Running into this problem too.  I am tempted to write a regex that looks for '^# Finished .*' and '^# Generated .*' and strips them out.  Would that work for folks?

**Comment by dorkmatt** [comment]
Maybe @ghankins has some thoughts here?

**Comment by ytti** [comment]
@pozar yes that should work, this isn't hard problem,  anyone with access to SROS device can just change the model, verify fix works and send PR. 

I'm happy to do it if no one else will, but I will require access to such device

**Comment by job** [comment]
@ytti i can give you access to a Nokia:

```
A:dcg-3.router.nl.coloclue.net# show version
TiMOS-B-14.0.R4 both/hops Nokia 7750 SR Copyright (c) 2000-2016 Nokia.
```

**Comment by pozar** [comment]
I have updates to the timos.rb file to address this.  Will submit.

**Comment by pozar** [comment]
Hmm..  It seems I don't have a way to push a branch into this repro.  What are the steps?

**Comment by pozar** [comment]
PR is at https://github.com/ytti/oxidized/pull/723

**Comment by ytti** [comment]
Thanks @pozar

**Comment by laf** [comment]
The PR to fix this was merged in so closing this now.
