### ISSUE TITLE
Can't download config from Cisco ASA

### ISSUE THREAD

**Issue by kmanpdx** [ytti/oxidized#570]
Problem: I can't backup ASA configuration
Model is: 5512X
Version: 9.6.1
Error Message: 

```
Sep 20 16:41:02 VAN-SVR-IPAM oxidized[12396]: lib/oxidized/node.rb: Oxidized::SSH failed for sea-asa5512x-fw
Sep 20 16:41:02 VAN-SVR-IPAM oxidized[12396]: lib/oxidized/job.rb: Config fetched for sea-asa5512x-fw at 2016-09-20 23:41:02 UTC
Sep 20 16:41:02 VAN-SVR-IPAM oxidized[12396]: sea-asa5512x-fw status no_connection, retry attempt 3
Sep 20 16:41:02 VAN-SVR-IPAM oxidized[12396]: lib/oxidized/worker.rb: Jobs 0, Want: 1
Sep 20 16:41:02 VAN-SVR-IPAM oxidized[12396]: lib/oxidized/worker.rb: Added sea-asa5512x-fw to the job queue
Sep 20 16:41:02 VAN-SVR-IPAM oxidized[12396]: lib/oxidized/worker.rb: 1 jobs running in parallel
Sep 20 16:41:02 VAN-SVR-IPAM oxidized[12396]: lib/oxidized/job.rb: Starting fetching process for sea-asa5512x-fw at 2016-09-20 23:41:02 UTC
Sep 20 16:41:02 VAN-SVR-IPAM oxidized[12396]: lib/oxidized/input/ssh.rb: Connecting to sea-asa5512x-fw
Sep 20 16:41:02 VAN-SVR-IPAM oxidized[12396]: lib/oxidized/input/ssh.rb: expecting /^\r*([\w.@()-\/]+[#>]\s?)$/ at sea-asa5512x-fw
Sep 20 16:41:03 VAN-SVR-IPAM oxidized[12396]: lib/oxidized/input/cli.rb: Running post_login commands at sea-asa5512x-fw
Sep 20 16:41:03 VAN-SVR-IPAM oxidized[12396]: lib/oxidized/input/cli.rb: Running post_login command: "terminal pager 0", block: nil at sea-asa5512x-fw
Sep 20 16:41:03 VAN-SVR-IPAM oxidized[12396]: lib/oxidized/input/ssh.rb terminal pager 0 @ sea-asa5512x-fw with expect: /^\r*([\w.@()-\/]+[#>]\s?)$/
Sep 20 16:41:03 VAN-SVR-IPAM oxidized[12396]: lib/oxidized/input/ssh.rb: expecting /^\r*([\w.@()-\/]+[#>]\s?)$/ at sea-asa5512x-fw
Sep 20 16:41:03 VAN-SVR-IPAM oxidized[12396]: lib/oxidized/worker.rb: 1 jobs running in parallel
Sep 20 16:41:04 VAN-SVR-IPAM oxidized[12396]: lib/oxidized/model/model.rb Collecting commands' outputs
Sep 20 16:41:04 VAN-SVR-IPAM oxidized[12396]: lib/oxidized/model/model.rb Executing show version
Sep 20 16:41:04 VAN-SVR-IPAM oxidized[12396]: lib/oxidized/input/ssh.rb show version @ sea-asa5512x-fw with expect: /^\r*([\w.@()-\/]+[#>]\s?)$/
Sep 20 16:41:04 VAN-SVR-IPAM oxidized[12396]: lib/oxidized/input/ssh.rb: expecting /^\r*([\w.@()-\/]+[#>]\s?)$/ at sea-asa5512x-fw
Sep 20 16:41:04 VAN-SVR-IPAM oxidized[12396]: lib/oxidized/worker.rb: 1 jobs running in parallel
Sep 20 16:41:23 VAN-SVR-IPAM oxidized[12396]: message repeated 19 times: [ lib/oxidized/worker.rb: 1 jobs running in parallel]
Sep 20 16:41:24 VAN-SVR-IPAM oxidized[12396]: 10.165.0.3 raised Timeout::Error with msg "execution expired"
Sep 20 16:41:24 VAN-SVR-IPAM oxidized[12396]: lib/oxidized/node.rb: Oxidized::SSH failed for sea-asa5512x-fw
Sep 20 16:41:24 VAN-SVR-IPAM oxidized[12396]: lib/oxidized/job.rb: Config fetched for sea-asa5512x-fw at 2016-09-20 23:41:24 UTC
Sep 20 16:41:24 VAN-SVR-IPAM oxidized[12396]: sea-asa5512x-fw status no_connection, retries exhausted, giving up
Sep 20 16:41:24 VAN-SVR-IPAM oxidized[12396]: lib/oxidized/worker.rb: Jobs 0, Want: 1

```

When I ssh manually it looks like this:
Type help or '?' for a list of available commands.
sea-asa5512x-fw1/act/pri> en
Password: ******
sea-asa5512x-fw1/act/pri#

Details: I am not sure I can turn off the 'type help' message - which is a PITA.  Please let me know if you need more information

**Comment by ytti** [comment]
I don't see the model enabling you? Have you set enable on it? It looks like the work stops at 'show version' as if 'show version' does not return prompt.

**Comment by kmanpdx** [comment]
You are correct: I'm not setting enable because on the Cisco IOS routers, they go straight into privilege 15 but the Cisco ASA's do not (can not as Cisco does not allow it).  If I add

vars:
  enable: S3cr3tx

Then the Cisco IOS devices fail.  It seems there's options for adding groups and applying different configurations to the groups.  But I'm not clear how that would be configured from the documentation.  I think I would need something like

groups:
  ciscoasa:
    username: admin
    password: blank
    enable: blank
  ciscoios:
    username: admin
    password: blank

Sorry to open a bug for this, looks like it's human (me) issue.  But I'm not clear how to solve the problem

**Comment by kmanpdx** [comment]
OK nevermind I figured it out.  My config file looks like this:

source:
  default: csv
  csv:
    file: "/home/oxidized/.config/oxidized/router.db"
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
      username: 2
      password: 3
    vars_map:
      enable: 4

Then my router.db like this:

#for ios devices
van-c3650-a1-stk1:ios:netadmin:password

#for asa
van-c3650-a1-stk1:ios:netadmin:password:enable_password

**Comment by ytti** [comment]
Good job, I'm closing the case. Personally I'd disable enable everywhere, I do not see point in it, but of course we'll continue supporting it.
