### ISSUE TITLE
Cannot map username from config

### ISSUE THREAD

**Issue by aplalmeida** [ytti/oxidized#571]
Username in debug logs is not maping from config.

Config:
[config.txt](https://github.com/ytti/oxidized/files/487313/config.txt)

router.db
arista-1:eos

Logs:
oxidized@101-oxidized:/etc/oxidized$ oxidized
I, [2016-09-22T12:56:17.692744 #12485]  INFO -- : Oxidized starting, running as pid 12485
I, [2016-09-22T12:56:17.695423 #12485]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
I, [2016-09-22T12:56:17.782148 #12485]  INFO -- : lib/oxidized/nodes.rb: Loaded 1 nodes
Puma 2.16.0 starting...
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://127.0.0.1:8888
W, [2016-09-22T12:56:20.903981 #12485]  WARN -- : <server-ip> raised Net::SSH::AuthenticationFailed with msg "Authentication failed for user username@<server-ip>"
W, [2016-09-22T12:56:21.296945 #12485]  WARN -- : arista-1 status no_connection, retry attempt 1
W, [2016-09-22T12:56:23.247250 #12485]  WARN -- : <server-ip> raised Net::SSH::AuthenticationFailed with msg "Authentication failed for user username@<server-ip>"
W, [2016-09-22T12:56:23.298159 #12485]  WARN -- : arista-1 status no_connection, retry attempt 2
W, [2016-09-22T12:56:25.231251 #12485]  WARN -- : <server-ip> raised Net::SSH::AuthenticationFailed with msg "Authentication failed for user username@<server-ip>"
W, [2016-09-22T12:56:25.299253 #12485]  WARN -- : arista-1 status no_connection, retry attempt 3
W, [2016-09-22T12:56:27.820539 #12485]  WARN -- : <server-ip> raised Net::SSH::AuthenticationFailed with msg "Authentication failed for user username@<server-ip>"
W, [2016-09-22T12:56:28.300748 #12485]  WARN -- : arista-1 status no_connection, retries exhausted, giving up

**Comment by danilopopeye** [comment]
The 'vars' config should be the index from the 'router.db' not the values themselves.

**Comment by aplalmeida** [comment]
Ok, Thankyou.
With your comment I could see I had two problems.
1 - I make export "OXIDIZED_HOME="/etc/oxidized", but is not working well
2 - About vars.
