### ISSUE TITLE
<host> raised Oxidized::PromptUndetect with msg " Password: not matching configured prompt (?-mix:^([\w\s.@-]+[#>]\s?)$)"

### ISSUE THREAD

**Issue by Alwaysin** [ytti/oxidized#573]
Hello!

With a Powerconnect, I got:

```
<host> raised Oxidized::PromptUndetect with msg "
Password: not matching configured prompt (?-mix:^([\w\s.@-]+[#>]\s?)$)"
<host> raised Errno::ECONNRESET with msg "Connection reset by peer"
```

Is it maybe because the password has a "!" inside? I think about that because on my switch I get:

```
26-Sep-2016 17:15:54 %AAA-W-REJECT: New ssh connection for user line ssh, source <oxidized_ip> destination <switch_ip>  REJECTED
```

```
$ cat config 

---
username: username
password: password
model: dell
interval: 600
log: "/home/oxidized/.config/oxidized/log/oxidized.log"
use_syslog: false
debug: false
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 127.0.0.1:8888
vars: {}
groups: {}
pid: "/home/oxidized/.config/oxidized/pid"
input:
  default: ssh, telnet
  debug: false
  ssh:
    secure: false
output:
  default: git
  file:
    directory: "/home/oxidized/.config/oxidized/deviceconfigs"
  git:
    user: demma
    email: demma@systran.fr
    repo: "/home/oxidized/.config/oxidized/oxidized.git"
source:
  default: csv
  csv:
    file: /home/oxidized/.config/oxidized/switch.db
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
      username: 2
      password: 3
    vars_map:
      enable: 4
model_map:
  cisco: ios
  juniper: junos
  dell: powerconnect
  force10: ftos
```

```
$ cat switch.db 
switch1:dell:admin:pass!word

```

```
# ssh switch1

Password:********

switch1> 

```

**Comment by ytti** [comment]
Maybe add:
```
input:
  debug: true
```

And/or tshark/tcpdump. It indeed looks like you may enter the password, and then reobserve the password prompt.
Tshark/tcpdump would prove what you're actually sending.

**Comment by Alwaysin** [comment]
Thanks, with debug: true I could see that it was expecting a username prompt, which I don't have (only asking for password). So I've commented this : ```#expect username``` in /usr/local/rvm/gems/ruby-2.1.2/gems/oxidized-0.16.3/lib/oxidized/input/ssh.rb, but ithe problem is that I have other equipments requiring usernames.

**Comment by ytti** [comment]
You could copy the model to ~/.config/oxidized/model

rename the class and filename, and remove the 'username' stanza from the model.

map that device to the new model, and you should have model which does not expect username

**Comment by laf** [comment]
@Alwaysin Have you managed to resolve this from the info ytti has given you?

**Comment by Alwaysin** [comment]
Sorry I won't be able to comment this anymore, the use case is gone :(

**Comment by laf** [comment]
If anyone else experiences this, feel free to reply here and we can re-open.

@Alwaysin Thanks for replying.
