### ISSUE TITLE
Issue with Remote Repo

### ISSUE THREAD

**Issue by lobo5519** [ytti/oxidized#575]
running into an issue outputting to a remote gitlab server. 

(#<Rugged::SshError: error authenticating: no auth sock variable>) 

I have confirmed the SSH key is working. 

Config:

output:
  default: git
  git:
    user: removed
    email: Removed
    repo: git@gitlab.doamin.com:Configs/Device-Configs.git
hooks:
  push_to_remote:
    type: githubrepo
    events: [post_store]
    remote_repo: git@gitlab.domain.com:Configs/Device-Configs.git

Is there a mis-configuration?

**Comment by lobo5519** [comment]
I was able to get it working by specifying the private and public key

**Comment by ytti** [comment]
Thanks for the update, closing.
