### ISSUE TITLE
oxidized.service issue

### ISSUE THREAD

**Issue by lobo5519** [ytti/oxidized#576]
I had to add WorkingDirectory=/home/oxidized to get this working. Without it I was getting 

"Failed to resolve path ' git@gitlab.domain.com:stuff/Network-Device-Configs.git"

Not sure if I am doing something wrong here...

**Comment by ytti** [comment]
Is this related to github hook? I assume from gitlab, yes.

**Comment by lobo5519** [comment]
Yes

**Comment by ytti** [comment]
Do you have full backtrace of the crash.

**Comment by lobo5519** [comment]
Crash file:


--------------------------------------------------
2016-09-28 18:28:16 UTC
first 'Failed to resolve path '/git@gitlab.domain.com:stuff/Network-Device-Configs.git': No such file or directory' was raised while opening git repo, then 'Failed to make directory '/git@gitlab.domain.com:stuff': Permission denied' was while trying to create git repo [Oxidized::Git::GitError]
--------------------------------------------------
/var/lib/gems/2.3.0/gems/oxidized-0.16.3/lib/oxidized/output/git.rb:176:in `rescue in rescue in update'
/var/lib/gems/2.3.0/gems/oxidized-0.16.3/lib/oxidized/output/git.rb:173:in `rescue in update'
/var/lib/gems/2.3.0/gems/oxidized-0.16.3/lib/oxidized/output/git.rb:169:in `update'
/var/lib/gems/2.3.0/gems/oxidized-0.16.3/lib/oxidized/output/git.rb:57:in `store'
/var/lib/gems/2.3.0/gems/oxidized-0.16.3/lib/oxidized/worker.rb:47:in `process'
/var/lib/gems/2.3.0/gems/oxidized-0.16.3/lib/oxidized/worker.rb:14:in `block in work'
/var/lib/gems/2.3.0/gems/oxidized-0.16.3/lib/oxidized/worker.rb:14:in `each'
/var/lib/gems/2.3.0/gems/oxidized-0.16.3/lib/oxidized/worker.rb:14:in `work'
/var/lib/gems/2.3.0/gems/oxidized-0.16.3/lib/oxidized/core.rb:36:in `run'
/var/lib/gems/2.3.0/gems/oxidized-0.16.3/lib/oxidized/core.rb:28:in `initialize'
/var/lib/gems/2.3.0/gems/oxidized-0.16.3/lib/oxidized/core.rb:4:in `new'
/var/lib/gems/2.3.0/gems/oxidized-0.16.3/lib/oxidized/core.rb:4:in `new'
/var/lib/gems/2.3.0/gems/oxidized-0.16.3/lib/oxidized/cli.rb:12:in `run'
/var/lib/gems/2.3.0/gems/oxidized-0.16.3/bin/oxidized:9:in `<top (required)>'
/usr/local/bin/oxidized:23:in `load'
/usr/local/bin/oxidized:23:in `<main>'
--------------------------------------------------

**Comment by danilopopeye** [comment]
@lobo5519 could you post your config? seems that the repository path or remote is misconfigured.

**Comment by laf** [comment]
@lobo5519 Any further update on this?
