### ISSUE TITLE
How does oxidized know when a node is down ?

### ISSUE THREAD

**Issue by Nyanyah** [ytti/oxidized#579]
Hello,

I don't fully understand how oxidized works. How does it know when a node is down / a configuration has changed ? Is it fetching for configurations non-stop ?

Thanks and sorry for my lack of knowledge on this.

**Comment by ytti** [comment]
Oxidized tries to fetch config from each node every interval (interval parameter in config). After it has fetched the config, it'll store it to file or git, git will know if actual change occurred or not. 

There is also possibility to manually ask oxidized to fetch config from specific moment. So it is possible for example to monitor syslog messages from routers, when they inform about config change, ask oxidized to fetch the config immediately and store customer committer name (user name from syslog, for example) and commit message (commit message from syslog, for example).

**Comment by Nyanyah** [comment]
Oh I see, didn't see this interval setting. Thanks lots.
