### ISSUE TITLE
Allow push to remote

### ISSUE THREAD

**Issue by kevin-fibich** [ytti/oxidized#58]
Since rugged/libgit2 ignores hooks, an option would be nice to let oxidized automatically push new commits to a configurable remote.

**Comment by SaaldjorMike** [comment]
I'm coming from a rancid-git installation with a hook to push the configs to a remote repository, so this would be awesome to see. :+1:

**Comment by ytti** [comment]
I think correct solution to this issue should be #60, instead of specific support for remote push.

So you'd have hook which is called before/after output/store, and you'd then do what ever you want in the hook. We could provide in example directory hook to fork 'git push'.

**Comment by ytti** [comment]
Closed as duplicate of #60
