### ISSUE TITLE
F5 Full Backup

### ISSUE THREAD

**Issue by clay584** [ytti/oxidized#582]
The current tmos.rb module is backing up the base LTM configurations and some other important items, but depending on the modules that are actively running in Big-IP, you may be missing some of the configurations.

For example, the current tmos.rb does not backup private keys, certificates, etc.  Also, if you are running other modules like ASM, some data is stored in a local SQL database which would not be captured with oxidized.

The only true way to get a backup of an F5 that you can do a full restore from, is to perform a UCS archive and then transport that gzip file off of the box.

Perhaps you can still scrape all of the data that you are already scraping, but also perform a UCS archive and copy it down via SCP/SFTP into the oxidized repo.  Not sure how git will handle a binary file, maybe git LFS could be used or simply do a .gitignore on the gzip files and add a process in oxidixed to keep a rolling buffer of X number of backup files (configurable).

Also, there is a consideration of old UCS archive cleanup on the F5 device in which these backups are taken.  Maybe after copying off-box, then go back and delete the UCS file on the F5 device as well.

A consideration is that you are now putting private keys on the oxidized server, so encrypting the file is a must and can be done with a command flag on the F5 device.

the command to perform a UCS archive and encrypt it is as follows:

tmsh -q save sys ucs hostname-ucs-10-04-2016-05_40_32.ucs passphrase supersecretpassword

The files are stored in /var/local/ucs on the F5.

Here is an example of fulling backing up multiple F5 devices using bash.  I have this running on about 40-ish devices currently and works great.  Would be nice to integrate into oxidized.

https://github.com/clay584/misc_net_scripts/tree/master/f5/f5_backup

**Comment by fitzplb** [comment]
@clay584 I was just looking at whether I could do this but it doesn't seem like it's possible with the existing model framework to run commands outside of the device (i.e. to scp the file over to the oxidized server). Did you get anywhere with it?
