### ISSUE TITLE
Unable to install gems for the application

### ISSUE THREAD

**Issue by lakshveer** [ytti/oxidized#584]
```
no implicit conversion of Symbol into Integer. Bundler cannot continue.
```

**Comment by ytti** [comment]
What exactly are you doing to install it? 'gem install oxidized'?

**Comment by lakshveer** [comment]
My gem file include following:
This is the gem file im using.I don't want to make any changes in this one.These gems are the dependencies for my application.
source 'https://rubygems.org'

# Required for CocoaPods 0.39.0
ruby '>= 2.0.0', '<= 2.2.4'

gem 'activesupport', '4.2.5'
gem 'cocoapods', '0.39.0'
gem 'xcpretty', '0.2.2'
gem 'plist', '3.2.0'
gem 'calabash-cucumber', '0.17.1'
gem 'run_loop', '2.0.3'

**Comment by lakshveer** [comment]
The ruby dependencies are being managed through gemfile.For that we are using a bundler.

**Comment by laf** [comment]
@lakshveer Any feedback on this or can the issue be closed?

**Comment by laf** [comment]
@lakshveer If you need help still, please reply to this and we will re-open the issue.
