### ISSUE TITLE
some devices have trouble with SSH input sending "\n" instead of "\r"

### ISSUE THREAD

**Issue by rfdrake** [ytti/oxidized#598]
This only affects Net::SSH.  Net::Telnet adds the newline and detects the correct one to send based on the telnet negotiation.

I thought I had found a workaround by hardcoding the "\r" in the command.  For example:

```
cmd "show sfp *\r" do |cfg|
```

The problem seems to be that the parser doesn't know what to do with the errant newlines so it leaves the commands in the output file.  Sometimes with the prompt on the preceding line:

```
# show sfp *
#
# No Instances.
#
# hostname#
show config run
```

I'm not sure what would be the best way to fix this.   If we could specify the encoding in the model class then the backend code could filter things appropriately, but I'm not good with Ruby and I'm lost.

It's also entirely possible I'm barking up the wrong tree.  I know the first part of my problem was caused by the newlines and it was hard to track down, but it may be that I'm now facing other issues.

**Comment by ytti** [comment]
If far end needs \r, I'd say it's by-design that you need to add them, but you make fair point with telnet.
I'd need to see your model to comment on errant newlines, I suspect you're using ```send``` when you should use ```cmd```.
