### ISSUE TITLE
SSH Proxy - DNS Resolution

### ISSUE THREAD

**Issue by nbarry101** [ytti/oxidized#599]
Hi,

I've been looking at connecting to multiple sites via SSH proxys, rather than having an oxidized VM at each site.

The initial testing looks great, but i've noticed that DNS resolution of switches happens before connecting to the SSH proxy, rather than after, meaning that the oxidized server must be able to resolve the switch, rather than relying on the SSH proxy to do the resolution.

Is this something we can look at changing?

Thanks!
Nic

**Comment by ytti** [comment]
We could dd option if connection should be by IP or name.

**Comment by nbarry101** [comment]
Hi ytti, connection via name currently works if I put the target internal name in the oxidized server hosts file. Is there anyway we can have oxidized use the ssh proxys dns server to lookup the name? Cheers

**Comment by ytti** [comment]
No, not currently, we could change so that we use name not IP.

**Comment by nbarry101** [comment]
Sure thing, thanks for hearing the suggestion :)

**Comment by nbarry101** [comment]
Hi ytti,

Sorry to be pushy, but was wondering whether you've had a chance to look into this? :)
It'd make the SSH proxy just that bit more usable :)

Cheers
Nic

**Comment by ytti** [comment]
Can you try this:
https://github.com/ytti/oxidized/commit/e2899b55638101ddf97aeab919a9f064daf05451

**Comment by laf** [comment]
@nbarry101 have you tried the patch that ytti has provided?

**Comment by nbarry101** [comment]
@laf apologies, I feel bad for pushing @ytti to look into this, as shortly after he did I moved out of that role, and haven't had a chance to attempt the update.
Hopefully someone else finds it useful!
As a workaround I have put the switch names in the hosts file.

**Comment by laf** [comment]
No worries :) As it's recorded here then maybe it's worth closing for now as people can search and find this if they experience similar issues @nbarry101
