### ISSUE TITLE
Add support for Ubiquiti Unifi configurations

### ISSUE THREAD

**Issue by jquagga** [ytti/oxidized#603]
Good day,

I've worked out a shell of model.rb to pull configurations from my UBNT Unifi Access Points.  I believe this will also pull configs from their switches / routers (but I have none to test).  These devices are traditionally managed with controller software, but I think it's helpful to have the ability to pull and git diff whatever changes happened between updates.  This just pulls the running config from the device directly with ssh.  However if this shouldn't be included, I understand.  

I believe this needs some help configuring the secret settings.  My ruby skills are not sharp enough.  I've attached a copy of the running.cfg from one of my APs and there are few lines which I think should be hidden if secret is enabled.  users.#.passwords, aaa.#.psk, snmp.community should probably be hidden.  

Here is the unifi.rb I'm presently using.  

```ruby
  class Unifi < Oxidized::Model

# Unifi #

  prompt /^[^#]+# /

  cmd :all do |cfg|
    cfg = cfg.lines.to_a[1..-2].join
  end

  cmd 'cat /tmp/running.cfg'

  cfg :telnet do
    username  /login:\s/
    password  /^Password:\s/
  end

  cfg :telnet, :ssh do
    pre_logout 'exit'
  end

end
```

And here is the cfg file.  [running.cfg.txt](https://github.com/ytti/oxidized/files/567484/running.cfg.txt)

**Comment by ytti** [comment]
And this is different to https://github.com/ytti/oxidized/blob/master/lib/oxidized/model/airos.rb

**Comment by jquagga** [comment]
Ah, I'm sorry.  That airos.rb actually works better.  Unifi is a different product line from the AirOS stuff so it didn't occur to me that setting to AirOS would pull the UAP configs.  I just knew I needed different settings than the EdgeSwitch/OS stuff.  I shall close this - Thank you!
