### ISSUE TITLE
Passing enable password when not needed

### ISSUE THREAD

**Issue by mkesler80** [ytti/oxidized#604]
I just noticed in one of my device updates the enable password was passed when the device was already in privileged exec
Cisco IOS 15.3(3)M6

 ! Translating <enable_pass>...domain server (172.16.1.9)

This was just before show version was run so it's the first line of the backup now.  I just set up oxidized so I'm not sure what else you might need from me to verify this.

**Comment by ytti** [comment]
Remove enable password for that node? For example make it ```false```or ```nil```

**Comment by mkesler80** [comment]
That's a good point.  I currently have the enable pass in the config file.  Only a few devices need enable so I can make that change.  Is there a way to specify the enable password per device with CSV input without specifying the username and password?

**Comment by ytti** [comment]
I don't really understand your question, can you try to explain the practical problem you're trying to solve.

**Comment by mkesler80** [comment]
In my config file I've specified service account credentials that are used to ssh to each device along with an enable password.
I have a router.db file with hosts entered in this format
<host>:<model>
As I understand it the normal format for these entries is <host>:<model>:<user>:<password>:<enable_pass>
If I wanted to continue to use the service account credentials in the config file and specify the enable password in the router.db file what would the host entries look like?
I don't think <host>:<model>:<enable_pass> would work would it?

**Comment by ytti** [comment]
Empty field will mean "" string. You probably want ```nil``` or ```false```

You will also need latest version, 0.18.0.

**Comment by mkesler80** [comment]
So I could use
host:model:nil:nil:enable_pass
and that would continue to use the ssh credentials I have set in my config file?

**Comment by ytti** [comment]
Yeah it should fall back to global config.

**Comment by laf** [comment]
@mkesler80 Was your issue resolved?
