### ISSUE TITLE
api to rename nodes

### ISSUE THREAD

**Issue by rfdrake** [ytti/oxidized#609]
Forgive me if this is already covered in the API.

I think it would be nice to have a REST way to do a node rename, so that the node history doesn't disappear with the name change.

On the backend this would just do a "git mv oldfile newfile"/git commit.  Internally it would need to rename it in the ring buffer as well, at least until the source file is reloaded, then it would be up to the source to make sure the name was correct.

**Comment by ytti** [comment]
Seems useful suggestion, not something I'm gonna work in foreseeable future but would consider accepting PR.

I really want ring buffer mostly gone and stats away from memory into SQL on-disk database, this would create persistent stats over reloads, and oxidized memory use would not scale as function of nodes but more reasonably as function of threads.
From core point of view, it's rather big change, but on the other hand, core is quite small part of oxidized so it wouldn't be that much work. 
It would also make this more trivial, as we don't have to worry about run-time-rename, just rename it  in SQL and let it be right on next-attempt.
In this context, it seems duplicate work to try to implement this feature, before moving state from memory to disk, which makes me uninterested in implementing it.
