### ISSUE TITLE
Error for incorrect .git permissions is quite opaque

### ISSUE THREAD

**Issue by will-h** [ytti/oxidized#61]
If the .git repo is not writeable, the error seems to be:

== Sinatra/1.4.5 has taken the stage on 8888 for development with backup from Puma
wrong argument type Rugged::Repository (expected String)
== Sinatra has ended his set (crowd applauds)
/var/lib/gems/1.9.1/gems/oxidized-0.2.3/lib/oxidized/output/git.rb:36:in `init_at': wrong argument type Rugged::Repository (expected String) (TypeError)

Not very obvious!

**Comment by ytti** [comment]
Agreed. Do you have crashfile for this, so we can see the call stack.

Which rugged version are you running (gem list|grep rugged).

**Comment by ytti** [comment]
I get this error on debug:

    Failed to make directory '/home/ytti/.config/oxidized/oxidized.git/objects': Permission denied
    /var/lib/gems/2.1.0/gems/oxidized-0.3.0/lib/oxidized/output/git.rb:75:in `init_at': Failed to make     directory '/home/ytti/.config/oxidized/oxidized.git/objects': Permission denied (Rugged::OSError)

Without debug:
    Failed to make directory '/home/ytti/.config/oxidized/oxidized.git/objects': Permission denied

Which I think is good enough. 
    [ytti@ytti.fi ~/.config/oxidized]% gem list|grep -i rugged
    rugged (0.21.0)

I tested by doing
'sudo chown root oxidized.git'

Can you repro your bad warning message on 0.21.0, if so, how?

**Comment by will-h** [comment]
Debugging some more. I've found if the repo _already exists_ but is owned by another user it fails with this error. I did this by backupping my current directory; chown -R will * on the respository.

rugged (0.21.2) here.

--------------------------------------------------
2015-02-22 10:40:42 UTC
wrong argument type Rugged::Repository (expected String) [TypeError]
--------------------------------------------------
/var/lib/gems/1.9.1/gems/oxidized-0.2.3/lib/oxidized/output/git.rb:36:in `init_at'
/var/lib/gems/1.9.1/gems/oxidized-0.2.3/lib/oxidized/output/git.rb:36:in `rescue in store'
/var/lib/gems/1.9.1/gems/oxidized-0.2.3/lib/oxidized/output/git.rb:32:in `store'
/var/lib/gems/1.9.1/gems/oxidized-0.2.3/lib/oxidized/worker.rb:37:in `process'
/var/lib/gems/1.9.1/gems/oxidized-0.2.3/lib/oxidized/worker.rb:13:in `block in work'
/var/lib/gems/1.9.1/gems/oxidized-0.2.3/lib/oxidized/worker.rb:13:in `each'
/var/lib/gems/1.9.1/gems/oxidized-0.2.3/lib/oxidized/worker.rb:13:in `work'
/var/lib/gems/1.9.1/gems/oxidized-0.2.3/lib/oxidized/core.rb:36:in `run'
/var/lib/gems/1.9.1/gems/oxidized-0.2.3/lib/oxidized/core.rb:29:in `initialize'
/var/lib/gems/1.9.1/gems/oxidized-0.2.3/lib/oxidized/core.rb:11:in `new'
/var/lib/gems/1.9.1/gems/oxidized-0.2.3/lib/oxidized/core.rb:11:in `new'
/var/lib/gems/1.9.1/gems/oxidized-0.2.3/lib/oxidized/cli.rb:9:in `run'
/var/lib/gems/1.9.1/gems/oxidized-0.2.3/bin/oxidized:9:in `<top (required)>'
/usr/local/bin/oxidized:23:in `load'
/usr/local/bin/oxidized:23:in `<main>'
--------------------------------------------------

**Comment by ytti** [comment]
In my test

 1) having repo owned by another user => reasonable error message
 2) having write to repo AND read to repo/config but NOT to other files => unreasonable error message

After change:


````
[ytti@ytti.fi ~/.config/oxidized]% sudo chown root oxidized.git 
[ytti@ytti.fi ~/.config/oxidized]% oxidized 
first 'Could not find repository from '/home/ytti/.config/oxidized/oxidized.git'' was raised while opening git repo, then 'Failed to make directory '/home/ytti/.config/oxidized/oxidized.git/objects': Permission denied' was while trying to create git repo
[ytti@ytti.fi ~/.config/oxidized]% sudo chown ytti oxidized.git 
[ytti@ytti.fi ~/.config/oxidized]% cd oxidized.git 
[ytti@ytti.fi ~/.config/oxidized/oxidized.git]% sudo chown root *
[ytti@ytti.fi ~/.config/oxidized/oxidized.git]% oxidized 
first 'Could not open '/home/ytti/.config/oxidized/oxidized.git/config': Permission denied' was raised while opening git repo, then 'Could not open '/home/ytti/.config/oxidized/oxidized.git/config': Permission denied' was while trying to create git repo
[ytti@ytti.fi ~/.config/oxidized/oxidized.git]% sudo chown ytti config
[ytti@ytti.fi ~/.config/oxidized/oxidized.git]% oxidized              
first 'Failed to create temporary file '/home/ytti/.config/oxidized/oxidized.git/objects/tmp_object_git2_Jwk9Fu': Permission denied' was raised while opening git repo, then 'wrong argument type Rugged::Repository (expected String)' was while trying to create git repo
[ytti@ytti.fi ~/.config/oxidized/oxidized.git]% 
````
