### ISSUE TITLE
HP Comware xtd-cli-mode Password

### ISSUE THREAD

**Issue by adamboutcher** [ytti/oxidized#611]
Hi,

As all the commands required for Oxidized to work are being some stupid password wall xtd_cli_mode, the HP Comware 1950 doesn't get its configuration backed up.

Some kind soul on Reddit has found the password [here](https://www.reddit.com/r/networking/comments/3phmat/hp_195048gpoe/cy3eywi/) (foes-bent-pile-atom-ship), I was wondering if you guys could add support?

Thanks

**Comment by ytti** [comment]
It looks like the password maybe changing per firmware?

**Comment by adamboutcher** [comment]
This model of switch HP Comware 1950 has always had a different password
although it looks like it's changeable per firmware, could we have this as
a variable?

Thanks

**Comment by ytti** [comment]
We could have hash mapping firmware to password. Then query for version, and set password from hash based on returned version. 

But I don' really understand the problem even, I don't have these devices. Maybe @sid3windr @erJasp @amarti2038 or @nickhilliard can chime in.

**Comment by adamboutcher** [comment]
There's a section for the 1910/1920 I believe but the command it initially sends is incorrect for the later models...

**Comment by adamboutcher** [comment]
The line
https://github.com/ytti/oxidized/blob/master/lib/oxidized/model/comware.rb#L32

is incorrect for this model switch, it should be

> send "xtd-cli-mode\n"

**Comment by ytti** [comment]
@sid3windr comments about the cli-mode command?

**Comment by adamboutcher** [comment]
I know it's been a while but do we have any news/update on this issue?

**Comment by laf** [comment]
@adamboutcher Can we send both commands to catch the different models or will that cause issues?

**Comment by adamboutcher** [comment]
If you send _cmdline-mode on to my model which uses xtd-cli-mode just ends up saying "% Unrecognised command found at '^' potision.", so you could check for that and then provide the correct command.

**Comment by adamboutcher** [comment]
I can't test how the models that don't support the xtd-cli-mode command would act but I cant see why not.

**Comment by laf** [comment]
Try it for you, add the command to the model (see https://github.com/ytti/oxidized/blob/master/docs/Creating-Models.md on how to do it in your own install). See if it works and then feel free to submit as a pull request. I'm not sure it's the way the project would want it to be done but let's see.

**Comment by semplonius6** [comment]
i made the hp1950 work by making a copy of the comware model to : /var/lib/gems/2.3.0/gems/oxidized-0.21.0/lib/oxidized/model/comware1950.rb

changeing the lines:
username /^login: $/
password /^Password: $/

and:
 cfg :telnet, :ssh do
    # enable command-line mode on SMB comware switches (HP V1910, V1920)
    # autodetection is hard, because the 'summary' command is paged, and
    # the pager cannot be disabled before _cmdline-mode on.
    if vars :comware_cmdline
      post_login do
        #send "_cmdline-mode on\n"
        #send "y\n"
        #send vars(:comware_cmdline) + "\n"
        send "xtd-cli-mode\n"
        send "y\n"
        send vars(:comware_cmdline) + "\n"
      end
    end

**Comment by adamboutcher** [comment]
@semplonius6 Thanks for the help, I'm not a ruby dev so wasn't sure where/how to edit the files.
I've pushed a change to the comware file which works for my newer model Comwares:
- OfficeConnect 1950-48G-2SFP+-2XGT
- 5700-32XGT-8XG-2QSFP+ Switch

**Comment by adamboutcher** [comment]
PR #1305

**Comment by wk** [comment]
Closed by #1305
