### ISSUE TITLE
Dell PowerConnect - Differences in output, causing many commits 

### ISSUE THREAD

**Issue by nbarry101** [ytti/oxidized#615]
Hi,

I've recently noticed an issue with some minor differences in output after implementing a SSH proxy.

Basically it appears that sometimes show version is outputted, and sometimes it is not.

![screen shot 2016-11-11 at 10 20 29 am](https://cloud.githubusercontent.com/assets/5484303/20198520/39eaa5ac-a7f9-11e6-9c2a-a9dfd392dc32.png)

![screen shot 2016-11-11 at 10 20 43 am](https://cloud.githubusercontent.com/assets/5484303/20198523/3dd97846-a7f9-11e6-8ccb-6f1c52327d3f.png)

Is there anything I can tweak to fix this?

Cheers,
Nic

**Comment by ytti** [comment]
This https://github.com/ytti/oxidized/commit/689d4dba60de7a1faf555011f9db6fb3aef2fbea may fix your problem.

**Comment by nbarry101** [comment]
Thanks - i'll let you know whether this helps.

**Comment by nbarry101** [comment]
Sorry for the delay in confirming this, but the issue is now resolved! Thanks.
