### ISSUE TITLE
oxidized process is not being terminated after last config it's being updated.

### ISSUE THREAD

**Issue by claudiugc** [ytti/oxidized#617]
I issue command oxidized or oxidized -d and it remains at:     Listening on tcp://10.10.1.98:8000

```
[oxidized@oxidized root]$ oxidized -d
Puma 2.16.0 starting...
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://10.10.1.98:8000
ctrl-c
^C[oxidized@oxidized root]$
````
log says: 
```
D, [2016-11-18T12:59:14.087836 #4295] DEBUG -- : lib/oxidized/job.rb: Config fetched for 10.10.27.102 at 2016-11-18 20:59:14 UTC
I, [2016-11-18T12:59:14.474074 #4295]  INFO -- : Configuration updated for dell/10.10.27.102
D, [2016-11-18T12:59:14.474183 #4295] DEBUG -- : lib/oxidized/worker.rb: Jobs 0, Want: 1
````
if i don't terminate the process with ctrl-c it will fill up the log with the last line of the log at 1 second intervals.

routerdb file:

10.10.1.210:nxos:cisco
10.10.1.216:nxos:cisco
10.10.1.217:nxos:cisco
10.10.1.218:nxos:cisco
10.10.1.219:nxos:cisco
10.10.1.221:nxos:cisco
10.10.1.240:ios:cisco
10.10.1.102:powerconnect:dell
10.10.1.103:powerconnect:dell
10.10.1.104:powerconnect:dell
10.10.1.105:powerconnect:dell
10.10.1.107:powerconnect:dell
10.10.1.108:powerconnect:dell
10.10.1.109:powerconnect:dell
10.10.1.111:powerconnect:dell
10.10.1.112:powerconnect:dell
10.10.1.131:powerconnect:dell
10.10.1.132:powerconnect:dell
10.10.1.133:powerconnect:dell
10.10.1.134:powerconnect:dell
10.10.27.102:powerconnect:dell

config file:

```
---
interval: 3600
log: "/home/oxidized/.config/oxidized/logs/oxidized.log"
debug: false
threads: 30
timeout: 10
retries: 1
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
groups:
  cisco:
    username: admin
    password: redacted
    vars:
      enable: same
  dell:
    username: admin
    password: same
    vars:
      enable: same
  oldcisco:
    username: admin
    password: same
    vars:
      enable: same
rest: 10.10.1.98:8000/oxidized
pid: "/home/oxidized/.config/oxidized/oxidized.pid"
input:
  default: ssh ,telnet
  debug: false
  ssh:
    secure: false
output:
  default: file
  file:
    directory: "/home/oxidized/.config/oxidized/configs"
source:
  default: csv
  csv:
    file: ~/.config/oxidized/router.db
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
      group: 2
    vars_map:
      enable: 3
model_map:
  cisco: nxos
  dell: powerconnect
  oldcisco: ios
```

Please advice,
Thank you.

**Comment by ytti** [comment]
To me it looks like normal behaviour. Oxidized is a daemon and it'll run forever.

**Comment by claudiugc** [comment]
That's all i wanted to know regarding the process,  the interval in the config tells it when to run again?

**Comment by ytti** [comment]
The interval tells how often to fetch config for particular device, i.e. how old should configuration backup config be at most.

**Comment by laf** [comment]
@ytti Looks like this can be closed, questions have been answered
