### ISSUE TITLE
remove_secret doesn't remove all password on Cisco ios

### ISSUE THREAD

**Issue by jfjallid** [ytti/oxidized#620]
the option remove_secret: true
does not remove all encrypted passwords on Cisco ios devices from the configuration which could be deemed sensitive such as the configuration row:
"enable secret 5 $1$Ac8t$jaszMu.tsfEsdd3qa/KwBN/"

**Comment by ytti** [comment]
Feel free to submit PR.

**Comment by ytti** [comment]
Can you explain why ```cfg.gsub! /^enable secret \d \S+/, '<secret hidden>'``` wouldn't match on that?
