### ISSUE TITLE
Oxidized doesnt always grab whole config

### ISSUE THREAD

**Issue by air101** [ytti/oxidized#621]
Hello Oxidized Supporters,

I've wrote my own Model for Woltec Routers. You ssh into the router and enter "show running-config". It displays one site and then you have to press space key to get the next config page. It works quite well but
sometimes it doesnt grab all the config and therefor creating a new version of the config file. It seems that it hangs at "--More--". Is there any way to validate the config file? Each config file has "#end of configuration" at the end of the grabbing.

Thank you and best Regards!

**Comment by ytti** [comment]
The obvious guess is that your model is incorrect. You didn't post it, so I can't review it, but even if I could, I couldn't guarantee that review will find the problem. 

On common mistake is to use ```send vars(:enable) + "\n"``` this will cause problems, as we don't consume the following prompt. That should instead be ```cmd vars(:enable)```

**Comment by air101** [comment]
Thats my current Model for the Router:

class WelotecTK800 < Oxidized::Model

  # WelotecTK800 model #
  # Only SSH supported for the sake of security

   prompt /\d\d:\d\d:\d\d (\w+#)/
   comment '# '

  expect /^((.*)--More--(.*))$/ do |data, re|
    send ' '
    data.sub re, ''
end

  cmd :all do |cfg|
cfg.each_line.to_a[1..-2].join
  cfg
end

  cmd 'show running-config' do |cfg|
  cfg.gsub!(/show running-config/, '')
  cfg.gsub!(/\d\d:\d\d:\d\d (\w+#)/, '')
  cfg.gsub! /^: [^\n]*\n/, ''
  cfg
  end

  cfg :ssh do
  pre_logout do
   expect /#end of configuration/
   send "exit\n"
   expect /Are you sure to Exit current mode\/console\?\[Y\|N\]/
   send "y\n"
   end
  end
end

**Comment by ytti** [comment]
I can't immediately tell what's wrong there. Could you produce sanitised device online, so that it's reachable from 91.198.120.1 and send authentication details to saku@ytti.fi

**Comment by air101** [comment]
I'll see what I can do :)
