### ISSUE TITLE
Decentralization needs

### ISSUE THREAD

**Issue by uZer** [ytti/oxidized#622]
Hey there,

Thanks for this great tool! I'm using oxidized in a large network with high latency constraints (about 500 ms to reach some nodes). The parsing of a full equipment configuration can take more that 20 minutes (saw that on rancid), so I'd like to scale my oxidized installation on 5 instances around the world to minimize the latency. Not a big deal yet thanks to ansible. I am using git hook to push everything to a remote gitlab instance and this is where my question is:

Is there a way to use only one git repository to store all devices config I would get on 5 oxidized instances?
Each instance would only connect to local equipment, but the hook would push them in the same repository as the other oxidized instances. I guess this requires the hook to `git pull` before `git push`.

Thanks by advance for your help.

**Comment by ytti** [comment]
The latency itself shouldn't really hurt Oxidized, so unless you specifically want to have many installations, I don't think you need them.

As long as the instances are not fetching same nodes, and you can do fast-forward in git, I think you can safely push from all of the instances to same master repo.

**Comment by uZer** [comment]
Thanks for your answer, I'll try this next week and keep you posted.

**Comment by uZer** [comment]
You were right, decentralization on a single remote works perfectly 👍 
```
Oxidized pushed to branch master of uZer/oxidized_infra (Compare changes)
a0a3472d: update xxxxxxxxx - Oxidized
f2fe80db: Merge remote-tracking branch 'origin/master' - Oxidized 
```

Thanks for your support
