### ISSUE TITLE
Wrong paths on web interface

### ISSUE THREAD

**Issue by paulocoimbrati** [ytti/oxidized#626]
Oxidized is configured to writing out the backup files:
_output:
  default: file
  file:
    directory: "/root/.config/oxidized/configs/backup"_

Files are not saved at "backup", but at configs : 
_ls -lah /root/.config/oxidized/configs/
drwxr-xr-x 5 root root 4,0K Dez  2 00:41 .
drwxr-xr-x 5 root root 4,0K Dez  2 10:39 ..
drwxr-xr-x 2 root root 4,0K Dez  2 10:43 PTP
drwxr-xr-x 2 root root 4,0K Dez  2 10:43 RT
drwxr-xr-x 2 root root 4,0K Dez  2 10:41 SW_

and on web interface, this error, when I try access some backup: 
_Errno::ENOENT at /node/fetch/RT/BA-BRM-A01-COR-RT-001
No such file or directory @ rb_sysopen - /root/.config/oxidized/configs/backup/RT/BA-BRM-A01-COR-RT-001_

**Comment by ytti** [comment]
Which Oxidized version are you running, I could have sworn we've fixed that, but perhaps not. The stored files certainly are in expected location, it's trying to read wrong location for sure, definitely a bug.

**Comment by paulocoimbrati** [comment]
oxidized -v
0.18.0

**Comment by ytti** [comment]
Ok, I'll fix that.
