### ISSUE TITLE
Using single quotes in Event Hooks causes an error

### ISSUE THREAD

**Issue by marrold** [ytti/oxidized#627]
Hi, 

I'm trying to use an event hook to push JSON to an API. The curl command works from the shell however when I start Oxidized it throws an error

The offending line-

```
cmd: 'curl -H "Content-Type: application/json"  -d '{"value1": "$OX_NODE_NAME"}' -X POST https://maker.ifttt.com/trigger/Oxidized_Updated/with/key/TopSecretKey'
```

The error-

```
Error loading config: (<unknown>): did not find expected key while parsing a block mapping at line 53 column 5
/var/lib/gems/2.2.0/gems/oxidized-0.18.0/lib/oxidized/config.rb:50:in `rescue in load': Error loading config: (<unknown>): did not find expected key while parsing a block mapping at line 53 column 5 (Oxidized::InvalidConfig)
        from /var/lib/gems/2.2.0/gems/oxidized-0.18.0/lib/oxidized/config.rb:47:in `load'
        from /var/lib/gems/2.2.0/gems/oxidized-0.18.0/lib/oxidized/cli.rb:24:in `initialize'
        from /var/lib/gems/2.2.0/gems/oxidized-0.18.0/bin/oxidized:9:in `new'
        from /var/lib/gems/2.2.0/gems/oxidized-0.18.0/bin/oxidized:9:in `<top (required)>'
        from /usr/local/bin/oxidized:23:in `load'
        from /usr/local/bin/oxidized:23:in `<main>'
```

If I remove the JSON, Oxidized starts as normal, so I believe the single quotes are causing the problem. I've tried escaping them with backslashes but it still fails.

Does anyone have any suggestions? I'm afraid I'm not familiar with Ruby.

**Comment by ytti** [comment]
Yeah single quotes definitely are causing your problem, as the string is ending when on the 2nd single quote.
So you probably should escape the the single quotes for the -d

**Comment by marrold** [comment]
Thanks for the quick response.

Same error with `\'`

'''
oxidized@oxidized:/home/matthew$ oxidized -d
Error loading config: (<unknown>): did not find expected key while parsing a block mapping at line 53 column 5
/var/lib/gems/2.2.0/gems/oxidized-0.18.0/lib/oxidized/config.rb:50:in `rescue in load': Error loading config: (<unknown>): did not find expected key while parsing a block mapping at line 53 column 5 (Oxidized::InvalidConfig)
        from /var/lib/gems/2.2.0/gems/oxidized-0.18.0/lib/oxidized/config.rb:47:in `load'
        from /var/lib/gems/2.2.0/gems/oxidized-0.18.0/lib/oxidized/cli.rb:24:in `initialize'
        from /var/lib/gems/2.2.0/gems/oxidized-0.18.0/bin/oxidized:9:in `new'
        from /var/lib/gems/2.2.0/gems/oxidized-0.18.0/bin/oxidized:9:in `<top (required)>'
        from /usr/local/bin/oxidized:23:in `load'
        from /usr/local/bin/oxidized:23:in `<main>'
'''

**Comment by ytti** [comment]
For a workaround, could you make shell script which you call so that the cmd is just reference to the shell script?

**Comment by marrold** [comment]
That will work. Thanks

**Comment by ytti** [comment]
https://github.com/dotmaster/toYaml/issues/1

It seems in YAML you escape single quotes with double quote
