### ISSUE TITLE
XOS Configuration Change False Positive

### ISSUE THREAD

**Issue by adamboutcher** [ytti/oxidized#629]
Hi,

I have an old Extreme Networking switch, and it's flagging up a change in oxidized every time it runs due to the config output containing the date the config was polled as seen by the following git commit extract:
`-  # Summit48si Configuration generated Mon Dec 5 01:34:08 2016`
`+ # Summit48si Configuration generated Mon Dec 5 01:45:46 2016`

Is there any way we can ignore this line change?

**Comment by ytti** [comment]
I'm confident as you review the model and perhaps some other models you can come up with a regexp to mask the changing bits. 

If you do not have the time, I can help you, but I'll need access to a device to confirm change works.
