### ISSUE TITLE
Array convert error in acos.rb 

### ISSUE THREAD

**Issue by devnulls** [ytti/oxidized#63]
I'm try to pull config from A10 device and seems stuck on Aflex array. not a ruby enthusiastic but will try to sort out :dash: 

2014-12-05 12:31:55 UTC
can't convert Array into String [TypeError]
--------------------------------------------------
/var/lib/gems/1.9.1/gems/oxidized-0.3.0/lib/oxidized/string.rb:23:in `initialize'
/var/lib/gems/1.9.1/gems/oxidized-0.3.0/lib/oxidized/string.rb:23:in `initialize'
/var/lib/gems/1.9.1/gems/oxidized-0.3.0/lib/oxidized/model/model.rb:156:in `new'
/var/lib/gems/1.9.1/gems/oxidized-0.3.0/lib/oxidized/model/model.rb:156:in `process_cmd_output'
/var/lib/gems/1.9.1/gems/oxidized-0.3.0/lib/oxidized/model/model.rb:91:in `cmd'
/var/lib/gems/1.9.1/gems/oxidized-0.3.0/lib/oxidized/model/acos.rb:39:in `block (3 levels) in <class:ACOS>'
/var/lib/gems/1.9.1/gems/oxidized-0.3.0/lib/oxidized/model/acos.rb:38:in `each'
/var/lib/gems/1.9.1/gems/oxidized-0.3.0/lib/oxidized/model/acos.rb:38:in `block (2 levels) in <class:ACOS>'
/var/lib/gems/1.9.1/gems/oxidized-0.3.0/lib/oxidized/model/acos.rb:36:in `each'
/var/lib/gems/1.9.1/gems/oxidized-0.3.0/lib/oxidized/model/acos.rb:36:in `block in <class:ACOS>'
/var/lib/gems/1.9.1/gems/oxidized-0.3.0/lib/oxidized/model/model.rb:136:in `instance_eval'
/var/lib/gems/1.9.1/gems/oxidized-0.3.0/lib/oxidized/model/model.rb:136:in `block in get'
/var/lib/gems/1.9.1/gems/oxidized-0.3.0/lib/oxidized/model/model.rb:135:in `each'
/var/lib/gems/1.9.1/gems/oxidized-0.3.0/lib/oxidized/model/model.rb:135:in `get'
/var/lib/gems/1.9.1/gems/oxidized-0.3.0/lib/oxidized/input/cli.rb:13:in `get'
/var/lib/gems/1.9.1/gems/oxidized-0.3.0/lib/oxidized/node.rb:54:in `run_input'
/var/lib/gems/1.9.1/gems/oxidized-0.3.0/lib/oxidized/node.rb:32:in `block in run'
/var/lib/gems/1.9.1/gems/oxidized-0.3.0/lib/oxidized/node.rb:30:in `each'
/var/lib/gems/1.9.1/gems/oxidized-0.3.0/lib/oxidized/node.rb:30:in `run'
/var/lib/gems/1.9.1/gems/oxidized-0.3.0/lib/oxidized/job.rb:8:in `block in initialize'

**Comment by aakso** [comment]
@devnulls can you try if the attached patch works? I'm in a middle of something and cannot test against real ACOS device :/


```
commit ca780ab77dad920970febd5bf267da30aded8980
Author: Anton Aksola <anton.aksola@nebula.fi>
Date:   Mon Feb 23 08:19:08 2015 +0200

    Return empty strings from ACOS data gathering cmd calls
    
    Fixes #63
    
    With the introduction of Oxidized::String in ff150578 we cannot return
    anything other than strings from cmd method call blocks as String.new
    will raise TypeError.
    
    It would be nicer to fix this in base model class somehow. Few ideas:
      - Provide separate method for data gathering commands that do not
        append to device config
      - Typeswitch in Base#cmd for strings or Oxidized::Strings. Any other
        type -> no appending
      - Provide :no_ouput or similar kw arg to Base#cmd

diff --git a/lib/oxidized/model/acos.rb b/lib/oxidized/model/acos.rb
index 75fbacf..f024664 100644
--- a/lib/oxidized/model/acos.rb
+++ b/lib/oxidized/model/acos.rb
@@ -22,7 +22,7 @@ class ACOS < Oxidized::Model
       # only consider scripts that have passed syntax check
       h[h.keys.last] << $1 if l.match /^([\w-]+) +Check/  
     end
-    ''
+    '' # data gathering: return empty string so output is not appended
   end
 
   cmd :all do |cfg, cmdstring|
@@ -41,6 +41,7 @@ class ACOS < Oxidized::Model
             out << "aflex create #{name}"
             out << content
             out << ".\n"
+            '' # we are returning the real output later
           end
         end
       end```
