### ISSUE TITLE
Groups and ssh_port

### ISSUE THREAD

**Issue by axemann** [ytti/oxidized#632]
Hi all,

I'm having an issue with specifying the ssh_port variable under a group.  My source is HTTP from LibreNMS, and I have a pfSense box that runs SSH on a custom port (22222), but when I specify that variable in the 'groups:' config, it doesn't appear to be using the port.

Here's my 'groups:' config section (sorry about the bad formatting, GitHub n00b here):

```
`groups:`
`  pfsense:`
`    vars:`
`      ssh_port: 22222`
```
The system appears to be pulling the correct hostname, os, and group from LibreNMS:

```
`[`
`    {`
`        "hostname": "pfsense",`
`        "os": "pfsense",`
`        "group": "pfsense"`
`    }`
`]`
```

Not sure what's going on here, or if I'm misunderstanding what the 'groups:' config is capable of.  Do I also need to specify something in the 'vars:' root config section?

Let me know if you need any additional config output.

Thanks!

**Comment by ytti** [comment]
That should work. It should work on node, group and 'root' level. 

It's set here: https://github.com/ytti/oxidized/blob/master/lib/oxidized/config/vars.rb#L8

And It's used here:
https://github.com/ytti/oxidized/blob/master/lib/oxidized/input/ssh.rb#L26

I don't immediately see ay reason why it's not working. Is your indentation correct?

**Comment by axemann** [comment]
@ytti, I believe so.  I'm attaching a partially-sanitized full config below.  Everything looked okay to me, but I'm new to YAML-style configs:
```
---
username: <redacted>
password: <redacted>
#model: pfsense
interval: 3600
use_syslog: false
debug: true
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 0.0.0.0:8888
vars: {}
groups:
  pfsense:
    vars:
      ssh_port: 22222
pid: "/home/oxidized/.config/oxidized/pid"
#pid: "/var/run/oxidized.pid"
input:
  default: ssh, telnet
  debug: true
  ssh:
    secure: false
output:
  default: git
  file:
    directory: "/home/oxidized/.config/oxidized/configs"
#    directory: "/etc/oxidized/configs"
  git:
    user: oxidized
    email: axemann@gmail.com
    repo: /etc/oxidized/configs/git-repos/default.git
source:
  default: http
  debug: true
  csv:
    file: "/etc/oxidized/router.db"
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
      username: 2
      password: 3
    vars_map:
      ssh_port: 4
      enable: 5
  http:
    url: http://librenms.7priest.local/api/v0/oxidized
    scheme: http
    delimiter: !ruby/regexp /:/
    map:
      name: hostname
      model: os
      group: group
    headers:
      X-Auth-Token: '<redacted>'
model_map:
  cisco: ios
  juniper: junos
  pfsense: pfsense
  quanta: quantaos
  apc: apc_aos
  unifi: airos
```

**Comment by ytti** [comment]
I can't imagine the CSV breaking anything, but please remove it nontheless, as it has ssh_port map, which is more specific than group level. It shouldn't be read, but it's useless config for you anyhow.

Are we convinced you are getting groups correctly from http? Like if you intentionally set wrong username/password in group level (which overrides root level) will login to pfsense fail? Is pfsense in its own git repo? If you have groups, and single_repo isn't set, then each group would create own git repo.

**Comment by axemann** [comment]
I've tried user/pass in both sections with the same result, but I just tried setting a bad password in the `groups:` section and it said that it couldn't connect (after removing the `csv:` config block) so that's an improvement.

I'll try setting `single_repo` and see if that makes a difference.  If not, I'll blow away the repo and let the process create a new one and we can go from there.

**Comment by axemann** [comment]
Well, apparently I can't read my own router.db contents.  Turns out I was using a different username in the CSV and decided to use the wrong one for the group config.  That's what I get for assuming, LOL.

@ytti, you can close this as resolved, due to ID10T error. :flushed:

**Comment by ytti** [comment]
Happy to hear it works!
