### ISSUE TITLE
Groups and push to remote

### ISSUE THREAD

**Issue by jonare77** [ytti/oxidized#636]
Getting this error:

Hook push_to_remote (#<GithubRepo:0x00000002594028>) failed (#<NoMethodError: undefined method `[]' for nil:NilClass>) for event :node_success

Using single local repo, and groups defined i router.db.

Config:

```
model: junos
interval: 3600
use_syslog: false
debug: false
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 0.0.0.0:8888
vars: {}
groups: {}
pid: "/home/oxidized/.config/oxidized/pid"
log: "/home/oxidized/.config/oxidized/logs/oxidized.log"
input:
  default: ssh
  debug: true
  ssh:
    secure: true
output:
  default: git
  debug: true
  git:
    single_repo: true
    user: git
    email: jon.are.endrerud@ringerike.kommune.no
    repo: "/home/oxidized/.config/oxidized/rkdevices.git"
source:
  default: csv
  csv:
    file: "~/.config/oxidized/router.db"
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
      group: 2
      username: 3
      password: 4
    vars_map:
      enable: 5
model_map:
  cisco: ios
  juniper: junos
hooks:
  push_to_remote:
    type: githubrepo
    username: administrator
    remote_repo: 
    procurve: git@gitlab.rk.local:administrator/procurve.git
    h3c: git@gitlab.rk.local:administrator/h3c.git
    cisco: git@gitlab.rk.local:administrator/cisco.git
    
    events: [node_success]


    publickey: "/home/oxidized/.ssh/id_rsa.pub"
    privatekey: "/home/oxidized/.ssh/id_rsa"
```

**Comment by ytti** [comment]
Which Oxidized version are you running? Do you have full backtrace?

**Comment by jonare77** [comment]
Im kind of a noob, do you mean a full log when talking backtrace ?

the problem occured when going from a single push repo to grouped.

E, [2016-12-09T12:07:55.715976 #5033] ERROR -- : Hook push_to_remote (#<GithubRepo:0x00000001936c90>) failed (#<NoMethodError: undefined method `[]' for nil:NilClass>) for event :node_success
D, [2016-12-09T12:07:55.716573 #5033] DEBUG -- : lib/oxidized/worker.rb: Jobs 0, Want: 1
D, [2016-12-09T12:07:55.716730 #5033] DEBUG -- : lib/oxidized/job.rb: Starting fetching process for 10.199.19.1 at 2016-12-09 11:07:55 UTC
D, [2016-12-09T12:07:55.716672 #5033] DEBUG -- : lib/oxidized/worker.rb: Added 10.199.19.1 to the job queue
D, [2016-12-09T12:07:55.716922 #5033] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2016-12-09T12:07:55.717035 #5033] DEBUG -- : lib/oxidized/input/ssh.rb: Connecting to 10.199.19.1
D, [2016-12-09T12:07:55.797061 #5033] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^\r*([\w.@()-\/]+[#>]\s?)$/] at 10.199.19.1
D, [2016-12-09T12:07:56.610104 #5033] DEBUG -- : lib/oxidized/input/cli.rb: Running post_login commands at 10.199.19.1
D, [2016-12-09T12:07:56.610282 #5033] DEBUG -- : lib/oxidized/input/cli.rb: Running post_login command: nil, block: #<Proc:0x00000001d767d8@/var/lib/gems/2.3.0/gems/oxidized-0.18.0/lib/oxidized/model/asa.rb:56> at 10.199.19.1
D, [2016-12-09T12:07:56.610334 #5033] DEBUG -- : lib/oxidized/input/ssh.rb 7ireWall @ 10.199.19.1 with expect: /^\r*([\w.@()-\/]+[#>]\s?)$/
D, [2016-12-09T12:07:56.610483 #5033] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^\r*([\w.@()-\/]+[#>]\s?)$/] at 10.199.19.1
D, [2016-12-09T12:07:56.717193 #5033] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2016-12-09T12:07:57.080378 #5033] DEBUG -- : lib/oxidized/input/cli.rb: Running post_login command: "terminal pager 0", block: nil at 10.199.19.1
D, [2016-12-09T12:07:57.080487 #5033] DEBUG -- : lib/oxidized/input/ssh.rb terminal pager 0 @ 10.199.19.1 with expect: /^\r*([\w.@()-\/]+[#>]\s?)$/
D, [2016-12-09T12:07:57.080625 #5033] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^\r*([\w.@()-\/]+[#>]\s?)$/] at 10.199.19.1
D, [2016-12-09T12:07:57.545632 #5033] DEBUG -- : lib/oxidized/model/model.rb Collecting commands' outputs
D, [2016-12-09T12:07:57.545739 #5033] DEBUG -- : lib/oxidized/model/model.rb Executing show version
D, [2016-12-09T12:07:57.545766 #5033] DEBUG -- : lib/oxidized/input/ssh.rb show version @ 10.199.19.1 with expect: /^\r*([\w.@()-\/]+[#>]\s?)$/
D, [2016-12-09T12:07:57.545911 #5033] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^\r*([\w.@()-\/]+[#>]\s?)$/] at 10.199.19.1
D, [2016-12-09T12:07:57.717432 #5033] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2016-12-09T12:07:58.200161 #5033] DEBUG -- : lib/oxidized/model/model.rb Executing show inventory
D, [2016-12-09T12:07:58.200261 #5033] DEBUG -- : lib/oxidized/input/ssh.rb show inventory @ 10.199.19.1 with expect: /^\r*([\w.@()-\/]+[#>]\s?)$/
D, [2016-12-09T12:07:58.200458 #5033] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^\r*([\w.@()-\/]+[#>]\s?)$/] at 10.199.19.1
D, [2016-12-09T12:07:58.677140 #5033] DEBUG -- : lib/oxidized/model/model.rb Executing more system:running-config
D, [2016-12-09T12:07:58.677238 #5033] DEBUG -- : lib/oxidized/input/ssh.rb more system:running-config @ 10.199.19.1 with expect: /^\r*([\w.@()-\/]+[#>]\s?)$/
D, [2016-12-09T12:07:58.677377 #5033] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^\r*([\w.@()-\/]+[#>]\s?)$/] at 10.199.19.1
D, [2016-12-09T12:07:58.717631 #5033] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2016-12-09T12:07:59.717798 #5033] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2016-12-09T12:08:00.717986 #5033] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2016-12-09T12:08:01.718160 #5033] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2016-12-09T12:08:01.838569 #5033] DEBUG -- : lib/oxidized/input/cli.rb Running pre_logout commands at 10.199.19.1
D, [2016-12-09T12:08:01.838671 #5033] DEBUG -- : lib/oxidized/input/ssh.rb exit @ 10.199.19.1 with expect: nil
D, [2016-12-09T12:08:01.854186 #5033] DEBUG -- : lib/oxidized/node.rb: Oxidized::SSH ran for 10.199.19.1 successfully
D, [2016-12-09T12:08:01.854257 #5033] DEBUG -- : lib/oxidized/job.rb: Config fetched for 10.199.19.1 at 2016-12-09 11:08:01 UTC
I, [2016-12-09T12:08:02.718678 #5033]  INFO -- : GithubRepo: Pushing local repository(/home/oxidized/.config/oxidized/rkdevices.git/)...
E, [2016-12-09T12:08:02.719914 #5033] ERROR -- : Hook push_to_remote (#<GithubRepo:0x00000001936c90>) failed (#<NoMethodError: undefined method `[]' for nil:NilClass>) for event :node_success

**Comment by ytti** [comment]
What version are you running, I didn't give this much attention yet, as I have some recollection this may be fixed bug. If you're not running latest, could you try to upgrade please.

**Comment by jonare77** [comment]
Not at the office now, but the version shoud be 0.18

Mvh
Jon Are Endrerud
Drift, IT Enheten
Ringerike Kommune
Mob: 97531690




On Fri, Dec 9, 2016 at 12:27 PM +0100, "ytti" <notifications@github.com<mailto:notifications@github.com>> wrote:


What version are you running, I didn't give this much attention yet, as I have some recollection this may be fixed bug. If you're not running latest, could you try to upgrade please.

-

**Comment by ytti** [comment]
If you changed to single_repo, change the ```remote_repo``` to string, instead of hash/dict like it is now. ```remote_repo: something_something```

**Comment by jonare77** [comment]
No luck, but I will setup a new machine and to some further testing on this. Im new to ruby, hooks and everything. Oxidized is just super compared to Rancid and other pricy products. Thanx

**Comment by jonare77** [comment]
This config runs perfect. Push is correct and no error. When I include a map for group and try to push the repo remote the problem occurs. Will take it step by step and see what happening.

model: junos
interval: 3600
use_syslog: false
debug: false
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 0.0.0.0:8888
vars: {}
groups: {}
pid: "/home/oxidized/.config/oxidized/pid"
log: "/home/oxidized/.config/oxidized/logs/oxidized.log"
input:
  default: ssh
  debug: true
  ssh:
    secure: true
output:
  default: git
  debug: true
  git:
    user: git
    email: jon.are.endrerud@ringerike.kommune.no
    repo: "/home/oxidized/.config/oxidized/oxidized.git"
source:
  default: csv
  csv:
    file: "~/.config/oxidized/router.db"
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
      username: 2
      password: 3
    vars_map:
      enable: 4
model_map:
  cisco: ios
  juniper: junos
hooks:
  push_to_remote:
    type: githubrepo
    username: administrator
    remote_repo: git@gitlab.rk.local:administrator/oxidized.git
    events:
    - node_success
    publickey: "/home/oxidized/.ssh/id_rsa.pub"
    privatekey: "/home/oxidized/.ssh/id_rsa"

**Comment by ytti** [comment]
In your original config, there is no indent after 'remote_repo' keys, this makes the 'groups' keys of 'push_to_remote', instead of being keys of 'remote_repo'. Does the indentation on github issue reflect indentation on disk? If so, then it wouldn't work without fixing the indentation.

**Comment by jonare77** [comment]
Ok thanks for help, will check this out.

Fra: ytti [mailto:notifications@github.com]
Sendt: fredag 9. desember 2016 18.49
Til: ytti/oxidized <oxidized@noreply.github.com>
Kopi: jonare77 <jonare@endrerud.org>; Author <author@noreply.github.com>
Emne: Re: [ytti/oxidized] Groups and push to remote (#636)


In your original config, there is no indent after 'remote_repo' keys, this makes the 'groups' keys of 'push_to_remote', instead of being keys of 'remote_repo'. Does the indentation on github issue reflect indentation on disk? If so, then it wouldn't work without fixing the indentation.

**Comment by laf** [comment]
@jonare77 Did you fix the indentation issue?
