### ISSUE TITLE
Custom git port ignored by githubrepo hook

### ISSUE THREAD

**Issue by nktl** [ytti/oxidized#643]
It looks like githubrepo ignores custom git port and always tries to connect to 22.
This is required for git hosts like Bitbucket.

My config:

```
hooks:
  push_to_remote:
    type: githubrepo
    events: [post_store]
    remote_repo: git@bitbucket:7999/repos/networkrepo.git
    publickey: /home/oxidized/.ssh/id_rsa.pub
    privatekey: /home/oxidized/id_rsa
```

I can see authentication attempt hitting port 22 in the log on the server though, it obviously does not work very well:

```
Dec 15 12:20:56 oxd01 oxidized[25653]: I, [2016-12-15T12:20:56.314272 #25653]  INFO -- : GithubRepo: Pushing local repository(/etc/oxidized/configs/)...
Dec 15 12:20:56 oxd01 oxidized[25653]: I, [2016-12-15T12:20:56.314463 #25653]  INFO -- : GithubRepo: to remote: git@bitbucket:7999/repos/networkrepo.git
Dec 15 12:20:56 oxd01 oxidized[25653]: D, [2016-12-15T12:20:56.314542 #25653] DEBUG -- : GithubRepo: Using ssh auth with key
Dec 15 12:20:56 oxd01 oxidized[25653]: E, [2016-12-15T12:20:56.379561 #25653] ERROR -- : Hook push_to_remote (#<GithubRepo:0x00000002599708>) failed (#<Rugged::SshError: Failed to authenticate SSH session: Waiting for USERAUTH response>) for event :post_store
```

Tried prefixing the repo with git:// or ssh://, bit it does not make a difference, :7999 port value seems to be igrored?

**Comment by nktl** [comment]
By the way, I can see that remotes are properly configured in git oxidized repo and manual push using git client works just fine:

```
[oxidized@oxd01 default.git]$ git remote -v
origin  ssh://git@bitbucket:7999/repos/networkrepo.git (fetch)
origin  ssh://git@bitbucket:7999/repos/networkrepo.git (push)

[oxidized@oxd01 default.git]$ git push origin master
Counting objects: 42, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (41/41), done.
Writing objects: 100% (42/42), 93.86 KiB | 0 bytes/s, done.
Total 42 (delta 20), reused 0 (delta 0)
To ssh://git@bitbucket:7999/repos/networkrepo.git
 * [new branch]      master -> master
```

**Comment by ytti** [comment]
How do you determine that 7999 is not used? Could you run tshark when then push occurs to confirm that 7999 is not being used?

**Comment by nktl** [comment]
I did some more digging on this with tcpdump - it looks like the traffic is not going to port 22 any more. 
Not sure what exactly helped, I updated Rugged to the latest version and cleaned oxidized git repo completely in the meantime.

Unfortunately the push still fails, albeit with different error:

```
Dec 15 13:50:48 oxd01 oxidized[2924]: I, [2016-12-15T13:50:48.552424 #2924]  INFO -- : GithubRepo: Pushing local repository(/etc/oxidized/default.git/)...
Dec 15 13:50:48 oxd01 oxidized[2924]: I, [2016-12-15T13:50:48.552671 #2924]  INFO -- : GithubRepo: to remote: ssh://git@bitbucket:7999/repos/networkrepo.git
Dec 15 13:50:48 oxd01 oxidized[2924]: E, [2016-12-15T13:50:48.647829 #2924] ERROR -- : Hook push_to_remote (#<GithubRepo:0x000000012981e0>) failed (#<Rugged::SshError: Failed to authenticate SSH session: Callback returned error>) for event :node_success
```

In Wireshark I can see that the SSH session is established with key exchange happening between both parties - but then the traffic drops after a few encrypted packets later.

**Comment by ytti** [comment]
It does seem like authentication is failing, it works from CLI, without agent?

**Comment by nktl** [comment]
Absolutely, works just fine using CLI as oxidized user with the same keys and git endpoint (git@bitbucket:7999/repos/networkrepo.git).

In fact, this is what I am doing right now - running 'git push' periodically from cron :(

**Comment by ytti** [comment]
And you're positive you're not using agent? ```ssh-add -l``` lists no keys? If you don't manage far-end, can you change it to your own servers and recreate problem, so that you can see what the far-end logs say?

**Comment by nktl** [comment]
Positive - no keys in agent. I manage the other end, but not seeing any activity in the logs for oxidized hook  job (only stuff for my cron job), which means ssh auth must be failing very early....

**Comment by ytti** [comment]
Hmm far-end openssh should totally see auth fail no matter how early, I think it would be useful. Perhaps try to add verbosity there.

**Comment by laf** [comment]
@nktl Have you managed to look into this further?

**Comment by nktl** [comment]
No sorry - After spending a lot of time troubleshooting this, I eventually gave up and now use local oxidized git repo + crude cron job to execute git push to our Bitbucket.

**Comment by laf** [comment]
Might be worth closing for now then.

**Comment by nktl** [comment]
Yes, please close it - will re-open if this ever has to be revisited later.

**Comment by ding107** [comment]
I am having this exact same issue. BitBucket uses port 7999 and the hook is trying to connect on port 22 (verified with tcpdump) even with the port in the URL

**Comment by dangoscomb** [comment]
We are also experiencing the same issue. The git URL is specified with the port number, however pcaps show that it is trying to connect out on the default port 22.

**Comment by ytti** [comment]
When you do ```git remove -v``` you see correct port, but that port is not used?

**Comment by dangoscomb** [comment]
I am not sure where the local working copy of the repo is located? I was
under the impression there wasn't one.

Config wise I have this:

output:
  default: git
  git:
    user: Oxidized
    email: oxidized@hso-group.net
    repo: "/home/oxidized/git-repos/default.git"
hooks:
  push_to_remote:
    type: githubrepo
    events: [post_store]
    remote_repo: "ssh://git@bitbucket.xxxxxxx.xxx
:2222/net/oxidized-configs.git"
    publickey: /home/oxidized/.ssh/id_rsa.pub
    privatekey: /home/oxidized/.ssh/id_rsa


I've also tried different strings (not in quotes, without ssh://) for the
repo spec but get the same result.

**Comment by ytti** [comment]
You don't need to have local working copy. The repo the one in your config, the default.git.

It should honour the 'remote -v' of that.

https://github.com/ytti/oxidized/blob/master/lib/oxidized/hook/githubrepo.rb#L9

Here we only even consider the remote_repo, if origin has not been set. And if I read the code right, we actually in 'fetch' don't ever consider the remote_repo. It's kinda just hoping that the initial set of origin is applicable.

So if you've previously set SOME origin (the code sets it), it will honour that over remote_repo. 

So please see 'git remote -v' of your repo, and update the URL as needed.

**Comment by ytti** [comment]
We might want to do something like:

```
remote = repo.remotes['oxi_hook_githubrepo'] || repo.remotes.create('oxi_hook_github_repo')
repo.remotes.set_url("oxi_hook_githubrepo", remote_repo(ctx.node)=
```

And change line 18 to 'oxi_hook_githubrepo' , this way we'd reset the oxi_hook_githubrepo remote every time to what ever is in config, so if you change config it'll reflect to action.
Now the config is one-time, changes won't affect.

**Comment by dangoscomb** [comment]
ok, it seems because the repos were created before adding a remote then the
URLs were not subsequently added.

In addition we had to move to a single repo config (not a major issue) as
our group names have spaces, etc which don't translate on to what bitbucket
names the same repos.

All working now with a newly created single repo

**Comment by ytti** [comment]
You didn't need to recreate anything, just reset the url as shown.
