### ISSUE TITLE
problem with telnet connection ios/iosxr

### ISSUE THREAD

**Issue by mattttv** [ytti/oxidized#649]
hi guys

Does anyone know the answer to this problem?
I have an IOS/IOSXR (could be both and tried both with same result) device which shall be connected through telnet.
Debug options are enabled for input and logs in general.

I can log in to the device via telnet so the connection is possible.

Unfortunately the logs are not very helpful:
general log [1]
ssh-log is empty (that is fine)
telnet-log just keeps repeating [2]

ssh is not allowed due to missing firewall rule - so the ECONNREFUSED is fine.
But telnet works when I try it manually. Overmore the prompt looks the same on this device as it does on an working device:
DEVICE01#

Has anyone an advice?
Thank you very much in advance.

Kind Regards,
Matt

[1]
DEBUG -- : lib/oxidized/worker.rb: Added DEVICE01 to the job queue
DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
DEBUG -- : lib/oxidized/job.rb: Starting fetching process for DEVICE01 at 2016-12-22
․
DEBUG -- : lib/oxidized/input/ssh.rb: Connecting to DEVICE01
DEBUG -- : 192.168.1.1 raised Errno::ECONNREFUSED with msg "Connection refused - co

DEBUG -- : lib/oxidized/node.rb: Oxidized::SSH failed for DEVICE01
DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
              ....this line is repeated several times
DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
 WARN -- : 192.168.1.1 raised Timeout::Error with msg "timed out while waiting for more data"
DEBUG -- : lib/oxidized/node.rb: Oxidized::Telnet failed for DEVICE01

[2]
username: Trying 192.168.1.1...
Connected to 192.168.1.1.

username:

**Comment by ytti** [comment]
The username prompt is not capitalised, IOS and IOS-XR capitalise the u. Are you sure this is IOS or IOS-XR device. When you login to it manually and issue ```sh ver```, what does it output?

**Comment by mattttv** [comment]
hi ytti! thank you for the answer!
Yes it definitely is an IOS device [1]

Maybe that was an individual setting - anyway I think this "issue" is resolved - or do you think it would be appropriate to match for an regex instead of a hardcoded string so that username is matched as well?

Kind Regards,
Matt

[1]
Cisco IOS Software, 1841 Software (C1841-IPBASE-M), Version 12.4(15)T10, RELEASE SOFTWARE (fc3)

**Comment by ytti** [comment]
Why is it solved? 

We match on a regexp, not on a string, we can easily relax the regexp. Question is, why is it lower case u?

I believe TACACS can provide custom login prompts, perhaps it is also configurable. If this is the case, if you've intentionally changed the login prompt to non-standard, then I believe best option would be to put custom ```~/.config/oxidized/model/ios.rb``` reopen the class, and redefine the username prompt to match your environment.

**Comment by mattttv** [comment]
sooo there is a way to overwrite the mode-file? that is very helpful! I will add this to the docu as well :+1: 
I changed my local ios.rb to 
 
`username /^(u|U)sername:/`
`password /^(p|P)assword:/`

I propose that this regex should be case insensitive. Or is there a reason you kept it case sensitive?

Kind Regards,
Matt

**Comment by mattttv** [comment]
Unfortunately I cannot tell you why the login prompt is username and not Username because the administration of the devices is out of my scope.
I agree with you that if this problem has not come up yet and it seems to be a local problem only you should not change the model file.

However it is a very helpful feature to overwrite the model files with a configuration file - thanks again!
Kind Regards,
Matt

close

**Comment by ytti** [comment]
If you ever find time/scope to investigate into this, I'd love to know if it's something local or something Cisco itself does. Because latter we surely need to fix.

**Comment by zombah** [comment]
Hello,
On Cisco ASR 9006/9010 telnet login prompt look like this:
`(/dev/vty0) login:`

**Comment by ytti** [comment]
Thanks, I believe @mattttv issue was that the prompt was actually custom prompt delivered by TACACS.
