### ISSUE TITLE
Cannot start Oxidized

### ISSUE THREAD

**Issue by joseaugustocardoso** [ytti/oxidized#650]
When I trying to configure the oxidized to read device list on librenms by http, I receving the error:

[oxidized@librenms oxidized]$ oxidized
I, [2016-12-22T15:22:11.129255 #27099] INFO -- : Oxidized starting, running as pid 27099
I, [2016-12-22T15:22:11.176658 #27099] INFO -- : lib/oxidized/nodes.rb: Loading nodes
F, [2016-12-22T15:22:11.235753 #27099] FATAL -- : Oxidized crashed, crashfile written in /home/oxidized/.config/oxidized/crash
cannot interpret as DNS name: nil
/usr/share/ruby/resolv.rb:1195:in `create': cannot interpret as DNS name: nil (ArgumentError)

**Comment by ytti** [comment]
Can you share the crash file. Can you share the JSON given from librenms.

**Comment by laf** [comment]
@joseaugustocardoso you've also posted the same on librenms/librenms#5227 :(

**Comment by ytti** [comment]
The error is because we're feeding resolver name of ```nil``` type (i.e. not a string). Why do we get name ```nil``` is heart of the problem. Perhaps problem in data, perhaps problem in mapping, perhaps bug in code.

**Comment by laf** [comment]
We're happy to pick up on our side @ytti

**Comment by joseaugustocardoso** [comment]
@laf yes, I thinked that here the guys cant help-me. But, thank you for preoccupation. Oxidized is a killer feature on our deployment. I trying to implement the LibreNMS in a net very large.

**Comment by laf** [comment]
See my response in the thread you've opened on librenms

**Comment by joseaugustocardoso** [comment]
My config file:

---
username: 
password: 
model: ios
interval: 3600
use_syslog: false
debug: false
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 127.0.0.1:8888
vars: {}
groups: {}
pid: /home/oxidized/.config/oxidized/pid
input:
  default: ssh, telnet
  debug: false
  ssh:
    secure: false
output:
  default: file
  file:
    directory: /home/oxidized/.config/oxidized/configs
source:
  default: http
  debug: true
  http:
    url: http://127.0.0.1/api/v0/oxidized
    scheme: http
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
      group: group
    headers:
      X-Auth-Token: '029f854fec93bd162a7e8b4ee08ef9d9'
model_map:
  cisco: ios
  juniper: junos


[oxidized@librenms oxidized]$ cat crash 
--------------------------------------------------
2016-12-23 00:12:22 UTC
cannot interpret as DNS name: nil [ArgumentError]
--------------------------------------------------
/usr/share/ruby/resolv.rb:1195:in `create'
/usr/share/ruby/resolv.rb:1037:in `generate_candidates'
/usr/share/ruby/resolv.rb:1066:in `resolv'
/usr/share/ruby/resolv.rb:513:in `each_resource'
/usr/share/ruby/resolv.rb:406:in `each_address'
/usr/share/ruby/resolv.rb:115:in `block in each_address'
/usr/share/ruby/resolv.rb:114:in `each'
/usr/share/ruby/resolv.rb:114:in `each_address'
/usr/share/ruby/resolv.rb:92:in `getaddress'
/usr/local/share/gems/gems/oxidized-0.19.0/lib/oxidized/node.rb:15:in `initialize'
/usr/local/share/gems/gems/oxidized-0.19.0/lib/oxidized/nodes.rb:19:in `new'
/usr/local/share/gems/gems/oxidized-0.19.0/lib/oxidized/nodes.rb:19:in `block (2 levels) in load'
/usr/local/share/gems/gems/oxidized-0.19.0/lib/oxidized/nodes.rb:15:in `each'
/usr/local/share/gems/gems/oxidized-0.19.0/lib/oxidized/nodes.rb:15:in `block in load'
/usr/local/share/gems/gems/oxidized-0.19.0/lib/oxidized/nodes.rb:126:in `synchronize'
/usr/local/share/gems/gems/oxidized-0.19.0/lib/oxidized/nodes.rb:126:in `with_lock'
/usr/local/share/gems/gems/oxidized-0.19.0/lib/oxidized/nodes.rb:10:in `load'
/usr/local/share/gems/gems/oxidized-0.19.0/lib/oxidized/nodes.rb:121:in `initialize'
/usr/local/share/gems/gems/oxidized-0.19.0/lib/oxidized/core.rb:14:in `new'
/usr/local/share/gems/gems/oxidized-0.19.0/lib/oxidized/core.rb:14:in `initialize'
/usr/local/share/gems/gems/oxidized-0.19.0/lib/oxidized/core.rb:4:in `new'
/usr/local/share/gems/gems/oxidized-0.19.0/lib/oxidized/core.rb:4:in `new'
/usr/local/share/gems/gems/oxidized-0.19.0/lib/oxidized/cli.rb:12:in `run'
/usr/local/share/gems/gems/oxidized-0.19.0/bin/oxidized:9:in `<top (required)>'
/usr/local/bin/oxidized:23:in `load'
/usr/local/bin/oxidized:23:in `<main>'
--------------------------------------------------
[oxidized@librenms oxidized]$

**Comment by laf** [comment]
@joseaugustocardoso please respond to the issue you've created in librenms

**Comment by joseaugustocardoso** [comment]
The problem was the group.
@laf helpd me on librenms repo.

Thank you.
