### ISSUE TITLE
WebGUI Won't Load

### ISSUE THREAD

**Issue by keefe007** [ytti/oxidized#655]
I followed your installation guide for debian on a ubuntu server and the webgui won't load.  Any suggestions?

**Comment by job** [comment]
ticket closed due to lack of information on:

* OS
* ruby version
* other relevant debug info

**Comment by laf** [comment]
@ytti you can define templates for issues and pull requests:

https://github.com/librenms/librenms/tree/master/.github

Not that they always get followed :)
