### ISSUE TITLE
oxidized leaks memory when fetching full version history from git

### ISSUE THREAD

**Issue by jalmargyyk** [ytti/oxidized#656]
I have around 4k devices in oxidized. When I use oxidized-web and try to fetch all configuration versions of certain file, the oxidized process hogs a lot of memory. The issue is that this memory is never freed and ultimately oxidized process will eat all the memory available on the server. 

The memory consumption seems to come from these lines:
https://github.com/ytti/oxidized/blob/master/lib/oxidized/output/git.rb#L84-L93

First I tested with ruby 2.2.6p396 (2016-11-15 revision 56800) and then with the latest ruby-2.4.0-rc1 from rvm. No difference. Also Rugged gem was updated to the latest available. Any ideas on how to debug this further?

**Comment by falkowich** [comment]
+1 Same issue here. Not the same ruby version thou.

**Comment by ytti** [comment]
oxidized-web will assign it to instance variable ```@data```which will remain in the memory until something else is assigned there and the old is GC'd. But if subsequent runs to ```version``` use increasingly more memory, then something is off.

**Comment by devicenull** [comment]
This still seems to be an issue:

I started off here:

    # cat /proc/9225/status | egrep 'VmPeak|VmSize'
    VmPeak:  5472512 kB
    VmSize:  5275904 kB

Then, I refreshed a /version page 5 times (the device in question had 21 revisions, if that matters)

    # cat /proc/9225/status | egrep 'VmPeak|VmSize'
    VmPeak:  8421632 kB
    VmSize:  8356096 kB

Then I refreshed that page 5 more times:

    # cat /proc/9225/status | egrep 'VmPeak|VmSize'
    VmPeak: 10716420 kB
    VmSize: 10585348 kB

I waited a few minutes, and a little bit of garbage collection happened:

    # cat /proc/9225/status | egrep 'VmPeak|VmSize'
    VmPeak: 10716420 kB
    VmSize:  9012484 kB

But, it stayed there, and I didn't see any further garbage  collection happening after ~10 minutes.

**Comment by wk** [comment]
Could you comment if this issue is still present in modern Ruby (2.5+) and recent Oxidized (0.26.3+)?
