### ISSUE TITLE
ArubaOS show inventory diff changes

### ISSUE THREAD

**Issue by kdim953** [ytti/oxidized#657]
In reference to https://github.com/ytti/oxidized/pull/70

it seems my aruba devices are still showing changes even though the only thing changing is temperature and fan speed under 'show inventory'

```
[root@vm-net ~]$ oxidized --version
0.19.0
```

![screen shot 2017-01-09 at 12 15 15 pm](https://cloud.githubusercontent.com/assets/19291898/21781663/526d130e-d665-11e6-85bd-3e52c3ebca4a.png)

**Comment by ytti** [comment]
It shouldn't be hard to regexp those changing data to ```<n>```or so. @yeled may be able to help

**Comment by kdim953** [comment]
Is the Aruba model dead for this project?

**Comment by ytti** [comment]
This isn't large or busy project. In vast majority of cases when users have problem with model, they fix the model and submit PR.

I'm confident if you review the model and some other models, you're able to add regexp to the model to remove those changes.

You can run custom model by copying the distribution model to ```~/.config/oxidized/model/``` directory and modify it.

**Comment by vppencilsharpener** [comment]
Pull request https://github.com/ytti/oxidized/pull/668 has a fix for this and was accepted last night. I happened to be working on it separately yesterday and didn't see this issue until just now.

**Comment by ytti** [comment]
Thanks.
