### ISSUE TITLE
How I modify the model to separate the result of each command to each file

### ISSUE THREAD

**Issue by switchaphon** [ytti/oxidized#666]
Can I customize the model to generate each output file for each command of each device.

Such as 
./output/11.22.33.44_show_running_config
./output/11.22.33.44_show_version

the output configuration is defined as below 

_output:
  default: file
  file:
    directory: /home/oxidized/.config/oxidized/output_
 

And I have customized the ios.rb as below :

  cmd 'show startup-config' do |cfg|
      cfg
  end

  cmd 'show version' do |bar|
      bar.type = 'show_version'
      bar
  end

  cmd 'show inventory' do |bar|
      bar.type = 'show_inventory'
      bar
  end

However there is the  result in ./output folder only one file for command "show startup-config" 

Any idea ?

**Comment by ytti** [comment]
The ```file``` output module does not support this feature, you need to use ```git``` output module. It wouldn't be too hard to add if this is crucial.

**Comment by switchaphon** [comment]
Thank @ytti 

I already did as below :

`output:
  default: git
  git:
      user: oxidized
      email: oxidized@ntt.co.th
      repo: "~/.config/oxidized/repos/default"q`

`  cmd 'show startup-config' do |cfg|
     cfg
  end

   cmd 'show vlan' do |bar|
      bar.type = 'show_vlan'
      bar
   end
`

How we can check that separated file?

**Comment by ytti** [comment]
The separate file should just appear on your git repo.


If it does not, are you sure your custom module is really being used? I.e. that file should be 'ios.rb' in ~/config/oxidized/model directory.
