### ISSUE TITLE
[BUG] Vyos model regex prompt incorrect on Vyos v1.1.7 (latest stable)

### ISSUE THREAD

**Issue by soakes** [ytti/oxidized#670]
Hi guys,

Today I have tried to add in one of my Vyos routers running Vyos v1.1.7 (latest stable) and just found that it can't login successfully and extract the running config.

I am using the vyatta model as per github instructions.  I have also had a quick look at the ruby code and the rest of the info inside works i.e. on extracting config, so i'm sure its just the prompt that needs tweaking.

The debug output shows that the prompt setting is incorrect.

```
D, [2017-01-23T14:37:52.689878 #5920] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
W, [2017-01-23T14:37:52.970101 #5920]  WARN -- : xx.xx.xx.xx raised Oxidized::PromptUndetect with msg "Linux rt1 3.13.11-1-amd64-vyos #1 SMP Wed Aug 12 02:08:05 UTC 2015 x86_64
Welcome to VyOS.
This system is open-source software. The exact distribution terms for
each module comprising the full system are described in the individual
files in /usr/share/doc/*/copyright.
Last login: Mon Jan 23 14:27:52 2017 from xx.xxx.xx.xx
support@rt1>  not matching configured prompt (?-mix:\@.*?\:~\$\s)"
D, [2017-01-23T14:37:52.970248 #5920] DEBUG -- : lib/oxidized/node.rb: Oxidized::SSH failed for xxxxxx, Hetzner - Falkenstein, Germany (Ethernet) [1000]
D, [2017-01-23T14:37:53.690193 #5920] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
```

My regular expressions knowledge ins't my strong point or I would of fixed it so I wonder if someone could either tell me the new regex or supply me a new ruby file I could use.

Thanks in advance.

**Comment by ytti** [comment]
What device it is? The model prompt appears to expect ```$``` + space in end of prompt, you have ```>```. If it's edgeswitch, there is separate model for that.

**Comment by soakes** [comment]
Thanks for the reply, its the official download from their website running on a physical machine.

No prompt changes have been made, its a fresh install.

**Comment by ytti** [comment]
Well that is strange, I don't have vyatta, but people who do run it seem to have entirely different type of prompt. The prompt in the model looks like shell prompt, your prompt looks nothing like shell prompt. You could try to copy the model to ~/.config/oxidized/model directory and modify it. Make prompt something like ```/^\w+@\w+>\s*$/``` and see if that works

**Comment by soakes** [comment]
It is the shell prompt but they are also printing the motd (/etc/motd).  The prompt is at the very end.

`support@rt1>
`
Thats the prompt.

**Comment by ytti** [comment]
I mean the prompt the model is trying to find looks like unix shell prompt, the prompt you see is nothing like unix shell prompt. But try as I suggested in previous comment to see if it helps.

**Comment by soakes** [comment]
Confirmed works, thank you.

Just before I wrote this issue, I contacted a friend who knows regex very well and he has just got back to me while you were helping me with this issue.  He's just an improvement version which also covers the existing checks as well as that it adds support for my version, so if anyone else has this issue, they now have a working fix.

`/\@.*?(\:~\$|\>)\s/` 

I also just tested picking up a blank/fresh install of Vyos on another box and this also suffered the same problem (fresh install, blank config right now).  

Thanks again for the very quick response.

**Comment by ytti** [comment]
The MOTD has nothing to do it, it's just the prompt you see is entirely different than what the model sees, you might want to ping one of the people who have contributed on the model. I've never touched vyatta so I'm of little help. But clearly we're missing something here.

**Comment by soakes** [comment]
Thanks, wasn't sure if it did or did't. I was only going by the output in the log and figured it was that it was also matching that.

I will see if I can track one of them down shortly to do some more testing, for now what i've done so that I don't effect anything, is that I have created a new .rb file called vyos.rb and added the changes into that.  This way it wont get replaced on upgrades (temp fix until some upstream fix can be worked out in the future).
