### ISSUE TITLE
problem pfsense (versions)

### ISSUE THREAD

**Issue by pjust51** [ytti/oxidized#671]
Hi,

i use oxidized for backup configuration of my pfsense (v2.1.5)  and it works, except for versions with git output :

Here are screenshots to illustrate the problem :

- with the "configuration" button from first page, no problem :
https://www.noelshack.com/2017-04-1485185637-pfsense-1.png

- with the versions button then configuration, xml tags are deleted and the backup from older versions is unusable :
https://image.noelshack.com/fichiers/2017/04/1485186495-pfsense-2.png

can you provide a solution or fix the problem ? thanks

**Comment by ytti** [comment]
This is oxidized-web issue. I'm not unfortunately very familiar with that code, it might be good bet to open the case there, and add notifies to people who have written that code, like @ytti

**Comment by pjust51** [comment]
Thanks i open the case at oxidized-web

**Comment by wendelj** [comment]
This was fixed by this PR:
https://github.com/ytti/oxidized-web/pull/116
