### ISSUE TITLE
Problem with custom model for older FoundryOS devices

### ISSUE THREAD

**Issue by rjorgenson** [ytti/oxidized#676]
Hi,

Our environment has some older FoundryOS devices which is very similar to the IronWolf devices. I copied the IronWolf model and removed the logout command as it's not used and everything runs fine up until the user-mode prompt after quitting the shell. It just hangs but the prompt return matches the prompt regex in the model.

`prompt /^.*(telnet|ssh)\@.+[>#]\s?/i`

I removed the $ at the end of the regex because the debug log wasn't showing any EOL characters after the prompt.

`SW-SSH@host.name>`

The run eventually times out and all the output is in the ssh debug output with the user-mode prompt as the last line without any newline characters at the end.

`end`
`SW-SSH@host.name#quit`
`SW-SSH@host.name>`

Here is the pre_logout commands in the model

`    pre_logout 'quit'`
`    pre_logout 'exit'`

It never runs the exit command and eventually times out. Does anyone have any ideas why that regex would not be matching that prompt to run the second pre_logout command?

**Comment by rjorgenson** [comment]
I found #208 and tried the suggested fix of just sending one exit command and that did not produce any results =/

**Comment by wk** [comment]
This appears to be resolved in #693.
