### ISSUE TITLE
ciscosmb and remove secrets problems

### ISSUE THREAD

**Issue by zxyz** [ytti/oxidized#678]
The string for removing secrets in **ciscosmb.rb** seems to be outdated. It says:

```
cfg.gsub! /username (\S+) privilege (\d+) (\S+).*/, '<secret hidden>'
```

but the positions in the config (I'm using the latest version 1.4.7.6 for the SMB switches) changed:

> username mary password encrypted 304d600546879683f824bffgdfa61j10018210ce privilege 15

I tried to adapt the string (one of my many trial and error versions: `cfg.gsub! /username (\S+) passsword encrypted (\S+) privilege (\d+).*/, '<secret hidden>'`) but I failed all the time. My regex abilities really are not good, but that bad...? So I took another approach.

The remove secrets for the snmp-server community works on my smb switches (`snmp-server community <configuration removed>`) but if I edit **ciscosmb.rb** and change

```
cfg.gsub! /^(snmp-server community).*/, '\\1 <configuration removed>'
```
to
```
cfg.gsub! /^(snmp-server community).*/, '\\1 <configuration removed test>'
```

stop oxidized, delete all the saved configs in oxidized and restart oxidized it still says  `<configuration removed>`.  In the web interface under Model it says "CiscoSMB", so the device seems to be recognized correctly.

Where is the Truck in front of me which I'm not seeing?

**Comment by davama** [comment]
This is how we have it 

>     cfg.gsub! /^(username (\S+) password (\S+)) (\S+).*/, '\\1 <redacted>'

and this is the results

> username manager password encrypted \<redacted\>

**Comment by zxyz** [comment]
@davama it works, thank you so much!
But I still don't understand why my "configuration removed test" didn't work.

Anyway, I also got strings of the following kind in my switch config:

> snmp-server host <IP address> traps version 2c <password>

where the password is as sensitive as in the `snmp-server community` config ans also should be removed. Therefore I suggest adding something like

> cfg.gsub! /^(snmp-server host).*/, '\\1 <configuration removed>'

to the **ciscosmb.rb** file.

**Comment by davama** [comment]
@zxyz you're welcome

>  But I still don't understand why my "configuration removed test" didn't work.

 i dont know man. im no ruby masta


` cfg.gsub! /^(snmp-server community).*/, '\\1 <redacted>'`


`snmp-server community <redacted>`

all trial and error and all knowing google

**Comment by ytti** [comment]
You can experiment in REPL shell, like ```irb``` or ```pry```. May give some insight.

```
irb
string = "something something\nyet more something"
string.gsub /regexp/, 'replacement'
```

And observe output.

**Comment by wk** [comment]
@davama I notice that in the current `ciscosmb.rb` model, the old formulation `/username (\S+) privilege (\d+) (\S+).*/, '<secret hidden>'` is used, and not the `/^(username (\S+) password (\S+)) (\S+).*/, '\\1 <redacted>'` one you propose. 

Does yours catch both cases, or only more recent versions? In the former case, it would be great if you could submit a PR replacing it, in the latter case, adding it in next to the existing one so that both cases are addressed.

Closing this ticket, as it seems the question of the original author has been addressed.
