### ISSUE TITLE
Removing machines from router.db can lead to oxidized dying

### ISSUE THREAD

**Issue by RichiH** [ytti/oxidized#68]
If you remove a machine from router.db, and then click the reload link, oxidized can die with an error that it's unable to find said machine.

    oxidized@noc1  ~ % unable to find '$machine'
    == Sinatra has ended his set (crowd applauds)                                   
    == Sinatra has ended his set (crowd applauds)                                   
                                                                                    
    [1]  + 39551 done       oxidized

**Comment by RichiH** [comment]
PS: I can not always reproduce this, but it has happenend several times, now.

**Comment by ytti** [comment]
Do you have crashfile for that? Anything in syslog.

It would be interesting to see our callstack for find_node_index which raised that.

Good candidate for this behavior is our retry code. Scenario:

1. oxidized is running
2. thread is working on $machine
3. $machine is removed
4. $machine fails to fetch config
5. we retry $machine
     => unable to find $machine, raise error


We do it here:
worker.rb:

        if node.retry < CFG.retries
          node.retry += 1
          msg += ", retry attempt #{node.retry}"
          @nodes.next node.name                                    ## this would raise if node.name does not exist                        
        else

Fix might be

def process job
    ......
rescue Oxidized::NodeNotFound => error
   Log.warn "#{node.name} was removed while collecting"
end


But I'd need reliable way to test it.
