### ISSUE TITLE
Running git oxidized vs. gem

### ISSUE THREAD

**Issue by jlixfeld** [ytti/oxidized#682]
Hey there,

I'd like to run the git version of oxidized to test some model support that isn't yet pushed to the gem version.

Is there an install guide for running the git version?  I can't imagine it's as simple as just running git-dir/oxidized/bin/oxidized, is it? :)

Also would be helpful to be able to use the git version of oxidized-web too, if there's some instruction on how to do that in addition.

Thanks!

**Comment by ytti** [comment]
```
git clone
rake install
```

MIGHT do it. Or
```
git clone
rake build
sudo
umask 022
gem install pkg/*.gem
```

**Comment by ytti** [comment]
If it's jsut model you want, you could ```curl``` the model into ~/.config/oxidized/model/ directory.

**Comment by jlixfeld** [comment]
Thanks ytti!

**Comment by davama** [comment]
Can we please have this in the README.md ?
Might be helpful

**Comment by ytti** [comment]
Pull request accepted :)

**Comment by davama** [comment]
:D  #683
