### ISSUE TITLE
Deadlock install on Centos 7

### ISSUE THREAD

**Issue by pouyoux** [ytti/oxidized#684]
Hello,

I can't install oxidized on Centos 7 :
- if I use ruby packages provided by the distro (2.0.0) : oxidized complains that slop package is too recent (v4 vs v3)
- if I use ruby packages 1.9.3 : it's fine for slop but net-ssh v3 can't be installed because ruby version is too old (needs ruby 2.0 at least)

so ruby v1.9.3 is too old, v2.0.0 is too recent and there is no ruby version between those 2, what can I do ?

**Comment by ytti** [comment]
How did you install oxidized? We're using slop3.5, not slop4. Ruby 2.0 and newer rubies all are supported and should work. 
If you install oxidized via gem it should not install slop4, but slop3.5.

**Comment by pouyoux** [comment]
I did a fresh install for putting you screenshots and it's working fine thought I don't get why.

# /usr/local/rvm/src/rubygems-2.6.10/bin/gem install oxidized
Fetching: slop-3.6.0.gem (100%)
Successfully installed slop-3.6.0
Fetching: net-ssh-3.0.2.gem (100%)
Successfully installed net-ssh-3.0.2
Successfully installed oxidized-0.19.0
Parsing documentation for slop-3.6.0
Installing ri documentation for slop-3.6.0
Parsing documentation for net-ssh-3.0.2
Installing ri documentation for net-ssh-3.0.2
Parsing documentation for oxidized-0.19.0
3 gems installed

obviously slop has been upgraded to 3.6.0 ;)

thanks for your help
