### ISSUE TITLE
could not settle on host_key algorithm

### ISSUE THREAD

**Issue by jlixfeld** [ytti/oxidized#686]
Hey there,

I've got a device that requires ssh-dss that oxidized can't seem to connect to.  I've modified my ssh_config to add +ssh-dss, but now I'm getting an error from oxidized:

```
W, [2017-02-02T16:43:15.050010 #68653]  WARN -- : 10.219.36.2 raised Net::SSH::Exception (rescued RuntimeError) with msg "could not settle on host_key algorithm"
W, [2017-02-02T16:43:16.043036 #68653]  WARN -- : 10.219.36.2 status no_connection, retry attempt 1
```

I've done some digging, and Net::SSH had an issue where it couldn't parse '+' within ssh_config (https://github.com/net-ssh/net-ssh/issues/314) and it's supposedly fixed in 4.0.1.  I'm not ruby savvy at all, but from what I've been able to cobble together, I have 4.0.1 installed, but since there are multiple versions, I'm not sure if I'm actually using the right one, or if this is the same issue at all, or something completely different.

```
root@librenms:/home/oxidized/.config/oxidized/logs# gem list net-ssh

*** LOCAL GEMS ***

net-ssh (4.0.1, 3.1.1, 3.0.2)
root@librenms:/home/oxidized/.config/oxidized/logs#
```

Can anyone possibly lend a clue?

**Comment by ytti** [comment]
Even if you install newer, you'll actually use what ever net-ssh version given software wants to use, i.e. you can have many gems and each gem could mandate specific version of net-ssh, and that's fine. Unlike say dpkg or rpm, everything does not need to converge on single version.

In oxidized.gemspec we specify which net-ssh version we want, we want 3.x.x but 3.0.2 or newer. Net::SSH 4 is very new, like month old or so, I've not tested it.

You're welcome to clone the gitrepo, change the gemspec to 4.0, build and install the package, and see how it goes.

**Comment by laf** [comment]
PR #895 may help with this. @jlixfeld Can you try that PR and see if it works for you?

**Comment by jsynack** [comment]
The oxidized gemspec is net-ssh 4.1.0 as of 6ed0d936342d57b0fc21b8357075b9ffa0837156 / Jul 2 .  

This should be safe to close? @jlixfeld  - Do you still have problems with the ssh-dss device?
