### ISSUE TITLE
Can't connect to Fortigate

### ISSUE THREAD

**Issue by LemonLight** [ytti/oxidized#688]
Hi, 

I have go a problem with a Fortigate 60E which is in 5.4. Oxidized can't connect to my Fortigate whereas I can connect with ssh on the server.

Here there I my config file :

[config.txt](https://github.com/ytti/oxidized/files/750689/config.txt)
[latest.txt](https://github.com/ytti/oxidized/files/750688/latest.txt)
[router.txt](https://github.com/ytti/oxidized/files/750690/router.txt)

Any idea ?

Thank you !

**Comment by ytti** [comment]
Can you do:
```
input:
  debug: true
````

It looks like it may stop at this command, based on your ```lastest.txt``` https://github.com/ytti/oxidized/blob/master/lib/oxidized/model/fortios.rb#L37

If you run that manually in CLI, does it work?

**Comment by LemonLight** [comment]
Debug is already on true.

Yes the command "show" works perfectly in CLI.
Also, when I open the file in logs/my.host.net, I can see a part of the config (there is 1797 lines) and it ends with a "--More--", but the config is incomplete.

**Comment by ytti** [comment]
Can you check the last lines with editor which shows special characters, like maybe vim? It seems that maybe it didn't match on the More prompt at all.

**Comment by LemonLight** [comment]
On the last line I have got a "--More--". 
On other lines where there is "--More--" I have got a "--More-- ^M         ^M"

**Comment by ytti** [comment]
Our expect line is ```expect /^--More--\s$/ do |data, re|``` so it looks like there should be exactly 1 space after the last dash in More. Can you change the ```\s``` to ```\s?``` and retry?

**Comment by LemonLight** [comment]
So I changed `expect /^--More--\s$/ do |data, re|` by `expect /^--More--\s?$/ do |data, re|` but it doesn't work

**Comment by ytti** [comment]
What about just ```--More--``` to see if it's prompt issue at all.

**Comment by LemonLight** [comment]
You want me I put this `expect --More--$/ do |data, re|`

**Comment by ytti** [comment]
Can you arrange sanitised access to affected device from 91.198.120.1 and email me auth details at ```saku@ytti.fi```?

**Comment by LemonLight** [comment]
I send you an email

**Comment by ytti** [comment]
Your config takes longer than timeout, increase timeout and it'll finish.

**Comment by LemonLight** [comment]
It's correct, it works now (I put 60 sec timeout) ! Thanks a lot ! 👍
