### ISSUE TITLE
Issue with backuping Cisco 3750-X

### ISSUE THREAD

**Issue by Tito-aix** [ytti/oxidized#689]
Hello,

I'm new to this product and as a first test, I can't backup my configuration with a Cisco 3750-X.

The device pings and DNS is also OK.

Could you please check my configuration files and logs from the console ?

I stay available for any question.

Regards,

Thierry

[Config file.txt](https://github.com/ytti/oxidized/files/750768/Config.file.txt)
[Crash log.txt](https://github.com/ytti/oxidized/files/750769/Crash.log.txt)
[Debug.txt](https://github.com/ytti/oxidized/files/750920/Debug.txt)

**Comment by ytti** [comment]
In your config file change ```vars:``` to ```vars: {}```

**Comment by Tito-aix** [comment]
Thanks for the quick response, it works well now !

By the way, do you please have some configuration to implement web interface and versioning ?

**Comment by ytti** [comment]
Change output to ```git``` for versioning. And install ```oxidized-web``` for web interface.

**Comment by Tito-aix** [comment]
Thanks for your availability, let's enjoy !
