### ISSUE TITLE
Undefined method `has_key?' for nil:NilClass Dell Powerconnect

### ISSUE THREAD

**Issue by dipenshah90** [ytti/oxidized#691]
I am testing various backup configuration tools and really like what oxidized has to offer. I really appreciate the awesome work you guys have done here.

I am facing an error: "undefined method `has_key?' for nil:NilClass" after I resolved "no usable device error."

Config file:
interval: 600
use_syslog: false
debug: false
threads: 30
timeout: 20
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
pid: /home/oxidized/.config/oxidized/pid
vars:
 remove_secret: true
groups:
rest: 127.0.0.1:8000/oxidized
pid: /home/oxidized/.config/oxidized/pid
input:
 default: ssh, telnet
 debug: false
 ssh:
    secure: false
output:
 default: file
 file: 
 directory: /home/oxidized/deviceconfigs
source:
 default: csv
 csv:
    file: /home/oxidized/.config/oxidized/router.db
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
      username: 2
      password: 3
model_map:
 cisco: ios
 juniper: junos
 dell: powerconnect

[config.txt](https://github.com/ytti/oxidized/files/751583/config.txt)

router.db
192.168.x.x:powerconnect:admin:password

error message:
[oxidized@localhost ~]$ oxidized
I, [2017-02-03T16:04:35.783499 #6750]  INFO -- : Oxidized starting, running as pid 6750
I, [2017-02-03T16:04:35.784026 #6750]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
F, [2017-02-03T16:04:35.784389 #6750] FATAL -- : Oxidized crashed, crashfile written in /home/oxidized/.config/oxidized/crash
undefined method `has_key?' for nil:NilClass
/usr/local/share/gems/gems/oxidized-0.19.0/lib/oxidized/node.rb:195:in `resolve_key': undefined method `has_key?' for nil:NilClass (NoMethodError)
	from /usr/local/share/gems/gems/oxidized-0.19.0/lib/oxidized/node.rb:139:in `resolve_input'
	from /usr/local/share/gems/gems/oxidized-0.19.0/lib/oxidized/node.rb:17:in `initialize'
	from /usr/local/share/gems/gems/oxidized-0.19.0/lib/oxidized/nodes.rb:19:in `new'
	from /usr/local/share/gems/gems/oxidized-0.19.0/lib/oxidized/nodes.rb:19:in `block (2 levels) in load'
	from /usr/local/share/gems/gems/oxidized-0.19.0/lib/oxidized/nodes.rb:15:in `each'
	from /usr/local/share/gems/gems/oxidized-0.19.0/lib/oxidized/nodes.rb:15:in `block in load'
	from /usr/local/share/gems/gems/oxidized-0.19.0/lib/oxidized/nodes.rb:126:in `synchronize'
	from /usr/local/share/gems/gems/oxidized-0.19.0/lib/oxidized/nodes.rb:126:in `with_lock'
	from /usr/local/share/gems/gems/oxidized-0.19.0/lib/oxidized/nodes.rb:10:in `load'
	from /usr/local/share/gems/gems/oxidized-0.19.0/lib/oxidized/nodes.rb:121:in `initialize'
	from /usr/local/share/gems/gems/oxidized-0.19.0/lib/oxidized/core.rb:14:in `new'
	from /usr/local/share/gems/gems/oxidized-0.19.0/lib/oxidized/core.rb:14:in `initialize'
	from /usr/local/share/gems/gems/oxidized-0.19.0/lib/oxidized/core.rb:4:in `new'
	from /usr/local/share/gems/gems/oxidized-0.19.0/lib/oxidized/core.rb:4:in `new'
	from /usr/local/share/gems/gems/oxidized-0.19.0/lib/oxidized/cli.rb:12:in `run'
	from /usr/local/share/gems/gems/oxidized-0.19.0/bin/oxidized:9:in `<top (required)>'
	from /usr/local/bin/oxidized:23:in `load'
	from /usr/local/bin/oxidized:23:in `<main>'

**Comment by ytti** [comment]
Change ```vars:``` to ```vars: {}```

**Comment by dipenshah90** [comment]
It did work. But, got a new error when I click on config part of Web UI. I am using a dell powerconnect switch. 

Error: 

User Name: not matching configured prompt (?-mix:^([\w\s.@-]+[#>]\s?)$)"
W, [2017-02-06T09:39:13.638745 #17110]  WARN -- : 192.168.6.244 raised Oxidized::PromptUndetect with msg "unable to detect prompt: (?-mix:^([\w\s.@-]+[#>]\s?)$)"

Thanks :)

**Comment by ytti** [comment]
You are using ```poweconnect``` model? Can you do:
```
input:
  debug: true
```

And provide the file

**Comment by dipenshah90** [comment]
Yes powerconnect.

You mean this?

* Listening on tcp://127.0.0.1:8888
2017-02-06 11:04:50 - TypeError - no implicit conversion of nil into String:
    /usr/local/share/gems/gems/oxidized-0.19.0/lib/oxidized/output/file.rb:42:in `read'
    /usr/local/share/gems/gems/oxidized-0.19.0/lib/oxidized/output/file.rb:42:in `fetch'
    /usr/local/share/gems/gems/oxidized-0.19.0/lib/oxidized/nodes.rb:61:in `block in fetch'
    /usr/local/share/gems/gems/oxidized-0.19.0/lib/oxidized/nodes.rb:174:in `block in yield_node_output'
    /usr/local/share/gems/gems/oxidized-0.19.0/lib/oxidized/nodes.rb:126:in `synchronize'
    /usr/local/share/gems/gems/oxidized-0.19.0/lib/oxidized/nodes.rb:126:in `with_lock'
    /usr/local/share/gems/gems/oxidized-0.19.0/lib/oxidized/nodes.rb:170:in `yield_node_output'
    /usr/local/share/gems/gems/oxidized-0.19.0/lib/oxidized/nodes.rb:60:in `fetch'
    /usr/local/share/gems/gems/oxidized-web-0.8.0/lib/oxidized/web/webapp.rb:80:in `block in <class:WebApp>'
    /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `call'
    /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `block in compile!'
    /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `[]'
    /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
    /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:994:in `route_eval'
    /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
    /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1015:in `block in process_route'
    /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `catch'
    /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `process_route'
    /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:973:in `block in route!'
    /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `each'
    /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `route!'
    /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1085:in `block in dispatch!'
    /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
    /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
    /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
    /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1082:in `dispatch!'
    /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `block in call!'
    /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
    /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
    /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
    /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `call!'
    /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:895:in `call'
    /usr/local/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
    /usr/local/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
    /usr/local/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
    /usr/local/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
    /usr/local/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
    /usr/local/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
    /usr/local/share/gems/gems/rack-1.6.5/lib/rack/nulllogger.rb:9:in `call'
    /usr/local/share/gems/gems/rack-1.6.5/lib/rack/head.rb:13:in `call'
    /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/show_exceptions.rb:25:in `call'
    /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:182:in `call'
    /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:2013:in `call'
    /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `block in call'
    /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1787:in `synchronize'
    /usr/local/share/gems/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `call'
    /usr/local/share/gems/gems/rack-1.6.5/lib/rack/urlmap.rb:66:in `block in call'
    /usr/local/share/gems/gems/rack-1.6.5/lib/rack/urlmap.rb:50:in `each'
    /usr/local/share/gems/gems/rack-1.6.5/lib/rack/urlmap.rb:50:in `call'
    /usr/local/share/gems/gems/rack-1.6.5/lib/rack/builder.rb:153:in `call'
    /usr/local/share/gems/gems/puma-2.16.0/lib/puma/server.rb:557:in `handle_request'
    /usr/local/share/gems/gems/puma-2.16.0/lib/puma/server.rb:404:in `process_client'
    /usr/local/share/gems/gems/puma-2.16.0/lib/puma/server.rb:270:in `block in run'
    /usr/local/share/gems/gems/puma-2.16.0/lib/puma/thread_pool.rb:106:in `call'
    /usr/local/share/gems/gems/puma-2.16.0/lib/puma/thread_pool.rb:106:in `block in spawn_thread'
W, [2017-02-06T11:05:08.355112 #4669]  WARN -- : 192.168.6.244 raised Oxidized::PromptUndetect with msg "********

User Name: not matching configured prompt (?-mix:^([\w\s.@-]+[#>]\s?)$)"
W, [2017-02-06T11:05:30.549168 #4669]  WARN -- : 192.168.6.244 raised Oxidized::PromptUndetect with msg "unable to detect prompt: (?-mix:^([\w\s.@-]+[#>]\s?)$)"
W, [2017-02-06T11:05:30.587483 #4669]  WARN -- : 192.168.6.244 status no_connection, retry attempt 1

Please let me know if there is any other file you're looking for?

**Comment by ytti** [comment]
Are you sure your password/login is correct, it seems like it's expecting prompt, but it's getting username prompt, which would happen if we gave wrong auth details

But what I was asking for was session log, file in device's name.

**Comment by dipenshah90** [comment]
I found this in oxidized/input as a input.rb file. I hope this is the file you're talking about.

module Oxidized
  class PromptUndetect < OxidizedError; end
  class Input
    include Oxidized::Config::Vars

    RescueFail = {
      :debug => [
        Errno::ECONNREFUSED,
      ],
      :warn => [
        IOError,
        PromptUndetect,
        Timeout::Error,
        Errno::ECONNRESET,
        Errno::EHOSTUNREACH,
        Errno::ENETUNREACH,
        Errno::EPIPE,
        Errno::ETIMEDOUT,
      ],
    }
  end
end

Also, it is weird that oxidized was working fine for me at least the Web UI (first page). But, once I rebooted my vm it throws an error:

Error loading config: (<unknown>): did not find expected key while parsing a block mapping at line 2 column 1
/usr/local/share/gems/gems/oxidized-0.19.0/lib/oxidized/config.rb:50:in `rescue in load': Error loading config: (<unknown>): did not find expected key while parsing a block mapping at line 2 column 1 (Oxidized::InvalidConfig)
    from /usr/local/share/gems/gems/oxidized-0.19.0/lib/oxidized/config.rb:47:in `load'
    from /usr/local/share/gems/gems/oxidized-0.19.0/lib/oxidized/cli.rb:24:in `initialize'
    from /usr/local/share/gems/gems/oxidized-0.19.0/bin/oxidized:9:in `new'
    from /usr/local/share/gems/gems/oxidized-0.19.0/bin/oxidized:9:in `<top (required)>'
    from /usr/local/bin/oxidized:23:in `load'
    from /usr/local/bin/oxidized:23:in `<main>'

I am sure I might be doing something wrong in the setup, to end up with so many errors lol. 

Do you suggest a fresh start?

**Comment by ytti** [comment]
I am talking about:
```
input:
  debug: true
```

and check what file the device in question produces

**Comment by dipenshah90** [comment]
Hi Ytti,

We got the desired output. I was running in it in wrong directory all the time. You can close the ticket. I appreciate your prompt respons
![oxi](https://cloud.githubusercontent.com/assets/7194155/22700334/4d14646e-ed28-11e6-9ff7-f9d64d44b7ce.png)
e.

Thanks!
