### ISSUE TITLE
Missing secret matching on asa model

### ISSUE THREAD

**Issue by erlendrosok** [ytti/oxidized#696]
There's a few secrets I noticed are not getting properly removed on the asa model.

```
snmp-server host (\S+) (.*)
snmp-server community (\S+)
ikev1 pre-shared-key (\S+)             #Only added for ikev2
key (.*)                                            #Under aaa-server configuration
passwd (\S+) encrypted

```
Best Regards

Erlend Røsok

**Comment by wk** [comment]
Some of these appear to have been added in #742. If you feel any filters are still missing, feel free to submit a PR for the necessary changes.
