### ISSUE TITLE
output per vendor

### ISSUE THREAD

**Issue by networkpadawan** [ytti/oxidized#705]
Is it possible to output the configs per vendor like /configs/junos, /configs/ios, /configs/arista? do I need to patch the code or is there a config flag to change? thanks!

**Comment by ytti** [comment]
If you make vendor a group, then you should get either own repo per group or own directory per group.

**Comment by networkpadawan** [comment]
sure enough, it works! thanks, please close the issue.

**Comment by ytti** [comment]
Thanks man. Feel free to close issues  you create.
