### ISSUE TITLE
new device type

### ISSUE THREAD

**Issue by networkpadawan** [ytti/oxidized#707]
two questions:

is it possible to add a character after "exit" command?
The juniper ex2500 asks "Sure you want to close this session (y/n) ?:" it is very much like the ios syntasx (show running-config) but it hangs on the end session

since ill be adding a new "vendor" can i just add the file to the models folder or do I need to change something on the engine?

**Comment by ytti** [comment]
We have many models which ask random questions. I think it's OK to add in junos.rb. You can copy the model to ~/config/oxidized/model/junos.rb and edit it until it works. Pull request would be accepted.

**Comment by networkpadawan** [comment]
Sorry, noob with ruby, do you know the closest one that does show running-config, expects --More-- untill goes back to "#" prompt" these devices are quite old and I can only extend the terminal to 300 lines, if I put zero the output that comes out is garbage. I can try and error, but even with debug on I only check the command being executed and timing out, my bet is that the expect is not being run, but Im not certain. Of course i will push as soon as it is stable/working.

**Comment by networkpadawan** [comment]
I had this working with expect/bash, can someone help me convert this to ruby/oxidized model?

#!/usr/bin/expect -f

# Set variables
set username [lindex $argv 0]
set password [lindex $argv 1]
set hostname [lindex $argv 2]
set enablepassword [lindex $argv 3]
set date [exec date +%F]
set folder [exec date +%d-%m-%y]
#log_user 0

# Log results
log_file -noappend ../net_configs/ex2500/$hostname.conf

# Don't check keys
spawn ssh -o StrictHostKeyChecking=no $username\@$hostname

# Connection issues & priv password
expect {
timeout { send_user "\nTimeout Exceeded - Check Host\n"; exit 1 }
eof { send_user "\nSSH Connection To $hostname Failed\n"; exit 1 }
"*assword:" { send "$password\r" }
}

# dump config
expect {
"*#" {
send "show running-config\n"
expect {
   -ex "--More--" { send -- " "; exp_continue }
   -ex "end\r" { send "exit\r" }
}
#expect "*#"
#send "exit"
expect "*?"
send "y"
}
}

**Comment by ytti** [comment]
If you can't produce model, which I'm confident you can with some effort. But if you cannot expand the time, arrange me access to sanitsed device from 91.198.120.1 and email me auth details to saku@ytti.fi and I'll produce it, probably within a week.

**Comment by networkpadawan** [comment]
that´s impossible for me:) nevermind, for this device i´ll do it with bash, this tool helps already for the rest!

**Comment by ytti** [comment]
It's impossible to a) give access to me and b) make it yourself? What was your expectation opening this issue? I cannot access device and you won't build the model, what was the optimal outcome from this issue?

**Comment by networkpadawan** [comment]
it´s impossible to give access to you/anyone. my expectation was A) someone that had a similar device already working but didn´t push the model, B) someone with ruby knowledge that could make the model based on the issue (adapt the expect to the line "Sure you want to close this session (y/n) ?") i did it in bash, but am not proficient in ruby to do something like this, hence the close.
