### ISSUE TITLE
ciscosmb returns Unrecognized command after show running-config

### ISSUE THREAD

**Issue by qw24** [ytti/oxidized#708]
Hi- 
I'm using the  docker container oxidized/oxidized  latest  from 8 days ago.
It is unable grab anything but show version from Cisco SG300-52 switches,  it looks like ssh is successful but it doesn't have the rights to issue the command show running-config.  Other router and switch backups are working, they are using an enable password.

**router.db file is like this:**
nms231h2:ciscosmb:user:password

**The config showing on oxidized web page is this:**
! SW version    1.4.1.3 ( date  29-Mar-2015 time  16:24:16 )
! Boot version    1.3.5.06 ( date  21-Jul-2013 time  15:12:10 )
! HW version    V02
% Unrecognized command

**The ssh log:**
nms231h2>terminal datadump
^Mnms231h2>terminal width 0
^Mnms231h2>terminal len 0
^M% Unrecognized command
nms231h2>show version
^MSW version    1.4.1.3 ( date  29-Mar-2015 time  16:24:16 )
Boot version    1.3.5.06 ( date  21-Jul-2013 time  15:12:10 )
HW version    V02
nms231h2>show running-config
^M% Unrecognized command
nms231h2>exit

**The docker logs:**
D, [2017-02-08T17:08:52.803139 #16] DEBUG -- : node.rb: returning node key 'model' with value 'ciscosmb'
D, [2017-02-08T17:08:52.803245 #16] DEBUG -- : lib/oxidized/node.rb: Loading model "ciscosmb"
D, [2017-02-08T17:08:52.804503 #16] DEBUG -- : lib/oxidized/model/model.rb Added all to the commands list
D, [2017-02-08T17:08:52.804558 #16] DEBUG -- : lib/oxidized/model/model.rb Added secret to the commands list
D, [2017-02-08T17:08:52.804592 #16] DEBUG -- : lib/oxidized/model/model.rb Added show version to the commands list
D, [2017-02-08T17:08:52.804627 #16] DEBUG -- : lib/oxidized/model/model.rb Added show running-config to the commands list

.......
I, [2017-02-08T17:08:52.805211 #16]  INFO -- : lib/oxidized/nodes.rb: Loaded 1 nodes
D, [2017-02-08T17:08:53.197246 #16] DEBUG -- : lib/oxidized/core.rb: Starting the worker...
Puma 2.16.0 starting...
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://0.0.0.0:8888
D, [2017-02-08T17:08:53.197322 #16] DEBUG -- : lib/oxidized/worker.rb: Jobs 0, Want: 1
D, [2017-02-08T17:08:53.198435 #16] DEBUG -- : lib/oxidized/worker.rb: Added nms231h2 to the job queue
D, [2017-02-08T17:08:53.198487 #16] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2017-02-08T17:08:53.198593 #16] DEBUG -- : lib/oxidized/job.rb: Starting fetching process for nms231h2 at 2017-02-08 17:08:53 UTC
D, [2017-02-08T17:08:53.198864 #16] DEBUG -- : lib/oxidized/input/ssh.rb: Connecting to nms231h2
D, [2017-02-08T17:08:53.814303 #16] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^User ?[nN]ame:/, /^\r?([\w.@()-]+[#>]\s?)$/] at nms231h2
D, [2017-02-08T17:08:54.198646 #16] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2017-02-08T17:08:54.620768 #16] DEBUG -- : lib/oxidized/input/cli.rb: Running post_login commands at nms231h2
D, [2017-02-08T17:08:54.620872 #16] DEBUG -- : lib/oxidized/input/cli.rb: Running post_login command: "terminal datadump", block: nil at nms231h2
D, [2017-02-08T17:08:54.620915 #16] DEBUG -- : lib/oxidized/input/ssh.rb terminal datadump @ nms231h2 with expect: /^\r?([\w.@()-]+[#>]\s?)$/
D, [2017-02-08T17:08:54.621126 #16] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^\r?([\w.@()-]+[#>]\s?)$/] at nms231h2
D, [2017-02-08T17:08:55.048369 #16] DEBUG -- : lib/oxidized/input/cli.rb: Running post_login command: "terminal width 0", block: nil at nms231h2
D, [2017-02-08T17:08:55.048513 #16] DEBUG -- : lib/oxidized/input/ssh.rb terminal width 0 @ nms231h2 with expect: /^\r?([\w.@()-]+[#>]\s?)$/
D, [2017-02-08T17:08:55.048682 #16] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^\r?([\w.@()-]+[#>]\s?)$/] at nms231h2
D, [2017-02-08T17:08:55.198902 #16] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2017-02-08T17:08:55.473936 #16] DEBUG -- : lib/oxidized/input/cli.rb: Running post_login command: "terminal len 0", block: nil at nms231h2
D, [2017-02-08T17:08:55.474030 #16] DEBUG -- : lib/oxidized/input/ssh.rb terminal len 0 @ nms231h2 with expect: /^\r?([\w.@()-]+[#>]\s?)$/
D, [2017-02-08T17:08:55.474237 #16] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^\r?([\w.@()-]+[#>]\s?)$/] at nms231h2
D, [2017-02-08T17:08:55.898583 #16] DEBUG -- : lib/oxidized/model/model.rb Collecting commands' outputs
D, [2017-02-08T17:08:55.898691 #16] DEBUG -- : lib/oxidized/model/model.rb Executing show version
D, [2017-02-08T17:08:55.898737 #16] DEBUG -- : lib/oxidized/input/ssh.rb show version @ nms231h2 with expect: /^\r?([\w.@()-]+[#>]\s?)$/
D, [2017-02-08T17:08:55.898910 #16] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^\r?([\w.@()-]+[#>]\s?)$/] at nms231h2
D, [2017-02-08T17:08:56.199136 #16] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2017-02-08T17:08:56.327082 #16] DEBUG -- : lib/oxidized/model/model.rb Executing show running-config
D, [2017-02-08T17:08:56.327189 #16] DEBUG -- : lib/oxidized/input/ssh.rb show running-config @ nms231h2 with expect: /^\r?([\w.@()-]+[#>]\s?)$/
D, [2017-02-08T17:08:56.327358 #16] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^\r?([\w.@()-]+[#>]\s?)$/] at nms231h2
D, [2017-02-08T17:08:56.758621 #16] DEBUG -- : lib/oxidized/input/cli.rb Running pre_logout commands at nms231h2
D, [2017-02-08T17:08:56.758724 #16] DEBUG -- : lib/oxidized/input/ssh.rb exit @ nms231h2 with expect: nil
D, [2017-02-08T17:08:56.758883 #16] DEBUG -- : lib/oxidized/input/ssh.rb exit @ nms231h2 with expect: nil
D, [2017-02-08T17:08:57.199417 #16] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2017-02-08T17:08:58.199624 #16] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2017-02-08T17:08:59.199830 #16] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2017-02-08T17:09:00.200044 #16] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2017-02-08T17:09:01.200318 #16] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
D, [2017-02-08T17:09:01.756662 #16] DEBUG -- : lib/oxidized/node.rb: Oxidized::SSH ran for nms231h2 successfully

 Thanks

**Comment by ytti** [comment]
Maybe  you need to enable?

**Comment by qw24** [comment]
I tried making a new model and it worked but only over telnet,  it looks like it's timing out over ssh
Is there something I'm missing?
Not being a coder any help with a model that will work enable and with ssh would be appreciated.  
Thanks

New model
 cfg :telnet, :ssh do
    username /^User ?[nN]ame:/
    password /^\r?Password:$/
 post_login 'terminal datadump' # Disable pager
    post_login 'terminal width 0'
    #preferred way to handle additional passwords
    if vars :enable
      post_login do
        send "enable\n"
        cmd vars(:enable)
      end
    end


ssh log 
nms231h2>terminal datadump
^Mnms231h2>terminal width 0
^Mnms231h2>enable
^M***********
^MPassword:nms231h2#

**Comment by qw24** [comment]
There is this issue Model 'ciscosmb' - enable not working #231  that was closed.
Should i do a request to add enable support? or is there some other way that it is supposed to work?
Thanks

**Comment by ytti** [comment]
If you can't modify the model to make it work with enable, please provide me access to sanitised device and I'll modify the model.

**Comment by qw24** [comment]
I did get enable and backups to work with a new model, but only over telnet not ssh.
Is there any other debugging that can be done to help with this?

in the docker logs it seems to be failing here
D, [2017-02-08T20:43:56.783006 #15] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^\r?([\w.@()-]+[#>]\s?)$/] at nms231h2
W, [2017-02-08T20:44:16.783498 #15]  WARN -- : 10.128.0.72 raised Timeout::Error with msg "execution expired"

Attached are the full docker logs for ssh and telnet  and the new model ciscosmbnew.rb 
[docker-log.txt](https://github.com/ytti/oxidized/files/767509/docker-log.txt)
[ciscosmbnew.txt](https://github.com/ytti/oxidized/files/767510/ciscosmbnew.txt)

Thanks

**Comment by ytti** [comment]
Perhaps you should run:
```
input:
  debug: true
``` 

And see what terminal output is produced as ```devicename-ssh.log```, the model seems to be expecting to see prompt regexp, which seems not to happen, so what are the last lines it sees?

**Comment by qw24** [comment]
Backup over ssh is working now-  Thanks for your help

**Comment by jirib** [comment]
I had similar issue and it was too low user level issue on sg300-20. Giving to a user 'Read/Write Management Access' make it working.
