### ISSUE TITLE
multiple input in a single module

### ISSUE THREAD

**Issue by enryIT** [ytti/oxidized#709]
Hello,

is it possible to use multiple input sequentially in a single module?
I mean, we have a network device that doesn't support displaying its configuration on the cli, BUT it does support saving the config via telnet and it have an always-on ftp server on it.

The idea is to first issue the "save configuration" command via telnet and then retrieve the file via ftp.
It should be possible and I tried tinkering with the modules and input type but i failed.

Can someone help me on this?
Thanks.

**Comment by ytti** [comment]
This is currently not possible. It has been brought up previously too. 

I think it's important use case, and we should support it, but it's not a trivial change.
