### ISSUE TITLE
Test and release 0.3.0

### ISSUE THREAD

**Issue by ytti** [ytti/oxidized#71]
I'm lazy bum, so I'll give it to nope :)

**Comment by sts** [comment]
Any updates?

**Comment by ytti** [comment]
The latest point release is actually 0.3.0, needed to upload it, so I can add nopedial as author, so he can push gems. Just looking at docs, changelogs etc now.
Nopedial will probably rollout 0.3.0 today.

**Comment by nopedial** [comment]
I released 0.3.0 today. We actually miss documentation for some features, but that's in the works. I have updated both the git repo and rubygems to the new version.
