### ISSUE TITLE
Database security purpose

### ISSUE THREAD

**Issue by Tito-aix** [ytti/oxidized#713]
Hello,

Is it possible to encrypt router.db file ?

Or maybe to avoid plaintext passwords somehow ?

Thanks !

Regards,

Thierry

**Comment by MajesticFalcon** [comment]
Private key files

On Feb 10, 2017, at 7:01 AM, Tito-aix <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello,

Is it possible to encrypt router.db file ?

Or maybe to avoid plaintext passwords somehow ?

Thanks !

Regards,

Thierry

**Comment by Tito-aix** [comment]
Thank you for the quick response, do you please have some thread on this subject ?

**Comment by MajesticFalcon** [comment]
You can provide an array of private key files, however they will still be unencrypted and in plain text. It would be nice to be able to provide a directory for key files to be read. I will look into implementing this.


________________________________

**Comment by ytti** [comment]
If you specify:
```
source:
  csv:
   gpg: secret
```

We'll try decrypt file with said secret. This is not on any released version, you'd need to use git version.
https://github.com/ytti/oxidized/blob/master/lib/oxidized/source/csv.rb#L24-L29
