### ISSUE TITLE
Add user that a change to exec hook

### ISSUE THREAD

**Issue by jasonyates** [ytti/oxidized#714]
The exec hook includes the $OX_NODE_FROM which appears to be the IP address that made a configuration change when triggered from the Syslog server. But I can't find a way to include the username that made the change in to an exec hook.

**Comment by ytti** [comment]
Do these help: https://github.com/ytti/oxidized/blob/master/lib/oxidized/hook/exec.rb#L69-L72

**Comment by laf** [comment]
@jasonyates Have you looked at what ytti has linked to and does this help you?

**Comment by danilopopeye** [comment]
@jasonyates ping
