### ISSUE TITLE
Backup schedule

### ISSUE THREAD

**Issue by sebisme** [ytti/oxidized#717]
Hello,

Is there a way to schedule the backup so that it will occur at a defined time. I assume there is a way to handle the interval, through configuration, but how can i ask a specified backup job to happend i.e. at 8:30 pm and so on ?

**Comment by ytti** [comment]
You could use the API ```/next``` to request some device is moved to head of the queue at 0830pm

**Comment by sebisme** [comment]
I could, indeed. But for some reason, i really have to define a backup schedule within the config for some devices. (i.e. to prevent network overload, since i trigger some larger backups than the "show configuration" ones on Checkpoint FW, through oxidized).

So, although i'm a complete ruby noob, i tried to implement it that way :

- In my config, i added an `exectime` param, in the format 'HH:MM:SS'
- In the class `Config` (file `lib/config.rb`) i added the line `asetus.default.exectime = false` into the `self.load` method
- In the `Node` class (file `lib/node.rb`) :
  - in the `initialize` method, i added the line `@exectime = resolve_exectime opt`
  - i added the private method `resolve_exectime` as follows :
  ```
  def resolve_exectime opt
    exectime = resolve_key :exectime, opt
    now = Time.now
    if !exectime
      !!exectime
    else
      # Ruby noob ! Is there a way towrite those 2 next lines a prettier way ?
      ext = Time.at(exectime) # We recieve only hh:mm:ss
      ets = Time.new(now.year, now.month, now.day, ext.hour, ext.min, ext.sec)
    end
  end
  ```
  - i added the method `in_time?` as follows :
  ```
  def in_time?(exectime = nil)
    exectime = exectime.nil? ? @exectime : exectime
    if exectime
      now = Time.now
      timespan = (now >= exectime) ? now - exectime : exectime - now
      timespan.round <= (60 * 5)
    else
      true
    end
  end
  ```
  - i added the method `exectime?` as follows :
  ```
  def exectime?
    !!@exectime
  end
  ```
- And finally, in the `Worker` class (file lib/worker.rb) i called the `node.in_time?` method from the `work` method as follows (in context) :
  ```
  node = @nodes.get
  next unless node.in_time?
  node.running? ? next : node.running = true
  ```

It works fine for me now, but to go a bit further, it could be interesting to override that exectime while calling the API `/next`...
To do that, i suppose i have to modify the nodes.next method ? right ?

Also, do you want me to submit a PR with those modifications ? I'll be glad to do so, but since i'm not a good ruby dev, maybe those modifications aren't relevant ?

**Comment by ytti** [comment]
I think we need to give it bit time, to see if there are more demand for feature like this. Anyhow, I think it's interesting approach and I'm happy if it works for you.

And if you want to pass it in /next, you could indeed modify ```Node#exectime```.
