### ISSUE TITLE
Init Script

### ISSUE THREAD

**Issue by sts** [ytti/oxidized#72]
There is no way to automatically start oxidized and keep it running. What is the proposed way to do this?

**Comment by ytti** [comment]
duplicate of #45

**Comment by sts** [comment]
Is Ubuntu the only supported platform (=> upstart)? Other systems are using SysV init or systemd.

**Comment by ytti** [comment]
Not at all, this is why #45 is still unresolved. We need more complete solution. I'm not sure what it is. One would be just to include various init scripts in the package and let users copy them.
