### ISSUE TITLE
Reload button does not work when deployed outside url root

### ISSUE THREAD

**Issue by Mk-00** [ytti/oxidized#724]
I have deployed Oxidized under domain.tld/oxidized/. It seems to work fine with https after configuring apache reverse proxy but the reload button does not work. From console I found that it is trying to get reload.json from root: GET https://domain.tld/reload.json 404 (Not Found)

**Comment by ytti** [comment]
Correct place for this would be oxidized-web project. I'm sure if you browser the source code you'll figure out how to remedy this.

**Comment by Mk-00** [comment]
Yes, sorry about posting this to wrong place. I managed to fix this in oxidized-web and just made a pull request.
