### ISSUE TITLE
junos is chatty about scale-subscriber numbers

### ISSUE THREAD

**Issue by pozar** [ytti/oxidized#726]
We are an ISP that is constantly updating subscribers attached to the network.  Either from CPEs going up and down or provisioned.  So these numbers change frequently and look like:

-#   scale-subscriber                    728         1000           0    permanent
+#   scale-subscriber                    727         1000           0    permanent

I can add a regex to take these out, but I suspect some folks may want this data.  Ideas?  Perhaps  this can be an option to ignore this line in the config?  Comments welcomed.

**Comment by ytti** [comment]
Is the number updated by the system or by operator via commit? If by system, I think we should have this for everyone, if by operator via commit I believe you should subclass the model and fix it in your local ~/.config/oxidixed/model/junos.rb

**Comment by pozar** [comment]
The number updates when a CPE connects/disconnects.  Has nothing to do with config change.  So this can update a bunch if you have a number of subscribers.  Just shows where you are in your license number.  I have code that takes that number out.  Before and after the code change:
-#   scale-subscriber                    271         1000           0    permanent
+#   scale-subscriber                                1000           0    permanent
I can fork and send this in.

**Comment by ytti** [comment]
Ok, I believe we should remove that information, like replace it with ```<count>``` or such.

**Comment by pozar** [comment]
Will do.  Testing now and will submit.

**Comment by pozar** [comment]
I should say that this problem will only come up if you are pulling down the license count and license keys like we are doing.  So this "issue" is not an issue unless you add the command below.  The ISP I am doing contract work for wants these pulled so we can get an idea of inventory and what limits and keys are on boxes.  

I have forked the code and will be adding a PR assuming this is of interest to others.

Tim
---
    cmd('show chassis hardware') { |cfg| comment cfg }
+   cmd('show system license') { |cfg| comment cfg }
+   cmd('show system license keys') { |cfg| comment cfg }
  
    cfg :telnet do
      username(/^login:/)
---

**Comment by pozar** [comment]
PR at https://github.com/ytti/oxidized/pull/738
