### ISSUE TITLE
tplink random characters missing

### ISSUE THREAD

**Issue by mediumo** [ytti/oxidized#730]
I found a strange problem with my new tplink model.
First I thought there was a problem with linefeeds etc. which i corrected with some gsubs.

But now in "production" i see diffs from run to run. They are comming from random missing characters in the output. I already commented out every gsub in the model...

I thought ok, maybe the cheap tplink switches are skipping them on the "show running-config" command.
But when I manually connect via ssh tee my output and compare multple runs, the output is identical.
that means the character removal is happening somewhere in oxidized.

also already tested with disables ssh channels.

Regards
Olaf

**Comment by MarkStitson** [comment]
I have just found the same issue on a TP-Link TL-SG5428. I also have two TP-Link TL-SG3424v1 and two TP-Link TL-SG3410v1 where I have not yet seen the issue.
I have however seen odd ASCII 0 characters appearing.
I'm too busy to look into the code in detail at the moment, but happy to test if someone has a potential fix.

**Comment by ytti** [comment]
If it's just spurious characters not needed, gsub should do it. ```string.gsub! /\x00/, ""```

**Comment by MarkStitson** [comment]
I did already apply that exact fix, but the problem seems to be related with the ASCII 0 appearing and what superficially looks like a backspace being inserted. I'm currently looking if this appears in the git as well as the file output. I haven't seen it in the file output yet, but it is too early to draw any conclusions.

**Comment by MarkStitson** [comment]
I've now seen this in the file output as well, so that points at the input rather than the output.

**Comment by wk** [comment]
This is an older issue, and Oxidized has seen several new releases since it has been posted. If this is still relevant, please re-attempt this on a more recent (0.24.0) version and update the issue with your findings.

**Comment by spi43984** [comment]
I have the same issue and commented about it in #1608
