### ISSUE TITLE
Docker container crashes with "no implicit conversion of String into Integer"

### ISSUE THREAD

**Issue by lunacite** [ytti/oxidized#733]
```
I, [2017-02-17T22:46:36.793504 #267]  INFO -- : Oxidized starting, running as pid 267
I, [2017-02-17T22:46:36.839898 #267]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
F, [2017-02-17T22:46:36.858136 #267] FATAL -- : Oxidized crashed, crashfile written in /root/.config/oxidized/crash
no implicit conversion of String into Integer
/var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/source/http.rb:44:in `dig': no implicit conversion of String into Integer (TypeError)
	from /var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/source/http.rb:44:in `block (2 levels) in load'
	from /var/lib/gems/2.3.0/gems/asetus-0.3.0/lib/asetus/configstruct.rb:21:in `each'
	from /var/lib/gems/2.3.0/gems/asetus-0.3.0/lib/asetus/configstruct.rb:21:in `each'
	from /var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/source/http.rb:42:in `block in load'
	from /var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/source/http.rb:38:in `each'
	from /var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/source/http.rb:38:in `load'
	from /var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/nodes.rb:15:in `block in load'
	from /var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/nodes.rb:127:in `synchronize'
	from /var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/nodes.rb:127:in `with_lock'
	from /var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/nodes.rb:10:in `load'
	from /var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/nodes.rb:122:in `initialize'
	from /var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/core.rb:14:in `new'
	from /var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/core.rb:14:in `initialize'
	from /var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/core.rb:4:in `new'
	from /var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/core.rb:4:in `new'
	from /var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/cli.rb:12:in `run'
	from /var/lib/gems/2.3.0/gems/oxidized-0.19.0/bin/oxidized:9:in `<top (required)>'
	from /usr/local/bin/oxidized:22:in `load'
	from /usr/local/bin/oxidized:22:in `<main>'
I, [2017-02-17T22:46:38.040129 #270]  INFO -- : Oxidized starting, running as pid 270
```

repeat ad nauseum

Source is http from LibreNMS container.

**Comment by ytti** [comment]
Can you show me your configuration file.

**Comment by lunacite** [comment]
---
username: cisco
password: REDACTED
model: ciscosmb
interval: 3600
use_syslog: false
debug: false
threads: 30
timeout: 300
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 0.0.0.0:8888
vars: {}
groups: {}
pid: "/root/.config/oxidized/pid"
input:
  default: ssh, telnet
  debug: false
  ssh:
    secure: false
output:
  default: file
  file:
    directory: "/root/.config/oxidized/configs"
source:
  default: http
  http:
    url: https://librenms.url/api/v0/oxidized
    insecure: true
    map:
      name: hostname
      model: os
      group: group
    headers:
      X-Auth-Token: 'b3ef1980ad73cd6a7e0fa173dfa472a8'


  csv:
    file: "/root/.config/oxidized/router.db"
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
      username: 2
      password: 3
model_map:
  cisco: ios
  juniper: junos
  ciscosb: ciscosmb

**Comment by ytti** [comment]
Can you tshark/tcpdump what the HTTP query is returning, I suspect it's not returning what you want. Btw. it's not ```insecure: true```, it's ```secure: false```.

**Comment by lunacite** [comment]
There's no point at which I can do a tcpdump, the service fails to start in the container once per second. 

I changed all the instances to secure: false and it has had no effect.

**Comment by ytti** [comment]
You can't keep tcpdump running? Can you run it on the HTTP server end? I'd like to understand if you're making HTTP query or not. 
My best guess right now is that you're making HTTP query, getting bogus data, and we're not handling that correctly.

**Comment by lunacite** [comment]
No requests get made, the oxidized service never starts. The PID just keeps incrementing in the container. 

`I, [2017-03-06T23:22:16.871800 #721]  INFO -- : Oxidized starting, running as pid 721
I, [2017-03-06T23:22:16.911327 #721]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
F, [2017-03-06T23:22:16.928037 #721] FATAL -- : Oxidized crashed, crashfile written in /root/.config/oxidized/crash
no implicit conversion of String into Integer
/var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/source/http.rb:44:in `dig': no implicit conversion of String into Integer (TypeError)
	from /var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/source/http.rb:44:in `block (2 levels) in load'
	from /var/lib/gems/2.3.0/gems/asetus-0.3.0/lib/asetus/configstruct.rb:21:in `each'
	from /var/lib/gems/2.3.0/gems/asetus-0.3.0/lib/asetus/configstruct.rb:21:in `each'
	from /var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/source/http.rb:42:in `block in load'
	from /var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/source/http.rb:38:in `each'
	from /var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/source/http.rb:38:in `load'
	from /var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/nodes.rb:15:in `block in load'
	from /var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/nodes.rb:127:in `synchronize'
	from /var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/nodes.rb:127:in `with_lock'
	from /var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/nodes.rb:10:in `load'
	from /var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/nodes.rb:122:in `initialize'
	from /var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/core.rb:14:in `new'
	from /var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/core.rb:14:in `initialize'
	from /var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/core.rb:4:in `new'
	from /var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/core.rb:4:in `new'
	from /var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/cli.rb:12:in `run'
	from /var/lib/gems/2.3.0/gems/oxidized-0.19.0/bin/oxidized:9:in `<top (required)>'
	from /usr/local/bin/oxidized:22:in `load'
	from /usr/local/bin/oxidized:22:in `<main>'
I, [2017-03-06T23:22:18.109843 #724]  INFO -- : Oxidized starting, running as pid 724
I, [2017-03-06T23:22:18.150597 #724]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
F, [2017-03-06T23:22:18.168300 #724] FATAL -- : Oxidized crashed, crashfile written in /root/.config/oxidized/crash
no implicit conversion of String into Integer
/var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/source/http.rb:44:in `dig': no implicit conversion of String into Integer (TypeError)
	from /var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/source/http.rb:44:in `block (2 levels) in load'
	from /var/lib/gems/2.3.0/gems/asetus-0.3.0/lib/asetus/configstruct.rb:21:in `each'
	from /var/lib/gems/2.3.0/gems/asetus-0.3.0/lib/asetus/configstruct.rb:21:in `each'
	from /var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/source/http.rb:42:in `block in load'
	from /var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/source/http.rb:38:in `each'
	from /var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/source/http.rb:38:in `load'
	from /var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/nodes.rb:15:in `block in load'
	from /var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/nodes.rb:127:in `synchronize'
	from /var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/nodes.rb:127:in `with_lock'
	from /var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/nodes.rb:10:in `load'
	from /var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/nodes.rb:122:in `initialize'
	from /var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/core.rb:14:in `new'
	from /var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/core.rb:14:in `initialize'
	from /var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/core.rb:4:in `new'
	from /var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/core.rb:4:in `new'
	from /var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/cli.rb:12:in `run'
	from /var/lib/gems/2.3.0/gems/oxidized-0.19.0/bin/oxidized:9:in `<top (required)>'
	from /usr/local/bin/oxidized:22:in `load'
	from /usr/local/bin/oxidized:22:in `<main>'`

**Comment by lunacite** [comment]
It will continue to die, attempt to start, die, until the container is stopped, and never gets into a working state

**Comment by ytti** [comment]
Are you extrapolating this information based on short runtime or did you actually verify that no HTTP  GET is being made?

The backtrace implies HTTP GET was made, and it's very confusing if none has been made.

The backtrace shows crash while parsing the HTTP GET output.

**Comment by lunacite** [comment]
Turns out I was looking at the wrong interface, it was an issue with librenms & a bad API token.

**Comment by chasgames** [comment]
Thank you for posting this, i had the same issue, turned out someone had deleted the API user in LibreNMS.

oxidized_1  | A server is already running. Check /root/.config/oxidized/pid

oxidized_1  | I, [2017-10-16T11:42:27.659244 #207]  INFO -- : lib/oxidized/nodes.rb: Loading nodes
oxidized_1  | F, [2017-10-16T11:42:27.669341 #207] FATAL -- : Oxidized crashed, crashfile written in /root/.config/oxidized/crash
oxidized_1  | no implicit conversion of String into Integer
