### ISSUE TITLE
Sophos UTM

### ISSUE THREAD

**Issue by scubes13** [ytti/oxidized#734]
I would like to determine how to backup a config file from a Sophos UTM (v9.4) firewall appliance.

I am totally new to oxidized, so I have not a clue where to start.

The config file can be downloaded from within the web gui for the firewall. The firewall also is able to email the config file on a schedule.

I am not sure if the config can be downloaded via SSH, though SSH access is available.

Would anyone be willing to assist in figuring this out?

**Comment by ytti** [comment]
We do not have ```http``` input method, but it will be easy to add, but not as easy as just adding new model.

Either give me access to a sanitised device, or perhaps look at input/tftp.rb input/ftp.rb and models using them.

**Comment by scubes13** [comment]
I can provide you access to a clean non-production device.

Here are screenshots of the backup screen in the Sophos XG firewall (local/FTP/email).....

![screen shot 2017-02-19 at 11 30 36 am](https://cloud.githubusercontent.com/assets/2099940/23104199/1ed8b3d4-f697-11e6-9942-84397fac79ad.png)

![screen shot 2017-02-19 at 11 30 53 am](https://cloud.githubusercontent.com/assets/2099940/23104200/1ed922d8-f697-11e6-9931-6ddd913f13b3.png)

![screen shot 2017-02-19 at 11 31 05 am](https://cloud.githubusercontent.com/assets/2099940/23104198/1ed753e0-f697-11e6-9da4-d64625f85671.png)

Here are the options on Sophos UTM firewall (download/Email).....

![screen shot 2017-02-19 at 11 34 36 am](https://cloud.githubusercontent.com/assets/2099940/23104229/99280b6c-f697-11e6-931d-6ceee1b8f846.png)

![screen shot 2017-02-19 at 11 35 04 am](https://cloud.githubusercontent.com/assets/2099940/23104230/992bb91a-f697-11e6-97bb-3fb7da44ca81.png)

Let me know how you'd like to connect for access to either firewall....

**Comment by ytti** [comment]
So what we'd need is actual ```HTTP GET``` which you'd want to gather, i.e. how to get the config out.

**Comment by wendelj** [comment]
I poked through the API documentation for Sophos UTM but I don't see an endpoint to grab backup files with.
I don't imagine this would be too hard using the CLI though. Make a call to create a backup from the CLI. Wait until it finishes Grab the backup it created.

Sophos UTM backup via CLI info: https://community.sophos.com/kb/en-us/119814

**Comment by arnovdveen** [comment]
for sg this may be the best solution: https://support.sophos.com/support/s/article/KB-000034929?language=en_US
then by scp it can be pulled from the device.

for xg it could be done by api calls, but i have to check how.
