### ISSUE TITLE
Mail Notification - How to?

### ISSUE THREAD

**Issue by nvmike** [ytti/oxidized#736]
Hello 
I understand that the issue has been raised on how to send mail notification for events like Config changes or success/fail of rotation.
Unfortunately I failed to find any instruction on how to make this happen...So I remain stuck with Rancid :-(

Mike

**Comment by natm** [comment]
@nvmike have you looked at `oxidized-report-git-commits` script included in the `extras` directory?

https://github.com/ytti/oxidized/blob/master/extra/oxidized-report-git-commits

**Comment by anden4380** [comment]
I am not that strong in Linux but i have a Oxidized running and backingup my config from my switches

But i cannot find out how to get this mail notification to work :-( 

i have install ssmtp and i can send mail from my server but where to i set it up in Oxidized?
