### ISSUE TITLE
Question about output types

### ISSUE THREAD

**Issue by nullzeroroute** [ytti/oxidized#737]
Is it possible to have multiple output types?  Going through the issues it looks like that functionality was added however I can't find any documentation related to that.  I'm having a problem with writing to git and file.  I'm new to this, any help is appreciated.  If there's a better forum for posting beginner questions let me know.

Here's a snip from my config.

output:
 default: file
 file:
    directory: /home/oxidized/deviceconfigs
 default: git
 git:
    user: Oxidized
    email: o@example.com
    repo: "/home/oxidized/deviceconfigs/devices.git"

The first time it ran the git repository was created in /home/oxidized/deviceconfigs/devices.git and the initial config files were saved in  /home/oxidized/deviceconfigs so I thought it worked, however a firewall configuration change later in the morning only updated devices.git and a new file for that firewall configuration did not show up in  /home/oxidized/deviceconfigs.  The git repo writing does appear to be working because git log shows the different configuration versions, and they are correct.  

I would like to have both the git repo and the most recent device configuration file saved.

**Comment by ytti** [comment]
It is not currently supported. 

Maybe add in crontab periodic 'git pull'

**Comment by nullzeroroute** [comment]
Thanks for confirming.  I read in another thread that having multiple output types was supported, maybe I got the feature confused with something else.

I'm clueless when it comes to git and version control services in general, so I had a peer show me a few things.  I found that I can view all of the changes with...
git log
...then I can view the entire device config at a point in time after a change was made by doing a...
git show <commit tag>:<device name>

For example, doing the following...
git show b8964c75508ea822585e8f769a60d6e7eb89404b:router123.somedomain.com
...shows me the entire configuration for that device after the change occurred.

Just figured I'd include that just in case any other newbies were lurking this page for help.

**Comment by ytti** [comment]
Something like this might inspire:

 1. catcfg node - show latest config
 2. catcfg node date - show config at date
 3. diffcfg node - compare latest to yesterday
 4. diffcfg node date1 - compare latest to date1
 5. diffcfg node date1 date2 - compare date1 and date2


´´´
catcfg() {
  node=$1
  date=${2:-$(date --date=tomorrow -I)}
  IFS="," read group node <<< $(find /home/rancid/*/configs -iname "${node}*"|grep -v raw$|grep -v inventory|grep -v installed|grep -v new$|ruby -F'/' -nae 'puts $F[3]+","+$F[-1]')
  rev=$(git --git-dir=/home/rancid/${group}/.git rev-list -1 --before=$date master)
  git --git-dir=/home/rancid/${group}/.git show ${rev}:configs/$node
}

diffcfg() {
  node=$1
  date1=${2:-$(date --date=yesterday -I)}
  date2=${3:-$(date --date=tomorrow -I)}
  file1=$(mktemp /tmp/.diffcfg-${USER}-XXXXX)
  file2=$(mktemp /tmp/.diffcfg-${USER}-XXXXX)
  catcfg $node $date1 > $file1
  catcfg $node $date2 > $file2
  vimdiff $file2 $file1
  rm $file1 $file2
}
```

**Comment by nullzeroroute** [comment]
Thank you for the suggestion.
