### ISSUE TITLE
exclude uptime from 'show version' on IOS

### ISSUE THREAD

**Issue by ecm75** [ytti/oxidized#740]
I noticed that I got a lot of config updates reported by oxidized when fetching configs from several IOS devices.
It turned out that the only line which was constantly changing was the uptime reported by `show version`.
I fixed it with this simple patch, maybe it's worth including...

```
-  cmd 'show version' do |cfg|
+  cmd 'show version | exclude uptime' do |cfg|
```

**Comment by ytti** [comment]
We're only collecting one line of the output: https://github.com/ytti/oxidized/blob/master/lib/oxidized/model/ios.rb#L39

Which oxidized version are you running?

**Comment by ecm75** [comment]
Hi,

please close this, it was my fault..
I had a test version in .config/oxidized/model/ios.rb in which I removed the `.first` for some reason :/

I'm running 0.19.0 and it's working just fine with the original code.
