### ISSUE TITLE
Issue with reported last config change on Cisco ASA

### ISSUE THREAD

**Issue by ecm75** [ytti/oxidized#741]
Simmilar to the earlier reported uptime causing constant config updates, I had an issue with Cisco ASAs reporting slightly different timestamps for the last config change.

Here's a patch to work around this issue by simply cutting the seconds part:
```
--- a/lib/oxidized/model/asa.rb
+++ b/lib/oxidized/model/asa.rb
@@ -23,6 +23,7 @@ class ASA < Oxidized::Model
     # avoid commits due to uptime / ixo-router01 up 2 mins 28 secs / ixo-router01 up 1 days 2 hours
     cfg = cfg.each_line.select { |line| not line.match /(\s+up\s+\d+\s+)|(.*days.*)/ }
     cfg = cfg.join
+       cfg.gsub! /(Configuration last modified by) (\S+) at (\d+:\d+)(:\d+\.\d+) (.*)/, '\1 \2 \3 \5'
     comment cfg
   end
```

**Comment by ytti** [comment]
But last modified only changes when config is written, so why does it cause constant change?

I'm fine by removing it from the output, just curious.

**Comment by ecm75** [comment]
Yea that's what you'd expect to see, but here's what I see on several of our devices when issuing several subsequent show version commands:
```
router# show version | include last modified
Configuration last modified by enable_15 at 11:19:34.290 CEST Wed Nov 2 2016
router# show version | include last modified
Configuration last modified by enable_15 at 11:19:34.450 CEST Wed Nov 2 2016
router# show version | include last modified
Configuration last modified by enable_15 at 11:19:34.720 CEST Wed Nov 2 2016
router# show version | include last modified
Configuration last modified by enable_15 at 11:19:34.210 CEST Wed Nov 2 2016
```

The date kind of "jitters"...
I still have to investigate if it's just on some fw versions...

**Comment by jsynack** [comment]
+1 on this.

I  have seen this on several older ASA units. The msec can jitter, so removing the msec and second from the output should keep things running cleaner with just the hour:minute in the output.  While there is the edge case that a jittering second could 'flip' the minute - it is probably not worth the extra code to handle that case.

As @ecm75 shows - this jitters even on the same CLI session , with no actual changes that have taken place for months on the unit. And it is not impacted by NTP sync status/etc. It can skip forward or go backwards 

We modified our local `asa.rb` for this - I wanted to confirm that someone else has seen this in the wild as well.

This was run back-to-back:

```
dsfw3058> show ver | inc mod
Configuration last modified by xxx at 18:56:28.666 PDT Sat Oct 21 2017
dsfw3058> show ver | inc mod
Configuration last modified by xxx at 18:56:29.026 PDT Sat Oct 21 2017
dsfw3058> show ver | inc mod
Configuration last modified by xxx at 18:56:29.006 PDT Sat Oct 21 2017
dsfw3058> show ver | inc mod
Configuration last modified by xxx at 18:56:28.936 PDT Sat Oct 21 2017
dsfw3058> show ver | inc mod
Configuration last modified by xxx at 18:56:28.997 PDT Sat Oct 21 2017
dsfw3058> show ver | inc mod
Configuration last modified by xxx at 18:56:29.007 PDT Sat Oct 21 2017
dsfw3058> 
```

**Comment by ecm75** [comment]
Still not patched in master?
I just updated my oxidized instance and I'm again hitting this issue...

**Comment by laf** [comment]
> Still not patched in master?
> I just updated my oxidized instance and I'm again hitting this issue...

Have you submitted the fix?
