### ISSUE TITLE
Cisco 3560 and telnet

### ISSUE THREAD

**Issue by richbibby** [ytti/oxidized#743]
Hi.  not sure if the correct forum, so apologies if not.  I'm sure this isn't a bug, but I cannot back up my Cisco 3560's over telnet.  Logs just show: 

username: Trying x.x.x.x...
Connected to x.x.x.x....

I can connect manually from oxidized to the switches, using the same credentials as oxidized uses.

appreciate any help
Rich

**Comment by ytti** [comment]
Are you running with debugging turned on? Have you tried also to turn on input debugging:
```
input:
  debug: true
```

And  observe the session file created on device's name.

**Comment by richbibby** [comment]
yes for input debugging, but no for the top level (I presume thats the default, but overwritten by the input debugging?

debug: false
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 0.0.0.0:8888
log: /home/oxidized/.config/oxidized/log
vars:
  remove_secret: true
groups: {}
pid: "/home/oxidized/.config/oxidized/pid"
input:
  default: telnet, ssh
  debug: true


the file debug output file created for these devices shows only this: 

username: Trying x.x.x.x...
Connected to x.x.x.x....

username: Trying x.x.x.x...
Connected to x.x.x.x....

**Comment by richbibby** [comment]
prior to enabling logging for input, I was seeing log entries on my ssh session to oxidized, but they are no longer outputting to the screen.  one of the older entries shows: 

raised Timeout::Error with msg "timed out while waiting for more data"
status no_connection, retry attempt 1

**Comment by ytti** [comment]
You're saying the device-telnet/device-ssh files are empty? They are always over-written by new attemps, so you might want to run with ```tail -f``` to catch what's happening.

**Comment by richbibby** [comment]
Hi ytti, 

Apologies, this is the exact same issue as: https://github.com/ytti/oxidized/issues/649

I changed my local ios.rb to
```
username /^(u|U)sername:/
password /^(p|P)assword:/
```
Again, it seems to be the TACAC's server customizing the login and presenting a lowercase u in username.

All good now :-)
Thanks for your help.
Rich

**Comment by ytti** [comment]
Appears to be, or are you sure? I'm skeptical lot of people would configure custom prompts in TACACS server. 
If this is from TACACS server, I see little point to fix. If it's not from TACACS server, we definitely need to fix it.

**Comment by Wax-Trax** [comment]
I'd like to commend that I just ran into something similar, and fixed it in a similar manner. In my environment, we authenticate network devices against TACACS, and 99% of our devices are backed up via SSH, but we have a few older Cisco boxes that don't have a k9 image, so Telnet is the only option.

When you log in with Telnet, TACACS changes the login prompt to "UserID:" in our case. Like Rich, I modified the ios.rb file for the Telnet section, and everything started working.

Though this is not directly related to Oxidized, I thought it might be something that wouldn't hurt to be documented somewhere. Thanks for this great project! :-)

**Comment by ytti** [comment]
I'm happy to accept PR for documentation, but I mean documentation seems to be ```if you ask your TACACSs to print non-standard login prompt, then TACACSs will print non-standard login prompt, and standard login prompt regexp won't work```, I kind of hope that would have been implied?

This is user configuration in TACACS, if you do not provide this attribute to TACACS, it does not change the prompt.

**Comment by Wax-Trax** [comment]
My apologies, I may have missed that. This is one of those things that makes perfect sense in hindsight, but was a little difficult to troubleshoot at the time simply because I forgot that my TACACS server is configured with a custom prompt for Telnet (because of course I use SSH whenever possible, and rarely is Telnet needed in my environment). 

This issue isn't directly related to the project, I just wanted to add to this thread that I experienced it too, and that it is one thing to potentially be aware of when troubleshooting if things aren't working as expected.

**Comment by ytti** [comment]
Why do you configure custom prompt in Tacacs? Seems like recipe for disaster, particularly if you don't understand the implications.

But yeah, I think the thread is useful, as there has now been two cases like this. But honestly, I feel like people who change this, and don't know they've changed this, are going to be very challenging to help.

**Comment by Wax-Trax** [comment]
I agree 100% with you, especially about changing the prompt being a recipe for disaster. In my case, for the enterprise network I help manage, the decision to change the TACACS prompt was made many years ago by someone else (for an unknown reason) before I got there, and we have custom scripts that now depend on that custom prompt. I don't like the situation, but I don't have any influence over the matter.

**Comment by ytti** [comment]
Understood. We do support nodes configuring their own custom prompt, so you could avoid using customer model by specifying the node prompt in your ```source```.
