### ISSUE TITLE
SSH -1

### ISSUE THREAD

**Issue by batmatjojojo** [ytti/oxidized#744]
Hello, I encounter a worry on several devices, the SSH is version -1 and not 2.

Is it possible to force the ssh -1 in the oxidized configuration?

Thank you for your answers

Best regards

**Comment by ytti** [comment]
We do not at this time support SSHv1. I recommend using Telnet for those devices where SSHv2 is not available.

**Comment by batmatjojojo** [comment]
That's unfortunate,

In our company, we have many (old) equipment that requires this option, will you integrate it one day?

Best regards

**Comment by ytti** [comment]
When you say many, which vendors/models support only sshv1? I'm not currently planning to add SSHv1 support, but I'll consider accepting pull request for such. I'm not currently aware which maintained libraries support SSHv1, I suspect there are none.

**Comment by batmatjojojo** [comment]
Mostly HP procurve, we are in a big company and the network equipments are not often of our perimeter, so it is impossible to modify SSH authentication, that is why the addition of this functionality would be perfect.

In thanking you

**Comment by ytti** [comment]
We have other procurve users who use SSH, perhaps you can upgrade devices for SSHv2? As far as I know SSHv1, from security POV, is broken by design.

**Comment by batmatjojojo** [comment]
Thank you for your reply, I think we will embark on an upgrade campaign;)

Best regards
