### ISSUE TITLE
Firewall netscreen SSG

### ISSUE THREAD

**Issue by batmatjojojo** [ytti/oxidized#745]
Hello,

I encounter problems on Firewall juniper ssg140.6.3.0r21.0,

I am very good at connecting via ssh from the same network and from the machine.

XXXXXXXXXXX raised Timeout :: Error with msg "execution expired"
W, [2017-02-27T14: 32: 27.310075 # 2680] WARN -: XXXXXX raised Net :: OpenTimeout (rescued Timeout :: Error)
W, [2017-02-27T14: 32: 27.971114 # 2680] WARN -: XXXXXXXXX status no_connection, retries exhausted, giving up

I have a master and slave (M) et (S)
XXXX(M)-> 
XXXX(S)->

DEBUG : D, [2017-02-27T15:47:22.295372 #4890] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^[\w.:\(\)-]+->\s?$/] at XXXXXXXXX

Thank you for your help

**Comment by ytti** [comment]
Perhaps turn on input debugging:
```
input:
  debug: true
```

and ```tail -f``` the file, to see what session looks. File name will be device name and input method.

**Comment by batmatjojojo** [comment]
The problem is solved , thank you
