### ISSUE TITLE
 not matching configured prompt

### ISSUE THREAD

**Issue by batmatjojojo** [ytti/oxidized#747]
Hello, I have a problem with a prompt command

I have tried several commands but I can not find the right one

W, [2017-03-01T08:30:36.027421 #10080]  WARN -- : 10.27.246.39 raised Oxidized::PromptUndetect with msg "::: Property of XXXXXXXXX - XXXXXXX :::
::: Property of XXXXX - XXXXXXX :::
Type help or '?' for a list of available commands.
DEVICE#  not matching configured prompt (?-mix:^([\w.@()-]+[#>]\s?)$)

Tkank's for your help

**Comment by ytti** [comment]
Can you do input debug:
```
input:
  debug: true
```

look at the file created, check if there are some unprintable characters in the prompt output.

**Comment by udhos** [comment]
I have also noticed this effect: simple regex rules fail to match simple prompts.
Since I could not find special characters, I suspect the issue is somehow related to multi-line matching.
Try to remove the leading '^' as work-around.

**Comment by ytti** [comment]
If removing ^ works, then almost certainly there is some trash there, usually ^M i.e. replace ^ with ```^\r?```

But it should be easy to view what it is.
