### ISSUE TITLE
Error on VRP - Huawei device

### ISSUE THREAD

**Issue by jnizamj** [ytti/oxidized#749]
Hi,
I'm using Huawei CX600. When I run oxidized, it returns me part of "display version" command and then "Error:Too many parameters found at '^' position." at the bottom of file. 
I tried to skip "display version" and " display device" in /lib/oxidized/model/vrp.rb but failed.
How can I fix this?
I have no issue when fetch from JunOS and IOS. Only VRP having this error.
Thanks.

**Comment by ytti** [comment]
Does the device itself accept ```display version``` when you manually enter it? If not, what command does it accept?

What do you mean you failed to skip them? You deleted the the ```cmd``` block and still saw the problem? Then you must have edited wrong version model.

**Comment by jnizamj** [comment]
Hi,
Yes, I skipped the block to run "display current-configuration all" only.
Now I managed to run it now. It was due to my privilege level. "display current-configuration all" only runable by level 15. Then, I changed to " display current-configuration" instead.

Please close this.thank you very much!
