### ISSUE TITLE
unable to get config from ZTE devices

### ISSUE THREAD

**Issue by jnizamj** [ytti/oxidized#750]
Is there any lib available which compatible with ZTE devices?
Thanks.

**Comment by ytti** [comment]
No, I'm sure you can produce one. Copy some model to ~/.config/oxidized/model/mynewmodel.rb and edit it until it works.

```
input:
  debug: true
```

Will help greatly. Start simple, just support ssh, login and collect on command.

**Comment by jnizamj** [comment]
Dear ytti,
Thanks. I've successfully created new model for ZTE and working fine.

[zte.txt](https://github.com/ytti/oxidized/files/1005182/zte.txt)

**Comment by ytti** [comment]
Please submit pull request if you feel like it. We prefer to use OS name as model name, not hardware.

**Comment by chasgames** [comment]
Thanks @jnizamj  and @ytti this helped us too.

We found we had to put terminal length after enable though and then it started working, the secrets removal don't seem to work, not sure how to fix but good the config backup is working :+1: . 

~/.config/oxidized/model/zte.zb
```
class ZTE < Oxidized::Model

  prompt /^([\w.@()-]+[#>]\s?)$/
  comment  '! '

  cmd :all do |cfg|
    cfg.each_line.to_a[1..-2].join
  end

  cmd :secret do |cfg|
    cfg.gsub! /^(snmp-server community).*/, '\\1 <configuration removed>'
    cfg.gsub! /username (\S+) privilege (\d+) (\S+).*/, '<secret hidden>'
    cfg.gsub! /^username \S+ password \d \S+/, '<secret hidden>'
    cfg.gsub! /^enable password \d \S+/, '<secret hidden>'
    cfg.gsub! /wpa-psk ascii \d \S+/, '<secret hidden>'
    cfg.gsub! /^tacacs-server key \d \S+/, '<secret hidden>'
    cfg
  end

  cmd 'show version' do |cfg|
    comment cfg.lines.first
  end

  cmd 'show running-config' do |cfg|
    cfg = cfg.each_line.to_a[3..-1]
    cfg = cfg.reject { |line| line.match /^ntp clock-period / }.join
    cfg.gsub! /^Current configuration : [^\n]*\n/, ''
    cfg.gsub! /^\ tunnel\ mpls\ traffic-eng\ bandwidth[^\n]*\n*(
                  (?:\ [^\n]*\n*)*
                  tunnel\ mpls\ traffic-eng\ auto-bw)/mx, '\1'
    cfg
  end

  cfg :telnet do
    username /^Username:/
    password /^Password:/
  end

  cfg :telnet, :ssh do
    # preferred way to handle additional passwords
    if vars :enable
      post_login do
        send "enable\n"
        cmd vars(:enable)
        send "terminal length 0\n"
      end
    end
    pre_logout 'exit'
  end

end
```

**Comment by ytti** [comment]
it's actually more broken that way, send doesn't expect any output, but if the line produces prompt, then the send is just broken. In your case ```terminal length 0``` produces prompt.

The model expects that if you _DO_ enable, there is enable prompt asking for password. If this is NOT true, the model does not work. Like if you enable but after enable you get prompt directly, the model won't work in such case.

Fix is to either send your enable password to ```false```, as you do not need to enable. Or fix the model so that that ```enable``` expects proper enable password prompt.

Like such:
https://github.com/ytti/oxidized/blob/master/lib/oxidized/model/ios.rb#L135-L142

**Comment by chasgames** [comment]
Ah ok thanks @ytti for the explanation will look into it further.
