### ISSUE TITLE
Slack: Option to only send a link to diffs into slack

### ISSUE THREAD

**Issue by makzdot** [ytti/oxidized#756]
Hi,

Great stuff oxidized. I was wondering is it possible to create an option to only post a link to slack instead entire snippets with possible secrets. (We want our secrets backupped). I get kinda nervous when posting secrets to a cloud solution like slack.

Kind regards.
Max

**Comment by ytti** [comment]
No, but I'll accept PR if you want to add that support.

**Comment by natm** [comment]
I will add this to my todo list, it seems like a good ask.

**Comment by natm** [comment]
@makzdot as promised see https://github.com/ytti/oxidized/pull/763

**Comment by makzdot** [comment]
Hi @natm, Great news thanks. I'll try it out ASAP

**Comment by laf** [comment]
This has been merged in now.
