### ISSUE TITLE
How to configure syslog and trigger config fetch

### ISSUE THREAD

**Issue by BenoitJ76** [ytti/oxidized#759]
Hello,

Can you please explain me how to configure this feature: "syslog udp + file to catch config change event (ios / junos) and trigger config fetch"

What are the options to fill in the config file? Is it possible to do this from a remote syslog server?

Thank you for your help.

**Comment by ytti** [comment]
You monitor syslog for changes, then use the API to ask Oxidized to fetch given node.

Some example code in /extra
https://github.com/ytti/oxidized/blob/master/extra/syslog.rb
https://github.com/ytti/oxidized/blob/master/extra/rest_client.rb

**Comment by natm** [comment]
We do this using Logstash, all our network devices send syslog to it, from there we push logs to Elastic Search + Kibana.

Simplified overview - In our Logstash config we have grok rules to match for "config saved" style messages, those appearing triggers Logstash to call Oxidized via HTTP.

**Comment by laf** [comment]
@BenoitJ76 Do you need anymore information?
