### ISSUE TITLE
enhancement for "oxidized.service" file

### ISSUE THREAD

**Issue by zxyz** [ytti/oxidized#760]
on my system oxidized startup with systemd fails after a reboot because the network is not ready. 
Adding `After=network-online.target` in the `[Unit]` section solved this for me

```
[Unit]
Description=Oxidized - Network Device Configuration Backup Tool
After=network-online.target

[Service]
ExecStart=/usr/local/bin/oxidized
User=oxidized

[Install]
WantedBy=multi-user.target
```

**Comment by ytti** [comment]
Send pull request, thanks!

**Comment by davama** [comment]
@zxyz  Id noticed that too

https://github.com/ytti/oxidized/pull/921

**Comment by laf** [comment]
@davama Why have default being optional? Should it not be on by default?

**Comment by davama** [comment]
placed it that way because everyones env is diff. so you can set or not. up to you
if you want to change that PR then resubmit. it's the same to me

**Comment by laf** [comment]
I would have thought though network services would be a requirement no matter what though :)

**Comment by davama** [comment]
agreed
when i first installed i never had it. only later in life of our system did i have to add them. the lines are there so thats a start

**Comment by danilopopeye** [comment]
@laf + @davama we can close this one, right?

**Comment by laf** [comment]
@danilopopeye I don't see why not, I think it would be better to have it enabled as network services seems a key requirement to oxidized to start.

If others agree I'll open a PR.

**Comment by danilopopeye** [comment]
> If others agree I'll open a PR.

fine by me 😃 closing this one
