### ISSUE TITLE
Parallel Threads

### ISSUE THREAD

**Issue by winglessza** [ytti/oxidized#762]
Hi,

I was under the impression Oxidized could run multiple threaded config downloads at the time, but it seems its just running in a single threaded queuing. Any insight into this?

**Comment by ytti** [comment]
It runs as many as it needs to reach rotation interval. 

If you have large interval and/or very few nodes, one thread might be all it needs to collect all of the nodes within interval.

Are you not getting new config backup of any given node within interval?

**Comment by winglessza** [comment]
Thanks for the response.

Thanks. I was under the assumption that it would download up to the maximum thread count at the start of the interval. My interval is set to 6hours, and we have some very large configs from oracle acme's that can take up to 3 minutes to completely pull the config, so was wanting to run these in parallel, so that other devices could be downloaded at the same time.

**Comment by ytti** [comment]
Unfortunately that is not how we guarantee fetch, we guarantee config to be no older than interval.
