### ISSUE TITLE
custom base path

### ISSUE THREAD

**Issue by jgroom33** [ytti/oxidized#764]
I'm running oxidized in a docker container.
Instead of exposing a static port (8888) the container's port is dynamically mapped to a different path:
http://hostip/foo
When the user opens that url, they see the following Sinatra error in the browser:

```
Sinatra doesn’t know this ditty.

Try this:
# in webapp.rb
class Oxidized::API::WebApp
  get '/foo/' do
    "Hello World"
  end
end
```

Is there a way to tell oxidized that it's root url path is different?

**Comment by ytti** [comment]
Have you tried setting path to the 'rest' config option? e.g.
```
rest: 10.0.0.1:8000/oxidized
```

**Comment by laf** [comment]
I can confirm `rest: 0.0.0.0:8443/oxidized` works for us.

**Comment by jgroom33** [comment]
thanks!  That does the trick
