### ISSUE TITLE
Block in precompiled_postamble

### ISSUE THREAD

**Issue by maciekleja** [ytti/oxidized#766]
I get the following error when I click links or reload the page for oxidized for every device I have in the .db file.  

So if I'm on the http://server:8888 page and I hit reload and I have 3 devices in .db I'll see this error three times:

/usr/local/rvm/gems/ruby-2.4.0/gems/tilt-2.0.6/lib/tilt/haml.rb:50:in `block in precompiled_postamble': Haml::Engine#precompiled_method_return_value at /usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/forwardable.rb:156 forwarding to private method Haml::Compiler#precompiled_method_return_value

Everything appears to continue to work on the site itself but wondering what this could be.  Thanks!

**Comment by juliosousa** [comment]
Any news?

**Comment by ytti** [comment]
Do you have full traceback? This seems to be ```oxidized-web``` issue, not ```oxidized```. But I'd like to see full traceback to see which ```oxidized-web``` code line causes this.

**Comment by amachekhin** [comment]
Looks like the same issue here (CentOS 6.9):

```
/usr/local/rvm/gems/ruby-2.4.2/gems/tilt-2.0.8/lib/tilt/haml.rb:77:in `block in precompiled_postamble': Haml::Engine#precompiled_method_return_value at /usr/local/rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/forwardable.rb:157 forwarding to private method Haml::Compiler#precompiled_method_return_value
/usr/local/rvm/gems/ruby-2.4.2/gems/tilt-2.0.8/lib/tilt/haml.rb:77:in `block in precompiled_postamble': Haml::Engine#precompiled_method_return_value at /usr/local/rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/forwardable.rb:157 forwarding to private method Haml::Compiler#precompiled_method_return_value
/usr/local/rvm/gems/ruby-2.4.2/gems/tilt-2.0.8/lib/tilt/haml.rb:77:in `block in precompiled_postamble': Haml::Engine#precompiled_method_return_value at /usr/local/rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/forwardable.rb:157 forwarding to private method Haml::Compiler#precompiled_method_return_value
```

Might be this bug in Ruby:

https://github.com/haml/haml/issues/909

I upgraded haml to version 5.0.4, but messages still appears every time I visit or refresh oxidized page.

**Comment by wk** [comment]
This is an older issue, and Oxidized has seen several new releases since it has been posted. If this is still relevant, please re-attempt this on a more recent (0.24.0) version and update the issue with your findings.
