### ISSUE TITLE
OpenSSL Cipher is deprecated

### ISSUE THREAD

**Issue by maciekleja** [ytti/oxidized#767]
Every time the interval occurs, for every device whether it's a Cisco or Juniper device I will see two outputs (per device):

```
/usr/local/rvm/gems/ruby-2.4.0/gems/net-ssh-3.0.2/lib/net/ssh/transport/cipher_factory.rb:97: warning: constant OpenSSL::Cipher::Cipher is deprecated
/usr/local/rvm/gems/ruby-2.4.0/gems/net-ssh-3.0.2/lib/net/ssh/transport/cipher_factory.rb:72: warning: constant OpenSSL::Cipher::Cipher is deprecated
```

Everything appears to continue to function but wondering if this is affecting any performance/ causing any issues and whether it's an easy fix.   Thanks!

**Comment by jsynack** [comment]
Oxidized gemspec is now set for 4.1.0 for net-ssh. 
Fixed here https://github.com/net-ssh/net-ssh/commit/beb299e8f1899622dccb318ca9d3d3573e96a8a8

This should be OK to close/resolve.
