### ISSUE TITLE
FabricOS v6.1.1b - configshow: unrecognized option `-all'

### ISSUE THREAD

**Issue by cgsecurity** [ytti/oxidized#768]
In oxidized/model/fabricos.rb, a fallback to 'configshow' should be implemented if 'configShow -all' returns "unrecognized option `-all'"

**Comment by ytti** [comment]
Sure, go ahead? :>

cmd "configShow -all" do |blaablaa|
   blaablaa = cmd "configshow" if blaablaa.match /recognized option/
   ... mangle blaablaa normally ...
end

**Comment by cgsecurity** [comment]
I don't know ruby, I tried without success...

cmd 'configShow -all' do |cfg|
    cfg = cmd 'configShow' if cfg.match /recognized option/
    cfg
end

**Comment by ytti** [comment]
Without success is awfully non-specific. Do you have crash files? Anything in logs? Did you enable input: debug: true, did it output anything?
