### ISSUE TITLE
No implicit conversion of nil into String

### ISSUE THREAD

**Issue by jcshelby** [ytti/oxidized#773]
I saw another issue here for a similar problem but it seemed this should be resolved in later versions of Oxidized. I am getting the below error when attempting to either write a config to a local directory or when attempting to write that config to a git repository. The issue I saw already closed was for a git repo only. I also included the debug output from my attempt to run oxidized. It looks like everything is working except the write to disk operation. The relevant config is also below. Thanks in advance for your help and my apologies if these questions are simple fixes - I'm new to both Ruby and Oxidized :). 

Ruby version: 2.4.0
Oxidized version: 0.19.0
![oxidizedoutput](https://cloud.githubusercontent.com/assets/18707360/24009444/0238bd54-0a43-11e7-9a26-7c6fb2bc1907.PNG)

**Comment by ytti** [comment]
It seems that for some reason ```node``` is nil, which means your node's name is nil, which shouldn't happen.
Can you show your config and your source list of nodes, is 'name' set and mapped?

**Comment by jcshelby** [comment]
I'm using a router.db file as my source. The only entry is below as is my config. Thanks for the quick response and help! 
![oxidizedoutput](https://cloud.githubusercontent.com/assets/18707360/24010158/0bb4cf1a-0a45-11e7-8213-ace3c22f7550.PNG)

![oxidizedoutput](https://cloud.githubusercontent.com/assets/18707360/24010114/ef47b504-0a44-11e7-8ec9-214f73387db6.PNG)

**Comment by ytti** [comment]
change the IP to name, name is mandatory, IP is not.

**Comment by jcshelby** [comment]
Perfect! That fixed it. Thanks for the help and quick response. I'll make a note of that for the future :)
