### ISSUE TITLE
http://oxidized.company.com/node/show/<NODE> - Shows enable password

### ISSUE THREAD

**Issue by ghost** [ytti/oxidized#776]
http://oxidized.company.com/node/show/<NODE>

{:name=>"<NODE>",
 :full_name=>"<NODE>",
 :ip=>"10.130.0.4",
 :group=>nil,
 :model=>"ASA",
 :last=>
  {:start=>2017-03-21 14:14:12 UTC,
   :end=>2017-03-21 14:14:32 UTC,
   :status=>:no_connection,
   :time=>20.882648859},
 :vars=>{:enable=>"<PASSWORD>\t\t\t"}}

Is there a way to remove the enable password variable from appearing in the node page?

**Comment by ytti** [comment]
Not at this time. Vars are arbitrary, they don't have by-design meaning, meaning is given to them by models. So from our POV, it's just data.
Now if we'd want to have some two level nodes API, where we display full or partial information depending on some user permission or what not. We'd need to enrich the vars concept with meta data. So the vars would turn into something like:
```
vars:
  enable:
    value: xyzzy
    secret: true
  var2:
  var3:
  ...
```

I'm not gonna work on this, except perhaps during rewrite, which may or may not come.

**Comment by wk** [comment]
Closing this as the original author appears to have left GitHub, and we don't expect @ghost to take further interest outside of the framework of an organized séance.
