### ISSUE TITLE
Get no connection error when using cfg.gsub fonction with multiple line regex

### ISSUE THREAD

**Issue by patvallerand** [ytti/oxidized#781]
Hi, 
I have an issue when using dot match newlines option in cfg.gsub function. 
For all device that **does not match** a the multiple line regex and use the defined model library get a no connection error and configuration is not collected

Here is my model library. the two potential line that can cause the error are in bold.

`class IOS < Oxidized::Model

  prompt /^([\w.@()-]+[#>]\s?)$/
  comment  '! '

  cmd :all do |cfg|
    cfg.each_line.to_a[1..-2].join
  end

  cmd :secret do |cfg|
    cfg.gsub! /^(enable (password|secret) )\d \S+/, '\1<PASSWORD>'
    cfg.gsub! /^(username (\S+) privilege \d+ (password|secret) )\d \S+/, '\1<PASSWORD>'
    cfg.gsub! /^(username (\S+) (password|secret) )\d \S+/, '\1<PASSWORD>'
    **cfg.gsub! /^(tacacs( |-)server .*?key )\d \S+/mi, '\1<TACACS KEY>'**
    cfg.gsub! /^(snmp-server community )\S+/, '\1<SNMP COMMUNITY>'
    cfg.gsub! /^(snmp-server host \S+ (version \S+ |vrf \S+ |:?)(version \S+ |vrf \S+ |:?))\S+ /, '\1<SNMP COMMUNITY>'
    **cfg.gsub! /^(\s+key.\d+.\s+key-string )\d/mi, '\1<KEY-STRING>'**
  end

  cmd 'show running-config' do |cfg|
    cfg = cfg.each_line.to_a[3..-1]
    cfg = cfg.reject { |line| line.match /^ntp clock-period / }.join
    cfg
  end

  cfg :ssh do
    post_login 'terminal length 0'
    post_login 'terminal width 0'
    # preferred way to handle additional passwords
    if vars :enable
      post_login do
        send "enable\n"
        cmd vars(:enable)
      end
    end
    pre_logout 'exit'
  end
end
`

Best Regards

**Comment by patvallerand** [comment]
After more research, I have the same issue with single line regex... the issue seem to occur when gsub not matching a regex

**Comment by ytti** [comment]
cfg! will return ```nil``` if it didn't do replacement, it'll return itself it did do replacement.

So you want to have ```cfg``` before end, to ensure that we return value of cfg.

**Comment by patvallerand** [comment]
Many thanks ytti ! With your explanation I got a better understanding
work perfectly !!
