### ISSUE TITLE
Logon page. 

### ISSUE THREAD

**Issue by arturs0** [ytti/oxidized#784]
Hello, 

The question I have is if it would be possible to use a logon page with oxidized. 

If yes would you have any examles? 

Best Regards, 

Artur

**Comment by ytti** [comment]
Oxidized does not support itself, you might maybe run basic auth on your web front before oxidized.

**Comment by davama** [comment]
@arturs0 
It's quite simple with nginx. We use LDAP but there are other auth methods

```
   # oxidized SSL
    server {
	listen       <ip>:9002;
	server_name  h-txa-1ter-ecr-1;
	ssl on;
	location / {
		auth_ldap "LDAP Authentication";
  		auth_ldap_servers ldap_local;
	        proxy_pass          http://127.0.0.1:9002;
    	}
```

**Comment by laf** [comment]
@ytti Proposing this is closed as auth is dealt with outside of oxidized-web

**Comment by hostinggeek** [comment]
@davama,
 
did you have to satisfy any dependencies to make your ldap authentication work?  I'm having problems getting it going.  It seems straight forward enough, but when I try to add the oxidized_ssl.conf to my config, it wont start.  I know this is dealt with outside oxidized-web, but I don't think I'm alone with needing to find alternative login methods.

Thanks,

Rick

**Comment by davama** [comment]
Wow!
This is an old thread…

For new comers:

at least our org, we now use [authelia](https://github.com/authelia/authelia)  to protect our web frontends including apis. Awesome project! Highly recommend
