### ISSUE TITLE
New model request: Raisecom

### ISSUE THREAD

**Issue by taking-care-of-business** [ytti/oxidized#788]
Hello,

Would it be possible to include Raisecom devices into Oxidized?
If so, what information would be needed to assist developers with this request?
If it helps, the command-line is Cisco IOS-like.

**Comment by MajesticFalcon** [comment]
Can you provide access to one of these devices for testing?

On Mar 28, 2017, at 2:56 PM, taking-care-of-business <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello,

Would it be possible to include Raisecom devices into Oxidized?
If so, what information would be needed to assist developers with this request?
If it helps, the command-line is Cisco IOS-like.

**Comment by ytti** [comment]
Yeah either one sanitised device online. Or then just take a crack at it yourself. I'm sure you'll find it's rather easy produce models.
Copy existing model to ~/config/model/newmodel.rb play around with it, rely on input debugging to get feedback:

```
input:
 debug: true
```

And I'm sure you're good.

**Comment by taking-care-of-business** [comment]
Thanks for the feedback.

If I were to provide access to the device, then I'd prefer to harden on who will connect to the device. If I have that information, then I might be able to get that arranged.

Otherwise, pending time, I can play around with the debugging. My scripting is fairly bad ... but I'll trust your confidence :)

Having that said, and if I do figure out the newmodel.rb configuration, how would one the file to the Oxidized git repo (or is it preferred for me to leave it on my system locally?)

**Comment by ytti** [comment]
You'd fork the repo in github, commit the change to git and send pull request, which we'd then merge.
