### ISSUE TITLE
Oxidized dies on HUP reload

### ISSUE THREAD

**Issue by fhibler** [ytti/oxidized#79]
xxxx 22685  2.2  0.5 829120 42916 pts/1    Sl+  13:55   0:11 /usr/bin/ruby1.9.1 /usr/local/bin/oxidized

xxxx@mon01:~$ kill -HUP 22685

xxxx@mon01:~/.config/oxidized$ oxidized 
Puma 2.11.1 starting...
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://10.0.0.31:8888
Hangup

Log doesn't show anything obvious.

**Comment by RichiH** [comment]
@ytti If we had maintainer or similar status, we could assign labels ;)

**Comment by fhibler** [comment]
My fault, actually I didn't update oxidized to the version which includes the HUP update.

Afterwards it's screwed completely thou:
xxxx@mon01:~$ oxidized 
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': /var/lib/gems/1.9.1/gems/oxidized-0.3.0/lib/oxidized/core.rb:20: syntax error, unexpected '{', expecting keyword_end (SyntaxError)
      trap 'HUP' { nodes.load }
                  ^
/var/lib/gems/1.9.1/gems/oxidized-0.3.0/lib/oxidized/core.rb:20: syntax error, unexpected '}', expecting keyword_end
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /var/lib/gems/1.9.1/gems/oxidized-0.3.0/lib/oxidized.rb:5:in `<module:Oxidized>'
	from /var/lib/gems/1.9.1/gems/oxidized-0.3.0/lib/oxidized.rb:1:in `<top (required)>'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /var/lib/gems/1.9.1/gems/oxidized-0.3.0/lib/oxidized/cli.rb:3:in `<class:CLI>'
	from /var/lib/gems/1.9.1/gems/oxidized-0.3.0/lib/oxidized/cli.rb:2:in `<module:Oxidized>'
	from /var/lib/gems/1.9.1/gems/oxidized-0.3.0/lib/oxidized/cli.rb:1:in `<top (required)>'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /var/lib/gems/1.9.1/gems/oxidized-0.3.0/bin/oxidized:8:in `<top (required)>'
	from /usr/local/bin/oxidized:23:in `load'
	from /usr/local/bin/oxidized:23:in `<main>'

**Comment by fhibler** [comment]
Solved with 4908e399dde3546bd81e612a20b9b13982429583
