### ISSUE TITLE
Librenms  We couldn't retrieve the device information from Oxidized

### ISSUE THREAD

**Issue by kristoferus75** [ytti/oxidized#792]
Hi !

Oxidized work perfekt but if i want to open a config in librenms i get this error:

We couldn't retrieve the device information from Oxidized

and if i open the url in the browser or with curl: 

curl http://172.30.31.20:8888/node/show/HOSTNAME?format=json 
i get this error:

`MultiJson::AdapterError: Did not recognize your adapter specification (cannot load such file -- json/ext/parser).
	/usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:55:in `require'
	/usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:55:in `require'
	/usr/local/share/gems/gems/json-2.0.2/lib/json/ext.rb:7:in `<module:Ext>'
	/usr/local/share/gems/gems/json-2.0.2/lib/json/ext.rb:6:in `<module:JSON>'
	/usr/local/share/gems/gems/json-2.0.2/lib/json/ext.rb:3:in `<top (required)>'
	/usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:55:in `require'
	/usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:55:in `require'
	/usr/local/share/gems/gems/multi_json-1.12.1/lib/multi_json/adapters/json_gem.rb:1:in `<top (required)>'
	/usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:55:in `require'
	/usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:55:in `require'
	/usr/local/share/gems/gems/multi_json-1.12.1/lib/multi_json.rb:157:in `load_adapter_from_string_name'
	/usr/local/share/gems/gems/multi_json-1.12.1/lib/multi_json.rb:101:in `load_adapter'
	/usr/local/share/gems/gems/multi_json-1.12.1/lib/multi_json.rb:103:in `load_adapter'
	/usr/local/share/gems/gems/multi_json-1.12.1/lib/multi_json.rb:91:in `use'
	/usr/local/share/gems/gems/multi_json-1.12.1/lib/multi_json.rb:73:in `adapter'
	/usr/local/share/gems/gems/multi_json-1.12.1/lib/multi_json.rb:133:in `current_adapter'
	/usr/local/share/gems/gems/multi_json-1.12.1/lib/multi_json.rb:139:in `dump'
	/usr/local/share/gems/gems/sinatra-contrib-1.4.7/lib/sinatra/json.rb:113:in `block in resolve_encoder_action'
	/usr/local/share/gems/gems/sinatra-contrib-1.4.7/lib/sinatra/json.rb:112:in `each'
	/usr/local/share/gems/gems/sinatra-contrib-1.4.7/lib/sinatra/json.rb:112:in `resolve_encoder_action'
	/usr/local/share/gems/gems/sinatra-contrib-1.4.7/lib/sinatra/json.rb:98:in `json'
	/usr/local/share/gems/gems/oxidized-web-0.8.0/lib/oxidized/web/webapp.rb:230:in `out'
	/usr/local/share/gems/gems/oxidized-web-0.8.0/lib/oxidized/web/webapp.rb:117:in `block in <class:WebApp>'
	/usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `call'
	/usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `block in compile!'
	/usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `[]'
	/usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
	/usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:994:in `route_eval'
	/usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
	/usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:1015:in `block in process_route'
	/usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `catch'
	/usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `process_route'
	/usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:973:in `block in route!'
	/usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `each'
	/usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `route!'
	/usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:1085:in `block in dispatch!'
	/usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
	/usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
	/usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
	/usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:1082:in `dispatch!'
	/usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `block in call!'
	/usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
	/usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
	/usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
	/usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `call!'
	/usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:895:in `call'
	/usr/local/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	/usr/local/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/usr/local/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
	/usr/local/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/usr/local/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/usr/local/share/gems/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
	/usr/local/share/gems/gems/rack-1.6.4/lib/rack/nulllogger.rb:9:in `call'
	/usr/local/share/gems/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
	/usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/show_exceptions.rb:25:in `call'
	/usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:182:in `call'
	/usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:2013:in `call'
	/usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `block in call'
	/usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:1787:in `synchronize'
	/usr/local/share/gems/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `call'
	/usr/local/share/gems/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in `block in call'
	/usr/local/share/gems/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `each'
	/usr/local/share/gems/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `call'
	/usr/local/share/gems/gems/rack-1.6.4/lib/rack/builder.rb:153:in `call'
	/usr/local/share/gems/gems/puma-2.16.0/lib/puma/server.rb:557:in `handle_request'
	/usr/local/share/gems/gems/puma-2.16.0/lib/puma/server.rb:404:in `process_client'
	/usr/local/share/gems/gems/puma-2.16.0/lib/puma/server.rb:270:in `block in run'
	/usr/local/share/gems/gems/puma-2.16.0/lib/puma/thread_pool.rb:106:in `call'
	/usr/local/share/gems/gems/puma-2.16.0/lib/puma/thread_pool.rb:106:in `block in spawn_thread'`

i have talked to laf from librenms and he told me that i should ask here :-)
The webinterface from oxidzed works without problems !

my setup:  centos 7 with this installed gems:

gem list

*** LOCAL GEMS ***

asetus (0.3.0)
backports (3.7.0, 3.6.8)
bigdecimal (1.3.2, 1.3.0, default: 1.2.8)
bundler-unload (1.0.2)
did_you_mean (1.0.2, 1.0.0)
emk-sinatra-url-for (0.2.1)
executable-hooks (1.3.2)
gem-wrappers (1.2.7)
haml (4.0.7)
io-console (0.4.6, default: 0.4.5)
json (2.0.3, 2.0.2, default: 1.8.3)
minitest (5.10.1, 5.8.5)
multi_json (1.12.1)
net-ssh (4.1.0, 4.0.1, 3.0.2)
net-telnet (0.1.1)
oxidized (0.19.0)
oxidized-script (0.3.1)
oxidized-web (0.8.0)
power_assert (1.0.1, 0.4.1, 0.2.6)
psych (2.2.4, 2.2.2, 2.2.1, default: 2.1.0)
puma (3.8.2, 2.16.0)
rack (2.0.1, 1.6.5)
rack-protection (1.5.3)
rack-test (0.6.3)
rake (12.0.0, 11.3.0, 10.4.2)
rdoc (5.1.0, 5.0.0, default: 4.2.1)
rubygems-bundler (1.4.4)
rubygems-update (2.6.11, 2.6.8)
rugged (0.25.1.1, 0.25.1, 0.25.0, 0.24.0)
rvm (1.11.3.9)
sass (3.4.23)
sinatra (1.4.8, 1.4.7)
sinatra-contrib (1.4.7)
slop (4.4.1, 3.6.0)
test-unit (3.2.3, 3.1.5)
tilt (2.0.7, 2.0.5)

Please help !

kind  regards
kristoferus75

**Comment by laf** [comment]
@kristoferus75 Is this still an issue?

**Comment by kristoferus75** [comment]
Hi laf ! Yes from the oxidized man i got no answer  ! But if have now installed oxidized in a docker container and now it work also with and in librenms :-) docker container should not be the solution but ok it work ! You can close this ticket ! kind regards kristoferus75

**Comment by laf** [comment]
If it works in a docker container then it should be no different here. I can't close the issue so you'll need to :)
