### ISSUE TITLE
Support Flat output of versioned config via http

### ISSUE THREAD

**Issue by jgroom33** [ytti/oxidized#796]
It would be beneficial to use Oxidized as a source for configuration restoration.  This could be accomplished via support for fetching a specific file.

Current behavior:
https://<ip>/oxidized/node/fetch/<hostname>
displays flat text of config

Additional desired behavior:
https://<ip>/oxidized/node/version/fetch?node=<ip>&date=2017-04-03%2012:35:18%20+0000

**Comment by ytti** [comment]
This does sound like we're NIHing our own version management system. We'd need to have clear reason why ```git``` or some other existing one isn't doing it for us.

**Comment by jgroom33** [comment]
Preferably, the config would be available via http.

However, I agree that a better implementation would be an external git + http solution
