### ISSUE TITLE
Versioning not visible in Web UI 

### ISSUE THREAD

**Issue by packtman** [ytti/oxidized#799]
Hi,

I am not able to see versioning in my Oxidized UI. I made few changes in my switch for validation, but, the Oxidized UI just shows the last updated version and not the previous versions. 

Sharing below my configuration. Not sure, what I am missing exactly. 

Thanks.
[oxidized.txt](https://github.com/ytti/oxidized/files/900056/oxidized.txt)

**Comment by laf** [comment]
You are using the file output which doesn't support versioning afaik, you need to switch to git output.

**Comment by packtman** [comment]
You are right!! I can see it now :)
Thanks @laf

**Comment by laf** [comment]
No probs, please close this issue :)

**Comment by packtman** [comment]
@laf do you know if we can avoid versioning for some lines? For example: " System Up Time (days,hour:min:sec):" changes with time (for example 3600 seconds)? Can I skip it from versioning?

**Comment by laf** [comment]
Yes that can be excluded, here's an example PR https://github.com/ytti/oxidized/pull/70/files

You can either create your own model to overwrite the defaults or if it's genuinely an issue submit a pull request with the change.

**Comment by packtman** [comment]
Awesome! Thanks! Closing the issue.
