### ISSUE TITLE
telnet returns empty ios configs - ssh works fine on same device

### ISSUE THREAD

**Issue by banananananananana** [ytti/oxidized#817]
I've been ranting in this [thread](https://github.com/ytti/oxidized/issues/474) but i thought it was about time i made a post regarding this specific issue.

Right now, i have a router.db with a single cisco ios device - Catalyst 2960 (WS-C2960-24TC-L) IOS 15.0(2)SE2 (LANBASEK9)

I have over 200 of these devices... Some have telnet enabled, others use ssh.

If i poll the above device with telnet, it returns an empty config. If i use ssh, the full config is returned.

the debug log for telnet shows this:

```
Trying 10.10.10.123...
Connected to 10.10.10.123.

User Access Verification

Username: yourmom
Password:

switch1>enable

Password required, but none set
Password:
switch1#
switch1#terminal length 0
switch1#terminal width 0
switch1#show running-config
Building configuration...

Current configuration : 19690 bytes
!
! Last configuration change at 15:07:42 MEDT Wed Apr 19 2017 by yourmom
! NVRAM config last updated at 15:03:15 MEDT Wed Apr 19 2017 by yourmom
!
version 15.0
no service pad
service timestamps debug datetime localtime
service timestamps log datetime localtime
service password-encryption
etc. etc. etc
```

even though oxidized says:
`I, [2017-04-19T15:10:51.913344 #7193]  INFO -- : Configuration updated for cisco-device/10.10.10.123`
And the logs show great success:
```
cat logs/10.10.10.123-telnet | wc -l
641
cat logs/10.10.10.123-ssh | wc -l
633
```
The telnet results in an empty config file...

The ssh log looks similar, but it returns the expected config....

I really am at a loss here... I've tried messing about with so many things trying to solve this. But i've had no lock so far. I'm thinking it's the telnet.rb file that needs tweaking, but i can't put my finger on it.

**Comment by sanjmonkey** [comment]
see comments on: [issue 474](https://github.com/ytti/oxidized/issues/474)

**Comment by ytti** [comment]
What are you inputting from the model to the password prompt? Or does the password prompt just disappear? As we are looking for buffer to find prompt to determine end of command, it's crucial that we eat all prompts, so that we don't get desynchronised. I've commented on #474
