### ISSUE TITLE
raised Timeout::Error with msg "execution expired" - very long config

### ISSUE THREAD

**Issue by tstasevych** [ytti/oxidized#818]
I am having issue with Juniper SSG (ScreenOS). We have bunch of these devices and all of them are working great except for the one that has very long configuration (over 4000 lines). On debug it shows the following: 

`Apr 19 08:17:01 gitlab oxidized[1104]: W, [2017-04-19T08:17:01.521942 #1104]  WARN -- : JFW042 status no_connection, retry attempt 3
Apr 19 08:17:23 gitlab oxidized[1104]: W, [2017-04-19T08:17:23.768838 #1104]  WARN -- : 192.168.251.42 raised Timeout::Error with msg "execution expired"
Apr 19 08:17:43 gitlab oxidized[1104]: /var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/input/telnet.rb:107: warning: constant Net::Telnet::TimeoutError is deprecated
Apr 19 08:17:43 gitlab oxidized[1104]: W, [2017-04-19T08:17:43.791850 #1104]  WARN -- : 192.168.251.42 raised Timeout::Error with msg "timed out while waiting for more data"
Apr 19 08:17:44 gitlab oxidized[1104]: W, [2017-04-19T08:17:44.532348 #1104]  WARN -- : JFW042 status no_connection, retries exhausted, giving up
Apr 19 08:18:06 gitlab oxidized[1104]: W, [2017-04-19T08:18:06.956419 #1104]  WARN -- : 192.168.251.41 raised Timeout::Error with msg "execution expired"
Apr 19 08:18:27 gitlab oxidized[1104]: /var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/input/telnet.rb:107: warning: constant Net::Telnet::TimeoutError is deprecated
Apr 19 08:18:27 gitlab oxidized[1104]: W, [2017-04-19T08:18:27.015258 #1104]  WARN -- : 192.168.251.41 raised Timeout::Error with msg "timed out while waiting for more data"
Apr 19 08:18:27 gitlab oxidized[1104]: W, [2017-04-19T08:18:27.543060 #1104]  WARN -- : JFW041 status no_connection, retry attempt 1
Apr 19 08:18:49 gitlab oxidized[1104]: W, [2017-04-19T08:18:49.854887 #1104]  WARN -- : 192.168.251.41 raised Timeout::Error with msg "execution expired"
Apr 19 08:19:09 gitlab oxidized[1104]: /var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/input/telnet.rb:107: warning: constant Net::Telnet::TimeoutError is deprecated
Apr 19 08:19:09 gitlab oxidized[1104]: W, [2017-04-19T08:19:09.880236 #1104]  WARN -- : 192.168.251.41 raised Timeout::Error with msg "timed out while waiting for more data"
Apr 19 08:19:10 gitlab oxidized[1104]: W, [2017-04-19T08:19:10.553567 #1104]  WARN -- : JFW041 status no_connection, retry attempt 2
Apr 19 08:19:32 gitlab oxidized[1104]: W, [2017-04-19T08:19:32.856676 #1104]  WARN -- : 192.168.251.41 raised Timeout::Error with msg "execution expired"
Apr 19 08:19:52 gitlab oxidized[1104]: /var/lib/gems/2.3.0/gems/oxidized-0.19.0/lib/oxidized/input/telnet.rb:107: warning: constant Net::Telnet::TimeoutError is deprecated
Apr 19 08:19:52 gitlab oxidized[1104]: W, [2017-04-19T08:19:52.920365 #1104]  WARN -- : 192.168.251.41 raised Timeout::Error with msg "timed out while waiting for more data"
Apr 19 08:19:53 gitlab oxidized[1104]: W, [2017-04-19T08:19:53.569872 #1104]  WARN -- : JFW041 status no_connection, retry attempt 3
Apr 19 08:20:15 gitlab oxidized[1104]: W, [2017-04-19T08:20:15.853058 #1104]  WARN -- : 192.168.251.41 raised Timeout::Error with msg "execution expired"
`

When I turned on input debug and started tailing it, it would go about 2/3s of config through and then stops. After it timeouts, does it again and stops within 2-3 lines of a previous tailing. Almost looks like buffer is too small or something. When I just SSH from the oxidized user and get config, I get all of it.

Any ideas?

Thanks,
Tadey

**Comment by tstasevych** [comment]
@ytti , any idea about this one.

Thanks!

**Comment by packtman** [comment]
@tstasevych Did you try increasing the timeout to 200+? 240 worked for me for 8000+ lines.

**Comment by tstasevych** [comment]
@packtman, thank you, that was it!
