### ISSUE TITLE
How do I turn on debug on specific router

### ISSUE THREAD

**Issue by tstasevych** [ytti/oxidized#819]
Hello,

I would like to be able to debug one router at a time if i need to. I tried configuring maping, but it did not work for me. @ytti, would you please point to the right direction, if you got a moment. 

Thanks,
Tadey

**Comment by ytti** [comment]
This is not currently possible. I suggest changing source list for single node you're debugging.

**Comment by tstasevych** [comment]
Thank you for quick response.
