### ISSUE TITLE
Assistance with adding device support for Silku EtherHaul

### ISSUE THREAD

**Issue by bdg-robert** [ytti/oxidized#821]
I've confirmed these devices can be ssh'd to and their configurations displayed in the session. I tried to start writing my own model file but that's proven to be a bit of a daunting task for me, as I am not a coder. I'm willing to learn to write it and submit it to the project, but I'm afraid I'll need some help.

Is there any documentation on how to add models that I missed, or is anyone willing to assist me in writing a Siklu model file?

Here's what I have so far, using the edgeswitch.rb model file as a template - commented on the right with my thoughts/questions:

```
class Siklu < Oxidized::Model

# Siklu EtherHaul #

  comment ' #'

  prompt                                  # Not sure what yo put here
                                          # The command to show the configuration is correct on the next line, but I'm not certain what the following line is...
  cmd 'copy running-configuration display' do |cfg|
    cfg.each_line.to_a[2..-2].reject { |line| line.match /System Up Time.*/ or line.match /Current SNTP Synchronized Time.*/ }.join
  end

  cfg :telnet do                          # I'm not sure the Siklu supports telnet, so this may be unnecessary
    username /User(name)?:\s?/            #
    password /^Password:\s?/              #
  end

  cfg :ssh do                             # SSH only, I think
    post_login do                         # No enable or paging to deal with
    pre_logout 'exit'                     #
    pre_logout 'n'                        # Is the 'n' a new line?
  end

end
```

Here's output from an interactive session on how to pull the configuration from the device:

```
ssh noc@10.2.8.178
EH-1200F, S/N: F541137143, Ver:  7.0.0 16739
noc@10.2.8.178's password: 
LIT-BLK2-HERW>copy running-configuration display

User: 

# license configuring
set  license encryption status disable
set  license data-rate status 1000
set  license extend-mm status disable
set  license extra-range status disable
set  license oam status disable
set  license resiliency status disable
set  license synce status disable

# syslog configuring

# net-config configuring
set net-config config-file disable config-error-restart-delay 60 dhcp-relay disable

<-----Trimmed for brevity----->

# ieee1588 configuring
set ieee1588 admin down ptp-encapsulation unknown air-delay-correction 0

# aaa configuring
set aaa mode local shared-secret none connection-timeout 5 user-default-level user


LIT-BLK2-HERW>exit
exit
Connection to 10.2.8.178 closed.
```

I don't think there's an enable command, and comments in the configuration file are preceded with a '# '. Exit is how you end the session.

I haven't worked up the courage to try it yet, so hopefully someone can help me out with the bits I've annotated above.

**Comment by ytti** [comment]
```prompt```should be regexp of your prompt,  inyour case something like ```prompt /^[\w-]+>$/```

Remove telnet if you're note gonna test it.

Otherwise, give it a go, see what happens. 

In config:
```
input:
  debug: true
```

Creates session file, so you can see what the script saw, good luck.

**Comment by bdg-robert** [comment]
I'll make these changes and give it a go.

As for submitting this to be added to the main project - would the prompt not need to be agnostic? Our naming convention is basically everything before the ">" symbol.

**Comment by bdg-robert** [comment]
Went ahead and tried it - after Oxidized failed to start several times, I managed to get the model file down to this:

```
class Siklu < Oxidized::Model

  # Siklu EtherHaul #

  comment '# '

  prompt /^[\w-]+>$/

  cmd 'copy running-configuration display'

  cfg :ssh do
  end

end
```

The ssh debug log file shows a successful login and the configuration is displayed, however I see these warnings in the log file:

```
W, [2017-04-21T14:59:33.890929 #23807]  WARN -- : 10.2.30.2 raised Timeout::Error with msg "execution expired"
W, [2017-04-21T14:59:34.074686 #23807]  WARN -- : 10.2.30.2 status no_connection, retry attempt 1
W, [2017-04-21T14:59:55.768121 #23807]  WARN -- : 10.2.30.2 raised Timeout::Error with msg "execution expired"
W, [2017-04-21T14:59:56.077490 #23807]  WARN -- : 10.2.30.2 status no_connection, retry attempt 2
W, [2017-04-21T15:00:17.790586 #23807]  WARN -- : 10.2.30.2 raised Timeout::Error with msg "execution expired"
W, [2017-04-21T15:00:18.080736 #23807]  WARN -- : 10.2.30.2 status no_connection, retry attempt 3
W, [2017-04-21T15:00:40.597389 #23807]  WARN -- : 10.2.30.2 raised Timeout::Error with msg "execution expired"
W, [2017-04-21T15:00:41.084031 #23807]  WARN -- : 10.2.30.2 status no_connection, retries exhausted, giving up


```

Any idea what the issue might be? Do I need to leave in the `pre_logout 'exit'` statement?

**Comment by ytti** [comment]
add ```pre_logout "exit"```

Also does it print full config or will there be pager prompt  between each screen?

**Comment by bdg-robert** [comment]
I added the exit statement and the warnings cleared up.

There is no pagination, so that wasn't an issue. The only problem I see now, which is really only a cosmetic issue, is that at the beginning of the saved config I see the command we pass to print the config, and at the end of the config I see another prompt:

```
copy running-configuration display

User: 

# license configuring
set  license encryption status disable
set  license data-rate status 1000
set  license extend-mm status disable
set  license extra-range status disable

<-----Cut for brevity----->

# aaa configuring
set aaa mode local shared-secret none connection-timeout 5 user-default-level user


LIT-UP-TRAP>
```

**Comment by ytti** [comment]
You can add:

´´´
cmd :all do |cfg|
  cfg.each_line.to_a[1..-2].join
end
```

This removes first and last line of each command.

**Comment by bdg-robert** [comment]
That got it. I'll read up on how to submit the file for addition to the project - thanks for your help.
