### ISSUE TITLE
Oxidized Manager

### ISSUE THREAD

**Issue by mpking828** [ytti/oxidized#823]
Sorry if this is not the appropriate place for this.

I'm working up an install of oxidized, documenting it as I go with an eye towards linux newbie's such as myself.

I see someone has a web-based manager for oxidized https://github.com/justinjahn/oxidized-manager
Have you guys seen any other?  Any thoughts on the one I linked?

**Comment by laf** [comment]
Probably better to post this on Gitter: https://gitter.im/oxidized/Lobby?source=orgpage

**Comment by mpking828** [comment]
Thanks!
