### ISSUE TITLE
Backup of PFSense : tag </pfsense> is missing

### ISSUE THREAD

**Issue by adminrezo** [ytti/oxidized#825]
Hi,

Thanks for your work with Oxidized.

I use oxidized for my Cisco network devices and it works well.
With PFsense the config file is copied but the last tag </pfsense> is missing.
So I can't restore my config to PFsense.

When I add it manually, restore is OK.

My config : 
Debian 8, Oxidized 0.19
Output Git.

Thanks in advance for your help.

**Comment by ytti** [comment]
Copy ```https://github.com/ytti/oxidized/blob/master/lib/oxidized/model/pfsense.rb```to ~/.config/oxidized/model/pfsense.rb and modify it.

First thing I'd try is to change ```cmd :all``` so that ```-2``` is changed to ```-1```. This may help, if I understood your problem correctly.

**Comment by adminrezo** [comment]
Works very well.
Thx !
