### ISSUE TITLE
Number of threads

### ISSUE THREAD

**Issue by ivarhjulben** [ytti/oxidized#829]
Hi

I have read the post https://github.com/ytti/oxidized/issues/457 about have threads are created and I think the idea is good.

In my small test setup only one thread is created. If one or more device backup jobs hangs and waits for "timeout x retries" to proceed with the next backup job then it's not possible in Oxidized Web to do a reload for a node during this time.

I don't know the best algorithm or if it's easy to fix, but I was thinking that if no matter how many threads that are in use - one extra free thread could be created for something like this?
(of course up the number of Oxidized.config.threads)

Cheers,
Martin

**Comment by ytti** [comment]
Oxidized web is in its own thread already, but some methods are locked to single thread access, so that oxidized web cannot handle them at the same time as we're handling node config.

Reload does nothing but reloads list of nodes, i.e. rereads ```source```.  While threads are fetching config from the device, they are not locking any state, so I'm not sure what is going on. We only lock state while we're processing fetched config.

**Comment by ivarhjulben** [comment]
Sorry I meant the update button next to each node :-)

**Comment by ytti** [comment]
The update button only moves device to the head of the queue. You can put ```next_adds_job: true``` in configuration to force addition of new job (thread) when movings something to head of the queue. https://github.com/ytti/oxidized/blob/master/lib/oxidized/nodes.rb#L76

**Comment by ivarhjulben** [comment]
Thanks, I will try that :-)

**Comment by laf** [comment]
@ytti is it possible to cut a release so we can make use of that option?

**Comment by ytti** [comment]
I'll try to get around to it this weekend, if not, bump the thread.

**Comment by InsaneSplash** [comment]
*bump* :)

**Comment by deepseth** [comment]
Looks like this was pushed in 0.20.0

> FEATURE: next-adds-job config toggle (to add new job when ever /next is called)

Tested requesting /next for two notes simultaneously and got results for both together. Looks like this works.

**Comment by laf** [comment]
@ivarhjulben Is your issue now solved?
