### ISSUE TITLE
Oxidized crashes after some time

### ISSUE THREAD

**Issue by petoma** [ytti/oxidized#830]
HI,
after some time (30-60minutes) oxidized just crashes  with the following error:
```
pi@raspberrypi:~$ more .config/oxidized/crash 
--------------------------------------------------
2017-05-05 20:34:04 UTC
can't be called from trap context [ThreadError]
--------------------------------------------------
/var/lib/gems/2.1.0/gems/oxidized-0.19.0/lib/oxidized/nodes.rb:126:in `synchronize'
/var/lib/gems/2.1.0/gems/oxidized-0.19.0/lib/oxidized/nodes.rb:126:in `with_lock'
/var/lib/gems/2.1.0/gems/oxidized-0.19.0/lib/oxidized/nodes.rb:10:in `load'
/var/lib/gems/2.1.0/gems/oxidized-0.19.0/lib/oxidized/core.rb:17:in `block in initialize'
/var/lib/gems/2.1.0/gems/oxidized-0.19.0/lib/oxidized/core.rb:37:in `call'
/var/lib/gems/2.1.0/gems/oxidized-0.19.0/lib/oxidized/core.rb:37:in `sleep'
/var/lib/gems/2.1.0/gems/oxidized-0.19.0/lib/oxidized/core.rb:37:in `run'
/var/lib/gems/2.1.0/gems/oxidized-0.19.0/lib/oxidized/core.rb:28:in `initialize'
/var/lib/gems/2.1.0/gems/oxidized-0.19.0/lib/oxidized/core.rb:4:in `new'
/var/lib/gems/2.1.0/gems/oxidized-0.19.0/lib/oxidized/core.rb:4:in `new'
/var/lib/gems/2.1.0/gems/oxidized-0.19.0/lib/oxidized/cli.rb:12:in `run'
/var/lib/gems/2.1.0/gems/oxidized-0.19.0/bin/oxidized:9:in `<top (required)>'
/usr/local/bin/oxidized:23:in `load'
/usr/local/bin/oxidized:23:in `<main>'
--------------------------------------------------
```

and since I am not a programmer, I am asking for a help here.

```
pi@raspberrypi:~$ more .config/oxidized/config
---
username: oxidized
password: heslo
model: ios
interval: 3600
use_syslog: false
debug: false
threads: 30
timeout: 5
retries: 1
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: webpage:8888
vars: {}
groups: {}
pid: "/home/pi/.config/oxidized/pid"
input:
  default: ssh, telnet
  debug: false
  ssh:
    secure: false
output:
  default: git
  git:
      user: oxidized
      email: oxidized@nebesa.sk
      repo: "~/.config/oxidized/oxidized.git"
source:
  default: http
  debug: false
  http:
    url: http://webpage:8080/api/v0/oxidized
    scheme: http
    delimiter: !ruby/regexp /:/
    map:
      name: hostname
      model: os
      group: group
    headers:
      X-Auth-Token: 'token'

model_map:
  cisco: ios
  juniper: junos
```

thank you

**Comment by ytti** [comment]
Are you sure the PID isn't receiving trap, like SIGINT?

**Comment by petoma** [comment]
hi, I am sorry for stupid question. but what is SIGINT and how to make sure it is not receiving any traps? 
and there is no PID, when after it crashed:
pi@raspberrypi:~$ ps -aux | grep oxid
pi       27074  0.0  0.1   4276  1848 pts/1    S+   12:57   0:00 grep --color=auto oxid

pi@raspberrypi:~/.config/oxidized$ ls 
config  config.old  configs  crash  logs  oxidized.git  router.db

thank you

**Comment by ytti** [comment]
I mean are you trying to send it any signal (i.e. via kill or otherwise). It looks like it may be broken signal handling. Perhaps your init/systemd etc system tries to send the process a signal? 

Can you correlate it with something else happening in the system at that time, something else which might cause it to send some signal to the process.

**Comment by petoma** [comment]
hi, the oxidized process crashes without my interaction. I ran it again nad set log: in an oxidized config file so I will see the result in few moments. thank you

**Comment by ytti** [comment]
I don't think we log trap handling at all. My suspicion right now is that something in your system is  sending some signal to it, and we're trapping it incorrectly.
Perhaps something is trying to restart the process or restart systemd/init/

**Comment by petoma** [comment]
hi, here is what log says:
F, [2017-05-07T 16:16:21.646017 #2853] FATAL -- : Oxidized crashed, crashfile written in /home/pi/.config/oxidized/crash


syslog:
2017-05-07 16:17:01 localhost	CRON	pam_unix(cron:session): session opened for user root by (uid=0)	0	
2017-05-07 16:16:21 localhost	SSHD	pam_unix(sshd:session): session closed for user pi	0
2017-05-07 16:16:01 localhost	CRON	pam_unix(cron:session): session closed for user librenms	0
2017-05-07 16:16:01 localhost	CRON	(librenms) CMD ( /opt/librenms/alerts.php >> /dev/null 2>&1)	0
2017-05-07 16:16:01 localhost	CRON	pam_unix(cron:session): session opened for user librenms by (uid=0)

**Comment by ytti** [comment]
Guess you could try adding bunch of traps here: https://github.com/ytti/oxidized/blob/master/bin/oxidized#L5 and on existing ones output some string to let you know it was hit.

**Comment by petoma** [comment]
ehm, I am sorry for the stupid question (again) but what exactly should I add on the line 5? :)
thank you

**Comment by ytti** [comment]
If you're not comfortable debugging the code, then probably nothing. How are you refreshing your list of nodes? Are you perhaps sending HUP to the process, and is this always happening when you send HUP?

https://github.com/ytti/oxidized/blob/0b5af4573c7832f7fb1eeeb39c5e8c7375936bfd/lib/oxidized/core.rb#L17

**Comment by petoma** [comment]
hi,

pi@raspberrypi:~/.config/oxidized$ more /var/lib/gems/2.1.0/gems/oxidized-0.19.0/lib/oxidized/core.rb 
module Oxidized
  class << self
    def new *args
      Core.new args
    end
  end

  class Core
    class NoNodesFound < OxidizedError; end

    def initialize args
      Oxidized.mgr = Manager.new
      Oxidized.Hooks = HookManager.from_config(Oxidized.config)
      nodes        = Nodes.new
      raise NoNodesFound, 'source returns no usable nodes' if nodes.size == 0
      @worker      = Worker.new nodes
      trap('HUP') { nodes.load }
      if Oxidized.config.rest?
        begin
          require 'oxidized/web'
        rescue LoadError
          raise OxidizedError, 'oxidized-web not found: sudo gem install oxidized-web - \
          or disable web support by setting "rest: false" in your configuration'
        end
        @rest        = API::Web.new nodes, Oxidized.config.rest
        @rest.run
      end
      run
    end

    private

    def run
      Oxidized.logger.debug "lib/oxidized/core.rb: Starting the worker..."
      while true
        @worker.work
        sleep Config::Sleep
      end
    end
  end
end

**Comment by ytti** [comment]
It's not clear to me what you hoped to accomplish with that reply. How are you refreshing list of your nodes?

**Comment by petoma** [comment]
my bad :) I misunderstood the question...I integrated the oxidized with librenms and the source of nodes is librenms.

**Comment by ytti** [comment]
Can you confirm if this happen same time as librenms is issuing /reload to oxidized? If you turn off rest, does it stop from happening?

**Comment by laf** [comment]
LibreNMS (latest master) only does a reload when a new device is added or a device is set to be rediscovered so if the crash within 5 minutes it could be a correlation - however we merely call the reload api call via oxidized-web (i.e. Same as clicking reload from the webui)

**Comment by ytti** [comment]
I don't think LibreNMS is doing anything wrong, I fear we're doing something wrong handling traps. But the API itself shouldn't be a trap, so that wouldn't explain it.

**Comment by laf** [comment]
I was just confirming how the process worked from our side :)

**Comment by petoma** [comment]
well, the interesting thing is that the oxidized process has been up for more than 3 hours now. it saved the configuration of my router and since then no config backup occurred (according to logs). But when the rest is disabled, how am I suppose to view the backup file? thank you

**Comment by ytti** [comment]
I'm not offering it as solution, I'm offering it as means to gather more information. 

If you keep rest on, and manually surf curl http://url/reload - what happens?

**Comment by petoma** [comment]
hi, it says "reloaded list of nodes" and in logs I see that  it loads the nodes again: INFO -- : lib/oxidized/nodes.rb: Loaded 1 nodes and the oxidized keeps running with the same process ID.

**Comment by ytti** [comment]
Can you run the oxidized-web through NGINX for example and log queries, to see what is being asked when it crashes.

**Comment by petoma** [comment]
Hi. I do not know why but it works now. I put back rest option and no crash since this morning. Every one hour oxidized checks the router and if needed backs up the config. Now the question how to set up the automatic backup based on config change? And does oxidized supportes something like clogin from rancid? Thank you very much for your time and help

**Comment by laf** [comment]
Oxidized will perform config backups based on the interval you define in your config.

For clogin, you can use `oxs`

**Comment by petoma** [comment]
and how to turn on this feature? syslog udp+file example to catch config change event (ios/junos) and trigger config fetch

thank you

**Comment by laf** [comment]
I believe this is the example included for this: https://github.com/ytti/oxidized/blob/master/extra/syslog.rb

I don't know how you make use of it personally, we use utilise something else for syslog and then just hit the oxidized api to initiate a config backup.

**Comment by petoma** [comment]
ok. I will take a look at it. I believe I can close the issue, everything works now. thank you all for your help and time.
