### ISSUE TITLE
Add support for HP 1910's

### ISSUE THREAD

**Issue by tracerrx** [ytti/oxidized#832]
`WARN: tilt autoloading 'tilt/sass' in a non thread-safe way; explicit require 'tilt/sass' suggested.
W, [2017-05-08T13:37:03.023411 #28431]  WARN -- : 10.10.10.101 raised Oxidized::PromptUndetect with msg "
******************************************************************************
* Copyright (c) 2010-2016 Hewlett Packard Enterprise Development LP          *
* Without the owner's prior written consent,                                 *
* no decompiling or reverse-engineering shall be allowed.                    *
******************************************************************************

<HP> not matching configured prompt (?-mix:^\r?([\w -]+\eE)?([\w-]+# )$)"`

**Comment by laf** [comment]
You should format the example by wrapping it around "```" at the top and bottom (without the ")

**Comment by tracerrx** [comment]
Fixed... Changed type from procurve to comware
