### ISSUE TITLE
fortios - vlan configuration not saved

### ISSUE THREAD

**Issue by networkpadawan** [ytti/oxidized#834]
In fortios, the backup that is run does not save the configuration of vlan interfaces associated with a given vdom. i think it is because the script is not entering the vdom to do the backup, and is only saving the configuration of policies. anyone else with fortigates having this issue?

**Comment by ytti** [comment]
I don't have fortigate, someone with those boxes probably wants to fix the model.

**Comment by gbeekmans** [comment]
I'm using Oxidized to track over 50 Fortigates ranging from the bigger 600C units to the smaller 80C ones on all different versions of firmware. I haven't noticed missing VLAN interfaces in the config Oxidized pulls out.

In my Oxidized generated file I see the following (trimmed to make it readable):

config global
...
config system interface
    edit "My VLAN Name"
        set vdom "root"
        set ip a.b.c.d 255.255.255.0
        set vlanid xxx
    next
    edit "My Other VLAN"
        set vdom "another_vdom"
        set ip e.f.g.h 255.255.255.0
        set vlandid yyy
    next
end

I just ran a diff on the Oxidized generated file and a backup file generated by the Fortigate Web GUI (where I chose Full Backup). They are identical aside from expected slight changes in time stamps, private key encryption and so on. All interfaces, vdoms, VLANs, policies, etc are accounted for.

What are you missing? I'd like to make sure I'm not missing anything myself, either.

**Comment by laf** [comment]
@networkpadawan Do you see the same thing or are you missing something else?

**Comment by networkpadawan** [comment]
Hi, sorry for the delay.
On my Case it was the user that I used.
it needs to be a superadmin to get the full configuration. if you use a vdom admin user you won´t be able to get all the config:)

**Comment by laf** [comment]
@networkpadawan can we close this now then?

**Comment by networkpadawan** [comment]
yes! of course, forgot to do so.
