### ISSUE TITLE
apc_aos Model Map Issues

### ISSUE THREAD

**Issue by tracerrx** [ytti/oxidized#835]
I keep getting:

> [2017-05-09T10:39:33.618354 #3609] ERROR -- : node {:name=>"apc-1", :model=>"apc", :username=>"apc", :password=>"MYPW", :vars=>{:enable=>"enablepassword"}} raised Oxidized::ModelNotFound with message 'apc not found for node 10.10.10.241'

I have tried both apc_aos, Apc_aos in the router.rb config and as mappings to "apc" in all sort of cases... Any ideas?

**Comment by ytti** [comment]
The model name is same as the filename, i.e. ```apc_aos``` are you sure you have that model file?

**Comment by davromaniak** [comment]
Hi.

The correct mapping in the "model_map" section is `apc: apc_aos` (I use it with Observium db as the SQL source) if you have "apc" in the model field of your source.

Thanks.
