### ISSUE TITLE
[Q] Reverse proxy using subfolder?

### ISSUE THREAD

**Issue by soakes** [ytti/oxidized#839]
Hi guys,

I have been trying to run oxidized behind an apache reverse proxy and sadly failing.

Now this all works fine if you give it the whole domain/subdomain i.e. https://example.com or https://oxidized.example.com however, what I am trying to achieve is the following.

I would like to stick it in a sub folder like: https://manage.example.com/oxidized

I have tried several different configs which usually work with most web apps but they don't seem to work with this.  

I believe I know the problem is, that I don't believe you have support for baseurl i.e. /oxidized/ and so the app is hard encoded with always going to the root instead hence lookup fails.

Unless I am really blind in the docs/code but I can't seem to find this option anywhere.  If this is the case, I believe it would be nice if you could add this support to save us having to remember 100's of urls/domains/subs.

Thanks for reading.

**Comment by laf** [comment]
Works for me:

In oxidized config
`rest: 0.0.0.0:8443/oxidized`

**Comment by soakes** [comment]
Confirmed works.

I feel so bad, I didn't even think to try that.  So sorry for the noise.

**Comment by laf** [comment]
No worries :) Don't forget to close the issue :D

**Comment by soakes** [comment]
Thanks 👍

**Comment by soakes** [comment]
Just to make this complete, heres my config for Apache 2.4 using .htaccess

1) Create your sub folder/sub-directory within your document root.
2) Create the following .htaccess file inside the new sub-directory that you have just created (beware may need adjusting as this forces SSL)

```
RewriteEngine On
RewriteCond %{HTTPS} !=on
RewriteCond %{ENV:HTTPS} !=on
RewriteRule .* https://%{SERVER_NAME}%{REQUEST_URI} [R=301,L]
RewriteRule (.*) http://127.0.0.1:8081/oxidized/$1 [P]
DirectoryIndex disabled
```
3) Adjust your oxidized config file as shown by @laf and restart the oxidized service.

If you would like to add some authentication, so that your configs are protected.  Please add the following config at the end of the first bunch of code. 

```
AuthType           Digest
AuthName           "oxidized"
AuthUserFile       /var/apache/virtual/manage.example.com/httpdocs/.htdigest 
BrowserMatch       "MSIE"      AuthDigestEnableQueryStringHack=On
Require            valid-user
```
**N.B**: Make sure you fix/correct the path to suit your environment.

Lastly you will need to create your password file with the following command:

`htdigest -c .htdigest oxidized username`

**N.B**: -c creates a new file, do not use this if your adding users to existing file as it will wipe the contents.

Last thing to note, you may need to add auth_digest to apache and if your on a debian based distro you can simply do:

`a2enmod auth_digest`

You always can substitute the digest auth with auth_basic, just beware that basic has flaws, as the data is sent in plain text where digest auth isn't.  

Digest auth will run safely even under non-ssl environments and personally it is a good habit/practice to do even if all your sites are SSL.  

Hope this info is useful to some of you who's struggling with a working decent config.

**Comment by geordish** [comment]
Just to add to this.

If you are running https only, there are a couple of places where the generated links are HTTP.

You can fix that in your apache config by adding:
```apache
ProxyPass / http://127.0.0.1:8888/
ProxyPassReverse / http://127.0.0.1:8888/
RequestHeader set X-Forwarded-Proto "https"
```

You will also need to enable some modules
```bash
a2enmod headers
a2enmod proxy
```

**Comment by soakes** [comment]
You can, however the rewrite condition will automatically convert any non-ssl traffic to SSL i.e. http to https so this isn't directly needed, however its still a nice touch tho.

**Comment by deajan** [comment]
Some solution that works for me using a reverse proxy and a subdirectory in apache:

First, modify your oxidized config file to include your subdirectory.
Example for subdirectory 'oxidized' you'll het 

`rest: 0.0.0.0:8888/oxidized`

Then setup an apache reverse proxy like this
```
        ProxyPass /oxidized http://localhost:8888/oxidized
        ProxyPassReverse /oxidized http://localhost:8888/oxidized
        # Add this line if your virtualhost uses SSL
        RequestHeader set X-Forwarded-Proto "https"

        # Add the following block if you want to limit oxidized access to localhost, and ask for a password for anyone else
        # Create the .htpasswd file with `htpasswd` command.
        <Location /oxidized>
                AuthUserFile /var/www/default/ftp/www/.htpasswd
                AuthName "Restricted Access"
                AuthType Basic
                Require ip 127.0.0.1
                Require valid-user
        </Location>
```

**Comment by chrisch80** [comment]
@deajan: Just a small question to your config (which is by the way working fine) or generally a discussion for all:

In your config (or generaly if reverse proxy is used) there are later the following possiblities to access oxidized:
1. http(s)://<server-ip>/oxidized ... that is the reverse proxy way which will forward internaly to http://localhost:8888/oxidized but not visible for the user.
2. http(s)://<server-ip>:8888/oxidized ... that is the direct way. But here is no Auth available? Isn't it? This seems to be a security issue if somebody knows the used port?
It maybe make sense to change the oxidized config line:
rest: 0:0:0:0:8888/oxidized
to
rest: localhost:8888/oxidized
In this case only the reverse proxy can access/forward to oxidized the directly way without Auth is not available anymore.
