### ISSUE TITLE
REST API Documentation

### ISSUE THREAD

**Issue by os2tux** [ytti/oxidized#844]
Is there any documentation on the REST API endpoints available to Oxidized? I went through the README file but didn't find anything specific to or referencing this. Thanks in advance!

**Comment by ytti** [comment]
Not really, oxidized-web code is pretty much the all you got, sorry

**Comment by jcshelby** [comment]
No worries - just thought I'd ask. I'll read through that and follow up with any other questions I have. Thanks for the confirmation!
