### ISSUE TITLE
Multi-Level REST API JSON Support

### ISSUE THREAD

**Issue by InsaneSplash** [ytti/oxidized#845]
Currently Oxidized only seems to only support JSON data mapping values 1 level deep. Some systems provide this data deeper in the JSON tree and therefore one cannot use the API as a source for node information.

If there a way to map it to a lower level?

ie
```
"results": [
        {
            "platform": {
                "id": 12,
                "name": "ProCurve",
                "slug": "procurve"
            },
      }
]
```

**Comment by ytti** [comment]
This is supported:

https://github.com/ytti/oxidized/commit/ddbfedc97c5add661286d0f12c4ac98275dbeb82

**Comment by InsaneSplash** [comment]
Would you perhaps have an example for me?

**Comment by ytti** [comment]
Separate the keys with dot in the map. You will also need latest oxidized (0.20.0 or git)

**Comment by InsaneSplash** [comment]
AH! ok I am currently running 0.19. :)
I see 0.20 was released 4hrs ago 👍
