### ISSUE TITLE
Source API JSON multi-tier error

### ISSUE THREAD

**Issue by InsaneSplash** [ytti/oxidized#847]
When trying to use a multi-tier json http source, the following error is being generated. My map values are in the format x.y.z

```
no implicit conversion of String into Integer
/var/lib/gems/2.3.0/gems/oxidized-0.20.0/lib/oxidized/source/http.rb:44:in `dig': no implicit conversion of String into Integer (TypeError)
        from /var/lib/gems/2.3.0/gems/oxidized-0.20.0/lib/oxidized/source/http.rb:44:in `block (2 levels) in load'
        from /var/lib/gems/2.3.0/gems/asetus-0.3.0/lib/asetus/configstruct.rb:21:in `each'
        from /var/lib/gems/2.3.0/gems/asetus-0.3.0/lib/asetus/configstruct.rb:21:in `each'
        from /var/lib/gems/2.3.0/gems/oxidized-0.20.0/lib/oxidized/source/http.rb:42:in `block in load'
        from /var/lib/gems/2.3.0/gems/oxidized-0.20.0/lib/oxidized/source/http.rb:38:in `each'
        from /var/lib/gems/2.3.0/gems/oxidized-0.20.0/lib/oxidized/source/http.rb:38:in `load'
        from /var/lib/gems/2.3.0/gems/oxidized-0.20.0/lib/oxidized/nodes.rb:15:in `block in load'
        from /var/lib/gems/2.3.0/gems/oxidized-0.20.0/lib/oxidized/nodes.rb:127:in `synchronize'
        from /var/lib/gems/2.3.0/gems/oxidized-0.20.0/lib/oxidized/nodes.rb:127:in `with_lock'
        from /var/lib/gems/2.3.0/gems/oxidized-0.20.0/lib/oxidized/nodes.rb:10:in `load'
        from /var/lib/gems/2.3.0/gems/oxidized-0.20.0/lib/oxidized/nodes.rb:122:in `initialize'
        from /var/lib/gems/2.3.0/gems/oxidized-0.20.0/lib/oxidized/core.rb:14:in `new'
        from /var/lib/gems/2.3.0/gems/oxidized-0.20.0/lib/oxidized/core.rb:14:in `initialize'
        from /var/lib/gems/2.3.0/gems/oxidized-0.20.0/lib/oxidized/core.rb:4:in `new'
        from /var/lib/gems/2.3.0/gems/oxidized-0.20.0/lib/oxidized/core.rb:4:in `new'
        from /var/lib/gems/2.3.0/gems/oxidized-0.20.0/lib/oxidized/cli.rb:12:in `run'
        from /var/lib/gems/2.3.0/gems/oxidized-0.20.0/bin/oxidized:9:in `<top (required)>'
        from /usr/local/bin/oxidized:23:in `load'
        from /usr/local/bin/oxidized:23:in `<main>'
```

**Comment by InsaneSplash** [comment]
it starts to run through the returned json data, but after the first part of the entry it breaks.
I see this with a `puts node.inspect` 

```
["count", 1591]
no implicit conversion of String into Integer
```

**Comment by InsaneSplash** [comment]
seems the problem is that the result hash may contain an array of values which ruby is trying to parse as a hash...I could be wrong?

**Comment by ytti** [comment]
You should tell what your input (JSON) is and what is your config. But I believe we discussed this in chat, and you had object [ object ], which means it won't work. As we only support:

```key1.key2.key3.key4``` we do not support
```key1[ary_element].key2.key3.key4```

**Comment by Ynnot** [comment]
look at your password in config file if you don't have """" add them. I already have this problem and when i add """" it was ok.

**Comment by InsaneSplash** [comment]
I tried to modify the code to detect the array element and expand it, but my Ruby skills seem to be faling short. I will keep on though.

**Comment by ytti** [comment]
Just spit-balling here.

Today:
```  
def dig(key, *rest)
      value = self[key]
      if value.nil? || rest.empty?
        value
      elsif value.respond_to?(:dig)
        value.dig(*rest)
      else # foo.bar.baz (bar exist but is not hash)
        return nil
      end
end
```

Something like this pseudoish code, mindstream, wrote straight to the comment window, mainly for inspiration. You should test externally, not with oxidized, to simplify your problem.

```
def dig(key, *rest)
  value = self[key]
  key, ary_index = key.split('[')
  if ary_index
    value = self[ary_index.chop.to_i]
  end
  if value.nil? || rest.empty?
    value
   elsif value.respond_to?(:dig)
     value.dig(*rest)
   else
      return nil
    end
end
```

Intention is that if key contains [42],  say 'moi[42]', we assume that behind 'moi' key there is an array, and from that array we want index 42. Which then may be value or may be object. 
However if it's another array, we're screwed again, so  code probably should support 'moi[42][66]', etc at arbitrary length, i.e. you should actually return array of potential array indeces, and recursively assign next and next value. Maybe #inject is your friend.

Again, write entirely separate code for it, so it's faster to test.

**Comment by InsaneSplash** [comment]
wow you must see the matrix! :)

**Comment by wk** [comment]
@InsaneSplash if you have since gotten further and have implemented this functionality, a PR is welcome!
