### ISSUE TITLE
telnet with procurve

### ISSUE THREAD

**Issue by Ynnot** [ytti/oxidized#857]
Hi !

I try to test telnet for my hp procurve but it doesn't works my input config file : 
input:
  default: ssh, telnet
  debug: true
  ssh:
    secure: false
Do i Have to add something ? 
Or can we use ssh1 because procurve didn't work with ssh2

thank you guys

**Comment by ytti** [comment]
We do not support SSHv1 at all currently. I don't think there is ruby library for SSHv1, but if there is, I am open to adding the support.
OpenSSH does not support SSHv1 either anymore, so forking to it isn't really an option.

Your input config at least does not prohibit your procurve from working. But ```it doesn't works``` is not sufficient detail to really investigate the problem.

As you have input debugging on, it should create file of session log when trying to connect, what does that file contain? Any crash files? Anything in logs?

**Comment by Ynnot** [comment]
when i started oxidized i have this message for my procurve : 

W, [2017-05-17T10:24:45.281887 #11927]  WARN -- : X.X.X.X raised Net::SSH::Exception (rescued RuntimeError) with msg "incompatible SSH version `SSH-1.5-OpenSSH_2.9p1'"
/var/lib/gems/2.3.0/gems/oxidized-0.20.0/lib/oxidized/input/telnet.rb:107: warning: constant Net::Telnet::TimeoutError is deprecated
W, [2017-05-17T10:25:05.434439 #11927]  WARN -- : X.X.X.X raised Timeout::Error with msg "timed out while waiting for more data"
W, [2017-05-17T10:25:06.173547 #11927]  WARN -- : XXXX status no_connection, retry attempt 1
W, [2017-05-17T10:25:06.537913 #11927]  WARN -- : X.X.X.X raised Net::SSH::Exception (rescued RuntimeError) with msg "incompatible SSH version `SSH-1.5-OpenSSH_2.9p1'"
/var/lib/gems/2.3.0/gems/oxidized-0.20.0/lib/oxidized/input/telnet.rb:107: warning: constant Net::Telnet::TimeoutError is deprecated
W, [2017-05-17T10:25:26.667523 #11927]  WARN -- : X.X.X.X raised Timeout::Error with msg "timed out while waiting for more data"
W, [2017-05-17T10:25:27.178449 #11927]  WARN -- : XXXX status no_connection, retry attempt 2
W, [2017-05-17T10:25:27.673435 #11927]  WARN -- : X.X.X.X1 raised Net::SSH::Exception (rescued RuntimeError) with msg "incompatible SSH version `SSH-1.5-OpenSSH_2.9p1'"


Do I have to change the timeout ? 
thanks

**Comment by Ynnot** [comment]
I up timeout from 20 to 60 but it's still the same.

**Comment by ytti** [comment]
We need to see what the telnet is doing, probably it is not seeing your prompt or something. With:
```
input:
  debug: true
```

it'll create file with telnet string and the device IP/name, and you should then see what the telnet session is seeing.

**Comment by Ynnot** [comment]
yes i have this file in log : @iP-telnet with this content : 

RESTRICTED RIGHTS LEGEND

^M Use, duplication, or disclosure by the Government is subject to restrictions
^M as set forth in subdivision (b) (3) (ii) of the Rights in Technical Data and
^M Computer Software clause at 52.227-7013.

^M         HEWLETT-PACKARD COMPANY, 3000 Hanover St., Palo Alto, CA 94303

^M^[[1;24r^[[20;1H^[[20;1HPlease Enter Login Name: ^[[?25h^[[20;1H^[[?25h^[[20;26H^[[20;26H^[[?25h^[[20;26HTrying _@IP...
Connected to @IP.
^[[2J^[[?7l^[[3;23r^[[?6l^[[1;1H^[[?25l^[[1;1HHP J4813A ProCurve Switch 2524
^MSoftware revision F.05.79

^MCopyright (C) 1991-2014 Hewlett-Packard Co.  All Rights Reserved.

**Comment by Ynnot** [comment]
i think the proble is frome the enable login passaword which is the same to logon on the device i know we can add this : 
models: 
  procurve:
      username: User
      password: Password
      vars:
        enable: Password

But can we set the user in the vars: enable: ? knowing that this is the same User/password

**Comment by ytti** [comment]
Well to me it looks like it is not finding the login prompt:
https://github.com/ytti/oxidized/blob/master/lib/oxidized/model/procurve.rb#L56

That looks nothing like your login prompt, which appear to be 'Please Enter Login Name:'

I'm not sure what you're trying to say, or why you think it has something to do with enable.

**Comment by Ynnot** [comment]
for me it seems that he succeed to enter the first login pwd cause that' say : ^M^[[1;24r^[[20;1H^[[20;1HPlease Enter Login Name: ^[[?25h^[[20;1H^[[?25h^[[20;26H^[[20;26H^[[?25h^[[20;26HTrying _@IP...
Connected to @ip.

then when i'm going on my procurve device i have to connect with enable to get the config backup so it's why i think the problem is from enable login password.

**Comment by ytti** [comment]
What does the login process look to you normally? Are you saying 'please enter login name' isn't your first login prompt to the device? I don't see any passport prompt, so to me it looks like it is waiting for login prompt ,which never comes, because it does not match the regexp.

**Comment by Ynnot** [comment]
in fact it say 
Please Enter Login Name:
Please Enter Password:

so i enter login and password but then if i want to get my config i have to type enbale and he ask me again 
Please Enter Login Name:
Please Enter Password:

with the same login password

**Comment by ytti** [comment]
Well those prompts do not seem to match at all on what the model expects.

So either the model needs to be modified for those, or you need to change them. I don't know if those are standard in some procurve model or are  you perhaps setting them via TACACS.

**Comment by Ynnot** [comment]
we found the solution but we have to put the hostname of the device follow by > so now i tried many regex to match with all device hostname :)

**Comment by ytti** [comment]
Well that's pretty terrible workaround.

**Comment by Ynnot** [comment]
so for the telnet it's ok but now i think it's really an enable problem. this is last lines of my @IP-telnet file : 

^M^[[1;24r^[[24;1H^[[24;1H^[[2K^[[24;1H^[[?25h^[[24;1H^[[24;1Hsd-sw1-f11> ^[[24;1H^[[24;13H^[[24;1H^[[?25h^[[24;13H^[[24;13Hshow syste^[[24;13H^[[?25h^[[24;23H^[[24;23Hm informat^[[24;23H^[[?25h^[[24;33H^[[24;33Hion^[[24;33H^[[?25h^[[24$

^M^[[1;24r^[[24;1H^[[24;1H^[[2K^[[24;1H^[[?25h^[[24;1H^[[24;1Hsd-sw1-f11> ^[[24;1H^[[24;13H^[[24;1H^[[?25h^[[24;13H^[[24;13Hshow runni^[[24;13H^[[?25h^[[24;23H^[[24;23Hng-config^[[24;23H^[[?25h^[[24;32H^[[24;0H^[E^[[24;1H^[[24;32H^[[24;$

^M^[[1;24r^[[24;1H^[[24;1H^[[2K^[[24;1H^[[?25h^[[24;1H^[[24;1Hsd-sw1-f11> ^[[24;1H^[[24;13H^[[24;1H^[[?25h^[[24;13H^[[24;13Hlogout^[[24;13H^[[?25h^[[24;19H^[[24;0H^[E^[[24;1H^[[24;19H^[[24;1H^[[2K^[[24;1H^[[?25h^[[24;1H^[[1;24r^[[24;1H^$

**Comment by ytti** [comment]
There isn't any enable code in the model, so I  don't think it would even try to enable.

**Comment by Ynnot** [comment]
ok thank you i'll try to add line code in procurve.rb to set the enable !

**Comment by Ynnot** [comment]
Hi !

Telnet and enable are now set but when i get my config backup i can only see until the third interface and when i see the whole config backup : 

This is the configuration in web interface : 
! Image stamp:    /ff/Ff/Ff/Ff
!                 May 15 2014 18:20:03
!                 F.05.79
!                 1373
! 
!  Status and Counters - General System Information
! 
!   System Name        : hostname                                      
!   System Contact     : oxidized@oxidized.Fr                              
!   System Location    : here          
! 
!   MAC Age Time (sec) : 300    
! 
!   Time Zone          : 60   
!   Daylight Time Rule : Western-Europe            
! 
! 
!   Software revision  : F.05.79          Base MAC Addr      : 
!   ROM Version        : F.02.01          Serial Number      :   
! Invalid input: information

Running configuration:

; J4813A Configuration Editor; Created on release #F.05.79

hostname "hostname" 
snmp-server contact " oxidized@oxidized.Fr" 
snmp-server location "here" 
time timezone 60 
time daylight-time-rule Western-Europe 
cdp run 
no web-management 
interface 1 
   name "name" 
   broadcast-limit 25 
exit
interface 2 
   name "name" 
   broadcast-limit 25 
   speed-duplex 100-full 
exit
interface

And in the telnet log file : 

May 15 2014 18:20:03
^M                F.05.79
^M                1373
^M^[[1;24r^[[24;1H^[[24;1H^[[2K^[[24;1H^[[?25h^[[24;1H^[[24;1Hsd-sw1-f11# ^[[24;1H^[[24;13H^[[24;1H^[[?25h^[[24;13H^[[24;13Hshow syste^[[24;13H^[[?25h^[[24;23H^[[24;23Hm-informat^[[24;23H^[[?25h^[[24;33H^[[24;33Hion^[[24;33H^[[?25h^[[24$
^M Status and Counters - General System Information
^M  System Name        : hostname
^M  System Contact     : fdkfàf@fdfd.fr
^M  System Location    : somewhere
^M  MAC Age Time (sec) : 300
^M  Time Zone          : 60
^M  Daylight Time Rule : Western-Europe
^M  Software revision  : F.05.79          Base MAC Addr      : 
^M  ROM Version        : F.02.01          Serial Number      : 
^M  Up Time            : 113 days         Memory   - Total   : 10,236,248
^M  CPU Util (%)       : 19                          Free    : 7,608,264
^M  IP Mgmt  - Pkts Rx : 6,228,661        Packet   - Total   : 512
^M             Pkts Tx : 6,160,845        Buffers    Free    : 510
^M                                                   Lowest  : 351
^M                                                   Missed  : 0
^M^[[24;1H^[[2K^[[24;1H^[[1;24r^[[24;1H
^M^[[1;24r^[[24;1H^[[24;1H^[[2K^[[24;1H^[[?25h^[[24;1H^[[24;1Hsd-sw1-f11# ^[[24;1H^[[24;13H^[[24;1H^[[?25h^[[24;13H^[[24;13Hshow syste^[[24;13H^[[?25h^[[24;23H^[[24;23Hm informat^[[24;23H^[[?25h^[[24;33H^[[24;33Hion^[[24;33H^[[?25h^[[24$
^M^[[1;24r^[[24;1H^[[24;1H^[[2K^[[24;1H^[[?25h^[[24;1H^[[24;1Hsd-sw1-f11# ^[[24;1H^[[24;13H^[[24;1H^[[?25h^[[24;13H^[[24;13Hshow runni^[[24;13H^[[?25h^[[24;23H^[[24;23Hng-config^[[24;23H^[[?25h^[[24;32H^[[24;0H^[E^[[24;1H^[[24;32H^[[24;$
^MRunning configuration:
^M; J4813A Configuration Editor; Created on release #F.05.79
^Mhostname "hostname"
^Msnmp-server contact " fdkfàf@fdfd.fr "
^Msnmp-server location "Equinix PA2, 93200 Saint-Denis, France"
^Mtime timezone 60
^Mtime daylight-time-rule Western-Europe
^Mcdp run
^Mno web-management
^Minterface 1
^M   name "name"
^M   broadcast-limit 25
^Mexit
^Minterface 2
^M   name "name"
^M   broadcast-limit 25
^M   speed-duplex 100-full
^Mexit
^Minterface 3
^M   disable
^[[24;1H^[[2K^[[24;1H^[[1;24r^[[24;1H   broadcast-limit 25
^Mexit
^Minterface 4
^M   disable
^M   broadcast-limit 25
^M   speed-duplex 100-full  
etc...

I d'ont understand why he can't get the whole config in web interface ? 

thanks

**Comment by Ynnot** [comment]
Hi ! 
It's ok for procurve model now but for powerconnect (dell) he takes generic password while it's an other login password and i set first in the config file the models with login password then i change to set groups with login password and he still take the wrong login/password. I suppose he didn't detect it's a powerconnect model. Did you know in which code he make the relation between the config and the model ? 

Thank you !

**Comment by Ynnot** [comment]
So I set this in procurve.rb : 

` cfg :telnet, :ssh  do
    if vars :enable
      post_login do
        send "enable\n"
        send "myUsername\n"
        send vars(:enable) + "\n"
      end
    end
    post_login 'no page'
    pre_logout "logout\ny\nn"
  end
`
but he doensn't do the enable. Is the code seems ok for you ? 

thanks.

**Comment by Ynnot** [comment]
i close
