### ISSUE TITLE
F5 config backup

### ISSUE THREAD

**Issue by lokilak** [ytti/oxidized#858]
Hello !

I am trying to setup oxidized for running specific jobs on my GTM/s and LTM boxes, everything works as long as i login as root, as it directly logs into bash shell . but i wanted to create a user account which only has tmsh shell access by default and will switch to bash eventually, for  executing some commands. I have edited the default tmsh commands which were in tmos.rb to show commands to get it worked it works with no problem, but when ever i send the command bash or run util bash in order to switch from tmos to bash shell , it is getting stuck at  expect(below log for reference) i have tried to change  the prompt regex but nothing helped, if anyone can point me to right direction it would be a great help.

48451] DEBUG -- : lib/oxidized/input/ssh.rb bash @ F5_load with expect: /^([\w.@-]+[#>]\s?)

**Comment by ytti** [comment]
Yeah it seems you are just not matching correctly to what ever prompt you receive. Remember there may be unprintable characters. Add:
```
input:
  debug: true
```

to get session log file, view it with some editor which shows unprintables, like vim, perhaps that'll help.

**Comment by lokilak** [comment]
Thanks  Ytii , The debug is enabled it shows as empty file  but when i opened with VIM and did set: list it shows $, but nothing else , i am checking these logs in /home/.config/oxidized/logs/ folder, am i missing something in the debug part or the debug is not generating at all?.

**Comment by ytti** [comment]
If it's all empty, then you missed your window, it is being rewritten on every attempt. You probably want to break oxidized once you have your data. Maybe 'tail -F filename'

**Comment by lokilak** [comment]
Hi ,

I tried running oxidized abut 30mins, keeping tail -f filename in logs folder, i did not see any logs showing up , and to re-check if everything is correct on my end i have checked logs for cisco and Juniper i can see the logs for these(tail-f cisco and juniper files ), but i don't see any debug getting logged for F5's. I have even tested removing the bash command from the tmos.rb, i can see the output for the commands i ran in my output folder but i am not seeing any debug info on the debug files. am i missing something or it is is not logging for F5?

**Comment by wk** [comment]
Related to #437 and #419
