### ISSUE TITLE
Group Configuration Issues

### ISSUE THREAD

**Issue by chavo21** [ytti/oxidized#862]
I am trying to add groups to my configuration but it doesn't seem to respect what I have added.  The oxidized service starts correctly and will collect configurations, but it doesn't recognize the groups.  I have also found Issue #651 and follow what was suggested there. 

The following is my configuration:
```
interval: 3600
use_syslog: true
debug: false
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 127.0.0.1:8888
next_adds_job: false
vars: {}
groups:
  switch:
    username: ****
    password: ****
  router:
    username: ****
    password: ****
  mpls:
    username: ****
    password: ****
models: {}
pid: /home/oxidized/.config/oxidized/pid
input:
  default: ssh, telnet
  debug: false
  ssh:
    secure: false
output:
  default: git
  git:
    user: oxidized
    email: oxidized@oxidized.com
    repo: "/home/oxidized/oxidized/git"
source:
  default: csv
  csv:
    file: /home/oxidized/.config/oxidized/router.db
    delimiter: !ruby/regexp /:/
    map:
      name: 0
      model: 1
      groups: 2
    gpg: false
model_map:
  cisco: ios
  juniper: junos
```
Also, the following is my routerdb:
```
****:cisco:switch
****:cisco:switch
****:cisco:switch
```
Anyone have a suggestion or idea to what is happening?

**Comment by OCangrand** [comment]
> source:
>   default: csv
>   csv:
>     file: /home/oxidized/.config/oxidized/router.db
>     delimiter: !ruby/regexp /:/
>     map:
>       name: 0
>       model: 1
>       groups: 2

It's group and not groups.

**Comment by chavo21** [comment]
That was it.  Thank you.
