### ISSUE TITLE
When catching/rethrowing exceptions, don't lose original backtrace

### ISSUE THREAD

**Issue by fxkr** [ytti/oxidized#863]
I made a stupid mistake and copied router.db over config. Unsurprisingly, oxidized refused to start:

```
root@oxidized ~ # sudo -u oxidized oxidized
Error loading config: undefined method `each' for "example.com:procurve:manager:password":String
/opt/oxidized/.gem/ruby/2.1.0/gems/oxidized-0.20.0/lib/oxidized/config.rb:52:in `rescue in load': Error loading config: undefined method `each' for "example.com:procurve:manager:password":String (Oxidized::InvalidConfig)
	from /opt/oxidized/.gem/ruby/2.1.0/gems/oxidized-0.20.0/lib/oxidized/config.rb:49:in `load'
	from /opt/oxidized/.gem/ruby/2.1.0/gems/oxidized-0.20.0/lib/oxidized/cli.rb:24:in `initialize'
	from /opt/oxidized/.gem/ruby/2.1.0/gems/oxidized-0.20.0/bin/oxidized:9:in `new'
	from /opt/oxidized/.gem/ruby/2.1.0/gems/oxidized-0.20.0/bin/oxidized:9:in `<top (required)>'
	from /usr/local/bin/oxidized:23:in `load'
	from /usr/local/bin/oxidized:23:in `<main>'
```

Which is not helpful, so I looked at the code. It looks like:

```ruby
      begin
        asetus.load # load system+user configs, merge to Config.cfg
      rescue => error
        raise InvalidConfig, "Error loading config: #{error.message}"
      end
```

"Somewhere within asetus"- the original error location is discarded.  I don't know if there is a usual convention for exception chaining in ruby, but one possible (maybe not idiomatic) fix would be:

```ruby
      begin
        asetus.load # load system+user configs, merge to Config.cfg
      rescue => error
        raise InvalidConfig, "Error loading config: #{error.message}. Caused by: #{error.backtrace}"
      end
```

**Comment by ytti** [comment]
This looks good to me. Perhaps guard it to debug? I.e. something like:

```
rescue => error 
  if Oxidized.config.debug
    puts "==== asetus raised #{error.class} ===="
    puts
    puts error.backtrace
    puts
    puts "========"
 end
 raise InvalidConfig, "Error loading config: #{error.message}"
end
```

Or use ```Oxidized.logger.debug``` like:
```
error.backtrace.each do |line|
  Oxidized.logger.debug line
end
```

Or any other solution which gives you sufficient amount of information to solve your mistake.

**Comment by fxkr** [comment]
I'd say whether to show a backtrace and not losing half the backtrace due to re-raising are different issues.

## Showing or hiding backtraces

I think the decision should be made at the highest level the exception propagates to, instead of at the re-raise location. That way you also prevent code duplication like the custom formatting you proposed above would have eventually lead to (if you re-raise at multiple places in the codebase).

The nicest way I've seen to make that decision is to define a class like "UserError" that all custom error classes like "InvalidConfig" inherit from. Then at the top level, if the error instance_of? UserError, and if debug is off, you show only the error message. Otherwise you render it as an exception.


## Loosing half the backtrace

I see now that my original proposal was bad. Sorry! Since Ruby 2.1.0, there's the `.cause` method that gives you the original exception (recursively). So there's no need to add the traceback of the original exception "manually" as I proposed. It's too bad ruby doesn't show it by default, though.

Maybe there's a standard method to format exceptions including their `.cause`s that I'm not aware of, or a gem that implements it more nicely (e.g. better order).

## Conclusion

So maybe something like this in `bin/oxidized` would do?

```ruby
begin
  require 'oxidized/cli'
  Oxidized::CLI.new.run
rescue => error
  if error.instance_of? UserError and not Oxidied.config.debug
    warn error.message
  else
    warn "Exception #{error.class}: #{error.message}"
    loop do
      error.backtrace.each do |line|
        warn line
      end
      error = error.cause
      break unless error
      warn "Caused by #{error.class}: #{error.message}"
    end
  end
end
```
(And add a "UserError" class and make "InvalidConfig" etc. inherit from it.)

**Comment by ytti** [comment]
Looks good to me.

**Comment by wk** [comment]
@fxkr would you be able to turn this into a PR against current master with the proposed changes?
