### ISSUE TITLE
Systemd service file misses sigkill signal

### ISSUE THREAD

**Issue by davromaniak** [ytti/oxidized#864]
Hi.

I know there's a "FIXME", but as we need to use "kill -9" to stop Oxidized, it misses the correct signal in the Systemd service file.

We only need to add "KillSignal=SIGKILL" under the "Service" section of the service file.

Do you think it's usefull to modify the service file or we can wait for the fix to come ?

Thanks.

**Comment by davromaniak** [comment]
Hi.

If you want, I can also add the line proposed in the issue #760 in a pull request.

Thanks.

**Comment by ytti** [comment]
I'm happy to accept changes to the service file.

**Comment by davromaniak** [comment]
Hi.

I will do this at the end of the month, as I'm currently on vacation with no access to any running Oxidized instance :).

Thanks.
