### ISSUE TITLE
multi login/password for one os

### ISSUE THREAD

**Issue by Ynnot** [ytti/oxidized#865]
Hi,
I have 2 different powerconnect model for each i have a different login/password. How can i set this ? i didn't have group, i user models in config file for each model.

thanks a lot !

**Comment by davromaniak** [comment]
Hi.

I don't see how you can achieve this without having the credentials in your source (file, sql, or whatever).

But in this case, you might have to specify it for every other equipment in the list.

Thanks.

**Comment by Ynnot** [comment]
thaks i close
