### ISSUE TITLE
Setting git output's single_repo option to true breaks version output if no groups

### ISSUE THREAD

**Issue by Merlin83b** [ytti/oxidized#866]
Similar to #413, if you set the `single_repo` option to `true` in a configuration not using groups, trying to look at a particular version of a device configuration results in the "Version not found" error.

The option should probably be silently ignored in this case, since the output module would use a single git repository anyway.

**Comment by ytti** [comment]
This is probably oxidized-web issue, if I understood correctly.

**Comment by fractalbrain** [comment]
Hi!  I'm having the same issue (I'm using github).  My workaround was to assign everything a "default" group, keep the "single_repo: true", and restart oxidized.

**Comment by shepherdjay** [comment]
This appears to be addressed in an old pull request #979 - not sure if that fix can be manually applied while the pull request is reviewed and pending as I'm not familiar with Ruby.
