### ISSUE TITLE
have ip address in view by default

### ISSUE THREAD

**Issue by ethanmullins** [ytti/oxidized#873]
Is it possible to have the ip column showing by default? I always have to click on "show/hide columns" to enable it.

**Comment by bheum** [comment]
It's possible. You can edit the file /var/lib/gems/2.1.0/gems/oxidized-web-0.8.0/lib/oxidized/web/views/nodes.haml (path may vary for your installation)

In the buttom section of the nodes.haml you find 
`      columnDefs: [{
        visible: false,
        targets: 1`

Remove the 1 after targets: and all columns should be displayed.

**Comment by ethanmullins** [comment]
Thanks! That worked perfectly.

**Comment by infratihc** [comment]
Hi, it's possible to have the default sort by group ?

**Comment by ethanmullins** [comment]
I'm leaving this for my future self as well as anyone else who stumbles upon this:

When removing the 1 after "targets:" we would get all columns, but then lose the ability to sort columns based on status, type, etc.

Leaving the 1 and changing from "visible: false" to "visible: true" displays all columns by default and doesn't break the sorting ability.
