### ISSUE TITLE
question: Linksys SWR support feasible?

### ISSUE THREAD

**Issue by oernii** [ytti/oxidized#875]
Hi, I wanted to add support for our Cisco/Linksys SRW2048, which has a very peculiar CLI:
- telnet/ssh to the switch
- login (curses style menu login - move to password field with TAB)
- press CTRL-z
- input "lcli"
- login again
- input "show startup-config"
- input "exit"
- input "logout"

My question is if it is feasible to do this with oxidized?

**Comment by ytti** [comment]
What do you mean 'login again', do you mean it'll give another password prompt?

Main problems seesm to be:

  1. need to input data, before authenticating.  (we can't do this now, but it would be easy to add)
  2. need to login twice, if this means need to telnet/ssh twice, it's harder problem than 1. but something we'd be able to do, if I'll find time/motivation for refactor (same solution would fix models where we need to login then ask box to send it over ftp, i.e. use ssh/telnet + ftp).

For 1. you might even be able to get away by adding enough \t to the beginning of username. If that hack will work, and if by 'login again' you just mean re-enter password. Then it should be able to hack together just model.

**Comment by jirib** [comment]
I suppose SRW doc is here: https://www.cisco.com/c/dam/en/us/td/docs/switches/lan/csbms/srw2048/administration/guide/SRW-US_v10_UG_A-Web.pdf

**Comment by helotpl** [comment]
I'm having same problem, any solution so far or workaround?
