### ISSUE TITLE
dcn-software is same as ios

### ISSUE THREAD

**Issue by paszczus** [ytti/oxidized#877]
Hello,
We have few switches from DCN (Digital China Networking) and there is same syntax as in Cisco IOS. I have mapeed dcn-software to ios and it is working fine.
Maybe you can add this mapping by default.

**Comment by ytti** [comment]
We don't have any default mapping, because we don't know what people call the devices in their inventory systems.
But you could potentially update README.md to reflect that it is supported, and then just link the operating system in README.md to ios?
