### ISSUE TITLE
Password not being send to ironware devices through telnet

### ISSUE THREAD

**Issue by Punicaa** [ytti/oxidized#879]
While trying to setup Oxidized to pull configuration from multiple devices I noticed that all my Ironware devices failed when connecting through telnet. The following message is logged:

X.X.X.X raised Timeout::Error with msg "timed out while waiting for more data"

After investigating it seems that oxidized sends the username, but not the password and then it just times out. The log of the telnet sessions shows this and tcpdump does as well.

**Comment by ytti** [comment]
Perhaps it does not recognise the password prompt? Maybe it's different to model regexp?

**Comment by laf** [comment]
@Punicaa Do you have any further feedback to provide?

**Comment by michael-todorovic** [comment]
Hello,
I am having the issue as well. 

```
root@server:~/.config/oxidized# telnet device
Trying <ip>...
Connected to device.
Escape character is '^]'.
[custom welcome message]
device - Brocade ICX7740-PREM Router


User Access Verification

Please Enter Login Name: myusername
Please Enter Password: 

User login successful.

telnet@device#exit
```

After checking ironware.rb, regexp seems ok. 

On some other devices (same model/version), SSH works and configuration is read successfully. However, [SSH is buggy](https://www.reddit.com/r/networking/comments/44qyp3/brocade_pushed_out_firmware_to_switches_now_i/) so we have to fallback on telnet, which is not working (yet).

Current tested version of ironware are 08.0.30eT213 and 08.0.30nT213.

**Comment by wk** [comment]
You could try modifying the password prompt from `/^(Please Enter Password ?|Password):/` to `/(Please Enter Password ?|Password):/` in your model to see if perhaps the devices throws some control characters which aren't immediately visible in the output in the password line, but which prevent the string from matching.
