### ISSUE TITLE
pfsense not found for node

### ISSUE THREAD

**Issue by rzig** [ytti/oxidized#882]
Hi! I just set up oxidized, and connected it to my LibreNMS installation. It is able to get devices from the LibreNMS API successfully, one of which is a PfSense firewall. When I run `oxidized` it outputs the following error:

    ERROR -- : node {:name=>"pfsense.localdomain", :model=>"pfsense", :group=>"default"} raised Oxidized::ModelNotFound with message 'pfsense not found for node 192.168.1.1'.`

I'm not sure why this isn't working, PfSense is one of the supported device types. Here is my oxidized config file:

```
---
username: username
password:
password
model: junos
interval: 3600
use_syslog: false
debug: false
threads: 30
timeout: 20
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 0.0.0.0:8888
vars: {}
groups: {}
input:
  default: ssh, telnet
  debug: false
  ssh:
    secure: false
output:
  default: file
  file:
    directory: "/opt/librenms/.config/oxidized/configs"
  source:
    default: http
    debug: false
    http:
      url: http://192.168.1.30/api/v0/oxidized
      map:
        name:  hostname
        model:  os
        group: group
    headers:
      X-Auth-Token: asdfasdfasdfasdfasdf
model_map:
  cisco: ios
  juniper: junos
```
The config file appears to be correct because the model name provided by the LibreNMS API ("pfsense") corresponds to the model name in your code. Just in case it was case insensitive, I tried the following `model_map`s but to no success, they had the same error:
```
model_map:
  cisco: ios
  juniper: junos
  pfsense: PfSense
```
and
```
model_map:
  cisco: ios
  juniper: junos
  PfSense: pfsense
```
I'll also ping @laf on this since it relates to LibreNMS. I'm assuming I just need to add a device map, but am not sure what it should be.

**Comment by laf** [comment]
You shouldn't need to map the OS as they are the same for LibreNMS and Oxidized.

I'd hit the LibreNMS api and make sure the device is reported as pfsense: http://192.168.1.30/api/v0/oxidized

**Comment by rzig** [comment]
Thanks for your quick reply! When I run `curl -H 'X-Auth-Token: whatever' http://192.168.1.30/api/v0/oxidized` I get the following response:
```
[
    {
        "hostname": "pfsense.localdomain",
        "os": "pfsense",
        "group": "default"
    }
]
```

Also, here is the oxidized config in the Web UI: 
![image](https://cloud.githubusercontent.com/assets/16417432/26757333/7251c3f2-4886-11e7-8f9a-81cd5a725785.png)

**Comment by rzig** [comment]
@laf the VM came with an outdated version of the Oxidized gem that did not have PfSense support. Upgrading the gem fixes the issue.
