### ISSUE TITLE
raised Net::SSH::ConnectionTimeout (rescued RuntimeError) with msg "timeout during server version negotiating"

### ISSUE THREAD

**Issue by tomranson** [ytti/oxidized#883]
Hi all,

I have a particular device which is noticeably slow (5-6 seconds elapsed) to respond to SSH session initialisation (the root cause of this is something under separate investigation), and as a result Oxidixed throws the following and fails to ever log into the device. If we use good old OpenSSH then there is a 5-6 second delay when waiting for a password prompt (most devices are <1s to this point).

W, [2017-06-06T12:47:10.117112 #16328]  WARN -- : x.x.x.x raised Net::SSH::ConnectionTimeout (rescued RuntimeError) with msg "timeout during server version negotiating"
W, [2017-06-06T12:47:11.088737 #16328]  WARN -- : x.x.x.x status no_connection, retry attempt 1
W, [2017-06-06T12:47:51.128260 #16328]  WARN -- : x.x.x.x raised Net::SSH::ConnectionTimeout (rescued RuntimeError) with msg "timeout during server version negotiating"
W, [2017-06-06T12:47:52.098031 #16328]  WARN -- : x.x.x.x status no_connection, retry attempt 2
W, [2017-06-06T12:48:32.139720 #16328]  WARN -- : x.x.x.x raised Net::SSH::ConnectionTimeout (rescued RuntimeError) with msg "timeout during server version negotiating"
W, [2017-06-06T12:48:33.106837 #16328]  WARN -- : x.x.x.x status no_connection, retry attempt 3
W, [2017-06-06T12:49:13.148847 #16328]  WARN -- : x.x.x.x raised Net::SSH::ConnectionTimeout (rescued RuntimeError) with msg "timeout during server version negotiating"
W, [2017-06-06T12:49:14.115230 #16328]  WARN -- : x.x.x.x status no_connection, retries exhausted, giving up

To workaround the root cause for now, how can I make oxidized more tolerant to this ssh session initialisation timeout please? The Oxidized "timeout" configuration parameter does not appear to do the trick (and is set to 20 (seconds?) anyway)).

Many thanks.

**Comment by ytti** [comment]
```
./transport/session.rb:      @server_version = ServerVersion.new(socket, logger, options[:timeout])
```

The code seems to support timeout option, which we pass: https://github.com/ytti/oxidized/blob/master/lib/oxidized/input/ssh.rb#L35

So by increasing timeout in config, it should allow longer time for ServerVersion negotiation.

**Comment by laf** [comment]
@tomranson Have you tested increasing the timeout option as per ytti's response?
