### ISSUE TITLE
Can't see versions under versions tab

### ISSUE THREAD

**Issue by simongia** [ytti/oxidized#885]
![oxidized2](https://user-images.githubusercontent.com/29277519/26928090-f97aaa7a-4c54-11e7-9bdd-c8a35279dab0.PNG)
![oxidized1](https://user-images.githubusercontent.com/29277519/26928091-f9879d16-4c54-11e7-99eb-54daa205d5b1.PNG)

Hi,

When i click on the "version" icon under the node display, i don't get a list of versions.
In the directory, old config files don't exist when i reload the service. Just the new backup files.

[oxidized@oxidized prod]$ uname -a
Linux oxidized 3.10.0-514.21.1.el7.x86_64 #1 SMP Thu May 25 17:04:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

[oxidized@oxidized prod]$ cat /etc/redhat-release 
CentOS Linux release 7.3.1611 (Core) 

[oxidized@oxidized ~]$ oxidized -v
0.20.0

Configurations files
----------------------
**config file**

`---`
`# comment`
`#username: `
`#password: `
`#model: cisco`
`interval: 3600`
`use_syslog: false`
`#add`
`log: /var/log/oxidized_logs/logs`
`debug: true`
`threads: 30`
`timeout: 20`
`retries: 3`
`prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/`
`rest: 127.0.0.1:8888`
`next_adds_job: false`
`vars: {}`
`#modify`
`groups:`
`  lab:`
`      username: admin`
`      password: testtest`
`#     enable:`
`  prod:`
`    username: admin`
`    password: testtest`
`#    enable:`
`  fw:`
`    username: admin`
`    password: testtest`
`#    switch:`
`#	username: admin`
`#	password: testtest`
`models: {}`
`pid: /home/oxidized/.config/oxidized/pid`
`input:`
 ` default: ssh, telnet`
`  debug: false`
`  ssh:`
`    secure: false`
`output:`
`  default: file`
`  file:`
`    directory: /home/oxidized/.config/oxidized/configs`
`source:`
`  default: csv`
`  csv:`
`    file: /home/oxidized/.config/oxidized/router.db`
`    delimiter: !ruby/regexp /:/`
`    map:`
`      name: 0`
`      model: 1`
`      #add`
`      group: 2`
`    gpg: false`
`model_map:`
`  cisco: ios`
`  juniper: junos`
`  #add`
`  nexus: nxos`
`  fw: asa`

**routeur.db file**
`[oxidized@oxidized oxidized]$ cat router.db `
`1.1.1.1:nexus:lab
1.1.1.1:nexus:prod
`

**Comment by davromaniak** [comment]
Hi.

You need to use the git output to have the version tab working.

Thanks.

**Comment by simongia** [comment]
Thanks for your quick reply

Can you tell me if you can compare the version ?

**Comment by bheum** [comment]
You can compare two versions of a device-configuration using diff on the versions page.
