### ISSUE TITLE
Encrypt password 

### ISSUE THREAD

**Issue by simongia** [ytti/oxidized#891]
Can you tell me if it's possible to encrypt passwords? And / or link it to a DB (ldap, other)

Thanks

**Comment by sebisme** [comment]
Hello @simongia,

It IS possible.
Here's what i did with mysql
Config file :

`source:`
`    default: sql`
`  sql:`
`    adapter: mysql2`
`    database: 'mydb'`
`    table: 'mytable'`
`    query: 'SELECT mt.dsn_name, mt.address, mt.model, mt.username, mt.input, mt.port, CAST(AES_DECRYPT(mt.password, "decrypt_key") AS CHAR(255)) AS pwd, CAST(AES_DECRYPT(mt.enable, "decrypt_key") AS CHAR(255)) AS enbl FROM mytable AS mt WHERE mt.status = 1'`
`    host: 'localhost'`
`    password: 'db_password'`
`    user: 'db_user'`
`    map:`
`      name: dns_name`
`      ip: address`
`      port: port`
`      model: model`
`      username: username`
`      password: pwd`
`      enable: enbl`

It's not "perfect" as the decryption key is hard coded in the config file, but it can help,
You may have to install the mysql2 gem.

**Comment by ytti** [comment]
We also support encrypting the CSV file. Thansk @sebisme for your example.

**Comment by laf** [comment]
@sebisme Do you need any more info?

**Comment by Nightreaver** [comment]
@ytti and where is the "how to" for encrypting inside csv?

**Comment by laf** [comment]
@Nightreaver this should help: https://github.com/ytti/oxidized/issues/713

**Comment by Nightreaver** [comment]
so it will encrypt the whole csv file with gpg password ? not just password portion?
Can we also use SSH-key instead?

**Comment by laf** [comment]
You must provide the encrypted csv originally, it's the gpg password you add to config for oxidized to un-encrypt the file.
