### ISSUE TITLE
Hide sensitive info on Mikrotik / RouterOS

### ISSUE THREAD

**Issue by spinza** [ytti/oxidized#900]
I will test this soon but I don't see any configuration for hiding sensitive information in https://github.com/ytti/oxidized/blob/master/lib/oxidized/model/routeros.rb.

Can this be added?  I'm not sure as to the code to do so but RouterOS has a convenience function called `/export hide-sensitive`.  Can this be called instead when the Oxidized `remove_secret` flag is set?  I see it currently calls `/export` regardless and does not seem to scrub the information afterwards.

**Comment by spinza** [comment]
I don't know ruby that well but I guess I want to run
```
if :secret `/export hide-sensitive` else `/export`
```

**Comment by ytti** [comment]
It's actually ```vars(:remove_secret)```. So you could do something like like.

```
post do
  run_cmd = vars(:remove_secret) ? '/export hide-sensitive' : '/export/'
  cmd run_cmd
end
```

**Comment by spinza** [comment]
I really don't know ruby.  So how do I work it in here:
```ruby
  cmd '/export' do |cfg|
    cfg.gsub! /\x1B\[([0-9]{1,3}((;[0-9]{1,3})*)?)?[m|K]/, '' # strip ANSI colours
    cfg.gsub! /\\\r\n\s+/, ''   # strip new line
    cfg = cfg.split("\n").select { |line| not line[/^\#\s\w{3}\/\d{2}\/\d{4}.*$/] }
    cfg.join("\n") + "\n"
  end
```

How about this at [L17 in routeros.rb](https://github.com/ytti/oxidized/blob/master/lib/oxidized/model/routeros.rb#L17)?
```ruby
  post do
    run_cmd = vars(:remove_secret) ? '/export hide-sensitive' : '/export/'
    cmd run_cmd do |cfg|
      cfg.gsub! /\x1B\[([0-9]{1,3}((;[0-9]{1,3})*)?)?[m|K]/, '' # strip ANSI colours
      cfg.gsub! /\\\r\n\s+/, ''   # strip new line
      cfg = cfg.split("\n").select { |line| not line[/^\#\s\w{3}\/\d{2}\/\d{4}.*$/] }
      cfg.join("\n") + "\n"
    end
  end
  
```

**Comment by ytti** [comment]
Your example should work.
