### ISSUE TITLE
node not found with groups

### ISSUE THREAD

**Issue by networkpadawan** [ytti/oxidized#901]
When I try to fetch a node, it only works if I put the group on the URL, if i put fetch/node/NODEID it gives a node not found. Is this by design? or should it work both with group and without?

**Comment by ytti** [comment]
It'll only work for groupless without group. There is no technical reason why we couldn't create non-deterministic version which returns first match.
Without group specifier, we could potentially have multiple devices with same name. Notion is that that if you're integrator helping many customers, many of them might have router named 10.0.0.1.

**Comment by networkpadawan** [comment]
Is this the same for show/node/NODEID ?

**Comment by ytti** [comment]
No. show/node finds first index with given IP or Name, i.e. it's not deterministic. However it'll also return group info.

**Comment by networkpadawan** [comment]
But it always returns the first one? because when i try /node/show/NODE, i get a node not found, but with /node/show/GROUP/NODE it works ok. my problem is that librenms is having issues with group support, meaning the request only goes with the node info. But they are having a hard time reproducing the problem. I think it´s becase they use the "default" group on their tests.

**Comment by ytti** [comment]
Show should find first one, fetch should require group. If this is not true, then it's a bug. If this is undesired behaviour but true, then it's enhancement.

**Comment by networkpadawan** [comment]
your software, you tell me:) i can tell you that right now, it returns node not found, when using /show/node/NODEID when using single_repo and groups.

**Comment by ytti** [comment]
I can't immediately explain that. The code is:

https://github.com/ytti/oxidized/blob/master/lib/oxidized/nodes.rb#L54-L55

It should not know anything about single_repo, or output at all. It just looks at nodes array for index which has NODEID name or IP, then returns data about that node.

Literally this fails:
https://github.com/ytti/oxidized/blob/master/lib/oxidized/nodes.rb#L130-L132

And you're saying 'NODEID' actually is valid name or IP? Can you try just to ```curl``` it?

**Comment by networkpadawan** [comment]
it his the valid name. the tests are just done with or without group on the URL. ill try to post curl examples asap.
