### ISSUE TITLE
Custom global gsub

### ISSUE THREAD

**Issue by casdr** [ytti/oxidized#912]
We have some custom gsub rules that hides lines for several models. One example is that we have a user that logs in to check if firewall rules are applied. If everything is already applied, the configuration itself won't change, but it'll change the "Last configuration change by..." line.

I've excluded this line now, but probably not all users want this too. My suggestion is to add a configuration option that will enable users to add global exclusion rules.

**Comment by ytti** [comment]
Dunno what platform that is, but at least in IOS you won't get that unless you enter configuration mode. And of course you can review config without being in configuration mode.

You could create your own model in  ```~/.config/oxidized/model/modelname.rb``` and reopen the distribution one:

```
require 'distribution_dir/model/modelname.rb'
class ModelName
  ## your local changes
end
```

**Comment by casdr** [comment]
Totally forgot about doing it that way, thanks @ytti :)

**Comment by casdr** [comment]
If others want the same, I've fixed this by creating the following file in `~/.config/oxidized/model/fortios.rb`

```require '/var/lib/gems/2.0.0/gems/oxidized-0.20.0/lib/oxidized/model/fortios.rb'
class FortiOS
  cmd :all do |cfg|
    cfg.gsub!(/(Virus-DB|Extended DB|IPS-DB|IPS-ETDB|Botnet DB|IPS Malicious URL Database): (.*)/, '\1<stripped>\3')
    cfg
  end
end```
