### ISSUE TITLE
Adding new model for Avaya ERS

### ISSUE THREAD

**Issue by tslytsly** [ytti/oxidized#916]
We have a large number of Avaya ERS 3500 switches.
In many ways the CLI and commands are like Cisco iOS, but there are differences.

I can get away with using the iOS model, but it does generate errors.

I'd like to add support for the Avaya command line, is it as simple as adding a new file to the /oxidized/model directory? 
Thanks

**Comment by ytti** [comment]
We already have two Avaya models:

------
Avaya

VOSS (VSP Operating System Software)
BOSS (Baystack Operating System Software)
-----

Starting new model is as easy as creating file in ```~/.config/oxidixed/model/modelname.rb```

**Comment by tslytsly** [comment]
Ah, great.
I'll have a play with the BOSS model.

Thanks
