### ISSUE TITLE
Continuous errors in logs :: status no_connection, retries exhausted, giving up

### ISSUE THREAD

**Issue by papatango71** [ytti/oxidized#922]
I continuously see these errors in the syslog for oxidized.  I have checked a large majority of the devices that are reporting errors and they are all successfully able to be logged into via oxidized's username and password when done on the CLI.  Is this issue due to a module that is outdated..??

Jul  6 18:02:17 nms01-eqch2 oxidized[11033]: x.x.x.x raised Timeout::Error with msg "execution expired"
Jul  6 18:02:18 nms01-eqch2 oxidized[11033]: pr01.eqse2.xxx.net status no_connection, retry attempt 1
Jul  6 18:03:12 nms01-eqch2 oxidized[11033]: x.x.x.x raised Timeout::Error with msg "execution expired"
Jul  6 18:03:13 nms01-eqch2 oxidized[11033]: pr01.eqse2.xxx.net status no_connection, retry attempt 2
Jul  6 18:04:07 nms01-eqch2 oxidized[11033]: x.x.x.x raised Timeout::Error with msg "execution expired"
Jul  6 18:04:08 nms01-eqch2 oxidized[11033]: pr01.eqse2.xxx.net status no_connection, retry attempt 3
Jul  6 18:05:02 nms01-eqch2 oxidized[11033]: x.x.x.x raised Timeout::Error with msg "execution expired"

**Comment by laf** [comment]
Is that all the output?

What's your timeout value in oxidized config?

**Comment by laf** [comment]
If that is all the output then have you enabled debug in the config file to get more info?

**Comment by papatango71** [comment]
I have the following enabled for debug in the config file as well as increased the timeout from 40 to 120 but no change. 

Global
timeout: 120
log: /home/oxidized/.config/oxidized/logs/
debug: true

input:
  default: ssh, telnet
  debug: true
  ssh:
    secure: false

When I look at the logs directory for one of the devices I do see that a config was collected:

oxidized@nms01-eqch2
[/home/oxidized/.config/oxidized/logs]$ ls -l x.x.x.x*
-rw-rw-r-- 1 oxidized oxidized 43844 Jul  6 21:07 x.x.x.x-ssh
-rw-rw-r-- 1 oxidized oxidized  8346 Jul  6 21:07 x.x.x.x-telnet

I am not sure why it is trying to use telnet on this devices since SSH is working.    I am not sure if this issue is leading to this or not but I see this in the device config section on LibreNMS:

Sync status: no_connection

Thank you.

-Patrick

**Comment by laf** [comment]
That's the debug output rather than config afaik. Post the full info from each.

**Comment by papatango71** [comment]
---
username: oxidized
password: xxx
model: cisco
interval: 3600
use_syslog: true
log: /home/oxidized/.config/oxidized/logs/
debug: true
threads: 30
timeout: 120
retries: 3
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
rest: 127.0.0.1:8888
next_adds_job: false
vars: {}
groups:
  cisco:
    username: oxidized
    password: xxx
  juniper:
    username: oxidized
    password: xxx
  opengear:
    username: root
    password: xxx
  fortios:
    username: oxidized
    password: xxx
  acos:
    username: oxidized
    password: xxx
models: {}
pid: "/home/oxidized/.config/oxidized/pid"
input:
  default: ssh
  debug: true
  ssh:
    secure: false
output:
  default: git
  git:
    user: oxidized
    email: oxidized@librenms.xxx.net
    repo: "/home/oxidized/.config/oxidized"
  debug: true
source:
        default: http
        debug: true
        http:
          url: http://librenms.xxx.net/api/v0/oxidized
          map:
            name: hostname
            model: os
            group: group
          headers:
            X-Auth-Token: '6438c5cebfd11bd48d6f50b5ff12dc92'
model_map:
  cisco: ios
  juniper: junos
  nexus: nxos
  fortigate: fortios
  iosxe: ios
  arista_eos: eos
  opengear: opengear


I am not sure where else to look for logs outside of the defined log directory and /var/log/messages.  If I am missing anything please let me know and I will supply that information.  

The output in the logs directory is the actual config from the router so I am sure why this error is happening.

oxidized@nms01-eqch2
[/home/oxidized/.config/oxidized/logs]$ more x.x.x.x-ssh


RP/0/RSP0/CPU0:PR01.EQSE2#terminal length 0
Thu Jul  6 21:27:39.785 UTC
RP/0/RSP0/CPU0:PR01.EQSE2#terminal width 0
Thu Jul  6 21:27:40.382 UTC
RP/0/RSP0/CPU0:PR01.EQSE2#show inventory
Thu Jul  6 21:27:40.995 UTC
NAME: "module 0/RSP0/CPU0", DESCR: "ASR9K Route Switch Processor with 440G/slot Fabric and 12GB"
PID: A9K-RSP440-SE, VID: V08, SN: FOC2002NKD8

**Comment by papatango71** [comment]
This issue seems very close to the issue in https://github.com/ytti/oxidized/issues/360.  I checked and I am running the recommended net-ssh version 3.0.2.   I tried downgrading to net-ssh 3.0.1 but oxidized seems to only run with net-ssh 3.0.2.  This issue is effecting 12 routers but all my other devices are fine.  Not sure where to go from here.   Any help would be greatly appreciated.

**Comment by ytti** [comment]
Can you try to build oxidized from the git (git clone; cd oxidized*; rake build; gem install pkg/oxidized*). And see if that helps.

**Comment by papatango71** [comment]
YTTI,  I did exactly as you instructed and I am getting the exact same error.  This issue is still happening.  It seems to be only effecting Cisco ASR 9000s.  What is confusing is that there is a log file in the debug output that shows that the config was collected.

xidized@nms01-eqch2
[/home/oxidized/.config/oxidized/logs]$ ls -l xx.x.x.x-ssh
-rw-r--r-- 1 oxidized oxidized 44898 Jul 10 18:30 x.x.x.x-ssh

The last line of the log shows that it issued an "exit" to log out of the router

 !
!
lldp
!
end

RP/0/RSP0/CPU0:BR02.EQCH2#exit

I am not sure if this could be the issue or not but the routers that are showing issues require that <enter> be hit a couple of times after issue'ing the exit command.  This is most likely related to Cisco IOS-XR 5.1.3 and will be corrected when we upgrade to IOS-XR 5.3.1.  In the mean time, is there a fix / work around we can put in place..??

Thank you.

-Patrick

**Comment by papatango71** [comment]
This issue has been resolved.  The issue is related to Cisco's IOS-XR 5.1.3 version of firmware

**Comment by patilanna** [comment]
I am facing issue for backuping Huawei S5624P switch devices.

log file for device.


********************************************************************************
*  Copyright(c) 1998-2006 Huawei Technologies Co., Ltd.  All rights reserved.  *
*  Without the owner's prior written consent,                                  *
*  no decompiling or reverse-engineering shall be allowed.                     *
********************************************************************************

<xxxS5624P-SW-A1>
%Jan 17 13:01:20:958 2020 xxx-S5624P-SW-A1 SHELL/5/LOGIN:- 1 - rutuja@ttl(10.209.132.150) in unit1 login

Debug logs
========

D, [2020-01-17T13:01:20.794937 #29542] DEBUG -- : lib/oxidized/worker.rb: Added /xxx-S5624P-SW-A1 to the job queue
D, [2020-01-17T13:01:20.795459 #29542] DEBUG -- : lib/oxidized/job.rb: Starting fetching process for xxx-S5624P-SW-A1 at 2020-01-17 07:31:20 UTC
D, [2020-01-17T13:01:20.795823 #29542] DEBUG -- : lib/oxidized/input/ssh.rb: Connecting to xxx-S5624P-SW-A1
D, [2020-01-17T13:01:20.797488 #29542] DEBUG -- net.ssh.transport.session[1652f24]: establishing connection to xxx-S5624P-SW-A1:22
D, [2020-01-17T13:01:24.363006 #29542] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^(<[\w.-]+>)$/] at xxx-S5624P-SW-A1
W, [2020-01-17T13:01:26.286961 #29542]  WARN -- : xxx-S5624P-SW-A1 raised IOError with msg "closed stream"
D, [2020-01-17T13:01:26.287128 #29542] DEBUG -- : lib/oxidized/node.rb: Oxidized::SSH failed for xxx-S5624P-SW-A1
D, [2020-01-17T13:01:26.333671 #29542] DEBUG -- : xxx-S5624P-SW-A1 raised Errno::ECONNREFUSED with msg "Connection refused - connect(2) for "xxx-S5624P-SW-A1" port 23"
D, [2020-01-17T13:01:26.333835 #29542] DEBUG -- : lib/oxidized/node.rb: Oxidized::Telnet failed for xxx-S5624P-SW-A1
D, [2020-01-17T13:01:26.333955 #29542] DEBUG -- : lib/oxidized/job.rb: Config fetched for xxx-S5624P-SW-A1 at 2020-01-17 07:31:26 UTC
W, [2020-01-17T13:01:26.808193 #29542]  WARN -- : /xxx-S5624P-SW-A1 status no_connection, retry attempt 1
D, [2020-01-17T13:01:26.808361 #29542] DEBUG -- : lib/oxidized/worker.rb: Added /xxx-S5624P-SW-A1 to the job queue
D, [2020-01-17T13:01:26.808451 #29542] DEBUG -- : lib/oxidized/job.rb: Starting fetching process for xxx-S5624P-SW-A1 at 2020-01-17 07:31:26 UTC
D, [2020-01-17T13:01:26.808592 #29542] DEBUG -- : lib/oxidized/input/ssh.rb: Connecting to xxx-S5624P-SW-A1
D, [2020-01-17T13:01:26.809315 #29542] DEBUG -- net.ssh.transport.session[3fcb8c1a52b0]: establishing connection to xxx-S5624P-SW-A1:22
D, [2020-01-17T13:01:30.108578 #29542] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^(<[\w.-]+>)$/] at xxx-S5624P-SW-A1
W, [2020-01-17T13:01:32.048889 #29542]  WARN -- : xxx-S5624P-SW-A1 raised IOError with msg "closed stream"
D, [2020-01-17T13:01:32.049056 #29542] DEBUG -- : lib/oxidized/node.rb: Oxidized::SSH failed for xxx-S5624P-SW-A1
D, [2020-01-17T13:01:32.096810 #29542] DEBUG -- : xxx-S5624P-SW-A1 raised Errno::ECONNREFUSED with msg "Connection refused - connect(2) for "xxx-S5624P-SW-A1" port 23"
D, [2020-01-17T13:01:32.096971 #29542] DEBUG -- : lib/oxidized/node.rb: Oxidized::Telnet failed for xxx-S5624P-SW-A1
D, [2020-01-17T13:01:32.097089 #29542] DEBUG -- : lib/oxidized/job.rb: Config fetched for xxx-S5624P-SW-A1 at 2020-01-17 07:31:32 UTC
W, [2020-01-17T13:01:32.814395 #29542]  WARN -- : /xxx-S5624P-SW-A1 status no_connection, retry attempt 2
D, [2020-01-17T13:01:32.815344 #29542] DEBUG -- : lib/oxidized/worker.rb: Added /xxx-S5624P-SW-A1 to the job queue
D, [2020-01-17T13:01:32.815614 #29542] DEBUG -- : lib/oxidized/job.rb: Starting fetching process for xxx-S5624P-SW-A1 at 2020-01-17 07:31:32 UTC
D, [2020-01-17T13:01:32.816285 #29542] DEBUG -- : lib/oxidized/input/ssh.rb: Connecting to xxx-S5624P-SW-A1
D, [2020-01-17T13:01:32.818084 #29542] DEBUG -- net.ssh.transport.session[3fcb900c5b5c]: establishing connection to xxx-S5624P-SW-A1:22
D, [2020-01-17T13:01:36.258064 #29542] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^(<[\w.-]+>)$/] at xxx-S5624P-SW-A1
W, [2020-01-17T13:01:37.267395 #29542]  WARN -- : xxx-S5624P-SW-A1 raised IOError with msg "closed stream"
D, [2020-01-17T13:01:37.267560 #29542] DEBUG -- : lib/oxidized/node.rb: Oxidized::SSH failed for xxx-S5624P-SW-A1
D, [2020-01-17T13:01:37.312544 #29542] DEBUG -- : xxx-S5624P-SW-A1 raised Errno::ECONNREFUSED with msg "Connection refused - connect(2) for "xxx-S5624P-SW-A1" port 23"
D, [2020-01-17T13:01:37.312727 #29542] DEBUG -- : lib/oxidized/node.rb: Oxidized::Telnet failed for xxx-S5624P-SW-A1
D, [2020-01-17T13:01:37.312847 #29542] DEBUG -- : lib/oxidized/job.rb: Config fetched for xxx-S5624P-SW-A1 at 2020-01-17 07:31:37 UTC
W, [2020-01-17T13:01:37.823551 #29542]  WARN -- : /xxx-S5624P-SW-A1 status no_connection, retry attempt 3
D, [2020-01-17T13:01:37.824475 #29542] DEBUG -- : lib/oxidized/worker.rb: Added /xxx-S5624P-SW-A1 to the job queue
D, [2020-01-17T13:01:37.824700 #29542] DEBUG -- : lib/oxidized/job.rb: Starting fetching process for xxx-S5624P-SW-A1 at 2020-01-17 07:31:37 UTC
D, [2020-01-17T13:01:37.825319 #29542] DEBUG -- : lib/oxidized/input/ssh.rb: Connecting to xxx-S5624P-SW-A1
D, [2020-01-17T13:01:37.827263 #29542] DEBUG -- net.ssh.transport.session[17f82fc]: establishing connection to xxx-S5624P-SW-A1:22
D, [2020-01-17T13:01:41.456480 #29542] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^(<[\w.-]+>)$/] at xxx-S5624P-SW-A1
W, [2020-01-17T13:01:43.574183 #29542]  WARN -- : xxx-S5624P-SW-A1 raised IOError with msg "closed stream"
D, [2020-01-17T13:01:43.574372 #29542] DEBUG -- : lib/oxidized/node.rb: Oxidized::SSH failed for xxx-S5624P-SW-A1
D, [2020-01-17T13:01:43.621260 #29542] DEBUG -- : xxx-S5624P-SW-A1 raised Errno::ECONNREFUSED with msg "Connection refused - connect(2) for "xxx-S5624P-SW-A1" port 23"
D, [2020-01-17T13:01:43.621423 #29542] DEBUG -- : lib/oxidized/node.rb: Oxidized::Telnet failed for xxx-S5624P-SW-A1
D, [2020-01-17T13:01:43.621534 #29542] DEBUG -- : lib/oxidized/job.rb: Config fetched for xxx-S5624P-SW-A1 at 2020-01-17 07:31:43 UTC
W, [2020-01-17T13:01:43.830420 #29542]  WARN -- : /xxx-S5624P-SW-A1 status no_connection, retries exhausted, giving up
D, [2020-01-17T13:06:36.743702 #29542] DEBUG -- : resolving DNS for xxx-S5624P-SW-A1...
[root@caspianserver logs]# vim debug.log
I, [2020-01-17T13:01:24.666786 #29542]  INFO -- net.ssh.connection.channel[cd8a34]: sending channel request "pty-req"
D, [2020-01-17T13:01:24.667041 #29542] DEBUG -- socket[1652b78]: queueing packet nr 9 type 98 len 60
D, [2020-01-17T13:01:24.702812 #29542] DEBUG -- socket[179ac24]: received packet nr 11 type 94 len 44
I, [2020-01-17T13:01:24.703063 #29542]  INFO -- net.ssh.connection.session[103c694]: channel_data: 0 24b
D, [2020-01-17T13:01:24.703349 #29542] DEBUG -- socket[179ac24]: received packet nr 12 type 94 len 124
I, [2020-01-17T13:01:24.703498 #29542]  INFO -- net.ssh.connection.session[103c694]: channel_data: 0 110b
D, [2020-01-17T13:01:24.767502 #29542] DEBUG -- socket[1652b78]: sent 152 bytes
D, [2020-01-17T13:01:24.797489 #29542] DEBUG -- : lib/oxidized/worker.rb: 3 jobs running in parallel
D, [2020-01-17T13:01:24.868188 #29542] DEBUG -- socket[1652b78]: read 36 bytes
D, [2020-01-17T13:01:24.868506 #29542] DEBUG -- socket[1652b78]: received packet nr 8 type 99 len 12
I, [2020-01-17T13:01:24.868663 #29542]  INFO -- net.ssh.connection.session[cd98bc]: channel_success: 0
I, [2020-01-17T13:01:24.868767 #29542]  INFO -- net.ssh.connection.channel[cd8a34]: sending channel request "shell"
D, [2020-01-17T13:01:24.869000 #29542] DEBUG -- socket[1652b78]: queueing packet nr 10 type 98 len 28
I, [2020-01-17T13:01:24.904448 #29542]  INFO -- net.ssh.connection.keepalive[103c57c]: sending keepalive 0
I, [2020-01-17T13:01:24.904613 #29542]  INFO -- net.ssh.connection.session[103c694]: sending global request keepalive@openssh.com
D, [2020-01-17T13:01:24.904886 #29542] DEBUG -- socket[179ac24]: queueing packet nr 11 type 80 len 44
D, [2020-01-17T13:01:24.969653 #29542] DEBUG -- socket[1652b78]: sent 52 bytes
D, [2020-01-17T13:01:25.070381 #29542] DEBUG -- socket[1652b78]: read 488 bytes
D, [2020-01-17T13:01:25.070708 #29542] DEBUG -- socket[1652b78]: received packet nr 9 type 99 len 12
I, [2020-01-17T13:01:25.070884 #29542]  INFO -- net.ssh.connection.session[cd98bc]: channel_success: 0
D, [2020-01-17T13:01:25.071116 #29542] DEBUG -- socket[1652b78]: received packet nr 10 type 94 len 428
I, [2020-01-17T13:01:25.071316 #29542]  INFO -- net.ssh.connection.session[cd98bc]: channel_data: 0 412b
D, [2020-01-17T13:01:25.106039 #29542] DEBUG -- socket[179ac24]: sent 68 bytes
D, [2020-01-17T13:01:25.172068 #29542] DEBUG -- socket[1652b78]: read 216 bytes
D, [2020-01-17T13:01:25.206774 #29542] DEBUG -- socket[179ac24]: read 132 bytes
D, [2020-01-17T13:01:25.207084 #29542] DEBUG -- socket[179ac24]: received packet nr 13 type 1 len 108
D, [2020-01-17T13:01:25.272866 #29542] DEBUG -- socket[1652b78]: received packet nr 11 type 94 len 44
I, [2020-01-17T13:01:25.273099 #29542]  INFO -- net.ssh.connection.session[cd98bc]: channel_data: 0 20b
D, [2020-01-17T13:01:25.273380 #29542] DEBUG -- socket[1652b78]: received packet nr 12 type 94 len 124
I, [2020-01-17T13:01:25.273536 #29542]  INFO -- net.ssh.connection.session[cd98bc]: channel_data: 0 106b
I, [2020-01-17T13:01:25.474634 #29542]  INFO -- net.ssh.connection.keepalive[cd91a0]: sending keepalive 0
I, [2020-01-17T13:01:25.474810 #29542]  INFO -- net.ssh.connection.session[cd98bc]: sending global request keepalive@openssh.com
D, [2020-01-17T13:01:25.475097 #29542] DEBUG -- socket[1652b78]: queueing packet nr 11 type 80 len 44
D, [2020-01-17T13:01:25.676288 #29542] DEBUG -- socket[1652b78]: sent 68 bytes
D, [2020-01-17T13:01:25.776999 #29542] DEBUG -- socket[1652b78]: read 132 bytes
D, [2020-01-17T13:01:25.777370 #29542] DEBUG -- socket[1652b78]: received packet nr 13 type 1 len 108
D, [2020-01-17T13:01:25.798066 #29542] DEBUG -- : lib/oxidized/worker.rb: 3 jobs running in parallel
D, [2020-01-17T13:01:26.111430 #29542] DEBUG -- socket[179ac24]: read 0 bytes
D, [2020-01-17T13:01:26.185903 #29542] DEBUG -- socket[1652b78]: read 0 bytes
D, [2020-01-17T13:01:26.212191 #29542] DEBUG -- socket[179ac24]: read 0 bytes
W, [2020-01-17T13:01:26.286961 #29542]  WARN -- : xxx-S5624P-SW-A1 raised IOError with msg "closed stream"
D, [2020-01-17T13:01:26.287128 #29542] DEBUG -- : lib/oxidized/node.rb: Oxidized::SSH failed for xxx-S5624P-SW-A1

====

CentOS Linux release 7.7.1908 (Core)
oxidized -v 0.27.0
