### ISSUE TITLE
Extraneous spacing when viewing specific version

### ISSUE THREAD

**Issue by candlerb** [ytti/oxidized#924]
When I directly view the config from the front page, everything is fine.

However, if I click on the "versions" icon, and then select a specific version, I see the output with excessive padding (looks like triple-spaced).  This is with Chrome under OSX. If I 'inspect' the element then I see:

![image](https://user-images.githubusercontent.com/44789/27932648-6e88ec4e-6296-11e7-99c9-b2eef5d8402e.png)

And in the source:

![image](https://user-images.githubusercontent.com/44789/27932527-f55685f2-6295-11e7-95a3-1de3a1e7b4f1.png)

And in the CSS pane:

![image](https://user-images.githubusercontent.com/44789/27932545-0787aefe-6296-11e7-9d66-7245fa380a4b.png)

I believe the problem is with the newlines combined with `white-space: pre`.  If I remove the spurious white space from within the `<div>` elements then it formats properly:

![image](https://user-images.githubusercontent.com/44789/27932632-5e1a9c90-6296-11e7-8211-cfc05c77bb51.png)

![image](https://user-images.githubusercontent.com/44789/27932664-853bbf98-6296-11e7-98b4-5143e20badf8.png)

**Comment by ytti** [comment]
This is oxidized-web issue. Pull request to oxidized-web would be greatly appreciated. By now almost none of the views code and CSS is written by me. So in all probability you already know more about it than I do.

**Comment by candlerb** [comment]
Sorry about that. I think that https://github.com/ytti/oxidized-web/issues/132 already covers this, but the screenshots here may be helpful.
