### ISSUE TITLE
Add support for setting hmac

### ISSUE THREAD

**Issue by mkevenaar** [ytti/oxidized#927]
Hi,

some of our switches require to set a hmac. 

> diff ssh.rb ssh.rb.orig
> 44d43
> <       ssh_opts[:hmac] = vars(:ssh_hmac).split(/,\s*/) if vars(:ssh_hmac)

Can you add this to your code?

Thanks in advance

Maurice

**Comment by ytti** [comment]
sure send pull request

**Comment by laf** [comment]
No further information has been provided so this issue is being closed.

If you have more information to provide then please do so and we will re-open this issue.
