### ISSUE TITLE
Weird line spacing when looking at git diffs

### ISSUE THREAD

**Issue by mattie47** [ytti/oxidized#930]
Hi,

So I've just got Oxidized working today, and along with that I've just outputted data to a git repo.

However, when trying to look at any device diffs, I'm getting some rather strange line spacing (effectively making the output unreadable:

Please see below:

![image](https://user-images.githubusercontent.com/4696925/28002877-12c06172-658d-11e7-93c0-d0417bc37063.png)

![image](https://user-images.githubusercontent.com/4696925/28002991-f0a30efe-658d-11e7-8a48-6fa202ff0705.png)

Any thoughts?

**Comment by ytti** [comment]
This is oxidized-web issue, and I believe it has been fixed in recent pull request, just not released yet.

**Comment by mattie47** [comment]
Correct. This has been fixed by 
https://github.com/ytti/oxidized-web/commit/57e32ddca56d8647da332bb24088860359780d91?diff=unified

I was able to edit the two affected files with the above changes and it has fixed my issue.

Thanks,

Matt
