### ISSUE TITLE
Add extra lines/output to the saved config file. 

### ISSUE THREAD

**Issue by mattie47** [ytti/oxidized#933]
Hi,

I've been trying to figure out how I can do something as simple as add a comment or new line into the saved config file?

I've spent some time today googling and trying various ruby config but having no major luck.

Take the following example of saved config:

```
! System Name
!  Switch
! System Contact
! 
! System Location
show running-config
!
service password-encryption
!
hostname Switch
```

I simply want to add a line of "-----------" followed by a new line before the "show running-config" starts.

Surely this is something simple I add to the vendor model file?

I know I can do this in a gross way by actually sending a command to the device and saving it, but surely there's a better way of doing this. What I currently have configured is below:

```
 #This shows the system information at the top and comments it out#
  cmd 'show system' do |cfg|
    cfg = cfg.each_line.to_a[0...-2]


   # Strip system (up)time and temperature
    cfg = cfg.reject { |line| line.match /System Status\s*.*/ }
    cfg = cfg.reject { |line| line.match /RAM\s*:.*/ }
    cfg = cfg.reject { |line| line.match /Uptime\s*:.*/ }
    cfg = cfg.reject { |line| line.match /Flash\s*:.*/ }
    cfg = cfg.reject { |line| line.match /Current software\s*:.*/ }
    cfg = cfg.reject { |line| line.match /Software version\s*:.*/ }
    cfg = cfg.reject { |line| line.match /Build date\s*:.*/ }

    comment cfg.join
    end


#Gross way of adding a line to break up "show system" and "show run"
  cmd '!-----------------------------------------------------------------' do |cfg|
     cfg
  end


  #Actually get the devices running config#
  cmd 'show running-config' do |cfg|
    cfg
  end
```

I've tried looking through most vendor source files but haven't found one doing it.

Thanks

Matt

**Comment by laf** [comment]
Do you want to really store the output of different commands to different files? If so take a look at https://github.com/ytti/oxidized/issues/125 and see if it helps.

**Comment by mattie47** [comment]
Hi @laf ,

Thanks for the reply.

No I don't want to store it as a separate file. I just want format and make the output of the saved device config look legible. I just want to put a line in between the last show command and the beginning of the actual running-config so it's easier to see where the devices config begins.

Thanks,

Matt

**Comment by jdomag** [comment]
Looking for the same thing, any hint would be much appreciated.

**Comment by mattie47** [comment]
Essentially the feature request is just the ability to pass comments into the saved output file between commands being run.

Thanks,

Matt

**Comment by jdomag** [comment]
@mattie47 
I've done it in the following way. "Insert" puts additional string on the beginning of the output, where "<<" adds the string at the end. Hope it helps. 

cmd 'show version' do |cfg|                       
  cfg.gsub! /(U|u)ptime (.*)/, '<uptime removed>' 
  **cfg.insert(0,"\nStaring: show version \n")**     
  cfg                                             
  **cfg << "\n Ending: show version \n"**           
end

**Comment by laf** [comment]
Thanks for that @jdomag - @mattie47 Does that answer your question?

**Comment by mattie47** [comment]
@jdomag 

Thanks for those useful comments. I hadn't realised you'd edited your post, and added a few more useful things. Thanks!

@laf  Yeah I think my request has been answered. 

Using the following config: 

```
   cmd 'Show System' do |cfg|
    cfg.gsub! /System Status\s*.*/, ''
    cfg.gsub! /RAM\s*:.*/, ''
    cfg.gsub! /Uptime\s*:.*/, ''
    cfg.gsub! /Flash\s*:.*/, ''
    cfg.gsub! /Current software\s*:.*/, ''
    cfg.gsub! /Software version\s*:.*/, ''
    cfg.gsub! /Build date\s*:.*/, ''
    cfg.insert(0,"\n!-------------------------------------------------------------------------------- \n")
    cfg
    cfg << "\n!--------------------------------------------------------------------------------\n \n"
    end

  #Actually get the devices running config#
  cmd 'show running-config' do |cfg|
    cfg
  end


```

It outputs like so (which is pretty much what I was wanting):

```

!-------------------------------------------------------------------------------- 
Show System


Board      ID   Bay     Board Name                        Rev   Serial number
--------------------------------------------------------------------------------
Base       483          SwitchBlade x908 GEN2             X6-0  A10064A172100016
Expansion  487  Bay1    AT-XEM2-12XS                      X3-0  A05384A171600069
Expansion  486  Bay8    AT-XEM2-4QS                       X3-0  A05383A171600054
PSU        451  PSUA    AT-SBxPWRSYS2/AC                  A-2   6A000106        
Fan module 485  FANA    AT-FAN08                          A-0   -               
Fan module 485  FANB    AT-FAN08                          A-0   -               
--------------------------------------------------------------------------------


--------------------------------------------------------------------------------
Environment Status : Normal

Bootloader version : 6.2.6





Current boot config: flash:/default.cfg (file exists)

System Name
 C1-x908-STK
System Contact

System Location

C1-x908-STK#
!--------------------------------------------------------------------------------
 
show running-config
!
service password-encryption
!
hostname C1-x908-STK

`````

I haven't got it working perfect yet, but it's definitely in the right step.

Thanks again all.

Matt

**Comment by laf** [comment]
@mattie47 Ace. I'll close this down then, feel free to reply back if you need it opening.
