### ISSUE TITLE
Oxidized stops backups for one switch (NXOS)

### ISSUE THREAD

**Issue by rbeumer** [ytti/oxidized#934]
Our version: 0.19.0
We have an issue with (it seems) NXOS switches. We have two of them and after a random time Oxidized stops making backups for one of those switches. Other OS'es don't seem to have the issue. Forcing an update via the web interface does not work, the status remains green and not blue.

Debug output from the log file shows no entries regarding this device after the last successful backup:

    D, [2017-07-11T06:47:47.428233 #1576] DEBUG -- : lib/oxidized/worker.rb: Jobs 0, Want: 1
    D, [2017-07-11T06:47:47.428486 #1576] DEBUG -- : lib/oxidized/worker.rb: Added [aggr1.redacted-name] to the job queue
    D, [2017-07-11T06:47:47.428611 #1576] DEBUG -- : lib/oxidized/job.rb: Starting fetching process for [aggr1.redacted-name] at 2017-07-11 04:47:47 UTC
    D, [2017-07-11T06:47:47.428675 #1576] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
    D, [2017-07-11T06:47:47.428994 #1576] DEBUG -- : lib/oxidized/input/ssh.rb: Connecting to [aggr1.redacted-name]
    D, [2017-07-11T06:47:47.637429 #1576] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^(\r?[\w.@_()-]+[#]\s?)$/] at [aggr1.redacted-name]
    D, [2017-07-11T06:47:48.429470 #1576] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
    D, [2017-07-11T06:47:48.643417 #1576] DEBUG -- : lib/oxidized/input/cli.rb: Running post_login commands at [aggr1.redacted-name]
    D, [2017-07-11T06:47:48.643568 #1576] DEBUG -- : lib/oxidized/input/cli.rb: Running post_login command: "terminal length 0", block: nil at [aggr1.redacted-name]
    D, [2017-07-11T06:47:48.643610 #1576] DEBUG -- : lib/oxidized/input/ssh.rb terminal length 0 @ [aggr1.redacted-name] with expect: /^(\r?[\w.@_()-]+[#]\s?)$/
    D, [2017-07-11T06:47:48.643857 #1576] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^(\r?[\w.@_()-]+[#]\s?)$/] at [aggr1.redacted-name]
    D, [2017-07-11T06:47:49.045951 #1576] DEBUG -- : lib/oxidized/model/model.rb Collecting commands' outputs
    D, [2017-07-11T06:47:49.046117 #1576] DEBUG -- : lib/oxidized/model/model.rb Executing show version
    D, [2017-07-11T06:47:49.046182 #1576] DEBUG -- : lib/oxidized/input/ssh.rb show version @ [aggr1.redacted-name] with expect: /^(\r?[\w.@_()-]+[#]\s?)$/
    D, [2017-07-11T06:47:49.046388 #1576] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^(\r?[\w.@_()-]+[#]\s?)$/] at [aggr1.redacted-name]
    D, [2017-07-11T06:47:49.429838 #1576] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
    D, [2017-07-11T06:47:49.448977 #1576] DEBUG -- : lib/oxidized/model/model.rb Executing show inventory
    D, [2017-07-11T06:47:49.449103 #1576] DEBUG -- : lib/oxidized/input/ssh.rb show inventory @ [aggr1.redacted-name] with expect: /^(\r?[\w.@_()-]+[#]\s?)$/
    D, [2017-07-11T06:47:49.449307 #1576] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^(\r?[\w.@_()-]+[#]\s?)$/] at [aggr1.redacted-name]
    D, [2017-07-11T06:47:49.853733 #1576] DEBUG -- : lib/oxidized/model/model.rb Executing show running-config
    D, [2017-07-11T06:47:49.853864 #1576] DEBUG -- : lib/oxidized/input/ssh.rb show running-config @ [aggr1.redacted-name] with expect: /^(\r?[\w.@_()-]+[#]\s?)$/
    D, [2017-07-11T06:47:49.854074 #1576] DEBUG -- : lib/oxidized/input/ssh.rb: expecting [/^(\r?[\w.@_()-]+[#]\s?)$/] at [aggr1.redacted-name]
    D, [2017-07-11T06:47:50.430230 #1576] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
    D, [2017-07-11T06:47:50.487233 #1576] DEBUG -- : lib/oxidized/input/cli.rb Running pre_logout commands at [aggr1.redacted-name]
    D, [2017-07-11T06:47:50.487363 #1576] DEBUG -- : lib/oxidized/input/ssh.rb exit @ [aggr1.redacted-name] with expect: nil
    D, [2017-07-11T06:47:51.430643 #1576] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
    D, [2017-07-11T06:47:52.431183 #1576] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
    D, [2017-07-11T06:47:53.431721 #1576] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
    D, [2017-07-11T06:47:54.432224 #1576] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
    D, [2017-07-11T06:47:55.432740 #1576] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
    D, [2017-07-11T06:47:56.433088 #1576] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
    D, [2017-07-11T06:47:57.433664 #1576] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
    D, [2017-07-11T06:47:58.434150 #1576] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
    D, [2017-07-11T06:47:59.434648 #1576] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
    D, [2017-07-11T06:48:00.435324 #1576] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
    D, [2017-07-11T06:48:01.435871 #1576] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
    D, [2017-07-11T06:48:02.436705 #1576] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
    D, [2017-07-11T06:48:03.437263 #1576] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
    
    [...] 
    
    D, [2017-07-11T06:52:47.586554 #1576] DEBUG -- : lib/oxidized/worker.rb: Jobs 1, Want: 2
    D, [2017-07-11T06:52:47.586819 #1576] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
    D, [2017-07-11T06:52:48.587727 #1576] DEBUG -- : lib/oxidized/worker.rb: Jobs 1, Want: 2
    D, [2017-07-11T06:52:48.587894 #1576] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
    D, [2017-07-11T06:52:49.588132 #1576] DEBUG -- : lib/oxidized/worker.rb: Jobs 1, Want: 2
    D, [2017-07-11T06:52:49.588340 #1576] DEBUG -- : lib/oxidized/worker.rb: 1 jobs running in parallel
    D, [2017-07-11T06:52:50.588654 #1576] DEBUG -- : lib/oxidized/worker.rb: Jobs 1, Want: 2

**Comment by rbeumer** [comment]
It seems that Oxidized as a whole is slowing down. Backups are often a few hours late until I restart the service.

**Comment by wk** [comment]
@rbeumer Are you still experiencing this issue? Have you attempted upgrading to the latest version of Oxidized to see if that improves matters?

**Comment by laf** [comment]
Looks to be the same as #887 so probably worth closing this down @wk
