### ISSUE TITLE
Reload button on nodes uri doesn't honor rest config entry

### ISSUE THREAD

**Issue by jgroom33** [ytti/oxidized#937]
Config file snippet:
....
debug: false
threads: 30
timeout: 20
retries: 3
rest: 0.0.0.0:8888/oxidized
....

Reload button always directs to https://x.x.x.x/reload.json
Reload button *should* direct to https://x.x.x.x/oxidized/reload.json assuming above config snippet

**Comment by laf** [comment]
Is this not for [oxidized-web](https://github.com/ytti/oxidized-web) rather than here?

**Comment by jgroom33** [comment]
Thanks.  I didn't realize they were separate.
