### ISSUE TITLE
Additional hooks for API calls

### ISSUE THREAD

**Issue by mrplow87** [ytti/oxidized#940]
I'm proposing an additional `post_store` hook, if the configuration pull was initialized through an API call (`/node/next/[node_name]`).

The scenario I'm thinking of is this: 
Oxidized has a scheduled run once a day (at night for example). Changes found during these scheduled runs should trigger a notification script through the `post_store` hook and inform us about undocumented changes (it could be a security issue).

Now, during work hours, configuration changes are made by an admin and an API call is issued to Oxidized after logout from the switch (`/node/next/...`) . This change should not trigger the `post_store` hook, because this change is wanted and will be documented. So an additional `post_store` hook is needed which only applies to API calls. Also, the post_store hook needs to know it was not triggered by the API.

Is this something others would want? I'm trying to figure out how this could be done in the code, but I'm fairly new to Ruby, so I can't make any promises for a PR 🙁 Trying my best, though!

The possibility to edit the commit message while doing the API call would be nice (maybe by using a HTTP header?), but that's just wishful thinking.

**Comment by mrplow87** [comment]
While working through the code ([oxidized-web], [oxidized]), I found out how to submit author and commit message. 

For anyone interested:

`curl -X PUT -d '{"user":"Foo Bar","from":"foo@bar.tld","msg":"Your message here"}' "http://127.0.0.1:8888/node/next/node.name.local?format=json"`

This will cause the commit message in your repository to look like this:
`update node.name.local from foo@bar.tld with message 'Your message here'`

So, the mentioned API call in Oxidized's README.md is a `PUT` request, not `POST`.

[oxidized-web]: https://github.com/ytti/oxidized-web/blob/master/lib/oxidized/web/webapp.rb#L106
[oxidized]: https://github.com/ytti/oxidized/blob/master/lib/oxidized/nodes.rb#L70

**Comment by danilopopeye** [comment]
@mrplow87 could you open a PR to document this behaviour?

**Comment by mrplow87** [comment]
PR created, discussion started :)
