### ISSUE TITLE
Aruba S2500-24P/48P

### ISSUE THREAD

**Issue by BullfroG21** [ytti/oxidized#941]
Hi,

I have problems fetching the configuration from devices of Aruba S2500-24P/48P.
The node does not fail (at least the Oxidized web GUI is showing green), but there is actually no configuration stored. 

I added some verbose messages in the aows.rb model, so I am able to see that Oxidized is able to access the via SSH and the read the configuration.

Does anyone has an idea or a similar issues?

Keep on the great work on this project.
with kind regards

**Comment by laf** [comment]
You should enable debug in oxidized config as per the README, then take a look at the debug file created for that device.

**Comment by laf** [comment]
@BullfroG21 Any update on this?

**Comment by laf** [comment]
No further update provided so this issue is being closed.

If you have more info to provide then please respond and we can re-open this issue.
