### ISSUE TITLE
Version crash

### ISSUE THREAD

**Issue by Ynnot** [ytti/oxidized#944]
Hi,

When i try to see version of my devices, oxidized crash  with this error :

![image](https://user-images.githubusercontent.com/24589443/28563408-2a93ad82-7126-11e7-95bb-ee3886f0a947.png)

When i search the VmSize and VmPeak on my server i see that VmPeak is bigger than VmSize : 

![image](https://user-images.githubusercontent.com/24589443/28563705-0da61074-7127-11e7-94bb-fc27109ef1b0.png)

Do you know if it's possible to fix it ? 

Thank you

**Comment by laf** [comment]
Try starting oxidized in a screen session or in the foreground to see what's recorded when it crashes.

**Comment by laf** [comment]
@Ynnot Any update on this?
