### ISSUE TITLE
Wrong success status on devices with enable

### ISSUE THREAD

**Issue by michael-todorovic** [ytti/oxidized#945]
Hello,
It seems like errors on devices with enable functions are not handled correctly. I had the case where first password is correct BUT enable password was wrong in oxidized configuration.

The first steps are working so it makes oxidized happy. After that, it tries to "enable"and it can't dump the configuration because of the wrong enable password. However, it still shows a success status, which is wrong. It should be failed or warning.

Michael

**Comment by danilopopeye** [comment]
@michael-todorovic can you post the output generated in this case?

**Comment by laf** [comment]
No further information has been provided so this issue is being closed.

If you have more information to provide then please do so and we will re-open this issue.
