### ISSUE TITLE
Driver for Westell 8178G and Westell 8266G devices

### ISSUE THREAD

**Issue by ignaqui** [ytti/oxidized#946]
### I'm submitting a ...
- [ ] Bug report
- [X] Feature requested
- [ ] Question / Support request

Hello,

We use Westell devices in our network (mostly Westell 8178G and Westell 8266G), so I wrote a driver for them devices (file attached). Please be aware that ssh daemon is broken on those devices, so only telnet-based shell works.
Maybe it worth to add driver to the code.

Thank you,
ignaqui
[weos.txt](https://github.com/ytti/oxidized/files/1180260/weos.txt)

**Comment by laf** [comment]
You should submit a pull request with this new model @ignaqui
