### ISSUE TITLE
Question: Is Github the required out to enable Config Diff?

### ISSUE THREAD

**Issue by merryllem** [ytti/oxidized#949]
Is Github the required output to enable Config Diff?

**Comment by davromaniak** [comment]
Hi.

No, you only need to use GIT as the output and Oxidized will create a local GIT repository.

After that, you can place a hook to push it to a remote GIT repository but that's not mandatory.

Thanks.

**Comment by laf** [comment]
@merryllem You need to use git output to get config diff via the oxidized webui. https://github.com/ytti/oxidized#output-git

From there you can send your configs to a remote git repository as well.

**Comment by laf** [comment]
@merryllem any update on this?

**Comment by merryllem** [comment]
Thank you, that answered my question.
