### ISSUE TITLE
Interval seems to unset threads

### ISSUE THREAD

**Issue by gbeekmans** [ytti/oxidized#957]
With the interval variable set to '0' I am able to set the 'treads' variable to a sufficiently high number to effectively poll all my configured nodes at once and have it finish up checking everything within a minute or so.

When I set 'interval' to a value (say 3600 to re-check everything hourly) it seems to no longer honour the configured threads. Observing network traffic, it checks nodes one or two at a time. It would take over an hour to check all nodes at that rate. In some cases that's too long for us to wait for changes to be captured.

Is this by design or have I setup something incorrectly?

**Comment by laf** [comment]
The interval variable is as far as I'm aware the configured time you want all devices to poll in, more threads will be spawned as needed to accomplish that.

**Comment by gbeekmans** [comment]
If that is the case, how do I configure Oxidized to re-check all nodes once in a while? Our equipment configuration changes frequently so I'd want to obtain a new set of config files a few times a day at minimum (hourly preferably).

**Comment by laf** [comment]
Setting interval to 3600 will attempt to backup the configs once an hour.

**Comment by laf** [comment]
No further information has been provided so this issue is being closed.

If you have more information to provide then please do so and we will re-open this issue.
