### ISSUE TITLE
Last Update listed sometimes in UTC sometimes in local timezone

### ISSUE THREAD

**Issue by gbeekmans** [ytti/oxidized#958]
After all nodes have been polled some nodes are showing a last update time in the current timezone ie:
2017-08-02 15:47:42 MDT

For other nodes it shows UTC:
2017-08-02 21:47:57 UTC

What causes this inconsistency?

**Comment by ignaqui** [comment]
+1
I have the same exact issue

**Comment by 191801737** [comment]
I have the same exact issue

**Comment by davama** [comment]
Just noticed this myself too...
![image](https://i.imgur.com/HaiqXwH.png)

The actual server where oxidized is, is configured with UTC

**Comment by wk** [comment]
Potentially duplicate of ytti/oxidized-web#120 ytti/oxidized-web#125 ytti/oxidized-web#158

**Comment by packetlifter** [comment]
I've solved this today by adding the `convertTime ` function to the /oxidized-web-0.13.1/lib/oxidized/web/views/nodes.haml file and then called the function on load.

![image](https://user-images.githubusercontent.com/50010791/65813444-dfdd9500-e207-11e9-9c1b-c80429afcc23.png)
