### ISSUE TITLE
Question: Trigger backup from on device and add comments to go into Git commit

### ISSUE THREAD

**Issue by mattie47** [ytti/oxidized#961]
Hi,

So I was thinking it would be quite cool to actually be on a switch/router and trigger oxidized to do a backup.

Furthermore, given that backups are stored in Git, I was hoping to then somehow add a comment into the git backup when I trigger it. 

On Allied Telesis products, the user can use bash scripts for this task (and activate the .sh file from the CLI)

Allied Telesis has busybox in the shell, so most commands like wget etc work from bash scripts. 

So essentially what I want to do:

- After making some config changes, run a bash script to get oxidized to poll the device. When doing the backup, comments get added to the new revision file in git. 

So something like:

awplus#activate config_backup.sh --comment "Removed old SNMPv2 server. Replaced with new SNMPv3 server and user/password"

I was hoping someone might be able to give me some pointers with where to start on this task? 

Bear in mind I'm also relatively new to git, but know it has a lot of potential..

**Comment by mattie47** [comment]
I just noticed the "Message" field in the version page.

Have done a quick google and come across #516 which I have not yet had time to investigate, but will look into hopefully later this week.


Thanks,

Matt

**Comment by laf** [comment]
@mattie47 As you've found, this is definitely something that's been asked and answered before :)

I'm closing this down as it's not something that needs to be fixed here. Feel free to ask similar questions on the irc channel or gitter.

**Comment by mattie47** [comment]
Hi @laf 

No worries with closing this. 

What's useful is you've pointed out there's an IRC channel for asking more informal questions.

What are the details for IRC or gitter? Perhaps this would be useful in the readme?

Thanks,

Matt
