### ISSUE TITLE
Question: How are people populating their source list of devices?

### ISSUE THREAD

**Issue by mattie47** [ytti/oxidized#962]
I know Oxidized has a lot of potential, especially given that the source list of devices can either be a static file, or an sql database etc.

What I'm curious about, is how people may be populating this information dynamically?

There is probably a hundred ways to do this, but I'm just curious what people may be currently doing. 

Any tips/thoughts/comments?

Three ways I'm intrigued to try (but not sure how yet):

- Populate database file from Oxidized web end

This would be really useful, especially as it could be a tab beside migration (or part of the migration page), and I suspect you could probably do this somehow with PHP.

- Populate Oxidized by getting device list from LibreNMS

Given the current integration between LibreNMS and Oxidized, it would be cool if there was a field within Libre (where the config tab is) to actually kick off populating the device in Oxidized if it wasn't already.

-  Populate the device list based on a custom file

This is probably what a number of people do. Whether it's a file output from a device inventory system or something else, but somehow get the list of devices then add required variables such as vendor and model.

I'm just wondering how people may already be doing this (as it should be pretty generic and have logic it putting into the required oxidized format).

Overall, my programming/scripting knowledge sucks but I'm willing to learn!

Thanks,

Matt

**Comment by davama** [comment]
> Populate the device list based on a custom file

This is sort of what we do. But our custom file is technically our monitoring system which we update manually. We pull from there and update the sqllite db. If device is dead then we dont add to the oxidized db so oxidized doesnt waste time on dead devices.

But my OCD kicks in so how do we know that a config is still valid/decommed or not? We also have a script that checks the age of the git repo and flags them if 6months old or deletes them automatically if 1year old. Still waiting on the 1 year part of the script to run....dec 2017 here we come!

environment of about 15,000+ devices...yay!

**Comment by laf** [comment]
@mattie47 I'm not really sure what you're trying to gain from these questions (don't take offence to that comment :). The way you've described the above ways to feed data into Oxidized already exist already and are documented in the readme. Do you need specific help with one of them?

**Comment by mattie47** [comment]
Hi @davama 

Thanks for that insight!


Hi @laf 

Essentially what I'm trying to gain is more of an understanding or examples of how others might have achieved similar tasks to what I suggested.

I've spent a lot of time in the readme file and blog posts such as:

http://packetpushers.net/install-oxidized-network-configuration-backup/

https://log.cyconet.org/2016/01/29/oxidized-silly-attempt-at-really-awesome-new-cisco-config-differ/

http://www.whoopis.com/core/oxidized-quickstart-tutoria.html


But there are still quite a few gotchas when you're doing all this for the first time... 

I've been documenting stuff as I go as I hope to do my own blog post at some point.

I guess you could say I've asked these questions because the readme is useful from the POV that it explains how to configure things on Oxidize's side, however having never done SQL or the other database options before, I was hoping someone might be able to point to an example of how they have achieved this with theirs.

Alternatively, I have Oxidized working with LibreNMS - Is there a way to populate Oxidized with the devices configured inside Libre?

**Comment by laf** [comment]
So for MySQL based on the example config you would need a table called nodes

Within that table the following columns:
ip
model
username
password
enable

You can actually call these what you like as long as you set the mapping correctly as per the example config: https://github.com/ytti/oxidized/#source-mysql

LibreNMS is easy: http://docs.librenms.org/Extensions/Oxidized/ + the default docs for Oxidized are based on LibreNMS setup.

**Comment by mattie47** [comment]
Hey thanks for the help @laf 

I haven't had time yet to have a look into this, but you've sufficiently answered my question. 

I intend on trying to use LibreNMS to populate my database of devices to backup, which you mentioned on  https://gitter.im/oxidized is relatively easy to do by following "feeding oxidized" here: http://docs.librenms.org/Extensions/Oxidized/

Thanks for that. 

Will close this and if I think of anything more useful, I'll add a comment here. 

Thanks.
