### ISSUE TITLE
How to correctly configure passwords with special characters in  config file?

### ISSUE THREAD

**Issue by telskamp** [ytti/oxidized#964]
Hey  Guys sorry to  ask this noob question  I am currently configuring an oxidized docker to work with my librenms monitoring server.
I managed to get the device import from librenms working. However since we are using passwords that begin and/or end with special characters I cannot get it to work.
If i just put the passwords in like below oxidized errors and wont start, However if i put them between single or double quotes, oxidized does start but is not able to login.
`
models:
  ios:
    username: admin
    password: *BLABLA?
    vars:
      enable: !password#
`
Anyone care to comment/have a solution for this?

**Comment by laf** [comment]
You could try escaping the chars, `\*BLABLA\?

**Comment by telskamp** [comment]
the character  ``   is not accepted at all it seems:
`Error loading config: (<unknown>): found character that cannot start any token while scanning for the next token at line 54 column 15 (Oxidized::InvalidConfig)`

**Comment by laf** [comment]
Sorry that was my mistake, missed the other ` which was to show code rather than for you to use. Take another look.

**Comment by telskamp** [comment]
np, I am now trying with backslashes, will report back in a bit. Is it me or is this yaml format just a pain in the behind?

**Comment by laf** [comment]
I happen to like it :) But then we are switching a lot over to yaml in LibreNMS so maybe I'm a bit biased :D

**Comment by telskamp** [comment]
it still is not giving me the juice Is there anything else i could have done wrong? I am trying to use oxidized  to backup our cisco devices using telnet  but it does not work  when i enable debugging this is the only thing it gives me:

`Password:                                                                                                                                                                                                                                                     
% Password:  timeout expired!                                                                                                                                                                                                                                 
Password:                                                                                                                                                                                                                                                     
% Password:  timeout expired!                                                                                                                                                                                                                                 
Password:                                                                                                                                                                                                                                                     
% Password:  timeout expired!                                                                                                                                                                                                                                 
% Bad passwords        `

**Comment by telskamp** [comment]
when i manually loging using telnet i am able to login using the same pasword I have in  my config file

**Comment by laf** [comment]
Unfortunately I'm not sure I've got anything else to suggest. You could post the full debug file?

**Comment by telskamp** [comment]
Well the full debug file does contain a lot of company specific info i would rather not put online.
I did make a little redacted file that only contains information about one of the first network devices it is trying to back-up and replaced the telnet password with "telnetpassword" I can confirm that I am able to login to this switch using telnet  and the password it is using. What I did notice is that nowhere in the process it is actually listing our vars: enable: password (which has special characters) What also stands out to me is that it is trying to resolve the ip address?
[oxidebug.txt](https://github.com/ytti/oxidized/files/1205024/oxidebug.txt)

**Comment by laf** [comment]
Is that the specific devices debug / crash file?

**Comment by telskamp** [comment]
I am not sure which file you are referring to, these are the debug logs it is spitting out to the docker container log file. in the oxidized/logs/10.0.0.114-telnet file it only states:

User Access Verification

Password:
% Password:  timeout expired!
Password:
% Password:  timeout expired!
Password:
% Password:  timeout expired!
% Bad passwords

**Comment by telskamp** [comment]
@laf  You may close this incident, I have finally gotten green-light to reconfigure our switches to use ssh and using ssh it works like a charm! telnet sux anyway.
Thank you for your advise and support so far. If your ever in the Netherlands I would like to buy you a beer!
Keep up the good work!
