### ISSUE TITLE
Edit the config to proxy ssh ?

### ISSUE THREAD

**Issue by reavenm** [ytti/oxidized#973]
It would be possible to proxy the ssh/telnet but in the sense of editing the config to ssh a router through another router or even telnet ?

**Comment by danilopopeye** [comment]
have you looked at the [ssh-proxy-command](https://github.com/ytti/oxidized#ssh-proxy-command) config?

**Comment by reavenm** [comment]
I saw that and I know normally you use a linux host for this but is possible to use a Cisco router to connect to another cisco router through oxidized ?

**Comment by danilopopeye** [comment]
not that I'm aware of, sorry.

**Comment by reavenm** [comment]
btw, exactly how the proxy variable works ?

**Comment by reavenm** [comment]
i am able to proxy ssh directly from the oxidized server , but how is this configure in oxidized

**Comment by danilopopeye** [comment]
assuming you have mapped the variables as described in the [docs I mentioned](https://github.com/ytti/oxidized/issues/973#issuecomment-322831306), then you should pass the host to be used as proxy in that field. it will look something like this in your router.db:

    name:model:enable:host.to.proxy

you can have a look in the actual code here: [input/ssh.rb](https://github.com/ytti/oxidized/blob/b7f823617c9babb416d797334a2d6951d6a9f223/lib/oxidized/input/ssh.rb#L36-L42)

**Comment by laf** [comment]
No further response has been provided to this so this issue is now being closed.

If you have further information, please provide it and we can re-open this issues.
