### ISSUE TITLE
Help - login with web authentication (nginx)

### ISSUE THREAD

**Issue by kiq-moraes** [ytti/oxidized#977]
Hello guys,
I 'm using CENTS 7 running oxidized and I' d like some kind of web authentication, to avoid undue hits.
I tried the following commands below , but the pop window does not appear to enter user and password.
Could someone suggest me something or exemplify how can I do this?

I already created the username and password with:

    sudo htpasswd -c /etc/nginx/.htpasswd nginx

in nginx.conf:

```
 server {
        listen       80 default_server;
        listen       [::]:80 default_server;
        server_name  _;
        root         /usr/share/nginx/html;
        auth_basic "Acesso Restrito";
        auth_basic_user_file /etc/nginx/.htpasswd;
        // Load configuration files for the default server block.
        include /etc/nginx/default.d/*.conf;
        location / {
        proxy_pass ip:port/;
        //auth_basic "Acesso Restrito";
        //auth_basic_user_file /etc/nginx/.htpasswd;
        }
        error_page 404 /404.html;
            location = /40x.html {
        }
        error_page 500 502 503 504 /50x.html;
            location = /50x.html {
        }
    }
```

Thanks!

Caíque

**Comment by danilopopeye** [comment]
@kiq-moraes could you try this guide: [how-to-set-up-basic-http-authentication-with-nginx-on-centos-7](https://www.digitalocean.com/community/tutorials/how-to-set-up-basic-http-authentication-with-nginx-on-centos-7)

**Comment by kiq-moraes** [comment]
Hi guys,
I fixed the lines that were wrong and now it's working!
Thank you all.

 server {
        listen ip:port;
        server_name _;
        root         /usr/share/nginx/html;
        // Load configuration files for the default server block.
        include /etc/nginx/default.d/*.conf;
        location / {
        auth_basic "Acesso Restrito";
        auth_basic_user_file /etc/nginx/.htpasswd;
        proxy_pass http://127.0.0.1:port/;
}
