### ISSUE TITLE
Help with getting "nodiff" working for output

### ISSUE THREAD

**Issue by mattie47** [ytti/oxidized#978]
Hi,

Firstly thanks to those who have helped me with various issues thus far...

I've been trying to get my head around https://github.com/ytti/oxidized#output-types

This implies you can have devices polled and have some commands such as "show version" or "show system" stored in a "nodiff" repository, meanwhile commands such as "show run" are stored in a different repo which diffs can be achieved.

Maybe I've been expecting too much, but I assumed after configuring this, you'd be able to see both from the oxidized web gui correct? 

I was half expecting if I clicked on a node and downloaded the config it would show me first the "show version" followed by the actual running-config. If I desired to see a diff of configs, I would just do this as per normal.

Is this how this functionality works?  Or am I limited to looking specifically at the git repo itself for this sort of information?

For reference, I've been trying various things on my alliedwarePlus.rb file:

````
oxidized@mattr-tb:/var/lib/gems/2.3.0/gems/oxidized-0.20.0/lib/oxidized/model$ cat nano alliedwareplus.rb
class AlliedwarePlus < Oxidized::Model

  #Allied Telesis Alliedware Plus Model#
  
  prompt /^(\r?[\w.@:\/-]+[#>]\s?)$/
  comment  '! '

#   cmd 'Show System' do |cfg|
#    cfg.gsub! /System Status\s*.*/, ''
#    cfg.gsub! /RAM\s*:.*/, ''
#    cfg.gsub! /Uptime\s*:.*/, ''
#    cfg.gsub! /Flash\s*:.*/, ''
#    cfg.gsub! /Current software\s*:.*/, ''
#    cfg.gsub! /Software version\s*:.*/, ''
#    cfg.gsub! /Build date\s*:.*/, ''
#    comment cfg.insert(0,"--------------------------------------------------------------------------------! \n")
#	Unhash below to write a comment in the config file.
#    cfg.insert(0,"Starting: Show system! \n")
#    comment cfg
#	Unhash below to write a comment in the config file.
#   cfg << "\n\nEnding: show system!"
#    comment cfg << "\n--------------------------------------------------------------------------------! \n\n"
#    end


  cmd 'show version' do |state|
    state.type = 'nodiff'
    state
  end

  #Actually get the devices running config#
  cmd 'show running-config' do |state|  
    state = Oxidized::String.new state
    state
  end

  #Only configured for SSH. Needed to add 'enable' as Priv-Exec users don't get 
  #put into "enable mode" by default on login. 
  #Set term length to 0 so the entire config is output without intervention.
  #Finally, "terminal no length" is added to set the terminal length back to default.

  cfg :ssh do
    post_login 'enable'
    post_login 'terminal length 0'
    pre_logout 'terminal no length'
    pre_logout 'exit'
  end


end
````

Does my device file look correct? 

Thanks,

Matt

**Comment by mattie47** [comment]
Okay so I do actually see the show version when I do a git clone of the primary repo:

-rw-r--r-- 1 oxidized oxidized  4355 Aug 21 16:06 d1-x550--show_running-config
-rw-r--r-- 1 oxidized oxidized 12806 Aug 21 16:06 d1-x550--show_version

Does oxidized web have functionality around the nodiffs output, or is it expected you manage all of this in an external git server, or perhaps use something like gitlab?

Thanks,

Matt

**Comment by mattie47** [comment]
The only reference I've found of someone else using nodiff is https://github.com/ytti/oxidized/issues/201 

If there are any other examples (beyond the README) I'm happy to look further.

Thanks,

Matt

**Comment by danilopopeye** [comment]
> Does oxidized web have functionality around the nodiffs output, or is it expected you manage all of this in an external git server, or perhaps use something like gitlab?

don't remember ever seeing anything related to output types in oxidized web. actually, never used myself. 😛 

@mattie47 do you see a error or anything at all when searching for this device in oxidized web?

**Comment by mattie47** [comment]
Hi @danilopopeye 

No errors. I don't recall seeing anything unusual in the logs either.

![1](https://user-images.githubusercontent.com/4696925/29538896-d28e20f2-871b-11e7-966a-70042dde3575.PNG)
![2](https://user-images.githubusercontent.com/4696925/29538897-d29035a4-871b-11e7-87a6-9e048ef86a50.PNG)


Thanks,

Matt

**Comment by mattie47** [comment]
Closing as this is likely an enhancement request for https://github.com/ytti/oxidized-web/
