### ISSUE TITLE
Oxidized and FIB's ( FREEBSD )

### ISSUE THREAD

**Issue by winglessza** [ytti/oxidized#981]
Hi,

Been using oxidized for around 6 months now great piece of software. Ive been using rancid for a couple of years , with some heavy customization to cater for multiple rdomains (openBSD) and FIB's ( FreeBSD ).

Is there an easy way to execute custom ssh or telnet commands via config and var maps to FIBS through mysql innate to the current code, rather than having to rewrite some of the code myself.

ie.

FreeBSD : 
setfib -T10 ssh 10.0.0.1
-> run command withing forward information base (Routing Table 10 )

OpenBSD:
route -T10 execute ssh 10.0.0.1
-> run command with rdomain 10 (Routing Table 10)

Thanks.

**Comment by laf** [comment]
If I understand what you want correctly then you would need to run a custom model that will run these commands.

**Comment by winglessza** [comment]
Do you perhaps have any direction here on the context that would be used to execute this type customization within a model file?

**Comment by laf** [comment]
Do you have a base model you're working from?

**Comment by winglessza** [comment]
class JunOS < Oxidized::Model

**Comment by laf** [comment]
https://github.com/ytti/oxidized/blob/master/lib/oxidized/model/junos.rb#L39

Possibly duplicate those lines and change the commands being sent? Bear in mind I'm not a ruby dev.

**Comment by laf** [comment]
No further information has been provided so this issue is being closed.

If you have more information to provide then you can respond and we will re-open this issue.
