### ISSUE TITLE
store multiple versions.

### ISSUE THREAD

**Issue by seekerOK** [ytti/oxidized#984]
It is possible to store multiple version in file output ? Like keep the last x backups.

**Comment by laf** [comment]
Nope:

#903
#425

**Comment by seekerOK** [comment]
I dont think is the same, I am **NOT** talking about using git + file.
I mean only use file as output but instead of the backup replace the flat file just keep x number of backup, like the last two flat files backup.

**Comment by laf** [comment]
You need to use git for that, flat files don't understand or support versioning.

**Comment by seekerOK** [comment]
Don't get fixated in the term "versions/versioning", I know thats what git is for and I know flat files done understand/support "versioning"
I just want to keep the last 2,3,etc..  flat files instead of replacing the same. if that cant be done or added, well ok.

**Comment by laf** [comment]
It isn't supported at present no.

Personally and this isn't the projects stance, I don't see why that would be added when git provides that. Regardless of the word 'versioning'

**Comment by rbeumer** [comment]
I agree about Git being the best solution for this. You could probably hack something together with logrotate, though it would be very ugly and would require way more effort than using a Git repo.
