### ISSUE TITLE
Is the aruba mobility controller supported ?

### ISSUE THREAD

**Issue by seekerOK** [ytti/oxidized#985]
Is the Aruba Mobility Controller supoported ? 
**Model: | Aruba3400-US
Version: | 6.4.4.9**

I am getting a "... _raised Oxidized::ModelNotFound with message 'AOSW not found for node x.x.x.x_ '

**Comment by seekerOK** [comment]
didnt know models is case sensitive in router.db, **AOSW != aosw**

**Comment by seekerOK** [comment]
It does the backup but raised an error: **raised Timeout::Error with msg "timed out while waiting for more data"**
this is the log for the device:
    
```
process monitor log
end

(AOSW-001) #exit
(AOSW-001) >exitConnection closed by foreign host.
```

**Comment by seekerOK** [comment]
the above device log is when it capture the backup through ssh, the error apparently raised when it tries to exit the telnet session device telnet log below
    
```
no snmp-server enable trap

process monitor log
end

(AOSW-001) #▒▒e▒▒x▒▒i▒▒t▒▒
(AOSW-001) >
```

**Comment by seekerOK** [comment]
get rid of the error by changing the _input order_ from **telnet, ssh -> ssh, telnet**

but the telnet session seems to be missing an additional **exit**

**Comment by laf** [comment]
Would you be able to submit the fixes on a PR?

**Comment by seekerOK** [comment]
I would not know where to fix this.
I assume it would be in the aosw.rb, around here, but not sure:
```
    cfg :telnet do
    username /^User:\s*/
    password /^Password:\s*/
  end

  cfg :telnet, :ssh do
    if vars :enable
      post_login do
        send "enable\n"
        cmd vars(:enable)
      end
    end
    post_login 'no paging'
    post_login 'encrypt disable'
    if vars :enable
      pre_logout 'exit'
    end
    pre_logout 'exit'
  end
```
And I didn't fix it I  just avoid the error by connecting via ssh first.
