### ISSUE TITLE
Parse name from comment

### ISSUE THREAD

**Issue by sts** [ytti/oxidized#990]
Some devices show the name of the user who committed a configuration version in the `sh run` output. It would be great if the username would get parsed by oxidized and made be available in hooks. This could be used to mention users in git commits messages, webhooks etc.

Is this a feature which would make it into upstream?

**Comment by mattie47** [comment]
This would be pretty cool...

Perhaps https://github.com/ytti/oxidized/issues/714 would be a starting point on this?

**Comment by danilopopeye** [comment]
@sts can you post a example from a device?

**Comment by ZacharyPuls** [comment]
@danilopopeye I'm not the OP, but here's what I've used in the IOS `show running-config` output to determine which user changed the config:
![gitlab-update](https://user-images.githubusercontent.com/15753366/30342459-9728d7a0-97bf-11e7-800e-0dfbea924f6f.PNG)

**Comment by sts** [comment]
@danilopopeye see below for some examples:

Cisco ASR
```
! Last configuration change at 00:00:00 UTC Thu Aug 01 2017 by root
! NVRAM config last updated at 00:00:00 UTC Thu Aug 01 2017 by root
```

Cisco ASA

```
! Configuration last modified by root at 00:00:00.000 GMT Thu Aug 01 2017
```

Juniper EX
```
## Last commit: 2017-08-01 00:00:00 UTC by root
```
