### ISSUE TITLE
Hide enable secret form the node show screen

### ISSUE THREAD

**Issue by seekerOK** [ytti/oxidized#991]
Is possible to hide the enable secret from the node show screen, the one that appears when you click the node name I think is reads from the router.db beside displaying start/end time and status.

**Comment by seekerOK** [comment]
like limiting the output of **%pre** in 
https://github.com/ytti/oxidized-web/blob/master/lib/oxidized/web/views/node.haml

**Comment by laf** [comment]
I think this should be posted in oxidized-web and is possibly a duplicate of oxidized-web/issues#24

**Comment by seekerOK** [comment]
definitely a duplicate, thanks
