### ISSUE TITLE
Cisco WS 6500 don't write entire config

### ISSUE THREAD

**Issue by lvaudois** [ytti/oxidized#992]
Hi,

Trying to backup the configuration of a Cisco WS 6500, it lists not the entire config.

It only write the first line of sh version command and the sh inventory section but not pastes the sh running-config.

I updated the ios.rb from the github repo but don't solved the issue.

Here is the API comment

{:name=>"vss",
 :full_name=>"vss",
 :ip=>"X.X.X.X",
 :group=>nil,
 :model=>"IOS",
 :last=>
  {:start=>2017-08-24 13:05:40 UTC,
   :end=>2017-08-24 13:05:47 UTC,
   :status=>:success,
   :time=>6.224436445},
 :vars=>{:enable=>nil}}

What can I do to backup the entire conf? Thanks in advance!

**Comment by lvaudois** [comment]
Hi,

Please close this issue, it was a simple password issue.

**Comment by JulienNoazette** [comment]
check your log ;)
May be your password isn't correct.
