### ISSUE TITLE
Source: HTTP with LibreNMS is erroring out

### ISSUE THREAD

**Issue by FragmentedPacket** [ytti/oxidized#994]
I'm getting the following error whenever I try and run oxidized on my VM:

> [root@librenms ~]# oxidized
> Error loading config: (<unknown>): found a tab character that violate intendation while scanning a plain scalar at line 33 column 10
> /usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/config.rb:52:in `rescue in load': Error loading config: (<unknown>): found a tab character that violate intendation while scanning a plain scalar at line 33 column 10 (Oxidized::InvalidConfig)
>         from /usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/config.rb:49:in `load'
>         from /usr/local/share/gems/gems/oxidized-0.20.0/lib/oxidized/cli.rb:24:in `initialize'
>         from /usr/local/share/gems/gems/oxidized-0.20.0/bin/oxidized:9:in `new'
>         from /usr/local/share/gems/gems/oxidized-0.20.0/bin/oxidized:9:in `<top (required)>'
>         from /usr/local/bin/oxidized:23:in `load'
>         from /usr/local/bin/oxidized:23:in '<main>'

 

Here is my sanitized configuration:

> ---
> username: un
> password: pass
> model: cisco
> interval: 3600
> use_syslog: false
> debug: false
> threads: 30
> timeout: 20
> retries: 3
> prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/
> rest: 127.0.0.1:8888
> next_adds_job: false
> vars: {}
> groups: {}
> models: {}
> pid: /root/.config/oxidized/pid
> input:
>   default: ssh
>   debug: false
>   ssh:
>     secure: false
> output:
>   default: git
>   git:
>     user: Oxidized
>     email: email@email.com
>     repo: "/root/.config/oxidized/configs/config.git"
> source:
>   default: http
>   debug: true
>   http:
>     url: http://localhost/api/v0/oxidized
> 	scheme: http
> 	delimiter: !ruby/regexp /:/
>     map:
>       name: hostname
>       model: os
>     headers:
>       X-Auth-Token: 'abc'
> model_map:
>   cisco: ios
>   juniper: junos
>   hp: procurve
>   iosxe: ios

I think it's failing further down up the stack than my configuration, but that is just a guess.

Here is the API call to get the device (I have other ones that I figured out and mapped them from a different issue thread on here)

>   {
>         "hostname": "vpav05aacc01.thechildrenshospital.org",
>         "os": "ios"
>     }

**Comment by laf** [comment]
> found a tab character that violate intendation while scanning a plain scalar at line 33 column 10

This seems to suggest that your config file is badly formatted.

**Comment by FragmentedPacket** [comment]
You're correct.

That is low hanging fruit. Sorry for wasting your time.
